### ISSUE TITLE
Spike: Resolve ambiguity in calling param vs. non-param overloads on enums

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#10025]
The compiler is currently unable to resolve the following program even though it seems it should be able to:

```chapel
proc foo(param x) {
  enum color { red, green, blue };
  writeln(chpl__enumToOrder(color.red));
}
foo(1);
```

However, it can resolve this one:

```chapel
proc foo() {
  enum color { red, green, blue };
  writeln(chpl__enumToOrder(color.red));
}
foo();
```

This is causing problems when we try to reduce reliance on enum->int casts because we need to call chpl__enumToOrder() from within a generic function like this to do I/O on enums.

**Comment by mppf** [comment]
@bradcray - I'll let you investigate if this solves your problem in the context of your branch, but it allows that test to pass:
```
diff --git a/compiler/passes/buildDefaultFunctions.cpp b/compiler/passes/buildDefaultFunctions.cpp
index 67e802470f..6053663b3e 100644
--- a/compiler/passes/buildDefaultFunctions.cpp
+++ b/compiler/passes/buildDefaultFunctions.cpp
@@ -982,6 +982,7 @@ static void build_enum_to_order_function(EnumType* et, bool paramVersion) {
   baseModule->block->insertAtTail(def);
   reset_ast_loc(def, et->symbol);
   normalize(fn);
+  fn->tagIfGeneric();
 }
 
 //
```

I believe the problem is that copying a BlockStmt during instantiation is what calls build_enum_to_order_function in this case (`BlockStmt::copyInner` calls `buildEnumFunctions`). Since this happens during resolution for generic instantiations (as in the param case), the usual logic that tags generic functions doesn't apply (since that happens at the start of resolution and the copy didn't exist yet at that point). The other code building enum functions (build_order_to_enum_function and build_enum_cast_function) call tagIfGeneric explicitly, so the patch above just does the same for build_enum_to_order_function.

**Comment by bradcray** [comment]
That does it, thank you!  (I feel stupid given that this was a cut-and-paste error.. but it would've taken me forever to find.  Added this to my branch in 37997f67d40b7d41b4ea184a3058c34da7d1f4d1.
