### ISSUE TITLE
Compiler segfault with cycle of records

### ISSUE THREAD

**Issue by BryantLam** [chapel-lang/chapel#10080]
### Summary of Problem
Compiler segfaults when trying to parse records that are cyclically dependent. There are two variable declarations `x` and `y` in `main` that can or cannot be selectively omitted depending on whether you're using version 1.17.1 or master.

### Steps to Reproduce

**Source Code:**
```chapel
module RecordCycle {
record R1 {
  var a: R3;
}
record R2 {
  var a: R1;
}
record R3 {
  var a: R2;
}
proc main() {
  var x: R3;
  var y: [0..0] R3;
}
} // module RecordCycle
```

### Configuration Information
`chpl version 1.17.1`
`chpl version 1.18.0 pre-release (b0251ba45e)`

**Comment by daviditen** [comment]
The code shown above gets:
```
cycle.chpl:8: error: unable to resolve return type of function '_defaultOf'
cycle.chpl:3: error: called recursively at this point
```

But if you remove the declaration of `x`, or both `x` and `y`, then the compiler segfaults.

**Comment by bradcray** [comment]
Note that this is related to issue #7714 and that the same fix would likely close both issues.

Interestingly, I'm 95% certain that in the past we had a user-facing error message for directly recursive records like:

```chapel
record R {
  var x: R;
}
```

but today, I'm getting the same `_defaultOf`-style message that @daviditen reports above.

Just to make sure we're all on the same page, since records allocate their storage "in-place", recursive records like this don't make sense in Chapel (i.e., this would not be a legal program, but it shouldn't segfault and should give better error messages directly pointing out the recursive record fields).
