### ISSUE TITLE
Remote caching hangs under ugni

### ISSUE THREAD

**Issue by ronawho** [chapel-lang/chapel#10125]
While testing https://github.com/chapel-lang/chapel/pull/10091, I encountered hangs for some remote-cache tests.

In particular the `--cache-remote` variants for the comm count tests in performance/ferguson/ were hanging for me. I was just running `start_test --performance --perflabel cc- test/performance/ferguson/`

I did not investigate these hangs, but I figured I should create an issue to note them.

**Comment by bradcray** [comment]
I had a user report running into similar hangs when using `--cache-remote` on Crays for codes that use the `Block` distribution (and verified this myself).  For example, the following:

```chapel
use BlockDist;
var D = {1..20} dmapped Block(boundingBox={1..20});
writeln(D);
```

Hangs for:

* `CHPL_COMM=ugni`, `--cache-remote`, `-nl 4`

But does not hang for:

* `CHPL_COMM=gasnet/aries` or `gasnet/udp`, `--cache-remote`, `-nl 4`
* `CHPL_COMM=ugni`, `-nl 4` (without `--cache-remote`)

It appears that simple cases that don't use `Block` (such as `hello4-taskpar-dist.chpl`) also hang.  So it may simply be that `ugni` and multi-locale programs don't work well together (the trivial `hello.chpl` worked OK).

Since we've started suggesting people use `--cache-remote` to address the "distributed field communication problem" (issue #10160), I've bumped this up in priority.
