### ISSUE TITLE
should untyped generic instantiated with owned depend on intent?

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#10215]
Based on the design in #8938, the type instantiated for an unconstrained generic formal, when passed an owned actual, is the borrow type:

``` chapel
proc f(x) {
  // x.type is borrowed MyClass
}
f(new owned MyClass());
```

This issue asks if a corresponding behavior should apply to other intents:
 * `in` and `const in`
 * `ref` and `const ref`

See also #10142.

**Comment by mppf** [comment]
See also afc5fdd34e5824bf6a5de94a5522ef81d728f212 which removed the sensitivity to intent and passed testing

**Comment by bradcray** [comment]
I'm trying to make sure I'm understanding what you're proposing/asking here.  Is the idea that if I were to write:

```chapel
proc f([const] in x) {
  writeln(x.type:string);
}
var myC = new owned MyClass();
f(myC);
```

we need to decide whether `x` should be a copy-in of a borrow of `myC` vs. a copy-in of `myC` itself (presumably resulting in a new owned class whose scope would be `f()`)?  Thanks.

**Comment by mppf** [comment]
> we need to decide whether `x` should be a copy-in of a borrow of `myC` vs. a copy-in of `myC` itself (presumably resulting in a new owned class whose scope would be `f()`)?  Thanks.

Yes, that's the question. I also have some hope for consistency with task intents but I'm not really sure what to expect there.

There's also the analogous question about `ref` intent.

``` chapel
proc f([const] ref x) {
  writeln(x.type:string);
}
var myC = new owned MyClass();
f(myC);
```

Should it output `borrowed MyClass` or `owned MyClass` ?

**Comment by mppf** [comment]
> somewhat like variable initialization and that we'd borrow in the `var x = myC;` case (right?).

``` chapel
var x = new owned MyClass();
var y = x;
```

y will have type `owned MyClass`. This would create a borrow:

``` chapel
var x = new owned MyClass();
var y:MyClass = x;
```

**Comment by mppf** [comment]
> Do you have arguments for why `borrowed` might make sense in the `ref` cases?

In fact it would probably be a compilation error (can't pass result of coercion by ref). I only wish for the rule about instantiation to be as simple as we can get it.

**Comment by bradcray** [comment]
> In fact it would probably be a compilation error

OK, sounds like having `ref` simply mean "refer to the original [owned] thing" is what we're converging on for this case then?

> `y` will have type `owned MyClass`

That'll teach me to make guessy assertions without quickly checking them first...  (Shoot, what does it say about me / the design when a long weekend makes me unable to get simple cases right...?  Let's assume it's "me" not the design... :) ).

OK, so taking a step back:

Arguments in favor of having `in` take ownership
-------------------------------------------------
* makes it more like generic (untyped) variable initialization; or assignment into a thing of like type, both of which are what I think of `in` as suggesting.

Arguments in favor of having `in` borrow
-----------------------------------------
* makes it more like the completely generic default intent case, where I've argued that since the default intent for classes is `in`, people might expect this symmetry (but... how confident are we based on experience so far that this was the right choice?)

Are `inout` and `out` other cases worth thinking about?  In the `inout` case, my intuition would be that the procedure would take ownership of it and then return ownership to the actual at the end of the procedure.  In the `out` case,

```chapel
proc f(out x) {
  return new owned MyClass();
}
var myC: new owned MyClass;
f(myC);
```

my assumption is that `myC` would take ownership of the object created in the `return` statement.  So perhaps these suggest that `in` should take ownership as well?

Is my thinking out loud here helping at all?

**Comment by mppf** [comment]
> makes it more like the completely generic default intent case, where I've argued that since the default intent for classes is in, people might expect this symmetry (but... how confident are we based on experience so far that this was the right choice?)

Is your question "was this the right choice" asking about generic-untyped-default-intent-is-borrow ? I havn't been surprised by it yet but also havn't seen a test case where I felt it was super satisfying...


> Are `inout` and `out` other cases worth thinking about?  In the `inout` case, my intuition would be that the procedure would take ownership of it and then return ownership to the actual at the end of the procedure.

Right, I tend to view `inout` and `out` as embellishment on `ref`. I would expect that if the type stays `owned` in the `ref` case that it would also stay `owned` in the `inout` case. Otherwise it would be impossible to use `inout` in this situation.

> In the `out` case,
> 
> ```chapel
> proc f(out x) {
>   x = new owned MyClass();
> }
> var myC: new owned MyClass;
> f(myC);
> ```
> 
>  my assumption is that `myC` would take ownership of the object created in the `return` statement.  

As with `ref` or `inout`, it would be an error if `x` was of type `MyClass`. In other words `out` wouldn't be very useful if it made `x` have type `MyClass` as with the default intent.

> So perhaps these suggest that `in` should take ownership as well?

It at least seems to indicate that there's a kind of consistency with such a choice, yes.

> Is my thinking out loud here helping at all?

yes, thanks.

One thing I am hoping for here is that we have a simple way of describing the instantiate-owned-actual-as-borrowed rule to users. It would help if it only applies to the default intent, since that's something we can describe with fewer cases. It would alternatively help if it applied to all intents. But, we know already it won't apply to `type` intent and it seems fairly clear from this discussion that it can't apply to `ref`, `out`, or `inout`.

Which leaves the `in` intent - where there is still some uncertainty. However I am leaning towards allowing the ownership transfer in that case. I like the idea that `in` and `ref` and `const ref` disabling the behavior provides a reasonable alternative to `managed?`.

**Comment by bradcray** [comment]
> Is your question "was this the right choice" asking about generic-untyped-default-intent-is-borrow ? 

Yeah.

> However I am leaning towards allowing the ownership transfer [for `in` intents]

I think I'm also leaning toward having `in` result in ownership transfer.  But I'm increasingly concerned about whether we've made the right decision for the fully generic case (though simultaneously, I don't like questioning something that was set pretty early in the design exploration... though the fact that you haven't come across cases for which is was super-satisfying is a little reassuring).

Specifically, I think it would be the first case where a default argument intent didn't have an explicit rewrite that would get the same behavior, is that right?  That seems concerning.  It also reminds me of the concern that someone (Vass?  Lydia?) brought up early in the discussion in which they noted that `sync` types used to have "special" behavior w.r.t. generics and that ultimately we decided that it was too confusing / unusual to maintain as an outlier.  So that makes me wonder if the "simple way of describing instantiated-owned-actual-as-borrowed rule" is to simply do away with it?

What are your favorite arguments for the current behavior with default intent?  Re-reading slide 31 of the [1.17 release notes](https://chapel-lang.org/releaseNotes/1.17/09-ongoing.pdf), I find myself thinking "OK, maybe it'd be a little surprising at first, but it doesn't seem inconsistent." (and it does appear in the "construction ahead" section :) ).  Plus it would make slide 32 ("exceptions to the rule") less exceptional.

**Comment by mppf** [comment]
>  But I'm increasingly concerned about whether we've made the right decision for the fully generic case

I still think it's the right choice.

> though simultaneously, I don't like questioning something that was set pretty early in the design exploration... though the fact that you haven't come across cases for which is was super-satisfying is a little reassuring

It's probably more that there's not that much code actually using owned/borrowed in a non-trivial way yet. If you want a more accurate answer to how important it is to the current tests we have converted, I could turn it off & run testing. (But that doesn't help with the problem of lacking more examples / better examples).

> Specifically, I think it would be the first case where a default argument intent didn't have an explicit rewrite that would get the same behavior, is that right?

It would, if we make `in` different from the default as we are discussing here. If we made `in` mean `borrow by in intent`, it would not. That would be OK with me, because presumably ownership transfer would still be possible with `ref`.

A possible alternative might be to allow `borrowed` as an intent.

> What are your favorite arguments for the current behavior with default intent?

1. It's important for API design sanity that both the author of a function an the person calling it know that it can do ownership transfer. With "default to borrow", `proc f(x)` does not do ownership transfer, but `proc f(x:owned)` does. I think this situation is reasonably clear and understandable.
2. We don't want using `owned` to reduce performance, and using a default of `const ref` or of `in` would both add overhead. `const ref` adds a double-dereference when the argument is used (in a loop, say). `in` would add reference counting for `shared` and a small amount of extra work for `owned` (but the more serious problem with `owned` is that the actual will become empty).
3. We didn't want the default intent for (non-generic) `owned` to be `const ref` because that would prevent us from passing `owned ChildClass` actuals to an `owned ParentClass` formal. While this is theoretically possible, it doesn't seem possible to express in C without breaking strict aliasing. This is only relevant because an earlier strategy had the default `const ref` for generic and non-generic owned arguments.

**Comment by bradcray** [comment]
> If we made `in` mean `borrow by in intent`

Is the idea here that we'd define `in` this way in all cases, and that for things like `int`, say, "borrowing by `in` intent" would mean "making a copy"?

**Comment by mppf** [comment]
> > If we made `in` mean `borrow by in intent`

> Is the idea here that we'd define `in` this way in all cases, and that for things like `int`, say, "borrowing by `in` intent" would mean "making a copy"?

`proc f(arg:int)` we could call this "borrowing by in intent" if we wanted; the borrowing part is moot

`proc f(arg:owned)` is definitely not "borrowing" but does have a default of in intent (to do ownership transfer)

`proc f(arg:borrowed)` is borrowing and uses the in intent

`proc f(arg)` is borrowing (for class/owned/etc-type actuals) and uses the in intent

> Is the idea here that we'd define `in` this way in all cases

I don't think we can do that, because of the `owned` / `owned MyClass` defaulting to ownership transfer (which I'm quite happy with BTW).

**Comment by bradcray** [comment]
OK, thanks.  Next question then:  Outside of this issue, do we have cases where the transfer from `actual` to `formal` in this call:

```
proc foo(in formal [: t]) { ... }
foo(actual);
```

is fundamentally different than in this declaration:

```
var formal [: t] = actual;
```

And  if not, can we maintain that symmetry in this effort?

**Comment by mppf** [comment]
Regarding in intent vs copy-initialization, AFAIK these are pretty much the same for all types, in terms of when copies are created (they obviously can have different scoping).

Earlier we were both leaning towards `in` intent disabling the instantiate-as-borrow behavior, and the reason you're bringing up here was in your earlier comment with the headings.

> Specifically, I think it would be the first case where a default argument intent didn't have an explicit rewrite that would get the same behavior, is that right?

We could consider it having a rewrite that included a type, e.g.:
``` chapel
  proc foo(x) { }
```

``` chapel
  proc foo(in x: `managed?`) { }
```

But such a thing would require (AFAIK) the concept of `managed?` (even if they syntax/name ends up totally different).

**Comment by mppf** [comment]
@bradcray - I'm running to a case with DimensionalDist2D that relies on this behavior. DimenisionalDist2D has an initializer that accepts a generic argument and stores it in a generic field. I'd like the user of DimensionalDist2D to specify an ownership strategy for the distributions for the dimensions; maybe they are shared among many 2D dists or maybe the 2D dist is to free them. So, I'd like the DimensionalDist2D initiailizer to *not* have the instantiate-as-borrow behavior. We're talking about allowing `in` intent to do that but at the moment I also need `pragma "no borrow convert"`.

**Comment by mppf** [comment]
See also 
https://github.com/chapel-lang/chapel/pull/11046#issuecomment-419568084

> Assuming clean testing, this looks good, thanks!  For those following along at home, my way of thinking of this being the right behavior is:
>
> * `var x = new owned C()` causes `x` to be `owned C` because that seems most natural
> * `var y = x` causes `y` to be `owned C` because the type signatures are identical to the previous
> * `in` intent should behave similarly to variable initialization suggesting that `proc foo(in y)` > should behave the same as the previous

While it's not necessarily the final answer, what is implemented is reasonable at least until we gain more experience and desire to change it. At that point, this issue can be re-opened or a new issue created.
