### ISSUE TITLE
Codegen compiler performance regression from #10187

### ISSUE THREAD

**Issue by ronawho** [chapel-lang/chapel#10304]
There was a ~2x slowdown for codegen as a result of "Refactoring codegenPrimitive, and adding a limit to denormalize" (https://github.com/chapel-lang/chapel/pull/10187)

Here's some [graphs](https://chapel-lang.org/perf/chap01/?startdate=2018/07/06&enddate=2018/07/11&graphs=topaveragecompilationtimeperpass)

![image](https://user-images.githubusercontent.com/1588337/42662809-d83740ee-85e7-11e8-89f1-872d0b41fd1b.png)

Note that there was a huge performance improvement for resolution on the same day as a result of https://github.com/chapel-lang/chapel/pull/10143, but it'd still be nice to see if we can resolve the codegen regression.

I verified the cause of the regression by running test/performance/compiler/bradc/cg-sparse-timecomp.chpl on /tmp of chapcs07, but it should be reproducible anywhere.

**Comment by bradcray** [comment]
In reading about this PR, I was curious about the impact of using function pointers, but had hoped it would be smaller than this.

I found myself wondering whether, having introduced the per-primitive functions, using a switch statement to call into them rather than the function pointers would get us most of the benefit of the cleanup—while the switch statement would still exist, at least most of the code would be moved out of it, resulting in a cleaner result.

@benharsh wondered whether, through counting, we could determine whether there was a small set of primitives that were used the most and if just special-casing those in a switch statement (or otherwise) would get us most of the performance back without requiring the full switch statement.  This seems practical, though also a little unfortunate (when adding a new primitive, one would have to ask which approach to take and maybe be confused about the presence of both).

**Comment by mppf** [comment]
@ronawho - thanks for noticing the problem. Actually simply moving the "register all of the primitive codegen fns" code out of codegenPrimitive resolves the performance issue. So @bradcray's hopes can be restored.

**Comment by ronawho** [comment]
Looks like #10321 resolved this (and codegen is actually a little faster than it was before!):

![image](https://user-images.githubusercontent.com/1588337/42771359-d1d9f7d6-88db-11e8-98d0-f7f67f6692cb.png)
