### ISSUE TITLE
Opportunity for minor improvements to two enum cast error messages

### ISSUE THREAD

**Issue by cassella** [chapel-lang/chapel#10385]
Edit: after reading through the OP, this comment is a good place to look next: https://github.com/chapel-lang/chapel/issues/10385#issuecomment-1013547887

### Summary of Problem

When casting an abstract enum to `real` or `bool`, the error is
reported from `ChapelBase.chpl` rather than the user code (and
unexpectedly reports a failure to cast to `int(64)` instead of to
`real` or `bool`):

```chapel
enum E { R,G,B };

writeln(E.B:real);
```

```
$CHPL_HOME/modules/internal/ChapelBase.chpl:1116: error: can't cast from an abstract enum ('E') to int(64)
$CHPL_HOME/modules/internal/ChapelBase.chpl:1116: note: unresolved call had id 835818
```

(Casting to int here instead, the error names the line of the cast in
my code.)

Second, when casting invalidly from a partially abstract enum to int,
the runtime error message names the line defining the enum, rather
than the line with the cast:

```chapel
enum E { R, G, B=3 };

writeln(E.B:int);

writeln(E.R:int);
```

```
fortytwo@magrathea:~/src/chapel (master)$ ./enumtothings -nl 1
3
enumtothings.chpl:1: error: halt reached - illegal cast: E.R has no integer value
```

Reporting line 5 as the source of the error would be more helpful.

**Associated Future Test(s):**
 [`test/types/enum/bad-cast-to-real.chpl`](
           https://github.com/chapel-lang/chapel/blob/master/test/types/enum/bad-cast-to-real.chpl
          ) #12694

### Configuration Information

```

fortytwo@magrathea:~/src/chapel (master)$ chpl --version
chpl version 1.18.0 pre-release (770c998)
Copyright (c) 2004-2018, Cray Inc.  (See LICENSE file for more details)

fortytwo@magrathea:~/src/chapel (master)$ printchplenv --anonymize
CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: gnu
CHPL_TARGET_ARCH: native *
CHPL_LOCALE_MODEL: flat
CHPL_COMM: gasnet *
  CHPL_COMM_SUBSTRATE: udp
  CHPL_GASNET_SEGMENT: everything
CHPL_TASKS: qthreads
CHPL_LAUNCHER: amudprun
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: intrinsics
  CHPL_NETWORK_ATOMICS: none
CHPL_GMP: gmp
CHPL_HWLOC: hwloc
CHPL_REGEXP: re2
CHPL_AUX_FILESYS: none

fortytwo@magrathea:~/src/chapel (master)$ gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
```

**Comment by lydia-duncan** [comment]
Note that in the first case the error is reported from ChapelBase (probably) because you have CHPL_DEVELOPER=true in your environment.  If you were to run it through the test system or compile with `--no-devel`, it reports the error at foo.chpl:3 (I just verified this).  The error message should still say `real(64)` instead of `int(64)`, though

**Comment by cassella** [comment]
I opened a PR with a future.

I also found that compiling the second example with `no-devel` produces a binary that reports the line of the cast in the error.

**Comment by pree-T** [comment]
Is this issue still open?

**Comment by bradcray** [comment]
Yes!

**Comment by pree-T** [comment]
Can someone help me to fix this issue as I am relatively new to open source contribution? @bradcray

**Comment by bradcray** [comment]
Suggested starting steps:

0a) Clone the `main` branch of the Chapel repository from GitHub if you haven't already
0b) Build Chapel and make sure you can compile and run some basic tests, like `test/release/examples/hello*.chpl`
0c) Compile and run the "future" test named in the OP above: test/types/enum/bad-cast-to-real.chpl to ensure that you get the bad behavior
0d) Run `util/start_test test/types/enum/bad-cast-to-real.chpl` to get some experience running the Chapel [test system](https://chapel-lang.org/docs/developer/bestPractices/TestSystem.html)

The root problem here is that the way we currently implement enum->real casts is by casting from enum->int->real.  But abstract enums in Chapel (those without any associated integer values) don't support enum->int casts, so the error message noted in the OP is generated, complaining about casting to int rather than casting to real.

I think the easiest fix is to put a special case into this routine checking to see whether the enum is abstract and creating a real-based version of the error if it is.  This routine should help:  https://chapel-lang.org/docs/modules/standard/Types.html?highlight=isabstractenumtype#Types.isAbstractEnumType

**Comment by pree-T** [comment]
Thank you! How do I set up the environment? I am facing difficulty in that , as in what all dependencies do I need to install as VScode Editor shows several syntactical errors.

**Comment by bradcray** [comment]
I don't know anything about VSCode (and would be surprised if it knew anything about Chapel out of the box), but general information for building and using Chapel is available here:  https://chapel-lang.org/docs/usingchapel/index.html and general information about contributing is here:  https://chapel-lang.org/contributing.html

**Comment by jabraham17** [comment]
https://github.com/chapel-lang/chapel/pull/25455 will resolve this issue for `real`. I also noticed that `bool`, `complex`, and `imag` suffer from same problem. #25455 will also fix that
