### ISSUE TITLE
generate warnings for potential modification of non-promoted arguments in promoted call

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#10412]
Consider the following program:

``` chapel
record R {
  var value:int;
}

proc R.addem(a:R, b:R) {
  this.value = a.value + b.value;
}

var A:[1..10] R = [i in 1..10] new R(i);
var B:[1..10] R = [i in 1..10] new R(i);
var C:[1..10] R;

C.addem(A, B); //OK
writeln(C);

var result:R;

result.addem(A, B); // almost always a race condition!

writeln(result);
```

Note that if `addem` is declared as a 3-argument function (rather than a method), the compiler issues an error about modifying a constant shadow variable.

Note also that adding the `ref` intent to `addem` does not prevent the above program from compiling.

This issue proposes that this program should produce a warning or an error.

See also #10345 which describes the context in which a user originally ran into this problem.

**Comment by bradcray** [comment]
Oh, interesting, @mppf!  I hadn't thought about the fact that the shadow variables would protect us from this behavior already for standard arguments and that the problem was specific to `this` arguments (and obviously hadn't taken the time to experiment with it and find out).  This makes it seem as though a solution should not be far off.  Tagging @vasslitvinov on this since he is king of intents and shadow variables.

Here's another case that shows the same issue with `int`s which eliminates some of the questions I always have about how good our `const` checking is for records which might muddy more complicated examples (in my mind, if not the code base):

```chapel
proc ref int.foo(x: int) {
  this += x;
}

var x = 42;
x.foo(1);
writeln(x);   // works as expected

var A =	[1, 2, 3];
var B: [1..3] int;
B.foo(A);
writeln(B);   // works as expected

x.foo(A);
writeln(x);   // "works" but should arguably generate an error
```
