### ISSUE TITLE
Warn if we detect HUGETLB_NO_RESERVE isn't set

### ISSUE THREAD

**Issue by ronawho** [chapel-lang/chapel#10451]
We have launcher hooks for [ugni](https://github.com/chapel-lang/chapel/blob/master/runtime/src/comm/ugni/comm-ugni-launch.c) to set `HUGETLB_NO_RESERVE=yes` (required for numa affinity otherwise hugepages get faulted in allocation time) and `CHPL_JE_MALLOC_CONF="lg_chunk:24"` (which tells jemalloc to use chunk sizes that are a multiple of the hugepage.) lg_chunk:24 is for 16M hugepages and will change for different hugepage sizes.

If the launcher isn't being used or something we should detect that these env vars aren't set in ugni and issue a warning since they can have pretty large correctness implications. 

Semi-related to https://github.com/chapel-lang/chapel/issues/7841

**Comment by gbtitus** [comment]
Is this seeking to warn if it's not set at all, or to warn if it's not set to `=yes`?  I would be okay with the former but I'd prefer to continue to be able to force it to `=no` to turn off the no-reserve behavior.  (I guess an acceptable alternative would be to add an internal meta-EV that would turn off the "not set" warning.)

**Comment by ronawho** [comment]
Only warn if it isn't set at all (still want users to be able to override if they choose)

**Comment by gbtitus** [comment]
We should only do this if `HUGETLB_DEFAULT_PAGE_SIZE` is set, right?  If we're not using hugepages (i.e., current "minimal registered" mode) then neither `HUGETLB_NO_RESERVE` nor `CHPL_JE_MALLOC_CONF` matters.

**Comment by ronawho** [comment]
Yeah, that sounds right. Although maybe then we want a different warning saying "Pretty please load a hugepage module!" :)

**Comment by gbtitus** [comment]
I hear you and it's tempting, but we do document running without hugepages as a valid configuration, so I guess I'll pass on that "pretty please" improvement.  :)

**Comment by bradcray** [comment]
If we believe hugepages are essential for good performance, I'd be inclined to print a warning if someone ran without them (esp. if the warning can be silenced with the `--quiet` flag).  I think we ran into a case earlier this year where someone was publishing performance results that seemed to be obtained without a hugepages module, and it'd be nice to have such users be able to self-diagnose issues like this rather than hoping they ask us whether there results are as expected.

**Comment by gbtitus** [comment]
Strictly speaking hugepages are only essential for good performance when the program communicates.  A counterexample would be something like stream-ep, which actually gets slightly better performance with comm=ugni right now if you unload the hugepage module before running it.  But, point taken.

Based on the conversation here I'm going to adjust slightly.  I'll emit a warning if hugepages aren't being used.  I'll emit a warning if they are being used but `HUGETLB_NO_RESERVE` isn't set to something.  And if hugepages are being used but `CHPL_JE_MALLOC_CONF` isn't set, instead of just a warning I'll emit an error (and halt), because that's likely to lead to segfaults or internal errors etc.

**Comment by gbtitus** [comment]
After conversing with @ronawho we think we would only get segfaults out of jemalloc if its chunk size were larger than the hugepage size, but its default chunksize is 2 MiB and that's the smallest hugepage size on Aries-based systems, so `CHPL_JE_MALLOC_CONF` will be a warning too, at least for Aries.  Maybe I'll get fancy and make it an error on Gemini-based systems.

**Comment by bradcray** [comment]
> Strictly speaking hugepages are only essential for good performance when the program communicates. A counterexample would be something like stream-ep, which actually gets slightly better performance with comm=ugni right now if you unload the hugepage module before running it. 

That's a good point.  My assumption would be that most (interesting) programs communicate and that the delta between stream's hugepages vs. non-hugepages performance is modest enough that the warning generally makes sense.  If you guys think this is important enough not to generate a warning, I'll defer.  Alternatively, the warning could caution that "programs that do a lot of communication should load a hugepages module" so that the user has their eyes open and the stream-ep user can decide to ignore the warning / run with `--quiet`.
