### ISSUE TITLE
--main-module error message not useful in --library compilation

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#10462]
### Summary of Problem
The following code generates an error saying `a program with multiple user modules requires a main function` when compiled with --library mode.  Main functions don't have meaning in library compilation, but we do still need to know what to name the generated library file.

I think the error message instead should key off of the absence of `-o` to name the generated file.

Alternatives:
- If we supported programs that included multiple Chapel libraries, we could generate a library file and header per module specified on the command line.
- We could recommend they still use `--main-module` but have the error message not mention a main function

### Steps to Reproduce

**Source Code:**

```chapel
module A {
  export proc bar() { }
}
module B {
  export proc baz() { }
}
```

**Compile command:**
`chpl --library foo.chpl`

**Associated Future Test(s):**
[`test/compflags/lydia/library/errorMessage/multiMod/multipleModules.chpl`](https://github.com/chapel-lang/chapel/blob/master/test/compflags/lydia/library/errorMessage/multiMod/multipleModules.chpl) #10469

### Configuration Information

- Output of `chpl --version`: 1.18.0 (pre-release)

**Comment by lydia-duncan** [comment]
I'm not sure about the prioritization of this

**Comment by bradcray** [comment]
I like the behavior you've proposed (lack of main module requires use of `-o` flag), but would probably directly name the `-o` flag in the error message for those who might have trouble connecting those dots without it.

This seems like not particularly high priority, but it also seems like it should be extremely easy to implement?  (i.e., isn't it just a simple conditional in the place where the error message is currently generated?)  If so, I think it's worth knocking off rather than waiting until someone hits it...

**Comment by lydia-duncan** [comment]
That seems reasonable to me.  I'll add it to my next sprint cycle
