### ISSUE TITLE
Queried locale of owned or shared variables

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#10566]
What should this program do:
``` chapel
class MyClass {
  var x:int;
}

var a:owned MyClass;

on Locales[numLocales-1] {
  a = new owned MyClass(1);
  writeln(a.locale.id);
  
  var b:owned MyClass;
  writeln(b.locale.id);
  on b {
    writeln(here.id);
  }
  on Locales[0] {
    writeln(b.locale.id);
  }
}

writeln(a.locale.id);
on a {
  writeln(here.id);
}
```

If `unmanaged` is used instead of `owned`, it prints out only `1` lines when run on two locales.
But, since the compiler currently views `owned` as a record, it considers owned variables to be wherever they are stored - rather than where a stored class is located.

**Comment by mppf** [comment]
@bradcray @benharsh - any thoughts here?

**Comment by benharsh** [comment]
My initial reaction is that owned and shared should behave like unmanaged.

**Comment by bradcray** [comment]
My intuition was also to have it behave like unmanaged (i.e., to refer to the locale on which the class object is stored) since I think our view is generally that the record is something that the (typical) user wouldn't be thinking about or concerned about.  Do you have arguments for taking a different perspective?

**Comment by bradcray** [comment]
To make sure I'm understanding, I think you're saying that perhaps even in Chapel 1.17 and earlier, `on C` should've referred to the locale storing the pointer/reference to the class C object, not to the one on which C itself was allocated?  To me, this feels like too big a change to consider at this point in time.

For reference, I believe our rationale for the current approach was that it seemed more useful and more likely to be what someone cared about ("Take me to where the object and its fields are located") and therefore supported the common case better.  We may have made a generic programming argument as well ("take me to the place where this variable lives so that I can compute on it locally, regardless of whether it's a class, a record, an int, etc.).  I'd have to dig deeper than these recollections if we wanted to recreate the discussion and decision process.

**Comment by bradcray** [comment]
I've just assigned this to Michael and myself because I think it'd be nice to resolve early in the next release cycle (I'd lost track that it hadn't been in this one).
