### ISSUE TITLE
Investigate unmanaged in release/examples

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#10598]
Generally speaking we shouldn't be using `unmanaged` or `new borrowed` in release/examples. This issue is documenting the task of `grep`ing for these and trying to resolve them where possible.

Also check for `_to_unmanaged` or `_to_borrowed` since these can generally be replaced with the generic cast.

**Comment by bradcray** [comment]
Oops, I had not seen / thought to look for this prior to opening my issue this morning.   Since mine was an epic and this mentions a few things to check for that I didn't, why don't I put this under the epic.

**Comment by bradcray** [comment]
@mppf: Is your thinking about avoiding `new borrowed C()` that we should be simply writing these as `new C()` or that we should try to write them in some way that doesn't use this pattern at all?

FWIW, I didn't find any hits for `_to_unmanaged` or `_to_borrowed` within release/examples.

**Comment by mppf** [comment]
> FWIW, I didn't find any hits for _to_unmanaged or _to_borrowed within release/examples.

great, less work for the moment.

> @mppf: Is your thinking about avoiding new borrowed C() that we should be simply writing these as new C() or that we should try to write them in some way that doesn't use this pattern at all?

I was imagining that we'd prefer `new owned C()` for these examples.

**Comment by bradcray** [comment]
Looks like the cases that use `new borrowed` at present are:

* benchmarks/shootout/chameneosredux.chpl (which I'm already working on rewriting in PR #10945)
* primers/classes.chpl (which I think is appropriate since it's teaching the concept)
* primers/learnChapelInYMinutes.chpl (which was changed from `new C` to `new borrowed C` in df7be02cdb27d1bf0956e391b2a1634d5353719e)

I've updated issue #10947 to include this last case.

**Comment by mppf** [comment]
I think @bradcray did most of the work on this one - thanks! The epic #10947 can remain open but I think we've done what we hoped to for this sprint, so I'm closing this issue.
