### ISSUE TITLE
Mason: refactor run and build behavior

### ISSUE THREAD

**Issue by Spartee** [chapel-lang/chapel#10622]
Currently there are a few places in the latter stages of the mason pipeline that a user might get tripped up. This issue will address those points and suggest a refactor for each of them.

### --release
When a user throws `--release` a new folder is created within `target/` that is the home to the new "release" executable. This executable, once formed, is the sole target of calls to `mason run`. Users are not able to run the debug version until they run a `mason clean`. This is not intuitive and should provide more feedback to the user about which version of the package is currently being run. 

##### Suggested implementation
Cargo mitigates this problem by allowing users to throw the `--release` flag with their calls to `cargo run`. I suggest the same approach. Mason will run the debug version unless `mason run --release` is called. This will require a refactor in both `MasonBuild` and `MasonRun`

##### Cargo approach
```
// building and running debug version of the package
$ cargo build
    Finished dev [unoptimized + debuginfo] target(s) in 0.02s

$ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.02s
     Running `target/debug/w`
Hello World!
```

```
// building and running the release version of the package
$ cargo build --release
   Compiling w v0.1.0 (file:///Users/spartee/chapel/w)
    Finished release [optimized] target(s) in 0.23s

$ cargo run --release
    Finished release [optimized] target(s) in 0.02s
     Running `target/release/w`
Hello, world!
```

### Run time arguments
As Thomas states in #8852 , it is not well documented how run time arguments are handled in mason. Currently, all flags not recognized by mason are passed down to the chapel module executable. This should be clearer for the user. I suggest that we implement a `--` that will seperate the commands intended for mason and the runtime arguments. As cargo puts it, 

```
All the arguments following the two dashes (`--`) are passed to the binary to
run. If you're passing arguments to both Cargo and the binary, the ones after
`--` go to the binary, the ones before go to Cargo.
```

### Documentation
These issues could have been more intuitive if the documentation was a bit clearer on how exactly a user should be working through the mason pipeline. As Thomas also states in #8852, the documentation is not very clear, and I believe that is due to a dearth of examples. Along with the improvements suggested above, resolution of the issue would include a few examples in the Chapel documentation of how to go about using the more intricate functionalities of `mason build/run`.

**Comment by ben-albrecht** [comment]
> Run time arguments

Just to elaborate on this some more (mostly for my own clarity) -- the case where we run into trouble is when `mason` shares a flag name and type with the program it is building/running (conflicts with `chpl` compiler flags for building, and the program configs for running).

An example of this is a program with a `config const show: bool`. How do we distinguish setting the `--show` flag for `mason` vs the program?

```bash
mason run --show # Ambiguous - currently gets used by mason
```

In #8852, I proposed that we utilize `--` to separate arguments that are meant for `mason` vs. the program it is building/running, since it matches how we skip config parsing.

From the [docs](https://chapel-lang.org/docs/master/technotes/main.html#usage):

> placing the argument `--` in the argument list will cause all following arguments to be passed to the declared main function and will suspend handling of any builtin command line arguments

Unfortunately, Chapel's use of `--` prevents us from using `--` as well, since the Chapel argument parsing consumes the `--` and it never shows up in the `args` array. It might be possible to enable this via changes the config code, but that would open up a broader design question of if that's something we want to enable.

So we'll need to add a new mason-specific delimiter that causes all the following arguments to be passed to the program rather than mason.  Sounds like the current proposal is to use `==`. I'm not crazy about this syntax, but it's a starting point. I wonder if it is possible to use as single dash? e.g.

```bash
mason run --show - --show=false
```

Instead of:

```bash
mason run --show == --show=false
```

Open to other ideas if anyone has some.

**Comment by Spartee** [comment]
Just to add, both `==` and `-` work as delimiters. Some that do not are `|` `:` `$` and `&`.

**Comment by mppf** [comment]
I'd recommend:
1. Add a workaround (turn off `--` handling or pass `--` to arguments; activate this using an internal API)
2. create an issue about either making that API public or always giving the main args `--`
