### ISSUE TITLE
How should a library compile to make a python module handle things like int8, uint32, etc?

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#10634]
My understanding of the situation is that Python has only a single size of int, float, double, and complex, which varies in size depending on the system.  However, [numpy](https://docs.scipy.org/doc/numpy/user/basics.types.html) does supply alternative sizes.

Motivation:
While different sizes is not necessarily as important as basic support, having a plan for all the sizes ahead of time may prevent backwards incompatibility.  For instance, if we think it is better to use numpy for all sizes, it would be good to know that now rather than changing what the translation of a Chapel int means later.

Proposal:
- Use regular python sizes for Chapel versions without an explicit size attached.  E.g. Chapel real -> Python double
  - (Question for me: Is this possible at codegen?  Did we replace all generic versions with the relevant size at function resolution?  I feel like that's something that happens.  If so, my solution may need to occur earlier in compilation)
- Use numpy sizes for explicitly sized Chapel types.  E.g. Chapel int64 -> Python numpy.int64
  - Generate a warning for these types so that they know they must use numpy.  Allow the user to turn off this warning.
    - If I end up using only numpy types and no default python types, I would put this in the documentation for this flag instead of having a warning every time.
- Sizes or primitive types that are not supported should get a warning message, when possible.

Rationale:
While numpy is a common package, it is not guaranteed to be installed for a particular version of Python.  When a particular size is specified, it is done so for a reason - the user should get what they asked for, if possible.  Further, if they care about the size, they probably have numpy installed in their Python version.

**Comment by mppf** [comment]
I think there are some misunderstandings in the above (or at least it's only true for Python 2):


> Generally, In languages like C/C++, the precision of integers is limited to 64-bit, but Python has built-in support for Arbitrary-precision integers. Since Python 3 there is no longer simple integer type, and all integers are represented as a bignum.

source: https://rushter.com/blog/python-integer-implementation/


> Almost all machines today (November 2000) use IEEE-754 floating point arithmetic, and almost all platforms map Python floats to IEEE-754 “double precision”.

source: 
https://docs.python.org/3/tutorial/floatingpoint.html

Based on these, here is what I would do:

| Chapel | Python
| --- | ---
| bigint | int 
| real | float
| int(32) | numpy.int32

I'm not sure how to handle Python 2 but would lean towards not making long-term choices based on Python 2's int type.


> Generate a warning for these types so that they know they must use numpy. Allow the user to turn off this warning. 

I have no idea when you're imagining this warning will appear, but before considering adding the warning, maybe first check out what happens if we create an example where we imagine the user is confused about it? If nothing bad happens, nothing to do. If it already generates a reasonable error/warning, nothing to do.

**Comment by lydia-duncan** [comment]
Oh, interesting.  I was basing my information off of [this](https://docs.python.org/3.3/library/stdtypes.html#numeric-types-int-float-complex)

**Comment by lydia-duncan** [comment]
I'm not sure I trust a blog over the Python 3.3 documentation, but it is entirely possible that the documentation is outdated

**Comment by mppf** [comment]
> Integers have unlimited precision
> ...
> Floating point numbers are usually implemented using double in C

source: https://docs.python.org/3.3/library/stdtypes.html#numeric-types-int-float-complex

**Comment by lydia-duncan** [comment]
Or am I mixing up float and double?

**Comment by lydia-duncan** [comment]
Oohhh, wait, there isn't a "double", that's the C part.  Ugh, my reading comprehension is bad today

**Comment by lydia-duncan** [comment]
I also need [this](https://nyu-cds.github.io/python-cython/01-syntax/) for the Cython translation

**Comment by bradcray** [comment]
I'm not enough of a Python expert to be able to weigh in on most of this, but this sentence caught my eye:

> Use regular python sizes for Chapel versions without an explicit size attached. E.g. Chapel real `->` Python double

Specifically, I was worried that it was suggesting that it would be OK to map Chapel types without explicit sizes to arbitrary sized types in other languages (i.e., "since you didn't mention a width, we're free to pick one); whereas since Chapel's `real` is meant to merely be a shorthand for `real(64)` I don't think it should result in anything other than a 64-bit floating point value in exported functions.  But reading a second time, I feel more confident that you're only asking what Python type name should be used to represent such arguments, not how many bits we should give such values (right?).

**Comment by lydia-duncan** [comment]
Yeah, I want the sizes to match (otherwise we will run into really weird errors).  My question is mostly about the best way to ensure that they match - either by explicitly using numpy types all the time (which seemed a little restrictive, but also possibly "safer"), or by using the default Python types in certain situations where we feel it is appropriate.
