### ISSUE TITLE
Handle default values for exported functions in python library compilation

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#10667]
I believe we lose the idea of default values after function resolution, meaning that codegen is too late to output them.  Standard C does not support default values, so such information can't live in the header or .pxd file.  However, Python does allow them, and you can specify the value in the .pyx's function declaration, e.g.:

```cython
from foo cimport functionName as chpl_functionName

def functionName (arg1 = 0):
  chpl_functionName(arg1)
```

Imo, we should make an effort to support this case.  Our AI workflow implementation also relies on it (made possible today by writing the .pyx files ourselves).

**Comment by lydia-duncan** [comment]
I believe that Python argument default values cannot rely on other arguments, like Chapel ones can.  This means that special treatment is needed for
```Chapel
export proc functionName (arg1: int, arg2: int = arg1) {...}
```
versus
```Chapel
export proc functionName (arg1: int, arg2: int = 3) {...}
```
And default values that rely on global variables or executing functions will likely also prove tricky

**Comment by bradcray** [comment]
This challenge strikes me as being equivalent to exporting overloaded Chapel functions to Python (which presumably supports them) via C (which doesn't), and the overloading case may be easier to solve first (because it's more straightforward and because I think we handle default arguments via introducing additional overloads?  (or used to at least).

I'm guessing your hand-generated `.pyx` solution helps manually map from the logical user-facing name to the C name we codegen, is that right?  Since Chapel FnSymbols store both their Chapel `name` and their generated `cname` could the compiler do the same mapping when it generates the `.pyx`?

**Comment by bradcray** [comment]
> in part because we only recently allowed exported functions to have different names from what they were declared with in the Chapel code, right?

No, it's been 7 years now:  https://github.com/chapel-lang/chapel/commit/8e370cd0580f3cdfad07a910059a70716e02a200.  The recent change was to permit them to take param string expressions in addition to the previously supported identifiers and string literals.

**Comment by lydia-duncan** [comment]
Ah, right right.

**Comment by bradcray** [comment]
For Chapel cases that don't violate Python's rules, do we have a hand-translated case of what we would do in the pyx/pyd files to make them work?  I was assuming not in reading this issue previously, but @ben-albrecht said something in email that suggested that maybe we do?

Maybe put a different way, I'm wondering where this issue falls on the "we know what we need to do and just need to do it" vs. "we need to figure out what we're going to do" axis.

**Comment by lydia-duncan** [comment]
We have a hand-translated case, but it's internal (the AI workflow stuff).  I believe it falls under "we know what we need to do and just need to do it"

**Comment by lydia-duncan** [comment]
Not having this support present has resulted in a lot of pain for @ben-albrecht
