### ISSUE TITLE
default comparison for records with default types is not symmetrical

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#10872]
``` chapel
record R {
  type t = int;
  var x:t;
}

proc main() {
  var r64 = new R(int(64), 64);
  var r32 = new R(int(32), 32);
  
  // This works on master
  writeln(r32 == r64);
  
  // this does not
  writeln(r64 == r32);
} 
```

**Comment by mppf** [comment]
PR #10873 will make the above test compile and run (and the behavior symmetrical) but I'm leaving this issue open to ask if it should fail to resolve in both cases.

**Comment by bradcray** [comment]
I agree that the asymmetry seems clearly wrong.  I'm trying to think about what I'd expect the behavior to be, though.  Thinking out loud, I imagine three possible interpretations:

1.  r32 and r64 are different types, so trying to do `==` on two such records should result in a compile-time error by default.  If the user wants to do comparisons across different instantiations of `R`, they should write the `==` operator themselves.

2. The default comparison should compare all fields including the type field, in which case it should resolve, but return `false` for this case.

3. The default comparison should compare all execution-time fields of the record, in which case it should resolve, and return `true` for this case since we support `==` between `int(32)` and `int(64)` (via coercion of the 32-bit value).

If I were to rank these choices, I think I'd rank them as 1, 3, 2.  But I think the expectation between 2 and 3 could be confusing enough that I think 1 is probably the better choice.

**Comment by vasslitvinov** [comment]
If we have two record types with identical fields - can we compare their instances?

```chpl
record R1 { var x: int; }
record R2 { var x: int; }
var r1: R1, r2: R2;
writeln(r1==r2);
```

If yes, then any instantiations of G should be comparable.

I thought that the defaults for record comparison and assignment look only at record fields, not the record types per se. Under that philosophy, it should be "yes" above.

Should we include "compile-time" fields in the comparison?

I think we should, because otherwise two records that differ only in a param field would be the same, ex:

```chpl
record R { param x; }
var r1: R(1); var r2: R(2);
writeln(r1 == r2);
```

I suggest that comparison of records differing in compile-time fields generates a compile-time "false".

Another twist is comparing two records with like-named field that is `param` in one and `type` in the other. Since `==` over this combination does not resolve, `==` over such two records should not resolve either.

**Comment by bradcray** [comment]
> If we have two record types with identical fields - can we compare their instances?

I assume from your question that you didn't try this?  Running your example shows that no, we can't.  And I think this is appropriate—if I have an "age" record and an "SAT score" record, it doesn't make sense to support comparisons between them automatically even if they happen to store the same fields.

Your response increases my confidence that not supporting comparisons by default between different generic instantiations would be the least surprising given that you preferred my option 2 over 3 where I'd gone the opposite way.  The author of a record can always provide the comparison if they want to support either 2 or 3.

**Comment by vasslitvinov** [comment]
Disallowing comparison between records of different types makes sense to me. In which case we should go with Option 1.

By the same reasoning it make sense to disallow default **assignment** between records of different types  or different instantiations of the same generic type.

For both assignment and comparison, it would be nice to generate a specific error message instead of a generic "cannot resolve".

**Comment by vasslitvinov** [comment]
P.S.

> I assume from your question that you didn't try this?

I was/am thinking "from scratch" rather than from whatever is currently implemented.

**Comment by ben-albrecht** [comment]
I am in favor of the more restrictive option 1 as discussed above.

Open question - Should these rules apply to classes as well?

The following compiles and runs on master today:

```chpl
class C {
  type t = int;
  var x:t;
}

proc main() {
  var r64 = new owned C(int(64), 64);
  var r32 = new owned C(int(32), 32);
  
  // false
  writeln(r32 == r64);
  
  // false
  writeln(r64 == r32);
} 
```

**Comment by mppf** [comment]
- [ ] try disallowing assignments such as r64/r32
- [ ] try disallowing comparisons such as r64/r32. Check other comparison operatiors.

**Comment by mppf** [comment]
I'm seeing 64 errors from not allowing the `=` across different types like this:
```
> $CHPL_HOME/modules/dists/CyclicDist.chpl:776: In function 'dsiAccess':
> $CHPL_HOME/modules/dists/CyclicDist.chpl:801: error: type mismatch in assignment from _remoteAccessData(int(64),1,int(64),true,false) to _remoteAccessData(int(64),1,int(64),false,false)
```

e.g. optimizations/sungeun/RADOpt/access1d.chpl
