### ISSUE TITLE
Relocation/-fPIC errors when exporting Chapel as shared/dynamic library

### ISSUE THREAD

**Issue by BryantLam** [chapel-lang/chapel#10887]
I tried using [these instructions to export Chapel as a **shared** library](https://chapel-lang.org/docs/1.17/technotes/libraries.html) and encountered relocation errors and "recompile with -fPIC" suggestions.

`chpl --library --dynamic <file.chpl>`

From https://github.com/chapel-lang/chapel/issues/10036#issuecomment-403113923, it looks like this use case is not meant to be supported. If so, what is the purpose of `chpl --dynamic`?

For context, I'm trying to export Chapel functions as a shared library because I want to interoperate *Chapel to C to Python* and Python wants to only load shared libraries.

**Comment by ronawho** [comment]
By default we build position-dependent .a's for the runtime/third-party. You can opt-in to building PIC .a's by building the runtime/third-party with `CHPL_LIBMODE=shared` set (you'll have to clobber the runtime/third-party first.) This will give you libraries that can be linked in, but since they're static you'll still need to provide the final -L/-l args. You should be able to get those with something like `/util/config/compileline --libraries`

https://github.com/chapel-lang/chapel/pull/10175 added support for building PIC third-party code in order to support python/chapel interoperability, but today it's an undocumented feature with some known performance regressions for privatized arrays (regressions documented in https://github.com/chapel-lang/chapel/issues/10036)

cc @lydia-duncan

**Comment by BryantLam** [comment]
Closing.

Resolution is to use environment variable `CHPL_LIBMODE=shared` on a clean/clobbered (`make clobber`) source tree, at least until #10898 is resolved.

**Comment by lydia-duncan** [comment]
#11327 makes it so that a `make clobber` is no longer necessary.  It also changes the environment variable to `CHPL_LIB_PIC` and the intended setting to `pic`, to reflect that the variable impacts whether -fPIC is used.
