### ISSUE TITLE
Alter behavior of -o flag in library compilation to prepend lib to final .so/.a

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#10938]
Today, `chpl -o foo --library foo.chpl` will generate `foo.a` or `foo.so` depending on whether you are compiling dynamically or statically.  This seems to work fine for regular C compilation (as long as the exact path to the library is used), and the dynamic version works fine when making a Python module from that library.  However, the static version runs into issues when making a Python module - certain symbols defined in the library itself can't be found (see #10923) when we try to import the generated module.

Since the typical strategy is to name libraries with a `lib` prefix (and `chpl --library foo.chpl` also generates a `libfoo.a` or `libfoo.so`), we'd like to propose changing the behavior of the -o flag to add a `lib` prefix in `--library` compilation, to give the least surprising behavior.

**Comment by lydia-duncan** [comment]
Brad and I were a little concerned that this would mean there was no way in the Chapel compiler to specify `foo.a`/`foo.so`, but the user can always rename their library after the fact (and should know that they are opting into something that won't work in their own Cython compilation)

**Comment by bradcray** [comment]
I argued offline to Lydia that since we were already turning `-o foo` into `foo.a` or `foo.so` (that is, we weren't taking the literal name supplied by `-o` but were modifying it further by adding a suffix) that this felt thematically similar to me.  I also think it feels nicely symmetrical that when compiling `foo.chpl`, the default behavior will now match what you get if you say `-o foo` for executables and for libraries.
