### ISSUE TITLE
lifetime checking and loop expressions

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#11022]
### Summary of Problem

The following pattern:

```chapel
var x = [i in 1..3] new borrowed C(i);
```

might appear as though it's creating an array of borrows that will be reclaimed when the current scope exits, but in actuality, the borrows will be reclaimed before they're even stored in `x` since loop expressions introduce their own lexical scopes (like the one `i` lives in).  This is a case that the lifetime checker doesn't currently warn about, but it seems subtle enough that it seems it would be nice if it did.

### Steps to Reproduce

**Associated Future Test(s):**

[`test/classes/delete-free/lifetimes/forall-of-new-borrowed-escapes.chpl`](
           https://github.com/chapel-lang/chapel/blob/master/test/classes/delete-free/lifetimes/forall-of-new-borrowed-escapes.chpl
          ) #11015

### Configuration Information

- Output of `chpl --version`:  `1.18.0 pre-release (94b97a0cda)`

**Comment by vasslitvinov** [comment]
Seems to me that this should be legitimate, like a record with a borrowed field.

**Comment by mppf** [comment]
Iterator scoping can be different from function scoping. In particular, with an iterator, a value at the scope of the iterator body can be reclaimed automatically when the iterator continues, rather than in the process of yielding. For example:

``` chapel
iter yieldIteratorTmpBorrow() {
  var tmp = new owned C();
  for i in 1..10 {
    yield tmp.borrow();
  }
}
```

If this were a function that returned `tmp.borrow()`, we would have a lifetime checking error inside the function, since the function is returning a borrow from a "scope" local variable. However we might decide that this iterator declaration should be allowed by the checker. If it is allowed by the checker, we have to worry about cases like this:

``` chapel
proc badIteration() {
  var b: borrowed C;
  for x in yieldIteratorTmpBorrow() {
    b = x;
  }
  writeln(b); // uh-oh, use-after free
}
```

which implies that we would need to detect the problem by inspecting calls to the iterator.

But, the exact same iteration and capture should be legal if the iterator is yielding borrows from globals:
``` chapel
iter yieldGlobalBorrows() {
  for i in 1..10 {
    yield global.borrow();
  }
}
proc okIteration() {
  var b: borrowed C;
  for x in yieldGlobalBorrows() {
    b = x;
  }
  writeln(b); // it's OK, it's a borrow from a global
}
```

Another wrinkle is that we might want to support iterators that yield references to iteration variables, e.g.:
``` chapel
iter yieldRefX() ref {
  var x = 0;
  for i in 1..10 {
    yield x;
  }
  writeln(x);
}
```

This leads us to several design options:
 1. We simply prohibit an iterator that yields from an borrow of a variable scoped to the iterator. The main problem with this is that the yieldRefX pattern would not be legal.
 2. We consider, at any loop invoking an iterator, that any yielded borrow has scope of the loop. This would detect errors in all the above programs (including a loop calling yieldGlobalBorrows).
 3. We use interprocedural analysis to decide what scope the iterator is yielding to distinguish the yieldIteratorTmpBorrow and yieldGlobalBorrows cases. We use this scope inside the loop to decide if `b = x` is OK or not.
 4. We consider (2) above the default (yielded borrows have scope of the loop they are called in). Additionally, we allow users to override this default by specifying a lifetime for the yield of the iterator (similarly to how we hope to provide a way for users to specify the lifetime of a function return). The iterator `yieldGlobalBorrows` would need the extra annotation and the compiler would use it to verify that it didn't return anything of more limited scope than a global (in that case).

I think I'm going to try for (2) for now and consider (4) the future-work improvement on it.

**Comment by vasslitvinov** [comment]
+1 for (2) for now and (4) as a future direction.

**Comment by cassella** [comment]
OOC, is there a way to write Brad's initial code so that it has the behavior it appears to have?

**Comment by mppf** [comment]
@cassella -
``` chapel
class C { var i: int; }
var x = [i in 1..3] new owned C(i);
var y = [elt in x] elt.borrow();
writeln(x.eltType:string);
writeln(y.eltType:string);
```

**Comment by mppf** [comment]
I'm looking at making iterator methods have a default of the receiver lifetime, but functions have a default of the loop lifetime. Otherwise it's hard to get array iteration to work right.

**Comment by vasslitvinov** [comment]
I suggest that the following three cases should get similar treatment w.r.t. lifetimes:

* a variable: `var x = new borrowed C();`
* a record field: `record R { var y = new borrowed C(); } var r: R;`
* an array element: `var A = [1..3] new borrowed C();`

In all cases, it means "a borrow from an owned value that gets deleted when the enclosing variable (`x`, `r`, `A`) goes out of scope."

Therefore, contrary to what this issue requests, these should be allowed.

Pro: intuitive.

Cons: contradicts "the letter of the law" that requires that the owned temp be deallocated at the end of the initializer (for `R`) or the forall-expression's loop body (for `A`).

Another cons: how are we going to implement that?? While it seemed to work pre-11501 in an RA variant -- [see BucketArray field here](https://github.com/chapel-lang/chapel/pull/11321/files#diff-b71f0b704929d4b58e5990ae7c0c997a), I don't know how.

And a cons: how do I tell which of R instances should deallocate their borrow's owned instance (and when?) and which shouldn't?
```chpl
var r1, r2, r3: R;
r1 = r2;
proc foo(in rArg: R) { }
foo(r3);
```

Given all these cons, why would the user actually want to write any of the above? Why not use `owned` directly like so:

* a variable: `var x = new owned C();`
* a record field: `record R { var y = new owned C(); } var r: R;`
* an array element: `var A = [1..3] new owned C();`

A: this is a "pro". When it is owned, it can be taken away. A borrowed thing will always be there.

**Comment by mppf** [comment]
The `new borrowed` design is that it is exactly equivalent to this:
``` chapel
var x = [i in 1..3] (new owned C(i)).borrow();
```

Which is just a specific form of the general pattern:
``` chapel
var x = [i in 1..3] f(g(i));
```

where we suppose that  f and g return records.

Right now, the expression temporary storing the result of g(i) is destroyed at the end of each of this loop's iterations. I think it would be unreasonable, surprising, and difficult to implement if the compiler instead created an array of temporaries storing the results of g(i) so they could have the same lifetime as x.

What if the loop were this kind of monte-carlo simulation?

``` chapel
var probability = * reduce [i in 1..n] computeProbability( createRandomArray() );
```

Here `createRandomArray` would return an array (say of size `m`). If `m` is reasonably large and `n` is reasonably large, making this change would cause the program to run out of memory instead of computing a reasonable result.
