### ISSUE TITLE
lifetime checking and initializing fields with `new borrowed`

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#11021]
### Summary of Problem

If a field is initialized with a `new borrowed` expression, the lifetime checker doesn't provide any warning to the user that the borrow will be invalid after the initializer has completed even though the field will live on.  This seems like a pattern that a user might be blindsided by since initializers are somewhat special routines and one might interpret the initialization expression as having the lifetime / scope of the field rather than the variable  (I'm not arguing that this behavior should change, merely that the compiler should help flag such cases).

```chapel
proc init() {
  this.x = new borrowed C();
}
```

### Steps to Reproduce

**Associated Future Test(s):**
[`test/classes/delete-free/lifetimes/field-init-escapes.chpl`](
           https://github.com/chapel-lang/chapel/blob/master/test/classes/delete-free/lifetimes/field-init-escapes.chpl
          ) #11015

### Configuration Information

- Output of `chpl --version`:  `1.18.0 pre-release (94b97a0cda)`

**Comment by mppf** [comment]
See also some discussion on another issue:
https://github.com/chapel-lang/chapel/issues/11526#issuecomment-434829714
https://github.com/chapel-lang/chapel/issues/11526#issuecomment-434832967
https://github.com/chapel-lang/chapel/issues/11526#issuecomment-434934240

**Comment by mppf** [comment]
I really don't think the compiler should add hidden fields to records or classes. 

Didn't we just decide to remove another field the compiler was adding, `outer`, in #9674 ? That one wasn't even hidden.

For the sake of argument, let's suppose for a second that the compiler added an `owned` field to store the `new borrowed`. What are the issues?

### Different numbers of temporaries for different initializers

Well, the first problem is that not all initializers necessarily create an `owned` temporary, and different initializers create different numbers of them. That means that these `owned` temporaries might be `nil` or not, depending on how the object was constructed. It also means there might be quite a few of them that are almost always unused.

### = won't work as expected, part 1

The second problem is that if the user wanted to use `=` on their record, it would behave strangely.

The immediate problem is that `=` on a record with an `owned` field mutates the RHS. That means that this pattern
``` chapel
const r1 = new MyRecord(...);
var r2: MyRecord;
r2 = r1; // Fails if MyRecord contains an 'owned'
```
will not compile.

I do not think we should implicitly add a field that introduces this problem. Instead, I think the programmer should have to explicitly put an `owned` field. This is so that they can (more) easily understand the reason that the generated `proc =` mutates the RHS.

### = won't work as expected, part 2

OK, but maybe we're not worried about that problem for some reason. What would happen in the unlikely event the user just always used `var` and `ref` arguments for their records?
``` chapel
var r1 = new MyRecord(...);
var r2: MyRecord;
r2 = r1; // What does this do?
```

Let's suppose that MyRecord contains two fields:
``` chapel
record MyRecord {
  var b = new borrowed MyClass();
  var _owned_tmp; // added my the compiler to store the temporary
}
```

OK, now what will the compiler-generated `proc =` look like?
``` chapel
proc = (ref lhs:MyRecord, ref rhs: MyRecord) {
  lhs.b = rhs.b;
  lhs._owned_tmp = rhs._owned_tmp;
}
```

Here note that as I mentioned, because not all initializers will necessarily use `new borrowed`, `_owned_tmp` might store `nil`. There is an argument that ownership transfer from `nil` should always be an error.  If we did that, this assignment function would already be problematic.

### = won't work as expected, part 3

Suppose that the user was confused by the behavior of the compiler-generated = in this case, or maybe they just needed to do something more complicated. What if they try to write their own `=`, and as a starting point, make it the same as the compiler-generated `proc =` ?

``` chapel
proc = (ref lhs:MyRecord, const ref rhs: MyRecord) {
  lhs.b = rhs.b;
}
```

Now, the user will immediately run into problems.
``` chapel
var outerR: MyRecord;
{
  var innerR = new MyRecord(...);
  outerR = innerR;
  // owned temporary destroyed here
}
writeln(outerR); // but outerR refers to the borrow of it here
```

Whether or not this is detected as a compile-time error by the lifetime checker, I think it would be immensely confusing for the user. Vs if `new borrowed` in this context were just an error, and they used an `owned`, this program has reasonable behavior and won't core-dump or fail to lifetime check.

### problems with lifetime checking

What if the user wants to update `b`?
``` chapel
var x = new MyRecord();
var theClass = x.b;
x.b = new borrowed MyClass(); // does not update the owned temporary
{
  var y: MyRecord;
  y = x; // "moves" x._owned_tmp to y._owned_tmp
  // now that temporary is destroyed
}
writeln(theClass); // uh-oh, use-after-free!
```

After assigning to `x.b`, Now x._owned_tmp and x.b point to different memory. But the original owned value - and the original borrow is still removed on assignment from x on the `y = x` line.  Then `y` is destroyed, freeing the memory. But this pattern would be difficult for the lifetime checker to detect and error for:
 * MyRecord now contains both an `owned` and a `borrow`. This kind of case can be inherently more difficult.
 * theClass is only ever borrowing from the in-scope variable, `x`
 * the compiler can sometimes detect when a `nil` `owned` is dereferenced, but it would be difficult to extend this analysis to record fields, which would be required in this case.


### probably don't want to generalize to all nested call results

But, just as in https://github.com/chapel-lang/chapel/issues/11022#issuecomment-435044818, why should we only be talking about `owned` temporaries from `new borrowed` here? The `new borrowed` design is that it is exactly equivalent to `(new owned Something(..)).borrow()`. This pattern is just a nested call where the inner call returns a record. Would you argue that in the following case, the result of `g` should be added as a hidden field in the record?
``` chapel
proc g(): SomeOtherRecord { ... }
proc SomeRecord.init() {
   this.someField = f(g());
}
```

What if the result of `g()` is big, say, an array?
``` chapel
proc MonteCarloSimulation.init() {
   this.probability = reduceProbabilities( applyTransformation( createRandomArray() ) );
}
```

Here `createRandomArray` makes a big array. Would you argue that it needs to be stored in a hidden field in the record?

If the answer to the above questions is "no", then how would the compiler know that it's supposed to do the special thing for `owned` but not for arrays? Sure, we could make `new borrowed C` behave as we like, but what about `this.someField = (createOwnedRecord()).borrow();` ?

Beyond all of that, right now the scope of the temporaries is determined by the normalizer, which doesn't know the types. So it'd be significantly difficult to even make such a rule only apply to `owned`.

**Comment by bradcray** [comment]
I haven't made it through all of Michael's previous post yet, but was initially pretty convinced by his sentiment that the compiler shouldn't add a hidden `owned C` field to a class/record to support my ability to use `new [borrowed] C()` in a field initialization or initializer initialization context and was planning to say so here.  My thought was that if, as the class author, my intention is to have this object logically be owned by the class and match its lifetime, it seems reasonable for me to make an `owned C` field explicitly using `var x = new owned C();  (say).

However, as I was typing that up and thinking about what counterarguments there might be, I realized that this is not unlike our argument for why a standalone variable `var x = new C();` would be scoped/borrowed rather than owned.  The argument being that it results in a more "inert" pointer type that can't inadvertently have its ownership transferred, say by class author or user who doesn't understand the full implications of ownership.  So then I was left wondering why that argument wouldn't apply here as well.

So now I think I need to read the rest of Michael's argument above, but am quickly running into the weekend, so am capturing these two opposing points of view for the time being before heading out and will dive back into this next week.

**Comment by bradcray** [comment]
OK, I caught up with @mppf's previous comment, and am convinced by his arguments against adding hidden fields.

Without making other changes, I think this means that `new C()` will never be useful / usable as a field initializer (or the RHS of a field initialization in a class initializer), is that right?  I.e., it'll always need to be decorated in some way?

I'm a little nervous to say it out loud, but my quandary about "inert" pointers in the previous comment has led me to wonder over the weekend whether there would be benefit in having some sort of "non-transferrable owned" type which would be similarly inert once initialized (could only be borrowed, not transferred; couldn't be nil'ed, just de-initialized).  I say "nervous" because then it causes me to wonder whether `new C()` should mean this...  (which would be similar to having `new C()` mean `new owned C()` and would restore the seeming asymmetry in cases like `var myC: C = new C();`

**Comment by mppf** [comment]
> OK, I caught up with @mppf's previous comment, and am convinced by his arguments against adding hidden fields.

😌 

> Without making other changes, I think this means that new C() will never be useful / usable as a field initializer (or the RHS of a field initialization in a class initializer), is that right? I.e., it'll always need to be decorated in some way?

Yes.

> I'm a little nervous to say it out loud, but my quandary about "inert" pointers in the previous comment has led me to wonder over the weekend whether there would be benefit in having some sort of "non-transferrable owned" type which would be similarly inert once initialized (could only be borrowed, not transferred; couldn't be nil'ed, just de-initialized). I say "nervous" because then it causes me to wonder whether new C() should mean this... (which would be similar to having new C() mean new owned C() and would restore the seeming asymmetry in cases like var myC: C = new C();

I've been tracking the issues we've identified with `new C()` being `new borrowed C()` over at the end of #8938 and I've added a link to your comment there.

I think if we decide to allow the asymmetry we should just make `new C()` be the same as `new owned C()`.

I'd be open to creating another type that has a subset of the functionality of `owned` but worry that we're adding complexity without much benefit. Most of the time, I think a `const` `owned` covers the same ground. There are certain cases where something being `const` can be awkward, though.
