### ISSUE TITLE
problem looping over Unicode strings

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#11060]
I find that the `these` method on Unicode strings produces an unreasonable output:

``` chapel
var x = "eu.éú";

for ch in x {
  writeln(ch);
}
```

I would expect this program to output
```
e
u
.
é
ú
```

however it instead outputs
```
e
u
.
é
?
ú
?
```

I can't see a use-case where this behavior is expected or useful.

I think the remedy is two-fold:

1. Make `these` operate the same as the `uchars` iterator by default
2. Provide a way to get the byte at a given offset, so that someone wanting to loop over a string one byte at a time can do so with a `for offset in 1..theString.length` and then a call to this function.

**Comment by dmk42** [comment]
This is what `uchars()` is for.

**Comment by bradcray** [comment]
I'm moving this (and @mppf's  other recent string stories) into the backlog and assigning them to @dmk42 because I think they deserve attention in short order.  In doing so I don't mean to imply that @mppf's stance is right and should be acted on without further discussion/design.  Rather, these seem like the kinds of string design decisions that I've been hoping we'd be discussing and deciding during the past few years, but which seem to linger.

**Comment by bradcray** [comment]
> This is what `uchars()` is for.

I think I agree with Michael's stance that if we say "Chapel's strings are UTF-8 by default" (which I think of as the intention) it makes the most sense to have the default iterator have the behavior that uchars() does.  What would the counterargument be?

**Comment by dmk42** [comment]
I strongly disagree.  I think default indexing should be by byte as Rust does (in fact they don't even have indexing by codepoint or grapheme), and default iterators should be the same as default indexing.

**Comment by mppf** [comment]
> I strongly disagree. I think default indexing should be by byte as Rust does (in fact they don't even have indexing by codepoint or grapheme), and default iterators should be the same as default indexing.

Let's unpack this a little bit.

First, in Rust, they don't seem to have a concept of a "default" iterator. See for example https://tio.run/##KyotLvn/Py1PITcxM09DU6GaS0EhJ7VEoVLBVkGp8kybkjVQIC2/SCFZITMPKAqSV1AoKMrMK8nJU9RQqq5V0lFI1gSpquWq/f8fAA

If we wanted to be like Rust, we'd simply remove `iter string.these` and add `iter string.bytes` in addition to `iter string.uchars`.

To be clear, Rust *does* have a "default" of byte indexing for string slices; that is, integer indices are interpreted as byte offsets -- see https://doc.rust-lang.org/book/second-edition/ch04-03-slices.html#string-slices

Second, you're saying that it's important to you that these two programs behave the same:
``` chapel
for i in 1..mystring.length {
  var c = mystring[i];
  writeln(c);
}
```

``` chapel
for c in mystring {
  writeln(c);
}
```

While I can understand the desire for consistency in such cases, here it seems to me to be making other choices worse. For example, I'd rather take the viewpoint that there is no default unit for string indexing and that it must be specified (somehow) than leave `mystring.these()` in the unusable state it is in now (for Unicode).

But, I also don't see any particular benefit to this particular consistency. It seems rather more low-level than I expect we want users of the String type to be thinking.

But earlier I said this:

> I can't see a use-case where this behavior is expected or useful.

Can you think of a use-case where a user would actually want to iterate over the bytes that wouldn't be better accomplished by other means?

Summarizing:

* we should be like Rust -> Rust doesn't do this
* it should be consistent with `[]` access -> how/why does that help?

**Comment by bradcray** [comment]
Can you say more about why?  My intuition is that when people work with strings at the user level, they want to work with the logical characters (by some definition) rather than the underlying bytes.  If my name were "Brad" with an accent over the A, it feels much more useful and natural to have the default iterator yield four logical characters rather than five bytes (say).

I get that there's a desire to have an efficient way to get at most of the operators, but it doesn't seem to me that default iteration would need to be one of them because I wouldn't expect to be using it in a performance-critical section (like serializing the string to a file).  There, I'd expect to use some sort of serialization iterator specifically.

**Comment by bradcray** [comment]
Sorry, for some reason, I didn't see Michael's response in my browser before posting my previous note, so it may not be clear without context that I was trying to reply to David's last post rather than Michael's.  I'll try to edit it to clarify that.

FWIW, while I agree that the two loop forms in Michael's example do not need to behave the same, I also think that it would be attractive if they did (and similarly, given my Brad-with-accent example, I think it would be attractive to have myname[4] (or 3) return 'd' for 1- (or 0-) based indexing rather than the byte before that.  It seems to me that the cases which need to be optimized for speed (use bytes) are those in which a standard library (like a strstr() type of routine) return an offset and then it's used to index into a string.  But in that case, it seems like such libraries could return some wrapped integer type (`byteoffset`) because the object doesn't need to be particularly user comprehensible (i.e., I'm probably not going to print out the integer or reason about it, but rather to use it to access the string?).

Put another way:  The interfaces that the user is most likely to interact with (default iteration and default indexing) seem like they should use the most natural-to-humans approach (return logical codepoints if not graphemes, which we seem to have eliminated) while those that are by definition more opaque ("I'm taking the result of this routine and using it to index") can use more opaque types.

These are the kinds of points I've [tried to bring up over here](https://github.com/chapel-lang/chapel/issues/10834#issuecomment-416359642) on issue #10834 as well as on email after our deep-dive, but those queries and feedback have never seemed to go anywhere or be acknowledged.

**Comment by bradcray** [comment]
At the risk of continuing to talk to myself, I was thinking about this a bit more this morning and realized that there seems to be a strong corollary here with sparse arrays (ours, and in general).  Given a sparse array with the index set `{1, 2, 4, 8, 16, 32}` (say), the array is very fast to iterate over using the following loop form:

```chapel
for a in SparseArr do
  writeln("next element is ", a);
```

because the loop can simply iterate over the sparse array's dense representation in memory.  But if the user writes:

```chapel
for i in SparseArr.domain do
  writeln("element ", i, " is ", SparseArr[i]);
```

which is logically identical, the performance will typically be much worse because they're doing a random access to a sparse array in each iteration (and randomly accessing sparse arrays is expensive).  The "solution" to this is arguably two-fold:

1) (short-term) teach users to either use the first loop form, or to use zippered iteration when they need to access the array's indices alongside its elements:

```chapel
for (i,a) in zip(SparseArray.domain, SparseArray) do
  writeln("element ", i, " is ", a);
```

2) (longer-term) teach the compiler to strength reduce random accesses within loops, particularly for loops over an index set that matches the array being randomly accessed, to convert the second loop above to the one just above (say).

Though not precisely the same, unicode strings seem similar in this respect to me—the "intuitive" random access routine for them is the friendliest, but expensive (O(n)).  Yet I'm not convinced that that's a reason to adopt the unintuitive semantics by default (though, again, nobody's really taking up the debate with me or providing motivating examples).

Another thing that occurred to me while mulling this over this morning is that we could always parameterize strings by what type of iteration and indexing they want to support.  E.g., imagine something like:

```
type intuitiveString = string(accessType=codepoint, defaultIter=codepoint);
type michaelString = string(accessType=byteoffset, defaultIter=codepoint);
type asciiString = string(accessType=byteoffset, defaultIter=byteoffset);
```

Then nothing is lost and the debate simply becomes a matter of what the default values for these parameterizations should be.  This feels a bit similar to channels being locked (intuitive but expensive) or unlocked (less safe but cheap) by default, associative domains being parallel-safe or not, etc.

**Comment by bradcray** [comment]
> Recently @dmk42 and I were discussing possibly making indexing and slicing methods for strings simply not accept integer arguments - meaning that "there is no default".

Yeah, I proposed this as well in email after the deep-dive, but I don't think I like it.

**Comment by dmk42** [comment]
Yes, I meant to comment on that as well.  Not having a default makes it absolutely clear in the code what is happening.  I am definitely in favor of that.

**Comment by bradcray** [comment]
There are lots of things that aren't clear in Chapel code until you understand what's going on, but I'm not convinced that's a reason to throw convenience out the window (we haven't before, I'm not convinced we should here).

In any case, I think it's past time to write up some examples illustrating these questions and to put them in front of a larger group (the team and/or chapel_users).

**Comment by dmk42** [comment]
The resolution to this issue was that we decided to implement `byteIndex` and make default indexing work by codepoint instead of by byte.
