### ISSUE TITLE
Add a way for DefaultRectangular to switch between RMO and CMO

### ISSUE THREAD

**Issue by daviditen** [chapel-lang/chapel#11092]
As a user who would like to interoperate with Fortran code, it would be good to be able to specify that arrays are in CMO instead of the current RMO.

From a description written by Brad:

> The hypothesis is that with a small number of code changes in DefaultRectangular we could support either (and that since most other things build on DefaultRectangular, these will likely just be able to inherit its support).
>
> I think the toughest part here is coming up with a clean interface and getting it past the group.  I think the ultimate approach will likely involve a param on the classes themselves which perhaps takes its default from a global config param; but this will require exposing the names of the classes themselves for people to use them, which will probably require renaming the classes.  So for starters I might just introduce the global param and have it be a whole program setting.
>
> An acid test would be whether we can run the full test suite in CMO mode without anything breaking.

**Comment by bradcray** [comment]
@daviditen : Just to make sure I'm interpreting properly:  Your branch still prints arrays in RMO by default, and most of the tests above use "tricks" to print them outside of the typical interface (iterating and indexing).  If so, that seems completely reasonable and I think that they can be considered to be working as expected.

The bulk transfer would be nice to get working for CMO since we're likely to be wanting to do stencil styles of transfers with CMO arrays.  @benharsh may have tips there if the fix isn't obvious.

**Comment by daviditen** [comment]
@bradcray, Yes, `writeln(my2DArray);` strides through the array to print in RMO.  The tests above fill in the array and then use the base pointer to step through and print values in memory order.  I agree that they are working as expected, but the testing system still lists them as failures for now.

I think bulk transfer is still working for CMO, just it takes the "complex" path instead of the "simple" one.  I suspect the "complex" path is slower though, so agree it would be nice to make it take the "simple" one.

**Comment by daviditen** [comment]
My preference is for the enumeration as I think it's possible one could want a storage order besides RMO and CMO.  `ArrayStorageOrder.ZOrder`?

**Comment by daviditen** [comment]
Closed by PR #11316.
