### ISSUE TITLE
BlockDist to DefaultRectangular assignment not triggering bulk comm

### ISSUE THREAD

**Issue by ronawho** [chapel-lang/chapel#11298]
Figure out why assignment from BlockDist to DefaultRectangular is not triggering bulk comm and why it's creating parallelism on a machine that already has numCores/here.maxTaskPar tasks running. 

I'm a little sparse on details at the moment, but for context this is from https://github.com/StanfordLegion/task-bench/commit/c05970df9c064ad5e6165714066b2c7c01502900. Here we were expecting the assignment to trigger bulk communication, but it didn't. It also created additional tasks (when `here.maxTaskPar` tasks are already running), which significantly degraded performance of the rest of the application. So far as I know all of our parallel iterators will check how busy the node is and not create additional tasks if we're already using `here.maxTaskPar` tasks, so that part was especially confusing to me.

**Comment by elliottslaughter** [comment]
I'm the author of the code that originally lead to this issue.

As a follow-up, I noticed a performance degradation resulting from using array assignment on a block distributed array. The workaround for this appears to be to assign the elements one at a time. To my understanding, this ought to be doing the same thing as the array assignment (since as @ronawho noted, it already was not doing bulk communication). However somehow there's a order of magnitude difference in performance here, which is most noticeable when running small task granularities.

You can see the workaround here: https://github.com/StanfordLegion/task-bench/commit/45205300ed456b7e172ba2af9a91e8790b09dcfd

**Comment by elliottslaughter** [comment]
At the suggestion of @bradcray I tested a version of this change where I use a nested array, such that the final array (which is being assigned to) should be just a regular, remote array and not subject to a block dist. You can see the patch below. Unfortunately, this approach still costs us about 2x over the workaround, an effect which is most noticeable for very small tasks.

https://github.com/StanfordLegion/task-bench/commit/ba8f0ba21d6d820399ec052bb7c28cc6fb385379
