### ISSUE TITLE
Error or abort when building with `make -j` when `CHPL_LLVM=llvm`

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#11404]
LLVM is known (by us, at least), to overload the system when made in parallel.  If I remember correctly, it fails to track how many threads it has spawned for the parallel make and will continue to spawn them until the system runs out of memory, which is usually catastrophic.  Since we know this, it might be good to stop building with an error when we try to make llvm under these circumstances.

**Comment by ronawho** [comment]
I'm not sure how easy it is to catch this in our makefiles. This is kinda of a lame solution, but if you find yourself doing this often you could create a bash wrapper to catch yourself. In my .bashrc I have something like:

```bash
unamestr=`uname`
if [[ "$unamestr" == 'Linux' ]]; then
  num_cores=$(grep -c ^processor /proc/cpuinfo)
elif [[ "$unamestr" == 'Darwin' ]]; then
  num_cores=$(sysctl -n hw.ncpu)
fi

make() {
  make_j=0
  for var in "$@"; do
    if [[ $var == "-j" ]]; then
      make_j=1
    fi
  done

  if [[ $make_j -eq 1 ]]; then
    command nice make "$@" -j $num_cores
  else
    command make "$@"
  fi
}
```

This intercepts calls to `make` and if I see a plain `-j` I'll prepend `nice` and append `-j<num_cores>`

**Comment by daviditen** [comment]
@lydia-duncan can we close this issue? `make -j` is telling make to use as much parallelism as it possibly can. If you want less than that you can either do something like @ronawho's wrapper or make sure to always specify a number after the `-j` - `make -j4`. I don't think it's LLVM's Makefile's place to tell make to use less parallelism than was requested.

**Comment by lydia-duncan** [comment]
My concern is not about having a way to indicate a specific amount of parallelism.  My concern is that a strategy we've gotten used to when making the compiler with `CHPL_LLVM != llvm` causes my machine to crash when `CHPL_LLVM == llvm`.  I don't think we should have a way to invoke our makefiles that results in crashing someone's computer, regardless of if there's work-arounds available, that makes us seem unstable and dangerous to use.  Maybe the fact that it's because we're calling out to LLVM and LLVM is doing this indicates that we should file a bug with LLVM instead, but this is a problem that should be resolved rather than ignored just because we can train developers to avoid it.

**Comment by bradcray** [comment]
When you say `CHPL_LLVM=llvm`, you mean `CHPL_LLVM=bundled` now, right?  (i.e., something you have to opt into rather than anything we'd select automatically for you).

It seems to me that it's hard for us to know whether someone's use of `make -j` will be good or bad for their system, and that if we don't recommend people build using `make -j` (which a quick `git grep` suggests we don't) then we shouldn't invest too much effort trying to come up with a solution to a problem that is difficult to anticipate.  I think we've also updated several versions of LLVM by now, so it seems possible that if they did have a "too much parallelism" issue in their Makefiles, that it may be resolved.

For those reasons, I'd be in favor of closing this until/unless a user is bitten by this and we think it's our fault rather than theirs or LLVM's.

**Comment by lydia-duncan** [comment]
Shoot, yeah, I meant `bundled`.  Still getting used to that.  Basically, "long build not helped by usual way of getting parallelism".  I don't remember it being machine specific but that may be because I got scared and aborted any chapcs runs I accidentally fired off.  Not recommending it to users does make me feel better but I still worry we're sweeping a problem under the rug instead of resolving it.

**Comment by bradcray** [comment]
I just did a `make -j` on `chapcs11` with `CHPL_LLVM=bundled` and had no issues.  So either the situation has improved since 2018 or the behavior is sufficiently machine-dependent that I don't think it's worth our time to determine how to protect the users from themselves/their issues.  In either case, I'm still in favor of closing this issue.
