### ISSUE TITLE
module-scope variables and temporaries

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#11526]
For example, the following program compiles and then shows valgrind errors when run:

``` chapel
module M1 {
  class C { var x: int; }
  var global: borrowed C = new borrowed C(1);
}

module M2 {
  use M1;
  proc main() { 
    writeln(global);
  }
}
```

Additionally, consider the following variant:

``` chapel
var global: borrowed C = new owned C(1);
```

Here is another similar case with a reference to an array slice:

``` chapel
module M1 {
  proc makeArray() {
    var A:[1..100] int;
    return A;
  }
  ref slice = makeArray()[1..10];
}

module M2 {
  use M1;
  proc main() { 
    writeln(slice[1]);
  }
}
```

I think that all of these programs should work and the important temporary should become a module-scope variable. However this is different from how the compiler currently handles normalizing inner calls.

For example

``` chapel
var global = f(g());
```

assuming f and g both return records, the temporary storing the result of g will currently be destroyed at the end of the module init.

This issue proposes that the temporaries created in top-level blocks (i.e. that end up being initialized in the module init function) remain allocated until the module deinit function. Additionally it proposes that the strategy in #11534 be used to reduce the potential impact of increased memory usage from these temporaries remaining allocated as module-scope/global variables.

**Comment by mppf** [comment]
@vasslitvinov - I'm really curious what your reaction to this problem is.

**Comment by vasslitvinov** [comment]
It is clear to me that the `owned` temporary created in support of a global `borrowed` variable needs to survive through that global's deinitialization in its module's deinit().

Whereas currently the compiler destroys the `owned` temporary at the end of the module init().

**Comment by bradcray** [comment]
This feels somewhat similar to another case that has led to some confusion.  If I recall correctly, it was something like:

```chapel
class C {
  var x: D = new D();
}
```

where the scope of the `D` variable appears to be in the class (so seems like it should live as long as the object does) yet ends up being more like for the life of the initializer.  This case can also be stepped into more explicitly via:

```chapel
class C {
  var x: D;
  proc init() {
    this.x = new D();
  }
}
```

where here the scope of `new D` is more obviously the initializer, yet I think it could be argued that since it's in used in an initialization assignment, its lifetime should be the same as the field rather than of the enclosing scope.

In both cases, I can see a "letter of the law" interpretation that says we're doing the right thing (and maybe if lifetime checking caught all these cases, we'd just learn how to deal with them", but there also seems to be a "spirit of the law" interpretation which argues that these can be surprising / confusing / unintuitive to users.

FWIW, the statement of this issue steps into one of my pet peeves which is that I'd argue that Chapel doesn't have global variables, and that the examples here are actually module-scoped variables.  While we've traditionally used "global" as a shorthand for module-scoped, I think we should try to break ourselves of that habit.

**Comment by mppf** [comment]
@bradcray - I changed it to use "module-scoped" but this will be a hard habit to break.

Regarding the initializer case, I think that needs another issue, because I'm going to argue that we should support this pattern for global variables but not for initializers. The reason is that doing it for initializers would require us to add fields to the user's record, and that seems counter-intuitive. Besides that, it's easy to get into problems where, say, one is using `proc =` for the record. I think it's unlikely that the compiler-produced version of this will have the correct behavior and I don't think it's possible to write it correctly without naming the `owned` temporary field. Point being that if we added that `owned` field implicitly, I think it'd be almost impossible to actually use the record. (Assuming the record needs to do things like be assigned or copy-initialized).

**Comment by mppf** [comment]
@bradcray - the initializer case has its own issue already - #11021. I'll comment there about it a little but but let's leave this issue for the module scope case.

**Comment by mppf** [comment]
@cassella 

> I think having different behavior for "module scope variables" and
> initializers would be confusing.

I disagree. Global variables and record fields are very different.

> 
> I think if writing the x = new D() the two ways Brad did above
> result in different behavior, it'll be confusing.

I don't see any reason that writing the `init` yourself vs. having the compiler-generated initializer do it should matter. I'm not proposing that, anyway.

> 
>     I'm going to argue that we should support this pattern for [module-scoped] variables but not for initializers.
> 
> I assume you mean for the initialization-statement of module-scoped
> variables, not for other ways of assigning to a module-scoped
> variable? (e.g., in an arbitrary function.)

No, by initializer I mean `proc init`, whether compiler-generated or not.

But, please let's move discussion of the field case to #11021, unless it's an argument about what we should do in the module-scope case.

**Comment by benharsh** [comment]
I'm generally in support of hoisting temporaries to module-scope when those temporaries are running in the module-init function. I did something similar in #11307 to fix some module-scope array-of-array issues where the temps for runtime types were being destroyed at the end of them module-init function.

I agree with Michael that the related issue for initializers is different enough to warrant a separate issue.

**Comment by vasslitvinov** [comment]
Here is one way to look at what this issue is requesting. Consider this module as the "main" module in the program:

```chpl
module M {
  // proc/iter declarations are not shown
  top-level-stmt-1;
  ...
  top-level-stmt-N;
}
```

Let's say that the explicit module deinit function contains `deinit-stmt-1; ... deinit-stmt-K;`. If there is none, K=0.

Then, module-level variables and temporaries are initialized/deinitialized the same way as when the following block-statement is executed:

```chpl
{
  top-level-stmt-1;
  ...
  top-level-stmt-N;
  main();
  deinit-stmt-1;
  ...
  deinit-stmt-K;
}
```

In other words, module-level declarations, a call to main, and the BODY of the user deinit function (when present) are all in the same scope. As with a block statement, the variables declared by top-evel-stmt-*, if any, are deinitialized at the close curly brace.

**Comment by mppf** [comment]
As far as I can tell, Brad, BenH, Vass, and I are on the same page in terms of having the default behavior for these temporaries be module scope. I think it's going to be useful to relax that in certain cases, but that's for #11534.
