### ISSUE TITLE
Cannot define new method on type alias

### ISSUE THREAD

**Issue by BryantLam** [chapel-lang/chapel#11646]
I want to define a method on a type alias, and have it effect the resolution for the aliased and aliasing types.
```chapel
proc int.m1() {
  writeln("m1 with ", this);
}

1.m1();
2.m1();

type int_v2 = int;

var i2: int_v2 = 11;
i2.m1();

// Defining a method on int_v2 does not work.
// --> error: cannot resolve base type for method 'm2'
proc int_v2.m2() {
  writeln("m2 with ", this);
}

// If it did work, I would now expect these to work:
1.m2();
2.m2();
i2.m2();
```

I don't know if there's additional complexity to consider with e.g.,
```chapel
class Container { type t; }
type StringContainer = Container(string);
proc StringContainer.method() {}
```

`chpl version 1.19.0 pre-release (78051d35)`

**Comment by lydia-duncan** [comment]
I've had a note to myself for years (whoops) with a question about whether this sort of thing should impact only the type alias or should impact both the alias and the original type.  Personally, I lean towards only impacting the alias (the argument being that there are two times when you would make a type alias: when the original name was too long, and when you want it to mean something separate but otherwise have the same characteristics as the original.  It is the latter case that makes me think we should only impact the alias) but I haven't thought very deeply about it.

**Comment by BryantLam** [comment]
For non-generic types, there is not a good reason why defining methods on a type alias should preclude the original type from also having that method.

In the case of generic types, I could see a rationale for methods on a concrete or partially concrete type alias resolving into the equivalent `where` clause on the generic type, but I haven't thought through all of the (potentially confusing) ramifications of this.

**Comment by lydia-duncan** [comment]
It is very complex and you've illustrated some concerns that hadn't occurred to me yet.  Only being able to add methods to an aliased type does save us a little bit of worry about doing operations the original type couldn't handle but you are right that any use of duck typing/interfaces/reflection on if a particular method name resolves would run into these issues.

**Comment by vasslitvinov** [comment]
As of today, a type alias is interchangeable with the aliased type - and has been for longer or shorter time - in a few cases:
* the type of a formal vs. the type of an actual
* a variable declaration
* `new` expression, ex. `type T=object; new T()` is the same as `new object()`

See also a discussion in #15825 .
