### ISSUE TITLE
extern/export functions and where clauses

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#11658]
The compiler includes an error if an extern function has a where clause. I don't think this error makes sense.

For example:
``` chapel
extern proc printf(fmt:c_string) where true;

proc main() {
  printf("test\n");
}
```

But, now:
 1. Where clauses are evaluated and supported on concrete functions (#5238)
 2. An `extern proc` can specify use a different `cname` (#10053)

As a result, there are plausible scenarios where one might want to use `where` clauses to select between different declarations for an extern function (possibly including changing the cname).

At the same time, since `extern` functions represent the Chapel view of a C function, there is no reason that the Chapel compiler couldn't process `where` clauses for them.

The situation is different for `export` functions - the interpretation might be that the `where` clause should disable the function from being exported - but the where clause won't be evaluated at the call site.

Should the compiler allow where clauses for:
 * extern functions?
 * export functions?

**Comment by lydia-duncan** [comment]
It seems like it could be possible to encode the information provided by a where clause into the generated .pyx file for Python interoperability.  If we wanted to follow that path, we could take the position that a where clause is ignored with a warning message where it can't be enforced by the Chapel compiler.  We would of course want to think carefully before doing that, since removing that functionality later would be a breaking change

**Comment by bradcray** [comment]
I'm open to supporting where clauses on extern functions based on the arguments above.  

I'd be inclined not to support them on export functions for now, but I could see adding support for them later for external languages that had a where-clause equivalent that we could map to.  (This seems similar to me to supporting default arguments for Python which supports them, but not for C which doesn't).
