### ISSUE TITLE
why is release pidigits slower with --llvm?

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#11807]
Release version of pidigits is slower with --llvm, by about 15%. Why?

https://chapel-lang.org/perf/chapcs/llvm/?startdate=2018/07/05&graphs=pidigitsvariations,submittedpidigitsshootoutbenchmark

But, it's faster on the shootout box:

https://chapel-lang.org/perf/shootout/llvm/?startdate=2018/07/05&graphs=submittedpidigitsshootoutbenchmark

Perhaps this is due to the GMP build rather than anything the Chapel compiler is doing.

**Comment by mppf** [comment]
Seemed to go away around 12/10/2018.

**Comment by ronawho** [comment]
Likely resolved by https://github.com/chapel-lang/chapel/issues/11835

When we dynamically link on chapcs machines we end up getting the libgmp.so that's used to build our local versions of gcc, which has slower perf  -- https://github.com/Cray/chapel-private/issues/87

(Since we stopped throwing `--static` for performance testing in https://github.com/chapel-lang/chapel/pull/12652 we see the worse performance for all chapcs configs, and that private issue tracks resolving that)
