### ISSUE TITLE
prevent promotion during early detection of leader/standalone

### ISSUE THREAD

**Issue by vasslitvinov** [chapel-lang/chapel#11829]
The following happens while compiling this test:
```
test/studies/lsms/shemmy/m-lsms.chpl
```
* Serial these() is resolved on a Block array of Sparse domains.
* The compiler eagerly looks for the corresponding standalone iterator, by resolving a these(tag=standalone) call.
* Block does not provide standalone iterators.
* Sparse DOES provide a standalone iterator over domains.
* The result of resolving that call is the Sparse domain standalone iterator, promoted over the elements of that Block array.

We clearly do not want early detection of parallel iterators to use promotion. Maybe we should disallow promotion of an iterator at all.

Michael's suggestion: assert that all iterators in iterator group are declared in the same scope.
Brad's suggestion: disallow promotion on iterators and see what happens over the test suite.

This task is to modify the compiler to ensure appropriate behavior in such a situation.

**Comment by bradcray** [comment]
It frustrates me that we still rely on the serial iterator in order to resolve a parallel loop when standalone and/or leader-follower iterators are available.  It's not clear what role the resolution of the standalone iterator plays in the case above, and whether it's part of the problem.  If we were to not look at the serial iterator, would it help with this issue?

Put another way, given `forall i in j...` or `[i in j]`, I think we should be:

* trying to resolve j's standalone iterator
* if that fails, trying to resolve j's leader + follower iterator
* if that fails, trying to resolve j's serial iterator for cases that permit it

**Comment by vasslitvinov** [comment]
> we still rely on the serial iterator in order to resolve a parallel loop

The principled way to address this issue is to move forward with "leader/follower 2.0". Specifically, change how parallel iterators are organized. For example, as in #11435.

> If we were to not look at the serial iterator, would it help with this issue?

I do not see how. While seeking, say, the standalone iterator, (currently on master) promotion will still occur in the m-lsms context or other cases. We would still need to disable promotion for `these` standalone search and still decide whether we want promotion for other standalone iterators.

**Comment by bradcray** [comment]
> I do not see how.

OK, I assumed it was relevant since you listed it in your "the following happens" bullets.

**Comment by vasslitvinov** [comment]
m-lsms is working on my branch now.

Disabling of promotions is discussed in #11879 and implemented in #11937.
