### ISSUE TITLE
--div-by-zero-checks does not cause a run-time error

### ISSUE THREAD

**Issue by ty1027** [chapel-lang/chapel#11832]
The following code includes division by zero:
```
var x = 1.0;
var y = x / 0.0;
writeln( y );
```
I expected that the compilation with `--div-by-zero-checks` would cause a run-time error, but I instead obtained the output `inf` (i.e., no effect from the above option). I think it would be very useful if the program halts at run-time (or print a warning message) when the above option is provided...

For comparison, for the following Fortran code,
```
program main
    implicit none
    real x, y

    x = 1.0
    y = x / 0.0
    print *, y
end
```
gfortran-8.2 with no option gives
```
Infinity
```
while `gfortran-8 -ffpe-trap=zero` gives a run-time error as
```
Program received signal SIGFPE: Floating-point exception - erroneous arithmetic operation.
```
Similarly, this python code
```
x = 1.0
y = x /	0.0
print( y )
```
gives
```
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    y = x / 0.0
ZeroDivisionError: float division by zero
```
(But... my concern is that it might be not straightforward to detect division by zero, given that C (or C++) is used as the backend compiler of Chapel? <-- as compared to Fortran etc.)

chapel version: 1.18.0 (installed via Homebrew on OSX10.11)

**Comment by mppf** [comment]
--div-by-zero-checks is currently implemented and working for integers, e.g.:
``` chapel
var a = 1;
var b = 0;
writeln(a / b);
```

Results in
```
error: halt reached - Attempt to divide by zero
```

I think the question you are asking here is if that flag should also check for floating point division by zero. Implementing that is easy (just add a check of chpl_checkDivByZero and the halt into the `/` overload for real division in ChapelBase). The hard part is deciding if that check is reasonable.

One problem that floating point code has is that the numbers are all by nature approximate. In that sense, 0.0 might be something that was the result of rounding. Would you want  `n / 0.001` to count as "division by zero"? Since floating point values are approximate, we'd have to choose some non-zero number `e` for which `n / e` results in a division-by-zero error. Further, the value of `e` can't be much smaller than smallest representable floating point number (in whatever format).

Whether or not you think that infinity is "just another number" depends on what kind of math you are in to. I personally like to think of it that way - see https://en.wikipedia.org/wiki/Riemann_sphere

Nonetheless the IEEE floating point standard defines division by zero as resulting in infinity. This S.O. question asks why it does that:  https://stackoverflow.com/questions/14682005/why-does-division-by-zero-in-ieee754-standard-results-in-infinite-value

Back specifically to the question of what Chapel should do in this case:
 * if you want to check for division by zero, you can do that explicitly in your program, either by checking for something close to 0 before doing the division, or by checking for isfinite after the division.
 * it might be reasonable to add a halt for floating point division by zero, but it probably should have a different flag (e.g. I think the Fortran flag you cited `-ffpe-trap=zero` refers specifically to floating point). We'd have to define what "zero" means in this context though (as I mentioned above). Additionally I wouldn't expect it to be enabled by default, since IEEE floating point can represent the result of division by zero somehow.

**Comment by ty1027** [comment]
[@mppf, Hello, thanks very much for your detailed explanations! I will read the linked pages and related things and then add my opinions further (by modifying this reply).]

**Comment by mppf** [comment]
Sounds good. You should @ -mention me again in a new comment though when you're done writing your comment.

**Comment by mppf** [comment]
There is some discussion on issue #11335 that relates to this issue - see the comments starting here https://github.com/chapel-lang/chapel/issues/11335#issuecomment-448840742

**Comment by damianmoz** [comment]
IEEE754 compliance says that code keeps going even after an exception occurs. You can test for that exception within your C/C++ code using the C routine 'fetestexcept'.   I am not sure what the gfortran interface is. Chapel follows the C/C++ approach because that it uses a C runtime. Going back long before IEEE754, a Fortran program under Unix raised the SIGFPE exception and the '-fpe-trap=list' helps preserve that behaviour in gfortran. If you want traps, and I have NOT done this for a VERY LONG time, you should set the IEEE754 exceptions that you want to trigger a trap, e.g. in C as
```
err = feenableexcept(FE_DIVBYZERO | any other IEEE754 exception that you want to trap);
```
and you should be good to go. Type 'man fenv' to get a list of the exceptions. As this is done at the C level, you need to handle this through Chapel's external C linkage, an explanation for which @mppf is far more skilled at describing that I am. I have no idea if fegetexcept, feenableexcept, and fedisableexcept are available with the LLVM back end although that are only library routines in glibc.

By the way, it is trivial in C to test whether division-by-zero has occurred
```
if (fetestexcept(FE_DIVBYZERO) == FE_DIVBYZERO)
{
    // OOPs - have seen divisiion by zero
    ...
}
```
Again, to access that, you need to write some extern C linkage stuff in Chapel.

**Comment by damianmoz** [comment]
For what it is worth, the IEE754 standard recommends optional exception handling in various forms, including the presubstitution of user-defined default values, and traps (exceptions that change the flow of control in some way) and other exception handling models which interrupt the flow, such as try or catch. The traps and other exception mechanisms are optional.

**Comment by damianmoz** [comment]
Hey @mppf, I think --div-by-zero-checks should stay as integer only. Just my 2c.

**Comment by mppf** [comment]
Thanks @damianmoz for your comments here!

**Comment by bradcray** [comment]
@ty1027 / all: I'm wondering what we should do about this issue.  Based on the discussion so far, I'm inclined to close it as an "ain't broke / won't fix" (where a separate issue could be filed proposing some sort of distinct floating point division by zero check if desired), but I'm open to other suggestions.

**Comment by mppf** [comment]
I think it'd be reasonable to consider this a feature request for #11968 and close this one.

**Comment by ty1027** [comment]
@bradcray @mppf Hi, thank you very much. After posting this question (and suggestion by @mppf), I read some materials about IEEE floating points and was trying to gather more info about the treatment of such errors in other languages, but could not make much progress until now... And yes, I agree that the option will be kept for integer division, and the case for floating points will be considered (if necessary) in different issues. So please go ahead and close this one. Thanks much again :)
