### ISSUE TITLE
Cast for homogeneous tuples

### ISSUE THREAD

**Issue by BryantLam** [chapel-lang/chapel#11845]
Feature request. Does it make sense to allow casting between homogeneous, same-size tuples? It seems handy for casts that would normally be allowed if the types weren't a tuple, but I might be overlooking something.

```chapel
var str = 5: string;
var strs1 = (5, 5): 2*string; // ("5", "5")

var tup = (5, 5);
var strs2 = tup: tup.size*string; // Same as strs1
```
Today, this reports compilation error `illegal cast to non-type`.
`chpl version 1.19.0 pre-release (0001e1ca6a)`

**Comment by mppf** [comment]
The problem here actually isn't a missing cast operator but rather one of operator precedence.

I believe that the following works as you are expecting:


``` chapel
var str = 5: string;
var strs1 = (5, 5): (2*string); // ("5", "5")
writef("%ht\n", str);
writef("%ht\n", strs1);


var tup = (5, 5);
var strs2 = tup: (tup.size*string); // Same as strs1
writef("%ht\n", tup);
writef("%ht\n", strs2);
```

Chapel's language specification indicates that `:` has higher precedence than `*` (see section 10.11). That section includes some discussion for the reason that cast has the precedence it does. It's likely that if we changed the relative precedence of `*` and `:` that there would have other unintuitive results.

I'd like to close the issue with that in mind - please let me know if you disagree.

**Comment by BryantLam** [comment]
Thanks! I didn't consider that operator precedence would cause this, and I do agree that `:` should have higher precedence than `*`.

**Comment by BryantLam** [comment]
Side note: This issue would be a good example for the compiler to say "did you mean?..."
