### ISSUE TITLE
What is the Overhead in Accessing Array Slices

### ISSUE THREAD

**Issue by damianmoz** [chapel-lang/chapel#11923]
Given
        var x :[1..8, 1..5] real;
and
        var col1v = x[1..8, 1];

Then which of my assertions (1..10) are right/wrong please

A)      var col3v = x[1..8, 3];

        1. This makes a copy into a vector
        2. col3v.domain is {1..8} of contiguous elements, stride 1

B)      ref col3r = x[1..8, 3];

        3. This does NOT make a copy
        4. col3v.domain is {1..8} of non-contiguous elements, stride 5

C)      ref row3r = x[3, 1..5]

        5. This does NOT make a copy
        6. row3r.domain is {1..5} of contiguous elements, stride 1

D)      col3v += col1v * 0.5;

        7. No temporaries are created
        8. Is the same as

                [i in 1..8] colv3[i] += col1v[i] * 0.5;

E)      col3c = col3v + col1v * 0.5;

        9.      Temporaries are created
        10.     Is this the same (more or less) as
```chapel
			var t = col3v;

			[i in 1..8] t[i] += col1v[i] * 0.5;
			col3c = t;
```

P.S. Why is there a limit to the size I can drag this window (it seems the limit is 29 lines)
P.P.S. Why does not ```chapel work (maybe it does not format until I submit this)

**Comment by damianmoz** [comment]
Ok. Amateur question time.

Looks like I answered my own PPS. Chapel formatting as per triple back quotes done at submission.

How do I consistently preserve tabs in cut-and-pasted texted. The 2nd and 4th lines in my post both were indented by a hard tab in the original file. But that disappears when I did a cut and paste. For some reason it preserved tabs when it thought I was doing a list.

Also, I cannot count. The maximum window size appears to be 24. Is this a hard limit? How do I grow this.

**Comment by damianmoz** [comment]
My use of the word stride above is bad. By stride I mean the separation in memory is 5 reals or 40 bytes rather than the Chapel meaning of stride.

Chapel's strict definition of the stride is 1.

**Comment by bradcray** [comment]
Hi @damianmoz —

I believe that all of your statements are generally correct apart from (E), which I believe is also temporary-free.  Specifically, I expect (E) to evaluate equivalently to:

```chapel
[i in 1..8] col3c[i] = col3v[i] + col1v[i] * 0.5;
```

or more precisely:

```chapel
forall (c1, c2, c3) in zip(col3c, col3v, col1v) do
  c1 = c2 + c3 * 0.5;
```

Specifically, when Chapel promotes functions or operators, it effectively does so for entire statements using zippered notation, and does not preserve whole-array semantics.  As a classic example, if you wrote something like:

```chapel
A[1..n] = A[2..n+1];
```

in Chapel, it wouldn't have the semantics:

```chapel
tmp = A[2..n+1];
A[1..n] = tmp;
```

but rather:

```chapel
forall (a1, a2) in zip(A[1..n], A[2..n+1]) do
  a1 = a2;
```

which effectively means that statements with overlapping reads and writes result in race conditions and are likely problematic (something that I hope the implementation will warn about someday, but does not yet).

Our philosophy is that the savings in memory and time (due to better cache utilization) generated by assuming zippered interpretations of such statements outweighs the "familiarity" or convenience of adopting whole-array semantics in the language; and that such cases where the RHS and LHS expressions alias in overlapping ways are rare (since, even in stencil codes, you're usually sloshing between two buffers to compute deltas between consecutive iterations).

So, being picky, item (D) would also rewrite as a zippered iteration rather than a random access, but the two should behave equivalently.

I haven't verified these manually, so am describing what I believe we've implemented.  If you find otherwise (or want/need me to be more precise in checking), let us know.

**Comment by bradcray** [comment]
As far as GitHub UI-oriented issues go:

* When you're writing or editing an issue or comment (like this one), you should have "Write" and "Preview" tabs above the text entry box, so if you want to see that your ```chapel blocks are rendering as you'd hope, click "Preview" then click back to "Write" when you're ready to edit more.

* I'm also seeing a maximum text box size when I drag it out bigger, but I don't know how dependent this is on browser / OS / screen size / etc.  This seems unlikely to be within our control.

* I don't have tips about TABs, but sometimes find answers to questions like this by clicking on the "Styling with Markdown is supported" link just below the text entry window.

**Comment by damianmoz** [comment]
Thanks for the information about how Chapel handles those vectors. I am glad that zippering is smart enough to not generate temporary storage for itself.  By the way, if I am actually stupid enough to use
```chapel
    A[1..n] = A[2..n+1];
```
then I need to retire. As long as in my code I do not have to do that zippering because zippering in many cases somewhat destroys the readability of the algorithm.

No need to verfy. I am happy to know what is supposed to happen.

Thanks for the tips about the GitHub UI. FYI, when I click Preview, the chapel code is not rendered. It is however rendered after I hit Comment. I can live with a window size of 24 lines. It might high keep my
replies short and sweet and cut down on the krap. I cannot live without TABs so I need to experiment more. The Styling text says that there is a way to indent 4 spaces but then never says how to achieve it.
Why it wants to throw my tab away is a bit weird.

How do I cut and past the person to whom I am replying. Copying the link and then pasting it simply results in text that looks like 'https://github.com/PERSON. And Preview does nothing with it.
