### ISSUE TITLE
Should arrays and strings sliced by an empty range with out of bounds endpoints behave the same?

### ISSUE THREAD

**Issue by cassella** [chapel-lang/chapel#11927]
### Summary of Problem

Slicing an array with an empty range whose bounds are beyond those of
the array results in an empty array.  Slicing a string with such an
empty range results in a runtime error.  Should they behave the same?

```chapel
var A = [ 1, 2, 3, 4, 5];

writeln(A[2..3]);
writeln(A[3..2]);
writeln(A[13..12]);


var s = "hello";

writeln(s[2..3]);
writeln(s[3..2]);
writeln(s[13..12]);
```

```
fortytwo@magrathea:~/src/chapel (master)$ ./emptyslice -nl 1
2 3


el

$CHPL_HOME/modules/internal/String.chpl:683: error: halt reached - range out of bounds of string
```

(This example slices the string by bytes, but slicing by an empty out-of-bound range of codepoint indices behaves similarly.)

**Associated Future Test(s):**

None yet

### Configuration Information

```
fortytwo@magrathea:~/src/chapel (master)$ chpl --version
chpl version 1.19.0 pre-release (6c2b01a)
Copyright (c) 2004-2018, Cray Inc.  (See LICENSE file for more details)
fortytwo@magrathea:~/src/chapel (master)$ printchplenv --anonymize
CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: gnu
CHPL_TARGET_MACHINE: x86_64
CHPL_TARGET_ARCH: native *
CHPL_LOCALE_MODEL: flat
CHPL_COMM: gasnet *
  CHPL_COMM_SUBSTRATE: udp
  CHPL_GASNET_SEGMENT: everything
CHPL_TASKS: qthreads
CHPL_LAUNCHER: amudprun
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: intrinsics
  CHPL_NETWORK_ATOMICS: none
CHPL_GMP: gmp
CHPL_HWLOC: hwloc
CHPL_REGEXP: re2
CHPL_AUX_FILESYS: none
fortytwo@magrathea:~/src/chapel (master)$ gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
```

**Comment by mppf** [comment]
>  Should they behave the same?

I think so

**Comment by bradcray** [comment]
Same here.

**Comment by bradcray** [comment]
@dmk42 : Any thoughts on this one?

**Comment by dmk42** [comment]
It seems to me that the situation is inconsistent no matter how I look at it.  If I add the following line to the program above
```chapel
writeln(A[4..7]);
```
I get a fatal error message.  Array slicing aborts if the slice is partially out of bounds, but returns an empty range if it is completely out of bounds.

String slicing always aborts if at least part of the slice is out of bounds, which is consistent within itself but inconsistent with array slicing.

I think both array and string slicing should either
1. always return as much of the sliced object as is in bounds (including empty), or
2. always halt if part of the range is out of bounds.

I'm fine with either way.  Option (1) appeals to me slightly more, but that's just a gut feeling.

**Comment by bradcray** [comment]
Chapel defines array slices like `A[lo..hi]` as "access all elements from A described by the range `lo..hi`.  For a range like `4..7`, this means the elements at indices 4, 5, 6, and 7.  For a range like `7..4`, this means "no items" because ranges in which the low bound exceeds the high bound are empty / contain no elements.  So `A[7..4]` says "access all of the following elements: (none)" and it shouldn't matter that the integers used to define the degenerate range aren't within bounds for the array because they're never used to access the array.

By analogy, an array defined `var A: [7..4] real;` is an empty array and does not store elements for any index values even though the integer indices `7` and `4` happen to be named in its degenerate domain.

**Comment by dmk42** [comment]
OK, that means in this case `A[4..7]` should return elements 4 and 5 (my option 1) rather than halting as it does now.

**Comment by bradcray** [comment]
Based on the definition I gave, I'm not understanding your argument.  If I access `A[6]` or `A[7]`, I'll get an OOB error since A has no element corresponding to indices 6 or 7.  If `A[4..7]` means "access elements 4, 5, 6, and 7 of A" (the indices defined by the range 4..7) then it seems that it should give an out-of-bounds message as well since elements 6 and 7 are out of bounds.

Trying a different way, the algorithm is intended to be:
* determine what indices the range describes, if any (where an empty range describes no indices)
* access the array at all of those indices if legal / in-bounds; give an error if they are not

**Comment by dmk42** [comment]
Ah, that makes sense now.  Thanks.
