### ISSUE TITLE
spike: throws and memory management

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#11946]
The task in this spike is to come up with a starting point plan for how `throw` and `catch` work with `owned` errors.

This is related to issues #9376 #10221 and #9698.

**Comment by mppf** [comment]
Here I can see two overall strategies:
 1. Enable one to`throw` a record or an integer or anything else. Then throwing an `owned Error` would also work.
 2. Change the requirement on `throw` from throwing an `unmanaged Error` to throwing an `owned Error`.  Then one would presumably write `throw new owned Error` rather than `throw new unamnaged Error` or `throw new Error`.
2a. In addition, change `throw new Error` to mean `throw new owned Error` by default.
2b. Create a syntactic shortcut for `throw new owned Error` e.g. `throw Error`.

The kind of code no be enabled by `Error` being `owned Error` is described in issue #10221:

A) Wrapping an error in another error:
``` chapel
try {
  ...
} catch e: UserError {
  throw new LoggerError(e); // current implementation deletes e at end of this block!
}
```
B) Double-throw results in double free
``` chapel
// Double throw on single object resulting in double free.
try {
  var ex = new Error();
  forall i in 0..1 {
    throw ex;
  }
}
catch e { ... }
```
C) Use after free of thrown error
``` chapel
// Use after free.
var ex = new Error();
try { throw ex; }
catch e { ... }
// Use ex in some way after it was deleted in catch block.
```

**Comment by lydia-duncan** [comment]
After the meeting today I just wanted to express my hesitancy about any explicit memory management in the catch block declaration.  There's obviously some different actions to take depending on if you caught a `shared` or `owned` error and were rethrowing it, but I think those are details the user shouldn't have to worry about.  For me, the majority of responses in catch blocks are going to be unified along the type of Error returned (SysError, MySpecialMessageError, etc) so any potentially for accidentally missing some because they happened to be `unmanaged` instead of `owned` just seems like a source of frustration.

**Comment by mppf** [comment]
@lydia-duncan - are you saying that we should only have catch blocks that present to the user `owned` errors? Because that's what I'm trying to get to, if it wasn't clear.

**Comment by lydia-duncan** [comment]
Yeah, it sounded like you were going to adjust the catch block to take in an owned and if the user tries to throw something that isn't owned, you would generate a warning and replace it with an owned.  I just wanted to make sure my objection got logged if we changed our mind or something

**Comment by mppf** [comment]
Not really an objection then, more like reasoned agreement? :)

**Comment by mppf** [comment]
As a starting point, the plan is to make the catch blocks  e.g. `catch e: UserError` have owned type (e has type owned UserError within the block) and leave throws alone (users are expected to write throw new owned UserError for now).

**Comment by mppf** [comment]
> So are we going to do a warning on different throws, or is that a later effort?

I'm not sure.

`throw new SomeError` works now and seems relatively harmless. But it would be reasonable to warn in this case, especially for `throw myBorrowedClass`. I think I'm planning to leave that part alone for the moment.

**Comment by lydia-duncan** [comment]
`throw new SomeError` working seems sufficient for, but I would like to have an issue open to track that we don't have a warning for the user when they throw something that isn't owned, in case someone actually runs into it or in case we forget.  I would also lean towards adding it if it is super trivial just because I don't like how many dark corners we have without warnings

**Comment by mppf** [comment]
#12081 tracks the desire for the warning
