### ISSUE TITLE
Spike: Investigate solution for first-class function memory leaks

### ISSUE THREAD

**Issue by benharsh** [chapel-lang/chapel#12071]
This spike involves investigating the cause of first-class function leaks. Can first-class functions be owned classes? If not, what are their lifetimes?

**Comment by bradcray** [comment]
If they can't be owned, it seems like they could definitely be shared, with some performance penalty?  And maybe at this point since fcf's are somewhat of a prototype rather than a first-class feature, having them be leak-free would be worth the overhead that having them be shared might incur?  Though owned would be best if it can be made to work...

**Comment by bradcray** [comment]
Thinking about my note above slightly more over lunch:  I also don't mean to imply (in this comment, in offline discussions) that we couldn't leave it unmanaged if there's an obvious place to put the delete.  My assumption was that perhaps there wasn't or we'd have done it already, but that may be wrong and giving us too much credit.

**Comment by bradcray** [comment]
Not directly related to the leaks, but somewhat related to the owned vs. shared vs. unmanaged conversation here...   I was just trying to write some code that stores first-class functions in an array and it worked well as module-scope code, but broke down when I pushed it into an object due to lifetime issues:

```chapel
record R {
  var fns: [1..2, 1..2] func(C, C, shared C);

  proc init(fn1, fn2, fn3, fn4) {
    fns[1, 1] = fn1;  // error here "Setting borrowed formal illegal without specifying formal lifetime constraint"
    fns[1, 2] = fn2;
    fns[2, 1] = fn3;
   fns[2, 2] = fn4;
  }
}
```

This was interesting because I don't think of f.c.f.'s as being classes (and suspect most users won't / shouldn't either), yet this error essentially reveals that they are.

**Comment by bradcray** [comment]
Tagging @mppf on this because of my last comment and his work on lifetime checking.  After filing this, I was able to use the lifetime annotations to assert that my objet would not outlive the function symbols, but again, it doesn't feel like I should need to be thinking of functions as classes as an end-user(?).

**Comment by mppf** [comment]
Why are FCFs currently implemented as classes? Is it fundamental or an implementation oddity?

Well, the first thing to remember is that our FCFs were designed to be able to capture values or references (one writes these captures as uses of outer variables). But an FCF can store a reference to a function-local variable, and then be returned, which is bad news. Since we hadn't decided if this was going to be legal in the language anyway, and the implementation of it was interfering with other key efforts, I disabled it in PR #4794 (see also #8350 and #8351 which track the open question of if FCFs should be able to capture variables).

The second thing to know is that our FCFs were designed to allow run-time binding, so that all of the FCFs with a given signature can be stored in a variable with the same type. When combined with variable capture, that makes FCFs inherently fairly class-like - or at least, a class hierarchy is an appealing way to implement them. Compare with the scenario in which capturing variables is not legal at all in a FCF - then we could simply store function pointers and there isn't really a need for anything class-like. Of course, the compiler could one day implement FCFs as something class-like that isn't actually a class. But if they are class-like we might want borrow checking on them, right? Or, put another way, if an FCF could store a reference to an outer variable, or a class pointer to a outer `owned` class variable instance, don't we need the lifetime checker to track the lifetimes of them?

I would personally prefer that the next thing we do on FCFs is to directly resolve the language design question about capturing outer variables. If resolving the memory leak needs to change user programs, I'd rather we make that change at the same time as resolving other FCF language design problems. (can you capture variables? Do we like the syntax we have now?).

I'm supportive of a quick look to see if the leak has an "easy" solution, which is what I understand this spike to be doing. However I think it's really important to keep the current effort limited to that, at least until we decide that it's time for a larger effort on FCFs.

**Comment by benharsh** [comment]
I have a branch that can eliminate first-class function leaks by using ``shared``, but encounters 4 failures in full testing:

- extern/fnPtrs/passBadFnsToCChapel
- functions/jturner/fun_call_mismatch
- functions/jturner/lambda_call_mismatch
- functions/jturner/return_first_class_function

The first three involve adjusting our error messages to remove the "_shared" part of the FCF's type string. The last one relates to user-specified return types, and I'm not sure what would need to be fixed there.

I'm going to close this for now as it satisfies the "quick look" nature of the issue. I think it's worth having a discussion on how much more work we want to put into an FCF implementation that may not satisfy our long-term vision.
