### ISSUE TITLE
Compiler performance regression from #11880

### ISSUE THREAD

**Issue by ronawho** [chapel-lang/chapel#12141]
There was a non-trivial regression in terms of the number of statements we emit and compiler performance from "Allow underscores in the number when casting from string to integral" (#11880):

Here's some graphs ([emitted code size](https://chapel-lang.org/perf/chapcs/?startdate=2018/11/23&enddate=2018/12/30&graphs=jacobiemittedcodesize), [compilation time](https://chapel-lang.org/perf/chap01/?startdate=2018/11/23&enddate=2018/12/30&suite=allcompilationpasstimings)): 

![image](https://user-images.githubusercontent.com/1588337/51715685-a60c1d00-1fee-11e9-8e39-126df20fdd67.png)

![image](https://user-images.githubusercontent.com/1588337/51715687-aa383a80-1fee-11e9-9201-ff4c48e26891.png)

**Comment by daviditen** [comment]
Wow, that's surprising.  I'll look into it.

**Comment by daviditen** [comment]
PR #11880 uses a few String methods in the string->int cast function that were otherwise unused for the jacobi test.  Since jacobi has an integer config var, it potentially calls the cast function.  Short of removing the functionality from #11880 or pushing it down into the runtime I think there's not much to do about this bump in code size.
