### ISSUE TITLE
Multi-locale interop: Figure out how to reuse on clause function numbering for exported functions communication

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#12143]
The on clause implementation already does a transformation to functions that are called via cross-node communication.  Determine the steps necessary to extend or transform this logic so it can also be used on the exported functions in a generated library.

**Comment by lydia-duncan** [comment]
The strategy I was originally thinking of may not be relevant. This issue is empty enough that I could still adapt it to the correct strategy, but close it for now until I have that information

**Comment by lydia-duncan** [comment]
The hope is that we can reuse the on statement numbering strategy instead of starting from scratch, though there are some adjustments that will need to be made (i.e. applying it to exported functions, including exit with maybe some special adjustment, etc)

**Comment by lydia-duncan** [comment]
Updated the description based on the work that we expect to do

**Comment by ronawho** [comment]
In terms of on-clauses in general -- there's actually not a ton that we can reuse because even our most basic on-clauses still rely on being able to do RDMA and we don't serialize everything. We also have relatively small landing pads in the runtime for incoming on-clauses so if our argument bundlers are larger than a few hundred bytes we'll still need RDMA to get the rest. For true RPC calls we need to be able to serialize and deserialize everything without relying on RDMA (and we'll want some way of returning values)

For specifically re-using the on-clause numbering as a way to translate function names to integers.  This is actually really simple, so you could reuse some of the existing machinery or just write your own. 

Today we have a ftableVec and ftableMap. When we have a new entry for the function table we just add it to both place and the map stores the correlation between the function and a unique integer. I actually don't think the vector is needed and just a map would suffice, but that's what we have today. We could either directly use the ftable data structures or we could create a new one for exported procs, the implementation is really simple so I don't know if you gain anything by re-using the existing ftable{Vec,Map}
