### ISSUE TITLE
Design: single-node (login) program calls into multi-locale Chapel library

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#12155]
Here's Brad's sketch of a strawman approach to supporting multi-locale libraries / interop:

As our ability to export Chapel libraries that can be called from Python/C(/Fortran?) improves, we need to flesh out our story for having a foreign language program interoperate with a Chapel library running across multiple locales.  We should ultimately handle two cases: (a) where the foreign language program is running on the same compute node as locale 0; and (b) where it is running on a login node and the Chapel program is running on distinct compute nodes.  For this discussion, I'll focus on the latter since I think it's the more important, interesting, and challenging case.  I'll come back to the former case at the very end.

In the recent past, we've talked about having a compilation mode in which the compiler generates client/server stubs for certain routines to provide an RPC-like mechanism in which a Chapel-generated program running on the login node communicates with the multi-locale Chapel program running on the compute nodes in order to have them do its bidding.  The following description digs into the design of how that could be made to work in more detail.

The main observation is that there is a strong analogy between this scenario and current multi-locale execution.  Specifically, to execute an on-clause from locale 0 onto locale 1, locale 0 knows how to bundle up its arguments with a function ID and send them across the wire, both locales have a common mapping of function IDs to function pointers permitting them to talk about functions' identities in a consistent way, and locale 1 knows how to listen for such requests, unpack the arguments, and call the function.  In this multi-locale library scenario, we need to be able to do a similar thing, except by having a program running on the login node bundle the arguments up, make an "active message"-like call to locale 0.  Meanwhile, locale 0 would listen for such requests, unpack the arguments, and make the call.  Note that, in this description, I'm imagining the program running on the login node not to be the end-user's foreign language program, but a Chapel compiler-generated binary similar to the launcher program we have today (more on that in a few paragraphs).

Some major differences compared to our current active message support that I can see are:

(1) the login node and locale 0 will almost certainly need to talk over some connection other than the standard Chapel comm layer since (a) we don't want the login node to be part of the overall Locales[] communication group, and (b) locale 0 will already belong to the main Locales[] communication group (and most of our comm layers probably can't have multiple distinct comm groups running simultaneously).  This is where we've typically talked about using ZMQ, but we could also use another technology like sockets if there were benefits to doing so (e.g., portability, standardness, etc.).  In any case, we'd need the ability for the login node to make active message-style requests to locale 0 and for locale 0 to listen for those requests and service them, similar to how it would listen to on-clause requests from any other locale, simply on a distinct port / channel / message queue.

[Note that it's probably reasonable, at least as a starting point, to have locale 0 only handle one such request like this at a time; ultimately, it would only need to handle multiple simultaneous requests if/when we permit the external language to call multiple exported Chapel routines simultaneously.  Also note that we _may_ ultimately want to support the ability to make active message calls in the reverse direction (locale 0 requesting them of the login node) if we thought it was important for the Chapel program to call `extern` routines back on the login node rather than simply on its own compute node (as we do today)].

(2) in bundling up the arguments to the active message, we may want/need to use deeper copies than we typically do for on-clauses given that the login node isn't in the shared namespace (address space) of the Chapel program running on the compute nodes, so wouldn't necessarily support RDMA efficiently or well.  (in saying this, I'm imagining we wouldn't want to go so far as to support gets/puts between locale 0 and the login node, at least in the short-term... but maybe I'm wrong about that).

My hope is that by treating the serving of these exported library calls in a manner similar to active messages, we can re-use or repurpose existing code in the compiler (and runtime?) to enable multi-locale interoperability rather than creating everything from scratch.  E.g., I'm hoping we can reuse compiler code that creates function IDs for on-clauses to also generate them for these exported routines (noting that there will be two disjoint sets of function IDs: those used between compute nodes and those used between the login node and locale 0).

Another design question relates to getting the multi-locale program itself up and running.  Normally we do this with a chapel launcher, which is a reasonably passive C program running on the login node waiting for the compute node to finish.  In this multi-locale library scenario, I think that the launcher program essentially becomes the stub that communicates with locale 0 in the active message descriptions above, and so has a much more active role during the program's execution than for a typical standalone Chapel program.  Specifically, I imagine that:

* the `--library-python` (or C or Fortran) compilation will generate the launcher executable as the main `.a` or `.so` library against which the external language program is linked;
* the multi-locale Chapel program will be generated using a `_real` executable, as in typical multi-locale compilations; its main difference is that rather than running `main()` on locale 0 once it's launched, locale 0 will start listening at its channel back to the login node for active message-style requests that indicate a call the exported routines.
* the initialization of the library will result in the launch of the `_real` program on all of the compute nodes, using the typical launching mechanisms, but where the key arguments will presumably have to be supplied as arguments to the library initialization function rather than on the command-line (since the command-line is essentially now the one running the foreign language program).  Effectively the library initialization function replaces the `main()` routine in the launcher as it exists today.
* the teardown/exit of the library will presumably do something akin to requesting that locale 0 execute `exit()` (so may be able to be implemented simply by exporting `exit()`).

Recapping the above: When compiling a Chapel `--library-python` program in `--no-local` mode...
* the "launcher binary" will be a `.a` or `.so` intended to be linked into the Python program
* a `_real` binary will also be created.
* initializing the library will result in launching the `_real` binary across all of the compute nodes, and running its (C) `main()` on each locale.  This will do the normal Chapel setup and initialization, but rather than  having locale 0 call (Chapel) `main()`, it will establish a channel with the login node that can be used to service active message requests and then go into a passive "listen at that channel" mode
* when the foreign language program calls an exported Chapel routine, it makes the call into the launcher binary, similar to what happens for `--local --library-python` compilations today.  However, rather than running the procedure directly there on the login node, the launcher program bundles its function ID and arguments up into an active message request which it sends off to locale 0 via ZMQ, sockets, or some other mechanism; having made the request, it waits for locale 0 to let it know that the routine has ended.
* meanwhile, locale 0 has been listening for such messages, and upon receiving one, unpacks the arguments, decodes the function ID, and calls the function, similar to what would happen for a normal active message request (albeit potentially with arguments copied more deeply (?)).
* this function implements the Chapel code in the normal way which will do arbitrary Chapel stuff, potentially involving other Chapel locales in the usual way.  I.e., once the call is made, there shouldn't be any special code required to execute it on the compute nodes... all of the wiring should be in getting the call made, and returning from it...
* the routine will eventually return, at which point locale 0 communicates back to the login node the fact that the routine has completed, along with any returned values.
* this can happen multiple times until eventually the program exits or the library's cleanup function is called, at which point the login node communicates to locale 0 to call `exit()`.  Locale 0 does this and the multi-locale program tears itself down as usual.

Possible extensions:
* permit the login node to make multiple calls to exported routines simultaneously? (only useful if the foreign language program itself is parallel and can make multiple non-blocking calls to exported routines at the same time.  In any case, we shouldn't feel the need to support this in the initial version, I think).
* permit locale 0 to make extern calls that execute back on the login node rather than locally on its own compute node?  (this will likely require language changes as well, I think, to distinguish between the two ways of calling an extern?)

For the case when the external language program happens to be running on locale 0, we could potentially skip the login<->locale 0 active messages part of this proposal, but it leaves questions about how to launch the library in multi-locale mode.  It would also require the locale 0 binary to be generated differently than it is today (or in the above proposal), since it would need to support being linked into the foreign program and handling calls to the exported routines.  My current thinking is to handle this case as just a degenerate form of the above in which the launcher program and locale 0 instance happen to be running on the same node rather than adding special support for it (the reason being that it supports the more general, and arguably important, case in which they're different nodes while avoiding having to create different / specialized code, at least until there's a compelling need to do so).

**Comment by lydia-duncan** [comment]
Note that Brad has significantly updated the description (with my permission).  This update would be good to review prior to our meeting

**Comment by gbtitus** [comment]
> Another design question relates to getting the multi-locale program itself up and running. Normally we do this with a chapel launcher, which is a reasonably passive C program running on the login node waiting for the compute node to finish.  ...

This is conceptually true, but what the Chapel launcher actually waits for is not the compute node(s) themselves, but rather some other, underlying launcher provided either by the system or Chapel's third-party GASNet package.  It's this latter launcher which directly waits for the compute node(s).  On Cray X* systems the underlying launcher is the system-provided `srun` or `aprun` command, while on conventional clusters where Chapel uses GASNet it's one of the GASNet launchers which in turn uses system capabilities like `ssh` or `mpirun` underneath.  I mention this not to nit-pick but because it has implications for this situation:

> For the case when the external language program happens to be running on locale 0, we could potentially skip the login<->locale 0 active messages part of this proposal, but it leaves questions about how to launch the library in multi-locale mode. ...

At least for the Cray X* case I don't believe we can run the system launcher on the compute nodes.  We may also not be able to run it from a compute node assigned by an `mpirun` initiated by GASNet, when we're using that sort of configuration.  (I've seen `mpirun` jobs refuse to start recursive `mpirun` jobs while investigating comm=ofi full testing failures.)  And at least on Cray X* systems running the system launcher is a necessity, because if nothing else that is (indirectly) how Cray network resources get apportioned to the job.  So when designing how this aspect of it will work I think we ought to assume that some originating launch will have occurred on the login node, and that at least the bootstrapping of communication among the program instances on compute nodes will make use of capabilities set up as part of this launch.

**Comment by lydia-duncan** [comment]
> So when designing how this aspect of it will work I think we ought to assume that some originating launch will have occurred on the login node

It sounds like for a compute node to compute node communication, the program would have to explicitly launch both of them, instead of getting launched and launching the other?

**Comment by lydia-duncan** [comment]
> I suspect trying to get the entire cross-product of workload managers and platform types correct right out of the box is intractable

My hope is that we would be able to call into our launcher code in some way, so that if a normal Chapel program would need to be updated for a platform, a program using a Chapel library would benefit from that improvement

**Comment by bradcray** [comment]
> > For the case when the external language program happens to be running on locale 0...

> At least for the Cray X* case...

Personally, I'm only worried about this case for non Cray X* systems (e.g., I have a cluster of workstations and want to use one of them both for my interactive job and as locale 0 because it's a small cluster).  And more generally, I'm not interested in supporting this mode on any system that doesn't permit it; I just want to have a story for supporting it on those that do.

**Comment by gbtitus** [comment]
> My hope is that we would be able to call into our launcher code in some way, so that if a normal Chapel program would need to be updated for a platform, a program using a Chapel library would benefit from that improvement

I was more concerned here about the case where the main program isn't Chapel and the Chapel library initialization code finds itself running on a compute node, with no Chapel launcher having been involved at all.  I don't think we can solve that particular situation by invoking Chapel launcher code from the library init, because the Chapel launcher is really just a thin wrapper over the system launcher(s).

**Comment by bradcray** [comment]
I've changed this issue's title (again) to try and hone in on the main use case that I'm interested in tackling in this issue.  Below, I've tried to capture my characterizations of offline conversations with others (in my own words) and my current thoughts on them.  If I've mischaracterized, mis-summarized, or misunderstood the arguments, please correct me.

> "What about the case of an SPMD foreign program (MPI, say) wanting to interoperate with a multilocale Chapel library such that there's a 1:1 relationship between its ranks and Chapel's locales?"

I think this is definitely an interesting and valuable use case for interoperability, but it feels sufficiently different to me that I'd like to tackle it in a separate issue (and it's part of why I tried to dial this issue's title in better just above).  Specifically, for this case, I tend to imagine that we'd have some sort of `--library-spmd` flag that would tell the Chapel program that rather than owning `main()` and being launched by one of our launchers, the library initialization routine would be called in an SPMD manner, at which point the Chapel locales would need to discover each other and initialize themselves in a peer-to-peer fashion rather than a "Chapel owns the launcher" fashion.  This seems like an important pattern, yet sufficiently different that I don't think this effort should need to worry about it, or is likely to be impacted by it.

> "What about the case when a user's compute node wants to call out to a Python (say) library routine and have it run on that locale's compute node rather than back on the login node?"

This is the distinction I was trying to make in the issue text about whether an extern function call would be able to run on the compute node vs. the login node.  My current thinking is that extern functions should always run on the compute node (for simplicity), and that communication back to the login node should always be done through returning from the exported functions, at least for starters.  Under that model, calling out to a Python routine seems similar to how we currently call out to C to get at functions like `sin()`, simply using a different language (e.g., in the past we've talked about having `extern` declarations take the foreign language implementing the extern as an optional keyword/decorator where the default (and only option today) is "C").  Such a capability seems valuable whether we're running a single or multi-locale Chapel program in standalone mode or as a library, so seems independent to this issue to me.  Put another way, if we had the ability to have a single-locale standalone program call out to Python today, I think we'd have the ability for this multi-locale library scenario to do the same thing on each compute node.

> "What if I need to pass a more complicated type from Python to Chapel than I'm able to do today?" e.g., a DAG or graph of classes which require pointer swizzling to avoid infinite loops or redundant transmission of data?"

This also seems somewhat independent of this issue in that a single-locale Python->Chapel interoperability scenario would presumably want to do the same thing.  Today we only support passing a few types from Python to Chapel, but we should definitely continue to expand that set of types over time.  In the approach given in the issue text, if we could pass a type from Python to Chapel in single-locale mode, we could pass it to the chpl-generated launcher client stub running on the login node which would get things rolling.

The part that isn't independent of this issue is the need to (presumably) deep-copy the data type from the Chapel client stub to locale 0.  I.e., it's likely that the simple "pass from Python to Chapel" capability described in the previous paragraph would result in the two programs referring to the same shared variable(s) since they're running in the same process / address space; but to get the variable(s) to the multilocale program, we'd presumably need to deep-copy it/them across the wire (this was item (2) in the issue text above).  Michael proposed that rather than rolling our own deep-copy / serialization mechanism, we make use of an existing technology like protobuf or pickl.  That seems reasonable to me and reflects what others have suggested recently along the lines of "if Chapel could speak protobuf, it'd help it play well with other languages."  Lydia created issue #12201 to dig into this as a spike (though maybe others already have expertise here that would help her).

That said, I also believe that for the main use cases we're interested in for the near-term it seems likely to me that we could get by with only passing relatively simple types and opaque handles between the client and server and have any more complex data transfer needs go through the file system (since big data structures that are worthy of multi-locale execution seem unlikely to fit onto the login node anyway).  Moreover, I think that swapping out a simple, primitive type serialization capability for something richer can be done later on if/when necessary without throwing away the overall framework or wasting too much work.

[On the general topic of "deep copies to locale 0", I've been thinking that we should perhaps only support `export`s of routines whose intents have [deep] copy-in / copy-out semantics when compiling in `--no-local --library-*` mode to avoid seeming mismatches in behavior or surprises.  Trying to export other cases should arguably result in a compiler error ("Chapel can't pass type X by intent Y to a multi-locale library")].

> "Maybe the Python program running on the login node should speak directly to the multi-locale Chapel program running on locale 0?"

While this might be slightly more efficient, my intuition is that doing so would require our compiler to be able to spit out client code in multiple languages in order to keep the client-side user interface simple; whereas if we can interoperate from a given language to Chapel in single-locale mode (something we want anyway) and can establish this client-server relationship between two pieces of `chpl`-generated code (which doesn't seem so bad), then it seems like we can have the language in question interoperate with a multi-locale Chapel program through composition of these two technologies and avoid teaching the compiler how to make each language serve as an RPC client for the multi-locale Chapel program.

The main downsides to this approach that I can see are (a) the potential loss of efficiency by taking "two hops".  But one of them should just be a shallow inter-language hop, so not likely to add much overhead compared to hopping across the network; and (b) an argument that maybe there are only ~2-to-4 login-node languages that we'd care about supporting in this mode anyway, so the arity that we're saving may not be so high (?).  That said, even doing 1 implementation rather than 2 seems like a savings to me.

> "Maybe `chpl` should code-generate the client stub running on the login node and the server stub running on locale 0 using Python rather than C/LLVM in order to make use of Python's support for packing arbitrary data into buffers and shipping them across wires.  Then the Python program on locale 0 can make an interoperability call into locale 0 of the Chapel program to service the call."

This seems pretty different from today in that the Chapel compiler doesn't have any experience generating Python and I'm disinclined to put Python on the critical path running on a compute node.  I'm also disinclined to do this given my assumptions that (a) only supporting simple data types seems likely to suffice for the near-term and (b) if it doesn't, teaching Chapel to speak something like protobuf / pickl seems valuable independent of this effort.

**Comment by mppf** [comment]
> > "Maybe the Python program running on the login node should speak directly to the multi-locale Chapel program running on locale 0?"

> The main downsides to this approach that I can see are (a) the potential loss of efficiency by taking "two hops". But one of them should just be a shallow inter-language hop, so not likely to add much overhead compared to hopping across the network; and (b) an argument that maybe there are only ~2-to-4 login-node languages that we'd care about supporting in this mode anyway, so the arity that we're saving may not be so high (?). That said, even doing 1 implementation rather than 2 seems like a savings to me.

If we combined this idea with the strategy of using protobufs/pickle/related technologies, we can use a library that somebody else has already written that can do the multi-language interoperability (and generate RPC stubs for various languages). Then the 1 implementation we'd need to do is to extend that library to support Chapel (which arguably we'll want to do anyway).

> I'm disinclined to put Python on the critical path running on a compute node. 

That's an interesting thought. I wonder to what degree it's important in the context of programs already using Python-Chapel interop.
