### ISSUE TITLE
Design - rename the _void value and its type

### ISSUE THREAD

**Issue by daviditen** [chapel-lang/chapel#12208]
The global "void value" is currently named `_void` and has type `void`.  The type is currently the same as the type of a function with no return statements or a blank return statement.  An early pass in the compiler turns empty return statements into `return _void;`.

"Void values" and empty returns are not interchangeable concepts, and the compiler needs to treat them differently. For example, a call to a function that doesn't return cannot be assigned to a variable, but a call to a function that returns a "void value" can be.

A function with an empty return cannot have any non-empty returns, but a function that returns a "void value" can return other types in other paths that are param folded.  Issue #9152 runs into this.

I think we need to separate these concepts by giving "void values" a new and distinct name and type.  I think Python's `None` and `NoneType` would be a good fit for this concept, but I'd prefer to lowercase the leading 'N's giving `none` and `noneType`.

This issue is to try to reach consensus on this renaming and separation of concepts.

**Comment by bradcray** [comment]
Some quick reactions:

* I think it makes sense to rename the `_void` value no matter what since the leading underscore has always suggested to me that it's just a placeholder name.  I've never had any great inspiration here as to what the final name should be, though.  If `none` doesn't seem inconsistent with how it's used in other languages, I'm open to that.  A quick look suggests that Python's `none` might be more like our `nil`, though?  (in which case `noneType` would be more like our `_nilType`?).  But I'll defer to the Python programmers here if they think it's a good match.

* It seems a little unfortunate to have to rename the `void` type given that I suspect that it's currently used far more often for the "param fold this thing out" case than it is for the "I don't return anything" case (i.e., I'm guessing people don't assert that in their code as often?), so more code would need to change if I that's correct.  But it may not be.

* That said, our use of `void` is also arguably also inconsistent with C's use of it.  Though it is the way I always wish C would behave.  :)

* Part of me is tempted to say that procedures that don't return anything would simply not declare a return type, but the downside of that is that it makes it impossible to distinguish from the function header between "I don't return anything" and "The compiler should figure out what I return"?  

* That leads me to wonder whether the non-type-inferred "I don't return anything" case should/could simply be `proc foo(): { ... }`.  I.e., "Here's my return type.  [nothing... I have no return type]".  For a case like this it looks easy to parse, but I could imagine if there were where-clauses, lifetime constraints and return intents, then things might get a bit more ambiguous (?).  Or maybe not... I guess each of those things starts with a keyword...

* As proof (as if it were needed) that I'm not a PL guy, some Googling has led me to articles on [unit types]([url](https://en.wikipedia.org/wiki/Unit_type)) and [bottom types](https://en.wikipedia.org/wiki/Bottom_type) where the former is like our `void`/`_void` type and value and the latter is closer to "I return nothing".  Looking for some inspiration there, we could use `nothing` as the bottom type: `proc foo(): nothing { return; }` ("procedure foo returns nothing").

* We could also potentially use `()` (a 0-tuple) as the value for the unit type, as lots of other languages that we like and respect do:  `proc bar(): void { return (); }`.  The main downside to this that I can think of is that I believe we want 0-tuples in other contexts (like varargs functions) and may want to distinguish between 0-tuples of ints and 0-tuples of reals, so may not want to bring empty tuples into this context (?).  It also seems a little odd to me to lean on tuples to provide this singleton value.

* I sometimes whimsically wonder whether we could have `void` be both a type and a value, but that always seems a bit terrifying and too context-sensitive.

* I suspect `_void` is not used as often as `void` is and so might be tempted to call `_void` `voidValue` (as opposed to making the value `void` and the type `voidType`.

Having typed all this, I think I'd vote for:

```chapel
proc foo(): { ...return;...}  // I return no value
proc bar(): void { ...return nothing; ...} // I return an empty value
```
if it were possible (not syntactically ambiguous), or:

```chapel
proc foo(): nothing { ...return;...}  // I return no value
proc bar(): void { ...return voidValue;...}  // I return an empty value
```

if it were.

**Comment by ben-albrecht** [comment]
> If `none` doesn't seem inconsistent with how it's used in other languages, I'm open to that. A quick look suggests that Python's none might be more like our `nil`, though? (in which case `noneType` would be more like our `_nilType`?). But I'll defer to the Python programmers here if they think it's a good match.

Chapel's `_void` could be considered similar to Python's `NoneType` (the result of `type(None)`). 

This can be illustrated in #12027, for example, where we will port python's function:

```python
def choice(a, size=None, replace=True, p=None)
```

to Chapel as:

```chpl
proc choice(arr: [], size:?sizeType=_void, replace=true, prob:?probType=_void)
```

**Comment by daviditen** [comment]
> It seems a little unfortunate to have to rename the void type given that I suspect that it's currently used far more often for the "param fold this thing out" case than it is for the "I don't return anything" case (i.e., I'm guessing people don't assert that in their code as often?), so more code would need to change if I that's correct. But it may not be.

I think it's actually the other way.  My searches find that it's used significantly more often (~3x) throughout the tests and modules in the "I don't return anything" way.

> That said, our use of void is also arguably also inconsistent with C's use of it. Though it is the way I always wish C would behave. :)

I'm not certain which use of `void` you consider to be inconsistent with C.  The "I return nothing" `void` seems pretty consistent.  The "param fold me away" `void` doesn't really have an equivalent.

I don't like the empty parenthesis means `void` idea because I think we'll want it to mean 0-tuple, and then we'll be back in a situation with two different things named the same thing and needing to try to disambiguate based on context.

I was hoping to avoid changing the "I don't return anything" `void` because it has been around for so much longer than the "void value" `void` and is currently more widely used.  Plus the "void value" is named with a placeholder as you pointed out, so seems more OK to change.

**Comment by bradcray** [comment]
> Chapel's `_void` could be considered similar to Python's `None`.

I'm definitely happy to defer to others here if the link seems right (I'm obviously not the right person to ask about Python behavior.  :) ).  I agree that in Ben's example the analogy seems stronger than whatever I found on the web that made it seem more `nil`-like to me.  

> I think it's actually the other way. My searches find that it's used significantly more often (~3x) throughout the tests and modules in the "I don't return anything" way.

Huh, OK.

> I'm not certain which use of `void` you consider to be inconsistent with C. The "I return nothing" `void` seems pretty consistent. The "param fold me away" `void` doesn't really have an equivalent.

Sorry for the confusion.  I meant the new "fold me away" sense (so am agreeing with you... this was me arguing with myself, not you).

> I don't like the empty parenthesis means `void` idea

Yeah, me neither.

> I was hoping to avoid changing the "I don't return anything" `void` because it has been around for so much longer than the "void value" `void` and is currently more widely used. Plus the "void value" is named with a placeholder as you pointed out, so seems more OK to change.

Those are good arguments.  I'd definitely like to hear from others on this issue before calling it closed, though, and will encourage that.

**Comment by mppf** [comment]
> "Void values" and empty returns are not interchangeable concepts, and the compiler needs to treat them differently. For example, a call to a function that doesn't return cannot be assigned to a variable, but a call to a function that returns a "void value" can be.

> A function with an empty return cannot have any non-empty returns, but a function that returns a "void value" can return other types in other paths that are param folded. Issue #9152 runs into this.

> I think we need to separate these concepts by giving "void values" a new and distinct name and type.

I'm not sure I agree. Or, at least, I don't see that separating these concepts is the solution I would pick. I would certainly agree that #9152 is a problem but it just looks like a compiler bug rather than a language design issue to me.

It sounds like the suggestion to separate them is coming from a desire for different behavior in these two cases:
``` chapel
proc returnVoid() { return _void; }
var x = returnVoid(); // now x has type void
```

``` chapel
proc noReturn() { }
var x = noReturn; // currently compilation error
```

I think that in both of these cases, `x` should have type `void`. But, you might ask, won't the user now be more likely to be confused / miss out on early and straightforward detection of an error? I think there is a simple remedy to that problem and it amounts to putting attention towards improving the error message.

If the user's code literally had this:

``` chapel
proc noReturn() { }
var x = noReturn; // and x is never used
```

then I don't think it's particularly important that the compiler raise an error. (Of course you may disagree with me about that). But supposing that `x` is used, I think there should be an error:

``` chapel
proc noReturn() { }
var x = noReturn;
var y = x + 1;
writeln(x);
```

To be useful, this error just needs to point out that `x` is of type `void` because it is capturing `noReturn` and that's probably where the error is. I'd expect it would point that out after some other error (like "You can't add void values" or "You can't write a void value").

It might get a little strange with instantiated functions, like this:
``` chapel
proc genericAddOne(arg) { return arg + 1; }
proc noReturn() { }
var x = noReturn;
var y = genericAddOne(x);
```

However I think the compiler is still up to the task of pointing out the reason that `arg` was `void` is that at the instantiation point `x` is `void` because `noReturn` does not return a value.

Anyway, I think this kind of error message would be equivalently useful in the returnVoid case.


lastly -

> * I think it makes sense to rename the `_void` value no matter what since the leading underscore has always suggested to me that it's just a placeholder name.

+1 to that.

**Comment by daviditen** [comment]
The separation between returning nothing and returning a "void value" was intentional: #6049.  There appeared to be mostly agreement that your
```
var x = noreturn();
```

example should be an error.

**Comment by bradcray** [comment]
My intuition is still to treat these two cases distinctly.  I think that functions which return nothing are a fairly common and simple case where it'd be nice to nip conceptual mistakes from them in the bud immediately rather than permitting them to propagate to a variable used elsewhere and needing to handle the issue down the line (i.e., seems like more compiler complexity and potentially more mental complexity for the programmer?).  Whereas I think functions that intentionally return `_void`/`none` with the intention of propagating the value + type onwards to fold out code based on param-time decisions occur less frequently and are worthy of handling differently as suggested here and in the original discussions on this feature.

I could imagine we might want to do things like permit `_void`s to be permitted in some cases where non-returning functions are not.  For example, it doesn't seem crazy to me to permit `_void` to be accepted by a writeln() (essentially a no-op?) such that `writeln(noreturn());` would be an error ("I think you made a mistake") where `writeln(returnVoid());` would not be?  (Or, if not this case, can we conceive of other cases where we'd want to handle the two cases differently?)

The correlation to unit types (types with one legal value like `None` and `NoneType`) and bottom types (types with no legal values like `void`) also seems strong to me, suggesting that two distinct types are appropriate since these are two distinct PL concepts / cases.

It seems like the main downside to taking this issue's path is having two type identifiers in the language where _perhaps_ we could get away with one, but given the likely benefits of things being easier for users and the compiler, that downside doesn't seem all that bad to me. 

OTOH, if we were able to get away with one type, I might be tempted to call the value `nothing` and the type `void` to avoid having a type called `noneType` (which seems a bit ugly to me since it would be our first built-in camelCase type I think?).  But this is a stopgap suggestion...  as I say, my intuition is still to have two types for these two concepts.

**Comment by daviditen** [comment]
I opened a new issue to just talk about the names of these three things, under the assumption that splitting them apart is decided here.  It is #12885.

**Comment by daviditen** [comment]
We've decided to separate the two concepts into `void`, `nothing`, `none`.
