### ISSUE TITLE
add chpl_comm_getput_unordered

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#12251]
Related to  #12150. The compiler might like to translate a chpl_comm_get call into a unordered/buffered call, but it's hard for the compiler to (reliably) know that one side is local. In contrast it'd be easy for the runtime to check that one side is local and to just do a workaround get/put if not.

So, we'd like to have a call that's something like chpl_comm_getput_unordered to accept arguments where both the LHS and RHS could be remote. It can just fall back on ordered/blocking get and put if it's a case the implementation doesn't handle yet.

**Comment by mppf** [comment]
@gbtitus - if both are remote, it could always chpl_gen_comm_getput which already exists (but may not be used right now / may not be quite right outside of llvm) and just copies chunks of data. It's not true that we'd need to do it in each comm layer if it's in the runtime - the runtime can have general helper functions that call comm-layer-specific functions.

Of course, if you know you'd implement it with an `on` statement (which isn't obvious to me), putting it in module code would be fine.

All that said, it doesn't matter to me much whether it's in the runtime or in module code.

**Comment by ronawho** [comment]
For context this is meant to implement something like:

```chpl
LHS = RHS
```

where the compiler can't prove that either are local. For the C backend the compiler currently emits a GET of RHS, followed by a PUT to LHS. We're looking at adding a single function that will do that internally, so that if LHS is local we can do an unordered get and otherwise do normal blocking GET/PUT

**Comment by ronawho** [comment]
And for now only ugni supports unordered GETS, but I imagine this will be in a common shim, not implemented for each comm layer. Something similar to: 
https://github.com/chapel-lang/chapel/blob/e6d3518acb94ba8591056e506fa7b90f51e58b17/runtime/include/chpl-comm-compiler-llvm-support.h#L54-L82

**Comment by gbtitus** [comment]
> For the C backend the compiler currently emits a GET of RHS, followed by a PUT to LHS. We're looking at adding a single function that will do that internally,

Perhaps I'm misunderstanding something. That sounds like a double transfer in the case that both LHS and RHS are remote.  Why do that?  Why not AM to one or the other and do a single transfer?  (A local one, even, if both LHS and RHS are on the same remote node.)

**Comment by ronawho** [comment]
Assuming LHS and RHS live on different nodes a GET+PUT is going to be much faster than an AM+PUT and the AM will introduce additional CPU overhead. Even if LHS and RHS live on the same node I think the GET+PUT will still be faster and I'm not sure that will result in any more network traffic than an AM.

And just to be clear on master today the compiler emits the GET+PUT directly, we're just looking to add a wrapper function to make some other optimizations easier. If for some comm layer we think an AM+PUT will be better than a GET+PUT then adding a getput function to the runtime makes that easier to do since the implementation won't be hardcoded in the compiler.

**Comment by gbtitus** [comment]
> Assuming LHS and RHS live on different nodes a GET+PUT is going to be much faster than an AM+PUT and the AM will introduce additional CPU overhead. Even if LHS and RHS live on the same node I think the GET+PUT will still be faster and I'm not sure that will result in any more network traffic than an AM.

I don't believe that, as a blanket statement.  Which is faster must depend on AM latency, transfer size, and network bandwidth.  It may be that the circumstances which would let us to do one of these as a fast-AM + PUT cannot occur, but nobody has said that yet.  Perhaps no transfer is large enough?  The bulk transfer code wouldn't doesn't exercise this, at least it didn't when last I looked at it, because it goes to some effort to do all transfers from either the sending or receiving side.

**Comment by ronawho** [comment]
> I don't believe that, as a blanket statement. Which is faster must depend on AM latency, transfer size, and network bandwidth. It may be that the circumstances which would let us to do one of these as a fast-AM + PUT cannot occur, but nobody has said that yet. Perhaps no transfer is large enough? The bulk transfer code wouldn't exercise this, or at least it didn't when last I looked at it, because it goes to some effort to do all transfers from either the sending or receiving side.

Oh duh, yeah you're right. I've been thinking about bale and RA style codes that are doing single-word updates. That said, I don't think we will currently emit code that will result in a large get/put outside the bulk-comm. I think at most we'll emit a PUT/GET that's the size of a record (which could be arbitrarily large, but are generally small)

**Comment by mppf** [comment]
At least as far as how this relates to #12150, the compiler sometimes generates a dsiAccess that returns an int (for e.g. a DefaultRectangular index array in indexgather instead of a block one). That means that we might like to tell the runtime which variables must be copied and which it can rely on existing for longer.

**Comment by gbtitus** [comment]
> That said, I don't think we will currently emit code that will result in a large get/put outside the bulk-comm.

Okay, so if bulk comm already avoids transfers where both operands are remote and every other case involves records which are hardly ever large, then this seems okay.
