### ISSUE TITLE
Support zmq_getsockopt for ZMQ_LAST_ENDPOINT

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#12356]
Edit: new proposal down below the hidden comments

Today, our ZMQ module supports a subset of the ZeroMQ features.  This has mostly been sufficient, but in order to support multi-locale interoperability using ZMQ, I would like to be able to create a connection without having to provide a port number and then retrieve the connection information that was used.  To do that, I need to call `zmq_getsockopt` with the option `ZMQ_LAST_ENDPOINT`.  `zmq_getsockopt` is not currently wrapped by our ZMQ library, and while ZMQ_LAST_ENDPOINT is present in the module file, it is a private variable.

My proposal:
- expose a `LAST_ENDPOINT` constant similar to [LINGER](https://chapel-lang.org/docs/latest/modules/packages/ZMQ.html#ZMQ.LINGER) for `ZMQ_LINGER`
- add a method `getsockopt` to the `Socket` class which takes in an `option: int`, similar to [setsockopt](https://chapel-lang.org/docs/latest/modules/packages/ZMQ.html#ZMQ.Socket.setsockopt).

`getsockopt` would then be able to support `LAST_ENDPOINT` and `LINGER`, but none of the other options just yet.

**Comment by lydia-duncan** [comment]
An alternative would be to expose a method to `Socket` specifically for `LAST_ENDPOINT`.  I suspect we will want to support the whole API eventually, so would prefer to match it as much as possible, even though the scope of what `getsockopt` supports would be limited for the time being.

**Comment by lydia-duncan** [comment]
@nspark - thoughts?

**Comment by mppf** [comment]
Sounds reasonable to me.

**Comment by lydia-duncan** [comment]
Wrinkle in this proposal - the function has multiple return types, which it handles in C with `void*`.  Due to the arguments being execution constants instead of param values, we can't base a where clause off of which option is being requested, so overloading the function seems out of the picture.  We could follow the individual method per option strategy I proposed as an alternative (and this looks like [what Java is doing](https://github.com/zeromq/jzmq/blob/1166757b9f1beee7663b5343f077f80a6a62a2bb/jzmq-jni/src/main/java/org/zeromq/ZMQ.java#L752))

**Comment by bradcray** [comment]
Isn't using a method per option equivalent to passing in a param argument (which could then be converted to the appropriate execution-time constant for the C routine?).

**Comment by lydia-duncan** [comment]
Hmm.  I thought of that, but dismissed it since we couldn't declare the param to have the same value as the execution time constant (i.e. I wouldn't be able to write: `param LAST_ENDPOINT= ZMQ_LAST_ENDPOINT;`, right?).  But maybe I didn't think about that strategy long enough . . .

**Comment by lydia-duncan** [comment]
I got this to work by making the LAST_ENDPOINT a param defined using the same number as in the `zmq.h` file.  Since getsockopt can also take LINGER as an option, I made LINGER a param as well using the same strategy.

This means that if a later version of ZeroMQ changes the numbers it uses for these constants, we will need to update our param declarations or setsockopt and getsockopt will get the wrong information back.  Since the `zmq.h` file had some numbers missing between constants, I suspect the numbers will not change, though.

This allows us to overload the function for different return types.

It does, however, mean that one potential option for setsockopt is a param (LINGER) while the other two are execution constants (SUBSCRIBE, UNSUBSCRIBE).  I'm leaning towards making them params as well for consistency, but will not update the declaration for setsockopt to take a param argument until it needs to.

**Comment by bradcray** [comment]
Can't you make the params be whatever values we want them to be and then just pass in extern const symbols to the extern function?  I.e., there's no specific need to pass the params that Chapel needs to distinguish between types directly to the extern routine, or to have them have the same numeric value, is there?  I'd expect you'd just need to be able to map from the Chapel param to extern C symbol name (and then have the C compiler take it from there).

**Comment by mppf** [comment]
If we do end up with params with the same numeric value, we can just add some code that verifies that these match the C variables, to avoid potential for errors if they ever do change.

I think what @bradcray described should be possible but I don't have a particular opinion about how far it should go.

(And, note, with the LLVM backend and/or extern blocks, we *can* make a #define or enum constant into a Chapel param, because we parse the C files with clang before Chapel function-resolution-time).

**Comment by lydia-duncan** [comment]
> Can't you make the params be whatever values we want them to be and then just pass in extern const symbols to the extern function? I.e., there's no specific need to pass the params that Chapel needs to distinguish between types directly to the extern routine, or to have them have the same numeric value, is there? I'd expect you'd just need to be able to map from the Chapel param to extern C symbol name (and then have the C compiler take it from there).

It's true, that is something I can do.  I chose not to for a couple of reasons:
1. I didn't want the addition of more constants (which we will definitely do) to have to go traipsing through the file or docs to figure out what number to use next, or to feel the desire to update old ones if new constants get added in between them (there's 9 constants in the file in between LINGER and LAST_ENDPOINT that aren't exposed yet).  And counting the ones available just seemed painful.  Using the current number in the ZMQ header makes it less mental work to figure out what the number should be.
2. Doing a translation between the param and the C constant relies on us being principled about updates going into the translator and ensuring we use the right one when their names are similar.  It seems like using the same number gives us less risk

> (And, note, with the LLVM backend and/or extern blocks, we _can_ make a #define or enum constant into a Chapel param, because we parse the C files with clang before Chapel function-resolution-time).

That would be nice!  It'd be unfortunate to make the ZMQ code dependent on one backend, though, right?  Even if it was the default

**Comment by bradcray** [comment]
> 1. I didn't want the addition of more constants (which we will definitely do) to have to go traipsing through the file or docs to figure out what number to use next, or to feel the desire to update old ones if new constants get added in between them (there's 9 constants in the file in between LINGER and LAST_ENDPOINT that aren't exposed yet)

I was imagining that these constants would all be defined adjacent to one another, within the vicinity of the routine (or routines) that accept them.  I.e., no traipsing permitted.  I was also imagining that an enum would be the most natural type for this param argument which would avoid the need to give them numbers at all and automatically group them into a single source location.

> 2\. Doing a translation between the param and the C constant relies on us being principled about updates going into the translator and ensuring we use the right one when their names are similar.  It seems like using the same number gives us less risk

To me, using the same number as the C header file represents a maintenance burden because if ZMQ doesn't guarantee any particular numbering in its public interface, it seems they could change in the future, where the names presumably can't.  If the translator were changing enum names into ZMQ extern const names, it doesn't seem like it would be difficult to keep them in sync, assuming the two names were similar.

I agree with this comment from Michael and would be nervous if we didn't do such assertions:

> If we do end up with params with the same numeric value, we can just add some code that verifies that these match the C variables, to avoid potential for errors if they ever do change.

And with this one from Lydia:

> It'd be unfortunate to make the ZMQ code dependent on one backend, though

**Comment by lydia-duncan** [comment]
I'd forgotten that param enums were possible now.  It's still going to be huge - setsockopt takes ~50 options and getsockopt takes ~70 (I may have mixed those numbers up) and at least some of them are not shared between the two routines, but removing the number portion by using enums and translating to their underlying C equivalent should make things better

**Comment by bradcray** [comment]
On the way home last night, I found myself wondering whether a routine per option would in fact be better/cleaner/easier than the param approach now that I know the arity of the number of options we're talking about.  Specifically, it seems like the benefit in C of having a single routine (enabled by the `void*` return type and burden on the user to get it into the right type) seems lost in Chapel since it can't be a single routine (assuming we don't want users to similarly cast the result); in either case, we'll have to add new code to add a new option (and hopefully, in either case, it'll just be a modest amount of code); and the user's effort on remembering naming would go into the routine name rather than the option names.  Obvious downsides are that the interface would be more different than C.

Still another option would be to have the routine return a union of the possible types that can be returned in order to get it back into a single routine, but I don't know if our unions are up-to-snuff for that (and there have been calls to remove them in the short-term from some).

**Comment by lydia-duncan** [comment]
>  Obvious downsides are that the interface would be more different than C.

Yeah :( That said, there is precedent for having individual routines - I had a link earlier to Java doing that for at least ZMQ_LAST_ENDPOINT.  However, we don't do that for setsockopt and those routines are closely tied - I'd prefer if we followed the same strategy for both, whatever that strategy ends up being.

**Comment by lydia-duncan** [comment]
I'm starting to get a little worried about how close to the release this is.  It seems like these are all good things to consider and that it would be frustrating for a user to start relying on one syntax and then have to change to another in the following release if that did end up being the right choice

**Comment by lydia-duncan** [comment]
(Old comments hidden for a fresh start at the conversation based on the discussion that occurred.  Feel free to read them if you are curious)

**Comment by lydia-duncan** [comment]
Option 1:
----------
Have a version of the function per potential option  (`getsockopt_linger(): int`, `getsockopt_last_endpoint(): string`, etc.) provided

Pros:
- Return type is obvious to the user
- While different than the C interface, there is at least precedent - 
Java has done this.

Cons:
- When all ZMQ options are present, there will be ~70 versions of this 
function

- Different strategy than its counterpart, setsockopt, which takes some 
of the same options (but not all)
   - Could modify setsockopt to behave in the same way for consistency


Option 2:
---------
Make the argument accepted param, so that the different return  types can be in param conditionals and thus folded away at compile time(`getsockopt(param option: optiontype)`)

Pros:
- Only one function to document

- More similar to setsockopt set up
   - Though may want to make setsockopt's independent options into 
params for consistency (since otherwise we'd end up with only some of 
its options being param due to their use in getsockopt)

- More similar to the C interface

Cons:
- The return type of getsockopt might not be clear to the user.
   - The ZMQ API documentation does list the types that correspond to 
each option that could be provided, and we can provide a helper function 
to determine what the return type would be ahead of time.

- The param constants can't take the value of their C counterpart (since 
those are known at execution time)
   - Will require translation between the Chapel param and the C version 
when calling the C implementation


Option 2a:
----------
 use current numbers in zmq.h (e.g. `param LAST_ENDPOINT = 42`)
- those numbers could change in a different release (we'd need to 
validate it).


Option 2b:
----------
 use our own numbers (e.g. `param LAST_ENDPOINT = 2`)
- we have to do mental work to determine what number to use for each new 
option supported.  Since there are a large number of options, 
determining which number should be used next would be burdensome, 
especially if subsequent options weren't added in order (most of the 
constants are already defined using externs in ZMQ.chpl today).


Option 2c:
----------
 use an enum (e.g. `enum option { LINGER, LAST_ENDPOINT...}`
- it'll have at least 70 constants in it by the end (more if we have to 
do the same thing for setsockopt, since there's overlap) and chpldoc 
doesn't support comments on individual enum constants, just the enum 
declaration itself (see https://github.com/chapel-lang/chapel/issues/5022)



Option 2a is my preferred strategy, followed by Option 1, then 2b, then 
2c.  It's the closest to what I currently have implemented, but I'm open 
to the group feeling differently (modifications shouldn't be too 
difficult either way).

**Comment by bradcray** [comment]
* As a variation of option 1, could we call the routines something like:

        `getLinger()`,
        `getLastEndpoint()`,
        etc.

  rather than having the sockopt portion in there, for brevity /
  simplicity?  I'm assuming that "Linger" or "LastEndpoint" or whatever is
  the option that the 'getsockopt' prefix is referring to (?), making it
  seem redundant to me.

* It's not obvious to me why having 70 params is strictly better than 70
  functions or 70 enums, though you seem to use those counts as
  counterarguments against the option 1 and 2c approaches.  In the
  function case, I'm guessing that there would be a core function per
  possible return type and that each of the 70 functions would be a 1-5
  line routine that invoked the core routine?  (i.e., it's not like it's
  70 unique functions with completely distinct implementations).

* In cases where there are n choices available, I'm forced to choose
  between them, and other choices are not valid and would require more
  support to implement, I prefer enums to params or strings because they
  (a) constrain the type and values that can be passed in (i.e., I can't
  make up a new integer and pass it in), (b) force the use of a
  descriptive name (i.e., I can't pass in the underlying integer).  For
  that reason, of the 2 a, b, c options I prefer 2c.

* I do think that setsockopt() should be as symmetrical as possible with
  whatever approach we take.  Why does it not have similar type safety
  issues as getsockopt()?

* Are there other (more modern) type-strict precedents we could look to
  for inspiration other than Java and C?

**Comment by lydia-duncan** [comment]
> could we call the routines something like: `getLinger()` ...?

We definitely could!  I didn't in the initial proposal because I was trying to keep as close to the ZMQ API as possible (and iirc the Java version had the name still there).  I think it will be easier to find the ZMQ counterpart via a google search if the name still has getsockopt in it, but we can easily solve that through a link to the documentation (even though the page for getsockopt is huge)

> It's not obvious to me why having 70 params is strictly better than 70 functions or 70 enums

70 params will in this case turn into more than 70 functions due to the overlap of the options used by setsockopt and getsockopt (e.g. `setsockopt_linger` and `getsockopt_linger`, rather than just one setsockopt, one getsockopt, and one version of each option).  70 params will turn into 70 enums, but #5022 means their documentation will be worse

> I do think that setsockopt() should be as symmetrical as possible with
  whatever approach we take.  Why does it not have similar type safety
  issues as getsockopt()?

The argument for setting the value is able to be generic, and the call to C's `zmq_setsockopt` casts the value to c_void_ptr before sending it.

> Are there other (more modern) type-strict precedents we could look to
  for inspiration other than Java and C? 

Not sure, I'll take a look!

**Comment by mppf** [comment]
I think having params or an enum for all of the 0MQ getsockopt options is overdoing it. That's just my personal opinion - it could work - it just seems that if we're trying to "Expose 0MQ functionality" then we might want to allow for programmers to use the documentation from 0MQ to know how to call our library. Which would imply
 1) We wouldn't want to change the names (or if we do, have a recipe)
 2) We'd want the function names the same or follow an recipe

Considering the other options... I don't understand why we need getsockopt to return the gotten value. In the C 0MQ interface, `zmq_getsockopt` returns 0 on success and effectively uses an `out` argument to set the value.

Why don't we make `getsockopt` have a signature like this:

``` chapel
proc getsockopt( socket, option: c_int, out result) throws
```

?

Then it can still be generic based upon the `out` type. We could additionally throw an error if somebody called getsockopt with the wrong output type (but hopefully the 0MQ library can already do this, at least when the sizes differ).

Secondly, as a completely different alternative, you have this option:

> getsockopt_linger(): int, getsockopt_last_endpoint(): string

Why not consider having getsockopt_int that returns an int and getsockopt_string that returns a string? Then there would be a small number of methods. Additionally (like the above case) we could check that the right variant is called for a given ZMQ option.

(By the way, the Curl module faces many of the same issues, and there it uses the getsockopt_int/getsockopt_string strategy. That doesn't mean that it's right or anything though.)

**Comment by lydia-duncan** [comment]
[Swift](https://github.com/goloveychuk/ZeroMQ/blob/master/Sources/Socket.swift#L66) uses `UnsafeMutableRawPointer` as the result type, so there's only one version of the method.

[Rust](https://docs.rs/zmq/0.9.0/zmq/struct.Socket.html) uses a method per option (`get_linger()`, `set_linger()`, etc.).

If I'm reading this right, [Julia](https://github.com/JuliaInterop/ZMQ.jl/blob/master/src/sockopts.jl#L3) has a method per option (`get_linger()`, `set_linger()`).

That said, all of these places link back to the original C API (and the Swift and Julia documentation was either not obvious or incomplete)

**Comment by lydia-duncan** [comment]
I think the out argument strategy is interesting.  I'd have to experiment with it to be certain the compiler isn't too conservative about potentially bad assignments into it.

I am using `_int` and `_string` versions in the C helper functions that I call already.  I'm not very fond of having that be part of the interface we expose to users, but I prefer it to having a pair of functions per option, personally.

To me, the benefit of having it be part of the return type is that the user could just write:
```chapel
var x = s.getsockopt(LAST_ENDPOINT);
```
They will need to know the type ahead of time when they call `setsockopt`, though, so maybe it isn't unreasonable to request it for `getsockopt` as well

**Comment by lydia-duncan** [comment]
Verified: using an out argument allows the method to be used without issue, and means that we can leave LINGER defined as a const with the same value as the extern constant ZMQ_LINGER that we got from the header file.

I'm finding I'm not entirely clear on your preferences.  Michael, it sounded more like you were tossing ideas around, or did I misunderstand?  Brad, it sounds like you prefer using enums over params or separate functions, is that your overall best preference of all the strategies?

**Comment by mppf** [comment]
I'm fairly happy with method-per-option or with out argument. I think out argument is probably the best option at the moment. I'm not really excited about using params to change the return type. I don't have a real clear idea what an enums solution looks like and as a result I don't really have an opinion about it. (But maybe it uses the param-value of the enum to change the return type - and then I don't really like it from a stylistic point of view).

**Comment by bradcray** [comment]
It's not clear to me that using a generic `out` argument is more attractive than using a generic return type (which I'd prefer of those two choices).  I think Michael makes an argument that the `out` argument would provide some compile-time type checking, but I suspect that errors would occur within the body of the library routine (?) whereas returning would result in an error in user code, which seems easier to wrestle with (?).  I also agree with Lydia that from a usability standpoint, the return results in nicer looking code.

Mentally rewinding to figure out how we got here, I think it was because I was finding the overloads:

```chapel
proc getsockopt(param option: int) throws where (getsockoptRetTypeHelper(option)
                                               == string) {

  proc getsockopt(param option: int) throws where (getsockoptRetTypeHelper(option)
                                               == int) {
```

to be unwieldy and roundabout to read as a developer while also anticipating the day when we showed where-clauses in `chpldoc`-generated documentation.  I think I was also imagining that we wanted to be explicit about return types in library routines and that that's why we had the multiple user-level routines.  But if that last assumption isn't true, then I'd be inclined to have a single top-level routine:

```chapel
proc getsockopt(param option: whatever) { ... }
```

that does all the switching on whether it's an int vs. string vs. whatever type inside the routine rather than outside.  This keeps the interface clean for the developer and the user.

That said, really putting myself in a user's shoes, getsockopt() feels to me like a very old-fashioned interface and not particularly friendly as compared to per-option methods; and Rust and Julia are good languages to be in company with.

And of course, we could always support both interfaces, where one approach calls the other...

**Comment by mppf** [comment]
>  I think Michael makes an argument that the out argument would provide some compile-time type checking, but I suspect that errors would occur within the body of the library routine (?) whereas returning would result in an error in user code, which seems easier to wrestle with (?). I also agree with Lydia that from a usability standpoint, the return results in nicer looking code.

If we wanted to, we could make a `param` version of `getsockopt` that did type checking at compile-time. But, we could leave that to future work. E.g. for when we have better ability to get the C constants into params, with --llvm, when it's the default, etc.

>  I also agree with Lydia that from a usability standpoint, the return results in nicer looking code.

I agree with that. The question is just how much effort we want to go to for this function in this module.

> `proc getsockopt(param option: whatever) { ... }`

I think it'd be unnatural for the return type to vary based on an integer `param` argument. (Yes, that is a reasonable thing to do in other contexts, but here I think it'd be confusing).

> That said, really putting myself in a user's shoes, getsockopt() feels to me like a very old-fashioned interface and not particularly friendly as compared to per-option methods; and Rust and Julia are good languages to be in company with.

I'd be quite happy with the method-per-option interface. I think we could say that we've reached consensus with that strategy.

> And of course, we could always support both interfaces, where one approach calls the other...

The only reason I can think of having 2 interfaces here is if it helped us in the event that the C zmq library gained new options for setsockopt/getsockopt but we hadn't updated the module. But, in that event, the `extern const` declarations wouldn't be there either... So we're probably better off exposing the C zmq handle to a user in that position so they can write the `extern` declarations themselves. (Unless we switch to using extern blocks as a matter of course, then the `out` argument option could be a good answer for such a user).

I don't think we should add 2 interfaces right now.

**Comment by lydia-duncan** [comment]
>  I think Michael makes an argument that the out argument would provide some compile-time type checking, but I suspect that errors would occur within the body of the library routine (?) whereas returning would result in an error in user code, which seems easier to wrestle with (?)

The mock-up I made has us throw an error from the function if the option provided wasn't expected based on the type of the out argument.  I'd want to wordsmith the message a bit from where it currently stands if we took that route, but I don't know that it would be harder to wrestle with than an error in user code.

>  I think I was also imagining that we wanted to be explicit about return types in library routines and that that's why we had the multiple user-level routines.

I think that's right.  We could do that in the out argument case by having overloads for the different expected types of the out argument (it's not what I did in the mock up, but it wouldn't be difficult).

>  I'd be quite happy with the method-per-option interface. I think we could say that we've reached consensus with that strategy.

I'm willing to follow that strategy.  I also would prefer to not add 2 interfaces.  I will, however, link to both prior implementations here, in case we eventually follow that route.  Thanks for the discussion!

**Comment by lydia-duncan** [comment]
I think the only question that remains is: for setsockopt, should we deprecate the original, or just add the set* functions alongside it?  If the latter, should an effort be made to extend it in the future when additional set* functions are added (i.e. by defining the additional options as explicit constants like LINGER)?

**Comment by bradcray** [comment]
If there's no intention to support both styles of interface, I'd deprecate it for symmetry.
