### ISSUE TITLE
Execution time where clauses

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#12370]
I would like to be able to write a where clause that depends upon execution time information.

My concrete example is writing a wrapper to call ZeroMQ's getsockopt function, whose return type is a `void*`.  What is actually returned using that `void*` depends on what `option` argument value is passed - `LINGER` returns you an `int` while `LAST_ENDPOINT` returns you a `char *`.  I'd like the Chapel equivalent to not be similarly opaque to the user.  It seems like we ought to be able to write function overloads such that you'd get a Chapel `int` or `string` or whatever the return type ends up being without forcing the user to perform the cast or conversion from `c_void_ptr` themselves (or getting around the issue by writing a differently named version for each expected return type).  However, the `option` potential values are all C constants, and where clauses must be evaluated at compile time.

**Comment by lydia-duncan** [comment]
That said, this is probably complicated to implement, given our current where clause strategy

**Comment by bradcray** [comment]
To me, this idea doesn't fit with the statically typed nature of the language.

**Comment by bradcray** [comment]
I still don't see a path forward for this feature request, not due to being complicated to implement so much as not fitting the language philosophy.  You seem to be asking to be able to write a function foo() which returns one of two types based on execution-time information.  Yet, if we can't know what type it is until execution time, we don't know what type to make variable `x` in cases like: `var x = foo();`.  We could say that x's type is also not known until execution time, but that's a very different language than what Chapel has set out to build (a dynamically typed rather than statically typed one).

Am I misunderstanding, or can I label this "won't fix" and close it?

**Comment by lydia-duncan** [comment]
Thanks for the reminder, I meant to come back and follow up but got distracted
