### ISSUE TITLE
Can we remove pragma "no prototype"?

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#12396]
`pragma "no prototype"` / `FLAG_NO_PROTOTYPE` appears on a number of `extern` symbols in the standard modules. It is unlikely that this flag is still needed on those functions. Can the flag be removed from any `extern` functions? Can it be entirely removed?

**Comment by AnubhavUjjawal** [comment]
I found them in two places. Should I remove them and then submit pull request??
![screenshot 2019-03-06 at 1 21 36 am](https://user-images.githubusercontent.com/22658701/53833311-35bdc780-3fae-11e9-931d-0f32ed705f7c.png)
![screenshot 2019-03-06 at 1 21 25 am](https://user-images.githubusercontent.com/22658701/53833319-38b8b800-3fae-11e9-9987-ce0ff2fd9ff2.png)

**Comment by ronawho** [comment]
Just FYI for history/context:

`FLAG_NO_PROTOTYPE` was added in 84bb02af5c to support a `--gen-extern-prototypes` flag. That flag was removed in 818b977bf1, so there's no point in having the "no prototype" flag anymore. I don't understand what 84bb02af5c was attempting to do, but I'm still pretty confident we don't need the flag anymore.

**Comment by bradcray** [comment]
I think the notion was to have the Chapel compiler generate the C prototypes that it was expecting to get from a C header file so that the two could be diff'd to see whether they matched or not.  But this always struck me as a bit naive given how much Chapel boils typedefs down to basic types and the richness of decorators that one can apply to a C prototype that would break a diff even if the two were equivalent.  I definitely think this can be removed.
