### ISSUE TITLE
Design spike: LLVM library compilation

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#12459]
This is a post-release task.

Linux/gcc compilation when chpl__module.o and chpl_compilation_config.c.o are put into the same library file (say libfoo.a) requires the library to be listed both before and after libchpl due to libchpl depending on symbols defined in chpl_compilation_config.c.o (`-lfoo -lchpl -lfoo`, in a simplified form).

This strikes me as potentially unfriendly, though I'm not sure what a better solution would be.  I need to experiment to see if having chpl_compilation_config.c.o in a separate library file will work or just cause more circularity.  But if such a separation would work, would that be preferable?

**Comment by lydia-duncan** [comment]
@mppf and @dmk42 - I'd like your input on this (but again, it's a post-release task.  I'll re-ping again after code freeze)

**Comment by bradcray** [comment]
Note that we also have repeated libraries due to circularities in the current executable link step for the C back-end as well (at least, historically we did... I don't know whether anyone's tried removing duplicates anytime recently):

```
... -lchpl  -lm -lgmp -ljemalloc -lchpl -lqthread -L/Users/bradc/chapel/third-party/hwloc/install/darwin-x86_64-native-clang-none-flat/lib -lhwloc -lm -lre2 -lpthread
```

In the case this issue is addressing, is this something we can put in our generated Makefile stub to save the user from having to deal with it (i.e., it's a little ugly, but most people wouldn't be the wiser), or does it put some sort of burden on the user directly?

**Comment by lydia-duncan** [comment]
When we update `--library-makefile` to work for LLVM, I was planning on listing it twice and would imagine this will make things easier for the user.  It seems like that might be frustrating for users that write it on their own (but they probably will be using `--library-makefile` anyways due to the sheer volume of `-I` and `-L` options we require to build and this issue would pale in comparison to that).

So I'm okay with us deciding this is acceptable
