### ISSUE TITLE
Inconsistent `nil` objects returned from `new`

### ISSUE THREAD

**Issue by BryantLam** [chapel-lang/chapel#12472]
Bug. Inconsistent behavior with nil-assignment from `new`. I thought I knew the rules for how to use `new` (always use parentheses), but now I'm not so sure. Are blocks 1 and 4 legal? How is block 1 and 2 different, versus blocks 3 and 4?

```chapel
class C {}
class D { type t; }

proc main() {
  // 1
  {
    var d = new C;
    var o = new owned C;
    var s = new shared C;
    var b = new borrowed C;
    writeln((d == nil, o == nil, s == nil, b == nil));
  }
  
  // 2
  {
    var d = new C();
    var o = new owned C();
    var s = new shared C();
    var b = new borrowed C();
    writeln((d == nil, o == nil, s == nil, b == nil));
  }
  
  // 3
  {
    var d = new D(int);
    var o = new owned D(int);
    var s = new shared D(int);
    var b = new borrowed D(int);
    writeln((d == nil, o == nil, s == nil, b == nil));
  }
  
  // 4
  {
    var d = new D(int)();
    var o = new owned D(int)();
    var s = new shared D(int)();
    var b = new borrowed D(int)();
    writeln((d == nil, o == nil, s == nil, b == nil));
  }
  
  // 5; Similar to 1.
  {
    type Dint = D(int);
    var d = new Dint;
    var o = new owned Dint;
    var s = new shared Dint;
    var b = new borrowed Dint;
    writeln((d == nil, o == nil, s == nil, b == nil));
  }
  
  // 6; Similar to 3, or 4?
  {
    type Dint = D(int);
    var d = new Dint();
    var o = new owned Dint();
    var s = new shared Dint();
    var b = new borrowed Dint();
    writeln((d == nil, o == nil, s == nil, b == nil));
  }
}
```
```terminal
# Should all be false.
(false, true, true, false)
(false, false, false, false)
(false, false, false, false)
(false, false, false, false)
(false, true, true, false)
(false, false, false, false)
```
`chpl version 1.19.0 pre-release`

**Comment by bradcray** [comment]
I could be missing something, but I offhand, I agree that block 1 and 4 aren't what's intended and look to me like bugs in the compiler in which it's not being as strict as it should be.  Those who've worked more on initializers can correct me if I'm wrong (@benharsh, @lydia-duncan, @vasslitvinov, @mppf?).

Block 4 is the one that troubles me the most.  Since the `D` type does not support a `this()` method that takes no arguments, an additional invocation should not be able to be applied to it.  I don't believe that the compiler creates automatic `this()` methods for classes, so I'm guessing that this is just an expression that's getting silently dropped on the floor (?).

For blocks 1 and 5, I think the question is essentially "Do we permit argument lists to be dropped for `new` expressions that don't require arguments?"  My instinct is that the answer ought to be "no" because it provides a minimal amount of convenience while introducing potential ambiguities if the type in question does support a 0-argument this() method (is the user saying `new C` and then invoking its 0-argument this() method?  Or are they saying `new C()` and not invoking anything on it?).  Though we could choose to do so for convenience and then break the tie in the ambiguity in a stated way.

Overall, my guess is that this is a case of focusing on getting the cases that need to work working and failing to note that some other cases slipped through the cracks as well.

**Comment by benharsh** [comment]
Some thoughts:

I think we're not supposed to allow new-expressions without parentheses. When this happens, the compiler fails to recognize the pattern and effectively turns "new owned C" into "new _owned(C)", which is like writing "var o : owned C". The same goes for shared, but I'm not sure why borrowed/blank aren't effected. I don't yet know how difficult it would be to identify this parentheses-less pattern and emit an error (@mppf maybe has a better idea?)

In block 4, I think we're recognizing the expression as "new <type-expr>()", which is the same as block 6. I don't think anything is getting silently dropped on the floor. I would be fine with disallowing this pattern.

**Comment by bradcray** [comment]
OK, it sounds to me like the silent translation from `new owned C` => `: owned C` (and related cases) should definitely be made illegal and generate an error (and I guess this explains why the `nil` checks return `true`?...they essentially become default-initialized class variables?).  This seems similar to other classic cases when we didn't distinguish value expressions from type expressions sufficiently which led to confusion and unhappiness rather than benefit.

**Comment by benharsh** [comment]
I should have said before, but I'm working on a PR to add an error message for the parentheses-less case.

**Comment by BryantLam** [comment]
@benharsh -- I assume your PR would disallow blocks 1 and 5. You stated that blocks 4 and 6 are equivalent. On the surface, they do appear to be so, but I logically have trouble rationalizing that block 4's syntax should be legal (I think from the discussion, the extra parentheses don't do anything, so why have them when the syntax in block 3 clearly feels like evoking the initializer). IMO, block 4's syntax should be illegal too, whereas block 6 should remain legal.

**Comment by benharsh** [comment]
My PR will disallow blocks 1 and 5 (issuing an error for each line in the block with a new-expression).

Sorry, I should have said that eventually the compiler treats blocks 4 and 6 as the same thing. I agree that block 4's syntax should not be legal. I haven't tried creating an error for that case yet because I wanted to focus on the 'nil' issue first. I'll create a separate issue to track the desired error for block 4.
