### ISSUE TITLE
warning: Throwing unmanaged error - please throw owned

### ISSUE THREAD

**Issue by dlongnecke-cray** [chapel-lang/chapel#12529]
### Summary of Problem

When I write code to throw an error, I get a rather perplexing compiler warning:

`warning: Throwing unmanaged error - please throw owned`

I understand Chapel's default memory ownership to be `borrowed`, and so I'm not sure why the compiler infers it to be unmanaged in this case.

@mppf Brad said you might like to tackle this one.

### Steps to Reproduce

**Source Code:**

```chapel
proc foo() throws {
  throw new IllegalArgumentError("Error message.");
}

foo();
```

**Compile command:**

`chpl foo.chpl`

**Execution command:**

`./foo`

### Configuration Information

- Output of `chpl --version`:

chpl version 1.19.0 pre-release (eecc5d445b)

- Output of `$CHPL_HOME/util/printchplenv --anonymize`:

CHPL_TARGET_PLATFORM: darwin
CHPL_TARGET_COMPILER: clang
CHPL_TARGET_ARCH: x86_64
CHPL_TARGET_CPU: native
CHPL_LOCALE_MODEL: flat
CHPL_COMM: none
CHPL_TASKS: qthreads
CHPL_LAUNCHER: none
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: cstdlib
CHPL_GMP: gmp
CHPL_HWLOC: hwloc
CHPL_REGEXP: re2
CHPL_AUX_FILESYS: none

- Back-end compiler and version, e.g. `gcc --version` or `clang --version`:

Apple LLVM version 10.0.0 (clang-1000.10.44.4)
Target: x86_64-apple-darwin18.2.0
Thread model: posix

**Comment by bradcray** [comment]
@mppf: David mentioned this to me, and I couldn't rationalize the current behavior based on my recollection of our recent discussions.  Did something get missed, or am I forgetting some reason that it would behave this way?

**Comment by mppf** [comment]
I'm not sure if the question here is "Why is there a warning in this case? Why doesn't it just work" or "Why is the warning so confusing?".

First, note that `throw new IllegalArgumentError()` means, according to the borrowed-new-by-default rule, the same as `throw new borrowed IllegalArgumentError()`, which is useless because the error created will be destroyed at the end of the function, so would immediately lead to use-after free. You couldn't return a `new borrowed` either.

Second, note that the error reports `unmanaged` but that's just because the implementation goes to some length to make this pattern still function (and if it compiled it to `new borrowed` then it would lead to core dumps). Of course we could try to improve the error, but that can be hard to do while also:
 * giving real errors for throwing a borrowed variable (which would otherwise core dump)
 * handling the type being thrown being a type alias that could be `owned SomeType` (say).

What if we wanted `throw new IllegalArgumentError()` to just work? Here are the possibilities that I know of:
 a) changing `new SomeClass` to mean `new owned SomeClass` rather than `new borrowed SomeClass`
 b) changing `throw new SomeClass` to be an exception to the borrowed-new-by-default rule, so it translates to `throw new owned SomeClass`.
 c) create a new shortcut for constructing and throwing an error at the same time, so that `throw SomeClass(arg)` translates to `throw new owned SomeClass(arg)`.

@bradcray - you and I did discuss this and as I recall we agreed to require the source code use `throw new owned` for now. That doesn't mean we have to stick to the current behavior. I think a significant part of this element of the decision was changing code to use `throw new owned` would make it keep working in the longer term while also allowing us to refine the design (say by doing a, b, or c above).

#### concerns with a) changing `new SomeClass` to mean `new owned SomeClass` rather than `new borrowed SomeClass`

I think this one has some merit (and in fact I personally wanted `new SomeClass` to mean `new owned SomeClass` from the beginning) but since it's about much more than `throws` we'd want to have good reasons for doing this in other cases.

#### concerns with  b) changing `throw new SomeClass` to be an exception to the borrowed-new-by-default rule, so it translates to `throw new owned SomeClass`.

I think the main concern here is that it might lead to confusion. Normally programming languages try to allow parts of expressions to be expressed in variables. So I might expect the following two programs to be equivalent:

``` chapel
var x = new SomeClass();
throw x;
```

``` chapel
throw new SomeClass();
```

but under than proposal they wouldn't be.

#### concerns with c) create a new shortcut for constructing and throwing an error at the same time, so that `throw SomeClass(arg)` translates to `throw new owned SomeClass(arg)`.

It just seems to make the language include more special syntax.

**Comment by mppf** [comment]
Please see PR #12533.

**Comment by bradcray** [comment]
I'd say the confusion was with the error.  I remembered that we decided to not have `throw new Error()` result in an automatic change to `new owned Error()` (for fear of introducing an inconsistency; because it'd be easy to special-case it if/when users complained about being forced into this pattern); but the current warning seems similarly confusing since it suggests that we're not creating a `new borrowed` (which would be the consistent interpretation) but rather a `new unmanaged` (which feels as inconsistent as automatically switching to `new owned`...  at least, I couldn't come up with a satisfactory explanation for David last night).  I hear you saying that having it literally be `new borrowed` would result in a core dump, so I think my expectation would be that we'd make this an error rather than warning (i.e., you have to type `new owned Error()` or to throw an already existing owned error) and to have the error talk in terms of throws of `new borrowed` (or perhaps better, in terms of a _lack_ of `new owned`) rather than bringing unmanaged into the mix.  Either that, or I'd need to understand better as a user why unmanaged had come into the mix than I do currently.

**Comment by mppf** [comment]
@bradcray - can you have a look at PR #12533 ? Maybe we can simply adjust the warning to be more reasonable.

**Comment by bradcray** [comment]
Seeing PR #12533, I think it improves things, though I still think that maybe just making the first warning into an error would be preferable / simpler.  If we went with something like PR #12533 (warnings only, not errors), I'd probably change the second line to something like "converting borrowed error to unmanaged error to avoid core dumps".  But I also think that if we're going to go to that level of heroism to help the user's program not crash, the obvious question would be "Why didn't we just change it to `owned`?"  Where I think the obvious answer is "We didn't want to introduce an inconsistency."  But I think by doing anything with it, we have.  Hence, an error seems preferable to me.

**Comment by mppf** [comment]
@bradcray - Right, but I had left it a warning because `throw new SomeError()` worked in the last release and was in fact the only way to write it, so I was trying to ease the code transition. Do you think it's more preferable to abandon that (have it be a compilation error) or to make the second line more ambiguous (like `attempt to throw an unmanaged or borrowed Error, please throw owned Errors`).

**Comment by bradcray** [comment]
I think either of those are preferable to the current behavior on master.  I'd probably go with the error, but am not 100% certain I'm right and would suggest getting other opinions.  Your proposed new wording here also makes me wonder "Can I throw a shared error?" which seems like it _might_ make sense to do?  And also, if I'm not saying `throw new...` but am throwing a pre-existing error, will throwing an unmanaged or borrowed work the same as throwing a new unmanaged or new borrowed?

**Comment by dlongnecke-cray** [comment]
Sorry, I should have better explained that in this case my confusion is with:

- The error message is at odds with what I expect the ownership of ``new SomeClass()`` to be.
- It's not clear to me as a user how the ``unmanaged`` is introduced from the code that I wrote. 

There's also a separate issue with the required syntax being overly verbose (ie, `throw new owned SomeClass()` is a pain to write), but @mppf covered all that in the great breakdown above.

**Comment by mppf** [comment]
I'm testing PR #12533, which now removes the confusing 2nd line (at the cost of more code in the compiler).

**Comment by bradcray** [comment]
If it wasn't clear, I really am curious whether shared errors can be thrown, whether it would make sense for them to be, etc.

**Comment by mppf** [comment]
> If it wasn't clear, I really am curious whether shared errors can be thrown, whether it would make sense for them to be, etc.

At the very least the answer is "not right now". In earlier discussions, I couldn't come up with a use case where I could see it making sense. As a result, the design of having catch blocks like `catch e` make `e` be an `owned Error` seems to preclude the possibility of throwing `shared Error`s.

**Comment by bradcray** [comment]
OK, thanks.  In that case, if the second warning line were to evolve into something like your proposed:

```
attempt to throw an unmanaged or borrowed Error, please throw owned Errors
```

I wonder if it should name `shared` as a third "attempt" that won't work.

**Comment by mppf** [comment]
PR #12533 doesn't have the 2nd line anymore, but does give an error if you try specifically to do `throw new shared`.
