### ISSUE TITLE
Internal error when taking a reference to `this` in `init()` of class/record

### ISSUE THREAD

**Issue by ty1027** [chapel-lang/chapel#12695]
### Summary of Problem
In the following code, I am trying to take a reference to `this` in` init()` of a class (or record) to "rename" `this` to some other name (e.g., self), but the compilation fails with internal error. On the other hand, if I take a reference to `this` in `postinit()`, the code compiles successfully.

(This issue is not blocking for me and just reported here because of internal error.)

### Steps to Reproduce

**Source Code:**
This code results in internal error (for both class and record).

```chapel
class Cls    // or, record Rec
{
    var n: int;
    proc init() {
        const ref self = this;
        self.n = 100;
    }
}
var a = new owned Cls();
writeln( a.n );

$ chpl test.chpl
test.chpl:4: internal error: UTI-MIS-0602 chpl version 1.19.0
Note: This source location is a guess.
```

but if I change `init()` to `postinit()`, the code compiles and prints 100.

For comparison, I've tried a similar C++ code below, which seems to be working

```c++
#include <iostream>
using namespace std;

struct Cls
{
    int n;
    Cls() {
        auto& self = *this;
        self.n = 100;
    }
};
int main() {
    cout << Cls().n << endl;  // prints 100
}
```
while a similar Swift code below results in an error:

```swift
class Cls
{
    var n: Int
    init() {
        let my = self
        my.n = 100
    }
}
var a = Cls()
print( a.n )
```
If I further insert `n = 10` at the beginning of `init()` (so as to complete the initialization of properties), the code compiles and prints 100.

**Compile command:**
`chpl test.chpl`

### Configuration Information

- Output of `chpl --version`:
chpl version 1.19.0
Copyright (c) 2004-2019, Cray Inc.  (See LICENSE file for more details)

- Output of `$CHPL_HOME/util/printchplenv --anonymize`:
CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: gnu
CHPL_TARGET_ARCH: x86_64
CHPL_TARGET_CPU: native
CHPL_LOCALE_MODEL: flat
CHPL_COMM: none *
CHPL_TASKS: qthreads
CHPL_LAUNCHER: none
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: cstdlib
CHPL_GMP: gmp
CHPL_HWLOC: hwloc
CHPL_REGEXP: re2
CHPL_AUX_FILESYS: none

- Back-end compiler and version, e.g. `gcc --version` or `clang --version`:
gcc (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0

**Comment by bradcray** [comment]
I'm going to say that this is a bug in that the code as you've written it that is not intended to be supported by Chapel; yet we also don't generate an error message for it, resulting in the internal error instead.  Tagging @benharsh to get his opinion as well.

Specifically, given your initializer:

```chapel
    proc init() {
        const ref self = this;
        self.n = 100;
    }
```

Chapel's initializer design does not permit the user to do things with an object until it is fully initialized, where I'm guessing that "taking a reference to the object" is considered to be a case of doing something with it.  In this case, you could argue that what you're doing is innocuous since you're not actually referring to the object's uninitialized fields through`self`, so maybe the compiler should permit it, but it feels like a slippery slope where we'd need to have the compiler understand references taken to an object in order to understand its initialization.  In general, we've been trying to keep the initializer rules and analysis simple, which I think would mean not permitting this pattern.  So I think this should be generating an error message similar to the one you'd get if you tried to call a method on `this` before initializing it (even if that method didn't do anything unsafe with the uninitialized object).  You're welcome to lobby that we should not be so strict, of course.

If you were OK with the default initialization of the object, you could insert a this.complete() call before taking the reference to the object, forcing the compiler to complete the initialization of the object before running the rest of your code.  This seems to work and is arguably similar to the postinit() approach ([try it online](https://tio.run/##RY4xCsMwDEV3n0KjAyVJ14ZOvUFvYBSFGFzZ2KYZSs7uSgm02v77X1/C1SUKrWFwpcAjFJAZBoj5Apkw5hmehOZjlL9dBr6B5zodOuWIony1HZwJnbr60mN8pUCVbDf9DIxcqrQuUCgscD@Sf1thz4Kv43jS3exGbzqBTBvEjWnWJ7V1y75SYAtOlkS39gU)):

```chapel
    proc init() {
        this.complete();
        const ref self = this;
        self.n = 100;
    }
```

**Comment by benharsh** [comment]
I think Brad's view here is correct. For the foreseeable future I think this should be a compilation error.

**Comment by ty1027** [comment]
@bradcray @benharsh
Thank you very much for the comments, and I agree that taking a reference to `this` in `init()` should be a compile-time error if things can become unsafe/subtle/complicated. Indeed, in the code snippet above, Swift also seems to consider `let my = self` as illegal because the initialization of `self` is not completed:

```swift
test.swift:3:9: note: 'self.n' not initialized
    var n: Int
        ^
test.swift:6:14: error: use of 'self' in property access 'n' before all stored properties are initialized
        my.n = 100
             ^
test.swift:5:13: error: variable 'self.n' used before being initialized
        let my = self
            ^
```
The reason why I tried the above code is that I sometimes use a different name for the "this" variable in Python or Fortran (e.g., "me" or "my") to make the code somewhat shorter / more readable. (In those two languages, the first argument is passed explicitly to a method, so I can use any variable name.)

Now, I'm wondering if once the `init()` is completed,  is it possible (legal) to take such a reference to `this` in user-defined methods (other than `init()`)? For example,
```chapel
proc Mytype.myfunc() {
    const ref my = this;
    // math expressions using my.foo, my.baa, etc
} 
```
But if this can cause possible unsafe behaviors or more complications, I will definitely stick to "this" (no problem at all here).

**Comment by bradcray** [comment]
As far as I know, once the object has been initialized, creating const refs to it in other methods ought to be fine.  At least, I'm not jumping to any reasons that it would be problematic.
