### ISSUE TITLE
Mason: Improve mason external testing

### ISSUE THREAD

**Issue by ben-albrecht** [chapel-lang/chapel#12724]
There are a few issues with the `test/mason/spack-integration` test:

1. [x] The `fetch` line with digits replaced with `n` can sporadically mismatch due to a varying number of digits (e.g. `9.32 -> n.nn` vs. `10.21 -> nn.nn`)

2. [x] The current test installs openblas to test against the linear algebra library. This is a large program and takes a long time to build.

re: 2 - I propose we switch to testing a small C program with few dependencies. [curl](https://spack.readthedocs.io/en/latest/package_list.html#curl) or [zmq](https://spack.readthedocs.io/en/latest/package_list.html#czmq) are pretty small and already have a Chapel interface, but still have a lot of dependencies.

This is part of https://github.com/chapel-lang/chapel/issues/7106

**Comment by gbtitus** [comment]
The existing .prediff handles any number of digits, such that `10.21` will nevertheless turn into `n.n`.  However, based on the .good mismatch on 2019-03-25 it looks like the fetch perhaps prints times, which have optional minutes and always seconds, and the .prediff only works when the minutes aren't there.  I have a slight preference for continuing to match the fetch line, because then if the fetch fails it'll be obvious it did so.  If we don't match the fetch explicitly then when it fails, some other part of the check will mismatch and we'll have to surmise that it was actually the fetch that failed.  However, matching the fetch properly will admittedly take a more complicated regexp replacement, say to match `([0-9]+m )?[0-9]+[.][0-9]+s` and turn it into `<time>`.  And if there's a way to make `spack-integration` test what is intended without doing a download then by all means we should avoid that.

**Comment by ben-albrecht** [comment]
> And if there's a way to make spack-integration test what is intended without doing a download then by all means we should avoid that.

Agreed, but I'm not aware a way to accomplish this without hosting an internal spack cache that can be accessed from all of our testing configurations. I think this would be good to solve (for other areas outside of Spack integration testing too), but it won't be a trivial effort.

**Comment by gbtitus** [comment]
#12737 solves the fetch output mismatches.

**Comment by ben-albrecht** [comment]
Thanks @gbtitus !
