### ISSUE TITLE
Private distribution can leak memory

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#12731]
### Summary of Problem

The following tests that uses the Private distribution leak memory:

- [ ] modules/vass/SSCA2-with-Private-1.chpl
- [ ] modules/vass/SSCA2-with-Private-2.chpl
- [ ] parallel/forall/task-private-vars/block.chpl
- [ ] parallel/taskPar/sungeun/private.chpl

where the leaks show up as:

```
====================
Leaked Memory Report
==============================================================
Number of leaked allocations
           Total leaked memory (bytes)
                      Description of allocation
==============================================================
1          48         Private
==============================================================
```

### Configuration Information

- Output of `chpl --version`: `chpl version 1.20.0 pre-release (4d906d1)`

**Comment by mppf** [comment]
#6726 had some discussion of this; the most relevant is this:

> 
> *oh*
> If `PrivateDist` is a singleton, we have no business calling `new PrivateDist()` in test code under any circumstances. Instead, we should be following the pattern of DefaultDist, where a global (single) variable is created and that is the value used when constructing a PrivateDist. (Or a function is available to return the single instance).
> 
> Along those lines, for the `dmapped Private()` syntax to work, we'll need the compiler to somehow know that since PrivateDist is a singleton, it shouldn't turn that in to a `new`. I think we havn't seen this problem with `DefaultRectangular` because the compiler just has special support for it (and we don't write tests that `dmapped DefaultDist()`). Not certain.
> 
> Ah good point. PrivateDist and DefaultRectangular distribution descriptors claim themselves singleton using `proc singleton() param return true`. Record `_distribution` checks that and refuses to delete it in proc _do_destroy(). So these guys are pretty much guaranteed to leak. (Does our DefaultRectangular distribution leak?)
> 
> BTW what is it about PrivateDist that we need to make it a singleton? Why not `new PrivateDist()` freely and rely on reference counting to clean up?
> 
> My guess is that it's because there's no benefit in distinguishing one instance of PrivateDist() from another -- it has no distinguishing state.

**Comment by mppf** [comment]
> Does our DefaultRectangular distribution leak?

Valgrind doesn't report it as a leak, because a global variable refers to the allocated memory. Valgrind doesn't consider the PrivateDist one a leak either, actually. I'm not sure why our `--memTrack` code does not report a leak for the DefaultDist but does for PrivateDist. As far as I can tell, the singleton DefaultDist is never freed.

Note that the compiler runs the module deinitalizer for ChapelLocale *after* the module deinitializer for DefaultRectangular. So, if, the DefaultRectangular module deinitializer destroyed the singleton, we would have the possibility of a use-after-free error.

Would it be appropriate to find a way to convince `--memTrack` to not report the PrivateDist allocation as a leak?

**Comment by bradcray** [comment]
@e-kayrakli: Can this be closed now?

**Comment by e-kayrakli** [comment]
There can still be a more principled approach than what we have, but https://github.com/chapel-lang/chapel/pull/15547 closed the leak
