### ISSUE TITLE
Mason build does not check for Chapel version compatibility

### ISSUE THREAD

**Issue by tjstavenger-pnnl** [chapel-lang/chapel#12760]
For example, if in my package I execute 'mason add LinearAlgebraJama@0.1.0' and then 'mason build' while running Chapel 1.19.0, I get the following error:

```
$ mason build -M src/modules -M src/aggregation --show
Updating mason-registry
Compilation command: chpl /home/ahm/git/chgl/src/CHGL.chpl -o /home/ahm/git/chgl/target/debug/CHGL -M src/modules -M src/aggregation --main-module CHGL /home/ahm/.mason/src/LinearAlgebraJama-0.1.0/src/LinearAlgebraJama.chpl
/home/ahm/.mason/src/LinearAlgebraJama-0.1.0/src/LinearAlgebraJama.chpl:185: note: Constructors have been deprecated as of Chapel 1.18. Please use initializers instead.
/home/ahm/.mason/src/LinearAlgebraJama-0.1.0/src/LinearAlgebraJama.chpl:185: error: Type 'CholeskyDecomposition' defines a constructor here
/home/ahm/.mason/src/LinearAlgebraJama-0.1.0/src/LinearAlgebraJama.chpl:1166: error: Type 'EigenvalueDecomposition' defines a constructor here
/home/ahm/.mason/src/LinearAlgebraJama-0.1.0/src/LinearAlgebraJama.chpl:1296: error: Type 'LUDecomposition' defines a constructor here
/home/ahm/.mason/src/LinearAlgebraJama-0.1.0/src/LinearAlgebraJama.chpl:1555: error: Type 'Matrix' defines a constructor here
/home/ahm/.mason/src/LinearAlgebraJama-0.1.0/src/LinearAlgebraJama.chpl:1567: error: Type 'Matrix' defines a constructor here
/home/ahm/.mason/src/LinearAlgebraJama-0.1.0/src/LinearAlgebraJama.chpl:1580: error: Type 'Matrix' defines a constructor here
/home/ahm/.mason/src/LinearAlgebraJama-0.1.0/src/LinearAlgebraJama.chpl:1612: error: Type 'Matrix' defines a constructor here
/home/ahm/.mason/src/LinearAlgebraJama-0.1.0/src/LinearAlgebraJama.chpl:1624: error: Type 'Matrix' defines a constructor here
/home/ahm/.mason/src/LinearAlgebraJama-0.1.0/src/LinearAlgebraJama.chpl:2307: error: Type 'QRDecomposition' defines a constructor here
/home/ahm/.mason/src/LinearAlgebraJama-0.1.0/src/LinearAlgebraJama.chpl:2529: error: Type 'SingularValueDecomposition' defines a constructor here
Build Failed
```

The deprecated (and removed) support for constructors wasn't warned in any way or backported somehow, it just failed. It would be nicer to see a message about how I'm running Chapel 1.19.0 and how it isn't compatible with a package intended for 1.16.0.

**Comment by bradcray** [comment]
I'm not a mason or LinearAlgebraJama expert (so maybe should keep quiet and wait for one of them to get to work tomorrow), but am wondering:  This strikes me as arguably being an issue with the LinearAlgebraJama package's manifest in which it isn't correctly indicating that it requires an earlier version of Chapel?  (i.e., my understanding is that if the manifest says "1.16.0" it means "that version or later"; whereas "1.16.0..1.18.0" means "only these versions").

**Comment by bradcray** [comment]
Again, with the caveat that I'm not a mason expert, I believe that there is a way to have the manifest file specify a range of legal Chapel versions.  See the very last code line in this section:

https://chapel-lang.org/docs/tools/mason/mason.html#the-manifest-file

Which is what made me consider this more a problem with the package than with mason itself.  

That said, it does point to a larger problem in mason that we're wrestling with (and hopefully will improve upon this summer) which is that we don't currently have a great way to automatically test external mason packages (either ourselves, or by having their authors do so trivially) in order to catch such issues early rather than only once a new release has gone out or without a human being constantly vigilant.  There's some discussion of this on issues #9846, #12724, #10559, and #10713.

**Comment by ben-albrecht** [comment]
> my understanding is that if the manifest says "1.16.0" it means "that version or later"; whereas "1.16.0..1.18.0" means "only these versions"

That's correct. When designing mason, we made the choice to default to "this version or later" with assumption that testing infrastructure would help identify packages that broke with new versions so that we could "cap" the chapel version on the package when needed. Unfortunately, developing that testing infrastructure has not received the necessary resources yet.

> Which is what made me consider this more a problem with the package than with mason itself.

Right. I think this issue would be more appropriate on https://github.com/chapel-lang/mason-registry as "this package is broken with Chapel 1.19" and the package repository itself as  "Please update package to support Chapel 1.19".

I'll leave this issue open until we get the package manifest file updated for `LinearAlgebraJAMA`.

Thank you for reporting @tjstavenger-pnnl !

**Comment by bradcray** [comment]
@ben-albrecht / @tjstavenger-pnnl : With Ben's update to the registry, can this issue be closed now?

**Comment by tjstavenger-pnnl** [comment]
Yes -- if there were a way to somehow test or enforce this across packages, that would be optimal.
