### ISSUE TITLE
compile-time nil checking error expected but missing

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#12772]
The program below should result in a run-time (rather than compile-time) error:

``` chapel

class C { var x: int; }
  
proc main() {
  var A: [1..10] owned C;

  var buf = new owned C(1);
  A[1] = buf;

  var x = buf.x;
  writeln(x);
}
```

**Comment by DanilaFe** [comment]
@mppf: The OP seems to contradict the issue title. Is the compile-time or the run-time issue expected? On `main` today, I'm seeing a compilation error:

```
comnil.chpl:4: error: cannot default-initialize the array A because it has a non-nilable element type 'owned C'
```

This seems right to me due to an attempt to initialize an array of non-nilable C objects (even though `A[1]` presumably would get "initialized". If that's the case, I will lock in the behavior and close this.

**Comment by mppf** [comment]
I can't think of a reason it should be a runtime error. I'm going to close this (I think we have other tests of arrays of non-nilable owned being errors). Feel free to add the case above as a test.
