### ISSUE TITLE
Set compiler name during build

### ISSUE THREAD

**Issue by marcinz** [chapel-lang/chapel#12777]
### Summary of Problem

During build, a compiler can be selected using the `CHPL_*_COMPILER` variables,  but the actual names of the compiler executables are hardcoded. When building on a Mac, for example, compilers are often installed using a system like Homebrew, which gives compilers names related to their versions. For GCC 8, for example, the executables are named `gcc-8` and `g++-8`. Currently, one has to use unreliable methods to use such non-standard compiler names, such as:

```
alias gcc='gcc-8'
alias g++='g++-8'
```

It would be nice to have variables to control compiler names that would be reliable and would not require alias tricks. Perhaps using the standard `CC`/`CXX`/`LD` variables would be the easiest?

**Comment by bradcray** [comment]
It's not entirely clear to me how this would end up working with our current makefile environment.  For example, say that you set CC to `cc` which was an alias for `gcc` but then set CHPL_HOST_COMPILER to `intel` and CHPL_TARGET_COMPILER to `cray-prgenv-cray`.  What should happen?

**Comment by marcinz** [comment]
Hmm, I am not sure. But what would be the best way to handle this for brew GCC installations on a Mac? Could there be some variable such as `GCC_EXECUTABLE` that is `gcc` by default, but I can set it to `gcc-8` if I need to? `gcc` is hardcoded already for `gnu`, so it seems to me that replacing it by configurable variable with a default value should not have any impact on how things work now, but it would handle the case where I have to use the `alias` workaround.

**Comment by bradcray** [comment]
Yes, I think we could definitely implement a new override-able variable like this.  My main hesitation with the original proposal primarily related to the theme of relying on CC to indicate the default given that Chapel is often used in a cross-compilation environment where multiple compilers are involved.

That said, with additional thought, it occurs to me that (with effort) there are some other things we could do.  For example, we could have the script that infers CHPL_*_COMPILER check whether CC is set and, if so, use it to infer what compiler it is by running `$(CC) --version` and mapping that to one of our known compiler strings.  And/or, we could have the Makefile.gnu file inspect CC, check whether it seems to be gcc, and use that compiler if it is (falling back to 'gcc' otherwise).  Both of these approaches feel a bit fiddly / fragile to me compared to your proposal (in that they require recognizing and reacting to various compiler version formats across versions), but have the obvious benefit of leaning more on the standard variable.  They also have the downside of arguably becoming less important once we switch to the LLVM back-end by default (which we hope to do in this release cycle), so could end up being wasted effort.

**Comment by marcinz** [comment]
Yes, I agree about wasting effort if LLVM will be a default. I can live with aliases if necessary.

**Comment by bradcray** [comment]
I think that adding an overridable variable to Makefile.gnu permitting users to set an environment variable like your proposed GCC_EXECUTABLE would be easy and safe enough to implement that I'd be willing to take it on if you prefer it to your current approach of creating the alias.  Let me know if that's the case.

I think that making our scripts and Makefiles smarter at inspecting CC and trying to draw conclusions from them is potentially attractive but feels like a lot more work (and potentially fragile), particularly in an LLVM-by-default world.  So I would likely file those away as thoughts for the future rather than stepping up to them right now.

I should've also mentioned another workaround for those following this thread:  A sufficiently motivated user could:

* create their own clone of Makefile.gnu (calling it Makefile.gcc8, say)
* edit it to say `CC=gcc-8` and `CXX=g++-8`
* set CHPL_*_COMPILER to gcc8 in their environment to use this Makefile rather than the other

I don't mean to suggest that this is more attractive than the other options we've been discussing, just letting readers know that it's an option.

**Comment by ronawho** [comment]
I think you'd need something like `CHPL_GNU_CC_NAME` and `CHPL_GNU_CXX_NAME` (or whatever you want to call it, but I think you need to be able to specify the C and C++ compiler.

Makefile.gnu and compiler_utils.py:get_compiler_name() are the 2 places I know of that would need to be updated.

**Comment by bradcray** [comment]
If we proceeded with this, I was wondering if we could just get away with calling the variables GCC and GXX (as extensions/alternatives to CC and CXX).

**Comment by bradcray** [comment]
@mppf: While looking for another issue, I found myself thinking we could probably close this (at least based on reviewing the OP)?

**Comment by mppf** [comment]
Yes, thanks. I believe this is resolved by #17923.
