### ISSUE TITLE
confusion around casting signed integers of different sizes

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#12782]
I have this program:
``` chapel
var w = 0;
var r = -1;

var aa = r:int(32);
var bb = aa:uint;
writef("%xu\n", bb);

var z = r:int(32):uint;
writef("%xu\n", z);

var w32 = w.safeCast(int(32)):uint;
var r32 = r.safeCast(int(32)):uint;
var val = (w32 << 32) | r32;

writef("%xu\n", val);
```

I was expecting it to print out ffffffff (ie. -1 as a 32-bit integer). However it prints out ffffffffffffffff.

I think the current behavior is consistent with the behavior of C but I'm not sure I've ever understood why the C compilers do this. It seems at the very least that there is something to document about it.

**Comment by BryantLam** [comment]
Because all modern CPUs use two's complement arithmetic, C/C++ signed types effectively preserve their value through sign extension when casted. Here, the relevant cast is from int32 to uint64, which sign extends so that if uint64 was later converted back to signed int64 or intX, it would still be value -1.

[From cppreference](https://en.cppreference.com/w/cpp/language/implicit_conversion#Integral_conversions):
(When casting from int64 to int32)
> If the destination type is signed, **the value does not change if the source integer can be represented in the destination type**.  Otherwise the result is [implementation-defined (until C++20)] [the unique value of the destination type equal to the source value modulo 2^n where n is the number of bits used to represent the destination type (since C++20)].

Sign extension is usually used here when converting to a larger storage type, but isn't explicitly called out because the exception is when casting from a small unsigned value with a 1 in the leading position to a larger signed value--sign extension would yield the wrong result; padding zeroes is what should occur in this case.

(When casting from int32 to unsigned-int64)
> If the destination type is unsigned, the resulting value is the smallest unsigned value equal to the source value modulo 2^n where n is the number of bits used to represent the destination type. That is, depending on whether the destination type is wider or narrower, **signed integers are sign-extended or truncated and unsigned integers are zero-extended or truncated respectively**.

**Comment by mppf** [comment]
@BryantLam - thanks for the tip, I see that casting first to `uint(32)` makes this program work the way I want:

``` chapel
var w = 0;
var r = -1;

var aa = r:int(32);
var bb = aa:uint(32):uint;
writef("%xu\n", bb);
```

However it seems like something that should be documented somewhere for Chapel. (I created the issue because in the past we've much many such details in the specification).

But, now that I look more carefully, I see that it is documented reasonably well - 9.2.1 Explicit Numeric Conversions

> When an int is converted to a larger int or uint, its value is sign-extended to fit the new representation.

So, I'll close this issue.
