### ISSUE TITLE
require parallel iterators to co-locate with the serial iterator

### ISSUE THREAD

**Issue by vasslitvinov** [chapel-lang/chapel#12800]
Background: The current goals for Chapel 2.0 do not include improvements of our iterator story. Meanwhile we have discussed the idea of requiring the user to declare all flavors of an iterator textually close to each other. For example, if the user wishes to declare a leader and a follower iterators, they must be co-located with the corresponding serial serial iterator.

Proposal: This issue proposes to enact a restriction that all flavors of a given iterator be declared in the same scope.

Chapel code that satisfies this restriction will be easier to convert to a different syntax that requires textual co-location. At the same time, if we decide not to pursue a co-location requirement, we can remove this restriction while maintaining backward compatibility.

The proposed restriction is based on the current iterator story and may not be where we will end up eventually. However, it should be cheap to implement and will likely reduce user efforts to adjust their code to a new iterator story, should that become needed.

**Comment by bradcray** [comment]
This proposal doesn't feel all that compelling to me:  It's not clear how it will really help users (e.g., there's no indication that overloads will have to be textually co-located in the future); my guess is that there are virtually no codes in existence that would need to change even if this were implemented (because overloads probably are declared at the same scope); and it adds work to our plate that doesn't feel necessary or valuable.

**Comment by vasslitvinov** [comment]
@mppf what do you think about this?

**Comment by mppf** [comment]
The point in doing it would be to make slightly fewer changes at the time we finalize the iterators story. However if we are comfortable leaving parallel iterators out of the current effort towards the language freeze, I think this can be put off.

**Comment by vasslitvinov** [comment]
By consensus, closing this for now.
