### ISSUE TITLE
Naming for the two void concepts and the void value

### ISSUE THREAD

**Issue by daviditen** [chapel-lang/chapel#12885]
Issue #12208 seems to have come mostly to a consensus about the idea of separating the two concepts that we currently call `void`.  There was one dissenter, but the level of dissent was fairly low.  This new issue is to discuss naming the three user-visible things.  There are two types and a value.

I propose that we take @bradcray's second choice from that issue:

```chapel
proc foo(): nothing { ...return;...}  // I return no value
proc bar(): void { ...return voidValue;...}  // I return an empty value
```

I was initially feeling that we should borrow from Python's `none` and `noneType` (capitalization changes intentional), but this could lead to confusion due to possibly subtle differences between the concepts in Chapel vs. Python.

The idea in his first choice seems too easy to overlook to me.  I think a person making the effort to declare the return type is going to want it to stand out more than a single character.

```chapel
proc foo(): where abc { ...return;...}  // I return no value
proc bar()  where abc { ...return 42;...}  // I return a value
```

**Comment by mppf** [comment]
``` chapel
proc foo(): nothing { ...return;...}  // I return no value
proc bar(): void { ...return voidValue;...}  // I return an empty value
```

Since `void` is a keyword anyway, and it literally means the absence of anything meaningful, why can't it be used in both a type and value context?

i.e. `return void;` instead of `return voidValue;`, but `proc bar(): void` would still be allowed. Because the compiler knows what `void` means in each setting.

My second reaction is that is seems to run counter to precedents/expectations from working with other languages for `void` to man the second case. Since in C (e.g.) a function declared to return `void` can't return anything at all (and there is no "void value"), wouldn't `void` be a better term for the first case?

``` chapel
proc foo(): void { ...return;...}  // I return no value
proc bar(): nothing { ...return nothing;...}  // I return an empty value
```

I'm curious if others find these reactions compelling.

**Comment by bradcray** [comment]
> Since void is a keyword anyway, and it literally means the absence of anything meaningful, why can't it be used in both a type and value context?

I almost proposed this, but ended up shying away from it since Chapel doesn't syntactically differentiate between type and value expression contexts.  For example, doing so would cause an ambiguity here:

```chapel
proc foo(type t) { ... }
proc foo(x) { ... }
foo(void);
```

One reaction could be "Maybe we just don't care about cases like this (i.e., "yes, that's an ambiguity")" but it seems unfortunate to me to introduce an intentional syntactic ambiguity into the language (e.g., a human reader seeing `void` in a completely unfamiliar context wouldn't know whether it was intended to mean the type or the value; this feels squishier than most other decisions in Chapel).

> Since in C (e.g.) a function declared to return void can't return anything at all (and there is no "void value"), wouldn't void be a better term for the first case?

This was something I half-heartedly proposed back on issue #12208, but it didn't get much traction (even with myself it seems).  I'm open to reconsidering it.  If we did, we'd need to come up with something for the other case.  For example maybe:

```chapel
proc foo(): void { ...return;...}  // I return no value
proc bar(): nothing { ...return none;...}  // I return an empty value
```

**Comment by mppf** [comment]
I like the last example above better than the proposal in the issue description. It would be useful to know - for other languages that allow returning "void" in some way, what do they call it? (E.g. in Python, it is called None, right?).

**Comment by bradcray** [comment]
I've been relying on the surveys within the Wikipedia articles to see what other languages do:

* https://en.wikipedia.org/wiki/Unit_type#In_programming_languages
* https://en.wikipedia.org/wiki/Bottom_type#In_programming_languages

Many of these weren't particularly appealing for Chapel (some of the ones on the fence got discussed in #12208).

**Comment by daviditen** [comment]
I'm open to @bradcray's most recent suggestion above with `void`/`nothing`/`none`.  It's pretty close to my original thought from the other issue which was `void`/`noneType`/`none`.

**Comment by bradcray** [comment]
I'm open to it as well if the Python experts don't feel that our use of `none` would be too confusing / inconsistent with Python's (I don't feel I'm a good judge of that; I think back on issue #12208, @ben-albrecht seemed to think it scanned for him?).  I feel so-so about `nothing` but like that it doesn't introduce a camel-case type and don't have a better idea in mind.  I feel OK about `void`.

**Comment by ben-albrecht** [comment]
I noted that Chapel's `_void` was similar to Python's `None` for giving default arguments to optional args:

```chpl
proc choice(arr: [], size:?sizeType=_void, replace=true, prob:?probType=_void)
```

With this proposal, would a user still use `void` for this or would they use `none`?

**Comment by daviditen** [comment]
> With this proposal, would a user still use void for this or would they use none?

`none`.

`void` is the type of a function that doesn't return anything.

**Comment by bradcray** [comment]
Put another way, `_void` on master today would become `none` under this proposal.

**Comment by ben-albrecht** [comment]
Thanks for the clarification. In that case, I don't think this would be confusing for Python users.

**Comment by daviditen** [comment]
I think we may have a winner then. 😄

**Comment by mppf** [comment]
I'm pretty happy with this -

``` chapel
proc foo(): void { ...return;...}  // I return no value
proc bar(): nothing { ...return none;...}  // I return an empty value
```

Looking at some of the wikipedia links @bradcray posted, I see that Lisp uses `NIL` as the value of the bottom type. That makes me wonder if we could equate `_nilType` with `nothing` (presumably using `nothing` as the user-facing name) and then if we could use `nil` instead of `none`. I'm wondering in particular if any of us have considered that.

**Comment by daviditen** [comment]
I don't like the idea of combining `nil` and `none`.  IMO they are different concepts and should be kept separate. A `nil` variable exists at runtime and has a type. It can later be assigned a non-nil value.  A `none` variable is removed by the compiler and can only have a type of `nothing`.

**Comment by bradcray** [comment]
David's response here mirrors my thinking.

**Comment by mppf** [comment]
OK, works for me. Thanks for thinking about it.
