### ISSUE TITLE
`new` accepts values rather than types?

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#12886]
In Chapel 1.19.0, the following code seems to compile and run:

```chapel
class C {
  var x: int;
}

var myC = new owned C(42);
var myC2 = new owned myC;  // note: Calling `new` on a value, not a type.
writeln(myC2);
```

which suggests that `new owned` accepts not just type specifications, but also values.  The same is true for `new shared`.  This seems like code that the compiler shouldn't accept and I suspect it's just sneaking through somehow.  Interestingly, `new borrowed` and `new unmanaged` don't support this, and `new myC` generates a different error message about there being no arguments to the type (which is questionable, since it's not a type).

**Associated Future Test(s):**
[`test/classes/errors/newValueNotType.chpl`](
           https://github.com/chapel-lang/chapel/blob/master/test/classes/errors/newValueNotType.chpl
          ) #12946 

### Configuration Information

- Output of `chpl --version`: `chpl version 1.20.0 pre-release (f421723)`

**Comment by bradcray** [comment]
@mppf: Is this a known issue that I've forgotten about?  Do you agree that it should generate an error?

**Comment by mppf** [comment]
AFAIK it's not a known issue but it's not surprising (given some of the other missing errors with these patterns). I agree it should generate an error.

**Comment by bradcray** [comment]
I added a future to capture this and updated the original description to point to the future.

**Comment by bradcray** [comment]
This bug came up on gitter today.  @mppf, any idea whether it's a heavy lift or not?  (it seems like it may be relatively straightforward?).

**Comment by mppf** [comment]
This is tricker than it looks because the following two statements have the same AST representation after parsing:
``` chapel
var myC2 = new owned myC;
var myC3 = new owned(myC);
```

They are both represented as `(new (call owned myC))`:
```
  unknown myC2[198040](198039 'new'(198037 call _owned myC))
  unknown myC3[198047](198046 'new'(198044 call _owned myC))
```

the `new _owned(something)` pattern is used internally in the implementation of owned and will work for user code as a way to call the copy initializer. One way to resolve the issue might be to parse `owned` and `_owned` differently and only allow `new _owned(something)` but not `new owned(something)`. This would have user impact because `new owned(myC)` would no longer be available to run the copy-initializer.

Another strategy might be to adjust the way that we parse `new owned <the rest>` to handle that as part of the `new` rather than as part of the rest as it is handled now. However I'm having trouble getting that to work (I get too many reduce/reduce conflicts). An alternative strategy to adjusting the parser would be to get the lexer to parse `new unmanaged` etc as a single token.

**Comment by mppf** [comment]
Ah, I think I have found an alternative strategy in modifying the parser that is working.

**Comment by bradcray** [comment]
> This would have user impact because new owned(myC) would no longer be available to run the copy-initializer.

Thinking about this a bit more, it seems odd to me that we would support copy initialization of a class in this way since we don't really support copy initialization of classes in general...  I.e., I think we usually require the user to invoke a `myC.clone()` method or something like that.  If you think this is an important feature (and provided in this manner), can you explain a bit more about it to me?  (or point me to documentation if we have it).

**Comment by mppf** [comment]
@bradcray - @vasslitvinov had a similar reaction. It's not only about copy initialization, which we could arguably just insist on occurring through variable declarations. I think that issue #14300 covers the main pattern that I'm not sure there is a better way to write - which is "giving" an unmanaged to an `owned` - which you currently write as e.g. `var x = new owned( myUnmanaged );`.

**Comment by bradcray** [comment]
OK, thanks for forking off #14300.

**Comment by bradcray** [comment]
Oops, I failed to notice until now that Vass forked it off, my bad.
