### ISSUE TITLE
array.{front(), back()} vs. domain.{first, last}

### ISSUE THREAD

**Issue by ben-albrecht** [chapel-lang/chapel#12989]
As a result of https://github.com/chapel-lang/chapel/issues/8620, we now have an odd inconsistency in the array/domain interface:

- `array.front()` - first element of an array
- `array.back()` - last element of an array
- `domain.first` - first element of a domain
- `domain.last` - last element of a domain

The array methods are derived from the `{push, pop}_{front, back}` methods (inspired by C++ `std::vector`), while the domain method names are intended to disambiguate **first** and **last** elements from **lowest** and **highest** elements which is important for domains with a negative stride.

**Comment by bradcray** [comment]
IMO, front and back only make sense for 1D arrays/domains, and be deprecated on arrays once the array-as-vec/list capabilities are moved into their own type (e.g., issues #9452 #12411 ).  first and last are also arguably somewhat 1D in nature, though not quite as bad, in my opinion, since they could be thought of as relating to serial iteration order (which both 1D and multidimensional objects support).

**Comment by ben-albrecht** [comment]
@bradcray - I like those opinions. What are your thoughts on adding `array.first` and `array.last` 
 when we deprecate `array.front()` and `array.back()`? This would be more concise than relying on the domain accessor:

```chpl
arr[arr.domain.first];
// vs
arr.first;
```

**Comment by bradcray** [comment]
I'm definitely open to that.  There's also `.low` and `.high` where for a range, low/high and first/last differ for negative strides.  Negative strides and domains/arrays have always been a little weirder, though (intentionally, but potentially confusingly), so that might require more thought before jumping right in.

**Comment by ben-albrecht** [comment]
@bradcray - do you think this is worth pursuing for 1.20 release?

**Comment by bradcray** [comment]
I continue to be a little nervous about what these should mean for negatively strided domains and issues like #13174 don't help with that nervousness.  I guess I'd like to see a pretty robust proposal for what we'd expect to do there.

**Comment by jabraham17** [comment]
Closing, arrays and domains are now unified on `.first` and `.last`

- https://chapel-lang.org/docs/main/language/spec/arrays.html#ChapelArray.first
- https://chapel-lang.org/docs/main/language/spec/arrays.html#ChapelArray.last
- https://chapel-lang.org/docs/main/language/spec/domains.html#ChapelDomain.first
- https://chapel-lang.org/docs/main/language/spec/domains.html#ChapelDomain.last
