### ISSUE TITLE
Thoughts on more scalable spin locks

### ISSUE THREAD

**Issue by ronawho** [chapel-lang/chapel#13016]
Placeholder to discuss better and/or more scalable spin locks than simple test-and-testAndSet locks. To start I'm imagining this issue will be about within node locks, but we can create additional issues for across node ones.

**Comment by ronawho** [comment]
Some existing discussions: 
 - https://github.com/chapel-lang/chapel/issues/9881#issuecomment-397706537
 - https://github.com/chapel-lang/chapel/issues/13012#issuecomment-492044820

**Comment by cassella** [comment]
Some experience from the Linux kernel side is that simple spinlocks
have severe NUMA-unfairness issues.

The Linux kernel moved from simple spinlocks like these to
ticket-based spinlocks in 2008, described here:

https://lwn.net/Articles/267968/

(The code is of course GPL.  The article doesn't include any code.)

The article describes the motivation for the change:

> On an 8 core (2 socket) Opteron, spinlock unfairness is extremely
> noticable, with a userspace test having a difference of up to 2x
> runtime per thread, and some threads are starved or "unfairly"
> granted the lock up to 1 000 000 (!) times.

The unfairness was particularly related to the "2 socket" part -- if
the spinlock resides in numa node 0's memory, the threads on numa node
1 would be starved.  I expect the unfairness becomes more extreme if
your numa nodes have more than the 2008-era 4 cores.


The kernel has since moved on to mind-bendingly complex queued
spinlocks, which reduce the amount of cacheline bouncing for
highly-contended locks,

https://lwn.net/Articles/590243/

**Comment by ronawho** [comment]
Closing, this is just a place to capture information, and we can continue doing so, but there's no real action items here.
