### ISSUE TITLE
Doc cleanup: Split domains and arrays

### ISSUE THREAD

**Issue by BryantLam** [chapel-lang/chapel#13036]
I'm getting a bit confused trying to read through the [Domain and Array Operations](https://chapel-lang.org/docs/master/builtins/ChapelArray.html) section of the documentation.

For example, the last subsection [Functions and Methods on Arrays and Domains](https://chapel-lang.org/docs/master/builtins/ChapelArray.html#functions-and-methods-on-arrays-and-domains) is difficult to quickly scan through. This documentation could use a bit of rework to e.g., split it into four separate subsections:
- domain functions
- domain methods
- array functions
- array methods

**Comment by rajpratyush** [comment]
Can I take up this issue if it is not yet stale?

**Comment by lydia-duncan** [comment]
I don't think it's stale, but I think taking on this issue would involve some discussion and may be best suited when done with strong help from someone that is very familiar with our arrays and domains (I have reasonable knowledge here, but I'd prefer someone on the core team with more knowledge stepped in - maybe ask for assistance in the Chapel Gitter channel?).  It may help to go through and formulate a proposal for how you'd like to see the docs improved (maybe by cutting and pasting the docs around rather than modifying the documented code explicitly)

**Comment by bradcray** [comment]
@rajpratyush : Though I'd love to snap my fingers and see this fixed, I'd suggest not getting entangled in this particular issue.  I think it's going to take a lot of work from the core team to get done, is already on our roadmap to try and get to in the next 6-12 months, and I think trying to work on it externally would be challenging.  I appreciate the offer to help, but I think this issue would make you more sad and frustrated than fulfilled.

**Comment by lydia-duncan** [comment]
I think this has been resolved by Andy's work on moving this information into the spec
