### ISSUE TITLE
Multilocale interoperabilty: Chapel strings discussion

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#13055]
This issue is for discussing how to handle Chapel string arguments and return types in multilocale library exported functions (*not* c_string arguments and return types)

TODO: fill in with notes tomorrow when I have my notebook with me

**Comment by bradcray** [comment]
I view the goal of this issue as being to enable use cases like https://github.com/chapel-lang/chapel/issues/12892.

In sprint planning and an earlier conversation, @dlongnecke-cray indicated that @mppf had concerns about strings given that their default intent for argument passing is "by reference" and multi-locale libraries don't share memory between the client and server.  My thought there was to have multilocale library mode issue a compiler error when exporting a routine that takes a string argument that doesn't use `[const] in[out]` intent (where `in` and/or `const in` are the two cases I'm most interested in for the short-term).

**Comment by mppf** [comment]
@bradcray - So far, @dlongnecke-cray has implemented such support for c_strings. I agree that we need to engage with the harder (and more general) task of exporting Chapel data types to C code - but I wonder if it would make sense to support `in`, `out`, and `inout` intent with `c_strings` that would do copies assuming that the string is null-terminated?

**Comment by bradcray** [comment]
> I agree that we need to engage with the harder (and more general) task of exporting Chapel data types to C code

If by "exporting Chapel data types to C code" you mean "giving external languages access to Chapel's string type and its methods," that's not what I'm proposing we do here.  Personally, I don't think we should worry about that capability yet and don't consider it necessary for this issue.  As outlined in #12892, I think that if I export a Chapel function that takes or returns a string, it should interoperate directly with Python strings (say) as opposed to being a way of giving Python access to the Chapel string type and its methods.  For me, the vision is similar to how Fortran arrays become Chapel arrays when passed into a Chapel array formal, and how Python integers become Chapel `int`s rather than `bigint`s.  But I think #12892 says it better than I have here.

Maybe put another way, I don't think that the Chapel programmer should bear the burden of exporting routines that accept/return `c_string` and then converting those cases to Chapel `string` themselves at the boundaries of the exported routines; rather, I think the compiler should be stamping out this boilerplate code for them so that `string` in Chapel ends up looking like the external language's string on the other side of the interop.

**Comment by dlongnecke-cray** [comment]
I've been brainstorming what this implementation is going to look like for single locale, and I'm not quite sure yet...

This is for exporting Chapel to C, to start with. Python interop would build on top of this (hopefully without too much more effort).

Since @lydia-duncan played a large part in implementing exports for arrays, I figure you'd have a good idea of what this might look like under the covers.

---

A) Silently convert Chapel `string` to [`const`]`char*` under the covers.

This would be the simplest option. Without even a length, it would rely on the buffer being null terminated in order to fetch the length when performing conversions.

Converting to `const char*` presents the same problem we experience with `c_string` right now, which is that you have to cast to `void*` to shed the `const` qualifier when freeing.

If we wanted to convert to `char*` instead, I'm not sure how to make Chapel aware of the existence of such a type.

---

B) Provide a wrapper for Chapel `string` in the spirit of `chpl_external_array`, perhaps something called `chpl_string_wrapper` or the like.

This would look something like:

```c
typedef struct {
    void* data;
    int64_t length;
} chpl_string_wrapper;
```

- This looks awfully similar to the type definition for `chpl_external_array`.
- I would like to have _data_ be a `char*` instead, but am not sure how I would map that into an `extern record` on the Chapel side.

---

C) Convert Chapel `string` into `chpl_external_array`.

- Not sure exactly what this would entail.
- It would avoid the duplication of wrapper type definitions.
- We could generalize the concept of converting to a `chpl_external_array` so that it becomes something akin to "export this chunk of data".

If we chose this option, then we solve two problems in one go: by supporting `chpl_external_array` in multi-locale interop we would also end up supporting Chapel strings.

If we wanted to differentiate the types, we could create a record called "chpl_string_wrapper" or the like that itself contains a `chpl_external_array` and abides by the same semantics.

---

D) Convert Chapel `c_string` to a wrapper type under the covers, something like `c_buffer`, which is a buffer with a size. Then insert conversion code to convert Chapel `string` to `c_string` and from `c_string` to `c_buffer`.

---

I've identified the point in the compiler where conversion calls and type transformations happen for `chpl_external_array`, which is `fixupExportedArrayFormals`. I figure code to transform Chapel `string` would look somewhat similar, and could be called in the same exact pass.

**Comment by bradcray** [comment]
(A) is the kind of thing I'm envisioning.  Given:

```chapel
export proc foo(in x: string): string) { ... }
```

say, I imagine the compiler producing something like:

```c
// this is the routine that C / Python via Cython would call
[const] char* foo([const] char* x) {  // or maybe we'd want to return the string via an argument?
  string_chpl x_chpl = c_char_star_to_chpl_string(x);
  string_chpl retval = foo(x_chpl);
  return chpl_string_to_c_char_star(retval);
}

// this is the Chapel routine that the above calls and that Chapel programmers would call
string_chpl foo_chpl(string_chpl x) {
  ... normal implementation of foo ...
}
```

where you should view all of the above as a really rough sketch (e.g., I'm not sure what const-ness to use, we may turn returns of strings into arguments, etc.).  We'll also need to change things depending on the intents used (where, again, my expectation is that certain modes may only allow `in/out` intents, for example to get around the "no shared memory" issue for multi-locale libraries, cases where the string formats don't match in situ, etc.)

I believe that this pattern is very similar to what we do for Fortran arrays, just that we're converting from / to different types, where the externally visible function takes care of all the translations and the user is none the wiser.  Tagging @daviditen since he spearheaded that effort.

**Comment by bradcray** [comment]
PS — The `const char*`s in my example above _could_ be replaced by `c_string`s, though personally I'd like to see `c_string` ultimately be retired in favor of things like `c_ptr(char)` if possible...  But this may be a quicker intermediate step given that we already have some `c_string` support.

**Comment by mppf** [comment]
> I would like to have data be a char* instead, but am not sure how I would map that into an extern record on the Chapel side.

Just use `c_ptr(c_char)`.

I have some concern that A wouldn't allow strings that contain the zero byte in them to move around properly. But perhaps that is an acceptable limitation for the time being.

I'd probable personally go with B of the options above but A is OK if we are comfortable with strings with zero bytes in them behaving in a potentially surprising manner. Arguably this is reasonable because we might want a `bytes` type to handle non-UTF-8 data and that could use a different strategy that enabled the zero bytes.

**Comment by lydia-duncan** [comment]
My initial impression is that A or B would be fine, though note that by following A we will lose information stored on the `_string` record, such as:
- the size the string buffer can extend to without needing to reallocate (`_size` field, as opposed to the `len` field)
  - This may impact cleanup of the string?
- the `isowned` field
  - This seems like it will complicate clean up and potentially lead to leaked/double freed memory
- and the locale on which the string lives (`locale_id` field)
  - Without this, we would probably have to copy the string to locale 0 before passing it to the user, and any string received by the user would be assumed to live on locale 0.  If we followed strategy B, we could explicitly provide a "localize me" strategy for the user.

I would be curious to hear @dmk42's thoughts on this as well.

**Comment by dlongnecke-cray** [comment]
I never considered the possibility of embedding null bytes into the string as @mppf suggests, but I believe that this is quite possible in a language such as Python. Since Python is our primary interop target, this makes option B seem a bit more attractive than option A at this time.

Option A precludes the possibility of needing to carry additional information with the string in the future (there may not be any, to be fair), while with B we can always add another field to the wrapper struct.

I'll go ahead and proceed with option B for now, unless anyone has further objections. Just sketching out my changes for now.

**Comment by bradcray** [comment]
> Since Python is our primary interop target

I don't know if I'd go _that_ far...

If I was simply a C programmer, what does Cython do to handle Python strings with intermediate zero bytes?  And do we need to go any further than they did?

**Comment by dlongnecke-cray** [comment]
The C programmer would have to interact with the wrapper struct, which contains a byte (`char*`, really) buffer with a length (`int64_t` length). The buffer is guaranteed to be null terminated but may contain embedded null characters (?).

Ideally, the Python programmer would only be exposed to a Python string, and wouldn't be aware of any intervening translation.

I know we would like the same for C, ideally, but then how do we address the possibility of embedded null bytes as was brought up by @mppf?

**Comment by lydia-duncan** [comment]
I believe there are ways to create Python strings of a specified length and then fill them in.  The encode/decode translation between `str` and `bytes` might make things trickier.

**Comment by bradcray** [comment]
> The C programmer would have to interact with the wrapper struct, which contains a byte (char*, really) buffer with a length (int64_t length).

That sounds pretty awful to me (see the original issue's request for C).  I think that given C's definition of "strings", translating a Chapel string that contains NULL bytes into a C string, it would be completely reasonable for C to stop early.  (Or possibly for the wrapper that's translating to C to issue a warning or error saying that the string contains NULL bytes so some of it won't be accessible from C; or possibly for the author of the routine to have to export both the string and an integer length field in their routine).

I'm more open to using a more elaborate implementation for Python as long as the Python programmer was none the wiser (i.e., it was all hidden within the wrapper / Cython code).  And I don't think there's any need to use the same implementation for all languages since we know what we're exporting for due to the `--library-*` flag.

I also think there ought to, ultimately, be a way to pass out the Chapel string representation unperturbed, I just don't think that should be the default behavior for exporting strings.

**Comment by dlongnecke-cray** [comment]
Python / higher level language wrappers are built on the C wrapper, which means we'd see a difference in the semantics of exported C functions when going between `--library-python` and `--library` (the former would export a wrapper struct, the latter a `const char*`).

To me such differences seem rather unintuitive.

For the sake of simplifying the implementation, I would prefer to build on only a single "wrapper type" rather than many.

If we can live with the above differences, then we can do something akin to: "if exporting a C library, strings are exported as `const char*`, in all other cases, export and build on top of the wrapper struct".

**Comment by bradcray** [comment]
> Python / higher level language wrappers are built on the C wrapper, which means we'd see a difference in the semantics of exported C functions when going between --library-python and --library.

That's potentially right.  As requested / proposed in #12892, I believe that when we're exporting to a given language, we should support a natural use of strings in that language.  If the only way to get that in Python is to map strings to different types in C vs. Python, so be it.  That said, I still don't feel completely convinced that a wrapper type is necessary, at least on day one for this feature (file a feature request for strings containing NULL bytes in exported functions for now and move on?).  And I wouldn't want to invest too much into creating a wrapper type if Cython's going to have trouble passing them through anyway...

> For the sake of simplifying the implementation, I would prefer to build on only a single "wrapper type" rather than many.

I think it would be fine to focus on supporting strings for a single language for now (preferably Python), but I don't think a C programmer who wants to pass "hi" into their Chapel program should have to create a wrapper record out of their string in order to do so.  I think this is a case where the implementation should be willing to be more complex to make the user's life simple (pay the implementation cost once, benefit from it over and over again).

**Comment by lydia-duncan** [comment]
> I still don't feel completely convinced that a wrapper type is necessary, at least on day one for this feature

Note that it will be more of a backwards compatibility breaking change to alter the type users have to pass to an exported function rather than the innards of a type.  But this is still new territory so maybe we're okay with that?

**Comment by dlongnecke-cray** [comment]
After some deliberation, I've decided to map exported Chapel strings to `c_string` as @bradcray is suggesting rather than a wrapper struct. If embedded null bytes turns out to be a problem down the line, we can address that issue then.

**Comment by bradcray** [comment]
> Note that it will be more of a backwards compatibility breaking change to alter the type users have to pass to an exported function rather than the innards of a type.

I don't understand why that would be the case.  The vision presented in #12892 and [above](https://github.com/chapel-lang/chapel/issues/13055#issuecomment-501116916) is that I pass in my language-native string (whatever is most naturally a string in the language) into Chapel and that the compiler does whatever wrapping/unwrapping is necessary to turn it into a Chapel string.  Whether a `[const] char*` or some other sort of "external_string" type is used by that wrapper, the user / client should be unaware of it, and their code should not need to change if we change this compiler-generated wrapper code.

**Comment by lydia-duncan** [comment]
That sort of unwrapping will drop locality and other information on the floor.  We carry that information around for a reason, it seems entirely reasonable to me that a user will want to maintain it when they get a string from Chapel.  Otherwise, they are forced to pay the cost of localizing a string before returning it, even if they want to send it on to an exported function that would operate on the same locale as the original Chapel string.  I don't see a way to provide that information compactly without using a wrapper, so if we found that really users wanted it we would have to update the type.

One could argue that we could provide this wrapper as an alternative version that would maintain the locality and other information - my argument against this is that we would then be supporting 3 string strategies instead of 2, which is a maintenance burden and potentially a source of confusion for users and the compiler (which seems especially unnecessary when the original second string strategy has "C string" built into the name).

One could also argue that the user could write such a strategy themselves - personally, I find that much higher of a demand than asking the user to call `.c_str()` when they want to work with native C strings.  Though that does depend on what we think the more common use case is - working with a string that was originally in Chapel or working with a string that was originally in another language.

**Comment by bradcray** [comment]
> That sort of unwrapping will drop locality and other information on the floor.  We carry that information around for a reason, it seems entirely reasonable to me that a user will want to maintain it when they get a string from Chapel.

I disagree, particularly for common cases of multi-locale interoperability.  I believe the case we should be focused on is copying strings in and out of Chapel, not on passing references to Chapel string objects in and out of Chapel (which we could support in the future via an "opaque string" or "Chapel string" export rather than a simple "string").

> Otherwise, they are forced to pay the cost of localizing a string before returning it, even if they want to send it on to an exported function that would operate on the same locale as the original Chapel string.

But we're talking about either shared-memory libraries, in which case there are no other locales than the single one, or multi-locale libraries, in which case the front-end / client code isn't running on any of the locales (or at least can't assume it is).

> which seems especially unnecessary when the original second string strategy has "C string" built into the name

But we are trying to retire `c_string`s...

**Comment by lydia-duncan** [comment]
> But we are trying to retire `c_string`s...

Oh, I must have missed that.  That definitely removes my argument on the number of supported strategies.

**Comment by mppf** [comment]
> After some deliberation, I've decided to map exported Chapel strings to c_string as @bradcray is suggesting rather than a wrapper struct. If embedded null bytes turn out to be a problem down the line, we can address that issue then.

This is absolutely fine with me. As I said in my earlier comment, I think it's probably reasonable to expect people to use a `bytes` type if they want to handle null bytes in the interop argument passing.

**Comment by bradcray** [comment]
I'm not sure whether this discussion is still ongoing or resolved, but thinking more about Lydia's point:

> That sort of unwrapping will drop locality and other information on the floor. We carry that information around for a reason, it seems entirely reasonable to me that a user will want to maintain it when they get a string from Chapel.

I would expect this to come up more if/when an exported function returned a reference to a string (which I'd propose we not worry about in the short-term), not when it simply returned a string value.  By analogy, when an exported routine passes or returns an integer, it copies the value in / out, it doesn't pass a wide pointer / reference to the integer around.  I think strings should be similar in this regard (and proposed above that we only support passing strings into multi-locale exported routines by `in` intent to help ensure that this is the case for the near-term).

**Comment by dlongnecke-cray** [comment]
I'm leaving this discussion open until the implementation PR is up, just in case!

Now is the time that I should ask about supported intents. Should I have my code emit an error if an exported function has a string formal that does not have the `in` intent?

And what about return values?

a) Are return `c_string` values themselves a copy of the `string` buffer?
b) Are they a handle to the buffer, which the original string's destructor may free?
c) Are they a handle to the buffer, which the original string has relinquished (and thus will not be freed by the `string` destructor)?

**Comment by bradcray** [comment]
> Should I have my code emit an error if an exported function has a string formal that does not have the in intent?

For multi-locale library compilation, I'd think so.  For single-locale it doesn't seem as obviously necessary (but would be fine with me if it helps make progress).

> And what about return values?

I'd similarly error for returning a string by ref intent for multi-locale libraries.

I don't know the answers to your questions about `c_string`s and am hoping they largely go away, at least in the user's view of things.

**Comment by dlongnecke-cray** [comment]
There is a big problem to do with type elision if we only map `string` to `c_string` in exported functions.

Consider the following exports:

a) `export proc foo(): c_string`
b) `export proc bar(): string`

In the current world, both A and B are converted to the following exported C signature:

a) `c_string foo(void);`
b) `c_string bar(void);`

However, the implied vs actual semantics for these functions are very different.

a) For A, the original return type of the function is `const char*`. For C users, a return type of `const char*` implies that the caller is not responsible for cleaning up the memory that is returned by the function. Since there is a one-to-one mapping between Chapel's `c_string` and C's `const char*`, this reasoning holds, and we can say that it is always the _callee's_ responsibility to cleanup a returned `c_string` (if necessary at all).

b) However, the same reasoning does not hold when we start converting Chapel `string` to `c_string`. When we convert a Chapel `string` to a `c_string`, we have three options with regards to memory allocation:

- Get a handle to the string's buffer via `c_str()`.
- Get a handle to the string's buffer via `c_str()`, and set `isowned=false` to prevent the string's destructor from freeing the buffer.
- Return a copy of the string's buffer. (Possibly via `in` intent, or manually).

The first option is unreasonable - it will cause undefined behavior.

The second option perverts the implied semantics of a `c_string` / `const char*` return type, because the returned `c_string` may need to be deallocated. Whether or not it needs to be deallocated depends on whether the original Chapel string owned its buffer or not.

The third option is the most consistent because it always returns a dynamically allocated `c_string`. However, by returning a dynamically allocated `const char*` / `c_string`, we still leave C programmers confused and annoyed.

We already have to write `free((void*) someCstring);` today for multi-locale interop of `c_string`, which I consider to be quite distasteful.

---

After discussing (blabbering at, really) with @lydia-duncan, I'm leaning towards the following rules for exporting Chapel `string`...

The following Chapel signature:

`export proc foo(s: string): string`

Will be exported as:

`char* foo(c_string);`

That is to say:

- String formals in exported Chapel functions are converted to `c_string` / `const char*`
- String return types in exported Chapel functions are converted to `char*` / `c_ptr(char)`

This implies the following semantics for single-locale Chapel programs:

- String actuals converted from passed in `c_string` arguments will always have `needToCopy=false`, they do not own their buffer.
- The `char*` buffers returned will _always_ be dynamically allocated, and it is the end user's responsibility to free them.

To me, this solution provides the most consistent semantics, that can help deal with the problems explored above.

Oh, and, @mppf it would be great if you could weigh in on this issue.

**Comment by mppf** [comment]
@dlongnecke-cray - I think that when considering the design options, you should imagine that `c_string` does not exist at all and instead people are using `string` or `c_ptr(c_char)` at the Chapel level. Then, these turn into `char*` arguments with different semantics in C. I don't view that as a problem but it might be reasonable to e.g. put a comment next to function prototypes in any generated header files about the Chapel code they were converted from.

**Comment by dlongnecke-cray** [comment]
Ok, so instead I should just map Chapel `string` to `char*` only, instead of making formals const? I feel like my original idea is able to convey the semantics of the remapping as clearly as possible, while:

`export proc foo(s:string): string` -> `char* foo(char* s);`

Might leave a C programmer wondering whether he can make a call like this:

`foo("Some string literal");`

Because the formal `s` is not const.

**Comment by mppf** [comment]
You can pass not-const actual to a const formal. The const argument just means that the function called won't modify it. We need the ability to talk about pointer-to-const (for other reasons) and so if the constness becomes important for this work we'll need to address that by adding e.g. `c_ptr_const` and use `c_ptr_const(c_char)`.

**Comment by dlongnecke-cray** [comment]
In this case I am worried more about what the types might convey rather than the (in)ability to do so. As a C programmer, when I see a `char*` formal I have an expectation that the string will be modified, so I'm not going to pass a string literal (ah, you made a lightning edit).

**Comment by dlongnecke-cray** [comment]
With the upcoming merge of https://github.com/chapel-lang/chapel/pull/13357, I think it is safe to say that discussion on this issue has been brought to a close.
