### ISSUE TITLE
When using slurm-gasnetrun_ibv, mpi influences the number of threads

### ISSUE THREAD

**Issue by marcinz** [chapel-lang/chapel#13082]
### Summary of Problem

When using slurm-gasnetrun_ibv, the choice of underlying MPI influences how many threads are spawned by Qthreads. For example, with MPICH2, a maximum number of threads is used, but with Openmpi only one thread is launched. To work around that issue, the following is necessary for OpenMPI:

`setenv MPIRUN_CMD  "mpirun --bind-to none -np %N %C"`

This is very surprising. 

In the least, a naive user would benefit from being warned that only 1 thread is used even if more cores are available.

**Comment by marcinz** [comment]
@ronawho

**Comment by bradcray** [comment]
Capturing some notes from chat, largely paraphrasing Elliot:

* The `*gasnetrun_ibv`-based launchers use `mpirun` to launch programs by default

* By default OpenMPI's `mpirun` limits affinity to a single core.  This causes Chapel's querying of the number of cores to get `1` as the result, due to OS limiting.

* OpenMPI's `--bind-to-none` flag can be used to override the above default.

* Setting MPIRUN_CMD can be used to tell `gasnetrun_ibv` to use a different `mpirun` command.  

* Therefore, setting `MPIRUN_CMD ="mpirun --bind-to none -np %N %C"` can be used for such launchers when using OpenMPI to override the default.

* `numPUs(accessible=false)` returned the right number of cores (not surprisingly), so could potentially be used to generate a warning if there was a large difference between the accessible=true and accessible=false values.

* Elliot writes "Whether MPI limits affinity is mpi vendor and version specific. There is no universal way to disable binding so we can't just set something on our end. We'd probably need to work with the gasnet team to have some option we can set that they then translate to the different mpi vendors."  My impression is that there are really only 2 (or maybe 2-1/2) core MPI implementations (MPICH, OpenMPI, and possibly MVAPICH), and I'd guess that this is an area that vendors wouldn't customize much, so it seems plausible to me that we (ideally through GASNet) could do something smart for OpenMPI-based implementations to avoid having to set MPIRUN_CMD.

**Comment by ronawho** [comment]
@bonachea @PHHargrove we're running into an issue where OpenMPI defaults to binding processes to a single core by default. Users can work around this by passing `--bind-to none`, but we're looking for a more general way we could tell the gasnetrun_* launchers that we want to disable any binding the backend launcher might do.

For `gasnetrun_mpi.pl` it seemed pretty easy to extend the `-c` processing for OpenMPI and throw `-bind-to none` when `-c 0` is given, but then I saw `gasnetrun_ibv.pl` doesn't have an equivalent `-c` option. Any thoughts or advice here?

**Comment by PHHargrove** [comment]
@ronawho 
I think you have identified a deficiency in `gasnetrun_ibv.p`.  It should take a `-c N` option, even if for no other purpose than to pass it through to `gasnetrun_mpi.pl` when using that for the actual spawning.
Would you mind entering a bug report at https://gasnet-bugs.lbl.gov/bugzilla ?

**Comment by ronawho** [comment]
Thanks @PHHargrove -- I opened https://upc-bugs.lbl.gov/bugzilla/show_bug.cgi?id=3946

**Comment by bonachea** [comment]
Proposed fix now available for testing:

https://bitbucket.org/berkeleylab/gasnet/pull-requests/277

**Comment by ronawho** [comment]
Awesome! I'll give a try first thing tomorrow morning

**Comment by ronawho** [comment]
Patch from the GASNet teams works for me. @marcinz and/or @LouisJenkinsCS if you get a chance can you verify that https://github.com/chapel-lang/chapel/compare/master...ronawho:proto-gn-affinity-fix resolves this for you (and eliminates the need to set `MPIRUN_CMD`)

**Comment by bonachea** [comment]
@ronawho : Thanks for validating the fix.

The gasnetrun improvement will be available in the GASNet 2019.6.0 release which should be available for download in eight days (June 14th).

We'd strongly advocate you simply incorporate our forthcoming release (which has numerous other fixes and improvements), rather than continuing to cherry-pick fixes to the 9-month-old release.

**Comment by bradcray** [comment]
> We'd strongly advocate you simply incorporate our forthcoming release (which has numerous other fixes and improvements), rather than continuing to cherry-pick fixes to the 9-month-old release.

Elliot's out today, but I don't doubt we'll do this.

**Comment by ronawho** [comment]
Yup, plan is to update to latest gasnet version. I wasn't sure of the timing for your June release, so I was debating between upgrading to 2019.3.2 and cherry-picking or just waiting for 2019.6. If it's only a week away, I'll likely just wait.

**Comment by ronawho** [comment]
@marcinz and/or @LouisJenkinsCS this should be resolved with https://github.com/chapel-lang/chapel/pull/13311 and https://github.com/chapel-lang/chapel/pull/13353.
