### ISSUE TITLE
module use pollutes local scopes due to public/transitive `use ChapelStandard`

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#13118]
[Forked from @bryantlam's comment: https://github.com/chapel-lang/chapel/issues/13041#issuecomment-496724325]

### Summary of Problem

The `use` of a seemingly innocuous library module can eclipse user variables when there are naming conflicts due to the compiler-injected `use` of `ChapelStandard` which, like all `use`s currently, is transitive by nature.  I believe the fix here is to implement `private use` (issue #6093) and then utilize it for the compiler-injected `private use ChapelStandard`).

### Steps to Reproduce

**Associated Future Test(s):**
[`test/modules/use/usePollutesDueToChplStandard.chpl`](
           https://github.com/chapel-lang/chapel/blob/master/test/modules/use/usePollutesDueToChplStandard.chpl
          ) #13117

### Configuration Information

- Output of `chpl --version`: `chpl version 1.20.0 pre-release (f8efa5c)`

**Comment by lydia-duncan** [comment]
A simple modification to `use ChapelStandard` privately resulted in DefaultDist "having an illegal super class".

I have a vague memory that we might do some fun stuff where we only insert the use of ChapelStandard if the module doesn't have other uses . . .

**Comment by bradcray** [comment]
Does putting a `private use ChapelDistribution;` into `DefaultRectangular.chpl` resolve that error?

**Comment by lydia-duncan** [comment]
Yup, but then we encounter it for DefaultAssociative.

> I have a vague memory that we might do some fun stuff where we only insert the use of ChapelStandard if the module doesn't have other uses . . .

If my memory serves (and I'm not making this up), we did that as a stopgap and that it would be appropriate to remove that special case code in favor of privately using ChapelStandard.

**Comment by bradcray** [comment]
My (vague) recollection is that we stopped auto-inserting `use ChapelStandard;` into internal modules at all.  So it may be that things compile on master today because the modules that they use explicitly `use ChapelStandard;` themselves and result in those modules becoming available transitively.  So I view the need to insert new `use`s into internal modules to fulfill their requirements as a sign that your branch is working correctly and that we're making the dependences in the internal modules more explicit (which I think was the goal of not inserting `use ChapelStandard;` into them to begin with: to have them state their dependences clearly and avoid the circularities that occurred when all internal modules included each other).

**Comment by lydia-duncan** [comment]
Oooh, that also sounds familiar!  Okay, I'll keep pushing along this path, then.

**Comment by lydia-duncan** [comment]
I am down to 7 failures on a rebased version of the branch.  This is after a few merges to master so that I could disentangle them from the other error messages.

I still need to look into the cause of these four.  I suspect that is only really two errors remaining.
[Error matching compiler output for interop/fortran/genFortranInterface/chapelProcs]
[Error matching compiler output for interop/fortran/genFortranInterface/uintWarnings]
[Error matching compiler output for interop/fortran/genFortranInterface/unhandledType]
[Error matching compiler output for library/standard/List/bradc/emptySeq3]

These three are not entirely unexpected and will be resolved once everything else has been cleaned up (to avoid wasting time continually updating them):
[Error matching program output for modules/bradc/printModStuff/foo]
[Error matching program output for modules/sungeun/init/printModuleInitOrder]
[Error matching program output for modules/vass/deinit-order-modules (compopts: 2)]
