### ISSUE TITLE
unorderedCopy only supported for numeric types?

### ISSUE THREAD

**Issue by BryantLam** [chapel-lang/chapel#13113]
Is there a rationale for why the following doesn't work? I'm not sure what the ramifications are for expanding support to all bit-copyable types instead of just numeric ones.

```chapel
use UnorderedCopy only;

record R {
  var x: int;
}
var a = new R(1);
var b = new R(2);
UnorderedCopy.unorderedCopy(a, b);
// error: unorderedCopy is only supported between identical numeric types
```

**Comment by ronawho** [comment]
unorderedCopy will eventually be extended to support all POD types. Today it's numeric only so that we could start with a simpler runtime implementation. https://github.com/chapel-lang/chapel/issues/13052#issuecomment-494440435 has some more info.

For an example of why this made the implementation simpler, if you have something like:

```chpl
var rArray: [1..10] R;
for i in 1..10 {
  var r = new R(i);
  unorderedCopy(rArray[i], r);
}
```

The runtime interface takes the address of the src/dst but in this case the src is overridden each iteration so we have to store the value in a separate buffer and use the address of that buffer instead of the original one. Today that buffer is only 8 bytes, so we limited the user-API to numeric types. Longer term we would like to support all POD types, but then we have to be careful about not creating too large of buffers (and avoiding copies for large types.)

Alternatively you could argue that the lifetime of the src needs outlive the unordered fence so maybe that example should be illegal.

**Comment by BryantLam** [comment]
(I was trying to use unorderedCopy on bools and ran into this issue.) This limitation seems like a place where I'd consider querying the size of a type and implement unorderedCopy differently if the size was too big or e.g., emit a not-implemented error.

**Comment by ronawho** [comment]
Ah, the bool case is probably just an oversight, not a technical limitation. 

FWIW a lot of the initial effort was trying to figure out how to match the performance of UPC for Bale and for that the restricted API was ok. The rough plan is to:
 - flesh out the unordered operations (optimize unorderedCopy for PUTs, add fetching atomics)
 - extend unorderedCopy to all POD types
 - implement unordered operations in non-ugni comm layers

I'm currently working on optimizing unorderedCopy for PUTs, but I'll take a quick at extending for bools now.

**Comment by ronawho** [comment]
unorderedCopy on bools should be supported as of https://github.com/chapel-lang/chapel/pull/13123

**Comment by ronawho** [comment]
`unorderedCopy` now supports all POD types. (Implemented in https://github.com/chapel-lang/chapel/pull/14230, and optimized in https://github.com/chapel-lang/chapel/pull/14255)

The Chapel name for `POD` is being discussed in https://github.com/chapel-lang/chapel/issues/14228, but whatever we call it the restrictions are pretty close to the C++ :  numeric/bool/enum or tuples/records of those types where records can't have copy-initializers, initializers, or assignment overloads

**Comment by BryantLam** [comment]
Are Chapel unions considered POD?

**Comment by bradcray** [comment]
> Are Chapel unions considered POD?

I don't know whether they currently are w.r.t. the compiler's definition, but I think that they could be if their individual components were POD.  @ronawho, do you agree?  (and do you know how the compiler currently treats them?)
