### ISSUE TITLE
Weird interaction with bool size query and ref intent 

### ISSUE THREAD

**Issue by ronawho** [chapel-lang/chapel#13120]
I'm not sure I'm using the right terms, but the following program fails to compile:

```chpl
proc foo(ref a:bool(?), const ref b:bool(?)) { a = b; }
var a = false, b = true;
foo(a, b);
```

```
badbool.chpl:3: error: unresolved call 'foo(bool, bool)'
badbool.chpl:1: note: this candidate did not match: foo(a: bool(8), b: bool(8))
badbool.chpl:3: note: because call actual argument #1 with type bool
badbool.chpl:1: note: is passed to formal 'ref a: bool(8)'
```

Seems to work with `int(?)`, `bool`, and `chpl_anybool` parameters. Using `var a = false:bool(8), b = true:bool(8)` also seems to work, so maybe the problem is that `bool` is a distinct type and not just a typedef for `bool(8)`?

The `in` intent version seems to work:

```chpl
proc foo(in a:bool(?), const in b:bool(?)) { a = b; }
var a = false, b = true;
foo(a, b);
```

(though `inout` also fails to resolve)

**Comment by bradcray** [comment]
> bool is a distinct type and not just a typedef for bool(8)

Not related to the problem, but for general information's sake: `bool` is a distinct type in Chapel because the language doesn't define it as having a specific width; instead, it's defined as "let the compiler decide" where for the current C-based implementation the behavior is "let the back-end compiler decide."  I.e., it's codegen'd to C's `bool` (which, I think, also lets the C compiler decide on the width).

**Comment by bradcray** [comment]
I think I may have a lead as to how to fix this.

Also, it looks like we've worked around this in internal modules as follows:

```chapel
  inline proc =(ref a: bool, b: bool) { __primitive("=", a, b); }
  inline proc =(ref a: bool(?w), b: bool) { __primitive("=", a, b); }
```

One challenge for the form that takes a width (`bool(?w)` rather than your `bool(?)`) is that there is no good answer for what value `w` is.  So maybe we only permit unspecified-width `bool` to dispatch to `bool(?)`

**Comment by bradcray** [comment]
> I think I may have a lead as to how to fix this.

Yep, I now have 90% of a solution.  Just need to take care of the `bool(?)` vs. `bool(?w)` issue.

**Comment by ronawho** [comment]
Not sure how relevant this is, but I had been assuming chpl_anybool was old, but it's actually pretty new -- added in https://github.com/chapel-lang/chapel/pull/10143

**Comment by bradcray** [comment]
Ah, and it looks like the reason it was added was to avoid stamping out `bool(?w)` signatures for each legal value of `w` (which is what the compiler has traditionally done in order to resolve things like `+` correctly and reasonably).
