### ISSUE TITLE
Should we provide isBoolType etc. in Types module?

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#13220]
Right now there for querying if something is a bool, there is isBoolType accepting a type, isBoolValue accepting a value, isBool accepting a type, isBool accepting a value. I think it would be reasonable to only provide and document isBool. Of course the others can exist but be undocumented as long as we like.

Right now, isBool and isBoolType are documented, but isBoolValue is undocumented.

If we decide to provide and document things like isBoolType, we'll need to document several similar methods, e.g.  isClassType, isBorrowedClassType, ..., isNilableClassType.

**Comment by bradcray** [comment]
Your issue text focuses on bool here, but I think that this is true for most types, isn't it (i.e., an `isXType()` specific to types, an `isXValue()` specific to values, and an `isX()` that permits either)?  This was an approach @vasslitvinov and I discussed and that he implemented several years ago (the ability to be specific about what you were asking, or just to ask a general question).  I don't recall how well-discussed it was at the time.

**Comment by mppf** [comment]
> Your issue text focuses on bool here, but I think that this is true for most types, isn't it 

Yes, that's what I meant by "etc."

**Comment by vasslitvinov** [comment]
Good thinking!

We do not document most of the `isX` functions individually, instead we have a couple of summary chpldocs placed strategically so that they occur under a long list of individual `isX` functions on the webpage.

Having a single summary chpldoc works for `isClass` together with `isRecord`, `isInt`, etc. This is not quite the same for `isNilable` `isBorrowed` and the likes. Or maybe we can still do a single summary chpldoc, just need to phrase it appropriately.

When we were rolling out `isX` functions, the movation for having `isXType` was this. In addition to querying whether the argument is a particular kind of thing, also allow the user to assert that the argument is a type.

For `isXValue`, we saw unclarity about what "value" mean. It could be seen as "value vs. type" or as "value vs. ref" or "value vs. expression" etc. We wanted to figure it out before making the `isXValue` functions public, i.e. documenting them, and never did that.

Looking at all this now, I personally do not think that the `isXType` and `isXValue` are worth a lot as additions to simply `isX`. Yet, if we retain `isXType`, it is good to provide `isNilableType` et al., for consistency.

**Comment by stonea** [comment]
I suppose so.  For the actual the "Should we provide isBoolType" part of the title of the issue the answer is: yes, we do. In this issue we decided to make all three flavors of all the query functions for primitive types available: <https://github.com/chapel-lang/chapel/issues/19361>.  We also have separate `isClass`, `isClassType`, and `isClassValue` functions.

For more specific queries about attributes on classes we just have the top level `isX` function documented without corresponding `isXType` and `isXValue` functions: (e.g. we document `isBorrowedClass`, `isUnmanagedClass`, and `isNilableClass` but not `isBorrowedClassType`, `isUnmanagedClassType`, `isNilableClassType`, etc.)

I think this is a reasonably cut of what to document and what not to and we could certainly add documentation for other functions later without breaking backwards compatibility for 2.0.  In the meantime I'd advocate closing this issue unless we hear feedback from users or have a motivating use case for changing things.
