### ISSUE TITLE
string concatenation with ranges causes function promotion instead of coercion-to-string

### ISSUE THREAD

**Issue by BryantLam** [chapel-lang/chapel#13281]
Possible feature request. The following code uses string concatenation instead of variadic arguments (like `writeln`), but exhibits function promotion with ranges instead of a coercion of range to string. Is this intended or just an oversight?

```chapel
proc println(s: string) {
  writeln(s);
}

proc main() {
  writeln("test 1");
  writeln(1..10);
  
  writeln("\ntest 2");
  writeln("" + (1..10));
  
  writeln("\ntest 3");
  writeln("" + ((1..10) :string));
  
  writeln("\ntest 4");
  println("" + (1..10));
}
```
```terminal
test 1
1..10

test 2
1 2 3 4 5 6 7 8 9 10

test 3
1..10

test 4
6
7
8
9
10
1
2
3
4
5
```

I suspect if there was a coercion for ranges to strings, then the intended output of all `1..10` would occur, but I don't know how to test this hypothesis. I also don't know if there's unintended consequences with what is proposed.

**Comment by BryantLam** [comment]
Thinking more about it, this might not be an attractive idea because it's hard to rationalize what this output should be:
```chapel
var arr: [1..8] int;
writeln("hello" + arr);
```
It would be nice for logging output to prevent code bloat due to so many variadic inputs, though I suppose that's why the alternative form of `writeln("args %t %t %t".format(1, true, "hello"))` would be more prevalent (but isn't `string.format` still variadic?...).

**Comment by bradcray** [comment]
For a bit of history:  Early on, Chapel supported coercions from most every type to the string type "for convenience."  But in practice, this tended to result in more confusion than benefit as things would tend to accidentally coerce to strings in cases when the user never intended it, resulting in much execution-time expense and confusion.  At the time that we decided to retire "anything can coerce to a string", we added `+` overloads between strings and common / core types in order to support some common patterns: numeric types, bools, and enums.  To be honest, I typically forget that these overloads exist and tend to write such patterns as `"hello " + expr:string` rather than just `"hello " + expr`.

I think that what we have today is all we intended to add at the time, but again, this was back in the still very early years (https://github.com/chapel-lang/chapel/commit/03c4187f3e40460095e32ab7914a6eaa5647d2f0).  If we were approaching the topic from scratch again today, I'd be inclined to either not support any of these `string + value` overloads or else support them for any types that support "cast-to-string".

**Comment by mppf** [comment]
> I'd be inclined to either not support any of these string + value overloads or else support them for any types that support "cast-to-string".

IIRC all types support cast-to-string (since we have some logic that converts them to strings through a channel, and all types support writeln / writeThis).

I'd lean towards removing the string + value overloads. Here I am reading the situation as this issue showing that these led to significant confusion.

It might be nice to see how many tests would require updates with such a change.

**Comment by bradcray** [comment]
> It might be nice to see how many tests would require updates with such a change.

I've started a branch to explore this.  So far, the problem has been tons of code in the internal modules (and in hello5* and hello6*) that do `"string" + intval` in order to generate error messages or output messages.

**Comment by bradcray** [comment]
I'm down to 446 errors on this branch now, and have started hitting a higher fraction of cases that are user test code (like the error messages above, typically cases where a string and integer value are combined to make a message).

**Comment by bradcray** [comment]
@BryantLam: I've forked the question of which string + value concatenations Chapel should support to issue #13409 if you'd like to weigh in there.

**Comment by bradcray** [comment]
Down to ~100 errors now, and I believe all remaining cases are in user test code rather than module code.
