### ISSUE TITLE
Mason: Implement Mason Show

### ISSUE THREAD

**Issue by oplambeck** [chapel-lang/chapel#13362]
Usage: `mason show [options] <package@version>`

Have mason print out the `Mason.toml` of a package.

Design Questions: 
- Should `mason show` with no args display the current project's manifest?
- Should `mason show` support args without a version number, e.g. `mason show Pkg`, which just grabs the latest version?
- Should it be built as an extension of `mason search` e.g. `mason search [package] --show`

Any requests and suggestions are encouraged @npadmana , @Spartee , @ben-albrecht

**Comment by ben-albrecht** [comment]
> Should mason show with no args display the current project's manifest (as you suggested)?

I don't see a lot of value here for the complexity it introduces in the interface, i.e. the command behavior now depends on your CWD. We can always add this in later if we change our mind on it, whereas reversing the decision would require deprecation.

> Should mason show support args without a version number, e.g. mason show Pkg, which just grabs the latest version?

I think this would be nice, as long as it states it is displaying the latest version, e.g.

```
> mason show Pkg
Displaying the latest version: Pkg@1.4.2
<contents of Pkg>
```

> Should it be built as an extension of mason search e.g. mason search [package] --show

I find this appealing since it helps keep the total number of mason subcommands manageable. However, I am not sure what the behavior should be when there is more than 1 result from the search string. Should it print an error about requiring a specific package name, display multiple manifest files, or something else?

**Comment by oplambeck** [comment]
> I am not sure what the behavior should be when there is more than 1 result from the search string. Should it print an error about requiring a specific package name, display multiple manifest files, or something else?

I was thinking of something like this
`> mason search Foo --show`
`Please Specify which package manifest you would like to view `
`Foo@1.0.0     Foo@0.1.0`
`> mason search Foo@1.0.0 --show`
`<contents of manifest>`

**Comment by ben-albrecht** [comment]
OK, I think that could work. 

So `mason search --show <pkg>` will essentially do a `mason search` with an added message about `--show` requiring a single package if there are multiple matches.
