### ISSUE TITLE
Extend Publish to take a registry as an argument 

### ISSUE THREAD

**Issue by oplambeck** [chapel-lang/chapel#13365]
In a use case where a user has a local registry and a package they do not intend to fully publish but would like to incorporate into their

`mason publish local-registry` would automate the process of copying of manifest files into a local registry with addition of a source field.

**Comment by oplambeck** [comment]
@ben-albrecht @Spartee 

Interested in hearing your thoughts on following potential design.

Add a `--local` flag that tells publish that the user wants to publish to a local registry and then also accepts name of the local registry in case the user has more than one local registry. 

`mason publish --local <local-registry>` 

Would also support `mason publish --dry-run --local <local-registry>`

**Comment by ben-albrecht** [comment]
I think there are 3 use-cases to consider here, both of which may result in some variations of how `mason publish` works:

1. User wants to publish their package to the chapel-lang/mason-registry hosted on github. This is tackled in https://github.com/chapel-lang/chapel/pull/13198/files.

2. User wants to publish their package to some other registry hosted on a remote git repository, hosted anywhere (github, gitlab, bitbucket, etc.).

3. User wants to publish their package to a local registry on their filesystem, primarily for the purpose of re-using that package in other local development. This is the specific use-case requested by user @npadmana.

I think it would be valuable to capture the prerequisites, the command required, and outcome (what mason publish is able to do) for each of these.

> Add a --local flag that tells publish that the user wants to publish to a local registry and then also accepts name of the local registry in case the user has more than one local registry.

I would suggest a more general flag name such as `--registry` since this could accept remote git addresses. We might even make this an optional positional argument where the default value is the main registry: `git@github.com:chapel-lang/mason-registry.git`. Hopefully we could distinguish local git addresses from remote git addresses through some parsing.

**Comment by Spartee** [comment]
@oplambeck @ben-albrecht I think Ben is right that ``mason publish`` should handle the first case where a user wants to put a package in the mason-registry, and there should be a general command that handle the second and third use case Ben listed.

I also think that if we offer a way to put it in a local registry(on a filesystem) we should think about the case in which a user no longer wants that package in their local registry or needs to update that package. We would not want them to have to do that manually.

**Comment by ben-albrecht** [comment]
@oplambeck - I know you've started development on this already, but note there are still a couple of open questions which we may end up addressing in the PR review cycle:

- `--registry` flag vs. positional argument
- what exactly are the prerequisites, the command required, and outcome (what mason publish is able to do) for each of the cases outlined above
