### ISSUE TITLE
Should users have to explicitly use SysBasic and SysError?

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#13373]
While making the use of ChapelStandard private, I discovered that we were using SysBasic and SysError by default.  This was happening as part of a deeper use chain, so wasn't obvious from reading the use statements in ChapelStandard (until #13372).  To maintain behavior, I inserted a use of them into ChapelStandard, but this raises the question: should these modules be included by default or should the user have to make a use statement to utilize them?

**Comment by bradcray** [comment]
For those unfamiliar with what these modules define, their documentation is here:

https://chapel-lang.org/docs/master/modules/standard/SysBasic.html
https://chapel-lang.org/docs/master/modules/standard/SysError.html

With a quick look at them in their current state, my preference would be that:

* things like `c_float`, `c_double` not be available by default (and ideally be moved to SysCTypes.chpl)
* most of the other SysBasic types not be available by default
* I'm less clear on whether the `proc E*` and `const E*` errors should be available by default, but would be happy if we didn't need to make them available by default

I'm much less clear on whether or not SysError's contents should be available by default or not.  Its contents seem less objectionable to have available by default, but maybe better would be to have its contents automatically be available when a module that throws SysErrors is used?  (i.e., maybe we could have a `public use SysError` in such modules so that using a syserr-throwing function also resulted in the module defining the errors it throws to automatically be available?)

**Comment by mppf** [comment]
Right, the I/O module can throw errors that are described in SysError. Since functions in the I/O module are visible by default, if the I/O module `public use SysError` then they'd be available by default.

I think `SysBasic` should probably be refactored - moving some things into SysCTypes / CTypes. (I'm not sure it actually makes sense for the C interop types module to begin with Sys anyway). - and creating a new module for system error codes.

In the spirit of minimizing namespace pollution, I think I have a slight preference for making the contents of neither of these modules available in user code by default. I think that the reason that the I/O module is available by default is for very basic things - mainly just `writeln`. I would consider moving those into something that is included by default (e.g. `ChapelIO`) and leaving fancier things like writef, stdout, stderr, channel methods available only when requested in a `use IO;`. If we did that, I'd advocate for making `use IO` also bring in the SysErrors. If we chose to continue to keep all of the fancier I/O things visible by default, then I'd advocate for people using them to `use SysErrors`, but I am less confident in the reasonableness of that.

I do not have a strong preference here.

**Comment by lydia-duncan** [comment]
In the cases that triggered deciding whether to include them by default, it seems they are solely used for the internal implementation rather than any part of the interface that is exposed (code showing the use statements that would be lives [here](https://github.com/chapel-lang/chapel/pull/13372/commits/469a42885f0b763873462e70c1a5585b2a3bd901)).  I think we're in agreement here, so I will proceed with reverting that commit

**Comment by lydia-duncan** [comment]
After discussing with Michael, we've spawned #13348 for the concerns he's raised about IO's symbols.

**Comment by lydia-duncan** [comment]
We also opened an internal task for the rearrangement of SysBasic, Cray/chapel-private#328

**Comment by ben-albrecht** [comment]
> I would consider moving those into something that is included by default (e.g. ChapelIO) and leaving fancier things like writef, stdout, stderr, channel methods available only when requested in a use IO;. If we did that, I'd advocate for making use IO also bring in the SysErrors.

This is my preference as well. I imagine users would rarely need to explicitly `use SysError`, since the modules that emit the error would include it.

**Comment by bradcray** [comment]
Philosophically, I like this proposal, though I find it hard to think of `writef` and `stdout` as being that much less worthy of being included in the standard context than `writeln` is (with slight preference for the `writef` remaining available more than `stdout` being...  namely, I think of the choice between `writeln` and `writef` to be one of personal style and don't know that we should make one of them more accessible than the other.
