### ISSUE TITLE
Adding distributed sparse diagonal

### ISSUE THREAD

**Issue by wongalvis14** [chapel-lang/chapel#13385]
Adding a diagonal (add indices and set values) in a sparse distributed array is super slow

As a part of my project, I've made a helper function to do that so that I can create large sparse arrays in shorter time
https://gist.github.com/wongalvis14/5e80097dbafededea3c6b90049f7dfde

It does not perform well because adding indices in sparse itself is pretty slow and it doesn't scale well as there are more indices in the sparse domain, but it is the fastest I can get for now (there's a more hacky way to do something similar to `bulkAddHere` mentioned by @e-kayrakli  , which may be faster)

This can also be helpful for functions like `eye` or something similar to scipy's `scipy.sparse.spdiags`

If this is worth an addition to the LinearAlgebra library, I can go ahead to submit it for more feedback

**Comment by wongalvis14** [comment]
And for reference, on 4-locale Swan machine with --fast, it takes almost 7.8 seconds to create a 2^15 * 2^15 tri-diagonal sparse matrix, it can be 5-10 times slower or even worse with other approaches

**Comment by bradcray** [comment]
I think the original text above alludes to this, but to be explicit: this seems related to issue #12673 (in that, if we had localAdd() or bulkLocalAdd() routines, it wouldn't be too hard to spin up the locales owning the diagonal and have them add their local indices along the diagonal).

**Comment by e-kayrakli** [comment]
`bulkAddHere` is here!: #13411 

Once it gets into the master, it's supposed to help with this problem.

**Comment by e-kayrakli** [comment]
I have recently merged #13411, and I think the problem that this issue is addresses should be resolved. With this change there is an additional `addOn` argument to `bulkAdd`, which you can use iff you know that the array of indices you are adding belongs to a single locale. Below is an (untested) sketch of how you could use that in this context:

```chapel
coforall l in dom.targetLocales() do on l {
  const locSubdom = dom.parentDom.localSubdomain();
  const rowRange = locSubdom.dim(1);
  const colRange = locSubdom.dim(2);
  const overlapRange = max(rowRange.low, colRange.low)..min(rowRange.high, colRange.high);
  
  if overlapRange.length > 0 {  // I own some of the diag
    var myIndices = [0..#overlapRange.length] 2*int;
    for (myInd, i) in zip(myIndices, overlapRange) {
      myInd = i;
    }
    dom.bulkAdd(myIndices, addOn=here);
  }
}
```

I think something like this is a reasonable approach to achieve good performance adding indices on the diagonal. It may not scale greatly with really high number of locales as most of them will be idle, but still it shouldn't be horrific.

@wongalvis14 -- is there anything particular in this issue that you feel not properly addressed? Otherwise, I am inclined to close it.

**Comment by bradcray** [comment]
>  It may not scale greatly with really high number of locales as most of them will be idle, 

Unless only one dimension is blocked (?).

**Comment by e-kayrakli** [comment]
> Unless only one dimension is blocked (?).

Yup, if that's the case. I don't see anything obviously wrong in terms of scalability.

**Comment by e-kayrakli** [comment]
I think this issue has been resolved as I noted earlier in the discussion. I am closing it now.. @wongalvis14 -- feel free to reopen or comment here if you think this is not resolved
