### ISSUE TITLE
What string + value concatenations should be supported by default, if any?

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#13409]
At present, Chapel supports mixed-type concatenations between strings and...

* ...numeric types
* ...enumerated types
* ...booleans

with the arguments in either order.  This can often be convenient (e.g., we particularly use them a lot in generating error messages), but it also feels a bit arbitrary (why just these types?  why not others?  or why any other than strings at all?)

This issue asks whether we should:

* not support (by default anyway) string concatenation with any types other than strings (users would have to write `"answer is: " + val:string` rather than `"answer is: " + val`)
* stick with the status quo
* support string concatenation with any type that supports being cast to string
* something else

For context, this issue came out of #13281 in which the status quo resulted in confusion.

**Comment by vasslitvinov** [comment]
The options "no support" and "support any type" make sense to me.

Given that we use and enjoy the string+value option, we may as well continue doing so. Limiting string+value to some types feels arbitrary, however. For example, we can say `writeln(x)` for any type of `x`. Within the scope of this issue, string+x feels morally equivalent to that, so make sense to be allowed for any type of x.

**Comment by mppf** [comment]
I still have the same position I did [earlier](https://github.com/chapel-lang/chapel/issues/13281#issuecomment-505486736)

I'd lean towards "not support" and the reason is that I think that issue  #13281 shows that these led to significant confusion.

I think varargs functions (like `writeln("the number is ", 5)`) are a reasonable way to support this pattern for error messages. Even if the result is the string, we can support something like

``` chapel
var s:string;
s.write("the number is ", 5); // worked once-upon-a-time but doesn't work today
```

Or add a new method (maybe even an initializer?)
``` chapel
var s:string;
s = stringify("the number is ", 5);
```

Or just ask people to use `string.format` in such a case:

``` chapel
var s:string;
s = "the number is %t".format(5);
```

I also don't personally find simply adding the cast to be objectionable:
``` chapel
var s:string;
s = "the number is " + 5:string;
```

The point being - there are enough other ways to do this that I think have less potential for confusion. Lastly, a minor thing, but the alternatives that don't use `+` can actually be more efficient (because they can use some kind of `StringWriter` object which appends to just one string instead of relying on `+` which always creates a new string for each `+`).

[Java allows "string" + 5](https://tio.run/##y0osS9TNL0jNy0rJ/v@/oDQpJzNZITknsbhYwTcxM0@hmosTKlhcklgCpMryM1MUcoFSGsElRZl56dGxColF6cWaIJWcwZXFJam5evmlJXoFQMmSnDwNJY/UnJx8HYXw/KKcFEUlBW0FU01rLs5artr//wE) but Java doesn't have the potential for confusion from promotion.

**Comment by gbtitus** [comment]
> The options "no support" and "support any type" make sense to me.

I'm with @vasslitvinov here - those seem like the only sensible positions.  Anything else asks too much of Chapel users' memory for language details.  Plus, why should for example `string + int` promote the `int` to a `string` and then concatenate, rather than promote the `string` to an `int` (with 0 or throw an error if it doesn't seem to represent an integer value) and then add?  Yet another thing to remember.  So between "no support" and "support any type", "no support" seems clearly best to me.  And as @mppf notes one can get the same result with `str + nonStr:string` which is hardly longer and much more obvious when reading the code.

**Comment by bradcray** [comment]
I agree with all the sentiments expressed here that we should be more consistent one way or the other.  It seems that more people have expressed interest for the "disallow all string + value overloads" side of the equation and I think Greg's argument that it's arguably ambiguous whether `"1" + 2` should be `"12"` or 3, so by only providing `t + t` overloads, we force the user to break the ambiguity (where one could create their own + overload or a helper/package module that provided such overloads if they found them useful.

If anyone is curious to see what this world looks like in our modules and testing system, see PR #13658, which I'm working on getting ready for review.
