### ISSUE TITLE
Add multilocale library as last link argument in Cython build command for multilocale Python libraries

### ISSUE THREAD

**Issue by dlongnecke-cray** [chapel-lang/chapel#13458]
> I think this means we'll need to explicitly add the second -l of the library to the Cython build command for multilocale python libraries. That shouldn't be too hard, though, just a separable task`
https://github.com/chapel-lang/chapel/pull/13453#issuecomment-511049390

**Comment by lydia-duncan** [comment]
Alternatively, it maybe should go in `makePYFile` in library.cpp (starting around line 655).  We can walk through this in a meeting or something :)

**Comment by dlongnecke-cray** [comment]
After scrounging around for a bit, I'm not too clear on what my objective is here. Is the goal of this issue to append the compiled Chapel library as the last argument _here_?...

```
chpl_libraries=["chpl", "gasnet-udp-par", "amudp", "m", "gmp", "jemalloc", "chpl", "qthread", "hwloc", "m", "re2", "pthread"] <<< Here would work as well.
setup(name = 'TestLibrary library',
  ext_modules = cythonize(
    Extension("TestLibrary",
      include_dirs=[numpy.get_include()],
      sources=["TestLibrary.pyx"],
      libraries=["TestLibrary"] + chpl_libraries))) <<< Append here for GNU?
```

Where here is the final generated `TestLibrary.py` module wrapper for a user's Python library.

I know that this amount of effort is a bit more than zero points, but I'm wondering if it might help if I understand the build process here. 
---

In `make_python_module` in `compiler/codegen/library.cpp`, there is the following snippet of code:

```
  // We might be using the GNU linker, in which case we need to do this.
  if (llvmCodegen) {
    fullCythonCall += " " + name;
  }
```

However it looks like that only fires under LLVM. I have a vague recollection of adding something similar, but can't remember why at the moment.

Are we sure we shouldn't append the library as the last link argument unconditionally?

**Comment by lydia-duncan** [comment]
> Is the goal of this issue to append the compiled Chapel library as the last argument here?

I think either of those spots in the code snippet you've quoted is reasonable.

> However it looks like that only fires under LLVM. I have a vague recollection of adding something similar, but can't remember why at the moment.

We added that because the code organization when compiling for LLVM has a similar circularity (meaning that symbols in the generated code rely on runtime symbols, and the runtime symbols also rely on symbols that will be generated).  I think when that extension got added I had forgotten about the generated code for the .py file so it might be that having LLVM trigger the extension for the .py file's library lists would also have worked.

> Are we sure we shouldn't append the library as the last link argument unconditionally?

I'm not sure, I think that's a reasonable thought.  It seems like it would lower the chances of running into this sort of thing again and having to extend the situations when we include the library multiple times.  My hesitancy is really from not wanting to write things redundantly but that could be considered more of an annoyance with GCC than anything else.  I don't know that it is harmful to include the library multiple times when we don't need to (and `compileline` seems to do so when compiling with clang, where we shouldn't need to)

**Comment by lydia-duncan** [comment]
In writing the cron script for running multilocale python libraries on a linux system, it looks like we also need to update the code that generates `chpl_libraries=["chpl", ...` to include "zmq" as part of the list.

**Comment by dlongnecke-cray** [comment]
Ok. Glad I took this "0 pointer" for granted and waited!

**Comment by dlongnecke-cray** [comment]
Resolved by https://github.com/chapel-lang/chapel/pull/13570.
