### ISSUE TITLE
Making changes to the existing `list` API

### ISSUE THREAD

**Issue by dlongnecke-cray** [chapel-lang/chapel#13511]
This issue documents feedback/potential changes to to the `list` API to consider before the next release.

Most of these are due to experience gained from https://github.com/chapel-lang/chapel/issues/13233, but a couple are intended to be more "far reaching"...

General criticisms:

- **The `indexOf` method does not need to throw.** Since the domain of a list object is fixed from `1..list.size`, the `indexOf` method could return a sentinel value such as `-1` instead. This would make it function as a `contains` method as well.
- **The `remove` method does not need to throw, or alternatively, it should return the element removed.**
- **If `remove` should throw, consider adding a `discard` method that will remove if possible, but does not throw.** The `set` type already has such a method.
- **The `extend` method could be generic over any iterable.** However, there is a small performance benefit to be had when `extend` is aware of the iteration bounds. Would it be possible to overload a generic `extend` method for well known container types?
- **Consider the name `appendMany` or `bulkAppend` instead of `extend`.** I predict a future where many operations over containers will have variants that accept an `iterable`. In this case it would be best to prefer a standardized naming convention for "bulk" operations across all containers.
- **Now is the time to consider a standardized interface for all standard library containers.** This can be enforced with a feature like constrained generics, but there is no reason why it cannot be codified now.

**Comment by dlongnecke-cray** [comment]
Should methods such as `pop` halt instead of throw?

**Comment by dlongnecke-cray** [comment]
It would be good to be able to remove a range, as in:

```
prefixArray.pop(pos..prefixArray.size);
```

**Comment by e-kayrakli** [comment]
After reviewing #13530 I think the following should be added to the `list` interface:

- array-as-vec had `.back()` whereas in `list` you have to do `list[list.size]`. I think `list` type could use a `.back()` method and similarly `.front()`. These two are more list-like operations rather than array-like operations to me.

- There should be a way to create list from an array. Ideally both 
```
var l = new list(myArray);
``` 
and 
```
var l: list = myArray;
```
- I also find it very unfortunate to create an array out of a list just to be able to iterate over it in parallel. So, there should be parallel iterators for lists. (I don't know the underlying implementation, so this may not be as straightforward as I think).

- Going a bit further on parallel iterations: in the PR that brought me here (#13530) there are idioms where arrays are parallel-zipped with their domains. Wouldn't it be nice to just do:

```
forall (idx,elem) in zip(1..myList.size, myList)
```
which I believe can be done today, especially if list implementation uses arrays under the hood. However, it may be a bit of a "leader/follower 2.0" discussion to be able to do that.

Even though list interface makes some nice changes as in #13530, it also makes the code uglier due to these missing pieces, IMHO.

**Comment by e-kayrakli** [comment]
While working on #13420, I thought it would be useful to have a zero-copy version of `list.toArray()`(maybe `list.asArray()`) that returns an array object that uses the same _ddata as the `list` object. Although it could be useful, two obvious concerns:

- Can we make sure that the user is aware of the implications of doing that?
- The `list` record using `_ddata` is not part of its interface. Although I think it is unlikely, if the internal representation is changed to something that is unsuitable, then `list.asArray` would be useless.
