### ISSUE TITLE
Partial Instantiations: expressing the concrete version of 'range'

### ISSUE THREAD

**Issue by benharsh** [chapel-lang/chapel#13566]
One likely future for generic type expressions in Chapel is for the language to state that a type expression like ``foo`` will always be generic if type ``foo`` has generic fields, even if all of those fields have default values. This would have a significant impact on the use of the ``range`` type, which has three generic fields (index type, bounded-kind, stridable). If we were to proceed with this plan some new expressions could be made possible:

```chpl
// formerly 'x' had to be of type `range(int(64), BoundedRangeType.bounded, false)`
// in new world 'x' just has to be any kind of range, allowing easier initialization from more interesting range values.
var x : range = 1..10 by 2;
```

Some existing uses of ``range`` would become more complicated under this new scheme:

```chpl
record R {
  var x : range;
}
// 'R' is now a generic type, formerly was concrete
```

This second pattern is most impactful in our internal modules that implement arrays, where we often have a field with a type expression like ``range(idxType)`` or ``range(idxType, stridable=stridable)``. Such fields would now become generic, requiring us to instantiate yet another field when trying to make array classes concrete: 
``DefaultRectangularArr(1,int(64),false,int(64),int(64))`` vs 
``DefaultRectangularArr(1,int(64),false,int(64),int(64), range(int(64), BoundedRangeType.bounded, false))``

Should we introduce a way for users to express they just want the rest of the fields to use their defaults?

**Comment by benharsh** [comment]
@bradcray , @mppf : running into this on my development branch and wondering what you think about this potential usability problem.

**Comment by bradcray** [comment]
Ugh, that is more impactful than seems attractive... I'm mentally chewing on this now that you've pointed it out, but in the meantime here's a quick thought...

> Should we introduce a way for users to express they just want the rest of the fields to use their defaults?

Conversely, we could have a way for users to express that they want to opt into the passive evaluation (e.g.,

* `range(?)`: a completely generic range
* `range(stridable=false, ?)`: a range in which everything other than stridable is unbound
* `range(idxType=?)`: a range in which the idxType is unbound but everything else takes its default

I'm definitely interested in @mppf's thoughts since his recent work has been involved in generics and instantiation from a different angle.

**Comment by mppf** [comment]
I still think that we should make `range` by itself be generic, where possible. Historically we've had `range(?)` to opt in to it being generic and `range` would be concrete. It makes sense to me that if we change the default behavior (to get things like `var x : range = 1..10 by 2;` to work, and in my view, to make argument types more consistent) then we'd create a way to opt-in to getting the concrete `range` with the default settings.

Brainstorming some ideas to express it:
 * `defaulted(range)`
 * `range(defaults)`
 * `range(_)`

Unfortunately `range()` probably doesn't make sense if we want partial instantiations to work (e.g. `range(uint)` would still be generic on strideability, so the `()` don't remove generic-ness).

**Comment by bradcray** [comment]
My thinking last night made me think that my brainstorming comment may have had more merit than I was originally thinking.  Specifically:

* we've sometimes talked about implementing types like `int` as a record yet I don't think we'd want to make `var x: int;` mean "a generic int", so making the default be "resolve things that have a default" and a way to opt out of it would preserve behavior for scalar types without making special cases for them (which we could always do since they're "built-in" but it seems nicer to have them be as normal as possible; or rather, to have users write their own record types that are as normal as possible).

* the proposed behavior would be more consistent with how we treat formal argument types currently (...mostly...*) in that we support `R(?)` as a way to say "any R() please".  So adopting this strategy would require fewer changes to existing code and to the language.

* while we have people who get confused by `var r: range = 1..10 by 2;` there's arguably just a learning curve that we need to address here to teach them that the `range` type is a very specific instantiation of a generic type and that they want `range(?)` or `range(stridable=true)` to get the behavior they were hoping for.  We could also choose to make ranges not have a default stridability argument (though I'm not very much in favor of that).

(* = I believe we have some special-cases in the compiler right now in the formal argument position like treating `domain` as "any kind of domain" rather than "a domain with its defaults filled in" (but domain's are sufficiently non-defaulted that maybe there isn't a real difference?  Still, I think we're doing something special here rather than putting our weight on any sort of partial instantiation semantics given that we haven't had them).

**Comment by mppf** [comment]
If we do that, is there a challenge with partial instantiations?

``` chapel
record R {
  type idxType = int;
  type eltType;
  param rank;
}

... R(int) ...; // does this set idxType=int or eltType=int?
```

Anyway I had thought we had some good reason to make `range` generic outside of `var x:range;` but I do not really have the rationale in front of me (although I still prefer the generic version of range...)

**Comment by bradcray** [comment]
For Michael's example, I'm imagining `R(int)` would set `idxType` to `int` and that `eltType` and `rank` remain unbound.  I'm still thinking in terms of a type initializer-like routine that has the signature `proc type init(type idxType=int, type eltType, param rank)` where normal argument matching semantics would apply.

The "new things" in my quick proposal would be
* `R(idxType=?)` would be legal and say to not use the default for `idxType`, leaving it unbound / generic.  Thus `R(idxType=?, int)` would set `eltType` to `int`.
* A final `?` in the signature would prevent any additional unbound generics from taking their default value.  Thus `R(eltType=int, ?)` would leave `idxType` and `rank` unbound (though rank would be anyway since it doesn't have a default value.

> I had thought we had some good reason to make range generic outside of var x:range;

I think it seemed attractive at first blush to have `range` be generic such that `var x: range = 1..10 by 2;` would work for users, but I worry that @benharsh's experience in converting array/domain code over suggests that doing so makes the type more generic than we'd like and suggested to me that a type author ought to have a way to easily say "this is the default signature for this type if you don't want to think of it as being generic" where `R(?)` would be the opt-out mechanism to keep it as generic as possible.  I think this is just the dual of what Michael was proposing above, but has the advantages of being more similar to what I think we currently have implemented and optimizing for the case where a type does want a default generic signature (rather than optimizing for the case where everything remains more generic).

**Comment by mppf** [comment]
I am not sure if we have reached a language design decision on this issue. I had thought we were interpreting `range` as "use the defaults" and `range(?)` as "the generic version". However what is implemented does this depending on context. That might be good and what we want. Or maybe not.

Today, a declaration like this results in the "use defaults" range:
``` chapel
{
  var r: range; // default: unstrided range
}
```

However if the range is initialized at its declaration point, the type is interpreted as generic:
``` chapel
{
  var r: range = 1..10 by 2; // creates a non-default, strided range
}
```

This is also the case if split-init applied and made the range initialized later:
``` chapel
{
  var r: range;
  r = 1..10 by 2; // creates a non-default, strided range
}
```

Should the author of such code, in the split-init case, need to write `var r: range(?);` ?
What about the `var r: range = 1..10 by 2;` case?

**Comment by benharsh** [comment]
I think michael's examples should require ``range(?)`` to work and that the demonstrated behavior is a bug.

**Comment by bradcray** [comment]
Reviewing the conversation, I agree with @benharsh.
