### ISSUE TITLE
Rewrite tests in `test/studies/shootout/reverse-complement/bharshbarg` to use the `bytes` type

### ISSUE THREAD

**Issue by dlongnecke-cray** [chapel-lang/chapel#13622]
The "array-as-vec" methods on arrays are soon to be deprecated, so the following tests should consider use of the `bytes` type instead (rather than say, the `list` type):

- test/studies/shootout/reverse-complement/bharshbarg/revcomp-buf.good
- test/studies/shootout/reverse-complement/bharshbarg/revcomp-line.good

**Comment by dlongnecke-cray** [comment]
Since you are the proud new maintainer of the `bytes` type @e-kayrakli, perhaps you would consider the honor of rewriting these tests?

**Comment by e-kayrakli** [comment]
To me, this is a matter of IO support for doing things like `readUntil(">")`. Note that the use of `list` here is necessary because we need a flexible structure that can extend. We can think of using bytes concatenation here instead of building a `list(uint(8))`. But the current use of `list` doesn't look too bad to me.

Pinging @bradcray as the shootout master to hear what he thinks whether we should try to use `bytes` for these versions of revcomp.

**Comment by bradcray** [comment]
I don't think we need to keep this issue open, personally.  I think we've got some leads on ways of using `bytes` in revcomp using our current strategies that follow those of other leading (non-heroic) solutions, and agree that I/O is probably the bigger issue for making revcomp better going forward.

**Comment by e-kayrakli** [comment]
@dlongnecke-cray -- I am going to close this one, feel free to reopen if you disagree.
