### ISSUE TITLE
Design: should the result of 'x!' be an alias to 'x' ?

### ISSUE THREAD

**Issue by vasslitvinov** [chapel-lang/chapel#13621]
There are two ways to think about the value of the expression`x!`:

* it borrows from `x`, or
* it is an alias to `x`.

When `x` is of a class type, both cases are sound, since the not-nil check passes before the result of the expression can ever be used.

Currently the "borrows" version is implemented, although the "alias" version may be more intuitive.

Is the "alias" interpretation sound if `x` is of a Swift-style Optional type that we have are contemplating for Chapel, when the underlying type is not a class, ex. `int` ?

**Comment by mppf** [comment]
@vasslitvinov - is another way to describe this question - should the postfix `!` operator return a reference?

While the compiler does fold together nilable and non-nilable types partway through compilation, conceptually since these are different types. That is why we have "borrow" today.

Is "alias" is workable? For classes, it could work because the representation of `MyClass?` and `MyClass` is the same (for a given ownership).

Could it work for `int?`? In particular, `int?` is some type that is larger than `int` (because it can store all `int` values *and also* `nil`). So let's suppose it is 16 bytes, for concreteness. In contrast, `int` is 8 bytes. Then a reference to `int` cannot be converted to a reference to `int?`. It might be possible to allow a reference to `int?` to convert to a reference to `int`, though, if the `int?` stores the integer value first. (This is similar to how we currently handle classes, even though it's not technically legal C). If `int?` is a union type, I think it could still work.

So, I think *alias* is possible but would require some thought about aliasing rules (e.g. adjustments to our TBAA metadata emission for --llvm).

**Comment by mppf** [comment]
I think we could ask the same question for `x.borrow()` itself. I personally think that making `x.borrow()` return a `const ref` to the pointer within an `owned` (say) is possible but complicates the implementation and optimization of code using the `borrow` without significant benefit IMO.

@vasslitvinov - did you have a use-case in mind that would benefit from the "alias" interpretation?

**Comment by mppf** [comment]
So supposing we did the "alias" interpretation, wouldn't we have the problem that `x!` asserts the non-nil nature at that moment, but this could change? I.e.

``` chapel
class MyClass { var x:int; }
var x:borrowed MyClass? = (new owned MyClass(1)).borrow();
const ref nonNilReference = x:borrowed MyClass;
x = nil;
writeln(nonNilReference.x); // nil dereference that we don't want to check at runtime!
```

This makes me think that the "alias" interpretation is unworkable.

**Comment by vasslitvinov** [comment]
Yeah unfortunately the alias interpretation may be unsound, due to potential concurrent updates to the source of the `!`.

Is that a show-stopper for having `x!` be an alias to `x` ?

@mppf - I do not have a use case. "I thought it would be an alias" was my initial reaction when I saw x! being a borrow.

**Comment by mppf** [comment]
> Yeah unfortunately the alias interpretation may be unsound, due to potential concurrent updates to the source of the `!`.

> Is that a show-stopper for having `x!` be an alias to `x` ?

I think so. It seems to me to create a hole in the type system.

**Comment by vasslitvinov** [comment]
This looks like a no-go.
