### ISSUE TITLE
fix chpl__buildDistType

### ISSUE THREAD

**Issue by vasslitvinov** [chapel-lang/chapel#13634]
The following internal module code is currently made to compile with `pragma "unsafe"` :

```chpl
proc chpl__buildDistType(type t) type where isSubtype(t, BaseDist) {
    var x: t;
    var y = new _distribution(x);
    return y.type;
  }
```

The problem is that `t` is non-nilable so the compiler does not like its being default-initialized.

What do we want to do about this code?

* Switch `t` to nilable? This is a poor option because that puts a nilable piece into the returned type.

* Switch to `var x = new t(); `?  This does not work, for example, for Cyclic because the corresponding initializer requires some arguments that this function does not know about.

Sample test where this is involved:

    test/classes/initializers/phase1/domainMaps/init-dmap-dom-arr-local.chpl

**Comment by bradcray** [comment]
My guess is that since this routine is just trying to reason about static types, we should rewrite it to make more use of primitives (e.g., "static typeof") rather than trying to create a value and then return its type.  I suspect that won't be trivial, but it seems like the best way to proceed (keep all of the reasoning in the type space rather than working hard to create a value only to throw it away after getting its type.
