### ISSUE TITLE
should owned.borrow() have a const ref version?

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#13638]
Should this be allowed?

``` chapel
var x: owned MyClass = ...;
const ref b = x.borrow();
```

or, put another way
``` chapel
proc g(const ref b: borrowed MyClass) { }
var x: owned MyClass = ...;
g(x);
```
If we did, I would expect that `owned.borrow` would have value as well as `const ref` return intent overloads. As a result, we would expect that the `const ref` version would only be used in patterns that required it.

It is possible because `owned MyClass` contains something with the same representation as the borrowed pointer.

This question is related to #13541 and #13621.

While this issue is being concrete by asking about `owned`, it is expected that the answer will be generalized to `shared` and `unmanaged` as well.

**Comment by vasslitvinov** [comment]
The reason we want to have the `const ref` overload of borrow() is so that the recipient of the reference can track the potential concurrent changes to the source of the borrow?

**Comment by vasslitvinov** [comment]
I think `x.borrow()` should continue to be a snapshot of `x`. So, here:
```chpl
var x: owned MyClass = ...;
const ref y = x.borrow();
x = something else;
```
`y` continues pointing to the original value in `x` after `x` is reassigned.

The only challenge is that the above, as written, should be illegal w.r.t. lifetime checking because the original value in `x` is deleted when `x` is reassigned, while `y` is still pointing to it.

By contrast:

```chpl
var x: owned MyClass = ...;
const ref y = x;
x = something else;
```

would make `y` track updates to `x`.

**Comment by BryantLam** [comment]
How are these declarations different?
```chapel
proc g(const ref y: borrowed MyClass) { ... }
// and
const ref y = x: borrowed;
```

**Comment by vasslitvinov** [comment]
Good question. I think nailing down the semantics of both cases is part of this issue, or closely related.

**Comment by vasslitvinov** [comment]
@BryantLam there is another difference: `x: borrowed` produces a snapshot of `x`'s value, whereas `const ref y` has the potential of tracking the value of the actual in case there are concurrent updates to the actual. For tracking, the actual must be of a subtype of the formal's type, including the same type. Otherwise it is the case of an implicit coercion, assuming the call resolves. In this case, like with an explicit cast, the formal refers to a snapshot of the actual that's stashed in a temp.

**Comment by vasslitvinov** [comment]
One way to look at this issue is by asking:

#### Is `owned MyClass` a subtype of `borrowed MyClass` ?

In this example:
```chpl
proc g(const ref b: borrowed MyClass) { ... }
var x: owned MyClass = ...;
g(x);
```

If yes, then the formal `b` will track concurrent changes to `x`, if any.

If no, then there will be a coercion from `x` to `b`. It will, at the time of the call, store a borrow from `x` in a temp. `b` will be a reference to this snapshot.

#14773 suggests that `owned MyClass` is NOT a subtype of `borrowed MyClass`. Therefore borrowing should create a snapshot, rather than a reference.

Another way to look at this issue is starting with:

#### Should `.borrow()` produce a snapshot or a reference to its argument?

If it produces a reference, then it is possible for the borrow to track updates to its source, for example in the above code snippet.

Our current answer, perhaps motivated by the other perspective, is that borrowing produces a snapshot.

There are several ways to borrow in Chapel from any flavor of a class type:

* the borrow method: `x.borrow()`
* an explicit cast to a borrowed type, ex.: `x: borrowed`
* an implicit coercion, ex. passing it to a `borrowed`-typed formal
* the postfix-`!` operator

For consistency and clarity, we would like all four to behave the same, that is to return a snapshot. For the postfix-`!` operator, producing a reference is not even an option, as it would be unsound when applied to a nilable type, see #13621.

For these reasons, `owned.borrow()` should not have a `const ref` version.

**Comment by mppf** [comment]
I'm closing this issue since the discussion seems to be leading us to the current situation - `owned.borrow()` does not have a `const ref` version.
