### ISSUE TITLE
Array defined by single-element enum range fails

### ISSUE THREAD

**Issue by npadmana** [chapel-lang/chapel#13650]
Consider the following code

```chapel
enum E {A};
const x : [E.A..E.A] int = [1];
```
This fails at runtime with the following error 
```
.code.tio.chpl:2: error: halt reached - enumerated type out of bounds in chpl__orderToEnum()
```

Making the enum have two elements works 
```chapel
enum E {A,B};
const x : [E.A..E.B] int = [1,2];
```

**Comment by bradcray** [comment]
Thanks for reporting this.  I'm almost certainly to blame here.

**Comment by bradcray** [comment]
Oh, interesting...  This occurs because in setting up the array, we are trying to create an empty range of the enum type (so the equivalent of `1..0` for the enum).  But since the enum doesn't have two elements, it isn't possible to do this and it manifests as this error.  This makes this bug relate closely to some of the recent discussion on issue #5165.

@npadmana: Could you let me know whether this is something you're wanting to do in your code, or something you stumbled across and are filing for the record?

**Comment by npadmana** [comment]
@bradcray -- no, not a blocker at all. Stumbled into it writing the NPB-FT benchmark....

**Comment by bradcray** [comment]
OK, thanks.  I've got a simple change that at least changes this from a vague execution-time error to a better compilation-time error.  I'll plan to merge that to improve things slightly, and continue thinking about what to do about this case.

**Comment by bradcray** [comment]
I've merged PR #13655 to generate a better, compile-time error message for this case, but am not going to close this issue until we take a strong stance about whether or not to support this case (and how).  At the same time, I'm not planning to particularly prioritize it other than w.r.t. how it comes up in conversations over on #5165 and the like unless someone requests more attention here.

**Comment by bradcray** [comment]
I've filed a minor variation on this as issue #17464.

**Comment by bradcray** [comment]
Proposed implementation in: https://github.com/chapel-lang/chapel/pull/17511

**Comment by bradcray** [comment]
@npadmana : Thanks for filing this feature request, which is now available on the development branch.
