### ISSUE TITLE
Should bytes be a mutable type or not?

### ISSUE THREAD

**Issue by e-kayrakli** [chapel-lang/chapel#13707]
We are adding a new `bytes` type to the language. `bytes` type is very similar to `string` type, however one major difference is `bytes` type does not have any encoding, i.e. can store arbitrary bytes.

Another potential difference is mutability. `string` type is immutable in-place. One school of though is to make `bytes` type also immutable for making it as similar to `string` as possible. Another option is to make it mutable in-place to allow it to be used in wider use cases.

Python has both `bytes` and `bytearray` types where the former is immutable and the latter is immutable. As of today, `bytes` implementation is in the internal modules (albeit we are still working on its integration to the language) as an in-place immutable type similar to `string`

**Comment by e-kayrakli** [comment]
My 2 cents on the issue: I like bytes type to be as similar to strings as possible but having `bytes` type encoding free *and* mutable is not horrifically different IMHO. 

That being said, I am not 100% comfortable with this and making it immutable seems "safer" and less confusing at a high level. I am not sure what kind of use cases are out there where `bytes` mutability (or string's immutability as opposed to bytes' mutability) can throw people off.

A relevant read is python's [PEP 3137](https://www.python.org/dev/peps/pep-3137/)

**Comment by bradcray** [comment]
I find myself wondering if we could select between the two using either:
* `const b: bytes;` vs. `var b: bytes;`
* `[const | var] b: bytes(mutable=[true | false]);`

I think the downside to the first approach is that we have `const` and `var` strings even though all strings are immutable, so the `const` vs. `var` essentially says whether or not the variable can point to a different string buffer (I think?).  So that probably doesn't fly for `bytes`.

I think the multi-byte/variable-width characters of UTF-8 are a main reason not to make strings mutable.  Since bytes have fixed-width elements, I'm not sure of reasons to make them never be mutable.

We could just use `var b: [1..n] uint(8);` to get an array of "bytes", but my impression is that in some of our programs (e.g., the CLBG entries?), there have been opinions in the past that a mutable bytes variable would clean up the code significantly (presumably because the operations on the variables are more string-like than array-like?).

**Comment by mppf** [comment]
I don't think `bytes` should be mutable other than `+=`

> I think the multi-byte/variable-width characters of UTF-8 are a main reason not to make strings mutable. Since bytes have fixed-width elements, I'm not sure of reasons to make them never be mutable.

Here is my reasoning.

One day, I hope that `string` and `bytes` can use reference counting (at least for relatively large strings). This kind of thing is sometimes referred to as a "rope" implementation (e.g. https://en.wikipedia.org/wiki/Rope_(data_structure) but I mean something more general than what is exactly described there). If we make them mutable, we cannot share the same data buffer between two `string` or `bytes`.

E.g.

``` chapel
var x = computeSomeGiganticBytes();
var y = x; // this could use reference counting to share the data
y += computeSomeOtherBytes(); // this can append by keeping a list of pointers to data
                              // similar to the `list` we are building
```

So I'd say my concern has to do with the future ability to change algorithms if trying them shows that they significantly improve performance.

**Comment by bradcray** [comment]
@mppf: Couldn't a compile-time distinction between mutable and immutable bytes support the optimization above for the immutable cases without precluding the creation of mutable bytes variables?

**Comment by mppf** [comment]
@bradcray - I want to be able to append with `+=` to the normal `bytes` or `string` type and still have the "rope"-y implementation. I don't think it makes sense for `+=` to do anything to a `const` variable.

**Comment by bradcray** [comment]
What if `var b: bytes;` was equivalent to `var b: bytes(mutable=false);` yet we permitted people to declare `var b:bytes(mutable=true);` and only applied your optimization in the former cases?

**Comment by mppf** [comment]
@bradcray - I view `bytes(mutable=true)`, when that is not the default, as philisophically the same as adding a `mutableBytes` type (just with a different name). I have no problem with having a separate type that is mutable.

Are you imagining that one could `+=` on a `var b: bytes(mutable=false)` (I think you are?)

**Comment by bradcray** [comment]
> I view bytes(mutable=true), when that is not the default, as philisophically the same as adding a mutableBytes type (just with a different name).

I agree they're equivalent; I think the benefit is that there's no need to come up with (and potentially reserve?) a new type name.  `mutableBytes` or `bytesArray` is also a bit more of a mouthful (and if considered built-in, would be the first camelCase built-in type I think?)

>Are you imagining that one could += on a var b: bytes(mutable=false) (I think you are?)

Sure.  I think the ability to modify bytes using subscripting was the main benefit that mutability would give to CLBG codes (though @e-kayrakli and/or @benharsh may know better).

**Comment by e-kayrakli** [comment]
Separate type seemed to be the solution to the problem since the beginning. I think I like `bytes(mutable=true)` slightly better than `mutableBytes` or `byteArray` (or probably any other name). A user can define a type alias if they wany, anyways.

> Sure. I think the ability to modify bytes using subscripting was the main benefit that mutability would give to CLBG codes (though @e-kayrakli and/or @benharsh may know better).

I don't know others off hand but knucleotide is doing in-place case changes IIRC.

**Comment by e-kayrakli** [comment]
Following from my previous comment, one thing that we should consider is the behavior of `toUpper`, `toLower` etc family of methods. As of now, they return new `bytes`/`string` objects. I (rather strongly) think if they are called on mutable `bytes` object, they should return new mutable `bytes` object.

But providing alternatives like `convertToUpper` or something like that that can make the change in-place sounds like a good idea to me both in terms of elegance and performance. Another interface alternative is to provide overloads with `inPlace=false` argument that can be passed to mutable `bytes` only. I slightly prefer new set of methods.

p.s. python's `bytearray.upper()` method also returns new `bytearray` object. I don't see an in-place alternative, though.

**Comment by bradcray** [comment]
I agree that `toUpper` and `toLower` should behave consistently for bytes and strings whether the bytes type is mutable or not.  I remain confused after last week's meeting about the assertion then that it is in-place for strings and follow-up comments that it's not.  I.e., do we want it to be in-place and it just didn't happen to get implemented that way the first time around?

**Comment by mppf** [comment]
@bradcray - the user-facing API is that it's not in place (it returns a new string) but the *implementation* currently does it in place.

**Comment by bradcray** [comment]
Does that mean that the implementation is incorrect, or that it's correct and doing it in-place, simply on a newly copied string rather than the original one?  (and in either event, does this mean that the German character problem isn't really a problem we need to worry about—that we just need to allocate additional bytes when we copy the string for such characters?)

**Comment by e-kayrakli** [comment]
The current implementation creates the copy of `this` and iterates over the copy character by character (or byte by byte for `bytes`) and changes them in the copy's buffer *in-place*.

The German character problem is a problem. It wouldn't be if these methods were starting from an empty string and appending character by character.

**Comment by e-kayrakli** [comment]
Just to clarify I don't think we should change anything about `toUpper` etc and the mutable `bytes` objects should also not change `this`. However, providing some in-place alternatives only for the mutable `bytes` type seems appealing.

**Comment by mppf** [comment]
> The German character problem is a problem. It wouldn't be if these methods were starting from an empty string and appending character by character.

Right, this is getting a bit off-topic here, but I think that is an implementation bug and should be fixed.

**Comment by e-kayrakli** [comment]
While playing around with the `bytes` implementation and how we can achieve this, I have three following alternatives:

1. **Add a `set` method. Give a compiler error if `mutable==false`.**
   We may need this because `bytes.this` returns a `bytes` object. Therefore, supporting mutable bytes is probably not as easy as just adding a `ref`version of `proc this`
2. **Add a `proc this() ref` that returns another mutable `bytes` object which shares the original object's buffer. And add a `proc =(b: bytes(mutable=true), i: uint(8))` that can only be used for 1-length bytes objects.**
   This sounds like jumping through bunch of hoops.
3. **Try to see if we can have something like `bytesView` object or something that is returned by `proc this()` and `proc this() ref`**
  This may be the most principled approach. But it may be an overkill. It can also support idioms like (1 can also do this, I think. it is more difficult for 2):

```chapel
var b = b"some bytes";
b[1..4] = b"no"; //note the length change
```

I am leaning towards 1 because its simplicity. Also, one can argue that not supporting `b[4] = 65;` even for mutable bytes avoid possible confusions.

**Comment by bradcray** [comment]
> bytes.this returns a bytes object. 

I would've expected `bytes.this(i: integral)` to return a uint(8) (or ref-to-uint(8)) since it's the closest thing we have to a byte.  I think the main reason that this is not the case for strings is (a) because the size of the return type could be variable, (b) to get null-termination (?).

I think `bytes.this(r: range)` is a different can of worms and would imagine taking the bytesView-style approach.

**Comment by mppf** [comment]
>  I think the main reason that this is not the case for strings is (a) because the size of the return type could be variable, (b) to get null-termination (?).

I think it's so that the type is more self contained. `string.this(i)` could return an `int(32)` representing a codepoint.

Anyway I think bytes and string should be consistent in this regard (return integer or return same type).

I'd like to have bytesView / stringView objects that "borrow" from the original string/bytes and are checked by the lifetime checker. But I wouldn't use those for `this(i: integral)`.

**Comment by BryantLam** [comment]
> I think it's important for bytes and string to support the same API where possible. People will be toggling code between them a lot (at least if Python 3 experience is any indication).

I want to reiterate this point. I imagine that someday the bytes and string type would implement a constraint so that a constrained generic could use either of them for most of the work. There might be a limited set of calls that only make sense on strings (Unicode?) or bytes, but even some straightforward things like `.numCodepoints` could be implemented on bytes.

**Comment by bradcray** [comment]
In discussing `bytes` a bit today, I found myself wondering whether we'd want to tie "fixed length" nature with "mutable" nature such that only fixed-length bytes (ones that can be allocated in-place and will never require re-allocation) can be mutated.  This could be done with a second type like `fixedBytes` or `bytesFixed`, or could potentially be done by having a `bytes` type initializer that took a size as a param (or maybe even a const?), e.g. `bytes(size=4)` that enabled both the allocate-in-place and mutable behaviors simultaneously.  My thinking is that general `bytes` may get reallocated or reassigned over time, but that the memory for fixed-size bytes will always be in the same place, making it more amenable to re-assignment, somewhat similar to arrays (which is what I fall back to when I want a fixed-length or mutable bytes today, which always seems unfortunate). Does this quick reaction hold up?

**Comment by mppf** [comment]
Since we started this discussion, we've added `c_array`. I am curious if fixed-length `bytes` is more appealing than corresponding `c_array`, e.g., `c_array(uint(8), 4)`. If so, why?

**Comment by bradcray** [comment]
>  I am curious if fixed-length bytes is more appealing than corresponding c_array

I agree they're similar, but I think fixed-length `bytes` remains attractive because (a) if I'm writing Chapel code that doesn't interact with C, I don't want to rely on a `c_` type / the `CTypes` / `CInterop` module to write this pattern, and (b) I want the full suite of `bytes` methods and library routines to work with my data (without opting into C-specific things like the ability to assign between `c_array` and `c_ptr`, etc.).

In addition, I'd like a fixed-length `bytes` type to be able to be `const` or `var`-sized rather than requiring it to be `param`-sized.

**Comment by e-kayrakli** [comment]
We are living with "No" as an answer for the original question for a while. I think we are happy with that decision and that's how we stabilized `bytes` for 2.0.

This issue still has a lot of interesting discussions for potential for future alternative types or improvements for the `bytes` type. For the time being I am closing this issue with a Notes label on it.
