### ISSUE TITLE
Change the default privacy from public to private?

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#13801]
We've long toyed with the idea of whether the default privacy should be `private` instead of `public`.  We haven't made the switch yet due to having lived in a world where everything was `public` for a very long time (since we hadn't implemented privacy controls until fairly recently) - changing the default behavior would be a breaking change and involve having to update a lot of code to explicitly be `public` that was before relying on the default.

This issue is to consider what should change.  We may need to split it into subissues (though I would argue for avoiding that as much as possible, as it will make the rules easier to remember).

**Comment by lydia-duncan** [comment]
The following idea was mentioned [here](https://github.com/chapel-lang/chapel/issues/13528#issuecomment-522785424):
> `use M;` should mean `public use M;` if M is a public module and `private use M;` if M is a private module

I find this idea appealing.  With that in mind, I would propose that we separate this discussion into two categories:
- privacy of statements
  - Currently, use statements are the only thing that would fall under this category, though import statements will likely do so as well
- privacy of symbols
  - This contains the brunt of what we expect to apply privacy to: modules, functions/iterators, module level variables/params/consts, type aliases/enums/classes/records, etc.

I would then propose that we focus on the privacy of **symbols**, and allow the default privacy of statements to reflect the symbols that are used in them (see also [this comment](https://github.com/chapel-lang/chapel/issues/13528#issuecomment-521826447) and the comment preceding it).

**Comment by bradcray** [comment]
The last time this topic was brought up with users in the room, the decision was made to stick with public-by-default and call it done.  The main rationale I heard is that this is what Python programmers would expect and Python programmers are a community that are often attracted to Chapel.

**Comment by lydia-duncan** [comment]
Closing based on the above.  We can revisit this if folks feel differently later

**Comment by BryantLam** [comment]
One idea that I like a lot is to transition toward changing the default privacy to some new "package public" but not truly public. Rust currently uses keyword `pub(crate)` to denote this where the `crate` keyword specifies the boundaries of where `public` is visible, in this case, only `public` to submodules of a crate/package.

That way, package authors can still use all their submodules in a "public" way but package *users* cannot call into any functions (e.g., from the top module) unless they're explicitly marked as `public`. This seems like the best of both worlds where authors aren't overly annoyed (and can still `private` any modules that don't need exposure to other modules in the same package) while still being explicit in which interfaces are presented to actual users via explicit `public`.

**Comment by BryantLam** [comment]
https://github.com/chapel-lang/chapel/issues/7200#issuecomment-536132008 got me thinking that the default privacy specifier should be changed to `private`. (.. or with other module changes to introduce  packaging, then `pub(crate)` would make more sense).

Benefits
- Implicitly use the better specifier for improving compilation performance
- `private` is backwards-compatible if later changed to be a weaker privacy specifier, such as a `pub(crate)`-equivalent
    - In the worst-case scenario, `private` would later become `public` again and we'd only have wasted a lot of time, whereas going from `public` to `private` is not possible without breaking things.

Disadvantages
- Potentially a lot of code would break today, though I do wonder how much code in actuality. How often is it that an author uses a non-`use`d symbol from one of their own modules via a transitive `use`?
    - In a way, this would also enforce better coding practice because C/C++ has transitive includes and users eventually learn that you should (try to) include headers in a self-contained way so that removal of other headers don't adversely affect the current translation unit. In practice, this doesn't always happen because of the infectious transitive behavior of headers effectively always being `public` whereas Chapel users can decide on `public use` to opt into that behavior.

**Comment by mppf** [comment]
@bradcray - I feel a bit confused by this issue being closed when combined with some of the discussion elsewhere, e.g. 

https://github.com/chapel-lang/chapel/issues/6067#issuecomment-379006730

> we've discussed the idea of making declarations in prototype modules and standalone code be public by default ("I'm sketching code and want to be able to access everything unless I say otherwise") whereas non-prototype module declarations might be private by default ("Don't expose anything unless I intentionally requested it"). I don't think there's been enough discussion of this issue to know that it's our path forward

But I might be missing something...

**Comment by bradcray** [comment]
@BryantLam: I'm definitely open to making `use` statements interpreted as `private use` by default.  I interpreted this particular issue as not being about public vs. private `use` statements by default but rather whether various declaration types (`var`, `proc`, `module`, `type`, etc.) should create public or private symbols by default if there's no modifier in front of the declaration.  That said, it's worded generally, so maybe it was intended to include both of these things?  In any case, I think we should fork the question as to whether `use` should be private by default into its own issue (and I agree that, other than the pain of making the switch, it seems like it's probably the better/safer default now that we have both flavors of `use` available).  (unless we wanted to have some sort of bigger switch for "I'm just sketching code in this module, so anything it declares or uses is public unless stated otherwise" vs. "this is intended to be a production module and anything it declares or uses is private unless stated otherwise").

To @mppf's question, in an offline user meeting that took place after the comment on #6706, we had an extensive conversation about public or private by default and after much debate, the decision was made to stick with the status quo.  The two main arguments that were made were (1) it's what Python programmers are used to, so if we're trying to attract them, that seems like the right option, and (2) it's what we've already got so it's not a breaking change.

That said, my preference probably would be private-by-default, and I didn't mean to imply that I'm not open to reconsidering this question (I've had Python enthusiasts tell me that they think private-by-default would be better, for example).  But since we are getting a lot of pressure to stop changing things and we did "make a decision", I didn't want to re-open a topic that was supposedly resolved (esp. since the OP of this issue, didn't introduce any new data or perspectives to negate the previous decision).

Back on the comment in #6706, though I've only heard a few opinions about prototype vs. production modules, most of them have been uniformly negative.  I'm personally still a big fan of having two modes of coding, one supporting quick sketches, and the other supporting production code, but it doesn't seem like the current mechanism for indicating that is winning hearts and minds (and I don't think I've seen a counterproposal that could take its place).

**Comment by bradcray** [comment]
(Aside: Bryant and I were chatting a bit more about making `use` private by default offline and wondering what the impact would be, leading me to put together a branch that tries it out for user code... will see what the impact on testing is).

**Comment by bradcray** [comment]
I forked this question about making uses private by default into issue #14183
