### ISSUE TITLE
Should we reserve 'init', 'init=', or 'deinit' as keywords?

### ISSUE THREAD

**Issue by benharsh** [chapel-lang/chapel#13897]
It might be a bit odd to reserve these when they're mainly just method names, but 'init=' is odd enough to warrant the discussion (and 'init'/'deinit' by association).

[edit: and postinit as well?]

**Comment by e-kayrakli** [comment]
In other contexts I mentioned that I am always on the side of reserving keywords, and I think the same way for `init`, `init=`, `deinit`. Because:

- I don't see them as very useful in other contexts. i.e. why would an application need a variable named `init`?

- Even if that was allowed, I'd find application code that uses `init` in another purpose confusing enough to ask the question why wasn't this reserved in the first place.

@bradcray --

I am not sure we'll be losing something if we do not support `ref x = this; x.init()`. Moreover, isn't it a bit different than reserving the keyword? I mean we can still allow the user to call `init` explicitly if there is a compelling reason to do so, and at the same time prevent them to be defined by the user.

**Comment by bradcray** [comment]
> I am not sure we'll be losing something if we do not support ref x = this; x.init().

In asking, I was worried that if we did support it, we'd open up a can of worms because currently the compiler looks for calls to `this.init()` and `super.init()` and does special things with them.  I was worried that if we were to support arguably equivalent forms of calling them it might complicate the implementation unnecessarily (and the ability of a user to understand the code?).

> we can still allow the user to call init explicitly if there is a compelling reason to do so, and at the same time prevent them to be defined by the user.

I suppose that's true.

**Comment by mppf** [comment]
If you left the decision entirely in my hands, I probably would not reserve `init` or `deinit` since these are primarily used as method names (rather than as something one can call) as was pointed out earlier. I.e. I don't see a chance for confusion with a variable `var init: bool;` in most contexts. However I am OK with reserving them, especially if Swift does so.

In the future, we may need to (in some very special cases) allow the user to more or less call init explicitly in something kindof like "placement new". Another strategy here is to rely on a "move" operator, which doesn't have the same impact regarding the keyword. But anyway I don't think this changes the picture much because we already have `this.init()` and `super.init()`.

**Comment by lydia-duncan** [comment]
It doesn't seem to have been mentioned here, but we should also note that `deinit` can be used for module deinitialization, and we have toyed with allowing `init` for module initialization.  With that in mind, the situations where `init`/`deinit` can be used other than in ways we have defined as part of the language dwindles significantly

**Comment by bradcray** [comment]
Came across this while reviewing issues related to today's deep-dive to see which new ones I should file.  @mppf when we originally discussed, you were open to this, but not necessarily in favor of it.  How are you feeling these days?

**Comment by dlongnecke-cray** [comment]
My intuition is that we should reserve all these as keywords. I found it very surprising that they were not already (and the fact that I've never felt the desire to use any of them outside of their normal contexts suggests to me that they should be reserved).

**Comment by mppf** [comment]
I think it's OK to reserve init, init=, and deinit as keywords.

**Comment by vasslitvinov** [comment]
... and `postinit` ?

**Comment by bradcray** [comment]
In a recent post-meeting discussion, we agreed to reserve `init`, `deinit`, and `postinit`.  `init=` is already reserved.  Now we just need to implement and document it.

**Comment by bradcray** [comment]
In implementing these, I would expect:
* deinit to be simplest (should only be used to define things; can't be called explicitly I believe)
* postinit() to be next (can be called, though it's not common)
* init() to be the hardest (due to calls within initializers through `this.init()`, `super.init()`, and maybe just `init()`(?)

I'd view the approach for the first two to be:
* deinit:
  * add to lexer
  * add to parser as a primary, secondary, or tertiary method you can define
    * must have 0 arguments, no return type (declared or inferred from return statements)
    * post-parse checks should make sure we don't have standalone deinit() routines
  * have it map down to the identifier `deinit` like any other identifier
  * don't accept it in other places in the parser
  * is that sufficient?

*  postinit()
  * similar to deinit
  * we could permit it to have more than 0 arguments as long as they were all defaulted, but for starters, I'd force zero and wait for someone to request other options
  * also have a rule in the parser's statement-level procedure call rule for `postinit()` (the only way it can be invoked, I believe?)

* init()
  * pretty different because of:
    * taking arguments
    * supporting multiple overloads
    * supporting explicit calls
    * (the first two of these are a lot like `init=`; the last is different though)

**Comment by cassella** [comment]
FWIW, there's somewhat related discussion in #8991.

**Comment by stonea** [comment]
> deinit to be simplest (should only be used to define things; can't be called explicitly I believe)

Looks like we explitly call it here: https://github.com/chapel-lang/chapel/blob/0359f8f257a7f2984895bb3bff844016c3d4b3ff/modules/internal/ChapelBase.chpl#L2569

though, given that it looks like this is where we implement the "implicit" call I don't think it'd be too much of a hack if we just add a new primitive to handle explicitly caling it there.

Doing some cursory greps in our module and test code I also see an explicit call to `deinit` here:

https://github.com/chapel-lang/chapel/blob/main/test/classes/deinitializers/deinitExplicitCall.chpl 

With the `.good` file is locking down the error: "error: direct calls to deinit() are not allowed".

So yeah, it looks like this isn't something supported in user-code today.

**Comment by bradcray** [comment]
> Looks like we explicitly call it here:

Oh wow, I had no memory of that.  I like your idea of using some sort of primitive / internal-only capability to get the behavior given the context and the error for user code.

**Comment by lydia-duncan** [comment]
This has been resolved - these names are reserved.  Closing
