### ISSUE TITLE
Ability to export routines that accept / return `byte`s

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#14110]
As a Chapel programmer working with Python, I'd like to be able to pass Python bytes objects into exported Chapel routines, operate on them within Chapel as type `bytes`, and return `bytes` expressions from exported Chapel routines back to Python as `bytes` objects.

**Comment by dlongnecke-cray** [comment]
The key concern that differentiates `bytes` from `string` is that it is legal for `bytes` to contain embedded null bytes, while UTF8 strings may only have a null byte as a terminator (similar to ASCII strings).

The process for exporting bytes will probably end up looking identical to strings short of how we choose to handle embedded null bytes.

---

At some point early in resolution, the compiler generates wrappers for routines that have string formals/return types. The wrapper maps string formals to `c_string` and returned strings to `c_ptr(int(8))`. 

Any changes to interop process to handle embedded null bytes would have to occur during the generation of this wrapper.

---

I think the easiest thing to do for the bytes type would be to declare a well known C type such as `struct chpl_bytes`, which contains a buffer handle along with a `size_t`/`uint64_t` length.

Since bytes may contain arbitrarily embedded null bytes, each buffer has to carry around an explicit length.

While this length could be passed for formals as a secondary argument, I see no way to do the same thing for returned bytes except via another formal argument (using a write pointer) or a struct. 

I personally think that the struct will end up being more elegant, especially when multiple bytes are passed to the same routine.
