### ISSUE TITLE
Feature request for reinterpret_cast/transmute.

### ISSUE THREAD

**Issue by BryantLam** [chapel-lang/chapel#14140]
Feature request to be able to modify the raw representation of a primitive type, like `real`s.

C++ has `std::reinterpret_cast` and Rust has `std::mem::transmute` to e.g., turn a `real(64)` into a `uint(64)` or vice versa. In the C++ case, care has to be taken to avoid undefined behavior or incorrect use of strict aliasing.

**Comment by mppf** [comment]
For `real` and `uint` specifically, this is discussed in #12053, where a solution is demonstrated using `c_memcpy`. I think `c_memcpy` is a reasonable solution for the implementation, but it would probably be nice to have a more user-facing way to do this for `real` to `uint` and back.

One proposal for that is a `jam` method - https://github.com/chapel-lang/chapel/issues/12053#issuecomment-455447758

Another variant discussed in that issue is `ieee754` / `toieee754` / `fromieee754`.

For arbitrary POD types, I think `c_memcpy` is a fine way to do this.

**Comment by damianmoz** [comment]
I can say as a user that it works brilliantly. Very clean.

**Comment by damianmoz** [comment]
After 2 years of usage, it works fine for a **const**.

But it does not work for a **param** and that needs to be addressed, probably sooner rather than later.

**Comment by bradcray** [comment]
> But it does not work for a param and that needs to be addressed, probably sooner rather than later.

To make this comment more concrete, would you be able to provide a code sample demonstrating what isn't working as you'd like?  I have some guesses, but don't like to guess.  Thanks.

**Comment by damianmoz** [comment]
I was deliberately holding off in case somebody had a better idea. It probably needs a round-table discussion @mppf knows a lot more than me on some details of this.  For completeness and at the risk of repeating the obvious to those who already know the details,  this sort of thing is done in C/C++ using type-punning which exploits the idiosyncracies of **union**s of floats+uint32_t and double+uint64_t.

By way of any example, the following code uses an interface **ieee754** module which provides functionality which matches and then enhances what is seen in C's **float.h** or C++'s **<numeric_limits>**. It uses the same technique to which Michael referred in his early post on this issues The interface is evolving. The code for the interface is given below this sample usage:
```chapel
// given
var x : real(w) = .... ;
param sqrt2 = 1.414213562373095048801688724209698;
// then 
const bits = x.asBits; // asBits property is the raw IEEE754 bit-wise encoding of `x`;
...
assert(bits.type == uint(w)); // those bits of a real(w) can be stored in a uint(w)

param sqrt2Bits = sqrt2.asBits; // not possible - see implementation below
```
Instead of `asBits`, I tried names of `bits` and `encoding` and `layout`,  the first being it strict definition as per the IEEE 754 standard, and the layout being an alternate description of it in the standard.

The implementation for a **const** or *var**, but not **param** identifier or expression is below. Any ugliness seen is solely mine. All good ideas seen belong to @mppf.
```chapel
    // extract the IEEE 754 encoding from a real(w) into a uint(w)

    inline proc (real(?w)).encoding : uint(w)
    {
        var src = this, dst:uint(w);

        c_memcpy(c_ptrTo(dst), c_ptrTo(src), c_sizeof(src.type));
        return dst;
    }

    // convert the IEEE 754 encoding inside a uint(w) to a real(w)

    inline proc type (real(?w)).reify(x: uint(?k)) : real(w)
    {
        var src = x, dst:real(w);

        compilerAssert(w == k);
        c_memcpy(c_ptrTo(dst), c_ptrTo(src), c_sizeof(src.type));
        return dst;
    }
```
It is fast. The Chapel compiler optimizes out the call to `c_memcpy`. Idea by @mppf. Thanks Michael.

What is in **ieee754** now works 80% of the time as I only need encoding of **param**s some of the time.

I could do the following messiness
```chapel
inline proc fpSqrt2RawEncoding (type T) param where T == real(32)
    return 0x3fb504f3:uint(32); // the correctly rounded bit pattern of sqrt2:real(32)
inline proc pSqrt2RawEncoding (type T) param where T == real(64)
    return 0x3ff6a09e667f3bcc:uint(64); // the correctly rounded bit pattern of sqrt2:real(64)
......
param sqrt2Bits = fpSqrt2RawEncoding(x.type); // where `x` was defined earlier in this post
....
// what we really want is
....
param sqrt2Bits = (sqrt2:real(64)).asBits; // if I want the 64-bit representation
// or
param sqrt2Bits = (sqrt2:real(32)).asBits; // if I want the 32-bit representation
```
But that is ugly.

At one stage I thought a generic solution was to allow the following to be legal. It basically makes type punning a first class operation.
```chapel
const bits = (x:void(w)):uint(w);
const sqrt2Bits = (sqrt2:void(w)):uint(w);
```
I think @bradcray and/or @mppf or both told me a long time ago that this was flawed. I cannot remember the details but it was several years ago. Maybe it was just too naughty to be considered.

There are actually more pieces to this puzzle that @mppf raised in #18599. But they have nothing to do with making the raw encoding, i.e. bit pattern within a **real**(w), available within the program, so I will avoid complicating things unless we want to kill this issue stone dead.

@mppf preferred the name of `toBits()` which agrees with Rust. Swift 4 has no equivalent method although you can recover the bits, i.e. raw encoding, associated with the individual Negative, Exponent and Significand fields.

**Comment by damianmoz** [comment]
Sorry, my first attempt at that last post had an old version of the **.asBits** and **.asReal** methods which had very different names.

I edited that last post to correct my mistake.

Maybe there needs to be a **bits**(w) type which only supports the assignment operator. That really just amounts to replacing the word **void** above with **bits**. Just a thought.

**Comment by damianmoz** [comment]
From memory, and I have not used it for a long time, that **jam** method was just a way to expose C's type punning which uses a C **union**. It was my attempt at transmute which I think it the concept we seek.

Michael's suggestions works just as well as my old **jam** method for anything except a **param**. And it is pure Chapel so it was cleaner than my attempt. If I could have figured out a way to return a param intent from C using an inline function, then mine would been a more universal solution.  Maybe there is a way but it was beyond my skill set. And I have no idea of the internals of reinterpret_cast. 

Anyway,. that is the history of how I got to here and Michael's helpful involvement. I have been using that for a few years now.

**Comment by mppf** [comment]
Right, we can't call `c_memcpy` on params. We would have to add some sort of primitive to the compiler (whether it is something like memcpy or something more like "real to bits as uint" / "bits as uint to real") to have it work on params. But either way I'd expect we'd want to add something along the lines of `asBits` / `asReal` to the standard library, somewhere, and from there consider adding support for `params` in it.

**Comment by bradcray** [comment]
@mppf: Correct me if I'm wrong, but what we're talking about here sounds relatively straightforward to me, where the only challenging part is coming up with a good name for the routines.

For the bits-to-type case, my first thought was that maybe it should be an `asType(type t)` method so that it could be applied to other types as well.  But I suppose that—at least for the types whose memory layouts are at all guaranteed in Chapel today and that would fit into a uint—the floating point types are the only ones that really need this capability?  (i.e., we'd only really need `asReal()`, `asImag()`, and `asComplex()` of varying widths?).  I suppose it's possible that some user records would fit within a uint as well and therefore maybe want the conversion, but OTOH, it's challenging for us to guarantee that as a language, at least without taking a stronger role with memory layout in the C back-end...

**Comment by mppf** [comment]
> @mppf: Correct me if I'm wrong, but what we're talking about here sounds relatively straightforward to me, where the only challenging part is coming up with a good name for the routines.

Yes. And in particular, ideally the name communicates that it is a very different operation from `1.1:uint` e.g. which just results in `1`.

> But I suppose that—at least for the types whose memory layouts are at all guaranteed in Chapel today and that would fit into a uint—the floating point types are the only ones that really need this capability?

Yes, I think we should limit our concern here to floating point types, and floating points that we are saying are IEEE 754 types at that.

**Comment by damianmoz** [comment]
Would not the AsImag() and AsComplex() build on the more fundamental asReal() operation, or what Rust calls transmutation which leaves it quite generic and means you don't have to worry about IEEE 754 at all?

The key issue here is how you handle this problem when the data you have is a **param**.

My agonizing over the name previously was all about trying to make it easier to document things and make it obvious for people to use. In the end, I simply ensure that there was a preamble in the document explaining what I was doing in the same sort of language as say a text on floating point computation. That is all about representation, encoding and layout. As long as I explained what I was trying to achieve, I could leave the introduction of the name until later in the documentation. Mind you, whatever name it is, it still needs to read well when you are reading code. But you are on top of that.

**Comment by bradcray** [comment]
> Would not the AsImag() and AsComplex() build on the more fundamental asReal() operation, or what Rust calls transmutation which leaves it quite generic and means you don't have to worry about IEEE 754 at all?

Implementation-wise, yes—they'd all be doing the same thing at the core.  The reason for the different routines would be so that different return types would get generated for Chapel, along the lines of:

```chapel
proc (uint(32)).asReal(): real(32) { ... }
proc (uint(32)).asImag(): imag(32) { ... }
proc uint.asReal(): real { ... }
proc uint.asImag(): imag { ... }
proc uint.asComplex(): complex(64) { ... }
```

**Comment by bradcray** [comment]
> The key issue here is how you handle this problem when the data you have is a param.

Oops, hit "send" too soon.  Yes, I think the answer here is that we teach the compiler how to do this sort of casting, expose it as a primitive, and then use that primitive to implement the param versions of the routines above.

**Comment by damianmoz** [comment]
No rush, but what is the timeline here?

This new feature is the only way I know to handle the **param** definition of a Signalling NaNs. Even doing it with a **const** is a bit messy.

It could also mean that the **param** INFINITY or (under Chapel 2.0) **inf** could be implemented directly in Chapel.

Thanks.

**Comment by bradcray** [comment]
I've put together a quick prototype for the param real(64) -> param uint(64) case in this branch https://github.com/bradcray/chapel/tree/real-uint-param-bits-convert and asked @damianmoz to try it out and see if it's working as expected.  If so, I'll clean it up and extend it to 32-bit values and in the opposite direction.  Here's a sample test I used to run it:

```chapel
param r: real = pi;

compilerWarning(r:string);

param u: uint = r.toBits();

compilerWarning(u:string);

writeln(r);
writeln(u);

proc param (real(64)).toBits() param : uint {
  param ui: uint(64) = __primitive("real64 as uint64", pi);
  return ui;
}
```

Note that I'm not committing to this interface name or design, just used it as a way to expose the primitive that implements the param conversion.

**Comment by damianmoz** [comment]
Great. Thanks for progressing this @bradc. I will investigate it shortly. Will that work for **const** **real**(w) data too?

**Comment by damianmoz** [comment]
Thanks for the explanation. Just wanted to know what I needed to test. You are right. There is already a working solution for **const** and **var**..

**Comment by bradcray** [comment]
Thanks for confirming.  I'm definitely imagining we would merge support for param, var, and const at the same time once we get to the point of having a PR to merge.  I just wanted to focus my effort on where it seemed to be needed most for now.

**Comment by bradcray** [comment]
@damianmoz: Just pinging on this to see whether you've had a chance to give it a try yet.

**Comment by damianmoz** [comment]
I (largely) wrap that other project up tomorrow. So should have time next week.

**Comment by damianmoz** [comment]
OK. Looks like simple testing with **real**(64) works.

But, the lines of code for a **real**(32) were missing.

So, assuming the 8 in the 64-bit stuff meant 8 bytes, I changed that a 4 and 64 -> 32 and recompiled.

Simple testing shows that **real**(32) works also!!

Thanks heaps.

Can I use this version as my 1.28 version?

**Comment by damianmoz** [comment]
On a slightly tangential note, but related to your post above, given a real number _x_, how do I compute
```chapel
i * x
```
and vica versa.

That simplifies the _AsImag_ method above, etc.

**Comment by damianmoz** [comment]
The reason why I asked about that coercian was that I would normally do
```chapel
const two = 2:real(32);
const _0plus2i = two:imag(32);
const _2asreal = zeroplus2i:real(32);

writeln(_0plus2i.type:string, " = ", _0plus2i);
writeln(_2asreal.type:string, " = ", _2asreal);
```
which shows the types as **imag**(32) and **real**(32) respectively.

However, I saw a routine
```
_i2r(...)
```
the other day and wondered what it is all about. Or is that now deprecated?

Just curious.

**Comment by bradcray** [comment]
> OK. Looks like simple testing with real(64) works.

Great, thanks for taking a look Damian!  (and yes, you're correct that I didn't implement the 32-bit versions... wanted to make sure that this was as expected first).  I'll see if I can get this in for next month's 1.29 release.

> However, I saw a routine `_i2r(...)` ... is that now deprecated?

Not deprecated, but not intended to be user-facing.  As a user, I would typically write this pattern using the cast as well.

**Comment by damianmoz** [comment]
Your 64-bit implementation was clear and clean enough that my quick cut and paste and **g/64/s//32/gp** gave me the 32 bit version instantly.

Thanks again. Looking forward to 1.29.

**Comment by bradcray** [comment]
@damianmoz : Do you have some favorite floating point <-> integer values that I could use as validation tests to lock in that my implementations are correct?  I've been Googling around a bit to see whether I could stumble across any great examples, but apparently haven't come up with the right terms yet, so I thought I'd ask the master.  Thanks!

**Comment by damianmoz** [comment]
I have no favorite values but I normally test with **real**(32) because that means I only have to check 32 bits are correct, not 64.

I will normally pick some significands for testing (what some people call the mantissa) which are exact, e.g. 
```
higher 3 bits all 1,
higher 3 bits all 1, lower 3 bits all 1
```
as well as significands which are approximate like those of 1.0/7.0, 1/13.0, and 1/17.0.

And then use lots of different exponents.

If need be, I run tests on every possible **real**(32). That is impossible for **real**(64) but that I do not have a Cray with a gazillion cores at my disposal, and even that might be pushing it.

The big trick is manipulating the bit patterns which are IEEE 754 encodings is to try and do simple operation and be rigorous in how you use those encodings. And anywhere that is not obvious, comment liberally.

As the IEEE 754 standard evolves every 10 years, and usage is influenced somewhat by what the optimizer does, always a moving target, I can never be a master, I just keep learning and relearning. I still find myself bouncing ideas off others who are members of the IEEE 754 committee, others in the floating point community, and, through an intermediary, Kahan himself. So, I know I will never be a master, but hopefully always competent. Maybe by the time I get to Kahan's age which is nearly 91 now, I might get closer to that goal.

Hope that helps. Feel free to send me your test program and I can see if I can add anything to what you are doing.
