### ISSUE TITLE
UTF-8 validation for strings

### ISSUE THREAD

**Issue by e-kayrakli** [chapel-lang/chapel#14177]
Chapel strings are UTF-8 encoded. However, currently we don't check whether a given byte buffer is a valid UTF-8 sequence while creating a string.

The general consensus is that we should add this check during string creation. Interestingly, doing so can allow us to cache some properties of the string (number of codepoints, whether it is all ASCII etc) to improve performance for some common operations.

Exactly when should we validate?
--------------------------------

There are two main ways a string is generated in Chapel. String literals, and
I/O. They both end up calling an appropriate string factory function at the end.
So there are two alternatives on implementing UTF-8 validation.

1. String creation time: This is in the common path for both ways. So, it means
less implementation and maintanance effort. Another benefit is that if we want
to piggyback some metadata caching about the string (whether it is ASCII, or
some information about multibyte codepoints).

2. Separately in I/O and parser: This has the advantage of giving an error early if
necessary. Arguably, long string literals are unlikely so maybe it doesn't make
much difference for parsing string literals. But it may matter if you are
reading a long file and there are invalid bytes right in the beginning. Another
advantage may be giving a compile time error if the source file contains strings
literals with non-UTF-8 bytes.

Going through some of the past discussions, it seems that the agreement was that
we are going with the first option.

What is the behavior for when there are invalid bytes in a string?
------------------------------------------------------------------

If we are going with option 1, then we'll need to throw an error. Currently we
have a `DecodeError` which is thrown when you attempt to decode a `bytes` with
invalid byte sequence to `string`. Should we use the same error type? Or do we
see UTF-8 validation as a different (more intrinsic to the language may be?)
error and should create a different error type.

One other alternative is to rename it so that it explains the issue more clearly
for either case. `StringDecodeError` can be an option and I don't think it'll
create any confusion if it comes from `bytes.decode`

Should we add a "back door"?
----------------------------

We may consider allowing the users to opt out from validation. Most obviously
this can allow them to get rid of the validation overhead if they know the input
string to be UTF-8 in the first place. But can we support something like that
for string literals? If so how? We can consider adding an environment variable
to control the overall behavior. This is also related to #12728 and to some 
extent adjusting the Chapel environment to use UTF-8 encoding.

Note about NULL bytes
------------------------
NULL byte is valid ASCII and therefore UTF-8 and Chapel strings and bytes
currently can contain NULL bytes. Strings will continue to do so even after
validation is implemented. C (and maybe other) interoperability layers should
avoid using `strlen`, `strcmp` etc functions that rely on NULL-terminated
strings.

Caveats
-------

- `string.localize()` creates a copy of the string. If the string was local to
  begin with, this is done through calling `createStringWithBorrowedBuffer`
  which re-validates the string. We may want to do something better than
  `localize` in the future. For now I see three alternatives:

  1. If we do not have a back door, then, a string is validated already.
     Therefore, we don't call validate if `createStringWithBorrowedBuffer` is
     called with a `string`

  2. If we add a back door, then, we should keep a `var valid: bool` in string
     record.

  3. Do nothing and accept that we may validate a buffer that has already been
     validated. (I am not a big fan of this option)

- It looks like the current QIO decode logic we have may not support some UTF-8
  sequences. This may need to be adjusted. One example that I bumped into is the
  replacement character `\uFFFD`.

**Comment by e-kayrakli** [comment]
#12723 suggests a test which can probably be part of this effort

**Comment by e-kayrakli** [comment]
#14325 Makes some changes to the `bytes` implementation that are necessary for this to move forward

**Comment by mppf** [comment]
Re where to validate:

> 1. String creation time
> 2. Separately in I/O and parser

It seems obvious to me that somebody creating a string literal containing invalid UTF-8 would want the error to occur at compile-time. Having program start-up fail and instead throw an error due to invalid UTF-8 in a literal seems unfortunate.

Here I think that neither of the options presented are sufficient. I think that the compiler should arrange to call an internal/private function for the string literals which does not do validation. Other than that, I think that we should start by doing the validation in the string validation functions. Since not all string creating happens through I/O, this covers more cases than 2. describes.

In the future, we might have the I/O system take on the task of ensuring that any read data is valid UTF-8. Arguably it already tries to do that (but we would need to do more testing and make adjustments - the issue above already noted an issue with the UTF-8 replacement character). If that happens, I would expect the I/O system also to use an internal/private function to create the strings in a way that does not do validation in order to avoid redundancy. However, the user-facing string factory functions would still do validation in that event.

Summing it up - I think validating in the string factory functions is a great starting point, and from there we should validate literals/param strings at compile-time and then validate read string data in the I/O code (and then arrange to avoid redundant validation if there is any benefit to doing so).

**Comment by bradcray** [comment]
> I think validating in the string factory functions is a great starting point, and from there we should validate literals/param strings at compile-time and then validate read string data in the I/O code (and then arrange to avoid redundant validation if there is any benefit to doing so).

I agree with what Michael says (and think it's consistent with `writef()/readf()` where ultimately we want to do more compile-time checking for param formatting strings, but having any checking is better than none).

I don't think there should be a back door for users, but that having a "prevalidated" code path for internal use makes sense.

I don't have a strong feeling about validating within the I/O system vs. at string creation time at present.  Whatever we do, I'd like to not have to support three different string validation pieces of code.  Ideally, they'd all use the same code (which might suggest doing the validation in C so that it can be reused in the compiler and via the runtime?).

**Comment by e-kayrakli** [comment]
> I don't think there should be a back door for users, but that having a "prevalidated" code path for internal use makes sense.

Just to be clear, the following is not a back door (simply because it is not documented) right?

```chapel
var x: string;
x.buff = my_c_arr_that_contains_non_utf8_sequences;
```

Arguably you can break many things if you play around with the internals of types and UTF8 validation will only be an example of that?

I think more or less this is something that we can use internally to avoid redundant validation. For example, when we are returning from `bytes.decode()` we don't need to validate the string because we expect the decoded buffer to be valid utf8.

**Comment by bradcray** [comment]
Right, I'm saying that I don't think the language should support an officially sanctioned back door (at least, I haven't been convinced of that yet).  If we have one for our own development purposes, don't document it, and a user chooses to step into it, I don't think that's a problem (for us... it may be a problem for them if we change things down the road).  In this case, I assume it's relying on the existence of a `.buff` member within string that is undocumented and therefore arguably being abused (?).

**Comment by e-kayrakli** [comment]
>  In this case, I assume it's relying on the existence of a .buff member within string that is undocumented and therefore arguably being abused (?).

Yes, that's correct.
