### ISSUE TITLE
Should there be const pointer types for interoperability?

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#14214]
In C, `const char*` and `char*`are different types. Should the Chapel interoperability support allow one to express a C pointer to const?

It might be written `c_ptr_const`.

Associated future test:
  test/extern/ferguson/externblock/struct-fn-ptr.chpl

**Comment by bradcray** [comment]
Would we also need a different variant to express `char* const`?

**Comment by mppf** [comment]
@bradcray - I've never understood the point of that in C, honestly. But arguably
```
const x: c_ptr(c_char);
```

or

```
proc f(const arg: c_ptr(c_char)) { }
```

does it, doesn't it?

**Comment by bradcray** [comment]
That's what I was wondering as well.  I think for a single variable or argument, yeah, it might.  If you needed to describe an array of these, or a pointer to one of them, though....  Maybe it comes up rarely enough that we can cross that bridge when we need to.  It's just what springs to mind when I start thinking about trying to represent the variety of type compositions using distinct identifiers in Chapel.

**Comment by bradcray** [comment]
Thinking about this today in the context of #18792, it seems as though when we add this, we'll need either a different routine like `c_ptrToConst` to create these pointers, or will have to add support for overload disambiguation based on the const-ness of the actual argument (or will have to leverage the compiler to implement `c_ptrTo()`).

Specifically, I'm imagining something like the following for scalar types:

```chapel
proc c_ptrTo(ref x: ?t): c_ptr(t) { ... }
proc c_ptrTo(const ref x: ?t): c_ptrToConst(t) { ... }
```

where today, we don't support such overloads.

**Comment by bradcray** [comment]
@mppf: @riftEmber and I were talking about this a bit today, and I was musing about whether it was low-hanging fruit or not.  It seems like it should be (other than agreeing on a syntax maybe), but was curious whether you saw challenges I didn't:

* create some source-level way to distinguish between `const t*`and `t*`, whether that's using two types (as you suggest in the OP), an optional `param` in the type or the like (this design probably being the hard part)
* have some of the c_ptr capabilities become aware of this choice (e.g., have `this` return a `const ref` rather than a `ref`
* have the C back-end emit the `const` when code-generating
* I think you've said that nothing is required to be done for the LLVM code generator?

Are there other things you're aware of here that I'm forgetting about?

**Comment by bradcray** [comment]
Also, I find myself thinking it'd be nice to have `c_ptrTo(expr)` return the equivalent of a `const t*` when `expr` is const and ` t*` when it's not, but I don't think we could express this at the Chapel level today because it would require the equivalent of overloading based on argument intent.  Does that seem right, or is there something I'm overlooking?

**Comment by mppf** [comment]
>  It seems like it should be (other than agreeing on a syntax maybe), but was curious whether you saw challenges I didn't...

To my understanding, settling on the language design here is the hard part, and I would agree that the implementation is not really a big deal.

> because it would require the equivalent of overloading based on argument intent. Does that seem right, or is there something I'm overlooking?

We can use return intent overloading & I think the compiler will emit a const-checking error in one place or another if you try to get a `ref` for a `const` value.

Additionally, we do discard candidates needing to pass something `const` to a `ref` argument. I think combined with return intent overloading, this could work for this case as-is. I think it's interesting to consider if we want to allow overloads based solely on argument intent. I would imagine we could have a design there that is a generalization of return intent overloading. But, I don't know if/when we really need that.

**Comment by bradcray** [comment]
@mppf: Thanks for these comments, which I'm only getting around to reading now.  I'm not seeing how return intent overloading would help, so am curious whether I'm missing something obvious, or whether I just didn't ask the question well.  I think the ideal would be if we could write:

```chapel
var x: c_int = 45;
const y: c_int = 33;
var px = c_ptrTo(x);
var py = c_ptrTo(y);
```

and have `px` be a `c_ptr(c_int) while `py` is a `c_ptr_const(c_int)` or `c_ptr(c_int, const=true)` (or however we end up spelling the pointer-to-const type).  But in both cases I'd expect the thing being returned to have `out` rather than `ref` return intent, so am not seeing how return intent overloading could come into play (worse, in trying some experiments to do some more aggressive/workaround-y things with return intent overloading, it looks as though they have to have the same return type?)

**Comment by mppf** [comment]
>  in trying some experiments to do some more aggressive/workaround-y things with return intent overloading, it looks as though they have to have the same return type

Yeah, I think you're right about that, so it's not going to work as-is.

We might be able to adjust the compiler to treat c-pointers similarly to references within the compiler. Or, we could make other language changes to enable this pattern (generalizing return intent overloading in some way; maybe to formal intent overloading). 

The reason I had been thinking that return intent overloading would work today is that I was mis-remembering how [formal intents impact which functions are candidates](https://chapel-lang.org/docs/language/spec/procedures.html#legal-argument-mapping). I remembered that it *does* consider the formal intent. However, it just uses that to decide whether implicit conversions are allowed. It does not rule out candidate functions for const-checking reasons. We could consider making it do that (or, we could make the ones that will result in an error be less preferred during disambiguation).

**Comment by riftEmber** [comment]
I have created issue https://github.com/chapel-lang/chapel/issues/21597 for design discussion on this next sprint.

**Comment by riftEmber** [comment]
Const C pointers are implemented in https://github.com/chapel-lang/chapel/pull/21913.
