### ISSUE TITLE
How to create ownership for an unmanaged class?

### ISSUE THREAD

**Issue by vasslitvinov** [chapel-lang/chapel#14300]
Consider the situation where the user creates a class instance as `unmanaged`, then later wants to manage it automatically as an `owned` or `shared`. How should the user express this conversion? Here are some ideas:

```chpl
(A)   var myOwned = new owned (myUnmanaged);

(B)   var myOwned = myUnmanaged: owned;

(C)   var myOwned: owned C?;
      myOwned.retain(myUnmanaged);

(D)   var myOwned = myUnmanaged.toOwned();

(E)   var myOwned = buildOwned(myUnmanaged); // some global function

(F)   var myOwned = owned.fromUnmanaged(myUnmanaged);  // a type method
```

**A** is how we do it now.
**B** is currently disallowed; we could allow it.
**C** is available, currently it requires that 'myOwned' be nilable.
**D** would introduce a sibling to `.borrow()`.

[2020-01-14] The current consensus is **F**.
**C** will remain available.

**Comment by mppf** [comment]
Other alternatives:
``` chapel
(E)  var myOwned = buildOwned(myUnmanaged); // some global function
(F)  var myOwned = owned.takeUnmanaged(myUnmanaged);  // some type method
```

**Comment by mppf** [comment]
This issue is related to #13950 and #14298.

**Comment by bradcray** [comment]
(A) seems weird to me because I think it's one of the only cases where `new` is not followed by a type (I'm not considering `owned` to be a (complete) type).

(B) seems acceptable (and maybe even attractive) to me, though I don't have a good sense of how orthogonal / similar it is to other related constructs and patterns.

(C) seems acceptable, but unfortunately verbose.  Then again, I don't know how common this case will be or how streamlined we need to make it.

(D) seems acceptable and potentially attractive, though also pretty similar to (B) if (B) doesn't have any drawbacks / points of confusion

(E) seems strictly less attractive than (F)

(F) I might call this method something else, but it also seems acceptable / attractive

**Comment by mppf** [comment]
I don't like (B) but I'm not sure I can coherently explain why.

I don't like (D) because it uses up a method name and I don't think we really need to (i.e. users won't be able to write MyClass.toOwned).

I think I'm personally happy with (A) or (F) (whatever the final name becomes).

**Comment by bradcray** [comment]
Given that my displeasure with (A) comes from thinking of it as not having equivalents in the language (cases where `new` takes something other than a type, the keyword `owned` being applied to something other than a type or generic type specification context), are there other parallels to this that I'm not thinking of?

If not, it sounds like the intersection (between you and I anyway) is (F) which I find attractive (it's what I would've come up with this morning if I'd been asked to propose something, modulo the specific name).

**Comment by mppf** [comment]
> Given that my displeasure with (A) comes from thinking of it as not having equivalents in the language (cases where new takes something other than a type...

I don't think of it that way - I think of `owned` as a (generic) type containing all `owned` clases.

**Comment by bradcray** [comment]
I think of `owned` as being part of a type specification, but not a complete type.  So in the cast context, I think of the expression `this: that` as indicating "make this into that (where if "that" isn't a full specification, the rest can be inferred from the value context of `this`) whereas in the `new ...` context, I really expect to see a full type specification and to not leave anything up to guesswork.  I.e., I really think of the pattern as `new complete-concrete-type(arguments)`.

**Comment by mppf** [comment]
>  I.e., I really think of the pattern as `new complete-concrete-type(arguments)`.

Right, but if we have

``` chapel
record R { var x; }

var rec = new R(1);
```

then the type argument to `new` is generic.

(It would be fine with me to consider it a totally subjective choice, in which case we might still choose F... and anyway `new owned()` might be syntactically confusing because people are used to `new owned C()` ... and since it's a rare enough operation having special syntax for it isn't necessarily the right move).

**Comment by bradcray** [comment]
That's a good point, but I don't think of `owned` as being generic in the same way.  And while the class argument to it could be viewed as providing the missing detail, it still seems different to me than `1` in your `new R(1)` providing the missing detail that `R` needs.  To me, it tips its hand to our implementation approach rather than the notion of it being a keyword-based modifier on a class type.  I think the syntactical confusion you allude to is definitely where my head is at (it doesn't feel like the pattern I'd expect to see is complete or expected).  This is just my opinion, though, I'd be curious what others think as well.

**Comment by vasslitvinov** [comment]
I am viewing `owned` w.r.t. the `new` context the same way as Brad does. I also like treating `owned` as a generic type that is instantiatable with any concrete `owned` type.

F sounds good to me. How about `owned.fromUnmanaged(x)` ?

**Comment by vasslitvinov** [comment]
Naming proposal: `owned.create(arg)`

`create` seems to be the leading choice for factory methods in #14291 .

@bradcray OK with you?
