### ISSUE TITLE
Reflection getRoutineName -> getProcName

### ISSUE THREAD

**Issue by BryantLam** [chapel-lang/chapel#14342]
Bug / feature request. Why is the `Reflection` function to get a function name called `getRoutineName`? I naturally assumed it was `getProcName` (it wasn't) and I had to go look it up.

Please rename `Reflection.getRoutineName` to `getProcName`.

**Comment by bradcray** [comment]
I believe the answer for this choice is "because it is intended to apply to iterators and procedures."  We've typically used the term "function" to refer to this union, but I've recently been lobbying for routine or subroutine because I think function is a more loaded term (and doesn't suggest iterators to me).

**Comment by BryantLam** [comment]
Hmm okay. I can at least understand how Routine was chosen. As a note for user experience, I work with procedures almost all the time, so `getProcName` just seemed natural to me.

That said, I don't care too strongly other than having to remember this tidbit or look up the documentation every so often, so feel free to close out the ticket if there's no more discussion. Thanks!

**Comment by bradcray** [comment]
We could potentially support `getProcName()` and `getIterName()` variants that would only work if they were in the corresponding context and throw a compiler error otherwise.  That would give you the behavior and name you'd expect and support your common case without strictly introducing two ways to do the identical thing (since the behavior is different when used in the wrong thing).

**Comment by BryantLam** [comment]
It's an interesting idea, though I don't think I would care about having a compiler error if I ever decided to refactor from a procedure to an iterator. From a code-correctness standpoint, the runtime behavior of the variants didn't change.
