### ISSUE TITLE
`map` doesn't work when value type is an owned class

### ISSUE THREAD

**Issue by BryantLam** [chapel-lang/chapel#14361]
Bug. `map` doesn't work when value type is a class.

```chapel
class MyInt {
    var x: int;
}

use Map;

var myMap = new map(string, owned MyInt);
```
```terminal
# chpl version 1.21.0 pre-release (8b3bca92)
$CHPL_HOME/modules/standard/Map.chpl:96: In function 'init=':
$CHPL_HOME/modules/standard/Map.chpl:105: error: illegal lvalue in assignment
```

Also, I'm certain the `remove` function won't work either since I tried something similar on a bare associative array.

**Comment by bradcray** [comment]
The reported behavior seems specific to the value type being an owned type.  Making it a shared or unmanaged class makes the code above work.  That said, I think there are other problems with non-nilable element types and maps, related to issue #14367 (i.e., I think the current map implementation works for cases like `map(string, shared MyInt)` today because of #14367, where it would stop working if/when #14367 was fixed).

Tagging @daviditen on this.

**Comment by daviditen** [comment]
The thing that is causing this error is that the `init=` function takes its argument by `const ref` intent. Then it assigns all of the values (in this case none) in the `rhs` map to the `lhs` map, which for an `owned` class type modifies the const `rhs` to set the values to `nil`.

Changing the argument to use `ref` gets rid of the error by allowing the `rhs` to be modified.
