### ISSUE TITLE
Chapel C_NetCDF not populating arrays

### ISSUE THREAD

**Issue by diyorzakirov07** [chapel-lang/chapel#14369]
I have a 3 dimensional netcdf file that I am trying to read.
One of the dimensions is latitude values that I was trying to put into an array using nc_get_vara_double. Instead of populating the array with all the values, I am getting just one value repeating over the whole array. One possible work around, is manually populating arrays using loops, but that would be more complex when working with multiple dimensions. 

Here is a snippet of what I am trying to do. 

```chapel
var lats: [1..180] c_double;
var start: size_t = 1;
var count: size_t = 2;
writeln(nc_get_vara_double(ncidTemp, ncvarid(ncidTemp,"lat"),start,count,lats));

writeln(lats);
```

**Comment by bradcray** [comment]
@daviditen: Can you advise here?

**Comment by daviditen** [comment]
By 3-dimensional do you mean that the file contains three variables? It looks like the "lat" variable in the file is 1-dimensional.

The `nc_get_vara_double` function expects an array with the same number of elements as your data is ranked. I think the scalars are working since the data is 1-dimensional, but a better representation would be to make them single element arrays.

I think you want `start = 0` and `count = 180` to read the entire "lat" variable.

The NetCDF library documentation states that new code shouldn't use `ncvarid` but should use `nc_inq_varid` instead.

**Comment by daviditen** [comment]
Somebody pointed out that the call to `nc_get_vara_double` is probably promoting over the `lats` array which isn't what you want here. Can you please try passing a pointer to the beginning of the array instead like this?

```
nc_get_vara_double(ncidTemp, ncvarid(ncidTemp,"lat"),start,count,lats[1])
```

**Comment by diyorzakirov07** [comment]
@daviditen Thank you, passing the pointer seems to solve the problem.
