### ISSUE TITLE
Should non-ASCII literal characters be allowed in bytes literals?

### ISSUE THREAD

**Issue by e-kayrakli** [chapel-lang/chapel#14393]
Currently, bytes literals any literal characters. For example, the following is valid Chapel code:

```chapel
var myBytes = b"Türkçe";  // 'ü' and 'ç' are not ASCII
writeln(myBytes);
```

However, corresponding literal in Python is not allowed:

```python
>>> myBytes = b"Türkçe"
  File "<stdin>", line 1
SyntaxError: bytes can only contain ASCII literal characters.
```

Should we also prevent non-ASCII literal characters to be used in bytes literals? It maybe more in line with the notion that `bytes` type representing arbitrary bytes rather than characters that can be more than 1 byte long. If we do that then the first snippet will have to be written like:

```chapel
// escape bytes individually for Unicode with UTF8 encoding
var myBytes = b"T\xc3\xbcrk\xc3\xa7e";
writeln(myBytes);
```

**Comment by bradcray** [comment]
When you first posted a question about this, I was surprised that a bytes value would be more restrictive than strings in terms of what could be in its literals (since its contents are intended to be more arbitrary, not less).  Your explanation "It may be more in line with the notion that bytes type representing arbitrary bytes rather than characters that can be more than 1 byte long." clarifies the rationale that I was missing.  That said, while it is a "purer" vision of bytes literals, it also feels like a much less productive one (i.e., my intuition would be to let the bytes literal contain anything a string literal could).

At the same time, it always concerns me to go against Python.  Is there additional rationale from the Python community about why they went this way?  Any sign of discontent at not being able to change a string literal to a bytes literal this easily?

**Comment by e-kayrakli** [comment]
I have looked a bit but couldn't find a direct answer to your question. bytes literals were proposed in [PEP 3112](https://www.python.org/dev/peps/pep-3112/)

One thing that I am wondering is how often a file is re-encoded once it is created. Because if a source's encoding is changed, then the contents of bytes literals with non-ASCII character literals would change. Same thing is true for strings but strings are meant to be sequences of characters and it should be OK for them to be re-encoded. This may be a stretch, though.

**Comment by mppf** [comment]
I'd let the non-ascii characters be in bytes literals and then the bytes literal would contain the UTF-8 encoding of them.

I think that Python doesn't promise UTF-8 encoding for strings and as a result such a strategy doesn't make as much sense there.

> Because if a source's encoding is changed, then the contents of bytes literals with non-ASCII character literals would change. 

Chapel source code is (and always will be) UTF-8.

**Comment by e-kayrakli** [comment]
> I'd let the non-ascii characters be in bytes literals and then the bytes literal would contain the UTF-8 encoding of them.

Just for the record, this is what happens right now.

> Chapel source code is (and always will be) UTF-8.

This is assuring for this context. I am personally leaning towards allowing them, because it is less restrictive. But would be fine if we want to prevent them, too.

**Comment by bradcray** [comment]
@e-kayrakli: Searching for something else, I just stumbled into a raft of issues like this that made me ask "can this be closed now?"

**Comment by e-kayrakli** [comment]
It's a bit hard to tell when a design discussion was concluded when the decision ends up to be "no action". Currently this is a "no action" decision, and so far we are happy with that decision. Closing.

**Comment by bradcray** [comment]
Oh, now that you've said that, I was mixing this up with another issue (the one about "can non-UTF8 characters be embedded into strings?").  If you think it's premature to close this, I'm fine with leaving it open as well (though I'm also OK with the status quo I think; at least nobody has said anything about it that's caused me to panic).

**Comment by mppf** [comment]
I'm happy with leaving it as-is (with "yes" to the question in the title).
