### ISSUE TITLE
Sparse subdomain compiler error

### ISSUE THREAD

**Issue by StefanTeodorescu** [chapel-lang/chapel#14562]
### Summary of Problem

I am trying to define an array of sparse subdomains, so I can iterate through them (I need this in the problem I'm trying to solve, not relevant for the bug itself). What I am ultimately trying to achieve are two domains that would iterate through a matrix like a chessboard (one domain for the "white" cells, one domain for the "black" cells). Is there any possible way to do this? From what I see in the documentation, the only type of domain where I can add indexes are sparse ones.

### Steps to Reproduce

**Source Code:**

```chapel
const dom = {1..10, 1..10};
var x: [0..1] sparse subdomain(dom, stridable=true);
```
When I try to compile this code, I get this error:
`foo.chpl:2: internal error: PAS-NOR-IZE-1831 chpl version 1.20.0`

or

```chapel
var x: [0..1] sparse subdomain();
```
When I try to compile this code, I get this error:
`internal error: AST-ALI-0073 chpl version 1.20.0`

**Compile command:**

`chpl foo.chpl` (just simple compilation of my code)

**Execution command:**

I can't execute it as it is a compiler error.

### Configuration Information

- Output of `chpl --version`:  chpl version 1.20.0
- Output of `$CHPL_HOME/util/printchplenv --anonymize`:
```
CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: gnu
CHPL_TARGET_ARCH: x86_64
CHPL_TARGET_CPU: native
CHPL_LOCALE_MODEL: flat
CHPL_COMM: none *
CHPL_TASKS: fifo *
CHPL_LAUNCHER: none
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: cstdlib *
CHPL_ATOMICS: cstdlib
CHPL_GMP: none *
CHPL_HWLOC: none
CHPL_REGEXP: none *
CHPL_LLVM: none *
CHPL_AUX_FILESYS: none
```
- Back-end compiler and version, e.g. `gcc --version` or `clang --version`: gcc (GCC) 9.2.0
- (For Cray systems only) Output of `module list`:

**Comment by daviditen** [comment]
The compiler expects the `subdomain` call to have exactly 1 argument, a domain that is the parent domain. It shouldn't issue internal errors when that isn't the case though, so thanks for filing this issue.

You can avoid the problem by making it have just a single domain argument in each case.

**Comment by daviditen** [comment]
If you want a checkerboard pattern with domains to describe the "black" cells vs. the "white" cells you'd probably be better off with two strided rectangular domains instead of sparse:

```chapel
const dom = {1..10, 1..10};
var x: [0..1] subdomain(dom by 1);

x[0] = dom by 2 align 1;
x[1] = dom by 2 align 2;
```

**Comment by StefanTeodorescu** [comment]
Thanks for answering and giving me a solution for my problem!

**Comment by bradcray** [comment]
It took me awhile to catch onto this, so just in case others didn't follow: x[0] and x[1] together describe only the black squares (say), and an additional two domains would be required to describe the opposite color.  Here's a [TIO example](https://tio.run/##bYzBDoIwEETv/Yo5QmJIl6ONh35H00NBok1qMVAVQ/j2ukWPnjaz7830V3cfQs79GOeE83jDCSs1DckD9rMp8XQTliOM5GwxPzrWnI9Vsbs3qFZCLEZarv5eLVzwlwhSDOgPaLlSZjXPMrLwMSmhTZkpOn0D7YHl1@TTEGKla5XzBw) that illustrates this.

@StefanTeodorescu: In case it's of value / interest: Years ago we talked about how to support this pattern and discussed having a special domain map(*) which could express checkerboard patterns and directly generate loops such that rows would be visited in turn (whereas if we iterated over x[0] and then x[1] in order to get all the black squares above, we'd do all the odd rows first and then all the even rows second which might be just fine, or might be terrible for spatial locality depending on the number of rows and columns; and in either case it's a bit of a mouthful).

You could think of such a domain map as generating loops like the following in C, where each row is visited in turn:

```c
for (i=0; i<8; i+=2) {
  for (j=i%2; j<8; j+=2) {
    ...
  }
}
```

I believe that someone even prototyped such a thing, though I suspect the code has long been lost to time.  Anyway, I mention it because it would be an alternate way to express checkerboard patterns in Chapel, where you might imagine it looking like this:

```chapel
const D = {1..n, 1..n};
var A: [D] real;
const Black: subdomain(D) dmapped Checkerboard(black=true),
      White: subdomain(D) dmapped Checkerboard(black=false);

forall (i,j) in Black do
  A[i,j] = ...
```

(* = a domain map in Chapel is a recipe for implementing domains, loops over domains, arrays over those domains, accessors and indexing for those arrays, etc.)

**Comment by StefanTeodorescu** [comment]
Thanks for the elaborate answer, I've just read it now. I've eventually stuck to the 'naive' for implementation for my pattern. For a little bit of context, I was working on a project which involved red-black successive over-relaxation, which needs exactly this pattern for some CPU intensive operations.

I thought that by using these domains, they would work out data locality better than my own for loops, so the domain map idea sounds cool for this type of optimizations. I guess it's your choice whether you eventually get to fit this in the language, if there is enough demand for a feature like this.

Thanks again!

**Comment by bradcray** [comment]
> I guess it's your choice whether you eventually get to fit this in the language

Just to avoid confusion, it's not really a matter of putting it into the language.  Domain maps are designed to be a user-implementable feature, so it's really a question of whether someone implements this pattern.  That someone could be a user, or it could be us as part of a library.

**Comment by jabraham17** [comment]
Neither of the code snippets cause internal errors on main today, but they do have unhelpful error messages.

This is the second strange sparse syntax error I have come across today (https://github.com/chapel-lang/chapel/issues/13097 was the other). This motivated me to add a better error message for this, which I have done in #25473

**Comment by DanilaFe** [comment]
We had a little bit of a race condition. Jade and I opened our PRs (https://github.com/chapel-lang/chapel/pull/25472 and https://github.com/chapel-lang/chapel/pull/25473) within two minutes of each other.

**Comment by jabraham17** [comment]
I am closing https://github.com/chapel-lang/chapel/pull/25473 in favor of https://github.com/chapel-lang/chapel/pull/25472. The two PRs have identical approaches

**Comment by lydia-duncan** [comment]
@StefanTeodorescu - note that this was resolved when the aforementioned PR was merged.  Thanks for reporting, and thanks @DanilaFe (and @jabraham17 :) ) for fixing!
