### ISSUE TITLE
Time.getCurrentTime behavior isn't generally useful

### ISSUE THREAD

**Issue by BryantLam** [chapel-lang/chapel#14571]
Design issue. The `Time.getCurrentTime` function returns the elapsed (default) seconds since midnight local time, not Unix epoch. Why? This behavior doesn't seem that useful.

1. The user needs to manually transform the output into something useful, like an actual time point; e.g., 7:53 PM. This is in contrast to `getCurrentDate` which returns a `(year, month, day)` tuple; why not this function too? Maybe something like `(hour, minute, second, timezone) :(int, int, real, TimeZone)`.
2. This function shouldn't be used to arbitrarily time code or implement a timer because, in the event that the timing event occurs around midnight, the start and end return values cannot be generally subtracted without accounting for midnight rollover.

**Comment by BryantLam** [comment]
(Documenting this issue before I forget. It's not a priority for me at all.)

**Comment by Aniket21mathur** [comment]
I did some workaround and came across the following functions

1) Python - datetime.now().time() returns a time object with (hours, minutes, seconds)
`datetime.time(21, 34, 51, 343376)`

2)Javascript - We have a single function that gives us both time and date. 
```

2 | var today = new Date();var time = today.getHours() + ":" + today.getMinutes() + ":" + today.getSeconds();
-- | --

**Comment by ben-albrecht** [comment]
@Aniket21mathur - A few comments/questions:

- This issue is about the [`Time`](https://chapel-lang.org/docs/master/modules/standard/Time.html) module rather than the [`DateTime`](https://chapel-lang.org/docs/master/modules/standard/DateTime.html) module, so comparisons to other languages should reflect that.
- Are all time functions returning time since Unix epoch?
- Do any time functions include the time zone like @BryantLam proposes above?
- It would be useful to look at some other modern PLs like Rust, Go, and Swift.

**Comment by Aniket21mathur** [comment]
> * This issue is about the [`Time`](https://chapel-lang.org/docs/master/modules/standard/Time.html) module rather than the [`DateTime`](https://chapel-lang.org/docs/master/modules/standard/DateTime.html) module, so comparisons to other languages should reflect that.

There are some of the time modules that return the current date, along with the time. For example in Go:-

```
    now := time.Now()
    p(now)
```
returns something like

`2012-10-31 15:50:13.793654 +0000 UTC`


> * Are all time functions returning time since Unix epoch?

Not all, some like `time.time()` in Python returns time since Unix epoch.

> * Do any time functions include the time zone like @BryantLam proposes above?

Yes, the `time.Now()` in Go as described above, also `time.timezone` in python returns the offset in seconds of the local time zone from UTC.

Swift3 seems to have a single Date() function that is used to get the components(hours, minutes, seconds) of current time.

Thanks!

**Comment by ben-albrecht** [comment]
@Aniket21mathur - thanks for driving this issue forward. As a heads up, the core dev team is working towards finalizing the Chapel 1.21 release, and probably won't have much time to discuss this design issue until things calm down. 

You are welcome to comment with other information you think is helpful / relevant in coming to a decision, and even propose a design for our `Time.getCurrentTime` in the meantime.

**Comment by Aniket21mathur** [comment]
> You are welcome to comment with other information you think is helpful / relevant in coming to a decision, and even propose a design for our `Time.getCurrentTime` in the meantime.

Sure. :smile:

**Comment by bradcray** [comment]
For those following this issue, we're currently planning on deprecating `Time.getCurrentTime()` and friends in favor of capabilities in the `DateTime` module.  `Time` is a module that dates from the early years of the project when we needed some capabilities to get up and running.  `DateTime` reflects a more recent effort to support a more complete and better designed set of functionality for reasoning about dates and times.
