### ISSUE TITLE
Only seeing 7 cores being utilized when there is 8 cores available using a forall loop

### ISSUE THREAD

**Issue by bofomiso** [chapel-lang/chapel#14626]
### Summary of Problem

When I am running my matrix multiplication using a forall loop I expect all cores to be used but only see that 7 of the 8 cores are being used.
all 4 are used on the first board and 3 of the 4 are being used on the second board.

### Steps to Reproduce

**Source Code:**
```
use Random, Time;

var t:Timer;

t.start();
config const size = 10;
var grid : [1..size, 1..size] real;
var grid2 : [1..size, 1..size] real;
var grid3 : [1..size, 1..size] real;

fillRandom(grid);
fillRandom(grid2);

const D3 = {1..size, 1..size, 1..size};
forall (i,j,k) in D3 do {
  grid3[i,j] += grid[i,k] * grid2[k,j];
}

t.stop();
writeln("Done!:");
writeln(t.elapsed(),"seconds");
t.clear();
```

**Compile command:**
```
chpl --fast -o mm mm.chpl
```

**Execution command:**
```
./mm -nl 2 --size=1000
```
### Configuration Information

- Output of `chpl --version`:
```
chpl version 1.20.0
Copyright (c) 2004-2019, Cray Inc.  (See LICENSE file for more details)
```
```
- Output of `$CHPL_HOME/util/printchplenv --anonymize`:
```
CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: gnu
CHPL_TARGET_ARCH: aarch64
CHPL_TARGET_CPU: aarch64 *
CHPL_LOCALE_MODEL: flat
CHPL_COMM: gasnet *
  CHPL_COMM_SUBSTRATE: udp
  CHPL_GASNET_SEGMENT: everything
CHPL_TASKS: fifo *
CHPL_LAUNCHER: amudprun
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: cstdlib *
CHPL_ATOMICS: cstdlib
  CHPL_NETWORK_ATOMICS: none
CHPL_GMP: none *
CHPL_HWLOC: none
CHPL_REGEXP: none *
CHPL_LLVM: none *
CHPL_AUX_FILESYS: none
```

**Comment by bofomiso** [comment]
![board1](https://user-images.githubusercontent.com/25334380/70669238-a1fae500-1c2a-11ea-8ef7-c42bb5f9b168.png)

**Comment by bofomiso** [comment]
![board2](https://user-images.githubusercontent.com/25334380/70669256-aaebb680-1c2a-11ea-8769-aa95d5b66fc7.png)

**Comment by bradcray** [comment]
Hi @bofomiso — Could you see whether compiling and running $CHPL_HOME/examples/hello4-datapar-dist.chpl and running it on 4 locales with increasingly big problem sizes (`--numMessages=1000` then 10000 then 100000 etc.) gets you a run in which all cores are utilized on your second board.  If so, I think I can explain what's going on.

**Comment by bradcray** [comment]
(Oops, I had a typo in my original post above that I've now fixed.  I didn't mean for you to run it on 4 locales, just 2).

**Comment by bradcray** [comment]
Since this has been quiet yesterday, I'll keep talking to myself:

I think the reason you're not seeing all 4 cores used in the matrix multiplication code you posted here relates to my answer to your most recent [SO question](https://stackoverflow.com/a/59292599/6815267), which is that nothing in your code says explicitly or implicitly to use other locales.  I.e., I believe all of your computation is running on locale 0 (and you could verify this by putting `assert(here.id == 0);` into the body of your forall loop, for example.  See the SO answer for further details.

In contrast, the hello4*.chpl program I mentioned above uses a distributed array to spread work across locales and therefore ought to use all cores which is why I wanted you to check that.

But then that raises the question "Why is there _any_ utilization on your second node if none of the program is running there?"  I believe the answer to that relates to the fact that Chapel does some computation on each node to get the program up and running.  I think the reason that the CPUs still look 100% utilized is that Chapel tends to busy-wait threads when they don't have anything to do.  That said, I'm a little surprised that 3/4 cores are being utilized rather than 1, 2, or all.  Tagging @ronawho who has more experience in this area than I do to see if he has any insights.

**Comment by bofomiso** [comment]
Sorry been away from my computer all day, Just ran it the program hello4-datapar-dist.chpl and it indeed does use all 8 cores 
@bradcray

**Comment by bradcray** [comment]
> What was suppose to happen when I put assert(here.id == 0); into the body of my forall loop.
@bradcray

`here` refers to the locale (node) on which the current task is running and `here.id` gives a unique ID for the locale starting from 0.  If your code were distributed, some of the iterations would be run on locale 1 and the assertion would fail.  It appears to me that it is not (it doesn't use on-clauses, distributed domains or arrays, or other abstractions that farm iterations out to locales), so I would expect the assertion to pass which validates that your code is never using other locales.

This is a pretty fundamental concept in Chapel: the language does not automatically parallelize your code across multiple locales, the burden is on the programmer to do that.  Although using various concepts in the language, like distributed arrays, can simplify that burden significantly.  If you compare the text of hello4-datapar-dist.chpl to hello3-datapar.chpl, you'll see an illustration of this.  The former uses distributed concepts in Chapel, so uses all locales; the latter doesn't, so only uses locale 0.  Your code here is currently like the latter in this respect.

I'm going to close this issue since nothing is actually wrong with Chapel, but we can continue discussing it if this explanation (and the one I put on your SO issue) are still not clear.

**Comment by bofomiso** [comment]
@bradcray It is clear thanks for the explanation.

If I had a question on Cyclic dist would you want me to ask another SO question?
Sorry for all the questions, trying to understand how the language works

**Comment by bradcray** [comment]
I think questions whose answers may be useful to others are ideal for SO since it creates a database of questions and answers.  So if it's a clarifying question about Cyclic, or how to use it, then yes, let's take it back there.  I think GitHub is best for wrestling through personal issues or bugs that may not be of as much value to others.
