### ISSUE TITLE
record comparison not lexicographic order, and not a total order?

### ISSUE THREAD

**Issue by cassella** [chapel-lang/chapel#14783]
My impression of #11347 was that the desire for a record comparison operator was for sorting / search-tree searching purposes.  And @bradcray 's concern that the comparison between records would depend on the order of the fields of the record suggests a lexicographic ordering.

But as implemented, it's not.  As described in the spec changes in #14777, `r1 <= r2` for example returns true only if every field of `r1` compares less than or equal to the corresponding field of `r2`.  This means that there are some records e.g. `r1=(1,2)` and `r2=(2,1)` where `r1` doesn't compare as `<`, `==`, or `>` `r2`, which wouldn't work for using that comparison for some of the uses described in the issue.

I can't tell though if the issue shifted to having a separate `treeOrder()` or `default_comparator()` for cases that need a total ordering?  I don't see the implemented behavior even alluded to in the issue though.

### Steps to Reproduce

**Source Code:**

```chapel
{
  record R {
    var x, y: int;
  }

  var small = new R(1, 1);
  var mid1 = new R(1, 2);
  var mid2 = new R(2, 1);
  var big = new R(2, 2);


  var Rs = [ small, mid1, mid2, big ];

  for r1 in Rs {
    for r2 in Rs {
      writeln(r1, " == ", r2, ": ", r1 == r2);
      writeln(r1, " < ", r2, ": ", r1 < r2);
      writeln(r1, " <= ", r2, ": ", r1 <= r2);
      writeln(r1, " > ", r2, ": ", r1 > r2);
      writeln(r1, " >= ", r2, ": ", r1 >= r2);
      writeln(r1, " != ", r2, ": ", r1 != r2);
      writeln();
    }
  }
}
```

Particularly, this part of the output:

```
(x = 1, y = 2) == (x = 2, y = 1): false
(x = 1, y = 2) < (x = 2, y = 1): false
(x = 1, y = 2) <= (x = 2, y = 1): false
(x = 1, y = 2) > (x = 2, y = 1): false
(x = 1, y = 2) >= (x = 2, y = 1): false
(x = 1, y = 2) != (x = 2, y = 1): true
```

I was expecting `(1,2) < (2,1)` to be true, among others.

edit 1/19: fix bug in test code, which didn't affect this particular stanza.

**Associated Future Test(s):**

None yet.

### Configuration Information

```
chpl version 1.21.0 pre-release (543d7d7)

CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: gnu
CHPL_TARGET_ARCH: x86_64
CHPL_TARGET_CPU: native *
CHPL_LOCALE_MODEL: flat
CHPL_COMM: gasnet *
  CHPL_COMM_SUBSTRATE: udp
  CHPL_GASNET_SEGMENT: everything
CHPL_TASKS: qthreads
CHPL_LAUNCHER: amudprun
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: cstdlib
  CHPL_NETWORK_ATOMICS: none
CHPL_GMP: gmp
CHPL_HWLOC: hwloc
CHPL_REGEXP: re2
CHPL_LLVM: none
CHPL_AUX_FILESYS: none

gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
```

**Comment by e-kayrakli** [comment]
@cassella -- Thanks for pointing this out. Initially reading the issue, I got the impression that we don't want lexicographical order and so implemented a total order. One clarification here, though: You see a total order behavior, right? The issue title is confusing to me, but maybe because it was from before your update to your code.

@mppf @bradcray -- Re-reading the issue and checking the tuple comparisons, I think we want lexicographical order and not total order. It was probably what you both wanted from the beginning but I may have misinterpreted the discussion in #11347.

Switching to lexicographical ordering would probably make sense if we revert some of the refactoring. [Here](https://github.com/chapel-lang/chapel/compare/master...e-kayrakli:record-lex-order) is a quick branch for lexicographically-ordering record comparison functions. It gives the desired behavior for the examples reported in this issue, but probably can use some more testing.

**Comment by cassella** [comment]
I meant a total order in the sense of https://en.wikipedia.org/wiki/Total_order

particularly the last point about `forall a,b, a <= b or b <= a`, which isn't satisfied here.

**Comment by mppf** [comment]
> Re-reading the issue and checking the tuple comparisons, I think we want lexicographical order and not total order. It was probably what you both wanted from the beginning but I may have misinterpreted the discussion in #11347.

I don't care to argue about what "total order" means for us right now, but I would want lexicographic order, just as tuples have, yes.

**Comment by bradcray** [comment]
I'd been assuming lexicographic order for these operators as well.
