### ISSUE TITLE
Code in defer block is run after deinitializer

### ISSUE THREAD

**Issue by dlongnecke-cray** [chapel-lang/chapel#14797]
### Summary of Problem

The code contained in a defer block is run after deinitializers for any local variables created in the same scope.

I expect the opposite to be true (defer blocks run first).

### Steps to Reproduce

Reproducer courtesy of @mppf:

```chapel

record R {
  var x: int;
  proc init() { this.x = 1; writeln("init 1"); }
  proc deinit() { writeln("deinit ", this.x); }
}

proc test() {
  var rec = new R();
  defer { writeln("defer setting 0"); rec.x = 0; }
  writeln("created rec ", rec);
  writeln("end");
}

test();
```

Note that taking a reference to the variable or avoiding use of a defer block both seem to fix this issue.

**Comment by bradcray** [comment]
To make sure I'm understanding: The assertion is that it's more correct to have the defer block run first and then the local variable initialization, is that right?

It seems this was the case in 1.20 ([TIO](https://tio.run/##VY5NCoMwEIX3nuLhSqEU3Tb0Et5AkmkNSJQ4VEE8ezqJNtBVJjPv59NDP9MYgic9eYMOewF8eo/tAetYyW/2k5bZclVjBw92uW94olVYvWUaXVXGK9qyVjh@BkPZkmXnDuXtSkn6oyiSgWlJ8qtfgKTE0YquqiOGoRf5/7S4WIjZujea2C6mxNacIFmqPfVMJoVKuzwpMt/JGbFHlJNChfAF)).  Has it changed since then?

**Comment by mppf** [comment]
Yes. The issue is that `rec` in the example is deinited "after last mention" which, today on master (after my recent deinit changes), the compiler thinks is right before `writeln("end")`. But, since `rec` is mentioned in the `defer` block, the compiler needs to keep it alive until the defer block runs. To fix, I'm expecting to adjust the compiler to consider a use in a defer block to make a variable expire at the end of the block. This will not be hard to adjust.
