### ISSUE TITLE
[design] import statement, a la Python

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#14799]
This issue is a counterproposal to #13831 and #14790, based on behavior in Python.

What Python Does
==============
For the following examples, M is a package module that contains another module N, which contains a symbol x and a symbol y.

Qualified Example
------------------
For qualified access to N's symbols, you can use two strategies.  You can use the basic `import` form:
```Python
import M.N

print(M.N.x) # Full path as specified in the import is required
# Note: you can rename upon import to shorten this
```
Or you can use the `from ... import ...` form:
```Python
from M import N
print (N.x)
```

Unqualified Example
---------------------
The `from ... import ...` form can also be used for unqualified access of N's symbols, both by listing all the symbols to get in an unqualified manner:
```Python
from M.N import x, y
```
or by blanket including them (this is frowned upon):
```Python
from M.N import *
```
You cannot specify non-module symbols as the last stage name in a basic `import`.

Module Paths
--------------
Usually, a fully qualified path to a symbol is required to access it.  However, you can specify relative paths to shorten the fully qualified name, using leading `.`s.  For instance, if the M package also had a module Other, you could import it from N like this:
```Python
from . import Other
```
and if instead Other was a sibling to M, you would write:
```Python
from .. import Other
```

Re-Exports
-----------
Python `import` statements cannot be declared to be public, so far as I can tell.  However, you can allow symbols it imported to be available to other modules using the `__all__` variable.

For instance, to allow M to re-export N's x and y as though they were in M only, you can write this in M:
```Python
from .N import x, y

__all__ = ['x', 'y']
```

Note that `__all__` limits the symbols available when a `*` is used, but that public symbols (e.g. symbols that don't start with `_`) in the module can still be accessed by explicitly mentioning them in the import statement.

The Proposed Chapel Strategy
======================
Similarly to the strategy proposed in #14790, the Chapel `import` statements will trade off between specifying qualified or unqualified access.  While we could use the `from` rearrangement syntax, it does seem a little confusing so this proposal sticks with using `only` lists to specify unqualified access (though we can certainly still use `from`).  Following Python, specifying a longer path as part of the import statement will result in needing that full path for qualified access.  E.g.

```chapel
module M {
  module N {
    var x: int;
    var y: bool;
  }
}
module User {
  proc main() {
    import M.N;
    writeln(M.N.x); // works
    // writeln(N.x); // doesn't work, only M.N is brought in, not N on its own
    // writeln(x); // doesn't work, unqualified access of N's symbols is not enabled by the import
  }
}
```
Here's an example accessing M.N's symbols in an unqualified manner only:
```chapel
// same definition for M and N
module User {
  proc main() {
     import M.N only x, y;
     writeln(x);
     writeln(y);
     // writeln(M.N.x); // does not work because neither M nor M.N itself are brought it
  }
}
```

Differences from #13831 
-------------------------
- Enables `import` to bring in qualified and unqualified access to more than just a module itself
- Drops `except`
  - This means that users have to explicitly list every symbol they want included for unqualified access. We probably should enable `*` to be used in the `only` list so that full unqualified access is not a burden
- `only` list applies to unqualified access instead of limiting what qualified access is available
  - This gives the user less control over qualified access.  However, it's entirely possible that most users won't want to limit what can be accessed in a qualified manner, so maybe it won't be missed.
  - It also might be confusing to have the presence of the `only` list impact whether we are enabling qualified or unqualified access, when that is not the case for `use` statements.
- Qualified access must include the full path specified in the `import path.to.module` case.
  - This is the main difference from the Rust strategy in #14790

Similarities to #13831 
----------------------
- Still enables `as` for renaming a symbol
- Still uses `import` for the keyword

Open Question
---------------
- Currently we support naming a module relative to your current scope in addition to from the top level without additional steps.  However, Python requires leading `.`s to do so, corresponding to the relative depth difference.  Should we follow that precedent here?
- `use` statements in Chapel support `public` and `private` for determining whether their presence at the top level of a module impacts scopes which `use` that module.  However, Python chooses to have all `import` statements only be `private`, with the `__all__` variable definition enabling more direct privacy control for the module's symbols (instead of assuming leading `_` indicate privacy) and symbols it obtained via import.  Should we follow that precedent for exposing re-export capabilities - using potentially a new keyword, or a module-level variable, or something along those lines?

**Comment by BryantLam** [comment]
> * Qualified access must include the full path specified in the `import path.to.module` case.
>     * This is the main difference from the Rust strategy in #14790

Do you know if the `from ... import ...` syntax became more preferred in Python specifically because this stated behavior seems really confusing to me. Does the design document for `from ... import ...` mention this quirk (?) as a problem that was being solved?

I can see that Python adopting `from M import N` yields more predictable behavior (a la Rust-style targetted imports) because `from x import y` will always import *just* y (i.e., qualified access to `N`) whereas `import x.y` always require fully specifying `x.y` in all symbol lookups.

> * Currently we support naming a module relative to your current scope in addition to from the top level without additional steps.  However, Python requires leading `.`s to do so, corresponding to the relative depth difference.  Should we follow that precedent here?

Personally, I like that there's no ambiguity due to anchoring, but the choice of syntax that Python selected is rather error-prone. Dots become harder to see when you start trying to make a difference between `...` versus `....`. Also, it encourages deeper hierarchies if you have to traverse more than two levels above your current scope, which IMO is a bad thing.


> * However, Python chooses to have all `import` statements only be `private`, with the `__all__` variable definition enabling more direct privacy control for the module's symbols (instead of assuming leading `_` indicate privacy) and symbols it obtained via import.  Should we follow that precedent for exposing re-export capabilities - using potentially a new keyword, or a module-level variable, or something along those lines?

This seems acceptable, though less elegant than simply using `public` which has a known definition in OO languages. Python's solution seems more like a quirk of the language's evolution.

**Comment by lydia-duncan** [comment]
I'm not finding the design document for `from ... import ...`.  It looks like it's been around since at least PEP 8, and is mentioned in the "what's new in Python 2.0" docs from 2000.  I suspect the requirement of the fully qualified path is less confusing when coming from the perspective that the full path wasn't available outside of import statements.

**Comment by BryantLam** [comment]
From [the References section of `import`'s documentation], there's some PEPs that might be relevant for their rationale sections. PEP 328 talks about absolute vs. relative imports. The other PEPs are relevant for packaging.

**Comment by BryantLam** [comment]
More thoughts. In a hypothetical world, the Python-inspired form would be:

```chapel
import std.io.Buffer; // Python-style
std.io.Buffer.someTypeFunc();
var x = new std.io.Buffer.Object();
```
versus
```chapel
import std.io.Buffer; // Rust- or Chapel-style
Buffer.someTypeFunc();
var x = new Buffer.Object();
```

I personally don't see a benefit to the Python-inspired style since you could technically do the same thing without an import statement at all using some (notional) anchor point to the top-level:
```chapel
// `import /` is implied
/std.io.Buffer.someTypeFunc();
var x = new /std.io.Buffer.Object();
```
If the anchor was to a relative point, I think this is even more moot:
```chapel
import this.Child; // Rust: self::Child
this.Child.someFunc();
var x = new this.Child.Object();
```
I don't see the benefit in writing it with this style versus `import this only Child`. And if users prefer `import this only Child`, why offer the former behavior?

I think my argument against this behavior in particular is that it doesn't seem useful.

**Comment by BryantLam** [comment]
(Side note. There's an ambiguity with using `this` instead of `self` as an anchor point. Something to think about.)

**Comment by lydia-duncan** [comment]
I made some slides to make it easier to compare the proposals side-by-side.  The difference between the two is that the first will be consistent with the line for `M.x` (for instance) across the charts, while the second will always group all supported syntax together and all unsupported syntax together, even if that means interspersing checkmarks and Xs.

[2020-02-04-import-rearranged.pptx](https://github.com/chapel-lang/chapel/files/4156532/2020-02-04-import-rearranged.pptx)
[2020-02-04-import.pptx](https://github.com/chapel-lang/chapel/files/4156533/2020-02-04-import.pptx)

**Comment by BryantLam** [comment]
Slide 14: `self`/`this` extension. It would be convenient, but isn't a requirement; a user could still convert each `use` statement into two `import` statements of equivalent behavior.

Slide 14, Box 3: A user could write `import M only N as B, self as A`, but that's just bad practice. One limitation the compiler could impose is to not allow renaming on `self` so the user is coerced toward writing it as two lines:
```chapel
import M as A;
import M.N as B; // [[0]]
```
(They could still write the equally awful `import M as A only N as B` unless Chapel forbids a module rename on the same line as an only-symbol rename as discussed previously.)

----

My hot take on the important questions.

#### How much of `import`'s design should be shared with `use`?

I'm in favor of `import` being its own thing, but I recognize that `use` statements have inherited a lot of behaviors over the years. [This may mean that `use` statements should be equivalent to whatever other statements if only to bring sanity to how `use` statements should behave.](https://github.com/chapel-lang/chapel/issues/14790#issuecomment-578865648) If some clause on a `use` statement elicits confusion, the user could proxy the equivalent `import` (or whatever) statements and determine what behavior should result.

I personally prefer more fine-grained control over my symbols whether that is with one `import` grand design or with some design-constrained `import` + other keywords.

#### Is it confusing to switch between qualified access and unqualified access?

It only looks confusing with the current syntax choice. Rust's approach is to always import the last component, regardless of what kind of symbol it is. It doesn't feel as confusing if the syntax was instead:
```chapel
import M;            // qualified access
import M.a;          // unqualified access
import M.{a, b, c};
import M.a as x;     // [[1]]; similar to form [[0]]
import M.{a as x, b as y, c as z};
```
though admittedly the last line is something users still have to recognize as unqualified access since it is only apparent if you write it as three `import` statements of the [[1]] form.

#### Should `import` enable shorter qualified access or longer qualified access?

I would prefer shorter. See https://github.com/chapel-lang/chapel/issues/14799#issuecomment-582138123.

#### Should module paths always be from a root location?

I would like some way to disambiguate. #13915 

#### Should we retire `use` after this?

No opinion other than *I* don't want to use `use` statements.

**Comment by BryantLam** [comment]
One case not covered in the slides is `import M.N as B`. If I had to guess, I don't know what Python would do.

**Comment by lydia-duncan** [comment]
Python uses that as a way to shorter long paths, so you'd be able to write `B.x` instead of `M.N.x` or `M.B.x`

**Comment by BryantLam** [comment]
Wow that's crazy. I would have guessed `M.B.x`.

**Comment by lydia-duncan** [comment]
I think at this point I can say that we're going to follow the Rust proposal for import statements, replacing `only` list syntax with more Rust-like `.{}` lists to avoid the clarity issue Greg pointed out.  This means that:

- `import M;` will enable `M.x` (aka qualified access to M's symbols)
- `import M.x;` will enable `x` (aka unqualified access to the symbol x defined in M)
- `import M.{x, y};` will enable `x` and `y` (aka unqualified access to the symbols x and y defined in M)
- `import M.N.O;` will enable `O.x` (aka qualified access to O's symbols without always having to use `M.N.O` at the front)
- `import M as N;` will enable `N.x` (aka qualified access to all of M's symbols but using the name N)
- `import M.x as mx;` will enable `mx` (aka unqualified access to x but using the name mx
- `import M.{x as mx, y};` (aka unqualified access to M.x and M.y, calling them mx and y respectively) 

It sounds as though we will not support `import M.*;` for the moment (this would mean unqualified access to all public symbols in M if we were to implement it).  We may revisit this later if users request it, but will encourage `use` statements in its place.

We can support things like `import M.{x, y, this};` to enable `x`, `y`, and `M.<all public symbols in M>` (aka unqualified access to x and y, and qualified access to M's symbols), but will wait to do so until there is user demand.

We're going to wait to decide on relative imports of nested modules (e.g. importing M.N from within M) based on discussion around submodules-as-files.

For re-exporting symbols, the general consensus is to use `public import` as opposed to alternate syntax or strategies.
