### ISSUE TITLE
Syntax for ref-maybe-const intent

### ISSUE THREAD

**Issue by daviditen** [chapel-lang/chapel#14822]
There is an internal ref-maybe-const intent for formal arguments, but it is not exposed currently with any syntax. In trying to get owned classes working with `map`, I've found that exposing this intent would be useful. A proposed syntax from @mppf is to add a question mark to const, e.g.

```chapel
proc f(const? ref argName) { ... }
```

This would make argName be `ref` if `f` modifies it, and `const ref` otherwise.

**Comment by mppf** [comment]
I'd just add that ref-if-modified is the default intent for arrays and record `this` method arguments. It seems appealing to have an explicit way to request it.

It would be nice if it could combine with return-intent-overloading as well, since it's common to want to write a function accepting some arguments (or maybe `this`) as ref-maybe-const and then return ref-maybe-const (where the return const-ness is the same as the argument). Today we tend to do this with multiple overloads.

**Comment by cassella** [comment]
Does this conflict or a synergize with the syntax Brad mentioned in #14639 (for a different maybe-const question)?  I can't tell if there might be an ambiguity when the arg to `f()` might just plain be a const or not as in that issue, vs. the ref-if-modified behavior desired here.

**Comment by mppf** [comment]
@cassella -

`proc f(const? ref argName) { ... }` is but one straw-person proposal for the feature.


`proc f(const(?) ref argName) { ... }` would syntactically fit better with what @bradcray proposed in #14639 (and would allow naming the const-ness as a param bool, presumably, like `proc f(const(?isconst) ref argName) { ... }`  - which allows for returning something with the same constness - `proc f(const(?isconst) ref argName) const(isconst) { ... }`.

**Comment by mppf** [comment]
Allowing something like `f(const(?isconst) ref argName) { ... }` would not be trivial in the implementation because the compiler doesn't currently clone functions for ref-maybe-const arguments. It would have to start doing that in order to set the param because it's not known until after resolution which return intent overload would be used.

Also we could consider making ref-maybe-const the default intent for more types. It is currently the default for arrays but it might be interesting to consider making it the default for `owned` or for records generally.

**Comment by jabraham17** [comment]
Closing this, as we decided to deprecate and remove ref-maybe-const. See #21398
