### ISSUE TITLE
Should we revise some formal names in bytes/string interfaces?

### ISSUE THREAD

**Issue by e-kayrakli** [chapel-lang/chapel#14877]
### The problem

Some `bytes` methods/functions take another bytes or buffer arguments that are
named `s`. This is a rather trivial design choice, but it didn't get much
attention (none at all?) and it may be surprising/annoying to some.

The methods/functions in question:

```chapel
proc createBytesWithNewBuffer(s: bytes); // and 5 other factory functions
proc join(const ref S); // S can be tuple or array
```

### Options

1. Keep as-is.

  **Pro**: The symmetry with `string` makes remembering argument names and
  generic programming with both easier.

  **Con**: Maybe confusing.

2. Change those formal names to `b`.

  **Pro**: More consistent with type name
  **Con**: Asymmetry with string

3. Change both `string` and `bytes` methods/functions to have a common name

  **Pro**: Symmetry and likely consistent naming
  **Con**: Changes in `string` arguments can have a big impact on existing code.

### My opinion

The formal for `join` should change because of capitalization, anyways.  I think
we can adopt different approaches for factory functions and the `join` method.

Left to my own devices, I'd:

- Take 3 for `string.join` and `bytes.join` and change the formal name to
  `items` (or `values`)

- Take 2 for factory functions, because they are not symmetric with `string.

I can't ignore the appeal of 1 for not breaking anything, though.

**Comment by bradcray** [comment]
I think more descriptive names would be nice (i.e., option 3), both for the end-user who wants to use formal-ident-based argument matching; and for the developer who wants to search on all references to the identifier.  If we stuck with short names, I'd probably choose something neutral and less commonly used like 'x' rather than 's' and/or 'b'.

I don't expect a lot of (user) code will break over this change whenever it's made, but better to make it sooner than later.  We arguably have similar "poor choice of name" issues with lots of other module functions that didn't get much attention when they were introduced, even when symmetry did not come into play.

**Comment by e-kayrakli** [comment]
I am currently leaning towards making all those arguments listed in the original post to `x` following @bradcray's suggestion.
