### ISSUE TITLE
How to import nested modules?

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#14904]
This is a sub issue of #13831, #14790 and #14799.

It's still up in the air whether nested modules will be able to be imported using
relative naming without some special action to indicate relative naming should
occur.  E.g. for a module structure:

```chapel
module A {
  module B {
    var x = 13;

    proc foo() {
      writeln("In B.foo()");
    }
  }
  import ...; // what to write here to import B ?
}
```
what import statement(s) could be written in A to allow qualified access to B's
symbols?

Should relative naming be allowed, e.g. `import B`? 

Pros of relative naming:
- Convenience
  - Adding strategies like `this.<submodule>` or `self.<submodule>` would restore
     some of this convenience
- Makes submodules less special as compared to other symbols (e.g. variables,
classes, functions defined at the same scope as the submodule)
  - But those symbols can't be put in import statements today* (there will be another issue
    discussing that)
  - More generally, modules already have things that are special about them.  This could be
     one of those things
- Consistent with use statements today
  - But we could similarly update use statements

Cons of relative naming:
- No current way to distinguish in a module hierarchy when multiple modules share a
name and one is defined at the top level
  - Could provide a special symbol like Rust does to force the statement to resolve
     to the top level module instead of the closest one.
- Less safe.  Current strategy means that in a file-as-submodule hierarchy, a module
   could get added at a closer scope than the one that was being imported, leading to
   compiler errors in the best case scenario and hijacking in the worst case
   - Potentially on the user - having relative naming doesn't prevent them from writing
      the full path and protecting themselves from this, it just allows them not to.

**Comment by bradcray** [comment]
[I'm finding this issue's text a little hard to understand in that it asks an open-ended question "what could be written?" and then lists pros and cons without being clear what's being evaluated. 
 For that reason, I may be misunderstanding it.]

I'm increasingly convinced (based on discussions with @BryantLam) that this decision is entangled with how we split modules across multiple files, so would suggest we discuss this part of the import design simultaneously with that question and assume for the time being that no `import` is required to refer to `B.x` or `B.foo` from within `A` today (since, as @mppf points out, no `use` is required to do this today, so we're really making a decision about both `use` and `import` when we wrestle with this).

Or we could decide the answer for `use` statements independently of `import` (i.e., resolve issue #13536) and then have `import` inherit that decision.  But I think we'd still want to do that with multi-file modules in mind.

**Comment by lydia-duncan** [comment]
> it asks an open-ended question "what could be written?" and then lists pros and cons without being clear what's being evaluated.

Yeah, the evaluation is really more aimed at whether relative naming should be allowed rather than the syntax itself, but that absolutely isn't as clear as it could be.

**Comment by mppf** [comment]
PR #15249 adds support for `import this.SubModule;` and `import super.SiblingModule;`
