### ISSUE TITLE
Enable deprecation warnings for more IO routines

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#14934]
On master (chpl version 1.21.0 pre-release (6becb020d6)), when calling `readf()` (which worked with Chapel 1.20), the following confusing error message is printed out:

```
testit.chpl:2: error: unresolved call 'readf("%i", int(64))'
$CHPL_HOME/modules/internal/LastResortIO.chpl:278: note: this candidate did not match: (IO.channel).readf(fmtStr: string)
testit.chpl:2: note: because call is not written as a method call
$CHPL_HOME/modules/internal/LastResortIO.chpl:278: note: but candidate function is a method
$CHPL_HOME/modules/internal/LastResortIO.chpl:271: note: candidates are: (IO.channel).readf(fmtStr: string, ref args ...?k)
```

To me, this seems less helpful / more confusing than just getting a simple unresolved call error message and then needing to figure out that I'm missing a `use`.  For that reason, I think we should either generate better error messages for cases like these, or else give up on the LastResortIO.chpl module (where my preference would be to generate better error messages when we can).

Checking the source of the LastResortIO.chpl module, it seems that the error overloads are there and simply commented out.  Uncommenting them out seems to cause the better error message.  Checking the routines that are commented out, I feel most nervous about `read()`, `readf()`, `readln()`, and `string.format()` being commented out because they seem reasonably likely to be used/useful.

Of those, it looks like only readf() might cause the bad behavior above given that it's the only one of the four that has an error overload defined on a channel.

**Comment by immadisairaj** [comment]
I am trying to uncomment [this](https://github.com/chapel-lang/chapel/blob/5c585bbea611842c7f13dc0ff9130977ab6e6b12/modules/internal/LastResortIO.chpl#L221) part of code in LastResortIO.chpl and try to compile a valid chapel and I get an error.

```
$CHPL_HOME/modules/standard/IO.chpl:5632: error: cannot resolve base type for method 'channel._match_regexp_if_needed'
```

As the above comment message of the particular code say that it is due to "ChapelIO needing the channel class and having the use of this module at the same scope as the use of IO." I am not sure of how ChapelIO is linked with LastResortIO. I think we might have to do something similar to "IO.file" as there is no issue with the method.

**Comment by bradcray** [comment]
Hi @immadisairaj — Thanks for taking a look at this.  I don't think there's any longer any expectation that the attempts to generate warnings for types will or should work.  So I wouldn't put any effort into trying to get that specific overload uncommented (and, I believe, the same for the overloads which try to generate warnings for enums).  @lydia-duncan is the expert here, though and may correct me if I'm wrong.

**Comment by lydia-duncan** [comment]
Brad's analysis is correct.

> I am not sure of how ChapelIO is linked with LastResortIO.

ChapelIO is the place where internal, essential IO operations that must be in every program go (e.g. `writeln`).  It has a `private use` of the IO module, which allows it to access the `channel` type in these essential functions.  The IO module used to be publicly used, but we decided to stop doing that and stop bringing in so many symbols by default.  To change that behavior with a nicer error message for the user, we created LastResortIO with a similar interface to the IO module, but with these overloads so that an error message can be provided.  LastResortIO is publicly used by ChapelIO to make it easy to find the two of them together and to prevent it from being a better match if the user actually uses IO themselves.  As a consequence, though, it is at the same scope as the use of IO, so we get this error.

**Comment by immadisairaj** [comment]
@lydia-duncan 
I have tried changing the method 'readf' in "LastResortIO.chpl" as
```
proc readf(fmtStr:string, ref args ...?k): bool throws {
  compilerWarning("readf will no longer be available by default,\nplease insert a use of the IO module to continue calling it.");
  return readf(fmtStr, (...args));
}
```
Then the warning is being printed and also the program is being compiled(takes some time to finish compiling after printing warning message).

If I keep the definition as `(IO.channel).readf` then the compiler does not detect the function call itself as in the error message `note: because call is not written as a method call`.
I would like to know if the program has to compile or not while printing a warning message.

**Comment by bradcray** [comment]
@immadisairaj: It's correct that the program should continue to compile and run.  The goal of the warning is to let people know that they _ought_ to update their code to include `use IO;` (which should make the warning go away), but not to force them to do so.  If we wanted to force it, we could change `compilerWarning()` to `compilerError()` which would terminate compilation.

**Comment by lydia-duncan** [comment]
I agree with Brad!  Sorry for the confusing use of error versus warning in my last response

**Comment by immadisairaj** [comment]
@bradcray @lydia-duncan What all methods are likely to give warnings? I suppose even for the `write`, `writef`, `writeln` there should be a warning. If that is the case then we have to remove these methods in "ChapelIO.chpl" file in order to produce warnings.

**Comment by lydia-duncan** [comment]
> If that is the case then we have to remove these methods in "ChapelIO.chpl" file in order to produce warnings.

Nah, the sorting of ChapelIO versus IO is correct at this point (or at least, I would need evidence it isn't).  Basically, anything in IO.chpl itself that can get a warning generated by LastResortIO should get a warning.

**Comment by lydia-duncan** [comment]
Oh, and while I have you on this - any PR enabling these warnings should include a new test of the deprecation warning in test/deprecated/io/.  Definitely feel free to open a PR with a small chunk early to get started and ensure you're on the right track before doing too much work that might need to be changed :)

**Comment by immadisairaj** [comment]
> Nah, the sorting of ChapelIO versus IO is correct at this point (or at least, I would need evidence it isn't). Basically, anything in IO.chpl itself that can get a warning generated by LastResortIO should get a warning.

When I run the code `write(5);` at the same point and added `compilerWarning` for that method, then the code does not print any warning message.
But if I comment out [this](https://github.com/chapel-lang/chapel/blob/568dca76fcb47342c4facdc22c3c8a1884d6f9e4/modules/internal/ChapelIO.chpl#L835) method, then the warning message prints out twice. I am trying to figure out what the problem is.

>  Definitely feel free to open a PR

Yeah sure, I will open a PR

**Comment by lydia-duncan** [comment]
> When I run the code write(5); at the same point and added compilerWarning for that method, then the code does not print any warning message.
But if I comment out this method, then the warning message prints out twice. I am trying to figure out what the problem is.

Right - nothing in ChapelIO.chpl should get a warning message.  It's still included by default, using IO isn't necessary.

This is a scoping concept - that definition of write is closer in scope than anything in LastResortIO, so will always be found first.  It's publicly included by ChapelStandard, which is used by every non-internal module (a use of that module is inserted by the compiler into even user defined modules).

**Comment by lydia-duncan** [comment]
I'm also reminded that the pragma "last resort" means that such functions are only considered if no other option is present
