### ISSUE TITLE
Retire `.domain` in favor of `.indices`?

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#15103]
With the introduction of a `.indices` query that can be applied to various collection types including arrays, should we retire the `.domain` query on an array in favor of `.indices`?

Arguments in favor:
* `.indices` is a bit more of a natural / common English term
* it would remove a special case in the parser in which a keyword is accepted as a method name (yet one that a user couldn't define themselves... see issue #10939).
* it would remove a redundant way of doing something

**Comment by ben-albrecht** [comment]
All of the motivations behind this resonate with me, but I am currently undecided. It seems like a heavy breaking change for a small benefit. I also find `.domain` returning the array domain to be elegant and intuitive.

**Comment by gbtitus** [comment]
I voted against. I like that the name of the method that gives me an array's domain is `domain`.  I don't mind the redundancy that's come along with the addition of `indices`.  And I don't mind the special case in the parser because parsers often have special cases, although admittedly that's easy for me to say because I don't work on the parser!

**Comment by e-kayrakli** [comment]
I am currently against this but waiting a bit more before I vote, because the arguments listed above make good sense to reject hastily.

I am against, because arrays have domains which are somewhat a bigger concept than having just indices. And as Ben mentioned, we'd lose some elegance if we are not able to query the domain of an array using `.domain`.

A slightly less important concern is that whether that would lead a beginner to think `a.indices` for `var a: [1..10] int` would return a range rather than a domain because the definition of `a` uses a range for the indices of the array.

**Comment by ronawho** [comment]
I originally voted in favor of this, but just removed my vote, since what Greg and Engin said resonated with me. Not sure where I stand now.

**Comment by bradcray** [comment]
It's hard for me to decide whether I think the reluctance to remove `.domain` is because we're just not used to `.indices` yet, or whether it's because it's a bad idea.

One of the ways I'm thinking about this is to think about what kind of style we want to promote (given that, now, we literally have to make the decision about which of the two forms to highlight in our examples, codes, and docs).

I keep coming back to the question: Given a new Chapel user, which of `A.indices` or `A.domain` would they understand most intuitively?

Using a keyword as a method bothers me not just because of the parser special-case, but also because (a) it tends to throw off syntax highlighters, and (b) on principle.  Can anyone come up with other languages that use keywords as method/variable/field names?

If we end up being afraid to make this decision now, but wanted to reserve the right to make it later, we could also consider (potentially) having `--warn-unstable` give a warning for `.domain` suggesting users move to `.indices` to be safe.

**Comment by ben-albrecht** [comment]
> If we end up being afraid to make this decision now, but wanted to reserve the right to make it later, we could also consider (potentially) having --warn-unstable give a warning for .domain suggesting users move to .indices to be safe.

This seems like a reasonable decision. We have had `indices` on master for less than a week. I think I could make a much more informed decision after getting used to using `indices` in my own code and observing which style I naturally gravitate towards.

**Comment by gbtitus** [comment]
> Using a keyword as a method bothers me not just because of the parser special-case, but also because (a) it tends to throw off syntax highlighters, and (b) on principle. Can anyone come up with other languages that use keywords as method/variable/field names?

I can't do that, but for (a) I can point out a case of the opposite.  In C a type-specifier (the syntactic element that names the type in a declaration) can be not only a keyword such as `int` or keyword phrase such as `struct <tag>`, but also a user identifier that has been previously defined as a typedef name.  This poses a problem for parsers which have to figure out whether they're looking at a declaration or anything else that can start with an identifier (typically solved by having the scanner consult the symbol table to differentiate between typedef-names and all other identifiers).  It also poses a problem for syntax highlighters, which cannot get the highlighting right for this case without developing at least enough semantic knowledge about the program to know which identifiers are typedef-names at the scope being highlighted.

**Comment by bradcray** [comment]
For all those still following this issue (plus @mppf who voted but may not be following it):  There was a sufficiently large difference of opinion on the question that I didn't end up pursuing it for this release.  But I'm wondering whether we should put a `--warn-unstable` warning in for uses of `.domain` in user code in case we decide to pursue it in the future.

Tradeoffs:
* doesn't affect most users, who probably never use --warn-unstable
* could give people who see the warning incentive to advocate for one position or another
* if we don't retire .domain, we warn people against using it needlessly
* if we don't warn against it, we have less ground to stand on if we do decide to retire it later

The PR is here for your consideration: #15323

**Comment by bradcray** [comment]
@ben-albrecht: Are you saying "yes, let's merge this" or "yes, these tradeoffs are tricky to decide between"?

**Comment by ben-albrecht** [comment]
>  But I'm wondering whether we should put a --warn-unstable warning in for uses of .domain in user code in case we decide to pursue it in the future.

My 👍 was aimed at this making it unstable to reserve the right to remove it.

**Comment by ronawho** [comment]
Having forgotten how this was defined, I found myself not wanting to use `.indices` on distributed arrays because it wasn't intuitive to me if `.indices` includes the distribution or just the raw index set. i.e for:

```chpl
use BlockDist;
var A = newBlockArr({1..10}, int);
var B: [A.domain] int;  // obviously a distributed array 
var C: [A.indices] int; // not so obvious to me if this is a distributed array or local
```

But I'm still not sure if that's just because I'm used to domain and if that wasn't there as a second option maybe I wouldn't have that confusion.

I do remember having a hard time wrapping my head around domains when I was first learning Chapel, so having a concept that's more natural / common definitely resonates. However, nowadays I think of a domain as an index set with a distribution, so just calling it `indices` feels like it's missing something.

**Comment by e-kayrakli** [comment]
@ronawho's example above is a good demonstrations of my hesitations [above](https://github.com/chapel-lang/chapel/issues/15103#issuecomment-596643469)

Catching up on some of the discussion here, I am still finding myself against this. 

@bradcray's

> I keep coming back to the question: Given a new Chapel user, which of A.indices or A.domain would they understand most intuitively?

doesn't sound like the most important question we should answer for this discussion to me. Although I agree that the term `indices` can be easier to grasp for a beginner, I don't think the term `domain` remains a confusing term for a long time while learning Chapel. It is by nature a more complicated concept than "indices" suggest, and IMHO `domain` being less intuitive can force the learner to spend more mental energy understanding how arrays are laid out in a distributed memory and such.

One important point that I want to expand here is sparse domains. Although similar to distributed domains, the above example of @ronawho's can also be confusing in a different way for sparse domains. `var C: [A.indices] int;` looks too much like C is a COO array regardless of whether A is CSR/CSC or whatever, to me. I think that's because I see the CSR-ness information carried in `domain` and not in `indices`.

> Using a keyword as a method bothers me not just because of the parser special-case, but also because (a) it tends to throw off syntax highlighters, and (b) on principle. 

I see the points here, too. But mentally I have been using the term `domain` as a more opaque thing when I am writing Chapel code. I don't interpret `A.domain` as a method call but more like a magical query that gives me the domain of the array A. Of course you may not like magic :)

I view the syntax highlighter issue the same. As this is a magical operation to me, it never bothered me that `domain` is highlighted in `A.domain`. That being said, it should be an easy fix for the vim highlighter (and hopefully for any other serious highlighter) that I don't mind doing if we want to stop highlighting `A.domain` but want to retain the highlighting in `var A: domain(1)`

**Comment by vasslitvinov** [comment]
Other cases where we use a keyword as a method:
```chpl
someArr.domain
someVar.locale
someExpr.type
```

**Comment by bradcray** [comment]
Based on the feedback, what if we said:

* `Arr.domain`: literally returns a `const ref` to the array's domain, as it does today
* `Arr.indices`: returns the indices of the array in some form, either well-defined based on the array's type, or potentially up to the domain map how it's represented (TBD).

For example, for a dense rectangular Block-distributed domain, `Arr.indices` could return a default domain representing the index set rather than the distributed domain, as `Arr.domain` does.

This approach would have the benefit of:

* supporting `Arr.indices` consistently across collection types
* removing the sense that users need to be able to define their own `.domain` methods as requested in https://github.com/chapel-lang/chapel/issues/10939 for their own collection types (because they should be defining `indices` methods instead)
* avoiding the current redundancy by having the two behaviors differ from one another

**Comment by e-kayrakli** [comment]
As someone opposed to retiring `arr.domain`, I am OK with the proposal above. Though, I have some questions.

- Do we have a real use case for needing `arr.indices`? I don't think it is awkward or anything, but just checking to see whether this proposal came about from a use-case that we have seen recently.
- Should we also add `dom.indices`? I think the way for `.indices` to work should be that domains also have `.indices`. And that `dom.indices` should return *something* that can be used to create domains of other types. For example, for rectangular domains, it can return `whole`, which is a DR, I think. For irregular domains, it can be an iterator, and then we can beef up our story that can enable a relatively efficient way of doing things like

```chapel
var spsDom: sparse subdomain(parentDom) = assocDom.indices;  // and vice versa
```

I also find the following code to be easy to read and understand:

```chapel
var newDom = myBlockDom.indices dmapped Cyclic();
```

- With that scheme, `arr.indices` can be added for consistency with other types and as a convenience for `arr.domain.indices`.

**Comment by bradcray** [comment]
> Do we have a real use case for needing arr.indices? I don't think it is awkward or anything, but just checking to see whether this proposal came about from a use-case that we have seen recently.

The motivation for supporting `.indices` on all collection types came from the change between 1- and 0-based programming, in which it was noted that if all of our collection types had supported `.indices` from the start—and our codes had used it rather than hard-coding idioms like `1..collection.size` or `0..<collection.size`, then the switchover would've been much less painful.  The idea behind supporting `array.indices` is to support `.indices` on all collection types rather than requiring the user to learn that lists, tuples, strings support `.indices` but arrays must use `.domain`.  In terms of an `interface`, you could imagine that for a collection to be `indexable`, it might support `.indices` and `.this()` that takes a single value of the type generated by `.indices`.

> Should we also add dom.indices? 

I don't have a strong opinion about that at present.  If I were to argue against it, I'd say that it's not symmetric with the other cases above in which `.indices` gives the set of indices that can be used to index into the type, but we don't really index into domains.  It also seems somewhat tautological to me ("What is a domain?" "An index set."  "What's the value of this domain?"  "These indices."  "What are the indices of this domain?"  "The same thing.").

Put another way, I could imagine writing either of your idioms in the previous comment without the `.indices` and having them work fine.  The first [seems to](https://tio.run/##S85ILEjN@f8/OT@vuETBRcFWodpQT8@s1poLKpKfkgIW1FEw1lEwRYgXFxRbKRQXJBYVpyoUlyal5OcmZuZpuGgCFYP0WHOVF2WWpOYAhYAqNa3//wcA).  The [second does too](https://tio.run/##S85ILEjN@f@/tDhVwSknPznbJbO4REfBuTI5JzMZxLbm4krOzysuUXBxUrBVyEsth6jKz9WoNtTTM6vVtIbJOwPlgYpSchMLClJToEZoFJckFpV4plTYGgJVlhdllqTm5Gm4OGta//8PAA) (although this is only a single-locale run, so something subtle could be going wrong).

That said, I'm not inherently opposed to supporting `dom.indices`.  But I don't think it follows obviously/naturally from this issue or the 0- vs. 1-based indexing discussion.

The desire to ask a block-distributed dense domain what the DR value of its entire index set resonates with me a bit.

**Comment by e-kayrakli** [comment]
>  It also seems somewhat tautological to me ("What is a domain?" "An index set." "What's the value of this domain?" "These indices." "What are the indices of this domain?" "The same thing.").

I'd argue that the answers here are not right or too simplified. To me Q:"What is a domain?" A:"An index set's layout over system memory", Q:"What's the value of this domain?" A:"Some sort of representation of indices, and their mapping to the system memory", Q:"What are the indices of this domain?", A:"Here's something that represents indices in this domain". Where `dom.indices` would fill in the gap that we have for the third question today.

> The idea behind supporting array.indices is to support .indices on all collection types rather than requiring the user to learn that lists, tuples, strings support .indices but arrays must use .domain.

This is not news to me, however, it reminded me of one of my earlier worries with retiring `arr.domain`. If we were to add `arr.indices`, are we introducing a new performance pitfall that is just too easy to fall into?:


```chapel
// let me define a block array
var blockArr = newBlockArr(...);

// let me set each index
forall i in blockArr.indices do  // ... why is this not scaling??
  blockArr[i] = compute(i);
```

> In terms of an interface, you could imagine that for a collection to be indexable, it might support .indices and .this() that takes a single value of the type generated by .indices.

I think this is a good argument.

**Comment by bradcray** [comment]
> I'd argue that the answers here are not right or too simplified. 

I definitely agree that they're too simplified, yet also not completely inaccurate.

> are we introducing a new performance pitfall that is just too easy to fall into?

We definitely would be introducing a new performance pitfall, but I think providing a collection-independent way of querying the indices of that collection is crucial enough to warrant it.  An alternative would be to have `.indices` return the distribution-preserving domain as it does today; but then we either have two ways of getting the same thing (which we tend to avoid), or we'd need to retire `.domain` (which proved to be unpopular in this issue).

I suppose we could support `.domain` on other collections, but given that the concerns people had above revolved around "the domain is a special thing in Chapel and querying it should preserve the special properties", I think this would be weird (e.g., a list doesn't literally have a domain, so pretending that it does feels like it would confuse rather than clarify the issue).

Another option would be to have `.domain` and `.localizeIndices()` on arrays to avoid any possibility of confusion, but then we lose the ability to have a collection-neutral way to query indices.

We've discussed having a `--performance-pitfalls` flag that would help identify issues like this, and I could imagine using it to help users sort out simple errors themselves.

**Comment by bradcray** [comment]
@e-kayrakli : What do you think about spawning this latest proposal ("What if `.indices` returned something different than `.domain` for arrays?") into its own issue with the goal of kicking off a fresh discussion and closing this one as "won't fix"?

**Comment by e-kayrakli** [comment]
@bradcray -- Sounds good to me.

**Comment by bradcray** [comment]
OK cool, I've forked my current proposal off to issue #17883.  I think we could probably close this issue at this point due to lack of champions (@mppf and I were in the minority), but will keep it open a bit longer in hopes of finding that #17883 has sufficient traction that we can close this one.

**Comment by redhatturtle** [comment]
I was reading this topic again while considering #17883 and realized I never actually posted my thought here. So to keep the discussion in #17883 about the new proposal I'll register my objections to this idea here. 

I have the same objections that other people in the discussion brought up. I like the intuitiveness and clarity of the `.domain` query especially since the concept of a domain is quite fundamental for Chapel and usually a novelty for newcomers.

As others noted I would be hesitant to assume that `.indices` returns as domain's distribution rather than just the global index space of the 
array. So while for new user the term indices might seem more intuitively understandable it does this by 'hiding' the larger concept of a domain.

**Comment by bradcray** [comment]
I'm closing this issue, considering it to not have garnered support, especially relative to #17883.

**Comment by bradcray** [comment]
Yet apparently, I failed to close it... trying again.
