### ISSUE TITLE
virtual dispatch and default param arguments

### ISSUE THREAD

**Issue by benharsh** [chapel-lang/chapel#15164]
Continuing from #13962 , where we decided that the default value and virtual method should match. There are two related cases that do not work on master today.

Consider the following program:
```chpl
class Parent {
  proc method(arg:int = f()) {
    writeln("in Parent.method arg=", arg);
  }
}

class Child : Parent {
  override proc method(arg:int = g()) {
    writeln("in Child.method arg=", arg);
  }
}

proc main() {
  var x:Parent = new Child();
  x.method();
  //   run child's default (virtually dispatched) `g()` and so print out `in Child.method arg=1`

  var y = new Child();
  y.method(); // expect this to run `g` and so print `in Child.method arg=1`
}
```

Case 1:
If the functions invoked as default values return a param:
```chpl
proc f() param { return 0; }
proc g() param { return 1; }
```
Then the compiler incorrectly folds the calls away and the wrong default value is used for the ``x.method()`` call.

Case 2:
If the formals have the ``param`` intent, then ``x.method()`` has the wrong default value.

**Associated Future Test(s):**
[`test/functions/default-arguments/default-argument-class-override3a.chpl`](
           https://github.com/chapel-lang/chapel/blob/master/test/functions/default-arguments/default-argument-class-override3a.chpl
          ) #17653

**Comment by cassella** [comment]
In case this aspect's been lost since #7880, case 1 applies not just when the default values of arg are param functions, but also when they're params, or even plain old int literals.  When I change the definitions here to `Parent.method(arg: int = 0)` and `Child.method(arg: int = 1)`, I get the same results as Case 1, as written above,

```
in Child.method arg=0
in Child.method arg=1
```

(See also #14167)

**Comment by mppf** [comment]
@benharsh - did you make a PR making these give an error for now? I can't remember where it ended up.

**Comment by benharsh** [comment]
I did not end up making a PR for errors. I ran into a problem where the compiler would issue duplicate errors for the first case, and was unable to find a way to detect the second case before having to move on to other tasks.

**Comment by bradcray** [comment]
PR #17653 resolves the first of @bharsh's first two issues here, but not the second.  Or at least, it doesn't cause the second to behave as I'd intuitively expect.  Specifically, given:

```chapel
proc f() param { return 0; }
proc g() param { return 1; }

class Parent {
  proc method(param arg:int = f()) {
    writeln("in Parent.method arg=", arg);
  }
}

class Child : Parent {
  override proc method(param arg:int = g()) {
    writeln("in Child.method arg=", arg);
  }
}

proc main() {
  var x:Parent = new Child();
  x.method();
  //   run child's default (virtually dispatched) `g()` and so print out `in Ch\
ild.method arg=1`                                                               

  var y = new Child();
  y.method(); // expect this to run `g` and so print `in Child.method arg=1`    
}
```

It prints:

```
in Child.method arg=0
in Child.method arg=1
```

But is that perhaps reasonable (or at least not unreasonable?).  Since it's a dynamic dispatch scenario, the compiler effectively says "I need to call one of these two overridden methods, but I'm not sure which one.  But they have a param argument, so I have to evaluate the `param` argument at compile-time.  So, not knowing better, I guess I'll call the one on the static type."  Is that reasonable?

I think in the old world of handling default arguments, we would've created 0-argument overloads of each method and this would have worked "as expected" because each 0-argument overload would be strongly coupled to its default argument, and then we'd dynamically dispatch between them.  But when we moved away from that approach (the reasons for which I can't recall anymore—related to moving evaluation of default args to the callsite?), maybe we lost that ability.

@mppf, what are your thoughts here?

**Comment by mppf** [comment]
@bradcray - that is interesting. In my mind we have default arguments being evaluated at the call-site for two reasons:
 * the function specialization approach can make quite a few "wrapper" functions (an exponential number, potentially); while the call-site-call-code-to-compute-default-argument doesn't have this problem. That said, even though there might be an exponential number of wrapper functions, the number is still limited by the number of calls, at least until we start creating lots of calls with generic code...
  * handling the defaults at the call site is important because a lot of the copy/move semantics for in/out/inout need to be handled at the call site in order to a) be efficient and b) interact well with other in/out/inout arguments.
  
 Anyway my suggestion for this case is to do these two steps:
  1. For the near term, make the compiler identify this case and issue an error.
  2. For the long term, we can go back to specializing `method` in this case based upon the `param` default argument and doing the virtual dispatch on the specialized version. Meaning the compiler would construct a zero-arg version with the default param value baked in. In a sense, it already does that when instantiating generics; we are just talking about handling  some of this in a different order. This is different from always specializing because we would only be specializing the `param` and potentially `type` formal arguments.
