### ISSUE TITLE
Unable to build Chapel Compiler using make command using Cygwin in Windows

### ISSUE THREAD

**Issue by ruchir-123** [chapel-lang/chapel#15289]
This is what it says:

$ make
Making the compiler...
make/Makefile.compiler.head:36: /home/HP/chapel-1.20.0/make/Makefile.base: No such file or directory
mingw32-make[2]: *** No rule to make target '/home/HP/chapel-1.20.0/make/Makefile.base'.  Stop.
Makefile:75: recipe for target 'compiler' failed
mingw32-make[1]: *** [compiler] Error 2
Makefile:60: recipe for target 'comprt' failed
mingw32-make: *** [comprt] Error 2

**Comment by Rapiz1** [comment]
It's weird to encounter such an error. Can you check that `/home/HP/chapel-1.20.0/make/Makefile.base` does exist?

**Comment by ruchir-123** [comment]
Yes, it exists

**Comment by bradcray** [comment]
Hi @ruchir-123: Thanks for filing this.  Like @Rapiz1, I'm not sure what to suggest if that file exists since the error is complaining that it does not.  Does your cygwin installation work for you otherwise?

Also, if you are using Windows 10+ and have the Windows bash shell, that would almost certainly be a simpler way of using Chapel that will also perform much better.

**Comment by bradcray** [comment]
I'm not sure what more we can do here without more information, as this doesn't appear to be a Chapel issue.  Closing for now, but the user can re-open if the problem persists and more information can be provided.
