### ISSUE TITLE
Addition of isEmpty() to LockFreeStack

### ISSUE THREAD

**Issue by souris-dev** [chapel-lang/chapel#15333]
### Summary of Problem
I think it would be great to have a method to check if the stack is empty or not without having to call the `pop()` function on it in case of a LockFreeStack. 

Currently, the `pop()` function returns a tuple of the form `(a: bool, b: type)` where `a` is `false` if no more elements are left.
But there is no function like `isEmpty(): bool` to check if the stack is empty or not without calling `pop()`.

Hence, I would like to propose another function `isEmpty(): bool` that returns `true` if the stack has no more elements.

Usage of the same would allow doing something like: 
``` chapel
use LockFreeStack;
var stack = new LockFreeStack(int);
for i in 1..4 {
    stack.push(i);
}

while (!stack.isEmpty()) {
    stack.push(6);
    // do something else, or do some more pushes
    stack.pop();
}
```

This could allow more consistent, more flexible and a simpler design of the user's program in many cases as the C++ STL has a similar function defined for a stack: `empty()` which returns `true` if it is empty.

**Comment by Rapiz1** [comment]
As far as I am concerned, the design goal of a lock-free stack is to support concurrent operations. `while (!stack.isEmpty()) stack.pop();` is simple but could be wrong when there are multiple threads. 
When you check `!stack.isEmpty()`, yes, it's not empty. But when you try to pop from the stack, the stack could have been poped by other threads and now it's empty and you get nothing. So I don't see the point of having such procedures since we can only know it's not empty at a certain moment but not sure about the next moment.

**Comment by souris-dev** [comment]
Yes, you are right about that, I realized that later when I looked into it. I further realized that a simple `list` can also be used as a stack for non-concurrent purposes by just using its `append` and `pop` operations.

**Comment by souris-dev** [comment]
Yes, you are right about that, I realized that later when I looked into it. I further realized that a simple `list` can also be used as a stack for non-concurrent purposes by just using its `append` and `pop` operations.
