### ISSUE TITLE
Should isBoundedRange() produce an error for non-range types?

### ISSUE THREAD

**Issue by Aniket21mathur** [chapel-lang/chapel#15399]
### Summary of Problem
isBoundedRange functions accept a domain as an argument without throwing an error and return false for a bounded domain

### Steps to Reproduce

**Source Code:**

```chapel
var r : range(stridable=true) = 0..10 by 2;
var D: domain(1, stridable = true) = {r};
writeln(isBoundedRange(r));
```
returns true, which is expected.

```chapel
var r : range(stridable=true) = 0..10 by 2;
var D: domain(1, stridable = true) = {r};
writeln(isBoundedRange(D));
```
should either throw an `IllegalArgumentError` or return `true`, but returns `false`

### Configuration Information

`chpl version 1.22.0.67f2aea2ed`

```
CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: gnu
CHPL_TARGET_ARCH: x86_64
CHPL_TARGET_CPU: native
CHPL_LOCALE_MODEL: flat
CHPL_COMM: none
CHPL_TASKS: qthreads
CHPL_LAUNCHER: none
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: cstdlib
CHPL_GMP: gmp
CHPL_HWLOC: hwloc
CHPL_REGEXP: re2
CHPL_LLVM: none
CHPL_AUX_FILESYS: none
```

**Comment by ben-albrecht** [comment]
This behavior is due to the following overload in `ChapelRange.chpl`:

```chpl
  pragma "no doc"
  proc isBoundedRange(r)           param
    return false;
```

This exists, because it follows the pattern of other `isType(x)` functions, where it returns `false` if `x` is not the type being queried (`range(boundedType=bounded)` in this case).

If you want a case that generates an error if not used on a range, you can check the `boundedType` directly:

```
// This would be a compiler error if `r` is not a range
writeln(r.boundedType == BoundedRangeType.bounded);
```

I am not sure if it makes more sense for `isBoundedRange` to be an exception to the `isType()` pattern as suggested in this issue or for it to remain how it is.

**Comment by Aniket21mathur** [comment]
> I am not sure if it makes more sense for `isBoundedRange` to be an exception to the `isType()` pattern as suggested in this issue or for it to remain how it is.

@ben-albrecht as per my opinion returning `false` might be misleading for a regular user(who might not give a second thought). Having an error thrown might be a good option.

 

> Would be interested in hearing what others think.

Yes, agreed. Let's wait for others to give their opinion on it. Thanks!

**Comment by ben-albrecht** [comment]
Another idea is to create a method equivalent to `range.hasLowBound()` and `range.hasHighBound()`, such as `range.isBounded()`. This would only be allowed on range types.

**Comment by ben-albrecht** [comment]
> If we have to deviate from the isType() pattern than I think an IllegalArgumentError might be better, though I surely need second opinion on this.

I think a compiler error would be more appropriate, if we were to consider this an error.

**Comment by Aniket21mathur** [comment]
> Another idea is to create a method equivalent to `range.hasLowBound()` and `range.hasHighBound()`, such as `range.isBounded()`

Yes, agreed. That would be a good alternative.

> Since the type is known at compile-time, I think a compiler error would be more appropriate if we were to consider this an error.

Yeah, this would save the user a run-time.

**Comment by bradcray** [comment]
I think BenA's original response captures the current philosophy of all of the is*() type queries:  That they are designed to answer a very general question like "is this thing this type?" where the answer is intended to be "false" ("no") if it is not.  For example, I can write `writeln(isOwnedClass(42));` and get `false` rather than having to do `if isClass(x) && isOwnedClass(x)` in order to be sure the thing is safely a class before determining whether it's an owned class.  This is helpful in generic programming situations where you have no idea what you're going to get and it shouldn't necessarily be a compiler error to ask a question:

```chapel
proc foo(x) {
  writeln(isOwnedClass(x));
  writeln(isBoundedRange(x));
}
```

I wouldn't be opposed to queries that are more specific / require a range, but I'm not sure these are the right queries to make work that way (or, if they are, we arguably have a lot of cases that need changing, potentially breaking existing code).

**Comment by Aniket21mathur** [comment]
> or, if they are, we arguably have a lot of cases that need changing, potentially breaking existing code)

@bradcray, I agree with you. I was going through the modules and there seem to be a lot of changes if we go this way.

**Comment by bradcray** [comment]
@Aniket21mathur: Is it OK if we close this issue then?  (we could still add a feature request for a method on ranges that answers questions like `isBounded()`, but I'd be inclined to fork that into its own issue.

**Comment by Aniket21mathur** [comment]
> Is it OK if we close this issue then? (we could still add a feature request for a method on ranges that answers questions like `isBounded()`, but I'd be inclined to fork that into its own issue.

It can be closed in that case :-)

Should I file a new issue requesting `range.isBounded()` , in place of the isBoundedRange() procedure?

**Comment by ben-albrecht** [comment]
> Should I file a new issue requesting range.isBounded() , in place of the isBoundedRange() procedure?

I think that is reasonable to open.

**Comment by bradcray** [comment]
My answer would be: If it's a feature you definitely want, definitely file it.  If not, I'd wait until someone does.

**Comment by Aniket21mathur** [comment]
@ben-albrecht @bradcray I have filed an issue https://github.com/chapel-lang/chapel/issues/15528, please have a look :-)
