### ISSUE TITLE
Adding explanantion of task intents to Task Parallelism primer

### ISSUE THREAD

**Issue by rahulghangas** [chapel-lang/chapel#15400]
As a new user with any language, my first instinct is to learn it from the docs. Using task parallelism can be particularly hard/limiting if the user is unaware about task intents. This issue is reminder that a subsection on task intents with a suitable example should be added to the docs [here](https://chapel-lang.org/docs/master/primers/taskParallel.html). Related to #12615

**Comment by tushargoyl123** [comment]
hi I am Tushar and I want to work on this issue ,Can u guide me through...

**Comment by bradcray** [comment]
@tushargoyl123 — This probably isn't a good first issue if you're not already familiar with Chapel because it requires understanding the language well enough to document it for others' use.  If I'm mistaken and you are already familiar with Chapel, the task is to edit the primer example located at https://github.com/chapel-lang/chapel/blob/master/test/release/examples/primers/taskParallel.chpl to describe task intents to someone new to the language.

**Comment by tushargoyl123** [comment]
> @tushargoyl123 — This probably isn't a good first issue if you're not already familiar with Chapel because it requires understanding the language well enough to document it for others' use. If I'm mistaken and you are already familiar with Chapel, the task is to edit the primer example located at https://github.com/chapel-lang/chapel/blob/master/test/release/examples/primers/taskParallel.chpl to describe task intents to someone new to the language.

Ok i will try my best

**Comment by DanilaFe** [comment]
I believe this issue can be closed, since we have a "Task Intents" section here: https://chapel-lang.org/docs/master/primers/taskParallel.html#task-intents
