### ISSUE TITLE
Add support for `use M as _ ...;`

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#15457]
This issue proposes an extension to the renaming of a module in a `use` statement (PR #14714) to include the ability to indicate that a user should not be able to refer to the module name itself (at least, as a result of this specific `use` statement... another may make it visible).

Here, I'm proposing `_` be used for this purpose since it is not a legal identifier, and feels a bit similar to its role in detupling contexts to mean "drop this on the floor".  But I'm open to other proposals as well.

As examples, `use M as _;` would permit M's public contents to be referred to, but not `M` itself.  Similarly `use M as _ only x;` would permit `x` to be referred to in an unqualified manner, but would not permit `M.x` to be written (as a result of this `use` statement), since it does not make `M` visible.

**Comment by lydia-duncan** [comment]
Another way to phrase it:
- `use M as _;` would be equivalent to `import M.*;` if we were to permit the latter (which we aren't planning on doing currently).  For modules that don't change, it would be equivalent to `import M.{every, single, symbol, in, the, module};`
  - Note: it is more valuable to do this on `use` statements, which are by definition less principled and for which this would be providing a more limited symbol access than was previously available, than `import` statements (which are more principled and for which this would introduce a mode that is more dangerous.  It extends the scope with more symbols than would otherwise be possible, and in a manner that allows symbols added later to be brought in, potentially hijacking user code).
- `use M as _ only x;` would be equivalent to `import M.x;`

**Comment by lydia-duncan** [comment]
Edge cases that are occurring to me just now:
- Should we be able to set multiple modules to be used for unqualified access only, e.g. `use M as _, N as _;` or
```chapel
use M as _;
use N as _;
```
? (My instinct is yes)
- We shouldn't be able to use `_` in other situations, right?  E.g. `use M only a as _;` (that would give us nothing but qualified access to M if we allowed it, but seems excessively verbose) or `import M as _;` (which would give us nothing whatsoever) or for forwarding?

**Comment by bradcray** [comment]
> Should we be able to set multiple modules to be used for unqualified access only

I think so / don't see any reason not to.

> We shouldn't be able to use _ in other situations, right?

I think that's right; or at least that we should wait for someone to make the case that we should support it in these other cases before worrying about it.
