### ISSUE TITLE
Behaviour difference between logarithm functions in Math module

### ISSUE THREAD

**Issue by Aniket21mathur** [chapel-lang/chapel#15556]
### Summary of Problem

The `log2` function returns an `int` output(floor) given an `int` input, but the `log` function returns a `real` for `int` input. It would be great if the functions are modified to show similar behaviour.
 
### Configuration Information

```
chpl version 1.23.0 pre-release (60cd4f4c0e)

CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: gnu
CHPL_TARGET_ARCH: x86_64
CHPL_TARGET_CPU: native
CHPL_LOCALE_MODEL: flat
CHPL_COMM: none
CHPL_TASKS: qthreads
CHPL_LAUNCHER: none
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: cstdlib
CHPL_GMP: gmp
CHPL_HWLOC: hwloc
CHPL_REGEXP: re2
CHPL_LLVM: llvm
CHPL_AUX_FILESYS: none
```

**Comment by bradcray** [comment]
In case it's unclear to anyone reading why this is (I'm pretty sure it's not to @Aniket21mathur :) ):  

Mechanically speaking, it's because `log()` only supports `real` arguments, so an `int` actual coerces to the `real` version, causing a `real` to be returned.  However, the `log2()` routine has both `real` and `int` overloads, each of which returns the similar type.

Historically speaking, I believe we got here because:

(a) the `Math.chpl` module started out modeling heavily what `math.h` supports in C, and (from what I can tell), C only supports `log()` on floating point values;
(b) at some point, we found ourselves writing hand-coded `log2()` functions for integers in lots of cases when computing problem sizes or the like in benchmarks, and so added a function for it, but did not add integer versions of the other log() functions.

If I were forced to decide how to break the inconsistency, I'd probably add int->int overloads of the other log functions (because I think it follows the trend of our math functions preserving types in most cases).

**Comment by ronawho** [comment]
Related to https://github.com/chapel-lang/chapel/issues/10292

**Comment by ben-albrecht** [comment]
I would consider this a duplicate of #10292. Should we close this issue and continue discussion over there?

**Comment by Aniket21mathur** [comment]
> In case it's unclear to anyone reading why this is (I'm pretty sure it's not to @Aniket21mathur :) ):

@bradcray thanks for explaining :-)

> I would consider this a duplicate of #10292. Should we close this issue and continue discussion over there?

Yes, it will be better to keep the discussion at a single place.
