### ISSUE TITLE
Compile fails in forall with +=; succeeds with .add()

### ISSUE THREAD

**Issue by octonion** [chapel-lang/chapel#15593]
### Summary of Problem
Adding elements to a domain works using .add(), but fails to compile using the (equivalent?) += operator.

### Steps to Reproduce

```chapel
var d: domain(int);

forall i in 1..2 {

  d += i; //fails to compile; d.add(i); works as expected.
}
```

**Compile command:**
`chpl bug.chpl`

**Execution command:**
`./bug`

### Configuration Information

- Output of `chpl --version`:
- Output of `$CHPL_HOME/util/printchplenv --anonymize`:

chpl version 1.22.0

- Back-end compiler and version, e.g. `gcc --version` or `clang --version`:

gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)

**Comment by Rapiz1** [comment]
```
a.chpl:5: error: illegal lvalue in assignment
a.chpl:3: note: The shadow variable 'd' is constant due to forall intents in this loop
```
The compilation error shows the reason. 

And this works for me.
```
var d: domain(int);

forall i in 1..2 with(ref d) {

  d += i; //fails to compile; d.add(i); works as expected.
}
```

I can recall some discussion in the IRC channel about adding documentation on this topic. It's in the language specs but not in primer.
@rahulghangas opened an issue about this https://github.com/chapel-lang/chapel/issues/15400 But no work has been done so far.

However, here are some pages in language specs you will find helpful.
* [Forall Intents](https://chapel-lang.org/docs/master/language/spec/data-parallelism.html)
* [Task Intents](https://chapel-lang.org/docs/master/language/spec/task-parallelism-and-synchronization.html#task-intents)

**Comment by bradcray** [comment]
Thanks for filing this, @octonion.  It's not immediately clear to me why one form would work and the other not, though I suspect it has to do with the argument intents for a LHS of `+=` vs. the `this` argument of the `.add()` method and is worth a deeper look.

**Comment by vasslitvinov** [comment]
As @Rapiz1 says, `d` in the OP example should not be modifiable in the forall loop body, unless a `ref` forall intent is used.

The fact that `d.add(i)` works is due to a missing constness check in our Chapel implementation. It should report an error just like the '+=' case. The first step to fix is this patch:
```diff
--- a/modules/internal/ChapelArray.chpl
+++ b/modules/internal/ChapelArray.chpl
@@ -1646,7 +1646,7 @@ module ChapelArray {
 
        The domain must be irregular.
      */
-    proc add(in i) {
+    proc ref add(in i) {
       return _value.dsiAdd(i);
     }
 
```

However somehow it is not enough.

Note that this issue is independent of `forall`. For example, even with the above patch:
```chpl
const d: domain(int);
d.add(5);  // is allowed even though it shouldn't be
d += 5;    // correctly reports an error
```

**Comment by vasslitvinov** [comment]
P.S. Similar `ref` intent should be added -- and enforced -- on other _domain operations such as `clear` and `remove`.

**Comment by bradcray** [comment]
Hi @octonion : Thanks again for reporting this.  Fixing it led to other related clean-ups in our const-checking as well.  The behavior of the program you submitted is now:

```
testit.chpl:5: error: cannot assign to const variable
testit.chpl:3: note: The shadow variable 'd' is constant due to forall intents in this loop
```

where the fix is to override the default `const` intent when `d` crosses into a parallel region using a `with` clause on the loop:

```chapel
var d: domain(int);

forall i in 1..2 with (ref d) {

  d += i; //fails to compile; d.add(i); works as expected.
}
```

I think that, arguably, using `const` intents for such shadow variables is a poor choice on our part for associative domains which are `parSafe=true` by default—that is, ones which support having multiple tasks add to the index set in parallel.  However, this would be non-trivial for us to add at present.  I've opened up #17221 to capture the idea going forward.
