### ISSUE TITLE
untyped array formal arguments with in intent and defaults

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#15628]
Relates to PR #9471 and my current work on PR #15239.

Consider the following example (taken from test/arrays/intents/in/default-value-linkage.chpl ):

``` chapel
proc defaultsValue(in D = {1..4}, in A = builder(D)) {
  ...
}

var DD = {1..4};
var AA : [DD] int;
defaultsValue(DD, AA);
```

The question here is whether at runtime the array A inside of defaultsValue has domain D or DD.

 PR #9471 adjusted this case to perform default initialization of a formal temp for the argument `in A` and then assign the actual argument `AA` to it. The main purpose of PR #9471 was to get cases like `proc foo(in D : domain(1), in A : [D] int)` working correctly. It did so by default initializing the array argument and then assigning into it.

However my recent work in PR #15239 allows a more efficient implementation for cases like `proc foo(in D : domain(1), in A : [D] int)`. In these cases, the actual argument is converted an array with the appropriate runtime type (using an operation different from default-init/assign).

Now, back to the example shown above `proc defaultsValue(in D = {1..4}, in A = builder(D))` with a call like `defaultsValue(DD, AA)`. Here I think we could, as a matter of language design, choose one of the following two behaviors.

1. The formal argument array A is default-initialized and then assigned into. The result is that `A.domain == D`.
2. The formal argument array A is copy-initialized from AA. The result is that `A.domain == DD`.

I think both of these behaviors are surprising.

1. is surprising because a pattern that looks like it would not generate array temporaries, such as `defaultsValue(DD, createArray())` would create a temporary. What if these arrays are really large? Generally speaking the language design tries to avoid the creation of array temporaries. Another way to put this is that it is surprising that if an actual argument is provided for `A` that the default expression is still evaluated.

2. is surprising because an untyped `in` argument gets its type from the default expression. Generalizing that to runtime types, the `A` argument should get its runtime type from the default expression.

Are there other possibilities here?

**Comment by mppf** [comment]
@bradcray @benharsh - I'd like to know your current thoughts about this, thanks.

**Comment by bradcray** [comment]
Are the curly brackets in the formal `{DD}` intentional / a part of the question's focus, or just extraneous?  (I think we allow this pattern today and just ignore the curly brackets (?), but should not permit it; or else should interpret it as an associative domain of domains).

**Comment by mppf** [comment]
@bradcray - extraneous, and fixed

**Comment by bradcray** [comment]
My quick response without a lot of deep thought (including only skimming your OP so far and not thinking too deeply about recent 1.21-related changes) tends to be:

* `A`'s domain seems like it should be `D` by virtue of the inferred formal type `[D] int` from builder().  Though I could also imagine an interpretation that builder() only constrains `A` to be `[] int` and permits it to have a different domain instead.

* I would expect `AA` to be default initialized since it _seems_ to be read (via passing it to the `in` intent) before it is written.

* I would expect `A` to be copy-initialized from `AA` rather than default initialized plus assigned.

* `D`'s `in` intent makes me feel that extra array copies may be reasonable (or at least, aren't unreasonable).  If changing `D` to `ref` intent didn't help eliminate such copies then I might be more worried (though having `A` have `in` intent still intuitively suggests "make a new variable" to me).

Reading your OP a second time a bit more closely, I'm understanding that the issue is that in your work, array copy initialization necessarily takes the domain of the RHS array as its own (?) and that my answers somewhat straddle the two cases you enumerate as a result.  Is there the potential for the array copy initializer to not inherit the RHS's domain if it already has one that is well-defined?  e.g., `var A: [1..n] int = ...;  var B: [0..n-1] int = A;` might be another case where perhaps B would want to copy initialize A but keep its own domain rather than taking A's?

**Comment by bradcray** [comment]
Regarding [my hidden comment above](https://github.com/chapel-lang/chapel/issues/15628#issuecomment-623564397), I've opened PR #15629.

**Comment by mppf** [comment]
> * `A`'s domain seems like it should be `D` by virtue of the inferred formal type `[D] int` from builder().  Though I could also imagine an interpretation that builder() only constrains `A` to be `[] int` and permits it to have a different domain instead.

> * I would expect `A` to be copy-initialized from `AA` rather than default initialized plus assigned.

As far as I know these two are in conflict.

> * I would expect `AA` to be default initialized since it _seems_ to be read (via passing it to the `in` intent) before it is written.

Yep, it would be, and that's not the main point here.

> * `D`'s `in` intent makes me feel that extra array copies may be reasonable (or at least, aren't unreasonable).  If changing `D` to `ref` intent didn't help eliminate such copies then I might be more worried (though having `A` have `in` intent still intuitively suggests "make a new variable" to me).

At the moment, I'm not concerned with eliminating all copies from this case; but as it was written we could copy elide a copy from AA. I don't see why D's intent has anything to do with it.

> Reading your OP a second time a bit more closely, I'm understanding that the issue is that in your work, array copy initialization necessarily takes the domain of the RHS array as its own (?) and that my answers somewhat straddle the two cases you enumerate as a result.

My work allows for things like `foo(in D : domain(1), in A : [D] int)` and for the `in A` argument in that event to not always cause default-init/assign or even copy initialization. There is a code path for "move initialization" that also adjusts the runtime type.

> Is there the potential for the array copy initializer to not inherit the RHS's domain if it already has one that is well-defined?  e.g., `var A: [1..n] int = ...;  var B: [0..n-1] int = A;` might be another case where perhaps B would want to copy initialize A but keep its own domain rather than taking A's?

Yep I already do this on my branch.

Let's look at the example one more time:

``` chapel
proc defaultsValue(in D = {1..4}, in A = builder(D)) {
  ...
}

var DD = {1..4};
var AA : [DD] int;


defaultsValue(DD, AA);
```

On master, the compiler converts this final call into:

```
var D_tmp = ...; // RHS not important right now
var A_tmp = builder(D_tmp);
A_tmp = AA; // this is assignment
defaultsValue(D_tmp, A_tmp);
```

This is the default-init/assign pattern that I have been talking about. I probably contributed to confusion by calling "var A_tmp = builder(D_tmp)" "default initialization" when that's not quite accurate.

Now, suppose that we want to move away from default-init/assign and have a better way to write "make sure the runtime type is D":

```
var D_tmp = ...;
var A_tmp = createArrayWithDomain(D_tmp, AA);
defaultsValue(D_tmp, A_tmp);
```

Changing the code to this would work OK in this example, but it relies on some magic. How does the compiler know that `A`'s domain should be `D` ? All we have is `in A = builder(D)`. Can the compiler figure out that `A`'s domain is `D` without evaluating `builder(D)` ? I have been supposing the answer to that is "no". Evaluating `builder(D)` create the array temporary we might not want.

I suppose, technically speaking, the following lowered code would meet your suggestions:

```
var D_tmp = ...;
var A_default = builder(D_tmp);
var A_tmp = createArrayWithDomain(A_default.domain, AA);
defaultsValue(D_tmp, A_tmp); 
```

But... if we have to create A_default anyway I'm not sure there is much we gain by using copy-initialization to create A_tmp instead of assignment. Perhaps copy elision could apply in some cases. But generally speaking, it uses more memory than the default-init/assign case, anyway. So this strategy isn't particularly appealing to me.

**Comment by bradcray** [comment]
On email, Michael wrote this:

> `in A = builder(D)` has to run `builder(D)` if we want it to
compute the runtime type of `A`, doesn't it? Wouldn't
that be suprising if an actual argument was provided for `A` ?

which helped clarify this paragraph for me (as well as the original question, probably):

> Changing the code to this would work OK in this example, but it relies on some magic. How does the compiler know that A's domain should be D ? All we have is in A = builder(D). Can the compiler figure out that A's domain is D without evaluating builder(D) ? I have been supposing the answer to that is "no". Evaluating builder(D) create the array temporary we might not want.

I agree that we wouldn't want to run `builder(D)` at execution time if an actual argument was provided (beyond the array temp, imagine that it does something expensive like going and reading the array from a file needlessly).  So returning to my original response, I think this part of it was more on-point:

> Though I could also imagine an interpretation that builder() only constrains `A` to be `[] int` and permits it to have a different domain instead.

So my revised response would be that, I'm imagining that the compiler should constrain `A` to match the static type of `builder()` (so, for example, "it's a 1D array of int") without trying to constrain or reason about `A.domain`'s value/identity.  This would suggest behavior 2 is the correct one to me.  You argue this is surprising because:

> is surprising because an untyped in argument gets its type from the default expression. Generalizing that to runtime types, the A argument should get its runtime type from the default expression.

Which suggests to me that we shouldn't expect initialization-based formal type inference to generalize in that way (i.e., it shouldn't be expected to take runtime types into account).  What sorts of downsides would that lead to?

Here's a class-oriented example that seems similar to me and appears to have worked as I'd expect in 1.20 (focused on static, rather than dynamic, types):
[TIO](https://tio.run/##XY7NDoIwEITvPMXEEyTGixoNxJPwIFgWbdK0pC2CMT47bsEf9LQ7@@3OrLiUDalhEEbX8gwuzqN1lOMAb1vKokio0jkccY@Aa2khGK3XWfR4ozyd0YrpZjujxZwS091@pI01AqdWqopsnKQwnabqtSrr6Qd/Ic0SsORbq6GpQx4nGc9IOfpHRUBv69qYWGr0nPhJSUb3zkpPSsf9EosUiyX6lb81lDpvpT5PFuGau1CC85Fvvyr/UUVQw/AE)

```chapel
config const useD = true;

class C {
  var c = 33;
}

class D: C {
  var d = 45;
}

class E: C {
  var e = 78;
}

proc builder(): owned C {
  if useD then
    return new D();
  else
    return new E();
}

proc foo(in x = builder()) {
  writeln(x, ": ", x.type:string);
}

foo();
foo(new C());
foo(new D());
foo(new E());
```

(it would be even better if I didn't have to declare the return type of `builder()` and the compiler inferred it to be `owned C` as the common super-class of the two `return` cases... something I think we ought to support, but don't seem to today).

**Comment by mppf** [comment]
> Which suggests to me that we shouldn't expect initialization-based formal type inference to generalize in that way (i.e., it shouldn't be expected to take runtime types into account). What sorts of downsides would that lead to?

Well, arguably there are 2 different things that happen on array initialization with inferred type, e.g. ``` var B = A; ``` where `A` is an array, or for an untyped `in` formal.
1. the compiler infers (some) type information
2. the compiler adds copy initialization (subject to copy elision) that produces a result with the domain of the RHS

I think we could simply say that 1. is limited to compile-time type information and that the domain being the same as A.domain comes from the copy/move initialization.

Anyway for these patterns I *think* that it's reasonable to expect users to write a type expression if they want to insist on the domain being a particular thing when the default value is not used.

The main other case I can think of besides the example in the main issue text is with fields. For example:

``` chapel
record R {
  var D = {1..100};
  var A = makeArrayWithDomain(D);
}

var x = new R(A=[1,2,3]);
// Will user now be surprised that x.D != x.A.domain?
// Arguably the code does not say it must be so. 
```

**Comment by bradcray** [comment]
> Anyway for these patterns I think that it's reasonable to expect users to write a type expression if they want to insist on the domain being a particular thing when the default value is not used.

I agree with that, and I think where I went off the tracks on my original response was that I was thinking like a human and inferring what the explicit type would be for the initializer, rather than like a compiler.

I think you're right that the untyped field case could be (more?) surprising, but a record author who wanted to prevent surprises could either supply the formal type (as in the argument-passing scenario) or create an initializer that somehow "made things right / less surprising."

**Comment by mppf** [comment]
Sounds like we are leaning towards

> 2. The formal argument array A is copy-initialized from AA. The result is that A.domain == DD.

@benharsh - does this sound OK to you?

**Comment by benharsh** [comment]
That sounds good to me 👍

**Comment by mppf** [comment]
@benharsh pointed out in separate communication another way of thinking about the formal argument with a default:

> another way to think about it might be `var A = if argSupplied then arg else builder(D)`
