### ISSUE TITLE
[Design] Interface of IntervalTree

### ISSUE THREAD

**Issue by Rapiz1** [chapel-lang/chapel#15671]
Ref: [Augmented Tree](https://en.wikipedia.org/wiki/Interval_tree#Augmented_tree)
IntervalTree
* `insert(x:(int,int))`: insert an interval. Does nothing if already present.
* `remove(x:(int,int))`: remove an interval. Does nothing if not present.
* `intersect_all(x:(int,int)): list((int,int))` returns a list of tuples. Each tuple represents a interval intersected.
* `intersect(x:(int,int)): (int,int)` same as `intersect_all`, but just returns one arbitary interval.

I don't think we should support `real` or other types. If users use `real`, there would be a problem of precision when comparing and intersecting. This will lead to a very tricky situation.

**Comment by cassella** [comment]
I'd add a `these()` and a `this()` (and a `size()` to find the bounds of `this()`).

I think overloads of the `intersect()` functions that take a single `int` to look up would be convenient, instead of requiring the user to use e.g., `(5,5)` to look for intervals containing `5`.

I don't think `real` is that problematic; or at least the `IntervalTree` can be written so as to make it the user's responsibility to take the needed care.

I'd say it should probably be generic over the intervals' endpoint-type, allowing different sizes of `int`, `uint`, (`real`), and even `bigint` from the `BigInteger` module.  Other types may also define `<` et. al.
