### ISSUE TITLE
how to initialize a sync variable as empty?

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#15756]
In PR #15755 I came across this pattern:

``` chapel
var s: sync bool;

proc foo() { ... uses s ...; }
foo();
s = true;
```

This is now an error (s is initialized in the split-init declaration at the bottom). However to fix it, I wanted to be able to write `var s: sync bool = <something>;` but that doesn't seem possible right now. Because any value I put there would make it full, e.g. `var s: sync bool = false`. The strategy I usually use to disable split-init of just writing `s;` after the declaration doesn't work in this case either, because that is a read that waits for the variable to be empty and leaves the variable empty.

When this is resolved, update these tests to remove workarounds:
 * test/functions/deitz/nested/test_nested_with_begin.chpl
 * test/parallel/begin/waynew/simple2.chpl
 * test/parallel/taskPool/figueroa/TooManyThreads.chpl

**Comment by bradcray** [comment]
This is a pretty significant semantic change that hadn't occurred to me before.  In case the change isn't clear to others:  historically, an uninitialized `sync` would be considered empty and an initialized `sync` would be considered full.

**Comment by mppf** [comment]
> This is a pretty significant semantic change that hadn't occurred to me before. In case the change isn't clear to others: historically, an uninitialized sync would be considered empty and an initialized sync would be considered full.

Right, but the idea with split-init is that any use of a split-inited variable between declaration and initialization is a compilation error. So at least somebody expecting `s` in the above code to be default initialized would see a compilation error (rather than confusing execution).

In particular, I don't see any problem with split-init applying to sync variables in a case like
``` chapel
var x: sync int;
x = 23;
... use x ...
```

Recall that in  #15113 / #15012 we were trying to give the same behavior for inner functions and module-scope variables and module-scope functions. And that it was a goal to make uses of a variable before they are initialized into compilation errors.

But, on master, the behavior is inconsistent, or at least perhaps not what we want.

These two simple cases do split-init `x`:
``` chapel
proc main() {
  var x: sync int;
  x = 23;
}
```

``` chapel
var x: sync int;
x = 99;
```

But with a function using `x`, it depends on how it is written.

This case split-inits x and raises a compilation error as I would expect:

``` chapel
proc main() {
  var x: sync int;
  inner();
  x = 23;
  proc inner() {
    writeln(x.readXX());
  }
}
```

As does this module-scope equivalent:

``` chapel
var x: sync int;
function();
x = 29;

proc function() {
  writeln(x.readXX());
}
```

However the following two cases do not split-init x at normalization time. (I think the split init code during normalize is delving into the body of `inner`). (The reason I came across this is that PR #15755 makes the split-init handling during resolution time slightly more general and it doesn't share this oddity).

Here is the nested function version, which does not split init x on master:

``` chapel
proc main() {
  var x: sync int;
  proc inner() {
    writeln(x.readXX());
  }
  inner();
  x = 23;
}
```

Here is the module-scope function version, which does not split init x on master:
``` chapel
var x: sync int;
proc function() {
  writeln(x.readXX());
}
function();
x = 23;
```

So, another way to ask the question about this split-init behavior - is "When the compiler is looking at mentions of `x` to decide if it can be split-inited, should it delve into functions between the declaration and the candidate assignment?"

If the answer is "yes", then the resolution-time split-init code needs to have some adjustment to consider these "uses".
If the answer is "no", then the normalize-time split-init code needs to stop delving into functions.

**Comment by bradcray** [comment]
Other than resulting in a breaking change to the language, I don't necessarily see a problem with extending split init to sync vars either; but I also don't see a big benefit to it given that sync vars are restricted to built-in scalar types (so the overhead of default initializing then assigning doesn't seem likely to be terribly expensive).  I suppose the main downside is that it causes a type to be different than the others.  But for me it also raises the question of whether a type author ought to be able to flag their type as not being a candidate for split initialization for any reason (where this might be a poster child).

If we were OK with breaking the language over this, maybe rather than using workarounds to force default initialization, we should adopt a language-level way to force default initialization like:

```chapel
    var s: t = init;  // default initialize s
```

in which case, for sync vars, this could potentially be the hook to reverting to the traditional "default value + empty" behavior.

I feel confused by this:

> Right, but the idea with split-init is that any use of a split-inited variable between declaration and initialization is a compilation error. 

I thought that the idea was that any use resulted in the variable being default initialized (isn't this why your typical strategy of writing `s;` after the declaration as a way to force default initialization works?).  I'm guessing you must be only talking about certain types of uses here?

> But, on master, the behavior is inconsistent, or at least perhaps not what we want.

I feel like I've lost the thread between this observation and the OP.  Is the inconsistent behavior specific to sync vars in some way, or are the behaviors you note true for vanilla ints in addition to sync ints?

**Comment by vasslitvinov** [comment]
The following is based on my understanding of the current situation that sync vars are currently subject to split init and that it may inconvenient when they need to be initialized to empty.

If so, disabling split init for sync/single vars makes sense to me. It helps that syncs can be declared only over POD types and that we may want to allow user types to opt out of split init as well.

The alternative `var x: sync int = init;` would be OK, too. The downside is that this is a bit obscure, the users are less likely to discover this feature. By contrast, the absence of split init would be hopefully easily observable.

**Comment by mppf** [comment]
> Other than resulting in a breaking change to the language, I don't necessarily see a problem with extending split init to sync vars either.

This is the part that confuses me and probably why we seem to be talking past each other in this issue.

I compile this program with the 1.22 release:

``` chapel
var x: sync int;
function();
x = 29;

proc function() {
  writeln(x.readXX());
}
```

and it results in this error:
```
split.chpl:2: error: module-scope variable 'x' may be used before it is initialized
split.chpl:1: note: 'x' declared here
split.chpl:3: note: 'x' initialized here
split.chpl:2: note: calls function 'function'
split.chpl:6: note: mentions module-scope variable 'x' not initialized yet
```

This error is a user-observable way of seeing that in 1.22 we *do* apply split init to sync variables. In fact, as far as I know, it was by design that it works that way. We wanted the initialization vs assignment behavior to be type-independent. The [language specification section on split-init](https://chapel-lang.org/docs/master/language/spec/variables.html#split-initialization) says nothing about types at all.

What am I saying? I'm saying that in 1.22 split init already applies to sync variables, and it would be a breaking change to make split init no longer apply to sync variables.

> maybe rather than using workarounds to force default initialization, we should adopt a language-level way to force default initialization like:
> 
> ```chapel
>     var s: t = init;  // default initialize s
> ```
> 
> in which case, for sync vars, this could potentially be the hook to reverting to the traditional "default value + empty" behavior.

Yes this is appealing to me but something that I always imagined would be written as `var s: t = default;`. Such a functionality would also be useful in the context of initializer arguments for typeless fields (see "Instantiated Type with Two Typeless Fields" in #12318 - although I'm saying more that it could be extended to handle that case more than that it would fall out)

> 
> I feel confused by this:
> 
> > Right, but the idea with split-init is that any use of a split-inited variable between declaration and initialization is a compilation error. 
> 
> I thought that the idea was that any use resulted in the variable being default initialized (isn't this why your typical strategy of writing `s;` after the declaration as a way to force default initialization works?).  I'm guessing you must be only talking about certain types of uses here?

Yes, you are correct. I was talking about uses of the variable in inner functions, which is what the original code in this example was doing.

``` chapel
var s: sync bool;

proc foo() { ... uses s ...; }
foo();
s = true;
```

> > But, on master, the behavior is inconsistent, or at least perhaps not what we want.
> 
> I feel like I've lost the thread between this observation and the OP.  Is the inconsistent behavior specific to sync vars in some way, or are the behaviors you note true for vanilla ints in addition to sync ints?

Here is the sequence of events:
 * I was working on PR #15755 to fix problems with split init of tuples
 * My changes caused compilation failures for two tests using a pattern like the `foo` code above and the compilation errors seemed correct to me
 * In adjusting these programs to compile, I didn't see a satisfying way to modify them
 * In figuring out why my changes in the PR caused the tests to fail, I figured out that the two parts of the compiler handling split init are treating function bodies (i.e. the body of `foo`) differently, leading to inconsistent behavior.

> are the behaviors you note true for vanilla ints in addition to sync ints?

The behaviors are true for ints or records or anything at all. I probably should have created a different issue when I discovered the inconsistency.

**Comment by bradcray** [comment]
Thanks for clarifying.

> in 1.22 split init already applies to sync variables

Something about the OP made me think that it was only now (post-1.22) that we were talking about changing how sync variables work.  It still strikes me as odd that this change in behavior for sync variables didn't come up until now (that I recall anyway), but thinking about it more, I suppose that it arguably doesn't matter for many cases because if a user was relying on the "default to empty" behavior before, they couldn't do much to avoid deadlocking their program other than write to the variable first which, for many code patterns, ends up acting the same as the split init.  But in cases where that initial write is more convoluted (like in this issue's example, I suppose?) it still feels like a language change that I didn't feel aware of going into 1.22.  For example, the spec still says "If a synchronization variable declaration has an initialization expression, then the variable is initially full, otherwise it is initially empty", but that doesn't seem like it's accurate anymore (though I'm having trouble quickly constructing an example that shows it's inaccurate).

So back on the question this issue poses, I think my answer would be to adopt some sort of `= init;` or `= default;` syntax to get this behavior, and it seems like an attractive feature in general (beyond this issue).  I'd rather use it than the workarounds we've been using to force default (non-split) initialization, for example.  The reason I suggested `= init` is that it feels symmetric to both `= noinit;` (not implemented yet, granted) and to the use of `init` as a special identifier for creating initializers.  I agree that the meaning is a bit more subtle / less intuitive than `= default`, but still think I prefer it for the original reasons.

As far as resolving the inconsistent behavior for functions, I don't have an immediate intuition as to which approach we should pursue.  I assume that the delving into functions that we've been doing wasn't accidental, so maybe we should keep doing that?  OTOH, I suppose either approach is technically a breaking change, so we could re-evaluate the design.  I'd be inclined to fork that discussion off to its own issue in any case (it seems like it deserves one and I don't think it's too late to be worthwhile).

**Comment by mppf** [comment]
> As far as resolving the inconsistent behavior for functions... I'd be inclined to fork that discussion off to its own issue in any case

Thanks for the suggestion; I've created #15764 (and more or less pasted information in to it).

**Comment by mppf** [comment]
>  It still strikes me as odd that this change in behavior for sync variables didn't come up until now (that I recall anyway)

Yep, it's the first time I recall noticing it.

> But in cases where that initial write is more convoluted (like in this issue's example, I suppose?) it still feels like a language change that I didn't feel aware of going into 1.22. For example, the spec still says "If a synchronization variable declaration has an initialization expression, then the variable is initially full, otherwise it is initially empty", but that doesn't seem like it's accurate anymore (though I'm having trouble quickly constructing an example that shows it's inaccurate).

It's not necessarily inaccurate - one could take the view that the initialization expression under split-init just appears in a different statement. Anyway I don't know of a case where this matters other than the compilation-error-or-not for the case at the top of the issue.

**Comment by mppf** [comment]
This comment summarizes some strategies with pros and cons:

### = init
`var s: sync bool = init`

Here the compiler would interpret `= init` as explicitly requesting default initialization.

Pros:
 * feels symmetric to `= noinit`
 * `init` is already a special identifier
 * generalizes nicely

### = default
`var s: sync bool = default`

Here the compiler would interpret `= default` as explicitly requesting default initialization.

Pros:
 * naming is relatively obvious
 * generalizes nicely

### = empty
`var s: sync bool = empty`

The sync/single types would support a global symbol that can be used to initialize a variable to be empty. Here `empty` would have its own type, e.g. `emptySyncVariableType`, and sync/single would include an `init=` that accepts a `rhs: emptySyncVariableType` which would perform the equivalent of default initialization (i.e. initialize the variable as empty).

Pros:
 * no compiler changes required
 * `empty` is relatively intuitive in this context

Cons:
 * doesn't help with generalizing this idea to other types

**Comment by bradcray** [comment]
> It's not necessarily inaccurate - one could take the view that the initialization expression under split-init just appears in a different statement.

To me, the inaccuracy seems to be that it's suggesting that such initializer-less expressions result in an initialized yet empty variable; but it seems as though it's actually uninitialized in cases like:

```chapel
var s$: sync int;
s$ = 42;
```

(i.e., I don't think s$ is ever actually empty in this program).  It seems to me that a more accurate description would be something like "a default initialized synchronization variable will be empty." and then it's up to other aspects of the language (like split initialization) to say when default initialization occurs).

For the three proposals you give above, I'd be inclined not to do something that's sync-specific since it seems useful in other cases (and could even be useful for user types).  So unless others following this disagree with that, maybe the next step should be to fork off a new more general issue about that feature (issue #12318 seemed to hope that a separate issue would be created for it, but I didn't see a link to it if it was).  I'm thinking of the motivations as being (a) a more direct way to disable split init without having to invoke an explicit initializer / use an initialization expression, (b) your typeless fields example, (c) this "default to empty" situation (which is arguably just (a) in a special form).

**Comment by mppf** [comment]
> It seems to me that a more accurate description would be something like "a default initialized synchronization variable will be empty." and then it's up to other aspects of the language (like split initialization) to say when default initialization occurs).

PR #15768 gives this a try.

**Comment by mppf** [comment]
> For the three proposals you give above, I'd be inclined not to do something that's sync-specific since it seems useful in other cases (and could even be useful for user types). So unless others following this disagree with that, maybe the next step should be to fork off a new more general issue about that feature (issue #12318 seemed to hope that a separate issue would be created for it, but I didn't see a link to it if it was). I'm thinking of the motivations as being (a) a more direct way to disable split init without having to invoke an explicit initializer / use an initialization expression, (b) your typeless fields example, (c) this "default to empty" situation (which is arguably just (a) in a special form).

Thanks for the suggestions. I've created #15769 to discuss a way to opt-in to default initialization.
