### ISSUE TITLE
make install: PERFORMANCE.md missing [chapel_1.22.1]

### ISSUE THREAD

**Issue by darked89** [chapel-lang/chapel#15854]
After compiling chapel_1.22.1 on Manjaro Linux 20.0.3 with gcc 10.1.0 (no errors)

**error**
```
make install 
Error: source file '/home/foobar/chapel_1.22.1/PERFORMANCE.md' missing
```

**fix/hack**
```
touch PERFORMANCE.md
make install 
```

DK

**Comment by bradcray** [comment]
@darked89: Thanks for reporting this.  It appears that we messed something up in the bundling of the 1.22.1 release and are currently looking into it.

**Comment by bradcray** [comment]
@darked89: We've fixed the release and updated it accordingly (this was the only file that was missing/wrong, fortunately).

Thanks again for reporting this, as it not only will save other 1.22.1 users hassle, but it also pointed out an issue with our release process for update releases (which we don't use very often) and testing.

**Comment by darked89** [comment]
That was a rather miniscule fix ;).
I am really impressed by your prompt response. 

Best,

DK

**Comment by bradcray** [comment]
Few things are better motivators than sheer embarrassment!  :D

(To pull back the veil a bit, the source of the issue was that our release process was using a script from the master branch to build the release from the release branch when it should've been using the copy of the script on the release branch.  On master, PERFORMANCE.md has been removed, so the script doesn't bundle it anymore, and this change was therefore applied to the release branch.  For most releases, the master and release branches are essentially in sync, so this hasn't bitten us in the past, but for an update release like this... oops.  It also pointed out that we don't have good testing for `make install` which was the only thing sensitive to the file being missing and the reason that our testing of the release didn't catch it.  https://github.com/Cray/chapel-private/issues/1071 linked above captures the need to introduce some `make install` testing).

Thanks again for reporting this.  I'm glad we caught it the day that 1.22.1 came out.
