### ISSUE TITLE
Add license field to Mason packages

### ISSUE THREAD

**Issue by ankingcodes** [chapel-lang/chapel#15886]
Currently, we don't have license field compulsory for Mason packages. This issue aims to add the field to the packages.

**Comment by ankingcodes** [comment]
@ben-albrecht could you list out some necessary changes required for getting this feature.

**Comment by ben-albrecht** [comment]
@ankingcodes - here are some thoughts on requirements, with some open questions to be resolved:

- [ ] Add support for a `license` field to the manifest TOML (e.g. update docs)
- [ ] Generate a license field for `mason new` and `mason init`, but leave the field as an empty string (unless a user overrides this in interactive session)
- [ ] Validate the `license` field
  - Q1. How should we validate license fields?
    - I think we want match the license identifier against the [SPDX](https://spdx.org/licenses/) list
    - If we're doing validation upon `mason update`, we'd want to cache SPDX licenses somewhere
    - If we are only doing validation upon `mason publish --ci-check`, it might be more acceptable to fetch the remote  
  - Q2. When should we validate license fields?
    - During a `mason update` and/or `mason publish --ci-check`?
      - I am leaning towards only `mason publish --ci-check` since this is where it wouldn't matter much before the package is published.
- [ ] Emit an error if a package does not include a license field in the CI testing when trying to publish the package
  - Q3. Should we start with a warning and ease into requiring licenses since it's a new feature?

**Comment by ankingcodes** [comment]
> Generate a license field for mason new and mason init, but leave the field as an empty string (unless a user overrides this in interactive session)

@ben-albrecht  Could we give an MIT license as default ? And let interactive override it if required ? I'm also okay with keeping it empty. 

> Q2. When should we validate license fields?

I think we should do that at `mason publish --ci-check`. I understand the caching the SPDX license, but I'm not sure about which remote you're indicating to fetch.

> Should we start with a warning and ease into requiring licenses since it's a new feature?

If a license field is supposed to be compulsory, we can start with it being an error rather than a warning.

**Comment by ben-albrecht** [comment]
> Could we give an MIT license as default ? And let interactive override it if required ? I'm also okay with keeping it empty.

I'm not sure. I don't want to push developers towards a certain license. We could see what other package managers do here. As an example, GitHub defaults to license of None when initializing a repository.

> I think we should do that at mason publish --ci-check. I understand the caching the SPDX license, but I'm not sure about which remote you're indicating to fetch.

OK. What I mean is when we do the `mason publish --ci-check`, it's OK to pull the SPDX license list if it hasn't been pulled before, rather than pulling it ahead of time, e.g. as part of the mason-registry.
