### ISSUE TITLE
Update 'make install' infrastructure to include third-party/whereami

### ISSUE THREAD

**Issue by daviditen** [chapel-lang/chapel#15884]
We're adding a new library in `third-party/whereami`. `make install` needs to be updated to include it.

**Comment by gbtitus** [comment]
I had asked for this issue to be filed because I thought the new `whereami` third-party package would be needed when building user executables and thus we'd need it in what `make install` builds.  But that's not so -- we only need `whereami` when compiling the launcher library, because it's compiled in, not linked in.  So, I'm closing this issue.

**Comment by bradcray** [comment]
Oh, I didn't get that distinction either.  So the `whereami` binaries are essentially compiled into the (launcher part of the) runtime libraries?

**Comment by gbtitus** [comment]
Yes, there's no such thing as "`whereami` binaries".  Basically you just `#include <whereami.c>` into your code.
