### ISSUE TITLE
Version module potential breaking design questions for Chapel 1.23.0

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#15911]
PR #13191 adds a new `Version` module to the Chapel standard modules to help users reason about the compiler version used to compile their program.  This issue brings up a few design questions that were posed during the module's review as food for thought.  If changes are desired, they should probably be made before 1.23.0 is released, as breaking the version module between releases reduces its value (we can also make other non-breaking changes or additions to the version module, but those can go in their own issues).

* **module name:** the current module is named `Version`... is that OK?  Other ideas that were discussed were:
  - `ChapelVersion`/`ChplVersion` (but the goal of the module is to support more general computations on versions, so that seems too Chapel-centric)
  - `Versioning`
  - `VersionSupport`

* **version() routine name:** The `version()` helper function name was chosen for simplicity and brevity to support writing expressions like `if chplVersion > version(2,0)` rather than `if chplVersion > new semanticVersion(2,0)` or `if chplVersion > semanticVersion.create(2,0)`.  But a downside of doing so is that it throws up some challenges to having a variable named `version` to indicate a module's version number without using qualified naming / renaming, because it's likely you'd want to write something like `const version = version(1,0,0);`

* **version(..., minor=0, ...) default:** Currently, the version() routine doesn't support a default argument for `minor` but does for `update` on the argument that updates don't matter as much for semantics/features, so are less likely to be queried / more likely to be unimportant.  @ronawho points out that for gcc he sometimes wants to just make queries like "is at least gcc 3".  I was a little concerned that `if chplVersion == version(3)` might be mis-interpreted as "is it `3.x.y`?" rather than "is it 3.0.0?" whereas I think `if chplVersion == version(3,0)` makes that a little more explicit (that said, ultimately, I think we're going to want other comparison methods that reason about compatibility rather than precise numbers).

* **types:** the module supports distinct `semanticVersion` vs. `sourceVersion` types in order to distinguish between different styles of version numbering and to avoid imposing commit semantics on every version number... Any significant objections to those concepts or names?

* **varying types:** currently, `chplVersion` varies between semanticVersion and sourceVersion depending on whether it's an official release or not.  Similarly, `version()`'s return type varies between the two depending on whether or not a `commit` argument is provided.  Are either of those decisions too weird?  (my thought was that most use cases would either be none the wiser or would focus on the released versions).

**Comment by bradcray** [comment]
Updated the OP today to reflect a question about whether `version()` is a good routine name given that it's likely to be a common choice for a module's version number constant.

**Comment by mppf** [comment]
> module name: the current module is named Version... is that OK? Other ideas that were discussed were:

What about `Versions` ? I also like `Versioning`.  I think some name that conveys it is primarily a module that supports version numbers, rather than a module storing the current version number, would be useful. (I think it happens to contain the version of the compiler, but I also think it's better if we think of that as a bonus, rather than the purpose of the module, in terms of naming. This is already reflected by calling the Chapel version `chplVersion` rather than say `version`.)

> version() routine name:
> version() name: 

Aren't these topics the same?

Anyway it seems like there is a tension between naming the generator function `version`, the type `version`, or having the expected use case store the value into a variable named `version.

One (horrible?) strategy to handle this would be to make `version` be the expected name for a value storing the version (let's say the type is `semanticVersion`) and then to make `proc semanticVersion.this(param major: int, param minor: int, param update: int = 0, param commit: string = "")` which creates another version. That way you could still write `version(1,2,0)` and it would work with whichever `version` variable happened to be in scope...

Anyway, I would personally rather have `version` be the expected name of version variables than the name of a function generating versions, if we have to choose. I don't think that `new semanticVersion(a, b, c)` is so bad, but it would make code comparing versions look less nice. (Maybe such code could frequently compare with reals though? (Or tuples - but tuples are probably not param enough...).

> varying types

No strong objection to what is there, but I'd probably have just made one type, with say commit="" having special meaning. AFAIK the various routines could still have the same behaviors. I don't really understand why having two types is actually useful in this case. That said, since the versions have param fields, the exact concrete type returned by `version` will not be fixed, either. Nonetheless having one generic type seems to me to make it easier to write something like `proc myPrintVersion(v: semanticVersion)` and not needing to make it totally untyped or have 2 versions of it.

**Comment by bradcray** [comment]
> Aren't these topics the same?

Yes, thanks.  In looking for it when editing today, I expected it to be next door to the other version() item, but forgot that I'd sorted by importance and didn't consider it as important the first time around.  I combined them into one bullet now.

**Comment by vasslitvinov** [comment]
#### Naming

I like `Version`, as it is short and sweet. Michael's suggestion of plural `Versions` is also good; it allows us to name the type `Version`, and parallels the plural in the module `LinkedLists`.

I think it is a very good convention to allow a library module have a constant `version`. Towards that, we could name the routine `ver()` -- or `Version.create()`. To summarize:

| purpose       | name     |
| ------------- | -------- |
| module name   | Versions |
| type name     | Version  |
| function name | ver()    |

#### Library.version issue

A couple of us (myself excluded) oppose having a function return a type that is not visible to the function's user. Here, we are considering a convention that library modules provide a constant -- or, equivalently, a function -- of a type defined in the Version module.

Does this mean that any library providing the `version` constant needs to have `public use Versions` to ensure that version's type is visible to the user?

If we are willing to accept `Lib.version` without requiring `use Version`, we can opt for these naming choices:

| purpose       | name     |
| ------------- | -------- |
| module name   | Version  |
| type name     | version  |
| function name | ver()    |


#### Routine name -> version comparisons

The following proposal relieves us from having to give a concise name to the `version()` function. However, let us consider it independently of the function name.

I propose to allow version comparisons against tuples, strings, and integers:
```chpl
Lib.version > (1,2)
Lib.version > "1.2.3"  // error if the string is malformed
Lib.version >= 2  // comparing just the major version
```

Taking it one step further, we could even provide implicit casts from tuple/string/int to the version type, or other ways of allowing assignment or initialization from tuple/string/int.
```chpl
const version: semanticVersion = (1,2);
```

Fun fact: the following also works, although at present requires all three numbers:
```chpl
const version: semanticVersion(1,2,3);
```

#### Minor default

It is more intuitive for me to write `if Lib.version > version(1)` than to write `if Lib.version > version(1,0)`, so I am with Elliot to allow this.

We need to be careful whether `myVerion > version(1,2)` means "1.2.1 or higher" vs. "1.3 or higher". This is perhaps the same issue as the next one.

I agree there is an issue of whether `version(1)` means `1.0.0` or `1.*`. I propose for it to mean `1.*`. Analogously `ver(1,2)` means `1.2.*`. This is where my intuition takes me; having `version(1)` mean `1.0.0` could make me confused.

To implement `1.*` et al., we could have the fields `minor` and `update` have the value `-1` or an empty string to indicate "any". Despite the expectation that `minor` and `update` are integers, in this case an empty string works fine -- because it indicates, at compile time, that there are no integers that the user can use.

#### Types

I was a bit surprised to learn that there is more than one type to express the version.

It would be natural for me to have a single type that provides all the desired functionality. As a bonus, we could give it a simpler name, like `Version`.

In particular, we could expand the functionality of `semanticVersion` as follows:

* official-ness is a bool param field; or we can have it be an enum or a string to indicate beta/RC/release/"unspecified" (see also python below)

* the SHA field is always present; it can be empty (or 0) or non-empty independently of official-ness

Even if we keep `sourceVersion` as a separate type with a semantic-version field, I suggest renaming `semanticVersion` to just `Version` or another similarly-simple variant. We can consider this as a nod to users who care only about semantic versioning. Cf. developers would have more characters to read/write for the type name.

#### Python

Here are some highlights of Python versioning.

* Python provides `PY_VERSION_HEX` [see this page](https://docs.python.org/3/c-api/apiabiversion.html) that combines major, minor, update versions and more as a single 32-bit integer.

It is cute to include 0xB for "Beta", 0xC for "release Candidate", and 0xF for "Final" release.

A key feature here is that it grows monotonically. We could provide this "as a single number" functionality as well. Although the version's string representation grows monotonically, so we got that covered.

* Python's version is a "named tuple", meaning that it can be compared against tuples.

* The version info is obtained from [the `sys` module](https://docs.python.org/3/library/sys.html) :

  - `sys.version_info`
  - `sys.hexversion`
  - `sys.implementation`  (not sure what to take from this one)

#### Imported by default?

Currently we have an "all or nothing" strategy: some standard modules are `use`-d by default in any program, making their entire contents available directly. The rest need an explicit `use`.

I have been wanting middle ground, where I am willing to name the module, however having to `use` it feels like an unnecessary burden. Especially if I use that module's functionality just once.

Example: it feels natural for me to write `Reflection.canResolve(....)` instead of just `canResolve`. I really don't like having to add `import Reflection` or `use Reflection`. Especially if I have just one or two uses of Reflection functions.

Proposal: define a subset of standard modules that are `import`-ed by default, for easier access.

`Version` could be one of the imported-by-default modules. //This is why this proposal is here.

#### Other

Intuitively I expect 1.7.2.SHA to come after 1.7.2. This is perhaps because I look at it lexicographically. Right now I get the opposite. Would be nice to see how other projects do it.

Unintended implementation omission? `_cast` from `sourceVersion` should also be `param` I think.

**Comment by bradcray** [comment]
@ronawho: With more time and distance, how do you feel about the convenience in naming of the current `version()` function relative to the tension it creates with having a `version` variable within a module?

**Comment by ronawho** [comment]
I'm not sure. When we were originally talking about this I was thinking about it in a `use` world, but if we're designing for an `import` world now then it's really `Version.version()` vs. a module variable named `version`, which I don't think conflicts?

That said, I'm not sure I love `Version.version()`, but I don't hate it.

**Comment by bradcray** [comment]
I don't think we should assume that just because `import` exists, programmers won't use `use` when sketching code out.  But I think even with `import`, there are problems with setting ourselves up for a naming conflict (and, last I tried, I wasn't able to get some simple test case patterns working with `import` due to issues in the compiler related to https://github.com/chapel-lang/chapel/issues/16024 and https://github.com/chapel-lang/chapel/issues/16128).

**Comment by ronawho** [comment]
Right, but if they `use` something, they're intentionally bringing everything into their namespace, so they kinda asked for the name conflict. My thought was that if I'm building a library and I'm far enough along to start versioning things, I'd probably be using `import` instead of `use` by that point because I'd care more about namespace collisions.

**Comment by bradcray** [comment]
Oh, but I'm thinking about the client of your library as well.  That is, I could do:

```chapel
use ElliotsLibrary, Version;

if ElliotsLibrary.version < Version.version(1,0,0) then
  compilerError("I don't want to use this stuff!");
```

but then isn't the value that was originally desired in the succinctness of having a `version()` help function lost compared to making the function be called `createVersion()` or `newVersion()` (or simply using `new sourceVersion()`)?

I.e., if the only situation where you can still write something like `if blah < version(x,y,z)` is one in which `blah` isn't simply `version`, have we maybe optimized for the wrong thing?

**Comment by ronawho** [comment]
Hmm, yeah maybe. I can't remember why I liked just `version()` better. I suspect part of it was thinking about it in a `use` world, but another part is that `new sourceVersion()` exposes that version is a record, so just looking at the code I wouldn't feel very confident that it's a param comparison.

**Comment by bradcray** [comment]
Right, that's why I'd prefer continuing to have a factory function like `createVersion()` or `newVersion()` where I think recent naming discussions have preferred the former.

I think in the main examples we'd discussed previously, we were asking the question `if chplVersion > version(1,23,0)` and not really thinking as much about the "libraries/packages containing version numbers" use cases.

**Comment by ronawho** [comment]
`createVersion()` and `newVersion()` still imply to me that something will be made at runtime. I'd probably just stick with `version()`

**Comment by bradcray** [comment]
> still imply to me that something will be made at runtime.

Something is made at runtime — a value representing the version number (which happens to be implemented as an empty record).

**Comment by vasslitvinov** [comment]
For this release, I propose that we resolve the following issues:
* module name
* version creation function name
* using the module to query the Chapel version vs.
  to declare+query versions of libraries and other purposes
* whether version(1.2.3) precedes or follows version(1.2.3.a85bce82)

#### Chapel version vs other versioning

I suggest that the version module not be required if all I want is to query the Chapel version.

As a bare-bones feature for 1.23, we could have three integer params or parenless functions like `chapelVersionMajor`, `chapelVersionMinor`, `chapelVersionUpdate` that are always available and do not require the versions module. We can refine this for 1.24.

#### Module name and creation function

I am OK with module `Versions` or `Versioning`, preferring `Versions` for brevity.

For version creation, I would like to have in 1.23 something that is acceptable enough while we are looking for that perfect name in 1.24. I vote for `createVersion` because it fits with our factory method conventions (right?). This also means that we do not provide things like `Versions.version(...)` for 1.23 to avoid committing to them too early.

If I were to choose the perfect name today, it would be `Versions.ver(...)`.

#### SHA version precedence

My intuition gives me `version(1.2.3)` < `version(1.2.3.a85bce82)`, perhaps because of lexicographic ordering. Ideally, our ordering would match how it is done in other popular projects.

**Comment by mppf** [comment]
> I think in the main examples we'd discussed previously, we were asking the question `if chplVersion > version(1,23,0)` and not really thinking as much about the "libraries/packages containing version numbers" use cases.

If versioned libraries really are using semantic versioning, won't comparisons involving just the first digit of the version be sufficient? Then, we can still have the minor version if we use `param real`s.

I understand that we'd have implementation difficulties with `if chplVersion > (1,23,0)` today. But wouldn't supporting ``if chplVersion > 1.23` cover 99% of the use cases without leading us towards needing a short name for the function to create a `version`?

**Comment by bradcray** [comment]
> I suggest that the version module not be required if all I want is to query the Chapel version.
> 
> As a bare-bones feature for 1.23, we could have three integer params or parenless functions like chapelVersionMajor, 
chapelVersionMinor, chapelVersionUpdate that are always available and do not require the versions module. We can refine this for 1.24.

To me, these suggestions seem like steps backwards in that:
* we've put a lot of effort into removing names from the default namespace in this release
* the original PR and proposal for this feature used standalone params and was panned reasonably heavily

> My intuition gives me version(1.2.3) < version(1.2.3.a85bce82)

It's understandable why that would be the case, yet in our numbering today (where we use SHAs for pre-releases, but not official releases), the latter definitely precedes the former.

> If I were to choose the perfect name today, it would be Versions.ver(...).

That's a lot of characters for a Vass identifier.  Why not `Versions.v()`?  :D :D :D

> won't comparisons involving just the first digit of the version be sufficient?

In the version number `1.23.0` is the first digit `1` or `23`?  If `23` then I think you make a good point, but use confusing 0-based counting.  :D  If `1`, I think comparing minor versions can be important because while they are not breaking versions, they can add features that weren't in the previous.  I.e., "I know that Chapel 2.11 introduced task teams as a non-breaking feature compared to 2.10, so I want to make sure I'm using at least 2.11.  

> wouldn't supporting if chplVersion > 1.23 cover 99% of the use cases without leading us towards needing a short name for the function to create a version?

I think that's an interesting proposal, and if you made it before as an alternative to `version()` and I missed it, I apologize (I'd seen the proposals to support comparisons with strings and tuples and such, but hadn't ever thought of them as a means of not getting hung up on the name of the `version()` module.

Based on what I'm hearing, it sounds like:
* there's a slight preference for `Versions` over `Version` (though most haven't weighed in)
* `createVersion()` might be the best name for the current `version()` function, where having the comparisons to floating point values would be a value-add that would reduce the need for `createVersion()`.
* and as mentioned on email, I have a PR that combines the two types into one here:  https://github.com/chapel-lang/chapel/pull/16486

**Comment by bradcray** [comment]
I'm going to close this as I think we're over the hump and out of time for the 1.23 release.  Specifically, I:

* combined the two types into one by popular demand
* renamed `version()` to `createVersion()` based on mostly popular demand
* left the module named `Version` due to a split vote, inertia, and simplicity
* left the default argument as-is because more can be added later without breaking existing code
