### ISSUE TITLE
Make clean does not clean up chpl-env-gen.h

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#15926]
We had an issue running test/runtime/sungeun/chpl-env-gen.test.c after a recent update to the runtime.  We had to explicitly remove build/runtime/$(printchplenv --runtime --path)/include/chpl-env-gen.h because make clean did not clean up the file.

**Comment by lydia-duncan** [comment]
@gbtitus or @ronawho - other information I should include?  Feel free to edit the issue as well

**Comment by bradcray** [comment]
Is there something about this that's more complicated than adding `rm -f $(CHPL_ENV_HEADER)` to the clean, cleanall, and clobber rules in runtime/Makefile?

**Comment by gbtitus** [comment]
> Is there something about this that's more complicated than adding `rm -f $(CHPL_ENV_HEADER)` to the clean, cleanall, and clobber rules in runtime/Makefile?

Think it might be better to arrange for the built `chpl-env-gen.h` to be in the `GEN_HEADERS` variable that is already deleted by clean/cleanall/clobber, but yeah, it looks like that's all that's needed.

**Comment by bradcray** [comment]
I implemented this in #15936, but then thought better of taking the approach of cleaning it.  Wouldn't the better/safer thing be to re-generate it when it needs to be re-generated?  See the PR for more detail.

Also, GEN_HEADERS didn't work as an implementation approach because the top-level Makefile doesn't reference that variable in its clean rule; I think GEN_HEADERS was inherited from the compiler's Makefiles but then never used in the runtime (at least, not recently).

**Comment by lydia-duncan** [comment]
I think re-generating it is a much better idea, it removes the need to call `make clean` in that situation.  However, the `make clean` call should probably still clean it up regardless

**Comment by gbtitus** [comment]
Based on some speed-archaeology `GEN_HEADERS` used to work but then someone removed the last/only thing(s) included in it, then `chpl-env-gen.h` was added but the author didn't realize there was such a thing as `GEN_HEADERS`.  I'm with @lydia-duncan though -- it would be good both to regenerate it when needed and remove it in `make clean`.
