### ISSUE TITLE
Compiler bug when using reduction with owned class

### ISSUE THREAD

**Issue by Tegan478** [chapel-lang/chapel#15971]
### Summary of Problem

Sorry if it turns out the error is actually on my end. I was going through old code on a tutorial I am updating and since the way classes are used has changed, I added a memory management strategy in order to try to fix the errors. When compiling I got this error message saying: 
tests.chpl:31: internal error: RES-IMP-NTS-0406 chpl version 1.22.0
Note: This source location is a guess.

Internal errors indicate a bug in the Chapel compiler ("It's us, not you"),
and we're sorry for the hassle.  We would appreciate your reporting this bug --
please see https://chapel-lang.org/bugs.html for instructions.  In the meantime,
the filename + line number above may be useful in working around the issue.

### Steps to Reproduce

**Source Code:**

```chapel
var A: [1..10] int = (-5, 6, -2012, -75, 2012, 48, -700, 65, 100, 0);

class customMin : ReduceScanOp {
type eltType;
var min : eltType = max(eltType);
var secMin : eltType = 0;

proc accumulate(val : eltType) { //accumulate val into result
if(val < min) {
secMin = min;
min = val;
} else if(val <= secMin){
secMin = val;
}
}

proc combine(other : customMin) { //combine 2 partial reductions
if(other.min < min) {
secMin = min;
min = other.min;
} else if(other.min <= secMin){
secMin = other.min;
}
}

proc generate() { //return the current state
return secMin;
}
}

writeln("The second minimum is ", owned customMin reduce A,".");
```

**Compile command:**

**Execution command:**

**Associated Future Test(s):**

### Configuration Information

- Output of `chpl --1.22.0`:
- Output of `$CHPL_HOME/util/printchplenv --anonymize`:
- Back-end compiler and version, e.g. `gcc --version` or `clang --version`:
- using cygwin for windows
- (For Cray systems only) Output of `module list`:

**Comment by rahulghangas** [comment]
@Tegan478 the interface for user defined reductions has changed a bit. Which means there are a few methods missing.

```chpl
var A: [1..10] int = (-5, 6, -2012, -75, 2012, 48, -700, 65, 100, 0);

class customMin : ReduceScanOp {
  type eltType;
  var minimum : eltType = max(eltType);
  var secMin : eltType = 0;

  proc identity return max(eltType);

  proc accumulate(val : eltType) { //accumulate val into result
    if(val < minimum) {
      secMin = minimum;
      minimum = val;
    } else if(val <= secMin){
      secMin = val;
    }
  }

  proc accumulateOntoState(ref state, x) {
    state = min(state, x);
  }

  proc combine(other : customMin) { //combine 2 partial reductions
    if(other.minimum < minimum) {
      secMin = minimum;
      minimum = other.minimum;
    } else if(other.minimum <= secMin){
      secMin = other.minimum;
    }
  }

  proc generate() { //return the current state
    return secMin;
  }

  proc clone() return new unmanaged customMin(eltType=eltType);
}

writeln("The second minimum is ", customMin reduce A,".");
```

Also, the left hand side of a reduce expression should be a class, not an object. So, you don't need the `owned` keyword

**Comment by mppf** [comment]
hi @Tegan478 - thanks for creating this issue. Assuming that @rahulghangas's suggestions work for you - then I think the next step would be to try to improving the error message in the case you encountered to be more reasonable.

**Comment by Tegan478** [comment]
Thank you @rahulghangas. That fixed it.

**Comment by bradcray** [comment]
@Tegan478: I'm back from vacation and curious what tutorial you're updating?  Thanks.

**Comment by Tegan478** [comment]
@bradcray I am a student at Knox College working on updating a tutorial made by my professor and some previous students:
[http://faculty.knox.edu/dbunde/teaching/chapel/](url)

**Comment by bradcray** [comment]
Thanks @Tegan478, and give my best to David!  If we can help you in your efforts to update the tutorial, please let me know.  I'm afraid a lot has changed since that Chapel 1.9-era tutorial, though hopefully you guys will feel it's mostly for the better.  

If you're interested in seeing some of those changes proactively, best bets are probably to look at https://chapel-lang.org/docs/language/evolution.html for major breaking changes and/or the "Highlights" sections of the [CHANGES.md](https://github.com/chapel-lang/chapel/blob/master/CHANGES.md) file in the release.  And then if something in particular is of interest to you, checking Chapel's [release notes](https://chapel-lang.org/releaseNotes.html) and [archived release notes](https://chapel-lang.org/release-notes-archives.html) for the corresponding release is the best way to learn more.  Again, let us know if we can help.

W.r.t. this particular issue, we've generally de-emphasized Chapel's ability to create user-defined reductions and scans in tutorials because the interface has been under flux, and is expected to evolve further.  That's not to say that you guys should feel the need to avoid it in your tutorials, but just wanted to let you know how we think of the feature in terms of stability (i.e., not very).

**Comment by Tegan478** [comment]
@bradcray Thanks for the advice! I'll be sure to look through those and also talk to David about what to do with user-defined reductions in the tutorial.

**Comment by DanilaFe** [comment]
This is no longer an internal error, though the feature is still not implemented. https://github.com/chapel-lang/chapel/issues/16462 tracks the implementation of the feature, and the associated test `test/reductions/sungeun/count.chpl` captures the error message that I'm getting out of this case.
