### ISSUE TITLE
Calling function w/ and w/out parens using qualified naming causes compiler segfault

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#16024]
### Summary of Problem

While writing a code today that called a function both with and without parenthesis using qualified naming, I got a compiler segfault (`internal error: UTI-MIS-0691`).  The segfault seemed to go away if I didn't use qualified naming, or if I wrapped the function calls in writeln() calls. 

### Steps to Reproduce

**Associated Future Test(s):**
[`test/functions/resolution/parenless-call-segfault.chpl`](
           https://github.com/chapel-lang/chapel/blob/master/test/functions/resolution/parenless-call-segfault.chpl
          ) #16022

### Configuration Information

- Output of `chpl --version`: `chpl version 1.23.0 pre-release (c54a5da1fe)`

**Comment by bradcray** [comment]
A long shot, but this may be related to #16023.  Or rather, the same fix may potentially address both of them.

**Comment by lydia-duncan** [comment]
I know why it is getting a segfault - resolveModuleCall assumes that the parentExpr of all such module calls is another CallExpr, but in the case of the first line you are making a first class function call and that doesn't have an outer CallExpr (its parentExpr ends up being the then BlockStmt in your test).

However, what to do about it is going to be a bit trickier.  We rely on module arguments when resolving qualified calls at function resolution, but inserting module arguments changes it from looking like a fcf call (since now it has arguments), so our transformation into a PRIM_CAPTURE_FN_FOR_CHPL call is skipped.  Fixing that will require a workaround at scope resolution, and possibly an adjustment of our resolution for PRIM_CAPTURE_FN_FOR_CHPL at function resolution.

**Comment by bradcray** [comment]
This isn't a deeply important issue for me, just something I wanted to capture after running into it (though obviously it would be great to fix).  If the fix is a heavy lift that we wanted to put off, putting in some sort of user-facing error to replace the segfault saying that such-and-such isn't supported yet (is it something like "module-qualified capture of function pointers?" though I don't think that's quite the right term).

Probably not obvious from this issue, but the way I ran into this had nothing to do with first-class functions, or at least wasn't intended to.  Instead, I was trying to demonstrate that if a library module like `M` switched from a paren-less function `y` to a paren-ful `y()` or vice-versa, we could use the new Version module to write queries that would let a user write code that would work with either version of `M`.  But then the segfault pointed out that that wasn't the case.

**Comment by lydia-duncan** [comment]
> is it something like "module-qualified capture of function pointers?"

Yup, basically!

> Instead, I was trying to demonstrate that if a library module like M switched from a paren-less function y to a paren-ful y() or vice-versa, we could use the new Version module to write queries that would let a user write code that would work with either version of M. But then the segfault pointed out that that wasn't the case.

Ah, I see.  So there's three different situations at stake:
- function was parenless and worked
- function got parens but the call remained parenless and so turns into a fcf representation when compiled with later versions, and finally
- the function got parens and the call was updated to also use parens.

That seems much more reasonable of a situation to encounter than I was expecting, though I suspect it will still be rare.

I would be fine with adding a user-facing error message and punting on the change for now - I dunno if it would be too heavy of a lift to fix if it is just the two spots I see, but I can see it getting out of hand since the change will violate our previously held expectations about such calls.  But I also probably wouldn't prioritize it over the other import/use bugs I want to work through

**Comment by lydia-duncan** [comment]
I opened #16128 for the new behavior so I could update the future to reference it.

**Comment by lydia-duncan** [comment]
I merged #16129, which replaces this behavior with that of #16128.  Closing in favor of the latter as a result
