### ISSUE TITLE
Calling function via qualified name confuses it with local variable of same name

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#16023]
### Summary of Problem

When initializing a variable using a qualified call to a function of the same name, like so:

```chapel
var y = M.y();
```

the compiler generates an error as though the qualified function call referred to the local variable:

```
error: 'y' used before defined
```

This behavior seems to be independent of whether `use` or `import` is used.  Interestingly, when `M.y` is a variable rather than a function call, the problem seems to go away.

### Steps to Reproduce

**Associated Future Test(s):**
[`test/visibility/import/edgeCases/qualInitsSameName.chpl`](
           https://github.com/chapel-lang/chapel/blob/master/test/visibility/import/edgeCases/qualInitsSameName.chpl
          ) #16022 
[`test/visibility/qualInitsSameName.chpl`](
           https://github.com/chapel-lang/chapel/blob/master/test/visibility/qualInitsSameName.chpl
          ) #16022 

### Configuration Information

- Output of `chpl --version`: `chpl version 1.23.0 pre-release (c54a5da1fe)`

**Comment by bradcray** [comment]
A long shot, but this may be related to #16024.  Or rather, the same fix may potentially address both of them.

**Comment by lydia-duncan** [comment]
It is a related part of the code, but I believe what is going on is that we are inserting an UnresolvedSymExpr for the function name as a result of resolveModuleCall, but because we haven't finished traversing the UnresolvedSymExprs in scopeResolve and we've created a new one, we end up resolving it later in that same pass (but ignore the fact that it is the baseExpr of a call and that the inserted module argument is present, because this is scope resolve not function resolution).

**Comment by lydia-duncan** [comment]
(This issue was resolved by the PR that closed it)
