### ISSUE TITLE
Update doc for map.getValue(key)

### ISSUE THREAD

**Issue by ankingcodes** [chapel-lang/chapel#16065]
`.getValue()` was added to support different class types as keys/values in maps. This issue is a gentle reminder for adding a doc-string to the signature of the proc.

**Comment by bradcray** [comment]
[On gitter](https://gitter.im/chapel-lang/chapel?at=5f0cf16386ccb45b59a4fc0f), @ankingcodes reported that he got an error message like:

```bash
 error: unresolved call 'map(string,string,false).getValue("Some-key")'
$CHPL_HOME/modules/standard/Map.chpl:332: note: this candidate did not match: map.getValue(k: keyType)
$CHPL_HOME/modules/standard/Map.chpl:332: note: because where clause evaluated to false
$CHPL_HOME/modules/internal/ChapelRange.chpl:1987: note: candidates are: _ic_chpl_direct_param_stride_range_iter.getValue()
$CHPL_HOME/modules/internal/ChapelRange.chpl:1951: note:                 _ic_chpl_direct_counted_range_iter_helper.getValue()
note: and 166 other candidates, use --print-all-candidates to see them
```

when trying to call `.getValue()` with a string argument.  Could we add an error overload of `map.getValue()` (or remove the where clause and add a conditional within it?) saying something like "map.getValue() only supports class types" if that's the intention since the error message above isn't particularly clear?

Tagging @dlongnecke-cray who has been running with collections and classes lately.

**Comment by dlongnecke-cray** [comment]
On it!
