### ISSUE TITLE
--warn-unstable on modules

### ISSUE THREAD

**Issue by BryantLam** [chapel-lang/chapel#16101]
Is there a way to mark a module as unstable so it gets warned via `chpl --warn-unstable`?

Something like:
```chapel
#pragma warn-unstable
module M {
  ...
}

import M; // <-- warning triggered here
```

**Comment by BryantLam** [comment]
Could also be extended for deprecated modules, functions, etc. similar to C++14 `[[deprecated]]` attribute and other desirable attributes (e.g., `unused`)

**Comment by bradcray** [comment]
There's not a language-level way to do it, nor a documented / user-facing way, but in the current implementation, one could accomplish this by writing:

```chapel
if chpl_warnUnstable then
  compilerWarning("Your unstable warning message here");
```

This could be promoted to a user-facing feature either by making `chpl_warnUnstable` more of a documented/user-facing symbol, or by baking it more into the language / implementation using one of the techniques you suggest.

**Comment by mppf** [comment]
It seems to me that this issue is requesting that a module be able to request it be compiled as if `--warn-unstable` is always thrown, that is, it shows a warning if unstable language features are used. It seems like something we could do with a general attribute syntax (see issue #14141).

**Comment by bradcray** [comment]
While I'm reluctant to speak for @BryantLam, from my reading of the OP, I think this can be closed without the need for an ack.  Specifically, compiling this test:

```chapel
@unstable
module M {
}

module Main {
  import M; // <-- warning triggered here                                       
  proc main() {
  }
}
```

gives:

```bash
$ chpl --warn-unstable testit.chpl
testit.chpl:6: warning: M is unstable
```

(the OP does as well if `import M;` is changed to `import this.M;` since explicit pathing to sub-modules is required for the `import` statement.

@mppf's comment has a different interpretation of the request, but I don't see how he's reading that into the OP, which seems to pretty clearly be warning about the reference to the module itself rather than a reference to something unstable within the module.  (I think his comment reflects a completely reasonable feature request, I just don't see what in the OP is suggesting that interpretation...  I guess arguably the title is, but the title is terse enough to be pretty vague).

**Comment by mppf** [comment]
@bradcray - re-reading the OP, I am inclined to agree with you.

**Comment by lydia-duncan** [comment]
Okay, I'll close it.  Thanks!
