### ISSUE TITLE
Should storing an array view in a variable make it non-view?

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#16275]
(Related to #5474 and #12178).

Generally, we have the behavior that storing a slice into a (non-ref) variable causes a copy of the slice to be made. Similarly for returning a slice from a function by value. (But we never created syntax for the alternative - see #12178).

In working on #16180, I was surprised that copying a reindex/rank change array left one with a reindex/rank change array. (However it does copy the elements). I was expecting that an array view would no longer be an array view once a copy of it is made. We've had this behavior since 1.18 (and the test program below didn't compile in 1.17 or 1.16).

Here is a test program to demonstrate:

``` chapel
proc returnIt(arg) { return arg; }

proc main() {
  var A: [1..2] real;
  var AA: [1..2, 1..2] real;

  {
    writeln();
    writeln("slice");
    const ref rB = A[1..1];
    writeln("to const ref is view:         ", rB.isSliceArrayView());

    var B = A[1..1];
    writeln("to var is view:               ", B.isSliceArrayView());
    
    const ref rReturned = returnIt(A[1..1]);
    writeln("returned is view:             ", rReturned.isSliceArrayView());

    const ref rD = A[1..1].domain;
    writeln(".domain to const ref is view: ", rD.isSliceDomainView());

    var D = A[1..1].domain;
    writeln(".domain to var is view:       ", D.isSliceDomainView());
  }

  {
    writeln();
    writeln("reindex");
    const ref rB = A.reindex(3..4);
    writeln("to const ref is view:         ", rB.isReindexArrayView());

    var B = A.reindex(3..4);
    writeln("to var is view:               ", B.isReindexArrayView());
    
    const ref rReturned = returnIt(A.reindex(3..4));
    writeln("returned is view:             ", rReturned.isReindexArrayView());

    const ref rD = A.reindex(3..4).domain;
    writeln(".domain to const ref is view: ", rD.isReindexDomainView());

    var D = A.reindex(3..4).domain;
    writeln(".domain to var is view:       ", D.isReindexDomainView());
  }

  {
    writeln();
    writeln("rank change");
    const ref rB = AA[1, ..];
    writeln("to const ref is view:         ", rB.isRankChangeArrayView());
    
    var B = AA[1, ..];
    writeln("to var is view:               ", B.isRankChangeArrayView());

    const ref rReturned = returnIt(AA[1, ..]);
    writeln("returned is view:             ", rReturned.isRankChangeArrayView());

    const ref rD = AA[1, ..].domain;
    writeln(".domain to const ref is view: ", rD.isRankChangeDomainView());

    var D = AA[1, ..].domain;
    writeln(".domain to var is view:       ", D.isRankChangeDomainView());
  }
}

```

It outputs
```

slice
to const ref is view:         true
to var is view:               false
returned is view:             false
.domain to const ref is view: false
.domain to var is view:       false

reindex
to const ref is view:         true
to var is view:               true
returned is view:             true
.domain to const ref is view: true
.domain to var is view:       true

rank change
to const ref is view:         true
to var is view:               true
returned is view:             true
.domain to const ref is view: true
.domain to var is view:       true
```

however I would expect only the "to const ref" rows to print out `true`.

**Comment by kateaditya646** [comment]
how to work on that bug guys its a very easy

**Comment by mppf** [comment]
@kateaditya646 - I don't think this issue is easy or a good starting issue. Please see https://chapel-lang.org/contributing.html for guidance on how to contribute to this project (if you haven't already looked at it).

**Comment by bradcray** [comment]
I agree that all of the array captures / returns should be copies and not views.

IIRC (and a quick check of the source suggests this), slices use the domain that was used to express the slice (and its distribution) to characterize the slice's domain, whereas rank-change slices and reindexings need to create a new domain (and distribution) in general; so it seems to me it is probably correct for them to be asymmetric in this regard.  Specifically, note that the ArrayViewSlice.chpl file doesn't have any classes corresponding to distributions or domains, but the other to ArrayView files do.  That's what makes me think that there's a natural/intentional asymmetry here.  This suggests to me that perhaps `isSliceDomainView()` isn't interesting / shouldn't exist?  (since it's not a question that ever has a `true` answer?).  Or maybe I just don't understand what these isDomainView queries are meant to be doing...  (I don't think they're user-facing, are they?)

**Comment by mppf** [comment]
>  This suggests to me that perhaps isSliceDomainView() isn't interesting / shouldn't exist?  (since it's not a question that ever has a true answer?)

I agree about that.

> (I don't think they're user-facing, are they?)

AFAIK they are not user facing. I was just using them as an easy way for the test to check if it was getting a view or non-view type

> so it seems to me it is probably correct for them to be asymmetric in this regard.

I think you are talking about the `.domain to const ref is view` line? FWIW after PR #16180 this test output is:
```

slice
to const ref is view:         true
to var is view:               false
returned is view:             false
.domain to const ref is view: false
.domain to var is view:       false

reindex
to const ref is view:         true
to var is view:               false
returned is view:             false
.domain to const ref is view: true
.domain to var is view:       false

rank change
to const ref is view:         true
to var is view:               false
returned is view:             false
.domain to const ref is view: true
.domain to var is view:       false
```

which seems reasonable to me.

**Comment by mppf** [comment]
@bradcray - I am wondering what you would expect the domain type for a view-captured-into-an array to be.

``` chapel
proc returnIt(arg) { return arg; }

proc main() {
  var A: [1..2] real;
  var AA: [1..2, 1..2] real;

  {
    writeln();
    writeln("reindex");
    var B = A.reindex(3..4);
    writeln("to var is view:               ", B.isReindexArrayView());

    const ref rD = B.domain;
    writeln("var.domain is view:           ", rD.isReindexDomainView());
  }

  {
    writeln();
    writeln("rank change");
    var B = AA[1, ..];
    writeln("to var is view:               ", B.isRankChangeArrayView());

    const ref rD = B.domain;
    writeln("var.domain is view:           ", rD.isRankChangeDomainView());
  }
}
```

Based on your comments on #16298 and #16300 - I suspect that the answer might be "the rank change/reindex domain".

FWIW the above program has this behavior on the main branch:

```

reindex
to var is view:               true
var.domain is view:           true

rank change
to var is view:               true
var.domain is view:           true
```

and currently this behavior with PR #16180:
```

reindex
to var is view:               false
var.domain is view:           false

rank change
to var is view:               false
var.domain is view:           false
```

I am guessing that the expected behavior is this:

```

reindex
to var is view:               false
var.domain is view:           true

rank change
to var is view:               false
var.domain is view:           true
```

**Comment by mppf** [comment]
Note that issue is specifically about the type of the array view arrays.

The element copies (or not) are occurring as expected:

``` chapel
proc returnIt(arg) { return arg; }

proc main() {
  var A: [1..2] real;
  var AA: [1..2, 1..2] real;

  {
    writeln();
    writeln("slice");
    A = 0;
    const ref rB = A[1..1];
    A = 1;
    writeln("to const ref behaves view:         ", A[1]);

    A = 0;
    var B = A[1..1];
    A = 1;
    writeln("to var behaves view:               ", B[1]);
    
    A = 0;
    const ref rReturned = returnIt(A[1..1]);
    A = 1;
    writeln("returned behaves view:             ", rReturned[1]);
  }

  {
    writeln();
    writeln("reindex");
    A = 0;
    const ref rB = A.reindex(3..4);
    A = 1;
    writeln("to const ref behaves view:         ", rB[3]);

    A = 0;
    var B = A.reindex(3..4);
    A = 1;
    writeln("to var behaves view:               ", B[3]);
    
    A = 0;
    const ref rReturned = returnIt(A.reindex(3..4));
    A = 1;
    writeln("returned behaves view:             ", rReturned[3]);
  }

  {
    writeln();
    writeln("rank change");
    AA = 0;
    const ref rB = AA[1, ..];
    AA = 1;
    writeln("to const ref behaves view:         ", rB[1]);
    
    AA = 0;
    var B = AA[1, ..];
    AA = 1;
    writeln("to var behaves view:               ", B[1]);

    AA = 0;
    const ref rReturned = returnIt(AA[1, ..]);
    AA = 1;
    writeln("returned behaves view:             ", rReturned[1]);
  }
}
```

prints this on master and with PR #16180:

```

slice
to const ref behaves view:         1.0
to var behaves view:               0.0
returned behaves view:             0.0

reindex
to const ref behaves view:         1.0
to var behaves view:               0.0
returned behaves view:             0.0

rank change
to const ref behaves view:         1.0
to var behaves view:               0.0
returned behaves view:             0.0
```

**Comment by mppf** [comment]
If `var B = A.reindex(3..4);` needs to have the reindexed domain, it could have a new array type e.g. `ReindexedArrayCopy`, which would have a reindexed domain but own its elements (i.e. not be a "view").

**Comment by bradcray** [comment]
> I think you are talking about the .domain to const ref is view line?

Yeah, sorry. I was not clear about that.

Regarding your question about the captured array not being a view, but its domain being a view, I see the conflict that you're pointing out (and suspect that this is at the heart of why we're not capturing reindex and rank-change slices on master today?).  Let me stew on this a bit more; I'm worried any answer I give off the cuff will be incorrect / problematic in the distributed case.

**Comment by bradcray** [comment]
OK, I thought about this a bit more over lunch, and am now trying to capture my thoughts crisply, typing them down as I do so... (it may sound like I'm lecturing, but I'm really just trying to get the facts straight for myself, so if I'm lecturing anyone, it's myself).

Given a block-distributed array:

```chapel
var A = newBlockArr({1..10}, real);
```

running on a 2-locale system, we'd expect locale 0 to own `A[1..5]` and locale 1 to own `A[6..10]`.  Now if we reindex this:

```chapel
ref B = A.reindex({0..9});
```

then we'd expect locale 0 to own `B[0..4]` and locale 1 to own `B[5..9]`.  Now if we capture B into a new variable C:

```chapel
var C = B;
```

we'd expect C's index set to be 0..9 and to have the same distribution as B and reindexed-A, such that locale 0 owns `C[0..4]` and locale 1 owns `C[5..9]`.  But for C to be a deep copy of B/A such that modifications to C or A weren't reflected in the other.

While for a block distribution, it's conceivable to think of creating a new block distribution and domain that describe C's mapping directly, in the general case, not all distributions can support arbitrary closed-form representations of rank-change slices or reindexings (e.g., a Cyclic 1D distribution targeting three locales would have a hard time supporting a slice of `1..n by 2` reindexed to be `1..n/2` since it wouldn't distribute the reindexed indices in the traditional dense round-robin way that Cyclic does).  And even for Block, it simplifies the domain map's implementation not to have to create variations of itself.  And, we'd generally like to having new expressions inherit/reuse existing domains rather than create new ones all the time, particularly for domains that are expensive to set up or store.  All of this is why we went to the current array view strategy in which those two operations create their own special domains and distributions which refer back to the original domain(s) and distribution.  And it's why C's domain would still consider itself to be a domain view (since it's the same domain as B / reindexed-A.

But C obviously isn't, or shouldn't be, an array view in the sense that it has its own storage and isn't referring to a different array.  How does this work today, since you note [a few comments above](https://github.com/chapel-lang/chapel/issues/16275#issuecomment-685012497) that it is?  (checking...).  From what I'm seeing, it looks like C is represented the same way as "reindexed A" was in the sense that `ArrayViewReindexDom.dsiBuildArray()` asks the underlying domain to build a new array and then refers to it indirectly, as the original reindexing would.  The main difference is that it sets `ownsArrInstance` to `true` to get the memory management correct when the view is destroyed.  This flag essentially is the difference between an array view referring to a pre-existing array and a new array created over an array view's domain.

What if, instead, dsiBuildArray() returned a new/distinct array type as you propose above, `ReindexedArrayCopy`?  Would we be able to implement all of the dsi interface on that new array type?

Taking dsiAccess() as an example, if we wrote `C[7]`, we'd need the `ReindexedArrayCopy.dsiAccess()` to use the reindexed domain/distribution in order to determine which locale owned element 7, much as `ArrayViewReindexArr.dsiAccess()` does today.  Thinking about `dsiBuildArray()` as another example, `ReindexedArrayCopy.dsiBuildArray()` would essentially have to defer to the underlying domains and distributions to determine what each locale should do to allocate `C` in a way that's compatible with reindexed A.  So that also feels like it would end up being quite similar to what `ReindexedArrayCopy` does today.

So, if they're so similar, what would be the motivation for `ReindexedArrayCopy`?  It would give us a distinct type and permit us to distinguish between the original array view and a copy of such an array view at compile-time.  But maybe we could do that by converting the `ownsArrInstance` bool from `const` to `param` in order to not have two array class implementations that (from what I'm guessing) would end up being fairly similar?

Or, could/should the existing calls to check whether or not something is an array view be made into non-param queries such that they can check `ownsArrInstance` as well?  (I'm guessing that the places we want to know this aren't all amenable to being runtime checks, but am not sure).

So I think that's why we are where we are today.  I'm pausing here for now to get your thoughts, @mppf.

**Comment by mppf** [comment]
@bradcray - thanks very much for talking yourself (and me) through all of that.

> From what I'm seeing, it looks like C is represented the same way as "reindexed A" was in the sense that ArrayViewReindexDom.dsiBuildArray() asks the underlying domain to build a new array and then refers to it indirectly, as the original reindexing would.

Somehow I never really caught on to this part, but it's good to know what's going on.

>  But maybe we could do that by converting the ownsArrInstance bool from const to param in order to not have two array class implementations that (from what I'm guessing) would end up being fairly similar?

Yep, that makes sense to me too. The compiler would just need to know how to check the param field in the right places, which is slightly harder but not a big deal.

> Or, could/should the existing calls to check whether or not something is an array view be made into non-param queries such that they can check ownsArrInstance as well? (I'm guessing that the places we want to know this aren't all amenable to being runtime checks, but am not sure).

We used to do this, but it basically adds a bunch of complexity to the compiler-modules interface and is the reason we had `chpl__unalias`. However over time `chpl__unalias` evolved into something that could be handled better at compile-time only (even while it was probably always adding extra copies for view copies). Then, for better or worse, in PR #16180 I have been trying to remove `chpl__unalias`.

**Comment by bradcray** [comment]
> The compiler would just need to know how to check the param field in the right places, which is slightly harder but not a big deal.

Assuming the compiler currently relies on the "is*View() routines" (does it?) I was thinking that we could change them to check the param field (or add new queries and use them instead).  If the compiler is doing something more primitive like looking directly at the type, you're right of course.

**Comment by mppf** [comment]
> Assuming the compiler currently relies on the "is*View() routines" (does it?) 

No, but this isn't a big deal either way.

**Comment by mppf** [comment]
Anyway I think I will try the `param` strategy and see if that gets us where we need to be.

**Comment by mppf** [comment]
@bradcray - what about this part?

```

    var D = A.reindex(3..4).domain;
    writeln(".domain to var is view:       ", D.isReindexDomainView());
```

I think that we want `D` to have the same distribution as the original (Supposing A was block distributed or something) and therefore `D` should be a reindex domain. Is that right?

**Comment by bradcray** [comment]
Hmm, that's a good question.  (thinking...).  Yes, I believe so.  D should store the indices {3..4} but using the distribution that governs A's original indices, so I think it would need to be a reindex domain to achieve that in the general case.

**Comment by mppf** [comment]
PR #16180 will address these and adds the test `test/arrays/ferguson/views-and-copying.chpl` based on the examples from this issue.
