### ISSUE TITLE
createStringWithNewBuffer should accept buffer type of: c_ptr(c_char)

### ISSUE THREAD

**Issue by ben-albrecht** [chapel-lang/chapel#16321]
### Summary of Problem

I was toying with migrating `c_string` code to `c_ptr(c_char)` code in preparation for deprecating `c_string` (#14215), and I ran into an issue with converting a `c_ptr(c_char)` back into a Chapel string. The issue stems from the argument type of `createStringWithNewBuffer()` to be `bufferType` (`c_ptr(uint(8)`), but `c_ptr(c_char)` is `c_ptr(int(8))`.

I think `createStringWithNewBuffer()`  should accept `c_ptr(int(8))` as well. 

### Steps to Reproduce

**Source Code:**

I expected the code below to work:

```chapel
// Doesn't work
use SysCTypes;

var s = 'foo';
var ptr = s.c_str():c_ptr(c_char);
var s2 = createStringWithNewBuffer(ptr, s.size);
writeln(s2);
```

However, this gave a resolution error:

```sh
cstring.chpl:7: error: unresolved call 'createStringWithNewBuffer(c_ptr(int(8)), int(64))'
$CHPL_HOME/modules/internal/String.chpl:690: note: this candidate did not match: createStringWithNewBuffer(x: c_string, length = x.size, policy = decodePolicy.strict)
cstring.chpl:7: note: because call actual argument #1 with type c_ptr(int(8))
$CHPL_HOME/modules/internal/String.chpl:690: note: is passed to formal 'x: c_string'
$CHPL_HOME/modules/internal/String.chpl:698: note: candidates are: createStringWithNewBuffer(s: c_string, length = s.size, policy = decodePolicy.strict)
$CHPL_HOME/modules/internal/String.chpl:728: note:                 createStringWithNewBuffer(x: bufferType, length: int, size = length+1, policy = decodePolicy.strict)
note: and 3 other candidates, use --print-all-candidates to see them
```

`bufferType` is defined in `ByteBufferHelpers.chpl` as:

```chpl
  pragma "no doc"
  type byteType = uint(8);
  pragma "no doc"
  type bufferType = c_ptr(byteType);
```

So, to work-around this issue, I switched to using the `bufferType`:

```chpl
// Works
use SysCTypes;
var s = 'foo';
var ptr = s.c_str():c_ptr(uint(8));
var s2 = createStringWithNewBuffer(ptr, s.size);
writeln(s2);
```

### Configuration Information

- Output of `chpl --version`: `chpl version 1.23.0 pre-release (b9fcd23fa7)`

**Comment by ben-albrecht** [comment]
Discussed this with @mppf.

@e-kayrakli probably has a valuable opinion on this.

**Comment by e-kayrakli** [comment]
I agree that we should add this.

The only potential challenge that I can think of is in validating the buffer if it contains negative integers. I would like to think that we can just cast the buffer to an uint buffer and validate based on that. However, that would mean some negative ints being interpreted as uints whose MSBs are set, and one can think of an array of negative ints that correspond to valid UTF8 buffer when interpreted as unsigned integers. Should we take those buffers as valid, or should we do a pre-validation for negative integers in the buffer?

**Comment by ben-albrecht** [comment]
> Should we take those buffers as valid, or should we do a pre-validation for negative integers in the buffer?

Asking from the perspective of someone who hasn't worked on strings much - what are the trade-offs here?

**Comment by mppf** [comment]
I think casting the `int(8)` to `uint(8)` would be just fine. I think it's reasonable to interpret the UTF-8 format as something on bytes rather than on 8-bit unsigned integers (say). I do not think any additional validation is necessary. It is OK and good if the negative integers are interpreted as uints with a high bit set.

**Comment by e-kayrakli** [comment]
> Asking from the perspective of someone who hasn't worked on strings much - what are the trade-offs here?

If you blindly take them as valid, it would be just weird and feels wrong. For example:

```python3
>>> "ç".encode()
b'\xc3\xa7'
>>> 0xc3-0xff
-60
>>> 0xa7-0xff
-88
```

So, if you have a C buffer of `int(8)`s that is basically `[-60, -88]`, we'll eat it up thinking it is the character "ç". But is -60 a valid byte in an UTF-8 string? My answer would be no, but maybe I should see UTF-8 data as just pure bytes without any sign, but the distinction isn't very intuitive.

If we want to prevent that, I don't see any clear way. Because a negative `int(8)` is not necessarily illegal byte. But one approach could be that we can limit strings to ASCII only, if the buffer passed is of type `c_ptr(int(8))`. In that case, negative integers would be invalid. And if that's the case, I think this doesn't have any extra overhead, because instead of validating the string against UTF-8, we just validate against ASCII, which is much simpler.

I don't have a strong opinion. I am never comfortable while dealing with strings in C... but I am wondering how C is handling UTF-8 data.

**Comment by mppf** [comment]
> but I am wondering how C is handling UTF-8 data.

Pretty sure C could would just treat the buffer contents as bytes (and ignore sign differences). You know, casting the pointer and all that.

> But is -60 a valid byte in an UTF-8 string?

Yes, it's just 0xC4, right? I don't see what the problem is...

https://en.wikipedia.org/wiki/UTF-8 describes UTF-8 in terms of bytes and does not mention signed or unsigned anywhere. I think that's because whether bytes are signed or unsigned is irrelevant as long as the code handling UTF-8 picks one representation and sticks to it...

**Comment by e-kayrakli** [comment]
@mppf -- you are right. Although I have to say that it still feels a bit weird to me, that looks like the right approach.
