### ISSUE TITLE
Disambiguate compile command in linear algebra documentation

### ISSUE THREAD

**Issue by CaptainSharf** [chapel-lang/chapel#16433]
### Summary of Problem
The compilation command in the [documentation](https://chapel-lang.org/docs/modules/packages/LinearAlgebra.html) for linear algebra assumes the variables `PATH_TO_LAPACKE_INCLUDE_DIR`, `PATH_TO_LIBGFORTRAN` and `PATH_TO_LAPACK_BINARIES` to be set in the build environment. It would be a good idea to indicate that these variables need to be set before using the compile command given in the doc. We can optionally provide recommended values for these variables.

**Comment by bradcray** [comment]
I'd be inclined to take the approach of formatting these differently rather than implying that they are (or need to be) pre-set environment variables.  For example, maybe `-I /path/to/lapack/header/file` or `-I` _`[path to LAPACK header file]`_?  But I'll defer to @ben-albrecht as the `LinearAlgebra` module expert if he thinks differently.

**Comment by ben-albrecht** [comment]
That would work for me.

**Comment by jabraham17** [comment]
I've opened https://github.com/chapel-lang/chapel/pull/25501 to implement the suggested `-I /path/to/lapack/header/file`
