### ISSUE TITLE
Can we remove 'initializers defined outside the module' warning?

### ISSUE THREAD

**Issue by vasslitvinov** [chapel-lang/chapel#16495]
[for post-1.23 consideration]

Currently the compiler / AggregateType.cpp in some cases produces the warning:
```
warning: initializers defined outside the module where the type was originally defined may cause issues
note: This will no longer be a problem when constructors are deprecated
```

Can this be removed now, or else rephrased to be more specific?

Tests: these currently contain this warning in .good:
```
test/classes/initializers/secondary/inDiffModule.chpl
test/classes/initializers/secondary/inDiffModule2.chpl
test/classes/initializers/secondary/inDiffModule3.chpl
test/classes/initializers/secondary/inDiffModuleBothSecondaryAndPrimary.chpl
test/classes/initializers/secondary/inDiffModuleBothSecondaryAndPrimary2.chpl
```

**Comment by vasslitvinov** [comment]
@lydia-duncan would you check this out after the release?

**Comment by lydia-duncan** [comment]
That sounds familiar - if my memory is correct, the issue was that only having initializers defined outside of the original module meant we were falling back on using constructors to be safe.  This was probably resolved as soon as we started generating initializers by default.  I've assigned myself and upped it in the backlog, and I'll set a reminder for myself as well.  Thanks for finding it!
