### ISSUE TITLE
when can a different type be passed to an inout formal?

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#16554]
Currently, it is allowable to pass an array slice to a generic `inout` argument. When that happens, the formal argument is instantiated with a copy of the slice and then this is copied back to the slice after the call.

However other parts of the compiler insist that an `inout` formal argument match the type of the actual exactly. As a result we have what might be viewed as inconsistent behavior in the following cases:

``` chapel
// this works
{
  var A:[1..10] int;
  ref slice = A[1..3];
  f(slice);
}

proc f(inout arg) { }

// this does not
{
  var A:[1..10] int;
  ref slice = A[1..3];
  g(slice); // error: value from coercion passed to ref formal 'arg'
}

proc g(inout arg: [1..3] int) { }

// this does
{
  var x: int(8);
  h(x);
}

proc h(in arg: int) { }

// this does not
{
  var x: int(8);
  i(x); //  error: unresolved call 'i(int(8))'
}

proc i(inout arg: int) { }
```

I would propose that the compiler resolve `inout` similarly to `in` and then if there are errors doing the write-back they will occur after the function is chosen.

**Comment by bradcray** [comment]
I tend to think that if the formal's type can be copy-initialized from the actual argument's type, that `in` should be legal (I think this relates to a question I sent you about passing block arrays to DR formals recently?).  And that if the formal's type can be assigned to the actual argument's type that `out` should be legal.  And if both of these are true, that `inout` should be legal.

I _might_ be convinced to believe that if you can assign from the actual type to the formal type that `in` should be legal as well, but I'm less confident about this extension.

**Comment by mppf** [comment]
> I tend to think that if the formal's type can be copy-initialized from the actual argument's type, that in should be legal (I think this relates to a question I sent you about passing block arrays to DR formals recently?). 

We did discuss it a bit and I view it as a form of user-defined coercion. It comes at some cost because we would presumably be resolving `init=` functions to decide if candidates were applicable.

> And that if the formal's type can be assigned to the actual argument's type that out should be legal. And if both of these are true, that inout should be legal.

That would mean that we might need to try resolving `=` (or maybe `init=`) when deciding if a function with an `inout` of a particular type is a candidate, which I had hoped to avoid (when thinking about this problem apart from the `in` intent question). However if we decided to allow the `in` case then this is not much worse.

I think the work on split-init/copy-elision blurs between `=` and `init=` and so it would be better if deciding if a function is a candidates didn't depend on `=` vs `init=`. One way around that is to do all of the checks on `init=` and assume that `=` is compatible.

**Comment by mppf** [comment]
I've created #16576 to discuss the similar question for 'in' formals

**Comment by mppf** [comment]
Another way to put the question I am asking is - when it is not legal, what is the form of the error?

There are two possibilities here (for `inout` specifically):

1. Finding candidates works as if it were `in` (whatever we do there - see #16576). If there is an error finding a suitable `=` call to perform the write-back (or an error finding a suitable `init=` for split initialization through an `out` intent formal), then the compiler raises an error.
2. A function isn't a candidate if the suitable `=` (or `init=`) for the write-back is not found. If another suitable candidate is found, it can be used and no error will be raised.

I *think* @bradcray's last comment is advocating for 2.

**Comment by bradcray** [comment]
[This rambles a bit, but ends up somewhere reasonable-ish, I think]

After reading [Michael's earlier response](https://github.com/chapel-lang/chapel/issues/16554#issuecomment-705718758), I temporarily decided that using `init=` rather than `=` for the copy-out might make more sense (if we use `init=` for `in`): both for symmetry and because I was forgetting that in a split init world, `init=` can make sense for `out` (where, in writing my previous comment, I was thinking only `=` did, forgetting about split-init).

However, in writing the above paragraph, I decided I was wrong.  That if `inout` intent is used, the variable is already known to be initialized (otherwise, it wouldn't be valid to read for `in`), so we know we're not initializing it on the way out, but re-assigning it.  That takes me back to thinking that `=` should be used for the `out` part of `inout` (if anything is).

Yet, for a plain-old `out` intent, it seems it would sometimes need to use `init=` and sometimes `=` depending on whether the variable had already been initialized or not, which starts to seem complicated.  However, if we think of `out` as being like `return`, then perhaps it's not really much more complicated than what we already do today to process returns (do we use assignment, or split initialization?), simply at function resolution time rather than as an afterthought?

In a world with only `inout`, I'd be open to Michael's first possibility (only dispatch based on `in` and then error if the `out` part can't be resolved).  And arguably, I suppose this is most similar to how `return`s work ("We call the function and then if the thing being returned is of the wrong type for its context, we only complain then.").

On the other hand, if we need to have the compiler support determining how to do the write-back for `out` intents, I'm not sure option 2 is much harder/worse (?).

Or we could go full-throttle and say that even `out` arguments are never used in function disambiguation, such that even a case like:

```chapel
proc foo(out x: domain(1)) {
}

var i: int;
foo(i);
```

would result in a "can't assign `domain` to `int`" error rather than the "unresolved call to foo()" error that it does today.

I suppose I feel most strongly that `inout` should be like `in` and `out` combined; and less strongly whether `out` should be more like a return (not involved in choosing resolution candidates) or more like other arguments (where it would be involved).  It appears to behave more like the latter today, but that may still reflect a world before we equated them as strongly with returns as far as things like split initialization (?).

(Of course, returns actually do affect resolution, at least a bit, in that we choose between `ref` and non-`ref` overloads based on context).

So maybe the next step is to fire off an issue similar to #16576 but for `out` intents?

Here's a program that I think is useful when thinking about this:

```chapel
record R {
  var x: int = 0;
  proc init=(x: int) {
    writeln("In init=");
    this.x = x;
  }
}

proc =(ref r: R, x: int) {
  writeln("In assign");
  r.x = x;
}


proc foo_out(out x: int) {
  x = 45;
}

proc foo_ret(): int {
  return 33;
}

// These should split initialize                                                
var unR: R;
var unR2: R;

// These should not                                                             
var myR = new R(78);
var myR2 = new R(78);

// foo_out(unR);  // Doesn't resolve today due to arg mismatch                  
// foo_out(myR);  // Doesn't resolve today due to arg mismatch                  

unR2 = foo_ret();
myR2 = foo_ret();

writeln(unR);
writeln(unR2);
writeln(myR);
writeln(myR2);
```

**Comment by mppf** [comment]
> I suppose I feel most strongly that `inout` should be like `in` and `out` combined;

Not sure this really changes anything but I thought through something so I thought I'd post it.

Let us consider a concrete example based upon your earlier example. There is a record `R` that can be initialized / assigned from `int`.

``` chapel
record R {
  var x: int = 0;
}
proc R.init=(x: int) { this.x = x; }
proc =(ref r: R, x: int) { r.x = x; }
```

Now, in #16576 we are considering whether or not
``` chapel
proc fIn(in arg: R) { }
fIn(1);
```
should resolve (using `R.init=(int)` to convert from `1` to the `in arg:R` formal argument).

In #16582 we are considering whether or not
``` chapel
proc fOut(out arg: int) { }
var r: R;
fOut(r);
```
should resolve (using `R.init=(int)` to convert from `out arg: int` to the actual `r: R`).

Now, what about `inout` arguments? I'm not sure which type to put on the formal, since `in` used one type, and `out` used the other, so let's try both and see what makes sense:

``` chapel
proc fInout1(inout argR: R) { }
var x: int;
fInout1(x);
```

Can that work? We can initialize `argR` (as with `in`) from the `int` to produce an `R`. But then, we don't have a way to convert from an `R` back to an integer.

``` chapel
proc fInout2(inout argi: int) { }
var x: R;
fInout2(x);
```

Can that work? Nope, we don't have a way to initialize `argi` from an `R`.

So, it seems that for `inout` to work, the types involved have to support *both*:
1. a copy-initialization conversion from actual type to the formal type (e.g. `proc formalType.init=(actualType)`)
2. a `=` overload from the formal type back to the actual type

I've been arguing that only the 1st of these needs to be considered for candidate resolution (and a lack of the 2nd can be an error after the candidate is chosen).

Notably, in my original post
``` chapel
{
  var x: int(8);
  i(x); //  error: unresolved call 'i(int(8))'
}

proc i(inout arg: int) { }
```

should not work because there isn't an assignment overload supporting things like `myInt8 = myInt`.

**Comment by bradcray** [comment]
My takeaway from your example is that it seems fairly rare that an `inout` argument will be used to change between actual and formal types in any significant way since it requires being able to convert/assign in both directions and (my guess is) most types will tend to support going in one direction but not the other (e.g., `int` can become `bigint` through `init=` but `bigint` won't be assignable to `int` without an explicit downcast; and there's no place for an explicit downcast to be introduced here).  Perhaps there are other cases where a user record `R` would be implementing sufficiently `int`-like behavior that the assignment from `R` back to `int` would be supported, but I'm guessing it's relatively rare (e.g., maybe if I had a `paddedInt` record type that was responsible for some sort of memory alignment or padding around an integer?  Arguably the conversions we support between all `bool` widths is similar in this respect, and a case where an actual argument of `bool(8)` and a formal of type `bool` would make sense and work, even though it's not terribly interesting).

One conclusion from this might be "if it's that rare, let's just require the formal and actual types to match", but I'd still prefer for the rule to be that `inout` is like `in` and `out` combined (even if it rarely results in any differences from the "types must match" approach).  [noting that we could still decide that formal and actual types must match for `in` and `out` as well, though that's not my current preference].

**Comment by mppf** [comment]
> Perhaps there are other cases where a user record R would be implementing sufficiently int-like behavior that the assignment from R back to int would be supported, but I'm guessing it's relatively rare

Another example of that would be a record that wraps an integer / real in order to add some kind of unit; we have units for byte vs code point in the String module - and there are related techniques (with other requirements) for attaching "meters" or "feet" to types.

**Comment by mppf** [comment]
> I'd still prefer for the rule to be that inout is like in and out combined

I think we are heading towards having `in` arguments with different types only work if the implicit conversion is explicitly enabled between those types. At the same time, for the similar question for `out`, I think we need to either require the types to match - or ignore the `out` type when choosing candidates (and error if `init=` / `=` is not found). See also https://github.com/chapel-lang/chapel/issues/16582#issuecomment-759508533 .

What is interesting about that is that if we require `inout` to be a combination of the `in` and `out` behaviors, we get these behaviors:
 * `out` Option 1 - types must match - so `inout` types must match
 * `out` Option 2 - `out` type ignored - so the `inout` call is allowed if the `in` part is allowed (i.e. there is an implicit conversion from the actual type to the formal type) but it might result in an error if `=`/`init=` don't resolve
 * `out` Option 4 - implicit conversion from formal to actual - so the `inout` call would be allowed if there is implicit conversion from actual to the formal (for the `in` part) and from the formal to the actual (for the `out` part). These kinds of circular implicit conversions are something we might decide not to support (see #16729).

**Comment by mppf** [comment]
PR #17231 adjusts the implementation for `inout` to only consider the `in` part for whether a function is a candidate according to the choice of Option 2 for `out`. Note that the slice example from this issue does not run correctly though, due to a bug that is present in 1.23 and described in issue #17241.
