### ISSUE TITLE
Unexpected error message issued: 'Encountered corrupt string metadata'

### ISSUE THREAD

**Issue by tmacd8** [chapel-lang/chapel#16702]
# Summary of Problem
The following source code compiles but causes an unexpected runtime error during execution.

### Steps to Reproduce

**Source Code:**

```
module X {
 private use Sys;
 private use FileSystem;
 private use Random;
 private use Time;
 private use List;
 private use IO;
 private use SysCTypes;

 type str = string;
 config const a:int = -1;

 var MSG: str = "";

  // directory creation returns true or false.
 inline proc mdir(const ref dpath: str, const perms: int): bool {
   try { mkdir(dpath, perms); } catch { return false; }
   return true;
 }  // mdir

 proc make_dir() {
   var val: c_string;
   var st: c_int = sys_getenv("TMP", val);
   if st != 1 {
     st = sys_getenv("DOCUMENT_ROOT", val);
     if st == 1 { val = ".."; }
   }
   const tmp: str = if (st == 1) then val else "/tmp";
   const pth: str = tmp + "/loc";

   try {
     // need a TMP directory (default is /tmp)
     if (exists(tmp) || !mdir(tmp, S_IRWXU | S_IRWXG | S_IROTH | S_IXOTH)) &&
         !isDir(tmp) {
       if a < 0 {
         halt("Cannot create a tmp path: '", tmp, "'");
       } else {
         MSG += "| ERROR: Cannot create a tmp path: '" + tmp + "'";
         exit(0);
       }
     }
   } catch {
     if a < 0 {
       halt("Unknown error creating a dir path: '", pth, "'");
     } else {
       MSG += "| ERROR: Unknown error creating a dir path: '" + pth + "'";
       exit(0);
     }
   }
 }

 proc main() {
  make_dir();
 }
}
```

**Compile command:**
`chpl x.chpl`

**Execution command:**
`./x`
x.chpl:33: error: halt reached - Encountered corrupt string metadata

### Configuration Information

- Output of `chpl --version`:
chpl version 1.23.0

- Output of `$CHPL_HOME/util/printchplenv --anonymize`:
CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: gnu
CHPL_TARGET_ARCH: x86_64
CHPL_TARGET_CPU: native
CHPL_LOCALE_MODEL: flat
CHPL_COMM: none
CHPL_TASKS: qthreads
CHPL_LAUNCHER: none
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: cstdlib
CHPL_GMP: none
CHPL_HWLOC: hwloc
CHPL_REGEXP: re2
CHPL_LLVM: none
CHPL_AUX_FILESYS: none

- Back-end compiler and version, e.g. `gcc --version` or `clang --version`:
gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0

**Comment by e-kayrakli** [comment]
Thanks @tmacd8 for the bug report!

This bug is caused by the weirdness coming from c_string and how Chapel strings interact with them in the UTF-8 strings world. It was previously reported here: https://github.com/chapel-lang/chapel/issues/15775

Quick summary: I think we should deprecate c_string to Chapel string assignments rather than fixing it (although the fix is easy). So, in my view it is a bug that you are not seeing a compile time error message for the line:

```chapel
const tmp: str = if (st == 1) then val else "/tmp";
```

which should ideally be

```chapel
const tmp: str = if (st == 1) then val:string else "/tmp";
```

Where the variable with c_string type is explicitly cast to Chapel string. Making this change will make your code execute as expected.

---

A caveat unrelated to the bug here:

This code deals with paths, which can be non-utf-8 in some systems. So, using Chapel strings can reduce the portability of your code. In that case you can create a "special" Chapel string from a c_string by:

```chapel
var myChapelString: string = try! createStringWithNewBuffer(myCString, decodePolicy=escape);
```

This'll store any non-utf-8 sequence in the c_string's buffer in an escaped way. You can use such strings with Path and FileSystem functions, which will recognize those escaped sequences and unescape them for you under the covers.

See https://chapel-lang.org/docs/master/builtins/String.html#non-unicode-data-and-chapel-strings for more on this.

**Comment by e-kayrakli** [comment]
Note also that this is part of deprecating c_string type altogether: https://github.com/chapel-lang/chapel/issues/14215

**Comment by bradcray** [comment]
@tmacd8: For context, what led you to use `c_string` rather than `string` for your string-processing needs?

**Comment by e-kayrakli** [comment]
I think it is because of [`sys_getenv`](https://chapel-lang.org/docs/master/modules/standard/Sys.html#Sys.sys_getenv)

**Comment by tmacd8** [comment]
Yes, it seemed like sys_getenv required a c_string.

**Comment by bradcray** [comment]
Ah, OK thanks.  We should think about making the Sys module more Chapeltastic in its next review.
