### ISSUE TITLE
Should operators be treated like methods when defined at the same scope as the type?

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#16725]
We added support for searching the type definition point first to look for methods last release, enabling us to ensure that types obtained in scopes where the original definition point was not visible could still maintain basic functionality wherever they were used.

This issue is to discuss if operators should be treated the same way.

Here's a motivating code example:
```chapel
module One {
  class MyClass {
    var field: int;
  }

  proc +(a: MyClass, b: MyClass) {
    writeln("in One.+ for MyClass");
    var ret = new MyClass(a.field + b.field);
    return ret;
  }
}

module Two {
  // Obtained an instance of MyClass using a locally scoped use, and returned it
  proc blah() {
    use One;
    var fieldVal = 10;
    return new unmanaged MyClass(fieldVal);
  }
}

module User {
  use Two;

  proc main() {
    var x = blah(); // unmanaged
    var y = blah(); // unmanaged
    // use One;      // With this line, this code will compile and run.  Without it, it will fail to find the +
    var z = x + y;  // owned, for kicks
    delete x, y;
  }
}
```

Pros:
- operators defined at the same scope as the type are expected to be usable wherever the type is accessible.  Failing to use these operators can cause behavior the type author does not expect, which may cause unexpected bugs.

Cons:
- Operators are not (currently) defined as methods on a type.  What distinguishes them from functions that aren't operators but require that one of their arguments is of the type in question?
  - Counterpoint: the compiler is specifically set up to recognize certain operators and translate the syntactic sugar into calls to those functions.  That distinguishes them from ordinary functions.
- In the case of operators like `+`, they can take multiple types.  Should we arbitrarily choose one of these argument types to jump to?  Should we jump to both definition points?

**Comment by bradcray** [comment]
I'm not crazy about this approach because it feels too implicit / automatic to me.  As you note in the last bullet, it also raises questions for what happens to mixed-type operators like `proc +(x: MyClass, y: int)` and `proc +(x: int, y: MyClass)` or, worse, `proc +(x: MyClass, y: YourClass)` and `proc +(x: YourClass, y: MyClass)`.

In general, I tend to prefer to think of operators, in their current form, as being like normal standalone functions that benefit from special syntax.

I agree that there needs to be a way to associate operators with a type, I'm just not excited about this being the approach.

**Comment by lydia-duncan** [comment]
@mppf also had a couple of suggestions.  I'm thinking of spawning those into separate proposal issues and linking them here?

**Comment by mppf** [comment]
I wish the motivating example was using a record. Using `owned` adds implicit conversions into the mix which is a whole other can of worms.

I think having some strategy here is important because I think people will expect assignment overloads work with their type, no matter where they got it.

I know of these solutions to the problem:
 1. Implement (some?) operators as methods and then the visibility rule for methods applies (i.e. #16730 )
 2. Implement some way of marking non-method functions as associated with a type (and then such functions would be treated similarly to methods as far as their visibility is concerned).

For 2, I know of two sub-strategies:
2a. Use something along the lines of #14141 to indicate that a function has this property. E.g.
``` chapel
@attribute(type associated proc)
proc = ( ref lhs: R, rhs: R) { ... }
```

2b. Have some kind of block where the type author can put the functions with this property, E.g. 
``` chapel
record R {
  associated proc {
    proc = ( ref lhs: R, const ref rhs: R ) { ... }
  }
}
// or
R.associated proc {
  proc = ( ref lhs: R, const ref rhs: R ) { ... }
}
```

**Comment by lydia-duncan** [comment]
One slight hiccup with 3b is compiler generated operators/functions.  It seems like we wouldn't be able to put generated functions into a special block, though we would be able to mark them with an attribute when appropriate.  #10650 shows an example (though it seems to work today - that might implies that there's some leftover code linking operators and methods that I should remove if we follow route 3 rather than that there's something that would need to be added for route 1).

**Comment by bradcray** [comment]
> It seems like we wouldn't be able to put generated functions into a special block

Why not?  (not that I'm advocating for that approach, just trying to understand).

**Comment by lydia-duncan** [comment]
You're right, wouldn't is the wrong word.  It would just be more difficult.  We'll have to consider:
- is only one such block allowed per type?  Or multiple?
  - if multiple, should we allow them to be defined outside the type scope?  Outside the module where the type is defined?
    - What scope considerations are there for this, in terms of visibility of the symbols defined in the block?
- what happens if the user hasn't specified a block already?  What if they have?

The attribute solution doesn't have to worry about that logically, even if they may end up tracked similarly in the implementation.

**Comment by mppf** [comment]
It doesn't seem a big deal to me. The compiler can use a flag on the symbols internally. This can apply to compiler-generated functions or to functions identified in the special block.

What I do think is tricky about these proposals is that there is (presumably) at least one argument in the function with the type in question. In the `R.associated proc { }` syntax, this type is clearly identified. But what if we have an attribute or a flag by that point? In the event of say a `proc =` from one type to another, the compiler needs to know which type the function should be associated with. What occurs to me is that we could solve this problem by having the compiler use whichever argument has a declared type that is defined in this module.

**Comment by lydia-duncan** [comment]
> What occurs to me is that we could solve this problem by having the compiler use whichever argument has a declared type that is defined in this module.

That's an interesting idea, though I do worry that inferring the type or types it should be associated with would take control away from the user.

**Comment by lydia-duncan** [comment]
On #16732, Michael says:
> IMO the question of how to associate operators with types has two options: 1) a feature to "associate these functions with this type" or 2) making them methods. I think that the 1st here adds some complexity in that people will have to figure out how to use the new feature. But I think the 2nd adds complexity because if they are methods (and we use the receiver type as the type they are associated with) then we are going to need the "reverse" forms for mixed-type binary operators. (So that either type in a mixed-type case can define the operator). If we have the reverse forms, then function resolution will have to be adjusted to resolve operators in a special way that combines the forward and reverse candidates into one list and then chooses between them somehow. This seems worse, in terms of complexity and potential for confusion, than the approach 1) of adding a feature to associate some free functions with a type.

And also:
> I think that designs that use free functions and have a way to associate them with types (e.g. proc + continues not to be a method but could be associated with particular types) still allow a new library to "glue" together two other independently developed libraries (in which case the new functions would be associated with neither type). I think that's reasonable to allow for operators, =, and casts.

A question that occurs to me as a result of those thoughts: in these strategies for associating a type with an operator, do we want to enable associating that operator with multiple types at once?

**Comment by bradcray** [comment]
> in these strategies for associating a type with an operator, do we want to enable associating that operator with multiple types at once?

I'm inclined to say "no" for simplicity.

As mentioned on other active issues about operator syntax, my current preference is to support both type method operators a la Swift (to associate them with a type and get them imported when the type is, as with other methods) as well as standalone operator functions (which would have to be `use`d or `import`ed in order to get access to them, which would require the ability to name operators in a filtering clause on `import`s (and benefit from them for `use`s).

For the mixed-type operator case, I'm assuming there will either be a most appropriate type for it (e.g., `int + bigint` probably should be associated with `bigint`) or that it will be made standalone if not (e.g., `yourCustomType + hisCustomType` would be something I'd provide as a standalone operator in a utility module that knew about both types).

**Comment by lydia-duncan** [comment]
With the merge of #17103, this issue can now be closed
