### ISSUE TITLE
Should we distinguish `relPath`/`realPath` better?

### ISSUE THREAD

**Issue by e-kayrakli** [chapel-lang/chapel#16757]
The Path module has:

- `relPath`: returns the relative path from current directory or some other
             path.
- `realPath`: returns the canonical path from the path.

They follow python's ` os.path` counterparts in terms of behavior. In the spirit
of making the interface aligned with that, we can keep them as they are.
However, they are too close for comfort, and prone to typos that can create
hard-to-debug issues. 

That being said, I am not seeing any grievance in the python community regarding
those.

**Comment by bradcray** [comment]
I don't think it would've occurred to me to be worried about these until you said something.  Even once you did, it doesn't give me big concern, I think because the vowel sounds are so different when said out loud.  It also feels like a case where, if you typed the wrong thing, you'd become aware of it pretty quickly in most cases that mattered (?).  If we weren't defaulting to following Python's lead for this module, I'd be more open to renaming it, but it feels a little odd to deviate by only one routine name?

**Comment by e-kayrakli** [comment]
There doesn't seem to be much support for this proposal. I think we should keep them as-is: we follow python in the path module and there's no need to break away from it without a strong motivation.
