### ISSUE TITLE
Path.splitPath behavior

### ISSUE THREAD

**Issue by e-kayrakli** [chapel-lang/chapel#16752]
`Path.splitPath` returns a (`dirname`, `basename`) tuple. This is because the
Path module was designed based on python's `os.path` and this behavior is
identical to `os.path.split`.

However, this diverges from Chapel's `string.split`, where if we were to follow
that precedence, we would make `splitPath` separate on path separators.

- Are we OK with this behavior? (It may be a breaking change if we are not)
- Do we want a new iterator that yields parts of a path?

My first reaction was that we should change the behavior, but that was before
learning that this and the rest of the module was following the `os.path` precedence.
Now, I am OK with keeping it as-is, but it may be valuable to create an iterator
that yields parts of a path.

**Comment by lydia-duncan** [comment]
I am in favor of leaving it as it is and adding a new iterator to yield parts of the path

**Comment by vasslitvinov** [comment]
What Lydia said.

**Comment by bradcray** [comment]
In general, if a function returns two, and always two, things, I prefer it to return a tuple than be an iterator (similarly, if we knew that `string.split()` were going to return three things always, I'd have it return a three-tuple).  I view split()'s role as an iterator to be more related to it generating an unknown number of things than anything inherent to the nature of splitting things.

What would be the advantage of adding a second iterator method that yields the parts of the path?  It seems that I can iterate over the tuple, so I could write `for s in splitPath("/users/bradc/chapel/bin")`.  I suppose there's arguably a slight bit of overhead to create and then destroy the tuple, but it seems like it's probably not that much (and that this pattern isn't likely to show up in performance-oriented code anyway?)

**Comment by e-kayrakli** [comment]
> What would be the advantage of adding a second iterator method that yields the parts of the path? It seems that I can iterate over the tuple, so I could write for s in splitPath("/users/bradc/chapel/bin"). I suppose there's arguably a slight bit of overhead to create and then destroy the tuple, but it seems like it's probably not that much (and that this pattern isn't likely to show up in performance-oriented code anyway?)

My thinking was an iterator that yields parts based on the path separator, and not just dirname/basename.

This is not something I strongly support and it was mostly based on my initial reaction when I see "splitPath" in the Path module and not a valid use case I can think of. The behavior of that iterator can be similar to:

```chapel
var thePath = "/x/y/z/.././t";
for dir in absPath(thePath).split("/") do writeln(dir);   // yields "x", "y", "t"
```

**Comment by bradcray** [comment]
> My thinking was an iterator that yields parts based on the path separator, and not just dirname/basename.

Ah, I see, got it.  My first reaction was "wouldn't the user just use string split for this?", but from your response, I can see that if it defaulted to splitting on "/" rather than whitespace, that could be convenient (as well as the auto-normalization of the path, in the event that we thought that was the right behavior).

This is one of the few cases that makes me think "if we had a distinct `path` type separate from `string`, it would make sense for it to have a `split()` method which behaves differently from strings in this way.  But without a groundswell of other reasons to support a distinct path type, it feels like overkill to create a new type just for this reason.

Even with paths as strings, I wouldn't object to supporting such an iterator, though I think coming up with a name for it is the hard part (and, from a library stabilization perspective, not strictly required since it's not a breaking change if that's all we do here).

**Comment by e-kayrakli** [comment]
I don't see any supporters for changing the existing behavior of `splitPath`. So, I am considering `splitPath` stable in this regard. 

We can add an new iterator to yield the parts of a path (and not just split into two by dirname/basename), however, that's not based on any real use-case. And I think we should do that when we have a better motivation.
