### ISSUE TITLE
Should we rename `basename`/`dirname` in the Path module?

### ISSUE THREAD

**Issue by e-kayrakli** [chapel-lang/chapel#16764]
The Path module design was based on Python's `os.path`, which has `basename` and `dirname` functions that perform similarly to their POSIX counterparts, but differ in some cases. Our versions follow the python's approach and differ from POSIX versions, as well.

<details> <summary>Differences</summary>

```
$ python3
Python 3.8.5 (default, Jul 21 2020, 10:42:08)
[Clang 11.0.0 (clang-1100.0.33.17)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from os.path import dirname
>>> dirname("/foo/bar/")
'/foo/bar'
>>> dirname("/foo/bar")
'/foo'
>>>

~
$ dirname /foo/bar/
/foo

~
$ dirname /foo/bar
/foo
```
</details>

While transliterating the python implementation we chose to camelCase other function names, except for these two. This issue asks whether we should rename them to `baseName`/`dirName`.

Argument for change:
- They are different than POSIX versions, but sticking with all lowercase for these instead of camelCasing like other python-based functions might suggest that these are following the POSIX behavior.

Argument against change:
- "basename"/"dirname" are sufficiently compound words.

I am leaning towards change.

**Comment by vasslitvinov** [comment]
+1 for camelCase, for consistency.

**Comment by e-kayrakli** [comment]
@lydia-duncan @bradcray -- do you have any thoughts on this matter?

I am still for changing them to camelCase. I would be more strongly defending my arguments for that if we were writing this module from scratch today. The fact that this would be breaking on a not-so-obscure interface makes me think more about it.

**Comment by bradcray** [comment]
I'd probably leave them as-is out of laziness and because I don't think anyone has complained about them, but don't think I feel strongly about it if the preference is to change to camel-case.  If the POSIX question weren't in the mix, I'd probably use the current approach because the "sufficiently compound" argument holds for me.  I'd also be open to supporting both camelCase and alllower versions of the routines where one does the POSIX thing and one does the Python thing, but I think I remember there being strong negative reactions to that among people I trust when I suggested it at the meeting, and I feel inclined to defer to them.  I can't recall whether we discussed having an optional argument to indicate "posix vs. non" or whether it resulted in similar negative reactions.

**Comment by vasslitvinov** [comment]
If we don't take the pain to rename now, it will be a sore in the eye for years to come.

I am game for an optional argument. Which sounds like a future non-breaking change.

**Comment by lydia-duncan** [comment]
Not sure how I missed commenting on this the first time around, thanks for the ping!

I prefer the non-camel case version of these names.  I suspect at least part of the reason is due to being used to it for this particular set of names, as normally I would prefer camelCase.  My comfort with it stems from prior to working on Chapel, so it isn't a result of these particular functions being the way they are.  I think there's sufficient precedent in other languages to justify it

**Comment by vasslitvinov** [comment]
For my own use I am happy with the non-camel case. The reason I'd like to switch is so that the naming is consistent with Python. Especially given that the behavior is. Otherwise new users will need to remember that the naming is different from python ("for historical reasons"?) while the behavior is the same.

**Comment by bradcray** [comment]
> I'd like to switch is so that the naming is consistent with Python.

Just to make sure we're on the same page, Python uses [`basename`](https://docs.python.org/3/library/os.path.html#os.path.basename) and [`dirname`](https://docs.python.org/3/library/os.path.html#os.path.dirname), right?

(I think the "Python consistency" argument here is typically that we've converted most other Python Path library names to camelCase, so why didn't we convert these ones too?)

**Comment by vasslitvinov** [comment]
Oh right. I retract my argument, then.

I can live with treating basename/dirname as "sufficiently compound" to be all-lower.

**Comment by e-kayrakli** [comment]
The general consensus for this discussion was for no change. We don't see this as an open discussion any more.
