### ISSUE TITLE
should compilerError be included by default?

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#16807]
For https://github.com/Cray/chapel-private/issues/1215

Today, `compilerError`,`compilerWarning`, and `compilerAssert` are available by default (that is, you don't have to import/use a module to get them). Should these be included by default?

**Comment by bradcray** [comment]
I'm not crazy about their names, but like having them be available by default.  My sense is that they're similarly useful as halt/assert/exit-style routines and that their usage is sufficiently "spread out" in the code base that it would get annoying to have to `use` or `import` a module each time they were desired.

**Comment by mppf** [comment]
I think making them have better names would require them not to be included by default. E.g. it seems to me that `Compilation.error("msg")` is about as easy as `compilationError("msg")` but we would probably not want to have `error()` available by default as a function creating a compilation error.

**Comment by e-kayrakli** [comment]
From the user's perspective, they are significantly different than functions because they "execute" at compile time. So, with the way they operate, they are closer to statements than functions. This special situation calls for them to be included by default, IMO. Or at the very least, it would feel weirder to me if they are not included by default.

@bradcray -- is your grievance about their names because wordiness, or because of the fact that they don't capture something that they should?

**Comment by bradcray** [comment]
> From the user's perspective, they are significantly different than functions because they "execute" at compile time.  So, with the way they operate, they are closer to statements than functions.

I'm not convinced.  Chapel functions that return `param` or `type` values also execute at compile-time:

```chapel
proc +(param x: int, param y: int) param { ... }
```

even when invoked on non-param arguments:

```chapel
proc sizeOfSum(x, y) param { return numBytes(x+y); }
```

So to me, while the user has to distinguish between compile-time and execution-time errors, it's not that much of a stretch to support in this form, nor a distinction that would give a typical user significant pause.  Specifically, I keep imagining myself as a user writing cases like:

```chapel
if (x.eltType != y.eltType) then
  // I want a compile-time error here because that's preferable and I can
if (x.rank != y.rank) then
  // I want a compile-time error here because that's preferable and I can
if (x.indices != y.indices) then
  // I'd love to have a compile-time error here if I could, but I understand that I can't; so I'll fall back to an execution-time error instead
```

As a user, what I want is two flavors of error.  I'm thinking about when they execute, but apart from that, am not considering them so different from one another (just like I don't for `param`-`+` and execution-time `+`).

I also want to back away from characterizations in today's meeting (some of which I made) that this is somehow an advanced feature that most users might not understand or use much—because I think we've found them incredibly valuable in writing helpful library errors, and should encourage other library authors to use them too (I'm thinking of the HDF5 `halt()` that we made into a `compilerError()` the other day to resolve user issue #16587 in a way that was far more satisfying than the user proposed themself—compiler error over having to catch a thrown execution-time error). 

> @bradcray -- is your grievance about their names because wordiness, or because of the fact that they don't capture something that they should?

I think they're pretty good at describing what they do.  It's a mix of:
* "wordiness", or really "slightly longer than my preferred identifier name for something I use fairly commonly"
* a bit "seems unfortunately asymmetric with the execution-time cases and names"
* a bit "is 'compiler' really the right modifier to use here?"  Does that imply "at compile-time" as clearly as it could/should?

I don't recall whether we discussed it at the dawn of time, but `compError`, `compWarning`, `compAssert` address my first bullet pretty well (get under my identifier length pain threshold), though `comp` has the downside of being ambiguous between `compiler` and `computation`.

Lee's proposal of `staticError` is notable because we considered it when we introduced this, but intentionally avoided it because we were getting feedback from users that `static` is more compiler jargon than an intuitive word for this kind of thing for someone coming from an applied math/science background (our use of 'lvalue' in error messages being a case that's similarly haunted us).  As a compiler/language person, I know what `static` means, but I don't find it intuitive if I really think about it or have to explain it to a layperson.

I thought the notion of having an `assert()` that accepted a `param` expression and resulted in a compiler assertion was intriguing.  At the time I bought the arguments that it was too subtle to a reader or that a programmer might think they've written a compile-time check when they hadn't.  But thinking about it more, I'm less sure that's a concern—or if it is, it's one we've already got in spades given `if [param-expr]` and the `+` overload examples above.

To address the second bullet, I sometimes wonder whether we should have a `compileTime=true|false` argument with a single set of `assert()`, `error()`, `warning()` routines, but that feels too subtle / ugly / annoying (I'd want to use the argument name to make the boolean's purpose clear, and then I'm typing even more than today).  The other route would be to make things symmetrical by calling today's cases `executionAssert()`, `executionError()`, `executionWarning()`, but then I'd be unhappy about the identifier length in both cases.

I also wonder a little whether, in a future interpreted environment `compiler*` sends the right message (given that it's the interpreter that would presumably generate the error and arguably at "execution"/"interpretation" time).  I think it's arguably acceptable, but still wonder about it...

**Comment by mppf** [comment]
> I thought the notion of having an assert() that accepted a param expression and resulted in a compiler assertion was intriguing.

Somebody brought up this case:

``` chapel
if someRuntimeCondition() {
  assert(somethingEvaluatingToParamFalse());
}
```

The concern here is that people might be surprised that the assert is being run at compile time.

> is your grievance about their names because wordiness

FWIW I don't like the names either but it's more because I'm not sure the words are clear and make sense in a sentence. E.g. `compilerError` is not a verb, should it be `emitCompilationError` instead?

But anyway I'd like to suggest this issue discuss a bit more whether or not they should be included by default.

**Comment by bradcray** [comment]
> But anyway I'd like to suggest this issue discuss a bit more whether or not they should be included by default.

What's to discuss?—Engin and I agree that they should be!  :D

**Comment by mppf** [comment]
I think it's reasonable to expect library authors to be able to find a module containing these. I think they shouldn't be included by default - that way we can have a cleaner default namespace.

Other languages with this kind of feature seem to make it just its own statement kind. E.g. `#pragma error` or something.

**Comment by mppf** [comment]
I am coming around to the idea that these should be included by default because we want to encourage their use in libraries. I had been saying that having it not included by default would help with naming - but now I'm not so sure about that. If the module were `Compilation` if one can do `use Compilation` (or commonly does so) then `error` probably doesn't make sense as the name. And if we wanted to require people write `Compilation.error()` then `Compilation` would be a global type or something (not a module) and then it could still be included by default.

**Comment by mppf** [comment]
In a separate conversation, we concluded it is reasonable to include these by default.
