### ISSUE TITLE
Should it be possible to disable assert checking?

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#16810]
For https://github.com/Cray/chapel-private/issues/1215

Related to #12466.

Should asserts be always on? Or should it be possible to turn them off (possibly with `--fast` or with a separate command line flag)?

Typical practice in other programming languages is to provide some way to disable the assertion checks. C, D, Scala, and Python all disable asserts in some configuration (release for D, `-DNDEBUG` for C, `-O` for Python, `-Xdisable-assertions` for Scala).

Having these disabled with `--fast` (or some other means) will allow performance-minded programmers to feel happy using them in more cases and as a result makes them more useful.

**Comment by mppf** [comment]
I think it should be possible to disable the assertion checks and that `--fast` should do so.

**Comment by bradcray** [comment]
> Related to #12466.

How is this different than #12466?

**Comment by mppf** [comment]
#12466 asks for a new function and this one proposes changing the existing one.

**Comment by e-kayrakli** [comment]
It might worth considering that with "normal" means, disabling assert checking would still evaluate the argument to assert today. And this differs from C's macro-based assert.

```chapel
assert(myExpensiveCheckFunction());
```

wouldn't call `myExpensiveCheckFunction` in C, but it would in Chapel (at least if we add disabling in the way that I assume this issue is proposing).

Dropping that call too would probably mean making assert a statement rather than a function. And I don't know what I think about doing that personally. I am definitely not advocating for it.

**Comment by bradcray** [comment]
Ah, OK.  As mentioned there, I think we should have two flavors or modes of assert, one that's always-on, one that's disable-able.  I'm not sure what they should be called, though.

**Comment by mppf** [comment]
> Ah, OK. As mentioned there, I think we should have two flavors or modes of assert, one that's always-on, one that's disable-able. I'm not sure what they should be called, though.

I wonder if it would be sufficient to have a separate command line option to turn on/off assertion checks. It seems to me that doing assertion checking should be up to the person deploying an application rather than the one writing it. E.g. if we had both flavors (say, `debug_assert` and `release_assert` to do the two things), wouldn't individual developers gravitate to just one of them? I.e. - I'm a performance-minded programmer so I always use the one that disables with `--fast`. Or, I'm a safety-minded programmer so I always use the one that doesn't get disabled). In which case wouldn't it be just as good to have a flag?

**Comment by bradcray** [comment]
> It seems to me that doing assertion checking should be up to the person deploying an application rather than the one writing it. [...] wouldn't individual developers gravitate to just one of them?

I typically imagine the decision as being more of an author role where they might be weighing things like "This check is cheap / important / run once at program startup, and really bad stuff would happen if it weren't done, so let's always do it."  vs. "This check is expensive and/or in performance-critical code, so it's better to permit it to be disabled."

**Comment by mppf** [comment]
> I typically imagine the decision as being more of an author role where they might be weighing things like "This check is cheap / important / run once at program startup, and really bad stuff would happen if it weren't done, so let's always do it." vs. "This check is expensive and/or in performance-critical code, so it's better to permit it to be disabled."

I think that the counter-argument is that if it's a failure mode that can occur in "release" builds then it should have more focus on the error message and being able to handle the error. In particular it is not a good practice to halt / exit from a library and that's what these would effectively do; if a library can fail then it should be doing so by throwing an Error, right?

OTOH maybe an always-on assert is better than getting undefined behavior if something is seriously wrong; it is merely a better way for the program to crash than core dumping.

**Comment by bradcray** [comment]
> if a library can fail then it should be doing so by throwing an Error, right?

I think it depends on the library.  For a bulletproof, world-class library, I'd agree.  But I think it's reasonable to write libraries /  packages that are more slapdash and user-oriented as well.  Of course, this relies on a library author / community to define what is or is not appropriate for their library and then to hold themselves to that standard ("We will not call halt, we will not call halting asserts, we will not use the `!` operator, etc.").  Ideally, over time, we could create such guidelines and standards of "grown-upedness" of a piece of code and the compiler could help its authors adhere to such decisions.

> OTOH maybe an always-on assert is better than getting undefined behavior if something is seriously wrong; it is merely a better way for the program to crash than core dumping.

That statement resonates with me.

I think the bottom line for me is that I tend to hear from users that they'd like both cases (or that distinct users would like different cases), which is why I tend to think in terms of "two flavors of assert" (or one flavor with a flag).

**Comment by mppf** [comment]
> which is why I tend to think in terms of "two flavors of assert" (or one flavor with a flag).

I thought we were trying to decide between two flavors of assert (like Rust has) and one flavor with a flag (which arguably is what C has)?

**Comment by bradcray** [comment]
OK.  I interpreted your previous comment as being an argument for only having one flavor of assert (well, half of it, you seemed to be arguing from both sides).

**Comment by mppf** [comment]
> OK.  I interpreted your previous comment as being an argument for only having one flavor of assert (well, half of it, you seemed to be arguing from both sides).

Yep, I'm not really sure what to do so am in fact arguing both sides. At the moment I am leaning more towards the "fail fast is better than undefined behavior" argument than the "you shouldn't do that in release code" one. So at the moment I lean towards having two different asserts. I think this is connected a bit to the question of what postfix `!` does in release code compiled with `--fast` (#13603).

**Comment by mppf** [comment]
We had a separate discussion in which the conclusion was "Let's have multiple flavors of assert; one of which can be disabled with --fast and once which is not". I've created #18024 to discuss the details there. I'm closing this issue since we do plan to have a flavor of assert that can be disabled.
