### ISSUE TITLE
Should we move the module docs for internal types to the spec?

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#16814]
For https://github.com/Cray/chapel-private/issues/1215

On the sidebar in https://chapel-lang.org/docs/master/ we have "Built-in Types and Functions" (although we plan to rename this to "Standard Type APIs" in the near term).

Should we migrate these sections of documentation into the language specification?

Note that some of these have duplicate (and out of date) sections in the spec:
 https://chapel-lang.org/docs/master/builtins/ChapelRange.html
 https://chapel-lang.org/docs/master/language/spec/ranges.html#predefined-functions-on-ranges

We've historically had problems updating both of these so they can be in conflict.

One proposal is to move the generated module docs into the spec (now that they both are/generate RST this is not so hard). Should we do that? Or is there some better alternative?

**Comment by dlongnecke-cray** [comment]
My first reason for originally voting no was similar to @ronawho (and I say this at risk of misquoting) in that I like how with the current arrangement, the methods on built-in types are quickly and easily accessible.

I dislike the thought of having to scroll through a bunch of wordy, stuffy spec paragraphs before finally getting to the method docstrings that I need.

My second reason for originally voting no was because while the "type" -> "language spec section" mapping is often one-to-one, it is not always. I imagine `string` and `bytes` would both be crammed into the `Types` section. Do we put their APIs inline with their introduction? This kind of breaks up the flow of the spec in a weird way. Dump them at the end? Seems like a hyperlink and scroll situation...Both ways seem unappealing.

What about the `Atomics` API? Do we just throw it into  `Task Parallelism`? `Data Parallelism`? How about `Memory Consistency Model`? Unclear...

At this rate it looks like we may be cramming multiple APIs into a single section in order to maintain cohesiveness. Either that or we add more sections but break up the flow of the spec as a whole.

Or we create an appendix sort of listing with every single API, which is basically what we do today in `Built-in Types and Functions`, just in my opinion, a bit more esoteric and harder to find (if more formal, I guess?!).

I guess I personally don't consider `Built-in Types and Functions` to be any less formal just because it's not a subsection of `Language Spec`.

However I eventually voted yes because it seemed like the tides were against me, and I didn't want to waste time bothering to rename `Built-in Types and Functions` when I didn't like any of the choices...

**Comment by bradcray** [comment]
I'm in favor of doing this move because I think it's odd that there are essentially two doc sidebar entries for each of our major types, one in the spec and one in the "Type APIs" section (for lack of a better name).  I also consider many/most of these APIs to be part of the types' definitions in the language rather than part of a standard library, say (and those that aren't should get moved into libraries as part of their reviews... they should all be on our standard module review list), so believe that they deserve to be described within the language specification rather than distinctly from it.

With respect to David's concern about bloating spec chapters, I think the answer here is simply to introduce additional structure and hierarchy to the spec.  The current structure was very influenced by the LaTeX document, but in its online format, I don't see any reason we couldn't / wouldn't use additional hierarchy and structure (reading the spec's current TOC for example is a major bummer of a laundry list).  For example, rather than having "task parallelism" be a single chapter that talks about creating tasks and sync variables and atomics, it could become a section of the spec with subsections for each of those topics.  Similarly, rather than cramming APIs into the same webpage as their types, we could break the "textual description" sections vs. the "API sections" into separate webpages listed on the sidebar (or potentially even sub-sections that are listed on the sidebar if there's a mechanism for doing that within sphinx... I can't recall).

**Comment by mppf** [comment]
Following the discussion yesterday there is consensus to do this, so I'm closing this issue which asks that question. We still have to actually do it. I've created issue #18027 to track that part.
