### ISSUE TITLE
`a+b` should be a valid statement

### ISSUE THREAD

**Issue by e-kayrakli** [chapel-lang/chapel#16841]
```chapel
var a = 10;
a;
```

parses fine, however

```chapel
var a = 10, b = 10;
a+b;
```

does not.

I don't think there is any real reason why `a+b;` shouldn't be interpreted as a statement. And I think that the parser should be adjusted to handle that.

**Comment by bradcray** [comment]
I feel like "line" is the wrong term here since it isn't related to lines at all, but rather statements.

Not to defend the current behavior, but maybe to rationalize it a bit:  Given that Chapel has paren-less functions, statement `a;` could be a function call and we wouldn't be able to tell at parse-time, so we need to support it.  In addition, historically, this was a way to block on a synchronization variable (though we're talking about removing that).  In contrast, one might argue that `a+b;` is never a useful statement (assuming that `+` is side-effect free and doesn't modify its arguments... which isn't guaranteed currently, but is the convention and true for built-in operators).

**Comment by e-kayrakli** [comment]
https://github.com/chapel-lang/chapel/issues/16842 seems like it is the opposite of this proposal. Because, if we were to disallow non-const `+` arguments (and assuming that it doesn't change the global state), `a+b;` has no impact on whatsoever.

I'd still argue that it should be compilable. Should the following be a compiler error?

```
proc foo() {
  return 5;
} 

foo();
```

warning, maybe, but I don't think this should be an error. I see this and the case in the OP identical. If the call (either `a+b` or `foo`) doesn't have any side effects and the results are not captured anywhere, we should compile it and ideally eliminate them as dead code.

**Comment by bradcray** [comment]
> If the call (either a+b or foo) doesn't have any side effects and the results are not captured anywhere, we should compile it and ideally eliminate them as dead code.

And just to verify something that I think you said in #16842:  You don't have a problem with (i.e., wouldn't have the compiler prevent) `+` overloads that contain global side-effects, is that right?

If that's the case, I agree we could/should support this.  If it's not (and we were to adopt #16842) then I don't see the point of expending effort to support richer ways of writing no-ops.

The inconsistency with #16482 that I was sensing is that if we were to believe that there is a "proper" definition of `+` and that the compiler should enforce it, I would expect that being side-effect free would be part of that proper definition.  And if that were the case, `a+b` is necessarily a no-op and we can know that syntactically.  Whereas `foo();` may or may not be and we can't determine that syntactically, only by looking at the definition of `foo()` after parse-time.

**Comment by mppf** [comment]
I think that the status quo is fine here. I think this is related to whether or not something like `a == b` is a valid statement on its own. I don't think it should be but I don't have a very strong specific case somebody would trip up on.

One sketchy example is this, suppose a user accidentally wrote `;` instead of `=`:
``` chapel
a ; a + b;
// oops I meant
a = a + b;
```

But my overall reaction is that I don't think the language needs `a+b` to be a valid statement (since AFAIK nobody has asked for it until now, and you're not asking because you want to use it but more out of completeness).

**Comment by mppf** [comment]
> I think that the status quo is fine here. I think this is related to whether or not something like `a == b` is a valid statement on its own. I don't think it should be but I don't have a very strong specific case somebody would trip up on.


Oh, how about this. A user trying to write an assignment accidentally included a second `=`:

``` chapel
a == b;
// oops, I meant
a = b;
```

**Comment by e-kayrakli** [comment]
> And just to verify something that I think you said in #16842: You don't have a problem with (i.e., wouldn't have the compiler prevent) + overloads that contain global side-effects, is that right?

That's right. I think there has been some good arguments about record tracking etc, which can be done if the operator is allowed to modify the global state. It definitely feels more awkward to have it modify the state of one or both of the operands.

> But my overall reaction is that I don't think the language needs a+b to be a valid statement (since AFAIK nobody has asked for it until now, and you're not asking because you want to use it but more out of completeness).

I think that's reasonable. I don't think anybody would get hurt by this, if we address #16842 by making `+` a "pure" operator. Otherwise, as it stands today (if we allow non-const arguments to operators) I'd argue more strongly that this is a bug that we need to fix. Though, I am still aware that no real use case has bumped into it yet.

> Oh, how about this. A user trying to write an assignment accidentally included a second =:

I think this is a good argument for catching these as errors. If we were to keep these cases as errors, it would be ideal to give a better error message.

**Comment by bradcray** [comment]
> as it stands today (if we allow non-const arguments to operators) I'd argue more strongly that this is a bug that we need to fix.

I'd consider it more like an unimplemented feature or a not-intended-but-we-re-open-to-it feature.  I'm most inclined to stick with the status quo and relax it later if/when someone requested it without it being a breaking change given that I don't see any big motivation for adding support for it (and agree with Michael that supporting `a == b;` as a standalone statement seems like it opens the potential confusion for `=` and `==` back up which we attempted to close by not supporting `=` at the expression level.

Re-reading the characterization in the OP, if the treatment of the two cases really bothered someone, I'd be much more inclined to make the `a;` case a compiler error or warning than to permit `a+b;` (where the main observation is that `a;` can't be a syntax error because it might be a call to a paren-less function; but it could generate a warning or error in `checkResolved.cpp` once we realize that it's a pointless variable reference).  There's a little bit of entanglement here with forcing split initialization, but I think if we adopted the `var a: t = init;` syntax that we've typed about, the need for `a;` to force default initialization would be lessened?

**Comment by mppf** [comment]
>  There's a little bit of entanglement here with forcing split initialization, but I think if we adopted the var a: t = init; syntax that we've typed about, the need for a; to force default initialization would be lessened?

I agree we shouldn't keep `a;` just for split-initialization - if we want to get rid of it we will have a different way to handle forcing default initialization (and we want that anyway).

**Comment by e-kayrakli** [comment]
A somewhat related case that I bumped into today (which I think is more obvious that we should support?):

```chapel
class C {}

param flag = true;

new C();    // compiles fine
if flag then new C() else new C();    // syntax error
var c = if flag then new C() else new C();    // compiles fine
```

**Comment by bradcray** [comment]
I'd agree we should probably be more consistent about `new C()` and conditional expressions that happen to generate `new C()` expressions.  I'm not sure which decision we should make about them, though.  Is there value in creating something and dropping it on the floor?  (where, at times at least, we've given the compiler permission to reclaim the object immediately after its creation since it's stored in a compiler-generated temporary)

**Comment by mppf** [comment]
If we make `new C();` no longer a valid statement maybe we don't have to fix the memory leaks it causes :)

**Comment by e-kayrakli** [comment]
> If we make new C(); no longer a valid statement maybe we don't have to fix the memory leaks it causes :)
(Actually I can't remember if we already fixed those).

I have a fix in the works :)

**Comment by bradcray** [comment]
Reminding myself of the conversation to-date, I'd be more inclined to make `new C()` an illegal standalone statement than to permit conditional expressions to be standalone statements.

**Comment by bradcray** [comment]
@e-kayrakli : Asking the question in a different way:  Are there cases that use a standalone `new C();` in a test in compelling ways?

**Comment by e-kayrakli** [comment]
There were only two tests that were bumping into the memleak with `new C`, and neither was realistic tests.

**Comment by bradcray** [comment]
Every time I look at this issue, I think "No, let's not do that."  I like the notes that Michael adds around about https://github.com/chapel-lang/chapel/issues/16841#issuecomment-742528323 which are definitely part of why we don't treat `=` or `op=` as a general expression nor `==` as a legal statement.  Generally, I like not having the grammar support or encourage no-op statements.  We could argue that `+` could be defined in such a way that it was not a no-op (say, it took one or both of its arguments by reference and modified them), but one of the main arguments against operator overloading (in general) is that it can be abused, and to me, this starts to become abusive—I don't know that I'd prohibit it, but I wouldn't change the language grammar over it.  So basically, I'm proposing we close this as "not part of our intention for the language at present" and we can keep referring to it and commenting on it as a closed issue just like we do today as an open issue.  If/when we get a really compelling case for enabling it, we can do that then.  (Engin, this is your cue to argue for why it should stay open).

One thing I want to ask Michael is whether he thinks we should try to come up with the "force initialization" replacement for `a;` before 2.0 in order to avoid committing to supporting `a;` forever (i.e., should it be on our "2.0 language concerns" list?

**Comment by e-kayrakli** [comment]
> So basically, I'm proposing we close this as "not part of our intention for the language at present" and we can keep referring to it and commenting on it as a closed issue just like we do today as an open issue. If/when we get a really compelling case for enabling it, we can do that then. (Engin, this is your cue to argue for why it should stay open).

I am fine with closing. I don't think I have anything compelling enough to keep this an open issue.

**Comment by mppf** [comment]
> One thing I want to ask Michael is whether he thinks we should try to come up with the "force initialization" replacement for `a;` before 2.0 in order to avoid committing to supporting `a;` forever (i.e., should it be on our "2.0 language concerns" list?

I think we have historically supporting `a;` because, for a sync variable, that did something. I think that if we wanted to not support `a;` we should think about where to draw the line here -- what about `a[i];` ?

IMO, `a;` has a clear enough interpretation & I'm not aware of a similar case to confusion between `=` and `==` that argues for removing it. Did you have such a case in mind?

If you are worried about it, I would suggest we consider making some of these full-statement-expressions unstable for now, since they are arguably a corner case of the language that people won't run into very much.

**Comment by bradcray** [comment]
> what about a[i]; ?

We can't make this a syntax error since it could be a procedure call to a single-argument procedure named `a`.  [Above](https://github.com/chapel-lang/chapel/issues/16841#issuecomment-742120490), I argued that `a;` could similarly be a call to a paren-less procedure call, though it could potentially be argued that since paren-less procedure calls should be field-like, perhaps it shouldn't be able to be expressed as a standalone statement like this.

Anyway, I'm not intrinsically opposed to the status quo here.  I was mostly reacting to your comment https://github.com/chapel-lang/chapel/issues/16841#issuecomment-742762477 which suggested to me you were more in favor of getting rid of it and thinking of the implications for Chapel 2.0.

**Comment by bradcray** [comment]
OK, thanks, I'm good with that as well.
