### ISSUE TITLE
How should forwarding interact with listing a type in a use/import limitation clause?

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#16858]
This is similar to #16852.  Note that due to the implementation of `owned` and `shared`, there are likely choices that must be made to allow them to work as implemented.

Say we have a module structure as follows, where a type is defined that contains a forwarded field of another type in one module, and a tertiary method on the forwarded field type is defined in another module:
```chapel
module definesType {
  record Container {
    forwarding var x: OtherType;
  }
  record OtherType {
     var foo: int;
  }
}
module definesTertiary {
  use definesType;

  proc OtherType.tertiaryMethod() {
    writeln("In forwarded tertiary method");
  }
}
```

Under what use and import scenarios should tertiaryMethod be available to instances of Container?

Case 1a:
Should listing the Container type in an only list or import list on the module enable it to be found?  E.g.
```chapel
use definesType;
use definesTertiary only Container; // Should this bring in tertiaryMethod for instances of Container?

var x = new Container(new OtherType(2));
x.tertiaryMethod(); // Should this resolve?
```

Case 1b:
Should listing the Container type in an except list on the module prevent it from being found?  E.g.
```chapel
use definesClass;
use definesTertiary except Container; // Should this prevent calls to tertiaryMethod for instances of Container?

var x = new Container(new OtherType(2));
x.tertiaryMethod(); // Should this resolve?
```

Case 2a:
Should listing the OtherType type in an only list or import list on the module enable it to be found?  E.g.
```chapel
use definesClass;
use definesTertiary only OtherType; // Should this bring in tertiaryMethod for instances of Container?

var x = new Container(new OtherType(2));
x.tertiaryMethod(); // Should this resolve?
```

Case 2b:
Should listing the OtherType type in an except list on the module prevent it from being found?  E.g.
```chapel
use definesClass;
use definesTertiary except OtherType; // Should this prevent calls to tertiaryMethod for instances of Container?

var x = new Container(new OtherType(2));
x.tertiaryMethod(); // Should this resolve?
```

Based on discussion in the inheritance thread, my guess is that the result will similarly be 1a no 1b yes 2a yes 2b no.

I also believe that because `owned`, etc., is implemented using forwarding, we probably have to follow this pattern in order for classes to work as described

**Comment by lydia-duncan** [comment]
@bradcray, @mppf and @vasslitvinov - I am similarly interested in your thoughts here (and have another issue in the pipe for generic instantiations)

**Comment by bradcray** [comment]
My quick intuition would be that `forwarding` should only be able to call methods that are visible from the `forwarding` statement itself and from the scope where the type was declared (which I think means "its primary and secondary methods").  I think this would mean that tertiaryMethod() could only be called on a `Container` in your example if the `definesType` module could see it via a `use` or `import`.

**Comment by lydia-duncan** [comment]
Would making the forwarded field generic instead of concrete (e.g. `forwarding var x;`) change your answer?

**Comment by bradcray** [comment]
No because I think the "from the scope where the type was declared" clause would cause that to still work out fine.  E.g., for our `_array` class which forwards to its generic `_instance` field, only the primary/secondary methods for the dsi class used to instantiate that field would be available (unless `ChapelArray.chpl` happened to contain `use SomeModuleDefiningTertiaryMethodsOnBlockArrays`, say, in which case those methods would also be available).

**Comment by lydia-duncan** [comment]
I'm more worried about `_owned`'s use of forwarding, tbh, since I think following that strategy would effectively lock classes out of having tertiary methods at all

**Comment by bradcray** [comment]
Hmm, that's an interesting case (and I definitely didn't think through the implications of its mention at the bottom of your OP).  My first thought that was `owned` is built into the language, so we should do whatever it takes to make it work.  But I suppose the real question is whether users should be able to create their own similar completely generic record wrappers and be able to use tertiary methods or not, where presumably it'd be nice for them to.  So let me think harder than my quick intuition (though it may  not be until Monday).

**Comment by lydia-duncan** [comment]
> Hmm, that's an interesting case (and I definitely didn't think through the implications of its mention at the bottom of your OP).

I definitely meant to be more explicit about it there, but got distracted by the other parts of the issue, so that's at least partially on me as well.

> My first thought that was `owned` is built into the language, so we should do whatever it takes to make it work. But I suppose the real question is whether users should be able to create their own similar completely generic record wrappers and be able to use tertiary methods or not, where presumably it'd be nice for them to.

Yeah, that's certainly on the table.  I think I'd need more advice/assistance on how to adjust it if we choose to follow that path.

> So let me think harder than my quick intuition (though it may not be until Monday).

Yeah, sounds good!  I think Michael is gone by now anyways, so no rush.

**Comment by mppf** [comment]
I would expect:
1a doesn't resolve
1b does resolve
2a does resolve
2b doesn't resolve

FYI I don't understand "yes" / "no" answers to these questions because the the way e.g. 1b is written asks the question 3 different ways (2 are in the code listing) and yes/no don't mean the same thing in all 3.

The reason I would answer as above is that I view method forwarding as something that is requested in the record/class but actually occurs at the *call site* (i.e. `x.tertiaryMethod()`). (The reason I view it this way has to do with how it is implemented).

But I think it's important that `forwarding` work this way. The reason has to do with one of the reasons we added the feature. If the `Container` class knows what type it is supposed to "forward" to, then it presumably also knows which methods will be forwarded, and writing forwarding functions manually is possible but inconvenient. In contrast, if `Container` is meant to be generic, it does not know what types it will be used with, and it doesn't know which methods are available on those types. As a result, the `forwarding` feature needs to use information from the calling context in order to be able to find these methods. (Now, we could think of this as a POI feature, but I just think of it as "forwarding is processed at the call site").

Now, for `owned` and `shared` specifically, the uses of `forwarding` in these should no longer be necessary, because we have implicit conversion available to the contained `borrowed` type. (That does not mean they definitely are not necessary - I have not checked that lately with testing).

However another case we can consider from the standard library is if somebody makes a custom DSI implementation for a new array type. `_array` forwards to their class types. But `_array` itself will never have direct visibility to it (because `_array` is in the standard module and the DSI implementation is in user code). Just from looking at `_array` in the standard library when compiling it, we won't know which methods exist on the custom class type. Like I said, we could consider such visibility to be coming from POI, or just inherent to `forwarding`, but I think the behavior in the above cases is the same either way.

**Comment by lydia-duncan** [comment]
> If the `Container` class knows what type it is supposed to "forward" to, then it presumably also knows which methods will be forwarded, and writing forwarding functions manually is possible but inconvenient. In contrast, if `Container` is meant to be generic, it does not know what types it will be used with, and it doesn't know which methods are available on those types. As a result, the `forwarding` feature needs to use information from the calling context in order to be able to find these methods.

This definitely resonates with me.

One thing I'm wondering about is how we view the interface it presents and how much of that should be reflected in which type the method is tied to in the limitation clause.  It seems like the Container type's dependence on the forwarded type is to some extent an implementation detail, which could argue for specifying the Container type - but also, looking at the module being used, it seems more natural to name the types that are specifically mentioned within it.  Anyways, that's more a musing than specifically impacting the decision we should make

**Comment by lydia-duncan** [comment]
I've opened #16976, which implements the decisions discussed here.  Closing so I don't forget to close this later.
