### ISSUE TITLE
How should generic instantiations interact with listing a type in a use/import limitation clause?

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#16859]
This is similar to #16852 and #16858.

Say we have a module structure as follows, where a generic type is defined in one module:
```chapel
module definesType {
  record GenericRec {
    param p: int;
  }
}
```

Now, it seems apparent to me that if you have a tertiary method defined on the generic type, it should be impacted by listing the type in the limitation clause of a use or import statement, e.g.
```chapel
module definesTertiary {
  use definesType;

  proc GenericRec.tertiaryMethod() {
     writeln("In tertiary method");
  }
}

module User {
  use definesType;
  use definesTertiary only GenericRec;

  proc main() {
    var x = new GenericRec(2);
    x.tertiaryMethod();
  }
}
```

But the situation seems more cloudy when you get to tertiary methods defined on instantiations of the type:

```chapel
module definesTertiary {
  use definesType;

  proc (GenericRec(2)).tertiaryMethod() {
     writeln("In tertiary method");
  }
}

module User {
  use definesType;
  use definesTertiary only GenericRec;      // Should this enable tertiaryMethod to be found?
  use definesTertiary only GenericRec(2); // Should we have to do this instead?  Should we be able to do this in addition?

  proc main() {
    var x = new GenericRec(2);
    x.tertiaryMethod();
  }
}
```
Note that today, you can't include parentheses in a limitation clause - it would require a parser change to do so (but that doesn't mean we can't choose to do it).

If we were to allow the second of the two choices (specifying an instantiated type in a limitation clause), what should happen when the tertiary method itself is on the generic type but the limitation clause specifies an instantiation?
```chapel
module definesTertiary {
  use definesType;

  proc GenericRec.tertiaryMethod() {
     writeln("In tertiary method");
  }
}

module User {
  use definesType;
  use definesTertiary only GenericRec(2);

  proc main() {
    var x = new GenericRec(2);
    x.tertiaryMethod(); // Should this work?
  }
}
```

**Comment by lydia-duncan** [comment]
@bradcray @mppf and @vasslitvinov - I think this is the last one, unless those issues spawn other considerations

**Comment by mppf** [comment]
> `module definesTertiary {` ... `proc (GenericRec(2)).tertiaryMethod()`

> `  use definesTertiary only GenericRec;      // Should this enable tertiaryMethod to be found?`

yes

> `  use definesTertiary only GenericRec(2); // Should we have to do this instead?  Should we be able to do this in addition?`

no

While I think it would be O.K. to make either choice here (because we are making here a choice about what `only` / `except` mean for generic types), I don't think we should bother to make `only` / `except` so precise as to possibly apply only to certain instantiated types.

I suppose we could view a similar question in an `import` context.

Should I be able to `import definesType.GenericRec(4)` ? It seems to me, "no". My rationale for that is that it is quite a large can of worms and I don't see a use case for it. My experience with the language is that it's quite rare to even care about methods on specific instantiations. So I wouldn't complicate the `use` / `import` story with it. In doing so, I don't think we'd be preventing people from writing important patterns.

**Comment by bradcray** [comment]
> I don't think we should bother to make only / except so precise as to possibly apply only to certain instantiated types

I agree.  I view the filtering options as being about naming symbols rather than general expressions or specific type instantiations.

**Comment by lydia-duncan** [comment]
I've opened #16976, which implements the decisions discussed here.  Closing so I don't forget to close this later.
