### ISSUE TITLE
Efficient sorting of arrays over sparse domains

### ISSUE THREAD

**Issue by ahysing** [chapel-lang/chapel#16888]
Concider this a feature request.

One suggests to sort only the sparse indecies when sorting a sparce domain. This will result in siginificantly better performance. **Implicitly Represented Values** for sparse arrays are equal, and can all be all be left in the same position when sorting. If implemented this way sort should run in ** N x log(N) ** time where **N** is the number of explicit array values with Implicitly Represented Values are left out.

### Summary of Problem

[sort](https://chapel-lang.org/docs/modules/packages/Sort.html?highlight=sort#Sort.sort) over an array with with 2**40 possible indices and two actual values. This should finish in less than a second.
When running this use case through chapel the resulting code spends hours  or days to finish.

### Steps to Reproduce

```chapel
use Sort;

proc main() {
    var start : int(64) = 0;
    var end : int(64) = 1 << 40;
    var ALL : domain(1) = {start..end};
    var D : sparse subdomain(ALL);
    D.add(0);
    D.add(10);
    var values : [D] real;
    values.IRV = 5.0;
    values[0] = 0.0;
    values[10] = 10.0;
    sort(values);
}
```

**Comment by bradcray** [comment]
Hi @ahysing —

Sorry for the delayed response due to winter break.  If I'm understanding, for a 2D sparse array with an IRV of 0.0, like:

```
0.0 5.6 0.0
1.2 0.0 0.0
0.0 0.0 3.4
```

you'd want the result to be:

```
0.0 1.2 0.0
3.4 0.0 0.0
0.0 0.0 5.6
```

(where, implicit in this result is that the nonzeroes are stored in row-major order).  Is that correct?

If so, my inclination here would be to not support `sort()` on sparse arrays by default; but then to give users the ability to get a handle on the dense array/buffer of non-IRV values (if the array's representation has one) and to call sort() on that.  This has the benefit of getting the behavior you want without suggesting that the logical array is sorted.  It would also avoid sticky questions about what to do when trying to sort a distributed sparse array.

> When running this use case through chapel the resulting code spends hours or days to finish.

I'm actually surprised that this compiles and runs at all.  I dialed the problem size down:

```chapel
use Sort;

proc main() {
    var start : int(64) = 0;
    var end : int(64) = 15;
    var ALL : domain(1) = {start..end};
    var D : sparse subdomain(ALL);
    D.add(0);
    D.add(10);
    var values : [D] real;
    values.IRV = 5.0;
    values[0] = 0.0;
    values[10] = 10.0;
    writeln(values);
    sort(values);
    writeln(values);
}
```

and found that it doesn't actually:

```bash
testit.chpl:15: error: halt reached - attempting to assign a 'zero' value in a sparse array: (11)
```

I think that what should happen here is that the `sort()` routine has errors when called on array types that it doesn't support.  Tagging @mppf for his thoughts as a principal author of that module.

**Comment by mppf** [comment]
I think we should make `sort` on a sparse array be a compilation error for now. (Also for associative arrays).

I agree in principle that one could sort a sparse array. Also, note that `sort` only can sort 1-D structures today.

Regarding the idea of exposing the dense buffers for the sparse array - I'm not sure if exposing arrays of elements is general enough as a feature and general enough in terms of allowing different sparse representations.

**Comment by bradcray** [comment]
> I think we should make sort on a sparse array be a compilation error for now. (Also for associative arrays).

OK, I'll put this together if it's as easy as I expect.

**Comment by bradcray** [comment]
Implemented the error message in #16896.

**Comment by bradcray** [comment]
I've merged #16896 which generates an error message when trying to apply the current `sort()` routine to a sparse array.

I'm wondering what we should do with this issue, particularly since based on the discussion in #16889, my sense is that @ahysing will be taking a different approach and not require this capability (?).  We could convert it to a general "Chapel's Sort library should support sparse arrays" feature request, but I'm skeptical that that's deeply meaningful and if nobody is currently wanting it, would just as soon close this issue to avoid generating implied work for ourselves that nobody may care about.

@ahysing / @mppf: Thoughts?

**Comment by ahysing** [comment]
I agree with you Brad.
Even thoough it is possible to specify what should happen when sorting a sparse arrays I can not see the real benefit, or use case, for this functionality. Spend your development efforts elsewhere.

**Comment by bradcray** [comment]
Great, thanks @ahysing.  I'll close this issue for now and when we have pressing use cases for sorting sparse arrays, we can revisit it then.
