### ISSUE TITLE
Compilation of a single line 'hello world' program taking too long.

### ISSUE THREAD

**Issue by namitshah** [chapel-lang/chapel#16894]
I installed Chapel today and have been compiling and executing simple programs in order to understand the language better.
Compilation of even a single line 'Hello World' program, however, is turning out to be a painfully long process for me (taking 15+ seconds).

Is this behavior normal?
No errors that I know of popped up during the set-up process.

Thanks for looking into this vague and possibly dumb issue.

**Comment by e-kayrakli** [comment]
Hi @namitshah -- This behavior is "expected". Last few releases have focused on adding new language features that inevitably slowed down the compiler. However, it is our hope that we will get more chance to focus on cutting down the compilation time in the near future. In all likelihood, it would be a process that would span multiple releases.

We track our nightly compiler performance. [This](https://chapel-lang.org/perf/chapcs/?startdate=2015/09/10&enddate=2020/12/21&graphs=compilationtime) may be the best summary of where we are today, and where we have been historically.

FWIW, on darwin with quickstart configuration, I am getting 16 seconds on `test/release/examples/hello.chpl` under regular load.

**Comment by bradcray** [comment]
Just to provide some context for why this is the state of the compiler today, I would ascribe it to three main things:

* the compiler architecture:  When the Chapel project started, our goal was to design and develop the language as quickly as possible to prove its value and be able to continue working on improving it.  To that end, we created a compiler architecture that was reasonably flexible, but also reasonably expensive.  That's something we need to revisit.
* the fact that much of Chapel is implemented within Chapel such that even a program as small as "hello world" ends up compiling thousands (maybe tens of thousands?) of lines of code.  We currently don't do a very good job of either saying "this program doesn't use these features, so we don't need to spend time compiling them" nor "these features can be compiled once and re-used for each subsequent compilation," either of which would help.  To get a sense of how much code we're talking about, try compiling with `--print-module-files` or `--savec [directory name]` to see how many .chpl files are parsed or how much code is generated.  Or use `--print-passes` to see how much of the time is spent in compiling the generated code (the final stage or two).
* the fact that compilation time hasn't been a priority for the project.  Historically, we've been focused primarily on creating a language that improves productivity for distributed memory parallel programming and have been able to rationalize our slow compile times by all the other nice benefits a user gets from the language (i.e., "Would you rather be doing this in C++ and MPI?").  But as Chapel matures, this is becoming more and more of a pain point.

I also wanted to point to issue https://github.com/chapel-lang/chapel/issues/8627 which is one of our few public facing issues on this topic, though we've had a number of discussions internally about how to improve things.  And to say that we're cautiously optimistic that this will be a focus area for the project in 2021.

I'm going to close this issue since I think https://github.com/chapel-lang/chapel/issues/8627 subsumes it and hopefully we've addressed your questions even if we haven't improved the compilation time for hello world yet (we can continue discussing it here or in another forum if you'd like, though...  I don't mean to curtail the conversation, just trying to avoid having duplicate issues that might get orphaned over time).

**Comment by bradcray** [comment]
BTW, I wasn't going to check my timings since yours seem to agree, but using the homebrew installation of 'chpl' on my Mac, I see compile times of 6.4 seconds without doing anything special to quiesce the machine.  Only on my development branch, which has a bunch of debugging support enabled, do I see timings more like 14-15 seconds.

@namitshah: I'm guessing you're probably not using a debug version of Chapel?  Are you compiling from a local disk or one that's mounted over NFS or the like?

**Comment by namitshah** [comment]
@bradclay,
Thanks for addressing this.
I have installed Chapel 1.23 (not in debug mode) on my Linux Mint system and am compiling the programs from my local disk.
The installation process also took a long amount of time, and as you and @e-kayrakli explained, this must be because of the current state of the compiler and the focus on bringing new features to it.

Anyway, I have got myself relatively comfortable with the structure of the language and would love to contribute to it.

Thanks again.

**Comment by bradcray** [comment]
@namitshah — Thanks for the details on your system.  Your compile times still seem a little slow for a non-developer/debug build, but aren't completely unexpected.

I was thinking more about my comment about prioritization above after posting it last night, and came up with this other way of thinking about it:  What I think people want from a productive parallel programming language is:

* good, productive features
* excellent performance
* fast compiles

If I had to prioritize only one of these things for Chapel, I'd have to pick "good, productive features" because there are already plenty of ways to get excellent performance in non-productive ways.  If I had to pick two, I'd pick the first two because people don't want to do scalable parallel programming that doesn't result in good performance.  And only once I got the first two into a shape that I felt Chapel had a future would I focus on the third.  That's basically the short version of how we got here and why we now think we can start to focus on faster compilation.

Needless to say, we'd be happy to have you contribute to the project.
