### ISSUE TITLE
channel.readf does not handle EOF for a regexp format string

### ISSUE THREAD

**Issue by npadmana** [chapel-lang/chapel#16891]
### Summary of Problem
When reading from a channel using `readf` and a regex format string, `readf` throws a `BadFormatError` on reaching EOF.

### Steps to Reproduce

The code below demonstrates this - the `useRegexp` switch uses a regular expression and fails. Not setting runs as expected.

**Source Code:**

```chapel
use IO;
use IO.FormattedIO;

config const useRegexp=false;

var ff=openreader("test.txt");
var got=true;
var ss : string;
while (got) {
  if useRegexp {
    got = ff.readf("%/(.+)/\n",ss);
  } else {
    got = ff.readf("%s\n",ss);
  }
  if (got) then writeln(ss);
}
```

Also consider a test file `test.txt` (has 3 lines)
```
hello
chpl
world
```

**Compile command:**
`chpl test.chpl`

**Execution command:**
```
$ ./test 
hello
chpl
world
$ ./test --useRegexp
hello
chpl
world
uncaught BadFormatError: bad format: no match (in channel.readf(fmt:string, ...) with path "test.txt" offset 17)
  test.chpl:11: thrown here
  test.chpl:11: uncaught here
```

### Configuration Information
```
chpl version 1.22.0
CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: gnu *
CHPL_TARGET_ARCH: x86_64
CHPL_TARGET_CPU: native *
CHPL_LOCALE_MODEL: flat
CHPL_COMM: none *
CHPL_TASKS: qthreads *
CHPL_LAUNCHER: none
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: cstdlib
CHPL_GMP: gmp
CHPL_HWLOC: hwloc
CHPL_REGEXP: re2
CHPL_LLVM: system *
CHPL_AUX_FILESYS: none
```

**Comment by bradcray** [comment]
@npadmana : Can you let us know whether this is a blocker for you, an annoyance, or something that you found but have worked around and are just letting us know about as a good citizen?  Thanks!

**Comment by npadmana** [comment]
@bradcray - not a blocker and there is an easy workaround (do the regexp matching after reading in the data). Just wanted to capture it.

**Comment by mppf** [comment]
Hi @npadmana - thanks for the bug report.

First, FYI if you just want to read 1 line at a time we have a function for that - 
[readline](https://chapel-lang.org/docs/master/modules/standard/IO.html#IO.channel.readline). (You might have figured out that `readln` reads just one word -- see #14107 if you want to discuss that element).

I think there is a bug here but I don't think it's quite what the issue describes.

The first question is how/why `%s\n` is working. As described in
[docs for %s](https://chapel-lang.org/docs/master/modules/standard/IO/FormattedIO.html#string-and-bytes-conversions), 
`%s` reads until whitespace. That means that it consumes one word and stops at the newline at the end of the line. Then the `\n` in your format string matches that newline ([it could also match non-newline spaces before the newline](https://chapel-lang.org/docs/master/modules/standard/IO/FormattedIO.html#note-about-whitespace) ). So it is successful. If you had more than one word on your line, as with the below file:

```
hello
chpl
world
many words on this line 
```

then we get an error like this

```
hello
chpl
world
uncaught BadFormatError: bad format: encountered non-whitespace (in channel.readf(fmt:string, ...) with path "test.txt" offset 17)
  $CHPL_HOME/modules/standard/IO.chpl:2187: thrown here
  program.chpl:13: uncaught here
```

because the `\n` is unable to find a newline (it consumes the ` ` after `many` but then stops on the `w`). (I'm sure this error could be improved).

Now with this knowledge about why it worked, why doesn't the regexp work? It is matching any character (including newline) and then looking for a newline afterwards. (It is looking for a newline after reading the entire file). I created this modified version of your program to address that:

```
use IO;
use IO.FormattedIO;

config const useRegexp=false;

var ff=openreader("test.txt");
var got=true;
var ss : string;
while (got) {
  if useRegexp {
    got = ff.readf("""%/([^\n]+)\n/""",ss);
  } else {
    got = ff.readf("%s\n",ss);
  }
  if (got) then writeln(ss);
}
```

Note that the triple-quoted strings disable the `\` escaping which makes sense for regexps because they have their own escaping language. (I.e. the escapes will be processed only when compiling the regexp rather than processing them twice). Probably doesn't matter if you are only working with `\n` though.

With this program and the multi-word `test.txt` I showed above, it produces this output when run with `--useRegexp`:

```
hello
chpl
world
many words on this line 
uncaught BadFormatError: bad format: no match (in channel.readf(fmt:string, ...) with path "test.txt" offset 42)
  $CHPL_HOME/modules/standard/IO.chpl:2187: thrown here
  nn.chpl:11: uncaught here
```

Now this part is a bug. The `readf` call should just return `false` instead of throwing, since we got to EOF and there was no other error. PR #16902 will fix that and the new output with `--useRegexp` is:

```
hello
chpl
world
many words on this line 
```

**Comment by npadmana** [comment]
Thanks, @mppf. Yes, this was a simplified version -- if I was just looping through lines, I would have just used `channel.lines()`, or `readline`. I agree that the error here is that `readf` was throwing instead of just returning `false` (even if my example ended up obscuring this somewhat).

However, I'm a little confused now about the behavior of `(.+)`. According to the documentation for re2 and the chapel docs, `.` by default should not match a newline, unless the `s` flag is set. So why is it matching newlines here?

From the Chapel docs --
```
s            let «.» match «\n» (default false)
```
