### ISSUE TITLE
Support for operators in forwarding only/except lists, and in imports and only/except lists for use statements

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#17003]
When forwarding a type that has an operator method, it seems obvious that users would want a way to explicitly opt in or out of forwarding operator methods defined on the type.  For instance,

```chapel
record Container {
  var x: OtherType;

  forwarding var only <; // or `forwarding var except +`
}

record OtherType {
  var y: int;
}
proc type OtherType.+(lhs: OtherType, rhs: OtherType) {
  return new OtherType(lhs.y + rhs.y);
}

proc type OtherType.<(lhs: OtherType, rhs: OtherType) {
  return lhs.y < rhs.y;
}

```

It seems reasonable to also add the support to use/import statements, since the only/except lists are similar to those used with forwarding.

Note that someone coming from Rust or Python might think `import M.*;` would mean "import everything from M", so it would be good to generate a warning for this case (that's potentially suppressible with a flag) along the lines of "Note that 'import M.*;' requests 'operator *' to be imported from module M in Chapel; if you intended to import all symbols from 'M', please use 'use M;' instead" or potentially only allow operators to be listed in the curly bracket import form, e.g.

```chapel
import M.{*};
```

**Comment by lydia-duncan** [comment]
One thing that occurred to me recently that could pose some problems: `except` lists that exclude all symbols in the module are currently implemented using `*` because we couldn't list operators in `except` and `only` lists.  What should happen with `*` when we enable operators as proposed in this issue?

Options I'm thinking of currently (open to addition options as well):
- Stop supporting `except *;` to mean "just enable qualified access for this module"
  - Potentially find a replacement symbol?
- `except *;` means "just enable qualified access for this module", `except <...>, *, <...>` and other combinations of `*` with other symbols means exclude `*` operator overloads in addition to the other symbols
- Can't explicitly exclude `*` via an `except` list

**Comment by bradcray** [comment]
I don't think I understood your point at first, but now think I do:  I think it's that it would be ambiguous whether `*` would represent "the name of an operator" vs. "the wildcard character"?  I.e., does:

```chapel
use M except *;
```

mean:

* bring in all symbols other than the `*` operator?
* bring in no symbols?

I'd be inclined to stop supporting `except *;` in its current form and interpret `*` as the operator (which would suggest deprecating it soon).

**Comment by lydia-duncan** [comment]
Yeah, that's exactly what I meant.  So `use Mod only;` would be the only way for use statements to enable just qualified access?  That doesn't seem like a bad thing to me.  I'll run it by the rest of the team before doing so.  Would we want `except *;` to just not be possible for a release cycle to make sure folks get the deprecation warning?  Or would switching the meaning and giving a warning be sufficient?

**Comment by bradcray** [comment]
> So use Mod only; would be the only way for use statements to enable just qualified access?

That's my thinking.  OR `import Mod;`

> Would we want except *; to just not be possible for a release cycle to make sure folks get the deprecation warning?

That would probably be the best thing to do, though I'd love for someone to convince me that it's not necessary...

**Comment by bradcray** [comment]
> Note that someone coming from Rust or Python might think import M.*; would mean "import everything from M", so it would be good to generate a warning for this case (that's potentially suppressible with a flag) along the lines of "Note that 'import M.*;' requests 'operator *' to be imported from module M in Chapel; if you intended to import all symbols from 'M', please use 'use M;' instead" or potentially only allow operators to be listed in the curly bracket import form, e.g.
> 
> import M.{*};

@lydia-duncan: Since mailing you earlier this week, it's been pointed out to me that requiring `import M.{*};` doesn't help for Rust programmers because in Rust, this is supported as a wildcard pattern as well.  My current thinking on this is that if we see an import that only imports `*` whether using curly brackets or not, we generate the warning to help people avoid confusion if they think it is a wildcard.  My assumption here is that (a) most people won't be importing operators at all, (b) those that do probably won't only be importing the single operator `*`.  We would not generate the warning if they're importing `*` along with other symbols.

That said, I also increasingly think we could probably also get away without the warning because the most likely thing to happen is for the user to say "Chapel, import **everything** for me!"  followed by either "I'm sorry, there is no `*` operator in that module to import" or "[user tries to use some of **everything** but it doesn't resolve; finds a SO Q&A saying why `import M.*;` didn't bring anything other than `*` and explaining the potential for confusion] ...oh, okay."  I.e., it's not exactly a dangerous misunderstanding to have.

Perhaps the bigger concern is:  If we decide to add a wildcard capability for the `import` statement someday, how would we express that?  But given that I'm fairly certain we've just eliminated the single case in which `*` meant wildcard in Chapel (and a fairly restricted / lame / roundabout one at that—"except everything!"), perhaps we just come up with our own way of saying this when that time comes.

**Comment by BryantLam** [comment]
I would advocate for a more special syntax form for two reasons:

* My opinion is that `*` on a use/import line to most people is a wildcard, not an operator. Other than `use M except *`, Chapel doesn't support use/import wildcard, but we can try to prevent human error due to pre-existing usage in other languages (though Rust and Python implement operators not as symbols but as traits or special methods) while leaving the door open to implement the wildcard.

* Importing or excluding operators is not expected to be a common activity.

My **_prototypical_** thoughts on syntax would be something like:
```chapel
import M.*; // or M.{*} // (1)
//       ^ wildcard
import N.operator {*} // or N.operator {+, -, *, /, <...>} // (2)
//                 ^ operator*
//       ~~~~~~~~ operator keyword required
import X.{M.*, N.operator{+, -, *, /}} // (3)
import Y.{M.*, N.operator+, L.operator*, ...} // (4)
```

(1) future-proofs for wildcarding

(2) requires operator keyword. This also opens up the possibility for IDEs to colorize the items in the list associated to `operator` differently than the module items being targeted. Something like:
* `<yellow>import <white>X.{M.*, N.<yellow>operator{+, -, *, /}<white>}`

(3) composition of (1) and (2)

(4) alternative syntax for (2) that (I don't like as much, but) generally seems fine since it's obvious with the `operator` keyword indicating that it's the multiplication operator. `operator*` or `operator{*}` could be misinterpreted/confused with wildcard ("give me all the operators via wildcard") but that interpretation can be compiler-warned or intuitively ruled out when it's not just the `*` symbol but other operator symbols are there too.

**Comment by bradcray** [comment]
I'm... not a big fan.  This seems pretty off-puttingly verbose/C++-like compared to typical Chapel style, and introduces an asymmetry for operators that I'm not fond of.  I.e., if I've got:

```chapel
module M {
  proc foo() { ... }
  iter bar() { ... }
  operator +() { ... }
}
```

it seems unfortunate that I'd need to say:

```chapel
import M.{foo, bar, operator+);
```

rather than simply:

```chapel
import M.{foo, bar, +};
```

That is, that operators would need to be treated specially/differently relative to procedures, iterators, methods.  For the highlighting point, it seems to me that operator symbols are pretty trivial to color directly within a syntax highlighter without needing an `operator` keyword to cue off of.

That's what makes me say that if/when we want wildcard matching, we should come up with some other way of saying it.  Spitballing while fixing dinner, I came up with:

```chapel
import M...;
import M._;
import M.*!;
import M.?;
import M.=>;
...
```

Or, if the main case that warrants a wildcard is re-exporting, maybe we support:

```chapel
reexport M;
```

and don't provide a way to bring `M.*` into the current scope (though it seems like you had a second case as well Bryant, that I don't think I captured in my notes for which maybe this wouldn't be appropriate).

**Comment by BryantLam** [comment]
> and introduces an asymmetry for operators that I'm not fond of
> ...
> `import M.{foo, bar, +};`

This is a valid point. I was thinking of `proc` (free functions or methods) being the "normal way" as I don't typically write iterators and haven't had the need to import one before.

> For the highlighting point, it seems to me that operator symbols are pretty trivial to color directly within a syntax highlighter without needing an operator keyword to cue off of.

The symbols are easy to highlight, but `*` is less trivial to do so if it can behaviorally be either wildcard or operator on the same line. The `operator` keyword was to distinguish (and as a secondary benefit, could be visually highlighted differently as I highlighted `M.*` white and `N.operator{*}` yellow).

> That's what makes me say that if/when we want wildcard matching, we should come up with some other way of saying it.

I'll keep stewing on ideas as those alternative wildcard symbol choices aren't that appealing to me.

My word of caution would be:
1. there is prior art for `*` as wildcard in other languages: Rust, Python, Java, Haskell, ...
2. use/import have support for implementing a module hierarchy via files, and files glob on wildcards, so choosing a different syntax is (weakly) breaking that analogy (for better or for worse)
3. importing operators isn't expected to be the common interpretation if wildcard imports are ever implemented

> if the main case that warrants a wildcard is re-exporting, maybe we support:
> 
> ```chapel
> reexport M;
> ```

IMO, wildcard imports are more likely to come from application users importing a subcomponent of a large module. [(Google search on Rust codes in GitHub.)](https://www.google.com/search?q=site%3Agithub.com+filetype%3Ars+%22use%22+%22%3A%3A*%22)

**Comment by bradcray** [comment]
> The symbols are easy to highlight, but * is less trivial to do so if it can behaviorally be either wildcard or operator on the same line. 

Sure, but the whole point of this thread / Lydia's recent change is to deprecate our single current interpretation of `*` as wildcard which arguably restores us to a simpler highlighting world and no need to distinguish between the two cases.  (That said, I'm also not a huge fan of highlighters that use dozens of colors to indicate every little thing because I find it more overwhelming than useful ("oh, this is teal rather than navy, so I should interpret that to mean it's a symbol from a standard rather than user module"), so am probably not the target audience for coloring wildcard `*` differently than operator `*` in the first place).

> there is prior art for * as wildcard in other languages: Rust, Python, Java, Haskell, ...

Sure, and on my filesystem as well, but if we're dissuading people from using wildcards most of the time because they're generally not considered a best practice (modulo the two use cases you mentioned this week which it might be helpful to have you summarize using Chapel syntax here so that we've got them in front of us during this discussion—could you do that?) then it feels like a reasonable thing to look for alternate reasons to express those patterns so that users won't just reach for `*` out of laziness / bad habits ("listing all the things I want to import specifically is too hard, so I'll just use `*` instead").

> use/import have support for implementing a module hierarchy via files, and files glob on wildcards, so choosing a different syntax is (weakly) breaking that analogy (for better or for worse)

Recall that Chapel uses the `include ` keyword to import modules based on file hierarchies, not `import`, and that it doesn't name filenames (currently) in its `include ` commands (though I've advocated for extending it to support that, but put off that debate for now due to lack of support so far).  So for this case it seems that we could extend `include ` to support filenames and to support `*` within those filenames without adding `*` as a wildcard to import.

> I'll keep stewing on ideas as those alternative wildcard symbol choices aren't that appealing to me.

Let me rationalize some of them:

* `import M...;` : the elipses visually indicate "you know... whatever M happens to contain, don't ask me to name it all"
* `import M._;` : `_` in Chapel usually represents an "I don't care" option and is not a legal identifier.  So this could be interpreted as "I don't really care to say what I want to import from `M`."
* `import M.?;` : Most import statements are very specific about what they're importing.  Any sort of wildcard-based import is inherently not saying and not sure of what is being imported, so the `?` indicates this uncertainty.  It's somewhat similar to using `?` in a type specifier to say "I don't have any idea what the param/type fields will be, e.g. `range(?)`, and don't even want to list each of them separately).
* `import M.*!;`: Chapel discourages people from importing everything from a module using a wildcard, so `import M.*!;` is a way of asserting "No, I *really* mean that I want to import everything!"
* `import M.=>;` : At this point I was just looking for other symbols we currently lex that are not operators and looked like they related to importing or bringing something in

**Comment by lydia-duncan** [comment]
> That said, I also increasingly think we could probably also get away without the warning because the most likely thing to happen is for the user to say "Chapel, import **everything** for me!" followed by either "I'm sorry, there is no `*` operator in that module to import" or "[user tries to use some of **everything** but it doesn't resolve; finds a SO Q&A saying why `import M.*;` didn't bring anything other than `*` and explaining the potential for confusion] ...oh, okay." I.e., it's not exactly a dangerous misunderstanding to have.

It also sort of feels like establishing a bad precedent to warn about things that are common in other languages but aren't in Chapel.  With `use M except *;` removed, as you said there's no use of `*` as a wildcard in the language.  May this is just a case of "Chapel is a different language"?

**Comment by BryantLam** [comment]
> With `use M except *;` removed, as you said there's no use of `*` as a wildcard in the language. May this is just a case of "Chapel is a different language"?

Right. My motivation has been to (in priority order):

1. Lessen the on-ramping mental burden of programmers from other languages. It is not uncommon to work between three or more languages in the same project. This mental context switching is arguably mitigated in most cases because people don't generally implement operators that often, but they sometimes do and it will happen a non-trivial number of times.

2. Possibly allow a feature request for `*` as wildcard. Not supported today. Not asking for it now or ever. But if eventually supported, it just seems like an unnecessary source of human error for what seems like a choice between syntactic purity of an uncommon use case vs. de facto practicality from other languages.

And on that note, **if `*` as mult is the way forward, that's okay with me.** I do care, but also don't care about this not-even-a-feature-request to push for reserving `*` as wildcard since Brad has suggested other candidates like `*!`-as-wildcard that are at least grep'able and reasonably understood once learned.

**Comment by bradcray** [comment]
> and gets silent, seemingly no-op, behavior.

Given the brief exploration in https://github.com/chapel-lang/chapel/issues/18267#issuecomment-910460634, I wouldn't expect this to give a no-op behavior once `*` is accepted as a symbol in import/use filtering lists.  Rather, I'd expect it to give an error, as `bar` does.

@BryantLam : I'd like to ask you to file a feature request issue requesting some means of doing `import M.[everything];` (without tying it to `*` per se).  Specifically, I believe you've said (offline) that you have at least two use cases in which you think it's principled to import everything and preferable to using `use`.  So I think it would be valuable to capture those cases clearly so that if/when we take up the wildcard feature request (which I suspect others will ask for over time), we've got those cases and conversation around them captured.  Is that something you could do?  (alternatively, I could file it on your behalf, but would need you to re-cap the motivating cases for me).
