### ISSUE TITLE
Unbounded ranges vs. bounded ranges with max bounds

### ISSUE THREAD

**Issue by vasslitvinov** [chapel-lang/chapel#17084]
If I have an unbounded range, should it behave the same way as a bounded range with maximum bounds?
* for integer index types?
* for enum or bool index types?

For example: &nbsp; // related: #13717
```chpl
var r1 = ..;
var r2 = min(int)..max(int);
writeln(r1 == r2);  // writes "false"
```

More interestingly, how about ranges over booleans or enums?
Is the current behavior here the right one?
```chpl
var r1 = false .. true;   // bounded
var r2 = false .. ;       // boundedLow
writeln(r1 == r2);           // prints "false"
for rr in r2 do writeln(rr); // prints "true" infinitely
```

Reference: the language spec [here](https://chapel-lang.org/docs/master/language/spec/ranges.html#range-concepts) and later in the definition of `BoundedRangeType` specifies that the unbounded end of the range is infinity.  This was written before ranges on enums/bools, however, and does not apply to those. Even for ranges over integers, does it really make sense to differentiate between the infinity and the maximum value of the index type, given that we are dealing with computers and not abstract math?

**Comment by Yash1256** [comment]
@vasslitvinov Sir Please correct me if I am wrong anywhere as I am new to Chapel and would love to contribute in your Organisation for GSOC.

> If I have an unbounded range, should it behave the same way as a bounded range with maximum bounds?

As per my understanding we can treat above the same way as mentioned because as for the unbounded one we can't set infinity as a limit so for that we can use the maximum value of the particular type as the upper bound for it for the Integer ones.
And for the bool and enum types if they are bounded low or high we can either take the max/min of that type to be the upper/lower bound respectively or throw the error to the user for providing invalid range.

> does it really make sense to differentiate between the infinity and the maximum value of the index type, given that we are dealing with computers and not abstract math?

No I think it dose not make sense to differentiate them.

**Comment by bradcray** [comment]
I believe that if a `uint(8)` range with the value `4..` is used to slice a `uint(64)` range or a `bigint` range, it should not be capped at `max(uint(8))`, which is what I believe would happen if we adopted the notion of making unbounded ranges equivalent to bounded with max values.

**Comment by vasslitvinov** [comment]
This is a good point. However this consideration does not apply to enums which do not have the multitude of representations (unless we have sub-enums??) so we could potentially have a different rule.

In any case, we need to define the following - for boolean and enum ranges:

* what is the index set of not-fully-bounded ranges ex. `false ..` 
  and `var r: range(bool, boundedNone)`
* based on the above, ensure correct implementation of `(false..) == (false..true)` 
  and `r == (false..true)`
* what should be the behavior of `for false.. do writeln();` 
  and `for r do writeln();`

**Comment by bradcray** [comment]
> what should be the behavior of for false.. do writeln();

I think it would be attractive to have (serial) iterators over partially bounded bool/enum ranges complain if they fall off the end of the legal values (we could potentially do this for unbounded integer ranges as well, though it's hard for int(64) and uint(64) without adding overhead, I think).

> and for r do writeln();

I don't think we ever support iteration over fully unbounded ranges do we?

> what is the index set of not-fully-bounded ranges ex. false ..
> and var r: range(bool, boundedNone)

I'd still probably think of the bounds as being infinities, conceptually.  I'm not sure the best way to describe that in the spec, though, without introducing the notion of intIdxType, which I'm still not excited about...

> so we could potentially have a different rule.

"different rule" sounds like something to avoid if possible.  :)

From a language stability perspective, we could simply outlaw unbounded bool ranges, which probably won't cause anyone strife.  Partially bounded enum ranges seem slightly more useful, though...  But we could still temporarily make them illegal if they weren't implemented well today and we didn't want to commit to figuring them out.

**Comment by mppf** [comment]
Another example (from #6160) is this:

``` chapel
var a:int(8) = 126;
for i in (a..) {
  writeln(i);
}
```

Which runs an infinite loop for me, today.

Is it reasonable for this to be an infinite loop that repeats values? If it were to match "max bounds" as the OP proposed, it would just print out 126 and 127.

> I think it would be attractive to have (serial) iterators over partially bounded bool/enum ranges complain if they fall off the end of the legal values (we could potentially do this for unbounded integer ranges as well, though it's hard for int(64) and uint(64) without adding overhead, I think).

Right but that wouldn't help the above case.

**Comment by bradcray** [comment]
I'd also be open to having serial iterators over int ranges complain if they fell off the end, if we can do it without adding overhead.  E.g., I could imagine setting the high bound of the loop that they go to max(idxType) and then halt after that loop.  Seems like this would still be problematic for unbounded int/uint (64-bit) values, though...  (and, actually, maybe int(8) ranges assuming the internal index is also an int(8)?  Maybe for those cases we could set the max to max(idxType)-1 and halt if we reach max(idxType).

Oh, so, what about writing it (conceptually) as:

```chapel
var hi = max(idxType)-stride;
for i in lo..hi do
  yield i;
yield (i+stride);
halt("Iteration over unbounded range fell off the end");
```

I still don't think that unbounded ranges should be interpreted as equivalent to maximal ranges in general though...

**Comment by vasslitvinov** [comment]
One option is to have the "fall off the end" check be guarded `if boundsChecks`.

> I still don't think that unbounded ranges should be interpreted as equivalent to maximal ranges in general though.

My reasoning at the moment:

* Start out by defining the "represented sequence" (spec terminology) for an unbounded range. If the range is over `bool` or `enum`, then the represented sequence has natural starting/ending point(s) if they are not specified by the range explicitly. For example, for `false..` , `..true` , or a `range(bool, bounds=none)`, the represented sequence is (false, true).

* For integers, ex. `(1:int(8))..` -- we could define it as 1..127 or as 1..+∞. The former is more consistent with the implementation, i.e., iteration over `(1:int(8))..` will never hit 128. It is also more consistent with enums/bools. The latter is what the spec says today.

* Then, uphold the principle that range equality is semantic, i.e., two ranges are `==` when they define the same sequence of integers. Which gives us, for example, that `(1:int(8)).. == (1:int(8)..(127:int(8))`

* My open question: what about two ranges with the same sequence of ints, just of different types? Ex. `(1:int(8))..(1:int(8)) == (1:int(32))..(1:int(32))` ?

**Comment by bradcray** [comment]
I'm open to interpreting the enum ranges this way, and the bool ranges for consistency (even though it seems hard to imagine a user ever using it or being unhappy that it wasn't interpreted this way), but not the integer ranges for the reason [given above](https://github.com/chapel-lang/chapel/issues/17084#issuecomment-773497780).

> One option is to have the "fall off the end" check be guarded if boundsChecks.

I don't see any real benefit to that since there's no overhead saved.

**Comment by vasslitvinov** [comment]
For iterating over fewer-than-64-bit open ranges, we could play a trick. Add bits to the index "under the hood," narrowing it before passing it into the loop body. This will allow us to check the fall-off condition without duplicating the loop body.

**Comment by ghbrown** [comment]
> I believe that if a `uint(8)` range with the value `4..` is used to slice a `uint(64)` range or a `bigint` range, it should not be capped at `max(uint(8))`, which is what I believe would happen if we adopted the notion of making unbounded ranges equivalent to bounded with max values.

In my opinion, capping at the max of the type and so slicing only some reduced range of a structure with bigger type seems logical (at least in this case, but maybe it makes less sense and causes bigger issues elsewhere?).
If such a change was implemented perhaps
```chapel
for i in (0..) {
  writeln(big_int_range[i]);
}
```
would need to become
```chapel
for i in (0:bigint..) {
  writeln(big_int_range[i]);
}
```
since I assume `0..` types to int(64) (or at least not bigint)? What it lacks in simplicity I think it makes up for in predictability.

If this isn't as well liked by others I still think overflow checks would be nice.

Would it be possible for somebody to clear up what currently happens when a small unbounded range is used to slice a structure with larger type? I feel my opinion on this should be more better informed before I decide one way or the other.
I tried to see myself with
```chapel
var a = 0..255;
for i in zip(0:int(8)..) {
  writeln(a[i]);
}
```
but got
```
range_for.chpl:23: error: unresolved access of 'range(int(64),bounded,false)' by '[int(8)]'
```

**Comment by bradcray** [comment]
> Would it be possible for somebody to clear up what currently happens when a small unbounded range is used to slice a structure with larger type?

@ghbrown: In general, when slicing one range with another, an intersection is computed.  So, for example `(1..100)[0..10]` would give `1..10` as its result.

My concern about interpreting `lo..` as being the same as `lo..max(lo.type)` was that, conceptually at least, `lo..` is intended to mean "from lo to ... something/whatever/infinity", so to cap it at an arbitrary value seems counter to that.  This could show up in a slice expression like `(-1000..1000)[0..]` where the `0..` had an index type of int(8), for example, since the conceptual answer should be `0..1000`, but if we treated `0..` as `0..max(int(8))` then we'd stop (seemingly arbitrarily) at 127.  Here's an example that demonstrates the current behavior that I'd like to preserve:  https://tio.run/##S85ILEjN@f@/LLFIIdOiSMFWwcAqM69Ew0JTT8@aq7wosyQ1J08DKKNXUlmQalVcUpSZl65pzQVWb2YC0mCop2doYGCApBoojk15XklqUXFqcklmfh5QG0hVNNDgWCSNSCp0FJSsFJR0UHShGvr/PwA

With respect to your concern:

> If such a change was implemented perhaps [I couldn't write]
> 
> ```chapel
> for i in (0..) {
>   writeln(big_int_range[i]);
> }

I don't think this is the case or problematic.  Specifically, you could still iterate over `0..`, and nothing about this proposal would make it illegal to use a smaller integer type to index into something that expected a larger index type.  Note in all of your code examples that indexing into a range using a singleton integer is not currently supported (as you were finding in your last example).  If your intention was to use this form to get the 'i'th index in the range, the current way to do that is with [`orderToIndex`:](https://chapel-lang.org/docs/1.26/builtins/ChapelRange.html#ChapelRange.range.orderToIndex)

> If this isn't as well liked by others I still think overflow checks would be nice.

Yeah, I think there's general agreement on this point.  Or at least, a lack of objections.

**Comment by bradcray** [comment]
I put together a PR that seems to implement the "iterate through all legal integers and then halt if the user hasn't broken out first" concept here:  https://github.com/chapel-lang/chapel/pull/19991  where I've only focused on integer types, not enums or bools. 
 It seems to be passing testing cleanly.  @ghbrown, you may be interested in experimenting with it based on your comments and concerns above.

**Comment by bradcray** [comment]
Now I've extended it to include enums and bools.

**Comment by bradcray** [comment]
@vasslitvinov : Now that #19991 has been merged, I'm curious whether you think we could close this issue?

**Comment by vasslitvinov** [comment]
My suggestion is to close it after changing the behavior of `==` for enum+boolean ranges:
```chpl
var r1 = false .. true;   // bounded
var r2 = false .. ;       // boundedLow
writeln(r1 == r2);        // prints "false" ---> change it to print "true"
```

**Comment by bradcray** [comment]
I've opened https://github.com/chapel-lang/chapel/issues/20896 to ask questions about the behavior of various range operations on unbounded ranges of bools/enums, which is something of a spin-off of this issue.

**Comment by bradcray** [comment]
With #21332 merged now and the remaining semantic questions spun off to #20896, I'm going to close this issue that kicked off some of the work that's been done and the questions that remain.
