### ISSUE TITLE
Support for searching a value in multi-dimensional, strided arrays

### ISSUE THREAD

**Issue by CaptainSharf** [chapel-lang/chapel#17113]
The module `Search` currently does not support searching for a value in rectangular multi-dimensional, strided arrays. However can we incorporate the method `orderToIndex` defined on all types of rectangular arrays to search for a value in multi-dimensional, strided arrays as well?

**Comment by bradcray** [comment]
@CaptainSharf : Are you thinking that the multidimensional array would be sorted in some way (such that a binary search-style approach could be used) or not (in which case we'd need a linear search)?  If the latter, I'm not sure `orderToIndex` plays a role here since you could just write:

```chapel
for i in Arr.domain do
  if Arr[i] = needle {
    result = i;
    break;
  }
}
```

Another approach would be to write such "linear" finds as reductions as a means of parallelizing them.  Though what's really wanted here is a "eureka" concept (see issue #12700).

**Comment by CaptainSharf** [comment]
@bradcray , I was thinking more in the direction of sorted multi dimensional arrays. I also wanted to know more about negative strided sorted arrays like an array with domain {1...5 by -1}. I'm assuming the smallest element in such an array would be at index 5. The current binary search assumes a normal ordering of elements from `lo` to `hi` in negative strided arrays.

**Comment by bradcray** [comment]
@CaptainSharf: Thanks for clarifying.  In my experience, multidimensional sorted arrays are not such a common or well-defined data structure to warrant this support; but it could be that they are and I'm just not aware of it.  Are you familiar with motivating examples or precedents in other languages/libraries?  (I ask because I'm not a big fan of building things "just in case" someone needs them.  In part because that time could be spent building things that people have expressed a need for; in part because it adds a code testing/maintenance/compilation time burden to the Sort module that feels like bloat if it's never used).

The question about the behavior of Search on arrays with negatively strided domains is a very reasonable one.  I have an opinion about it, but I don't know how much agreement we have on it within the team or community.  Arrays with negative strides have a number of problems / open issues on them (search "negative stride" in our issues).  For that reason, I _thought_ we'd added a `--warn-unstable` warning for them (and PR https://github.com/chapel-lang/chapel/pull/15180 seems to suggest this), but trying this test, I didn't get one:

```chapel
var A: [1..10 by -2] real;
```

But I need to quit for the day now, so don't have time to explore at the moment.

**Comment by CaptainSharf** [comment]
Hi @bradcray , I have looked at other widely used PLs/frameworks, there doesn't appear to be much support for sorting multi dimensional arrays. Thus, it seems to me that adding support for this feature might introduce significant overhead in array computations. Closing this issue, however I'd like to dig a bit deeper into the behavior of search for negative strided arrays.
