### ISSUE TITLE
Range BoundedRangeType verbosity

### ISSUE THREAD

**Issue by vasslitvinov** [chapel-lang/chapel#17126]
Currently bounded-ness of a range is given by an enum:
```chpl
enum BoundedRangeType { bounded, boundedLow, boundedHigh, boundedNone };
```

Its uses in creating ranges are often heavy-weight i.e. lengthy, ex.:
```chpl
var r: range(boundedType=BoundedRangeType.boundedLow);
```

How can we make it more attractive to users? Possible directions:
* `use BoundedRangeType;`
* factory functions
* shorten the name of the type or the individual enums?
* provide easier-to-use initializers, ex.:
```chpl
var r: range(boundedHigh=false);  // boundedLow, boundedHigh are optional args defaulting to true
var r: range(unbounded=true);
```

**Comment by bradcray** [comment]
I'm definitely sympathetic to this, though I probably am at least partially responsible for the current names (i.e., apparently I couldn't come up with better ones the last time we tried).

**Comment by mppf** [comment]
Here is a potential alternative. Would it be nicer/cleaner for the range type to be parameterized by two index types, one for the lower bound and one for the upper? Then we would use `nothing` to mean there is no bound:

``` chapel
record range {
  type lowerIdxType= int;
  type upperIdxType = lowerIdxType;
}
range(int, int); // has a high bound and a low bound
range(int); // defaults to range(int, int) 
range(nothing, int); // has no low bound and an integer high bound
range(int, nothing); // has no high bound and an integer low bound
range(nothing, nothing); // the unbounded range (since it covers all elements maybe it doesn't matter that it doesn't have an int-ish index type?)
```

It would also seem natural to me  to have something like myUnboundedRange.low return `none` (and this could be implemented without changing how BoundedRangeType works - as it is it says you get undefined behavior for calling low on a range with no low bound - which seems too loose for a thing known at compile time).

Besides that, it's obvious to me why we need range types to be parameterized by the index type - but it's not so obvious to me why we need to know at compile time if the range is bounded or not. I presume there are good reasons but I do not know what they are or if there is another way to address whatever the problems are.

**Comment by lydia-duncan** [comment]
I'm less okay with splitting it into two fields.  Here's my proposal for the names:
```chapel
enum RangeBound { low, high, both, none};
```

I don't really understand why "type" needed to be in the enum name - it seems like the important piece of information is that it is a bound specifically for ranges.  The names for the enum constants doesn't need to contain the type name in it - the shorter type name would make using the enum prefix less of a burden.

**Comment by bradcray** [comment]
> Would it be nicer/cleaner for the range type to be parameterized by two index types,

I'm not a fan.  To me, this feels like it opens traps like `range(int(64), uint(64)` and makes things feel less constrained and natural than the current approach or other alternatives.

> it's not so obvious to me why we need to know at compile time if the range is bounded or not.

I think the short argument might be that it lets us generate compile-time errors that would otherwise have to be execution-time ones.  But I wouldn't be surprised if there were also cases where it gave us helpful semantic information (I'm unsure).  Not a huge deal, but it could also enable us to optimize away the storage for the bounds (I don't believe we bother with this today).

> ```chapel
> enum RangeBound { low, high, both, none};
> ```

I agree this is an improvement.  I think we've been moving enums to lowercase, so should probably do so here (or with the current enum if we keep it).  I might call it `rangeBounds` since there are two of them that are being described.  We could also optionally make this enum more general than ranges, by calling it something like `boundedness`.

> The names for the enum constants doesn't need to contain the type name in it

I didn't look, but this _may_ date from the early days when we didn't require qualified naming of enums, as in C (?).

**Comment by lydia-duncan** [comment]
> I think we've been moving enums to lowercase, so should probably do so here (or with the current enum if we keep it). I might call it `rangeBounds` since there are two of them that are being described.

That all seems fine to me!

> I didn't look, but this _may_ date from the early days when we didn't require qualified naming of enums, as in C (?).

Ah, that would make sense.

**Comment by vasslitvinov** [comment]
Two thumbs up for Lydia's suggestion. I like plural `rangeBounds`. I also suggest renaming the field:
```chpl
  param bounds = rangeBounds.both;
```
If we infer the field's type from its initializing expression, we can say `rangeBounds` just once in the above?

> it's not so obvious to me why we need to know at compile time if the range is bounded or not.

If we don't, I'd expect challenges in emitting optimal code for a for-loop over an unstridable range or a slicing expression?

**Comment by bradcray** [comment]
Notes from the range module review, part 2:

Generally, people liked the shorter/sweeter `enum` as proposed by Lydia above.  There was some apprehension about using `rangeBound` as the enum's type name because:
* it makes it specific to "range" and we imagine potentially supporting unbounded domains over time as well (e.g., #10595)
* it seems preferable to avoid camelCase for a core enum type if possible to keep it simple / lightweight

Some proposals that were kicked around include:

```chapel
enum rangeBounds { both, low, high, none };
enum boundedness { both, low, high, none };
enum bounded     { both, low, high, none };
enum bounds      { both, low, high, none };
```

where, for the few who spoke up, `bounded` seemed to have a slight edge.

Along with wrestling with the name of the enum and its symbols, we should also think about the name of the field in the range type (or the query used to get that field).  It's currently `boundedType` which is also a bit of a mouthful.  I proposed:

```chapel
param boundedness: bounded;
```

which would mean writing things like:

```chapel
range(bounded.low);
```
```chapel
use bounded;
range(boundedness = low);
```
```chapel
range(boundedness = bounded.low);
```

Tagging @e-kayrakli , @lydia-duncan , @mstrout , @ronawho, @arezaii  on this comment because they were most involved in this part of the conversation in my memory.

**Comment by vasslitvinov** [comment]
#20169 would help further, allowing me to write pleasantly consice `range(bounds = low)`. 

#20169 would also allow me to write something a bit cryptic to an untrained eye, like `range(int, low, negative)`. To be fair, I would be able to write this even without #20169 -- I just need to `use` the relevant enums.

**Comment by vasslitvinov** [comment]
In the module review meeting today, we liked this proposal:
```chpl
enum boundedKind { both, low, high, neither };
var r: range(bounds=boundedKind.low, ...);
```
with the following proposed alternatives:
* enum `boundedKind` or `boundedness` or `boundKind`
* constant `neither` or `unbounded`

**Comment by vasslitvinov** [comment]
In today's deep dive we converged on `r.bounds : enum boundKind`

where earlier we defined `enum boundKind { both, low, high, neither }`
