### ISSUE TITLE
Range.intIdxType - should it be public?

### ISSUE THREAD

**Issue by vasslitvinov** [chapel-lang/chapel#17129]
`range.intIdxType` is the range's `idxType` if it is integral, otherwise `int`

Should `intIdxType` be in range's public interface?
* no: because it was introduced as an internal helper to implement ranges over non-integers
* yes: because it is used in domains, which can also have non-integer idxTypes,
  which may need to be handled by user-written domain maps

**Comment by bradcray** [comment]
I feel like I need to review how this is used currently and whether its use is necessary or just a particular implementation choice before being able to weigh in on this one.

**Comment by bradcray** [comment]
I've reviewed uses of intIdxType, something I've been meaning to do since we last reviewed the domains interface, and don't believe we should make it part of the public interfaces of domains, arrays, or ranges at present.  To me, this seems like the sort of thing that is below the bar for needing any team discussion, but I'm open to suggestions that I'm wrong about that, esp. from @lydia-duncan , @mstrout , @vasslitvinov , and @stonea.

I've got an implementation for this change here:  https://github.com/chapel-lang/chapel/pull/22620
