### ISSUE TITLE
Set CHPL_LLVM=none for pre-merge travis builds

### ISSUE THREAD

**Issue by daviditen** [chapel-lang/chapel#17135]
The pre-merge travis builds are detecting a system LLVM in https://github.com/chapel-lang/chapel/pull/17133 but then failing to build with it. Set CHPL_LLVM=none in those builds.

**Comment by mstrout** [comment]
Sprint planning: this would be a good task for Joe after he learns how testing setup is working.

**Comment by ronawho** [comment]
This seems like a problem a user could hit. Do we want to improve our detection of system llvm instead of having to forcibly disable it?

**Comment by daviditen** [comment]
> Do we want to improve our detection of system llvm instead of having to forcibly disable it?

Yes, but until that happens I think we can disable it here.

**Comment by bradcray** [comment]
Should/could #17133 be doing this check as part of its "if there is a system LLVM" check?  

That is, if users did have a system LLVM installed, and it was sufficiently old that we couldn't use it, shouldn't we choose not to use it, possibly suggesting that they upgrade their system LLVM or switch to another CHPL_LLVM setting?  (or is that what we're already doing and it's why the checks are failing?)

This is similar to what I was asking in https://github.com/Cray/chapel-private/issues/1633#issuecomment-778495392.  All of which makes me realize that the logic that we're discussing there and implementing here should really have more eyes on it before it's merged since it has a pretty big impact on how developers and users will interact with and install Chapel (and I don't feel super-confident that my ideas are best, even though I do think they're pretty good).

**Comment by daviditen** [comment]
The `util/chplenv/chpl_llvm.py` script looks for a system LLVM that matches the version listed in `third-party/llvm/LLVM_VERSION`. It appears that the failing checks in #17133 are finding a system llvm at version 11, but it is broken and missing expected headers.

**Comment by bradcray** [comment]
Got it, thanks for the clarification.  So to circumvent this, we'd need to do something like:
* try to compile a sample program with LLVM
* see that it fails, and fall back to something else if it does
?

**Comment by daviditen** [comment]
> try to compile a sample program with LLVM
> see that it fails, and fall back to something else if it does

Yes, we could do something like that. The sample program should ideally look a lot like our LLVM backend.

**Comment by daviditen** [comment]
https://github.com/chapel-lang/chapel/pull/17238 sets `CHPL_LLVM=none` in this CI testing until we get `system` working.

**Comment by daviditen** [comment]
#17238 is merged. Opened https://github.com/Cray/chapel-private/issues/1778 to look more into why CHPL_LLVM=system is detected but not working.
