### ISSUE TITLE
Range slicing syntax

### ISSUE THREAD

**Issue by vasslitvinov** [chapel-lang/chapel#17132]
This issue asks whether we can improve the way range slicing is written.

In our range module review on 2/04 a few of us noted that the current way to slice a range unintuitive:
```chpl
expr1(expr2)
```

Here are our considerations:
* The obvious alternative is to introduce a slicing method, ex. `expr1.slice(expr2)`
  especially that we already have `localSlice` methods.

* Slicing is particularly useful on domains and arrays. Some prefer to write it with square brackets, as in `expr1[expr2]`, although Chapel treats it the same as parens.
  Having to write `A.slice[x..y]` instead of `A[x..y]` can be seen as a step backwards.

* We could potentially support both the paren form and a method.
  Although this goes against the principle that there should not be two ways of doing the same thing.

* Whatever we do, it should be consistent between ranges, domains, and arrays.

* If expr1 is range and expr2 is an integer,`expr1(expr2)` should be a valid "element access" (by analogy to indexing into an array), perhaps meaning `orderToIndex` #14884

**Comment by bradcray** [comment]
I don't disagree that there's a learning curve to understanding what range slicing does, but I think it's similar enough to sub-array slicing and domain slicing, and sufficiently core/powerful to doing range algebra that it's worth preserving.  I definitely prefer writing it with square brackets, which I think makes it less confusing (and more similar to how we choose to write other slices, stylistically).

**Comment by vasslitvinov** [comment]
BTW I consider this issue to apply to all of range, domain, and array slicing.
We surely want the syntax to be the same in all three cases.

**Comment by bradcray** [comment]
> I consider this issue to apply to all of range, domain, and array slicing.

I don't think we should consider removing support for things like `A[2..n-1]` or `A[MyDomain]` by requiring them to be written using methods.  I consider these core to Chapel, part of its first-class support for rich array semantics, and natural syntactically.

> We surely want the syntax to be the same in all three cases.

I think there is an argument to be made that we could support range/domain slicing using a different syntax than array slicing (though I'm not going to be the one to champion it).  Specifically, an array slice must consist of indices that are in-bounds, like any other array access by a singleton index.  Whereas range and domain slicing compute intersections, so permit out-of-bounds slicing expressions.  One could argue that this difference is sufficient to justify different syntax.

My argument would be that if domain/range slicing required the slicing indices to be in-bounds, like arrays, then it's not particularly interesting or valuable (since the result is essentially the slicing indices themselves).  And that intersecting domains is sufficiently common—and sufficiently similar to array slicing—to deserve the syntax for conciseness.

**Comment by mppf** [comment]
I don't have a strong opinion here - but I'd draw the line at array slicing. I'd keep writing `A[MyDomain]` to mean slicing because there is a kind of analogue with promoted indexing in terms of what you get (but not how it is represented). But for ranges and domains, I'd write `MyDomain.slice`  or maybe even something along the lines of `MyDomain.intersect`.

**Comment by lydia-duncan** [comment]
Another alternative is to leave the `[]` form unchanged but only allow `()` to be used for accessing a specific index.  I agree that having `expr1(expr2)` return a slice is confusing and I think having the behavior be consistent across the three types would be ideal.  I find having a `slice` method appealing and wouldn't consider it to be reimplementing the wheel - I would think of it more like the `[]` form is a syntactic sugar over `slice()`

**Comment by bradcray** [comment]
> Another alternative is to leave the [] form unchanged but only allow () to be used for accessing a specific index.

I don't think we should re-open the question of whether accesses/calls via `[]` vs. `()` should be treated differently from one another at this point.  Also, note that ranges/domains don't support single-index accesses.

**Comment by vasslitvinov** [comment]
I like drawing the line at array slicing, as A(slice) parallels single-element access.

I also like Engin's suggestion to allow "indexing" into ranges and domains. Alas that would make today's slicing syntax justifiable for domains and ranges as well. I don't know how I would reconcile this justification with my dislike of that syntax for ranges/domains.

**Comment by bradcray** [comment]
> I also like Engin's suggestion to allow single-element "indexing" into ranges and domains.

I'm not a fan.  If the crux of this issue is that we're concerned that `myRange[i..]` or `myDom[i, ..]` are too ambiguous / confusing in Chapel to support without introducing a method name—which I disagree with(*)—then I don't see how we'd rationalize that it wouldn't be at least as confusing for `1..10[1]` to be `2` or `1..10[2..]` to be `3..10` or `myDom[i, ..]` to mean "give me the ith row of myDom using ordinal indexing rather than its natural indexing."

* = where I think these things are either sufficiently clear at face value to support, or easy enough to look up if you don't have an intuition as to what they mean.  I also think it's unlikely to be dangerous to support them in that I don't think you'd type them unwittingly, expecting some other result.

**Comment by vasslitvinov** [comment]
Good point about ordinal indexing. Now I don't like it any more.

**Comment by bradcray** [comment]
I'd like to advocate more forcefully for maintaining the status quo here.  I think that it's possible to write cases of range or domain slicing that look ridiculous or confusing or uninspiring, like `1..10[2..11]` or `{1..n, 1..n}[2..n-1, 0..n+1]` but I think cases like `myRange[3..]` ("give me all indices in myRange starting from `3`") or `My2Ddomain[i..i, ..]` ("give me the `i`th row of my 2D domain, if it has one") are reasonably intuitive and don't require a named method for clarity.  I'll continue to admit that yes, there's a learning curve here, but I don't think it's that onerous or surprising, and it continues to feel like a natural operation to support directly as an analog to array slicing.

**Comment by damianmoz** [comment]
.... I too would like to advocate strongly for maintaining the status quo here.

Also, has anybody given any consideration to my long ago suggested use of A[i **..** j **::** s] as a more concise alternative of A[i  **..** j **by** s].  The mods to the compiler are trivial. Then again, there have been strided slices i **:** j **:** s since at least the late 70s in fringe languages and (with that same syntax) in Python and Fortran since 1991 and 1992 respectively.

**Comment by bradcray** [comment]
For context, @damianmoz is referring to issue #15906 here.

**Comment by bradcray** [comment]
Capturing discussion from today's range review (take 2), there was general support for preserving slicing of ranges as meaning intersection as it does today.

**Comment by lydia-duncan** [comment]
@bradcray / @vasslitvinov - I think this issue can be closed, is that correct?

**Comment by vasslitvinov** [comment]
The consensus is to stay with the status quo. Closing.
