### ISSUE TITLE
Should sync string be supported?

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#17177]
This program compiles and runs today

``` chapel
proc main() {
  var x: sync string = "hi";
  writeln(x.readFE());
}
```

Should it? If it should, we should add testing for it. If not, we need to update https://github.com/chapel-lang/chapel/blob/fc00057e01d274d9cf6f63aec9db95f299feea5b/modules/internal/ChapelSyncvar.chpl#L71-L80

**Comment by bradcray** [comment]
It surprises me a little that we support sync strings today, but I'm also failing to come up with a reason that we shouldn't (given that they're not modifiable in-place) or that it wouldn't make sense.

If we decide to continue to support it, we should also add support for sync bytes.

**Comment by mppf** [comment]
> given that they're not modifiable in-place

strings are modifiable in place with `+=`

> that it wouldn't make sense.

on #17176 it sounded like you were leaning away from `sync shared` because `shared` doesn't fit in one pointer-sized value. Wouldn't the same apply to `string` ?

**Comment by bradcray** [comment]
[warning: lots of thinking out loud follows]

> strings are modifiable in place with +=

I was thinking more about the fact that you can't do something like `mystring[3] = "h";`—that strings only support all-or-nothing modifications.  Even `+=` to me is logically like `mystring = mystring + "suffix";` which is to say, logically, a complete re-assignment of the string that happens to share a prefix.  If we optimize that by realloc-ing it and extending it in place, that seems more like an optimization than a case that could run afoul of full-empty semantics?

For me the litmus test for why things like ints and bools logically make sense for syncs, and arrays and complexes haven't, relates to whether the type represents a singleton data value or multiple data values.  As soon as it's possible to modify just a piece of a data value (as in `myarray[3] = ...` or `mycomplex.re = ...`) then it gets much harder to define the interaction with the full/empty state.  Whereas if the user can only read/write "all or nothing" of the data type, then it makes sense to at least consider it to have the sync property.

Traditionally, and in my response so far, I've focused on the case of writing to part of a value, but maybe reading from part of a value (or equivalently, the ability to iterate over it) has the same problem since it isn't obvious whether those sub-reads should interact with the full-empty state or not.  So that might be a good reason not to support sync strings/bytes (i.e., even though I can't modify `mystring[3]`, I can read `mystring[3]`, so how should that interact with the full-empty state...?).

OTOH, if we go to requiring more explicit readXY/writeXY routines to interact with the sync, then maybe these questions are better defined, because I'd have to write something like `mystring.readFF()[3]` rather than simply `mystring[3]`?

> it sounded like you were leaning away from sync shared because shared doesn't fit in one pointer-sized value.

It was less a concern about the size/storage of the datatype and more around the "single vs. multiple values" concern above, where `owned` and `shared` seemed as though they were on the brink of representing multiple values in a way.  I also was having trouble getting my head around the complexity that something like `owned C?` has a notion of ownership vs. unowned/nil, but that `sync` also has a notion of full vs. empty, and the two seemed somehow either redundant or in competition with one another.  So it seemed reasonable to put it off until someone had a compelling need for it.

I should also say that, overall, I wouldn't have any qualms about making most of these nontrivial cases that we're discussing illegal for the time being and then relaxing it if/when the need arises in the future.  But I took this question to be more about what we should do ultimately rather than right now, so was answering it in that vein.

**Comment by mppf** [comment]
In the long term, I think it's reasonable for `sync myRecordType` to work and that would imply `sync string` as well as `sync owned` work in terms of what the implementation does.

However in the meantime since these operations are almost completely untested and we are aiming for stability I think we should disable them. I've created PR #17248 to disable them for now and plan to proceed with that if testing is reasonably clean.

**Comment by mppf** [comment]
In the spec, https://chapel-lang.org/docs/master/language/spec/task-parallelism-and-synchronization.html#synchronization-variables

> sync and single are type qualifiers and precede the type of the variable’s value in the declaration. Sync and single are supported for all Chapel primitive types ( Primitive Types) except complex. They are also supported for enumerated types ( Enumerated Types) and variables of class type ( Class Types). For sync variables of class type, the full/empty state applies to the reference to the class object, not to its member fields.

(where Primitive Types includes `string`)


> 
> Rationale.
> 
> It is only well-formed to apply full-empty semantics to types that have no more than a single logical value. Booleans, integers, real and imaginary numbers, enums, and class references all meet this criteria. Since it is possible to read/write the individual elements of a complex value, it’s not obvious how the full-empty semantics would interact with such operations. While one could argue that record types with a single field could also be included, the user can more directly express such cases by declaring the field itself to be of sync type.

The fact that the spec says that `sync string` should work gives me some pause, but if we are trying to not support things that have "more than a single logical value" as `sync` / `single` then IMO that rules out `shared` as well as `string`.

> Since it is possible to read/write the individual elements of a complex value, it’s not obvious how the full-empty semantics would interact with such operations. 

We don't have to support those operations on `sync complex`. Instead, `sync complex` can return the `complex` by value when it is read (and not ever give a reference to it). So the only way to read it is to get a whole `complex` out and the only way to write it is to put a whole `complex` in.

I think we could allow `complex` and `string` and general records, provided that when copy-initializing them (to, say, create a copy when reading a `sync MyRecord`) the RHS is not modified. If the RHS is modified then I think we get in to trouble trying to mutate what is protected by the `sync`/`single`. So I think that rules out `owned`.

**Comment by arezaii** [comment]
During module review we decided to remove support for sync string and update the documentation to say as much. The suggestion is to update PR #17248 with the documentation changes and merge it.

**Comment by slnguyen** [comment]
@arezaii  From the above discussion, it sounds like sync strung will not be supported for chapel 2.0 stabilization. If so should `string` be removed from the documentation (copied below): 

`sync and single are type qualifiers and precede the type of the variable’s value in the declaration. sync and single are supported for the primitive types nothing, bool, int, uint, real, imag, complex, range, bytes, and string`
https://github.com/chapel-lang/chapel/blob/main/doc/rst/language/spec/task-parallelism-and-synchronization.rst#synchronization-variables

**Comment by mppf** [comment]
@slnguyen - actually in PR #18379 I updated the implementation of `sync` and `single` to work with user records. If they work for user records, in my opinion, they should work for strings too. Since the docs already cover this, I'll close the issue.
