### ISSUE TITLE
sync variables and owned/shared

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#17176]
https://chapel-lang.org/docs/language/spec/task-parallelism-and-synchronization.html#synchronization-variables

says

> Sync and single are supported for all Chapel primitive types ( Primitive Types) except complex. They are also supported for enumerated types ( Enumerated Types) and variables of class type ( Class Types). For sync variables of class type, the full/empty state applies to the reference to the class object, not to its member fields.

After this was written, we developed the idea that "class types" includes `owned` and `shared`. Do we intend for these to be the element type in `sync` or `shared` ?

Meanwhile, there are confusing error messages when using `sync owned` and `sync shared` :

``` chapel
class C {
  var x: int;
}

proc main() {
  var x$: sync owned C? = new owned C(1); // error 1
  writeln(x$.readFE());
  var y$: sync shared C? = new shared C(1); // error 2
  writeln(y$.readFE());
}
```

So the next steps are:
 * decide if we want to support things like `sync owned C?` or `single owned C?`. For that matter, should we support `sync borrowed C?` or just things like `sync unmanaged C?` ?
 * update the language specification to clarify
 * update the implementation to give a better error message for any unsupported cases -- note that `isClassType` in the below is including `owned` and `shared` - https://github.com/chapel-lang/chapel/blob/fc00057e01d274d9cf6f63aec9db95f299feea5b/modules/internal/ChapelSyncvar.chpl#L71-L80

**Comment by bradcray** [comment]
Good question / this had escaped me.  My instinct is that a synchronized unmanaged or borrow variable could make sense since those are represented as raw pointers.  Whereas synchronized shared or owned seem... weird and/or hard to reason about.  At the very least, I think it would be reasonable to initially only support synchronized unmanaged and borrowed.

**Comment by bradcray** [comment]
Since this was filed, users have requested sync variables of non-nilable classes, so I've applied the `user label` tag to reflect that.  In recent discussions, Michael has reminded me that now that we don't have implicit reads/writes of sync/single, some of my historic hesitancies to supporting `sync` for values that are more complex than a single value may no longer apply.  I think my previous comment was made in my old frame of mind and can imagine that with explicit read/write methods applied my concerns may just evaporate.

**Comment by mppf** [comment]
Closing this issue because PR #18379 adds support for sync owned / sync shared.
