### ISSUE TITLE
Which method to use for compiling regular expressions in Chapel

### ISSUE THREAD

**Issue by leekillough** [chapel-lang/chapel#17187]
1. Free procedure in module `Regexp` (current method)
    `use Regexp;`
    `var re = compile("/a/");`
    
2. `init` method on `regexp`
      `use Regexp;`
      `var re = new regexp("/a/");`
       
3. `type` method on `regexp`
     `use Regexp;`
     `var re = regexp.compile("/a/");`

**Comment by bradcray** [comment]
With the caveat that I am not a big user of regex[p] in general (so am not necessarily the persona we're optimizing for...)

I find the `new regexp("/a/")` form pretty refreshing in that it seems to say very clearly and in a self-documenting manner what's going on.  I understand that one of the challenges with supporting it is that our initializers can't currently throw, and we'd want/need them to do that, but putting that aside:  What other benefits would a `compile`-style method have?

* uses the name that Python users are familiar with (which I wouldn't shrug off too lightly... is there rationale from their history we could learn from?)
* might make it more obvious that some non-trivial work is involved compared to many lightweight object creations?

If we did stick with `compile`, I think my preference would be to option 1, where I would probably try to keep my code clear by writing:

```chapel
use Regex[p];
var re = Regex[p].compile("/a/");
```

or:

```chapel
import Regex[p];

var re = Regex[p].compile("/a/");
```

[Sorry for all the `Regex[p]`s, just trying it on for size... :) ]

**Comment by lydia-duncan** [comment]
My ranking is 1, 3, 2, but I don't feel super strongly about it and suspect this preference is more from familiarity than anything else.

**Comment by leekillough** [comment]
My preference is for 2 except that we can't throw errors in `init()` right now. The `new regexp()` makes it sound like an expensive operation, like you're allocating something.

My second choice is 3, since it requires `regex[p].compile()` instead of just `compile()`, and I prefer long qualified names to refer to types instead of modules.
 
If we stick with 1, is there a way to prevent `compile()` from being accessed in an unqualified way, such as making it not get imported by default, so that you must use `Regex[p].compile()` instead of just `compile()`?

**Comment by leekillough** [comment]
Issues related to # 2 not being able to throw from initializers:

https://github.com/chapel-lang/chapel/issues/6145

https://github.com/chapel-lang/chapel/issues/8692

**Comment by bradcray** [comment]
> `r` just happens to be an object or state machine or whatever that find matches based on regular expressions. So, then, is new regex returning something other than a regular expression?

Hi Engin — To me, it seems like the logical conclusion of this is that you'd want to rename the `regex` type as well, or have it be opaque / unnameable to a user.  E.g., in approach 1, wouldn't writing `var re: regex = compile("/a/");` throw up a similar philosophical stumbling block?

**Comment by e-kayrakli** [comment]
Good point and that's right.

[Seeing the email notification for your comment, I thought "didn't I say that in my comment already?", but apparently I didn't]

Yesterday, while thinking on this, I went through the regex documentation. I didn't find the regex type to be documented, so that was a bit of a relief for this specific issue about the meaning of "regular expression". But that doesn't mean that it is not usable by the user, and we also have formals that are like `regex(string)` etc. Somehow `var r = new regex("foo.*bar");` still feels too on the nose compared to other similar concerns, though, and I don't know whether I would suggest renaming the `regex` type to emphasize it being more than a pattern string just on this ground.

To be clear, my preference is still mostly based on `compile` feeling familiar and common. My other arguments against initializer are not very concrete. All in all, I wouldn't argue too strongly against an initializer-based approach either.

**Comment by bradcray** [comment]
> I didn't find the regex type to be documented
> we also have formals that are like regex(string) 

Just to make sure we're on the same page with this side part of the conversation:  I'm assuming you would agree that, whatever the type is named, it _should_ be a visible / known name to the user, right (i.e., the `Regex` module and routines shouldn't rely on an opaque type for its arguments and return types)?

**Comment by e-kayrakli** [comment]
> I'm assuming you would agree that, whatever the type is named, it should be a visible / known name to the user, right 

Yes. Definitely.

**Comment by e-kayrakli** [comment]
It looks like nobody has strong opinions about this. I am seeing the following arguments for `compile` vs `init` based approaches:

#### `compile`-based

- similar to Python
- avoids the fact that initializers can't throw today
- doesn't require any work, no breaking change (slightly less so if we go with type method)

#### `init`-based

- `new regex('foo')` should be the intuitive way to create a `regex` object.

---

I am still for not changing anything (so I may be biased in my characterizations above). But, still, not very strongly. I think we need a champion for defending `init` based approach. Brad, I don't get the sense that you'd be up for being that champion, but I may be wrong.

**Comment by bradcray** [comment]
I continue to find `compile()` to be a fairly non-intuitive name for "turn this string representing a regular expression into a `regex` value," despite the precedent in Python—particularly within the context of developing a compiled programming language.  E.g., if you asked me what `compile()` did, my main guess would be "invoke the compiler?" and I'd expect `compile("*.chpl");` to compile all the source files in the cwd, not to create a regex that recognized Chapel filenames.  If the standalone routine were called `createRegex()` or `compileRegex()` or `newRegex()`, I wouldn't have that same reaction to it.

Moreover, in a recent "standalone routine" vs. "initializer" debate in a different module, @mppf suggested the guidance that if the main goal of the operation is to build a thing of the given type, an initializer would be most appropriate; whereas if the main goal is to do something else (e.g., access the file system to open a file) and the thing returned was just a byproduct of that operation / handle to its result, then it should be standalone.  To me this case feels more like the former than the latter in that I'm not sure what I'm doing in this operation apart from creating the resulting value representing the regular expression and supporting operations about it.

That said, this gets back a bit to Engin's question above about whether `regex` refers to the string `"brad*"` or the type that results from compiling that string into something that can do regex operations.  As things stand today with the type being named `regex`, it feels pretty clear to me like what we're doing is saying "Create a new `regex` value defined by the string 'brad*'", similar to how we might interpret `new Square(3.0)` as meaning "Create a new square whose sides are 3.0 units long."  So `new regex("brad*")` feels very natural to me.

**Comment by mppf** [comment]
@bradcray - yeah. The typical use in Python has `re.compile("mystring")` so it's clear what is being compiled. So that is arguably more like they type method `regex.compile`. We could consider supporting both `new` and the type method and maybe even put off the initializer if we don't want to implement throwing from initializers yet. @bradcray how do you feel about `regex.compile("mystring")` ?

**Comment by bradcray** [comment]
Capturing my answers from today's meeting:

> how do you feel about regex.compile("mystring") ?

I feel as though in a recent team conversation, we expressed a preference for standalone routines over type methods so that someone using a fully-qualified import style wouldn't have to say `Regex.regex.compile()` or `re.regex.compile()`.  If we stuck with `compile()`, I think it should come with a strong style preference for typing `Regex.compile()`, but the fact that we'd feel the need to say that suggests to me that the name isn't very good/clear.

> We could consider supporting both new and the type method

This seems to have the "supporting two ways of saying the same thing can lead to confusion" problem (in the "why would I say it this way rather than that way?" sense).

**Comment by ben-albrecht** [comment]
Minor note: Dropping `compile` function can make regex one-liners a little less satisfying as they require wrapping the new expression with parens:

```chpl
// Chapel 1.25
if compile(pattern).match(text) { ... }
// Proposed initializer version
if (new Regex(pattern)).match(text) { ... }
```

Not a big deal, and even less so if we continue to support most tertiary methods (https://github.com/chapel-lang/chapel/issues/17226), so that users can still do:

```chpl
if text.match(new Regex(pattern)) { ... }
```

I am still in favor of the initializer approach, but wanted to throw this out there.

**Comment by bradcray** [comment]
> as they require wrapping the new expression with parens:

I didn't want to open up the following can of worms yesterday, but wondered (as I think I have in the past) whether we'd also want to support string->regex casts, so that you could write this as:  `if ("Brad*":regex).match(text)` or `if text.match("Brad*":regex)`  (I can't recall whether my parenthesis here are required in the first case or not, but would probably use them in either case for clarity).

**Comment by mppf** [comment]
In fact that is already currently implemented

https://github.com/chapel-lang/chapel/blob/7c41c0d4a7fd7f772cda1ea2ab74492afeb56244/modules/standard/Regex.chpl#L1141-L1145

**Comment by bradcray** [comment]
> In fact that is already currently implemented

Ooh, even better!  And this makes me believe even more strongly that initializers are the right way to express this rather than `compile()` since casts seem in a similar space as initializers (create me something of one type from some other value).

I had one other thought about our "throwing initializers" conversation yesterday that I haven't had time to look into yet, so wanted to mention it in case someone beats me to it:  I wondered whether our `postinit()` calls could `throw` today, and if so whether that might be an alternate/simpler path to the stepping stone of "initializers can only throw after all fields are initialized."  I suspect it's not that easy (and may also be challenging since all initializers would call `postinit()` not just the one that takes a string), but it seemed like another potential tool for this effort.

**Comment by e-kayrakli** [comment]
Just to record our direction here (it hasn't been directly said in the last couple of comments):

- We want to deprecate `compile` in favor of `new regex` eventually.
- However, initializers cannot throw as of today, but we need that capability to make sure that the string passed to the initializer is a valid regex.
- Until we have that feature implemented (or figure out a workaround like Brad's comment above) we are not changing how we are building regular expressions.

**Comment by bradcray** [comment]
> However, initializers cannot throw as of today, but we need that capability to make sure that the string passed to the initializer is a valid regex.

I finally got around to trying something I've been meaning to out of curiosity, which is:  What actually happens today if we create an initializer that throws after the object is completely initialized and ignore errors?  The answer is "it seems to work":

```chapel
record R {
  var x: int;
  proc init() throws {
    this.x = 42;
//    this.complete();                                                          
    throw new Error("Hey!");
  }
}

var myR: R;
```

And the same for a postinit() call (with the additional benefit that we don't need to ignore errors):

```chapel
record R {
  var x: int;
  proc init() throws {
    this.x = 42;
//    this.complete();                                                          
    throw new Error("Hey!");
  }
}

var myR: R;
```

That's not to say that we are ready to have user-defined initializers throw errors per se (in particular, the throws here are probably not deinitializing the object, if they should...).  But that we could probably get a regex initializer to throw by hook or by crook.

**Comment by bradcray** [comment]
@slnguyen : I was returning to this as a potential Friday afternoon coding break, and see that you've taken it on in this sprint, which I'd missed previously.  Can you clarify what approach you're taking?  Specifically, are you making a throwing initializer or postinit, as proposed in my previous comment?  Thanks!

**Comment by slnguyen** [comment]
I was planning to implement the workaround, as proposed in your previous comment, but I haven't started yet. I can work on another regex issue if you wanted to work on this.

**Comment by bradcray** [comment]
No, I think it makes sense for you to own it—I just hadn't noticed (and had other things I'd prefer to look into on a Friday afternoon anyway).  Thanks, and I'll be curious how it goes!

**Comment by slnguyen** [comment]
Both the throwing initializer with `--ignore-errors` flag and the postinit workaround don't allow us to easily go from what we have today (e.g `var re = compile("/a/");` to using an init method (e.g. `var re = new regexp("/a/");`)

The initializer with `--ignore-errors` flag approach doesn't work since a throwing init() on a generic record isn't currently implemented. In more detail, when I add a throwing initializer to the regex record
```
 614 record regex {
 615 
 616   pragma "no doc"
 617   type exprType;
 618 
 619   pragma "no doc"
 620   var home: locale = here;
 621   pragma "no doc"
 622   var _regex:qio_regex_t = qio_regex_null();
 623 
 624 
 625   proc init()  throws {
 626     this.exprType = string;
 627     throw new Error("Hey!");
 628   }
 629 
 630   proc init(type exprType) {
 631     
 632     this.exprType = exprType;
 633 
 634   }
 ...
 ```
 I get the following errors
 ```
 chpl test_regex.chpl --ignore-errors
 $CHPL_HOME/modules/standard/Regex.chpl:625: error: initializers are not yet allowed to throw errors
$CHPL_HOME/modules/standard/Regex.chpl:625: In initializer:
$CHPL_HOME/modules/standard/Regex.chpl:614: error: cannot default-initialize a variable with generic type
$CHPL_HOME/modules/standard/Regex.chpl:614: note: 'this' has generic type 'regex'
$CHPL_HOME/modules/standard/Regex.chpl:614: note: cannot find initialization point to split-init this variable
$CHPL_HOME/modules/standard/Regex.chpl:626: note: 'this' is used here before it is initialized
$CHPL_HOME/modules/standard/Regex.chpl:626: error: unable to resolve type
$CHPL_HOME/modules/standard/Regex.chpl:626: error: use of 'call_tmp' before encountering its definition, type unknown
test_regex.chpl:2: internal error: RES-FUN-ION-2544 chpl version 1.26.0 pre-release (5b83bc9523)
Note: This source location is a guess.

Internal errors indicate a bug in the Chapel compiler ("It's us, not you"),
and we're sorry for the hassle.  We would appreciate your reporting this bug -- 
please see https://chapel-lang.org/bugs.html for instructions.  In the meantime,
the filename + line number above may be useful in working around the issue.
```

With the postinit workaround, a user would have to put `try`/`try!` around `var re = new regexp("/a/");`. For example
```
  1 module M
  2 {
  3   proc main() {
  4 
  5   use Regex;
  6 
  7   var rs : regex;
  8   rs;
  9 
 10   try {
 11     rs = new regex("hello");
 12   }
 13    catch {
 14      writeln("caught an error, unnamed catchall clause");
 15   }
 16 
 17   var str = " test hello world ":string;
 18   var match = rs.search(str);
 19   writeln(match);
 20   writeln(str[match]);
 21 
 22   }
 23 }
 ```
Otherwise they would get the following error
```
test_regex.chpl:5: In function 'main':
test_regex.chpl:8: error: call to throwing function postinit without throws, try, or try! (relaxed mode)
$CHPL_HOME/modules/standard/Regex.chpl:709: note: throwing function postinit defined here
test_regex.chpl:27: error: call to throwing cast without throws, try, or try! (relaxed mode)
test_regex.chpl:28: error: call to throwing cast without throws, try, or try! (relaxed mode)
```

I think for us to implement the init method for regex (`var re = new regexp("/a/");`) the next step would be to support initializers throwing errors

**Comment by e-kayrakli** [comment]
Just to close the loop here: in a module review discussion, the team has reached (confirmed?) consensus on deprecating `Regex.compile` in favor of throwing `regex.init`.

See https://github.com/chapel-lang/chapel/issues/14694#issuecomment-1209781393

https://github.com/chapel-lang/chapel/pull/21636 will make that change.
