### ISSUE TITLE
What can be passed to a `const ref` formal argument?

### ISSUE THREAD

**Issue by vasslitvinov** [chapel-lang/chapel#17195]
Reference: [argument intents in the spec](https://chapel-lang.org/docs/master/language/spec/procedures.html#the-const-ref-intent)

Consider a function that has a const ref formal, ex.
```chpl
proc f(const ref formal: SomeType) {.....}
```

What kinds of expressions of the type `SomeType` can we use as an actual argument to `f` ?

Variables, including formals, record fields, etc., whether `var` or `const`, can.

We also some time ago started allowing value expressions as actuals, ex.
```chpl
proc g(): SomeType { ... return ...; }
f(g()); // legal
```

This issue asks:
* Are `param` values legal actuals here?
  Ex. what if `g()` above had a `param` intent?

While there:
* Are we happy with allowing value expressions as actuals?
  Sounds like “it maybe slightly odd, but definitely convenient.”
* Should we also allow value and param expressions as actuals
  to **`ref`** formals, following the same rational as for `const ref` formals?

**Comment by bradcray** [comment]
I've never felt super-confident that we've been doing the right thing by permitting what you're calling value expressions (which I tend to think of more as a compiler-generated `const`s) to be passed to `const ref` intents; but I do think the "it may be slightly odd, but it's definitely convenient" might be my quote, which sums up about how I feel about it.  Note that we do permit user-defined `const`s to be passed to `const ref` intents, so arguably we're consistent here (?).

My current impression is that as long as we do permit `const`-style expressions to be passed to `const ref` arguments, we should do the same for `param` expressions.  Or, at least, I'd want to hear a good argument for why that would be a bad idea.

I'm not currently in favor of allowing `const` and `param` expressions to be passed to `ref` formals, or at least would need more of an argument for why that would be attractive.  I'm guessing you would restrict it to anonymous/compiler-generated `const` and `param` expressions rather than user `const` / `param` expressions.  I.e., that the following would remain illegal?

```chapel
const c = 42;
param p = 33;

foo(c);
foo(p);
foo(42);

proc foo(ref x: int) {
  x += 1;
}
```

**Comment by leekillough** [comment]
I think `param` should be passable as `const ref`, but not as `ref`. I think we agree.

> Not to distract to another language, but I think that the `Lvalue` and `Rvalue` distinction in C++ has held up well, and relates to copy- and move-constructors.

> An anonymous temporary (Rvalue) is not necessarily `const`, but it has certain immutable properties.

**Comment by dlongnecke-cray** [comment]
I find myself bumping into this a lot when working with `map.update()`, as it takes a key by `const ref`. It would be nice if I could pass a literal to the key:

```chapel
use Map;

var m: map(int, int, parSafe=true);
m.add(0, 0);

var k = 0;
m.update(k, new myUpdater(5)); // Just assume we already have an updater defined...
```

I'd love to be able to just pass `0` directly instead of `k`.

**Comment by vasslitvinov** [comment]
I agree that we should allow `param` values for `const ref` formals.

We can surely do without allowing them for `ref` formals.

**Comment by mppf** [comment]
> Are param values legal actuals here?

Just noting that these currently aren't allowed.

I'm happy with allowing call-expr temporaries or literals to be passed to `const ref` formals. 

In the past I have argued that we don't need the `lvalue` term or idea in the compiler. I think there are other ways to think about the same rules (IIRC Brad has brought up possibly thinking about the "value" return intent as "const"). In the past I have also argued that we could make remove the `lvalue` idea by allowing call-expr temporaries / nested calls to pass to `ref` formals but I don't think we must do that.

Note though that we *do* allow call-expr temporaries/nested calls to pass to `ref` formals for arrays. E.g. this compiles

``` chapel
proc f(ref x) { }
proc g() {
  var A:[1..10] int;
  return A;
}

f(g());
```

At some point in the language's history, the default intent for arrays was `ref`, and I think this rule came from that period. I do not know how hard it would be to tighten it up. But somehow for arrays specifically, this pattern does not bother me.

**Comment by bradcray** [comment]
> At some point in the language's history, the default intent for arrays was ref,

Just to make sure we're all on the same page, the default argument intent for arrays is still `ref`, isn't it?  I think it's funkier for `this` arguments of array type but for vanilla arguments, simply `ref`.  Unless you meant the default return intent for arrays, which... I don't remember the history of.

**Comment by vasslitvinov** [comment]
> the default return intent for arrays

In our previous lives it was `ref` as well. The motivation was to avoid copying an array unless explicitly requested by the user. We used reference counting to figure out when a locally-created array should be deallocated.

**Comment by mppf** [comment]
The default argument intent for arrays is `ref` or `const ref` depending on whether or not the array is modified in the body of the function. It is described in [this spec section](https://chapel-lang.org/docs/master/language/spec/procedures.html#default-intent-for-arrays-and-record-this). Of course it is reasonable to simplify and say these are both more or less `ref` but the distinction between `ref` and `const ref` matters for the present discussion since there are several people arguing that non-lvalues should not be mutable.

**Comment by bradcray** [comment]
Ah, I read that portion of the spec before posting my previous comment, but read it as "default intent for array and record `this` rather than "default intent for arrays; and for record `this`".

**Comment by vasslitvinov** [comment]
I propose to stabilize the following behavior for 2.0:

1. anything can be passed to a `const ref` formal argument
2. anything can be yielded by a `const ref` yield intent
3. an array returned by value can be passed to a `ref` formal argument; generalization: any expiring array temp

Rationale:
1. is mostly the existing behavior that the comments on this issue support
  my proposal adds passing params and literals to `const ref` arguments -- this is for consistency, as the comments on this issue express surprise for why it is not working
2. this is the yielding counterpart of 1.
  certain cases here were disabled in #21732 because "it is easier to enable later if we decide to do so", however they will work properly if re-enabled in the current compiler
3. this is to enable passing a result of a function to another function by the default intent when such result is generic

This slightly widens the set of programs allowed today. This widening is motivated by common sense rather than specific user requests.

**Comment by dlongnecke-cray** [comment]
I feel really weird about (2) as I feel like it hangs too much on our iterator implementation. I'm OK with 1 & 3.

**Comment by vasslitvinov** [comment]
> I feel really weird about (2) as I feel like it hangs too much on our iterator implementation

In my view this has nothing to do with our implementation. For example, consider this:
```chpl
proc myProc(const ref arg:int) { }
myProc(5);
```
How can this possibly work? A: by storing 5 in a temporary local variable and passing a reference to that variable into myProc(). In other words, within myProc `arg` is a const reference to an implicit variable that lives inside the caller's stack frame for the duration of the call expression.

For (2), all we need is to translate it into an iterator + loop:
```chpl
iter myIter() const ref { yield 5; }
for idx in myIter() { }
```

How can this possibly work? A: by storing 5 in a temporary local variable and yielding a reference to that variable into the loop body. In other words, within the loop body `idx` is a const reference to an implicit variable that lives inside the iterator's stack frame for the duration of the yield statement.

The only piece of "implementation" that we depend on is these temporaries. However, by giving a proper definition like the above, we lift them from "implementation" to "semantics." Also, observe that they are not specific to iterators and that we already [define them for other purposes](https://chapel-lang.org/docs/1.30/language/spec/variables.html#deinit-points).

**Comment by dlongnecke-cray** [comment]
I should say: I feel weird about (2) because it means that local variables in an iterator have the lifetime of the iterator. Does the spec already say this? If so, I'm OK with (2).

**Comment by mppf** [comment]
@dlongnecke-cray - we are talking about the iterator elements specifically in #21888 (and have an ad-hoc team considering it). My own view is that it is part of the fundamental nature of iterators that local variables (or temporaries) will exist throughout the loop they are driving.

Even if you imagine that there is a temporary created that will be destroyed at the end of the statement, that seems OK to me:

``` chapel
iter myIter() const ref {
  for x in 1..10 {
    yield 5;
  }
}
for idx in myIter() {
  f(idx);
}

// becomes this with the temporary
// (and imagining that destroying it does something which is not the case for an int)

iter myIter() const ref {
  for x in 1..10 { 
    var tmp = 5;
    yield /* const ref to */ tmp;
    destroy tmp;
  }
}
for idx in myIter() {
  f(idx);
  // no need to destroy idx because it is const ref
}

// and then it becomes this with iterator inlining

for x in 1..10 {
  var tmp = 5;
  const ref idx = tmp;
  f(idx);
  destroy tmp;
}
```

So the local variable in the iterator can have whatever lifetime makes sense in the iterator and it is OK. The non-inlined case has the various actions occuring at similar times. Are you worried about some other case?

**Comment by vasslitvinov** [comment]
> local variables in an iterator have the lifetime of the iterator. Does the spec already say this?

Turns out, the spec spells it out nicely: https://chapel-lang.org/docs/1.30/language/spec/iterators.html#the-yield-statement

Also, my common sense expects the following iterators to yield [references to] values 0, 1, 2, which would not work without `i` outliving the yield statement:
```chpl
iter i1()     {  var i = 0;  while i < 3 { yield i; i += 1; }  }
iter i2() ref {  var i = 0;  while i < 3 { yield i; i += 1; }  }
```

**Comment by dlongnecke-cray** [comment]
OK, I am fine with 1-3.

**Comment by mppf** [comment]
I'm on board with 1 and 2. For 3, I think we should think more about it in the context of #21398. In particular, if we end up removing ref-maybe-const, the default intent for arrays will just be `const ref`, and then we will probably not need the special behavior for (3). Either way, I think that we should think about changing this special behavior for (3) in some way because it is currently pretty strange.

**Comment by mppf** [comment]
> an array returned by value can be passed to a ref formal argument; generalization: so can be any expiring array temp

I've created #22330 asking about what we should do about the special rule for functions returning arrays.

**Comment by mppf** [comment]
PR #22816 removed the ability to pass a nested call-expr to a `ref` formal with arrays. (It still allows it for array views, but that has more to do with how they are implemented today than anything else & they are reference-like by nature).

That leaves the question of whether or not it's legal to pass a `param` to a `const ref` formal.

The current situation is:
 * it is not allowed for numeric param values (e.g. `1`)
 * it is allowed for param `bytes` and `string` (e.g. `"hello"`)
 
Nonetheless, on this issue, there seems to be broad agreement to make it legal. Because the implementation change is trivial, I went ahead and created a PR with that implementation change: https://github.com/chapel-lang/chapel/pull/23055 .
