### ISSUE TITLE
Can't create array over int(8) domain with more than 127 elements

### ISSUE THREAD

**Issue by cassella** [chapel-lang/chapel#17264]
### Summary of Problem

**Source Code:**

```chapel
var lo = -0x1:int(8);
var hi = 0x7e:int(8);
writeln((lo,hi));

var A : [lo..hi] int;
writeln(A);
```

```
(-1, 126)
$CHPL_HOME/modules/internal/ChapelBase.chpl:960: error: Attempting to allocate > max(size_t) bytes of memory
```

I added a `writeln(size)` to `ChapelBase.chpl`, which reports `-128`.

It works if hi is `0x7d`, reporting a size of `127`.

**Associated Future Test(s):**

None yet.

### Configuration Information

```
chpl version 1.24.0 pre-release (57a3573b44)

CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: gnu
CHPL_TARGET_ARCH: x86_64
CHPL_TARGET_CPU: native *
CHPL_LOCALE_MODEL: flat
CHPL_COMM: gasnet *
  CHPL_COMM_SUBSTRATE: udp
  CHPL_GASNET_SEGMENT: everything
CHPL_TASKS: qthreads
CHPL_LAUNCHER: amudprun
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: cstdlib
  CHPL_NETWORK_ATOMICS: none
CHPL_GMP: none
CHPL_HWLOC: bundled
CHPL_REGEXP: re2
CHPL_LLVM: none
CHPL_AUX_FILESYS: none

gcc (Ubuntu 10.2.0-13ubuntu1) 10.2.0
```

**Comment by bradcray** [comment]
Thanks for filing this, Paul.  I hit this recently as well (but apparently didn't file an issue for it?).  Potentially obvious, but I believe the core issue is that we tend to use `idxType` to store/compute on sizes, in part because I think the `.size` query on arrays tends to return `idxType` currently.  We've recently been talking about changing `.size` queries to always return `int` by default, and to have another query (like `.sizeAs(type t)`) that would permit the user to request a different size value (for cases like a uint-indexed array whose size exceeds `max(int)`—rue the day—or someone just wanting the size as a different integer without having to downcast).  I suspect that once we implement this plan, it would also resolve this issue.

**Comment by bradcray** [comment]
I've now verified that this will be fixed by #17628.

**Comment by bradcray** [comment]
@casella: Just wanted to note that this should be fixed now, and if you remember what caused you to bump into it and want to return to it, you should be able to now.  Give a shout if you find other problem cases that I missed.

**Comment by bradcray** [comment]
Argh, not @casella, but @cassella!  [edited the above, but didn't catch it fast enough—sorry @cassella!]

**Comment by cassella** [comment]
One more stamp on his card and you'll have to add him to the Contributors list.

**Comment by bradcray** [comment]
I know, I definitely feel like I owe him a few drinks...  <shame>

**Comment by cassella** [comment]
I don't remember exactly what I was trying to do, but it was probably something like passing an array like that `A` to `shellSort()`.  I don't remember for sure, but I think I convinced myself that the tests I ended up with would exercise the same case I was trying to hit there.  ([2/24 comments](https://github.com/chapel-lang/chapel/pull/17041#discussion_r582533367))
