### ISSUE TITLE
The spec lists unary & as an overridable operator, and doesn't list (binary) align or #

### ISSUE THREAD

**Issue by cassella** [chapel-lang/chapel#17337]
`doc/rst/language/spec/procedures.rst` has a table of operators that may be overridden:

```rst
Operator overloading is achieved by defining a function with a name
specified by that operator. The operators that may be overloaded are
listed in the following table:

arity    operators
======== ===============================
unary    ``&`` ``+`` ``-`` ``!`` ``~``
binary   ``+`` ``-`` ``*`` ``/`` ``%`` ``**``
binary   ``==`` ``<=`` ``>=`` ``<`` ``>``
binary   ``<<`` ``>>`` ``&`` ``|`` ``^`` ``by``
binary   ``=`` ``+=`` ``-=`` ``*=`` ``/=`` ``%=`` ``**=``
binary   ``&=`` ``|=`` ``^=`` ``<<=`` ``>>=`` ``<=>`` ``<~>``
```
Should the unary `&` be on that list?  Though I can define an `operator &(x: int)`, I can't invoke it either as prefix or postfix.

The table lists `by`, but not `align`.  I can define an `operator align(x: int, y: int)` and invoke it using infix notation.  Likewise `#`.  Are these intended to be overridable?

**Comment by mppf** [comment]
I thought that `&&` and `||` were also overrideable but I haven't checked.

**Comment by bradcray** [comment]
> I thought that && and || were also overrideable but I haven't checked.

It wouldn't completely surprise me if the short-circuiting operators (`&&` and `||`) were not user-overloadable since it's challenging to write a user-level routine that lazily evaluates its second operand (and/or unclear whether that lazy behavior should extend to user-defined overloads of these operators or not).

> Though I can define an operator &(x: int), I can't invoke it either as prefix or postfix.

Since Chapel doesn't support unary-`&` (right?), it's not surprising to me that you can't invoke it in that way.  From what I've seen recently, most of the operators don't do any checking to see if it's a form that we expect and can parse (e.g., I believe you can define a 0-argument or 4-argument `+` operator and just won't be able to invoke it).  The one case I'm aware of that does check the number of arguments doesn't get it correct in an operator method context ( #17325).

> The table lists by, but not align. 

I agree that `align` and `by` should be treated consistently, but don't feel strongly whether they should or should not be user-overloadable at present.  If they both work, then they should be added to the table, I'd say.

**Comment by cassella** [comment]
It turns out `&&` and `||` can not be overridden -- parse error writing `operator &&(` or `operator ||(`.

I'll open a PR bringing the spec into alignment with the compiler.
