### ISSUE TITLE
What determines the color of keywords in chpldoc output?

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#17386]
In chpldoc output (created by sphinx / pygments), some Chapel reserved words are green while others are blue.  For example, see: https://chapel-lang.org/docs/1.24/language/spec/lexical-structure.html#keywords

<img width="450" alt="Screen Shot 2021-03-09 at 2 27 32 PM" src="https://user-images.githubusercontent.com/7536222/110546658-a2ab5100-80e3-11eb-8e96-818bb9b47788.png">

What causes this choices and why are related keywords (like cobegin, begin, and coforall) rendered using different colors?

What rule of thumb would we want to use in choosing these colors?  (I tend to have the mentality that fewer colors for broader categories is preferable to more colors for narrower categories because once there are too many colors, I spend all my time trying to determine the pattern rather than read the code.  I've also rarely found the use of more than 3-4 colors/styles to be helpful rather than harmful).

**Comment by Venkatavaradan-R** [comment]
Hi @bradcray 

I had a quick look into this and this is what I have found so far:
sphinx uses pygments for its syntax highlighting as you mentioned.

>  What causes these choices and why are related keywords (like cobegin, begin, and coforall) rendered using different colors?

The pygments library has an in-built lexer for all the libraries they support, of which chapel is one. This is where the different keywords get grouped (as usual in the lexing process). The lexer can be found [here](https://github.com/pygments/pygments/blob/master/pygments/lexers/chapel.py)

The colors that are used for each group works with the help of different [Pygments styles](https://pygments.org/docs/styles/). There are a bunch of pre-defined styles, but Pygments (and sphinx by extension) also gives us the option to create our own 
[custom styles](https://pygments.org/docs/styles/#creating-own-styles). This can be easily incorporated into the build process by simply changing one argument  (`pygments_style`) in the base/root sphinx configuration file, [doc/rst/conf.py](https://github.com/chapel-lang/chapel/blob/master/doc/rst/conf.py) once we have created the custom style.

``#pygments_style = 'sphinx'` (been commented out)
As of now, no style has been specified.

> What rule of thumb would we want to use in choosing these colors? (I tend to have the mentality that fewer colors for broader categories are preferable to more colors for narrower categories because once there are too many colors, I spend all my time trying to determine the pattern rather than read the code. I've also rarely found the use of more than 3-4 colors/styles to be helpful rather than harmful).

I agree with this totally. Fewer colors > More colors. I think what colors they should be, comes down to personal preference. I like the pygments [Vim style](https://help.farbox.com/pygments.html) but with green instead of yellow.

**Comment by bradcray** [comment]
@Venkatavaradan-R : Thanks for looking into this.  I'm still missing something, though:  In the lexer you point to, it appears to me that `cobegin` and `coforall` are defined within the same category; so that's why it was unclear to me why they would be rendered as different colors.  Is that clear to you?

**Comment by Venkatavaradan-R** [comment]
Oh, I didn't notice that... looks like I'm still missing something here.
I'll do some more digging and get back to you.

**Comment by e-kayrakli** [comment]
I don't think the issue is the pygments lexer. You can run `pygmentize -s -l chapel` and type keywords and see how they are highlighted differently (assuming your terminal supports color output). It is not the most foolproof way, but there you can see that `cobegin` and `coforall` are highlighted the same, whereas `int` is highlighted differently.

I thought it maybe something special we do in sphinxcontrib-chapeldomain, but quick grep doesn't show anything interesting.

**Comment by bradcray** [comment]
Oh, interesting...  And I'm seeing that if I leaf through the spec itself, all keywords seem to be rendered green consistently.  So the issue seems somehow specific to the keywords list itself.  Ah, here's my guess:  The lexer expects keywords like `class` to be followed by the identifier being declared and will color the declared identifier a different color; so since `cobegin` happens to follow `class`, it gets this treatment.  The other cases are after `module`, `record`, and `union` (I was expecting `const`, `var`, `type`, and `param` to also have this effect, but it seems not).

So then maybe the question is whether there's a way we could override the highlighting for the keywords list itself so that other readers don't trip over this as I did?

**Comment by Venkatavaradan-R** [comment]
I played around with the [lexical-structure.rst](https://github.com/chapel-lang/chapel/blob/master/doc/rst/language/spec/lexical-structure.rst) file a bit and the problem is definitely what you've mentioned:
> The lexer expects keywords like `class` to be followed by the identifier being declared and will color the declared identifier a different color

I thought of a quick fix, which is to use a separate code block for each keyword which fixes the problem, but isn't easy on the eyes or very efficient:
![Screenshot from 2021-03-16 03-05-27](https://user-images.githubusercontent.com/44594675/111224504-8d16b980-8604-11eb-8fd4-8e53f6c4af80.png)


Another possibility is to use inline syntax highlighting which is provided by sphinx as an [extension](https://sphinxcontrib-inlinesyntaxhighlight.readthedocs.io/en/latest/#:~:text=Docutils%20supports%20inline%20syntax%20highlighting,code%20blocks%20and%20inline%20code).). This looks like it should give us exactly what we want without having to go through too much trouble. There are some weird errors cropping up when I try it, but I'll fix it and make a PR if everything is fine.

As for
> the question is whether there's a way we could override the highlighting for the keywords list itself
I couldn't find much but I will explore that possibility if the inline syntax highlighting doesn't work out.

**Comment by lydia-duncan** [comment]
> As for
> 
> > the question is whether there's a way we could override the highlighting for the keywords list itself
> 
> I couldn't find much but I will explore that possibility if the inline syntax highlighting doesn't work out.

We could maybe just make it a code block without specifying a language or specifying txt or something and that would cause none of them to get highlighted (which I think would be better?)

**Comment by bradcray** [comment]
Thanks for wrestling with this @Venkatavaradan-R!  I'd hoped that your quick solution was only not easy on the developer's eyes who was editing the .rst, but I agree that the rendered output isn't very nice.

If your approach doesn't work, two other things we could consider:

* turn off the highlighting of the identifier that follows `class` and friends.  I don't know how important this is for the documentation personally (and it seems weird already that we do it in some cases but not others)
* define a second domain that is like `chpl` but doesn't distinguish between these classes of keyword and use it in this one spot (though that sounds like a maintenance nightmare).
* I just saw Lydia's suggestion as I was typing this and am very open to it as well.  In fact, it may be my favorite amongst all these (since coloring the words in this list seems very unimportant; if we wanted to distinguish the types or other classes, we should arguably just make multiple lists anyway).

Mostly: Now that I know this is restricted to this one setting and not all of the documentation, I'm much less worried about it.  If there's a quick / easy fix, I think that'd be nice.

**Comment by e-kayrakli** [comment]
> Oh, interesting... And I'm seeing that if I leaf through the spec itself, all keywords seem to be rendered green consistently. So the issue seems somehow specific to the keywords list itself. Ah, here's my guess: The lexer expects keywords like class to be followed by the identifier being declared and will color the declared identifier a different color; so since cobegin happens to follow class, it gets this treatment. The other cases are after module, record, and union (I was expecting const, var, type, and param to also have this effect, but it seems not).
>
> So then maybe the question is whether there's a way we could override the highlighting for the keywords list itself so that other readers don't trip over this as I did?

Ah good catch!

Then I think the ideal solution is fixing sphinxcontrib-chapeldomain. It looks like we do that special casing here:

https://github.com/chapel-lang/sphinxcontrib-chapeldomain/blob/master/sphinxcontrib/chapeldomain/__init__.py#L271-L276

we can either (similar to what Brad is suggesting above):

1. check if the class "name" is another keyword, and if so stop special casing here (but this shouldn't happen very often?)
2. somehow skip the lexical structure file while doing this operation here (too workaround-y)
3. have a special code block for just using naive lexing avoiding these context checks, and use that block for that list of keywords (looks ideal, I don't know how much effort it is, and I don't think this issue worths too much effort) -- similar to Brad's 2nd bullet, I am realizing.

I don't have a preference between 1 and 2. Unless 3 is easy, I am against it. Among the other ideas above, I like Lydia's "let's not highlight that block" the best.

**Comment by Venkatavaradan-R** [comment]
Hi mentors!
Sorry about the delay, I've got my midterm tests going on so I was a bit caught studying for that.

I've tried out a bunch of stuff and here are the results:

1. 
> check if the class "name" is another keyword, and if so stop special casing here (but this shouldn't happen very often?)

I tried changing the [sphinxcontib-chapeldomain init file](https://github.com/chapel-lang/sphinxcontrib-chapeldomain/blob/master/sphinxcontrib/chapeldomain/__init__.py) and modified it to empty `return` whenever `name` is a keyword.

This doesn't work. I can't return null as the return value is being indexed [here](https://github.com/chapel-lang/sphinxcontrib-chapeldomain/blob/master/sphinxcontrib/chapeldomain/__init__.py#L351) and used for cross-referencing. I can continue working on this, but It may take some time as I need to fully understand the codebase before making any big changes.

2.
> Define a second domain that is like chpl but doesn't distinguish between these classes of keyword and use it in this one spot (though that sounds like a maintenance nightmare).

This seems to be unnecessary unless it will be used somewhere else in the future and I can't think of any other scenario where that would happen.

3.
> Another possibility is to use inline syntax highlighting.

I tried this as well, but it doesn't seem to work for some reason. If anyone knows what's happening please let me know. 

`.. role:: chplcode(code)
   :language: chapel


this is some chapel code :chplcode:\`coforall\`

`
It compiles and runs but the code isn't syntax highlighted. For more, see [ReST Roles](https://docutils.sourceforge.io/docs/ref/rst/roles.html#code).

4.
> We could maybe just make it a code block without specifying a language or specifying txt or something and that would cause none of them to get highlighted (which I think would be better?)

This worked like a charm and took 30 seconds to implement. Doesn't look half bad.
![Screenshot from 2021-03-17 07-21-48](https://user-images.githubusercontent.com/44594675/111402596-7ac67980-86f1-11eb-9bcb-6c7eb04a9f6f.png)


So for now, the question is, should I continue exploring these possibilities or should I make a PR with just a text block?

**Comment by e-kayrakli** [comment]
FWIW, my vote is to make it a text block with no highlighting.

**Comment by lydia-duncan** [comment]
Yeah, any other solution would be a lot more work for a special case that I don't think normal users of chpldoc would encounter

**Comment by bradcray** [comment]
I agree, thanks for investigating @Venkatavaradan-R!

**Comment by Venkatavaradan-R** [comment]
Awesome!

> thanks for investigating @Venkatavaradan-R!

My pleasure. I quite enjoy this! :smile:
