### ISSUE TITLE
date and datetime compatibility

### ISSUE THREAD

**Issue by king-11** [chapel-lang/chapel#17439]
after moving forward with the implementations of issue #16552 will probably need to ensure that both date and datetime use similar time zone information. For example

- ```date.today()``` doesn't consider localtime while ```datetime.today()``` does which can be an issue in operation involving the date and datetime.

I haven't yet checked which other functions will need to take into context localtime as well probably there can be a few others too.

**Comment by lkmeta** [comment]
I think that they both use the same time zone and there is no issue according to this. They both use `timeSinceEpoch = getTimeOfDay(); ` ([1st one](https://github.com/chapel-lang/chapel/blob/1108202e645de1bcbfe7d3a5130799d5c01c8ad8/modules/standard/DateTime.chpl#L286) and [2nd one](https://github.com/chapel-lang/chapel/blob/1108202e645de1bcbfe7d3a5130799d5c01c8ad8/modules/standard/DateTime.chpl#L930)) in order to find the current date and time that's why I think there is no problem with that. Of course, I hope I don't miss anything in what I've seen so far.

**Comment by king-11** [comment]
@lkmeta if you check the ```datetime.now``` function it used ```getlocaltime``` while ```date.today``` doesn't that's where the difference lies. And if you are on the gutter channel I also posted the results of running program over there.

**Comment by riftEmber** [comment]
It looks like this never much attention, including what I was able to find in the gitter chat logs. It looks like the root cause OP identified would still be present in the code today as we use `getLocalTime` only in `dateTime.now`.

That said, I haven't tried to reproduce the error, and from the gitter chat it seems dependent on the user's time zone (and I would guess also the time at which it is run). So reliably reproducing, if still possible, will likely require manipulating the system time information Chapel is exposed to.

I'm not investing the time to investigate this bug yet, but confirming it still seems worth trying to reproduce at some point and see if it's a current problem.

**Comment by riftEmber** [comment]
Ran into this while working on https://github.com/chapel-lang/chapel/pull/23114; noting it might be intentional that `dateTime.now` uses localtime while `dateTime.utcNow` doesn't (and would behave correspondingly to `date.today`).

**Comment by riftEmber** [comment]
With https://github.com/chapel-lang/chapel/pull/23176 I believe the last instance of inconsistencies is resolved, so current-time querying methods that don't have `utc` in the name all use local time, and those with `utc` use UTC time. The PR also updates documentation to clarify the different behaviors.

**Comment by king-11** [comment]
Great to see this getting resolved 😄
