### ISSUE TITLE
Deprecate proc= and/or create() in the Shared Module

### ISSUE THREAD

**Issue by slnguyen** [chapel-lang/chapel#17461]
Since assignment ('proc=') can effectively do the same thing as `create(shared)` can we deprecate the `create(shared)` function? Alternatively, should we keep the `create(shared)` function and remove the analogous assignment?

**Comment by bradcray** [comment]
@slnguyen : To make this a bit more concrete, would you add an illustrating example showing how each form would be used in practice?

**Comment by slnguyen** [comment]
I haven't used this module myself so I'm not sure if this example is how the shared module would typically be used, but here's an example motivating the issue. In the example `block1` uses assignment and `block2` uses `create(shared)`. In both cases `shared1.x` outputs the value of `shared2.x` after assignment/`create(shared)`.
```
class C { var x:int; }
  
{//block1
var shared1 = new shared C(1);
writeln("shared1.x: ", shared1.x); //output is 'shared1.x: 1'
var shared2 = new shared C(2);
writeln("shared2.x: ", shared2.x); //output is 'shared2.x: 2'
shared1 = shared2;
writeln("shared1.x: ", shared1.x); //output is 'shared1.x: 2'
}

{//block2
var shared1 = new shared C(1);
writeln("shared1.x: ", shared1.x); //output is 'shared1.x: 1'
var shared2 = new shared C(2);
writeln("shared2.x: ", shared2.x); //output is 'shared2.x: 2'
shared1 = shared.create(shared2)
writeln("shared1.x: ", shared1.x); //output is 'shared1.x: 2'
}
```

**Comment by bradcray** [comment]
The `shared.create()` form definitely seems superfluous in this case to me, though I can understand how it might be useful in other cases to turn an owned or unmanaged classes into a shared class.  And I can almost imagine that in a completely generic context where we might not know what flavor of class we're receiving, it would permit us to have a uniform way of turning things into `shared` (though I'm not sure how common or uncommon that pattern will be—"I don't know what this is, but I want to make it into a shared...").

@vasslitvinov, as the implementer of this overload, can you provide any further rationale for its benefit?

**Comment by vasslitvinov** [comment]
> [Why a `shared.create()` overload for `shared` ?]

#15119 claims "The argument types are allowed as follows, to match what was allowed using the deprecated forms".

Cf. to the best of my recollection, I added it because "this operation makes sense so let's implement it".

I agree with Sarah that we can deprecate it.

**Comment by bradcray** [comment]
> Are you thinking that assignment operators should never be forwarded?

For records containing forwarding fields, I'd generally expect that the compiler-generated `=` operator on the record would be chosen over forwarding to a field's `=` operator.  For classes containing forwarding fields, I'd hope that we'd use the default class `=` definition ("are these class variables pointing to the same object?") rather than forwarding.  So in the general case, I'm hoping no special-casing is required.

For owned/shared, I'm not sure I'm understanding the issue.  When you say "if we merely remove assignment operators", are you saying "if, in some future, we chose to no longer support any `=` operators between these types..."?  Though the OP here says that's an option (for one specific pattern, I think, not all of them?), has anyone seriously thrown weight behind deprecating all `=` operators on these types?

Could you provide an example showing the case that's feeling concerning to make it more concrete?

**Comment by lydia-duncan** [comment]
> > Are you thinking that assignment operators should never be forwarded?
> 
> For records containing forwarding fields, I'd generally expect that the compiler-generated `=` operator on the record would be chosen over forwarding to a field's `=` operator. For classes containing forwarding fields, I'd hope that we'd use the default class `=` definition ("are these class variables pointing to the same object?") rather than forwarding. So in the general case, I'm hoping no special-casing is required.
> ...
> 
> Could you provide an example showing the case that's feeling concerning to make it more concrete?

I was running into a specific case where some combinations of owned/shared/unmanaged/borrowed that are explicitly not supported on main today were accidentally getting enabled because extending forwarding to support operators meant that "failing to find an assignment operator between owned Foo and borrowed Foo" (for instance) led to looking for an assignment operator between Foo and Foo (which does exist).  In code, the following program used to fail with the message `Cannot assign to owned MyClass from borrowed MyClass` but with forwarding operators generally would "pass" (which seemed wrong to me):

```chapel
class MyClass {  var x: int;  }

var lhs = new owned MyClass();
var rhs = new borrowed MyClass();

lhs = rhs;
```

I took that problem one step further - if my solution to it ended up being option 2, then any attempts to later remove other assignment operators would run into the same problem if we deprecated the assignment operators that "work" with this change and try to rely on failing to resolve the assignment operator.  Basically, I was hoping to find a solution that was future proof and to leave sufficient breadcrumbs for future developers on how to solve the problem if we didn't find a better solution - I think explicitly not forwarding assignment operators at all is sufficiently future proof.

> 
> For owned/shared, I'm not sure I'm understanding the issue. When you say "if we merely remove assignment operators", are you saying "if, in some future, we chose to no longer support any `=` operators between these types..."? Though the OP here says that's an option (for one specific pattern, I think, not all of them?), has anyone seriously thrown weight behind deprecating all `=` operators on these types?

Not that I know of.  As I said, this was partially in case we try to change our mind in the future and partially to get more insight from folks that know owned/shared/etc better than I.

**Comment by mppf** [comment]
IMO the situation described in #20336 argues for removing `.create` in favor of using `=` (because a user might want to have a `.create` method on their class).

**Comment by mppf** [comment]
I'm closing this issue because:
 * I can't imagine that we'd want to deprecate `mySharedC = myOtherSharedC`
 * It's a bit unclear to me what this issue is asking
 * I've made #20648 about what we should do with `owned.create` and `shared.create`. What I understand to be the main point of this issue is covered as "Case 1" there.
