### ISSUE TITLE
New argument in map.getValue()

### ISSUE THREAD

**Issue by strikeraryu** [chapel-lang/chapel#17498]
## Summary of Problem
Currently, getValue() returns the element or returns the pre-initialized value if parSafe=false, so if the user wants to use map he has to check if an element exists and then initializing a value else changing store value, which is used a lot when working with maps.

## Solution
An overloaded version of the current ```getValue()``` function will be created where there will be an extra argument 'sentinel' will be added that will be returned if a key doesn't exist in the map

``` chapel
proc map.getValue(key) { ... }    // this is the routine as it exists today

proc map.getValue(key, sentinel) { ... }  // returns 'sentinel' if the key is not found
```
providing a 'sentinel' value will provide more robust usage.

eg,
``` chapel
map[key] = map.getValue(key, 0) + 1   // there is no more need to create extra fail safe condition 
```

**Comment by souris-dev** [comment]
(This looks like quite interesting, after going through the Gitter discussion).
This feature is certainly going to be quite helpful, but in some contexts one might want to have an error thrown instead. 
I'd be more interested having an overload of `getValue()` (or we could change the names as well to make this behaviour clearer) - one throwing an error and the other taking a sentinel - as @bradcray suggested.

That'd would provide better control.

**Comment by strikeraryu** [comment]
I also think we should add both options available so a person can choose in his meantime -@bradcray talked about. Our aim is to make a function that eliminates the code and provides quick usage but if we think other way and trying to add both options in one function might overcomplicate things which might defeat the purpose of having an option of returning sentinel. 
So I think we should create another function with a changed name as suggested by @souris-dev rather than overloading, which might further simplify things at the time of production.

**Comment by bradcray** [comment]
I was proposing simply doing:

```chapel
proc map.getValue(key) { ... } // this is the routine as it exists today

proc map.getValue(key, sentinel) { ... }  // returns 'sentinel' if the key is not found
```

To me, these signatures seem different enough that it wouldn't be terribly confusing to have them share the same name.  They could have different names as well, but I wonder whether it would just add more typing for something that doesn't warrant it.  This is a situation where I'd look at what [parallel] maps in other popular languages support for inspiration.

The question as to whether the non-sentinel value should halt or throw on error is a classic and tricky one that comes up in other situations as well (e.g., array indexing), where the tradeoffs are (a) overhead in terms of performance and/or catch blocks in the throwing version, (b) annoyance of having a program halt in the halting version.  Here's one team member's opinion/guidance on the topic:  https://github.com/chapel-lang/chapel/issues/10703  I keep wishing for some sort of cool design or pattern in which a user could choose between throwing and halting versions of such functions easily / productively, but I haven't come up with anything or seen anything that feels attractive and tractable yet.

**Comment by strikeraryu** [comment]
I may ask something so we are on the same page, exactly what we are talking about when we say halting. @bradcray

**Comment by bradcray** [comment]
Exiting the program with an error message.  This is what happens today when you do:

```chapel
var A: [1..10] real;
writeln(A[11]);
```

or:

```chapel
var m: map(string, int);
writeln(getValue("brad"));
```

today, for example.  In the case of array accesses, we decided that having them throw on OOB accesses was too impactful from a performance and productivity perspective, so have taken the halting behavior, with the ability to turn checks off for performant code.  I suspect the halting behavior in map was done for similar reasons, though I don't recall how much discussion or debate there was around whether throwing would be more appropriate.  I think it could be argued that maps are higher-level data structures than arrays, so could have different behavior, but I don't recall whether we've had that debate or not.

This general tension is what makes me want to "have my cake and eat it too"—have a solution that permitted either behavior by reading the user's mind and determining what would make them most happy (or let them choose without too much impact on their code).

**Comment by strikeraryu** [comment]
Yeah, that makes sense now. and again programming comes to a point when it takes more time to think about what users want than to implement that😅.

**Comment by bradcray** [comment]
> it takes more time to think about what users want than to implement that.

Sure, and the problem of course is that different users will want different things.  To be clear, I'm not suggesting we have to solve the halt vs. throw question in this issue per se, or to hold up making this improvement over the question.  I was just mentioning the challenge because @souris-dev brought up throwing.

I think the next step for this issue's specific proposal to proceed would be to (a) update the OP to make the proposal a bit more concrete (e.g., are we going with the two-overloads approach that I proposed above, or something else?  maybe sketch out the documentation + header for the proposed routine(s)), and then (b) for someone to kick off a design discussion (say on Discourse) to get reactions to the proposal from the broader team or community and see whether there are any.  Before doing that, we could also collapse down some of these comments that are a bit more meta to avoid confusing the discussion.

**Comment by strikeraryu** [comment]
I will update the issue, Can you explain the second part of (a) a bit
> sketch out the documentation + header for the proposed routine(s)) 

So I will work on it, and also where to share it?

**Comment by e-kayrakli** [comment]
I can see that this can improve the usability of `map`. My worries are around similar getters and whether/how we can support such sentinel arguments for those.

Specifically:

- `getAndRemove` sounds like we can add a similar overload, where if the returned value is the sentinel, it would imply that nothing was removed from the map
- `getReference`/`getBorrowed`: I am not sure if there's a sensible way of adding a similar overload for these.

Even if we cannot add this overload for some of them, I am not really against this proposal. Nonetheless, the asymmetry is kind of a drawback to me.

**Comment by bradcray** [comment]
> the asymmetry is kind of a drawback to me.

Eh, I don't know that I agree with this.  Wanting everything to halt equally annoyingly on an OOB error doesn't exactly seem like a virtue...  (i.e., I'd never argue "Why provide a safe way of protecting against some failure modes if we can't provide a safe way of protecting against all failure modes?"  These are obviously "more of a kind", but I don't think that's a reason to avoid making some of them better).

For `getBorrowed` (a routine that's already asymmetrical by definition, since it only applies to classes), if it's a collection of nilable classes, it seems as though the user could pass in `nil` as the sentinel?  (or perhaps the current routine should just return `nil` rather than halting in such cases without the user needing to pass a value in?)  Even in the case that it's not nilable, couldn't the user pass in a class reference, the routine could return a borrow of that class reference, and they could check it against the one they passed in?

It seems as though `getReference` could also take in a sentinel value by `ref` and return that sentinel value by `ref`?  Though since it's only available on `parSafe=false` maps, it also doesn't seem as strictly necessary to me (in that if you check for membership before making the call, there's no way the map could change out from under you before making the getReference() call if you're using it in a parallel-safe way).

**Comment by dlongnecke-cray** [comment]
I am torn between this and just throwing/catching errors. To me returning a sentinel feels kind of ugly, not to mention potential `inout` copying issues. Not to say that throwing isn't also ugly, but this kind of feels like what it was made for.

I think what is ugly is not that we should throw, but that the syntax for handling it is cumbersome.

Having to do:


```chapel

try {
  var v = myMap.getValue(0);
} catch IndexError: e {
  // Error, sentinel, whatever...
}
```

It would be nice if we could just do something like:

```chapel
var v = try m.getValue(0) else 1;
```

**Comment by dlongnecke-cray** [comment]
Anyhow, there's lots of elegant ways of solving this that don't exist in the language today, and I don't want to just sit around wishfully thinking.

I think adding an overload that returns a sentinel would be fine. I don't think we need to be concerned about the cost of copying, because if a user is calling `getValue()` then they probably don't care about the cost of copying anyway.

**Comment by bradcray** [comment]
> I am torn between this and just throwing/catching errors.

@dlongnecke-cray : It seems to me that the question of throwing/catching pertains to the current version of `getValue()`, where we could choose to make it throw or not if we wanted, independent of this issue?  (yet for some reason chose to have it not do so?).  Even if it did throw, we could still support this overload without causing problems to support a different style?  (maybe this is where you came around to on your second post...?).  I suppose the main downside of this would be interface bloat.

> I would also suggest that we move away from using:

Good point.  I think there are plenty of uses for "if I don't find something then..." patterns outside of this specific case which happens to work today (changing the LHS map to `map2` for example :) ).

**Comment by dlongnecke-cray** [comment]
> @dlongnecke-cray : It seems to me that the question of throwing/catching pertains to the current version of getValue(), where we could choose to make it throw or not if we wanted, independent of this issue?

I think that throwing/catching is another way to solve this problem of "getValue() will halt if the key is not in the map". I would prefer it if the syntax were not so cumbersome.

I feel like this overload is trying to circumvent using exceptions to avoid their syntax when this is basically what exceptions were made to do. Maybe I'm not appreciating the usefulness of this overload enough outside of my preconception of "we're doing this to avoid a halt".

**Comment by strikeraryu** [comment]
> I feel like this overload is trying to circumvent using exceptions to avoid their syntax when this is basically what exceptions were made to do.

But adding this overload will give a user the option of using exception or sentinel value, for a normal flow of his program he can stay with exception control but providing this overload is like handling this exception inside the function which will eventually increase the usage for the user if he doesn't want to focus on the exception control. Yeah I agree the same outcome can be achieved with few steps but providing the function makes it more intuitive to use, and that was what functions suppose to do.

**Comment by king-11** [comment]
I agree with @dlongnecke-cray. I think this actually gets around just a simple if...else check which when applied ensures better control over the program because then action can be taken if the value doesn't exist, like throwing an error or manipulating data to add to the key which is a more pronounced case observed I have observed. Whereas returning a sentinel value can be done just by checking if it exists or not, which never seemed like a more hassle so to speak while using Map implementation in various languages.

**Comment by bradcray** [comment]
> Whereas returning a sentinel value can be done just by checking if it exists or not, which never seemed like a more hassle so to speak while using Map implementation in other languages too.

I worry that this doesn't work so well in parallel contexts because the map may change between the check and the use of the check.  I.e.,

```chapel
forall k in myCollection {
  if m1.contains(k) then
    process(m1.getValue(k));   // m1 may not contain `k` by now because some other task may have removed it since our `contains` check returned
  else
    process(sentinel value);
}
```

whereas the use of the sentinel value makes the `.getValue()` query logically atomic w.r.t. data structure, essentially.

**Comment by king-11** [comment]
> I worry that this doesn't work so well in parallel contexts because the map may change between the check and the use of the check. I.e.,
> 
> ```chapel
> forall k in myCollection {
>   if m1.contains(k) then
>     process(m1.getValue(k));   // m1 may not contain `k` by now because some other task may have removed it since our `contains` check returned
>   else
>     process(sentinel value);
> }
> ```
> 
I see the point that value might get changed if say the user is adding and removing keys simultaneously in a parallel program but that will already be a mess in terms of parallel variations that can occur and handling this to do something useful out of the program will be pretty difficult and particularly I can't think of a scenario when user will do something ( any examples that I am missing ? ). Moreover even if the user is adding and removing values the more predominant situation would that he does that in a sequential manner which I believe is safe from variations even in a parallel environment.

```chapel
forall k in myCollection {
  if m1.contains(k) then
    process(m1.getValue(k));   
  else
    process(sentinel value); // add to m1
}
// some more instructions
forall k in myCollection {
  if m1.contains(k) then
    process(m1.getValue(k));   // remove keys
}
```

**Comment by bradcray** [comment]
@king-11:

> that will already be a mess in terms of parallel variations that can occur

Are you considering the case when operating on a [`map(parSafe=true)`](https://chapel-lang.org/docs/modules/standard/Map.html#Map.map.parSafe) instance?

> the more predominant situation would be that he does that in a sequential manner

In a language designed for parallel computing?

**Comment by king-11** [comment]
> Are you considering the case when operating on a [`map(parSafe=true)`](https://chapel-lang.org/docs/modules/standard/Map.html#Map.map.parSafe) instance?

Yes even if ```map(parSafe=true)``` we can't be sure about the final output will obtain if we add and remove keys parallelly and the result obtained at each run will vary based on execution order.
> In a language designed for parallel computing?

😅  I didn't mean getting rid of parallelism by sequential I meant that the two kinds of tasks i.e. removal and addition of keys operate sequentially whereas task belonging to the same kind will take place parallelly.

**Comment by bradcray** [comment]
I'm giving this a bump today based on a user request.
