### ISSUE TITLE
[Library Stabilization] BigInteger methods overwrite their receiver rather than returning

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#17699]
The documentation indicates that this is better for performance.  Should we provide standalone versions that return a new `bigint` instead/in addition? Note that a lot of methods like this create a local copy of their arguments when the arguments are remote (and usually there are two arguments).  Should we rename them?  Should we add compiler support for translating less optimal (but more understandable) forms into optimal forms?  I personally find it a bit odd, though I understand the reason behind it.

Michael says:
> I think it'd be reasonable to consider naming things like proc bigint.add differently [to make it clear that these overwrite their arguments]. But I don't know what we would name them to that would 1) be clear to newcomers and 2) be something one could easily map to a GMP operation.

Nikhil also brought this issue up at https://github.com/chapel-lang/chapel/issues/17616#issuecomment-834053841 and there was some good discussion in https://github.com/chapel-lang/chapel/issues/17616#issuecomment-834247288, https://github.com/chapel-lang/chapel/issues/17616#issuecomment-834544569, and https://github.com/chapel-lang/chapel/issues/17616#issuecomment-834622585

Affected methods are:
- `bigint.divexact()`
- `bigint.powm()`
- `bigint.pow()`
- `bigint.rootrem()`
- `bigint.sqrt()`
- `bigint.sqrtrem()`
- `bigint.nextprime()`
- `bigint.gcd()`
- `bigint.lcm()`
- `bigint.remove()`
- `bigint.gcdext()`
- `bigint.invert()`
- `bigint.fac()`
- `bigint.bin()`
- `bigint.fib()`
- `bigint.fib2()`
- `bigint.lucnum()`
- `bigint.lucnum2()`
- `bigint.add()`
- `bigint.sub()`
- `bigint.mul()`
- `bigint.addmul()`
- `bigint.submul()`
- `bigint.mul_2exp()`
- `bigint.neg()`
- `bigint.abs()`
- `bigint.div_q()`
- `bigint.div_r()`
- `bigint.div_qr()`
- `bigint.div_q_2exp()`
- `bigint.div_r_2exp()`
- `bigint.and()`
- `bigint.ior()`
- `bigint.xor()`
- `bigint.com()`

**Comment by bradcray** [comment]
I think it's crucial for performance to have a way for users to guarantee they can re-use an existing `bigint` rather than always creating new ones.  That said, I've long wished that we had a story for writing things in the more "functional" / "operational" style without taking a performance hit.  My favorite example (that Michael gets to hear about every 10 months or so) is from the pidigits shootout benchmark where our entry tends to use code like:

```chapel
    tmp1.mul(numer, nth);
    tmp2.add(tmp1,accum);
    tmp1.div_q(tmp2, denom);
```

rather than:

```chapel
    tmp1 = numer * nth;
    tmp2 = tmp1 + accum;
    tmp1 = tmp2 / denom;
```

because the performance hit is so significant in the second form.

I think we should continue to support the operator versions of these ops because, in spite the perf hit, they end up looking so clean and it supports some generic programming with other integer types.  But I think we have to continue to support the "takes the result" forms of these routines until/unless we come up with a way to get rid of any performance delta and give users the confidence that nothing will be lost.  And I wouldn't create "returns the result" equivalents of the routines that don't have an operator form until we can make that performance guarantee, because I don't think the clarity is that much better, and I worry that it will cause more confusion among users about which they should use and what the tradeoffs are (we can also always add them later without it being a breaking change).

I don't have a strong opinion as to whether the "takes the result" forms should be standalone or rely on `this` as one of the arguments (where I think Nikhil was expressing a preference for the former?) or support both forms.

**Comment by lydia-duncan** [comment]
In the module re-review today, Brad suggested potentially changing these to be standalone functions that take in the intended return value as a ref argument (named result or res or something).  That was motivated by feeling uncertain about invert being called as a method.  However, he didn't balk as much at the ones used in the pidigits implementation, so he was going to think about it more.  @bradcray - just noting that this is the issue and it also has a list of all impacted methods (though some of them have been renamed by now)

**Comment by bradcray** [comment]
> In the module re-review today, Brad suggested potentially changing these to be standalone functions that take in the intended return value as a ref argument (named result or res or something).

I'd completely forgotten that I (and Nikhil) had proposed this before:

> I don't have a strong opinion as to whether the "takes the result" forms should be standalone or rely on this as one of the arguments (where I think Nikhil was expressing a preference for the former?) or support both forms.

To me, this is the million dollar question for this library.  We're also discussing it a bit here:  https://github.com/chapel-lang/chapel/issues/17999#issuecomment-1029917170

**Comment by bradcray** [comment]
Though slightly different, `divQR` potentially belongs on this list as well, as it conceptually returns two values, where today one is `this` and the other is a `ref` argument.  The clean interface would be to have it return a tuple of q and r (which seems to be what Julia's clean BigInt interface does).

**Comment by mppf** [comment]
If we are keeping the 3-argument `add` etc then I think having them be 3-argument standalone functions is probably better.

It might not be what we want to do for `bigint` (because it brings in other changes / decisions) but my favorite way to solve this is with the compound operators idea ( https://github.com/chapel-lang/chapel/issues/17999#issuecomment-1029917170 ). I think that an interesting line of thinking is—if we suppose that we magically had compound operators already—would we still want these 3-argument `add` etc for `bigint` for some reason?

I think the main drawbacks of the compound operators idea are 1) that it might not be inherently obvious which combinations of operations will call which functions and 2) that it might require implementing quite a lot of compound operators. But in this bigint case specifically, I don't think either of these criticisms applies. For 1), whether or not `a = b + c` is calling `+` and then `=` or whether it is calling a combined `operator bigint.=(b1).+(b2,b3)` is only an optimization concern rather than a correctness one. (And, generally speaking, anything any code you call is doing can be an optimization concern, so it does not bother me that it might not be inherently obvious). For 2), these 3-argument functions already exist in `bigint`, so it is just a matter of naming them in a way that makes it easy to use them.
