### ISSUE TITLE
Fix bug with `bigint.pow` in BigInteger module when exponent is negative

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#17704]
When the exponent is a positive integer, we use the uint version, but when the exponent is negative we send the base as the mod value to work around the fact that GMP doesn't provide a pow version for integers and this wouldn't yield the same result if `y == -1` or if the base is negative.  It looks like this function was added along with a bunch of other int versions - I don't see a review and the PR did not add tests of this function specifically.

**Comment by bradcray** [comment]
Good catch.  Can the bigint pow() routine even handle negative exponents given that bigints can't represent fractional values?  I.e., should it just return 0 since any `1/n` fraction is essentially 0 as an integer?  (similar to the question asked [last night on Discourse](https://chapel.discourse.group/t/design-input-for-model-state/4575/16?u=bradcray) ).

**Comment by cassella** [comment]
> should it just return 0 since any 1/n fraction is essentially 0 as an integer

Keep in mind `pow(1, -1)`, `pow(-1, -1)`, and `pow(-1, -2)`.  Though those would probably just be a few more special cases on the way to returning 0.
