### ISSUE TITLE
Make `test/man/checkManPages` ensure `\--` is used

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#17714]
In recent PRs (#17660, #17446, #17400), we've improved the formatting of the online man pages so that they render `--` as `--` rather than `–` (an n-dash).  This issue suggests that we go one step further and have the `checkManPages` script ensure that any options mentioned in the man pages use `\--` rather than `--` in their `.rst` source files, to ensure we don't have such issues creep back in.  To pass, this change should cause `start_test test/man` to fail if:

* one of the flags changes names and no longer matches the compiler's flags (e.g., `\--baseline` becomes `\--baseline-foo`)
* a flag is referred to using `--baseline` rather than `\--baseline`

**Comment by shubhamkmr04** [comment]
Hi @bradcray I just wanted to let you know that I have started working on this and I would create a PR as soon as I found the perfect way to address this particular error.

**Comment by shubhamkmr04** [comment]
@bradcray I got it fixed. Now if we use flag `**--[no-]dead-code-elimination**` instead of `**\--[no-]dead-code-elimination**` on our man page, our script is failing with an error.
![Screenshot from 2021-05-14 21-26-55](https://user-images.githubusercontent.com/50761978/118297185-70f7a180-b4fb-11eb-98fd-3a55df362d14.png)
