### ISSUE TITLE
[Library Stabilization] Should `bigint.sgn()` return an enum?

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#17719]
The result space for this function in the BigInteger module is "+1 if op > 0, 0 if op = 0, and -1 if op < 0".  Should this continue to return the int values or should we return an enum which would be more descriptive?

The sgn function is defined here: https://gmplib.org/manual/Integer-Comparisons

**Comment by bradcray** [comment]
At first, I thought my reaction here would be similar to https://github.com/chapel-lang/chapel/issues/17706#issuecomment-840149204, but the values in this issue seem more valuable / less arbitrary to me than in that one, making me think we should stick with the current behavior.

Specifically, the behavior here seems similar to the "spaceship operator" (`<=>` in most languages, potentially `<==>` in Chapel) which returns negative, 0, or positive values depending on the relationship.  With that capability, it's nice that you can use `<`, `<=`, `==`, `>`, `>=` to represent various cases (negative, non-positive, zero, positive, non, non-negative) and I could see wanting to do the same thing here:  e.g., `if mybigint.sign() >= 0` would say "is mybigint non-negative?".  Whereas if it returned an enum, we couldn't write that without a cast-to-int.

(However, this makes me wonder why one would write this rather than just writing `if mybigint >= 0`...  It may be that this form is more expensive if it results in doing a full creation of a bigint and a general-purpose bigint.  If so, it suggests that, in Chapel, we might want to create `operator >(x: bigint, param y: int) where y == 0` overloads that call sgn() and avoid the more general comparison code paths?)

**Comment by lydia-duncan** [comment]
It does sound like we won't do this, but if we did, `Math.sgn()` should also be updated

**Comment by lydia-duncan** [comment]
I haven't heard strong support for this, so figure it would be best to just close it as "won't implement" instead of bringing it up in our remaining design slots

**Comment by bradcray** [comment]
Since we last discussed this, I've seen this routine (which I was previously mostly unfamiliar with) used in practice in codes and now understand it better—the use of integers here is attractive from the perspective of doing math with the values.  For example, see @jeremiah-corrado's Advent of Code Day 9 solution:  https://chapel-lang.org/blog/posts/aoc2022-day09-elvish-string-theory/  

Based on that new understanding and the precedent for the routine in other languages, I think it would be bad to change it.  Also note that the versions in AutoMath have the same behavior (though it seems a little odd to me that they return 8-bit values rather than w-bit values...).
