### ISSUE TITLE
Document the BigInteger module better

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#17738]
Our documentation of the BigInteger module is very sparse and references GMP a lot in what is there.  It should be more independent of GMP and cover all the publicly visible symbols in it.

-----

It might be nice to add some sections at the beginning (but part of that depends on what remains).

-----

> Casting from ``bigint`` to ``integral`` and ``real`` types is also
supported.

Should this be "or"?

-----

We hide the cast operators from documentation.  Should we?

**Comment by bradcray** [comment]
I generally agree with this.  I think it would be reasonable to have links from our routines to the underlying GMP routines for reference (if it were not a maintenance burden), but feel that our routines should at least have a quick description of each rather than nothing.

> We hide the cast operators from documentation. Should we?

I don't think so, and expect that this dates back to when we didn't have a user-facing way of defining casts?
