### ISSUE TITLE
Operations on mixed-size uints don't work / generate a confusing error message

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#17756]
### Summary of Problem

When subtracting an 8-bit uint from a 64-bit uint:

```chapel
var u: uint = 2;
var u8: uint(8) = 1;

writeln(u-u8);
```

we currently generate the error message:

```
illegal use of '-' on operands of type uint(64) and signed integer
```

which is confusing because—from the user's standpoint—they aren't using a signed integer operand.  This issue proposes that we either support this behavior or improve the error message.

I believe that this is occurring because we tend to coerce small `uint` values to larger signed `int` values over larger `uint` values.  Specifically, the `--explain-call` flag explains that the candidates are:

```
note: candidates are: -(a: uint(64), b: int(64)) [17001]
note:                 -(a: uint(64), b: uint(64)) [465095]
note:                 -(a: real(64), b: real(64)) [465139]
note:                 -(a: complex(128), b: complex(128)) [465227]
note:                 -(a: real(64), b: complex(128)) [465434]
note:                 -(a: complex(128), b: real(64)) [465519]
note: best candidate is: -(a: uint(64), b: int(64)) [17001]
```

and then says that the best candidate is:

```
$CHPL_HOME/modules/internal/ChapelBase.chpl:1982: note: best candidate is: -(a: uint(64), b: int(64)) [17001]
```

which is an error overload.

This issue asks how we should handle this.  For example:
* don't support this case, and improve the error message?
* add explicit support for `uint op uint` combinations where the `uint`s have different widths?
* add support for this case, but using another approach; for example, a change to how `uint` coercions work?

**Associated Future Test(s):**
[`test/types/integral/uintMinusSmallUint.chpl`](
           https://github.com/chapel-lang/chapel/blob/master/test/types/integral/uintMinusSmallUint.chpl
          ) #17755

### Configuration Information

- Output of `chpl --version`: `1.25.0 pre-release (75306b9359)`

**Comment by bradcray** [comment]
One idea I had, implemented in #17758 was to put the `last resort` pragma on the error overload to cause the `uint`/`uint` version to be called.  But this is problematic because it causes int/uint combinations to coerce up to the real/real version.  Obvious in retrospect—oops.

So then the questions for me are whether (a) we should provide additional uint/uint overloads of operators that preserve the uint-ness or (b) whether we should change something about how uints coerce.  The former is sufficient, but slightly annoying, and suggests that if users want to create binary procedures for t,t pairs like our operators, they'll have to go through the same pain.  The latter seems attractive at a high-level, but I'm not really sure how to express it.  Essentially "I can coerce to this or that, but I'd rather coerce to that, given the choice."

**Comment by bradcray** [comment]
PR #17765 adds explicit operator overloads for all pairs of `uint` x `uint` types and seems to generate the results I would expect for various `[u]int(w)` op `[u]int(w2)` pairs, so feels like a potential path forward.  But is it too clunky?  (e.g., a user wanting to provide similar functions over pairs of ints and uints would need to do the same explicit handling for uints).

**Comment by mppf** [comment]
One way to view this issue is that it is demonstrating a problem with function resolution's rules for finding a more specific function. Note for one thing that we have a rule preferring `int` over `uint` (see the last few bullets in [determining more specific functions](https://chapel-lang.org/docs/language/spec/procedures.html#determining-more-specific-functions). This rule predated my involvement but I've always been slightly suspicious of it. (But things break if we just remove it; it would not be so easy).

> Essentially "I can coerce to this or that, but I'd rather coerce to that, given the choice."

We do have logic like this in the compiler. See the function `prefersCoercionToOtherNumericType`. Note that it currently puts int and uint into one bucket (and that's probably because of the int/uint rule I mentioned above). There might be a modest adjustment to this that gets the behavior you want but at a quick glance I did not find it. I'd probably be able to find an adjustment to these rules that works but it would probably take more time than I can give it right now.

> One idea I had, implemented in #17758 was to put the `last resort` pragma on the error overload to cause the `uint`/`uint` version to be called.  But this is problematic because it causes int/uint combinations to coerce up to the real/real version.  Obvious in retrospect—oops.

That `int`/`uint` overload is actually quite problematic, since it's an error case, IMO.

One thing I wonder about is - what if, instead of having lots of specific overloads, could we instead implement e.g. `operator -( a: numeric, b: numeric)` (as well as param variations of these) and then have some param conditionals in there for the cases we handle and for the errors. I think the reason to have separate functions for the different types is so that users can create their own overload but I'm not sure that's actually a good goal for the following reasons:

 1. It creates "overload sets" which are errors today anyway
 2. The overload resolution rules are complicated and it's easy to make minor changes to these functions that cause everything to break
 3. I don't think people should be redefining `+` on built-in types in their programs

I know that there are some other (maybe historical?) reasons why we have these as concrete functions, but perhaps we could address those. (E.g. it seems attainable for the compiler to promote `+` defined as taking `numeric` arguments instead of only considering promotion on concrete functions).

**Comment by bradcray** [comment]
Just to make sure I'm not missing anything:  That seems symmetric to the OP to me: different op, different order of args, but otherwise the identical behavior?  (which I guess suggests "LHS vs. RHS doesn't matter?")

**Comment by mppf** [comment]
Right I was just including it here because at some point both should end up as tests

**Comment by mppf** [comment]
Another test case to add when this is fixed:

``` chapel
var x: uint(64);
var y: int(64);

var z = min(x,y);
writeln(z, " : ", z.type:string);
```

This one compiles on `main` but yields `z` of type `real(64)` which is not ideal. For min/max specifically with an int/uint mix, we can predict the return type. (With such a mix, min always returns int, and max always returns uint, in order for the result to always fit in the return type).
