### ISSUE TITLE
Compiler segfault (UTI-MIS-0916) in task intent code

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#17759]
### Summary of Problem

Compiling the following program results in a compiler segfault, seemingly in the code that introduces task intents:

```chapel
record R {
  var data: [1..3] real;
}

record S {
  var rr: R;

  proc foo() {
    forall i in 1..3 {
      rr.data[i] = i;
    }

    writeln(rr);
  }
}

var s: S;
s.foo();
```

Surprisingly, changing the declaration of `s` to:

```chapel
var s = new S();
```

causes it to pass.

### Steps to Reproduce

**Associated Future Test(s):**
[`test/types/records/bugs/segfault-on-task-intent.chpl`](
           https://github.com/chapel-lang/chapel/blob/master/test/types/records/bugs/segfault-on-task-intent.chpl
          ) #17759 

### Configuration Information

- Output of `chpl --version`: `1.25.0 pre-release (8200e791de)`

**Comment by bradcray** [comment]
@vasslitvinov : With a quick look, it looked to me as though this is yours.  Could you take a quick look and see?

**Comment by vasslitvinov** [comment]
This note is of interest only to curious compiler types. The short of the long is:
* I understand why the test crashes the compiler,
* I understand what is different about the modified version with `var s = new S();` ,
* my conclusion is that this is a very superficial issue, which I expect to fix shortly.

#### What happens in the test at the point of failure

The compiler is setting up a shadow variable for the access to the field `rr.data` within the forall loop, according to [forall intents when accessing a field of `this`, as defined in the spec](https://chapel-lang.org/docs/master/language/spec/data-parallelism.html#forall-intents) .

The implementation of this semantics creates an implicit `ref` alias to `rr.data`, called `rr_ref` in this case, then uses it as an outer variable and replaces `rr.data` within the loop body with a corresponding shadow variable.

`rr_ref` needs to be of the reference type `_ref(R)`. All the fuss here is because by the time `rr_ref` is being created and set up, `_ref(R)` has not been created yet. So the simple fix is to go ahead and create it.

#### Why the modified version passes

`_ref(R)` gets created due to this sequence of events:

* resolving `var s = new S();`
* compiler calls `resolveNew()`, which gets to the default initializer for `S` and start resolving it
* `resolveInitializerBody()` where the initializer looks like:
```
fn init(_mt, ref this: _ref(S), in rr: R) {
  def(_formal_temp_rr)
  move(_formal_temp_rr, rr)
  init field(this, "rr", _formal_temp_rr)
}
```
* `resolveExpr()` on the SymExpr for the `rr` formal
* which invokes `makeRefType()` on the formal's type. Boom.

The call to `foo()`, and then foo's body, are resolved after `var s = new S();` is resolved as shown above, therefore `_ref(R)` has been set up.

By contrast, the original version does not resolve the initializer yet:

* resolving `var s: S;`
* ... which amounts to introducing the AST `default init var(s, S)`
* ... and leaving it like that
* ... then proceeding to resolving the call to `foo()`, then foo's body, and getting in trouble because `_ref(R)` has not been created yet.

The AST `default init var(s, S)` would (if there is no crash) be converted to an initializer call, and the initializer would get resolved, after all statements in the body of the enclosing function (here, the module init function) have been resolved -- when `resolveFunction()` invokes `fixPrimInitsAndAddCasts()`.

**Comment by bradcray** [comment]
Thanks for this diagnosis, Vass!  (Now you've made me curious whether fixing this will potentially address some of the other semantic issues that I mentioned were related to variations of this program...  I may wait for this fix before filing those in hopes that it will).
