### ISSUE TITLE
--minimal-modules produces a SegFault in parser

### ISSUE THREAD

**Issue by leekillough** [chapel-lang/chapel#17785]
```
chpl --minimal-modules examples/hello.chpl 
internal error: seg fault [util/misc.cpp:916]
```
It seems to occur when string literal symbols are created. It is reproducible with:
```chpl
var x = "a";
```

**Comment by bradcray** [comment]
Note that there's no implied guarantee that any specific Chapel program will compile with `--minimal-modules`.  The goal of the flag is to permit compiler developers to focus in on a specific aspect of the language without necessarily dragging all of the internal modules along.  Since strings are one of several built-in types that are implemented in the internal modules (and not in the minimal modules), it's not particularly surprising that they wouldn't work in the `--minimal-modules` mode.

Typically, if one wanted to develop with a specific feature, like strings, with `--minimal-modules`, they would copy the pieces of the internal modules that enable that feature over to their local copy of the minimal modules hierarchy (stored in `$CHPL_HOME/modules/minimal`.

**Comment by leekillough** [comment]
@bradcray: I was using `--minimal-modules` to debug the compiler, without bringing in all of the modules, so that I have a smaller AST to debug with.

**Comment by leekillough** [comment]
Even if strings are not supported with `--minimal-modules`, the parser should not crash with a seg fault.

**Comment by bradcray** [comment]
> to debug the compiler, without bringing in all of the modules, so that I have a smaller AST to debug with.

That's fine, I'm just pointing out that there's no guarantee that any feature that depends on features that are not implemented within the minimal modules (like strings) will work / won't result in the compiler blowing up like this.  I.e., I don't consider this a bug, it's just part of the wild west that working with the minimal modules entails.

> the parser should not crash with a seg fault.

That's a potential philosophy that one could espouse, but I believe that the historical stance on `--minimal-modules` has been that there are no guarantees as to what will happen when you use features that aren't supported by the minimal module set.

**Comment by leekillough** [comment]
It seems to occur with any features not supported by minimal modules, e.g., this also produces it:
```chpl
class C {}
new owned C();
```
> That's a potential philosophy that one could espouse

I don't think seg faults should ever occur, even with wild-west options.

**Comment by daviditen** [comment]
https://github.com/chapel-lang/chapel/issues/16276

**Comment by bradcray** [comment]
> I don't think seg faults should ever occur, even with wild-west options.

Again, that's a reasonable philosophy, but it's not the one that the capability was developed with.  The intention of the mode was to permit developers to focus on specific issues that are built into the compiler — particularly function resolution.

Personally, I don't think we should expend much effort making `--minimal-modules` bulletproof given that it's likely to take a lot of work and won't benefit the end-user.  If there's a five-minute fix (TM) that would address the segfaults, I'd have no concerns about merging it.  But I'm skeptical that making `--minimal-modules` generate some sort of reasonable output for all of our tests (say) is a worthwhile use of our time.

**Comment by vasslitvinov** [comment]
@leekillough using the compiler with options like `--ignore-errors` can also cause crashes. I think this is intended and acceptable.

**Comment by bradcray** [comment]
Closing this based on the discussion above.
