### ISSUE TITLE
Deprecation and configs

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#17791]
While it seems pretty easy to add a warning when a deprecated config var, const or param is referenced in Chapel code, I think the behavior when it is referenced via the compilation or execution command is a little more up in the air so wanted to double check before implementing my instincts.

For example, say you have the following:
```chapel
deprecated "don't use x, use y" config var x: bool = false;
config var y: bool = false;

proc main() {
  writeln(x);
  writeln(y);
}
```
and you compile it with `chpl -sx=true foo.chpl`.  Should the act of using the compilation flag trigger a separate warning message from the writeln in the code?  What about if it was set at execution time, e.g. `./foo --x=true`?

My instinct says the flag use should trigger its own warning message.

**Comment by bradcray** [comment]
Unfortunately (because it's something I'd just as soon  not spend implementation resources on), I think that using the flag would need to generate a warning message.

I think your motivating example isn't quite realistic in that, if `x` were truly deprecated by the module's author, the code would no longer refer to it.  So it's likely that the only reference to a deprecated `config` would be a user who hadn't gotten the memo and was setting it in a script or Makefile or command-line (where the only other example I can think of is a module that `use`s this one and refers to it, like a normal variable; but I don't think we can count on that case existing).

Another case to worry about would be a `config` set in the compiler using the `-s` flag.
