### ISSUE TITLE
What should the syntax for a context manager statement look like?

### ISSUE THREAD

**Issue by dlongnecke-cray** [chapel-lang/chapel#17965]
What should the syntax for a context manager statement look like?

In #17809 there was more or less unanimous support for introducing
new syntax to support a context management statement.

This issue explores some possibilities for what the syntax of this
statement could look like.

To start things off, here's an example of a context manager taken
straight out of Python (which is what inspired this effort):

```python
with createAndUseSomeManager() as myResource:
  myResource.doSomething()
```

This code calls a function `createAndUseSomeManager()`, which
returns an instance of a type that can be used as a context manager.
Under the covers it calls `__enter__` on that object to get a handle
to a resource. Within the scope of the managed block, the resource
can be referred to as `myResource`.

So for the context manager construct, we're going to need syntax that
represents at least three pieces:

  - An expression to get the manager object, which produces a resource
  - An identifier that can be used as a "resource handle" 
  - A statement (which could be a block)

# 1) Immediate translation to Chapel

Let's say we just translated the Python syntax directly into Chapel.
We might end up with something like:

```chapel
with createAndUseSomeManager() as myResource do
  myResource.doSomething();
```

This may be acceptable. However there are still some questions that
may require new syntax to answer.

# 2) Handling multiple return intents

There is an open question, which is what the storage kind
(e.g. `ref/const ref/var`) of `myResource` should be if there are
multiple different return intents for the `__enter__` method of the
context manager object.

E.g., imagine if we used `record foo` as a context manager:

```chapel
record foo {
  var x = 0;

  // This would be called '__enter__' in Python...
  proc enterThis() ref { return x; }
  proc enterThis() { return x; }
  proc leaveThis() {}
}
```

Which overload of `enterThis()` is selected for `myResource`? What is
the storage kind of `myResource`? If we wanted to omit an explicit
storage kind, we would need to decide how to disambiguate based on
return intent.

But if we do not, or if we would like to explicitly select which
overload is called, we can introduce a fourth piece of syntax:

```chapel
// Create a copy of 'myResource' as a 'var'.
with createAndUseSomeManager() as var myResource do
  myResource.doSomething();

// Refer to 'myResource' with 'ref'.
with createAndUseSomeManager() as ref myResource do
  myResource.modify(); 
```

# 3) Potential confusion beteween 'with' and task intents

The `with` keyword is already used to introduce task/forall intent
lists (also known as "with clauses").

Because of this, we might want to use a different keyword besides
`with` to signal the start of a context manager statement. One
option is to use the keyword `manage`:

```chapel
manage createAndUseSomeManager() as myResource do
  myResource.doSomething();
```

This has the downside of adding a new keyword to the language.

# 4) Using a syntax that looks more like assignment 

One idea that has been proposed is to use a syntax that looks more
like assignment instead of using the `as` keyword to bind the
resource to a handle:

```chapel
with myResource = createAndUseSomeManager() do
  myResource.doSomething();
```

This idea is interesting, but I think it has a downside, which is
that what is occurring under the covers is not actually assignment
of `createAndUseSomeManager()` to `myResource`. Instead, what happens
looks more like:

```chapel
ref tempManager = createAndUseSomeManager();
var myResource = tempManager.enterThis();
```

Because it is too easy to take this form of syntax as assignment at
face value, I think it may cause more harm than good.

# 5) Unifying context managers and task intents (with clauses)

Because the original translated form uses the `with` keyword, this
gave rise to a novel idea: what if we could use context managers
within with clauses?

Perhaps something like:

```chapel
begin with (myResource = createAndUseSomeManager()) {
  myResource.doSomething();
}
```

This is a cool idea. However this first translation suffers from the
same problem as (4), which is that it is impossible to differentiate
the syntax from assignment.

To fix this problem, we could introduce the `as` keyword instead:

```chapel
begin with (createAndUseSomeManager() as myResource) {
  myResource.doSomething();
}
```

In this fashion, we could integrate context managers into with clauses.
We could offer this form as a secondary way of invoking a context
manager. I do not think we could have it be the only way of creating
a context manager, as with clauses can only be used by things which
may introduce task intents.

# 6) Flipping the order of context manager and resource handle

An alternative syntax that flips the order of `createAndUseManager()`
and `myResource` has been proposed:

```chapel
with myResource in createAndUseManager() do
  myResource.doSomething();
```

Here we list the resource handle before the manager expression that
is used to create it. Because the `as` keyword doesn't make as much
sense with this ordering, we can use the `in` keyword instead. The
`in` keyword also makes conceptual sense because it implies that we
are working with a resource _within_ a context.

# 7) Support for nested context managers

As a last piece of functionality we might want the syntax to support,
suppose we might want to allow nested context managers. Imagine a
situation where you have two managers: a timer entity and a file.
With our original translation, this could be achieved by nesting
context managers:

```chapel
var t = new timer();

// Open a file, then time how long it takes to write some stuff.
with open('file.txt', 'w') as myFile do
  with t do
    myFile.write('foo');

writeln(t.elapsed());
```

Nesting context managers works, but the downside is it introduces
nesting (potentially a lot of nesting, depending on how many context
managers we use).

As an extension to our syntax, we could support nested context
managers on a single line:

```chapel
var t = new timer();

with open('file.txt', 'w') as myFile, t do
  myFile.write('foo');

writeln(t.elapsed());
```

# 8) Summary

Here are some questions for discussion:

  - What keyword do we want to use to signal the start of a context
    manager statement? (e.g. `with` or `manage`)
  - How do we want to handle multiple return intents for `enter`?
    Are we OK with requiring the storage kind be expressed before the
    resource handle (e.g. `ref myResource`)?
  - Do we want to permit omitting the storage kind of the resource
    handle? We will have to decide what this means in the presence
    of multiple return intents for `enter`
  - Do we want to explore the assignment-like syntax, or are we in
    agreement that this might be too confusing?
  - Do we want to explore offering a secondary form of syntax that
    lets context managers be used in with clauses?
  - Do we want to consider inverting the order of the manager
    expression and the resource handle?
    (e.g. `myResource in createAndUseMyManager()`)
  - Do we want to extend the syntax to support nested managers?

**Comment by stonea** [comment]
For (2) I guess I'd want to know more use cases for resource managers. The only use case I'm aware of is opening and closing a file (in which case you'd want return a ref to the file object right?). What's the use case where you'd want to return a copy?
 
I guess having 'const ref' and 'ref' overloads makes more sense to me.  I guess my vote for that would be to return the const version by default and force the user to add some be explicit about wanting the non-const ref overload

--

For (4) I guess we already have a precedent set of adding new keywords to the language.  When we iterate through a range of values with use 'in' rather than `=`. That is we do: `for i in 0..n` rather than `for i = 0..n`.

--

I the syntax in (6) kind of confusing. For the canonical file-open example this syntax looks weird to me:

```chpl
with myFile in open('someFile.txt') do
    process(myFile);
```

You mention:

> The `in` keyword also makes conceptual sense because it implies that we are working with a resource within a context.

But that context is what's after the `do` keyword not the `in` keyword.  If I was unfamiliar with this syntax I think I might guess that`createAndUseManager()` returns some kind of aggregate value and you're pulling 'myResource' out of it to use in do block.

--

For (7): the use of a timer as a context manager object is pretty cool, I like that.  I imagine your first code example (nesting a with statement in the body of another one) would just naturally work; A `with` statement is just like any other right?

I imagine a common case might be opening two (or more) files (maybe one to read from and another to write to).

A quick stackoverflow search says that nesting withs together in a single
line is possible in Python https://stackoverflow.com/questions/1990373/nesting-with-statements-in-python

`with open(file1) as fsock1, open(file2, 'a') as fsock2:`

Not sure if we should follow that precedent or not.

**Comment by dlongnecke-cray** [comment]
> I guess having 'const ref' and 'ref' overloads makes more sense to me. I guess my vote for that would be to return the const version by default and force the user to add some be explicit about wanting the non-const ref overload

Right, there will be some sort of ordering to the resolution of the overloads, that we will have to decide on.

If we want the user to be able to control, in any fashion, which overload is selected, then I think we need to let them specify the storage kind. If we decide we don't want that syntax or it's just noise, then we'd omit that and rely on the resolution order (and for implementors not to excessively overload the return intent of their `enter` methods).

> I the syntax in (6) kind of confusing. For the canonical file-open example this syntax looks weird to me...

I think that's a fair point. It's easy to confuse it with iteration. My head doesn't get as confused because of the opening verb (e.g. `with`, `manage`). I read it almost as "manage my file in the context of my file opened".

> But that context is what's after the do keyword not the in keyword.

I see it more as the context is the entire scope of the block.

> If I was unfamiliar with this syntax I think I might guess thatcreateAndUseManager() returns some kind of aggregate value and you're pulling 'myResource' out of it to use in do block.

Well that's _almost_ what's happening.

> For (7): the use of a timer as a context manager object is pretty cool, I like that. I imagine your first code example (nesting a with statement in the body of another one) would just naturally work

Yeah, it should just naturally work. The desire to nest context managers on a single line was actually first brought to my attention by @bradcray, who said something to the effect of "imagine I want to turn on a timer, comm counting, and [some other timer or thing]". At which point the level of nesting starts to get a bit crazy.

**Comment by dlongnecke-cray** [comment]
As a straw-person proposal, if I was the only one voting here, I would choose:

- To use the `manage` keyword instead of the `with` keyword
- To allow the user to optionally specify the storage kind of the resource handle (e.g. `manage foo() as ref myResource`)
- To _not_ use the assignment style syntax
- To leave integration with task intents (with clauses) as future work
- To flip the order of resource handle and manager (e.g. `manage myResource in myManager() do;`)
- To support nesting of context managers on a single line (perhaps as future work)

**Comment by vasslitvinov** [comment]
I support these choices, with a couple of considerations:

I sense a symmetry between `manage` and `for`. Which means that the default storage type for `myResource` is what we would get in a for-loop over a similarly-yielding iterator. This also means zip syntax for multiple (nested) managers.

Alternatively, we could define the default storage type for `myResource` to be that of a default-intent formal. I don't think we have a moral obligation to have `myResource` be mutable by default. So we can apply the formal-intents principle "safety by default".

Allowing nested managers in a single `manage` construct has the problem that it was not intuitive to me which one is outer and which one is inner. Granted, this is my problem. In any case I am happy to leave it as future work.

Somehow I don't like `with` in this context, so would prefer to introduce `manage`. However I will accept `with` as well. One consideration is if we end up with `with`, it would be confusing for python-ers to have `with ... in ... do`. I DO like `in` much better than `as`. So this consideration pushes me towards `manage`.

**Comment by lydia-duncan** [comment]
I like the syntax you've proposed.  I definitely would like to avoid using `as` unless there's renaming involved.

**Comment by e-kayrakli** [comment]
I am a big fan of Python's context manager concept, and not a big fan of `manage` and `in` :) I am more strongly against `in` and prefer `as`, then `manage` vs `with`.

- `in` vs `as`: I'll just echo what @stonea said above. `manage f in open('myfile')` is just awkward to me. `f` sounds like a line in the file or something rather than the file object itself.

- `manage` vs `with`: I actually like `with` because, I feel like the use is very similar to that of forall intents. In both cases `with` specifies that there are some special variables in the following context. But I don't feel very strongly about this.

As the smallest change on the proposal above, I would like us to consider `manage myResource as myManager()` as the syntax.

---

If we go with `with`, we probably want to be significantly different than Python or completely identical. For that reason, and as my general preference,I'd do the following:

```chapel
with f = open('myfile') {

}
```


The fact that this is more like

```chapel
with f = open('myfile').enter() {

}
```

doesn't bother me much personally. When you have `a = b` in Chapel, you can't know for sure what that assignment means, in any case. It could be something complicated and/or overloaded that calls something special on `b`. Or another way to look at it, when you do `for a in A`, we actually make it `for a in A.these()`. Making `with a = b` into `with a = b.enter()` feels the same to me.

**Comment by dlongnecke-cray** [comment]
> @e-kayrakli: As the smallest change on the proposal above, I would like us to consider `manage myResource as myManager()` as the syntax.

I would actually prefer to just straight up use the Python syntax instead of flipping the order of resource/manager around but continuing to use the `as` keyword. To me this option makes the least sense in my head.

> When you have a = b in Chapel, you can't know for sure what that assignment means

I agree that you can't know exactly what the assignment will do. However I think you do know that it will resolve to some sort of `operator=` call. As far as symbol-to-def, I think it's very WYSIWYG.

> Or another way to look at it, when you do for a in A, we actually make it for a in A.these()

However we use special purpose syntax `for a in A` to indicate that (instead of `=`). I think the question is whether you associate the `.these()` call with the `in` keyword or the fact that a loop is happening (the `for` keyword).

I personally don't view `in` as a problem because I think the opening keyword of the statement indicates what exactly is happening (e.g. if it's `manage`, it's an `enter` call and not iteration). However I do recognize that not everyone feels that way. Another perfectly valid view is that `in` is actually almost akin to some sort of binary op.

To me the choice of opening keyword is less important than the ordering of the expressions. I'd personally be OK with either `with` or `manage`. Conversely, though, the choice of opening keyword _does_ matter when deciding the ordering of expressions xD.

---

> @vasslitvinov: Somehow I don't like with in this context, so would prefer to introduce manage. However I will accept with as well. One consideration is if we end up with with, it would be confusing for python-ers to have with ... in ... do.

Two(+?) people have argued against the `manage foo in bar()` form owing to `in` being confusing. I think that if we're against the `in` keyword, then something like `manage foo as bar()` isn't really an option because the ordering of the syntax makes no sense. Which leads us to `manage bar() as foo`, which is one `with` keyword away from being Python syntax.

At which point I agree with Vass that we should probably just consider adopting the Python syntax straight up.

If we do decide to add a secondary syntax form that lets you use context managers in task intents, then using the `with` keyword helps to align the two concepts.

---

> @lydia-duncan: I definitely would like to avoid using as unless there's renaming involved.

It sounds like one reason to avoid using the `as` keyword is that it could be confused with the renaming that occurs in import/use statements. I think this is a valid concern (right now we don't use `as` for anything but renaming AFAIK).

One way to sidestep that is to use the assignment form (`with a = foo() do`), however that comes with its own set of concerns.

Another option is to look for a different keyword other than `as` or `in`, but I have no clue what that keyword might be.

**Comment by e-kayrakli** [comment]
> I would actually prefer to just straight up use the Python syntax instead of flipping the order of resource/manager around but continuing to use the as keyword. To me this option makes the least sense in my head.

I don't have anything major against the Python syntax. My only minor worry is that the syntax around two different uses of `with` would be significantly different. 

I cannot read `manage myFile in open('someFile.txt') do` out loud and make sense out of the meaning, but `manage myFile as open('someFile.txt') do` reads much more meaningful to me. I just cannot pretend `in` to be just an operator and abstract away the word's meaning :) [I wouldn't be surprised if I am missing some intrinsic meaning of `as`, as a non-native speaker]

As for @lydia-duncan's concern around renaming, I think contexts are sufficiently different that it doesn't really bother me much.


>I agree that you can't know exactly what the assignment will do. However I think you do know that it will resolve to some sort of operator= call. As far as symbol-to-def, I think it's very WYSIWYG.

To be clear, it'll still resolve to some assignment, we'll only interpret the RHS differently before making the assignment. To me, it is similar to what happens in:

```chapel
record R {
  var x: int;
  proc getValue() { return x; }
  operator =(other: R) { this.x = R.getValue(); }
}

var r1 = new R(1);
var r2 = new R(2);

r1 = r2; 

writeln(r1);
```

**Comment by dlongnecke-cray** [comment]
> @e-kayrakli [I wouldn't be surprised if I am missing some intrinsic meaning of as, as a non-native speaker]

Right so I think we can take `foo() as bar` and expect it to make sense, because it almost reads like "something from `foo()` as `bar`". However I don't think we can flip the ordering of expressions, because "something from `bar` as `foo()`" reads like I'm expected to refer to the thing from `bar` as `foo()` (which also isn't possible). I think the RHS of the `as` has to be the resource/identifier/rename.

> To be clear, it'll still resolve to some assignment, we'll only interpret the RHS differently before making the assignment. To me, it is similar to what happens in...

I can see what you mean, but I think the part that is tripping me up is that when I see `r1 = r2`, I know that there will be a `operator=(other: R)` that I can look for. The syntax isn't "lying" to me as to what the type of the LHS and RHS are. However in the context manager case, it's confusing because the type of the RHS is not readily apparent (it may be a type I don't even have public access to the definition of, or something).

I think that the WYSIWYG of assignment is something that we want to preserve. Else why wouldn't we just write our for loops as: `for a = foo() do`?

**Comment by e-kayrakli** [comment]
I would read `manage f as open('myfile')` as "interpret `f` as `open('myfile')` in the following block. [and I am saying 'interpret' because I know that `f` is not literally the same as `open('myfile')`]"

>  [This would also confuse Python programmers to no end, I think.]

I agree with this. And to be clear, I am OK with either order of the arguments. I just want to avoid `in`.

> I can see what you mean, but I think the part that is tripping me up is that when I see r1 = r2, I know that there will be a operator=(other: R) that I can look for. The syntax isn't "lying" to me as to what the type of the LHS and RHS are. However in the context manager case, it's confusing because the type of the RHS is not readily apparent (it may be a type I don't even have public access to the definition of, or something).

Good points.

**Comment by bradcray** [comment]
I mostly haven't kept up with this issue, but didn't mean to ignore it so much either.  I skipped the OP due to its length and number of items and went right to the comments.

From @dlongnecke-cray:

> manage myResource in createAndUseMyManager1() do

I find myself wanting to use `from` rather than `in` here.  Upside: reads naturally and accurately; downside: new keyword

From @vasslitvinov:

> This also means zip syntax for multiple (nested) managers.

Even if we do go with the `in` keyword, I don't agree with this at all.  `zip` says something pretty complex about evaluating multiple expressions over a period of time in a coordinated manner.  In this context (ha ha), I think we're just extending Chapel's support for generally supporting comma-separated forms that share a keyword, as in `use M1, M2, M3;`, `var x, y, z: int;`, `foo(x, y, z);` etc.  They're evaluated once, in order, sequentially, and the contexts returned by each are managed by the corresponding variable.  Having to say `manage (myResource, _) in zip(createAndUseMyManager1(), createAndUseMyManager2())` strikes me as unnecessary overhead and overkill.

From the rest of the comments, I:

* agree that `in` isn't the most obvious/natural keyword here
* agree that if `as` were used, we'd want to flip the order to `manage createAndUseMyManager1() as myResource`

But I think of these three, I still like `from` best.  :)

**Comment by dlongnecke-cray** [comment]
Having read several responses, I'm now leaning towards a form like:

```chapel
manage myManager() as myResource do ...;
```

- We use the `manage` keyword instead of the `with` keyword to avoid conflating with task intents
- We use the `as` keyword due to discomfort about the `in` keyword, and keep the Python ordering `<expr> as <ident>`
- We avoid talking about storage kind for `myResource` for now (e.g. `ref myResource`), as we can discuss that later
- We can extend the syntax to support nesting later

This form does have the problem of `as` being confused with renames that occur in `use`/`import` statements (as brought up by @lydia-duncan). We could avoid this by using the `from` keyword (as suggested by @bradcray). However this introduces two new keywords for a single statement, which I think is kind of overkill.

**Comment by dlongnecke-cray** [comment]
Thumbs up for:

```chapel
manage myManager() as myResource do;
```

**Comment by dlongnecke-cray** [comment]
Thumbs up for:

```chapel
manage myResource from myManager() do;
```

**Comment by bradcray** [comment]
I didn't end up voting in the poll above because the two options were so similarly acceptable to me that I didn't feel I cared enough to throw my weight behind either (but didn't click "no preference" either because I was sure that I'd have a preference the next day).

One thing that I hadn't digested before the vote was the possibility that we might support patterns like:

```chapel
manage myManager() as var myResource do;
```

which I now see was mentioned in point 2 of the OP (I don't think I ever made it through the entire OP).  That gives me a bit of hesitation because usually `as` is just taking an identifier following it and using that as an alias for something, whereas this is making it more like "declare this new thing (which in fact we are) of this given type (`ref`, `var`, etc.) and make it refer to this thing to its left that you've already seen."  For me, that _feels_ more like our for* loops syntactically, since it's like:

```
for i in myIter() do...    vs.  manage myResource from myManager() do...  // basic form
for myIter() do...       vs.     manage myManager() do...   // anonymous form
for param i in myIter() do...   vs. manage var myResource from myManager() do ...   // specify type declaration form
```

where, for this third form, we'd originally imagined that for loops would take other storage specifiers as well to either assert what the user was getting implicitly or change the behavior (store a copy of the thing being referred to into this new var/const).  See https://github.com/Cray/chapel-private/issues/2271#issuecomment-900732900 for examples.

Anyway, as I say, this is only a bit of hesitation ("do I really want to introduce a new keyword over this?"), but it is hesitation nonetheless.  And if `from` was already a keyword it would definitely make me throw all my weight behind the `from` form.

@dlongnecke-cray points out that we could also choose not to support the `var` vs. `ref` forms in context managers which would make this concern go away, but I wouldn't want to make that decision simply because I find it ugly if we thought it was useful/needed/attractive/orthogonal.

Tagging @npadmana on this comment since he voted the opposite way above and probably isn't subscribed to this issue to see if he has thoughts on it.

**Comment by npadmana** [comment]
No strong opinions either way.... I voted in large part based on how I thought it read, but it's an incredibly mild preference.

**Comment by dlongnecke-cray** [comment]
Closed, the spec specifies the syntax for a manage statement.
