### ISSUE TITLE
Should Reflection.getRoutineName() be renamed?

### ISSUE THREAD

**Issue by dlongnecke-cray** [chapel-lang/chapel#17987]
Should Reflection.getRoutineName() be renamed?

The `Reflection` procedure `getRoutineName` gets the name
of the enclosing procedure.

```chapel
proc getRoutineName() param: string;
```

We currently use a mix of `function` and `routine` within the spec when
referring to callables that can be either procedures or iterators. Should
we rename `getRoutineName` to `getFunctionName` and adjust the
spec to match? Another option is to commit to using `routine`
consistently throughout the documentation.

Given that `function` can have certain implications to people that are
mathematically inclined, _I_ am inclined to prefer the term `routine`
when referring to a callable that could be either a procedure or an
iterator.

**Comment by mppf** [comment]
I thought @bradcray was arguing that he wanted to move away from `function` ? Might be good to bring that up here - in case we want to, say, adjust the spec to use `routine`.

**Comment by dlongnecke-cray** [comment]
Yeah, that's part of the reason why I mention the spec in the OP. I'm not saying that `getFunctionName` is necessarily the correct answer (if it seems that way, it's because I couldn't think of a third, more neutral word to use for both - oh! Maybe "procedure"?). Just that if we want to refer to everything as `routine`, there are a bunch of places in the spec that will have to be adjusted as well.

**Comment by dlongnecke-cray** [comment]
Bumping this as part of my "review of the Reflection module review".

I'll say that personally, I actually don't have a preference for `routine` vs `function` vs `procedure` beyond a slight preference for `procedure` purely due to our use of the `proc` keyword. I'm happy with any of them as long as we're consistent.

One thing that might be interesting is to go grep through the RST files and count how many uses of each word pop up. That might give us an indication of how things stand.

**Comment by bradcray** [comment]
> I use procedure as a neutral way to refer to a function/routine.
>  slight preference for procedure purely due to our use of the proc keyword.

Hi David — I think something got lost in translation, so trying to clarify:

Calling anything declared with `proc` a procedure seems completely correct to me (where we could also talk about 'method procedures' vs. 'standalone procedures' and other variations) and I don't think there's anything under debate there.

Where the terms 'function', 'routine' or 'subroutine' have traditionally been used is in cases where we're talking about the union of things declared with `proc` or `iter` (i.e., procedures and iterators).  `function` is the term we agreed upon when we last discussed this 10 or 15 years ago, but since then, I've regretted not thinking of and pushing harder for '[sub]routine' because, to me (and some users I've heard from), 'function' brings up all sorts of mathematical and functional programming implications that don't apply to us whereas 'subroutine' and 'routine' imply to me a chunk of code that have been bundled up to be called and returned from which feels more general.

So then the question is largely whether we make this change, or stick with 'function' chalking it up to water under the bridge that Brad didn't think of early enough to fight for in time.  But I think unifying on one of these two terms would be beneficial rather than using both of them interchangeably.

**Comment by dlongnecke-cray** [comment]
Thanks Brad, your explanation helps clarify a lot.

Given that, I actually prefer the name `routine` as a neutral way to refer to either a procedure or an iterator.

I too have gotten word from mathy folks that `function` implies all sorts of mathy things :).

However I'm also getting the sense that this is a long-waged war with the trenches dug deep?

**Comment by bradcray** [comment]
> However I'm also getting the sense that this is a long-waged war with the trenches dug deep?

No, I don't think that's accurate.  It's more like a non-neglected project of mine to try and push the conversation forward.  I may be misremembering, but I think the main objections have been "let's not re-decide things that we've decided before" rather than any deep love for function (?).  Here's the issue that I forgot already existed on this topic:  https://github.com/chapel-lang/chapel/issues/17769

**Comment by dlongnecke-cray** [comment]
It sounds like this issue is dependent on the outcome of #17769. Do you think I should close this issue and make a note that we should update `getFunctionName` to match whatever we decide there?

**Comment by bradcray** [comment]
I agree they're related, but I would probably keep this open rather than piggybacking, just so it doesn't get lost.

**Comment by lydia-duncan** [comment]
In looking at the notes on the Reflection module reviews, it looks like we've decided not to do this.  Closing
