### ISSUE TITLE
Future directions for CPtr memory alloc/free routines

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#18017]
Currently, the `CPtr` module defines these routines for allocating and freeing memory:

```chapel
proc c_calloc(type eltType, size: integral): c_ptr(eltType) { ... }
proc c_malloc(type eltType, size: integral): c_ptr(eltType) { ... }
proc c_aligned_alloc(type eltType, alignment: integral, size: integral): c_ptr(eltType) {
proc c_free(data: c_void_ptr) { ... }
```

As noted in a discussion that came up at https://github.com/Cray/chapel-private/issues/1896#issuecomment-818078445, these could be considered a bit odd in that:

* their naming takes the `c_foo()` pattern, yet their signatures do not match C's definition of `foo()` (e.g., C's routines don't take a `type` or return a typed pointer
* they don't call down to the corresponding C routines, but our runtime's version of the routines (which is sometimes the C routines, but more often jemalloc)

Some alternatives that have been discussed include:

* having them mimic the C routines more closely and call the C routines directly since that's what their names imply (vote :+1: for this option

* removing the `c_` prefix in order to avoid the implication that these are C routines (vote :heart: for this option)

* removing the `c_` prefix and working harder to make the routines Chapeltastic.  For example, perhaps we could just have an `alloc()` routine that takes a defaulted bool indicating whether or not to zero the memory and a defaulted alignment to indicate the alignment, reducing three routines to one (and maybe getting aligned allocations by default?) (vote :tada: for this option)

* same as previous but preserving the `c_` prefix.  Sure it's another case of `c_foo()` incorrectly implying that we're calling C's foo() but (a) since C doesn't have an `alloc()` (right?), it's unlikely to be overly confusing; (b) it returns a c_ptr() so is still pretty C-like (vote :rocket: for this option)

* something else?

**Comment by bradcray** [comment]
I didn't want to put too much bias into the OP, but the :+1: option has been fairly universally panned in that it's not something we want to encourage users to do.  We'd much prefer them to call through our allocator path and benefit from being more tightly integrated into things Chapel can do with memory (trace it, communicate it well, etc.) than bypass it.  We could potentially provide this _and_ one of the other options (that doesn't use the same naming scheme, presumably), but users could always extern out to C's routines if they really wanted to, and not providing them will reduce the chances that someone will accidentally learn about them first and call them instead of the preferred choice.

**Comment by mppf** [comment]
I'm interested in the single `alloc()` approach but it makes me wonder if that routine should be defined in CPtr/CTypes/whatever or in some other module (e.g. `Memory.Allocation`) and re-exported from CPtr/CTypes.

**Comment by lydia-duncan** [comment]
I'm not super bothered by the idea of having `c_` functions that take Chapel-specific concepts as long as we limit it to only Chapel-specific concepts.  I think someone using the C functions is going to already know that C doesn't support things like type arguments and so isn't going to get confused, and it seems unlikely we'll reach a world where programmers know about Chapel but not enough about C and still want to use the `c_` functions

**Comment by ronawho** [comment]
I personally don't mind the current interface. It doesn't exactly match the C interface, but it makes some nice cleanups to an asymmetric C interface so it doesn't both me and I would personally be fine leaving things as-is. Even when I was learning chapel I don't think I was confused by these interfaces, I thought it was a nice cleanup to make malloc/calloc interfaces match and adding types seemed like a nice improvement. That said, I'm not opposed to changing the interface if others want, so here's my feedback on the specific proposals.


> having them mimic the C routines more closely and call the C routines directly since that's what their names imply (vote 👍 for this option

I really, really don't want to expose routines that directly call c malloc/calloc/free. That will kill communication performance on many platforms and will increase the likelihood for mixed allocation calls which can lead to really hard to track down bugs. If a user really needs to use the system malloc, I think we should make them extern to it.

> removing the c_ prefix in order to avoid the implication that these are C routines (vote ❤️ for this option)

 If we drop `c_`, I think we need to add something else to indicate these are narrow/local pointers.

> removing the c_ prefix and working harder to make the routines Chapeltastic. 

I'd be fine with this, but would again want something to indicate it's a local pointer. I don't find optional arguments much simpler or better than different functions so while I don't oppose this, I'm not strongly in favor of it.

**Comment by mppf** [comment]
> I'd be fine with this, but would again want something to indicate it's a local pointer.

This seems like a great point. Maybe if we want to have a more unified thing, we have `Memory.Allocation.alloc` that returns a `_ddata` (with whatever user-facing name we have for that) and `c_alloc` that calls that but casts it to a c_ptr.

**Comment by gbtitus** [comment]
With regard to this:

> they don't call down to the corresponding C routines, but our runtime's version of the routines (which is sometimes the C routines, but more often jemalloc)

For me the biggest issue isn't whether these end up calling libc's `malloc()` or jemalloc's equivalent (which after all is supposed to have the same external behavior), it's that because these get to whatever the underlying allocator is via our runtime interface, they are subject to memory tracking where direct calls to that underlying allocator would not be. This is what causes problems when we either allocate directly from libc/jemalloc and free through the (misnamed) `CPtr.c_free()` or vice-versa: we end up confusing the memory tracking subsystem one way or another.

I voted :tada: (remove `c_` prefix and make them Chapeltastic) because that seems the least confusing (to users) of the given alternatives.

However, I think a better solution would be to remove these altogether, add a `ChapelRuntime` module to provide authoritative definitions of the few runtime interface functions we feel might be important for user code to use, and then put definitions of `chpl_malloc()`, `chpl_calloc()`, `chpl_free()` etc. in there.

**Comment by mppf** [comment]
> However, I think a better solution would be to remove these altogether, add a ChapelRuntime module to provide authoritative definitions of the few runtime interface functions

I guess to me this falls into the same situation as the Builtins module - being implemented in the C runtime is a property of these functions, not so much something about what functionality they offer. But it would be fine with me if we only had `Memory.Allocation.alloc` (say) and it was easy (maybe implicit?) to cast from the ddata that returns to c_ptr.

**Comment by gbtitus** [comment]
> I guess to me this falls into the same situation as the Builtins module - being implemented in the C runtime is a property of these functions, not so much something about what functionality they offer.

Sure, their topmost implementation could be module code instead of the runtime. The important thing is that these functions have to do with Chapel tracked (and registered, in some configurations) memory allocation. That's a functional difference, not merely a different implementation of the same external behavior. They wouldn't have to be in a `ChapelRuntime` module. We could put them in the same module as all the memory tracking stuff. But users have to understand that they can't just cast what they get from this to a `c_ptr` and then give the latter to `POSIX.free()`, for example. The things this interface deals with have semantics beyond just allocation.

**Comment by riftEmber** [comment]
These design decisions are addressed by the [CTypes design subteam](https://github.com/Cray/chapel-private/issues/4824); `c_*alloc` will be merged into one `allocate` and a corresponding `deallocate`. See design discussion [closing comment](https://github.com/Cray/chapel-private/issues/4824#issuecomment-1553476379) for more information.
