### ISSUE TITLE
What should `c_nil` be named?  Should it even exist?

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#18014]
It's been pointed out that `c_nil` is a weird identifier: the `c_` prefix indicates that it's referring to a C symbol named `nil`, but it's not.  The rationale for this was "It's C's equivalent to Chapel's `nil`", but that doesn't really hold up.

For that reason, it's been proposed that we either:

* change it to `c_NULL`: this would be more consistent with our other `c_` prefixes (vote :+1:)
* retire it in favor of just using `nil` for this purpose (related to issue #13520)  (vote :heart:)
* something else...?

**Comment by lydia-duncan** [comment]
For some reason, `C_NULL` seems more appealing to me than `c_NULL`, even though the `C_` part is a slight departure from our other prefixes.  Maybe because all caps seems like it should apply to every part of a name rather than just the "original name" part

I like the idea of still having `C_NULL`/`c_NULL` in some form, but it does seem extraneous so I'm not vehemently opposed to removing it and just using `nil`

**Comment by gbtitus** [comment]
I feel like the more separate we can keep the notions of Chapel references and other language's (especially C's) pointers the fewer mistakes people coming from those other languages will make when thinking about and writing Chapel code. I'm therefore not in favor of letting people use Chapel's `nil` where a `c_ptr` value is required, and voted for `c_NULL`.

As an extension nobody will like, I believe the C standard allows constant integers wherever pointer types are required and says explicitly that the integer value `0` is the "null pointer value". We could do the same for `c_ptr` values and simply define

```
param const c_NULL = 0;
```

Okay, just kidding, I'm not seriously proposing this.

**Comment by king-11** [comment]
I think retiring it would save the confusion but `C_NULL` as @lydia-duncan suggested seems appealing considering that is more aligned with `C` but I think since we will be moving towards a `POSIX` module we can entirely remove it from here and make sure to bring it back as `C_NULL` in the `POSIX` module

**Comment by riftEmber** [comment]
The [CTypes design subteam](https://github.com/Cray/chapel-private/issues/4824) has decided `c_nil` should be removed in favor of `nil`. This will be implemented by https://github.com/Cray/chapel-private/issues/4870. If we do ever re-introduce a concept like `c_nil`, the subteam favors naming it `c_NULL` to match the naming pattern of `c_` followed by the exact name of the thing in C.
