### ISSUE TITLE
LLVM Assertion Error in C interoperability example

### ISSUE THREAD

**Issue by ShreyasKhandekar** [chapel-lang/chapel#18022]
There seems to be some issue with the LLVM back-end on a case I am coming across with an example to demonstrate Chapel's interoperability with C.

I was trying a simple struct example:
The Chapel file is:
```c
extern record data{
    var x: c_int;
}
extern proc getNewData() : data;

var d :data;
d = getNewData();
```
The .h file is:
```c
typedef struct _data data;
data getNewData(void);
```
and the .c file is:
```c
struct _data {
    int  x;
};
data getNewData(){
    data *d = malloc(sizeof(data));
    d->x = 5;
    return *d;
}
```
I have omitted some boilerplate code from all files like `#ifndef`s and the necessarry includes
With the above files, I got the following error during compilation:

```bash
internal error: assertion error [llvm/clangUtil.cpp:2922]
```

 It does not matter if I return a pointer (and use the ref intent) or just return the struct itself. I get the same error.

The way to fix this was to move the struct definition completely into the header file instead of the C file.
But I believe it should also work if the struct definition is in the C file.

**Comment by mppf** [comment]
> The way to fix this was to move the struct definition completely into the header file instead of the C file. But I believe it should also work if the struct definition is in the C file.

I don't think I agree with this. Because of the way C compilation works, if it's not in the header file, a C compiler compiling something using it (separately, not including the data.c, say) won't have any way to know how many bytes are it `struct _data`.  That means it won't know how to allocate such a variable on the stack as a regular variable or when returning it.

Now, when using the Chapel interoperability features with C, I wouldn't expect Chapel to have magic powers that a C compiler would not. So I would think when you are writing `var d :data;` you are asking the Chapel compiler to do something it cannot (because, without the struct details in the header, how can it possibly know the size of `data` in order to allocate something on the stack?).

It is somewhat common in C or C++ programs to have opaque structs only defined in implementations but AFAIK when this approach is used the functions always accept/return pointers of that type e.g. `struct data* getNewData()`.

Speaking of that
```
data getNewData(){
    data *d = malloc(sizeof(data));
    d->x = 5;
    return *d;
}
```

I know this is just a reprodurer for an error, but this example has a memory leak - I'd expect it to either return `d` as a `data*` or to not call `malloc` in the first place.

**Comment by bradcray** [comment]
Conversations about the proper organization of C code aside, I was curious whether any of @mppf, @dlongnecke-cray, or @daviditen understood what the cause of the assertion failure was and why it's specific to the LLVM back-end?  (FWIW, I encouraged @ShreyasKhandekar to file this under the "all internal errors are bugs" clause.  Or is the point that the assertion failure is _because_ the C header doesn't provide enough information and our compiler assumes that it will have all the information, but in this case it doesn't?  If that's the case, presumably it would be fairly straightforward to replace the assertion with some sort of user-facing error message?  (maybe similar to `testit.chpl:2: error: Could not find C type for data` if the C/H files aren't even provided to the compiler?)  Or are there other cases that this assertion is protecting against for which that error message would not be appropriate?  Thanks.

**Comment by dlongnecke-cray** [comment]
Looking at the code near the assertion, we're just fetching the C struct def from clang and iterating to try and find a field with the same name as in the Chapel `extern record` def. We `INT_ASSERT` to make sure we've found one (and in this case we don't, presumably because it's not in the header).

We could change the INT_ASSERT to be something user facing, e.g. perhaps an error like

```
error: The C compiler was unable to find C declaration of record 'data' containing field 'x'
```

**Comment by bradcray** [comment]
That sounds like a great improvement, David.  I could also imagine shortening this to something like `Could not find a definition for 'data.x' in the external C code` (or perhaps "external C headers" and/or "field 'data.x'" to be more precise?).

**Comment by dlongnecke-cray** [comment]
Note that this is fixed for the `LLVM` backend, but this error can still occur with the C backend (and is only caught by the C compiler). Not so sure what to do about it in that case.

**Comment by mppf** [comment]
When working with libevent, @king-11 was running into a similar but slightly different issue. I've created #18289 for that.
