### ISSUE TITLE
Errors Module: Should we change the names of compilerError/Warning/Assert ?

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#18025]
This issue is a discussion of whether we should change the names of compilerError, compilerWarning, and compilerAssert while working towards module stability.

Note that some previous conversation about the names of these occurs in https://github.com/chapel-lang/chapel/issues/16807#issuecomment-738479451 .

Currently we have compilerError, compilerWarning, and compilerAssert. These names have some downsides:
 * seem wordy / long
 * they are asymmetric with the execution-time commands (both because of `halt` vs `error` and because it's just `halt` and not `executionTimeHalt` e.g. )
  * "compiler" as a modifier seems strange and might be innacurate with the Chapel interpreter
  * the current method names are not verbs even though they take some action

On the other hand, these names are fairly clear and people rapidly figure out what these functions do when reading Chapel code.
 
Brainstorming different names, we've come up with:
 * alternatives
   * `compilationError`
 * ways to shorten them:
   * `compError` `chplError` `paramError`
  * ways to make them more verby
    * `haltCompilation`, `haltCompiler`, `emitCompilationError`, `failCompilation, `reportCompilationError`
      * but note, the corresponding `warnCompilation` / `warnCompiler` don't seem quite right
  * having e.g. `halt` with a `compileTime=true/false argument to help with generic programming (but we probably would still want the different function names)
  
Adding a `compileTime=true/false` argument to `halt` / `assert` / `warning` doesn't impact module stability so isn't a primary concern (unless the thought of adding it causes us to want to choose particular names).

**Comment by lydia-duncan** [comment]
I'd like to put a vote for "keeping their names the same" :)

**Comment by jeremiah-corrado** [comment]
In a recent design discussion on this topic, @mstrout, @dlongnecke-cray, and I unanimously decided not to change the names of `compiler[Error/Warning/Assert]`. 

We considered several alternative names for the procedures; however we we were ultimately not in favor of renaming for a couple of reasons:
1. The idea that `compilerError` and `halt` have analogous functionality yet lack similarity in their names did not hold water for us. This is because `halt` causes an abrupt stop to the execution of a program, while `compilerError` does not necessarily halt the compiler immediately (particularly within Dyno's new resolution framework), but rather notifies the compiler that there was some error, and that resolution within the relevant section of code cannot continue. As such, we were not in favor of names like `haltCompilation`.
2. This left us with potentially more descriptive names like `emitCompilationError`; however we decided that the churn would not be worthwhile for a marginal improvement in naming accuracy

We also considered combining them with with the analogous runtime procedures (`halt`/`warning`/`assert`); however we were also opposed to that option for a few reasons:
1. the non-analogousness of `halt` and `compilerError` made us wary of combining them under a single procedure
2. the change could have the potential to make code either more verbose `halt("mesage....", compileTime=true);` or unclear `halt("message...", true);`
3. we've established a precendent of not housing distinct functionalities under the same name and distinguishing behavior using a `config param` (a la `list(parSafe=false)`/`list(parSafe=true)` -> `list`/`parallelList`)
4. it's not clear how the `errorDepth` argument would behave at runtime

**Comment by bradcray** [comment]
W.r.t. items 1 and 2 in the first list and 1 in the second list, it seems like a fix would be to rename the execution-time `halt()` routine to `error()` (?).  

[Don't interpret this as second-guessing the decision, though, the other points hold up for me and are things I wasn't entirely comfortable with despite originally being on the "unifying seems attractive..." side in the initial conversations].

**Comment by lydia-duncan** [comment]
Closing, since it looks like the decision was not to change them
