### ISSUE TITLE
Syntax for renaming fields inside an extern record

### ISSUE THREAD

**Issue by ShreyasKhandekar** [chapel-lang/chapel#18062]
Using the current set of C interoperability features, we can declare `extern record`s as follows:
```chapel
extern record Foo {
  var x: c_int;
  var y: c_string;
}
```
Just like we rename `extern proc`s or `record`s, we can also rename the fields within the struct as follows:
```chapel
extern record Foo {
  extern "x" var z: c_int;
  var y: c_string;
}
```

This begs the question as to what happens differently when we use the `extern` keyword for the fields of the structs as opposed to not doing so?

If the purpose of the `extern` is just to enable the renaming of the field, are we committed to this syntax?

**Comment by bradcray** [comment]
My impression is that nothing happens differently between declaring an `extern record` field as `extern` vs. normal.  Requiring the `extern`, as in:

```chapel
extern record Foo {
  extern var z: c_int;
  extern var y: c_string;
}
```

seems like overkill in that the fact that the fields are within an extern record, so should automatically be considered extern.  

But a limitation of that is that we have no way of renaming the symbol for Chapel's purposes if the C name happens to conflict with a Chapel reserved word (@ShreyasKhandekar hit a case like this which led to this issue where the field was named `domain`; previously @daviditen ran into a similar case in which (I believe it was) Fortran's C array interop capabilities used a reserved Chapel term as well).  Since currently the only way we have of giving a different C name for a symbol is to declare it as `extern` (or `export`, though that doesn't seem appropriate for this scenario), this is the only way to work around it.

So for me, the key question from the OP is:

> are we committed to this syntax?

Where my main reaction is "it feels slightly odd, but I don't have a proposal in mind that I like better than this workaround."  And if we generally felt committed to it, we should be sure to document it.

**Comment by mppf** [comment]
> it feels slightly odd, but I don't have a proposal in mind that I like better than this workaround

I have the same reaction, FWIW.

**Comment by ShreyasKhandekar** [comment]
> seems like overkill in that the fact that the fields are within an extern record, so should automatically be considered extern.

I agree with this. In terms of documentation of this syntax we can document this as
"Since it is redundant to use the `extern` keyword for fields inside an `extern record`, you may omit the `extern` keyword on this occasion, but if you want to rename the fields then we will have to use `extern` as usual"

I don't know why but it sounds less odd to me when I put it like that.

**Comment by mingodad** [comment]
Why not use `as`:
```
extern record Foo {
  var z as f: c_int;
  var y as g: c_string;
}
```

**Comment by bradcray** [comment]
That's definitely an intriguing proposal, @mingodad (for historical context, I'm pretty sure the `extern "c_name" var chpl_name;` capability pre-dated our `as` syntax).  I think if we were to go this route, we'd want to deprecate the `extern "c_name" ...` version altogether for consistency.  And we might want to not permit (or at least, generate a warning) if this form were applied to (say) fields of non-extern records, normal Chapel variables, etc.  I also like that it would get rid of the reliance on string literals for this purpose.

Oh, except that I think I'm remembering that the reliance on string literals was actually beneficial in some cases where the external symbol name either wasn't compatible with a Chapel identifier, or wasn't as simple as a Chapel identifier...  (e.g., maybe we'd use a short expression to refer to the external symbol).  I'd need to search the code and my memory more to remember what the example was and see whether I thought it was compelling or frightening.

**Comment by mppf** [comment]
Right, we use the string literal in the renaming in two ways - 1) for something like `struct stat` and 2) in some cases to compute the name with a param-returning function.

Regarding this:

``` chapel
extern record Foo {
  var z as f: c_int;
  var y as g: c_string;
}
```

I agree that it's intriguing but what bugs me about it is that since setting the cname is only really useful for interoperability I want the renaming to mention `extern` / `export` (or something interoperability-ish) rather than just using `as`. Now, in the above, I can see the `extern` on the record, but @bradcray was just saying we'd deprecate the `extern "cname"` version - which I wouldn't view as an improvement. (i.e. I like `extern "cname" var chplname` more than `var chplname as  cname` (or is it `var cname as chplname`? -- the syntax doesn't make it very clear which one is the Chapel name).

**Comment by mingodad** [comment]
English is not my primary language but based on usage by other programming languages I would say it should be:

orignal_name `as` new_name

So:
```
extern record Foo {
  var original_name_z as new_name_f: c_int;
  var original_name_y as new_name_g: c_string;
}
```

**Comment by mppf** [comment]
I think that means that it would be `var cname as chapelName`, in terms of the C and Chapel names of the same thing.

**Comment by mingodad** [comment]
And if by chance tomorrow `chapel` decide to support more than one exteranl `ABI` then the C++ route:

```
extern "C" var original_name_z as new_name_f: c_int;
extern "C++" var original_name_z as new_name_f: c_int;
extern "RUST" var original_name_z as new_name_f: c_int;
extern "PASCAL" var original_name_z as new_name_f: c_int;
...
 
```

**Comment by bradcray** [comment]
Oh wait, I'm realizing a fatal flaw in @mingodad 's proposal, which that one of the points of requiring the renaming (and the one that led to @ShreyasKhandekar opening this issue) is to support the case where the external identifier is a reserved word in Chapel.  So we wouldn't be able to support, for example, `var domain as chplDomain` because `domain` is a reserved word (at least, we wouldn't be able to without creating rules that would permit any renaming declaration to accept reserved words instead of identifiers as the first of the two symbols.  For me, that makes the `as` based approach, even less appealing.

> extern "C" var original_name_z as new_name_f: c_int;

We've discussed expanding `extern` to refer to non-C languages in the future where `C` would be the default, but I think if/when we do that, we're less likely to use a string identifier to enumerate the external languages, and more likely to use an enum (since there will only be a fixed number of external languages that the compiler is likely to know about, so they ought to be enumerable; and strings seem like a weak way to support such a finite set of enumerable options).

**Comment by mingodad** [comment]
It seems that for `C` structs we don't need rename at all we only need the correct type and order of declaration (maybe knowledge of padding?), any valid `chapel` name can be used it doesn't need to have and relation at all with the original name (although when possible it's good to have the same name to facilitate debug, cross reference, ...) because it's not located by name like functions in shared libraries:

Original C declaration:
```
struct CStruct {
 int domain;
 char *var;
};
```

 Chapel declaration:
```
extern record ChplName {
 int any;
 char *again_any;
};
```

**Comment by mingodad** [comment]
Well maybe the struct/record name should need rename to allow the generated code match the original `type` name.

**Comment by bradcray** [comment]
> because it's not located by name like functions in shared libraries:

Given the current Chapel compiler architecture, this is incorrect.  We do rely on knowing the C field name in order to match the Chapel field to the C field and generate proper code.  Put another way, we do not try to guess the offsets that the C compiler will use in order to generate our own offsets from a struct's base address using pointer arithmetic; instead, we generate code that refers to the C field by name (for the C back-end) or looks up the C field in the IR (for the LLVM back-end).  Note that this approach has also permitted specifying incomplete information about a struct such as not listing every field, not providing types for everything, reordering fields, etc. and that this has occasionally been a great productivity boost ("I only care about these two fields, so why do I need to teach the Chapel compiler about all the other ones?").

**Comment by mingodad** [comment]
I'm new here and don't know the inner guts of `chapel` but as you explained it I can see the the point. Thank you !

**Comment by ShreyasKhandekar** [comment]
I think if we like the `as` syntax better, it should not be too much effort to allow string literals to be used there as well.

>  I think if we were to go this route, we'd want to deprecate the extern "c_name" ... version altogether for consistency.

I agree with this as personally, though the current syntax does make sense, the terminology does not make it abundantly clear to someone who sees it for the first time that this is a form of renaming the record/proc/variable.

One alternative would be as follows

```chapel
extern record "Foo" as Bar {
  var x: c_int;
  var y: c_string;
}
```

and 

```chapel
extern record Foo as Bar {
  var "x" as z: c_int;
  var y: c_string;
}
```

where the quotation marks are optional as demonstrated in the general case and only if we encounter a chapel reserved keyword like `domain` do we have to use them.

**Comment by mppf** [comment]
I feel fairly positive about the proposal above, but I'd (personally) always require the quotation marks rather than making them optional. To me this comes across as a modest readability improvement on what we have today:

`extern "Foo" record Bar` becomes `extern record "Foo" as Bar`, which at least reads better.

I'm not sure how I feel about `var "x" as z` because again I don't think this renaming is relevant unless in an extern context. I would be satisfied if that syntax generated an error if it is applied to something other than an extern var or field.

**Comment by bradcray** [comment]
I agree that the re-introduction of quotes into the `as`-based proposal makes it stronger and would also tend to require the quotes for consistency, at least as an initial approach.  I tend to agree that we wouldn't want to support renaming things that aren't `extern` (either themselves, or by virtue of what they're being defined within).

**Comment by bradcray** [comment]
@mingodad, @ShreyasKhandekar: I've forked this `extern var "c_name" as chpl_name...` proposal off into its own issue: #18174 

For the question in this OP, it seems as though the response has generally been "Yeah, it seems like the current approach is reasonable given where we are today."  To that end, @ShreyasKhandekar, I was curious what you thought about closing this issue (or, otherwise, what you think we should do in order to close it in good conscience?).  Thanks!

**Comment by ShreyasKhandekar** [comment]
I think since we've got that proposal into a new issue, we can reasonable close this one.
One thing though that I believe should be part of the proposal is that we were using the `extern` keyword to rename fields inside an `extern` `record` and it should mention that if we use the `as` operator we won't need to (and shouldn't) do that.

If you could please get that in the OP for the new issue you've created I would feel good about closing this one.

**Comment by bradcray** [comment]
OK, I've updated the OP if you want to take a look.

**Comment by ShreyasKhandekar** [comment]
Looks good to me! Thank you for adding that.
I am closing this issue now.
