### ISSUE TITLE
What are the expectations from the `list` data structure?

### ISSUE THREAD

**Issue by e-kayrakli** [chapel-lang/chapel#18095]
Our current `list` module was designed based on Python's `list. The historical context in which it was added was when we wanted to stop supporting arrays-as-vec, and wanted a replacement for it.

As a quick summary, our `list` is implemented as a growing array of arrays, implemented using ddata.  This structure supports O(1) insertion and removal at the end, but anywhere else, they require shifting which is O(n) operation in the worst case. You can opt-in for parallel-safety, but then some methods cause compilation errors.

Based on this design and some specific questions, there were some design questions raised in today's module review meeting that begged the question "what do we want the `list` structure to be?". These questions are

- The name `list` suggests O(1) insertion and removal, which is not the case for our implementation. So, is `list` the right name?
- Should parallel safety be controlled by a flag, or a parallel-safe list is a different data structure?
  - We've based our design on python's `list`, but we have much different concerns than Python, of which parallel-safety is one.
- What do do with `pop` et al: https://github.com/chapel-lang/chapel/issues/16194
  - The name `pop` intimates that this is a stack, but it isn't.
  - Should we also add `push`?
  - What about `enqueue`/`dequeue`, then?
- How can we accommodate different list-like data structures?
  - We have `vector` and `unrolledLinkedList` with different performance implications. Are they "list"s?

All these questions led us to re-think what we want the `list` data structure to be. Do we want;

1. non-parallel-safe data structure with O(1) insertion and removal
   This is what "list" means for most, but we don't have O(1) insertion and removal at arbitrary locations.
2. an analogue for Python's `list`
   We have parallel-safety that complicates matters. It is not clear whether what `list` is in Python (there's no array type in Python, and `list` is as close as you can get) represents what we want our `list` to be. Some of the inconsistencies we have (e.g. `pop` but no `push`) are things we inherit from python that we hope to change.
3. a (optionally) parallel-safe data structure that supports indexing.
   This is what we have today, in my view. The implementation is esoteric and hard to describe in a way that users can argue about complexities of different operations.

(where these are not necessarily mutually exclusive set of options, nor is this an exhaustive list)

Some of the more in-detail design discussions gets stuck because it seems like we're trying to attribute so many properties on a single data structure. Or we don't have a clear vision for what we want the `list` type to be. This issue is to collect some opinions as what people expect from this data strucuture.

**Comment by mppf** [comment]
> O(1) insertion and removal
This is what "list" means for most, but we don't have O(1) insertion and removal at arbitrary locations.

This part does not bother me, FWIW.

My opinion is that we should imagine creating different APIs for sequential and parallel-safe collections, so we might have `sequentialContainer` and `parallelSequentialContainer` as interfaces, e.g.

Then I'd advocate that we split the existing list type into a two separate types
 * a sequential-only (not parallel safe) data structure
 * a parallel-safe data structure

Ideally the names of these types convey that they are more like C++ `vector` than a doubly-linked list (say). (But I don't think we should use the name `vector`).

In terms of doubly-linked lists, it's hard to have a doubly-linked list without internal pointers. I guess it's possible to use a doubly-linked list combined with a hashtable (to go from the element pointer to the list node) or maybe even to use an address trick (e.g. the list pointers are the 2 words just before the value) but I'm not so sure how much O(1) insertion in the middle is actually needed in our standard library in the near term. So I'd probably leave these as future work.

Note that the current algorithm used by `list` is intended to prevent reference invalidation when appending. This is not necessarily needed in all use cases and it probably makes the data structure slower than types that don't do that. Note that reference invalidation can be a problem even for sequential programs. But it's a more severe problem with parallel programs.

When we created `list`, I was concerned about the reference invalidation, but it seems that the parallel-safe API has since evolved so that preventing reference invalidation is a property of the API rather than a property of the implementation. So, it makes sense to me for programmers wanting to avoid reference invalidation to use a parallel-safe sequential collection, and we can move to other things in terms of implementation approach.

**Comment by jeremiah-corrado** [comment]
This issue was discussed in a recent deep dive meeting. Specifically the team focused on the question of whether `list` should be renamed.

This question arose because `list`'s implementation and API focus on O(1) access and efficient appends, so some might expect it to be called "vector" or something else. For some, the name `list` refers more to a linked-list, so renaming the type could avoid that confusion.

The current name comes from Python, but some other languages use `list` for their linked-list type:

| | Python | C++ | Go | Rust | Java | 
| --- | --- | --- | --- | --- | --- |
| growable array | list | vector | *array* | Vec | ArrayList |
| linked list | - | list | list | LinkedList | LinkedList |

It seemed that most people on the team were in favor of keeping the current name. This message is intended to summarize the discussion for future reference or to provide a starting point in case anyone wants to argue for renaming `list`.

**Comment by lydia-duncan** [comment]
I don't think there are any action items for this issue (that aren't already tracked by other issues).  Closing
