### ISSUE TITLE
Should we deprecate `list.sort`?

### ISSUE THREAD

**Issue by e-kayrakli** [chapel-lang/chapel#18100]
This method provides in-place sorting. We've had similar discussions about arrays: https://github.com/chapel-lang/chapel/issues/18089 where we were leaning towards removing a similar method on arrays. Should we do the same for `list`?

**Comment by lydia-duncan** [comment]
Similar to my comment on #18089 - I'm okay with this but only if we add ensure there's an alternate version available for people to switch to when we remove it.

**Comment by bradcray** [comment]
> This method provides in-place sorting.

Looking at the code, it doesn't look in-place to me.  It seems it:

* copies the entire list into an array (serially rather than in any sort of parallel / bulk way)
* sorts that temporary array
* destroys the list
* builds a new list from scratch from the sorted array

This seems like a bunch of hidden cost for something a user could do themselves in 2-3 lines of code without hiding anything or much of a performance difference?  If we were to support a list.sort() routine, I'd expect it to do the sort in-place with the existing memory (being knowledgeable of the list's implementation) rather than allocating an additional O(n) temporary buffer for it and using a general solution.  Even if it had to use the temporary array for some reason, I'd expect it to re-use the existing storage rather de-allocating it and then setting up a new list from scratch.  Finally, I'd probably look for a sort on lists in the `Sort` module, since things it relies on (like comparators) seem to be part of that world, and array support is there rather than as a method on arrays.

It also seems unlikely that today's `list.sort()` would work on an element type that couldn't be copied or didn't have a default value, which seems concerning?

As with #18089, I think we should deprecate this support without replacing it, using a message that encourages users to contact us if they relied on it (where I'm hoping / betting nobody does).

**Comment by e-kayrakli** [comment]
Yeah, I guess it depends on your definition of "in place". The doc says it's in-place, and I think it is because the list value on which this method is called becomes sorted after the call returns, instead of the call returning an entirely new list. But your argument makes sense. At the very least the doc needs to be adjusted.

In any case, I still think that we should remove this method. I don't have strong preference as to whether there should be replacement before we do that.

**Comment by jeremiah-corrado** [comment]
Removing the 2.0 label after #23040 and keeping this issue to track the concerns brought up with the implementation.

**Comment by jabraham17** [comment]
In https://github.com/chapel-lang/chapel/issues/24857, we decided to deprecate `list.sort` and replace it with the following, defined in the `Sort` module

```
proc sort(ref x: list, comparator: ? = new defaultComparator(), param stable: bool = false)
proc isSorted(x: list, comparator: ? = new defaultComparator()): bool
```

There should also be an overload of `sorted` that works on lists.
