### ISSUE TITLE
Reduce the number of ways by which `list` elements can be modified

### ISSUE THREAD

**Issue by e-kayrakli** [chapel-lang/chapel#18101]
We currently have `this`, `set` and `update` methods, all of which can be used to modify the contents of a `list.

- `this`: returns a ref, and the element can be modified using that ref. Gives a compiler error with parSafe=true
- `set`: Takes its argument as an `in` intent, so can be used to achieve a slightly different behavior where the new value is copied into the list (?)
- `update`: A way to update elements in a parallel-safe manner. Only meaningful with `parSafe=true`

It'd be best if we can reduce this number somehow. This is related to handling parallel-safety in `list`: https://github.com/chapel-lang/chapel/issues/18097

**Comment by lydia-duncan** [comment]
Based on name only, I'd remove `update`.  Based on functionality, I'd probably remove `set`?  If the main purpose of `update` is to provide a parallel safe way to change the contents, I'd like it's name to more clearly reflect that in some way.

**Comment by jeremiah-corrado** [comment]
This issue was discussed in a recent deep dive meeting. The following is a summary of the discussion around each of the three "modify" methods on 'list':

This:
---
The group was generally in favor of keeping the square-bracket access on the `list` type. Although returning a reference into the list allows the user to run into reference-invalidation problems, this functionality feels fundamental to the data type and we believe that good documentation will be sufficient for guiding users wrt reference invalidation. (In the `map `stabilization effort, we also decided to keep `this()`).

Poll: should we keep `list.this`:
- yes: 10 👍
- no: -

Set:
---
The set method, has the following signature, where it returns `true` when a value was set successfully, and `false` for an invalid index.
```chapel
list.set(i: int, in x: eltType): bool { ... }
```
Some points of discussion:
- The `map` type's `set` method was renamed to `replace`: https://github.com/chapel-lang/chapel/issues/20323. We might consider doing the same for list's `set` to keep the APIs more uniform.
- Maybe we could reduce the number of modifier methods by keeping this functionality, but renaming it to `update` (i.e., have two overloads of `update`, one that takes an updater/FCF, and another that takes an index and element).
- A question was brought up about why the `x` argument has an `in` intent. Specifically,`in` makes sense for operations like append because a new value is moved into some freshly allocated memory, but with `set`, an already allocated region of memory is simply being replaced by a new element. Could we remove the `in` intent?

On this last question: It appears that the `set` method was [added to `list`](https://github.com/chapel-lang/chapel/pull/16453) along with the `parSafe` mode as a way to update the value of an element, given that `this` is not available in `parSafe` mode. 

Were the argument taken by `ref`, it's value could be modified by another task after `set` is called, but before the value is moved into the list's memory. Taking the argument by `in` intent and using locks within `set` prevents this type of race condition. So, for the serial list, a `ref` intent could be used; but for the parallel and distributed lists, `in` intent should be used.

update:
---

The `update` method calls an "updater" (a record with a `.this(index: int, elt: eltType)` method, or an FCF/lambda with the same signature) on an element in the list.

Points of discussion:
- Update was also added to the list type along with `parSafe` to facilitate parallel safe modifications of an element. With `update`, it is possible to modify the value of an element based on its current value without worrying about interference from other tasks. This is not possible with `set`:
   ```chapel
   var v = lst[5];
   lst.set(5, v + 1); // possible race
   ```
   vs.
   ```chapel
    lst.update(5, lambda(i: int, v: int) {
        v += 1;
    });
    ```
- The map stabilization effort decided to keep the `update` method on the serial map. We may want to do the same for the sake of uniformity. 
    - The counter-argument is that this form of parallel safety isn't strictly necessary for the serial list. We may want to confine the strictly parallel safe features to the parallel and distributed lists.

**Comment by jeremiah-corrado** [comment]
## Final Design Decision:

During a recent design meeting, a sub-team consisting of myself, @lydia-duncan, & @daviditen, decided to rename `list.set` to `list.replace`.

Old API:
```chapel
var myList = new list(0..<10);
myList.set(4, 111);
writeln(myList); // [0 1 2 3 111 5 6 7 8 9 ]
```

New API:
```chapel
var myList = new list(0..<10);
myList.replace(4, 111);
writeln(myList); // [0 1 2 3 111 5 6 7 8 9 ]
```

We also decided to keep the `update` method's current design for the reasons given in the previous comment.

## Discussion and Rationale:

Pros:
- Follows the precedent from `map`'s stabilization. See: https://github.com/chapel-lang/chapel/issues/20323
- We were concerned about the current name for similar reasons that came up during the `map` stabilization discussions. Specifically, it was noted that the name "set" might imply that a new entry would be created in the `map` if the provided key does not exist; however, this is not the case. Instead, `map.set` would return false.
    `list.set` behaves similarly. To avoid similar forms of confusion, particularly on the end of the list:
    ```chapel
    var myList = new list(0..<10);
    writeln(myList.set(10, 111)); // false
    writeln(myList); // [ 0 1 2 3 4 5 6 7 8 9 ]
    ```
    we found that the name "replace" is a more intuitive match for the methods behavior:
   ```chapel
    var myList = new list(0..<10);
    writeln(myList.replace(10, 111)); // false
    writeln(myList); // [ 0 1 2 3 4 5 6 7 8 9 ]
    ```

We also considered renaming the method to `update` (as a second overload of the existing `update` method); however we leaned against this in order to keep the collection APIs more uniform and to make the difference in behavior more clear. Specifically, "replace" does not have a strong connotation that something needs to be computed to create a new value, which matches its behavior. The name "update" might imply that some action has to be taken on the value. By keeping the methods separate, the difference in behavior should be more intuative.
