### ISSUE TITLE
Incorrect result with dot(mat, mat[.., 1]) when using BLAS

### ISSUE THREAD

**Issue by redhatturtle** [chapel-lang/chapel#18118]
### Summary of Problem
Matrix multiplication with the Linear Algebra module gives a different, and arguably incorrect result, when using the BLAS implementation for the multiplication of a matrix by a column subdomain of a matrix. When compiling with BLAS the subdomain is always taken as a line subdomain. Using a `.T` method to transpose the sub-matrix "fixes" the result but obliviously isn't a reasonable behavior either.

It's my understanding that when multiplying matrices and vectors with `.dot` the vector will be assumed as a line when it's in the first argument and a column when it's in the second. And this should not depend on on the shape of the parent array. Furthermore transposing a vector shouldn't affect the results in any way. All the results I got without using BLAS were as I expected.

Obs: The operation seems to work fine with integer arrays, possibly because it never relies on a BLAS subroutine for integers?

### Steps to Reproduce

**Source Code:**

```chapel
use LinearAlgebra;

var matrix : [1..2, 1..2] real = reshape([1, 2, 3, 4], {1..2,1..2});

writeln("Matrix:");
writeln(matrix);

// Works fine. Output is [5, 11] = [1*1+2*2, 3*1+4*2]
writeln();
writeln("dot(Matrix, Matrix[1,..])");
writeln(dot(matrix, matrix[1,..]));

// Transposing the vector makes no difference, as expected.
writeln();
writeln("dot(Matrix, Matrix[1,..].T)");
writeln(dot(matrix, matrix[1,..].T));

// Different behavior depending on Linear Algebra implementations.
// Without BLAS [7,15] = [1*1+2*3, 3*1+4*3]
// With BLAS [5,11] = [1*1+2*2, 1*3+2*4] ???
writeln();
writeln("dot(Matrix, Matrix[..,1])");
writeln(dot(matrix, matrix[..,1]));

// Here transposing the vector "fixes" the BLAS version but has no effect on the other version.
writeln();
writeln("dot(Matrix, Matrix[..,1].T)");
writeln(dot(matrix, matrix[..,1].T));
```

**Compile commands:**
Without BLAS
`chpl --set blasImpl=off test.chpl`
and with BLAS
`chpl -I/usr/include -L/usr/lib64 -lcblas -I/usr/include -L/usr/lib64 -lgfortran -L/usr/lib64 -llapacke -llapack -lcblas test.chpl`

**Execution command:**
`./a.out`

### Configuration Information

- Output of `chpl --version`:
```
chpl version 1.24.1
Copyright 2020-2021 Hewlett Packard Enterprise Development LP
Copyright 2004-2019 Cray Inc.
(See LICENSE file for more details)
```

- Output of `$CHPL_HOME/util/printchplenv --anonymize`:
```
CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: gnu
CHPL_TARGET_ARCH: x86_64
CHPL_TARGET_CPU: native
CHPL_LOCALE_MODEL: flat
CHPL_COMM: none
CHPL_TASKS: qthreads
CHPL_LAUNCHER: none
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: cstdlib
CHPL_GMP: bundled
CHPL_HWLOC: bundled
CHPL_REGEXP: re2 *
CHPL_LLVM: none
CHPL_AUX_FILESYS: none
```

- Back-end compiler and version, e.g. `gcc --version`:
```
gcc (SUSE Linux) 11.1.1 20210625 [revision 62bbb113ae68a7e724255e17143520735bcb9ec9]
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by bradcray** [comment]
@redhatturtle : It appears that nobody has commented on this, but to make sure you're aware, it has been receiving some attention behind the scenes.

As I understand it (and as you may have guessed), the source of the issue is we're passing a pointer to the first element of the column to the BLAS routine without passing the corresponding striding information to tell it how to access the subsequent elements.  So possible fixes (in rough order of attractiveness) would be:

* send the striding information to BLAS as well to access the column in-place (I don't know BLAS well enough to be confident that this is tractable, but it seems likely that it should be)
* copy the column to contiguous memory before passing it to BLAS
* don't support this case and issue an error for it rather than having something like the current behavior occur

Though this showed up in the context of the BLAS routine, it points to a broader issue in Chapel that I thought we had handled already, but apparently not well (enough).  Namely, we've always discussed that we shouldn't permit arrays (or subarrays) that are not contiguous in memory to be passed out to an external formal argument expecting an array (which we interpret as a "C array", effectively).  That is, this program should not compile:

```chapel
require "foo.h";
// which is:
// static void foo(double X[]) {
//  for (int i=0; i<9; i++) {
//    printf("%lf\n", X[i]);
//  }
// }
extern proc foo(X: [] real);

var A: [1..10, 1..10] real = [(i,j) in {1..10, 1..10}] i*10 + j;

writeln(A);

foo(A[.., 3]);
```

but it does today, and prints out:

```
11.0 12.0 13.0 14.0 15.0 16.0 17.0 18.0 19.0 20.0
21.0 22.0 23.0 24.0 25.0 26.0 27.0 28.0 29.0 30.0
31.0 32.0 33.0 34.0 35.0 36.0 37.0 38.0 39.0 40.0
41.0 42.0 43.0 44.0 45.0 46.0 47.0 48.0 49.0 50.0
51.0 52.0 53.0 54.0 55.0 56.0 57.0 58.0 59.0 60.0
61.0 62.0 63.0 64.0 65.0 66.0 67.0 68.0 69.0 70.0
71.0 72.0 73.0 74.0 75.0 76.0 77.0 78.0 79.0 80.0
81.0 82.0 83.0 84.0 85.0 86.0 87.0 88.0 89.0 90.0
91.0 92.0 93.0 94.0 95.0 96.0 97.0 98.0 99.0 100.0
101.0 102.0 103.0 104.0 105.0 106.0 107.0 108.0 109.0 110.0
13.000000
14.000000
15.000000
16.000000
17.000000
18.000000
19.000000
20.000000
21.000000
```

That is, rather than printing the 10 elements representing column 3, it prints 10 elements consecutive in memory starting at column 3.  If this case were to generate a compilation error as intended, then you'd at least have gotten an error from your code rather than mysterious behavior.  And then it'd be up to the LinearAlgebra author to fix their calls to avoid relying on this behavior (by introducing the copy or passing the striding information).

I think the reason transposing works for you is that it essentially introduces a copy.  If you were to explicitly introduce an array copy of the column in question, that should work as well.
