### ISSUE TITLE
Modification to build and install instructions/docs

### ISSUE THREAD

**Issue by ghbrown** [chapel-lang/chapel#18150]
I recently encountered the apparently common "issue" of the Chapel command (`chpl`) not persisting across sessions, and opened a thread about it on the Discourse ([here](https://chapel.discourse.group/t/perisistance-of-chpl-command/6362)). Brad was kind enough to reply, and suggested the conversation be moved here and perhaps expanded in scope a bit.

The thrust of this issue as I see it is to discuss how to make Chapel relatively simple to test drive and install, even for those not intimately familiar with *nix, shells, and building/installing form source. This may involve unifying the various install guides in the docs, or just providing a bit more/less information and relevant links where necessary.

### A Focused Look At My Issue
As an example of why the existing documentation may not be satisfactory is my path to the non-persistence error and subsequent resolution:

interested in Chapel and want to try it out ->
Google "Chapel install" or similar ->
go to first result ([Download Chapel](https://chapel-lang.org/download.html)) ->
using Linux, so get the tar then follow link to [Quickstart guide](https://chapel-lang.org/docs/usingchapel/QUICKSTART.html) ->
this page has no reference to `./configure` or `make install` so `chpl` does not persist ->
Google issue of no persistence * ->
find relevant GitHub issue on Chapel ([here](https://github.com/chapel-lang/chapel/issues/6352)) ->
use `make install` (SOLVED)

*Technically, a link to the contents of `building.rst` IS on the Quickstart page, but it's halfway through a large table at the bottom of the page and is labeled as "for more information". Suffice it to say this link certainly does not stick out.

I think a preferable path might look like:

interested in Chapel and want to try it out ->
Google "Chapel install" or similar ->
go to first result ([Download Chapel](https://chapel-lang.org/download.html)) ->
using Linux, so get the tar then follow link to [Quickstart guide](https://chapel-lang.org/docs/usingchapel/QUICKSTART.html) ->
see note about how persistent install requires following instructions in [Building Chapel](https://chapel-lang.org/docs/usingchapel/building.html#readme-building) ->
these instruction include `./configure` and `make install` (DONE)

### A Slightly Broader Discussion
Reflecting on the situation and looking at things a little more closely, I think the main stumbling block is the Quickstart step. I'm not clear on the target demographic for the Quickstart. Who is spending their time on a full `make` (or a full `make` with third party packages) just to end up with a single terminal instance of the Chapel compiler? If they somehow use that single terminal instance to determine they like Chapel and want to install, they're directed to the full build instructions that seem to have them go through the `make` and `make check` again, finally getting to a `make install` at the very end.
*Brad mentioned most Chapel "pros" historically haven't used a configured and installed version of Chapel, bust since I have no idea what that leaves them to do, perhaps I'm way off base with this paragraph*

Of course I'm not intimately familiar with the Chapel project, but the most sensible and familiar thing for many people might be to just combine Quickstart and Building Chapel into a comprehensive build and install guide (perhaps mentioning the user can try things out before `make install`). `make install` would just be the final step of this unified guide, making `chpl` persistent/adding it to the path.

Any thoughts on streamlining and improving the make and install documentation would be appropriate here. Brad already gave a preliminary suggestion in the Discourse (with the caveat that he'd like to look at the docs more closely):

> My own quick reaction to this is that we should pare the quickstart instructions back to the bare minimum to get a quick start, and then quickly defer to the more detailed documents (like "building") for follow-on information like "if you want the preferred configuration / if you want to install Chapel".

but any related and general discussion would be great.

**Comment by bradcray** [comment]
Thanks for filing this @ghbrown, and in such detail.  And apologies for the delayed response—our "new issue" bot went AWOL, and even though you'd mentioned that you'd filed it on Discourse, it took me until now to find my way over here because of that.

I generally agree with your reaction here, where my general thoughts (summarizing the Discourse response) would be to:
* have something in the QUICKSTART instructions that talks about persistence / installing and refers to the docs as you suggest to address a FAQ proactively
* see what we can do to boil the QUICKSTART guide down further; it goes through cycles of being shorter and sweeter vs. more verbose, and I feel like we're currently in the latter camp
* consider hoisting the configure + make install instructions higher in the building.rst file (e.g., is it at the bottom only because it was added "more recently", or is it really most logical to put it there).

To answer (or at least give you my perspective on) a few of your questions / points:

> I'm not clear on the target demographic for the Quickstart.

I think of the main role of Quickstart as being to get someone up and running with some sort of Chapel instance as quickly as possible, where "quick" has two components:
* keeping it short and sweet rather than complete (i.e., building.rst is like the official documentation for building Chapel; this is like the condensed version that the short-on-time/patience will bother to read and do)
* minimizing build time by avoiding technologies that aren't core to Chapel

And then as a secondary role, to help people who want to spend more time with Chapel find the information they're looking for (the historical role of the table at the bottom).  The challenge we tend to run into is that, over time, everyone wants to say everything they think is important in the quickstart, so it grows over time, and then has to be pruned back to meet the short-and-sweet goal.

I also consider it to serve two rather contradictory audiences:
* those who wouldn't know how to do simple (to us) *nix commands like unpack a .tar.gz file without help
* those who are expert enough that if they see a terse set of steps like this, they can find what they need to do quickly

This also has tended to cause it to grow and shrink over time:  Are we providing enough information for the first group?  Are we being so sensitive to them that we're failing on the "short and sweet" goal?

Back on the "minimizing build time" point, some of the things that quickstart side-steps are:

* sets CHPL_TASKS to `fifo` to avoid having to build the third-party `qthreads` and `hwloc` libraries
* sets CHPL_MEM to `cstdlib` to avoid having to build the third-party `jemalloc`
* sets CHPL_GMP/RE2 to `none` to avoid having to build the third-party GMP/RE2
* sets CHPL_LLVM to none in order to avoid building the third-party LLVM and/or wrestle with whether or not the system has a compatible system-installed LLVM version.  This one will be particularly important in the next release, which tries to use LLVM by default.
* avoids building GASNet (for multi-locale runs) by setting CHPL_COMM=none (that said, this is also the default for most systems, so this isn't particularly specific to quickstart)

In addition to saving build-time, I'd also consider these choices to attempt to minimize the risk of someone hitting a portability issue in code that our team didn't write.  That is, I'd prefer peoples' first impressions of Chapel to be "I was able to quickly get an implementation that did the things I'd heard about in Chapel talks / docs" rather than "My build broke on a third-party package due to my use of a system / compiler that the Chapel team doesn't test against."

>  Who is spending their time on a full make (or a full make with third party packages) just to end up with a single terminal instance of the Chapel compiler?

In case it's not clear:  it's not really a single-terminal instance; it's just that you need to re-source the quickstart file (e.g., `. util/quickstart/setchplenv.bash`) in each shell in which you want to use it.  The original instance will work across multiple shells, it's just that something needs to add it back to your PATH so that your shell can find it again.  Maybe this is something we should clarify?  (e.g., "If you want to re-use this installation across multiple shells or sessions, make sure that each of them re-sources the setchplenv file?").

> they're directed to the full build instructions that seem to have them go through the make and make check again

I think of the second build / first non-quickstart build as being less about "now I want to install it" and more like "now I'm willing to invest some build time to get more features / performance" (and, hopefully by that point, they're invested enough that if we're unlucky enough that a third-party package or dependence breaks their build, they'll let us know about it rather than going through life thinking "I tried building Chapel once; it didn't work.")

That said, I would like to look at the Quickstart and building files to try and determine:
* for a power user, could they do a full build (with or without `make install`) without having to read all of building.rst?
* could we somehow move the first discussion of `make install` earlier, with a branch between:
  * "Maybe you want to use Chapel where it is and modify your dotfiles or source a bash file each time you want to use it?" vs.
  * "Maybe you want to do a configure + make install type of approach?"
To let users know about both modes earlier and get them where they want to be?

> Brad mentioned most Chapel "pros" historically haven't used a configured and installed version of Chapel, bust since I have no idea what that leaves them to do

To shed some light on what I was alluding to:  Most of us are working from clones of the github repo; and as developers, we often have multiple clones in order to have multiple plates spinning at a time, so have various dotfiles or shell aliases or whatever to switch between copies, getting the right settings and path, etc.

> but the most sensible and familiar thing for many people might be to just combine Quickstart and Building Chapel into a comprehensive build and install guide

My slight reservation to this (and the reason that we're in the state we're in) is that if the first thing I'm directed to is a massive file, it gives me a significant pause about whether I want to continue, even if in practice I only end up having to read the first section with the quickstart instructions.  Somehow the "short-and-sweet" quickstart guide's tl;dr mode seems less daunting to me, and then knowing that there are richer documents once I'm ready to invest more time is reassuring?

**Comment by ghbrown** [comment]
Unlike third party build issues/errors, I don't think time is a big factor/concern. The quickstart with no third party software took 4:51, while the second build in the quickstart guide (the more full-featured version) took 5:38. I honestly wouldn't have noticed this difference unless I timed it. Perhaps these aren't the two builds I should be comparing though?

> In case it's not clear: it's not really a single-terminal instance; it's just that you need to re-source the quickstart file (e.g., . util/quickstart/setchplenv.bash) in each shell in which you want to use it.

As somebody (maybe) approaching moderate familiarity with *nix, shell, and building from source, this is a somewhat new concept to me. Personally, I would not expect most users who just want to get a Chapel compiler and write some Chapel to fully understand this point (or more importantly want to use Chapel this way).

>To shed some light on what I was alluding to: Most of us are working from clones of the github repo; and as developers, we often have multiple clones in order to have multiple plates spinning at a time, so have various dotfiles or shell aliases or whatever to switch between copies, getting the right settings and path, etc.

I see. I certainly expected a `make install` sort of experience where I build the compiler once, then use it until I feel like upgrading to the new Chapel release. As the language becomes more widely adopted I think this is what most of the users will expect as well.

As for power users versus *nix beginners, I would say don't stress too much about either one (but especially the power users). As long as you clearly delineate the commands visually (in code blocks, like is already done) power users should be able to scrape up what they need very easily.

### Minimal action items
To reiterate, I think the minimal action items here are:
- give a link to and mention `building.rst` early in the Quickstart
- add a discussion of persistence (and so ways to use Chapel) in the Quickstart and `building.rst`
- hoist up the configure/install discussion and steps in `building.rst`, perhaps just putting it in the main discussion with a note like "if you would like to install Chapel for automatic persistence across sessions, `make install` (most users should do this)"

### Outline for single build guide
I still think it is possible (and preferable) to do this all in a single build guide though (no Quickstart). Here's how I would do it:
- **set up your environment**

*CHOOSE ONE OF THE BELOW*
first timers should create a compatibility focused environment via

```source util/quickstart/setchplenv.bash ```

power user and those who have already built with the above `source` should build a more full featured and performant version of Chapel in a new terminal, starting the process with

```source util/setchplenv.bash ```

and continuing the rest of the steps unchanged. If you are going to do performance testing of Chapel, please also see [performance tips](https://chapel-lang.org/perf-tips.html) in addition to building the full featured version of Chapel.

*if you are using a non-*nix environment (Cygwin-Windows, Mac OS) some environment settings may need to be set manually, consult the [environment setup guide](https://chapel-lang.org/docs/usingchapel/chplenv.html#readme-chplenv)

- **make chapel**

```make```

*brief discussion about GNU make, how to check their version, `gmake`, etc*

- **make check**

- **install your Chapel compiler (or set up automatic sourcing)**

most users will want to run

```make install```

to ensure the Chapel compiler command `chpl` persists, however, it is also possible to *discussion about sourcing/storing configurations*

- **compile and "Hello, world" tests**

- Makefile Targets and Makefile Options can still lurk at the bottom of the guide page

**Comment by bradcray** [comment]
> The quickstart with no third party software took 4:51, while the second build in the quickstart guide (the more full-featured version) took 5:38.

That's a smaller difference than I would've guessed, admittedly.  Was this with `make` or `make -j`?  (I'm guessing the former).  And by any chance, did you do a `make clobber` between the two steps?  (if not, the second build likely benefitted from the compiler having already been built in the first step).  For reference, I got 4:11 for quickstart

That said, even if the build times were identical, I think the fact that the quickstart mode avoids the potential for third-party portability issues still makes it worthwhile, personally.

In addition, things are about to get more thorny with the 1.25 release (I'm assuming  you're using 1.24?) in that the LLVM back-end will be used by default in the preferred build solution, where (a) building LLVM from the third-party directory definitely blows up the build-time of the "more full-featured version" significantly (sometimes by hours) while (b) using a system LLVM has not been as smooth an experience for all users and configurations as we hope for it eventually to be.

> Personally, I would not expect most users who just want to get a Chapel compiler and write some Chapel to fully understand this point
> ...
> As the language becomes more widely adopted I think [make install] is what most of the users will expect as well.

I agree with you and agree that one of the main takeaways of this issue is that we should clarify this.  In spending a bit more time re-acquainting myself with the quickstart instructions today, I'm [re-]finding the paragraph that starts with "Note that the environment settings from util/setchplenv.bash will not persist beyond this terminal session." and am thinking that this could be fleshed out to clarify this and to better point to the configure + install-style instructions.

> As long as you clearly delineate the commands visually (in code blocks, like is already done) power users should be able to scrape up what they need very easily.

I definitely agree with that as well, and wasn't trying to say more than that:  that we want them to easily be able to find the code blocks that tell them what we're expecting people to execute.

Thanks for the suggestions on how to potentially refactor this into a single file (or even just a clearer quickstart file).  I'll definitely stew on that some more as I'm wrestling with this question, and hope to make at least some modest improvements before the next release.

**Comment by ghbrown** [comment]
Yes, this was a serial `make`. I did not clobber between steps, but did `make clean`. Also, I am on 1.24-1.

> I'm [re-]finding the paragraph that starts with "Note that the environment settings from util/setchplenv.bash will not persist beyond this terminal session." and am thinking that this could be fleshed out to clarify this and to better point to the configure + install-style instructions.

I believe I saw that when I was hunting for the solution to my original issue, but was unsure of how that would work, and was looking for something more `make install`-like. I think any clarification/further explanation here would be great.

Glad I could provide my view on user problems with the instructions and docs, and please let me know if I can help in any way.

**Comment by bradcray** [comment]
Hi @ghbrown : I finally got back to this (just in time for this month's Chapel 1.25 release) and if you're interested in reviewing the results, they're in https://github.com/chapel-lang/chapel/pull/18404 (and should be live on the web in a few more days, once I get a review from someone on the team).

I didn't end up taking the "one file to rule them all" approach that you suggested, but tried to put more information right up front in QUICKSTART.rst to make it clear what the file's goal is (to be a tl;dr type of experience) and to point readers off to chplenv.rst and building.rst if they wanted full details rather than the cliff's notes version.  I also pointed to the "preferred configuration" earlier in the instructions so that someone savvy could avoid the stripped-down configuration if desired. I also put a section about using the installation across multiple shells/sessions, which in turn points to the relevant details in building.rst.  I don't think it's perfect for your profile / matches what you would do left to your own devices, but I think it's a significant improvement on what we had before and hopefully will prevent confusion / get people where they want to be more quickly.  If you have any comments or feedback, I'd be happy to receive them.

**Comment by ghbrown** [comment]
Thanks for taking time to address this. The PR definitely looks like it would have helped my case, and will be more clear for those expecting a `make; make install` sort of experience.

I'll be switching to Chapel 1.25 when it comes out, and I'll use the new docs when I do. Of course I know the solution to my original issue now, but I'll try to use the docs like I don't and report back.

**Comment by bradcray** [comment]
Thanks for taking a look!
