### ISSUE TITLE
Bug with overloaded return intents

### ISSUE THREAD

**Issue by dlongnecke-cray** [chapel-lang/chapel#18205]
In the following program, I expect assignment to `var` or `const` to select the overload of `makeRec` that returns by value. This is my understanding according to the spec: [Choosing Return Intent Overloads Based on Calling Context](https://chapel-lang.org/docs/language/spec/procedures.html#choosing-return-intent-overloads-based-on-calling-context)

```chapel
record rec { var x = 0; }

var gRec = new rec();

proc makeRec(): rec {
  writeln('proc makeRec(): rec');
  return new rec();
}

proc makeRec() ref: rec {
  writeln('proc makeRec() ref: rec');
  return gRec;
}

proc makeRec() const ref: rec {
  writeln('proc makeRec() const ref: rec');
  return gRec;
}

proc test() {
  writeln('T1: store in var');
  var x1 = makeRec();
  writeln();

  writeln('T2: store in ref');
  ref x2 = makeRec();
  writeln();

  writeln('T3: store in const ref');
  const ref x3 = makeRec();
  writeln();

  writeln('T4: store in const');
  const x4 = makeRec();
  writeln();

  writeln('T5: call without assignment');
  makeRec();
}
test();
```

For the `T1` and `T4` cases I would expect the value overload of `makeRec` to be selected, but the `const ref` overload is selected instead.

```
T1: store in var
proc makeRec() const ref: rec

T2: store in ref
proc makeRec() ref: rec

T3: store in const ref
proc makeRec() const ref: rec

T4: store in const
proc makeRec() const ref: rec

T5: call without assignment
proc makeRec(): rec
```

**Comment by bradcray** [comment]
Could it be that the current behavior is because of copy elision—i.e., we determine that the record created in the routine is dead and can be stolen back at the callsite?  So calling the `ref` version avoids a copy that we'd have to make if we were returning by value?  Can you try disabling copy elision to see how that change the behavior?

**Comment by dlongnecke-cray** [comment]
I compiled with `--no-copy-elision` and got the same output:

```
T1: store in var
proc makeRec() const ref: rec

T2: store in ref
proc makeRec() ref: rec

T3: store in const ref
proc makeRec() const ref: rec

T4: store in const
proc makeRec() const ref: rec

T5: call without assignment
proc makeRec(): rec
```

**Comment by mppf** [comment]
So, at the time that the compiler is choosing among the return intent overloads, it hasn't yet decided to elide the copy. The result is that it sees that the result of the ContextCallExpr is used as an argument to an `init=` call, and that function is accepting the argument with `const ref` intent. As a result, it chooses the `const ref` return intent overload.

I suspect that the most straightforward way to resolve this issue is to adjust resolution somehow. One approach is to lower `ContextCallExprs` + `PRIM_INIT_VAR` in resolution as  done for context managers here https://github.com/chapel-lang/chapel/pull/18227/files#r694842155 . Another approach is to adjust `PRIM_INIT_VAR` lowering itself to choose among the ContextCallExprs on the RHS. It seems that `PRIM_INIT_VAR` is already leaving out the copy for `var x = returnRecordByVal()` cases without the ContextCalls.
