### ISSUE TITLE
Internal error RES-LOW-ORS-1902 related to Errors and recursive iterators?

### ISSUE THREAD

**Issue by cassella** [chapel-lang/chapel#18218]
### Summary of Problem

I was trying to rework `test/library/packages/Curl/check-http.chpl` to
handle errors in order to ensure the server is stopped when an Error
is thrown.  I found an internal error, which I was able to narrow
down:

### Steps to Reproduce

**Source Code:**

```chapel
module CheckHttp {
  use FileSystem;
  use IO;

  proc main() throws {
    for f in findfiles() {
      var filereader = open(f, iomode.r).reader();
    }
  }
}
```

```
check-http.chpl:21: internal error: assertion error [resolution/lowerIterators.cpp:1902]
```

or

```
> check-http.chpl:22: internal error: RES-LOW-ORS-1902 chpl version 1.25.0 pre-release (31330febf2)
```

which is

```

// Return an appropriate IBB insertion point for an outbound goto 'gt'.
// 'loopRef' is the forLoop or its copy for lowering, whichever is inTree().
// 'IC' is the forLoop's _iteratorClass, or NULL if lowering a ForallStmt.
//
static Expr* ibbInsertPoint(Expr* loopRef, Symbol* IC, GotoStmt* gt) {
  DefExpr* gtTarget = toSymExpr(gt->label)->symbol()->defPoint;
  // Sanity: the goto's target is in the forLoop's function.
  INT_ASSERT(gtTarget->parentSymbol == loopRef->parentSymbol);
```

Both the loop over `findfiles()` and opening a file within it are
necessary.  A loop over `("foo", "bar")` doesn't trigger it, nor an
empty loop over `findfiles()`, nor just a call to `open()` with no
loop.

**Associated Future Test(s):**
[`test/functions/iterators/recursive/recursive-iter-findfilesfailure.chpl`](
           https://github.com/chapel-lang/chapel/blob/main/test/test/functions/iterators/recursive/recursive-iter-findfilesfailure.chpl
          ) #18252 

### Configuration Information

```
chpl version 1.25.0 pre-release (31330febf2)

CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: gnu
CHPL_TARGET_ARCH: x86_64
CHPL_TARGET_CPU: native *
CHPL_LOCALE_MODEL: flat
CHPL_COMM: gasnet *
  CHPL_COMM_SUBSTRATE: udp
  CHPL_GASNET_SEGMENT: everything
CHPL_TASKS: qthreads
CHPL_LAUNCHER: amudprun
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: cstdlib
  CHPL_NETWORK_ATOMICS: none
CHPL_GMP: none
CHPL_HWLOC: bundled
CHPL_RE2: bundled
CHPL_LLVM: unset [ built with CHPL_LLVM=none ]
CHPL_AUX_FILESYS: none

gcc (Ubuntu 10.3.0-1ubuntu1) 10.3.0
```

**Comment by bradcray** [comment]
@cassella : Thank you for filing this.  I believe that the issue is due to the use of a recursive iterator `findfiles()` in combination with a throwing function.  E.g., it would not surprise me if we'd never tried invoking a throwing function within a recursive iterator before (recursive iterators aren't used often in practice, and are often on the chopping block because they cause problems like this).  It looks like @vasslitvinov has been in this code most recently, though he's out of the office for a time at present.

A workaround that resolves your reduced case here would be to capture the results of the recursive iterator into a variable and then iterate over that:

```chapel
  proc main() throws {
    var files = findfiles();
    for f in files {
```

I'd be curious whether that would work for your motivating use case as well and would be a satisfactory workaround for the time being (where another workaround would be for us to write a non-recursive version of `findfiles()`).

**Comment by cassella** [comment]
That does work.  (I don't think there's any reason this particular test needs to use `findfiles()` to start with; it could just use a list of files in the current dir.)


I tried reducing the test further down to a handmade recursive iter so that I can write a future that won't be "fixed" by `findfiles()` becoming nonrecursive, but ran into a compiler segfault instead: #18235.

**Comment by cassella** [comment]
In preparing a future, I copied the `findfiles()` and `walkdirs()` iterators into the test (to insulate the future against changes to the FileSystem module that hide the bug), and the problem went away.  If I can't get it back, I'll submit the future just calling into the standard module as above.
