### ISSUE TITLE
Initialization and assignment of Replicated arrays

### ISSUE THREAD

**Issue by twesterhout** [chapel-lang/chapel#18248]
Currently both happen on the first locale:

```chpl
var A: [0..<10] real;
var B: [A.domain dmapped Replicated()] real = A; // now B.replicand(Locales[0]) is inialized to A and everything else to 0
B = A; // B.replicand(Locales[0]) is assigned A and everything else is untouched
```

an alternative would be to make the initialization and assignment behave as if there was an explicit loop over locales, i.e.

```chpl
// B = A is now effectively translated into the following
for L in Locales {
  on L {
    B.replicand(L) = A;
  }
}
```

The second approach seems much more intuitive to me, but I understand that it's a breaking change and the team might be reluctant to even consider it. However, what would be great is if the chosen behavior would be documented in the `Replicated` primer to avoid confusion for beginners (such as me).

Pinging @bradcray because we've just discussed this topic on Gitter.

**Comment by bradcray** [comment]
I'm inclined to keep assignment to replicated arrays as-is, on the argument that if most operations on replicated arrays are designed to only interact with the copy on the current locale, I'm not sure how I'd rationalize that assignment is different.  E.g., if:
* `writeln(myReplicatedArray);` means "print the local copy", and
* `myNormalArray = myReplicatedArray;` means "copy the local copy into the normal array"
then it feels asymmetrical to make
* `myReplicatedArray = myNormalArray;` mean "assign all copies", or worse
* `myReplicatedArray1 = myReplicatedArray2;` mean "read the local copy and assign it to all copies."
So it feels like it opens up a slippery slope where I'm not sure how we'd stop all operations from meaning "do this for all replicands" (which we could do, but that's arguably a different use case than Replicated was designed for).

I'm more open to an argument that initialization of a Replicated array should initialize all replicands, though I can argue either side of this.  The argument against it could be as simple as "initialization looks a lot like assignment in Chapel, so if we don't change assignment, we probably shouldn't change initialization either so that they behave the same."

But I think the argument in favor of it is a bit more compelling: we're going to initialize all replicands in any case (that is, `var R: [MyReplicatedDomain] real;` is going to zero out all replicands); so as long as we're touching all that memory, why not touch it to the value the user wants rather than zeroing out everything but only "user initializing" the current replicand.  For example, compare:

```chapel
var R1: [MyReplDom] real;   // implicitly zeroes all replicands
var R2: [MyReplDom] real = 1.0;  // implicitly zeroes all replicands then assigns 1.0 to the local copy
var R3: [MyReplDom] real;  // implicitly zeroes all replicands
coforall loc in Locales do on loc do R3 = 1.0;  // explicitly assigns (not initializes) all replicands to 1.0
```

This seems both syntactically inefficient and computationally inefficient (duplicate communication and computation required to set up the replicated array's values twice to get the ones that were desired from the start).  Moreover, while in the assignment case, there are reasonable ways a user can get the behavior they want, if the initializer doesn't behave this way, there's no real recourse to get the desired behavior.

Moreover, when initializing a replicated array field within an initializer, it means that a `this.complete()` has to be used to get the values right on all locales rather than relying on the compiler-provided initializer or a simple `this.replArray = initExpr;` style field initializer.

**Comment by twesterhout** [comment]
Closing because I think my original question has been answered, and the behavior is documented here https://chapel-lang.org/docs/main/primers/replicated.html
