### ISSUE TITLE
Should argument names `needle` and `region` be renamed for string, bytes, and regex methods?

### ISSUE THREAD

**Issue by arezaii** [chapel-lang/chapel#18264]
We would like to ensure that the argument names for common string and bytes methods like `find`, `rfind`,`count`, `startWith`, `endsWith`, and `replace` are meaningful and consistent across methods and types. 

Regex also uses the `needle` term, so I am including it here for completeness.

This issue is to collect input on possible renaming options.

Proposals for `needle(s)` replacement are:

- `substring` <-very clear
- `sub` <-matches Python
- `pattern` <-regex uses this to mean the same thing as `needle`

Proposals for `region` replacement are:

- `indices` <- possible confusion with `.indices` on these types
- `searchRange` <-prefer to avoid camelCase for argument names

**Comment by bradcray** [comment]
For `find()` (the only case I've really thought about), I tend to like:
* `substring` for `needle`
* `indices` for `region`
  * though I'm also OK with retaining `region`—I just find it vague (I almost want to call it `substring` as well since it indicates the substring that we're searching in or `range`, but... yeah)
  * but I also don't understand the potential for confusing it with the `.indices` method—both are ways of talking about string indices using ranges, so it's a consistent use of the term...

Do people here ever like using non-noun parts of speech for formals?  For example:  `fullname.find(what="Brad", where=2..)` or `fullname.find(this="Brad", in=2..)`

**Comment by arezaii** [comment]
> but I also don't understand the potential for confusing it with the .indices method—both are ways of talking about string indices using ranges, so it's a consistent use of the term...

I may be mistaken about the reasoning. Reviewing the notes, I believe @lydia-duncan mentioned possible _collision_, not _confusion_.

**Comment by bradcray** [comment]
> Reviewing the notes, I believe @lydia-duncan mentioned possible collision, not confusion.

I feel like I heard some of both, but I'm not sure either is an actual problem.  For example, most initializers use argument names that match field names, but there's no ambiguity in the compiler's interpretation of the code.  Again, not trying to say "there's obviously no problem", just that I don't see what it is if there is.

**Comment by lydia-duncan** [comment]
I like `pattern` as the argument name a lot.

My concerns about `indices` as a name is probably easily assuaged by testing it and seeing that it works just fine.  I mentioned it so it was something we were aware _could_ be an issue and so kept an eye on

**Comment by arezaii** [comment]
Adding a note that we identified the term `needle` is also used in the `regex` module [documentation](https://chapel-lang.org/docs/modules/standard/Regex.html?highlight=needle) when describing the `string` and `bytes` `search` methods.

When we update string/bytes we should update regex as well.

**Comment by slnguyen** [comment]
I'm in favor of `pattern` replacing `needle` as well since the argument name is going to be used in the regex, string, and bytes modules so it should be generic.

I'll test if `indices` replacing `region` results in test failures. If there are no failures I'll change `region` to `indices`. If there are failures I think we should retain `region`.

**Comment by ben-albrecht** [comment]
I like `indices`, and I equally like `substring` and `pattern` -- both are clear IMO.
