### ISSUE TITLE
Should `this` methods be replaced with operators of some form?  What form?

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#18263]
In the early times of Chapel, we needed a way to implement arrays and provide users a way to create other indexable/accessible data structures, but didn't have operator methods as we do today.  This led to the "cute" approach of having `proc this(...)` serve as the accessor method, where we wouldn't have to reserve a special identifier for the purpose since `this` was already reserved and seemed to suggest "call me"/"access me".

Now that we have operator methods, it's been pointed out that they may be a more clear / obvious way of expressing accessors, which seems compelling.  But if we went this route, how should they be expressed?  E.g.,

```chapel
// primary method form
record R {
  operator [](args) { ... }  // this and the next few choices require understanding that `[]` also defines `()`-based accesses
  operator [(args) { ... }  // single-bracket operator reflecting where args fall
  operator [(args)] { ... }  // put args syntactically where they actually go?
  operator [args] { ... }  // drop parens for argument list altogether?
  operator (args) { ... }  // drop name of operator altogether—there is no operator in the source, it's just the actual arguments list applied to the `this` expression
  operator this(args) { ... }
  operator call(args) { ... }
  operator index(args) { ... }
  operator access (args) { ... }
  // ...something else?
}

// secondary method form
operator R.[](args) { ... }
operator R.[(args) { ... }
operator R.[(args)] { ... }
operator R.[args] { ... }
operator R.this(args) { ... }
operator R.call(args) { ... }
operator R.index(args) { ... }
operator R.access(args) { ... }
// ...something else?
```

Other considerations:
* does the fact that parens and square brackets are interchangeable temper our response here?  Or cause us to want to stick with the status quo?
* what's the implication for the `these` iterator if we switch?  If we don't? (maybe it should've also been renamed `iter this` when we split `proc` and `iter` out as distinct declaration styles?)  See #19041 for more.

**Comment by ronawho** [comment]
Note that C++ calls `[]` the subscript operator -- https://en.cppreference.com/w/cpp/language/operator_member_access

**Comment by lydia-duncan** [comment]
We could also choose to abandon symbols and make it an operator that uses a phrase instead like `operator index` or `operator access`, which might be justified by supporting both `[]` and `()`

**Comment by bradcray** [comment]
> make it an operator that uses a phrase instead like operator index or operator access

Or `operator this`.  Are any of those beneficial enough to be worth making the change, though?  I.e., is it worth asking users to change their code from one specially named thing to another?

**Comment by bmcdonald3** [comment]
As someone who doesn't have much experience with Chapel, I prefer this syntax in the record: `operator [](args) { ... }`. As I was searching for this in the hash table, my first thought was "oh, this is probably an operator, so I'll search for all the operators", then when I couldn't find it I thought "oh, I should search for `[` or `[]`". When there were zero occurrences of either of these in the whole file, that seemed weird to me.

After Elliot sent me the docs for `proc this`, I was able to understand, but I would have to say that wasn't intuitive to me at all and that is all. So, something that could be found as an operator (since, to me, that's what it seems like this is) or at least through some sort of search of `[` or `[]` would be helpful.

**Comment by bradcray** [comment]
> I prefer this syntax in the record: operator [](args) { ... }

That's my preference from the candidates above as well, along with: `operator [(args)] { ... }` which has the slight cuteness/benefit of (a) putting the args where they would actually go and (b) looking as though it could be defining both `[]` and `()` as accessors (which any of these proposals does, since the two are interchangeable for function calls and accessors in Chapel).

One reason not to make this an operator is that most (all?) of our operators are either prefix or infix, taking all of the expressions it's applied to as arguments; but accessors like this are postfix and take the `this` argument in the `this` slot rather than in a formal argument slot.  This makes it more like a method call and less like our other operator calls, which we've viewed as being more like standalone functions that are associated with types through the method syntax.  That could be a reason to stick with the status quo (along with the "trying not to create needless work for ourselves" principle).

**Comment by mppf** [comment]
If we rename `this` would we also rename `these`? This morning I was thinking about this topic & these names for a totally different reasons and my mind went to `access` and `iterate` as the method names.

**Comment by dlongnecke-cray** [comment]
Reposting what I said in the megathread (#19038)...

---

The more I think about it, the more `this` makes sense as an operator.
In that `callable(foo, bar)` yields an expression (usually), and so it
fits right in with how other operator procedures are called by the
expression grammar.

So to me changing `this` -> `operator this` makes sense due to where
`callable(foo, bar)` can appear in the language.

I think we should call it `operator this`. Brad's explanation of the
origin of `this` (we call it `this` because you're calling "yourself",
and `this` is the receiver keyword) resonated with me.

I don't think we can call it `operator[]`, due to the fact that it is
possible to call something with either `[...]` or `(...)`.

Maybe we do want to offer both `operator()` and `operator[]` if we
decide that it should be possible for the two forms of syntax to
do different things. But from reading the language spec, it seems
like `[]` is just syntactic sugar for `()`.

I'm slightly more open to `operator call`, but that would reserve a
new keyword.

I don't think that `this` makes sense as an interface because there
cannot be any restrictions on either its arity or the type of its
arguments. If we tried to constrain it as an interface it would be
so weakly constrained as to pretty much be generic anyway.

---

In my ideal world we would make `these` into a series of interfaces,
one for serial/parallel/standalone parallel iteration.

I would be OK with an operator, but I think it would not be as cool
or "useful" to the compiler as using an interface.

**Comment by bradcray** [comment]
> Maybe we do want to offer both operator() and operator[] if we
decide that it should be possible for the two forms of syntax to
do different things.

I don't think we should go down that path.  These are very intentionally intended to be synonyms in order to blur the line between code and storage so that routines can be swapped where arrays are expected and vice-versa—particularly given that some of our array types (like sparse, associative, distributed) are not simply an address calculation but run an arbitrary amount of code.

> But from reading the language spec, it seems like [] is just syntactic sugar for ().

I don't know if I'd call it a "sugar" since it doesn't save any space or typing.  I'd just call them equivalents or synonyms or indistinguishable semantically.

**Comment by bradcray** [comment]
I updated the OP to include new ideas that have come up in this comments thread and from #19037, which I'm closing as I hadn't found this issue when searching for that one.

**Comment by bradcray** [comment]
I have to admit that my favorite approach as an operator so far is:

```chapel
operator (args)  // since there is no operator, it's just an argument list
```

but that I'm not wild about it because I don't look forward to writing:

```chapel
operator (ref this: R, i: int) { ... }  // `this` must be passed in explicitly for operators (or we need to make a new special case)
```

(for any operator form, for that matter) rather than the traditional:

```chapel
proc this(i: int) { ... } 
```

For that reason, my other two favorite forms are both `proc`-based:

```chapel
proc this(...)  // don't change; though subtle, what we have is not so bad and it has the benefit of leaning on a reserved word
proc (...)  // just drop the procedure name altogether since there isn't a procedure name or operator in the callsite—just the argument list
```

The final proposal is arguably even more subtle than the previous ("what would we search on in the documentation?") but it also arguably does a better job of meeting BenMcD's desire for the definition point to look like the callsite (method `proc foo()` is called as `myR.foo()`  while method `proc (...)` is just called as `myR(...)`).

**Comment by dlongnecke-cray** [comment]
I didn't think about the notion that if we want `this` to be an operator, it's probably going to be a freestanding procedure, and thus we'd have to pass in the receiver.

In which case something like:

```chapel
operator this(ref receiver, args...) {}
```

Also seems fairly appealing to me.

I worry that `operator (ref this)` would be confusing because it would be a special case where `this` can appear in an argument list (outside of a method?). And it would be the only `operator` where you omit the name of the operator.

I worry about the `proc (` for the same reason, we would be special-casing callables when arguably they behave like any other operator (the difference being that their arity is variable rather than being fixed, and they may not return an expression). But maybe those differences warrant the special treatment.

**Comment by bradcray** [comment]
> it's probably going to be a freestanding procedure, and thus we'd have to pass in the receiver.

It's less that it'd necessarily be a freestanding procedure (we support operator methods) and more that operators (to date anyway) don't support `this` value arguments.  We could say "this is a special operator that is different in this respect, but then we're removing one special-case to introduce another one.

To me, if we were to go with:

```chapel
operator this(ref receiver, args...) {}
```

then we've created a bunch of work for nothing—the name is still as special as it currently is (it's identical!), and we've lost the benefit of the implicit `this` argument while introducing potential new errors to for users to make and us to check for ("what if your `receiver` argument is of a different type than the one on which the operator is being defined?").

**Comment by dlongnecke-cray** [comment]
Ok, if it's an operator method, then couldn't we just do:

```chapel
operator this(args...) {
  writeln(this);  // Access receiver as per normal?
}
```

You would only have to pass the receiver if it is not an operator
method. I think that there's a nice form of symmetry there.

To me, the appeal of making `this` into an operator is that it aligns
it nicely with all the other expressions in the language that are
not directly callable.

Right now it kind of seems like the odd one out in that it's actually
just a normal procedure.

So you're right that in both cases we don't need to worry because
`this` is already a reserved word. I think making `this` into
an operator actually makes it more intuitive where to look (though
perhaps I have no right to speak about intuitiveness).

**Comment by bradcray** [comment]
> couldn't we just do:

That's not how operator methods work today.  For example, the `-` operator methods on a record R would be defined as follows:

```chapel
operator R.-(op: R) { // unary minus
  return new R(x=R.x);
}

operator R.-(lhs: R, rhs: R) {  // binary minus
  return new R(lhs.x - rhs.x);  // or whatever
}

operator R.-=(ref lhs: R, rhs: R) {  // op= minus
  lhs.x -= rhs.x;  // or whatever
}
```

i.e., there is no `this` argument (or if there is, it's the type on which the operator is being defined, not one of the values).

That's why I'm saying that using an operator for this case either adds burden (the need to pass extra arguments relative to today), or we'd have to change the way operators behave for this case, which turns one special case (it's just like other procedures only you call it like `myR(x,y,z)` rather than `myR.this(x,y,z)`) into another one (it's just like other operators except that it takes an implicit `this` value and its name has no little-to-no syntactic relation to how it's invoked).

**Comment by dlongnecke-cray** [comment]
Thanks for clarifying Brad. I had a suspicion that operator methods
didn't have access to the receiver.

I still end up preferring explicitly passing the receiver over
leaving it a `proc`, because it aligns calls with the other
expressions that you can't call directly.

In my mind, having to pass the receiver (and not having access to
`this`) in `operator this` is no stranger than not having access to
the receiver in the operator method for `operator+` (which I still
find weird, but I understand that it's a solution to a different
problem in visibility).

There is a slight disappointment in that we'd have to name things:

```chapel
operator this(ref receiver, args...)
```

Since we couldn't use `this` without adding a special case (which I
am not in favor of).

But that doesn't really bother me. I don't think on the whole things
end up looking pretty consistent.

Hopefully I'm understanding everything here.

**Comment by bradcray** [comment]
> I still end up preferring explicitly passing the receiver over
leaving it a proc, because it aligns calls with the other
expressions that you can't call directly.

Just to make sure I'm understanding this, I think you're saying
that you prefer it because using the operator doesn't let you
say `myR.this(...)` where using `proc this()` does (at least,
currently?  With a bit of work, we could prevent it, obviously...).

**Comment by dlongnecke-cray** [comment]
Exactly, in the same way that we can't call `operator+` directly (at
least, not today). Users have to define `operator+` to let their
types participate in `+` expressions.

In the same way, I don't envision a user ever calling `this` directly,
(at least, I've never seen it outside of implementation code).
Instead, it's almost always called indirectly by the compiler as a
means of implementing the "call" expression for a type.

I'm kind of viewing things from the opposite angle. Yes, making `this`
an operator prevents it from being called directly, but any other
operator implementing a binary/unary expression _can't_ be called
directly. So `operator` is how user types participate in using those
expressions.

From that perspective, it seems natural to me to say `operator this`
is how user types participate in being called.

**Comment by mppf** [comment]
The fact that operators don't automatically have a receiver argument for the instance (vs the type) is interesting. Perhaps it makes sense to have some operators (e.g. `operator []`) have a instance receiver rather than a type one. Otherwise, it feels to me like a really strange reason to make it a `proc` rather than an `operator`.

**Comment by bradcray** [comment]
Most people here are more on the "operator" side of the fence, but one other reason that I continue to lead to the `proc` side is that I see `this` and `these` as being siblings to one another, and it would seem odd to me if `this` became an operator and `these` remained a method.  But I also don't think `these` should become an operator because my intuition is that operators shouldn't encompass both procedures and iterators (as `def` used to do before we decided it was better to split it into `proc` and `iter`).

I could also argue back against this, though:  If we decided that it really ought to be an operator, it doesn't _quite_ have the same problem as `def` did because for a given name (say `access` or `iterate`) the language would define whether it was an iterator or procedure operator.  Still, it gives me discomfort to not have the declaration prefix make this distinction.

The other reason I wouldn't enjoy having it as an operator is the same as my previous concern about `this` becoming one.  I don't like the idea of interacting with `this` through an explicit argument rather than via the implicit `this` / like a normal method.  While Michael points out just above that we could just say "some operators are different in this respect", that makes me similarly uncomfortable in the "different operators have different rules" / asymmetrical sense.

**Comment by dlongnecke-cray** [comment]
> I don't like the idea of interacting with this through an explicit argument rather than via the implicit this / like a normal method

Why don't we find this peculiar in the case of `operator +`? Attacking this problem from reverse, when I started working with operators I found it strange that they were standalone functions instead of something like:

```chapel
// I wanted to write '+' this way:
record myInt {
  operator +(rhs: myInt) {
    return new myInt(this.value + rhs.value);
  }
}

// But this is the preferred (only? not sure, been awhile) way:
operator +(lhs: myInt, rhs: myInt) {
  return new myInt(lhs.value + rhs.value);
}
```

If we can only write things the second way, then I am wondering what it is about calls that makes you feel hesitant to introduce an `operator this` (other than not being able to leverage `this` as a formal name without special syntax edge cases)?

If the answer is we can do both, but prefer the second option, then maybe things don't really have to change if we just recommend people to write `operator this` the first way.

> While Michael points out just above that we could just say "some operators are different in this respect", that makes me similarly uncomfortable in the "different operators have different rules" / asymmetrical sense

I definitely think that we should strive to have all operators have a uniform interface for consistency's sake. One edge case stands out like a sore thumb.

> is that I see this and these as being siblings to one another, and it would seem odd to me if this became an operator and these remained a method

I guess I don't really see `these` in quite the same way as `this`. To me iteration seems like a much more complicated feature than `this`, and so it wouldn't bother me if we decide to have iteration remain a `proc`. I think ideally we would express it as an interface, but we're not really capable of that yet.

> But I also don't think these should become an operator because my intuition is that operators shouldn't encompass both procedures and iterators

I'm not even sure how that would work. Would we just expect to see `yield` in `operator these` when parsing it? In my head I was imagining we'd write `operator iter these` or something, but perhaps that's superfluous. I agree that not seeing the `iter` tag would feel unsettling.

**Comment by bradcray** [comment]
> Why don't we find this peculiar in the case of operator +? 

For me, it's because:
1) I like thinking of binary operators as being as symmetrical as possible between their operands rather than creating the asymmetry of having a 'this' argument and then a "the other operand" argument.  In part because it just feels more symmetrical and balanced; in part because it feels clearer how multiple overloads will be selected between in the event of the types of the actuals, including coercions, promotions, etc.  Basically, it acts like a normal function call and I don't have to think "Now how does the fact that one of these operands is `this` play into this?  Do we permit coercions on `this`?  promotions?  And if not, how would I handle that case?"
2) We support defining binary operators on types where the type need not be the left-hand operator (or even either of them, for that matter, though that'd be a bit odd...).  For example:
  ```chapel
  record R {
    operator +(r: R, i: int) { /* R + int */ }
    operator +(i: int, r: R) { /* int + R */ }
  }
  ```
  If `this` had to be `R`, how would we define an int + R overload that was available whenever `R` was?  I suppose would take an `radd`/`r+` approach like I think Python did, but we considered and threw that option out because it felt sloppy/ugly/special-casey compared to what we built instead.

>  I am wondering what it is about calls that makes you feel hesitant to introduce an operator this (other than not being able to leverage this as a formal name without special syntax edge cases)?

It's not the inability to name things `this` that I'm concerned about, it's more that it feels like I'm outside of the object poking into its innards through an argument like any other standalone routine rather than sitting right there inside the type poking around with them as a method.  Granted, our existing operators are the same way, but given my previous comments, I'm not sure how to get around that (they're going to be outside one of their operands in the binary case at any rate).  But I think the main thing is that if you were to ask me "What are the arguments of a call `myR.foo(x, y, z)`, I'd say `x, y, and z` would would ideally want to write a `.this()` method that took those three arguments.  But now I have to write it to take four, making the operator signature not resemble the callsite particularly well.

Granted, much of this reflects my stylistic preferences, but you asked.

> we can do both, but prefer the second option

A challenge to this is how to distinguish between unary and binary operators.  E.g., is:

```chapel
operator R.-(x: R) { ... }
```

a unary `-` defined on the argument `x`, or a binary operator defined between `this` and `-`?  We could obviously come up with different ways of naming the operators to permit both styles with both operators, but that all feels very special-casey and two-ways-to-do-the-same-thing to me. 

> I definitely think that we should strive to have all operators have a uniform interface for consistency's sake.

I'm not understanding:  In this statement, what makes it seem obvious to you that the "call me" capability inherently has operator nature while "deinit" or "hash" or "foo" is inherently a method?  (Note that it can't be the presence of `[]` or `()` because every method `.foo()` also gets to use `[]` or `()` without being an operator.  That's what makes me say that this resembles a method with no name more than an operator to me (though, granted, a truly nameless method would still require a `.` and this doesn't:  `myR.(i, j, k)` rather than `myR(i, j, k)`)).

> To me iteration seems like a much more complicated feature than this

That seems like a pretty arbitrary sense that can often be wrong in practice.  Here's an iterator over a simple range type

```chapel
record simpleRange {  // represents 1..n
  var n: int;
  iter these() {
    for i in 1..n do
      yield i;
  }
}
```

whereas the `this()` method for a distributed sparse array—or even a local one—is significantly more complex.  I think there are both complicated and less complicated instances of both iterators and accessors.

Or wait, do you mean "iterators are complicated to understand / to implement" and "procedures are not"?  I'm not fully sure I buy that either, but we've definitely all been raised taught how to write procedures from day 2 of programming 101, and not iterators, so I can understand that they're more familiar (e.g., I never have to teach someone learning Chapel what a procedure is).  That said, I'm still not sure that "complicated" is a good rationale for something remaining a method or "non-complicated" for it being an operator.

> I'm not even sure how that would work.

I think we would have to say something like "all operators are procedures and are expected to return things" (is that true?  Do we have any non-returning operators?  I'm not sure offhand, but would guess not?) "...except for the `these`/`iterate` operator which is like an iterator and so can (and typically should) contain 1 or more yields.  Then we'd teach the compiler to permit them in the one case, but not the others.

Again, I'm not advocating for this (in fact, I'm advocating against it).

**Comment by dlongnecke-cray** [comment]
I guess it looks like we can't have operators in "method form" as I thought they could, e.g.

```chapel
record r {
  var val = 0;
  operator +(rhs: r) {
    return new r(this.val + rhs.val);
  }
}

proc test() {
  var obj1 = new r(1);
  var obj2 = new r(2);
  // Compiler doesn't like this
  writeln(obj1 + obj2);
}
test();
```

So knowing that, I guess they can only be written as standalone procedures or as "type methods" ("operator methods"? Whatever we call `R.+`, that we're calling a method, but really is a standalone procedure with method visibility).

> A challenge to this is how to distinguish between unary and binary operators. E.g., is:

If we could write a unary minus in "method form", it seems like it would just be

```chapel
record R {
  operator -() { return new R(this.val - 1); }
}
```

But as I learned I guess we can't do that today anyway.

> I'm not understanding: In this statement, what makes it seem obvious to you that the "call me" capability inherently has operator nature while "deinit" or "hash" or "foo" is inherently a method?

To me the answer derives from the source of the call. The `hash()` call appears somewhere in code (even if for an internal type) and can be called by users, so it makes sense to me that it is a normal `proc`. The `deinit` is a particularly special case, but if you wanted to make the argument that by my logic we should have `operator deinit()` I might not disagree with you. We'd probably say that feels weird due to how special `deinit` is though.

> That seems like a pretty arbitrary sense that can often be wrong in practice. 

You're right that the level of abstraction underneath the covers is arbitrary.

I think "callable" / "this" / "call me" makes sense as an operator because in my head I visualize it next to other expressions. Just like `a + b`, I can have `foo(x, y, z)`, and the compiler does some transformation to call the thing that implements the expression `foo(x, y, z)`. I see operators as our way of saying "these things implement expressions", or that "some transformation from syntax to call is happening here". And `foo(x, y, z)` is just a N-ary expression (whereas most operators are unary or binary).

> But now I have to write it to take four, making the operator signature not resemble the callsite particularly well.

I think there is a learning curve to having to remember that in a method, the receiver acts as a hidden formal. Given that we can't have the sort of "method form" I was hoping for for operators anyway:

```chapel
record r {
  var val = 0;
  operator +(rhs: r) {
    return new r(this.val + rhs.val);
  }
}
```

And have to write it in the standalone format:

```chapel
operator +(lhs: r, rhs: r) { return new r(lhs.val + rhs.val); }
```

It seems like the mental burden here is just reminding/recalling that for the `this` operator, the `this` receiver is actually just a formal too?

Perhaps most don't do that for things like `+` because they've never really thought of writing them in the "method form" above. I had an expectation of wanting to write `+` in method form, though, and was surprised that it didn't work. I'm not sure what made me want to write it that way, but I had to do a similar sort of "mental unpacking" in my head to teach myself that `operator+` has to take a left-hand-side and right-hand-side.

> Or wait, do you mean "iterators are complicated to understand / to implement" and "procedures are not"?

Not necessarily to understand or implement, though I would wager in most cases that is true as well.

I'm just talking about the translation by the compiler from syntax to "thing the user writes that implements the syntax". In the case of `this` it's a call (regardless of what complicated thing it might be doing under the covers), whereas for `these` it's an `iter`, which is a more advanced concept (though as you say, not necessarily much harder to learn given the high level of abstraction).

> I think we would have to say something like "all operators are procedures and are expected to return things" (is that true? Do we have any non-returning operators? 

This could leave room for introducing more iterator operators in the future (not sure what those would be, though).

Maybe we'd just say that "an operator routine may be either a procedure or iterator (depends on the individual operator)". 

Sounds like you're definitely opposed to that idea, but I actually find myself warming up to it 😬.

**Comment by bradcray** [comment]
> > In this statement, what makes it seem obvious to you that the "call me" capability inherently has operator nature while "deinit" or "hash" or "foo" is inherently a method?

> To me the answer derives from the source of the call. The hash() call appears somewhere in code (even if for an internal type) and can be called by users, so it makes sense to me that it is a normal proc. The deinit is a particularly special case, but if you wanted to make the argument that by my logic we should have operator deinit() I might not disagree with you. We'd probably say that feels weird due to how special deinit is though. And I could make the argument that for operator +, there is a + in the code, and for foo(x, y, z), there is a call in the code, but you never really see a deinit call in the code, so it's even weirder.

So, if I'm understanding, things that are implicit or not-visible in the code are things you'd consider to be more operator-like?  To me, what makes an operator an operator today is (a) that its name tends to be symbolic rather than an identifier (e.g., `+`, `+=`, `<<`) and (b) that it supports infix, prefix, or postfix application to expressions rather than accepting its arguments as parenthesized arguments.  Specifically, leaving `this` and `these` aside, none of the things that are currently automatically called by other syntactical constructs — initialization, deinitialization, context management — are currently operators, and nothing about them seems to match the two characteristics that I tend to associate with Chapel's operators.

Maybe that suggests there should be some additional category of thing beyond proc/iter methods and operator methods, but I'm not sure I'd argue that.  Running with it, though, say we had `implicit proc` or `autoproc` declarations, and that we used this declaration style to declare `init`, `deinit`, `init=`, `postinit`, `enterThis`, and `leaveThis`.  On the plus side, it would call these things out as being a little special or different.  But what would it imply for someone who tried to declare a non-implicit `proc` named `init` or `postinit`?  That they could do so and that the routine would have no special purpose, but could be called like any other method?  (i.e., we haven't prevented them from using that name?).  I suppose that all has merit, yet rather than adding a new sibling to `proc`, `iter`, `operator` to do this, I think I very much prefer the proposals to either use a special naming convention for such routines that's only used by such non-user-callable routines instead—engin's #19050 effectively—and/or to reserve them as keywords.  I definitely prefer these two proposals over making this category of things into operators.  And `this` and `these` as defined today feel more like this group of methods than they do operators (in that they're implicitly called by the language, don't have symbolic forms, and don't show up in infix, prefix, or postfix forms syntactically.

**Comment by mppf** [comment]
>  I definitely prefer these two proposals over making this category of things into operators. 

I think that making them in to operators doesn't help with the desire to allow new special methods without breaking code that happened to use that method name, unless we allow an `operator` / `autoproc` / whatever and also a regular `proc` to exist with the same name at the same time. But having a `proc` and an `operator` / `autoproc` / whatever with the same name seems to me not to be particularly defensible.

The interfaces proposal has a similar issue but there I am more willing to believe having the same name for these two different things is OK. ( https://github.com/chapel-lang/chapel/issues/19074#issuecomment-1020180352 ).

#19050 does solve this forward-compatibility issue. Reserving some as keywords doesn't, really, as an approach for all special methods (but, that said, I like it for several of our current ones).

**Comment by lydia-duncan** [comment]
> I think we would have to say something like "all operators are procedures and are expected to return things" (is that true? Do we have any non-returning operators?

If my memory serves, the assignment operators don't return (e.g. `+=`, `-=` modify the value of the first argument rather than returning the result).

**Comment by bradcray** [comment]
> the assignment operators don't return

Of course, duh...  Thanks Lydia!  I've updated my previous comment to scratch out that whole sidebar (which was pretty irrelevant anyway).

**Comment by riftEmber** [comment]
In the [`this`/`these` design discussion](https://github.com/Cray/chapel-private/issues/5077) we decided to stick with `proc this()` as-is, not changing its name or making it an operator.
