### ISSUE TITLE
User-defined hash functions for Map

### ISSUE THREAD

**Issue by bmcdonald3** [chapel-lang/chapel#18291]
## Summary
Currently, the Chapel Map uses the default hash function in all scenarios, so even if the user wanted to use their own hash function, they are not able to. Many languages have hash table implementations that allow users to provide their own hash functions, and I also have observed performance improvements in certain instances with this change. I am proposing that we add this functionality to the `map` API.

### Proposal 1: Detect if there is a `hash` method provided on the key type
```chapel
  proc int.hash() {
    return calculateHash();
  }
  var myMap:map(int,string);
  // will use the above hash since it is defined on int, even though not explicitly stated by user
  myMap[1] = "hello";
```
### Proposal 2: Allow `map` to accept a hash record or first class function
```chapel
proc doHash(arg, seed:uint): uint {
  return calculateHash();
}
var myMap2: map(int, string, doHash);
myMap2[1] = "hello 2";
```

### Pros/cons of proposed solutions
1. Detect if there is a `hash` method provided on the key type:
  a. Pros: Simple to use, not much extra work by user
  b. Cons: Since `hash` method now has special meaning, it might no longer be used in applications for other purposes, not very intuitive; no one would know how to use it unless they had seen the documentation
2. Allow `map` to accept a hash record or first class function:
  a. Pros: Other implementations do this, such as the C++ one that our program is based on so there is precedence
  b. Cons: Changes the Map type to include the "hasher" type when specified, also, a little bit more work to program for a user in my opinion

## More info for the highly interested
I ran into this while running performance tests on the [k-nucleotide benchmark](https://benchmarksgame-team.pages.debian.net/benchmarksgame/program/knucleotide-chapel-3.html), where the C++ implementation that our implementation is based on allows a user to pass a hash function. The k-nucleotide implementation does the hashing with a required hash function before using the map, so we are double hashing in that case. If you want more info on the result of using the built in/user defined hash, see: https://github.com/Cray/chapel-private/issues/2365

C++ implementation usage:
```C++
struct T {
  ... other stuff ...
   struct hash{
     uint64_t operator()(const T& t)const{ return t.data; }
   };
};

cc_hash_table<T,unsigned,T::hash> myMap;
```

For additional discussion and implementation suggestions, see also #18234 and #11341

**Comment by mppf** [comment]
I think we should do (2) now and leave open the possibility for doing something like (1) in the future. But when we do something like (1) I think we should have a single method (e.g. `hash`) that is either compiler-generated or provided by the author of a type.

One question we have to answer before we can actually implement either is whether or not we want to use a "keyed hash". See the dicsussion in https://github.com/chapel-lang/chapel/issues/11341#issuecomment-435911553 which has some context for the `seed` argument. I think it is low cost enough to have an additional `seed` argument and it significantly improves flexibility for things like Cuckoo hashing. (A downside is that since we aren't currently using Cuckoo hashing we might end up with hash functions that don't appropriately use the `seed` argument in the near term - but I think that is less problematic than breaking the API in the future - it would just mean that certain hash functions might not perform well with certain hashtables).

**Comment by e-kayrakli** [comment]
> I think we should do (2) now and leave open the possibility for doing something like (1) in the future. But when we do something like (1) I think we should have a single method (e.g. hash) that is either compiler-generated or provided by the author of a type.

I really like (1), so I'd prefer we get there sooner rather than later. But I have no problem with (2) for a short term solution. Probably obvious, but note that if/when we switch to (1) from (2), it'll be breaking for the Map type. So, ideally, if we do it, we should do it before 2.0.

**Comment by bradcray** [comment]
I similarly find (1) really pleasantly ergonomic and packaged; and I like that it can take advantage of "private" data within the type, if applied to a record, say.  I find the first-class function approach in (2) second-best, but my sense is that FCFs today probably can't support it (I'm guessing that based on the fact that our sorts don't take FCFs, but take comparator records instead).  I tend not to like "send in a record" solutions because they feel heavyweight (I still couldn't call one of our sorts with a non-default comparator without going and reading the documentation, which seems like a bad sign).

Another thing intriguing about (1) to me is that if we use the Reflection-based approach that the current sketch of an implementation does, then we could look first for a hash function that accepts a seed, and fall back to one that doesn't take one if it doesn't exist such that a user could write a keyed hash or not depending on their level of motivation and/or our degree of supporting it.

**Comment by mppf** [comment]
> if/when we switch to (1) from (2), it'll be breaking for the Map type. So, ideally, if we do it, we should do it before 2.0.

I think we should support both (1) and (2), eventually. (1) is the equivalent of being able to provide a comparator for a particular sort call but (2) is the equivalent of being able to override `<` so that you can sort in a particular order. Certainly both are useful in sorting. I think both are useful as well in choosing hash functions.

I certainly don't think we should do (2) now and then deprecate it and replace it with (1).

>  find the first-class function approach in (2) second-best, but my sense is that FCFs today probably can't support it (I'm guessing that based on the fact that our sorts don't take FCFs, but take comparator records instead).

For sorting, it was because we wanted to have different types of comparators (`key`, `keyPart`, or `compare`) and having a record seemed an easier way to do that. Arguably the corresponding situation exists if we want keyed hashes and non-keyed hashes.

I think the main difference with FCFs is that AFAIK we can't write an FCF method. But other than that I'm pretty sure our FCFs would be up to the task of writing hash functions, generally speaking.

> I like that it can take advantage of "private" data within the type, if applied to a record, say.

I don't think there is a problem with FCFs / function-y records with private fields/methods. In particular I think that private fields/methods should be visible inside the module in which they are defined. See https://github.com/chapel-lang/chapel/issues/6067#issuecomment-434063660 if you want to discuss that more.

So it would be possible to define a hash record / FCF for a type when writing that type that can access the private fields.

Certainly, you could argue that all record authors should be providing a hash function to make a good type, but isn't that already the case because the compiler provides a default implementation?

> Another thing intriguing about (1) to me is that if we use the Reflection-based approach that the current sketch of an implementation does, then we could look first for a hash function that accepts a seed, and fall back to one that doesn't take one if it doesn't exist such that a user could write a keyed hash or not depending on their level of motivation and/or our degree of supporting it.

That is also true with (2).

Lastly, in terms of Cons of Proposal 1:

`proc int.hash()` -- if defining this changes the behavior of all maps/sets using `int` from this module that seems like it might be surprising, given that there might be some other module being used that expects `int.hash` to do a particular thing - in the same way that we expect `+` on ints to behave in a particular way.

**Comment by mppf** [comment]
My main discomforts with Proposal 1 are these:
 * First, we are effectively reserving the method named `hash` / giving it special meaning in the same way that `proc this` has special meaning. As a result, I am nervous about the name `hash` and the name becomes more of a "language design" choice, IMO.
 * Second, the draft implementation in https://github.com/chapel-lang/chapel/issues/18234#issuecomment-899893763 seems to be making 2 ways of providing the hash function for a type -- we have current function `chpl__defaultHash(x)` that can be provided but the prototype patch also allows `x.hash()`. It seems to me that we should be renaming `chpl__defaultHash(x)` to `x.hash()`. That is; after we do (1) that `chpl__defaultHash` is no longer available or generated by the compiler. I think that we should be handling deprecation (if we need it at all) by arranging for the compiler to give an error when it sees any function definition with the name `chpl__defaultHash`. @bradcray do you know of a particular reason not to use this renaming approach? Is the strategy of leaving both available an expedience?

**Comment by mppf** [comment]
@bmcdonald3 - could you add "See also #18234 and #11341" to the issue description? Thanks.

**Comment by bradcray** [comment]
> I think we should support both (1) and (2), eventually.

I'm fine with that as well.  But then I'm also curious why you'd start with (2) and leave (1) until later.  Maybe it's due to the discomforts you noted?  (but then what's going to make you more comfortable with them later rather than now?)

> (1) is the equivalent of being able to provide a comparator for a particular sort call but (2) is the equivalent of being able to override < so to change the default sort order for a particular type.

Huh...  I think of (1) as being the ability to define the hash function for a particular type more than (2), since I'd expect most full-fledged types that cared to define a hash to do so as a primary or secondary method.  It also seems to provide the potential to do it for a particular call using tertiary methods, though that doesn't seem like the common case (even though it was a recently motivated one).  Meanwhile, passing in a record or FCF seems more like a way to specialize a given map instance independently of the eltType rather than linking it to a particular type.  Did you get your numbering backwards?  If not, could you say why you seem to see it backwards from me?  Is it because the motivating example was trying to define it on `int` rather than a user type and used a tertiary method?

> I think the main difference with FCFs is that AFAIK we can't write an FCF method.

Is there anything that would require/desire the hashes passed via an argument to be written as methods rather than standalone functions?

> Certainly, you could argue that all record authors should be providing a hash function to make a good type, but isn't that already the case because the compiler provides a default implementation?

I think of it as being very similar to `writeThis()`:  The compiler provides a default implementation, and that may be good enough in many cases, but if you really want your type to print out a specific way / hash on certain aspects of its value and not others, you'd override it.  (That might suggest calling it `hashThis()` though frankly, I'm not wild about the name `writeThis()` so would think about changing that first, given the choice).

> if defining this changes the behavior of all maps/sets using int from this module that seems like it might be surprising, given that there might be some other module being used that expects int.hash to do a particular thing - in the same way that we expect + on ints to behave in a particular way.

This feels a little different to me in that changing hashes doesn't really change observable behavior, just performance, doesn't it?  E.g., even if I had my hash function return 0 for all values of my type, `==` would still be applied to distinguish between values, so all I'd really be doing is changing the conflict behavior of the hash function rather than anything semantic about the map or set?

> First, we are effectively reserving the method named hash / giving it special meaning in the same way that proc this has special meaning. As a result, I am nervous about the name hash and the name becomes more of a "language design" choice, IMO.

I don't disagree with this, but (a) it seems like an intuitive meaning for anyone who's taken their basic computer science classes, (b) it doesn't seem like a name that would be used for many things other than creating hash functions.  So my sense is that the main problem would be when someone wanted to create their own hash() method for use in their own hash-based contexts, but did not want to use it with our Map, Set, associative types for some reason (which doesn't seem like a significant problem to me).  I have a mild negative philosophical reaction to growing the set of special method names, but not a very significant one, particularly given that the compiler is already creating such methods for types, just with an internal name rather than a user-facing one (i.e., we're not growing the set of "standard" methods on a type, we're just formalizing it).

My bigger concern with approach (1), which relates to my inability to keep the POI-style rules of Chapel clear in my head without writing examples to test things, is whether we'd end up in a situation where a `Map` was created using a tertiary `hash` method, but was then used in other contexts where the default/primary/secondary `hash` method was used instead, such that we got inconsistent behavior depending on the calling context.  OTOH, if we did have problems like this, maybe it suggests that our POI-style rules aren't correct (or working correctly) yet for tertiary methods rather than that we shouldn't take the approach?  I.e., if I create a data structure in a context where it's sensitive to the visible tertiary methods, it seems we'd want that data structure to work wherever it ends up being used.  I don't feel confident that this would work in general since the `hash` method would be attached to the map's `keyType` rather than the `Map` itself (so it seems it wouldn't get sucked into new contexts automatically).  Sketching out an example:

```chapel
module SymbolTable {
  var table: map(string, int);
  proc string.hash() {
    return 0;  // Don't ask me why I'm writing such a terrible hash function
  }
  table.add("a", 0);
  table.add("b", 1);
  table.add("c", 2);
}

module M {
  import SymbolTable.table;
  table.add("d", 3);  // is this going to use SymbolTable.string.hash, or the typical / default string.hash?
}
```

Is the add("d", 3) going to use SymbolTable.string.hash (rationale: it's what was visible where the `map` instantiation was created) or the default one (rationale: it can't see the tertiary method based on the current imports)?

> it seems to me that we should be renaming chpl__defaultHash(x) to x.hash(). That is; after we do (1) that chpl__defaultHash is no longer available or generated by the compiler. I think that we should be handling deprecation (if we need it at all) by arranging for the compiler to give an error when it sees any function definition with the name chpl__defaultHash. @bradcray do you know of a particular reason not to use this renaming approach? Is the strategy of leaving both available an expedience?

I took the approach I did because I'm not really familiar enough with the current HashTable implementation to know what choices were made and why, and it seemed like an obvious safe place to inject the logic in the five minutes I spent on it.  I don't have any particular personal motivation for keeping `chpl__defaultHash()` nor any problem with retiring it.  I interpret `chpl__defaultHash()` as an internal / non-user-facing symbol, so wouldn't expect to need to deprecate it if we changed this.  Ditto if we changed the name of the compiler's default hash method to match the user's, given that I don't think we've documented it anywhere (?).

**Comment by mppf** [comment]
> 
> > (1) is the equivalent of being able to provide a comparator for a particular sort call but (2) is the equivalent of being able to override < so to change the default sort order for a particular type.
> 
> Huh...  I think of (1) as being the ability to define the hash function for a particular type more than (2), since I'd expect most full-fledged types that cared to define a hash to do so as a primary or secondary method.  It also seems to provide the potential to do it for a particular call using tertiary methods, though that doesn't seem like the common case (even though it was a recently motivated one).  Meanwhile, passing in a record or FCF seems more like a way to specialize a given map instance independently of the eltType rather than linking it to a particular type.  Did you get your numbering backwards?  If not, could you say why you seem to see it backwards from me?  Is it because the motivating example was trying to define it on `int` rather than a user type and used a tertiary method?

Yes, I got my numbering backwards, whoops!

> 
> > I think the main difference with FCFs is that AFAIK we can't write an FCF method.
> 
> Is there anything that would require/desire the hashes passed via an argument to be written as methods rather than standalone functions?

Yes, but we don't have to build it that way. If we were following along from the Sort module comparators, we'd expose the different hash function APIs (if you will) with different method names. We have been talking about having an API for a keyed hash and then falling back on an unkeyed hash if that doesn't resolve. So we could have them be methods with different names.

(I don't think it's critical to do that in this case, though. Additionally, I think something like a Cuckoo hashtable wouldn't work if you didn't provide a keyed hash (or we had an API for two hashes), so the only benefit from trying a keyed hash and then using an unkeyed one if it's not present is that some types could work with hashtables that don't need two hashes).

> 
> > Certainly, you could argue that all record authors should be providing a hash function to make a good type, but isn't that already the case because the compiler provides a default implementation?
> 
> I think of it as being very similar to `writeThis()`:  The compiler provides a default implementation, and that may be good enough in many cases, but if you really want your type to print out a specific way / hash on certain aspects of its value and not others, you'd override it.  (That might suggest calling it `hashThis()` though frankly, I'm not wild about the name `writeThis()` so would think about changing that first, given the choice).

I agree about the similarity to writeThis.

> 
> > if defining this changes the behavior of all maps/sets using int from this module that seems like it might be surprising, given that there might be some other module being used that expects int.hash to do a particular thing - in the same way that we expect + on ints to behave in a particular way.
> 
> This feels a little different to me in that changing hashes doesn't really change observable behavior, just performance, doesn't it?  E.g., even if I had my hash function return 0 for all values of my type, `==` would still be applied to distinguish between values, so all I'd really be doing is changing the conflict behavior of the hash function rather than anything semantic about the map or set?

Agreed.


> My bigger concern with approach (1), which relates to my inability to keep the POI-style rules of Chapel clear in my head without writing examples to test things, is whether we'd end up in a situation where a `Map` was created using a tertiary `hash` method, but was then used in other contexts where the default/primary/secondary `hash` method was used instead, such that we got inconsistent behavior depending on the calling context. 

> ...

> Is the add("d", 3) going to use SymbolTable.string.hash (rationale: it's what was visible where the `map` instantiation was created) or the default one (rationale: it can't see the tertiary method based on the current imports)?

I think this problem is possible with the `canResolve` approach that was prototyped. But if we think of it as renaming `chpl__defaultHash`, I don't think the problem is possible anymore. The reason is that the `map` code, when seeking to call `chpl__defaultHash(string)`, will find the implementation in the standard modules. (Here I am supposing that the default implementation is not marked "last resort" - I have more to say about that below). The POI / scoping rules will prefer the `chpl__defaultHash(string)` directly visible from the generic code in Map to the one that needs POI to get it. As a result, the provided overload of `chpl__defaultHash(string)` will just never get called in any setting.

However, a typical use of Proposal 2 wouldn't have this problem, because the `hasher` type and the `map` type would be different (so it's not about POI scopes as much as - can we find a function/method working on a new type at all).

I think that indicates to me two things:
 1. Maybe we do need both Proposal 1 and Proposal 2 for complete functionality -- i.e. perhaps we should try to do both at the same time.
 2. "last resort" interacts with POI in a way that can be confusing in this setting.

(how POIs currently interact with last resort is described as LR-2 in https://github.com/chapel-lang/chapel/issues/15948#issuecomment-667334488 / #16158).

(IIRC we are generally marking the functions created in buildDefaultFunctions as "last resort" but I don't think we should continue doing so; instead I think a) it should be up to the module defining to the type whether to have a user-provided one or compiler-generated one and b) the compiler should be able to reliably figure out if the module defining the type as a user-provided one - and this will be easier if we can user resolution-like ideas to do the check - where a challenging case would be a generic function - and anyway this is easier in the new compiler).

> 
> > it seems to me that we should be renaming chpl__defaultHash(x) to x.hash(). That is; after we do (1) that chpl__defaultHash is no longer available or generated by the compiler. I think that we should be handling deprecation (if we need it at all) by arranging for the compiler to give an error when it sees any function definition with the name chpl__defaultHash. @bradcray do you know of a particular reason not to use this renaming approach? Is the strategy of leaving both available an expedience?
> 
> I took the approach I did because I'm not really familiar enough with the current HashTable implementation to know what choices were made and why, and it seemed like an obvious safe place to inject the logic in the five minutes I spent on it.  I don't have any particular personal motivation for keeping `chpl__defaultHash()` nor any problem with retiring it.  I interpret `chpl__defaultHash()` as an internal / non-user-facing symbol, so wouldn't expect to need to deprecate it if we changed this.  Ditto if we changed the name of the compiler's default hash method to match the user's, given that I don't think we've documented it anywhere (?).

Sounds like we can agree on a "renaming" approach then. I was worried that there would be subtle behavior differences with the `canResolve` approach and I think they are there, judging by the SymbolTable example you made.

**Comment by bmcdonald3** [comment]
After getting some (a lot) of help from Michael on this, we were able to get approach (1) implemented with the arbitrary name `hashThis` that is open to change based on consensus, so weigh in on that please if you have an opinion. The current limitations with this approach is that it does not let you redefine `int.hashThis()` and other built-in type methods, but only ones on user-defined records.

For our specific use-case of the k-nucleotide benchmark, this will allows us to create just a simple record that wraps the index and use that for our map, so we can achieve the desired results, but it is a bit more roundabout then just redefining `int.hashThis()`.

With this in mind, deciding when/if we want to move forward with also allowing approach (2), where the user is able to pass in a hasher record/FCF that would allow a new hash method for `int.hashThis()` seems like the next question to me and I wanted to gauge where everyone stands on that.

Additionally, would we still like to get this change into this release?

Here is the link to the still-in-progress branch (just need to change/add testing): https://github.com/bmcdonald3/chapel/tree/user-defined-hash

**Comment by bradcray** [comment]
Cool, thanks for jumping on this today, Ben! (and Michael!)

I've tried to capture the discussion so far about the name of the method on #18340.

The inability to override the default hash for int/string/primitive types cools my jets a little bit in terms of trying to get this in for this release.  Specifically, I think it makes the record/FCF-based approach slightly more appealing for the CLBG entry, so I'm not sure that I'd put in a less-elegant version that used the record workaround in the meantime just to get a faster speed (but lower code size score, where we're already not that great).  I'd also like to make sure I understand why records work one way and primitive types another (e.g., is the implication that all tertiary method hashes won't work as I was fearing?  or just those on primitive types?  and in either case, why?).

So all of that (plus the split vote on the naming question initially) makes me think maybe we need a bit more time to let all of this cook a bit rather than rushing it in and then potentially changing it.

**Comment by mppf** [comment]
>  I'd also like to make sure I understand why records work one way and primitive types another (e.g., is the implication that all tertiary method hashes won't work as I was fearing? or just those on primitive types? and in either case, why?).

I don't think we can have tertiary methods hashing working (ever).

See the previous discussion:

> I think this problem is possible with the `canResolve` approach that was prototyped. But if we think of it as renaming `chpl__defaultHash`, I don't think the problem is possible anymore. The reason is that the `map` code, when seeking to call `chpl__defaultHash(string)`, will find the implementation in the standard modules. (Here I am supposing that the default implementation is not marked "last resort" - I have more to say about that below). The POI / scoping rules will prefer the `chpl__defaultHash(string)` directly visible from the generic code in Map to the one that needs POI to get it. As a result, the provided overload of `chpl__defaultHash(string)` will just never get called in any setting.

In particular for the case of `int.hashThis()`, the `map` generic code finds the one in the standard library. Our language design for POI scopes is to prefer such naturally visible candidates before looking at POIs. (The reason for this is to avoid surprise for the author of a generic library - to use the version from POI would be "hijacking"). As a result, a custom `int.hashThis()` will never be found to resolve the generic `hashThis` calls in a generic `map`.

Now, we could work around this problem by marking `int.hashThis` in the standard library with "last resort" but that introduces the possibility that a single `map`, when used in two different places in the code, would get two different hash functions (a very bad outcome that you anticipated with the SymbolTable example above).

My conclusion is:
 * The type author always defines `hashThis()` in the type's module (if they do not do so explicitly, the compiler adds one)
 * Tertiary overloads of `hashThis()` are not possible because of the way POI interacts with the function always being defined for a type
 * The record/FCF function approach is arguably a nicer way of writing a special hash for `int` for a special `map`.

**Comment by bradcray** [comment]
I think I misinterpreted:

> I don't think the problem is possible anymore

as meaning "if we were to switch to a method / use the same name for both then using a tertiary hash will work as you want" (though I was surprised that would be the case).  Where now I think you were saying "yes, that is a problem/fragility, but if we switch, then the fragility will go away and there just won't be a way of creating a custom hash method for a well-defined type."  Got it.
