### ISSUE TITLE
Restarting "index neutrality" discussion

### ISSUE THREAD

**Issue by mstrout** [chapel-lang/chapel#18295]
A previous issue started by @ben-albrecht proposed a definition for "index neutrality" (https://github.com/chapel-lang/chapel/issues/17624).  I would like to restart the conversation and propose a slightly different definition and an initial implementation goal.

A function is considered _index-neutral_ if it meets the following criteria:
- Any arrays accepted as arguments can have any offset or stride in their domains
- Indices will have meaning thus any arrays returned will inherit the domain from the argument arrays if possible
  - When doing a point-wise operation between two arrays, if they have non-overlapping indices there will be an error because the output indices are undefined.  (e.g., trying to add ``var A: [1..10,1..10]`` with ``var B: [1..10,11..20]`` would result in an error)
  - For point-wise operations where the domains overlap, the output could be the point-wise operation results in the intersection of the domains. (e.g., adding ``var A: [1..10,1..10]`` with ``var B: [0..9,0..9]`` would result in an array ``var C: [1..9,1..9]``, where ``C[i,j] = A[i,j]+B[i,j]``.)  
  - For a matrix-matrix multiplication, the typical semantics is to have the inner dimension ranges match.  However, in an index-neutral world, where we might want to enable blocked implementations of things, it would be better to use index meaning instead.  (e.g., multiplying ``var A: [1..10,30..40]`` with ``var B: [31..40,10..20]`` would result in ``var C: [1..10,10..20]`` and ``C[i,j] =`` sum over ``31..40`` of ``A[i,k]*B[k,j]``.)

For an initial implementation of index neutrality in the LinearAlgebra package, we will simplify things in the following ways:
- Require unit strides in any routines that already assumed unit strides.
- For point-wise operations, do NOT do the domain intersection.  Instead assume the domains line-up exactly.  Are there any use cases for point-wise arrays that have intersecting domains?
- For matrix-matrix operations, DO use the inner domain intersection.  It won't be too difficult because it is 1D range intersection, and a popular use case would be a block-distributed implementation of matrix-matrix multiplication.

In addition we will keep the output default domain as 0-indexed when matrices are constructed with extent information only.

Please provide feedback (especially @e-kayrakli and @damianmoz) about the above index neutrality definition.  Also, the proposed initial simplifications.

Related issues
- https://github.com/chapel-lang/chapel/issues/18159

**Comment by mstrout** [comment]
This is all very useful @e-kayrakli.  Thank you!

> If we were to have support for such operations, than they need to be limited to a "tensor" type of sorts.

I see now that `Vector` and `Matrix` are factory functions that return 1D and 2D arrays respectively and not `Vector` and `Matrix` types/classes.

We may eventually want to change that and have a `Tensor` type (i.e., a generalization of vectors and matrices), but I can see that for now we just want the LinearAlgeba library to operate like the Chapel pointwise operators for arrays and handle non-zero-indexed inputs appropriately.

I plan to use #17624 as a backing issue for some tasks to fix subsets of these.

**Comment by bradcray** [comment]
Catching up on this after vacation, sorry for the late response.  I started by writing a response to Michelle's OP and then added some additional commentary and notes while reading the thread up to this point (so if it sounds like I'm repeating things that were already said, I probably am, though I tried to note it on my second pass).

I'm also tagging @npadmana on this as someone else who I think of as being a user who might have opinions about LA (Linear Algebra).

> results in the intersection of the domains.

Like Engin, I'm not a fan of using intersection semantics by default.  I think it's more likely to be confusing ("oops, I made a simple typo and got a surprising result rather than an error") than it is desirable ("I _want_ intersection semantics").  I also think slicing in Chapel is easy enough to use that someone who wants the intersection can compute it easily and express it fairly cleanly themselves.  I'm also not aware of Linear Algebra operations (in the mathematical sense) naturally having intersection semantics.

> the typical semantics is to have the inner dimension ranges match. However, in an index-neutral world, where we might want to enable blocked implementations of things, it would be better to use index meaning instead.

This relates to a question I think we were asking when you were first starting up, Michelle, which was whether one could multiply a `[1..n, 1..n]` matrix by a `[0..<n, 0..<n]` matrix (or maybe slightly more compellingly, a `[lo..#b, lo2..#b]` array by a `[lo3..#b, lo4..#b]` array if I imagine myself to be pulling semi-arbitrary `b x b` blocks out of a matrix and am wanting to multiply them).  In that first conversation, I didn't really have an intuition, but if forced to pick a side, I would probably agree with Michelle's comment:

> When doing linear algebra, the indices do have meaning.

which is to say, for my b x b example above in a "real-life" example where I was pulling blocks out of a matrix, I'd expect that lo2 == lo3 in practice because for me to conflate the sub-matrices, they'd probably need to have matching indices to be semantically reasonable.

However, at that time, I asked @damianmoz about this (using the 1..n vs. 0..<n example as motivation), and he said he thought we should support such cases, and that he designed his numeric libraries in that way.  So if we follow his lead, that would mean requiring things to match in size, but not indices, to get index-neutrality.  In which case, I'd expect the result of the multiplications above to be `[1..n, 0..<n]` and `[lo..#b, lo4..#b]` respectively.

All that said, personally, if we were to decide that our definition of index neutrality in LA was "you can pass in matrices of any indexing scheme you want, but they need to be compatible with each other"—which is to say, for a matrix add, they'd have to have the same indices in each dimension; and for a matrix multiplication, the inner dimensions would need to have the same indices—I'd be comfortable with that as well, since it's index neutral in the sense that we're not forcing an indexing scheme on you, but requires your arguments to be self-consistent.  _That_ said, given that Chapel can do a decent job of mixing index sets through zippered iteration (at the cost of a few more index variables which could increase register pressure), I'm definitely also open to using the more relaxed definition that Damian proposes in which size matters, but not indices.  I'd feel more confident about this direction if we had a compelling case from math or a single application.  I suspect that the motivation probably amounts to more of a "I created an array using one indexing scheme and you created one using another, and I want to do operations with them without reindexing / copying either" (which is also a good rationale, but not as strong for me as a mathematical motivator).

For the rest of my response, I'm going to assume "Damian's right" and that we should only rely on shape/size matches, not index matches.  Thus, for the four points of Michelle's OP:

> * Require unit strides in any routines that already assumed unit strides.

I agree with this.  And if someone felt a routine that currently permitted non-unit strides didn't work well, I might be more inclined to remove the support for non-unit strides for that routine in the short-term rather than investing a lot of effort getting it working with non-unit strides.

> * For point-wise operations, do NOT do the domain intersection. Instead assume the domains line-up exactly. Are there any use cases for point-wise arrays that have intersecting domains?

I'd be more inclined to require the shapes to match and to have a binary op that returned a new matrix take the first array's domain (as an arbitrary tie-breaker that  matches existing Chapel array semantics).  That said, I'd also support a version of the binary op that took the result in as a third argument so that a user could pre-allocate the result's storage using a domain of their choice.  (I see Engin proposed this idea as well, though I'd probably make it a `ref` argument rather than an `out` argument to indicate that the domain and allocation were owned by the callee).

> * For matrix-matrix operations, DO use the inner domain intersection. It won't be too difficult because it is 1D range intersection, and a popular use case would be a block-distributed implementation of matrix-matrix multiplication.

I wouldn't do this, but would just require the size match for the inner dimensions.

> In addition we will keep the output default domain as 0-indexed when matrices are constructed with extent information only.

I agree with this based on where we are today, but would've liked more public debate on whether or not this was the appropriate choice of default before it was changed (and would definitely be open to taking the debate back up again if others were).  I.e., even though Chapel is 0-based, I don't know that LinearAlgebra necessarily must be.  As an example, if I were creating a library for calendar dates that involved arrays and indexing, I would number the months 1-12 and the days 1-[28-31] rather than making them 0-based because if you told me that 5/8/2021 == June 9th, I'd look at you like you were insane.  For that reason, I don't think Chapel's 0-based default should affect all library designs.  My sense is that Linear Algebra mathematically uses 1-based indices when it uses them at all, and if that sense is correct, it suggests to me that perhaps the LA library should / could be 1-based despite Chapel's choice for tuples, strings, etc.  I understand that there are precedents in both directions within community LA packages, and it would've also been good to survey those precedents to see which ones we feel more aligned with.  I feel like this design discussion didn't really take place in anything other than a passing manner (at least, that I can recall), and feel like we definitely made a mistake in our process, even if we would've arrived at the same decision.

Back on the "left-hand-side wins" aspect of pointwise operations, Engin said:

> And I don't think it is because of some deep design choice

I don't think this is correct.  I'd say we did very intentionally decide that Chapel would define the indices of a promoted/zippered operation to be those of the leader.  However, this decision was (obviously to those who are familiar with it) linked very strongly to our leader-follower semantics and implementation strategy.  So my point is that it didn't fall out accidentally, but was decided upon intentionally and proactively with eyes open at the time that we were designing zippered iteration and promotion.

Engin also mentions:

> In the past, we have had similar discussions about the distributed-ness/sparse-ness of the returned arrays

This is the question that really terrifies me.  In my response here, I'm focusing mostly on the logical indices of the result rather than the representation in terms of distributions / sparsity / etc.  For questions of representation, I feel a tension between doing something simple (like "inherit the first argument's implementation") vs. 'smart' (like "a sparse x a dense matrix should perhaps give a 'sparse row / dense column' result by default").  Anyway, I'm going to focus just on the indices question here for now (because it's hard enough), and think we should wrestle more about the representation questions on a case-by-case basis, hopefully coming up with a modest set of routine classes and rules for what kinds of results they should generate to be most productive (and without creating a nightmare of cross-products to worry about for ourselves).

And:

> I believe, in terms of design philosophy, the LinearAlgebra module wants not to have special types for vectors and matrices and work on Chapel arrays. 

We went back and forth on this, and I honestly can't quite recall how we ended up in the current "no special types" interpretation (@ben-albrecht might).  Specifically, I can't recall whether it was due to limitations in our ability to create good Matrix/Vector record types at the time without performance hits or an actual desire to simply use raw arrays.  One downside of the current approach is that you can't represent a matrix-matrix or matrix-vector product using `*` very easily without introducing confusion.  On the other hand, an upside is that you get all of Chapel's array support (including support for various domain maps) on your matrices and vectors without having to explicitly define all of those things on your Matrix/Vector/Tensor types (maybe forwarding would help here, which we didn't have when we started with LA, but I'm skeptical that it would get us fully where we'd need to be without a fair amount of manual wrapping).

**Comment by e-kayrakli** [comment]
> I don't think this is correct. I'd say we did very intentionally decide that Chapel would define the indices of a promoted/zippered operation to be those of the leader.

I see. I didn't have that context. "Things just fell out this way naturally" was also a good rationale for me, personally. That's probably why I was happy to assume that.

> I see Engin proposed this idea as well, though I'd probably make it a ref argument rather than an out argument to indicate that the domain and allocation were owned by the callee

Most definitely. I half-heartedly attempted to say the same thing when I said

>>"out" (but not really `out`) 

:)

> This is the question that really terrifies me. In my response here, I'm focusing mostly on the logical indices of the result rather than the representation in terms of distributions / sparsity / etc. For questions of representation, I feel a tension between doing something simple (like "inherit the first argument's implementation") vs. 'smart' (like "a sparse x a dense matrix should perhaps give a 'sparse row / dense column' result by default"). 

I think the approach of asking for a `ref` argument to put the result solves this issue, as well. FWIW, I believe we should have all our LA routines do something simple as you suggest here, and have an overload that takes such extra argument(s) to store the result and give the user more control if they want to. Both for index-neutrality and memory layout standpoints.

It can also have some positive performance implications, where a user might want to reuse an array that they don't need anymore, for example. This way, then can avoid allocation/deallocation costs.
