### ISSUE TITLE
What should the name of our standard hashing method be?

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#18340]
In https://github.com/chapel-lang/chapel/issues/18291 and related issues, we're evolving toward the notion of supporting a standard method on all Chapel types that supports hashing.  We already have something like this today in `chpl__defaultHash()`, but that isn't user-facing or documented (nor a name we'd want to use).  This issue asks what the user-facing name for such a method should be?

Initial candidates thrown out for consideration for a type `R` are:

* `R.hash()` :+1:
* `R.hashThis()` :heart:
* `R.hashCode()`
* `R.getHashCode()`

The latter two come from Java and C# and have not received much love, so will not get more attention in this OP.  So far, the first two have received approximately equal support.

Some of the discussion so far has been as follows, where I'm trying to be as neutral as possible, though I do have a preference which I probably won't be able to hide:

* `R.hash()`:
  * ...is short, sweet, and concise.  It seems clear what `myVal.hash()` means to anyone who knows about hashing.
  * However, its brevity also makes it more likely to be an identifier that a user would want to use
    * However, is it likely that they would want to use it (in this signature) for anything other than what we want to use it for?
    * Note that nothing prevents users from using the `hash` identifier in other contexts or with different signatures
  * Python uses `__hash__()` and Swift uses `hash()` (albeit with a different signature / behavior)

* `R.hashThis()`:
  * Is symmetric with `R.writeThis()` and `R.readThis()`, which are our standard methods for printing/scanning a type
  * However,
    * other standard methods like `init()`, `deinit()`, `postinit()` do not have `This()` in their names
    * `This()` seems somewhat redundant/tautological.  As a user, if I write a method that does `verb()`, I usually call it `.verb()` not `.verbThis()`
    * the I/O routines have not received their 2.0 review yet, and `This()` seems clunky to some of us in the I/O context as well (e.g., in its Chapel 2.0 review, I would ask whether we could replace them with something like `.read()`/`.write()`, `.serialize()`, the `<~>` operator, etc.)

Please feel free to add additional thoughts or arguments below, and I will try to incorporate them into the OP if appropriate.

**Comment by dlongnecke-cray** [comment]
I've come around on this and am in favor of `hash()` over `hashThis()`. My initial argument for `hashThis()` was that it would be consistent with other methods such as `readThis()` and `writeThis()` that are compiler generated and that are called within internal code.

However I think that the methods have different use cases:

- The `hash()` method would be called by _both_ user code and module code
- As far as I know, the `readThis()` and `writeThis()` methods are only ever called in the guts of the IO module

E.g. you never see a case like:

```chapel
var x = someObject.readThis(someChannel);
```

But you could _definitely_ imagine a user hashing a type:

```chapel
var x = someObject.hashThis();
```

And here `hashThis()` just looks weird.

I am also personally hoping that we can rename `readThis()` and `writeThis()` as well in order to be consistent, but I do not think we should wait to use `hash()` or call it `hashThis()` just for the sake of consistency.

**Comment by bradcray** [comment]
> As far as I know, the readThis() and writeThis() methods are only ever called in the guts of the IO module

Not to talk you out of coming over to the good side, but when defining `readThis()`/`writeThis()` methods, it's often the case that they invoke other `readThis()`/`writeThis()` methods (say, the one I define on my record may invoke the methods on all of its fields).  But given the rest of your response, it sounds like I can potentially count on you as an ally when we debate renaming `readThis()`/`writeThis()`.  :D

**Comment by dlongnecke-cray** [comment]
Wait, really? Granted, I haven't written many `readThis()` or `writeThis()` routines, but to my recollection I've only ever seen (or at least, only ever _written_):

```chapel
proc someObject.writeThis(ch) {
  ch <~> field1;
  ch <~> field3; // Skip field 2, it's hidden
}
```

**Comment by dlongnecke-cray** [comment]
Have we also considered the stance of:

- Users define a method called `hashThis()`
- Rename `chpl__defaultHash()` to `hashThis()`
- Define a `hash()` function in `ChapelBase` or the standard modules which calls `hashThis()`

This would be in line with what Python does for their `hash()` function. Users call `hash()`, but if a type wants to participate in overloading its hash function, it defines `__hash__()`.

This would give us behavior similar to `readThis()` and `writeThis()` (which in my head aren't really that ugly, because the `This` signifies that the methods can be overloaded but aren't really intended to be called directly - they are called by other features).

**Comment by bradcray** [comment]
> `ch <~> field1;`

In code like that, I tend to read `<~>` as a synonym for `readWriteThis()`... or else they're similar enough that I've been unable to internalize what the difference between them is (which is a bad sign).  It's a little odd to me to use `<~>` in a context like `writeThis()` that isn't designed for _both_ reading and writing (since that's what it was designed for).  But I definitely agree that `<~>` is a potential replacement for `readThis()`/`writeThis()` (although it's bidirectional where `readThis()`, `writeThis()` are unidirectional, so does that mean we add `<~` and `~>` as well?  Or abandon the operator forms?).  As you say, good fodder for the I/O discussion.

> Have we also considered the stance of:

@bmcdonald3 [has a draft of something like this](https://github.com/chapel-lang/chapel/issues/18291#issuecomment-912740248), but it's not quite the same (no standalone `hash()` function, just the methods, where `chpl__defaultHash()` has been replaced with a method).  I don't see huge value to supporting both `hash(val)` and `val.hash[This]()` myself, but could be missing something.

**Comment by dlongnecke-cray** [comment]
I view `readThis()` and `writeThis()` as being special methods in the exact same sense as `this()` or `these()`. They can be defined by users, but aren't intended to be called directly (and seeing them used that way kind of feels weird).

If we are defining a method which is called directly by user and internal code, then clearly something like `hash()` is the obvious choice.

What has me hung up here is that the general M.O. for `readThis()`/`writeThis()`/`this()`/`these()` is different than what is being envisioned for `hash()`.

Ideally, I would like it if most/all of these special methods could be consistent in how they work, either:

- All ending in `This`, all used indirectly by other features
- All using proper names (`read`/`write`/`hash`/`this`->`operator[]`(?)/`these`->`iterate`(?) and directly callable by the user

**Comment by bradcray** [comment]
> Ideally, I would like it if most/all of these special methods could be consistent in how they work, either:

I completely agree with that as long as the answer isn't that they all use `This`.  :D

**Comment by bradcray** [comment]
Noting that while, internally, we converged on using shorter method names like `hash()` rather than `hashThis()`, users have pushed back, not liking that Chapel does not have a standard way of demarcating "special" functions that can (arguably should) be supported by all/most types, like Python's `__specialFn__` signifier.  So this warrants more discussion still.

**Comment by bmcdonald3** [comment]
Is the discussion you would like to have here around `hash()` specifically or are you hoping to converge on a standard that we will use for all compiler-generated methods?

**Comment by dlongnecke-cray** [comment]
I'd be fine with naming our special methods `__specialMethod__`, but only if we plan on also providing nice clean "Chapeltastic" ways to call those methods.

In Python, types can override the behavior of the `hash()` function by defining a method called `__hash__`. But the `__hash__` magic method is rarely (if ever) called directly. This precedent exists for almost all magic methods.

If we are envisioning a world where both language and humans call `__specialMethod__` directly then I struggle to find words to express my revulsion with that naming choice... :D

> Is the discussion you would like to have here around hash() specifically or are you hoping to converge on a standard that we will use for all compiler-generated methods?

I think we should open a separate discussion for how to namespace / control access to method names when multiple modules provide/define them (unless we have one already, my apologies - I have not checked yet). I hope there is an answer there that will prevent/avoid a dystopian future where users call `x.__hash__()`...

**Comment by bradcray** [comment]
> Is the discussion you would like to have here around hash() specifically or are you hoping to converge on a standard that we will use for all compiler-generated methods?

I think we need to have the discussion about all of them at once, which will inform this one.  Note that while the compiler often automatically generates these, I think of them as being less about being "compiler-generated" methods, and more like "methods that provide standard capabilities we expect of all/most types".

**Comment by dlongnecke-cray** [comment]
Reposting what I said in the megathread (#19038)...

---

(Here `Hashable` is a theoretical interface which has a method
called `hash`.)

I think that `hash` should be a standalone procedure that accepts
a `Hashable`. I think this solves the namespace collision issue
in a natural way, because if a user has defined their own `hash`
function they can cast their type into a `Hashable` before making
the call (assuming such functionality is possible). To reduce the
possibility of namespace collisions even more we could name the
interface `ChapelHashable`.

Or we could let the user specialize their `hash` function for a
specific concrete type, in which case I figure that that overload
would be preferred over the `hash(obj: Hashable)`.

I don't think we should worry too much about defining a top level
`hash` procedure. It is such a core behavior that Brad's argument
(what else is a `hash` procedure going to do?) holds a lot of
weight. It's also not a method, so we're not polluting the method
namespace in the first place.

Additionally, I would expect the compiler to be able to automatically
derive types as instances of `Hashable` in the same way that it
could for `Readable` and `Writeable`. This ensures that users can
hash their POD types out of the box.

---

I kind of view this approach as a take on what Python generally
does (have a type define a dunder-method and then use a free
function to call that), except using interfaces instead of dunder-
methods.

I think this makes more sense for a language like Chapel, which is
statically typed.

My idea does lean on interfaces to work, though, and it could be that
we feel that interfaces are not ready enough to use right now.

I think that interfaces could be used as a viable solution to the
problems we are facing right now with special methods, so maybe it
is a good idea to pursue the notion if only to drive interface
development forward.

**Comment by DanilaFe** [comment]
I believe this is ready to be closed -- we introduced the `hashable` interface and the `hash` method.

The original issues were https://github.com/chapel-lang/chapel/issues/19050 and https://github.com/chapel-lang/chapel/issues/22618.

**Comment by bradcray** [comment]
Thanks, @DanilaFe !
