### ISSUE TITLE
[Map Module Review] Create proposals for serial/parallel/distributed maps

### ISSUE THREAD

**Issue by Maxrimus** [chapel-lang/chapel#18494]
One of the big topics that came up during the module review that was partially related to https://github.com/chapel-lang/chapel/issues/18097 but unique enough to garner its own topic was the idea of what to do with serial vs parallel vs distributed maps. The issue being that the most obvious solution would be to create two separate types, but that somewhat detracts from Chapel's inherent scalability. So the team wanted to create a proposal for what this possible solution might look like, the main crux of said proposal being to make the separate classes easy to swap out for simple movement between serial and parallel versions, with possible distributed versions being similarly scalable.

For more in depth discussion of the proposal ideas check the notes from the review(See the private mirror of this issue for the link: https://github.com/Cray/chapel-private/issues/2457) as well as the comments of the module review itself(https://github.com/cray/chapel-private/issues/2340)

**Comment by bmcdonald3** [comment]
When further discussion happens with this, I think that https://github.com/chapel-lang/chapel/issues/18825 is worth talking about and it could bring some clarity to this discussion as well.

**Comment by bmcdonald3** [comment]
In https://github.com/chapel-lang/chapel/pull/18810, @aconsroe-hpe and I were discussing whether or not compiling with `--fast` or `--no-checks` should disable all checks in a module or only explicit calls regarding bounds checking.

There are 2 examples that come to mind after this initial discussion:
1. Explicit bounds checking related to indexing
    - `if !found then boundsCheckHalt("map index " + k:string + " out of bounds");`
    - This is what `boundsCheckHalt` was created for, this checking is not done with `--no-check`
2. Non-"bounds" checking checks 
    - `resizeThreshold` checking is currently disabled in map with `--no-checks` using the `boundsChecking` param, even though it isn't an explicit boudns check:
```
if boundsChecking then 
  if resizeThreshold <= 0 || resizeThreshold >= 1 then 
    boundsCheckHalt("'resizeThreshold' must be between 0 and 1");
```

So the questions are: 
(a) Do we want to disable all checks with `--no-checks`, or only bounds checking for these data structures?
(b) Do we want the same behavior for `parSafe` and non-`parSafe` data structures in regards to bounds checking?

**Comment by bradcray** [comment]
If checks were not going to hurt performance, we'd leave them on all the time (i.e., not have the various `--no-checks` flags).  For the resizeThreshold check, since that's a simple integer check that's run once when a map is initialized (right?) I'd just leave it on all the time.  Compared to the memory allocations it does and the like, any overhead should be completely in the noise. And it would be annoying to have someone use a bogus value because they'd accidentally turned checks off.

Now for case 1, I feel like I need more information:  For a rectangular array, I can calculate where the element should live with some simple math, and if I'm OOB, that math could generate an invalid address, hence the checks.  For a set or map, though, where the indexing isn't simple math, but a potential loop over possible candidates, don't we know whether the index (which I think means "key" here, is that right?) is in-bounds or out of bounds by virtue of doing the indexing?  (in which case we should always print the message).  Or is this error that's quoted from somewhere lower in the code than the logical key lookup?

**Comment by bmcdonald3** [comment]
> don't we know whether the index (which I think means "key" here, is that right?) is in-bounds or out of bounds by virtue of doing the indexing?

That is a good point which I had not considered. So, what you are saying is rather than checking after searching for slots if it was found, we just print the error right away if the slot is not found to avoid having the check at all? This makes sense to me and I could see the value there; the only potential hangup with that approach today is that the find slot function is used in 2 different cases, the first case is to find an empty slot that can be filled, the second case is to get the value at the index. This means, in the first case, we expect to find an empty slot, which would then be considered "out of bounds" if we put the error there, while the out of bounds error would be what we are looking for in the second case.

A way we could have both of those needs met would be change from using a single find slot for both cases to having two find slot calls, one for when we expect a value to be there, one for when we do not in the `chpl__hashtable` implementation.

**Comment by bradcray** [comment]
> So, what you are saying is rather than checking after searching for slots if it was found, we just print the error right away if the slot is not found to avoid having the check at all? 

Right.

> A way we could have both of those needs met would be change from using a single find slot for both cases to having two find slot calls, one for when we expect a value to be there, one for when we do not in the chpl__hashtable implementation.

How about just having the helper function (it's not user-facing I think, right?) take a bool saying whether to issue an error or not.  Or it could take an error string and only print the error if it's non-empty or something like that?

**Comment by lydia-duncan** [comment]
After thorough investigation, we determined that the interface provided can be supported by parallel and distributed implementations.  Closing this issue
