### ISSUE TITLE
I/O module: should we prefer read(type t) to read(ref value)?

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#18496]
Today, both of these `read` calls work:
``` chapel
var x = stdin.read(int);

var y: int;
stdin.read(y);
```

See https://chapel-lang.org/docs/modules/standard/IO.html#IO.channel.read (but note that you have to scroll down a bit to get to the `type t` version).

However, the `read(y)` example is using a `read` call that accepts the value to read in to by `ref`. But, in order to pass something by `ref`, it has to already exist. That seems unfortunate in the context of reading since we'd like to be able to construct the value in the process of reading. That comes up in particular when reading something that is not default-initializeable. Also note that the requirement that the value exists already makes it harder for the `read` implementation to allocate classes during the read or to resize an array during the read.

One downside to the `read(type t)` strategy is that the function either returns a value or throws. That is nice for making the initialization situation clear and intuitive, but we lose the chance for `read` to return a bool indicating if EOF has been reached. However there are two ways to address that issue:
 1. The code calling `read(type t)` can call a function to check to see if the channel is at EOF. This works just fine if the channel is only used by one task. The function one would need to call exists today but is undocumented. https://github.com/chapel-lang/chapel/blob/d18e9ec571982887abe45ec3be43fd24b822e263/modules/standard/IO.chpl#L4113-L4120
 2. The code calling `read(type t)` can use try/catch to catch the EOFError in order to end a loop reading in data.
 
Due to the initialization issues mentioned above, the Encoder/Decoder design proposal #18499 uses a strategy of passing the type to decode in as an argument (rather than a ref to a value). Should we prefer the `type t` version of `read` more broadly?

We could consider:
 * deprecating the `read(ref val)` version entirely
 * updating the docs and primers to be more enthusiastic about the `read(type t)` version (where currently this version has a bit of a warning label on it in the docs).

**Comment by bradcray** [comment]
I'm definitely OK with preferring `read(type t)` — particularly assuming it can be used in a `var (x, y, z) = read((int, real, string));` kind of way.

But my preference would not be to deprecate `read(myVar)` forms because I think it's nice to be able to have symmetry between:  `write(x, y, z);` and `read(x, y, z);` for types (and now types+encoders) that are lossless when written/read this way.  W.r.t. the `ref` point, my intuition is that with the new-ish interpretation of `out`, we could use `out` there and have it work either for initialized or uninitialized variables, right?  In which case, I think it would also be good to make that change rather than continuing to rely on `ref` here.

**Comment by bradcray** [comment]
I don't feel particularly tied to the current `ioLiteral` approach.  If we currently supported something like `read("{", x, ",", y, "}");` and were talking about deprecating that, it would make me sad, but I don't think we do (right?).

OTOH, I think what you're saying is that such cases would have to be broken down into distinct lines like:
```chapel
readLiteral("{");
read(x);
readLiteral(",");
read(y);
readLiteral("}");
```

which also seems too bad.  But not so bad that I'd argue for keeping the current `ref` intent nor `ioLiteral` per se (and it feels like this case would be better handled using regex anyway?).

**Comment by bradcray** [comment]
Between the conversation about getValue this week on #18786 which made me think "I'm happy to have both throwing and non-halting, non-throwing versions of capabilities when possible to support either style" and participating in [Advent of Code](https://adventofcode.com/) (4 days so far), I wanted to double down on my "my preference would not be to deprecate read(myVar) forms" statement above, because all 4 advent of code days so far have required reading an unknown amount of data from input, and I've generally found myself preferring idioms of the form:

```chapel
{
  var myVar: myType;
  const success = read(myVar);
  ... do something with myVar ...
} while success;
```

over having to throw/catch or call an additional function to find EOF.  The one case where I ended up going to a try...catch idiom was one in which I was needing to read commas where I essentially had to lean on `readf(",")` since `read(",")` isn't supported, and then had to do a try...catch around it to check for EOF or not.  There are obviously other ways to skin this cat (read in the whole line, split on commas—proving once again that I'm not coming to Chapel from Python for not thinking of it earlier), but taking the "read into the right place as we go" philosophy that I'd been mostly trying to take, it definitely felt a bit clunkier.  If the readLiteral() above had returned a bool, that would've gotten me back into my try/catch-free approach.

(I also don't want this to sound as though try/catch-based approaches are inherently bad or untenable for me, I just find the versions that return bools simpler from a "depth of curly brackets" / "simplicity of control flow" perspective, which probably is primarily a result of my age and the languages I've spent most time programming in more than anything).

**Comment by mppf** [comment]
@bradcray - note that if we have `read(out args...): bool` and you pass in something that isn't default initializeable, it wouldn't be able to return `false` and would have to throw instead. But I think we could keep the signature for simple cases like string/int/etc.

**Comment by mppf** [comment]
Or we could make that function just give a compilation error if any argument is not default initializable. That might be better.

**Comment by mppf** [comment]
Closing this issue because in the context of other I/O decisions we have decided to support both of these without strongly emphasizing one or the other. Both `read(type t)` and `read(ref value)` are useful and valuable in different use cases, even though they don't both work in all cases.
