### ISSUE TITLE
I/O: deprecate iostyle

### ISSUE THREAD

**Issue by jhh67** [chapel-lang/chapel#18501]
A channel in Chapel can have an associated `iostyle` record that specifies how Chapel's basic types should be read or written. This functionality overlaps with format strings, which can also be used to specify how types should be read and written, and will be made obsolete with the proposed addition of Encoders/Decoders in #18499.  The `iostyle` functionality also appears to be little-used. For these reasons it should be deprecated.

**Comment by mppf** [comment]
The iostyle functionality corresponds to an idea in C++ (e.g. see [iostream::precision](https://www.cplusplus.com/reference/ios/ios_base/precision/) ) but 1) I'm not so sure we need that idea in Chapel since we have format strings that are more regularly used and 2) the current implementation has enough issues and is little-used enough that even if we want to eventually add such a feature, it would be better to think of it as a new design.

**Comment by bradcray** [comment]
I like the idea of attaching some sort of "default style" to a channel, but given how little-used/-understood our current iostyle records are, and how much work it would probably take to get them into a format we like, I agree with taking the approach of deprecating and either (a) reintroducing them as cases are needed or (b) (my preference) replacing them with encoders/decoders or methods on the reader/writer to change behavior.

**Comment by lydia-duncan** [comment]
iostyle was deprecated in #19054
