### ISSUE TITLE
bigints should be hashable

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#18562]
As a Chapel programmer, I'd expect all types to be hashable by default so that I can store them in maps, sets, and associative domains.  It seems that `bigint` values are not currently.

```chapel
use BigInteger, Map;

var m: map(bigint, string);

var i: bigint = 123;

m.add(i, "123");

writeln(m);
```

**Comment by bmcdonald3** [comment]
I am able to naively solve the BigInteger hash problem by defining a `biginteger.hash()` method, but I am still having a hard time constructing a good hash function (I found one online using C++, but where I struggle putting it into Chapel is the casting that it does; [hash function here](http://daniel-strecker.com/blog/2020-07-06_c++_hash_for_gmp_mpz_t_mpz_class/)). 

I am not quite sure how to do something like what is outlined in the above link in Chapel, so I have been unable to come up with anything better than a very simple hash function for bigint so far, but it does solve the error at least, so that may be enough for the short term?

As far as the compiler not generating a hash function issue, it is confusing to me because it does seem to be generating the expression for the hash function in the compiler. I am fairly certain the error is coming from the `BigInteger` module being located in `modules/standard` and not `modules/internal`, judging from what I have seen in `compiler/AST/ModuleSymbol.cpp`, `buildRecordHashFunction()` and generating the AST log, though, I am unable to understand exactly what is going on the code to say for sure if this is the case. It has been a bit of a struggle with the lldb tool for me so far, but I will plan to keep trying with that.

The `modules/standard` resulting in no hash function does make sense to me though, I would not expect to be able to run this code (which gives a similar error as the bigint hashing):
```chpl
var m: map(map(int, int), int);
var mKey: map(int, int);

m[mKey] = 5;
```
And the `bigint` record in `modules/standard` does seem like the only one in there that really makes sense to use a hash key, so maybe the answer would be to move where the `BigInteger` module is located?
