### ISSUE TITLE
Decide how set operators should decide which operand is chosen 

### ISSUE THREAD

**Issue by bmcdonald3** [chapel-lang/chapel#18653]
In the case of `a | b` (union) where `a` and `b` are both sets, there could potentially be a case where an object from set `a` is `==` equivalent to an object in set `b`, but not `===` equivalent. In this case, the set method needs to choose if either the RHS or LHS operand will "win" and make it into the resulting set. 

Python uses the element from the RHS, but our current implementation (inadvertently) chooses the element from the LHS. 

A conscious decision should be made regarding this and then documented so that a user would be aware and any changes would not be breaking from changing which operand is chosen by accident. Another possible option is to add a warning that the left hand side is always chosen, for example.

**Comment by bmcdonald3** [comment]
@bradcray @aconsroe-hpe Based on this discussion, I am getting the impression that we are in agreement that the LHS should always win and that the next steps here are to:
1. Make sure that all the set operators favor the LHS (and fix the ones that don't)
2. Document this in the set module

Is that where you guys stand on this or do you think it is necessary to have more discussion around this topic or anything?

**Comment by bradcray** [comment]
That sounds right to me, thanks!  If you haven't already sent around a mail or Discourse encouraging discussion, it might be good to do so to say "Over on this issue, those who have participated are converging on this approach.  Please jump on the issue if you disagree with this decision."  Put another way, I can't remember whether I jumped on here because I tend to comment on most design issues, or whether you've already tried to get people to look at it, but we shouldn't make the decision if it's just because Andrew and I happened to find our ways here and others didn't realize a decision was being finalized without notice.

**Comment by bmcdonald3** [comment]
After having implemented a test to lock in this behavior in #18842, it appears that elements have to both (1) be `==` equivalent and (2) hash to the same value for only one of the two to be included in the final set.

When I was first thinking of this issue, I was not aware that they needed to hash to the same value, and knowing that information makes me think this is much more unlikely (even though it probably was already unlikely) that this will be hit by a user. 

With this in mind, I am wondering should we:
(a) document that if the values are both `==` equivalent and hash to the same value, the first argument's value will be chosen?
(b) not document this because it seems rare enough that it will likely not be hit, but still keep the test to make sure there are no breaking changes?

**Comment by bradcray** [comment]
My initial reaction is that it should be illegal (or, a "user error") for two values to give `true` for `==` but to hash to different values.  Have you come across examples in related languages/projects where doing otherwise is a feature rather than a bug?

**Comment by bmcdonald3** [comment]
No, after doing some searching and C++ experimentation, I was not able to come up with any examples of this being a feature.

Modifying Andrew's example from above slightly:

```
class Bar:
    def __init__(self, x):   self.x = x
    def __repr__(self):      return f'Bar({self.x})'
    def __hash__(self):      return self.x # Modified from Andrew's example, now returns unique value rather than just 0
    def __eq__(self, other): return True

a = {Bar(0)}
b = {Bar(1)}

print(a == b) # False, even though __eq__ always returns true since the hash values are different
```

And commenting out the hash function does not work, giving an "unhashable type" error.

This seems to line up with the thought that `==` should also mean that they hash to the same value.

**Comment by bmcdonald3** [comment]
Having digested this a bit overnight, it seems to me that the question of whether or not two objects can be `==` equivalent while hashing to different values is a relatively separate issue than the issue in question, which is locking in the set operator behavior of LHS vs RHS.

Being worried about this issue (actually, both issues) being lost into the void, I am inclined to:
1. Open up a new issue about the relationship between `==` equivalence and hash values
2. Merge the current RHS/LHS documentation, noting it only applies when values are `==` equivalent and hash to the same value 

There is a question of whether or not we want to merge the current documentation before deciding on that issue, and I would be in favor of merging it now, but I would be curious if @bradcray disagrees with that, or sees this issue and the `==`/hash issue being more related than I am thinking of them and would like to resolve them both simultaneously.

**Comment by bradcray** [comment]
> the question of whether or not two objects can be == equivalent while hashing to different values is a relatively separate issue than the issue in question, which is locking in the set operator behavior of LHS vs RHS.

I agree with that.

> Open up a new issue about the relationship between == equivalence and hash values

I don't know whether this needs an issue per se (in that I don't think anybody has disagreed with it or would).  So I think that we should just state it as an assumption and requirement on the user's part in any documentation about creating user-defined hashable types / hash functions.

As an aside, the requirement also adds to my concerns about the compiler thinking it knows how to hash arbitrary types (issue #18577).  E.g., I could imagine someone creating their own `==` on a user-defined type, not thinking about creating a `hash` function, and causing problems if someone tries to create a set or map of the type.

> Merge the current RHS/LHS documentation, noting it only applies when values are == equivalent and hash to the same value

I don't feel like that caveat should be required here—that it should be a precondition of creating hash tables of the types in general, and not something that needs to be stated for each operation.  As an example, I think most any operation on a set or map has this "only applies" clause—e.g., I couldn't be guaranteed I'd find something I'd stored into my set or map if it weren't true.  So rather than applying it to each method, I'd just state it in the places that talk about creating hashable types.
