### ISSUE TITLE
Should we allow implicit conversions from param string to bytes?

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#18670]
I was looking at some function resolution code that allows implicit conversions from string literals / params to `c_string` and wondered if we should allow implicit conversions from `string` params to `bytes`.

A related question is whether or not `string` values should implicitly convert to `bytes`. Note however that because these have the default intent of `const ref`, we would not be able to create an implicit conversion when passing that way. That is because we don't want to create surprising copies in code that appears to only work with references - in particular it could create behavior changes if the `const ref` refers to a global that is then modified, say. As a result, the implicit conversion would only apply for `in` intent formals. However, this problem does not apply to `param` strings / string literals.

Here is an example program that doesn't compile today, but could compile if we allow param strings to implicitly convert to bytes:

``` chapel
proc foo(arg: bytes) { }

foo("test");
```

One interesting property of this choice is that we could allow `'` as a variable suffix (per #16310) if we were to remove both `b'bla"` and `c'bla'` string forms (which mean bytes literal and c-string literals today). I think we are expecting to completely deprecate `c_string` at some point. And then, maybe we don't need bytes literals if we can have implicit conversions.

**Comment by bradcray** [comment]
At first blush, I'm not that wild about this proposal.  Specifically, I'm not enthusiastic about not having a bytes literal because it means you couldn't do the equivalent of `var bytestring = b'hi there';` and it's generally felt healthy in the language to have literal formats for types as much as possible.  Moreover, since there are bytes sequences that are not legal strings, it would seem odd to me to permit illegal string literals in cases where they were about to become a `bytes` (or alternatively, to not support bytes literals that were not also legal string literals).

So, if we maintain bytes literals based on the argument above, then I don't see that writing the motivating program above would be that much more attractive/convenient/different than requiring the user to write:

```chapel
proc foo(arg: bytes) { }

foo(b"test");
```

(but maybe there are other programs that are more motivating than this one).

**Comment by mppf** [comment]
Those arguments make sense to me. Thanks for the discussion. Given that this would be a breaking change and it's not getting an enthusiastic response, I'm closing this issue, but I am happy that the discussion and rationale can be found in the future.
