### ISSUE TITLE
segfault when compiling a program trying to access an enum like an array

### ISSUE THREAD

**Issue by bmcdonald3** [chapel-lang/chapel#18674]
### Summary of Problem
The code below causes a segfault when compiling. I was hoping that indexing the enum like below would yield `testEnum.a`, but I don't think that is a common enum feature. An error message like what you get when you try to do `int[0]` could be valuable such as:
```
error: illegal type index expression 'int(64)[0]'
note: primitive type 'int(64)' cannot be used in an index expression
```

### Steps to Reproduce
```chapel
enum testEnum {a, b, c};
testEnum[0];
```

**Comment by bradcray** [comment]
Fixing the segfault should be fairly straightforward.  The idea of the feature you were hoping to get here is intriguing and arguably worth a feature request issue of its own.  Is there a precedent for it in other languages of interest to us?

**Comment by bmcdonald3** [comment]
I don't think there is a precedent for this; through some quick testing and scans of the docs, it looks like Python/C++ do not support the feature that I proposed. 

My motivation for doing so was not that I had used enums elsewhere and expected the functionality, to be honest I have never actually used an enum before and was just trying to figure out how they worked, but the case I mentioned would actually have been helpful for what I was trying to do (though, I'm not sure enums are the best thing for me to be using).

**Comment by bradcray** [comment]
I still think it could be worth opening an issue to discuss because we have, and rely upon, such a function to change integers into enums, but don't have a user-facing way to do this yet (and this seems attractive / intuitive compared to adding just a standalone routine to do it?  Or at least worthy of further discussion).  Or wait... checking quickly, it looks like we already have one here:  https://github.com/chapel-lang/chapel/issues/15102

**Comment by bradcray** [comment]
I believe that PR #18675 should fix this (I'm paratesting it now).

**Comment by bradcray** [comment]
Fastest bugfix ever?  :D
(actually, probably not... but in my defense, I was doing it concurrently with meetings)
