### ISSUE TITLE
'borrowed' keyword applied to an array crashes the compiler

### ISSUE THREAD

**Issue by twesterhout** [chapel-lang/chapel#18717]
### Summary of Problem

Trying to declare a `borrowed` array causes an internal compiler error (AST-EXP-0299).

### Steps to Reproduce

**Source Code:**

```chapel
record Chunk {
  type eltType;
  var D: domain(1);
  var data: borrowed [D] eltType;

  proc init(type eltType) {
    this.eltType = eltType;
  }

  proc init(array: [?X] ?t) {
    this.eltType = t;
    this.D = X;
    this.data = array;
  }
}

proc main()
{
  var x = new Chunk([1, 2, 3]);
}
```

**Compile command:**
`chpl -o error error.chpl`

### Configuration Information

- Output of `chpl --version`: 1.25.0
- Output of `$CHPL_HOME/util/printchplenv --anonymize`:
```
CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: llvm
CHPL_TARGET_ARCH: x86_64
CHPL_TARGET_CPU: unknown
CHPL_LOCALE_MODEL: flat
CHPL_COMM: gasnet *
  CHPL_COMM_SUBSTRATE: smp *
  CHPL_GASNET_SEGMENT: fast
CHPL_TASKS: qthreads
CHPL_LAUNCHER: smp
CHPL_TIMERS: generic
CHPL_UNWIND: system *
CHPL_MEM: jemalloc
CHPL_ATOMICS: cstdlib
  CHPL_NETWORK_ATOMICS: none
CHPL_GMP: bundled
CHPL_HWLOC: bundled
CHPL_RE2: bundled
CHPL_LLVM: system *
CHPL_AUX_FILESYS: none
```
- Back-end compiler and version, e.g. `gcc --version` or `clang --version`: gcc 11.2.0

**Comment by twesterhout** [comment]
Related: https://github.com/chapel-lang/chapel/issues/16860

**Comment by bradcray** [comment]
@twesterhout : Sorry not to acknowledge this one earlier—it slipped past me on a busy day.  This is not intended to work, but of course should also not crash the compiler.  Other users have mused about potentially wanting to do this in some way, but it has not been prioritized.

**Comment by dlongnecke-cray** [comment]
Looking at this now, it seems like we're generating incorrect AST due to the `to borrowed` primitive call. Specifically, the array type is being preserved as a bracket-loop expression instead of being transformed into an array type using `chpl__buildArrayRuntimeType` (and ditto for the array using `chpl__ensureDomainExpr`).

I think if I start by getting the correct AST to be output, then fixing this in a principled way like you wanted in [967dfe3](https://github.com/bradcray/chapel/commit/967dfe3f9f3e5e0165dfd0098214ed4b6d8846f1) should be much easier.

**Comment by dlongnecke-cray** [comment]
After generating an array type expression instead of a loop, the fix for this fell out naturally. See: #24560

**Comment by bradcray** [comment]
Thanks for the fix here, @dlongnecke-cray!  And thanks for reporting the issue, @twesterhout!
