### ISSUE TITLE
Should adding a module to the compilation command initialize the module?

### ISSUE THREAD

**Issue by bmcdonald3** [chapel-lang/chapel#18714]
### Summary
There are cases where initializing a module that has been specified by the command line could affect execution of the main module, even if not referenced from the main module, so it seems that may be something worth adding.

### Example
a.chpl:
```chpl
proc main() {
  writeln("in a");
}
```
b.chpl:
```chpl
module b {
  use a;
  writeln("in b");
}
```
Compiling and running the above files with both files on the command line today like this: `chpl a.chpl b.chpl` causes only `in a` to be printed. In other words, module b was never even initialized. This seems a bit strange since it was specifically put on the command-line and I think it would be valuable to initialize the module if specified like this.

### Additional questions
Other things to think about here are:
- Should the extra module initializations just be done at the end?
- Should the module initializations follow in the same order they were passed on the command line?
- Are there special cases where we would want different behavior? (e.g., module b used module a in the example above)

**Comment by bmcdonald3** [comment]
Capturing an argument made by Brad in a conversation:

Something to think about is "by causing this module to be used, I can adjust the behavior of other code without that code needing to be edited to be aware of it." Though it uses different mechanisms and has different outcomes, it reminds me a bit of using valgrind without having to edit source code or recompile anything. E.g., what if by naming this additional module on my chpl command-line, I could get automatic memory or comm diagnostics enabled for my program's run, for example, without changing any other modules? That seems like it could be pretty cool. (Didn't want to actually run that module? Then remove it from the chpl command line and it won't).

**Comment by bradcray** [comment]
It seems to me that, whether or not we make it the default, it would make sense to have a mode in which all modules explicitly named on / defined by the command-line were initialized at program start-up time.  E.g., you could imagine a flag called `--[no-]init-command-line-modules` or `--[no-]init-compile-line-modules`.  I'm not sure what the default should be, though I'm inclined to make it "initialize the modules named on the command line" because it's not obvious to me why someone would name it on the command-line if they didn't want it to be part of the program's execution.  It'd be interesting to see whether implementing this would result in any behavioral changes to our current test suite, and what those changes suggested about which default behavior might be least surprising.

The pseudocode I'm imagining for this is something like:
* resolve all code and modules as we do today
* for each top-level module defined by a file explicitly named on the `chpl` command line:
  * see whether that module is already in the active use set
  * if not, add it to the end of the current module initialization list

From memory, I believe this could be done towards the end of the pass that parses modules and other modules that they use or import.

As a more realistic motivating use case for this than the one in the OP, imagine a main module that permits an arbitrary number of other modules to register themselves with it, extending its capabilities.  For it not to have to know about all of those other modules, they would have to register themselves to the main module as part of their initialization process.  The main module can't ask them to do this registration because it doesn't know about them, suggesting that they register themselves as part of their module initialization.  But without changes to what we have today, they would be eliminated like `b.chpl` is above, so unable to do so.

And as a concrete example of this, imagine an Arkouda server module that starts with no inherent capabilities, where an arbitrary number of computation modules can register themselves with the server to provide an extensible set of services/operations without the server itself having to know what those services will be.

**Comment by mppf** [comment]
I was worried that my earlier work in PR #13369 which removes unused modules during scopeResolve was causing problems here so I looked in to it a bit. There were two other problems. I've created PR #18724 which gets the example working but I haven't run the test suite on it. I'm happy for help if somebody else wants to run testing with it and/or finish up the PR itself. Otherwise I will get back to it at some point.

**Comment by bradcray** [comment]
I don't have anything cooking and can give this a run.

Just to make sure we're on the same page:  My impression is that your PR didn't change anything here, did you come to that same conclusion?

**Comment by bmcdonald3** [comment]
@bradcray I have been experimenting with the linked PR and it seems to make the example I provided print both "in a" and "in b" when compiling with `chpl a.chpl b.chpl`, so I would say it did change something here, if that is what you mean by change something. I was also able to test it out in the Arkouda build process and it does seem to work there as well, though, I would definitely need to test it a bit more.

**Comment by mppf** [comment]
> Just to make sure we're on the same page: My impression is that your PR didn't change anything here, did you come to that same conclusion?

Right this works for me
```
zeus:main  [issue-18714] $ chpl a.chpl  b.chpl  && ./a
in b
in a
```

(Before, it only printed "in a")

**Comment by bradcray** [comment]
Oh, sorry, that was ambiguous.  I meant the previous PR which Michael was worried may have broken something which worked before.  From what I can tell, this never worked (as far back as 1.10.0) which isn't surprising given that we do lazy resolution of user code.

**Comment by mppf** [comment]
Yes, actually I mentioned it in the PR message #13369:

> Another wrinkle is that modules named on the command line are not currently automatically used and so their module initialization functions do not run if they are only mentioned on the command line and not used anywhere. This situation existed before this PR.

(But I hadn't noticed that until I had made #18724).

**Comment by bradcray** [comment]
A related question in this design space that came up in the testing of https://github.com/chapel-lang/chapel/pull/18724:

Should nested modules in a file named on the command-line be auto-initialized or not?

**M1.chpl:**
```chapel
module M1 {
  proc main() {
  }
}
```

**M2.chpl:**
```
module M2 {
  module I3 {
  }
}
```

By the perspective taken in this issue, both M1 and M2 should be initialized.  But should I3?

When we first ran into this, I said I wasn't sure, but that my instinct was "probably not."  Thinking about it a bit more, I'm realizing that in a code like:

```chapel
module M {
  use I2;
  module I1 {
  }
  module I2 {
  }
}
```

only inner modules that are used are initialized, whether this is user code or library code.  That is, in this example, only I2 and M would be initialized.  For that reason, I'd be inclined to say that only the top-level modules defined within a file named on the command-line should be initialized.  Or at least, I'm not seeing a strong argument for why the nested modules should be if they aren't used.

**Comment by lydia-duncan** [comment]
> Capturing an argument made by Brad in a conversation:
> 
> Something to think about is "by causing this module to be used, I can adjust the behavior of other code without that code needing to be edited to be aware of it." Though it uses different mechanisms and has different outcomes, it reminds me a bit of using valgrind without having to edit source code or recompile anything. E.g., what if by naming this additional module on my chpl command-line, I could get automatic memory or comm diagnostics enabled for my program's run, for example, without changing any other modules? That seems like it could be pretty cool. (Didn't want to actually run that module? Then remove it from the chpl command line and it won't).

This idea makes me a little uneasy.  It feels like hijacking to some extent, though I think the argument that it relies on something that has been explicitly specified by the user is a good counterpoint, and I find the example of registering modules for the main module to use compelling.  I'm still a little uneasy about code being run that isn't referenced anywhere, though.

> it's not obvious to me why someone would name it on the command-line if they didn't want it to be part of the program's execution

The example that comes to mind for me is a program that has evolved away from using the contents of one of the modules listed in its `make` command, but that hasn't realized it needs to remove the file from that command just yet.  I think one could argue, though, that the current behavior enables that to happen, while continuing to execute the module initialization might clue the user in that they don't want it any more.  Or maybe the module initialization output disappearing once the last use vanishes would be more helpful to trigger that realization?  It probably depends on the developer and how the module is set up.

**Comment by bradcray** [comment]
I understand your uneasiness, but am not sure it's worth ignoring the feature over, particularly if we have a flag that opts into or out of the behavior.

> that isn't referenced anywhere

Well, it is being referenced on the command-line...  

> but that hasn't realized it needs to remove the file from that command just yet.

There could also be a `--warn-unused-modules` flag that would warn against such cases if someone felt nervous about spending time compiling and initializing modules accidentally.

**Comment by bradcray** [comment]
@mppf: GIven your recent PR, what do you view the next steps as being for this issue?

**Comment by mppf** [comment]
I'll close it. PR #18724 adjusted the compiler for "Yes" and PR #19259 will update the language specification.
