### ISSUE TITLE
Unexpected module search behavior change 1.26 pre-release

### ISSUE THREAD

**Issue by jlbyrne-hpe** [chapel-lang/chapel#18743]
### Summary of Problem

With the 1.26 pre-release compiler, "use FormattedIO:" fails unless "use IO;" comes first. This is not the behavior of 1.25.0. 

### Steps to Reproduce

**Source Code: foo.chpl**

```chapel
module Foo {
     // use IO; // FormattedIO not found if commented out.
    use FormattedIO;
}
```

**Compile command:**
chpl ~/foo.chpl
foo.chpl:3: error: Cannot find module or enum 'FormattedIO'
### Configuration Information

I did configure the compiler to install into another directory. 

- Output of `chpl --version`:
chpl version 1.26.0 pre-release (b3897ad)
built with LLVM version 11.0.1
- Output of `$CHPL_HOME/util/printchplenv --anonymize`:
Output of $CHPL_HOME/util/printchplenv --anonymize:
CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: clang *
CHPL_TARGET_ARCH: x86_64
CHPL_TARGET_CPU: native *
CHPL_LOCALE_MODEL: flat
CHPL_COMM: none *
CHPL_TASKS: qthreads
CHPL_LAUNCHER: none
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: cstdlib
CHPL_GMP: bundled
CHPL_HWLOC: bundled
CHPL_RE2: bundled *
CHPL_LLVM: bundled *
CHPL_AUX_FILESYS: none
- Back-end compiler and version, e.g. `gcc --version` or `clang --version`:
clang version 11.0.1 (git@github.com:chapel-lang/chapel.git b3897ad)
Target: x86_64-unknown-linux-gnu
Thread model: posix

**Comment by bradcray** [comment]
Hi John —

Thanks for reporting this, which was news to me.

FWIW, I think the current behavior is the correct behavior (in that `FormattedIO` is a sub-module of `IO` and I believe the intention is for `IO` not to be `use`d by default).  The usage in the 1.25.0 documentation also suggests this by suggesting `use IO.FormattedIO;`:  https://chapel-lang.org/docs/modules/standard/IO/FormattedIO.html#module-FormattedIO

That said, it's not obvious to me with a quick look what's led to this change, and I'm running a git bisect to try to find out (while also querying the team to see whether anyone happens to know).

**Comment by bradcray** [comment]
Hi John —

It looks like this behavior changed due to a bug fix w.r.t. private uses/imports that was implemented in #18622.  Prior to that fix, the compiler was incorrectly looking into private uses/imports chains in some cases where it should not have.

As noted in my previous comment, I think that the current behavior is what is intended, since `FormattedIO` is a sub-module of `IO` and so it should not be possible to refer to that submodule without first `use`ing or `import`ing the parent module.  For that reason, I've applied the "ain't broke" label here and am proposing we close this issue if you agree.

Thanks again for bringing this to our attention.  Though I was aware of the bug fix and some of the effects it had, it hadn't occurred to me that this was a behavior that the bug had been enabling before, and I'm glad to understand it better now.  (and I definitely appreciate that you checked to see that the new behavior was a "feature" rather than an unanticipated bug or backslide).

**Comment by bradcray** [comment]
PS — I'm adding a test in PR #18744 to lock this behavior in / make sure we don't backslide in the future without noticing.

**Comment by jlbyrne-hpe** [comment]
I missed that they are actually nested. The indentation in the IO.chpl mislead me and I went along with it. The new behavior is correct. Good to know it was deliberate. I don't know whether I copied the un-nested "use FormattedIO" from an example or made it up myself and it just happened to work, I don't know. I'll leave this to you to close. Thanks.

**Comment by bradcray** [comment]
`git grepping` the sources for 'use'/'import' and 'FormattedIO', the only hit I'm finding is in IO.chpl itself (where it's legal because it's within the parent module itself), so that could be where you saw it.  Or we had some other cases that we've fixed since the bug fix.

Thanks again for filing and confirming.  (totally agree that the indentation on our modules is horked in many cases...  A housecleaning task that we never get to, hoping that most users aren't reading their sources).
