### ISSUE TITLE
[design] Reach consensus on halting/throwing in data structure methods

### ISSUE THREAD

**Issue by bmcdonald3** [chapel-lang/chapel#18825]
## Summary
Currently, `map`, `list`, and `heap` (and possibly others) all halt when attempting to access an element that does not exist in the data structure (e.g., `map.getValue(val)` halts if val is not in the map). This seems like limiting behavior, especially in a parallel context where the value may no longer exist in the time from checking if it exists with ` if map.contains(val)` to getting the value with `map.getValue(val)`. It would be great if we could set a precedence for what to do in these cases.

## The 3 main questions
If we could converge on a precedence for:
1. Halt or throw in a non-parallel safe method?
2. Halt or throw in a parallel safe method?
3. Should all such methods be in conformity, or is it alright to have a few that diverge from the pattern?

then that would be valuable for setting user expectations and when making decisions around the limitations/possibilities around adding new features, etc. to the modules. This should also bring some clarity to the `parSafe` discussion, where if we want different behavior that could bring some clarity there.

## (lots of) Proposals
A. Halt in both `parSafe` and not `parSafe` contexts

This is what we have today currently. A couple of benefits with this approach are (1) the code looks cleaner to the caller (i.e., no try! or error handling) and (2) the code is more performant due to folding out the halts when compiled with `--fast`. 

The checking being folded out when compiled with `--fast` could also be viewed as a downside, however, since the behavior is undefined if something does go wrong, which could result in some silent incorrect errors.

B. Throw in both `parSafe` and not `parSafe` contexts

The main benefit that I have been able to pick out here is (1) Users can decide what happens when their code does something unexpected, so it won't just crash their code

C. Throw in parallel safe context, halt in non-parallel safe context

Support for this case would support the position to move to 2 distinct `parSafe` and not `parSafe` data structures.

A benefit of this approach is that we are able to optimize our data structures in the non-parallel safe context where the undefined accesses are less likely, while still ensuring that errors can be handled in the non-parallel safe context.

D. Halt in parallel safe context, throw in non-parallel safe context

Support for this case would support the position to move to 2 distinct `parSafe` and not `parSafe` data structures. I can't think of a good argument for this approach, but including in case someone does.

E. Have no consensus and allow methods to either halt or throw based on individual judgements

This approach would allow greater flexibility in implementation, but would potentially add quite a bit of additional design discussion (which may not be ideal, depending on how you look at it...)

## Related discussions
User issue: https://github.com/chapel-lang/chapel/issues/17498
Discussion of adding a throw method to `map`, which breaks current precedence: https://github.com/chapel-lang/chapel/issues/18786
Parsafe discussion: https://github.com/chapel-lang/chapel/issues/18494

**Comment by mppf** [comment]
FWIW I think we have this design because `set`, `list` and `map` were originally functionality pulled out of arrays/domains. I think the halting behavior is reasonable for arrays and domains but my intuition is that halting shouldn't be the default behavior for set/list/map. I feel more strongly about this for set and map than for list. I don't think skipping the bounds check with `--fast` would save much with the implementations of these that we have today. I'd be open to having a way to opt in to halting/undefined behavior for out of bounds for these I just don't think it should be the default.

Specifically for the question of code elegance, of course the code is simpler if the programmer can ignore all possible error conditions, but that's not really practical. However I don't think that adding a `try!` call to insist that the element exists is an undue burden. E.g. `try! myMap.getValue(key)`.

**Comment by bmcdonald3** [comment]
I am thinking that throwing should be the default as well; the Arkouda developers mentioned wanting to remove all halts from their code base and instead handle all potential errors and, since they are using `map`, we would need to switch those methods to throw instead of halt for them to reach that goal of no possible halts.

**Comment by lydia-duncan** [comment]
I prefer throwing in all cases, but I wouldn't object to having a halting version that can be called.  I think at the very least all parallel safe functions should be unified with each other in how they handle this and all non-parallel safe functions should be unified with each other (where unified to me can mean supporting both strategies or supporting just one, as long as it is the same one).

**Comment by bmcdonald3** [comment]
Summarizing some key ideas from the module review today:

1. Having a param to toggle between halting/throwing could be the best of both worlds here
2. Engin: throws have a lot of overhead with the AST, so forcing that could have performance implications
3. DavidL and BenH: improving our throws to have some more advanced handling that could essentially do the same folding out of halts would solve this problem for us and wouldn't force us into having throwing and halting versions forever, but that isn't something we really have today

**Comment by bmcdonald3** [comment]
One thought that I had past the module review: If we just chose to support only `throw`ing versions for 2.0 and then add the `halt`ing stuff as necessary as non-2.0 things, that could make the process of stabilization a bit simpler and allow us to eventually trim down to the more advanced `throw`ing syntax proposed by DavidL and BenH without needing to keep around `halt`ing versions which may be less valuable in the future.

This is more of a 2.0 philosophy question though, rather than a good argument here, so just something to think about. Do we want this to be the best possible module that we can have today that may not be the best in the future? Or do we want to this to be the minimum required to achieve the desired functionality today and allow future unknowns to improve upon it?

**Comment by benharsh** [comment]
Following up, my idea (which is a bit of a stretch) was to parameterize throwing functions based on whether ``try!`` was used, since ``try!`` already captures the notion of "halt on an error". A hypothetical example of a half-baked idea:

```chpl
record R {
  var D : domain(1);
  var A : [D] int;

  proc init(n : int) {
    D = {0..#n};
  }

  // 'E' is a param boolean, and will be false if used inside a `try!`, and true otherwise
  proc this(i : int) throws(?E) {
    if E && outOfBounds(i) then throw OutOfBoundsError();
    else if !E && boundsChecking && outOfBounds(i) then
      halt("message");

    return A[i];
  }
}

var r = new R(10_000);
var sum : int;
forall i in 0..r.D.size with (+ reduce sum) do
  sum += try! r[i];
```

Anyways, this (very) rough idea here is that ``try!`` will cause a halt if there was an error, so we can give the author of the method that information. I think of ``try!`` as saying "I don't expect errors here", so with that in mind the author of the ``this`` method sort of has the "permission" of the user to halt.

**Comment by lydia-duncan** [comment]
> One thought that I had past the module review: If we just chose to support only `throw`ing versions for 2.0 and then add the `halt`ing stuff as necessary as non-2.0 things, that could make the process of stabilization a bit simpler and allow us to eventually trim down to the more advanced `throw`ing syntax proposed by DavidL and BenH without needing to keep around `halt`ing versions which may be less valuable in the future.
> 
> This is more of a 2.0 philosophy question though, rather than a good argument here, so just something to think about. Do we want this to be the best possible module that we can have today that may not be the best in the future? Or do we want to this to be the minimum required to achieve the desired functionality today and allow future unknowns to improve upon it?

I know I personally would find it annoying for a feature to vanish and then get re-added later.  So if we think we'll want a halting version post 2.0, even if it's only short-lived, I wouldn't remove the halting versions (but would be okay with having them be unstable or something)

**Comment by lydia-duncan** [comment]
I should also note, we talked about toggling at the collection level and at the program level as options

**Comment by bradcray** [comment]
> toggling at the collection level 

This seems attractive to me.  Or, we could set a default at the collection level which serves as the default at the method level, where that default could be overridden.  (Or we could only support the collection-level toggle initially and add the method-level toggle later on, which doesn't seem like it would be a breaking change).

**Comment by bmcdonald3** [comment]
Spoke with Lydia about this today, I think what the plan will be, keeping the distributed map in mind, is to switch all the methods to `throw` in the short/Chapel-2.0 term and then potentially revisit one of the more advanced proposals at a post-2.0 date.

I plan to take that implementation task on in the near future.

**Comment by bradcray** [comment]
> the Arkouda developers mentioned wanting to remove all halts from their code base and instead handle all potential errors and, since they are using map, we would need to switch those methods to throw instead of halt for them to reach that goal of no possible halts.

Note that arrays currently halt on OOB accesses, so in order to meet this goal, the Arkouda devs would need to change all their array accesses to use throwing accesses instead (which we don't support currently, and would almost certainly affect the performance of Arkouda).  On arrays, I think we've talked about having a `.access()` method that throws for people who want to catch their OOB accesses rather than have them halt their programs.  This could be another route to go here on maps:

* have `[]` be a halting get/set accessor for maps
* have explicit `set()`/`get()`/`replace()` style methods throw

The benefit would be that it would be similar to arrays (assuming arrays add an explicit throwing call going forward).  The downside is that the more concise (and, in my opinion, pleasant) syntax would be halting rather than throwing.

I'm not advocating for doing this or not at this time, just throwing it out as food for thought.

**Comment by bradcray** [comment]
Thinking about this more on the walk downtown, I think a rationale for making map differ in terms of having `[]` throw (say) is that accessing a map is inherently more expensive than a local, rectangular array anyway, so maybe the additional overhead of throwing is reasonable (and we could introduce a non-throwing access down the road if/when needed).

The only thing that makes me pause slightly in saying that is that we did have some users who were railing on us pretty hard for having too-slow map features a few years back, so maybe it's not as different as I was trying to convince myself it was.

**Comment by mppf** [comment]
> The only thing that makes me pause slightly in saying that is that we did have some users who were railing on us pretty hard for having too-slow map features a few years back, so maybe it's not as different as I was trying to convince myself it was.

I'm not sure if we've done much performance profiling of potentially halting vs. potentially throwing at all. Seems like having some initial information there would be nice if it's a consideration.
