### ISSUE TITLE
`DateTime` module review - casing renaming

### ISSUE THREAD

**Issue by aconsroe-hpe** [chapel-lang/chapel#18846]
As part of the `DateTime` module review, we've identified a number of identifiers that need to be renamed to follow our [standard module style](https://chapel-lang.org/docs/main/developer/bestPractices/StandardModuleStyle.html) guide. This module in particular as a few oddball names that are a bit weird with camelCase due to acronyms like ISO and UTC.

The below table is a list of proposed changes. Many of the identifiers appear more than once and would be changed in all uses (for example there is `proc date.isoformat()` and `proc datetime.isoformat()`. Also note that there are some concurrent discussions and decisions to be made that may remove some of these, but in the interest of getting the ball rolling and making sure we're happy with these names in the event things are kept, I've included them.

| from                   | to                     | notes |
|------------------------|------------------------|-------|
|`enum DayOfWeek`        | `enum dayOfWeek`       |       |
|`Monday`                | `monday`               |   *    |
|`enum ISODayOfWeek`     | `enum isoDayOfWeek`    |       |
|`proc isoweekday`       | `proc isoWeekday`      |       |
|`proc isocalendar`      | `proc isoCalendar`     |       |
|`proc isoformat`        | `proc isoFormat`       |       |
|`proc utcoffset`        | `proc utcOffset`       |       |
|`proc utcnow`           | `proc utcNow`          |       |
|`proc fromutc`          | `proc fromUtc`         |       |
|`proc fromordinal`      | `proc fromOrdinal`     |       |
|`proc toordinal`        | `proc toOrdinal`       |       |
|`proc fromtimestamp`    | `proc fromTimestamp`   |       |
|`proc utcfromtimestamp` | `proc utcFromTimestamp`|       |
|`proc fromutc`          | `proc fromUtc`         |       |
|`class TZInfo`          | `class TimeZone` | * |
|`proc tzinfo`             | `proc timeZone` | *|

In our discussion, it was raised that

1) `Monday` (`Tuesday` etc) might stay capitalized because they are proper nouns
2) `TimeZone` could potentially be spelled `Timezone` (and `timeZone` would be `timezone`) with the reasoning:
    > I'd be inclined to do "timezone" rather than "timeZone" on the argument that it's sufficiently compound and short/sweet to not warrant the capital Z. This also makes me feel like it would not be an aberration: https://english.stackexchange.com/questions/3934/time-zone-vs-timezone

**Comment by aconsroe-hpe** [comment]
If we deprecate the spelling of `DayOfWeek` and `Monday`, I'm having a hard time coming up with a good solution
```chapel
deprecated "This is now deprecated"
enum DayOfWeek {
  deprecated "Use monday"
  Monday = 0,
  monday = 0,
};

// TODO silence the deprecation warning from here?
type dayOfWeek = DayOfWeek;

var d1: DayOfWeek = DayOfWeek.Monday;
var d2: dayOfWeek = dayOfWeek.monday;

writeln(d1 == d2);
```

gives me
```
test/datetime-tz.chpl:12: error: unresolved enumerated type symbol or call 'type DayOfWeek.monday'
```

which may be related to #18937

**Comment by lydia-duncan** [comment]
I'd just add a new enum `dayOfWeek` and use the correct capitalization there, rather than adding new constants to the deprecated enum.  The user can figure out on their own that `DayOfWeek.Monday` should go to `dayOfWeek.monday`

**Comment by aconsroe-hpe** [comment]
But if the user's program is something like
```chapel
var myDay: DayOfWeek = myDate.weekday();
```
and we change `proc myDate.weekday` to return `dayOfWeek` instead, then their code breaks.
I don't think a return overload is possible in this case.
Even if it were, this code would be broken

```chapel
var d1: DayOfWeek = d.day();
var d2 = d.day();
writeln(d1 == d2); /* Is now a type error! */
```

**Comment by lydia-duncan** [comment]
Ah, right.  If you make `DayOfWeek` a type alias to the new enum instead, that'd work for the case you describe, but you'd still break code that used `DayOfWeek.Monday` . . .

**Comment by lydia-duncan** [comment]
Though maybe you could get around that by adding a parenless method named `Monday` to the type alias and mark that as deprecated?

**Comment by bradcray** [comment]
I don't know how much this helps, but with additional thought, I feel more and more strongly that we should not decapitalize `Monday` to `monday`.  It feels to me like a case of being slavish to conventions rather than doing the thing that people would really want.  (i.e., if I print out a value representing the date, presumably I want it to print as "Monday, November 15", not "monday, november 15".  And given that our enums stringify themselves as their names, keeping the names capitalized would do that).

**Comment by bradcray** [comment]
I had a couple more thoughts here over lunch:

* I think the right (but nontrivial) way to resolve this would be to work on improving the compiler to address the "unresolved enumerated type symbol or call 'type DayOfWeek.monday'" issue.  This isn't related to #18937 as you were hoping—it relates more to the fact that we don't resolve enums through type aliases such as `type`[def]s, type `proc`s, or presumably `expr.type` types of expressions.  And the reason I think the fix would be nontrivial (though Lydia might think otherwise) is that I believe that we resolve enums early in the compiler today (at scopeResolve) whereas we don't resolve type expressions (like type aliases, procedures, or `.type` queries) until function resolution, so much later in the compiler.  Thus, the "fix" would either be to teach scope resolve more about how to resolve through enum type aliases (to get your specific case working) or to move all enum resolution back to function resolution.  This is a classic case of our compiler resolving things in too many places (which is to say "2") that the new compiler is trying to resolve.
* Sometimes, I believe the only way to deprecate something cleanly—like some of the range capabilities in the last release—is to preserve the current behavior, warn that it's changing when anyone uses it, and give them an option to use the new approach by opting into it with a config param.  It feels like a roundabout/unsatisfactory approach to me, but can serve as a fallback if all else fails.
* I also think it can sometimes be rationalizable in our current world to say "not many users probably use this" and to break things a bit more, as long as the way to fix them is clearly described and simple.  For range capabilities, this didn't seem like it could be an option (too core), but my guess is that the number of applied uses of DayOfWeek today is much smaller, so getting an error message saying "This was renamed, please update your code as follows" without attempting to keep the existing program running _may_ be tolerable.
* In many (but not all) respects, enums are similar to param (or const?) values in a sub-module, so that might be another way to keep existing programs limping along; but it also feels like a fairly involved/esoteric workaround on our part.
