### ISSUE TITLE
problems with -I and -L ordering

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#18840]
When building a Chapel program, we use a C compiler to read dependencies (with the LLVM backend, we use an included clang for this) and a C compiler to do linking. We use `-I` options to control the header search path and `-L` options to control the linker search path. Similarly, these options are important for the build of the C runtime.

There are various workarounds that add paths to these in a variety of places, including system paths. At the very least we are adding `-I/usr/local/include` and `-L/usr/local/lib` in some Mac OS X configurations but I think it's very likely there are others. Additionally, if we simply use pkg-config information, we can end up with such paths to directories containing multiple packages, which might then contain a package we don't want to find as well.

One problem that can come up is when there is both a system installation of a package and it is bundled. This came up for a user in #18816 with RE2. If the `-I` or `-L` for the system path appears first in the generated compile or link lines, we have a problem because we will use the system version even if we were supposed to use the bundled one. I suspect that this problem can come up even for mason packages with a particular environment.

How can we fix this problem?

Some ideas:
* always use a path to a particular header / path to a particular library when working with our own third-party bundled versions (but this presents problems - I don't know of a practical way to do it for #includes and doing it for libraries means we have to choose static or dynamic linking ourselves rather than letting the linker decide)
* sort these arguments, so `-I` or `-L` options referring within `$CHPL_HOME` appear before the others.
* use some other flag, different from `-I` or `-L`, to indicate the path should be searched after something is not found in the `-I` and `-L` paths (does this exist?)

**Comment by bradcray** [comment]
> sort these arguments, so -I or -L options referring within $CHPL_HOME appear before the others.

Reading this, I found myself wondering about a simplified version of this:  Would it be sufficient to always prepend our Chapel-specific `-I` / `-L` flags to the compile / link lines such that they come before any system-provided or inferred paths?  This _seems_ as though it could be done either by always pre-pending such directories onto whatever FLAGS-style variables they're being applied to, while post-appending any directories that come from "the system" or that aren't `$CHPL_HOME`-based.  Or, we could have two sets of Makefile variables (or equivalents), one representing our local/personal directories and the other representing system-wide things.  (Maybe this is what you meant as well, though "sorting" sounded more like "literally sort the items in the variable before applying them" to me).

I'm admittedly pretty out of the loop on these scripts and Makefiles currently, particularly w.r.t. system-based queries, so am grasping at straws in saying this.  Maybe the main thing I'm lacking is:  What are the sources of system-based directories?  Are we querying them and adding them to our paths, or are they just the implicit things that are in the tools' paths (seems unlikely because I'd expect our command-line -I / -L to automatically take precedence over those), or something else?

**Comment by mppf** [comment]
> What are the sources of system-based directories?

>  Are we querying them and adding them to our paths?

Yes we are adding some as workarounds for various issues

E.g. https://github.com/chapel-lang/chapel/blob/198a6248e9d51f44ebfcdb5192c7e730cf19ce63/util/chplenv/chpl_llvm.py#L406-L410

**Comment by mppf** [comment]
And yes, we might be able to add them in a particular order. Where that concerns me is if we have something like a process to gather flags from pkg-config or whatever, if some of these refer to bundled directories and others to system directories, the order of gathering different dependencies will matter in a way that only causes problems on certain systems (e.g. we query GMP and find it in /usr/local, then find RE2 in third-party somewhere, but oops, the GMP paths for /usr/local now cause RE2 to be found there). That is why I didn't list it as a solution.

**Comment by bradcray** [comment]
> the order of gathering different dependencies will matter in a way that only causes problems on certain systems (e.g. we query GMP and find it in /usr/local, then find RE2 in third-party somewhere, but oops, the GMP paths for /usr/local now cause RE2 to be found there)

But if we prepend all bundled paths and postpend all system paths, we wouldn't hit this regardless of the order of the packages (I think), right?

**Comment by mppf** [comment]
When we are trying to figure out "What paths do you need to add for the configured GMP" e.g., then we might use a system path and might use a bundled path. To prepend the one and append the other would require knowing which one it was and also controlling the ordering - which as you said is more or less like sorting them. It's just we can't effectively have a function like `get_gmp_dash_L` because it would need to return 2 things depending on whether it was system or not. And if we are using something like pkg-config, we might not know whether it is system-wide or not (although we could certainly approximate it, by saying something like "if it's not bundled we consider it to be system wide").

**Comment by bradcray** [comment]
Ah, so if I'm understanding, the part I was oversimplifying is that the logic that would decide whether a given path is system or local is typically within each distinct package's (e.g., GMP's, JEMALLOC's) scripts/routines saying "What do you want to contribute to these paths?"  So the thing that's stitching the results together would have to know the answer to that.  Would a possible solution be to have those scripts return two paths (where one would likely be empty for any given call)—"specific-to-Chapel" paths and "user's environment" paths?

> And if we are using something like pkg-config, we might not know whether it is system-wide or not (although we could certainly approximate it, by saying something like "if it's not bundled we consider it to be system wide").

That's what I was imagining: that if pkg-config found it, it would be "system" or maybe "user environment" is what I should've been saying.  Essentially external to Chapel and not something we built or placed.  pkg-config should never point to our third-party directories I think, right?

**Comment by mppf** [comment]
> Would a possible solution be to have those scripts return two paths (where one would likely be empty for any given call)—"specific-to-Chapel" paths and "user's environment" paths?

Yes I was trying to say that. But this adds complexity and I might rather sort.

>  Essentially external to Chapel and not something we built or placed. pkg-config should never point to our third-party directories I think, right?

I think we sometimes use pkg-config to provide portability for our own bundled builds, but I am not certain.

**Comment by gbtitus** [comment]
The only place `git grep` shows us setting `PKG_CONFIG_PATH` in the Chapel repo is when we're using a Cray XC system as the host for the module build for HPE Cray EX, and there isn't already a `libfabric` package dir in that env var. If so then we set `PKG_CONFIG_PATH` to point to our bundled one so we can at least build everything. But we no longer do such cross-architecture module builds, because the EX module is now built in the (virtual) DST environment. So I think that's not a problem, because we don't depend on `pkg-config` to find our own third-party stuff. We always reference those dirs explicitly if the corresponding package is configured as 'bundled'.

Everywhere else I see references to `PKG_CONFIG_PATH` it seems to have to do with third-party packages saying what to do if they themselves don't build properly, which isn't what we're talking about here.

For the specific case of the system `/usr/include` or `/lib` or `/usr/lib` and so on I think for sure those should go on the end. They're there as a backstop in every usage I can think of, going back a long way (decades). One should always let them be overridden by alternatives. Other than those I don't think we deal with any directories that are package-nonspecific in the sense that they might provide, say, a `libgmp.*` library and a `libjemalloc.*` library, and we'd inadvertently pick up that `gmp` as a side effect of doing a `-L` to that directory in order to get the `jemalloc` there. Do we? Assuming not, I don't think the order much matters as long as we never reference a third-party `install` dir if we're not using the 'bundled' version of the corresponding package. (Since doing so might interpose a third-party library we didn't want in front of the PE-provided one found via `pkg-config` by the PE command line driver on an EX system, for example.)

**Comment by mppf** [comment]
> Other than those I don't think we deal with any directories that are package-nonspecific in the sense that they might provide, say, a libgmp.* library and a libjemalloc.* library, and we'd inadvertently pick up that gmp as a side effect of doing a -L to that directory in order to get the jemalloc there. Do we?

I don't think we do that for any bundled builds. But we do for system ones.

Say we use pkg-config to find these paths and gmp and jemalloc are installed system-wide and we're using the system gmp and bundled jemalloc. The system gmp pkg-config might give us /usr/local/include and /usr/local/lib/include, or for that matter, some custom path like /usr/shared-sw rather than /usr/local. If jemalloc is installed on the system with the same prefix, we will have a problem if the gmp paths appear before our bundled jemalloc ones.

In any case, I think you are saying that we can put our bundled `-I` and  `-L` flags first, ignoring the order amongst them, and that will go OK. I think I agree with that. Perhaps the easiest strategy along these lines is to think of our chplenv stuff as making several variables where today we have just two.

Instead of
 * `CHPL_THIRD_PARTY_COMPILE_ARGS`
 * `CHPL_THIRD_PARTY_LINK_ARGS`

Perhaps we could have
 * `CHPL_BUNDLED_COMPILE_ARGS`
 * `CHPL_SYSTEM_COMPILE_ARGS`
 * `CHPL_BUNDLED_LINK_ARGS`
 * `CHPL_SYSTEM_LINK_ARGS`

and then we would just make sure to put the bundled ones first when constructing compile/link commands.

**Comment by mppf** [comment]
> 
> Perhaps we could have
>  * `CHPL_BUNDLED_COMPILE_ARGS`
>  * `CHPL_SYSTEM_COMPILE_ARGS`
>  * `CHPL_BUNDLED_LINK_ARGS`
>  * `CHPL_SYSTEM_LINK_ARGS`

I am worried about exponential growth in these environment variables. Do we need C and C++ variants? Do we need host and target variants? Not thrilled with the idea of having 16 of them.

**Comment by mppf** [comment]
Also the above approach doesn't apply to mason packages or to the user provided command line arguments. For mason packages, is it always obvious from the context whether a dependency is system provided? Do we want a user providing a `-L` or `-I` argument to prevent bundled packages from functioning?

**Comment by ronawho** [comment]
> * sort these arguments, so `-I` or `-L` options referring within `$CHPL_HOME` appear before the others.

This is the option that makes the most sense to me. In terms of how to achieve that I'd be fine with separate bundled vs. system vars, but I also wonder if when we're building the final link command we can just look at the paths and adjust any in CHPL_HOME to be first. Or if we can't just look at the path, maybe the chplenv scripts could add a sentinel to make sure they get sorted first.

**Comment by mppf** [comment]
Thanks. I also like the approach of sorting these while creating the C compiler command / link command because it's robust for the various situations. I will look at figuring out how to do it.

**Comment by mppf** [comment]
Because it seems like it'd be hard to sort the command lines before the various places we invoke them (in makefiles for building the compiler, in support makefiles for building an executable for the C backend, in the C++ code for building an executable with the LLVM backend), I'm looking more at something like this:

```
    CHPL_BUNDLED_COMPILE_ARGS
    CHPL_SYSTEM_COMPILE_ARGS
    CHPL_BUNDLED_LINK_ARGS
    CHPL_SYSTEM_LINK_ARGS
```

except I am expecting we will need host and target, so maybe this

```
CHPL_HOST_BUNDLED_INCLUDE_PATHS
CHPL_HOST_SYSTEM_INCLUDE_PATHS
CHPL_HOST_BUNDLED_LINK_PATHS
CHPL_HOST_SYSTEM_LINK_PATHS
CHPL_TARGET_BUNDLED_INCLUDE_PATHS
CHPL_TARGET_SYSTEM_INCLUDE_PATHS
CHPL_TARGET_BUNDLED_LINK_PATHS
CHPL_TARGET_SYSTEM_LINK_PATHS
```

**Comment by gbtitus** [comment]
> Do we need host and target variants?

Yes. Or at least, our design should allow for needing them eventually even if we don't need them today. I expect that especially as the EX systems evolve over the next several years to include both a wide variety of CPU types in the blades and widespread use of the semi-virtualized UAI style "login nodes", we are going to need to fully support cross-compilation.

**Comment by skaller** [comment]
FYI I solve this problem in Felix as follows. If I build a bundled library it is given a name distinct from the standard one so it can never be confused with a third party install. 

This is actually a side effect of a solution to another problem: Unix linkers are extremely stupid and can't tell the difference between static and dynamic linkage, leading to all sorts of weird errors if they get jumbled up. So I partition all object files into two classes: designed for static linkage, and designed for dynamic linkage. This only make a difference on Linux (because Windows only supports static linkage, and Mac pretty much only supports dynamic linkage, that is -fPIC is applied in both case anyhow).

The distinction is carried through to the library component. I use the suffices `_static` and `_dynamic`. 
For example here's my bundled RE2 binaries:
```
libflx_re2_dynamic.dylib
libflx_re2_static.a
```
The only way there could possibly be an ambiguity is between versions of my product.

It can be a bit tricky: I can build static archives (.a files) of object files for both static and dynamic linkage so these need different names.

The fact linkers "choose" between static and dynamic is a major design fault and causes no end of grief. The library are distinct and should have distinct names (apart from distinct extensions). Of course many systems, including MacOS, have universal binaries which might contain both versions. It's best NOT to build these with bundled libraries. The only time you want this is when you're distributing a library to clients.

I also use `flx_pkgconfig` to find libraries from a data base. The user never specifies switches on the command line. The need for a resource specified in the source code, and the abstract name is mapped into a concrete one via a database which the user can manage. `flx_pkgconfig` is a generalised version of `pkgconfig` which is pretty badly broken.
