### ISSUE TITLE
Produce better error if doing GPU code generation and CHPL_COMM=none

### ISSUE THREAD

**Issue by stonea** [chapel-lang/chapel#18858]
As shown here: https://github.com/chapel-lang/chapel/issues/18850 GPU code generation does not work if `CHPL_COMM` is something other than `none`.

As of the release if you do this you'll get a confusing error message about a missing `fatbin` file at runtime. I believe on our working branch now you'll get a confusing error message about a missing `fatbin` file at compiletime (though I need to check).

Either way we should produce a better error or at least give the user a warning about `CHPL_COMM` at compile time. Ultimately we plan to have this supported but I'm not convinced that'll happen before the 1.26 so I'd rather add the warning\error now before we forget.

**Edit**: Also brainstorm other configurations that may not work and add errors\warnings as appropriate. One thing is `CHPL_LLVM=none`: https://github.com/chapel-lang/chapel/issues/18850#issuecomment-993847936

**Comment by e-kayrakli** [comment]
What I have in mind is:

- Make sure everything works fine if you compile with `--local` even if `CHPL_COMM!=none`
  - If so, impose that at compile time and produce a warning if `CHPL_COMM!=none` (and be quiet about it if `CHPL_COMM==none`)
- Warn at build time if `CHPL_LOCALE_MODEL=gpu` and `CHPL_COMM!=none`.
- Improve how the compilation processes interact with one another. What you say in the OP is definitely a part of it. But another part is handling errors from ptxas and fatbinary commands. Currently, if they fail the main compilation process doesn't fail. This is arguably a more general issue, though. I have https://github.com/Cray/chapel-private/issues/2757 for it.

**Comment by stonea** [comment]
I've verified this will error out (with the message about a missing `.fatbin` file) even when compiled with `--local` so long as we produce a GPU kernel (have an eligible `forall` loop). I think it makes the most sense to error out early under this configuration (even if the user has a program without any eligible `forall` loops).

**Comment by e-kayrakli** [comment]
> If I remove the = 1..10 out of the initialization for A the error goes away.

Recently, we switched to creating kernels for all foralls. I think that line turns into a forall that the loop analyzer thinks it's OK to create a kernel for, but it causes some issues. Could you capture that in a small issue?

**Comment by stonea** [comment]
> Could you capture that in a small issue?

Sure, filed a bug issue here: https://github.com/chapel-lang/chapel/issues/18914

**Comment by stonea** [comment]
@e-kayrakli

Off the top of your head, do you have a theory for why I'd get this message when I try to compile with `--local` (and `CHPL_LOCALE_MODEL=gpu`:

```
*** FATAL ERROR (proc 0): in do_kvs_init_inner() at net/gasnet-src/other/pmi-spawner/gasnet_bootstrap_pmi.c:479: PMI2_Job_GetId() failed
NOTICE: Before reporting bugs, run with GASNET_BACKTRACE=1 in the environment to generate a backtrace.
NOTICE: We recommend linking the debug version of GASNet to assist you in resolving this application issue.
```

(I'm not trying to get you to investigate this for me. I just want to make sure this isn't a known issue or that I'm doing something silly like failing to set up my environment correctly before I conclude that forcing `--local` isn't a workable solution).

If not I think I'll just do a hard error for when `CHPL_LOCALE_MODEL == "gpu" && CHPL_COMM != "none"`.

**Comment by e-kayrakli** [comment]
Huh.. that's strange. I can't imagine how you'd get an error from gasnet even after compiling with `--local`. You're using `--local` with `CHPL_COMM=gasnet`, right?

FWIW, hard error is fine with me. We can put that error at build time, too, I think. But it is not as important as just preventing compilation, I think.

**Comment by e-kayrakli** [comment]
>  We can put that error at build time, too,

I think we can add something like `validate` in `chpl_gpu` that takes the comm layer as an argument. Examples:

https://github.com/chapel-lang/chapel/blob/main/util/chplenv/printchplenv.py#L209-L212

There might be a time in the future where we can support only some comm layers with GPUs. We can build on that then.

Still, I consider this optional, though.

**Comment by stonea** [comment]
> I think we can add something like validate in chpl_gpu that takes the comm layer as an argument.

Catching the issue earlier (at the "compiling the compiler" compile time) is certainly preferable.

Does our team consider it a best practice to try and do as much validation as possible in `printchplenv.py`?

Digging around the code it looks like we end up calling `printchplenv`. In `driver.cpp`, `populateEnvMap` calls `runPrintChplEnv`, which according to a comment: "[passes] currently known CHPL_vars". So, in other words, if I populate the configuration using command line arguments like `chpl --comm gasnet` that'll get set before we run `printchplenv` and any validation code I add there will get run.  So yay, if I add validation code in `printchplenv` it gets run both at "chapel build" time and at runtime. I'm not sure if this was intentional or just a happy side effect.

Here's some things I noted while playing with this.  Not sure what actions to take based off this (let me know if you feel its worth filing Github issues. Maybe this is the sort of thing I could come back to on a post-release "issues week" or something like that):

* It looks like in `driver.cpp` we do some validation in `validateSettings`, but it looks like we also do a lot of validation in various set*() functions as well.  I kind of suspect that there's a lot of checks in there that would also, better be placed in `printchplenv.py`.

* If I do `make clean` or `make clobber` my error in `printchplenv` gets triggered. Which makes me wonder if it's really necessary to invoke `printchplenv` in this case. If so (maybe what we clean is based on the configuration?), then could we avoid doing the validation step?

* This is really nit-picky, but hey I'll point it out: when we do `USR_FATAL` to print an error from the compiler it prints out "error: ..." with "error" in bold but when we use the `error()` function in `printchplenv` it prints it out "Error: ..." (upper case and non-bold).  Do we want a consistent style?

* The only thing that really bothers me about all this (that is assuming that we agree that it's a best practice to try and do as much validation in `printchplenv.py` as possible) is the discoverability of this.  I guess code review provides a check, but it makes me wonder if there's a smpler code change or strategically placed comment.  I've added a comment to `validateSettings()`. It'd be pretty easy to overlook but, hey, it's better than nothing.

**Comment by bradcray** [comment]
> Does our team consider it a best practice to try and do as much validation as possible in printchplenv.py?

I would say "yes" for the most part (in that all paths lead to it, as you note), with the slight downside that when errors occur, they often aren't displayed to the user very cleanly or clearly because they can happen deep within a build, or repeatedly.  But that's an area where we could arguably improve over time (?).

> I'm not sure if this was intentional or just a happy side effect.

I think intentional, though it took us awhile to get to this point.

> Which makes me wonder if it's really necessary to invoke printchplenv in this case. If so (maybe what we clean is based on the configuration?), then could we avoid doing the validation step?

IIRC, I think that `clean` only cleans the current configuration, not others.  I think `clobber` clobbers all (so probably does not need to validate).  There'a also a `cleanall` that should be less sensitive to the current configuration.  At the same time, is there a downside to validating the current environment in these cases?  (beyond wasted work and possibly issuing errors that won't matter to a user who's just trying to clean up?)

> The only thing that really bothers me about all this is the discoverability of this.

What do you mean by discoverability here?  Like testability, or ability to know we aren't backsliding when we change things?

**Comment by stonea** [comment]
> IIRC, I think that clean only cleans the current configuration, not others. I think clobber clobbers all (so probably does not need to validate). There'a also a cleanall that should be less sensitive to the current configuration. At the same time, is there a downside to validating the current environment in these cases? (beyond wasted work and possibly issuing errors that won't matter to a user who's just trying to clean up?)

Well, I think "wasted work" and "issuing errors that won't matter to a user who's just trying to clean up" are worthwhile issues to address in the own right. `make clean` is one of those commands like "force quit" that I expect to just work (without taking any time or issuing new error messages).

`make clean` is what I run when I'm building something and get confusing errors messages and just want to set things back to the "start" to do a fresh installation.  Arguably, in this case setting things back to the "start" would involve cleaning up `CHPL_` environmental variables as well (so validation would be helpful to the user). Also arguably `make clobber` or `make cleanall` would be the "right" thing to use but I wouldn't expect most new users to know about it.

Anyway, if the reality is that `make clean` is configuration-dependent then (putting my comment about wanting `make clean` to just work without issuing new errors messages aside) maybe the right thing to do would be to have `make clean` suggest `make clobber` or `make cleanall` when it errors. I know Chapel isn't the only package out there with a `make clobber` command but for better-or-worse I think a lot of users are assume that `make clean` means "cleanup everything" and not "clean up one particular configuration". So maybe it would be worthwhile having make clean (at the end) warn the user (when other configurations exist) that other configurations exist?

Anyway I don't feel strongly enough about it to want to tackle this right now, but do let me know if you disagree with my thought process and if its worthwhile enough to file a Github issue.

> What do you mean by discoverability here? Like testability, or ability to know we aren't backsliding when we change things?

I mean what can we do we ensure that (new and old) people know about this best practice? (To me) `driver.cpp` seems like the "obvious" place to put in new validation code and I see a lot of validation code already in there. So I think a lot of folks would just modify `driver.cpp` without realizing that `printchplenv` might be a better place to modify.

I ended up adding a comment to `validateSettings` in `driver.cpp`: https://github.com/chapel-lang/chapel/pull/18916/files#diff-ffe5ebc2db819ba98925774825649904b144fd964e3710504bcce6ac4d1a205bR1674

**Comment by bradcray** [comment]
> Well, I think "wasted work" and "issuing errors that won't matter to a user who's just trying to clean up" are worthwhile issues to address in the own right.

That's completely reasonable, I just wanted to make sure I wasn't missing something more fundamental that would go wrong.

> I think a lot of users assume that make clean means...

When we were implementing `clean` and `clobber` and friends, I thought we did some research and concluded that there wasn't a sufficiently standard practice that we should follow rather than doing what we wanted to do.  Not trying to say "what we've got is right/best", just indicating how we got here.

> if its worthwhile enough to file a Github issue.

I don't feel strongly either way about this.

> I mean what can we do we ensure that (new and old) people know about this best practice?

I see.  Like many things, it seems tough to know where to document it such that people will see it when they need to.  I.e., we could put it in a bestPractices somewhere, but I'm guessing nobody would read it until someone in the know caught them doing the wrong thing in a code review and pointed them to it.  So is that useful, or does it just become a tool for shaming?

I like the comment you added to driver.cpp.  If I were to refine it, I'd say that checks that are about the environment and standard chplconfig-style environment variables could/should be done in the chplenv scripts; but that those which rely on interactions with compiler flags ought to (need to, right?) be done here (because I don't think the chplenv scripts have any way of knowing about the flags passed to `chpl`?

Having said that, though, you've now got me trying to remember how/why the `--comm gasnet` case you mention above works, since that is obviously a command-line flag that happens to back one of our standard chplenv variables (where I don't think of most compiler flags as being in that same category...).  Checking, the secret sauce seems to be that the `setEnv` function that's registered for this class of compiler flags combined with the fact that their environment variable equivalent in the arg_desc array is the underscore-prefixed version of the real environment variable.  This led me to scratch my head about [the following](https://github.com/chapel-lang/chapel/pull/2919#issuecomment-1006222488), but now we're really getting further from the topic.

**Comment by stonea** [comment]
> I see. Like many things, it seems tough to know where to document it such that people will see it when they need to. I.e., we could put it in a bestPractices somewhere, but I'm guessing nobody would read it until someone in the know caught them doing the wrong thing in a code review and pointed them to it. So is that useful, or does it just become a tool for shaming?

To play "docs advocate" I will say I have found some of our bestpractices documents to be helpful and refer back to them from time to time.

Anyway, this (the general issue of how to best share knowledge, best practices, avoid knowledge silos, etc.) is one of those questions I've had since I started to working on software as part of a team. I'm sure it's one of those vague, philosophical, questions with no easy\real answer (beyond putting in effort to communicate, have meetings, perform code reviews, document, etc.) but it's always interested to hear others takes on it, especially for those few times when things can be improved be restructuring the code, adding automated checks, coming up with some clever process, etc.

> I like the comment you added to driver.cpp. If I were to refine it, I'd say that checks that are about the environment and standard chplconfig-style environment variables could/should be done in the chplenv scripts; but that those which rely on interactions with compiler flags ought to (need to, right?) be done here (because I don't think the chplenv scripts have any way of knowing about the flags passed to chpl?

I changed the comment to this; thanks for the feedback!:

```
// NOTE: Before adding something here consider whether you should instead add
// it to printchplenv.py (or one of its associated chplenv scripts).  If
// placed there then you'll get the check both at runtime (because we end up
// calling printchplenv) but also when building the Chapel compiler itself.
// Generally speaking, if the checks are about environment and standard
// chplconfig-style environment variables checks could/should be done in the
// chplenv scripts; otherwise put the checks here.
```

I've also created a Github issue about 'make clobber' running printChplEnv validation checks (here: https://github.com/chapel-lang/chapel/issues/18924). I think I won't worry about the issue with 'make clean' unless I get evidence that it actually ends up confusing \ bothering someone.

**Comment by bradcray** [comment]
> I have found some of our bestpractices documents to be helpful and refer back to them from time to time.

I completely agree with that, and don't mean to sound anti-docs.  I do think that there are things that are sufficiently esoteric that they could be documented yet nobody would ever read them or know to go looking for them or how to find them.  This case may not be one of those things, I'm not sure.  In any case, I wasn't trying to say "let's intentionally not document it"—particularly if you wanted to and thought it would add value—so much as questioning whether it would help people avoid the mistake.  Maybe put another way, if we do document it and someone put the check in driver.cpp rather than printchplenv.py, it wouldn't surprise me and I don't think anyone should hold it against them.
