### ISSUE TITLE
`make third-party` doesn't build jemalloc?

### ISSUE THREAD

**Issue by BryantLam** [chapel-lang/chapel#18929]
`chpl version 1.25.1`

`make -j1 third-party` does not build jemalloc and thus causes build errors when building qthread.

---

I'm working with someone that builds with `make third-party` before running `make` to build everything else. (Is this the intended use? ~Related XXXX~ https://github.com/chapel-lang/chapel/issues/18929#issuecomment-1007733192.) `make third-party` does not appear to build jemalloc. I'm fairly sure this is a bug in the Makefiles or configuration as we were able to reproduce this with two separate systems and three different build dependencies (gcc 10.1, 11.1, 11.2 and python 3.8.5 and 3.9.5).

Also tested by doing `cd third-party/jemalloc && make jemalloc` which resulted in doing nothing.

#### Setup
0. Clean environment. No relevant env vars.
1. Unpack v1.25.1 release archive `&& cd` into it
2. `source util/setchplenv.bash`
3. `export LLVM_CHPL=none` (also tested with `bundled`)

#### Terminal Output
```terminal
$ make -j1 third-party
Making the third-party libraries...
cd chpl-venv && make test-venv
...
cd chpl-venv && make chpldoc-venv
...
[snip]
...
cd libfabric && make
...
cd libunwind && make
...
cd qthread && make
...
In file included from <CHPL_HOME>/runtime//include/chpl-mem.h:66,
                 from <CHPL_HOME>/third-party/qthread/qthread-src/src/alloc/chapel.c:18:
<CHPL_HOME>/runtime//include/mem/jemalloc/chpl-mem-impl.h:27:10: fatal error: jemalloc/jemalloc.h: No such file or directory
...
compilation terminated.
make[5]: *** [alloc/chapel.lo] Error 1
make[4]: *** [all-recursive] Error 1
make[3]: *** [all-recursive] Error 1
make[2]: *** [qthread-build] Error 2
make[1]: *** [<CHPL_HOME>/third-party/qthread/install/linux64-x86_64-native-gnu-none-flat-jemalloc-bundled] Error 2
make: *** [third-party] Error 2
```

**Comment by ronawho** [comment]
I don't know how good a job we do about documenting what makefile targets are intended to be user-facing, but I don't really think `third-party` is one of them (and maybe we should just remove it). `make runtime`, which calls runtime/Makefile is the code that ensures third-party packages are built in the right order and only builds the third-party libraries that are required by the current configuration: https://github.com/chapel-lang/chapel/blob/5de3f3289b8981e4f62c7b57cfb0b71ed91718ed/runtime/Makefile#L71-L86

I'm pretty sure `make third-party` just attempts to build all third-parties even if they're not needed and it doesn't respect any other dependencies (like qthreads needing hwloc and jemalloc). I think it will build jemalloc, it's just not building it before qthreads when you do a parallel build, so the qthreads build fails (although I now see you're doing a `make -j1` and we list jemalloc before qthread in the third-party target, so I'm a bit surprised the order isn't right.)

If `make third-party` is an important target to you, we could duplicate the dependency logic there, but otherwise I'd be inclined to remove the target. Could you say more about your use-case here?

**Comment by bradcray** [comment]
I feel similarly to @ronawho.  Most specifically: (1) I don't think we expect users to make the `third-party` step manually / directly (and am not finding any indications of that in the documentation, but let me know if I missed something); (2) I never use that Makefile target myself, and would not miss it if it were suddenly gone.

**Comment by BryantLam** [comment]
I never use this Makefile target either and wanted to bring this up as a "why is this here if it doesn't work" notice. I'm okay now that I know to inform others to build with just `make`.

For "Related XXXX", I also noticed jemalloc wasn't being built in the same manner as `make compiler` passes `CHPL_MAKE_HOST_TARGET=--host` whereas `make third-party` doesn't. I was going to file another issue, but probably not worth it if `make third-party` isn't intended to be user-facing and may be removed.

https://github.com/chapel-lang/chapel/blob/305194695c4d0842c745457618cd84efb972b2ee/Makefile#L76-L80

**Comment by ronawho** [comment]
I opened #18949 to remove `make third-party`. Copying an excerpt there that may provide some additional info:

> You could imagine wanting this target when building a matrix or something to just build the third-party packages once ahead of everything else, but that's not really how our build system works. We might build jemalloc multiple times for the host and target, qthreads with different schedulers depending on locale model, or gasnet for different conduits/substrates. The way we do this for our own module builds is to build the compiler once, and then for each target in our matrix use `make notcompiler` to build runtime/third-party/whatever for each aspect of the matrix. We rely on our build infrastructure to only rebuild when the unique install paths change (i.e. gasnet has a unique install path for different conduits/substrates, and qthreads for locale models.) This ensures we don't needlessly rebuild the third-party packages, just when the configuration may require different build steps.

And as a historical note, in our matrix builds for XC/EX modules we used to just call `make`, but we switched to `make notcompiler` in https://github.com/chapel-lang/chapel/pull/12116 to avoid rebuilding parts of the compiler (I think something weird with the version file) when varying runtime components.
