### ISSUE TITLE
`DateTime` module stabilization - time zones

### ISSUE THREAD

**Issue by aconsroe-hpe** [chapel-lang/chapel#18941]
As part of the module review for `DateTime`, we identified some issues with timezones.

Modeled after the Python `datetime` time zone information, the current `class TZInfo` is an abstract base class and must be subclassed with a concrete implementation per time zone. This prevents users from easily updating the time zones that would hypothetically be distributed with Chapel in the future. (Note that currently there are no concrete subclasses in the standard modules.) Timezones do change and is common to get these from the system like `tzdata`, which would fit better with a single class where each timezone was an instance.

In addition, we currently have multiple `halt`s in operations on two `datetime`s like `operator <` because comparing one with a timezone and one without is non-sensical, but is not caught at compile time. See #9941

Our conclusion from earlier discussions was: let's not worry about implementing everything about time zones today, but let's make sure we leave the door open to implement them well in the future.

Inspired by a conversation with @bradcray, the below sketches a nice way to have `record time` be generic over whether it has a timezone without resorting to something like `naiveTime` or the like present in other libraries to differentiate.

```chapel
/* hypothetical future implementation of timezone */
record timezone {
  var id:string;
  var dst:int;
  var offset:int;
}

record time {
  type tzType = nothing;
  var hours:int;
  var minutes:int;
  var tz:tzType;

  proc init(hours:int, minutes:int) {
    this.hours = hours;
    this.minutes = minutes;
  }

  /* I would expect us not to implement this today, but is how we would add them in the future */
  proc init(hours:int, minutes:int, tz:timezone) {
    this.tzType = timezone;
    this.hours = hours;
    this.minutes = minutes;
    this.tz = tz;
  }
}

operator time.<(t1:time(?tz), t2:time(tz)): bool {
  if t1.hours < t2.hours then return true;
  if t1.hours == t2.hours then return t1.minutes < t2.minutes;
  return false;
}

var utc = new timezone("utc", 0, 0);

var t1 = new time(10, 30);
var t2 = new time(11, 30);
var t3 = new time(10, 30, utc);
var t4 = new time(11, 30, utc);

writeln(t1 < t2);
writeln(t3 < t4);
writeln(t3.tz.id);
/* This is a compile error! */
/* writeln(t1 < t4); */
```

This looks nice to me, but raises issues in how to `deprecate` the old `DateTime.time` record because it has:
```chapel
proc time.init(hour=0, minute=0, second=0, microsecond=0, in tzinfo: shared TZInfo? = nil) { /*...*/ }
```

where you might be able to deprecate this `init` and forward it appropriately, but without going through the whole excercise, its not clear this is viable.

**Comment by bradcray** [comment]
>where you might be able to deprecate this init and forward it appropriately

Andrew — Is your concern here that the optional argument will cause an ambiguity with the new overloads?  FWIW, I don't think that it's necessary to preserve precisely a given set of routines during a deprecation period as long as you don't break callsites.  So, for example, given a routine:

```chapel
proc foo(x: int = 0) { ... }
```

I think it would be fine for a release to switch to:

```chapel
proc foo(x: int) { ...}

proc foo() { ...}
```

without any deprecation warning since a user's code calling the old routine would still work without them being any the wiser.  Can we do a similar thing here?  Or am I mis-guessing at your concern?

**Comment by aconsroe-hpe** [comment]
Currently, if you add
```chapel
  proc init(hours:int, minutes:int, in tz:shared TZInfo? = nil) {
    this.tzType = shared TZInfo?;
    this.hours = hours;
    this.minutes = minutes;
    this.tz = tz;
  }
```

```
test/datetime-tz.chpl:50: error: ambiguous call 'time.init(10, 30)'
test/datetime-tz.chpl:20: note: candidates are: time.init(hours: int, minutes: int)
test/datetime-tz.chpl:33: note:                 time.init(hours: int, minutes: int, in tz: shared TZInfo? = nil)
```
It is ambiguous, but since `tz` gets defaulted, shouldn't break users. But, then the user can't change their code today (b/c there is no correct-in-the-future init alternative to use) to fix the future breaking change!

I had another concrete concern but it has escaped me for the moment

**Comment by lydia-duncan** [comment]
You can mark the initializer you don't want them to use with `pragma "last resort"`.  But isn't the `(hours:int, minutes:int, in tz:shared TZInfo? = nil)` version a valid replacement for the one with only hours and minutes?

**Comment by lydia-duncan** [comment]
The new initializer is still accomplishing what the old one was, it's just now doing additional things under the covers, right?

**Comment by aconsroe-hpe** [comment]
If we make `proc init(int, int)` last resort, then this current code will continue working as expected:

```chapel
writeln(new time(10, 30) < new time(11, 30, getTimeZoneOrNil()));
```
but then the user has no way of opting in to use a statically known timezone

If we make `proc init(hours:int, minutes:int, in tz:shared TZInfo? = nil)` last resort, then the above code will break as we'll get a type error (the LHS now has type `time(nothing)`).

I'm going to pause on figuring out exactly how to do this and see if there is more support or opposition of changing `time` to have a static type just to make sure our efforts are not in vein.

**Comment by aconsroe-hpe** [comment]
As the author of #9941, I'm curious where @ronawho stands on this issue today. I think the proposed mechanism satisfies the original desire to remove the halts (and `try!` usage if they were throwing).

**Comment by ronawho** [comment]
I'm in favor of timezone being part of the type and removing the halts. I didn't read the discussion of how to deprecate the old approach in any detail so no comments there, but I'm in favor of this general direction.

**Comment by aconsroe-hpe** [comment]
I thought I had a good idea for this, but ran into some snags. This diff shows what I thought we could do:

```diff
diff --git a/modules/standard/DateTime.chpl b/modules/standard/DateTime.chpl
index 18ade188c4..27d98094b5 100644
--- a/modules/standard/DateTime.chpl
+++ b/modules/standard/DateTime.chpl
@@ -510,13 +510,17 @@ module DateTime {
     return d1.toordinal() >= d2.toordinal();
   }
 
+  config param oldTzType = true;
+
+  type oldTime = time(shared TZInfo?);
 
   /* A record representing a time */
   record time {
+    type tzType = if oldTzType then shared TZInfo? else nothing;
     pragma "no doc"
     var chpl_hour, chpl_minute, chpl_second, chpl_microsecond: int;
     pragma "no doc"
-    var chpl_tzinfo: shared TZInfo?;
+    var chpl_tzinfo: tzType;
 
     /* The hour represented by this `time` value */
     proc hour {
```

This is similar in spirit to refactoring a function from `f() { ... + 10;}` to `f(x=10) { ... + x;)` and then `f(x=if old then 10 else 20) { ... + x}` just at the type level instead, which I thought was a nice use of Chapel. We could still expose a type alias `oldType` that unconditionally retains the old type.

The issue arrises because the generic type formal (even with a default) puts itself (and so overloads look for it) at the front of the argument list to `init`. I was trying to figure out how to write something like `init(hour=0, minute=0, tzinfo=nil) where tzType == shared TZInfo?`. WIP but maybe this is workable?

**Comment by bradcray** [comment]
> The issue arrises because the generic type formal (even with a default) puts itself (and so overloads look for it) at the front of the argument list to init. 

@aconsroe-hpe : I'm not positive I'm following (haven't spent much time on this), but with a quick read:  would changing `tzType` from a `type` field to a `proc` that returns `type` address the problem you've hit?  (ultimately, `private type` ought to as well, but we don't have private fields yet... :'( ).

**Comment by bradcray** [comment]
> I was fixated on having it be part of the record

I was imagining it still being part of the record as a type method (rather than standalone outside of the record).  That should give you the per-record capability without making the record generic on a new field.

**Comment by aconsroe-hpe** [comment]
> > I was fixated on having it be part of the record
> 
> I was imagining it still being part of the record as a type method (rather than standalone outside of the record). That should give you the per-record capability without making the record generic on a new field.

I'm not understanding what you mean, could you sketch some code?

I tried moving tzType out (which may or may not line up with what you actually intended). After working around a compiler bug, I'm [here](https://github.com/chapel-lang/chapel/compare/main...aconsroe-hpe:sketch/datetime-transition?expand=1). I didn't work through all the changes, but you get the sense. Feels like a lot of duplication but I'm running out of ideas to do this in a backwards compatible way.

**Comment by bradcray** [comment]
Where you had:

```chapel
record time {
   type tzType = if oldTzType then shared TZInfo? else nothing;
  ...
}
```

I was imagining:

```chapel
record time {
  proc tzType type {  // or `tzType()` if you prefer
    return if oldTzType then TZinfo? else nothing;
  }
}
```

and wondering whether that would help.  I'm admittedly not following the challenges you're hitting at a deep level, but it seemed like it would avoid making `time` into a generic record based on the lack of a `type` field while keeping the behavior focused on the record.  That said, in typing this up, I realize I must be missing something else since I don't think this conditional makes use of the per-record state or information in any way.  So what did I miss?

**Comment by aconsroe-hpe** [comment]
Let me try to backup a bit: I'm trying to find a way to remove `chpl_tzinfo` from `record time` (and thus `record datetime`) in a nice backwards compatible way. That means

1) User's code that uses tzinfo today -- like `new time(tzinfo=mytz)` -- shouldn't break
2) Users should be able to make some change to their code that will bring their code from deprecated to non-deprecated
3) Users should be able to switch to an alternative that supports `tzinfo`

Goal 2 is met if we remove all traces of tzinfo (and `class TZInfo`) and users remove any use of it, but then they would have to switch to another library altogether that did handle timezones.

The approach I've been pursuing, where we phase out the type of `chpl_tzinfo`, was supposed to let a user keep using the old timezones by supplying their own type for `chpl_tzinfo` since `record time` is generic over `tzType`. This could be a `shared TZInfo?` which keeps the current behavior as it is, or they could switch to a `tzType` like `record myOwnTimezone` which is a non-nilable and gives them more static typing.

Perhaps a better way forward is to either
  * Break our promise on goal 3) by just deprecating the init with tzinfo
  * Implement the strongly typed version of `timeWithTimezone` to meet goal 3)
    * This is slightly different than my current approach which is: remove the tzinfo by making its type `nothing` and leave the rest as future work

**Comment by lydia-duncan** [comment]
I don't love the idea of `_time` being user-facing - it seems like you've altered most of the methods to be defined on that type (which I think you had to do because otherwise you were defining them on an instantiation of `_time` only, right?) and that will make it so that the name that turns up in the documentation.

I think earlier I was having a hard time trying to understand your goals.  Is it correct to say:
- we don't like the current support for timezones
- we don't have a replacement for the current support yet
- but we still want users to know their strategy for handling timezones may change in the future
- this affects the implementation of things like comparison operators, but only impacts the visible arguments of one initializer: `proc time.init(hour=0, minute=0, second=0, microsecond=0, in tzinfo: shared TZInfo? = nil)` currently.
- However, in order to make it possible to switch between the old timezone type and a potential new one in the future, we want to add a type field

If so, I think we want that initializer that uses the timezone to be unstable rather than deprecated, but only in the case where the user is trying to explicitly set that argument.  I think we can accomplish that by copying the initializer where one version (the unstable version) has the `tzinfo` argument but *doesn't give it a default value* and the other version has every other argument.  E.g.
```chapel
proc time.init(hour=0, minute=0, second=0, microsecond=0, in tzinfo: shared TZInfo?) { ... } // The unstable version
proc time.init(hour=0, minute=0, second=0, microsecond=0) { ... } // The version that will stay
```
These two initializers will not conflict (because you can't call the unstable version without providing the tzinfo argument).  The user won't have anything to replace their call with, but that's okay - they're now aware that the timezone information may change in the future, but without an explicit replacement, there's nothing to do about it just yet and they can continue to use it.  I'm not familiar with how to note something is unstable, but it looks like you can follow the example [in the gpu LocaleModel code](https://github.com/chapel-lang/chapel/blob/7367f0e813d8e7f68d1e3af9d19044c8f7def788/modules/internal/localeModels/gpu/LocaleModel.chpl#L32) and add a check for the flag to print out a compiler warning for now (and you'll probably want to indicate it in the documentation).

You can explicitly set the new type field in the body of the initializers - so if a user calls the unstable version, it will set the type to `shared TZInfo?` and if the user calls the other version, it will set the type to `nothing`.  This means that you don't have to include the type as an argument to the initializer, you can just set it in the body and the user can be none the wiser unless they print out their type as a string or try to store two different instantiations in an array.  You'll need to set that field in every initializer for the type, but that shouldn't be too difficult.  Here's a little code snippet demonstrating that you don't need it as an argument:
```chapel
class Bar {
  type t;
  var x: t;

  proc init(x: int) {
    t = int;
    this.x = x;
  }

  proc init(x: bool) {
    t = bool;
    this.x = x;
  }
}

proc main() {
  var b1 = new Bar(3);
  var b2 = new Bar(false);
  writeln(b1); // prints `{x = 3}`
  writeln(b2); // prints `{x = false}`
}
```

Does that simplify things?  Or are there problems that I've missed that make this infeasible?

**Comment by aconsroe-hpe** [comment]
> I don't love the idea of _time being user-facing

Me neither, and at first I was just going to chalk that up to "I wasn't intending it to be user-facing, it was just a sketch". Though, as you point out, I see now that it would show up in the documentation! I suppose I was thinking that `_time` would be `private` and that the type aliases would be public and that (here's where I went wrong), each of those type aliases would get rendered with all of their methods in the docs. (See [1] below for an extending rambling on this)

> I think earlier I was having a hard time trying to understand your goals. Is it correct to say:

Agreed on all points with the clarification that

> However, in order to make it possible to switch between the old timezone type and a potential new one in the future, we want to add a type field

We don't have to be tied to this solution, its just the one I've been pursuing.

I'm certainly curious about unstable vs deprecated because one hangup I've had -- and what leads to most of the complexity -- is that I was trying to deprecate something and provide the user with an upgrade path, but not explicitly give them an upgrade path. So perhaps the unstable "flag" makes more sense here. I just don't feel great about deprecating something without already having the replacement ready to go.

> ... so if a user calls the unstable version, it will set the type to shared TZInfo?

I think that if we go with the unstable route, I'm not sure we should make `time` generic, specifically to avoid:

> ... or try to store two different instantiations in an array

If an existing program works today with mixed uses of naive & aware `time`, I think we'd want it to keep working if its only marked unstable.

I like this direction though and will work on a new draft, thanks Lydia!

<details>

<summary>[1]</summary>

I was thinking it might be cool to have something like

```chapel
private record _Foo 
  param flag: bool;
  proc f1() where flag {}
  proc f2() {}
}

pragma "expand in the docs"
type FooWithTheThing = _Foo(true);
pragma "expand in the docs"
type Foo = _Foo(false);
```

And then in the docs, it would param fold everything and then show each type alias as if they were a record, like
```rst
.. record:: FooWithTheThing
   .. method:: f1
   .. method:: f2

.. record:: Foo
   .. method:: f2
```

This aims to get the best of both worlds, where the implementation might be easier to reason about as a single generic record with various types or params to configure it, but the docs would be clearest to show as if they were separately implemented.
</details>

**Comment by aconsroe-hpe** [comment]
I tried exploring this idea in https://github.com/chapel-lang/chapel/compare/main...aconsroe-hpe:datetime-unstable?expand=1 -- How does that compare to what you had in mind?

You'll notice there are a few more places than just `init` that end up possibly using a tzinfo (either the `tzinfo` field or one passed as an argument).

Also, I think my use of `compilerWarning` inside the conditional is probably wrong, but I was perhaps hoping to avoid duplicating each method into one from: 

```chapel
proc foo(in tz: shared TZInfo? = nil)
// becomes
proc foo() // no warning
proc foo(in tz: shared TZInfo?) // warning
```

**Comment by lydia-duncan** [comment]
Yeah, that looks great!  There's a couple of things I noticed that I would call out in a review (there's a stray extra comment, and I think some wording got duplicated but not adjusted for the new place it was applied), but that looks tractable and like the direction I was thinking.  Good catch on the additional places that would be impacted!

**Comment by riftEmber** [comment]
Never mind, I incorrectly thought that https://github.com/Cray/chapel-private/issues/3566 had completed the suggestion, but I'm unable to tell what happened in this issue. I see in the `Time` module today we still have the runtime `timezone` checks on `dateTime` comparisons, so this must not be done.

We do have `init`s that take `Timezone`s as unstable, with separate `init`s that don't take them. We don't have timezone awareness/naivety as a part of the `time` record type as far as I can tell.

**Comment by riftEmber** [comment]
In the Time final review https://github.com/Cray/chapel-private/issues/5170 it was decided to make timezone awareness part of the type of a `time`/`dateTime` (that is, implement https://github.com/chapel-lang/chapel/issues/9941) for 2.0. We also reconfirmed we won't be adding any concrete `Timezone`s to the standard modules for 2.0; I have created issue https://github.com/chapel-lang/chapel/issues/23047 to track the desire to do this post-2.0.

I think this issue is a bit stale in light of the `Time` revamping that has taken place since it was created, as well as the fact that the main discussion on it concerns an abandoned work-in-progress implementation of https://github.com/chapel-lang/chapel/issues/9941 (which I've started a fresh implementation of at https://github.com/chapel-lang/chapel/pull/23010). All 2.0-relevant contents of this issue are supplanted by https://github.com/Cray/chapel-private/issues/5170, and the post-2.0 contents are in https://github.com/chapel-lang/chapel/issues/23047, so I am going ahead and closing it.

As far as I can tell, the only implementation work completed for this issue was unstable-izing uses of `Timezone`s, via unstable `Timezone`-using overloads of many methods.
