### ISSUE TITLE
Should 'max(type t)' be renamed?

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#18952]
Something @damianmoz said on another issue this year has stuck with me which is that today
we have `max(x, y)` which returns the maximum of two values as well as `max(type t)` which
returns the maximum value representable by type `t` which seems confusing and a bit vague.
In this issue, I'm asking whether we should deprecate/rename `max(type t)` to avoid this
where alternatives might include:

* `maxval(type t)`
* `maxVal(type t)`
* `(type t).max` (a type method)
* ...your idea here...

(note that we'd want to do the same for min)

**Comment by damianmoz** [comment]
I was deliberately addressing the problems of the words **max** and **min** with regard to operators.

I used **maxval** and **minval** having a type as argument to match the current Chapel usage. And with these words already in common usage in another language, albeit not a massively popular one, I was proposing something that had gone through a standardization process, i.e. I was not proposing something radical.

As soon as you get into the attribute of a type, you open up a discussion on the Chapel whole floating point model. Do you really want to go there? And if so, do you want to talk about a maximum and minimum of its floating point number, are you talking in terms of its arithmetic value or the value of the exponent of the floating point radix, the latter of which corresponds to its absolute value.

**Comment by mstrout** [comment]
I like `maxval`.

**Comment by lydia-duncan** [comment]
I feel similarly to Engin about `max(int)` - it seems like a natural way to support getting the maximum of an integer and I don't really feel like it conflicts with `max(x, y)`, at least for me.  I also agree with `maxval` not really solving the problem (and additionally, I think it should be camelCased if we do use it, i.e. `maxVal`) and like `maxOf`/`minOf`, despite those terms potentially being a divergence from other precedence.

**Comment by damianmoz** [comment]
The bigger context is #7629 which has been hanging around for years and has seen some renewed attention, or more precisely, become more important, over the New Year break. Maybe we should have referenced that earlier.

At the risk of being esoteric ....

If you refer back to the original issue which is all about using **max** and **min** as operators, then I believe that this means that those two identifiers become reserved words to the compiler and one cannot simply do `max(int)` any more. That said, I believe that this does not preclude both **max** and **min** from being used as method names. Have I got that right @bradcray?

And in the spirit of using what another language has done to avoid conflict, I stole the idea of `maxval` and `minval` from PL/1 because those names gone through a standardization/discussion process in a language. Besides, no other language uses `minOf` or `maxOf`. Chapel already has the similarly stolen `isinf(x)` and `isnan(x)` which are not camel-cased so why is it important here? Adhering to camel-casing rules does bad things to the meaning. In the case in point, using `maxVal` and `minVal` overly emphasises the **Val**(ue) part of the name, at the expense of a potentially equal emphasis being needed on the first three letters.

Of course, you can easily avoid the need for **max** and **min** to be reserved words by adding two new operators. But then, how do you handle:
```chapel
const x = a max b;
...
t min= z;
```
Once you use new operators, the clarity of expression may suffer and it may introduce a whole new point of contention.

And again in the context of a **real**_(w)_ type, where in usage, the concepts of some maximum and minimum attribute of a floating point number (or type)  have often been used with an implied appended magnitude, what maximum and minimum is of concern?  Is it the maximum finite value, maximum normal value, maximum safe value, exact power of the radix, and so on. In such contexts, the minimum and maximum are again being used as qualifiers or subscripts to the attribute in question? I am deliberately mis-using the words to imply magnitude (as has been done historically) when I probably should be using words like **largest** and **smallest**. That historical implied use of magnitude use of the sense of a maximum and minimum is used to mirror the fact that say the attribute with `...max...` in the name will correspond tightly (or loosely) to when the maximum exponent is part of the calculation, and similarly with the minimum exponent.

But elaborating on that last paragraph belongs in another issue. The important thing for this issues is that whatever is decided here does not box us into a corner when it comes to addressing floating point numbers and their attributes.

**Comment by bradcray** [comment]
> If you refer back to the original issue which is all about using max and min as operators

This isn't quite right...  The _original_ issue (and my recent renewed interest in it) was about `max=` and `min=` being operators without extending the same courtesy to `max` and `min` without the `=` operator.

To be clear, if there's no appetite for renaming `max(type t)` and `min(type t)` as things stand today (which is to say, where `max` and `min` are not reserved), that's absolutely fine with me and we could close this issue.  Put another way, if Engin's view and reaction was the dominant one, then we probably should just stay where we are.  I've always felt slightly nervous about having such different overloads of `max()` for values vs. types, and seeing [Damian's comment about `maxval()` and `minval()`](https://github.com/chapel-lang/chapel/issues/7629#issuecomment-1003042208) on #7629 sparked that nervousness for me and suggested a potential fix, which led me to file this issue while doing some housecleaning this weekend.

> I believe that this means that those two identifiers become reserved words to the compiler and one cannot simply do max(int) any more. That said, I believe that this does not preclude both max and min from being used as method names. Have I got that right @bradcray?

If we went that route, you're essentially correct (we could _potentially_ special-case certain procedural forms, but I'd prefer not to).  I'm not aware of anyone advocating for reserving `max` and `min`, though (I don't even think you were on that issue, were you?  I haven't re-read the whole thing lately).

**Comment by damianmoz** [comment]
Silly me. I reread that 2017 posting and I indeed misread things. But having **max=** an operator but not **max** is not orthogonal. I do not like non-orthogonality. If I had been more observant, we probably could have solved that ages ago.

Also, I also do not like special cases. So that scares me.

I would say either close this issue and #7629, or ...

Introduce new operators to do the task. That way, you are not changing anything and any cause of conflict with current practice disappears.

But new operators means you are adding a new feature. Is it much work? Not much. What symbols are used? See #7629. Is it clean? Yes. Is it clear? Well, that's another discussion. Is it needed?????

I wish I was Solomon. But he was lucky. Information technology meant something different in his day.

**Comment by mppf** [comment]
FWIW I like the strategy of getting the maximum/minimum integer with `int.max`/ `int.min` or `int.largest` / `int.smallest` (and for all of the int/uint sizes) and it would be fine with me if we didn't add corresponding methods for `real`, `imag`, or `complex`, where the situation is more complicated (as @damianmoz has been saying, there are different kinds of numbers one might be looking for with floating point numbers - one would want different sorts of "property" type methods).

I'm interpreting the above discussion as a bit of a side issue but if it's not - I'm not following why changing `max(type t)` to something else (or keeping it) would impact `max=` and `max` on values in any way.

**Comment by lydia-duncan** [comment]
> Chapel already has the similarly stolen `isinf(x)` and `isnan(x)` which are not camel-cased so why is it important here?

Those names haven't been reviewed from a Chapel 2.0 perspective - we actually have a meeting scheduled to talk about the Math module today, so it's entirely possible they will get renamed

**Comment by damianmoz** [comment]
My apologies for introducing that side-issue. Given that the idea of **max=** and **min=** looks like it might die, we probably should discuss those names in a separate issue.

**Comment by bradcray** [comment]
> My apologies for introducing that side-issue.

I've hidden those responses to simplify the conversational log here (and these ones as well).

> Given that the idea of max= and min= looks like it might die, we probably should discuss those names in a separate issue.

I don't see their death as a foregone conclusion.  In any event, isn't #7629 already the separate issue?

**Comment by bradcray** [comment]
I feel as though this issue didn't garner a lot of support and that most who spoke up seemed to prefer the status quo, so I'm going to close this for the time being, though we could resurrect it in the future if it became a thorn in someone's side.
