### ISSUE TITLE
Math module: should we split it in two, one of which is not included by default?  If so, what names should be used?

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#18989]
Some of the symbols in the current Math module are a little niche, and some of them can cause problems with common experimental names (like `e`, see #13041) due to the module being included by default.

This issue proposes splitting the Math module into two modules, one of which will continue to be used by default and one of which will need to be used or imported by a user.  Should we follow this course of action?

If so, what names should we use for these two modules?  One proposal was to name the auto-included module `AutoMath` or `StdMath` and keep `Math` as the name of the module that is not included by default.

**Comment by lydia-duncan** [comment]
Vote here for if we should split the module into these two replacement modules

**Comment by lydia-duncan** [comment]
Vote here for new names

🚀 - AutoMath for auto included, Math for not included by default
👀 - StdMath for auto included, Math for not included by default
🎉 - Math for auto included, StdMath for not included by default
comment other suggestions and I'll update this comment

**Comment by bradcray** [comment]
Can you remind us:  What is the auto-included IO module named today?  `ChapelIO`?  (checking, I think "yes").  This comment is here mostly to say (1) it'd be cool if—for flavors like IO and Math that might have two versions in this way—we named them consistently, and (2) I don't like `Chapel` as the prefix for it.

`Auto` seems clear and self-descriptive to me, which is why I voted :rocket: of the three options above.  That said, I could also imagine some other prefix we haven't come up with yet.  I'm not crazy about `Std` as the prefix because it seems odd/redundant/potentially confusing to me to say "the standard module St[andar]dMath".

**Comment by ben-albrecht** [comment]
> Can you remind us: What is the auto-included IO module named today?

Other [auto-included modules](https://chapel-lang.org/docs/master/modules/standard.html#automatic-modules) are:

- Chapel Environment Variables (`ChapelEnv`, to be renamed though)
- Errors
- IO Support (`ChapelIO`)
- Math
- Types
- VectorizingIterator

I like the idea of these all using a common prefix, but only if we apply that prefix to all of them.

I'd also be OK keeping Math as Math, and separating any niche functions out into new appropriately named modules, where I think something like a SpecialFunctions library similar to Python and Julia would account for most of these.

**Comment by bradcray** [comment]
> I like the idea of these all using a common prefix, but only if we apply that prefix to all of them.

In case it wasn't clear, I'm only proposing the prefix for topic areas whose capabilities are split into auto- and non-auto categories like IO and Math (and, given your list, I think those are currently the only two).  I.e., I wouldn't make a module with a clear/precise name like 'Errors' become 'AutoErrors' just because it's automatically included.  While it permits one to know whether a module is auto-included from its name, I'd just as soon rely on the documentation for that so that if I want to write a fully qualified `Errors.identifier` expression in my code, I can use the cleaner name.  (Similarly if all of IO and Math continued to be used by default, I'd simply call them IO and Math).
