### ISSUE TITLE
chpldoc: why do numbers get truncated?

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#18992]
### Summary of Problem

The documentation for [e](https://chapel-lang.org/docs/1.25/modules/standard/Math.html#Math.e) and [pi](https://chapel-lang.org/docs/1.25/modules/standard/Math.html#Math.pi) in the Math module, for instance, only displays 5 decimal places when the module declares them with ~20 decimal places.  This seems wrong, and maybe like something that should be controllable by an attribute?

It doesn't look like the Math module is one of the ones we adjust the generated documentation for, so this is likely a general issue.

### Steps to Reproduce

**Source Code:**

```chapel
param e = 2.7182818284590452354;
```

**Compile command:**
`chpldoc foo.chpl`

**Associated Future Test(s):**
[`test/chpldoc/globals/realLength.doc.chpl`](https://github.com/chapel-lang/chapel/blob/main/test/chpldoc/globals/realLength.doc.chpl) #19085

### Configuration Information

- Output of `chpl --version`: 1.26.0 (pre-release)

**Comment by bradcray** [comment]
My guess:  Nobody's intentionally doing any truncation in our chpldoc + sphinx code path, but something along the way default prints to using this many digits if you don't say otherwise, similar to C's "%f":  https://tio.run/##S9ZNT07@/185My85pzQlVcGmuCQlM18vw44rM69EITcxM09DU6GaS0GhoAgokKahpJqmpKNgpGduaGFkAcImppYGJqZGxqYmmtZctf//AwA
