### ISSUE TITLE
Math module: if we split the module, what symbols should still be auto included?

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#18990]
This issue is for voting on proposals for how to divide the module as proposed in #18989.  If we don't follow that proposal, this one will be closed (but it seemed like people were leaning that way when it was initially proposed).

There were a few suggestions for how to divide the public symbols in the Math module.  Each suggestion will be in a comment and interested parties should feel free to vote on individual proposals, rank them, or propose new divisions.

**Comment by lydia-duncan** [comment]
My initial proposal:

Symbols that should be available by default
================================
- abs
- ceil, floor, though I am also open to having them in the other category.
  - I think divceil, divceilpos, divfloor and divfloorpos should go wherever it does.
- INFINITY
- isfinite, isinf, isnan
- log, log10, log2
  - Could also see the argument that `log` could be confused with a logger.
- max, min
- mod (though maybe the % operator is sufficient?)
- NAN
- round
- sgn, signbit?
- sqrt
- trunc
- gcd
- isclose

Symbols that maybe shouldn't be available by default?
=======================================
- Things like e, pi, log2_e, etc.
- carg 
- acos, acosh, asin, asinh, atan, atan2, etc
- cbrt (cube root)
- conjg
- cproj
- erf, erfc
- exp, exp2, expm1
- ldexp (multiples first arg by 2**second arg)
- lgamma, tgamma
- log1p?  logBasePow2?
  - Could also see them being grouped with the other logs
- nearbyint, rint
- j0, j1, jn, y0, y1, yn

**Comment by bradcray** [comment]
Things I would feel most regretful about having to use a library to get access to, in approximately sorted order:

* max, min
* abs
* INFINITY (though probably spelled/formatted differently?)
* NAN
* isinf(), isnan() (and maybe by extension, isfinite, though I'm not as familiar with that one... is it just !the other two?)
* log2(), log10() (and maybe by extension, log())
* mod, because it seems asymmetrical to support /, % by default, but not mod?
* sqrt

These ones are on the fence for me.  They don't quite feel like "Math", and the ones I use feel slightly annoying not to simply have available.  OTOH, I think I often use math-y tricks to get many of these rather than calling the routines. 
* ceil, floor, though I am also open to having them in the other category.
  I think divceil, divceilpos, divfloor and divfloorpos should go wherever it does.
* round
* trunc
* isclose


I wouldn't fight for these:
* sgn, signbit?
* gcd

There's not a lot on Lydia's "kick out" list that I'd fight for.  A part of me thinks "Aww, not pi?  Not sin() / cos()?" because they seem "more common" and unlikely to cause confusion.  But it's a slippery slope and I'm not sure where I'd draw the line.

As mentioned in chat, when reviewing these symbols, they don't all feel exactly like "Math" to me.  Some are more like "floating point representations", e.g.

> Could also see the argument that log could be confused with a logger.

I don't really buy this even though this is the one of the three logs that I'd kick out of the auto-included list first.  What logger interface would publish a standalone function that just takes a numeric value?  And making Math-y `log()` available doesn't preclude some other function from providing its own log methods (which seems like the most likely case for a Logger module) or taking a different signature or both.

**Comment by bradcray** [comment]
Michael, when you say:

> I consider log

does this apply to all 3 log functions, or just the log_e/ln flavor?

**Comment by mppf** [comment]
Yes, all 3, FWIW.

**Comment by damianmoz** [comment]
I will address some of the explicit issues after my preamble. But before that, how many people have read the 1985, 2008 and 2019 IEEE754 standards, the related IEEE854 standard integrated into the 2008 IEEE 754, and even some of the supporting documents.

On your ideas for which elementary functions to include by default. There is precedence (which I may or may not agree with) that you do **not** include any math routines in what is included by default. My 2c would want just:
```chapel
use m;
```
That would also solve that *@#!& problem with the constant that evaluates to `exp(1.0)` which would now be
```chapel
m.e
```
However, I am not a big fan of doing that across the board because the are things like operators and rounding modes which are implement as routines within the Math module.

I suggest we look at the various IEEE 754 standards. There was not even a rigorous list of recommend function in the body of the first 1985 release. An Appendix called _Recommended Functions and Predicates` with the following words under the title heading.
```
This Appendix is not a part of ANSI/IEEE Std 754–1985, IEEE Standard for Binary Floating-Point Arithmetic.
```
We need to make available by default only that functionality mandated (or recommended) operators within the main body of IEEE 754. Some of these are even explicit **operators** while others are the modes used in rounding operations. The fact that we do not define or implement them as Chapel operators but provide the functionality in a routine is irrelevant. There is always the argument that more things should be implemented as operators but that it another issue.

However, at most I suggest you include the following functions and constants which **appear** in the body of the 1985 standard:

- `sqrt(x)` because it is a mandated IEEE754 mathematical operation as important as add, subtract, divide, multiply and remainder so you do not even get to sit on the fence; and
- `INFINITY` or `inf` or whatever you want to call it but with its type corrected (for all time), i.e. it should be the smallest floating point supported  by the compiler.

The list of what we should keep in the 
We need to keep the following because they are mostly mandated (or recommended) operators and are part of the main body of IEEE 754 standard since 1985. The fact that we do not define them as Chapel operators but implement the functionality in a routine is irrelevant.

For all intents and purposes, that only leaves the following functions in that Appendix:

-  `scalbn(x, N)` and `logb(x)` which have been overtaken by subsequent events, and
- `nextafter(x, y)`, `copysign(x, y` and `class(x)`, the last of which obviously needs another name..

Both those points need more thought in a separate issues and I have addressed both of these in a new **ieee754** module which like **m**, also demands explicit inclusion. Do discussions about that belong on Github or on Discourse?

On those predicates in the standard, I will shortly document an issue to include all of the predicates with a view to implementing them in the compiler myself but that is outside the scope of this issue and may be outside the scope of my skill set - we will see.

The list of what we should keep in the 
We need to keep the following because they are mostly mandated (or recommended) operators and are part of the main body of IEEE 754 standard since 1985. The fact that we do not define them as Chapel operators but implement the functionality in a routine is irrelevant.

- `sqrt(x)` because it is a mandated IEEE754 mathematical operation as important as add, subtract, divide, multiply and remainder so you do not even get to sit on the fence; and
- `abs` is a monadic (unary) arithmetic operator as defined by the standard like negation;
- `conjg` is effectively a monadic (unary) arithmetic operator so it should be kept;
- **mod** and **rem** are dyadic arithmetic operators defined at the same time as add, subtract, multiple, and divide;
- `sqrt` - see above;
- `max` and `min` - these apply equally to other types so should not belong in a floating point math library even if we make them obey the rules of the IEEE 754 floating point standard  operators) including how they are interpreted if their arguments are unordered, i.e. either is a _NaN_
- `INFINITY` - see above (even if I do prefer `inf`);
- `ceil` and `floor` and `round` and `trunc` and `rint` and `nearbyint` are rounding modes defined in the body of the standard, and then implicitly the side issue of  `divceil` and `divfloor` and `divceilpos` and `divfloorpos`;

The following belong in the module you include:
- `NAN` - please tell me why it should be included by default with some examples;
- `log()`, `log2()`, or `log10()` - I am not even on the fence like @mppf;
- `isnan()` - because given a real number `x`, then `x != x` does the job just as well and if it doesn't, the compiler is broken;
- `isinf()` - because given a real number `x`, then `abs(x) == inf` does the job just as well even if `x` is a _NaN_ and if you are worried about IEEE 754 exceptions or optimizations raised by this, you need to include the facilities of the complete Math module anyway;
- `isfinite()` - because `abs(x) < inf` does the job just as well, and again with the same comments about IEEE 754 exceptions and optimizations; and
- `sgn` and `signbit` and `isclose` are serious floating point concepts and belong elsewhere; and
- `gcd`.

Note that I promoted both `nearbyint`, `rint` and `conjg` to being kept for reasons noted above.

At the risk of wearing out my welcome, making **max** and **min** operators would take them out of the mix here but I can handle leaving them as routines. It would also mean than **max=** and **min=** are also addressed.

**Comment by damianmoz** [comment]
I apologize for my earlier transmission of an incomplete posting. I got caught in some stupid insert mode and in getting out, I managed to hit the wrong key and post text which was still in a state of flux.

**Comment by damianmoz** [comment]
Hopefully this makes more sense that the previous convoluted text I deleted earlier:

I suggest taking a more rigorous approach to this problem.  Looking at the various IEEE 754 standards for guidance, in particular the original 1985 one, let's consider only the functionality mandated (or recommended) as operators within the main body of the IEEE 754 Standard from 1985. That way, what is default and what is not default has a traceable provenance that is validated by others. When comparing those two IEEE754-1985-inspired  lists against those mentioned at the start of this issue, the differences are quite easy to justify. If that does not make sense, please at least read the 1985 standard before replying. 

Most of the items which now remain in the default list routines are what the IEEE 754 standard defines as explicit operators, a few are constants, while the rest are associated with various rounding operation modes.  The fact that the functionality of all but the constants is provided by routines rather than implemented as Chapel operators is irrelevant.

Certainly the square root (`sqrt`) and remainder operations (`mod`)  must be in the default list as they are mandated by IEEE754 to be mathematical operations that are just as critical as add, subtract, divide, and multiply. So, really crucial. Also, both `nearbyint` and `rint` have been moved into the default list as they are relate directly to the rounding operations that are described within the body of that 1985 standard.

I took on board all of the ideas of @bradcray above, I pushed @mppf off his fence and took his suggestion, and took it on myself to make `isinf()`, `isnan()` and `isfinite()` not default, all on the basis that those made non-default were neither explicitly nor implicitly mentioned in the body of the standard. I dropped `isclose()` because I think it is disaster waiting to happen, in my humble opinion.

**... available by Default** - will **not** need a **use** statement:

- `abs()` is a monadic (unary) arithmetic operator mandated by IEEE 754 on floating point types, i.e.  it is like negation
- `sqrt()` is a monadic (unary) operator mandated by IEEE 754 as important as add, subtract, divide, multiply and remainder;
- `conjg()` is effectively a monadic (unary) arithmetic operator as important to **complex**(w) as negation is to **real**(w);
- `mod()` is a dyadic arithmetic operator is mandated by IEEE 754 as important as add, subtract, multiply, and divide;
- **max()** and **min()** - these apply equally to other types so are not exclusive to a floating point math library;
- `ceil()`, `floor()`, `round()`, `trunc()` and `rint()` and `nearbyint()` are rounding modes defined in the body of the IEEE 754 standard;
- `divceil()`, `divfloor()`, `divceilpos()` and `divfloorpos()` for reasons related to the item above;
- **INFINITY** or **inf** or whatever you want to call it but with its type corrected (for all time); and
- **NAN** - I am a bit ambivalent on this but it passes the same test by which the others have had to abide, so I kept it in.

My ambivalence might be reduced if I actually saw how **NAN** was defined. I am similarly also a bit worried about **INFINITY**, or should I actually be talking about _chpl_NAN_ and _chpl_INFINITY_.

**... NOT available By Default** - will need a **use** statement:

- `log()`, `log2()`, or `log10()` - as suggested by @mppf and others;
- `ln()`, `lb()`, or `lg()` - inline aliases for the three routines prior;
- `logp1()`, `log2p1()`, or `log10p1()`;
- `lnp1()`, `lbp1()`, or `lgp1()` - inline aliases for the three routines prior;
- `isnan()` - because given a **real**(w) number `x`, then `x != x` does the job just as well and if it doesn't, the compiler is broken;
- `isinf()`  - because given a **real**(w) number `x`, then `abs(x) == inf` does the job just as well even if `x` is a _NaN_;
- `isfinite()` - because `abs(x) < inf` does the job just as well even if `x` is a _NaN_;
- `sgn()` and `signbit()` and `isclose` are floating point introspection concepts and belong elsewhere;
- `isclose()` - please provide usage examples if you think otherwise; and
- `gcd()`.

Note that neither `isinf()` nor `isfinite()` will generate an IEEE 754 exception when their argument is a _NaN_, unlike the boolean expression given as an alternative. But if you need to start worrying about that level of functionality, you need the non-default Math features or the **ieee754** module which is due for release soon.

There was a very sparse Appendix called _Recommended Functions and Predicates` with the following words under the heading.
```
This Appendix is not a part of ANSI/IEEE Std 754-1985, IEEE Standard for Binary Floating-Point Arithmetic.
```
So with no recommended functions formally part of the IEEE 754-1985 standard, I do not even propose to visit what was discussed there. I will note though that it included `isfinite(x)` and `isnan(x)`, both of which are **not** in the default list.

I have attached an overloaded **proc** _cmplx_ which will create **complex**(w) numbers from given input. The _cmplx_ routine avoids casting as casting was deemed unwanted. If useful, it is so basic that it needs to go into the default list.
[cmplx.txt](https://github.com/chapel-lang/chapel/files/7874772/cmplx.txt)

**Comment by lydia-duncan** [comment]
I made a chart to help me organize better.  I think this accurately represents everyone's opinion when they posted.  `?` are for ones people were on the fence about.  Damian, I've included some `X?` for things that weren't listed specifically in your comment above, but I think reflect your thinking?

[Math default symbols.xlsx](https://github.com/chapel-lang/chapel/files/8018670/Math.default.symbols.xlsx)

If that accurately represents everyone, I think there's some clear overlap of symbols that don't need to be included by default.  Anything that people are on the fence about we might want to discuss more (possibly worth spawning individual issues on), since making them not included by default would be a breaking change.

**Comment by lydia-duncan** [comment]
### Symbols that have been decided on:
1. That will be included by default
- abs
- INFINITY
- max, min
- mod
- NAN
2. That won't be included by default
- log1p, etc.
- Bessel functions (j0, y0, etc)

### Symbols that I think are decided on but will double check in a PR

1. That won't be included by default
- e, pi, etc.
- carg
- sin, etc
- cproj
- erf, etc
- exp, etc
- ldexp
- lgamma, etc

### Symbols that still need discussion:

- ceil, floor
- divceil, etc
- isinfinite, etc.
- log, log10, log2
- round
- sgn
- signbit
- sqrt
- trunc
- gcd
- isclose
- cbrt
- conjg
- nearbyint, rint

**Comment by bradcray** [comment]
Woohoo!  Thanks for wrestling this one to the ground!
