### ISSUE TITLE
Should some modules that are included by default be imported instead of used?

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#18994]
Originally suggested by @vasslitvinov (do you remember the context?) and @ronawho pointed out that it might be useful to do this for certain symbols in the Math module - for instance, it seems like `e` is best referred to by `Math.e` because otherwise the meaning is unclear in the code itself

**Comment by bradcray** [comment]
I think Vass's motivator was that he didn't want to type `use Reflection;` or `import Reflection;` and simply wanted to do `Reflection.canResolve();`

I'm not a big fan of this proposal simply because it creates a special case and an additional category of module kind to remember and document.  I'm also not convinced that `Reflection` (or other modules) require or deserve special treatment in this way.

`e` is a definitely problem child, but also not something I'd introduce a new auto-module category for.  `e` mostly makes me wonder how other modern languages have dealt with it.

**Comment by bradcray** [comment]
> I don't think having e available in the namespace by default is a big issue. Users can redefine it in their own scope if they prefer to use it as a variable name, and it's convenient to have otherwise.

I used to think this as well, and am not sure I'd call it a "big" issue, but the number of users who have tripped over it and been confused by it has been larger than I'd like.  Specifically, the problem seems to come up when they have defined a variable `e` and think they are referring to it, but got something wrong (a scope?  a misunderstanding of the language?) and got `Math.e` as well.

That said, I feel reassured/less worried about this given that you found other notable precedents that always use `e`.  And I think putting this into the non-auto-used `Math` (which I think is the current expectation, even without a distinct `MathConstants`-style module, right?) will also mitigate it somewhat, particularly for programmers who use `import` style programming.

**Comment by damianmoz** [comment]
I would agree on both counts with the two points mentioned above
```
`e` is a definitely problem child, but also not something I'd introduce a new auto-module category for `e`.
```
From that same comment (and I apologize for selectively quoting)
```
I think putting this into the non-auto-used Math .... will also mitigate it somewhat
```
I would also agree.

Mind you, now that Math will no longer be auto-included, I will probably do
```chapel
use Math except e; 
```
because _e_ by itself has caught me out too way many times. If I ever need that value, I prefer to use (the far less elegant)
```chapel
param exp_1 = 2.71828.....' ; // Napier's constant or 'e' to its intimate friends
```
because that **param** naming convention agrees with others like `log_2` and so on. That means it I won't get caught when I using a identifier `e` for some exponent variable in my own code.

**Comment by lydia-duncan** [comment]
Now that `e` is no longer included in programs by default, I think this issue can be closed given that `e` was the original motivator behind it and we decided not to pursue this path for other reasons.
