### ISSUE TITLE
Math module - potential renaming for params

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#19000]
Here's a proposed renaming.  Alternate proposals and discussion welcome

| old name | new name
|------------------|--------------
| e | stays the same |
| log2_e | log2E |
| log10_e | log10E
| ln_2 | ln2 (or logE2 if we decide to use logE instead of ln in https://github.com/chapel-lang/chapel/issues/18995)
| ln_10 | ln10 (or logE10, ditto connection above)
| pi | stays the same
| half_pi | halfPi
| quarter_pi | quarterPi
recipr_pi | reciprPi
twice_recipr_pi | twiceReciprPi
twice_recipr_sqrt_pi | twiceReciprSqrtPi
sqrt_2 | sqrt2
recipr_sqrt_2 | reciprSqrt2

**Comment by ben-albrecht** [comment]
I know this issue is about renaming, but I think this is a good place to state that I am in favor of removing the `pi` variants and `sqrt`, `log`, and `ln` constants (couldn't those be supported via param functions?). I think these were added before these computations could be done within a param.

For reference, here are the math constants that a couple other languages provide:


Python:
```
pi, e, tau, inf, nan
```
Julia:
```
pi, e, eulergamma, catalan, golden
```

**Comment by lydia-duncan** [comment]
(I was going to put that in a separate issue)

**Comment by damianmoz** [comment]
Chapel already has some existing rules used to construct a **param** identifier and some of them are quite sound, especially when it comes to compound constants.

A constant which is a logarithm, say K, would be computed as
```chapel
K = log[B](C)
```
where **B** is the base which defaults to _e_ if is omitted but could be otherwise be **2** or **10**, . The existing Chapel rule that would create a **param** identifier name for _K_ (which is not unique to Chapel) is that use to create `log2_e` and `log10_e` above. It looks at the right hand side of the expression for K and then removes the trailing parenthesis and replaces the leading parenthesis by an underscore. So you end up with a **param** having a naming convention in this case like
```chapel
param log[B]_C = ......
```
I suggest that this existing Chapel rule be kept and even used more widely here, i.e. I would vote to keep the first two the same.

Let's see how that rule goes for the other examples.

One can express a current Chapel naming rule for a reciprocal identifier if one imagines that a function exists called **recipr** to create a reciprocal, i.e.
```chapel
recipr(x); 
```
The name of the actual **param** then created using the same existing Chapel rule as seen with the earlier logarithm and square root constants, i.e. strip the trailing parenthesis and replace the leading one by an underscore.

So given a compile type symbolic constant
```chapel
param name = .....
```
the rule to create the identifier of its reciprocal can be expressed as prepending **recipr_** to the name is now the first of 
```chapel
param recipr_name = ...
param rcp_name = ....
``` 
where the second assumes a function name of **rcp** because I wanted to use less characters.

Such an approach, which is consistent with the previous also preserves the name of the original constant, i.e. one can continue to do
```
grep pi source.chpl
```
to find all the occurences of _pi_ or _recipr_pi_.

A related existing Chapel rules for creating a constant name for say a multiple of something like
```chapel
two * pi
```
is simply to replace the multiply sign by an underscore and remove the spaces. That same rule preserves that ability to search, because you have names like `half_pi` and `quarter_pi`. That also retains symmetry with the original, something you do not have with
```chapel
param pi = ....
param reciprPi = ....
```

Sticking to the prepending rules means that for the cases about, you would end up with
```chapel
param pi = ....
param half_pi = ....
param quarter_pi = ...
param recipr_pi = ....
param recipr_half_pi = ....
param recipr_quarter_pi = ....
```
This has applied existing Chapel rules for creating consistent **param** identifier names, albeit more rigorously, and with the benefit
of being easily able to search for occurrences of the name and its relations in both source code and symbol tables.

So basically I would vote to keep the existing middle batch much the same, just with more consistency and rigour.

Continuing to apply that same existing Chapel rule rigorously across the board also means that something like a **param** constant for
```chapel
sqrt(2)
```
strip the last parenthesis and change the first to an underscore and we have
```chapel
param sqrt_2 = 1.41421356237309504880168872420969807856967187537694807317667973799073; // A002193 (OEIS)
```
which agrees with the current practice. 

And ditto for `recipr_sqrt_2`.

So now I would vote to keep the same existing rule for the last two.

That looks like a vote for a rigorous interpretation of the existing rules for the lot.

**So, my vote is to keep the good existing Chapel **param** identifier naming rules, just apply them consistently. They work - well**

Get rid of the bad rules for sure such as that `recipr` in the midde.

Leave camel casing for the names of a non-compound constant like the Euler-Mascheroni constant
```chapel
param eulerMascheroniDec = 0.57721566490153286060651209008240243104215933593992;
//or
param eulerMascheroniHex = 0x0.93C467E37DB0C7A4D1BE3F810152CB56A1CECC3Ap0;
```

**Comment by damianmoz** [comment]
I just realised that somebody might use the above rules for **param**s to affect routine names, specifically catching in this wide net the routine `rsqrt(x)` defined, but not calculated as
```chapel
proc rsqrt(x) return sqrt(x);
```
That name has been around for ages. But if this renaming is going to affect the style rules (a.k.a. guide) being pursued so that it affects everything, at most I would want to see
```chapel
proc r_sqrt(x) return 1 / sqrt(x);
```
and for consistency, that would mean changing the prefix **recipr_** or **rcp_** in the earlier comments to just **r_**

**Comment by lydia-duncan** [comment]
Prep information for an upcoming ad-hoc subteam discussion.

Note that I’m considering the `ln` and `log` ones handled by the log discussion in https://github.com/chapel-lang/chapel/issues/18995#issuecomment-1622471631

### 1. What is the API being presented?
```chapel
/* e - exp(1) or  the base of the natural logarithm */
param e = 2.7182818284590452354;
/* pi - the circumference/the diameter of a circle */
param pi = 3.14159265358979323846;
/* pi/2 */
param half_pi = 1.57079632679489661923;
/* pi/4 */
param quarter_pi = 0.78539816339744830962;
/* 1/pi */
param recipr_pi = 0.31830988618379067154;
/* 2/pi */
param twice_recipr_pi = 0.63661977236758134308;
/* 2/sqrt(pi) */
param twice_recipr_sqrt_pi = 1.12837916709551257390;
/* sqrt(2) */
param sqrt_2 = 1.41421356237309504880;
/* 1/sqrt(2) */
param recipr_sqrt_2 = 0.70710678118654752440;
```

### How is it intended to be used?

e and pi are the constants with those names.  The renaming constants are intended to cover pre-computed values that would be commonly used.

### How is it being used in Arkouda and CHAMPS?

- Arkouda
    - I believe e is not used in Arkouda.
    - pi is used in one file
    - half_pi, quarter_pi, recipr_pi, twice_recipr_pi, twice_recipr_sqrt_pi, sqrt_2, recipr_sqrt_2 are all not used in Arkouda
- CHAMPS
    - pi is used extensively in CHAMPS.  e is not.
    - half_pi, quarter_pi, recipr_pi, twice_recipr_pi, twice_recipr_sqrt_pi, sqrt_2, recipr_sqrt_2 are all not used in CHAMPS

### 2. What's the history of the feature, if it already exists?

Were shuffled around a bit due to the split into AutoMath/Math - used to be included by default in all programs, but now aren’t.

They used to live at the end of the module. They were added in June 2015, with some having different names in the first draft of the PR.  pi and e were always the same, but:
- half_pi used to be pi2
- quarter_pi used to be pi4
- recipr_pi used to be 1_pi
- twice_recipr_pi used to be 2_pi
- twice_recipr_sqrt_pi used to be 2_sqrtpi
- sqrt_2 used to be sqrt2
- recipr_sqrt_2 used to be sqrt1_2

The PR mentions that these were based on the constants defined in math.h on POSIX systems, and that if param reals were computed at compile time (which I think they are now), we would only need e and pi.
 
### 3. What's the precedent in other languages, if they support it? As relevant, we especially care about:
a. Python

Only pi and e are listed in Python’s math module’s constants list: https://docs.python.org/3/library/math.html#constants.  They also provide `tau`

b. C/C++

IEEE (https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/math.h.html) and Gnu’s (https://www.gnu.org/software/libc/manual/html_node/Mathematical-Constants.html) version define the constants as:
- M_E
- M_PI
- M_PI_2  (pi/2)
- M_PI_4  (pi/4)
- M_1_PI  (1/pi)
- M_2_PI  (2/pi)
- M_2_SQRTPI  (2/square root of pi)
- M_SQRT2  (square root of 2)
- M_SQRT1_2  (1/square root of 2)

Which matches the ones initially proposed in the PR that added them to Chapel.

c. Rust

Rust provides (https://doc.rust-lang.org/std/f64/consts/index.html):
- E
- FRAC_1_PI  (1/pi)
- FRAC_1_SQRT_2  (1/square root of 2)
- FRAC_2_PI  (2/pi)
- FRAC_2_SQRT_PI  (2/square root of pi)
- FRAC_PI_2  (pi/2)
- FRAC_PI_3  (pi/3)
- FRAC_PI_4  (pi/4)
- FRAC_PI_6  (pi/6)
- FRAC_PI_8  (pi/8)
- PI
- SQRT_2  (square root of 2)
- TAU

d. Swift

I think Swift just provides pi (https://developer.apple.com/documentation/swift/floatingpoint/pi), it doesn’t even seem to provide e or tau, let alone the other constants.

e. Julia

Julia just provides pi (https://docs.julialang.org/en/v1/base/numbers/#Base.MathConstants.pi) and e (https://docs.julialang.org/en/v1/base/numbers/#Base.MathConstants.%E2%84%AF) of these, I wasn’t seeing the other constants.

f. Go

Go provides (https://pkg.go.dev/math#pkg-constants):
- E
- Pi
- Phi
- Sqrt2
- SqrtE
- SqrtPi
- SqrtPhi 

### 4. Are there known Github issues with the feature?

- The log ones are covered by https://github.com/chapel-lang/chapel/issues/18995
- We talked about where these should live in https://github.com/chapel-lang/chapel/issues/18990 but the decision for them has already been implemented
- They are mentioned in https://github.com/chapel-lang/chapel/issues/19062, which we will cover as part of this discussion
- The issue used to determine our standard module style guide explicitly calls them out as examples of something we want to avoid: https://github.com/chapel-lang/chapel/issues/6698 

Other issues:
- Related to Math.e accidentally shadowing or conflicting with some symbols, which is less likely now that it is no longer included by default
    - https://github.com/chapel-lang/chapel/issues/19367
    - https://github.com/chapel-lang/chapel/issues/19313
    - https://github.com/chapel-lang/chapel/issues/18993
- https://github.com/chapel-lang/chapel/issues/18991 talking about the precision displayed for these constants and whether it’s appropriate (not for 2.0, more like a combination documentation issue and misunderstanding of floating points on my part)
    - https://github.com/chapel-lang/chapel/issues/18599 also talks about their precision but in a more intelligent way than I managed to in #18991.
- Pi is used as an example in some issues that aren’t related to the feature itself, so I’m not including them

### 5. Are there features it is related to? What impact would changing or adding this feature have on those other features? 

The ones involving the square root of something are related notionally to the `sqrt()` function.  Naming that doesn’t match that function’s name should probably be avoided, but it won’t otherwise impact it.

pi is used in nbody and quarter_pi is used in our c-ray examples, so those programs will need to be updated if anything changes. 

### 6. How do you propose to solve the problem?  
A.

| old name | new name
|------------------|--------------
| e | stays the same |
| pi | stays the same
| half_pi | halfPi
| quarter_pi | quarterPi
recipr_pi | reciprPi
twice_recipr_pi | twiceReciprPi
twice_recipr_sqrt_pi | twiceReciprSqrtPi
sqrt_2 | sqrt2
recipr_sqrt_2 | reciprSqrt2

- Pros:
    - Consistent with our standard module style guide
- Cons:
    - As Damian pointed out above, this does mean that `grep pi source.chpl` will only generate hits for `pi`, not for `halfPi`, etc.
        - Of course, users could rename them upon import or use of the Math module if they wanted the consistently searchable form, but that is an additional burden on them.

Might be useful to extend the comments to include names from other languages, so that it is easier for a user looking for what they’re familiar with in that language to find the Chapel equivalent.  That said, if such languages undergo a change like we are with our 2.0 effort or choose to deprecate them, we would find ourselves out of date.

B. Deprecate the pure computation versions (not e or pi, and not the log/ln ones)

- Pros:
    - Don’t have to determine a new name
    - Arguably the compiler param machinery can handle them reasonably enough
- Cons:
    - If user doesn’t want to have to type the computation being performed again, they’ll have to define it themselves instead of relying on a common one imported, which could lead to differences due to precision they choose to use (especially if they aren’t as educated on floating point precision)

C. Mark the pure computation versions unstable (not e or pi)

- Pros:
    - Users can let us know if they want us to keep it
- Cons:
    - Probably should still rename them, since right now they’ll cause confusion about what our standard modules’ approved style is

I think we should do both A and C.

**Comment by damianmoz** [comment]
Again, very well documented.

**Comment by lydia-duncan** [comment]
In our subteam discussion today, we decided to use the proposed new names and mark these constants unstable:
- halfPi
- quarterPi
- reciprPi
- twiceReciprPi
- twiceReciprSqrtPi
- sqrt2
- reciprSqrt2

It was pointed out that the compiler can't actually compute the `sqrt` ones today because `sqrt` is not a param function (oops, that was sloppy on my part).  But we decided to mark them as unstable anyways.
