### ISSUE TITLE
What, if anything, should we do about special method names?

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#19038]
Today, Chapel has the following special method names (ignoring those defined by operators):

* initialization: `init`, `postinit`, `init=`, `deinit`
* direct access/iteration: this, these
* I/O: readThis, writeThis, readWriteThis
* hashing: hash
* context management: enterThis, leaveThis

This issue is somewhat of an umbrella issue asking what we want to do about them—if anything—where I expect we'll wrestle with different subsets on distinct issues.

The motivation for this issue is to note that a variety of naming schemes are currently used:
* keyword-based (`init`, `this`)
* simple description (`hash`, `init`, `init=`, `postinit`, `deinit`)
* "doThis" style: `readThis`, `writeThis`, `readWriteThis`, `enterThis`, `leaveThis`
* cute/clever: `this`, `these`

And users have expressed concern about things like:
* How can I be alerted that I'm opting into a special method rather than happening to use a name that Chapel gives special meaning to?
* How can I ensure that my code will not break if/when more special methods are added over time?

And in some cases, these questions are complicated by the fact that the Chapel compiler will introduce implementations of these methods if the user hasn't created them (such that all types are printable or hashable by default, for example).

Here are some related issues:
- [ ] https://github.com/chapel-lang/chapel/issues/13897
  - [ ] https://github.com/chapel-lang/chapel/issues/15963 (on the topic of generating errors for bad uses of init methods)
- [x] https://github.com/chapel-lang/chapel/issues/18263
- [ ] https://github.com/chapel-lang/chapel/issues/19041
- [ ] https://github.com/chapel-lang/chapel/issues/18340
- [ ] https://github.com/chapel-lang/chapel/issues/18811
... more to be added as we go...

**Comment by dlongnecke-cray** [comment]
Big wall of text below trying to capture my thoughts from the recent
deep dive.

But to summarize, in my ideal world we use a combination of three
approaches to solve this problem:

  - For very special methods (`init`, `postinit`, `deinit`) we
    reserve these words, since the compiler already takes a
    strong hand in calling them and making sure they are properly
    defined
  - For many methods (`readThis` / `enterThis` / `these`) we use
    interfaces to constrain the method types
  - We turn `this` into `operator this`, since the language can
    call it, but at the same time we can't constrain its type

## `init` / `deinit` / `postinit` / `init=`

I was actually surprised when I learned that some of these are not
reserved words.

In the current state of the language, these all seem sufficiently
"uncallable", and have special rules guiding both their definition
and invocation, that it makes sense to reserve them and to say
that the compiler plays a special hand in ensuring they are defined
and used properly.

## `this`

The more I think about it, the more `this` makes sense as an operator.
In that `callable(foo, bar)` yields an expression (usually), and so it
fits right in with how other operator procedures are called by the
expression grammar.

So to me changing `this` -> `operator this` makes sense due to where
`callable(foo, bar)` can appear in the language.

I think we should call it `operator this`. Brad's explanation of the
origin of `this` (we call it `this` because you're calling "yourself",
and `this` is the receiver keyword) resonated with me.

I don't think we can call it `operator[]`, due to the fact that it is
possible to call something with either `[...]` or `(...)`.

Maybe we do want to offer both `operator()` and `operator[]` if we
decide that it should be possible for the two forms of syntax to
do different things. But from reading the language spec, it seems
like `[]` is just syntactic sugar for `()`.

I'm slightly more open to `operator call`, but that would reserve a
new keyword.

I don't think that `this` makes sense as an interface because there
cannot be any restrictions on either its arity or the type of its
arguments. If we tried to constrain it as an interface it would be
so weakly constrained as to pretty much be generic anyway.

## `enterThis` / `readThis` / `leaveThis` / `writeThis`

I think that these special methods should be turned into interface
methods.

They require specific type signatures, and interfaces are the ideal
way to specify their constraints.

Additionally, we could have the interfaces `Readable` and `Writeable`
be auto-derived by the compiler in the future, or it could just be
possible for the interface to provide a default implementation for a
given type (what we do today with `Reflection` primitives).

I don't think we have to worry about namespace collisions here,
because the `channel.read` and `channel.write` (and other IO) methods
would just take a `Readable` and `Writeable`, so we'd only be
stealing the interface name.

## `these`

I think that `these` should also be turned into an interface. We
could have three interfaces for serial, parallel, and standalone
parallel iteration.

I don't think it makes sense to have `these` be marked `operator`,
because loops are generally viewed as statements. (I generally
view `operator` as participating in the expression part of the
grammar.) I could be convinced to change my view on this, though,
as loop expressions do exist.

Additionally, the type of the `these` method is fixed in a way that
something like `operator this` is not, which is another point in
favor of interfaces to me. However it is not fully constrained (the
return type must be generic).

I could go either way on this one, but at first glance an interface
seems like the most appealing way to handle `these`.

It seems like it would also make it slight easier to implement, as
the compiler would only have to confirm that a type satisfies the
necessary iterator interface (as opposed to confirming that a
`these` method resolves in an adhoc way).

## `hash`

I think that `hash` should be a standalone procedure that accepts
a `Hashable`. I think this solves the namespace collision issue
in a natural way, because if a user has defined their own `hash`
function they can cast their type into a `Hashable` before making
the call (assuming such functionality is possible). To reduce the
possibility of namespace collisions even more we could name the
interface `ChapelHashable`.

Or we could let the user specialize their `hash` function for a
specific concrete type, in which case I figure that that overload
would be preferred over the `hash(obj: Hashable)`.

I don't think we should worry too much about defining a top level
`hash` procedure. It is such a core behavior that Brad's argument
(what else is a `hash` procedure going to do?) holds a lot of
weight. It's also not a method, so we're not polluting the method
namespace in the first place.

Additionally, I would expect the compiler to be able to automatically
derive types as instances of `Hashable` in the same way that it
could for `Readable` and `Writeable`. This ensures that users can
hash their POD types out of the box.

## Interfaces and auto-derivation

I am not sure what this will look like. In some languages that offer
interfaces it is possible for the compiler to automatically satisfy
an interface for a type if all the components of that type also
satisfy the interface.

Vass is the expert here, but it might be possible for interfaces in
Chapel to provide a similar sort of functionality.

I am not sure how default implementations of an interface method
interact with this capability (could we use this in place of
auto-derivation?).

**Comment by cassella** [comment]
I'm put in mind of how python handles special methods, with `def __word__(self):`.  Or at least that the special methods are all in their own "namespace" with that convention.  Something like that would address the two user-raised concerns Brad mentioned.  All `__word__()`s would be off-limits for user code, except to implement one of the documented special methods, but no bare `word`s would have to be reserved.

This makes sense to me for methods that won't be called directly by user code, but will be called by the compiler e.g. turning an `x[10]` into `x.__this__(10)`, or even by module code for the IO calls.


Another option would be to extend the `operator this` idea to make all such special methods be operators with alphabetic names, e.g. `operator enter()`.  This would also address those two concerns because there's no way to call such a thing besides the special compiler/module handling (right?), so users shouldn't be writing them inadvertently or be unpleasantly surprised if a new one is added.  I don't know if there are implications for making these interface operator methods.

(It doesn't seem right for the `init()` family, but maybe that's just because I'm used to those they way they are.)

**Comment by bradcray** [comment]
> All __word__()s would be off-limits for user code, except to implement one of the documented special methods, but no bare words would have to be reserved.

Hi Paul — We kicked this around verbally yesterday a bit, though I didn't capture the result here.  One of the things that people pointed out was that in Python, the expectation is that a user won't ever call directly into one of these dunder methods, but in Chapel we don't have that same expectation.  I.e., if you create a standard `.hash()` method and you or someone else creates a new collection that relies on hashing, it's reasonable for that code to call your `.hash()` method (or for your `.hash()` method on a record to call `.hash()` on each of its fields or the like.  In Python, the user-facing interface to `__hash__` is a standalone function `hash()` but this wouldn't have the proper visibility requirements in Chapel.  So the net result is that we'd need to and/or want to call directly to your `.hash()` method.  We could still use Python's decoration scheme and simply have different rules, but it seems like it would be clearer to either have the same rules or use a different decorator.  Engin had some thoughts along these lines and is going to post them somewhere when he gets the chance.

> Another option would be to extend the operator this idea to make all such special methods be operators with alphabetic names, e.g. operator enter().

We discussed this a bit as well, and it got a bit of traction, but the main stumbling block would seem to be if you define `operator enter()` and `proc enter()` how would you call each one and distinguish between them?

> (It doesn't seem right for the init() family, but maybe that's just because I'm used to those they way they are.)

Many of us on the call felt the same way here, and one proposal for dealing with this would be to say that anything that was defined with a reserved word would not need to go down whatever path we take for things like `.hash()`.  And then to reserve the words associated with initializers as proposed in #13897.

Of course, that also makes one wonder "Should we reserve the names of some/all of these other special methods as well as a solution", but `hash` seems like a not-so-good word to reserve to most of us, I think.

**Comment by bradcray** [comment]
I finally got the time to read David's big block of text.  Some of the items I've already responded to on the child topics of this umbrella topic, so won't repeat here. Here are some high-level reactions:

We don't have interfaces today, and aren't likely to have them in short order, so it's not clear to me what the practical implications of the interface-related parts of the proposal mean.  If it means we don't do anything now and just wait for interfaces, I worry that we're stuck with this mish-mash for Chapel 2.0.  If we do something temporarily better now and improve more once interfaces are online then we're back to the original problem of needing to figure out what to do now.

That said, I'm not convinced that I'm on-board with the interface approach, at least if I've got the right picture in mind for auto-derivation.  Specifically, I think it's a really powerful, productive, and important aspect of Chapel that virtually any variable or value can be printed out with no work on the user's part—while giving them the option to provide their own override of that method to customize it if they'd like to.  If the auto-derivation idea is that I'd have to opt into it using something like:

```chapel
record R: Readable, Writeable { ... }
```

or the equivalent, then in order to get the same "batteries included" features for I/O today, I'm going to have to type this after every type declaration that I make.  That seems counterproductive without offering any real benefits.  OTOH, if we took the approach of saying "Well, all types have the Readable and Writeable interfaces automatically and the compiler will fill them in if they don't" then I don't see how that's any different than what we have today.

And in either case, we still have to decide what the routines should be called, right?


Similarly, I don't see how having a standalone `hash()` routine that takes something meeting the `Hashable` interface helps, possibly just due to lack of details.  What is required to meet the `Hashable` interface?   Presumably something like a `.hash()` method and an `==` operator method?  If so, once we have such a method, why is calling `hash(myR)` preferable relative to simply calling `myR.hash()`?

**Comment by dlongnecke-cray** [comment]
Before I respond (with another wall of text 😄), I just want to emphasize that these ideas are expressed within the context of "in your ideal world / your ideal solution".

I definitely understand that we can't go this route for 2.0, but if possible, I would really love it if we could coordinate with @vasslitvinov and ensure that it is possible to transition to this approach in the future if we want to do so.

If we're trying to make practical decisions, I hope we change `this` into an operator and then just expect we'll follow https://github.com/chapel-lang/chapel/issues/19050 for everything else, with the exception of iterators (not sure what we'll do about those to be honest).

Wall of text time.

---

I would really like to see us require strict type signatures for special methods. I expect some users would want this as well, if only because a strict type helps make the requirements of the special method more clear.

Interfaces seem like the obvious/ideal way to achieve that goal. I'm not sure what the alternative would be - expressing to the compiler a set of valid function signatures for special methods in an adhoc way? That seems like a shame when interfaces can express requirements in a much more powerful way, and in code.

> Specifically, I think it's a really powerful, productive, and important aspect of Chapel that virtually any variable or value can be printed out with no work on the user's part

I 100% agree. I immediately fell in love with all the "batteries included" features in Chapel and would never want to compromise on that capability.

> If the auto-derivation idea is that I'd have to opt into it using something like...

The idea for auto-derivation is that we (the language developers) would mark certain built-in interfaces such as `Readable`, `Writeable` as candidates for auto-derivation. The compiler will then try to auto-derive those interfaces for any type that is applicable. So more your like second idea.

> OTOH, if we took the approach of saying "Well, all types have the Readable and Writeable interfaces automatically and the compiler will fill them in if they don't" then I don't see how that's any different than what we have today.

- The typed interface methods help express a bit more about what is expected of the methods
- We've reserved the name `readThis` and `writeThis` as a method only within the context of being a `Readable` or a `Writeable`. If our method takes a `Readable` then there's only one `readThis` that can be called
- If the user added their own `UserReadable` interface with a `readThis` method, they should have at least some control over choosing which is called by casting their type to a `UserReadable` (Michael imagined we might do `(obj:UserReadable).readThis(ch)`).

One of the crucial ideas that we may not have discussed yet is the ability to ephemerally cast to an interface type (e.g. the `(obj:UserReadable).readThis(ch)` call) in order to resolve potential ambiguity. If we don't have that ability then I'm not 100% sure these ideas work.

I've always just kind of assumed we would be able to do this, though. I wonder what @vasslitvinov thinks about this idea.

> Similarly, I don't see how having a standalone hash() routine that takes something meeting the Hashable interface helps

W.r.t. `hash()`, my reasoning for making it a standalone function was:

- Since it takes a `Hashable` there's no potential for namespace conflict within the body of standalone `hash()` when `obj.hash()` is called. The benefit of the standalone `hash` is that the conversion of the actual to the interface type happens automatically. No need to write `(obj:Hashable).hash()`.
- If the user wants to override the standalone `hash()` for a concrete type then that overload will be preferred if applicable. If some interface they wrote implements `.hash()` then they can cast to that interface before calling `obj.hash()` to get the right behavior.
- This is an aesthetic reason: all the other interface-backed ideas are called by the language to implement syntax, but here `hash()` is a method that is just called by a type internally. This distinction might be too shallow, but it makes sense in my head.

**Comment by vasslitvinov** [comment]
A version of the "interface" proposal is here: #19074

**Comment by vasslitvinov** [comment]
User-definability of `hash()`: #9182

**Comment by mppf** [comment]
@bradcray - consider adding `borrow` to the list of current special methods in the top post here (see also https://github.com/chapel-lang/chapel/issues/21372#issuecomment-1385678232 ).

**Comment by vasslitvinov** [comment]
Another approach to namespace control is type methods. We can introduce a predefined type, say `Chapel`, and define the special methods as methods on this type. For example:
```chpl
proc Chapel.hash(arg: myRecord) { .... }
writeln(Chapel.hash(x));
```
This does not require introducing any new language features! Except...

How to enable dynamic dispatch when the argument is a class, like we have today for hash(), writeThis(), etc.? Proposal: special-case the type methods on this predefined type to dispatch dynamically on their first argument when it is a class.

Alternatively, write the same code as above and consider `Chapel` (or whatever name we choose) to be a predefined module, not a type. That is, make this module magic by allowing outside code to define functions in this module.

**Comment by bradcray** [comment]
I'm closing this issue because we have effectively decided to use a combination of:

* reserved words (for initializers, default accessors, and default iterators)
* interfaces (for hashing, IO, context management, and probably most other things going forward)

and have started into the implementation of these approaches in earnest.
