### ISSUE TITLE
Math module - should the floating point manipulation functions live in their own module?

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#19061]
Suggested by Michael in the review meeting for the module and alluded to by others.

I think this impacts (in no particular order):
- signbit
- INFINITY
- NAN
- isfinite, isinf, isnan
- exp, exp2, expm1
- ldexp

It seems like it would be useful to have them all in one place.  They also are different from the other Math functions in that they have to do with the representation of the number in computers.  However, these symbols are a bit divided in terms of whether we think they should be available by default (if I'm identifying them correctly, which it is entirely possible I am not), and splitting based on that might result in too few symbols to be worth a module on their own.

**Comment by lydia-duncan** [comment]
@mppf, @bradcray, @damianmoz - have I correctly identified the symbols that fall under this category?  Did I miss any?  Have I accurately described why they might be considered separable from the other contents of the Math module?

**Comment by mppf** [comment]
I don't think I'd put INFINITY, NAN, or exp in such a module.

I'd expect such a module to be about taking apart details of floating point numbers and putting them back together. I'd expect:
 * signbit
 * isfinite, isinf, isnan
 * something to extract the exponent from a floating point number
 * something to extract the mantissa from a floating point number
 * ldexp (maybe renamed) to make a floating point number from mantissa + exponent

**Comment by bradcray** [comment]
I'm generally in favor of putting routines related to floating point binary representations and picking them apart or reasoning about them into a distinct module from Math.  I'm not familiar enough with what those routines are / should be to know precisely what such a module should entail.  @damianmoz made a veiled reference to potentially developing and contributing a module that _sounded_ something like this recently, so I'll be curious to hear more about that and what he thinks about this in general.

Here are a few quick reactions and follow-up questions:
* in the same way that `nil` is available by default without having to use/import a module for classes, I'd be inclined to do the same with special sentinel floating point values like infinity or nan (which I'd also stop writing as all-caps)
* I need reminding how `isInf(x)` differs from `x==infinity`.  If they're identical, do we need both?  If not, should we make them available by default the same way `x==nil` is available by default for nilable classes?
* I think I remember how `isNaN(x)` differs from `x==nan` (in that there are many representations that evaluate to NaN?)  I might make isNaN() available by default for the same argument as the previous bullet for that reason.  It also makes me wonder whether floating point `==` should do some sort of warning or error if NaN is passed in to avoid mistakes (or should `==` that gets `NaN` as a `param` argument automatically become `isNan()`, say?
* Is exp(x) the e**x routine?  If so, that seems like Math to me, not floating point representation

**Comment by damianmoz** [comment]
In answer to the first paragraph, watch this space.

**First Bullet Point**:
The original question was whether those symbols belong in a special module. The answer to that is **no** (where capitals do not mean emphasis, just so you see the answer). I think poor Michael was being misquoted in what he said at the meeting. What Michael says above seems to better reflect the meeting minutes. My response to your suggestion Brad of including them by default is **agreed**.  See my comment in #18990 where I based that argument on the precedence that those symbols appeared 36 years ago in the body of the first IEEE 754 standard, even though there is a practical argument that they belong in the explicitly included Math library (which I think Michael suggests unless I hve misunderstood). I am not say my suggestion is better, just that it followed the provenance/precedure rule that I was using for the other cases. I have very different opinion on the naming.  

**Second Bullet Point**:
You are almost correct. You forgot about capturing the negative case.

Strictly
```chapel
proc isinf(x : real(?w)) return abs(x) == INFINITY;
```
I would **not** have isinf() (or whatever it is going to be called) available by default. See #18990.

**Third Bullet Point**
Yes, I agree `isNaN(x)` is so much more correct mathematically than `isNan(x)`.

```chapel
proc isNaN(x : real(?w)) return x != x;
```
The reason why that is the case is not quite what you said. There is only one representation of NAN, which is a quiet NAN but there are multiple representations of a signalling NaN which is written as **sNaN** mathematically or **SNAN** in C/C++ or whatever name makes mathematical sense. The above code captures all of those cases. I documented that expression in #18990.

I would **not** include isNaN() by default. I said the same in #18990.

Anything compared for equality against **NAN** or **SNAN** or **NaN** or *SNaN** or **nan** (or whatever it is called) must evaluate as false. Anything else violates the standard. And I would not even compute that at compile because in the event that you use Chapel on a machine which supports signalling NaNs, you will not trigger the exception that must be raised. And certainly doing that automatic replacement thing with == would give the wrong result as defined by the standard. Happy to have a warning though, as people sometimes make silly mistakes.

**Fourth Bullet Point**:
Yes, `exp(x)`` is an exponential routine, i.e. the same as `e<sup>x</sup>` routine. If is not a floating point representation routine. It definitely belongs in Math. Similarly, `exp2(x)`` is an exponential routine and has nothing to do with floating point representation. Note that exp(x) should never evaluate as `e ** x` or even `pow(e, x)` even if _x_ is a small integer except maybe `x in [1, 2]` because the error will be grossly wrong over what the standard says it should be and most implementations provide today/

**Comment by damianmoz** [comment]
Can we get a summary of where this is at, taking into account of the feedback please?

**Comment by bradcray** [comment]
> In answer to the first paragraph, watch this space.

I'm still watching the space wondering if more information is coming... :D

**Comment by lydia-duncan** [comment]
Sure, here's a summary:

The list of symbols considered for a separate module are:
-  signbit
-  isfinite, isinf, isnan
-  something to extract the exponent from a floating point number
-  something to extract the mantissa from a floating point number
-  ldexp (maybe renamed) to make a floating point number from mantissa + exponent

Brad and Michael are in favor of a separate module, while Damian is not (I'm ambivalent).  There is still some disagreement about if `isfinite` etc should be included by default, which complicates the picture if we do decide to split into a separate module.

There were various questions about specific functions and their implementation that have been answered (though Damian, I think there's a typo in your response to Brad's third question - I think you meant:
> Yes, I agree `isNaN(x)` is so much more correct mathematically than `x == NAN`.

Unless there's a special distinction between `isNaN` and `isNan` that I'm not aware of?)  Otherwise, I don't think that the questions are relevant to the conversation any more?

**Comment by bradcray** [comment]
> while Damian is not 

I didn't interpret it that way, but was definitely confused by the "first bullet point" paragraph.  Specifically, Damian, while you said:

> ...belong in a special module. The answer to that is no

You also said:

> My response to your suggestion Brad of including them by default is agreed.

Where my mind combined these into "They should be defined in a separate module that is used by default" (since all code must live in some module).  Re-reading today, though, I suppose the other interpretation might be "They should be defined in the AutoMath module (or whatever we end up calling it) so that they're available by default"—is that what you meant, @damianmoz?

And then as a follow-up, if they were auto-included by default, would putting them in AutoMath be preferable to a new auto-used module like Float or AutoFloat, say?  And if so, why?  (to me, they seem to be more floating-point representation related than Mathy which is why I ask.  And while one could argue that it doesn't matter if they're auto-used modules, I think it still does in terms of the organization of documentation and those who use fully-qualified naming or use module filtering to rename or exclude the symbols).

**Comment by lydia-duncan** [comment]
I thought `agreed` specifically had to do with `INFINITY` and `NAN` (which are now not on the list because it sounded like I misinterpreted putting them on it)?

**Comment by damianmoz** [comment]
To keep it simple, I am happy that the following existing (or their replacements):
- signbit
- isinf, isnan, isfinite, isnormal (the last is defined in the same place in POSIX as the first three)
- ldexp()
- retrieval of, let's call it `k`, the unbiased exponent of a floating point number `x`
- retrieval of the signed significand of `x` which is arithmetically `x * 2**(-k)` 

I am easy either way whether the constants to represent positive infinity and a Not-A-Number live in that  separate module. But, in the event that they do not go in the separate model, I would just leave them in AutoMath.

Whether you call the floating point number in the last of those bullet points a mantissa is up to you. I do, but that is an imprecise term unless you lock down the definition in the documentation. You would most likely not compute it the way I have written it. Remember that Chapel is using a IEEE 754 floating point model (by default), not the dated and more restrictive C floating point model.

Also, the following code
```chapel
x != x
```
is the correct way to detect whether `x` is a Not-A-Number. I apologize if I am telling people how to suck eggs but he reason what the `isnan()` routine/macro appears iss because compilers were broken. Too many optimizes said that the line above was always **false* and optimized it away. In fact, when `x` is a Not-A-Number, it evaluates top **true**.  But most compilers in 2022, including Chapel are smarter than that so the above works. If `x` is a signalling Not-A-Number, the above also raises an Invalid IEEE 754 exception.The only reason why you would use `isnan()` is if you wanted to avoid an IEEE 754 exception in that event. 

n a floating point comparison, no number is allowed to compute as equal to a number which is a Not-A-Number, not even Not-A-Number itself. In Chapel, Fortran, C/C++, or whatever. So,the code
```chapel
x == NAN
```
or `NaN` (if that gets proposed/accepted) will **always** evaluate as **false**, which is probably not what you want.

**Comment by lydia-duncan** [comment]
I think we've finalized where these functions live, so I'm closing this issue
