### ISSUE TITLE
internal error split-initializing variables using de-tupling syntax

### ISSUE THREAD

**Issue by jhh67** [chapel-lang/chapel#19159]
### Summary of Problem

I was playing around with tuples and typed some gibberish and got an internal error.
```
foo.chpl:3: internal error: AST-PRI-IVE-0235 chpl version 1.26.0 pre-release (27f3d59788)

Internal errors indicate a bug in the Chapel compiler ("It's us, not you"),
and we're sorry for the hassle.  We would appreciate your reporting this bug --
please see https://chapel-lang.org/bugs.html for instructions.  In the meantime,
the filename + line number above may be useful in working around the issue.
```

### Steps to Reproduce

**Source Code:**

```chapel
var foo = (1,2);
var x,y;
(x, y) = (foo(0), foo(1));
```

**Compile command:**

`chpl --no-devel foo.chpl`

**Execution command:**

NA
**Associated Future Test(s):**

### Configuration Information

- Output of `chpl --version`:
```
chpl version 1.26.0 pre-release (27f3d59788)
Copyright 2020-2022 Hewlett Packard Enterprise Development LP
Copyright 2004-2019 Cray Inc.
(See LICENSE file for more details)
```
- Output of `$CHPL_HOME/util/printchplenv --anonymize`:
```
CHPL_TARGET_PLATFORM: darwin
CHPL_TARGET_COMPILER: clang
CHPL_TARGET_ARCH: x86_64
CHPL_TARGET_CPU: native
CHPL_LOCALE_MODEL: flat
CHPL_COMM: none *
CHPL_TASKS: qthreads
CHPL_LAUNCHER: none
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: cstdlib
CHPL_GMP: none *
CHPL_HWLOC: bundled
CHPL_RE2: bundled
CHPL_LLVM: none *
CHPL_AUX_FILESYS: none
```
- Back-end compiler and version, e.g. `gcc --version` or `clang --version`:
```
Apple clang version 12.0.0 (clang-1200.0.32.29)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```
- (For Cray systems only) Output of `module list`:

**Comment by bradcray** [comment]
Thanks for filing this.  This looks related to, yet different from, https://github.com/chapel-lang/chapel/issues/16937 and https://github.com/chapel-lang/chapel/issues/17196 (in that those also relate to split initialization for tuples, but didn't result in internal errors, I believe).

It sounds as though you're not stuck on this, but if anyone else were, a workaround would be to change the declarations of x and y to have types:

```chapel
var x,y: int;
```

**Comment by ghbrown** [comment]
I also ran into this issue recently when creating a function to return dynamically sized vectors:
```chapel
proc return_arrays() {
  // some size defining thing only known at runtime in function
  var magic_constant : int = 5; 
  var arr : [0..<magic_constant] int = 0;
  return (arr, arr);
}

var arr1, arr2;
(arr1, arr2) = return_arrays();
```
which gives
```
compiler_bug.chpl:10: internal error: AST-PRI-IVE-0242 chpl version 1.27.0 pre-release (cb4a7da0a0)
<plus the extra prose>
```
when compiled with `chpl`. I'm still on a recent but not bleeding branch of Michael's, so don't worry about finding the hash in `main`. Just reporting to add weight to the issue.

Also, the fix I intend to use for now is:
```chapel
var tup;
tup = return_arrays();
var arr0 = tup[0];
```
if anybody else runs into this need before things get changed.

**Tangent**: perhaps part of the reason this arose is that I don't know the "right way" to type def these variables (arrays of known type but unknown size) if it's possible at all. I tried both type defs like `var arr0 : [] int;` and without type defs (like above), but nothing seemed to work. I think in C you'd use pointers, and Fortran you might have to resort to them too unless dynamic allocation is friendlier than I remember (most of my Fortran experience has been fixed shape linear algebra).

**Comment by bradcray** [comment]
@ghbrown : Thanks for tagging onto this issue.  I've added the "user issue" label to reflect that (@jhh67 works on our team).  And I'm glad that you found a workaround that works for you.  That said, if your code is not more complicated than what you've shown here (and I realize it very well might be), I'd suggest simplifying it ever so much to:

```chapel
var tup = return_arrays();
var arr0 = tup[0];
```

Or, if you really only need the first component, you could do:

```chapel
var arr0 = return_arrays()[0];
```

In addition, note that I believe the sticking point in this issue relates to the use of split initialization in which the variables are declared with neither types nor initializers.  Once we get rid of the split initialization, as in my rewrites, to my knowledge, you should also be able to use:

```chapel
var (arr0, arr1) = return_arrays();
```

or:

```chapel
var (arr0, _) = return_arrays();
```

(which works with your test case at least).

To your question about declaring the types:  There's a long-term intent on supporting array declarations of the form:  `var A: [0..] real;` as a way of saying "a 1D array starting at 0 (say) but of unknown size", but unfortunately we haven't ever gotten that plumbed all the way through the compiler.  Here's an issue about that:  https://github.com/chapel-lang/chapel/issues/10596  For a case like yours, I think this is what I'd want, but let me know if you think otherwise.

**Comment by ghbrown** [comment]
@bradcray Thanks for the tips. My application thankfully isn't much more complicated, so these are nice simplifications. Predefining those variables is just a "bad" habit from Fortran, and I doubt I would have stumbled onto the issue otherwise.
Yes, the form of array declarations you gave look like what I was thinking might exist, and I agree they'd be nice to have.

**Comment by bradcray** [comment]
> Predefining those variables is just a "bad" habit from Fortran, and I doubt I would have stumbled onto the issue otherwise.

Cool, glad to hear it!  (although, also, sorry to hear it!  :D ).

I changed the title of this issue to tie it more directly to the split initialization context and am planning to update my first comment to give the more direct workaround.

**Comment by lydia-duncan** [comment]
I have a branch that transforms the internal compiler error into a more understandable one about the variable not having an initial type declaration.  I may be able to get it to actually work fully, but I'm feeling a bit like a bull in a china shop with the split initialization code so need some discussion with Michael before what I currently have gets merged anyways

**Comment by lydia-duncan** [comment]
I've merged that pull request now.  #16086 tracks the desire to actually support split init when the type isn't used (among other things), so closing this one and leaving that one open
