### ISSUE TITLE
llvm verification failures with `CHPL_COMM_DEBUG`

### ISSUE THREAD

**Issue by ronawho** [chapel-lang/chapel#19185]
Originally reported by the gasnet team with clang-13 and system llvm testing, but I can reproduce in other configurations. With `CHPL_COMM_DEBUG` we're seeing some compiler segfaults that I think are coming from llvm verification failures. I see the issue on my mac and linux64:

```sh
export CHPL_COMM=gasnet
export CHPL_GASNET_SEGMENT=smp
export CHPL_COMM_DEBUG=1
export CHPL_TARGET_CPU=none
```

```sh
chpl test/release/examples/benchmarks/hpcc/ra.chpl -O -s useOn=true
```
>```
>internal error: UTI-MIS-0923 chpl version 1.26.0 pre-release (596bf2e08c)
>```

```sh
chpl test/release/examples/benchmarks/hpcc/ra.chpl -O -s useOn=true --devel
```

>```
>inlinable function call in a function with debug info must have a !dbg location
>  %10 = call i32 @get_chpl_nodeID() #0
>inlinable function call in a function with debug info must have a !dbg location
>  %13 = call i64 @chpl_rt_buildLocaleID(i32 %10, i32 %12) #0
>internal error: LLVM module verification failed [llvm/clangUtil.cpp:2112]
>```

**Comment by ronawho** [comment]
@mppf I have bisected this to https://github.com/chapel-lang/chapel/pull/18880, can you take a look?

**Comment by mppf** [comment]
@ronawho - ah the notorious #18880. The problem goes away with `-g` on the `chpl` command line. Before #18880 we were, in this configuration, not getting a `-g` on the computed compile line. After, we are now seeing a `-g`.

You can verify that with `printchplenv --all --internal` where we see `CHPL_TARGET_BUNDLED_COMPILE_ARGS` and `CHPL_TARGET_BUNDLED_LINK_ARGS`  include a `-g`.

I would imagine that we don't want to be getting a `-g` into the compilation process for the generated code just because we have `CHPL_COMM_DEBUG`. And so as a result we should not add / filter out these `-g`. Does that seem right to you?

**Comment by mppf** [comment]
The `-g` is ending up in the gasnet .pc file we are parsing to gather needed arguments.

**Comment by mppf** [comment]
@ronawho - PR #19186 filters out the `-g` from gasnet - let me know if that approach looks OK to you.
