### ISSUE TITLE
should we remove all implicit int(?w) -> real conversions?

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#19194]
Alternative to #7740

@damianmoz posted in https://github.com/chapel-lang/chapel/issues/18888#issuecomment-998362431 :

> The implicit conversion within a 32-bit floating point expression of a 32 bit integer (that goes nowhere near 2**31-1) to a real(64) totally screws up my algebra.

And I replied with https://github.com/chapel-lang/chapel/issues/18888#issuecomment-999096108 :

> 
> It might be possible to stop doing `int(32)` -> `real(64)` implicit conversions, but we have `int(64)` -> `real(64)` conversions (the spec says this is an exception for convenience) and we have `int(32)` -> `int(64)` conversions. It seems likely (but I am not certain) that we need the implicit conversions to include transitive relationships, so if we have both of these, we probably need `int(32)` -> `real(64)`.
> 
> In my opinion though we could remove the `int(64)` -> `real(64)` conversions as long as we can keep param conversions for it (where we allow a literal like `1`, which has type `int`, to implicitly convert into a `real`). We are trying to stabilize the language though (and stop doing breaking changes like this).

This issue is a place for more focused discussion on the question of whether or not we should keep int->real implicit conversions.

**Comment by damianmoz** [comment]
I do not want to cause breaking changes.

From a selfish perspective, a fix whereby such things like this are flagged with a (user-selectable) warning from the compiler would likely be adequate for my needs.  Others may have different needs.

My 2c.

**Comment by mppf** [comment]
@damianmoz - right, but if it is a compiler flag then don't we have this problem I brought up in https://github.com/chapel-lang/chapel/issues/18888#issuecomment-1005705301 --

> > The whole idea is that it actually **is** a compiler flag and that it applies to modules being **include**d (or **use**d) but which I did not write.
> 
> In that case, wouldn't you either:
>  a) expect the standard library and any 3rd-party modules you use to adhere to this standard, or
>  b) be unable to use the standard library or 3rd-party modules?
> 
> If it's (a) then it seems to me that you are actually arguing for a language change. If it's (b) then I don't see how the idea is workable because I wouldn't expect you would want to take on implementing your own standard library.

**Comment by bradcray** [comment]
What if, either:

* rather than a compiler flag, one `use`d/`import`ed a module to opt into this behavior for a given chunk of code to control where the warnings happen?
* the flag only applied to source files named on the command-line?

The former feels more flexible and precise, though clunkier to implement (and maybe it would be too annoying to a user like Damian to have to apply it to every module he wrote?

The latter is easy to implement, but a bit more of a big hammer (in both the good and bad ways).

**Comment by mppf** [comment]
@bradcray - yeah that's a good point and maybe something we'd want to handle with the generalized attribute syntax (#14141). I suppose I have some nervousness with the `int` -> `real` conversions nonetheless - if it's a challenge for @damianmoz will it be a big problem for other users too?

**Comment by bradcray** [comment]
> I suppose I have some nervousness with the int -> real conversions nonetheless - if it's a challenge for @damianmoz will it be a big problem for other users too?

I'm fine reconsidering them as well, though I think I'd want some way to opt into them (ideally, we'd implement all coercions as module code, and then I could use a module to opt into them, e.g.).  IIRC, C's willingness to convert between them (and maybe C#'s as well?) is why we enabled them?

**Comment by damianmoz** [comment]
I am pretty easy. I would say "whatever suits you" but I do not understand exactly the level of work that I am effectively asking you to do and do not want to impose. Is there anybody else with this same issue who can provide some input.

I can handle challenges.

Basically, it needs to be possible to be sure that what looks like an expression that uses only 32-bit floating point (FP) arithmetic will be 32-bit FP arithmetic (with the speed advantages that this brings and known accuracy that it implies). If I have to be prompted to cast integers back down to 32-bit floats myself, that's cool. Several, i.e. at least 3 years ago, that was awkward because when a **param** integer was cast to a 32-bit float, the result was no longer still a **param**. But @mppf fixed that issue quite a while ago.

And similarly for 64-bit FP arithmetic (when and if 128-bit FP arithmetic is in the mix).

I would have thought that some of that same logic would be needed to help ensure that you can vectorize with the faster vector instructions made up of 32-bit floats. Or am I wrong?

I am not fan of what C does with conversions although that reasoning is rooted in the dim dark past - 40 years ago when we did not have the rigour of the IEEE 754 standard on which to fall back or FMA units to help us. I always check the assembler when I write C to ensure that there are no unnecessary conversions happening and that my 32-bit arithmetic IS just that.

Thanks heaps.

**Comment by mppf** [comment]
In conversation with @bradcray - we didn't reach a conclusion about what we should do here - but are interested in exploring further a design like this:
 * by default, there would only be implicit numeric conversions for params (i.e. not for variables with runtime values)
 * the standard library would be written with that assumption
 * it would be possible to `use` a module that brings in more relaxed rules by adding some implicit conversions (in particular we might create two such modules; one that creates the current rules; and another that 

The next step is to try doing some testing with the implicit non-param numeric conversions disabled to see what kind of cases this change would impact.

**Comment by bradcray** [comment]
> the standard library would be written with that assumption

FWIW, I don't know that this would need to be the case as long as it did not "infect" user code.  E.g., a standard library module (or even an internal one) should be able to `use`/`import` the module that provides the implicit conversions as long as it doesn't do so publicly.

Jumping back to the comment by @damianmoz that led to this issue from the OP:

> The implicit conversion within a 32-bit floating point expression of a 32 bit integer (that goes nowhere near 2**31-1) to a real(64) totally screws up my algebra.

Damian (or @mppf), I went back to the original issue and saw the anecdote about it being the one time you were really swearing at Chapel (which I completely do not believe, BTW :D ), but did not come away with a crisp mental example of how you were bitten / surprised by this.  I can completely believe it's a real problem, and feel a bit nervous about the 32-bit int->real conversions as well, but was curious whether you could create an example that showed the surprise/swear-worthy situation just to make it a bit more concrete to me.  (If it's on that issue and I just overlooked it, feel free to just point me in the right direction).

**Comment by damianmoz** [comment]
Maybe I am a bit slow, but you mention:
> by default, there would only be implicit numeric conversions for params (i.e. not for variables with runtime values)

Does that mean only for expressions containing only **param** identifiers or am I misreading it?.

Can you point me at the conversion module that gets **use**d so I can wrap my head around it about what happens.

If the above is what I think it is, I can then give it the thumbs up.  Thanks.

**Comment by damianmoz** [comment]
You mention the anecdote:
> it being the one time you were really swearing at Chapel (which I completely do not believe, BTW :D )
May-beeeeeeeee. Maybe I was just swearing at myself while I was saying "RTFM Damian you sausage!!!" It was more the fact that it took me so long to figure out what I was going on that was annoying.

Anyway, in answer to your question, consider
```chapel
const PrettyWellNear100PerCentOfTheTime = 100.0:real(64) - 0x1.0p-45;
const e32 = e:real(32); // I wish this only worked with an explicit 'use'

const i = (1 << 20):int(32);
const fi = i:real(32);
var x = e32 * i;
var y = e32 * fi;

writeln("x :", x.type:string);
writeln("y :", y.type:string);

assert(x.type == y.type);
```
Unfortunately, `x` above is a 64-bit floating point number and its computation is also done in 64 bit precision.

The integer `i` is contained in the set of **real**(32) numbers. The fact that
```chapel
assert((i:real(32)):int(32) == i)
```
is not always true is perfectly acceptable according to IEEE 754 rules. It is precision true if abs(i) < (2^23-1) and outside that range, there are precise relative error limits and they will never exceed 2^(-23) in relative terms as the standard tells us. The standard also says that the conversion, in terms of floating exceptions, never overflows, never underflows, never is invalid, never causes a divide by zero, although it may technically be inexact.

The variable `x` has a type of **real**(64). I never mentioned this level of precision.It is highly problematic that the arithmetic on the right hand side of the assignment is done using 64 bit floating point instructions. And the Chapel compiler never informed me that it was bumping the precision.

For _PrettyWell100PerCentOfTheTime_ the use of extra precision is redundant is totally redundant because integers in my programs hardly ever go above 2^20, let alone 2^23. Unfortunately, I cannot get away with **Int**(16).

I do not want the implicit conversion rules changed because that would be a 'breaking' change. Besides, something like CHAMPS probably deals with integers up around the 100,000,000 (the number of elements in a aerodynamics simulation or about 2^28 or). So they probably rely on it.

But it would be really useful to have a flag to the compiler which lets it tell me when it wants to use what is technically an unnecessary precision (in terms of IEEE 754) when using a 32-bit integer in a 32-bit floating point expression. Then I can do my own conversion to a **real**(32) beforehand to ensure consistent precision and consistent arithmetic and errors. Not quite as clean, but still perfectly clear.

The original example was a bit more complicated, but not much more. Why it took me so long to appreciate it is just down to the fact that I had skipped over those implicit conversion rules when I first saw them. They are now imprinted on my forehead but I am sure I will forget them occassionally.

**Comment by damianmoz** [comment]
Looking at the table for implicit conversions which is behind all of this, it needs some extra words along the lines of:

1. the behavior is not generic, the conversion applied to an **int**(32) is exact but that on an **int**(64) is not,
2. the implicit conversion behavior **int**(32)->**real**(64) agrees with pretty well no other common language.

The error behaviour of an **int**(w) in an otherwise **real**(w) expression relative to the underlying precision of the common real(w) type is not consistent. Unless you are careful, you cannot use a **real**(32) version of an algorithm to debug the **real**(64) version (or a **real**(128) version).

Chapel's implicit conversion rules disagree with those of Fortran, C, C++ all of whose rules are symmetric. I think Julia does what Chapel does. Julia has a `promote_rule` concept. No idea how it works but I assume it can be made to do whatever you want. Can you over-ride the default stff? Not sure  Swift was contemplating something like Julia's promote_rule but there is no decision to date that I can see. Note that C/C++ has FLT_EVAL_METHOD which I find frustrating but which has sound reasons in history. And at least it is documented and has consistency. A promote_rule in Chapel seems like too much work for too little return, especially as the usefulness is limited. A warning from the compiler is probably more than sufficient.

With (2), those refactoring from Fortran or C or C++ or Ada to Chapel will not love you. They could be chasing their tail unnecessarily when the results of an algorithm in Chapel behaves very differently to that from where they came.

When you support **int**(128) and **real**(128), you will have to change the table which is a breaking change in some circumstances.

The IEEE 754 standard says "anything goes" with implicit conversions (pretty much) so you are safe there. They are concerned with implementations of the standard which is reflected in the same language on different hardware, not of different languages on the same hardware implementation. That might be a little bit loose but it is close enough for the purposes of this discussion.

**Comment by mppf** [comment]
@damianmoz - thanks for your thoughts.

> Maybe I am a bit slow, but you mention:
> > by default, there would only be implicit numeric conversions for params (i.e. not for variables with runtime values)
> 
> Does that mean only for expressions containing only **param** identifiers or am I misreading it?.

Yeah, or literals or functions returning `param`.

> 
> Can you point me at the conversion module that gets **use**d so I can wrap my head around it about what happens.

It doesn't exist yet so I can't point you to it. We are considering it as a design possibility.

> 
> 1. the behavior is not generic, the conversion applied to an **int**(32) is exact but that on an **int**(64) is not,
> 2. the implicit conversion behavior **int**(32)->**real**(64) agrees with pretty well no other common language.
> 

It sounds like what was really bugging you here is that the conversion situation between `int(32)` -> `real(32)` and `int(64)` -> `real(64)` is inconsistent. There are two ways of fixing that:
 1. Removing all int -> real conversions (that aren't for params)
 2. Adding `int(32)` -> `real(32)` conversions

> 
> ```
> Specifically, the implicit conversion rule says is it computed as
> ```chapel
> const t = (x * k:real(64) * y * z):real(32);
> ```
> but does this then mean that the computation is then done as
> ```
> const t = (x:real(64) * k:real(64) * y:real(64) * z:real(64)):real(32);
> ```

Yes. Looking at compiler logs for a variant of your example, I am seeing 3 64-bit multiplies. Note that if that weren't the case, you would have `t` already inferred as `real(32)` without the cast.

If what you want is "I'm working with `real(32)` so please stay in `real(32)` until I tell you otherwise" then removing the implicit conversions is what would get you there. As I described in https://github.com/chapel-lang/chapel/issues/19194#issuecomment-1036611052 , we are considering switching to a design where you get no non-param implicit numeric conversions by default, but can `use` modules to opt in to more implicit numeric conversions.

**Comment by damianmoz** [comment]
@mppf mentioned

> If what you want is "I'm working with real(32) so please stay in real(32) until I tell you otherwise"
> then removing the implicit conversions is what would get you there.

Yes please. When my programs says **real**(w), I do not expect any sized integer **int**(j) to interfer, whether `j` is 16, 32, 64 or 128. This follows the rule of "never surprise the user" by giving them something they did not request. It also agrees with Fortran rules and  C/C++ (FLT_EVAL_METHOD=0 which has been the default for a while and what many have used since its arrival two (?) decades ago). See Clause 1 of 6.3.1.8 of the latest C23 draft which has the concept of a `common real type` - sorry, I cannot remember section number in the older versions.

That would solve the immediate problem but until you come up with those **use** modules. some people will be inconvenienced.

Your new design would also allow you tell inform the user of the consistency (or lack thereof) and accuracy that their chosen implicit chosen rules deliver.

The current rules also mean that you see the following inconsistent behaviour for `x`, `y` and `z` all **real**(32):
```chapel
param k = 2; // obviously exact
// const k = 2; // try this alternative
const t = x * k * y * z;
```
will give you differently typed `t` depending on whether `k` is a **param** or a **const**. Even if you force `t` to be a **real**(32) by a cast of the entire expression,  the value in `t` will potentially be different, if only in the last binary digit from such a simple expression. But that error can be a huge issue if your prime aim is are chasing errors between different implementations.

**Comment by damianmoz** [comment]
For the record
>Removing all int -> real conversions

This is what I personally prefer (even with **param** expressions) but I am not going to force my ideas.

This is what Ada95 does and what Fortran IV did strictly.

I believe that is also what Ada 2005 or 2012 or 202x still do.

One can argue that this should probably be the baseline (even for **param** expressions).

**Comment by damianmoz** [comment]
Not that I am suggesting that it is needed now. But strong typing will be bound to rear its head sometime, e.g.
```chapel
type yards = new real(32); // syntax stolen from Ada
type metres = new real(32); // this is distinct from real(32)

var x = 1600.0:metres;
var y = 1760.0:yards
var z = x + y; // you want the compiler to reject this mixing of types
```
Such code helps avoid conflicting algebra between Imperial and Metric units.

No I do not need this. But somebody is bound to in the future.

**Comment by bradcray** [comment]
@damianmoz : As the language currently stands, we usually imagine representing such patterns using records, like:

```chapel
record yards {
  forwarding var len: real(32);
}

record metres {
  forwarding var len: real(32);
}
```

That said, I've wanted the ability to do this in a lighter weight way as well, so it may still lie in our future...  There's also a community team working on a units library that may help with this specific type of example (but wouldn't support arbitrary new type aliases, I believe).

**Comment by damianmoz** [comment]
I saw the discussion about units. And yes, I would normally do yards and metres like you said if I was ever going to write a piece of software that did not use consistent units.

The only reason why I mentioned strong typing in this context was to ensure that whatever decision is made to address this issue, i.e. #19184, should be made such that it does not preclude or even make difficult, any future implementation of strong typing at some time into the future. No point shooting yourself in the foot in 2025 if you can plan to avoid it now.

**Comment by bradcray** [comment]
> > Removing all int -> real conversions
> 
> This is what I personally prefer (even with param expressions) 

I spent some time stewing on this last night, and wanted to give my reason for liking the coercions for params.  We already get people requesting that `3 / 2` might result in a `real` with value `1.5` rather than an `int` with value `1`.  While we generally haven't entertained that direction, I find myself very happy that I'm able to write expressions like:  `(x + y) / 2` (for real `x` and `y`) rather than having to either write `(x + y) / 2.0` ("I'm finding an average, so am dividing by precisely two things, so the extra precision seems pedantic and a little misleading") or `(x + y) / (2: real)` (similar argument).

Of course, this is also why I like to be able to write:  `(+ reduce [i in 1..n] f(i)) / n` rather than `(+ reduce [i in 1..n] f(i)) / (n: real))` for non-param `n`.  But as Michael [mentioned above](https://github.com/chapel-lang/chapel/issues/19194#issuecomment-1036611052), I'm definitely open to exploring the possibility (including the param case for consistency) to see how good or bad it feels.

**Comment by damianmoz** [comment]
Just summarizing, there are two concepts here:
a)      Type-safe as in Ada95 for 25 years, and Swift more recently,
b)      common real type as in C/C++ since C99 and Fortran since Fortran77.

On Tue, 15 Feb 2022, Brad Chamberlain wrote:

> We already get people requesting that 3 / 2 might result in a real with value 1.5
> rather than an int with value 1. While we generally haven't entertained that direction,

Thanks goodness.  That's dangerous. Forget you ever heard about that.

> I find myself very happy that I'm able to write expressions like: (x + y) / 2 (for real x and y)

This is concise and very readable. I like readable. (50+delta)% of me agrees with you as long as the compiler is using the concept of common real type, i.e. if the type `x` and `y` are at most **real**(w), then the type of the expression is **real**(w).

> Of course, this is also why I like to be able to write: (+ reduce [i in 1..n] f(i)) / n

We are on the same page there. Even so, with Chapel today, if `f(i)` was of type **real**(32), I would have been forced to append ":**real**(32)" to the above if I had wanted the result to be a **real**(32). So I would have lost that nice readability. In terms of potential errors, the summation already has an error of `n*epsilon`, and the `common real type` approach to the average makes the error `(n+1)*epsilon`. On the other hand, Chapel's implicit integer conversions keeps the total error at `n*epsilon`. For most practical problems that I have seen in my clients over the years, that would buy very little in practice where `n > 4` most of the time. So I cannot see the point of the Chapel implicit conversion. And in your earlier example, the Chapel implicit conversion has no advantage over the common type type because the division is by a power of 2 and 2 < the number of bits in the significand of a **real**(32). The use of the word mantissa in the Chapel docs is wrong. It is the significand.

> But as Michael mentioned above, I'm definitely open to exploring the possibility
> (including the param case for consistency) to see how good or bad it feels.

How about having (and I feel guilty about suggesting something which means more work for the team):

- common real-type as the default option selectable on the command line
- type-safe as an alternative option on the compiler command line; and
- introduce an optional warning when a possible loss of precision in an integer conversion is seen.

I think that the first of these means that you get the behavior you like for params and most people see no change and those existing Chapel rules which cause grief go away.

The second option means you get to appeal to a larger cross section of potential users, even though that group is not overly large. When I am feeling overly cautious, I would joint that club.

The third item there means that when the common real type is real(?s) and an int(?t) is seen in the expression where s <= t, then the user is warned that there is a about a possible loss of precision.

**Comment by mppf** [comment]
If we have different modules with different implicit numeric conversions, then when we call a generic function (e.g. `proc f(a, b) { return a + b; }` in another module, should the `+` there be aware of the implicit numeric conversions from the point of instantiation?

That makes the most sense to me because at the call site, if, say, we can do `int`  `+` `uint` due to implicit conversions, then so too should `+` work inside of `f`. But, what if the module defining `f` enabled some implicit conversions? How can we combine the information from its defining module and the point-of-instantiantion?

Also, I *think* this applies to things other than `+`; e.g. if we have something like this:

``` chapel
module Library {
  proc doSomething(arg) {
    helper(arg);
  }
}
module Program {
  use EnableUintIntImplicitConversions;
  use Library;
  proc helper(arg: int) { } // when helper is called, it is in Library
                            // but it is passed a uint and we have enabled int->uint here
                            // so I think this should compile?
  var x: uint;
  doSomething(x);
}
```

**Comment by bradcray** [comment]
Not directly related to the previous few comments:  During the past week since my conversation with Michael, I've been keeping an eye out for cases where I rely on coercions today, in order to consider what it would be like if they didn't exist, or if I had to take an additional action to enable them (e.g., `use` a module providing the coercions).  It's mostly felt like it would be a major hassle to me, as I find I rely on int(64)->real(64) coercions all the time.  That's not to say that I think we shouldn't continue to wrestle with this issue or think about what a "no (or fewer) coercions by default" world would look like.  But I'm less optimistic about how happy I would be in such a world than I was a week ago.

This led me to wonder whether—for someone who wanted to disable all coercions—we might take the approach of having a module that, upon being used, disabled them rather than enabling them.  E.g., `use NoCoerceMode;` would disable them for a given scope or module.  This is not perhaps not quite as attractive as the "use a module to enable them" approach in that I think the `NoCoerceMode` module would be more of a "magic" module whose presence would change the compiler's behavior rather than a module containing code that defined coercions (which is what I had been imagining for the other mode).  But it would still have the benefits of making the choice visible in the source code.

Catching up with Damian's latest response, it's less opposed to coercions than I was imagining, which is encouraging.  

Damian, I think there's something you've been saying in various ways in various issues that I wanted to make sure is correct.  I believe the `int(32) -> real(64)` coercion is one of the cases that you find most appalling, is that right?  If we were to disable `int(32)->real(64)` coercions yet continues to support `int(64)->real(64)` coercions and `int(32)->int(64)` coercions by default, would your preference be to have:
a) int(32) coerce to real(32) (to provide similar behavior to the 64-bit case, yet in a way that preserved bit width
vs.
b) int(32) would never coerce to a floating point value?

If your answer is (a), my follow-up question is:  If int(32) had the option to coerce to int(64) or real(32) would you expect:
i) it would prefer int(64) since it preserves the integral nature of the value
ii) it would prefer real(32) since it preserves the bit-width of the value
iii) it would report an ambiguity
iv) don't care—would not write code that relied on either behavior

Damian, you suggest:

> common real-type as the default option selectable on the command line
> type-safe as an alternative option on the compiler command line;

and I want to echo something that Michael said earlier which is that the thing which gives me pause here is the reliance of command-line flags.  This is for a few reasons:
1) it feels like a big hammer in that it would presumably apply to all files (or maybe all files named on the command-line?  or maybe all files not part of the standard library?)
2) when reading Fortran code in the past, I've sometimes been confused about assumptions made in the code that it would be compiled with certain command-line flags to work properly, since that information isn't visible within the source code.
These concerns are what lead me to tend to prefer a module-based solution for opting into or out of behavior that changes the code's implementation.  That way if you hand me a printout of your program, I can reason about what it's doing without also needing a printout of your Makefile.  Does this concern and approach resonate with you at all?

> introduce an optional warning when a possible loss of precision in an integer conversion is seen.

We've talked for years about having a `--check-???` flag (not quite sure what to call it... overflow?  precision-errors?) that would check for cases when a cast or coercion occurred that lost information (e.g., downcasting `max(int(64))` to `int(8)` would trigger it; putting an `int` into `real` that couldn't represent the int would as well), but never implemented it.  I think this would be a nice sibling to the checks for array out-of-bounds accesses and nil pointer checks in terms of catching the next most frequent source of errors in code, and subtle ones at that.  Of course, it could also be an expensive check for codes that relied a lot on such conversions, so there'd be some question as to whether it should be on or off by default.  `--fast` would turn it off in any case.

This sounds like exactly what you'd want for this third bullet, right?  FWIW, I don't think this would be _terribly_ difficult to implement, but it's a feature that we've talked about more amongst ourselves than having users express a desire for, which is why it's languished (along with maybe the concern about performance impacts if it's on by default).

> The use of the word mantissa in the Chapel docs is wrong. It is the significand.

Everywhere, or in a specific place?  Would you be willing to open a separate issue for this?  I'm worried it will get lost if it's only mentioned in larger issues like this one?

**Comment by damianmoz** [comment]
I can handle disabling Coercions.  You might name them as:
```chapel
use TypeSafeRealExpressions;   // the same as your NoCoerceMode
use CommonRealTypeCoercions;   // real(w) items control coercion rules
```
The latter would keep me happy and might keep you happy if we were both working on the same code because you still get **int**(64)->**real**(64) conversions in an expression which is dominated by real(64).

The coercion int(32)->real(64) total destroys conventional error analysis and  goes back to the since-discarded across-the-board rule that Denis Ritchie introduced in C over 40 years ago of doing all floating point arithmetic in real(64). In the 90s, people realised the downside of that with newer hardware and  resulted in changes in C99 which now uses the concept of "common real type". Most current C/C++ compilers default to  rule which means a floating point expression with **real**(w) as the dominant **real** type coerces any **int**(?k) in the expressin to a **real**(w) irrespective of the value of `k`..

Implicit coercions are too easy to cause a mistake to go undetected.

If dummy Damian uses an **int**(32), he means **int**(32).  If I have such a variable in an expression with an **int**(64), then 9,999 times out of 10,000 it will be a Damian mistake or something forced on me by what comes out of some Chapel construct like a domain range. I do not want integers dictating how my floating point expressions are evaluated.

My preference is for the compiler to look at a real expression and deduce the common real type.

1)  if I want coercions, any integer should coerce to that common real type;

2)  if I want to be type safe and I have that option, then an integer can only be explicitly coerced. 
 
I can live without out (b), even though I feel that such an **option** would be  an asset to the Chapel compiler.
Even having a compiler option to warn against expressions which are not type-safe would be useful.

So my answer to your (a)/(b) choice is **not** (a) but I do not need to be so dogmatic as to demand (b), even though I think the option of (b) is an asset. And I am happy to choose (1) by a **use** statement rather than a
compiler option. Sorry, I always think `compiler option`. I will try and get out of that habit.

You mention
> about having a --check-??? flag for things like possible loss of precision

and then said
> This sounds like exactly what you'd want for this third bullet, right?

So, my answer is yes. But in your own time. No urgency.

I apologise on behalf of poor Fortran programs for your bad experience with Fortran programmers. Programs that need certain command line options to achieve correct performance should have comments buried within the code to say so. Some compiler makes used to have C$ lines for this purpose but they were very compiler dependent.

I said and then you referenced:
> The use of the word mantissa in the Chapel docs is wrong. It is the significand.

It is mentioned in
```
https://chapel-lang.org/docs/language/spec/conversions.html
```
I will open a separate issue for this over the weekend.

The Github spelling checker objects to the word Fortran. Maybe there is a message there!!

**Comment by bradcray** [comment]
I stumbled across this while looking for something else and am wondering if we could close it now.  Specifically, recent releases have gone the opposite direction, permitting any int to implicitly convert to any real, and it seems unlikely we'd back that all out at this point.

**Comment by damianmoz** [comment]
With some of the recent changes now making Chapel behave like other programming languages have done for decades, the need for this is less pressing.

However, it would be good to schedule the implementation of a warning into the compiler to highlight when implicit conversion of any type happens. The reason for this is that generally the compiler will do the work. But occasionally I screw up and that apparentlyt implicit conversion can turn into an explicit conversion instruction which 99.999% of the time, is definitely not what is desired. So it would be good to be able to highlight it to the programmer at compile time rather than make them pour through loads of assembler to find some unwanted **cvt...** instruction that are doing naughty things to code performance.

But as far as making the language more type strict, that will never happen. So it can be closed subject to the previous paragraph which probably means opening another issue which is the addition of the warning message in the compiler.

**Comment by bradcray** [comment]
> However, it would be good to schedule the implementation of a warning into the compiler to highlight when implicit conversion of any type happens. 
> 
> which probably means opening another issue which is the addition of the warning message in the compiler.


I agree.  Let's move that "opt into implicit type warnings" feature request to a new issue (if it doesn't already have one) rather than re-interpreting this issue as that request, or keeping it open as a reminder.  Damian, would you like to open that, as its main champion?

@mppf, give a shout if you think this issue should be re-opened for any reason that I've missed.
