### ISSUE TITLE
Should we deprecate "is type subtype of" querying operators?

### ISSUE THREAD

**Issue by stonea** [chapel-lang/chapel#19239]
Currently types can be compared using the `<`, `<=`, and `>`, and `>=` operators to see if one type is a subtype of another.

On the one hand, using operators to express this seems kind of clever but on the other it may not be clear to end-users what these operators do. I think we should deprecate these operators in favor of using functions. The types module already has `isSubtype` and `isProperSubtype` functions and spelling it out seems clearer to me.

@mppf brought to my attention that one context to think about is using these operators in a `where` clause for a generic function (where maybe we want things to be more concise):

> It used to be that you could write `proc f(arg: integral)` or proc `f(arg: ?t) where 
 t:integral` but at some point I needed `:` to behave as the usual cast in a where clause so deprecated that. When I did, I changed these to `proc f(arg: ?t) where t <= integral`. Arguably having to write `proc f(arg: ?t) where isSubtype(t, integral)` is wordy for this use case. One thing to note is that some programmers might think that this is the only reasonable way to write a generic function (e.g. if they don't think of generic types and concrete types as the same category of thing).

**Comment by bradcray** [comment]
I'm generally supportive of this, though before making a final call, I'd be curious to see where we rely on such comparisons today and how they'd look without the operators.  Finding those cases should be easy (simply remove the operators or have them print a compilerWarning() and run paratest) and is something I could do myself if someone doesn't beat me to it (I have a paratest running already currently).

**Comment by stonea** [comment]
Hi @bradcray I have a draft PR that shows what the falllout would be for implementing this change: https://github.com/chapel-lang/chapel/pull/20466/files

There are a handful of places in our module code and handful of tests that would need to be updated. Nothing strikes me as being particularly harder to read or understand by using `isSubtype` in place of `<=` though.

One oddity in handling this is that the type comparison operators are handled by the compiler directly in resolution rather than in module code so this PR does require issuing the warning directly from the compiler.

Would you be fine with me proceeding with this PR?

**Comment by bradcray** [comment]
Seeing the diffs, I feel pretty neutral about this.  I don't think the changes are terrible, though they also make me realize that `isSubtype(x, y)` doesn't really make it particularly clear which direction the query is going (whether x or y is the type being queried).  This is obviously a pre-existing issue since `isSubtype(x, y)` already exists.  With `<=`, the directionality is clearer, though there's still arguably a learning curve as to whether the parent or child type is "greater than / less than".

In contrast, `x.isSubtype(y)` reads more clearly, though I don't think (?) we have the ability to create a type method "on any type" today, unfortunately (and that would require deprecating two things rather than one; and this would be a step in the right direction in any case).

I don't remember how unanimous vs. not the discussion about this was when we last reviewed it, but if there was any amount of hemming and hawing, I think it could be worthwhile asking the same "does this give anyone pause" question to the group as a whole (or potentially just to those who've written code that has used the comparison operators?).

**Comment by mppf** [comment]
> In contrast, `x.isSubtype(y)` reads more clearly

This would make another "special method", though, since a user can't write a method with that name anymore (at least, not a type method). Note though that `isSubtype` as well as the `<=` on types are supported directly by the compiler, so they don't really exist in module code at all. As a result, the lack of a type method "on any type" is not a major implementation challenge. (The special method issue is more concerning, IMO).

I do like the way that `isSubtype` vs `isProperSubtype` make the common thing shorter, vs. `<=` and `<`.

I don't personally feel strongly either way on this, but I was imagining that removing the operators would make Chapel less weird / special. I am curious if we have looked to see if any other languages offer more than `==` and `!=` as comparison operators on types.

**Comment by bradcray** [comment]
> I do like the way that isSubtype vs isProperSubtype make the common thing shorter, vs. <= and <.

I'm not following... how are they shorter?

> I am curious if we have looked to see if any other languages offer more than == and != as comparison operators on types.

Good question.

> This would make another "special method", though, since a user can't write a method with that name anymore

Yeah, I called that out in #20495, though it hadn't occurred to me yet when commenting above.  As a slight correction, I think it would prevent a user from writing a type method with that name and signature, not a normal method or a type method with a different signature (right?)  So if we were going to do it, "before 2.0" would be the ideal time.

As with a lot of these things, if it's built into the language and not a name+signature that seems likely users would want (which seems like the case to me), it wouldn't give me huge pause, particularly since I think type methods are written less frequently than others.

> Note though that isSubtype as well as the <= on types are supported directly by the compiler, so they don't really exist in module code at all.

The implementation is, but the `isSubType` symbol is defined in `Types.chpl`, isn't it?  (and, checking, it appears that the operator forms are as well?).  That said, since `Types` is an automatic module, it's hard to avoid (which could be a good thing if we do want to reserve the pattern since code wouldn't be sensitive to whether or not that module was used).

**Comment by mppf** [comment]
> > I do like the way that isSubtype vs isProperSubtype make the common thing shorter, vs. <= and <.
> 
> I'm not following... how are they shorter?

They're not shorter. I was saying, one usually wants `isSubtype`, and it's nice that it's shorter than `isProperSubtype. Vs, with the operators, one usually wants `<=`, but that is longer / more complex than just `<`.


> The implementation is, but the `isSubType` symbol is defined in `Types.chpl`, isn't it? (and, checking, it appears that the operator forms are as well?). That said, since `Types` is an automatic module, it's hard to avoid (which could be a good thing if we do want to reserve the pattern since code wouldn't be sensitive to whether or not that module was used).

Yes but those exist only for documentation. The compiler ignores them. (That is what `pragma "docs only"` is doing).

**Comment by stonea** [comment]
> I am curious if we have looked to see if any other languages offer more than == and != as comparison operators on types.

Doing some quick Google searches here's what I see for various languages (when trying to figure out how to determine if something is a subclass or something else):

* Python: `a.issubclass(b)` or `issubclass(a, b)`
* C++: No real good way IMO: use `dynamic_cast<B*> aObj` and see if it succeeds
* Java: Use `aObj.class.isAssignableFrom(B);` (Java also has an `instanceof` operator)
* Javascript: Use `A.prototype instanceof B`
* Swift: `obj is MyClass`

Ruby and Julia have operators that look simliar to ours:
* Ruby does have `<` and `<=` that returns true for subclass relations (https://ruby-doc.org/core-1.9.3/Module.html#method-i-3C).
* Julia has a `<:` operator that means "is a subtype of" (https://docs.julialang.org/en/v1/manual/types/ search for `<:`).

So I'd say there's some precedent for having operators like `instanceOf` or `isa` or `is` these operators read as keywords though and not symbols.  Having something that looks like less-than does exist in Ruby and Julia so it's not unheard of.

Personally I'd rather have things spelled out than using something like `<` or `<=`.

I do think `x.isSubtype(y)` looks nicer than `isSubtype(x, y)` but:

* It's not something I'd want to hold up our module stabilization deadline over, and also
* I think we'd still want to get rid of `<`, `<=`, etc.
* I think most people when seeing some function that reads like `isBinaryQuery(operandA, operandB)` would assume that `operandA` is supposed to be the `lhs` and `operandB` is the `rhs` so I don't think `isSubtype(x,y)` is really all that confusing.

**Comment by bradcray** [comment]
> They're not shorter. I was saying

I see where I was mis-parsing now, thanks for clarifying.  I agree that it's nice that the common case is shorter when spelled out; I'm not sure the one vs. two character operator makes that feel like a downside to the operator-based approach to me per se.

> Yes but those exist only for documentation. The compiler ignores them. (That is what pragma "docs only" is doing).

Got it, thanks.  I didn't read carefully enough to notice the pragma (obviously).

Andy, thanks for the check on what other languages do here.  Some of the cases you mention (C++ was the one that caught my eye, but it made me think others may be this way too) are less queries about the types and more queries about the objects themselves, right?  (am I right that our queries we're talking about here are for types only?)

FWIW, I like the Julia approach in that since `:` means 'type specification or cast' in Chapel, it more visually links the comparison back to types.  But downsides include adding more operators that we haven't been wanting to use in more general cases rather than reusing existing ones.  So I think if we were to keep an operator-based approach, I'd probably stick with the ones we've got rather than switching.

I also understand that those commenting on this issue remain mostly in favor of dropping the operators altogether.  I think the next step here is to get more eyes on the prototype PR or this issue and take a straw poll to confirm the previous decision, seeing the diffs in front of them.

**Comment by stonea** [comment]
I sent an email out to the group to ask for final feedback and so far haven't heard anything. 

Brad and I talked about this "offline" and I'm going to proceed with the change (sooner rather than later so there's a little bit of "bake time" before code freeze).

One lingering question we both had is why these get handled by the compiler in resolution rather than by the module code. @mppf do you happen to remember why that is? Is it for some optimization purpose or was it that because at the time we first wrote this it wouldn't have been possible to have module code handle it (or is that still the case?)

**Comment by stonea** [comment]
> One lingering question we both had is why these get handled by the compiler in resolution rather than by the module code. @mppf do you happen to remember why that is? Is it for some optimization purpose or was it that because at the time we first wrote this it wouldn't have been possible to have module code handle it (or is that still the case?)

Ah, looks like PR (Brad just pointed out to me) answers that question: 

https://github.com/chapel-lang/chapel/pull/10865

"These are not handled in overloads in ChapelBase (say) because then it would not be possible to use them with generic types"

**Comment by mppf** [comment]
Yes, and AFAIK, that constraint is no longer true, and now they could be handled in ChapelBase. However I don't think changing that by itself is worthwhile.

**Comment by bradcray** [comment]
> I don't think changing that by itself is worthwhile.

Maybe not worthwhile in the sense of "a priority to do immediately", but it does feel like a nice thing to do ultimately... to replace specialized compiler-specific code into just normal module code.

**Comment by stonea** [comment]
This is complete now as of merging this PR: https://github.com/chapel-lang/chapel/pull/21108
