### ISSUE TITLE
[Library Stabilization] round enum in BigInteger conflicts with round function in Math

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#19303]
``` chapel
use BigInteger;
use Math;

var x = round(1.5);

writeln(x);
```

```
$CHPL_HOME/modules/standard/BigInteger.chpl:199: error: symbol round is multiply defined
$CHPL_HOME/modules/standard/Math.chpl:1054: note: also defined as a function here (and possibly elsewhere)
```

This seems like something we should fix.

**Comment by mppf** [comment]
@lydia-duncan - FYI, I've just ran into this when working on https://github.com/Cray/chapel-private/issues/3108

**Comment by lydia-duncan** [comment]
Does using qualified naming avoid the conflict?

I don't think language level changes are the right solution if qualified naming avoids it - either we should rename the BigInteger enum or accept that there is potential for libraries to conflict and recommend using qualified access to distinguish it.

The Math round function is in the maybe column for if we should continue to include it by default.  It sounds like something that is very important to Damian so it may continue to be included, but if we do make it something that a user has to `use Math` in order to access, that changes the conflict into a normal one and one that is solvable through normal means.

**Comment by mppf** [comment]
> Does using qualified naming avoid the conflict?

Yes, AFAIK, but I haven't tried it much.

> I don't think language level changes are the right solution if qualified naming avoids it - either we should rename the BigInteger enum or accept that there is potential for libraries to conflict and recommend using qualified access to distinguish it.

Right, I wasn't proposing language level changes for this - more that I noticed it while investigating language changes.

> The Math round function is in the maybe column for if we should continue to include it by default. ... if we do make it something that a user has to `use Math` in order to access, that changes the conflict into a normal one and one that is solvable through normal means. 

Right -- or we could provide a way to adjust the implicit use of ChapelStandard https://github.com/chapel-lang/chapel/issues/19167#issuecomment-1049986810 - e.g. if you wrote `use ChapelStandard except round` maybe that could work & the compiler would leave out the implicit `use ChapelStandard`.

**Comment by lydia-duncan** [comment]
> Right, I wasn't proposing language level changes for this - more that I noticed it while investigating language changes.

Sorry, thought that was what you meant by saying:

> But, this problem can be solved by adding another shadow scope for the implicit use of the standard library

**Comment by lydia-duncan** [comment]
> or we could provide a way to adjust the implicit use of ChapelStandard [#19167 (comment)](https://github.com/chapel-lang/chapel/issues/19167#issuecomment-1049986810) - e.g. if you wrote `use ChapelStandard except round` maybe that could work & the compiler would leave out the implicit `use ChapelStandard`.

I think that would be a reasonable addition, yeah

**Comment by mppf** [comment]
> > Right, I wasn't proposing language level changes for this - more that I noticed it while investigating language changes.
> 
> Sorry, thought that was what you meant by saying:
> 
> > But, this problem can be solved by adding another shadow scope for the implicit use of the standard library

Right, I have been considering adding this shadow scope for other reasons as part of the language change I'm investigating and it would happen to solve the problem here. Hope that helps.

**Comment by mppf** [comment]
> either we should rename the BigInteger enum or ...

IMO we should rename try not to create symbol name conflicts within the standard library; after all we control all of the names.

**Comment by lydia-duncan** [comment]
I'm not against that as a goal and think it would be reasonable to rename the BigInteger enum (though I'm sad we're doing it again), but I'm uncertain about how proactive we should be on that front - there are a *lot* of symbols that will potentially be included as part of the standard libraries.  But maybe that should be a separate issue, leaving this one to focus on the particular instance?

**Comment by damianmoz** [comment]
I was waiting for that clash to raise its head. But as my knowledge on BigInteger is less than nothing, I abstained.

Are the 5 rounding directions defined by the IEEE 754 sufficiently general or important that there is a common definition. Having definitions for the same concept in multiple places goes against the whole concept of re-usability.

While floating point rounding probably does not belong in the language proper, it also applies to integer operations so maybe a generic and global **enum** is warranted. That answer is above my pay grade.

The names round() and truncate() (or trunc()) have been around as routines for at least 50 years. Why somebody would choose it as an enum, when (I believe) there was already an enum called Round for the same task, is beyond me.

Lots of fundamental questions in this one.

My 2c. Or maybe 1c.

**Comment by lydia-duncan** [comment]
> Why somebody would choose it as an enum, when (I believe) there was already an enum called Round for the same task, is beyond me.

The enum with capitalization in BigInteger was deprecated in favor of the uncapitalized version for consistency with the naming of other enums in the standard module.  The original enum was added to enable choosing which GMP division functions to call instead of defining individual division methods for each style of rounding.  It looks like GMP only provides three rounding directions - ceiling, floor and truncate (see https://gmplib.org/manual/Integer-Division).  Since GMP has been around for a long time, I don't think they're going to add additional ones at this point, but that doesn't mean we can't provide our own since this module is intended to be a Chapel Big Integer rather than necessarily tied to GMP (they just won't necessarily be as optimized and performant if we do)

> Having definitions for the same concept in multiple places goes against the whole concept of re-usability.

I think that's a fair point and something I was toying with myself.  However, the use in BigInteger is to solely to combine operations together (division and rounding) rather than to convert an individual number (especially since BigIntegers are integers rather than reals).  We've talked a little bit about the potential for defining a BigReal or something down the road (a floating point number that is by definition larger than could fit into a standard real today) and I would imagine that module/type would support an explicit round method on it.

**Comment by damianmoz** [comment]
Given
> The enum with capitalization in BigInteger was deprecated in favor of the uncapitalized version for consistency with
> the naming of other enums in the standard module.

As I mentioned, with names like **round**() being around for 50 years, it was bound to cause an issue. Decisions like that given nomenclature guidelines a bad rap amongst actual real-world users.

You mentioned:
> We've talked a little bit about the potential for defining a BigReal or something down the road (a floating point number
> that is by definition larger than could fit into a standard real today) and I would imagine that module/type would support
> an explicit round method on it.

Please do not. Bury that idea. Even a double-double type has serious issues and massively complicates floating point. Thank goodness we are finally starting to see **real**(128) in some processes with even more planned.  

Implementing a **real**(128) (and a **real**(256) in software or hardware (if the underlying processor supports it) would be infinitely more useful. If in software, it would have to follow all the IEEE rules. That would also require that there exists integral types with the same number of bits.

That said, there are lots more higher priority things in Chapel than (software) **real**(128) (and **int**(128)) out there. And any higher precision is even lower down the list.

**Comment by jabraham17** [comment]
In a recent offline discussion, we decided to rename `enum round` in `BigInteger` to `enum roundingMode` to avoid this name conflict
