### ISSUE TITLE
I/O module: assertEOF and atEOF

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#19316]
`assertEOF` is documented, while `atEOF` is not.  `assertEOF` will check if the channel has reached the EOF and will halt if it has not.  `atOEF` is inherently race-y, which at the time made us wary of exposing it to users, leading to the creation of `assertEOF`.

Note that C has an equivalent, `feof`, which tests the EOF indicator on a `FILE*`.  Python doesn't have an equivalent, so far as I could tell, but its `read()` function after reaching an EOF will always return the empty string, so that result can be used to perform a similar check.

The IO subteam believes that halting if the EOF has not been reached is not useful - it seems like we would want to continue to operate on the channel if we had not reached EOF yet.  We propose removing `assertEOF` and replacing it with a documented `atEOF` that warns users about races.  We could also potentially give `atEOF` a better name in the process.

This is still open for discussion, we are curious to hear other thoughts

**Comment by mppf** [comment]
One issue is that, if we actually use `atEOF` to write the loop, it won't work right.

Here is such a loop:

``` chapel
while (!reader.atEof()) {
  process(read(int));
}
```

In particular, with the input `1\n` (1 followed by a newline), what will happen is this:
 * `read(int)` consumes `1` and leaves the channel with the next thing to read being the `\n`
 * there is a `\n` available to read so `atEof` returns false
 * `read(int)` tries to read an integer from `\n` and starts by consuming whitespace. But it reaches EOF before it gets to an actual integer and so throws an error.

To address the problem, the loop could have some code to consume the whitespace (which some of the `readln` proposals would do). Also, in principle, it is possible to have `read(int)` consume trailing whitespace but I think that would be a big change from what I understand to be standard practice.

Is `atEof` still useful enough given the above issue?

**Comment by mppf** [comment]
If we keep it, should we spell it atEof / assertEof ?

**Comment by bradcray** [comment]
>  If we keep it, should we spell it atEof / assertEof ?

I feel as though @stonea has had the strongest and most informed opinions on capitalization of acronyms, so I'm tagging him here.

I understand the challenge of having an acronym early in a mixedCaseIdentifier like the terrible choice between `EOFIsMyFriend` vs. `EOFisMyFriend` vs. `EofIsMyFriend`.  For acronyms at the end of an identifier, it seems like the problem doesn't manifest so much making me prefer `atEOF` or `assertEOF` but I don't know whether there's a precedent for this (special casing acronyms at the end of identifiers) nor whether the potential for inconsistency would drive others crazy.

Rationalizing my preference, if I see `atXYZ`, I'm going to know that `XYZ` is an acronym, whereas if I see `atXyz`, it's unclear whether I should try to read `xyz` as a word or not (i.e., If I'd never seen EOF, would I be trying to make `eof` into an English word?)

Another approach would be to avoid acronyms when possible, and change this to `atEndOfFile` or `assertEndOfFile` and then let people do their own renamings  upon `use`/`import`.  :D

**Comment by stonea** [comment]
>> If we keep it, should we spell it atEof / assertEof ?

> I feel as though @stonea has had the strongest and most informed opinions on capitalization of acronyms, so I'm tagging him here.

If you asked me to vote on it today I'd choose atEof / assertEof just because that's the precedent I've seen in guidelines before and I'd rather have a consistently applied rule even if leads to slightly funky looking identifiers than having to guess every time I want to use or name a function.

Microsoft's .net guidelines say to capitalize the first letter of all acronyms except for acronyms that are only two letters:

  https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/capitalization-conventions

Google's convention (at least in this Javscript guideline) is to capitalize only the first letter:

  https://google.github.io/styleguide/jsguide.html#naming-camel-case-defined

Maybe there's some other guideline out there that has special rules for acronyms at the ends of words but I'm not aware of one. I also don't have a good idea to what extent Microsoft/Google/other companies actually follow these guidelines but having some sort of consistently applied naming convention seems sensible.

Of course we could set a new/different convention that acronyms should only have the first letter capitalized except when they're at the end of the word. My argument against that would be if people get used to typing EOF in all caps they'll tend to do it when it appears in the middle of an identifier as well.

**Comment by lydia-duncan** [comment]
Reopening so we do something with the unstable symbol in the future, but removing the 2.0 tag now that Jeremiah's handled it
