### ISSUE TITLE
Should we rename isFloatType (and friends) to something else?

### ISSUE THREAD

**Issue by stonea** [chapel-lang/chapel#19362]
This is something that came up during the types module review (https://github.com/Cray/chapel-private/issues/3034)

In Chapel we have the following query functions that ask something about a kind of a type:

```
  proc isPrimitiveType(type t) param    proc isPrimitiveValue(e) param    proc isPrimitive(e) param
  proc isNumericType(type t) param      proc isNumericValue(e) param      proc isNumeric(e) param
  proc isIntegralType(type t) param     proc isIntegralValue(e) param     proc isIntegral(e) param
  proc isFloatType(type t) param        proc isFloatValue(e) param        proc isFloat(e) param
```

Where each kind is defined as being one of the more specific types on the right hand side of this table:
```
  Primitives: nothing, void, bool, <anything numeric>, string, bytes
  Numeric:    <anything integral>, <anything float>, complex
  Integral:   int, uint
  Float:      real, imaginary
  Enum:       enum
```

For the most part I think the categories\names are good. The one that sticks out to me is 'float'. As a C programmer I'm used thinking of float as being a concrete (not a generic) type so I'm afraid some people might find this confusing.

During the module review meeting we discussed renaming this to 'isRealType' or 'isFloatingPointType' but didn't reach any consensus at the time.

**Comment by lydia-duncan** [comment]
What about `isPreciseType`?

**Comment by damianmoz** [comment]
It was mentioned that `isFloatingPointType` might be found to be confusing.

In fact, the name is technically correct so there is no confusion whatsoever. What looks like 'confusion' is likely a pragmatic choice made in C by either Denis or Ken  in the early 1970s and it would be good if we did not perpetuate such problems forever. I will document that issue later.

There is an IEEE 754 Standard for Floating Point numbers. It has been around for 35 years. Floating Point numbers of similar ilk but of varying persuasions have been around since the early 1940s with the work of Konrad Zuse. When you look at what he did and what Floating Point numbers are today, the similarities are uncanny.

Floating Point numbers (**real**(w)) numbers are a subset of Real Numbers which themselves are a subset of a Complex Numbers. The numerical behaviour of the individual components of a Chapel's **complex**(w) and the underlying component of an **imag**(w) is that of Floating Point numbers, although their net arithmetic operations follow the same rules as any Complex Number. So, while **complex**(w) and **imag**(w) are a subset of Complex Numbers, they are obviously not a superset of Real Numbers.

As the numerical behaviour of **real**, **imag** and **complex** is that of a Floating Point number as defined by IEEE 754,
the query of the type of `isFloatingPointType` is a very precise name.

I believe, but I was not around in IT at the time!!, that **double** is a contraction of **double float**. which has long since lost its ability to qualify the keyword **float**, even though **long** can still qualify the **int** type to create a type **long int**. You really need to go back to the late 60s where languages like Algol68 had a **real** type and a **long real** type to get the full history. Do we need to?

**Comment by damianmoz** [comment]
Apologies. I was reading probably reading my ancient notes wrongly. I found a better clue is some ancient photocopies at the back of those notes, namely from the FP11 floating point unit from the PDP 11/70 on  which C was being used under Unix in the late 1970s. While it refers to generic floating point operations, the manual said

> there `are  two floating-point formats, single-precision (F) and double precision (D)`. Note the **F** rather than **S**.
> It talks about conversions between `Double-To-Floating` and `Floating-To-Double`, as well as explaining mneumonics for
> LDCIF, LDCID, LDCLF nd LDCLD, the conversions of Single Integer to Single Float, Single Integer to Double Float, Long
> Integer to Single Float and Long Integer to Double Float respectively.

So **float** in C is just an abbreviation of the 32-bit floating point type. Allowing this abbreviation to have some sort of precedence over the overall concept from whence it came seems back-the-front.

**Comment by stonea** [comment]
> So float in C is just an abbreviation of the 32-bit floating point type. Allowing this abbreviation to have some sort of precedence over the overall concept from whence it came seems back-the-front.

On the one hand I'm sympathetic to this argument, the types that return true for `isFloatType()` are indeed encoded as IEEE floating point types and there's a temptation to ask why should we have to deal with C's baggage? On the other if there are small changes we can make to the language \ naming of things in the standard modules that make it less likely for folks to introduce bugs I think it's worthwhile considering.

I suppose today the only real harm would be if someone mistakingly use `isFloat(x)` when what they meant is `isReal(x)` (say in an assertion or a generic function). The problem case (in terms of the code not matching the programmer's intent) only occurs if x was a `complex`. I'm not sure if this sort of use case would come up often in practice or not though.

I think a more confusing situation (for folks coming from C) would be if we ever wanted to have a [builtin generic type](https://chapel-lang.org/docs/language/spec/generics.html#built-in-generic-types) named after this category (e.g. if we introduced a new generic type that meant both 'real' and 'imaginary'. We'd want the name of this type to match whatever name we use for today's `isRealType()` function). I guess if we feel this set of builtin generics is pretty well set we could forget about this concern though.

FWIW I think spelling it out as `isFloatingPoint()` / `isFloatingPointValue()` / `isFloatingPoint()` would be enough of a change to cause the hypothetical C programmer to second guess an unconscious reaction that this is dealing (solely) with Chapel's analogue to the C `float` type.

**Comment by damianmoz** [comment]
I only just noticed it. `isFloatType()` only returns **true** for **real**(?) and **imag**(?) types. In that case, I do not know what it means because while they behave numerically as an IEEE754 floating point number, then so too do ***complex**(?) types. The only difference between all 3 are the arithmetic rules (or non-rules) by which they abide. So I have no idea why the last of these is omitted. What use is this function is its current state?

I agree that a slightly longer form is good, e.g. `isFloatingPointType()` or even is `isIEEE754Type()` a.k.a. `isISO60559Type()`. Naa. Ditch that last one, ISO.....

**Comment by bradcray** [comment]
In today's meeting, it was proposed that perhaps we should just deprecate `isFloat*()` on the basis of:

* the stated potentials for confusion over the meaning
* the ambiguity over whether complex should return true or false (it currently returns false, which seems OK to me)
* an expectation that it probably isn't used a ton today

At first, I wasn't sure what I thought about this because it seems similar engouh to `isIntegral*()` to be worth supporting.  But then I realized that we've long thought about introducing a type class similar to `integral` yet never done so due to a combination of (a) lack of sufficient motivation and (b) lack of a good name.  The second resonates a little bit with this issue, so deprecating the query until/unless we had users who came up with strong justifications for wanting it sounded like a plausible way forward for me (at which point _they_ could come up with the name! :D ).

We talked about looking for current uses of `isFloat()` to see if it gave us pause.  I've checked:

* Arkouda (after @bmcdonald3 pointed out its use of it): Arkouda only supports `real` values currently so could just as easily use `isReal() instead.  ~3 of the 5 uses actually assume that the result is `real` ... the other 2 _could_ potentially work for `imag` if/when it was extended to use it, but I don't see this as a deeply compelling reason not to switch to `isReal()` today.
* Chapel's standard Types.chpl module uses isFloatType() in its definitions of `min()` and `max()` but seems like a case where we could just use an internal helper to get the same effect or change to isReal || isImag
* Chapel IO.chpl also uses isFloatType() in cases where treating reals and imaginaries interchangeably is reasonable, but I consider this to be fairly low-level code, and open to the same approaches as the previous bullet
* checking the `test/` directory quickly, nothing caught my eye, but it might make sense to have any current authors of those tests (there are not many) give a look and see what they think

I did not try to look at CHAMPS, ChplUltra, or ChOp today.

**Comment by stonea** [comment]
**To anyone reading this comment because I `@` mentioned you below**: We're thinking of removing `isFloat` because:

- It's confusing that it returns true for `real` and `imag` but not `complex`.
- It doesn't appear to be heavily used anyway
- Maybe someday we'll add a builtin generic `float` or `floatingPoint` typeclass (similar to what we have with `integral` or `numeric`) in which case that might influence what we'd want some future version of `isFloat` to mean.

One of the exercises I'm going through is to see how we use this in our existing code and tests. If I @ mentioned you it's probably because you have a test that uses it and I want to check if your ok with us dropping this function and having me update the test.

---

These are the instances under `test/` I see:

* A few uses under `library/packages/Sort/correctness`. None of these tests appear to make use of imaginary numbers (looks like theres tests for ints and reals and tuples thereof but no imag) so I'm guessing this is another case where the author meant `isReal` but did `isFloat` instead. @mppf (it looks like you authored these tests) please comment if this brings up any concerns you'd have about removing `isFloat` and if you'd be fine with me updating the test.

* `library/packages/Sort/performance/sort-performance-explorer.chpl` again doesn't seem to be operating on imaginary numbers

* `runtime/configMatters/comm/atomics.chpl` this one is funny. It's using `isFloat` to determine what format specifier to set for a `writef` and will use `%er` for floating point numbers but our documentation says that `%er` is for real numbers (https://chapel-lang.org/docs/modules/standard/IO/FormattedIO.html). I tried `writef("%er", 1.23i)` out and it arguably works (it will print `1.230000e+00`) but maybe that in itself is a bug (we do have a special class `%m` for imaginary numbers). FWIW this test also doesn't appear to be using imaginary numbers so updating it to use `isReal` instead should be innocuous. @ronawho (it looks like you authored this test). Please comment if you feel concerned about the possibility of removing `isFloat`.

* `types/tuple/const/tupleModifyBlankArgElem.chpl` -- this test actually does use `isFloat` in a `where` clause for a function and in this case means it (we will instantiate that function with both `real` and imag`. The test itself is pretty artificial though and it doesn't seem like a huge hassle to me to update the clause to read `where isReal(T) || isImag(t)`. @dlongnecke-cray it looks like you authored this test. Please comment if you feel concerned about the possibility of removing `isFloat` and if you'd be fine with me updating this test to do something like `where isReal(T) || isImag(t)` instead.

* Several under `test/users/vass/isX/`.  From a cursory glance it looks like a lot of these tests get automatically generated from some other script. These tests look like they're testing the `isXType` functions themselves rather than using them for some other purpose. @vasslitvinov given that would you be concerned if I removed `isFloat` and updated these tests to no longer use that query?

---

> I did not try to look at CHAMPS, ChplUltra, or ChOp today.

`grep -r "isFloat" *` is coming up empty for CHAMPS and ChOp  (I'm currently digging around for ChplUltra).

**Comment by vasslitvinov** [comment]
The tests under `test/users/vass/isX/` are there to lock in the behavior. They do not affect our design discussions. That is, it is fine to update these tests for the removal of isFloat.

**Comment by stonea** [comment]
@dlongnecke-cray pinging you again. I meant to ping you on https://github.com/chapel-lang/chapel/issues/19362#issuecomment-1217218267 but I had an editing snafu where I accidentally had your `@` message in backtick'd inline code text). I edited the comment but I have no idea if Github sends a notification after that.

**Comment by dlongnecke-cray** [comment]
Updating that test sounds A-OK to me.

**Comment by mppf** [comment]
Updating the sort tests to use isReal is fine with me

**Comment by ronawho** [comment]
> runtime/configMatters/comm/atomics.chpl

I think Greg wrote this test and I just moved it to a different dir at some point. Regardless, atomics are only supported for real floating points anyways, so this change seems innocuous.

**Comment by stonea** [comment]
Closing this issue with the submission of https://github.com/chapel-lang/chapel/pull/20548
