### ISSUE TITLE
problem with `touch -A` on alpine linux

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#19444]
Testing with alpine linux 314 I see this

```
cd /home/vagrant/chapel/third-party/hwloc/hwloc-src && find . -name "*.in" | xargs touch
touch -m -r  /home/vagrant/chapel/third-party/hwloc/hwloc-src/doc/doxygen-doc/hwloc.tag -d '+1 sec' /home/vagrant/chapel/third-party/hwloc/hwloc-src/README 2>/dev/null || \
	touch -m -r /home/vagrant/chapel/third-party/hwloc/hwloc-src/doc/doxygen-doc/hwloc.tag -A '01' /home/vagrant/chapel/third-party/hwloc/hwloc-src/README
touch: unrecognized option: A
BusyBox v1.33.1 () multi-call binary.

Usage: touch [-c] [-d DATE] [-t DATE] [-r FILE] FILE...

Update the last-modified date on the given FILE[s]

	-c	Don't create files
	-h	Don't follow links
	-d DT	Date/time to use
	-t DT	Date/time to use
	-r FILE	Use FILE's date/time
make[4]: *** [Makefile:67: hwloc-config] Error 1
```

It seems that the alpine linux `touch` command does not support `-A`. The use of `touch` with `-A` is here:

https://github.com/chapel-lang/chapel/blob/3f44e633969724e44703418294fb774571a22000/third-party/hwloc/Makefile#L67-L74

**Comment by ronawho** [comment]
Note that we try `touch -m -r '+1 sec'` first and then falllback to the `touch -A '01'` if that fails. I think I only added the `-A` fallback, but my memory is hazy on this. I'll try to look into this as part of bugfix week. @mppf were you just running this on vagrant?

**Comment by bradcray** [comment]
Michael's out, but I'm pretty sure it was on vagrant.  I wonder whether alpine doesn't support `-A` for security reasons.  It seems pretty questionable to let users change date stamps to specific times in the past...?

**Comment by mppf** [comment]
Yes I was running this on vagrant.

Also note that there are a lot of problems we run into on Alpine Linux. (In other words, other than this, we have #19404 and also problems doing the qthreads build. I am uncertain how hard we want to try to fix these right now). Fortunately, the quickstart build is working there.

Part of the issue is that this OS uses BusyBox and so things like `touch` are mere echos of the usual versions.

**Comment by bradcray** [comment]
@mppf: In case this hadn't been clear to you (it wasn't to me until this morning):  `touch -A` also isn't supported on, say, our internal paratest linux cycle servers, so it seems that the difference on alpine may be less about the lack of `touch -A` (where my mind was at last week), and more about why the original `touch` (the one before the `|| touch -A` conditional) isn't passing on alpine as it presumably always does when we build on our servers.

**Comment by mppf** [comment]
@bradcray - thanks for pointing that out - I wasn't aware of that wrinkle.

**Comment by ronawho** [comment]
FWIW that's what I was trying to convey in https://github.com/chapel-lang/chapel/issues/19444#issuecomment-1067368243. 

To fix this, I just want to get rid of the non-portable flags, and hopefully just do something like:

```diff
diff --git a/third-party/hwloc/Makefile b/third-party/hwloc/Makefile
index 6dcd60882a..a26e1caca6 100644
--- a/third-party/hwloc/Makefile
+++ b/third-party/hwloc/Makefile
@@ -65,13 +65,10 @@ hwloc-config: FORCE
        cd $(HWLOC_SUBDIR) && touch configure
        cd $(HWLOC_SUBDIR) && find . -name "*.in" | xargs touch
 #
-# For reasons not yet understood, our use of a separate build dir breaks
-# the doxygen doc rebuild step.  Ensuring that $(HWLOC_SUBDIR)/README is
-# newer than $(HWLOC_SUBDIR)/doc/doxygen-doc/hwloc.tag prevents make from
-# trying to do that step.
+# To prevent doxygen build, ensure $(HWLOC_SUBDIR)/README is newer than
+# $(HWLOC_SUBDIR)/doc/doxygen-doc/hwloc.tag
 #
-       touch -m -r  $(HWLOC_SUBDIR)/doc/doxygen-doc/hwloc.tag -d '+1 sec' $(HWLOC_SUBDIR)/README 2>/dev/null || \
-               touch -m -r $(HWLOC_SUBDIR)/doc/doxygen-doc/hwloc.tag -A '01' $(HWLOC_SUBDIR)/README
+       cd $(HWLOC_SUBDIR) && touch -c README
 #
 # Then configure
 #
```

(just touch the README to give it the current time instead of trying to give a time one second after doc/doxygen-doc/hwloc.tag.) I'm testing this now, and chatting with Greg in a bit to see if we can remember why we didn't just do something like that in the first place.

**Comment by ronawho** [comment]
Greg pointed out that just touching the `README` doesn't help in the case where a system has timestamps in the future. e.g. if all timestamps are from a day in the future, then touching the README wouldn't actually make the README newer, so ideally we really want to do something to make sure the README is newer than hwloc.tag. In other cases we would touch hwloc.tag, sleep, then touch README, but we don't really want to do that here because we don't know the full dependency chain of hwloc.tag so we could introduce other problems by trying that.

My thought for the release is just to add an `|| touch -c $(HWLOC_SUBDIR)/README` to the existing `||` chain. It's not ideal and it doesn't help on systems that lack both touch commands and have future timesteps, but I think it's a strict improvement over what we have today with the least risk of introducing additional bugs. 

Then post-release create a python script to do this touching to avoid having to worry about these portability issues, which may also let us get rid of the sleeps in other Makefiles. Linking to https://github.com/chapel-lang/chapel/issues/7665 for my future reference for hints about what types of bugs we have run into before.

**Comment by bradcray** [comment]
> My thought for the release

I'd mostly be inclined to not do anything for the release, though a user running into this on Ubuntu this morning has definitely unnerved me somewhat.  I guess I wish I understood better what sorts of cases (on alpine, in the user's case) cause us to fall into the `|| touch -A` case before making additional changes.

**Comment by ronawho** [comment]
On alpine I see:

```
alpine314:~/chapel/third-party/hwloc$ touch -m -r /home/vagrant/chapel/third-party/hwloc/../../third-party/hwloc/hwloc-src/doc/doxygen-doc/hwloc.tag -d '+1 sec' /home/vagrant/chapel/third-party/hwloc/../../third-party/hwloc/hwloc-src/README
touch: invalid date '+1 sec'
```

**Comment by bradcray** [comment]
Is it clear to anyone else what the impact is if we just remove this line?  I'm seeing the comment about the "doxygen docs rebuild step", but... do we even build the doxygen docs for hwloc?  Do we need to?  In what cases does the rebuild step trigger?

**Comment by bradcray** [comment]
Or, if removing it seems too extreme, could we just put an `-` in front of it to ignore non-zero return codes?  (specifically, I'd be curious whether that makes the alpine build work?)

**Comment by ronawho** [comment]
> Is it clear to anyone else what the impact is if we just remove this line? I'm seeing the comment about the "doxygen docs rebuild step", but... do we even build the doxygen docs for hwloc? Do we need to? In what cases does the rebuild step trigger?

If you remove the touch and make hwlog.tag newer than the README, hwloc will attempt to build their docs and fail:

```
touch third-party/hwloc/hwloc-src/doc/doxygen-doc/hwloc.tag
make
...
```

```
sed -n -f /tmp/eronagha/chapel/third-party/hwloc/hwloc-src/doc/README.sed doxygen-doc/html/index.html > doxygen-doc/html/readme.tmp.html
/bin/sh: doxygen-doc/html/readme.tmp.html: No such file or directory
Makefile:2385: recipe for target '/tmp/eronagha/chapel/third-party/hwloc/hwloc-src/README' failed
```

We don't need/want the docs, but it will automatically try if hwloc.tag is newer. We ran into this years ago in an internal thread from 2014. Thread titles are "[Chapel-commits] SF.net SVN: chapel:[23720] trunk/third-party/hwloc/Makefile" and "git and hwloc"

---

Note that since we store our third-parties un-tarred we have no control over the timestamps, so it's not hard for hwloc.tag to have a newer timestamp than the README.
