### ISSUE TITLE
I/O module: what to do with readWriteThisFromLocale?

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#19488]
Today we have this:

``` chapel
proc channel.readWriteThisFromLocale() : locale
```

It takes no arguments and returns the locale where the I/O operation started. It is needed for printing out a Replicated thing, since in doing the I/O we have an on statement.

But, it needs a clearer name.
Additionally, it seems very tied to the way the channel implementation works today in terms of ‘on’ statements. In particular, if we do Remote file local channel.chapel-lang/chapel#7953 it could change behavior.

**Proposal:**

* Rename it to something more descriptive and mark it unstable
* Open Q: What to rename it to, specifically?

**Comment by bradcray** [comment]
I'm definitely on-board with marking it unstable or de-documenting it.  Also open to renaming it, though I don't have a proposal in-hand, in part due to lack of motivation for using it (probably should go look at existing uses, though this feels less concerning than other issues, particularly if we mark it as unstable).

**Comment by mppf** [comment]
We've reached a decision to mark this method unstable for Chapel 2.0.

**Comment by lydia-duncan** [comment]
Resolved by Jeremiah's #22440
