### ISSUE TITLE
I/O module: change writeBytes to writeData

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#19493]
Today we have this:

``` chapel
proc channel.writeBytes(x, len: ssize_t) : bool throws
```

* Docs do not say what types can be passed in & the routine is generic
* It seems weird to use a C interop type for the size here
* Inconsistent camel casing with readbytes

**Proposal:**
``` chapel
proc writer.writeData(data, numBytes: int): void throws
```

* This function will ignore the channel’s Encoder (and always output binary)
* ‘data’ can be any of:
  * string, bytes
  * 1-D contiguous array of POD elements
  * c_ptr, c_void_ptr

* Open Q: is the name ‘writeData’ OK? Possible alternatives are ‘writeBytes’ or ‘writeBuffer’ or ‘writeMemory’ or 'writeBinary'
* Open Q: is it a problem that the caller will need to compute `numBytes` to pass? Is that too much of an annoyance when e.g. writing an array of `int` ?
* Open Q: Could consider only allowing `bytes` as the argument and requiring that the user convert before calling this. However that might present performance challenges since it will require more allocation.

**Comment by bradcray** [comment]
> is it a problem that the caller will need to compute numBytes to pass?

Could this have its default value inferred from the argument?  (e.g., "all of its bytes" by default — you have to pass in something else if you just want a subset)

> is the name ‘writeData’ OK?

I feel pretty "meh" about it just because "Data" is so vague.  Was `writeBinary()` considered?  (Is that an accurate description of what this does?  The docs are vague enough that I can't tell)

Would it make sense to unify writeBits() and writeBytes() into a single writeBinary() call that had overloads with distinct numBits/numBytes arguments to specify the unit?

Constrained to the alternatives given in the OP, I think I like `writeMemory()` best.

Coming straight from writeBits(), some obvious points of comparison that make the two routines seem less symmetric than their (old) names might suggest:
* is there a reason writeBits() only takes integers rather than being more generic? / equally generic to writeBytes()?  E.g., Is there a good argument for why I can use writeBits() to write 24 bits of an int but can't use writeBytes() to write 3 bytes of that same integer?
* why "data" here and "x" there?
* why is numBytes `int` here and `integral` there?  (I generally prefer `int` for simplicity when no power or generality is lost; I assumed `integral` was used there just in case someone happened to be storing "23 bits" as a `uint(64)`, which holds up for me if that was the rationale, but why not the same thing here (?).

> requiring that the user convert before calling this.

I agree with the performance concerns about requiring an allocation + copy.

**Comment by mppf** [comment]
> > is it a problem that the caller will need to compute numBytes to pass?
> 
> Could this have its default value inferred from the argument? (e.g., "all of its bytes" by default — you have to pass in something else if you just want a subset)

It could be inferred for string/bytes/data/array but not for c_ptr/c_void_ptr. Nonetheless I think that inferring it in this way is probably reasonable.

We proposed having the max to write always be in bytes (because that works for all the different cases) but a reasonable alternative would be to make a different function for writing array elements binary (where you specify the number of array elements rather than the total bytes).

> > is the name ‘writeData’ OK?
> 
> I feel pretty "meh" about it just because "Data" is so vague. Was `writeBinary()` considered? (Is that an accurate description of what this does? The docs are vague enough that I can't tell)

I think `writeBinary` is a reasonable name for it.

> Would it make sense to unify writeBits() and writeBytes() into a single writeBinary() call that had overloads with distinct numBits/numBytes arguments to specify the unit?

Of course we could do that. As a style matter, I would lean against doing so.

> Constrained to the alternatives given in the OP, I think I like `writeMemory()` best.
> 
> Coming straight from writeBits(), some obvious points of comparison that make the two routines seem less symmetric than their (old) names might suggest:
> 
>     * is there a reason writeBits() only takes integers rather than being more generic? / equally generic to writeBytes()?  E.g., Is there a good argument for why I can use writeBits() to write 24 bits of an int but can't use writeBytes() to write 3 bytes of that same integer?

You can use writeBytes to write 3 bytes of an integer. But which bytes you get would be platform specific (depending on endianness). Vs writeBits for 24 bits will always write the 24 least-significant bits.

We could imagine extending writeBits to work with > 64 bits - but say you want to write an array - writing 9000 bits of it is probably not actually useful. Anyway it would have a different behavior w.r.t. endianness. So I don't think we should try to do that. I don't think it helps with the use case (compression & decompression) that readBits/writeBits support.

>     * why "data" here and "x" there?

b/c in writeBits, x is interpreted as a number; but in writeData (whatever we call it), data is interpreted as a pointer. This interpretation matters because of endianness concerns.

>     * why is numBytes `int` here and `integral` there?  (I generally prefer `int` for simplicity when no power or generality is lost; I assumed `integral` was used there just in case someone happened to be storing "23 bits" as a `uint(64)`, which holds up for me if that was the rationale, but why not the same thing here (?).

AFAIK, the answer is "historical reasons" (different people wrote it). I think it would be OK to change writeBits/readBits to `int` if we want consistency here.

**Comment by bradcray** [comment]
> but not for c_ptr/c_void_ptr. 

Belated thought:  Can we put the c_ptr/c_void_ptr overloads into the CTypes module as tertiary methods so that we don't have to pull the C types into the IO module?  (or punt on them for now if they're not currently used?)

> We proposed having the max to write always be in bytes (because that works for all the different cases) but a reasonable alternative would be to make a different function for writing array elements binary (where you specify the number of array elements rather than the total bytes).

I might be inclined to make it take a `size: int` where the interpretation of `size` depends on the thing passed in:
* array?  Number of elements
* string?  Number of codepoints
* bytes?  Number of bytes
Which would make it similar to the direction my straw-person was heading in #19495 .  It also has the benefit of being similar to what `.size` means on these types.  I'm specifically wincing at making the caller of the array version have to compute the number of bytes required by their record eltType given that the language doesn't define that very well (which isn't to say it can't be queried but why require me to convert from something I understand "n elements of type t" into something that I don't as well "n elements times some unknown number of bytes per element" only to tell the routine something it could've figured out.

> > Would it make sense to unify writeBits() and writeBytes() into a single writeBinary() call that had overloads with distinct numBits/numBytes arguments to specify the unit?
> 
> Of course we could do that. As a style matter, I would lean against doing so.

I think I would as well now that I understand what `writeBits()` does better (i.e., can't be used for values larger than 64 bits).  But I'm definitely more comfortable having writeBinary() and writeBits() than I was having writeBytes() and writeBits() and having them be so different when they sound so similar.

> You can use writeBytes to write 3 bytes of an integer.

Oh wait, then maybe they were more similar than I realized.  But just to make sure I'm following:  You're proposing that the new routine not support this (because it can't be passed an integer), is that right?  (ignore the c_ptr versions, which I'm going to say are outside of the language and my current concern).

>  But which bytes you get would be platform specific (depending on endianness). 

If we did continue to support this capability, I think we'd want to make this as portable as writeBits() is.  And then I'd probably also want writeBits() to be able to write any number of bits from any of the same types.

> I think it would be OK to change writeBits/readBits to int if we want consistency here.

I'd also be willing to support integral here.  I think the symmetry here is less important if these routines aren't called writeBits() and writeBytes(), but it still might be nice to have all size-/num-taking arguments in the IO module consistently use integral or int.  I suppose an advantage to `int` (besides simplicity) is that we could change to `integral` later without breaking compatibility (check me on that).

**Comment by mppf** [comment]
> > but not for c_ptr/c_void_ptr.
> 
> Belated thought: Can we put the c_ptr/c_void_ptr overloads into the CTypes module as tertiary methods so that we don't have to pull the C types into the IO module? (or punt on them for now if they're not currently used?)

This kind of operation is important to some of our users (e.g. #13168). I think it's important to include them somewhere but I agree it is reasonable to include them as tertiary methods in CTypes. That means that we would split the cases differently from the OP proposal.

> > We proposed having the max to write always be in bytes (because that works for all the different cases) but a reasonable alternative would be to make a different function for writing array elements binary (where you specify the number of array elements rather than the total bytes).
> 
> I might be inclined to make it take a `size: int` where the interpretation of `size` depends on the thing passed in:
> 
>     * array?  Number of elements
> 
>     * string?  Number of codepoints
> 
>     * bytes?  Number of bytes
>       Which would make it similar to the direction my straw-person was heading in [I/O module: replace readline with readUtf8Line/readBytesLine/readLineData #19495](https://github.com/chapel-lang/chapel/issues/19495) .  It also has the benefit of being similar to what `.size` means on these types.  I'm specifically wincing at making the caller of the array version have to compute the number of bytes required by their record eltType given that the language doesn't define that very well (which isn't to say it can't be queried but why require me to convert from something I understand "n elements of type t" into something that I don't as well "n elements times some unknown number of bytes per element" only to tell the routine something it could've figured out.

OK

> 
> 
> > > Would it make sense to unify writeBits() and writeBytes() into a single writeBinary() call that had overloads with distinct numBits/numBytes arguments to specify the unit?
> > 
> > 
> > Of course we could do that. As a style matter, I would lean against doing so.
> 
> I think I would as well now that I understand what `writeBits()` does better (i.e., can't be used for values larger than 64 bits). But I'm definitely more comfortable having writeBinary() and writeBits() than I was having writeBytes() and writeBits() and having them be so different when they sound so similar.

👍 

> 
> > You can use writeBytes to write 3 bytes of an integer.
> 
> Oh wait, then maybe they were more similar than I realized. But just to make sure I'm following: You're proposing that the new routine not support this (because it can't be passed an integer), is that right? (ignore the c_ptr versions, which I'm going to say are outside of the language and my current concern).

If the array size is in number of elements, and the string size is in number of codepoints, we no longer have the possibility for writing part of an `int` (or part of a codepoint). It will always be possible with the `c_ptr` / `c_void_ptr` version.

> 
> > But which bytes you get would be platform specific (depending on endianness).
> 
> If we did continue to support this capability, I think we'd want to make this as portable as writeBits() is. And then I'd probably also want writeBits() to be able to write any number of bits from any of the same types.
> 
> > I think it would be OK to change writeBits/readBits to int if we want consistency here.
> 
> I'd also be willing to support integral here. I think the symmetry here is less important if these routines aren't called writeBits() and writeBytes(), but it still might be nice to have all size-/num-taking arguments in the IO module consistently use integral or int. I suppose an advantage to `int` (besides simplicity) is that we could change to `integral` later without breaking compatibility (check me on that).


OK so I'm going to try to combine all of the stuff here into a summary of an updated proposal:

``` chapel
// IO module methods
// (note these could be 1 generic function but I think it's easier to describe as overloads)

// writes size codepoints from a string
proc writer.writeBinary(data: string, size: int): void throws

// writes size bytes from a bytes
proc writer.writeBinary(data: bytes, size: int): void throws

// writes size number of elements from an array
proc writer.writeBinary(data: [], size: int): void throws
```

I think it's important to also have the low-level stuff so will show an updated proposal for that here:
``` chapel
// CTypes tertiary methods

// size is in number of elements
// (Q: is it better for this to be consistent with the array version or the c_void_ptr version?)
proc writer.writeBinary(data: c_ptr, size: int): void throws

// size is in number of bytes
proc writer.writeBinary(data: c_void_ptr, size: int): void throws
```

Does the above summarize our discussion and are you happy with it?

**Comment by bradcray** [comment]
Regarding the proposed interfaces:
* I'd probably change the default values of `size` from `-1` to `data.size` to make it more self-documenting and rely less on a sentinel value.  I'm trying to anticipate whether it would add overheads relative to a `-1`-based implementation, and am guessing that it's in the noise.
* For the low-level interface, I _might_ be inclined to rename `data` to `ptr` or `dataPtr` (since it's not the data but just a pointer to the data).  I'd probably definitely rename `size` to `numBytes` for those cases (since it's not as well-defined what 'size' means for a C type relative to the three Chapel types we're discussing).

> we no longer have the possibility for writing part of an int

Someone who wanted to could still do so using writeBits(), though right?

**Comment by mppf** [comment]
> Regarding the proposed interfaces:
> * I'd probably change the default values of `size` from `-1` to `data.size` to make it more self-documenting and rely less on a sentinel value.  I'm trying to anticipate whether it would add overheads relative to a `-1`-based implementation, and am guessing that it's in the noise.

Looks like that would be simple for all of these and so it would be fine with me.

> * For the low-level interface, I _might_ be inclined to rename `data` to `ptr` or `dataPtr` (since it's not the data but just a pointer to the data).  I'd probably definitely rename `size` to `numBytes` for those cases (since it's not as well-defined what 'size' means for a C type relative to the three Chapel types we're discussing).

Sounds reasonable to me.

> 
> > we no longer have the possibility for writing part of an int
> 
> Someone who wanted to could still do so using writeBits(), though right?

Yes, absolutely.

Here is the updated proposal:

``` chapel
// IO module methods
// (note these could be 1 generic function but I think it's easier to describe as overloads)

// writes size codepoints from a string
// default value of -1 means write the whole string
proc writer.writeBinary(data: string, size: int = data.size): void throws

// writes size bytes from a bytes
// default value of -1 means write the whole bytes
proc writer.writeBinary(data: bytes, size: int = data.size): void throws

// writes size number of elements from an array
// default value of -1 means write the whole array
proc writer.writeBinary(data: [], size: int = data.size): void throws
```

``` chapel
// CTypes tertiary methods

// size is in number of bytes
proc writer.writeBinary(ptr: c_ptr, numBytes: int): void throws

// size is in number of bytes
proc writer.writeBinary(ptr: c_void_ptr, numBytes: int): void throws
```

**Comment by bradcray** [comment]
Great!  And then would we have readBinary() counterparts as well?

**Comment by mppf** [comment]
Yes. Removing an out-of-date comment about `-1` we have this for the writes:

```
// IO module methods
// (note these could be 1 generic function but I think it's easier to describe as overloads)

// writes size codepoints from a string
proc writer.writeBinary(data: string, size: int = data.size): void throws

// writes size bytes from a bytes
proc writer.writeBinary(data: bytes, size: int = data.size): void throws

// writes size number of elements from an array
proc writer.writeBinary(data: [], size: int = data.size): void throws

// CTypes tertiary methods

// size is in number of bytes
proc writer.writeBinary(ptr: c_ptr, numBytes: int): void throws

// size is in number of bytes
proc writer.writeBinary(ptr: c_void_ptr, numBytes: int): void throws
```

The read functions have their own issue, #19496. I will post something there.

**Comment by bradcray** [comment]
Let's say I had some arbitrary variables I want to write out as binary data—some scalars, a record, etc.  Would we want to support a varargs `writeBinary()` that wrote them out one at a time, e.g., `writeBinary(myInt, myReal, myRecord);`  or would we need to do this using something like a binary encoder and a normal `write()`?  Can you say what the tradeoffs would be?  (writeBinary seems like a natural way to do this if we support it for (some) other types, but I realize that not all types are equally amenable to being written out in binary format...).

**Comment by mppf** [comment]
I'll reply to different elements of that idea separately:

### varargs writeBinary

I'm not sure how often it comes up - but I don't think it'd be a big problem to make `writeBinary` have a varargs version. However I feel more strongly that `writeBinary` should ignore the Encoder/Decoder; so it would still be possible to have a binary encoder that works with normal `write` calls. `writeBinary` would be something you would use when implementing such an encoder (and it can do that, varargs or not).

IMO the multiple-arguments version works pretty well for writing but when reading we have to worry about more things - what happens on EOF? Or if you read one thing and then find EOF?

So anyway my lean would be to leave out the varargs writeBinary/readBinary until somebody requested it.

### writeBinary of a record

I don't think we should support this at all. I don't think there's an obvious encoding of a record into a binary file, so I think it's a job for a binary Encoder + `write`. You might argue that the encoding of the record in memory is an "obvious" encoding but it would also obviously do the wrong thing with any contained pointers. E.g. what if the record you want to "writeBinary" is a record containing a string field? And it is worse for reading. So I think that's a job for the Encoder/Decoder mechanism.

I think it is reasonable to want to write "the data in memory" for a record to a file when doing low-level programming, but we will get that by supporting `writeBinary(ptr:c_ptr)`.

**Comment by bradcray** [comment]
I'm having trouble understanding how, as a user, I would choose between `writeBinary()` and `write()` using a binary encoder.  It seems like the latter is more general and useful: I could write out arbitrary expressions of arbitrary types, whereas `writeBinary()`  as defined above only supports strings, bytes, and arrays of [u]int(8).  Write `write()` with a binary encoder not handle those cases, or handle them differently?  

W.r.t. writing records, I was thinking of writing out a POD record.  Similarly, the OP talked about writing arrays of POD elements which seems to have fallen by the wayside at some point.  The answer to whether this routine should support that case probably is related to the answer to the previous question.

**Comment by lydia-duncan** [comment]
I've also been toying with the idea of having a binary encoder, but I don't remember if I mentioned that to the subteam so there may be an argument against it I'm forgetting

**Comment by mppf** [comment]
> I'm having trouble understanding how, as a user, I would choose between `writeBinary()` and `write()` using a binary encoder. It seems like the latter is more general and useful: I could write out arbitrary expressions of arbitrary types, whereas `writeBinary()` as defined above only supports strings, bytes, and arrays of [u]int(8). Write `write()` with a binary encoder not handle those cases, or handle them differently?

It would handle them differently. E.g., a `writeBinary(myString)` would just plop the string data into the output - with no length or terminator information - but if you are using a Google Protobuf binary encoder, it would output something like a variable-byte encoded length followed by string data. Similarly, other encoders might choose to mark the end of a string with a null byte, but I wouldn't expect `writeBinary(mystring)` to do so.

It is the same situation with an array in that an Encoder for general use would probably need to indicate the number of elements / number of bytes / some kind of terminator so that the array can be read back in.

It's my current view that having a writeBinary(mystring) / writeBinary(myarray) that ignores the Encoder is useful because:
 * it has clearly defined behavior that can be useful in low-level I/O cases
 * it can be used when implementing a binary Encoder

I wouldn't imagine it to be hard to choose between writeBinary(mystring) and write with a binary encoder. The binary encoder would be used if you are working with a generalized binary file format (e.g. Google Protocol Buffers; I think NetCDF has some similar ideas; or you can imagine a binary equivalent of JSON) but I wouldn't think of it as the right tool for the job in other cases.

> W.r.t. writing records, I was thinking of writing out a POD record. Similarly, the OP talked about writing arrays of POD elements which seems to have fallen by the wayside at some point. The answer to whether this routine should support that case probably is related to the answer to the previous question.

Yes I have been worrying about padding (the memory representation could have some padding and I don't think we define or specify that today). However it would be reasonable to include the functionality and just put a warning label on it in the documentation. Likewise we won't do anything for endianness for these cases - writing a record / array of records with writeBinary would just copy the bytes from memory to the file. Which will make sense for people trying to write C or similarly low level code. If they need to, say, write numeric values in a particular endianness, they will have to do it element-by-element. (Or use an Encoder if one exists for their file format).

**Comment by mppf** [comment]
Re varargs readBinary/writeBinary, I am comfortable with it if it only accepts numeric types. (I might be talked into extending that to arrays of numeric types).

**Comment by bradcray** [comment]
In a 1:1, Michael suggested dropping support for strings/bytes from readBinary/writeBinary under a vision that they would be less about parsing stuff, and more about just writing primitive things out to files to be used as the most basic building blocks for building out more complex binary encoders/decoders.  If we went that route (which I'm supportive of), I was proposing that the array versions of readBinary/writeBinary should read/write the whole array (or throw/return failure if that's not possible for some reason like EOF) and not provide the size argument (i.e., you write out the whole array and if you want to write less, you should pass in an array slice.

Tuples of primitive types seem like another potential type to support here in addition to primitive types and arrays (since they are somewhat array-like).

**Comment by mppf** [comment]
> In a 1:1, Michael suggested dropping support for strings/bytes from readBinary/writeBinary under a vision that they would be less about parsing stuff, and more about just writing primitive things out to files to be used as the most basic building blocks for building out more complex binary encoders/decoders.

I also don't like `readBinary(string)` or `writeBinary(mystring)` because in my view these do textual (not binary) I/O (because string data is textual).

Anyway if we don't have readBinary/writeBinary working with string/bytes then we still need a low level (non-Encoder-Decoder) way to read or write a string. Here I proposed `readSome` for the reading: https://github.com/chapel-lang/chapel/issues/19496#issuecomment-1123761560 . But I don't know what we would call the writing equivalent. `writeSome` seems a weird name for something to write a string but maybe it could work. But it gets me back to thinking of writeString / writeBytes / readString / readBytes.

**Comment by bradcray** [comment]
(Capturing things said in meetings): I still like the notion of supporting read/writeBinary string/bytes arguments.  Though strings are typically textual, they still have a binary representation, and bytes I think are not necessarily textual.  In both cases, I understand that there is some overlap in capability between `writeBinary(myString)` and `writeString(myString)` (and maybe with `write(myString) with the default encoder?), but I still think it's attractive in the sense of "being able to use a family of read*()/write*() routines (in this case * = Binary) for a variety of types in a given code section.  I.e., "I'm writing out some binary data to a channel and would like to do it for as many types as it makes sense for" rather than having to switch between different routines for different types.  Since strings and bytes have a binary representation and are among our primitive-ish types, it seems attractive to support them here as well.

In a meeting, Michael proposed that writeBinary(myString) would always only output the UTF-8 representation of a string whereas writeString() might support distinct string encodings on the way out, and that sounded attractive to me.

Capturing a related anecdote that I've mentioned elsewhere:  While writing out a binary array of uints() (using current Chapel binary I/O), I found myself doing things like "write("\n".toByte());` to get a "binary" newline into my output file until Engin pointed out I could just do `writeln();` which is simpler and more attractive.  For me, that was part of the lesson I feel like I keep learning that while strings are "textual" their binary and textual natures are essentially the same (modulo changing encodings, of course).  To that end, if I were using `writeBinary(myArray);` in this new world, it would be attractive to be able to say `writeBinary("\n");` (again, to stick with "all my I/Os here are using writeBinary() as much as possible) rather than to have to revert to `writeBinary("\n".toByte());` to fit into the supported types.

**Comment by mppf** [comment]
In an off-issue discussion, there was broad support for:
 * writeBinary with arrays of numeric elements
 * writeBinary for c_ptr / c_void_ptr as tertiary methods in CTypes

There was some support (but less broad support) for writeBinary for tuples of numeric types.

**Comment by mppf** [comment]
Also discussed in an off-issue discussion:

```
// writes size codepoints from a string
proc writer.writeString(data: string, size: int = data.size): void throws
// writes size bytes from a bytes
proc writer.writeBytes(data: bytes, size: int = data.size): void throws
// writes size number of elements from an array
```

There was broad support for writeString / writeBytes vs writeSome as the name. Additionally, there was some support for `writeBinary` / `readBinary` to apply to strings (where it would always work with UTF-8 even if we add character set conversion to channels; where `writeString` / `readString` would do character set conversion if the channel were configured to do that) (see also option 2 in #19193 for more information about character set conversion that can be configured on a per-channel basis).

**Comment by mppf** [comment]
See also https://github.com/chapel-lang/chapel/issues/19496#issuecomment-1142147893 -- I'm happy with having both `writeString` and `writeBinary(myString)` where they would work the same today but in the future, writeString could do character set conversion but writeBinary will always output UTF-8.

**Comment by mppf** [comment]
I think this is the current proposal:

``` chapel
// Writes size codepoints from a string
// Will do character set conversion in a future where a file/channel
// can be configured to use something other than UTF-8
proc writer.writeString(data: string, size: int = data.size): void throws

// writes size bytes from a bytes
proc writer.writeBytes(data: bytes, size: int = data.size): void throws
```

``` chapel
// writes size bytes from a string but always outputs UTF-8
proc writer.writeBinary(data: string, size: int = data.size): void throws

// writes size bytes from a bytes
proc writer.writeBinary(data: bytes, size: int = data.size): void throws
```

``` chapel
// writes all elements of the array or throws
proc writer.writeBinary(data: [] numeric, param endian = ioendian.native): void throws
proc writer.writeBinary(data: [], endian: ioendian): void throws
```

``` chapel
// CTypes tertiary methods
proc writer.writeBinary(ptr: c_ptr, numBytes: int): void throws
proc writer.writeBinary(ptr: c_void_ptr, numBytes: int): void throws
```

**Comment by mppf** [comment]
We could consider removing `writeBytes(someBytes)` in favor of `writeBinary(someBytes)`, or vice versa, because these two will always do the same thing, as far as I know.

**Comment by bradcray** [comment]
* In addition to the overloads you list, I thought there was an intention to support writeBinary() for each of the basic types, particularly the numeric types?

* In:
  
  > proc writer.writeBinary(data: [], endian: ioendian): void throws
  
  Is the dropping of `numeric` intentional, or an oversight?  Am I understanding correctly that the difference between this overload and the previous is that the endianness is param vs. not?  (and that that's something we think we can leverage for the purposes of optimization?)

* As mentioned in the deep-dive last week, I wonder whether we should drop the `size` arguments for `writeBinary()` of strings and bytes and just write out the whole thing (s.t. a user would have to slice if they just wanted to write out part of a string—seems like a simplicity of interface vs. performance issue).  The main downside I can see is that there'd presumably be an asymmetry in any readBinary() for those types (?).  And maybe that's a reason not to support readBinary()/writeBinary() for strings and bytes in this first draft at all.

* Before writing that, I was symmetrically wondering whether we should just file away writeString()/writeBytes() until such time as we support multiple character conversions just to reduce the number of things we're building and committing to while keeping users focused on a smaller set of routines.

**Comment by mppf** [comment]
> In addition to the overloads you list, I thought there was an intention to support writeBinary() for each of the basic types, particularly the numeric types?

Yes. I didn't list these because they are already implemented. See https://chapel-lang.org/docs/modules/standard/IO.html#IO.channel.writeBinary

> * In:
>   > proc writer.writeBinary(data: [], endian: ioendian): void throws
>   
>   
>   Is the dropping of `numeric` intentional, or an oversight?

An oversight. I've edited the comment to correct it.

> Am I understanding correctly that the difference between this overload and the previous is that the endianness is param vs. not?  (and that that's something we think we can leverage for the purposes of optimization?)

Yes. Additionally, the case where no endianness argument is provided will evaluate to the param version with native endianness.

> * As mentioned in the deep-dive last week, I wonder whether we should drop the `size` arguments for `writeBinary()` of strings and bytes and just write out the whole thing (s.t. a user would have to slice if they just wanted to write out part of a string—seems like a simplicity of interface vs. performance issue).  The main downside I can see is that there'd presumably be an asymmetry in any readBinary() for those types (?).  And maybe that's a reason not to support readBinary()/writeBinary() for strings and bytes in this first draft at all.

I'm fairly happy with having both writeBinary(mystring) and writeString(mystring) and I'd want them to both have the size argument, or not. Would you want to drop the size arguments from writeString / writeBytes as well, supposing we have both writeString and writeBinary(mystring) ?

> * Before writing that, I was symmetrically wondering whether we should just file away writeString()/writeBytes() until such time as we support multiple character conversions just to reduce the number of things we're building and committing to while keeping users focused on a smaller set of routines.

While that would be OK with me, I like the idea of having both, because then a savvy user can write code that does not need to change in the future when we have channels that can do character set conversion. I think it appropriate for us to plan ahead in the API in this way since the character set conversion is a feature that we are planning. I think the main counterargument would be that we might just never actually implement the character set conversion feature; either because Unicode is so successful or because Chapel users find UTF-8 input and output good enough for their needs.

**Comment by bradcray** [comment]
> Would you want to drop the size arguments from writeString / writeBytes as well, supposing we have both writeString and writeBinary(mystring) ?

The reason I was wondering about dropping `size` from the string/bytes overloads here was a combination of (a) wanting simplicity and symmetry in the design (e.g., if other primitive types don't support it and strings/bytes support slicing, it seems nice not to need these arguments for strings/bytes either) and (b) still hoping that someday we might add a varargs version of writeBinary() for convenience (where, specifically, I find myself thinking that there will be cases where having to use a separate statement per value you want to write out will get old).  So on that basis, I'd be OK with having these be different from writeString/Binary if it made them more similar to (and compatible with, from a varargs sense) the other writeBinary() overloads.  The c_ptr versions will still need lengths of course, so there'll be asymmetry there, but given that these are tertiary and C-level, that doesn't bother me (and similarly, I wouldn't expect a varargs writeBinary() to support c_ptrs.

I think the main flaw in this reasoning is that readBinary() for bytes/string seems like it must take a size, which means (a) there'll be asymmetry between the read/write cases and/or (b) readBinary() won't be as amenable to supporting a varargs version.

All of this makes me wonder whether we should put off writeBinary()/readBinary() for strings/bytes until there's need for it to see what that need looks like and whether the desire for varargs versions comes before or after that need.  (I realize in saying that that I've been championing supporting these routines, though in the last deep-dive, I also suggested we just be open to them and wait to implement them until they were desired, so had already started backpedaling a little).

**Comment by bradcray** [comment]
@mppf : Seeing Jeremiah's https://github.com/Cray/chapel-private/issues/3969 reminds me to note here:  I think we heard from users recently that they'd benefit from the ability to have a readBinary()/writeBinary() on records of POD, including potentially [records-of- | tuples-of- ]* POD.  I think we were shying away from these cases, at least in a first draft, in the discussion above, but wanted to note it before forgetting.  Let me know if you disagree with my interpretation of the request or understood differently.

**Comment by mppf** [comment]
I agree with that summary and the user request makes me much happier about supporting readBinary/writeBinary on trivial enough records (where POD is probably not quite the property we need but is also not too far off in concept. Here I'd probably say "records made of numeric type fields or records/tuples of these same types"). IIRC I was pushing back on the idea of readBinary / writeBinary on records but now I am thinking maybe we should do it soon.
