### ISSUE TITLE
I/O module: adjust naming for readbits and arguments to it

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#19494]
Today we have this:

``` chapel
proc channel.readbits(ref v:integral, nbits:integral) : bool throws
```

* Needs better camel casing on function name and arguments should have better argument name
* Conceptually, should use out rather than ref intent but doing so requires a language feature [#17198]
* It is very useful in compression/decompression contexts.

**Proposal:**

``` chapel
proc reader.readBits(ref x: integral, numBits: integral) : bool throws
```

* As discussed earlier, this function will ignore the channel’s Decoder

* Open Q: should we add an overload more like ‘read(type t)’ ?

  ``` chapel
  proc reader.readBits(type numericType, numBits: integral): numericType throws
  ```

**Comment by bradcray** [comment]
> should we add an overload more like ‘read(type t)’ ?

I generally like having both the "pass value in" and "pass type in, value will be returned" variations of routines like this.  That's obviously a non-breaking change, though (but nice to do as consistently as appropriate all the same).

**Comment by mppf** [comment]
Adding a note - https://github.com/chapel-lang/chapel/issues/19493#issuecomment-1086396682 suggests changing `numBits` from `integral` to `int` in order to be more consistent with other functions.

**Comment by mppf** [comment]
Supposing we have 
``` chapel
proc reader.readBits(type numericType, numBits: int): numericType throws
```

does it make sense / would it be OK to have a default value for `type` ? Here I am imagining that `uint` or `int` would be reasonable. (I think `uint` is more common for something reading bits; but `int` is a bit more the normal integral type in Chapel and it's also common for a function like this to always read < 63 bits so `int` would work too).

Then we could write things like `myreader.readBits(10)` to read 10 bits.

**Comment by bradcray** [comment]
I don't have a strong opinion about having a default value for type.  Not having one may improve the comprehensibility of the routine (no assumptions about what it returns).  But I agree that int or uint seem like reasonable defaults if we supported them.  We've also talked at times about supporting a bitvector type in Chapel, which could be a natural return type for this routine as well (?).

If we did have a default, would we swap the order of the arguments as well?  (and maybe we'd want to do so anyway since `numBits` seems like the more important piece of information?)

Looking at the names with fresh eyes, I feel as though `returnType` or `resultType` could be a better name than `numericType`.  Specifically, `numericType` seems like it's trying to document a type constraint that would be better to express as a type constraint or in the documentation.  At least, I can't think of a precedent for choosing argument names that reveal their types from other routines.

**Comment by mppf** [comment]
OK I think the current proposal is this:

``` chapel
proc reader.readBits(ref x: integral, numBits: int) : bool throws
proc reader.readBits(numBits: int, type resultType=int): resultType throws
```

**Comment by bradcray** [comment]
I tend to agree about the consistency in ordering.  I'm less sure whether I prefer Lydia's order or just using the reverse ordering, dropping the default on resultType (which I continue to feel "eh" about, in part because I'm not sure how surprising either choice of default result type would be.

**Comment by bradcray** [comment]
I agree that having the returned thing be the first argument feels more idiomatic.  Another advantage to not supporting a default besides making the call clearer and avoiding any assumptions about what the most logical default type would be is that we can always change our minds later without breaking code.

**Comment by mppf** [comment]
OK, given the above discussion, I think this is the current proposal:

``` chapel
proc reader.readBits(ref x: integral, numBits: int) : bool throws
proc reader.readBits(numBits: int, type resultType): resultType throws
```

**Comment by mppf** [comment]
From an off-issue discussion, the interface proposed in https://github.com/chapel-lang/chapel/issues/19494#issuecomment-1144740400 has enough support to move forward.
