### ISSUE TITLE
I/O module: replace readstring/readbytes with readUtf8/readBytes/readData

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#19496]
Today we have this:

``` chapel
proc channel.readstring(ref str_out: string, len: int(64) = -1) : bool throws
proc channel.readbytes(ref bytes_out: bytes, len: int(64) = -1) : bool throws
```

* read a given number of bytes from a channel into a string / bytes
* if the length is -1 then it reads until EOF
* Returns true if something was read, false upon EOF
* Issue [#13168] requests a version that can read into a pointer

**Proposal:**

``` chapel
proc reader.readUtf8(maxCodepoints: int = -1, maxBytes: int = -1) : string throws
proc reader.readBytes(maxBytes: int = -1) : bytes throws
proc reader.readData(data, maxBytes: int) : int throws
```

* All of these can read less than the max requested if there was some data and then an EOF (following Python)
* string/bytes returning functions return “” on EOF and use -1 to mean unlimited length (following Python)
* readData accepts same types as writeData and returns the number of bytes read or 0 on EOF
* These functions will ignore the channel’s Encoder

See also #19495 which proposes a similar change.

**Comment by bradcray** [comment]
I'm not crazy about `readUtf8` as a routine name because I'd like to think that most/many Chapel programmers will never have to understand what UTF-8 is and will just use strings to their hearts content without being any the wiser about it.  To inject the term into a routine name (and one that seems more about reading and returning a Chapel string) feels unfortunate to me and asymmetrical with `readBytes`.  I missed the conversation obviously, but why not just `readString()`?

Along those same lines, and acknowledging that I know we use lots of 'codePoints' in routines today already..., seeing the term here, I find myself thinking "Should we have just called codepoints characters in Chapel since we don't have a `char` type (so don't have to worry about character meaning "one byte").  I.e., "read 5 characters of this channel into this string" feels much more Chapeltastic and non-technical / off-putting than "read 5 codePoints of this channel in UTF-8 format into a string and return it".

**Comment by mppf** [comment]
I had intended for the naming in `readUtf8` to match with `readUtf8Line` from #19495 but obviously that issue is a point of contention so perhaps we should discuss there a bit further before we finalize this one.

If I ignore the connection to #19495 then I have no problem with `readString`.

> Along those same lines, and acknowledging that I know we use lots of 'codePoints' in routines today already..., seeing the term here, I find myself thinking "Should we have just called codepoints characters in Chapel since we don't have a `char` type (so don't have to worry about character meaning "one byte"). I.e., "read 5 characters of this channel into this string" feels much more Chapeltastic and non-technical / off-putting than "read 5 codePoints of this channel in UTF-8 format into a string and return it".

If you continue to feel that way then I think you should make an issue about it. The routines discussed here are just trying to use whatever style/convention we are using elsewhere. (My own opinion on the matter is that "codepoint" is well defined and people can know exactly what it means; so is "glyph" when used to mean, loosely, "a thing that appears on the screen". An example of the difference is that there are Unicode combining characters where multiple codepoints will make one letter/character. In contrast I think "character" means different things to different people and different things in different programming languages. And I would view the natural definition of "character" as meaning "glyph" rather than "codepoint".)

**Comment by mppf** [comment]
Following the direction from discussion in #19493 and #19495, here is a proposal for these read calls:

```
// IO module methods

// reads up to maxSize codepoints (for t=string) or bytes (for t=bytes)
// and returns it; but maxSize=-1 means unlimited length.
// Can return a short string/bytes if EOF is reached after some data.
// Returns the empty string/bytes if the reader is at EOF.
// Ignores the channel's Encoder/Decoder
proc reader.readBinary(type t=string, maxSize=-1): t throws;

// these two functions:
//   return `false` if EOF is reached and no data is read
//   resize the passed string/bytes (but may reuse the existing buffer)
proc reader.readBinary(ref s: string, maxSize=-1): bool throws
proc reader.readBinary(ref b: bytes, maxSize=-1): bool throws

// reads up to maxSize elements from an array
// returns the number of bytes read (which == the number of array elements set)
proc reader.readBinary(ref a: [] ?t, maxSize=a.size): int where t == uint(8) || t == int(8)


// CTypes tertiary methods

// these two return the number of bytes read, or 0 on EOF
// they can read up to maxBytes but might read less if EOF is reached partway through.
proc reader.readBinary(ptr: c_ptr, maxBytes: int): int throws
proc reader.readBinary(ptr: c_void_ptr, maxBytes: int): int throws
```

**Comment by mppf** [comment]
What bugs me about the above is that now we have `readBinary(string)` which feels like nonsense to me.

**Comment by bradcray** [comment]
Is `readBinary(string)` / `readBinary(myString)` / `readBinary(bytes)` / `readBinary(myBytes)` essentially now the same as `readFile([same arg])`?  I guess a difference is that readFile() probably won't take a max value...  Would that suggest not supporting a sentinel / default value for maxSize here either?

Or do they differ in some way—e.g., maybe `readBinary(string)` would stop reading at non-UTF8 data?

I'm not sure if either of these relate to why you think they feel like nonsense or not...

See also https://github.com/chapel-lang/chapel/issues/19493#issuecomment-1112690419 which asks about a varargs version of writeBinary() where, if we had it, I'd want to write `readBinary(myInt, myReal, myRecord)` as well.

**Comment by mppf** [comment]
What was bugging me about `readBinary(string)` is that it's not a binary read (since it's reading UTF-8 data). I'm going to make an issue proposing a `readUntil` instead and will post a link here.

I've created #19767 to propose `readAll`, specifically.

**Comment by mppf** [comment]
I'm proposing that readAll (or perhaps readSome) cover the case of reading a particular number of codepoints or bytes in issue #19767. If we go with that, we would still have these methods that could be called `readBinary`:

``` chapel
// reads up to maxSize elements from an array
// returns the number of bytes read (which == the number of array elements set)
proc reader.readBinary(ref a: [] ?t, maxSize=a.size): int where t == uint(8) || t == int(8)


// CTypes tertiary methods

// these two return the number of bytes read, or 0 on EOF
// they can read up to maxBytes but might read less if EOF is reached partway through.
proc reader.readBinary(ptr: c_ptr, maxBytes: int): int throws
proc reader.readBinary(ptr: c_void_ptr, maxBytes: int): int throws
```

**Comment by mppf** [comment]
I've created #19769 to propose readUntil.

**Comment by mppf** [comment]
Feedback in #19767 was that `readAll` with a size wasn't as good as having a different routine. So, I'll sketch `readSome`:

``` chapel
// reads up to maxSize codepoints (for t=string) or bytes (for t=bytes)
// and returns it. (separate method readAll would get all the data available)
// Can return a string/bytes of smaller than maxSize size if EOF is reached after some data.
// Returns the empty string/bytes if the reader is at EOF.
// Ignores the channel's Encoder/Decoder
proc reader.readSome(type t=string, maxSize:int): t throws;

// these two functions:
//   return `false` if EOF is reached and no data is read
//   resize the passed string/bytes (but may reuse the existing buffer)
proc reader.readSome(ref s: string, maxSize: int): bool throws
proc reader.readSome(ref b: bytes, maxSize: int): bool throws
```

Or we could go back to having `readString` and `readBytes` as the name here, which doesn't seem so bad.

Anyway, whatever the name, the above are intended to be included along with readAll (#19767) as well as the following `readBinary` calls:

``` chapel
// reads up to maxSize elements from an array
// returns the number of bytes read (which == the number of array elements set)
proc reader.readBinary(ref a: [] ?t, maxSize=a.size): int where t == uint(8) || t == int(8)


// CTypes tertiary methods

// these two return the number of bytes read, or 0 on EOF
// they can read up to maxBytes but might read less if EOF is reached partway through.
proc reader.readBinary(ptr: c_ptr, maxBytes: int): int throws
proc reader.readBinary(ptr: c_void_ptr, maxBytes: int): int throws
```

**Comment by mppf** [comment]
> What was bugging me about `readBinary(string)` is that it's not a binary read (since it's reading UTF-8 data). I'm going to make an issue proposing a `readUntil` instead and will post a link here.

Elaborating a bit on this - we have currently only support for UTF-8 but I have in mind that one day it will be possible to configure a channel to use a particular character set, and then that character set would be translated in to UTF-8 during the I/O operation. If we did that, it would seem surprising if any `readBinary` activated this character set translation. At the same time, I would expect to have a function "read n characters/codepoints into a string". So I don't think it can be `readBinary(string)` but I don't have a strong preference between `readString`/`writeString` and  `readSome(string)`/`writeSome(mystring)`.

**Comment by lydia-duncan** [comment]
In the deep dive on Tuesday, there was a strong preference for `readString/writeString/readBytes/writeBytes` over `readBinary/writeBinary` as the names to handle strings and bytes

**Comment by bradcray** [comment]
Well... I think the more accurate statement was that there was a strong preference for those routines over writeSome/readSome (which had no supporters).  But I don't view that choice and approach as precluding the ability to also support the ability to do string/bytes I/O using readBinary/writeBinary as well (the two of us who voted for that option voted for both).  Specifically, I liked Michael's suggestion that readBinary/writeBinary would only literally read/write the raw buffers used to store the string and bytes without any interpretation (so `writeBinary(myString)` would be constrained to writing out UTF8 strings, for example).

The advantage to supporting both would be that it supports the notion I mentioned in describing my `read(string)` preference of having a given `read*()`/`write*()` family support as many types as make sense.  I.e., if I'm doing a bunch of writeBinary() output for integers, bools, enums, etc. and strings/bytes have a valid binary output format (which they do), why force the user to switch to a different routine to get a string into that channel?

All that said, I also said that I'd be fine with putting this off until it's wanted/needed rather than feeling the need to support it on day one.  But I don't think we should consider the concept DOA.

**Comment by mppf** [comment]
Since at the present time they would do the same thing, I think it would be trivially easy to support both `readBinary(myString)` / `writeBinary(myString)` and `readString(myString)` / `readBinary(myString)`. I am happy with doing both as long as we document that `readBinary(myString)` / `writeBinary(myString)` will always work with UTF-8 since that is our string format (where readString/writeString in contrast can do some sort of character set conversion in the future).

**Comment by mppf** [comment]
Regarding this

```
proc reader.readBinary(ref data: [] numeric, param endian = ioendian.native): bool throws
```

I am uncertain about the return type. 

In the previous comment https://github.com/chapel-lang/chapel/issues/19496#issuecomment-1123761560 it was 

```
proc reader.readBinary(ref a: [] ?t, maxSize=a.size): int where t == uint(8) || t == int(8)
```

While changing it to `bool` and to throw if the entire array is not read might be the behavior we want, I'm not so sure about it today.

You can see the docs for what is currently implemented at https://chapel-lang.org/docs/modules/standard/IO.html#IO.channel.readBinary (but you have to scroll down a bit). The current situation is that `readBinary(c_ptr)` returns a number of bytes read but `readBinary(array)` returns `bool` and throws if the entire array is not read.

Some considerations:

 * For performance reasons (to potentially avoid unnecessary buffering) these functions don't leave the channel position at the starting point if the read failed. That means that if an error is handled after a `throw`, some of the data is now in the array (and no longer in the fileReader), but we don't know how much, without doing a bunch of extra book-keeping (e.g. running `reader.offset` before).
 * Other `read` functions like the plain `read(something)` return `bool` and throw if an early EOF is reached. (I think the implication is that these paths need to do buffering & that the channel needs to end up at the starting position if the read failed). So having `readBinary(array)` might make it more consistent with those.

My own opinion at the moment is that `readBinary(array)` should be changed to return an `int` of the number of elements read.

**Comment by bradcray** [comment]
> My own opinion at the moment is that readBinary(array) should be changed to return an int of the number of elements read.

I agree with this.  I think when we have the perspective of "The goal of this routine is that you know there's an array of a certain size in a file and you want to read it in", the bool seems reasonable.  But another important case is "The goal of this routine is to read some data into an array that's serving as a buffer and we have no idea how much or little there will be" in which case returning an `int` would be very useful.  Otherwise, the user has to fall back on the c_ptr overload, which feels somewhat less Chapeltastic.  For example, see https://github.com/chapel-lang/chapel/blob/a357dd9541aee305dac7135c3512aa9222d18292/test/studies/shootout/reverse-complement/bradc/revcomp-blc-gcc8.chpl#L47

**Comment by bradcray** [comment]
Thanks for the improvement in #21441 for reading arrays as binary @jeremiah-corrado!  (and for filing the comment above, @mppf!)
