### ISSUE TITLE
I/O module: replace readline with readUtf8Line/readBytesLine/readLineData

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#19495]
Today we have this:

``` chapel
proc channel.readline(arg: [] uint(8), out numRead: int,
                      start = _, amount = _): bool throws
proc channel.readline(ref arg: ?t) : bool throws
```

* First of these reads into a uint(8) array and the second reads into a string or bytes
* Having both `readln` and `readline` is confusing

**Proposal:**
* With proposed ‘readln’ changes, ‘readln(string)’ or ‘readln(bytes)’
  reads a whole line with the default Decoder (see #19499)
* But, still need other functions to specify a max len; work with other data types; work with non-default Decoder

``` chapel
proc reader.readUtf8Line(maxCodepoints: int = -1, maxBytes: int = -1) : string throws
proc reader.readBytesLine(maxBytes: int = -1) : bytes throws
proc reader.readLineData(data, maxBytes: int) : int throws
```

* All of these store the newline in the result, unless EOF was encountered before the newline (following Python)
* string/bytes returning functions return “” on EOF and use -1 to mean unlimited length (following Python)
* readLineData accepts same types as writeData and returns number of bytes read, and 0 on EOF
* These functions will ignore the channel’s Decoder

See also #19496 which proposes a similar change.

**Comment by bradcray** [comment]
I think we're making the wrong choice here by throwing readline() under the bus in favor of readln().  If you were my boss and gave me the ultimatum "You need to get rid of one of readln() or readline() because we're losing users over it, or else turn in your resignation", I'd throw readln() under the bus _way_ before I ever considered throwing out readline().

The main reasons for this are that I think:
* it's the more useful pattern of the two (I used it 31 times in Advent of Code and readln only 4 times)
* it's the clearer name for the capability, and
* it's the thing that Python programmers will search for and reach for.

I'd then look for ways to better unify it with Python's readline() (e.g., could we have a no-args version that returned a bytes which could be implicitly (or explicitly?) converted to a string or uint(8) if that's what the user was storing it into?) and/or generalize or improve it (e.g., should there be a version that took `type string | bytes | array` as an argument and returned that thing?  Can we add a boolean argument to say whether to preserve the newline or not?)

Thinking about the alternative (keeping readln() and dropping readline()), it feels like we're just making everyone unhappy: we're choosing the Pascal programmer's name for the routine rather than the Python programmer's name, which is optimizing for the obviously less crucial community.  Yet we're also changing its definition, so wouldn't even make the Pascal programmers happy.  Everybody loses.  The only reason I can think of for taking this approach is "spelling-wise, it's symmetrical to writeln()", but having a symmetrical routine only makes sense to me if the behavior is also symmetrical—or as symmetrical as is possible given that writing/reading aren't always trivially invertible.  But I'd say that the proposed behavior is less symmetrical to writeln() than the current behavior, so doesn't seem like a rationale for throwing 'readline()' under the bus.

All that said, I'm also still not convinced that supporting both routines is an untenable situation.  Only that if you forced me to get rid of one, I'd get rid of readln().  And at this point I'll probably start to repeat previous arguments, but...

* I don't think a Python programmer would reach for readln() if readline() existed and acted the way they expected.
* I don't think seeing them in print they're so visually similar that the eye would be confused.
* If you came across a call to 'readln' in the wild (where, statistically speaking, it seems likely to me that you'd have already come across 'readline()' calls first) and had no intuition for what it did, I don't think there's anything wrong with expecting you to read the documentation to find out, as with any unfamiliar routine.
* I'm not convinced by the "they sound the same" argument either:

For all my years working on Chapel, the number of times people say these routines out loud has been pretty small.  But I also think there's an easy fix which is to just define the correct Chapel pronunciation of 'readln' to be 'read-lynn' (like the name) and 'writeln' to be 'write-lynn' rather than saying 'line' in both cases.  'writeln()' is obviously used far more commonly in Chapel programs, yet I can't even think of how members of the team pronounce it out loud as I write this because I don't think it happens very often.  I say 'write-lynn' because 'write-line' just seems like too much of a mouthful even though it's the same number of syllables, and it also doesn't match the way my brain processes the identifier—I don't even think of 'ln' as "line" so much as "linefeed" or "newline" or '\n'.  (In fact, I've long been tempted to propose a `writelnln()` that would write two linefeeds after its arguments.  :D ).

I'm also not crazy about the names of the new proposed routines here, which feel clunky, wordy, and technical to me, particularly compared to readline().  But maybe if we can keep readline(), that's less of an issue?

**Comment by bradcray** [comment]
>  I hear you saying that readline is a better name than readln, to do something, if we want to keep only one of the names. However I also do not understand to what extent you feel that removing one of readln or readline, as names, is acceptable.

To be specific, I believe strongly that we should have a routine that reads a single line of input, as indicated by linefeeds, and that that routine should be called readline() (or readLine()) rather than read() or readln() or any of the new routine names in the OP that are proposed as replacements for readline().  And if you said "We can only do that by not having another routine named `readln()`, I would disagree, but agree that `readline()` is the one that should prevail.

> Regarding implicitly converting from proc readline():bytes to string, I don't think that is possible. We could implicitly convert from string to bytes (I don't remember right now if we do) but not the other way around.

Oops, you're right of course, and I got the relationship backwards in hurrying.  Strike that idea from the record.  I also see that there's a problem with having `readline()` only return a string, since the line in question may not be legal UTF-8, but may be a legal `bytes`.

> ```chapel
> proc reader.readline(type t=string, maxCodePoints: int = -1, maxBytes: int = -1)
> ```
> But no matter which order we choose, one of the following will do the "wrong" thing

I'd either address the above gotcha by supporting:

```chapel
proc reader.readline(type t=string)
proc reader.readline(type t=string, maxCodePoints: int)
proc reader.readline(type t=string, maxBytes: int)
```

which would force the user to use keyword-based argument passing when calling one that took an integer, which might be annoying to a minimalist programmer, but would make anyone reading their code happy.

Or. I might choose to only support the codepoints version when t=string and the `maxBytes` version when it's bytes or an array:

```chapel
proc reader.readline(type t=string)
proc reader.readline(type t=string, maxCodePoints: int) where t == string
proc reader.readline(type t=bytes, maxBytes: int)
```

Or, if we believed there was never a reason to read a number of bytes into a string or a number of codepoints into a bytes/array (which I think I do?), then I would support:

```chapel
proc reader.readline(type t=string, size: int=-1)
```

Or:

```chapel
proc reader.readline(type t=string)
proc reader.readline(type t=string, size: int)
```

if we didn't like relying on the -1 sentinel value.

All that said, I'm also not clear on when one would want to use these "only read this much of the line" arguments in practice, and wouldn't support them myself, if it weren't for the fact that Python does.  If the Python community felt like a mistake (or we decided that it was), I'd  just drop it for simplicity because "read this line, but only read part of the line" seems like a weird operation to me.  If I only wanted to read part of a line into a string or bytes, I'd first thing of using some form of readString() or readBytes() or read(type t) that took a max length instead.

Then, the one other thing that's missing is the optional bool to say whether to keep the final eol or not (which it looks like [Python has as well](https://docs.python.org/3.10/library/codecs.html?highlight=readline#codecs.StreamReader.readline)?)
(# 18849)

>  I think it probably makes more sense to read into an existing array than to return one.

The reason I think it's compelling to return an array is that it absolves the user of having to worry about how to make sure that the array is the right size—neither too large nor too small—similar to how they don't have to worry about it for `bytes` and `string`.  If `bytes` were modifiable in-place then I think it would be more reasonable to omit the array case, but I think there should be a way to say "read these bytes into a buffer that I can then modify" without having to copy it (from a bytes into an array, say).  If constraining this to only arrays of uint(8) or int(8) would make it go down better, I'm definitely open to that (that's the only case I've been focused on, and haven't thought hard about what arrays of other types might mean).

So, my strawperson minimal interface would probably be something like the following (where I don't feel confident of `keepEOL`):

```chapel
proc reader.readline(type t=string, size=-1, keepEOL=true): t
proc reader.readline(ref s: string, size=-1, keepEOL=true): bool  // or `out` rather than `ref`?
proc reader.readline(ref b: bytes, size=-1, keepEOL=true): bool   // or `out` rather than `ref`?
proc reader.readline(ref a: [] ?t, size=a.size, keepEOL=true): bool where t == uint(8) || t == int(8)
```

I moved this part to the end, as in my previous comment, because it seems the least related to the OP (which I read as "Let's get rid of readline()", which is what I'm reacting most negatively to).

> Do you disagree that it trips up users fairly regularly?  

I do.  I think there are definitely frequent hesitations like "Chapel has readline() and readln()?  Why?" when someone stumbles across both of them in practice.  But I viewed that as a pause point rather than a stumbling block personally.  Specifically, I can't recall a case where someone has said "I wanted to read a whole line, and `readln()` didn't do that for me.  I also think the situation was definitely worse before we had any library documentation, though I can't claim the current documentation is as clear or organized as I'd want it to be.

> The one case that I can point to as documented evidence is https://github.com/chapel-lang/chapel/issues/15844.

Unless I've missed something, #15844 is less about confusion between `readln()` and `readline()` and more about confusion about what causes a given string or bytes value to stop being read (whitespace, newline, eof, or something else).  And, interestingly, it's in the context of `read()` which is a very appropriate place for that question (i.e., "If I do `read(string)` where does the reading stop?).

**Comment by mppf** [comment]
(I haven't gotten to the above reply yet, and I will, but this is replying to something in https://github.com/chapel-lang/chapel/issues/19495#issuecomment-1086367338 ).

You mentioned Pascal as the historical source of the name `readln`. But `readln` in Pascal does not do what our readln does. If given a string, it reads to the end of the line. If given two strings, it reads the line to the first string, and stores an empty string in the second. And just a `read` in Pascal of a string will read a line (leaving the newline as the next thing available to read; so the difference between `read(mystring)` and `readln(mystring)` in Pascal is whether or not the newline is consumed). (Pascal is also doing some things I don't yet understand in terms of when a read returns the empty string - it does not seem willing to consider passing a newline for a plain read but I don't know exactly what the rule there is - at a guess reading into a string can never read a newline - only the `ln` part in `readln` can).

<details>

``` pascal
Program Example50;

{
  Program to demonstrate the Readln function.

  Compile it with

    fpc ex50.pp
}

Var S : String;

begin
 Writeln ('Type some words. An empty line ends the program.');
 repeat
   Readln (S);
   Writeln ('I read ', S);
 until S='';
end.
```

```
$ ./ex50
Type some words. An empty line ends the program.
a b c d
I read a b c d
e
I read e
```

``` pascal
Program Example50a;

{
  Program to demonstrate the Read function.

  Compile it with

    fpc ex50a.pp
}

Var S : String;
    F : TextFile;

begin
  Assign (F,'input.txt');
  Reset (F);
  While not Eof(f) do
    Begin
    Read (F,S);
    Readln(F);
    Writeln ('I read ', S);
    end;
  Writeln;
  Close (F);
end.
```

```
$ cat input.txt 
a b c d
e f g
$ ./ex50a 
I read a b c d
I read e f g
```

</details>

**Comment by mppf** [comment]
>  I'd just drop it for simplicity because "read this line, but only read part of the line" seems like a weird operation to me. If I only wanted to read part of a line into a string or bytes, I'd first thing of using some form of readString() or readBytes() or read(type t) that took a max length instead.

I think I could get on board with that proposal. I think in applications that process untrusted input, it's important to not be able to read an arbitrary long line (since that could cause an out-of-memory failure). But, the way Python does it is a bit weird:

```
$ cat input.txt 
a b c d
e f g
$ python3
>>> f = open('input.txt')
>>> f.readline(5)
'a b c'
>>> f.readline(5)
' d\n'
```

So if you wanted to read the lines and truncate or error if the lines were too long (which seem like reasonable behaviors in the context of an application trying to be secure) then you wouldn't be able to use `readline` at all anyway since that would cause the program to mix up lines.

> Then, the one other thing that's missing is the optional bool to say whether to keep the final eol or not (which it looks like [Python has as well](https://docs.python.org/3.10/library/codecs.html?highlight=readline#codecs.StreamReader.readline)?)
(# 18849)

I'm not sure what that documentation is for, but what I would call the "usual" readline call in Python does not support this optional argument to indicate if the newlines should be kept:

```
>>> f = open('input.txt')
>>> f.readline(keepends=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: TextIOWrapper.readline() takes no keyword arguments
>>> f.readline(1000, True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: readline expected at most 1 argument, got 2
```

**Comment by mppf** [comment]
Regarding the maximum length, it seems really weird to me to have an operation that allocates memory but we can't control the maximum length. Given the discussion above about how it is going with Python, I might simply suggest that it have a maximum size and the function will throw (instead of returning anything) if the line is longer than that.

For that situation, I think that the difference between code points and bytes is not so important (and if the goal is limiting the amount of memory used, all the memory could be in bytes).

So then we could have

``` chapel
// t can be bytes or string
// maxSize is always in bytes and intended only to limit maximum memory usage
// throws if the line is longer than maxSize bytes
proc reader.readline(type t=string, maxSize: int=-1): t throws
```

(we could consider size being in codepoint for string but IMO consistency is better and bytes will be OK if the goal is limiting maximum memory usage; also it would be fine to call it maxBytes)


> >  I think it probably makes more sense to read into an existing array than to return one.
> 
> The reason I think it's compelling to return an array is that it absolves the user of having to worry about how to make sure that the array is the right size—neither too large nor too small—similar to how they don't have to worry about it for `bytes` and `string`.

I think we need to discuss this more.

Let's suppose for a second that we did want to have a `readline` that returned an array.

If we gave it this obvious signature:
``` chapel
proc reader.readline(type t): t
```

then there are immediately 2 problems:
1. It's actually hard to write an array type in Chapel
2. The array type in Chapel includes the size.

So if I call it like this
``` chapel
var A:[1..10] int(8);
var line = stdin.readline(A.type);
```

then `line` will necessarily have domain `{1..10}`, due to the runtime type (and the fact that `t` was declared as the return type). See also
 * #19292

This leads me to thinking that a `readline` that works with an array needs a different signature since it won't fit in easily with a `readline(type t):t` function.

So that leads to the question of - what should `readline` that works with an array look like?

I think there are 2 choices here:
 1. Should it be called `readline` or some other variation on the name?
 2. Should it return the array or modify an existing array?

Here is a bunch of sketches (these are 4 alternatives in the design space):

``` chapel
// called readline, returns array
proc readline(type eltType): [] eltType throws

// called something else, returns array
proc readlineAsArray(type eltType=uint(8)): [] eltType throws

// called readline, modifies existing array
// returns how much it read
proc readline(ref intoArray): int throws

// called something else, modifies existing array
// returns how much it read
proc readLineData(ref data, maxBytes: int): int throws
```

Now, another thing we need to talk about is whether or not we want to provide a `readline`-like function that can store the result of reading into a `c_void_ptr` / `c_ptr`. Issue #13168 requests something along those lines for `read`. We could choose to skip it for `readline` and instead only provide it for a low-level read. Do you have an opinion on this matter?

If we are intentionally skipping the low-level `readline`, but we provide a low-level `read`, I would be comfortable with a `readline` variation that returns an array. However I'm not so sure that `readline(eltType=int(8))` is clear enough.

**Comment by bradcray** [comment]
> You mentioned Pascal as the historical source of the name readln. But readln in Pascal does not do what our readln does. If given a string, it reads to the end of the line. If given two strings, it reads the line to the first string, and stores an empty string in the second.

Oh interesting.  That makes it seems as though I combined my early experiences with Pascal with my more recent experiences with C scanf("%s") somewhere along the way in designing and/or implementing readln().  Specifically, note that [readln() of non-strings reads those things and then skips to the EOL](https://tio.run//##Vc9PT4QwEAXw@3yKdwOTSvy3rsLJgwdvxjV6LmUWm0Bp2hopxs@OuxASuPX9Mpl5tdIr2VwerRrHV9fVTrZ47mVrG95dFUS/BCweOlTcdsYHJwMjfDHeWFaNwfHbqKA7k9Ef0Yd0OCDHITht6mLKvUAUGHK8mMA1u1mlQCmgVkol19oQPp0OfFqcJu/RMnzXMvQ85DM8GXBrQ0SjDYNN5acydu6ZJRcFwU3N0n71jmJYJSlKoc75Z76VJj20z5EI9BuOC8cNDwsPG5YLyw2XC5cbVgufm5w@ko3jNW5wS3fY4Z729IBHon8).

So when I was thinking of `readln(arg1, arg2, arg3, ...)` I was thinking "You read each argument and then read a newline" while using C's 'scanf("%s") breaks on whitespace' behavior as my model for what reading a string should mean.

**Comment by bradcray** [comment]
> Regarding the maximum length, it seems really weird to me to have an operation that allocates memory but we can't control the maximum length. Given the discussion above about how it is going with Python, I might simply suggest that it have a maximum size and the function will throw (instead of returning anything) if the line is longer than that.

I'm much more comfortable with that than with a readline() that leaves part of the line unconsumed.  Alternatively, I could imagine it reading the max length into the type in question, then consuming the rest of the line and dropping it on the floor (or doing both that and throwing).

> then there are immediately 2 problems.

I agree that this is a problem and not one that we need to solve immediately (in that we can always add the capability later when array types are richer or more simple, when the need arises, etc.).  In the meantime, I'd definitely support a version that took the array as an argument (just as I'd support one that took the string or bytes by argument).

> Now, another thing we need to talk about is whether or not we want to provide a readline-like function that can store the result of reading into a c_void_ptr / c_ptr. Issue https://github.com/chapel-lang/chapel/issues/13168 requests something along those lines for read. We could choose to skip it for readline and instead only provide it for a low-level read. Do you have an opinion on this matter?

I think if we had that capability, it should go into the CTypes module or some other C-level module rather than the standard I/O module.  I also think I'd rather address performance overheads in using Chapel's files and channels (which seems to have been the motivation for #13168) rather than providing a low-level workaround out of the box and people using it instead.  If you gave me a choice between supporting a big family of read() routines in Chapel that took C pointers or a way of passing a Chapel channel or file + offset or whatever out to a C routine so that it could read from it into its pointers, I'd prefer the latter.  

All that said, I would probably be disinclined to support a readline() version for C pointers until someone made a strong argument for it (in the vein of "why create work for ourselves?")

**Comment by mppf** [comment]
> I'm much more comfortable with that than with a readline() that leaves part of the line unconsumed. Alternatively, I could imagine it reading the max length into the type in question, then consuming the rest of the line and dropping it on the floor (or doing both that and throwing).

If we are expecting the line not to be too long then I don't think it's prohibitive to find the end of the line before we return. It is easier to get the correct allocation that size anyway. So I still lean towards just `throw`ing, and leaving the input where it was, if the line is too long. That would allow a `catch` block to do then choose what to do with the too-long line—possibly including truncating it or possibly just skipping the whole line with `advancePastNewline`.

>  In the meantime, I'd definitely support a version that took the array as an argument (just as I'd support one that took the string or bytes by argument).

I have some questions about this.

1. Are you expecting the array-as-argument version to resize the array? (If so, we would have to also pass in the domain, right? e.g. `proc readline(D: domain, A: [D])`). I would absolutely expect a `readline` accepting a string or bytes argument to resize the string/bytes.
2. Are you expecting that the array-as-argument version would only set some of the array elements?

Either way, this seems very different from the `readline` returning a string/bytes, and so I would be inclined to give the array version a different name.

As I understand it, we can both be happy with this proposal (or something near to it) (modulo my concerns about `readline` vs `readln` but for now I am assuming that we will solve it by doing something to `readln`):

``` chapel
// t can be bytes or string
// maxSize is always in bytes and intended only to limit maximum memory usage
// throws if the line is longer than maxSize bytes
proc reader.readline(type t=string, maxSize: int=-1): t throws
```

Can you suggest the specific signatures you would add:
 * for reading into a string/bytes argument?
 * for working with an array?

Thanks

**Comment by bradcray** [comment]
>  So I still lean towards just throwing, and leaving the input where it was

That's fine with me.

> Are you expecting the array-as-argument version to resize the array?

No, just to use the existing data, or throw if the line exceeded the array size.

> Are you expecting that the array-as-argument version would only set some of the array elements?

Yeah, only the ones needed to represent the line's bytes.

> Either way, this seems very different from the readline returning a string/bytes, and so I would be inclined to give the array version a different name.

Why are you comparing to the returning versions rather than the "takes a string/bytes argument" versions, which are the more natural analogs?  Yes, it's different in that our strings/bytes don't (currently) have a fixed buffer so will become whatever size they need to be, forcing an alloc and possibly free.  But that difference seems completely reasonable to me given the distinct natures of the types.  The fact that all overloads already take a max size also makes it seem appropriate.

Again, I think the motivation for reading a line into an array is that our bytes/strings aren't modifiable in-place / will typically require [re-]allocation, so if I wanted to avoid allocations and/or do anything to the data in-place after reading it, an array makes for a great option.

This is also one of those cases where it feels like we've been supporting the capability and have made decent use of it, so it would surprise me that we'd throw it out simply because arrays aren't behaviorally equivalent to strings and bytes.

> we can both be happy with this proposal 

I still think it needs some sort of optional bool indicating whether to preserve or drop the EOLs.  I don't see a downside (default still behaves the same as ever) and plenty of upside (routine is already scanning for EOLs, so if I don't want it, why return it to me and force me to truncate the string, which might involve a copy if we haven't optimized that case?)

> Can you suggest the specific signatures you would add:

Didn't you already ask for this and I provided it in https://github.com/chapel-lang/chapel/issues/19495#issuecomment-1089265064 ?  Or was there something about that suggestion that we've ruled out?

**Comment by mppf** [comment]
> Again, I think the motivation for reading a line into an array is that our bytes/strings aren't modifiable in-place / will typically require [re-]allocation, so if I wanted to avoid allocations and/or do anything to the data in-place after reading it, an array makes for a great option.
> 
> This is also one of those cases where it feels like we've been supporting the capability and have made decent use of it, so it would surprise me that we'd throw it out simply because arrays aren't behaviorally equivalent to strings and bytes.
> 
> > we can both be happy with this proposal
> >
> > ``` chapel
> > // t can be bytes or string
> > // maxSize is always in bytes and intended only to limit maximum memory usage
> > // throws if the line is longer than maxSize bytes
> > proc reader.readline(type t=string, maxSize: int=-1): t throws
> > ```

> I still think it needs some sort of optional bool indicating whether to preserve or drop the EOLs. I don't see a downside (default still behaves the same as ever) and plenty of upside (routine is already scanning for EOLs, so if I don't want it, why return it to me and force me to truncate the string, which might involve a copy if we haven't optimized that case?)

It seems less essential to me from an API point of view but if we view it as a feature for performance optimization thin I am more comfortable with it.

> 
> > Can you suggest the specific signatures you would add:
> 
> Didn't you already ask for this and I provided it in [#19495 (comment)](https://github.com/chapel-lang/chapel/issues/19495#issuecomment-1089265064) ? Or was there something about that suggestion that we've ruled out?

You had this:

``` chapel
proc reader.readline(type t=string, size=-1, keepEOL=true): t
proc reader.readline(ref s: string, size=-1, keepEOL=true): bool  // or `out` rather than `ref`?
proc reader.readline(ref b: bytes, size=-1, keepEOL=true): bool   // or `out` rather than `ref`?
proc reader.readline(ref a: [] ?t, size=a.size, keepEOL=true): bool where t == uint(8) || t == int(8)
```

Note that the use of `size` instead of e.g. `numBytes` is discussed here: 
https://github.com/chapel-lang/chapel/issues/19493#issuecomment-1089326399 .

* the `t` argument for the first one can be `bytes` or `string`
* the `size` argument is in units of:
 * bytes for `bytes`
 * codepoints for `string`
 * array elements for arrays
* these functions will `throw` if the line is longer than the `size` passed (where `-1` means "unbounded size").

I am still tempted to call these `maxSize` because they indicate a maximum amount to read rather than an amount that must be read. (#19493 talks about an amount that must be read).

Regarding the `out` vs `ref` for `readline(b: bytes)` etc, I can see arguments either way:
 * in favor of `out` -- then `readline(b)` can be used for split init
   * but... I might rather see code like `var b = readline(bytes)`
 * in favor of `ref` -- then `readline(b)` can be written in a way so as to avoid reallocating the string/bytes buffer
   * but it requires some integration with the string/bytes code non-public API

Of the two I lean more towards `ref` for these readline calls since I think repeated use of readline is a likely use case and that the `readline(string)` call is there for the other patterns.

Now when it comes to `readline(array)` I see another problem. In the OP I had this
> `proc reader.readLineData(data, maxBytes: int) : int throws`

But your proposal returns a `bool`:

> `proc reader.readline(ref a: [] ?t, size=a.size, keepEOL=true): bool where t == uint(8) || t == int(8)`

The rationale for returning `int` is that it allows one to know which array elements have been read in to. Did you change it to `bool` intentionally? If you did, how would somebody making this call know which array elements have been read in to?


So, given the above, I would suggest:

``` chapel
// maxSize arguments indicate that the function should throw
// if it finds a line longer than that (and leaves the input there)

// keepEOL means that a newline found in the input will be included in
// the returned string. Note that if the input reaches EOF without a newline,
// the returned string won't contain a newline, even if keepEOL=true.

// For this one, t can be bytes or string
// This also supports a `readline()` call.
// Note that we could alternatively implement this as 3 overloads (if that helps documentation, say)
// Returns an empty string/bytes if EOF is reached and no data is read
proc reader.readline(type t=string, maxSize=-1, keepEOL=true): t

// these two functions:
//   return `false` if EOF is reached and no data is read
//   resize the passed string/bytes (but may reuse the existing buffer)
proc reader.readline(ref s: string, maxSize=-1, keepEOL=true): bool
proc reader.readline(ref b: bytes, maxSize=-1, keepEOL=true): bool

// Returns `0` if EOF is reached and no data is read.
// Otherwise, returns the number of array elements that were set by this call.
// This function always does a binary read (i.e. it is not aware of UTF-8 etc)
// and is similar in some ways to `readline(bytes)` but works with an array directly.
// However, it does not resize the array but rather stores up to first
// 'size' bytes in to it. The exact number of bytes in the array set will depend
// on the line length (and on keepEOL since the newline will be counted if it is
// stored in the array).
proc reader.readline(ref a: [] ?t, maxSize=a.size, keepEOL=true): int where t == uint(8) || t == int(8)
```

Given the number of caveats on `readline(array)` I still think it better to give it a different name. Anyway are you happy with the above suggestion or are there things you would adjust further?

**Comment by mppf** [comment]
``` chapel
proc reader.readline(type t=string, maxSize=-1, keepEOL=true): t
```

One issue with this is that if `false` is passed for `keepEOL`, it's not possible to tell the difference between an empty line and the `""` returned for end-of-file.

For this reason, I think we should leave `keepEOL` out of this one, but one can still call

``` chapel
proc reader.readline(ref s: string, maxSize=-1, keepEOL=true): bool
```

to use it (since that already separately returns `false` if EOF was reached)

**Comment by bradcray** [comment]
> Anyway are you happy with the above suggestion or are there things you would adjust further?

I'm generally pretty happy with it.  Questions I asked myself, some of which I answered are:

* Does it make sense for `type t` to default to `string` rather than `bytes` given that `bytes` is more efficient and more general?  I can see that one could argue "yes" if we believe that newlines are inherently related to text input, and therefore string data (do we?).  I could also argue "yes" from the perspective of supporting the common case and more productive type to work with by default.
* Does it make sense for `type t` to have a default rather than requiring `string` or `bytes` to be passed in?  I think "yes" in order to support the simple `readline()` case.
* Does the array overload require a `maxSize` argument distinct from the array size?  That is, do we imagine a max other than the array size would ever be useful and used?  I don't object to keeping it in for symmetry, but also wouldn't be sad if we removed it, or removed it until someone needed it.
* For the return type of the array case, I think I wasn't thinking hard about how to find the end of the line in the event that keepEOL was false.  I personally wouldn't give it a different name even though it is a bit asymmetrical since it still reads a line and stores it in the argument, but maybe there's an attractive and compelling name that would seem better if I heard it.  Mostly, I don't think I believe that all routines that share the same name must behave identically.
* Do we want `readline()` or `readLine()`?  The former seems hard to rationalize under Chapel's current naming guidelines even though it's what I'm used to now.  I think if we were starting from scratch I'd choose the latter.  And if we do `readFile()` I don't think it should be `readfile()`.
* Can we come up with a better name than `keepEOL`?  Is it ambiguous what "keep" means here?  Would 'dropEOL' or 'stripEOL' be clearer?  Or 'saveEOL' or 'returnEOL'?  And I think given recent opinions that've been voiced we probably have to rename to 'Eol' unless we want to make a push for "acronyms at ends of identifiers are OK to keep all-caps" (which I like, but haven't heard anyone supporting other than me so far).

Good point about the string/bytes-returning version not being able to support keepEOL.  That makes me a little sad, which makes me wonder whether this version should actually throw on EOF rather than return an empty string.  Consider:
* we can't write `while var s = readline(string)` in Chapel anyway because we can't (currently) declare new variables in loop headers
* even if we wanted to drop the result on the floor (though when would that be useful?), we can't even write `while readline(string)` currently because our strings aren't bool-comparable
* our `var s = read(int);` overloads rely on throwing w.r.t. EOF, so having readline(string) throw on EOF feels like it would be consistent ("the I/O routines that take types and return things throw on EOF")

Or, if we thought these arguments didn't hold, and that preserving the Python behavior for the "preserve" case was important, we could have keepEOF be a param bool and have only the `=false` case `throw`.

**Comment by mppf** [comment]
I have created #19768 about specifically the question of if we want `readline` or `readLine`.

**Comment by mppf** [comment]
> Can we come up with a better name than keepEOL? Is it ambiguous what "keep" means here? Would 'dropEOL' or 'stripEOL' be clearer? Or 'saveEOL' or 'returnEOL'? And I think given recent opinions that've been voiced we probably have to rename to 'Eol' unless we want to make a push for "acronyms at ends of identifiers are OK to keep all-caps" (which I like, but haven't heard anyone supporting other than me so far).

At the moment I am thinking that `stripEol` is the clearest of these options. It indicates that the end-of-line will be read from the channel (vs being left sitting there) but not included in the result if `stripEol=true`.

**Comment by bradcray** [comment]
Alternative names we could consider to (a) avoid worrying about which acronym capitalization to use, (b) rely less on jargon that a novice programmer might not be familiar with would be to use `Linefeed` or `Newline` rather than `EOL`/`Eol` in this argument's name.  Main downside is that this is an argument name that probably should be used at most callsites to avoid the naked bool, so it's more typing (but not much).

Or we could use an enum which would be more self-documenting, but have the standard challenge of being more typing due to full qualification of enums by default.

**Comment by mppf** [comment]
From an off-issue discussion:
 * strong support for `readLine` as the name, in contrast to `readline`
 * `stripNewline` had the most support as the optional argument name (where the only other argument names with any support were `stripEol` and `dropNewline`)
 * there was string support for `readLine()` with no arguments returning `string` (vs returning `bytes` or not being available at all)

**Comment by bradcray** [comment]
> The new proposed function seems to get rid of this functionality to choose which indices get filled.

I think the same effect could be achieved by passing in an array slice.  I.e., `ch.readLine(A[start..], ...)`?

**Comment by lydia-duncan** [comment]
True, but that will result in additional changes to calls.  So we'll want some sort of warning to be generated when the domain of the argument doesn't start at 0 (or we'll want to make sure the implementation uses `.first` instead of assuming index 0 is first) or something along those lines

**Comment by bradcray** [comment]
I'm not following...  Can you give an example of what the user might write that would necessitate that warning?

**Comment by lydia-duncan** [comment]
Yeah, that's because I'm trying to guide Shreyas and explain potential downsides to this approach at the same time.

**Comment by lydia-duncan** [comment]
The main crux of it is that the implementation of that `readline` overload today uses the `start` argument (which makes sense, since it asks for it).  So if we drop that argument, we need to do something to replace it in the body itself and we need to generate a deprecation message that informs the user of how the interface has adjusted and what it means for them.

If we just say "the start argument doesn't exist any more", a naive adjustment on the user's part would be to just drop the `start` argument without changing any other argument.  That's the only thing we called out, they're trying to get rid of the message quickly.  But if they sent in a value for start other than the first index in their array, that's going to cause problems for them, now they're overwriting stuff they were originally expecting to be fine.

In that earlier comment, I was thinking "well, maybe if we replace start with `0` in the code, and then ensure their domain starts at index 0, that'll be fine."  But that's unnecessarily limiting and won't catch all the cases that could cause problems.  If the user's domain already started at `0` but their `start` argument was something else, they're going to run into issues and we won't warn them about it.  Ideally, we'll allow the domain to start at any index.  But I don't know how to detect the user adjusting their call inappropriately in that world.

Maybe what we want is to generate a different warning when the original call had a different start than the first index of the domain?  That seems like a lot to ask of Shreyas for code he's not super familiar with and won't be working with for the rest of the summer, though.

**Comment by bradcray** [comment]
To me this seems like over-engineering the errors / not giving the user enough credit.  If we were preserving the routine name, I might be more inclined to hold the user's hand in this way, but since we're directing them to a completely new routine with a new signature / new arguments, I think it's on them to figure out how to update their call.  If they used `start` and think they can drop it without effect... that seems like a pretty naive assumption on their part.  That said, my guess is that the vast majority of use cases in the field (if there are (m)any at all) use the string/bytes versions rather than the array version, and don't use start when they do.

**Comment by ShreyasKhandekar** [comment]
Is there a preference to what kind of error we throw when we encounter a line that is longer than `maxSize`?
Currently on @mppf 's suggestion we throw the `BadFormatError` as follows:
```
BadFormatError: bad format (line longer than maxSize in channel.readLine(arg : [] uint(8)) with path "unknown" offset 8)
```

**Comment by mppf** [comment]
@ShreyasKhandekar - I just noticed that `channel.readLine([])` has the array argument named `arg` but in the above we were using `a` as the argument name. Was it something intentional to go with `arg`? It would be nice to get the name right in this release if we can.

**Comment by ShreyasKhandekar** [comment]
I think the name `arg` was a relic of the previous `readline` function. I must have missed the name change. We can use `a` if that is preferred.

**Comment by mppf** [comment]
It is preferred, at least to me. It's what we discussed above and in the deep dive. Would you be able to prepare a PR adjusting it? I wouldn't expect it to impact any tests and we don't have to deprecate it if we get the change in before the release. I think this shows the places that need to change: `cd modules/; git grep readLine | grep arg`.

**Comment by ShreyasKhandekar** [comment]
Just a side note that It would impact the output from the errors and therefore impact the tests.
ex: 
```chpl
try this._ch_ioerror(EFORMAT:syserr, "line longer than maxSize in channel.readLine(arg : [] uint(8))");
```
would change to
```chpl
try this._ch_ioerror(EFORMAT:syserr, "line longer than maxSize in channel.readLine(a : [] uint(8))");
```

**Comment by lydia-duncan** [comment]
I believe this was implemented, closing
