### ISSUE TITLE
I/O module: channel.advance exceptions

### ISSUE THREAD

**Issue by jhh67** [chapel-lang/chapel#19528]
```
proc channel.advance(amount: int(64)) throws
```
Under what circumstances should `channel.advance` throw an exception?  Currently, an exception is thrown if `amount` is negative, on `EOF` for a reading channel, or if an I/O error occurs while advancing. Should `advance` throw if `amount` is negative? It was proposed in the module review that it simply do nothing in that case.

**Comment by bradcray** [comment]
Potentially naive question, but: Is there a reason that a negative advance value doesn't / can't rewind the Chapel by that amount?

**Comment by lydia-duncan** [comment]
I think there's a question about the behavior if that were to be supported.  `advance` on a writing channel will write zeroes in while advancing forward - if rewinding, should the same behavior occur?  What should happen to committed updates to the channel that only partially overlap with the rewind?  Even if the behavior is defined, it might be much slower than the same operation in the opposite direction would be.  And channels with `locking==false` can already call seek to get to an earlier part of the channel.

**Comment by bradcray** [comment]
> advance on a writing channel will write zeroes in while advancing forward

I can't recall: Does it always write zeroes, or does it only write zeroes if it's entering a section of the file that hasn't already been written previously?  (where my quiet hope would be the latter, though I'm not clear on the implications if multiple channels are referring to an overlapping region of a file).  Checking the docs, it looks like the former, though?

> if rewinding, should the same behavior occur?

My intuition would be "no".

> can already call seek to get to an earlier part of the channel.

That's an interesting point and I think reveals that I think of these routines as being fairly interchangeable.  So given that, if you were teaching me about file I/O, when would I want to use seek vs. advance to move the channel offset forward?  (in both reading and writing contexts).  What would lead me to pick one over the other?

**Comment by mppf** [comment]
> I can't recall: Does it always write zeroes, or does it only write zeroes if it's entering a section of the file that hasn't already been written previously? (where my quiet hope would be the latter, though I'm not clear on the implications if multiple channels are referring to an overlapping region of a file). Checking the docs, it looks like the former, though?

I think it adds zeros if entering a new section. Probably the docs need fixing.

> That's an interesting point and I think reveals that I think of these routines as being fairly interchangeable. So given that, if you were teaching me about file I/O, when would I want to use seek vs. advance to move the channel offset forward? (in both reading and writing contexts). What would lead me to pick one over the other?

Seek is for going to an arbitrary position. Advance is for making small adjustments. In particular, you can assume that `seek` will completely discard the data saved in the channel's buffer; but advance will work with it. That means that advance does O(amount advanced) work but it also means that it is less disruptive to the buffering process.

**Comment by bradcray** [comment]
> Seek is for going to an arbitrary position. Advance is for making small adjustments. In particular, you can assume that seek will completely discard the data saved in the channel's buffer; but advance will work with it. That means that advance does O(amount advanced) work but it also means that it is less disruptive to the buffering process.

Are these terms and use cases common to other I/O libraries?  As words, they sound like near-synonyms to me, so these distinctions in behavior and expected use cases seem subtle to me.  I.e., though I don't have a great grasp on them each (because of the relationship to the channel's buffers which I don't really have a clear vision of either), I find myself wondering whether they could be combined into a single routine that had some arguments to say things like what should happen to the buffers or existing/new elements or the like.  Or whether their names could be further distinguished from one another to make the differences clearer?

**Comment by lydia-duncan** [comment]
They were words and behaviors I was familiar with prior to looking at the Chapel I/O interface.

Java, C++, and Python all have seek.  [C++'s](https://www.cplusplus.com/reference/cstdio/fseek/) `fseek` can set a file relative to the current position or relative to the start of the file and takes an int for the offset (so could potentially accept a negative value, though it seems incorrect to use a negative value and "the start of the file" in conjunction).  [Java's](https://docs.oracle.com/javase/7/docs/api/java/io/RandomAccessFile.html) `seek` will always adjust relative to the start of the file.  [Python's](https://docs.python.org/3/tutorial/inputoutput.html) seek will set the file relative to a specified position, which could be anywhere in the file.

I'm having trouble finding advance in any of those three languages and I didn't look at other ones, but to me "advance" always implies "forward" where "seek" implies "look anywhere necessary", so I don't find their use here particularly confusing.

**Comment by bradcray** [comment]
> I'm having trouble finding advance in any of those three languages and I didn't look at other ones, but to me "advance" always implies "forward" where "seek" implies "look anywhere necessary", so I don't find their use here particularly confusing.

This is the crux of what I was asking about:  What would lead me to reach for seek() vs. advance() if what I wanted to do was move forward in the file?  How would I mnemonically remember the difference between them in order to choose the right one without having to go and read the docs each time?  If advance() is something we've invented, could it be subsumed by seek(), or seek() with extra arguments, or an extended name (`seekAndDestroy()`) that made the difference between the two cases more obvious?  If it's not something we've invented, what's the precedent, and is it a good one?

**Comment by mppf** [comment]
We (I) invented `advance`. In practice the main main use cases for it have to do with the I/O "lightweight transactions" with `mark` and `commit` or `revert`. The pattern that comes up is something like this:
 * mark
 * read ahead to look for something or other and note its position
 * revert
 * advance to the position we noted

C++ has a similar functionality for reading with https://www.cplusplus.com/reference/istream/istream/ignore/

We don't want to discard the channel's buffer when doing that.

We have `channel.advancePastByte` which I don't think is confusing as a name. Would you agree?

The reason that we have both `advance` and `seek` is that at first I didn't think it was reasonable to have `seek` since I thought it would be too hard to implement with the channel's buffering strategy. So we only had `advance` which behaves like reading or writing in terms of the buffering. But then somebody (you?) convinced me that we could add `seek` to work in certain restricted cases and simply drop the buffering.

I think it is conceivable that we might be able to come up with something that combines `advance` and `seek` (probably called `seek` since that is common in other languages) but I have a pretty strong distaste for using optional arguments to indicate if it should drop the buffer or not (since I think of dropping the buffer as a totally different operation from moving forward with the buffering). So if we combined them I think the main challenge is making something that works as one would expect in common situations, and isn't too confusing in more complex cases.

A reasonable alternative would be to make it available only on reading channels and call it `ignore` (following C++).

**Comment by jhh67** [comment]
The breakout session devoted to this topic at the module re-review meeting decided to keep the name as being sufficiently descriptive. The difference between `seek` and `advance` needs to be explained better. `advance` performs the I/O and does the channel buffering but does not return the data, whereas `seek` changes the offset at which the next I/O will occur and flushes any channel buffers. So calling `advance` on a read channel will read data from the underlying file and buffer it. Calling `advance` on a write channel will fill the buffer with data from the file if they exist, and zeros otherwise. These data will be subsequently written to the file by the channel's buffering mechanism. 

The `seek` and `advance` documentation should make the following points:

- `advance` does the I/O to/from the channel buffer whereas `seek` discards the buffer and changes the file offset
- Because `advance` does the I/O it can only move forward in the file (negative I/O doesn't make sense)
- `advance` may be used on non-seekable files such as pipes and sockets
- Care must be taken to avoid excessive buffering when using `advance`
- An alternative to `seek` is to create a new channel at the desired starting offset
- `advance` makes the most sense when used in conjunction with lightweight transactions, e.g. search the channel for a desired I/O starting point as per Michael's example above, then `advance` to that point

**Comment by bradcray** [comment]
I wasn't in the breakout, but still find the differences between these routines not particularly clear from their names (though, arguably, this is true about a lot of the buffering-related aspects of Chapel I/O, which are subtle/hidden but important).  For example, if I saw code that opened a channel (to offset 0) and contained `c.advance(1024)` vs. `c.seek(1024)`, nothing about the names suggest to me how they're different or that they would be at all.  For that reason, I keep trying to think about whether there's some name that would make the distinction clearer, where the only ideas I've had so far are `advanceBuffer` or `advanceIntoBuffer`.

**Comment by mppf** [comment]
I'd be open to something like `advanceBuffer` / `advanceInBuffer` / `advanceIntoBuffer` but arguably we would also want to use the convention for `mark` / `commit` / `revert` -- `markInBuffer` / `commitInBuffer` / `revertInBuffer`.

I think a big part of why we were thinking `advance` is OK is that it doesn't match something from other languages (so is something we can attach our own meaning to without a lot of confusion).

At the same time, I that advance / mark / commit /revert are I/O features that don't necessarily need a short name.

**Comment by bradcray** [comment]
For me, it remains less an issue of confusion w.r.t. what other languages support and more the concern that the differences between `advance` and `seek` are not at all evident from their names.  That said, I'm not 100% certain that the new names make things that much clearer, though I do like that they emphasize the buffer's role.  Again, part of my confusion (with a lot of I/O routines) is around what role the buffer plays vs. just operating on the file itself; the degree to which I need to be cognizant of the buffer or not, etc.

**Comment by lydia-duncan** [comment]
Summary for ad-hoc sub-team discussion next sprint:

### 1. What is the API being presented?  How is it intended to be used?

```chapel
proc fileReader.advance(amount: int(64)) throws
proc fileWriter.advance(amount: int(64)) throws
```

Similar to seek, except the buffer is filled with the data that has been skipped.
- for fileReader, fills with zeroes
- for fileWriter, fills with data read from the file
In some settings the implementation may know that buffering is not needed.

Can be called on fileReaders/fileWriters that work with non-seekable files (e.g. a pipe or socket).

Discussions about the documentation of the difference between it and seek have already been completed (though the actions haven't been taken yet so far as I know).  The main thing that is open is whether the name is okay.

### How is it being used in Arkouda and CHAMPS?

Not used in Arkouda or CHAMPS

### 2. What's the history of the feature, if it already exists?

Michael created it for use with lightweight I/O transactions.  Initially we didn't think we could support seek due to the buffering strategy but we realized we could support it in limited scenarios and drop the buffer, which led to the addition of seek.

### 3. What's the precedent in other languages, if they support it?

It's pretty specific to our IO implementation, though there's a [skip in Java ](https://docs.oracle.com/javase/8/docs/api/java/io/BufferedReader.html#skip-long-) and [some precedent in C++](https://www.cplusplus.com/reference/istream/istream/ignore/)

### 4. Are there known Github issues with the feature?

- https://github.com/chapel-lang/chapel/issues/7954 mentions the possibility of renaming it to skip

### 5. Are there features it is related to? What impact would changing or adding this feature have on those other features?

It's related to the mark, commit and revert methods, as well as seek.  Some of the naming possibilities might impact those methods.

### 6. How do you propose to solve the problem?

A. Leave things as is
  - We haven't come up with good alternate names yet, I'm not convinced we can come up with better ones and I'm not sure it's worth trying to.

B. Rename advance to skip.
  - Pros: uses Java name
  - Cons: Does this actually help?

C. advanceBuffer
  - Maybe would imply mark/commit/revert should be similarly renamed (e.g. markBuffer/commitBuffer/revertBuffer)

D. advanceIntoBuffer
  - Maybe would imply mark/commit/revert should be similarly renamed (e.g. markInBuffer/commitInBuffer/revertInBuffer)

E. bufferAdvance
  - Maybe would imply mark/commit/revert should be similarly renamed (e.g. bufferMark/bufferCommit/bufferRevert)

I don't really like the proposed new names and think we should leave it as is.

**Comment by lydia-duncan** [comment]
Discussion summary:

We were pretty strongly in favor of keeping advance as is.

Some comments:
- Michael: likes both "keep as is" and "skip" options, not sure how to distinguish which is better
  - Lydia: skip has some precedence, but advance would mean less changes to make
  - Jeremiah: both imply "forward only", advance applies it better imo
