### ISSUE TITLE
Random: how to get various types out of the same generator

### ISSUE THREAD

**Issue by vasslitvinov** [chapel-lang/chapel#19604]
Given that a single PCGRandomStream generator can generate a variety of random number types:

* how to expose this feature to the user?
* do we need to associate a designated `eltType` with each generator instance?

See also #19605 

### How to obtain various random number types from a given generator?

* currently available: method `getNext(type resultType=eltType): resultType`
  we are considering dropping "get" from its name

* Python and Rust have methods with different names, ex. `randbytes`, `randint`, `next_u32`, `next_u64`

* idea: instead of next(type t) do `nextAs(type t)`

FYI: `getNext(t)` advances the state of our PCGRandomStream by a fixed "step", regardless of the size of `t`. The random bits for `t` are generated by advancing the state in an orthogonal dimension. This other dimension starts back at the origin when `getNext()` is invoked the next time.

Another case is bounded limitations. To generate a bounded random number, the generator needs to keep generating a new number until one is found that fits the bounds. If instead we apply rounding or mod, the generator may favor specific numbers / have a non-uniform distribution.

### Do we need a designated `eltType` for each generator instance?

Pro: do not need to specify `eltType` when all/most of the time the same eltType is requested.

Con: `eltType` is an add-on, it is not intrinsic to the generator.

Idea: `eltType=void` indicates there is no default type.

**Comment by vasslitvinov** [comment]
Having the element type as argument instead of part of the function name makes this it more clear and also takes advantage of Chapel features.  For example, we did not want `fits_ulong` and `fits_ulonglong` for bigint. This issue falls in same category.

**Comment by mppf** [comment]
A wrinkle in the current implementation is that if you make a PCG random stream for `eltType=int(32)` then it will refuse to generate 64-bit ints. The reason for this is that the 32-bit RNG carries less state (so that generating each 32-bit value can be faster).

An alternative approach is to have the RNGs always carry the same amount of states (e.g. enough for a 128-bit complex, which IIRC is 4 32-bit PCG generators), and to keep track of the "position" of each of these 4 states independently; and then when you do "getNext" to advance only the relevant ones; and to skip ahead any of them that aren't close to the current position needed.

**Comment by jeremiah-corrado** [comment]
When stabilizing the random module, we decided to simplify `randomStream`'s behavior/interface by making it only generate a [single type](https://chapel-lang.org/docs/modules/standard/Random.html#Random.randomStream.eltType). To generate random values of multiple types, multiple random streams are needed.
