### ISSUE TITLE
Filesystem module: copy vs. copyFile

### ISSUE THREAD

**Issue by jhh67** [chapel-lang/chapel#19663]
The `Filesystem` module currently supports the `copy` and `copyFile` methods. They are similar, except that `copyFile` only copies the contents of the file whereas `copy` also copies the file permissions and optionally additional file metadata such as uid, gid, access time, and modify time. There are several options:

1. Keep them as-is.
2. Add a `permissions` flag to `copy` and delete `copyFile`.
3. Eliminate the `metadata` and `permissions` flags and have different methods for the different combinations of things that are copied (contents, permissions, and metadata).

**Comment by bradcray** [comment]
This is one of those cases where having two routines seems complicated to me (in the "How will I ever remember the difference between them", at least given the current names which seem too similar).  For that reason, I like the idea of a single routine with a flag to switch between the two behaviors (possibly defaulted if we think there's an obviously better default).

I'm also open to more routines that have really clear names that define what they do, but I suspect those would be more difficult names to come up with.

**Comment by mppf** [comment]
AFAIK we got the two names from Python [shutil.copyfile](https://docs.python.org/3/library/shutil.html#shutil.copyfile) [shutil.copy](https://docs.python.org/3/library/shutil.html#shutil.copy).

In this particular case the choice of copying permissions/access time/etc or not seems a relatively minor adjustment and so I'm fairly comfortable with merging them and supporting optional arguments. The main downside to that is that we would go against the Python precedent.

**Comment by bradcray** [comment]
One of the things we discussed in the deep-dive was to look at other more modern precedents like Rust, Julia, maybe Swift.  Python's a good starting point, but it was pointed out that it may have needed to freeze things in before they were fully baked to minimize breaking changes (where the scattering of the routines across multiple modules was cited as potential evidence of this).

**Comment by daviditen** [comment]
Rust just has [`copy`](https://doc.rust-lang.org/std/fs/fn.copy.html) which always copies permissions.
Julia just has [`cp`](https://docs.julialang.org/en/v1/base/file/#Base.Filesystem.cp). The documentation doesn't say whether it copies permissions or not.
Swift just has [`copyItem`](https://developer.apple.com/documentation/foundation/filemanager/1407903-copyitem). The documentation doesn't say whether it copies permissions or not.

I think we should deprecate `copyFile` and add an optional argument `permissions` to `copy` that defaults to true. It looks like that's the direction commenters on this issue is currently leaning as well.
