### ISSUE TITLE
Filesystem module: isLink behavior when symbolic links are not supported

### ISSUE THREAD

**Issue by jhh67** [chapel-lang/chapel#19660]
Currently `isLink` returns `False` if called on a file system that does not support symbolic links. Should it throw instead?

**Comment by bradcray** [comment]
I don't think so because, to me, `isLink()` says "Is this existing file a symbolic link or not?" and if the file is stored on a filesystem doesn't support symbolic links, surely the answer is "no" (false)?

If the routine were saying something like "Create a new file that's a symbolic link" I could imagine throwing if the fs didn't support them because then you're asking it to do something it can't, but here you're just asking about a property that the file has ("I am not a symbolic link") and it doesn't seem exceptional that no file on the fs can be a symbolic link.

If someone really wanted it, I could see adding a "areSymbolicLinksSupportedByThisFileSystem()"-style query if someone needs to know the answer to that.  I just don't think we need to try and pack that answer into this query.

**Comment by lydia-duncan** [comment]
> If someone really wanted it, I could see adding a "areSymbolicLinksSupportedByThisFileSystem()"-style query if someone needs to know the answer to that. I just don't think we need to try and pack that answer into this query.

`linksSupported()` might be a nice, shorter name for that one :)

**Comment by daviditen** [comment]
In a design re-review meeting we reached consensus that this function should continue to do what it does today returning false. We also decided that it should be renamed to `isSymlink`.

Closed with
https://github.com/chapel-lang/chapel/pull/21061
