### ISSUE TITLE
Filesystem module: rename chown to setIds

### ISSUE THREAD

**Issue by jhh67** [chapel-lang/chapel#19666]
Rename `chown` to `setIds`. One setter method is used for both because the underlying `chown` system call takes both IDs as arguments, allowing both to be set atomically.

**Comment by mppf** [comment]
It's not obvious to me that `setIds` is a better name. Two reasons:
 * `chown` is a well known command name that is related;
 * `setIds` doesn't correspond to anything I am familiar with as a precedent
 * `setIds` doesn't get me thinking about the "owner" or "group" which is what I think it is setting

I like keeping `chown` but I think `setOwnerAndGroup` or `setOwner` would be better than `setIds`.

Also I would expect that, like `chown`, whatever this function is named, it eventually supports user and group names, not numbers, as well. I would want it to have the same name but `setIds` seems wrong if you give it a user name.

**Comment by mppf** [comment]
I was just poking at https://en.wikipedia.org/wiki/Chown to understand terminology but it seems to be saying that changing the owner of a file can only be done by root (while changing the group can be done by an unprivileged user). I wouldn't expect Chapel programs to be run as root at all (and in fact I expect we have a bunch of work we would need to do in order to do so safely - but that may never be a need for our system). So perhaps we should only have `setGroup` / `changeGroup` or something like that?

The only test we have of `chown` that actually runs doesn't even really check that it works

```
writeln("Attempting to chown");
try! {
  // chown and back -- in some systems this runs successfully
  chown(filename2, uid+1, gid+1);
  chown(filename2, uid, gid);
  writeln("chown works");
}
catch e: PermissionError {
  writeln("chown works");
}
writeln();
```

**Comment by mppf** [comment]
I'd support moving it to a OS.POSIX function (since the behavior is POSIX-specific and the name makes more sense in that namespace). Actually adding such a function can be done post 2.0 (supposing there are no urgent use cases for it) but I would expect it to be pretty easy to add the POSIX one if there is a use case for it (in particular since the name is already prescribed by POSIX).

**Comment by arezaii** [comment]
See https://github.com/Cray/chapel-private/issues/5015#issuecomment-1631794053 for summary of sub-team discussion on this topic.

**Comment by lydia-duncan** [comment]
We decided not to make the change, closing

**Comment by arezaii** [comment]
Can we close this since we decided not to rename `chown`, and https://github.com/chapel-lang/chapel/issues/22725 captures the possibility of adding a more POSIX-like `chown` in the future?
