### ISSUE TITLE
How should we allow users to override global hash table resizing policies?

### ISSUE THREAD

**Issue by bmcdonald3** [chapel-lang/chapel#19735]
## Summary
Today, our internal `chpl__hashtable` (which is used by associative domains, map, and set) resizes once exceeding 50% capacity by default through a value called `resizeThreshold`, though this value of 50% is rather arbitrary. Based on a users memory or performance concerns, changing this value can be valuable. Map and set can override this with a `resizeThreshold` argument in their initializers, but there is no way to do so for associative domains today, and changing the map/set values also requires recompilation. We are hoping to expose this in a more flexible way and need to decide on method and naming.

### Proposal 1: a single `config const` in the internal `ChapelHashtable` module
This has the flexibility of setting one value for all uses of `chpl__hashtable` for a simple way to modify the default `resizeThreshold`. In this proposal (and anyway), we would open up an issue to improve our story for config values so they don't always show up with `--help`.

### Proposal 2: 3 separate `private config const` values in set, map, associative domain
This keeps the values to the user modules and makes it more explicit, but becomes more complicated and provides arguably less value than just having the singl `chpl__hashtable` config value.

### Proposal 3: use something besides a `private config const`, but with either of the above proposals
Using a param would make the value not show up in `--help` output and there could be other benefits/combinations that I have not grasped the benefits of yet, so please mention if you have concerns with `private config const`.

## Names
1. `resizeThreshold`
    - verbose, describes behavior, matches set/map initializers 
2. `rThresh`
    - slightly shorter, doesn't conflict with set/map initializer names
3. `defaultHashTableResizeThreshold`
4. something else? (please propose if you don't like either of these names)

## Performance impact
threshold | % full  | lookup (scaled to 134m)
--------- | ------- | -----------------------
0.5       | 49.9%   | 14.0619 s
0.75      | 74.5%   | 18.7801 s

So, the larger the threshold, the worse the hashtable look up speed will be, but with the larger threshold comes less memory usage/later resizes. This difference in behavior is why a user may want this ability to modify the resize policy.

#### Related discussion
https://github.com/Cray/chapel-private/issues/2627

**Comment by bradcray** [comment]
Note that in proposal 2, the associative domains and arrays are not in user modules, so those cases share the need to name the module in order to set the private config, as in proposal 1.

I'll propose approach 1a: Make it a non-private config const (and then create a separate issue for improving the story for configs defined within internal modules, but leave that for future work rather than worrying about it now).  I think this has the benefit of simplicity (one variable rather than three).

I'd probably use a long, descriptive name for this, like `defaultHashTableResizeThreshold` because I don't expect it to be used much, so the length doesn't seem like a big downside; and should minimize conflicts with user-defined variables.

**Comment by dlongnecke-cray** [comment]
I'm confused, how do users even set a `private config const`? I'd advocate we just have a single `config const` in the `ChapelHashtable` module. I prefer the full name `resizeThreshold`.

Double agree with Brad, because I don't think users should have to put in the name of an internal module `ChapelHashtable.resizeThreshold` just to set it (the module name would be an unstable thing).

**Comment by bmcdonald3** [comment]
@bradcray that makes sense to me, I've updated the issue to reflect the updated proposal

**Comment by bradcray** [comment]
> how do users even set a private config const? 

Setting a private config const requires the module name to be given on the command-line.  See https://github.com/chapel-lang/chapel/issues/14622 for the history here.

**Comment by dlongnecke-cray** [comment]
Will users still have to fully qualify the config in Proposal 1 even if it isn't marked `private`?

**Comment by bradcray** [comment]
Proposal 1 has been edited since the issue was opened.  The original proposal 1 suggested a `private config const`, which would require full qualification.  The revised edition proposes just a `config const` which would not require full qualification unless the user code happened to contain a config const with the identical name (though the current text incorrectly suggests that full qualification would be required).

**Comment by dlongnecke-cray** [comment]
If that's the case, I'll strike my vote for `Proposal 1` and `defaultHashtableResizeThreshold` (just `Hashtable` IMO, to match the module name). Do we maybe want to put up little voting emojis, or are there too many options?

**Comment by bmcdonald3** [comment]
I was thinking that I would put up voting emojis in the Chapel channel once people had a chance to express their opinions here (it seems that yields better response than github issues in my experience).

**Comment by bmcdonald3** [comment]
I've opened up https://github.com/chapel-lang/chapel/issues/19743 about adding an `internal` prefix or something to suppress a config const from showing up in `--help` to go along with the new proposal 1.

**Comment by bmcdonald3** [comment]
Since the discussion window has closed, it sounds like we will go with proposal 1 and I will ask a naming question in the Chapel channel as a straw poll and then consider the discussion done (though, I'll probably post it mid-day tomorrow so more people are around to vote for it when it gets posted).

I'm thinking the three names I will propose are:
1. defaultHashtableResizeThreshold
2. defaultResizeThrehsold
3. resizeThreshold

Though, I am definitely on the `defaultHashtableResizeThreshold` side after hearing your arguments, so we've got 3 votes already.

**Comment by bmcdonald3** [comment]
The final vote was 9 votes for `defaultHashtableResizeThreshold` and 1 vote for `resizeThreshold`, so I think we have settled on `defaultHashtableResizeThreshold`. Just noting that Andy expressed a slight dislike of adding `default` on the front of the variable name, but he didn't feel strong enough to block the decision.

I spoke privately about the 1 dissenting vote and there wasn't a strong enough opposition to fight for the `resizeThreshold` name, so I'm considering this settled.

**Comment by bmcdonald3** [comment]
PR: https://github.com/chapel-lang/chapel/pull/19732
