### ISSUE TITLE
I/O module: readAll / readFile

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#19767]
This is a spin-off from discussion in #19496.

This issue proposes a separate method to read all of the data in a channel (from the current position to the end) and to return it as a string or bytes.

`readAll` or `readFile` have been suggested as names. I like `readAll` better because a channel isn't necessarily working with the file (at least I wouldn't refer to a pipe or socket as a file in regular conversation) and because a channel can have represent only a portion of a file.

Here is a sketch at what this function might look like:

``` chapel
// maxSize arguments indicate the maximum number of codepoints/bytes to read
// maxSize is in codepoints for string readAll and bytes for bytes readAll.
// maxSize of -1 means unlimited size.

// reads up until EOF or maxSize (whichever is encountered sooner)
// and returns whatever data was read in a string or bytes
// t can be string or bytes
proc reader.readAll(type t=string, maxSize=-1): t throws;

// Same as the above but updates a string/bytes argument.
proc reader.readAll(ref s: string, maxSize=-1): void throws;
proc reader.readAll(ref s: bytes, maxSize=-1): void throws;
```

The justification for including an optional `maxSize` argument is that it:
 * makes it easy to ask to read a particular number of codepoints/bytes
 * allows one to limit the amount of memory used
 
However, one could reasonably argue that with `maxSize` it's not `readAll` anymore but `readSome` (or something). Should we have `readAll` with an optional `maxSize`, or `readAll` and `readSome` as separate methods?

**Comment by bradcray** [comment]
I'd be inclined to either have the `type t` version not take a default type (s.t. the user always has to specify it), or to have it default to `bytes` (on the argument that it's a more general and cheaper type, and there's no reason to believe that the contents of a general channel will be a legal string).

I don't think I'd bother with a `maxSize` argument and would wait for someone to request it.  If they did, I'd be inclined to add another routine for it rather than adding an optional argument to this one.

I'd probably also add an array of [u]int(8) version of the `ref`-based versions in order to be able to read the file into a mutable format and have it throw if the file's contents were larger than the array.  Such a version might want to return the number of bytes read into the array directly or through an optional out argument (should all the `ref` versions return the size of the string/bytes read in this way?)

**Comment by mppf** [comment]
> I'd be inclined to either have the `type t` version not take a default type (s.t. the user always has to specify it), or to have it default to `bytes` (on the argument that it's a more general and cheaper type, and there's no reason to believe that the contents of a general channel will be a legal string).

Makes sense. For now I will remove the default type, but `bytes` is a reasonable option as well.

> I don't think I'd bother with a `maxSize` argument and would wait for someone to request it. If they did, I'd be inclined to add another routine for it rather than adding an optional argument to this one.

I think it's reasonable to add another function but I was trying to find a solution to #19496. I'll post something there. The reason that I was tempted to add a `maxSize` is to allow users to limit the memory usage of their programs.

> I'd probably also add an array of [u]int(8) version of the `ref`-based versions in order to be able to read the file into a mutable format and have it throw if the file's contents were larger than the array. Such a version might want to return the number of bytes read into the array directly or through an optional out argument (should all the `ref` versions return the size of the string/bytes read in this way?)

I think it would be OK for them to do so.

Here is a sketch incorporating your feedback.

``` chapel
// reads up until EOF
// and returns whatever data was read in a string or bytes
// t can be string or bytes
proc reader.readAll(type t): t throws;

// Same as the above but updates a string/bytes argument.
// Returns the number of codepoints (for string) or bytes (for bytes) read
proc reader.readAll(ref s: string): int throws;
proc reader.readAll(ref s: bytes): int throws;

// Same as the above but updates an array of bytes
// Returns the number of bytes read
proc reader.readAll(ref a: [] ?t): int where t == uint(8) || t == int(8)
```

**Comment by lydia-duncan** [comment]
In the deep dive on Tuesday, it seems like there was strong lean in favor of adding `readAll`

**Comment by jeremiah-corrado** [comment]
I have a draft PR for this issue here: https://github.com/chapel-lang/chapel/pull/20761

I ran into a few design questions as I was working on the implementation:

- Should the 2nd and 3rd methods overwrite the existing `string/bytes`, or append to them? Currently overwrites them because my implementation uses the existing `readBytesOrString` method that overwrites the string/bytes argument.
- What error type should the byte-array method throw when it runs out of room in `a`? Currently throws an `OS.IoError` with the `ESHORT` code. This seemed the most appropriate out of the existing error types to me, but perhaps it needs a new error type, since this is a pretty specific case?
- In the error case, should the byte-array method read bytes into 'a' until it's full - then throw, or check whether 'a' is large enough before it begins reading values into the array - and throw immediately? Currently does the former.

**Comment by bradcray** [comment]
> Should the 2nd and 3rd methods overwrite the existing string/bytes, or append to them?

I would think overwrite.

I don't have an obvious answer to the other two questions offhand.

**Comment by mppf** [comment]
> * What error type should the byte-array method throw when it runs out of room in `a`? Currently throws an `OS.IoError` with the `ESHORT` code. This seemed the most appropriate out of the existing error types to me, but perhaps it needs a new error type, since this is a pretty specific case?

IMO, `ESHORT` normally means "the input seemed incomplete as compared to what you are reading" but this is the opposite, right? Like it is `ETOOLONG`. But anyway `ESHORT` doesn't really exist outside of our project, IIRC. So, we should be thinking about what Chapel Error subclass it throws.

> 
> * In the error case, should the byte-array method read bytes into 'a' until it's full - then throw, or check whether 'a' is large enough before it begins reading values into the array - and throw immediately? Currently does the former.

If the channel represents a socket, it won't be possible to know how much there is to read until we've already buffered it all. I think it's better if the function doesn't have to do that. So, maybe what we want is: optimistically read what you can, but then throw if there is not enough room.

**Comment by mppf** [comment]
> Or maybe make a new IoError subclass for this particular case?

Yes, something along those lines sounds appropriate. Note that when we hide `ESHORT` (see #20130) we will have to figure out what to do here. So it's not just about how we would add an equivalent to `ETOOLONG`.

**Comment by mppf** [comment]
See also https://github.com/chapel-lang/chapel/issues/20130#issuecomment-1265876642 which discusses some approaches to error classes for these hidden error codes.

**Comment by jeremiah-corrado** [comment]
Regarding the specific implementation of the error type, this is what I'm thinking:
```chapel
/*
    :class:`ExceededCapacityError` is a subclass of :class:`IoError`
    indicating that an IO operation required more memory than was provided
*/
class ExceededCapacityError: IoError {
  proc init(details: string = "") {
    super.init(EIO: errorCode, details);
  }
}
```

Where
```chapel
try {
    ch.readAll(a);
} catch e:ExceededCapacityError {
    writeln(e);
}
```
would produce the following message when `a` is too small:
```
ExceededCapacityError: Input/output error (channel's contents exceeded capacity of bytes array in 'readAll')
```

Perhaps the name could be improved, but does this align with what you were thinking @mppf?

**Comment by jeremiah-corrado** [comment]
**Summary of issue:** This issue focuses on the implementation of a few new `fileReader.readAll` methods which consume the entire contents of a reading channel. One variant of `readAll` method accepts a reference to an array of bytes which it fills with the remaining contents of the channel. It has the following signature:
```chapel
proc fileReader.readAll(ref a: [] ?t): int throws where (t == uint(8) || t == int(8));
```
If the bytes array is too small, the method should throw; however, of the available error types in the `OS` module, none of the subclasses of `IoError` fit this scenario very closely. Those are: `EofError`, `UnexpectedEofError` and`BadFormatError`.

**Proposal:** I propose we create a new subclass of `IoError` with the following definition/description:
```chapel
/*
  :class:`ExceededCapacityError` is a subclass of :class:`IoError`
  indicating that an IO operation required more memory than was provided
*/
class ExceededCapacityError: IoError {
  proc init(details: string = "") {
    super.init(ERANGE: errorCode, details);
  }
}
```

The error code `ERANGE` is used because it has a similar meaning in the POSIX standard where it indicates that the provided storage was too small to hold the result (ex: in [strerror_r](https://linux.die.net/man/3/strerror_r))

`fileReader.readAll(a: [])` would be implemented such that the the following error message is produced when the channels contents exceed `a`'s size:
```
ExceededCapacityError: Result too large (channel's contents exceeded capacity of bytes array in 'readAll')
```

**Draft Implementation:** https://github.com/chapel-lang/chapel/pull/20761

**Comment by bradcray** [comment]
I haven't invested enough time understanding the lay of the land for our error classes and their implementation to have a very strong opinion here, but this generally sounds fine to me.  The one thing that gave me slight pause is whether "Exceeded" should be "Exceeds" in both the error class name and the message.  Is there a precedent for past- vs. present tense in our error messages?

**Comment by jeremiah-corrado** [comment]
Grepping for `throw new` in the standard modules it looks like most of the error messages are present tense. A majority of them are `illegalArgumentError`s (e.g., `illegalArgumentError("month must be between 1 and 12")`), and so present tense seems to make sense because the errors are generally referring to the state of the code (which isn't transient). 

In this particular case, I think past tense sounds better though because the error message is referring to the contents of the channel, at the time that `readAll` was called on it. If the program were run again, maybe the contents of a file would have changed, and the error would not be thrown again. 

So maybe a better name would actually be `fileReaderTooLarge` or something similar, with the current error message. This way, it's clear that the error has to do with the state of the file (relative to the arrays size), at the time the program was run.

And just to completely answer your question, there is a small precedent for past tense errors. For example: `LinearAlgebraError('gelsd(): SVD failed to converge...)`, `TomlError("Reached end of file unexpectedly")`, and in Map: `"key '" + k + "' not found"`.

**Comment by mppf** [comment]
Past vs present tense for errors is something we could consider including in our standard module style guide.

For the name, here are some variations (including some mentioned above) to see if any appeal:
 * `ExceededCapacityError`
 * `FileReaderTooLargeError`
 * `ExceedsCapacityError`
 * `InsufficientStorageError`
 * `InsufficientCapacityError`
 * `StorageTooSmallError`
 * `TooMuchDataError`

Of those I like `InsufficientCapacityError` the best, FWIW.

**Comment by jeremiah-corrado** [comment]
I'm happy with `InsufficientCapacityError` as well.

After looking at this some more, I think present-tense names sound better for the error classes themselves (and we don't currently have any past-tense names in the standard library).

For error messages, I think there are scenarios like this one where it makes sense to use past tense. Specifically:
```
InsufficientCapacityError: Result too large (channel's contents exceeded capacity of bytes array (100 bytes) in 'readAll')
```
or
```
InsufficientCapacityError: Result too large (channel's contents (200 bytes) exceeded capacity of bytes array (100 bytes) in 'readAll')
```

@bradcray and @mppf, are you happy with that message in this particular case?

**Comment by bradcray** [comment]
The nested parens in the error message grate on me slightly.  I might use an m-dash, colon, or semicolon instead.  But then I also think "Are we saying the same thing too many different times?"  That is:
* InsufficientCapacityError:  Seems like something wasn't big enough
* "Result too large":  Yep, definitely seems like something wasn't big enough
* "channel's contents exceeded": OK OK, I get it.

So what about just:
`InsufficientCapacityError: Channel's contents (200 bytes) exceeded capacity of array argument (100 bytes) in 'readAll()'`

I avoided the term "bytes array" in that rewrite because to me that sounds like an "array of `bytes`":  `var A: [1..100] bytes;`  I also put parens on `readAll()` just because... I guess I like that it makes something appear to obviously be a routine name.

**Comment by jeremiah-corrado** [comment]
"Result too large" and the outer parentheses come from `SystemError`'s `message()` implementation. Specifically, the `ERANGE ` error code gets translated into "Result to large". I believe this is intended to provide a few layers of detail in system error messages, i.e., "{Error Type Name}: {error-code message} ({message/details from the call site})"

So I could overwrite `message()` for `InsufficientCapacityError` to avoid the error-code message and print what you have above?

Or I could shorten the details string to make it slightly less repetitive:
```
InsufficientCapacityError: Result too large (100 byte array argument too small for 200 byte channel  in 'readAll')
```

The first option makes more sense to me because this error type is hard coded to use `ERANGE` as its system error-code, so the "Result too large"  portion can't change anyway.

**Comment by mppf** [comment]
> {Error Type Name}: {error-code message} ({message/details from the call site})

That might not be what we want for other error messages either. We might want to revisit the format. Also I don't think there is any particular reason that this error message needs to stick to that format.

I'm not picky about the exact wording of the error but I do like Brad's suggested wording.

**Comment by jeremiah-corrado** [comment]
This was resolved with https://github.com/chapel-lang/chapel/pull/20761
