### ISSUE TITLE
Chapel 1.26.0: building with GCC and CHPL_LLVM=bundled fails to find clang binary

### ISSUE THREAD

**Issue by devreal** [chapel-lang/chapel#19791]
### Summary of Problem

Building with GCC and setting CHPL_LLVM=bundled, make fails to find the `clang` binary, looking for `third-party/llvm/install/linux64-x86_64-clang/bin/clang` instead of `third-party/llvm/install/linux64-x86_64-gnu/bin/clang`. Notice the difference between `linux64-x86_64-clang` and `linux64-x86_64-gnu`. 

### Steps to Reproduce

**Source Code:**

Chapel release 1.26.0

```chapel
// Please provide source code that will reproduce the problem.
// You can insert your code inline if it's not too long.
// Otherwise, you can attach it as a file or provide a URL to it.
// To the extent possible, providing simplified programs demonstrating the
// problem will be appreciated.
// You can also replace this section with "Associated Future Test(s)" below.
```

**Compile command:**

```
$ export CHPL_LLVM=bundled
$ ./configure --chpl-home=/path/to/opt/chapel-1.26.0
$ make -j16
...
cd standard/gen/linux64-x86_64-llvm && python3 /path/to/src/chapel-1.26.0/util/config/make_sys_basic_types.py ChapelSysCTypes.chpl
/bin/sh: /path/to/src/chapel-1.26.0/third-party/llvm/install/linux64-x86_64-clang/bin/clang: No such file or directory
ERROR: Found 0 max values, but 18 types were expected.
```

Looking for the `clang` binary, it's there but in a different directory:

```
$ find . -name clang
./third-party/llvm/install/linux64-x86_64-gnu/lib/clang
./third-party/llvm/install/linux64-x86_64-gnu/lib/cmake/clang
./third-party/llvm/install/linux64-x86_64-gnu/share/clang
./third-party/llvm/install/linux64-x86_64-gnu/include/clang
./third-party/llvm/install/linux64-x86_64-gnu/bin/clang
...
```

**Comment by bradcray** [comment]
Thanks for reporting this, @devreal!  Could you provide more information about what's leading to GCC being used in your build?  E.g., are you setting any of `CC`, `CHPL_HOST_CC`, `CHPL_TARGET_CC`, `CHPL_HOST_COMPILER`, `CHPL_TARGET_COMPILER`?  Could you provide the output of `$CHPL_HOME/util/printchplenv --anonymize`?

Thanks again.

**Comment by devreal** [comment]
GCC is loaded through a module and that seems to set the `CC` env variable:

```
$ env | grep CC
CC=/opt/hlrs/non-spack/compiler/gcc/10.2.0/bin/gcc
GCC_VERSION=10.2.0
MPICC=mpicc
SITE_GCC_HOME=/opt/hlrs/non-spack/compiler/gcc/10.2.0
MPICC_CC=/opt/hlrs/non-spack/compiler/gcc/10.2.0/bin/gcc
OMPI_CC=/opt/hlrs/non-spack/compiler/gcc/10.2.0/bin/gcc
```

The output of `printchplenv`:
```
$ ./util/printchplenv --anonymize
CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: llvm
CHPL_TARGET_ARCH: x86_64
CHPL_TARGET_CPU: native
CHPL_LOCALE_MODEL: flat
CHPL_COMM: none
CHPL_TASKS: qthreads
CHPL_LAUNCHER: none
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: cstdlib
CHPL_GMP: bundled
CHPL_HWLOC: bundled
CHPL_RE2: bundled
CHPL_LLVM: bundled *
CHPL_AUX_FILESYS: none
```

It looks like LLVM is built with GCC, leading to the triple `linux64-x86_64-gnu`.

**Comment by bradcray** [comment]
@devreal: Thanks for that additional information.  I forgot that `printchplenv` doesn't print out `HOST` information by default anymore.  If you could also attach the output of `printchplenv --all --anonymize` (or update the previous comment to show that), that'd be great just to make sure we have the full picture.

Guessing, though, I'm expecting that `CHPL_HOST_COMPILER` will show that it's defaulting to `clang` rather than `gnu` and that if you were to `export CHPL_HOST_COMPILER=gnu`, the correct paths should be used.  That said, I think there's a bug in our logic since if we're inferring the use of `gcc`, we should likely be inferring that `gnu` is the host compiler.  Let us know whether or not making that setting fixes things for you.

**Comment by devreal** [comment]
No problem, here is the full output:

```
$ ./util/printchplenv --anonymize --all
CHPL_HOST_PLATFORM: linux64
CHPL_HOST_COMPILER: gnu
  CHPL_HOST_CC: /opt/hlrs/non-spack/compiler/gcc/10.2.0/bin/gcc
  CHPL_HOST_CXX: /opt/hlrs/non-spack/compiler/gcc/10.2.0/bin/g++
CHPL_HOST_ARCH: x86_64
CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: llvm
  CHPL_TARGET_CC: /path/to/src/chapel-1.26.0/third-party/llvm/install/linux64-x86_64-gnu/bin/clang --gcc-toolchain=/opt/hlrs/non-spack/compiler/gcc/10.2.0
  CHPL_TARGET_CXX: /path/to/src/chapel-1.26.0/third-party/llvm/install/linux64-x86_64-gnu/bin/clang++ --gcc-toolchain=/opt/hlrs/non-spack/compiler/gcc/10.2.0
CHPL_TARGET_ARCH: x86_64
CHPL_TARGET_CPU: native
CHPL_LOCALE_MODEL: flat
  CHPL_GPU_CODEGEN: none
CHPL_COMM: none
CHPL_TASKS: qthreads
CHPL_LAUNCHER: none
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_HOST_MEM: cstdlib
CHPL_MEM: jemalloc
CHPL_ATOMICS: cstdlib
CHPL_GMP: bundled
CHPL_HWLOC: bundled
CHPL_RE2: bundled
CHPL_LLVM: bundled *
  CHPL_LLVM_CONFIG: /path/to/src/chapel-1.26.0/third-party/llvm/install/linux64-x86_64-gnu/bin/llvm-config
CHPL_AUX_FILESYS: none
CHPL_LIB_PIC: none
CHPL_SANITIZE: none
CHPL_SANITIZE_EXE: none
```

I replaced the paths but checked that all of them actually exist (they use the `linux64-x86_64-gnu` triplet, which is "correct").

**Comment by bradcray** [comment]
@mppf: Can you remind me whether this is expected or not?  I can't quite recall what happens with just CC set, though this behavior seems wrong to me (hence the "Bug" label).

**Comment by mppf** [comment]
It looks like a bug to me too but I don't know what is going wrong, yet. Reproducing the problem seems like the next step (but I have not tried to do that myself, yet).

Looks like `make_sys_basic_types.py` is running `util/config/compileline --compile` and that is giving the wrong compiler. I wonder if updating `make_sys_basic_types.py` to load up the chplenv Python code and just do the query it needs (instead of spawning a subprocess) would help. In particular, the `CHPL_TARGET_CC` output from printchplenv seems OK.

**Comment by bradcray** [comment]
And now I've built llvm bundled with those settings and have reproduced the issue in the OP.

**Comment by mppf** [comment]
@bradcray - regarding compileline, my concern was that it might be getting confused about something in the environment, where it might not be confused if `compileline` is run separately. Could you check to see if manually running `util/config/compileline --compile` reproduces the problem? If so then I would agree we should be adjusting compileline in some way.

Even so, I think it would be reasonable for `make_sys_basic_types.py` to handle it more directly, although that is not strictly necessary if we can fix `compileline`.

Also, for historical reasons, `util/config/compileline` runs a `make` command to print out the compile command, but at this point this should already be computed by `printchplenv` and related scripts - try e.g. `./util/printchplenv --all --internal | grep ARGS` to see what I mean. (And also `CHPL_TARGET_CC` etc variables are relevant).

**Comment by mppf** [comment]
> That said, note that `CHPL_TARGET_COMPILER` is `llvm` in all these runs. At which point, I can't remember... Is `compileline` correct to be using `clang` since `llvm` is the target compiler (in which case the error is that something about the build put things into `third-party/llvm/install/darwin-x86_64-gnu/` rather than `third-party/llvm/install/darwin-x86-64-clang/` because of CC being set to `gcc`)? Or should `compileline` be following `CC` regardless of what `CHPL_TARGET_COMPILER` is set to and be giving us ` gcc` command-line?

From https://chapel-lang.org/docs/usingchapel/chplenv.html#chpl-compiler :

> The *TARGET* variables above are not inferred from CC / CXX when CHPL_TARGET_COMPILER=llvm...

So I think that `compileline` should be ignoring `CC` if `CHPL_TARGET_COMPILER=llvm`.

**Comment by bradcray** [comment]
Thanks for that pointer!  So that suggests to me that the bug is not in the `compileline` script, but in the choice of `third-party/llvm/install/darwin-x86_64-gnu/` as the install directory name rather than `third-party/llvm/install/darwin-x86_64-clang/`.  Does that sound right?  Or is there some reason that that install directory name should be embedding the compiler implied by `CC` rather than the one that using the LLVM back-end would use by default?

**Comment by mppf** [comment]
Yes. I think it's likely the scripts are just confused because compiler relevant for the LLVM install is the *HOST* compiler which `CC` does influence, and which defaults to `gnu` / `gcc`. The part I do not have an explanation for is where `third-party/llvm/install/darwin-x86_64-clang/` is coming from.

**Comment by bradcray** [comment]
So, I got somewhere on this, but not terribly far:

Recall that, in my shell, `CC=/usr/bin/gcc`, `CHPL_LLVM=bundled`, and `CHPL_TARGET_COMPILER=llvm`.

If I do `cd modules && make` then I get the error we've been discussing:

```
/bin/sh: /Users/bradc/chapel/third-party/llvm/install/darwin-x86_64-clang/bin/clang: No such file or directory
```

However, if I run the same commands that `make module` is running manually:

```
$ cd standard/gen/darwin-x86_64-llvm && python3 /Users/bradc/chapel/modules/../util/config/make_sys_basic_types.py ChapelSysCTypes.chpl
```

then things work.  Putting some debug printing into `make_sys_basic_types.py` what I'm finding is that a major difference is that `CC=/path/to/third-party/third-party/llvm/install/darwin-x86_64-gnu/bin/clang -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -resource-dir /Library/Developer/CommandLineTools/usr/lib/clang/10.0.1 -mlinker-version=450` rather than `CC=/usr/bin/gcc`.  And I suppose that makes sense since we're focused on the target compiler environment, and this is the target CC, and I get the same thing when I do `make CHPL_MAKE_HOST_TARGET=--target print-CC`

So that suggests to me that there's something that's cueing off of `CC` when determining the llvm path when it should be cueing off of `CHPL_HOST_CC`.  But then the question is "Where?"

**Comment by bradcray** [comment]
Ah, I _think_ I can describe the cause of the problem now:

So, when `modules/Makefile` includes `Makefile.base` after setting `CHPL_MAKE_HOST_TARGET=--target`, part of what `Makefile.base` does is set up `CC` and `CXX` to be ready to compile things for the target.  This sets CC to point to the bundled LLVM clang.  But once `CC` is set to that, subsequent calls to the `util/` scripts to determine [anything at all] will infer that the host compiler is the bundled version of clang since that's what CC is set to.  And the call from `make_sys_basic_types.py` to `compileline` is presumably just such a call (?).

Why does `CC` matter?  Because when we're building the bundled LLVM, we embed the C compiler with which we built it into its install path via `$CHPL_LLVM_UNIQ_CFG_PATH`.  So our scripts simultaneously need CC set to the host compiler (to determine the path to find the appropriate built bundled version of clang ) yet also to the target compiler (to invoke that clang itself to generate the module).  Yet it obviously can't be both at once.

Notably, if I comment out the CC and CXX lines from `make/compiler/Makefile.clang` (which is not a fix, but just as an experiment to avoid overriding the user's setting), the `make modules` step works.

All that said, I'm not sure to fix it, and (Michael) am hoping that having wired up a bunch of this you might.  A few ideas that occurred to me which I'm not particularly wild about:
* maybe `Makefile.base` shouldn't set CC/CXX by default, but that an additional `include Makefile.setCC` should be included only once one is ready to set them.  Thus, for this `modules` Makefile, we would only include the former and not the latter (?).  But it feels finicky to insert that latter include in all the right places.
* maybe none of our Makefiles should set or use CC/CXX, but should use CHPL_MAKE_[HOST|TARGET]_[CC/CXX] instead?  This might be OK except that I can't recall whether we always invoke CC/CXX explicitly, or whether we ever rely on any of the implicit/built-in Makefile rules to do so.  I'd guess they might all be explicit, but...?
* or maybe we should stop uniquifying the bundled LLVM install directory by host compiler?  Or should use some other way of identifying/querying the host compiler than calling another `util` script?

Of these, the "maybe Makefiles shouldn't use CC/CXX" feels the cleanest to me, though I think it may also run into some challenges because of using the same "How to change a .c into a .o" rules in the runtime Makefiles for both host and target compiles...?

**Comment by bradcray** [comment]
Ah, what about this:  Maybe we can use the CHPL_HOST_COMPILER setting when uniquifying the LLVM build directories (rationale: won't mix and match your .o files) without using it when uniquifying the install directories (rationale: because once it's installed, you probably don't care what it was built in anymore, much like how once we build `chpl` we don't have the `bin` directory encode which compiler it was built with?).  ???

**Comment by bradcray** [comment]
I've filed a proposed solution to this in https://github.com/chapel-lang/chapel/pull/19939

**Comment by mppf** [comment]
> * maybe none of our Makefiles should set or use CC/CXX, but should use CHPL_MAKE_[HOST|TARGET]_[CC/CXX] instead?  This might be OK except that I can't recall whether we always invoke CC/CXX explicitly, or whether we ever rely on any of the implicit/built-in Makefile rules to do so.  I'd guess they might all be explicit, but...?

> Of these, the "maybe Makefiles shouldn't use CC/CXX" feels the cleanest to me, though I think it may also run into some challenges because of using the same "How to change a .c into a .o" rules in the runtime Makefiles for both host and target compiles...?

I agree with this. I think that, long term, we should stop using CC/CXX in the Makefiles and instead use CHPL_MAKE_[HOST|TARGET]_[CC/CXX]. However I don't think we have to do that right now. In particular, if I succeed in arguing that we should have the compiler itself build with `cmake`, I think this problem would become moot.

**Comment by bradcray** [comment]
@devreal: Thanks very much for reporting this as it's something that I'm not sure we would've run into ourselves in short order (due to a combination of rarely doing both the bundled LLVM build and having CC set).  It should be fixed on `main`, and while I don't wish an LLVM rebuild on anyone, if you find otherwise in the future, please let us know.
