### ISSUE TITLE
I/O module: should we change or deprecate %t for readf/writef?

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#19906]
Spin-off from #19498.

In the Encoder/Decoder design, we are splitting the methods on channel/reader/writer in to methods that work with the Encoder/Decoder and methods that ignore it (see https://github.com/chapel-lang/chapel/issues/18504#issuecomment-1118972138 ). For the most part, `read` / `readln` / `write` / `writeln` are the only ones that work with the Encoder/Decoder. However, there is one exception. The `readf` / `writef` calls generally ignore the Encoder/Decoder but when using the `%t` format string they will work through the Encoder/Decoder. This makes it an outlier and an exception to the more general rule about which methods work with the Encoder/Decoder.

%t is also an odd thing in format strings because it's not really clear how precision or length should work with it. Say you are printing a record with a few float fields, what should "%3.1t" mean? Should it be controlling the total object or adjusting the formatting of each field within it? We have this problem also for complex numbers -- see #18498.

What should we do about this? Some possibilities:

A. Do nothing - %t is OK the way it is.
 * idea here would be that the exception is understandable because it is the purpose of %t to behave as if calling read/write
 * still have to make a decision about what field width / precision mean in this context
 
B. Change %t to only apply to builtin types
 * "You know what this argument's type is, so please just print it out the default way rather than making me tell you its type." ( https://github.com/chapel-lang/chapel/issues/19498#issuecomment-1140093435 )
 * Note that we already have %n for any numeric type. %t would also include bytes and string.

C. Replace %t with %? which only applies to builtin types.
 * %? is unused so far in format strings and might be more intuitive

D. Deprecate %t without replacement
 * expecting that people can just write separate read/write calls in addition to readf/writef

**Comment by lydia-duncan** [comment]
I like the idea of having a `%<any>` that behaves the same as `%<explicit type>` when sending an explicit type in.  If sending the same value through the general format specifier and the specific one doesn't do the same thing, I think that's doing something different than what `%t` does today and so should be considered a breaking change.

I would expect `%t` to be more in line with `%<explicit type>` than I would expect it to be in line with `write(<same argument>)` and would be inclined to report it as a bug if I found otherwise if I was a user and not someone contributing to this project.  I think it's at least partially because the change between `%t` and `%<explicit type>` is a single character, whereas the change between `%t` and `write(<same argument>)` is much more significant.  I'm far less likely to intermingle the latter set of calls on my own, I'll default to using `write(a, b, c, d)` because I like it better but if I'm modifying a code that is already using format strings, I'll continue using them and would be likely to use `%t` for cases where I don't know the type and `%<explicit type>` when I do.

**Comment by lydia-duncan** [comment]
With that in mind, I don't have a problem with `%t` not applying to types that don't have their own `%<explicit type>` letter

**Comment by bradcray** [comment]
I like B and C the best.  I'd probably rank them B, C, A, D.

**Comment by jeremiah-corrado** [comment]
> %t is also an odd thing in format strings because it's not really clear how precision or length should work with it. Say you are printing a record with a few float fields, what should "%3.1t" mean?

One potential approach to address this ambiguity is to temporarily store the precision/length information in the `fileWriter` such that it can be queried by the type's `myType.serialize` implementation. I'm imagining something like the following:

```chapel
record realPair {
  var x: real;
  var y: real;
}

proc realPair.serialize(writer: fileWriter) throws {
  if var pls = writer.precisionLengthString() {
    // write with the provided precision
    writer.writef("("+pls+", "+pls+")", this.x, this.y);
  } else {
    // otherwise, use some default precision
    writer.writef("(%.5r, %.5r)", this.x, this.y);
  }
}

// ...

var r = new R(0.123456789, 3.1415926535);

stdout.writef("%t", r);    // prints: "(0.12345, 3.14159)"
stdout.writef("%.10t", r); // prints: "(0.123456789, 3.1415926535)"
```

(This is inspired by Rust's solution to this problem. See their [`Formatter.precision`](https://doc.rust-lang.org/std/fmt/struct.Formatter.html#method.precision) and [`Display Trait`](https://doc.rust-lang.org/std/fmt/trait.Display.html) docs.)

For standard library types like complex numbers, and for compiler generated `serialize`, we'd still need to come up with a policy for how precision/length information is used. I suppose the simplest policy would be: "the precision and length of all `real` fields (or fields containing `real`) will be modulated by the precision and length arguments in the format string"

But this approach is nice because it allows users to overwrite `serialize` s.t. they can opt out of the default behavior. I.e., length/precision arguments can be ignored, only applied to some fields and not others, etc.

Generally, I think this approach would make option A pretty attractive.

**Comment by lydia-duncan** [comment]
Summary for the upcoming ad-hoc design discussion

### 1. What is the API being presented?
```chapel
writef("%t", <some arg>);
readf("%t", <some arg>);
"%t".format(<some arg>);
```

We want to talk about how it should behave on two avenues:
- Relative to other read/write calls
E.g.
```chapel
use IO;

var s: string = "This is a string";
write(s);
writeln();
writef("%t\n", s);
```

Where the output is
```
This is a string
"This is a string"
```

- Relative to the individual format specifiers
E.g.
```chapel
use IO;

var s: string = "This is a string";
writef("%s\n", s);  // print a string
writef("%S\n", s);  // print a string with quotes always
writef("%t\n", s);
```
Where the output is
```
This is a string
"This is a string"
"This is a string"
```

Those two examples are using the default behavior (where I believe only strings currently differ from their individual format specifier).  Note that using the (soon to be replaced with a serializer/deserializer) `%h` and `%j` prefixes causes `%s` and `%t` to be unified in their behavior:

```chapel
use IO;

var s: string = "This is a string";
writef("%hs\n", s);
writef("%ht\n", s);
```
gives the output:
```
"This is a string"
"This is a string"
```

Reminder: `%h` is for "Chapel formatting" and `%j` is for JSON.  While serializers/deserializers are intended to replace these features, an argument can be made that their different use case motivates a different treatment - `%h` and `%j` are visible in the format string itself, while serializers/deserializers are not going to be obvious in every single call involving the fileReader/fileWriter.

Here's what happens for reading with `%s` and `%t`:
```chapel
use IO;

var r = openReader("foo.txt");
var s1: string;
var s2: string;
r.readf("%s", s1);
r.readf("%t", s2);
writeln(s1 == s2);
```

With a text file:
```
This is a string
This is a string
```
the Chapel code will throw a bad format error when attempting to read with `%t` due to failing to find a starting `"`.

With a text file:
```
"This is a string, too"
"This is a string, too"
```
the Chapel code will also throw a bad format error at the same line because the read with `%s` will not grab the full line, only `"This` and so won't be at the right position in the file to start reading with `%t`.  Using `%js` instead will cause `%s` to look for `"` at the start and end, allowing the code to execute and giving s1 and s2 the same value.

I suspect that some of the rationale behind `%t` matching `%S` instead of `%s` is that the presence of `"` allows us to distinguish between when a number is meant to only be read as a number versus when it is intended to be read as a string.  Arguably using `%s` implies a greater amount of intentionality than `%t` when the corresponding argument happens to be a string.

Also important to note is that `%t` can currently be used with things that don't have an individual format specifier, like classes and records.  In these cases, `%t` will use the type's `readThis` or `writeThis` method as appropriate.

### How is it intended to be used?
Used as a way to indicate the argument should be formatted without explicitly specifying the type.  Can enable use in generic contexts or copying the call to use later in your code without requiring modification

### How is it being used in Arkouda and CHAMPS?
In Arkouda, there are ~287 uses (though it seems to frequently, but not exclusively, be used where `%n` would also work).  Looks to be especially helpful for their error and logging messages.

CHAMPS does not seem to use `%t`.

In our repository, it is used twice in the MemMove module and 90 times in the test directory.  Of the test directory uses, only 8 are in benchmarks and user code (2 in `test/npb/is/mcahir/intsort.mtml.chpl`, 4 in `test/users/npadmana/mpi/test_mpi.chpl`, 1 in `test/users/npadmana/mpi/transpose.chpl` and 1 in `test/studies/lsms/shemmy/s-lsms.chpl`), though most of the rest are not testing `%t` itself but rather are using it to validate a different feature.

### 2. What's the history of the feature, if it already exists?
Was added with readf/writef support in 2013 and has been basically unchanged since.  Is partially handled in the runtime and partially in module code, using `QIO_CONV_ARG_TYPE_REPR` to represent it.  Documentation of it was added with the initial feature.

### 3. What's the precedent in other languages, if they support it?
Conceptually, it is not specified as part of the [IEEE specification for print](https://pubs.opengroup.org/onlinepubs/009695399/functions/printf.html), so is not part of C, Julia or Swift.  Note that the IEEE specification does use `t`, but as a length modifier:
> Specifies that a following d, i, o, u, x, or X conversion specifier applies to a ptrdiff_t or the corresponding unsigned type argument; or that a following n conversion specifier applies to a pointer to a ptrdiff_t argument.

I don't see a conceptual equivalent in Python and Rust doesn't allow specifying explicit types in its format strings so it isn't really necessary there.

### 4. Are there known Github issues with the feature?
- Mentioned as part of the grab bag of IO documentation improvements, #18522
- formats generally are mentioned here (but not this one specifically): #7846
- printing with ranges display differing: #22250

### 5. Are there features it is related to?  What impact would changing or adding this feature have on those other features?
- We were considering replacing stringify with uses of it in: #20256
- There's also talk about how its behavior relates to that of `read`, `readLine` and `readln` in #19498, #14107 and #7952
- Interaction with serializers/deserializers is part of the motivation behind this discussion: #18504
- Interaction with the modifying specifiers is also relevant (though discussion on those is also ongoing): #18497

### 6. How do you propose to solve the problem?
There's a cross-product of decisions that could be made here.  For clarity (and so we don't forget something), I'll be enumerating individual possible decisions and we will decide on the combination that makes the most sense.

--------

Proposal 1A. `readf`/`writef` don't interact with the serializer/deserializer.
  - Pros:
    - Simplifies description of format specifier behavior, as it will be predictable and consistent
  - Cons:
    - `readf`/`writef` won't be useful with serializers/deserializers (but they aren't the only methods that behave like that)

Proposal 1B. `readf`/`writef` rely on the serializer/deserializer for all the format specifiers.  When a serializer/deserializer is not present (such as in the case of `"%t".format`), the default serializer/deserializer will be used.  This will mean that for certain serializers/deserializers e.g., JSON, `%s` and `%S` will match.
  - Pros:
    - Behavior will be unified with `read` and `write`
  - Cons:
    - If want default behavior, will have to provide default serializer/deserializer

Proposal 1C. `readf`/`writef` don't rely on the serializer/deserializer for individual format specifiers but do for `%t`.  When a serializer/deserializer is not present (such as in the case of `"%t".format`), the default serializer/deserializer will be used.
  - Pros:
    - Still have way to get default behavior without providing default serializer/deserializer
    - Behavior for individual format specifiers is predictable and consistent
  - Cons:
    - `%t` and matching individual format specifier may differ depending on the serializer/deserializer used, which seems potentially confusing.

------

Proposal 2A. Continue to maintain `%t`, supporting all types, including those without an individual format specifier
  - Pros:
    - What we have today, minimal code changes
    - Allows classes, records, arrays, domains and ranges in format strings, which can make a call involving them look more natural
  - Cons:
    - Differs from other languages, due to both providing a general format specifier and due to the use of `t`
    - What should format prefixes like, e.g. `%6` do when applied to a class or array? (where the answer today seems to be "nothing")

Proposal 2B. Limit `%t` to only supporting types with individual format specifiers.
  - Pros:
    - Less code to maintain, especially if decide to keep the serializer/deserializer implementation separate from readf/writef
    - Don't have to define what the format prefixes like, e.g., `%6` do for classes, etc.
  - Cons:
    - No format specifier support for classes, records, arrays, domains, ranges
    - Still differs from other languages, due to both providing a general format specifier and due to the use of `t`

Proposal 2C. Replace `%t` with a different specifier that only works for types with individual format specifiers.  The proposed version was `%?` in the OP but we could also consider something else.
  - Pros:
    - Easier deprecation than 2B
    - No longer will be using a symbol that other languages define for different behavior
    - Less code to maintain, especially if decide to keep the serializer/deserializer implementation separate from readf/writef
    - Don't have to define what the format prefixes like, e.g., `%6` do for classes, etc.
  - Cons:
    - No format specifier support for classes, records, arrays, domains, ranges
    - Still differs from other languages due to providing a general format specifier

Proposal 2D. Drop support for `%t` entirely
  - Pros:
    - Don't have to define what the format prefixes like, e.g., `%6` do for classes, etc.
    - Easier deprecation than 2B
    - Less code to maintain, especially if decide to keep the serializer/deserializer implementation separate from readf/writef
    - No longer will be using a symbol that other languages define for different behavior
  - Cons:
    - No format specifier support for classes, records, arrays, domains, ranges
    - Still differs from other languages due to providing `%n`, but the difference will still be reduced

--------

Proposal 3A. `%t` behaves the same as it does today w.r.t. strings - it will continue to involve `"` like `%S` while `%s` will not
  - Pros:
    - Consistent with a format specifier for strings
    - Enables reads to more easily mirror writes due to requiring an obvious start and end point
    - Less changes overall
  - Cons:
    - Not consistent with the format specifier for strings that people are most likely to turn to

Proposal 3B. `%t` will adjust to match `%s` instead of `%S`.  If there are scenarios where `%s` will also have quotes, then so will `%t`.
  - Pros:
    - Consistency with the format specifier for strings that people are most likely to turn to
  - Cons:
    - Reads with `%t` won't necessarily mirror writes due to only reading a single word instead of all enclosed symbols
    - More changes to implement

---------

I have a preference for 1A, 3A and am leaning towards 2A due to its frequent use in Arkouda

**Comment by lydia-duncan** [comment]
Added a proposal 2E based on an idea Michael had in the IO sub-team meeting yesterday

**Comment by mppf** [comment]
> I have a preference for 1A, 3A and am leaning towards 2A due to its frequent use in Arkouda

I don't understand how 1A can combine with 3A. In particular, I would think 1A would mean completely deprecating `%t`, because I think the main purpose of `%t` is to do things like print user-defined records. Is the proposal in 1A really that `%t` is only available for the types supported in the format strings with some other name? That might be good to clarify.

Re Proposal 2E:

I like the idea of being able to put a minimum field width on a `%t` and I think that works today but I am not certain. That feature allows easily making tables even if the printed table elements are records/tuples/etc (so it has a use case) but I'm also open to dropping the feature.

**Comment by lydia-duncan** [comment]
> I don't understand how 1A can combine with 3A. In particular, I would think 1A would mean completely deprecating `%t`, because I think the main purpose of `%t` is to do things like print user-defined records. Is the proposal in 1A really that `%t` is only available for the types supported in the format strings with some other name? That might be good to clarify.

Good question!  My expectation is that if `%t` is not relying on the serializer/deserializer, then it needs to rely on something else to determine its behavior.  In the case of types that have their own individual format specifier, I would expect them to follow the same code path (so `writef("%t %i", a, a)` would always print the exact same thing twice).  Basically, of the three "1" proposals, only 1C results in that call having different output.  I view the question of whether `%t` handles other types to be handled by the "2" proposals, or at least the union of the selected "1" proposal and the selected "2" proposal.  I don't remember if the decision was that readThis/writeThis will have to interact with the serializer/deserializer, but that would definitely be an easy candidate for how to continue to support user defined classes and records.

> I think the main purpose of `%t` is to do things like print user-defined records

That's not how it's used in practice.  At least in the cases I was seeing with arkouda, there were plenty of uses of `%t` where `%n` or `%S` would have been appropriate, in addition to the cases where it was used with classes/records/enums/etc.  It's definitely important to think about whether it will continue to interact with records and how, but that really should be handled by the decision on the "2" proposals.

> I like the idea of being able to put a minimum field width on a `%t` and I think that works today but I am not certain.

I meant to put that somewhere but it looks like I forgot.  It does not seem to do anything, at least for arrays:
```chapel
use IO;

var arr: [0..3] int;
writef("%16t blah\n", arr);
```
results in 
```
0 0 0 0 blah
```

**Comment by jeremiah-corrado** [comment]
Yes, I forgot to close. Thanks!
