### ISSUE TITLE
iteration over a literal `int(64)..#uint(32)` range yields int(32)s

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#19958]
### Summary of Problem

It seems to be that iterating over a uint/uint(32) range yields the corresponding signed type (int/uint(32)). I would expect it to yield the same type as the index type.

https://chapel-lang.org/docs/language/spec/ranges.html#range-types seems to imply that the stride is signed but the index type would remain unsigned in this case.

### Steps to Reproduce

**Source Code:**

```chapel
var u32:uint(32) = 2;
writeln("iterating over 0..#u32");
for x in 0..#u32 {
  writeln(x, ":", x.type:string);
}

var u64:uint(64) = 2;
writeln("iterating over 0..#u64");
for x in 0..#u64 {
  writeln(x, ":", x.type:string);
}
```

```
$ chpl cc.chpl  && ./cc
iterating over 0..#u32
0:int(32)
1:int(32)
iterating over 0..#u64
0:int(64)
1:int(64)
```

Interestingly, the problem seems to only appear when using the `#` operator. These cases don't show the problem:

``` chapel
writeln("iterating over 0..2:uint(8)");
for x in 0..2:uint(8) {
  writeln(x, ":", x.type:string);
}
writeln("iterating over 0..<u8");
for x in 0..<u8 {
  writeln(x, ":", x.type:string);
}
```

**Associated Future Test(s):**
TODO

**Comment by mppf** [comment]
> This seems correct to me. 0.. is a range(int(64)) and the # operator returns a range of the same type as its argument. No?

Wait but then why does iterating over `0..#u32` produce `int(32)` (vs `int(64)` which `0..` would have as index type)?

**Comment by cassella** [comment]
That's a good question.  I didn't think about that part.

**Comment by bradcray** [comment]
I'm probably at least partially responsible for the cause of this behavior.  I agree both with Paul's original interpretation and Michael's point about it not being realized in [this comment](https://github.com/chapel-lang/chapel/issues/19958#issuecomment-1149990223).

**Comment by cassella** [comment]
This may repeat somewhat the previous notes, but this shows:

1. Creating a range variable of `0..#u32` creates a range(int(64)) and yields int(64). (correct)
2. Asking `0..#u32` what its type is results in `range(64)` (correct)
3. Iterating over `0..#u32` yields `uint(32)` (incorrect)
4. Iterating over `s64..#u32` yields `int(64)` (correct).


```chapel
var u32 = 2:uint(32);
var s64 = 4:int(64);

var r = 0..#u32;
writeln("r: ", r.type:string);
for i in r { writeln(i, ": ", i.type:string); }

writeln("type of literal range: ", (0..#u32).type:string);
for i in 0..#u32 { writeln("again with literal: ", i, ": ", i.type:string); }

for i in s64..#u32 { writeln("again with literal-non-param range: ", i, ": ", i.type:string); }
```

```
r: range(int(64),bounded,false)
0: int(64)
1: int(64)
type of literal range: range(int(64),bounded,false)
again with literal: 0: int(32)
again with literal: 1: int(32)
again with literal-non-param range: 4: int(64)
again with literal-non-param range: 5: int(64)
```

I don't see anything quickly in `ChapelRange.chpl` that would explain that.  Does the compiler itself do anything special for iterating over range expressions?

> I'm probably at least partially responsible for the cause of this behavior.

Do you mean a particular PR?

**Comment by bradcray** [comment]
Thanks Paul, that's both helpful and encouraging (specifically, that it seems related to iterating over range literals, which I had not picked up on before).

> Do you mean a particular PR?

I don't have anything specific in mind, but was just thinking that I'd done a decent amount of work on the `#` operator and the "create a new range" code, so seemed like a likely suspect.  That said, given that the error seems specific to iteration, it makes me think that the cause is now more likely to be due to some of our optimized implementations of for loops, which have been jointly contributed to by Elliot and me.  So maybe I can still clear my name.  :)

Oh, and we have a handy flag to disable those optimizations, which makes that case behave as expected:  `--no-optimize-range-iteration`.  So that makes it most likely that it's me or Elliot.

And checking the code, it looks like this comment is related:

```c
    // replace a counted, low bounded range with unit stride with an equivalent   
    // direct range iter. e.g. replace:                                           
    //                                                                            
    //   `low..#count` (which is equivalent to `low..low+count-1`)                
    //                                                                            
    // with:                                                                      
    //                                                                            
    //   `chpl_direct_range_iter(low, low+count-1, 1)`                            
    else if (count && range && range->isNamed("chpl_build_low_bounded_range"))
    {
      Expr* low = range->get(1)->copy();
      iteratorExpr->replace(new CallExpr("chpl_direct_counted_range_iter", low, c\
ount));
    }
```

in that `low..#count` isn't identical to `low..low+count-1` in this case because when `low` is a `param`, it's willing to downcast to `count.type` whereas when it's not `param` it wouldn't.  So a simple fix might be to disable the optimization when the types don't match, while a more satisfying one would be to cast the `count` value to `low`'s type in the event that it's safe to do so (?).

Tagging @ronawho for his own curiosity.

(FWIW, Paul, I'm not sure what to make of your `u64..#u32` case above.  Am I reading correctly that the error message seems to have the types of the low and count value backwards, or did something get cut-and-pasted wrong?)

**Comment by cassella** [comment]
> (FWIW, Paul, I'm not sure what to make of your `u64..#u32` case above. Am I reading correctly that the error message seems to have the types of the low and count value backwards, or did something get cut-and-pasted wrong?)

Oops, I copy and pasted the error message correctly, but typed in the instigating case from memory.  I'll fix that.

**Comment by ronawho** [comment]
This is almost certainly the casting in `chpl_direct_counted_range_iter_helper`:

https://github.com/chapel-lang/chapel/blob/b1f1abb19a39b91e3ee25cb8caeca3b203dd55da/modules/internal/ChapelRange.chpl#L2110-L2111

I think we could do something to fix this casting or we could remove the `chpl_direct_counted_range_iter` overload for `int` low and `uint` count.

**Comment by damianmoz** [comment]
Something does not make sense here. Or maybe I have not recovered from a lack of sleep last night while recovering from CHIUW

I need to look at this in more detail. Is the issue that it should be unsigned or that it is 32 bits wide?

**Comment by damianmoz** [comment]
What version of the compiler please?

**Comment by mppf** [comment]
> Something does not make sense here.

I think we all agree about that!

> Is the issue that it should be unsigned or that it is 32 bits wide?

I think, in the discussion, we are thinking that `0..#x` should always lead to a range that uses `int` as the index type, regardless of the type of `x`. The thought here is that `0` is an `int` and `#x` just says "give me x index values from the range" -- but just saying "give me x of them" shouldn't affect the index type. Anyway, if you want a range that is not using the `int` index type, you can change the type of the starting value, or use `0..<x`, which will end up with an index type matching `x`'s type in this specific case.

We do get `int` out of iterating with a variable low bound `zero..#x` (with `var zero:int = 0;`) but not with a param low bound `0..#x`. We think it is a bug. I originally saw the issue on `main` but I've been able to reproduce the issue on 1.25.1.

Here is the program showing the problem again but with one more variation and comments about what happens:

``` chapel
var u32:uint(32) = 2;
writeln("iterating over 0..#u32");
for x in 0..#u32 {
  writeln(x, ":", x.type:string); // output 0:int(32) -- BUG
}

var zero:int = 0;
writeln("iterating over zero..#u32");
for x in zero..#u32 {
  writeln(x, ":", x.type:string); // output 0:int(64) -- correct
}

var u64:uint(64) = 2;
writeln("iterating over 0..#u64");
for x in 0..#u64 {
  writeln(x, ":", x.type:string); // output 0:int(64) -- correct
}
```

**Comment by mppf** [comment]
@bradcray @ronawho - in trying to fix it, I am seeing another problem in the same area of the code, where iterating over a range with a particular combination of types does not generate a compilation error, but constructing that range in a different context does:

``` chapel
var a:int(32) = 1;
var count:int(64) = 2;
for i in a..#count { // should result in compilation error, right?
  writeln(i);
}
writeln(a..#count); // results in compilation error today
```

(where on `main` today we only get the error for the last line).

I am planning to fix this as well.

**Comment by damianmoz** [comment]
Here is my 2c (which is concise but disagrees somewhat with the above).

A range is something with a lower bound, upper bound and a stride, each of which can have a **type**, and a comparison operation (boolen expression involving integral types) at the end of range when processing..

Technically, each of those 3 can be expressions, even if for many examples, those 3 items are **const** or **param** elements (as far as the definition of the **range** is concerned).

You treat the **type** of the range as the _dominant_ type seen across all the 3 elements.

My ideas disagree with what you have. But conceptually, they are not identical to what Chapel now has in integral (and floating point) expressions. Note that when there are only implicit **param**s and explicit **const** elements in those expressions, the type of the former, which is an **int**(_64_) in Chapel, must NEVER dominate. This means that an expression like
```chapel
const zero = 0:int(32);
const two = 2:int(32);
const r = zero .. 2147483647 * two;
```
will generate rubbish because that 2147483647 which is an implicit **int**(64) cannot influence the type of the edges of the range. That said, the compiler is free to complain about the inaccuracy (and impracticality) of trying to store the value of that expression in an **int**(32).

Hopefully I make sense.

**Comment by mppf** [comment]
> Note that when there are only implicit **param**s and explicit **const** elements in those expressions, the type of the former, which is an **int**(_64_) in Chapel, must NEVER dominate. This means that an expression like
> 
> ```chapel
> const zero = 0:int(32);
> const two = 2:int(32);
> const r = zero .. 2147483647 * two;
> ```
> 
> will generate rubbish because that 2147483647 which is an implicit **int**(64) cannot influence the type of the edges of the range.

Right, `2147483647` is `max(int(32))`, and the expression `2147483647 * two` will be (by design) evaluated as `int(32)`. It was my understanding that is what you have wanted, since if you are working with 32-bit ints, it would be surprising if e.g. `7 * two` resulted in a 64-bit int. Certainly in this case, the 32-bit multiplication overflows.

> Hopefully I make sense.

The part I am not following is - are there code examples that you wish to behave differently? You included one code example but it isn't clear to me if you are advocating for it compute the upper bound as a 64-bit int. (Here `2147483647 * two` is computed as an `int(32)` multiplication - anywhere it appears - so that seems pretty independent of considerations about ranges).

Note that this specific issue is only about the counted range iteration e.g. `for i in x.. # count` with different types of `x` and `y`.

**Comment by bradcray** [comment]
I think a problem with trying to equate range operations and mathematical operations today is that we don't have a notion of `param` ranges yet.  So where, today, `0 + myInt32` will result in an int(32) because the compiler treats 0 as a `param` that can implicitly downcast to another integer size (like `int(32)` here), one might expect `0..#myInt32` to similarly result in a range of int(32)s since the `0..` range is a param, and `#` is an operator.  And arguably, it would be more consistent with integers if we were to downcast the range from `range(int(64))` to `range(int(32))`.  However, because we don't have param ranges (and therefore don't have special downcasts for them), this does not happen.

Note that the form `0..<myInt32` does result in a range of type `range(int(32))` where the reason is that the operator isn't taking a range and some integer value, but two integers.  As a result, it can see that 0 is a `param int(64)` and that `myInt32` is an int(32)` and infer the appropriate index type for the resulting range.  This is one of several reasons that I prefer the `..<` operator when creating 0-based ranges over `#` (the others being that I think it's more self-documenting and slightly more precise / less roundabout).

**Comment by damianmoz** [comment]
Thanks @bradcray, that **param** stuff address the gap in my knowledge that was so clearly missing.

As to the question  "are there code examples that you wish to behave differently", the answer is No. My apologies that my words gave the impression that I wanted something different. I thought I had been very careful but sadly not.

While "this specific issue is only about the counted range iteration e.g. for i in x.. # count with different types of x and y", I was thinking more broadly. So whether the range is defined with explicit limits, a count with # or a bound with <, where any low, high or stride component of that range can be an expression, the rules are the same. Even
```chapel
const r = zero ..  2147483648 * two;
```
should yield an **int**(_32_) range with rubbish data and a warning about representational inaccuracy.

**Comment by bradcray** [comment]
> So whether the range is defined with explicit limits, a count with # or a bound with < [...], the rules are the same. 

Until we have param ranges, I don't think this can be the case.  Or, rather, I think the rules are the same, but they will _feel_ different to you.

Specifically, unlike `..` and `..<` which are binary operators that take zero, one, or two bounds and make a range from them, `#` is an operator that takes a range, domain, array, etc. and counts off that many values from it.  So while `0..#n` and `0..<n` may look and act similarly, the first says "take the unbounded range `0..` and count off the first `n` elements from it."  As a result, the range is only defined by its single, lower bound, and since it's an int(64), it's a range of int(64)s.  In contrast `0..<n` is a range of whatever type `param int(64)` and `n.type` unify to.

So, until/unless we have `param` ranges, I don't think there's a way to make these behave equivalently, unfortunately.  But, I also think that the current behavior is rationalize-able and that if we train people to use `0..<n` when creating a 0-based range, there will not be many surprises.

**Comment by damianmoz** [comment]
I will have to be ultra-careful with defining ranges in the future. I see that
```chapel
const p = 1..6;
const q = 1..<7;
const r = 1.. #6;
```
always gives me a range with indices which are **int**(_64_). This is not something I can see being what I would ever want.

**Comment by damianmoz** [comment]
Please compile and comment why Problem Child will not compile and yet Little Angel does? What is the difference?
```chapel
const one = 1:int(32);

proc show(lo, hi)
{
    const r = lo..#hi;
    const s = lo..hi;

    writeln(lo, " ", hi);
    write('\tlo ', lo.type:string);
    write( " and ", 'lo ', r.low.type:string);
    writeln(" and ", 'hi ', r.high.type:string);
    write('\thi ', hi.type:string);
    write( " and ", 'lo ', s.low.type:string);
    writeln(" and ", 'hi ', s.high.type:string, "\n");
}

show(0:uint(32), 2:uint(32));
show(0:int(32), 2:uint(32));
show(0:uint(32), 2:int(32));
show(0:int(32), 2:int(32));
show(one, 6); // Problem Child
show(one, 6:int(32));

var a:int(32) = 1;
var count:int(64) = 2;

for i in a..#count
{
    // should result in compilation error, right?
    writeln(i);
}
writeln(a..#count:int(32)); // all good
writeln(one..6);
writeln(one..#6); // Little Angel
writeln(one..<7);
```

**Comment by bradcray** [comment]
For those who don't want to compile, this generates the error:

```
testit.chpl:3: In function 'show':
testit.chpl:5: error: can't apply '#' to a range with idxType int(32) using a count of type int(64)
  testit.chpl:21: called as show(lo: int(32), hi: int(64))
note: generic instantiations are underlined in the above callstack
```

There are arguably two reasons that this doesn't work:

* the first relates to the reason why 'Little Angel' does work.  In its case, the `6` argument is supplied as a `param`, so the compiler can reason about it, determines that it's safe to downcast to an `int(32)` since it's a sufficiently small value, and does so.  Whereas the formal arguments to `show` are not declared as `param`, so the compiler is not able to reason about the numerical values passed to `hi`, and can't do the similar downcast
* the second could be argued as being a matter of over-conservatism.  Specifically, the current implementation of `#` conservatively says "Well, a count of type `int(64)` _could_ exceed `2**32`, therefore we'd better not support applying it to a range of `int(32)` (much like how `+` doesn't allow `int(64)` values to be added to `int(32)` values without a user downcast of the `int(64)` or an implicit upcast of the `int(32)`).  That said, I think it _could_ be argued that `#` should accept integers of any width so long as the value in question does not exceed the size of the range (or the maximum possible size in the case of an unbounded range).  I expect the current approach was taken in part to reflect some symmetry with `+` (though note there's also a slight asymmetry in designing the `#` operator to not change the type of the range, such that it is not upcast to `range(int(64))`), and in part because we could relax it without breaking code, whereas if we supported it and decided we were wrong, we'd be taking something away from users.  I think it would be completely reasonable to open a feature request asking that `#` accept any `integral` as its second argument, relying on dynamic bounds checks to make sure it worked if you (or anyone) wanted to request that.

**Comment by bradcray** [comment]
> maybe it should just look at treating range operations like mathematical operations

I'm not sure precisely what you're suggesting when you say that.  Here are two guesses:

* You may be saying that ranges should support `param` values, which would permit `param` ranges to downcast when appropriate.  We would completely like that as well (and I expect we'll have them someday), but adding that support is a lot of work that we have not been able to prioritize to date.  Note that it is challenging because we'd either need to replicate all of the Chapel code that implements ranges in the compiler; or we'd need to add support for more general `param` records and methods on those records so that the compiler could evaluate the code that implements ranges at compile-time.
* Or, you may be saying that when an operator like `#` applies to a range and an int, the behavior should be more like `+`.  But I don't think that this is actually all that attractive.  Specifically, an `int(32) + int(64)` in Chapel will produce an `int(64)`.  But I think if a user had gone to the trouble to create a range of `int(32)`'s, they would be upset if applying a `#` to it using an `int(64)` would suddenly turn it into a range of `int(64)`s.  So where `+` feels like a symmetric operator w.r.t. its arguments, to me `#` (and `by` and `align` and the like) feel a though the range should generally be considered dominant and have its type prevail.

**Comment by damianmoz** [comment]
I have problems wrapping my head around all the subtle aspects here. So, for my needs, I firstly translate a range into what would be set of array indices, and then write out an expression for the bounds and stride that define them and work from there. Hence, those bounds and stride are just mixed-mode expression, albeit with only integral modes with some being **param** and others **const**.

But the problem seems bigger than that so you need to address those extra issues.

I was just offering my take on it from my (more limited) perspective as a way of trying to simplify the problem. But I am not convinced I solve it, and it seems more and more like I do not, so maybe my words are better ignored.

It was just a contribution to the discussion.

**Comment by bradcray** [comment]
@damianmoz : It appears that you  may have seen this effort, but in case not (or anyone else is interested), 'Problem Child' now works on main due to `#` no longer requiring its operand to be of a compatible integer size as the range's `idxType`.

**Comment by damianmoz** [comment]
Thanks. Yes I have been monitoring this and #20091.
