### ISSUE TITLE
Unbounded range and for loop syntax issue

### ISSUE THREAD

**Issue by ghbrown** [chapel-lang/chapel#19973]
I came across some confusing behavior when mixing unbounded ranges and for loops. (I learned a lot from #17084 and skimmed #6160, but they are more about mechanics than syntax.)

```chapel
for i in 0.. {
  writeln(i : string);
}
```
gives a syntax error. In my opinion this is confusing because a finite range like `0..4` is syntactically acceptable here, and almost everywhere else bounded and unbounded ranged are syntactically interchangeable (`var a = 0..4;` and `var a = 0..;` are both fine). Indeed this cryptic error inspired some uneducated and misguided attempts to investigate and fix the wrong thing lead me on a bit of a wild goose chase (I am still learning, so perhaps take this with a grain of salt). Working solutions to achieve the desired behavior of an infinite loop include
```chapel
for i in (0..) {
  writeln(i : string);
}
```
and
```chapel
for i in zip(0..) {
  writeln(i : string);
}
```
Is there a good reason why one needs extra syntax for this special case? Since I think consistently having bounded and unbounded ranges be interchangeable is much more predictable, can this be fixed?

### Steps to Reproduce

**Source Code:**

Code snippets above, compiled with `chpl` and executed with `./`

### Configuration Information

- Output of `chpl --version`:
```
chpl version 1.27.0 pre-release (b03caba957)
  built with LLVM version 13.0.1
```
- Output of `$CHPL_HOME/util/printchplenv --anonymize`: using packaged version
- Back-end compiler and version, e.g. `gcc --version` or `clang --version`:
```
clang version 13.0.1
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

**Comment by ghbrown** [comment]
@mppf Thanks for pointing to the original. I might take a crack at messing with Bison for fun and see if I can get anything done.

Feel free to close this, I can continue on the original if needed.

**Comment by bradcray** [comment]
I am going to take you up on your offer to close this as a duplicate—thanks!

@ghbrown: FWIW, I took a quick crack at this once years ago and ran into challenges restructuring the grammar to resolve this.  Specifically, since we support domain literal expressions like `{1..n, 1..n}` and these expression forms are not currently sufficiently teased apart from simple variable references or more traditional expressions in the parser, the parser can't decide between `for i in 0.. { body of loop here; }` and `for i in 0..{1..n, 1..n} { body of loop here }`.  That said, a domain cannot be the upper bound of a range, so I believe we could either:
* restructure the expression hierarchy to support additional different flavors of expressions and make sure that the bounds of a range are sufficiently simple
* lean on some sort of bison tie-breaking rule to resolve this ambiguity in favor of "treat curly brackets after `..` as the body of the loop, not a domain literal

I'm more expert in the former than the latter, but got wrapped around the axle before completing the effort.  That said, the latter _may_ be the more straightforward way to do it if the grammar is structured in such a way that it would support it.
