### ISSUE TITLE
Improve `locale.umask()` interface in FileSystem module

### ISSUE THREAD

**Issue by jeremiah-corrado** [chapel-lang/chapel#20094]
The current `locale.umask()` method updates a locale's file creation mask and returns the old mask.

The file-creation-mask's value is stored in the runtime as a `mode_t` (defined in [`<sys/stat.h>`](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/sys_stat.h.html)). However, the interface exposes these values as Chapel integers:
```chapel
proc locale.umask(mask: int): int { }
```

Given that this method is directly modifying a value with a c-type, are Chapel integers the best choice for the interface?

Would it be better to create an enum over the possible values of `mode_t`, or expose the c-type more directly to the user?

**Comment by daviditen** [comment]
Should locale.umask take/return a mode_t instead of Chapel integers?
All the different modes are currently spelled out in the module as const ints. Should they be an enum instead? Or a mode_t?

Other languages:
Rust: umask is its own crate - has a Mode struct that can be created from an integer: 'Mode::from(0o644)' or a string: '"rw-rw-r--".parse().unwrap()'. Has constants representing all the different mode bits.
Python: Has 'os.umask(mask)' where 'mask' is an integer. Very similar to the current Chapel function. Returns the previous value as an int.
Julia: Doesn't currently have a procedure for setting umask: https://github.com/JuliaLang/julia/issues/24253

**Comment by bradcray** [comment]
My main thought here is that I don't think a routine in FileSystem should be dealing in C types like `mode_t` if we can help it.

**Comment by mppf** [comment]
It might be a bit out of left field, but this is a method on `locale` but that type also represents sublocales. If you call `locale.umask()` on a sublocale, will it impact the umask on other sublocales? If it does, is that a problem?

**Comment by lydia-duncan** [comment]
I believe when we originally made it `locale.umask`, we knew that sublocales were a possibility but hoped that their development would take `umask` into account (though I don't know that we left that breadcrumb anywhere)

**Comment by lydia-duncan** [comment]
We decided not to use different types for the argument.  We also decided to mark the function unstable for locale models other than flat.  #22865 implements the latter, closing
