### ISSUE TITLE
Should the `#` and `by` operators on ranges/domains/arrays take boolean values?

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#20114]
In #20098, I re-implemented `#` on ranges to take any integral value by
changing the second argument types from `int(w)`/`uint(w)` to `integral`.
This had the effect of disabling the ability to apply a boolean using the
count operator, like `1..10#true`, which our tests didn't catch because we
didn't have any.  However, it turns out that Arkouda does rely on this
behavior, so stopped compiling.

In #20111 , I am re-enabling `#` on booleans for the time being, but this
issue asks whether we should continue to support it or deprecate it
(requiring the user to cast booleans to integers before passing them to `#`).

Arguments against:
* `#` logically takes a numeric count value in order to count off that many
   values
* 0 and 1 aren't particularly interesting counts

Arguments in favor:
* Since booleans coerce to integers, and in many cases, we permit this
  style of coercion to get things done, maybe we should here as well?

A similar question can be asked about `by`:

Arguments against:
* strides of 1 aren't interesting and strides of 0 aren't permitted

Arguments in favor:
* same as for `#` (?)

**Comment by lydia-duncan** [comment]
I'm against it, personally, but I don't feel super strongly

**Comment by mppf** [comment]
> Since booleans coerce to integers, and in many cases, we permit this
style of coercion to get things done, maybe we should here as well?

This argument resonates for me. If we don't want booleans to coerce to integer in this case, why do we have booleans coerce to integers at all? I know in the past we've talked about wanting `+ reduce MyBoolArray` to work, but IMO that could be something special about `+` or even something special about `+ reduce` to allow that without allowing bool->int coercions.

So, put another way, I think we should either:
 * be happy with bool->int coercions including in this case; or
 * generally disallow bool->int coercions, including in this case (with some sort of exception so that `+ reduce MyBoolArray` still produces an int)

**Comment by bradcray** [comment]
Somewhat related, I've filed #20125 to capture the observation that `bool` actuals can be passed to `int(?w)` formals, but not to `integral` formals currently, which seems asymmetric.

**Comment by bradcray** [comment]
My current thinking here is:
* count should continue to support bools because users have made use of it and it's not pointless.  It's also been argued that these sort of "select 0 or 1" idioms can be helpful to write at times, if perhaps also a bit "cute".
* `by` should not support bools because a stride of 0 isn't meaningful and a stride of 1 is boring.

Though I was originally concerned that these should be symmetrical, I don't feel that way any more.

This also happens to be what's implemented today, so I'm going to close this issue.  If someone else wants to advocate for it, they can re-open it or start a new issue.
