### ISSUE TITLE
SysBasic module: should we deprecate ENOERR?

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#20129]
It seems like we made it up, it's not a POSIX error code.  It could be considered to make code more self-documenting (saying "check if this code means 'no errors' " versus "check if this code is zero and I know zero means 'no errors' "), but it's intended for error codes which are a low level C concept and this is something new rather than following precedent and potentially could confuse people into thinking it doesn't match what C expects when no error occurred.

If we do keep it visible for users, it should have a more Chapel oriented name.  Where would it live in that case?

It seemed like there was some division over whether it was useful, but if we did keep it no suggestions for where it should live

**Comment by bradcray** [comment]
I think we should drop it on the argument that:
* POSIX doesn't have it, so it doesn't belong in OS.POSIX
* its name isn't Chapeltastic, but changing its name would make it a poor sibling to the POSIX E* codes
* those who are working at this level coming from C will either be used to treating 0 as no error, or can create their own aliases for 0
* giving it a symbolic name seems to suggest that testings like `if !error` may or may not be legal anymore because the value of ENOERR may or may not be 0

**Comment by riftEmber** [comment]
SysBasic module deprecated in https://github.com/chapel-lang/chapel/pull/20998 along with ENOERR, which has been replaced with 0 everywhere
