### ISSUE TITLE
SysBasic module: What should we do with `fd_t`?

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#20128]
`fd_t` is a `c_int` representation of a file descriptor.  The name itself has origins in C, though seems like it is not necessarily present in every implementation.

There's also an `openfd` in the IO module (see #20143) that takes an `fd_t` as an argument.

It seemed like the general lean was towards hiding this in the implementation, though I was a little concerned that implementing a version of `openfd` that continues to use it as an argument would be more of a pain for users to write on their own (though that depends on if we want to keep `openfd` with a `c_int` argument)

**Comment by mppf** [comment]
> It seemed like the general lean was towards hiding this in the implementation, though I was a little concerned that implementing a version of `openfd` that continues to use it as an argument would be more of a pain for users to write on their own (though that depends on if we want to keep `openfd` with a `c_int` argument)

I'm not really following but I think we should keep `openfd` (maybe renamed) with a `c_int` argument.

I don't think we should expose `fd_t` in our Chapel API.

**Comment by bradcray** [comment]
> I'm not really following but I think we should keep openfd (maybe renamed) with a c_int argument.

In the IO module, or elsewhere?  At a sniff, it feels a bit low-level compared to other things in IO (in terms of the name, the behavior, the `c_int`).

If we were to keep it there, I'd propose it should take an `int` rather than a `c_int` and then rely on a safeCast() or the like before passing it off to C.

In any case, I agree with the proposal to drop `fd_t` as a type we support and rely on `c_int` when needed instead.

**Comment by bradcray** [comment]
When would a user ever use `openfd()` in practice?  Grepping tests very briefly, it looks like it's primarily used to get alternate views of stdin/stdout/stderr in reasonably obfuscated/unclear ways.  Should we consider just dropping support for `openfd()` and providing a friendlier way to get alternate stdout/stdin/stderr instead?  (I know I feel icky that we have submitted shootout entries that rely on `openfd(0)`/`openfd(1)`, for example.

**Comment by mppf** [comment]
Well, if you were doing interoperability with a C library, and the C library worked with a `FILE*`, you might like to have access to a Chapel view of that `FILE*` that allows line-buffered mixing between Chapel writelns and C printfs. Of course you could say "Don't rely on that" but I think this sort of use case was the motivation for it.

Anyway it's true that 99% of the issue here is specifically about stdin/stdout/stderr. One thing we could consider is having a config param that toggles these between being line-buffered and compatible with C stdin/stdout/stderr; and being faster with just the Chapel channel's buffering.

(The context here is that the line buffering is slow, especially when we buffer a line, give it to a `FILE*`, which buffers the line, and then writes it; vs just doing the buffering once and not doing line buffering).

**Comment by mppf** [comment]
Oh, whoops, I was answering the question about `openfp`... Apparently I cannot keep these straight in my mind.

For `openfd` you might use it if you use some POSIX feature to get a file descriptor (either because you are doing something not supported by the Chapel library or because you are implementing the Chapel library). Not all of these file descriptors correspond to anything on the filesystem. Some examples: `pipe` and the socket functions `listen` `accept` `connect`.

**Comment by riftEmber** [comment]
SysBasic module deprecated in https://github.com/chapel-lang/chapel/pull/20998 along with `fd_t`, whose usage is replaced by a `c_int` everywhere.
