### ISSUE TITLE
SysBasic module: Should we keep the four remaining error codes labeled POSIX?

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#20132]
The error codes in question are ENODATA, ENOSR, ENOSTR, and ETIME.

We believe these are POSIX extensions or optional error codes, rather than error codes that must be provided.  We think these are unlikely to be used and so don't merit getting moved to the OS.POSIX module, but can add them if someone requests them.

**Comment by bradcray** [comment]
I'm inclined to follow Greg's lead here (by not including them in OS.POSIX) and drop them.  It's easier to add them later than to have to worry about how to support them or whether we need to on systems that may not support them.

If the net effect of all these changes is that nothing will remain in SysBasic.chpl in 1.28.0, then I'd propose that rather than deprecating each symbol and type remaining individually, we deprecate the module as a whole, similar to what @jeremiah-corrado has been doing with the `Sys` module, to get a similar effect with far less work on our part.

**Comment by jeremiah-corrado** [comment]
I agree deprecating the module as a whole has saved a lot of work! 

For the symbols that *do* end up moving to another module, I am giving them their own deprecation message so that users know where to find the new one (along with a `pragma "last resort"` to avoid ambiguity errors, per your suggestion @lydia-duncan)

**Comment by mppf** [comment]
The error codes in question are ENODATA, ENOSR, ENOSTR, ETIME— right? I'm happy with leaving them out of OS.POSIX for now.

**Comment by lydia-duncan** [comment]
> The error codes in question are ENODATA, ENOSR, ENOSTR, ETIME— right?

Yup!  I'll update the OP, sorry

**Comment by lydia-duncan** [comment]
> If the net effect of all these changes is that nothing will remain in SysBasic.chpl in 1.28.0, then I'd propose that rather than deprecating each symbol and type remaining individually, we deprecate the module as a whole

Yup yup.  I opened individual issues so that the individual symbols can have whether they continue to exist or get removed entirely be discussed

**Comment by lydia-duncan** [comment]
Does Greg's response Brad quoted [in this issue](https://github.com/Cray/chapel-private/issues/3483#issuecomment-1171951796) impact anyone's thinking about whether these error codes should be moved to OS.POSIX?

**Comment by bradcray** [comment]
It doesn't particularly for me since Greg obviously did iterate through the E errors.  I.e., it seems most likely that he intentionally omitted these rather than that he happened not to get to the four that are extensions/optional.

**Comment by riftEmber** [comment]
SysBasic module deprecated in https://github.com/chapel-lang/chapel/pull/20998 along with these symbols
