### ISSUE TITLE
SysBasic module: Should we deprecate EEOF, ESHORT, and EFORMAT?

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#20130]
They are not included in POSIX, they are symbols we added for our implementation.  They are currently defined as macros to avoid communication when accessing their value (but this could be accomplished by making them "task local" or something).  With the advent of error handling, these feel more and more like implementation details (especially since a regular C function will not know about them).

We think we should hide them from users and move them to the IO module, where they are most used.

**Comment by bradcray** [comment]
FWIW, I think that this is a good 2.0 warm-up exercise.

W.r.t. SysBasic in general, I wonder whether the right next step after this warm-up would be to just look into deprecating the module wholesale rather than worrying about its contents symbol-by-symbol, similar to what @jeremiah-corrado did with Sys.  It will amount to a similar amount of effort, since any outstanding symbols used within it will have to be dealt with in one way or another.  But slapping a single deprecation warning on the module and then retiring the module as a whole seems simpler and more satisfying than retiring a symbol at a time, particularly now that we seem to largely be down to the most esoteric ones (?).

**Comment by lydia-duncan** [comment]
> W.r.t. SysBasic in general, I wonder whether the right next step after this warm-up would be to just look into deprecating the module wholesale rather than worrying about its contents symbol-by-symbol, similar to what @jeremiah-corrado did with Sys. It will amount to a similar amount of effort, since any outstanding symbols used within it will have to be dealt with in one way or another. But slapping a single deprecation warning on the module and then retiring the module as a whole seems simpler and more satisfying than retiring a symbol at a time, particularly now that we seem to largely be down to the most esoteric ones (?).

Yeah, I think that would be reasonable (and is part of the reason I suggested this one instead of #20132, since this has a more interesting action item as part of it while the other issue could be handled just as easily by deprecating the module as a whole)

**Comment by riftEmber** [comment]
If the entire module is going to be deprecated, does that mean the only part of this that isn't redundant with that eventually happening is moving these macros to the IO module?

**Comment by lydia-duncan** [comment]
Yeah, I think that's true, though I don't know when the deprecation of the rest of the module will happen.  It should be easy, but I don't personally anticipate having time for it in the next release cycle (so you could very easily deprecate and remove these symbols before the module as a whole gets deprecated)

**Comment by bradcray** [comment]
I agree.  If you felt up to the task of trying to just deprecate the module, I think that'd be great / admirable.  But if you wanted to stick a toe in the water first, starting with these symbols and then moving on to the module would be fair game.  IIRC, I think these were some of the trickier remaining symbols (?).

(I do think it would be great if the module as a whole were deprecated in the next release... the Sys* modules have made great progress, and this one feels super-close to me).

**Comment by riftEmber** [comment]
I think I'll stick with just deprecating and moving these symbols for this issue, and keep the deprecation of the module as a whole in the back of my mind (and on that note I'll link https://github.com/Cray/chapel-private/issues/3467).

**Comment by mppf** [comment]
A reasonable first step here is to hide `ESHORT` etc from users. However, there is another concern: the related classes can leak the value of these error codes. E.g. `UnexpectedEofError` is a subclass of `IoError` and that is a subclass of `SystemError`, and `SystemError` saves a system error code (as an integer but using the type `errorCode`). One potential direction would be to store another, more general, POSIX-y error code, like `EIO`, for these. Another potential direction would be to make them no longer be subclasses of `SystemError`.

**Comment by riftEmber** [comment]
I don't know a lot about how these error codes are used, but unless they are used extensively replacing them with an appropriate POSIX error code and allowing them to be indirectly visible to users (as they will be after move to IO) seems like a good next step to me.

**Comment by bradcray** [comment]
I've written up a description of these "use before encountering its definition" errors recently, and am trying to think where that was to avoid writing it up from scratch again.  It's a common issue to run into when changing dependencies in internal modules, particularly those involving locales which are among the first that need to be run since the locales need to be bootstrapped before most other things work (for example, I/O routines use `on` clauses to keep I/O coherent, which require locales).

Aha, here's one of the places I described this circularity, but I feel like it was the first of two recent times and that the second time I did even better:  https://github.com/Cray/chapel-private/issues/2658#issuecomment-971894306

What I didn't say in that comment was that one way to unravel these circularities is to hoist some of the symbols that are causing them into a new module that is used by the other two to break the circularity.  Where it sounds like you effectively did the equivalent by duplicating a necessary extern declaration to break the circularity.

**Comment by mppf** [comment]
Re https://github.com/chapel-lang/chapel/issues/20130#issuecomment-1265876642

> One potential direction would be to store another, more general, POSIX-y error code, like EIO, for these. Another potential direction would be to make them no longer be subclasses of SystemError.

AFAIK we still have to do one of these.

**Comment by riftEmber** [comment]
@mppf Will be doing one of those as part of https://github.com/Cray/chapel-private/issues/4116
