### ISSUE TITLE
IO module: proposed changes to iohints

### ISSUE THREAD

**Issue by jhh67** [chapel-lang/chapel#20141]
The `iohints` type is passed as an argument to the `open*`, `file.reader`, `file.lines`, and `file.writer` methods, and defines a set of hints about the I/O that the file or channel will perform.

The following `iohints` constants are provided:

- `IOHINT_NONE` defines an empty set, which provides no hints.
- `IOHINT_RANDOM` suggests to expect random access.
- `IOHINT_SEQUENTIAL` suggests to expect sequential access
- `IOHINT_CACHED` suggests that the file data is or should be cached in memory, possibly all at once.
- `IOHINT_PARALLEL` suggests to expect many channels working with this file in parallel.

The following binary operators are defined on `iohints`:

- `|` for set union
- `&` for set intersection
- `==` for set equality
- `!=` for set inequality

**Proposal**

As a result of the discussion during the recent module review the current proposal is to replace the current `iohints` with a `ioHints` record type that has parenless methods for the individual hints, e.g.
 ```
record ioHints {
  pragma "no doc"
  var fieldForActualValue: int;

  proc type sequential {
    return new iohints(valueCorrespondingToSequential);
  }
}
```
The `ioHints` type provides the `|`, `&`, `==`, and `!=` operators for manipulating and comparing `ioHints`.

The following hints will be supported:

`ioHints.none`: the default
`ioHints.sequential`: suggests that the file will be accessed sequentially
`ioHints.random`: suggests that the file will be accessed randomly
`ioHints.prefetch`:  suggests that the runtime/OS should immediately begin prefetching the file contents
`ioHints.mmap`:  suggests that `mmap` should be used to access the file contents

The first four of these hints map directly to hints provided to `posix_fadvise` and `posix_madvise`, with `ioHints.none` corresponding to `POSIX_*_NORMAL` and `ioHints.prefetch` corresponding to `POSIX_*_WILLNEED`. Note that `ioHints.mmap` does not correspond to a Posix hint, but instead suggests that `mmap` should be used to access the file instead of `read/write`. Also note that we will not support `POSIX_*_DONTNEED` because we currently only support `ioHints` when a file is opened or channel created and there is little benefit to specifying that the file contents won't be needed at that time.

**Comment by jeremiah-corrado** [comment]
As I've started implementing this, I realized that `ioHints.none` is not an option as `none` is a protected keyword.

Some alternatives: 
 - `ioHints.noHint`
 - `ioHints.normal`
 - `ioHints.empty`

I'm personally leaning towards `empty`

 @jhh67 do you have an opinion or alternate suggestions for the name?

**Comment by jhh67** [comment]
`ioHints.empty` seems good to me.

**Comment by lydia-duncan** [comment]
I like `noHint` best, personally.  It seems more self-documenting

**Comment by jeremiah-corrado** [comment]
Ok, I'm not super opinionated on this so I'd be good with changing it to `noHint`. @jhh67, any objections?

**Comment by mppf** [comment]
FWIW I like `empty` better than `noHint` (because it is a set, the empty set is well defined, and a simpler concept). Might be nice to do a poll here.

**Comment by jeremiah-corrado** [comment]
React here for `ioHints.noHint`

**Comment by jeremiah-corrado** [comment]
React/comment here for something else

**Comment by bradcray** [comment]
I'm mostly feeling sad that we can't use `none` for this which still feels the clearest to me of all options.  I get the "it's a set and it's empty" argument, but it still reads odd to me to say "Q: What hints are we providing?  A: 'empty'!"

One other candidate solution might be `default`

**Comment by bradcray** [comment]
A related follow-up question:  Would a user ever explicitly use / type this symbol?  If I'm and-ing a bunch of things together it seems like I wouldn't bother (I'd guess it's like a 0 value, so an identity?).  If I'm not passing in a hint explicitly, I'm guessing I'd just skip the argument rather than passing it in.

Basically, the reason I'm asking is that if a user wouldn't likely type it in most cases and it was just the default value for an argument, it might suggest optimizing the name to be as clear as possible in the procedure prototypes, whereas I was focused in the case of passing it in as an actual argument in the prior response.

**Comment by jeremiah-corrado** [comment]
>  If I'm not passing in a hint explicitly, I'm guessing I'd just skip the argument rather than passing it in.

I think that's right. The "empty" case will mainly be used as the default value in a bunch of IO function headers.

Are you saying `open(file: string, hints = ioHints.empty)` seems ok as a self-documenting header then? Or are you advocating for a different name like `ioHints.default` to sit in the function headers?

**Comment by bradcray** [comment]
Thanks for confirming, Jeremiah!  I wasn't advocating for a specific approach in asking that, but wondered whether it might change peoples' opinions (including mine) if that was the only place the identifier was likely to appear in well-formed / typical code.  For example, I might balk at the camel-case nature of `noHint` over `empty` if it was going to appear throughout the code, but if it only appeared in this signature, it might not seem as bad.

Personally, I think reading `hints = ioHints.noHint` specifies what's going on here to a casual reader more clearly than `hints = ioHints.empty`.  I think even `hints = ioHints.default` is slightly better if someone was balking at the need for camelcase, though it does seem slightly more vague.  I was also wondering whether I'd want to throw the typical "methods/fields/enum constants should start with lowercase" guidance under the bus and go with `hints = ioHints.None`.  I don't feel like it's a great option, but wanted to throw it out there as long as I'm brainstorming.

In any case, while I understand that this is a set and that the default value of the set is an empty set, `hints = ioHints.empty` is currently my least favorite option of those being considered here because the set-like nature isn't particularly clear.  `hintSet = ioHints.empty` would clarify that and so might be slightly better, but I think `hints` is strictly a better argument name.  I guess another approach would be to rename the type to `hints = hintSet.empty` to make the set-like nature clearer (?).

I cast my vote for `noHint` for these reasons, though I'd also be open to other options, so I also voted for the "something else" option.

**Comment by jeremiah-corrado** [comment]
>  I guess another approach would be to rename the type to hints = hintSet.empty to make the set-like nature clearer (?).

This actually sounds pretty appealing to me. Although maybe `ioHintSet`? 

It makes the behavior of the `|` and `&` operators more intuitive for users who might not realize that this is just a wrapper around a `c_int`. I.e. ioHints sounds kind of like a list of hints, so they might be thinking "I want hint A `&` hint B". Whereas if they are considering a set, the correct : "I want hint A `|` (set union (or bitwise-OR)) with hint B".

Also, a more significant change to the name makes the transition to the new type more visually obvious. For example, the current deprecation messages essentially say: 
```'iohints' is deprecated; please use 'ioHints' instead```
which looks like we just updated the name of the type to be camel-case.

**Comment by bradcray** [comment]
I buy all of what you're saying here Jeremiah, and would be comfortable proceeding with it if others who are invested here agree.

**Comment by jeremiah-corrado** [comment]
Ok so it sounds like there is no opposition to going with `ioHintSet` (and `ioHintSet.empty` as the default). I'm going to start making that change to [this PR](https://github.com/chapel-lang/chapel/pull/20229). Please notify me on this thread if you have any reservations about the above mentioned naming scheme.

**Comment by lydia-duncan** [comment]
I'd do a last minute ping to the whole group, not everyone follows every message on discussions.  But I think it'll probably be okay

**Comment by lydia-duncan** [comment]
@jeremiah-corrado - I think this is resolved with your #20229, right?

**Comment by jeremiah-corrado** [comment]
Yeah, it is. Thanks for catching that!

Just noting that these issues were spawned off of the discussion about `ioHintSet`s implementation:
- #20432
- #20430


but the base functionality discussed here has been implemented.

**Comment by lydia-duncan** [comment]
So we can close it?

**Comment by jeremiah-corrado** [comment]
Resolved by: https://github.com/chapel-lang/chapel/pull/20229
