### ISSUE TITLE
IO module: should we rename the `reader` and `writer` methods on the `file` type?

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#20154]
```chapel
 proc file.reader(param kind = iokind.dynamic, param locking = true,
                  start: int(64) = 0, end: int(64) = max(int(64)),
                  hints: iohints = IOHINT_NONE): channel(false, kind, locking) throws
 proc file.writer(param kind = iokind.dynamic, param locking = true,
                  start: int(64) = 0, end: int(64) = max(int(64)),
                  hints: c_int = 0): channel(true, kind, locking) throws
```

Partially motivated by and related to #18112 

These methods on the `file` type will (currently) open a channel for reading/writing respectively.  We've talked about splitting the `channel` type into a type for reading and a type for writing and the original proposed name accidentally caused some hiccups due to matching the names of these methods.  If we end up using different names for the types entirely, the hiccups go away, but does that mean these names are okay?

These names are pretty short and sweet.  But they don't necessarily indicate that something is created on their own.  There's been suggestions to rename them so that they indicate better than a channel (or whatever) ends up being created.  Something like:
- `getReader`/`getWriter` (but that doesn't indicate that something is created)
- `createReader`/`createWriter`
- `newReader`/`newWriter`

Note that #20133 will have some impact on these methods' arguments.

**Comment by mppf** [comment]
I'd like to leave the names as-is and my justification for that is that I think the important concept is that these methods return a sort of view into a file; the fact that they create a different record/allocate memory/etc is less important in my opinion. I also don't much care for the `getBla` style, because (for historical reasons) it applies to field-like things as an accessor, but if it's field-like, what do we gain from having `get` in front of it vs. just naming it with the thing being returned?

**Comment by mstrout** [comment]
Based on the discussion in https://github.com/chapel-lang/chapel/issues/18112#issuecomment-1164677774, I think we should leave `file.reader` and `file.writer` as is.

**Comment by lydia-duncan** [comment]
We decided not to do this, closing
