### ISSUE TITLE
GPU: Internal Error for Slicing Multidimensional Arrays

### ISSUE THREAD

**Issue by ShreyasKhandekar** [chapel-lang/chapel#20181]
### Summary of Problem
With `CHPL_LOCALE_MODEL=gpu` we get error with reading from or writing to slices of multidimensional arrays.
At compile time we get the following error:
```bash
internal error: Malformed PRIM_GET_MEMBER_* [optimizations/gpuTransforms.cpp:524]
```

### Steps to Reproduce

**Source Code:**

```chapel
var a = [1..10, 1..10];
for i in a.dim(0) {
    /// Get one row
    var x = a[i, 1..10];
}
```

This is similar to https://github.com/chapel-lang/chapel/issues/19981

**Comment by stonea** [comment]
If I try and compile as of the latest main (c346493c12042fbad62d37669358ac65a4fb077b) I no longer get the `Malformed PRIM_GET_MEMBER_` message. Instead I get this: 

```
foo.chpl:1: In module 'foo':
foo.chpl:4: error: unresolved access of '[domain(1,int(64),false)] range(int(64),bounded,false)' by '[int(64), range(int(64),bounded,false)]'
foo.chpl:4: note: unresolved call had id 182800
```

Which I think is expected. It's not a great error but I'll get the same thing with `CHPL_LOCALE_MODEL=none`. This is because in the example code array `a` is not a multidimensional array but rather a 2d array containing two elements (that are ranges).

I think you meant to do something like this:

`var a : [1..10, 1..10] int;`

In which case now it compiles and runs fine regardless of the locale model.
