### ISSUE TITLE
`ChapelLocale` module: Emit an unstable warning when using the `gpus` array without the GPU Locale Model

### ISSUE THREAD

**Issue by jeremiah-corrado** [chapel-lang/chapel#20222]
The `here.gpus` array is always accessible, but is only populated/useful when compiling with `CHPL_LOCAL_MODEL=gpu`. 

Should the compiler emit a warning when a program uses the `gpus` array, but is not compiled with a GPU Locale Model? For reference, GPU functionality in general is currently unstable, so it probably makes sense to extend a warning to the `gpus` array.

**Comment by bradcray** [comment]
I don't know that I'd make it an "unstable warning" (if, by that, you mean one that shows up when `--warn-unstable` is on so much as just a warning that's always on.  Or, if that's what is meant, I still don't know that I'd make the warning use the term "unstable" so much as to say something informational like "note that your choice of locale model doesn't support GPUs".

Of course, the downside to that is that it may be noisy for someone who's writing correct generic code and just expecting loops over the GPU sublocales to turn into no-ops or the like...  At least until we have a way to suppress specific warnings rather than throwing `--no-warnings`.

**Comment by jeremiah-corrado** [comment]
> Or, if that's what is meant, I still don't know that I'd make the warning use the term "unstable" so much as to say something informational like "note that your choice of locale model doesn't support GPUs".

I agree. I don't think the word "unstable" needs to be used, but I think it still sort of fits into this category, and it would be nice for users if they can toggle it on/off with the `--warn-unstable` tag for the reason you mentioned (writing correct generic code).

**Comment by bradcray** [comment]
To me, though, 'unstable' implies "will get better over time".  But in this case, do we really expect any change or improvement in behavior over time in this case?  I'd guess now, which is why it didn't seem right to me.

**Comment by jeremiah-corrado** [comment]
Ok that makes sense. For some reason I had it in my head that the use of the `gpus` array is itself an unstable feature.

I believe @stonea originally brought up the notion of throwing a deprecation warning in this case. Andy, do you know if there are might be any expected changes to the `here.gpus` array. Like in some future version of Chapel `on here.gpus[0] {}` might run the contents of the block on the CPU if the program is compiled without the GPU locale model (rather than doing nothing)? I seem to remember some discussion like this either from the module review or our offline conversation.

**Comment by stonea** [comment]
> I believe @stonea originally brought up the notion of throwing an unstable warning in this case. Andy, do you know if there might be any expected changes to the here.gpus array. Like in some future version of Chapel on here.gpus[0] {} might run the contents of the block on the CPU if the program is compiled without the GPU locale model (rather than doing nothing)? I seem to remember some discussion like this either from the module review or our offline conversation.

My expectation is in the long term we'll get rid of the gpu locale model as a separate locale model altogether and it'll just become part of the main locale model.  When we do that I'd expect `here.gpus` to return an empty array on a system without GPUs.

Since this function is part of the GPU support efforts though I'd rather we not lock it down in Chapel 2.0.

I think the best thing would be if the function were only available when `CHPL_LOCALE_MODEL=gpu` but as far as I know there's no easy way to do that. In the absence of that (assuming it's technically feasible) I'd advocate for issuing a warning message (ideally at compile time) if the function gets used and `CHPL_LOCALE_MODEL!=gpu`.

**Comment by bradcray** [comment]
> I think the best thing would be if the function were only available when CHPL_LOCALE_MODEL=gpu

I'd expect a pattern like:

```chapel
use ChplConfig;
proc foo() where CHPL_LOCALE_MODEL=="gpu" { ... }
```

to be a way to have a function only be available when the GPU locale model is enabled.  Alternatively, within the function, you could do something like:

```chapel
if CHPL_LOCALE_MODEL == "gpu" then
  compilerError("'foo' is not available when using the GPU locale model at present");  // or compilerWarning()
```

**Comment by stonea** [comment]
> I'd expect a pattern like:
> 
> ```chapel
> use ChplConfig;
> proc foo() where CHPL_LOCALE_MODEL=="gpu" { ... }
> ```
> 
> to be a way to have a function only be available when the GPU locale model is enabled. 

Hmm, if put `use ChplConfig;` in `ChapelLocale.chpl` I get 

`$CHPL_HOME/modules/internal/DefaultRectangular.chpl:1498: internal error: assertion error [codegen/cg-expr.cpp:2787]`

so I think there's some kind of module ordering issue there?  Although the fact that this is causing an assertion at codegen time (https://github.com/chapel-lang/chapel/blob/main/compiler/codegen/cg-expr.cpp#L2787) is making me think maybe there's a bug in the compiler?  Maybe I should investigate this more next sprint.

Anyway, if we could get that to work, I'd be really pleased.  I have to say, there's something self documenting about `where` clauses that I just love.

**Comment by stonea** [comment]
> > I think the best thing would be if the function were only available when CHPL_LOCALE_MODEL=gpu
> 
> I'd expect a pattern like:
> 
> ```chapel
> use ChplConfig;
> proc foo() where CHPL_LOCALE_MODEL=="gpu" { ... }
> ```
> 
> to be a way to have a function only be available when the GPU locale model is enabled.

Yes, that works. Thank you Brad!

I think we should also "no doc" that method until we "officially" consider it part of the base language outside of the safety of `CHPL_LOCALE_MODEL=gpu`.

I'm happy to post a PR to do this unless anyone objects?

**Comment by bradcray** [comment]
Oh good, I'm glad to hear it was a false alarm.  Working in ChapelLocale can definitely be fraught due to how early it is in the bootstrapping process, so it wouldn't have surprised me if there were issues, but I'm relieved to hear that it's workable.  I'd be fine with proceeding with a PR, though also don't feel sufficiently involved in the GPU effort to have a very well-informed opinion.

**Comment by jeremiah-corrado** [comment]
This was resolved by: https://github.com/chapel-lang/chapel/pull/21098
