### ISSUE TITLE
I/O module: replace stringify function with string.write

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#20256]
This issue is about this existing IO module function:

``` chapel
proc stringify(const args ...?k): string
```

* It should throw since `writeThis` / `encodeThis` etc can throw
* `stringify` doesn’t seem a very good name
* Related ideas are `"%i".format(1)` in Chapel and `repr` in Python

We can consider using either or both of the following alternatives to replace `stringify`:

### Option 1: `string.write` type method
``` chapel
proc type string.write(const args ...?k): string throws

// used like this:
var x = string.write(1, 2, 3);
// now x stores "123"
```

### Option 2: `string.write` method on string values

``` chapel
proc string.write(const args ...?k): void throws
// used like this
var x = "hello";
x.write(1, 2, 3);
// Open Question:  does this replace the string or append to it?
// In other words, is x now "hello123" or just "123"?
```

**Comment by mppf** [comment]
My own preference is to only support the string.write type method. The reason for that is that I don't think we have a strong precedent for methods that replace the receiver. (We have it in `bigint` but have been leaning away from keeping it -- see https://github.com/chapel-lang/chapel/issues/17699#issuecomment-1170537726 ). Of course, if we decided to only have the type method, that would be sufficient to remove `stringify` and we could add the Option 2 proposal as a non-breaking change. So, starting with Option 1 would be my preference.

**Comment by bradcray** [comment]
I'm fine with starting with just one of the options, with the possibility of adding a second option later, and agree that either option would be preferable to retaining stringify().  The thing that makes option 2 attractive/"obvious" to me is that it feels a bit more like sprintf() in C (which is where my head goes with this capability) if we think of the `char*` in C as being like a string value in Chapel.  That said, I agree that if we only had one method, starting with option 1 probably makes the most sense.

**Comment by jeremiah-corrado** [comment]
We recently voted as a team on some potential names for the type method to replace `stringify`. These were the results:

- `string.writeToString`: 3
- `string.write`: 4
- `string.convertToString`: 1
- `string.stringify`: 1
- `string.create`: 5
- `string.createFrom`: 2
- `string.swrite`: 2

<details>

`string.print`
`string.compose`
`string.fromWriting`
`string.combine`
<summary> names that got zero votes...
</details>

There is no clear winner; however it looks like we could resolve this by first voting on whether we should use a name that includes `write` or `create`. And then decide on a more specific name from there. 

During the meeting, the primary argument for choosing one of the names with `write` is that this function composes a new string using the same mechanism's as IO's `write` methods. I.e., `stringify` calls each arguments`writeThis` implementation — putting `write` in the method's name alludes to this fact.

The primary argument for `create`, was that this is essentially a factory function for creating strings (not technically because it's a type-method?). In previous discussions, we've standardized on using the word `create` in the names of factory functions, so using it here would hint at the method's behavior and maintain some consistency with naming conventions used in other modules.

**Comment by bradcray** [comment]
> it looks like we could resolve this by first voting on whether we should use a name that includes write or create.

We could go with `.createViaWrite()` as a solution that would potentially make everybody and nobody happy all at the same time.  :D

**Comment by jeremiah-corrado** [comment]
Another consideration for the name is that we'd like to preserve the option of eventually implementing a non-type method version. As such, we should try to pick a name that would make sense in both of the following contexts:

```chapel
// 1. used as a type method to make a new string
const s = string.writeToString("a number: ", 3, " and some other stuff: ", myRec);

// 2. used to write to (or overwrite) an existing string
var s2 = "hello!";
s2.writeToString(" some more information ... ", myRec);
```

With the second case in mind, I think that the `create` names make less sense because a new string is not being created. It also makes me wary of the name `write` (by itself) because it might imply that the string is being written somewhere else (maybe to `stdout`), rather than being written to.

**Comment by bradcray** [comment]
> As such, we should try to pick a name that would make sense in both of the following contexts:

I don't agree with that.  To me, `myChannel.write(...)` says "write these expressions to `myChannel`" while `myString.write(...)` says "write these expressions to `myString`", and that symmetry seems more worth preserving than having the type- and value-based versions of this string method share the same name.  Put another way, if you said that all three things cannot be named `write()` (which I think is a very reasonable position), I'd break the symmetry at `string.write()` (the type method) rather than between how we write to strings vs. to channels.

**Comment by vasslitvinov** [comment]
I expect `myString.write(a,b,c)` to APPEND the new stuff, the way channel.write does. If I want to overwrite myString's existing contents, I'd rather write `myString = stringify(a,b,c);` or whatever is our chosen replacement of stringfy.

I am with Brad that myString.write and string.write are different things and can (and should! :) ) be named differently.

**Comment by e-kayrakli** [comment]
It looks like we are a bit far from consensus, so I'll throw a different idea: How about we rename `stringify` as `writeToString` and keep it a standalone function in IO? I see the argument that `write` hints this being an IO operation rather than string operation. But if we are embracing that, why are we trying to make this into a type method on `string`?

For the non-type method version of this: the motivation for this can be performance*. But assuming what we have before, you can always do `myString += writeToString(x,y,z);` or `myString = writeToString(x,y,z);` to append and/or overwrite (more correctly, reassign) existing strings. 

\* Our strings can technically have a larger allocation than they have data. Is there a way for channels to use that existing memory as their buffer? Maybe for the overwrite case, the buffer doesn't need to be larger than the data, and as long as what we are writing is smaller than the allocation, we can avoid the cost of allocation. If this is the only motivation for that addition? (Not that I am against it, but not really eager either.)

**Comment by dlongnecke-cray** [comment]
I voted for `create()`. I worry that `write()` implies more than it should. Especially since a string is not a channel in this case.

It seems like `writeThis` is being called on the formals is just an implementation detail. I think it would be more appropriate to say that a string cast will (effectively - if we're worried about performance) be called on each component. Then `writeThis` just becomes a detail of the default-generated string cast for a given type.

I also worry about tying string casts in general to `writeThis`. It does not seem appropriate for string casts to fail in the same ways that an operation on a channel can fail. In general, I'd say that I would not expect any form of IO to be performed when performing a string cast. I'd prefer for the routine name to reflect that a bit more strongly (and perhaps the implementation as well - making sure to guard against errors from the IO machinery).

If we're unwilling to adjust the semantics of the function then I agree with Engin that we should rename the function but leave it standalone in `IO`. I'd be happy with `writeToString`.

**Comment by jeremiah-corrado** [comment]
One of the things we discussed in the previous module review was to deprecate `: string` in favor of whatever `stringify` ends up being called (see: https://github.com/chapel-lang/chapel/issues/19893#issuecomment-1309238525). I think reiterating some of the rationale for that decision might be beneficial to this discussion:

 - Generally speaking, we would like to have some mechanism in the standard library for users to get a `string` from a variable. Currently, casting to a string (`: string`) and the `stringify` procedure are the two ways to do that. Both are based on the same implementation that leverages IO code.
 - The IO subteam advocated for deprecating the current cast-to-string because it feels surprising that a cast would invoke IO code that can throw. It also feels quite surprising that overloading `writeThis` on a type can alter the result of that cast.

Deprecating `: string` leaves `stringify` as the only mechanism for converting any variable to a string. As some have pointed out above — and in a recent offline thread — the same concerns are still relevant when looking at `stringify`. I.e., why does it throw (it doesn't yet, but that will be updated), and why is it's implementation IO/`writeThis` dependant? 

These concerns with `stringify` motivated the IO team to present the above proposal where we'd:
1. rename it to make it clearer that IO operations are involved
2. make it a type method on the `string` type

**Comment by jeremiah-corrado** [comment]
With the concerns that have been brought up in this thread, and the lack of convergence on a name, I'm wondering if we should revisit the second aspect of the proposal.

Specifically, should `stringify` be replaced with a type method on `string`? A regular method on `string`? Or should it remain a top-level method somewhere in the standard library, and potentially just be renamed? To summarize, here are some advantages of each approach from the discussion above (and some recent offline discussion):

### type method:

* there isn't a strong precedent for methods that replace their receiver (with the exception of the `bigint` module). So a type method that creates a new string might be more appropriate than a method that overwrites an existing string 

* "string" is sort of part of the method's name. This might make it clearer that the result is a `string`

### method:

* if we went with a name like `string.write` or `string.writeToString`, there is a nice symmetry with `channel.write`. I.e. in the IO case, the channel is the thing being written to, and in this case, the `string` is the thing being written to.

* this is somewhat analogous to C's `sprintf` (where in this case, the receiver is updated rather than the first argument to the call)

### standalone proc:

* if top-level `write` is analogous to C's `printf`, then this would be analogous to `sprintf`. I.e., this does the same exact formatting as `write`, except it prints the result to a `string` instead of `stdout`

* it might be easier to decide on a name if we aren't worried about the possibility of eventually supporting this feature as a method *and* a type-method on `string`

**Comment by jeremiah-corrado** [comment]
In a recent design discussion, a sub-team (consisting of @bradcray, @benharsh, @arezaii, and myself) decided to deprecate `stringify` in favor of `string.format`. 

The deprecation message will indicate that the `%t` format should be used to achieve the same behavior as `stringify`:
```
warning: 'stringify(x)' is deprecated; please use 'try! "%t".format(x)' from IO.FormattedIO instead
```

Motivation/rationale
---
**the TL;DR:**

Overall, stringify is being used in two primary ways in the library and package modules:
  - casting individual variables to `string`: This functionality should eventually be supported by a universal cast-to-string that doesn't explicitly rely on IO infrastructure (see: https://github.com/chapel-lang/chapel/issues/19893 ); however this is future work. 
  - concatenating groups of variables and strings: A standalone or type-method replacement for stringify doesn't seem particularly well suited for this use case, as the result is often still concatenated with other strings (see the UnitTest example below). Alternatively, a method on `string` would be more suitable as a replacement, but would eventually be made obsolete by an IO-based string generation feature - see the "Future Direction" section below.
 
As such, we've decided to replace `stringify` (and the universal cast-to-string) with an existing feature that is already stable and will support both of the above use cases until new features are added post-2.0.

---
**more detailed rationale:**

- When attempting to decide on a procedure type for `stringify`'s replacement we ran into the following concerns with each possible approach:
   - **string method**: 
   ```chapel
   myString.write(...);
   ```
   In this case, it's not clear whether the contents of `myString` are overwritten or appended to. Overwriting the receiver feels much more analogous to something like `sprintf` from C; however it would be less analogous to the way IO operations work. I.e, `myWriter.write(...)` appends to the file represented by `myWriter`. Although we were most in favor of this approach, it didn't seem like there was an answer to the append/overwrite question that was both intuitive and consistent with the IO module. (We also worry that this feature would eventually be made obsolete by the new feature discussed below)
   - **standalone or type-method**: 
   ```chapel
   var myString = writeToString(...);
   var myString = string.ioWrite(...);   
   ```
   In these cases, the routine would generate and return a new string, which partially negates the efficiency benefits of `stringify`. I.e, the purpose of the function is to efficiently concatenate a group of arguments while using the IO infrastructure to convert them each to `string` representations. In many of the places where `stringify` is used in the library, it is either converting a single argument to `string`, and/or it is being used in a series of concatenations of strings. For example, see this procedure in the UnitTest module: https://github.com/chapel-lang/chapel/blob/0329b84ba996a290aac708f8619f6e61a9b7e2da/modules/packages/UnitTest.chpl#L381-L419
   Here, none of the efficiency benefits of stringify are being taken advantage of. As such, we weren't totally satisfied with a stringify replacement that returns a new string.

- Looking at uses of `stringify` in the standard/package modules, it became clear that `string.format` would be a straightforward replacement. Moveover, in some cases, the formatted IO approach was arguably cleaner than the uses of `stringify`. Example from UnitTest.chpl:  
	
	The following:
	```chapel
  var errMessage = "assert failed - '" + stringify(first) +"' and '"+stringify(second) + "' are not of same type";
	```
	can be replaced by:
	```chapel
  const errorMsg = "assert failed - '%t' and '%t' are not of same type".format(first, second);
	```

Potential Future Direction
---

There has been a long-standing desire to support an IO-like interface that allows writing/reading directly to/from `string`'s. This feature would encompass functionality very similar to `stringify` via the `fileWriter` type (or a similar type with the same interface). It might look something like this:
  ```chapel
  openWriter(myString).write("a record: ", r, " and: [", a, ",", b, ",", c, "]");
  ```
  With that functionality available, it would be potentially odd/confusing to also support one of the following replacements of `stringify` (particularly the first):
  ```chapel
  myString.write("a record: ", r, " and: [", a, ",", b, ",", c, "]");
  myString += writeToString("a record: ", r, " and: [", a, ",", b, ",", c, "]");
  myString += string.write("a record: ", r, " and: [", a, ",", b, ",", c, "]");
  ```
  In other words, it is less confusing to have one way to do something, and so we wouldn't want a fully feature rich write-to-string api AND a sort of one-off `string.write` method.

Note: In addition to providing `stringify`-like functionality, this feature would also provide:
  - the full range of IO methods for generating strings (e.g., `writeBinary`, `writeBits`, etc.), as opposed to only providing `write`
  - a straightforward path for incorporating serializers/deserializers into string generation (something that might be challenging within a single var-args routine):
    ```
    var stringWriter = openWriter(myString, serializer=fancySerializer);
    stringWriter.write(...);
    ```
  - `sscanf`-like functionality (see this [feature request](https://github.com/chapel-lang/chapel/issues/21248)), via the `fileReader` interface.

**Comment by mppf** [comment]
This direction is OK with me but I do have one concern.

> The deprecation message will indicate that the `%t` format should be used to achieve the same behavior as `stringify`:

> As such, we've decided to replace `stringify` (and the universal cast-to-string) with an existing feature that is already stable and will support both of the above use cases until new features are added post-2.0.

In #20256, it does not seem to me to be a sure thing that we would continue to have `%t` -- perhaps it has a different name and perhaps it only applies to builtin types. Did the discussion here include discussion about what would happen with `%t` ?

**Comment by jeremiah-corrado** [comment]
We did discuss this but it seemed like there was only a question about whether to keep `%t` on `readf`/`writef` (see: https://github.com/chapel-lang/chapel/issues/19906), and that `string.format` has already been stabilized as is. Does that sound correct to you, or does #19906 also pertain to `string.format` in your view @mppf?

(also the issue you linked above is this one, not sure if that was intentional).

**Comment by mppf** [comment]
> (also the issue you linked above is this one, not sure if that was intentional).

Oops, thanks, I've edited it to fix. You had the right issue number.

**Comment by benharsh** [comment]
In my experience, most languages that have a way of formatting a string also have an option for some simple/basic "just write the value in this position" behavior. I usually see this as something like ``"first arg: {} , second arg: {}"``. I think ``%t`` fulfills the same thing for us and that we should keep it (or something very much like it). I'm also just talking about ``%t`` here, not any variant with characters between ``%`` and ``t``.

**Comment by jeremiah-corrado** [comment]
> I'm pretty sure that we want to have only one format string syntax and it should be used by readf/writef as well as string.format.

Okay, thanks for clarifying. With this in mind, I agree that we should wait to move forward with deprecating `stringify` until the `%t` discussion resolves.

**Comment by lydia-duncan** [comment]
@jeremiah-corrado - I think this is complete?

**Comment by jeremiah-corrado** [comment]
Yes, this was completed in https://github.com/chapel-lang/chapel/pull/22068. Thanks @lydia-duncan!
