### ISSUE TITLE
I/O Module: Should we remove ``file.path``?

### ISSUE THREAD

**Issue by benharsh** [chapel-lang/chapel#20271]
This issue concerns the ``file.path`` method:

```chpl
proc file.path : string throws
```

This method returns a string representing the file's path. The returned value is the absolute path or the relative path, **whichever is shorter**.

There are two problems with this method:
1) The Path module might seem like a more logical place for this sort of thing.
2) The 'shortest path' behavior may appear inconsistent to users and may seem confusing

### Should we remove file.path in favor of a Path module function?

The advantage of this approach is that path-related stuff would be found entirely in the Path module.

A disadvantage is that ``myFile.path`` is very easy to use, and (to me) is more elegant/pleasing than ``absPath(myFile)``.

Another odd quirk is that the Path module functions that accept a file invoke ``file.path`` themselves, but we can provide some internal/undocumented function to provide that string if needed.

### Should we remove the shortest-path behavior?

It's unclear to me what the benefit of this behavior is over committing to just one kind of path.

-----

TODO:
- [ ] investigate whether ``file.path`` is used in any tests/benchmarks.

**Comment by bradcray** [comment]
With the caveat that I'm not a file system expert (and know there are tricky cases like "can a file's path change over time and what are the impacts on a routine like this?", I like the fact that this is a method/pseudo-field on files because it feels like a property of the file and `.path` feels like a natural way to get at it (similar to your "more elegant/pleasing" point above).

I don't feel like everything related to paths must appear in `Path` any more than I think that any routine that returns a bigint would need to be defined in the `BigInteger` module.  Put another way, I think of `Path` as supporting utilities related to manipulating and reasoning about paths, but not the only way to get at paths.

The "whichever is shorter" behavior gives me pause, but doesn't terrify me.  One solution would be to have an argument that let users choose between "relative", "absolute", and "shortest" with shortest as the default.  That would make anyone reading the documentation see the fact that there are options, but has the downsides that (a) we'd have to change it from a paren-less to a paren-ful method and (b) we'd have to introduce an enum.

Another approach would be to define a `getPath(f: file)` or `file.getPath()` routine is `Path` that permits all three modes, but to continue supporting `file.path` as a convenience and have its documentation say "This is like calling `Path.getPath()` with 'shortest' as the argument.  That would both define the current behavior and point users to an option for getting different behavior with slightly more work.

All that said, mostly, I don't find the current behavior terrible or broken and like this final approach in that it could be done incrementally if/when needed.

**Comment by benharsh** [comment]
In a discussion today, it was pointed out that the "shortest-path" behavior is useful for creating cleaner error messages. If we remove this shortest-path behavior for ``file.path`` we should probably preserve that behavior for error messages in the IO module.

**Comment by lydia-duncan** [comment]
In the discussion, we also took a few votes:

Remove `file.path` from the user's view: 0
Keep `file.path` in the user's view: 5

Maintain `file.path`'s behavior of returning the shortest path: 1
Choose a consistent thing for `file.path` to return: 6
Provide a way to select between shortest, absolute and relative for `file.path`: 0

Have `file.path` always return the absolute path: 7
Have `file.path` always return the relative path: -1

It also sounded like we could look into adding a way to get the shortest path for a particular file to the Path module, but that would be a post 2.0 effort (and something that should be spawned into its own issue)

**Comment by lydia-duncan** [comment]
In prepping for the discussion, I obtained the following list of places `file.path` is potentially used but did not open them yet:
<details>

```
test/io/dtjong/file-close-check.chpl:    writeln(f.path);
test/library/standard/Path/relPath/fileRelPath.chpl:  writeln('filepath= ', f.path, ' start= ', start);
test/library/standard/Path/relPath/fileRelPath.chpl:  writeln(f.path);
test/library/standard/Path/dlongnecke/absPath/fileAbsPath.chpl:  // writeln(f.path())
test/library/standard/IO/nonUTF8/basic.chpl:var p = f.path;
test/library/standard/IO/nonUTF8/basic.chpl:writeln("file.path works: ", p == filename1);
test/exercises/duplicates/duplicates-bonus-b3-size.chpl:    if a.path < b.path {
test/exercises/duplicates/duplicates-bonus-b3-size.chpl:    if a.path > b.path {
test/exercises/duplicates/duplicates-bonus-b3-size.chpl:      rec.size = getFileSize(rec.path);
test/exercises/duplicates/duplicates-bonus-b3-size.chpl:      rec.hash = computeFileHash(rec.path);
test/exercises/duplicates/duplicates-bonus-b3-size.chpl:        writeln("  ", hashAndPath[j].path);
test/exercises/duplicates/duplicates-bonus-b3-size.chpl:    rec.path = path;
test/exercises/duplicates/duplicates-bonus-b2-record.chpl:    if a.path < b.path {
test/exercises/duplicates/duplicates-bonus-b2-record.chpl:    if a.path > b.path {
test/exercises/duplicates/duplicates-bonus-b2-record.chpl:      rec.hash = computeFileHash(rec.path);
test/exercises/duplicates/duplicates-bonus-b2-record.chpl:        writeln("  ", hashAndPath[j].path);
test/exercises/duplicates/duplicates-bonus-b2-record.chpl:    rec.path = path;
test/functions/iterators/tzakian/open_inside_file_iter.chpl:  open(this.path, iomode.r, hints);
```

</details>

**Comment by jeremiah-corrado** [comment]
Resolved by: https://github.com/chapel-lang/chapel/pull/20769

**Comment by jeremiah-corrado** [comment]
Resolved by: https://github.com/chapel-lang/chapel/pull/20769
