### ISSUE TITLE
Memory.Initialization: explicitDeinit function signature

### ISSUE THREAD

**Issue by benharsh** [chapel-lang/chapel#20322]
The current signature of ``explicitDeinit`` is:

```chpl
proc explicitDeinit(ref arg: ?t)
```

There are some minor questions I want to raise concerning the argument name and return type.

### Return Type

We should set the return type to `void` in this case.

### Formal Name

Perhaps this is just my personal bias, but ``arg`` feels a little casual. In ``Reflection.getField`` we use the name ``obj`` and have deprecated the versions with the formal name ``x``. I propose we do the same here:

```chpl
proc explicitDeinit(ref obj: ?t)
```

**Comment by lydia-duncan** [comment]
I'm in favor of `obj` for the argument name and have a slight preference for `arg: ?t): t` over `arg): arg.type`

**Comment by benharsh** [comment]
@lydia-duncan : I messed up copying over some notes yesterday and confused some stuff with ``moveToValue``. Obviously ``explicitDeinit`` won't be returning anything, since it destroys whatever it was given. I'll be opening the ``moveToValue`` issue shortly.

Sorry for the confusion!

**Comment by bradcray** [comment]
> We should set the return type to void in this case.

Have we decided that we prefer `proc foo(): void` over `proc foo()` in terms of a function signature?  I realize that, with type inference, the latter is vague, but I also feel as though if we ensured that we declared return types for everything that did return something, I'd rather read the latter and assume the former than read/type the former.  Specifically, I think it's shorter/sweeter and that `void` is a somewhat esoteric concept, even though it's a common one for people coming from C/C++.

**Comment by benharsh** [comment]
I don't think we've decided that anywhere. I don't have any objection to ``proc foo()``, and would be fine adopting the convention of "blank implies void" in this case. Would we want to leave out any kind of ``:returns:`` chpldoc as well? We could indicate ``void`` there if we wanted.

**Comment by bradcray** [comment]
> Would we want to leave out any kind of :returns: chpldoc as well? We could indicate void there if we wanted.

I feel less strongly about that, though I'd probably just leave it off myself.  That said, I'm also someone who always feels a little silly typing `:rtype: int` for a procedure that's already documented `proc foo(): int`.

**Comment by benharsh** [comment]
@bradcray : I'm going to set aside the question of ``void`` as a return type for these Memory.Initialization functions until we decide whether we want to make that part of our standard practice regarding function signatures.

If you don't mind, I'd like to bring the discussion of the formal name ``obj`` over to this issue from the ``moveToValue`` issue since I think we now have a better option (``src``). Over there you [wrote a comment](https://github.com/chapel-lang/chapel/issues/20329#issuecomment-1206911868
) in which you point out that you (and probably the rest of us) talk about "objects" in reference to records and classes. This function should only be called on things that have either a ``deinit`` or ``chpl__autoDestroy``. Generally this would be records and classes, but would also include distributions, domains, and sync/single variables.

I would be OK changing the formal name to something meaningless like ``x`` since it seems like it will be difficult to arrive on a name that intends to convey some meaning.

**Comment by bradcray** [comment]
> This function should only be called on things that have either a deinit or chpl__autoDestroy. 

If we want to stick with `obj`, I'd be comfortable with that given these requirements (well, specifically the `deinit` requirement more than `chpl__autoDestroy`.  But since users shouldn't know about `chpl__autoDestroy` and hopefully it will go away someday and the routine name mentions deinit, that all seems OK to me.

One other case that may give people (but not me) pause about `obj` is that we recently added the ability to declare an `init` for external types.  I don't know that we added the ability to add a `deinit`, but I wouldn't be surprised if we found we should've someday.  Curious what @mppf thinks about that.  Anyway, I could imagine external types that had an init but were not objects, but am not worried about that because it seems to me that it's fair to consider anything that has an explicit deinit to be sufficiently object-like to warrant the name.

I'd be OK with `x` though given the above, I think I'd prefer `obj`.

Just to throw out one more concept, we could use `val` as something that's a bit less strictly OOP (though it could get into "What **is** a value anyway?" types of navel gazing).  (I think I still prefer `obj` though).

**Comment by benharsh** [comment]
I would also be OK with ``val``, and would prefer ``obj``.

**Comment by mppf** [comment]
I like `x` better, because I tend to use "object" to refer to exclusively to class instances.

In a strict sense, everything is not an object in Chapel. We have a built-in type called `object` that is the parent type for all class instances. So `int` is not a subtype of `object` and neither is a record type. Nor are arrays.

>  In Reflection.getField we use the name obj and have deprecated the versions with the formal name x

Maybe that was the wrong choice, since getField can apply to a record, and records are not subtypes of `object`.

**Comment by bradcray** [comment]
Oog, I hadn't thought of the `object` abstract parent class.  I tend to refer to all records and classes as objects when speaking about Chapel (and generally like doing so).  Put another way, Michael's reaction makes me think "Should we rename the root `object` class?" (less to permit the use of `obj` here but more because I don't have a good argument for why records are not objects (using English terms, not `object`s).

**Comment by mppf** [comment]
To consider renaming the root `object` class we would have to come up with another name. One drawback of renaming it is that `object` / `Object` has a lot of precedent in other languages.

(However I don't think I would object to renaming it, supposing we could come up with a name that is OK. I don't think `object` comes up that often for Chapel programs.)

**Comment by bradcray** [comment]
Your mention of `Object` makes me realize that given the capitalization conventions we've been going with, that would probably be a strictly better name for the type (not that it helps with this discussion).

Though object definitely has a lot of precedent, most OOP languages don't have multiple flavors of objects, like our classes and records I think (?).

Given that we've started using `class` as a generic "any class" type, I wonder if we could call it `Class`?

Checking the spec briefly, it looks like it refers to records as "object" (which is not to say "therefore that's right", just that it's not just my colloquial talking that does that... of course, I may have written those sections of the spec).  In other places it refers to "class object" to distinguish the class case.  The spec also refers to ranges as objects at one point.

This probably deserves to be forked off to another issue, though (sorry Ben)—I'll try to do that.

**Comment by benharsh** [comment]
I think we're all at least OK with ``x``, so that's what I'm going to go with for the time being unless someone feels strongly otherwise.

It should be noted that we're discussing the name of this function now over in #20410

**Comment by bradcray** [comment]
I've opened https://github.com/chapel-lang/chapel/issues/20414 for the side conversation about `object`.

While I'm not opposed to using `x`, I still think I prefer `obj` as a more descriptive / less cop-out name.  That makes me wonder how Michael will vote on #20414, and if he doesn't object to calling records objects going forward, I'd like to keep that in the running.  Unless we decide that records aren't objects (or, potentially, something else that this would be called on isn't).

**Comment by benharsh** [comment]
Following the subteam discussion, we have reached consensus on the argument name ``obj``. See also https://github.com/chapel-lang/chapel/issues/20410#issuecomment-1452576114 for the decision to rename this function ``destroy``.

**Comment by benharsh** [comment]
Resolved by https://github.com/chapel-lang/chapel/pull/21757
