### ISSUE TITLE
Memory.Initialization: moveToValue function signature

### ISSUE THREAD

**Issue by benharsh** [chapel-lang/chapel#20329]
This is the current signature of ``moveToValue``:

```chpl
proc moveToValue(const ref arg: ?t) 
```

I am proposing a new name/signature. The old function will be deprecated and later removed, and in the meantime will recommend using the new function:

```chpl
proc moveFrom(const ref src: ?t) : t
```

-----
Old Topics:

There are a couple of issues to raise here:

### Return Type

The return type is empty. We should change this to either ``t`` or ``arg.type``:

```chpl
proc moveToValue(const ref arg) : arg.type
proc moveToValue(const ref arg : ?t) : t
```

The type query currently exists for some minor convenience inside the function body: ``t == nothing`` and ``var result : t``.

The type query does not currently serve much of a purpose when the function body could use ``args.type`` just as easily. Of course, if we used it as the return type then it would be more justifiable. This is really more of a broader question regarding our standard conventions (if they exist for this case, or what they should be).

### Formal Name

Perhaps this is just my personal bias, but ``arg`` feels a little casual. In ``Reflection.getField`` we use the name ``obj`` and have deprecated the versions with the formal name ``x``. I propose we do the same here:

```chpl
proc moveToValue(const ref obj: ?t) : t
```

**Comment by vasslitvinov** [comment]
I propose renaming the function to `moveFrom`. Cf. "moveToValue" sounds unclear to me. 

I am content with `arg` for the formal's name. I am ok with "obj", too.

For the return type, I suggest the form `proc moveToValue(ref arg : ?T) : T`. This looks more elegant to me. Another motivation is that we can standardize on `?T` across our public module interfaces wherever we need to reference the type of a generic formal. A capital `T` is an indication that it is a type, whereas a lowercase "t" looks more like a value.

**Comment by bradcray** [comment]
Vass's comment resonates with me a bit.  Specifically, in reading the title of this issue and prototype of the routine, I was feeling hard-pressed to understand where the other side of the move was.  `var x = moveFrom(y);` seems to read a bit more cleanly than `var x = moveToValue(y);`.  But I've admittedly never used this routine.

A slight reaction to `obj`:  Would users use this call on types other than arrays and records?  Though I can imagine a world in which we said "everything is an object" (particularly since we permit methods on everything), I tend to only talk in terms of records and classes as being objects.

I do agree that `arg` feels like something of a cop-out of an argument name, though.  Would we want to use `from` or `src` as the argument name?  (`from` probably only makes sense if we don't call the routine `moveFrom()`).

I agree we should specify the return type and am pretty neutral between the two forms, with maybe a mild preference for the query-based form just because I think it's cleaner/cuter and plenty intuitive.  I think standard library routines should be able to use either form, though, and that we shouldn't force ourselves to unify on one or the other and find both plenty clear.

**Comment by benharsh** [comment]
I would be fine with an argument name of ``src`` if we changed the function name to ``moveFrom``.

**Comment by mppf** [comment]
I'm OK with `moveFrom`. In defense of `moveToValue` another name for this routine could be `moveFromReferenceToValue`. One interesting argument name option, then, is something that means "reference". Of course it can't be `ref` but `r` or `reference` might be reasonable.

**Comment by mppf** [comment]
@benharsh - I see `proc moveToValue(ref arg : ?t) : t` above but the documentation https://chapel-lang.org/docs/modules/standard/Memory/Initialization.html#Initialization.moveToValue has `const ref` intent. Is changing it to `ref` intent here an oversight or something you are proposing?

**Comment by benharsh** [comment]
> @benharsh - I see `proc moveToValue(ref arg : ?t) : t` above but the documentation https://chapel-lang.org/docs/modules/standard/Memory/Initialization.html#Initialization.moveToValue has `const ref` intent. Is changing it to `ref` intent here an oversight or something you are proposing?

Yes, definitely an oversight of mine when typing out the new signatures. Sorry!

**Comment by benharsh** [comment]
Thanks, everyone, for your input so far. I believe we are converging on the following proposal:

```chpl
proc moveFrom(const ref src: ?t) : t
```

Changes:
- ``moveToValue`` becomes ``moveFrom``
- formal ``arg`` becomes ``src``
- uses the pre-existing type-query to specify the return type

Any objections?

**Comment by vasslitvinov** [comment]
Replace `t` with `T`, anyone?

// Was this discussed on another issue?

**Comment by mppf** [comment]
> Replace `t` with `T`, anyone?
> 
> // Was this discussed on another issue?

It needs its own issue -- see https://github.com/chapel-lang/chapel/issues/20328#issuecomment-1210895219

**Comment by benharsh** [comment]
Resolved by https://github.com/chapel-lang/chapel/pull/21087
