### ISSUE TITLE
Memory.Initialization: Module Naming

### ISSUE THREAD

**Issue by benharsh** [chapel-lang/chapel#20425]
This issue exists to discuss the naming of the ``Memory.Initialization`` module, and whether it should be a sub-module of ``Memory`` or its own standalone module. Interested parties might benefit from reading over #16172, which includes a lengthy first-round of this sort of discussion.

Initially, the two names that made it to the final round and were voted upon were ``Memory.Movement`` and ``Memory.Initialization``.

This module is intended to support memory-movement semantics in Chapel through various functions, so keep that in mind when proposing ideas. Also note that this memory-movement is often in support of initializing uninitalized data (e.g. no-inited array elements).

**Comment by dlongnecke-cray** [comment]
I dislike the name `Memory.Movement`, because it evokes images of comm to me (which this is definitely not). IIRC we went with `Initialization` because it was the most suitiable name at the time, not necessarily because it's the best name overall.

I think one name suggested was `Memory.Move`/`Memory.Moves`, which I'd be fine with, but then it makes `deinit` feel out of place, so maybe we should move that to another submodule or something (or just live with it being a bit odd).

One of our intentions is to introduce a low level buffer or wide pointer or equivalent to `_ddata` (whatever form it ends up taking), and I was imagining it would get its own submodule as well.

I am a huge fan of the submodule approach. I would not be happy if we reverted to something like `MemoryMove` and `MemoryDiagnostics` at the top level (but of course as with all these things, I'd live with it, and I know I'm a small fish in a big pond 😄).

My rationale for that is the same as one of my rationales for factories being type methods - we went through all this effort to add `include` modules, and then we're not even going to bother to use them in a place where it seems obvious? Seems like a waste.

**Comment by bradcray** [comment]
If I were doing this again today, I believe I would call this module something like `MemInit`.

I don't really like the current hierarchical organization because:

* I don't find it appealing to have the empty `Memory` module at the top.  It results in what feels like the saddest page in our documentation to me:  https://chapel-lang.org/docs/modules/standard/Memory.html
* I don't feel like `Memory.Initialization` and `Memory.Diagnostics` are really siblings in any meaningful way.  Yes, they both have to do with memory, but one is about exposing deep semantic features in the language, and the other is about ways of measuring or logging memory utilization.  The former feels more core and on the cusp of being in the language proper, while the latter feels more like a utility library or external tool.  I'm not convinced that the commonality of "being about memory" is a good rationale for the current organization—lots of things are about memory.
* As an offshoot of the previous bullet, it seems like if the standard module index at https://chapel-lang.org/docs/modules/standard.html were done right, it should list the full path to each submodule in a different section which again make these two cases feel a bit more like outliers relative to the rest of the standard modules.
* I don't like that making it hierarchical requires more typing to get to either of the modules, particularly when I suspect most modules will only want to use one or the other rather than both.

**Comment by bradcray** [comment]
> we went through all this effort to add include modules, and then we're not even going to bother to use them in a place where it seems obvious?

I was thinking about this comment a bit more last night because it didn't sit right with me, but I was hard-pressed to say why yesterday afternoon.  I think it comes down to this:  I think the reason we added `include` was to provide at least one way of breaking a single logical module and its submodules into separate files if one wanted to.  I don't think we did it as an excuse or means to introduce more hierarchy into our module system.  E.g., while putting all of our collections under a `Collections` module is something that we could do, I'd much rather type `use List;` than `use Collections.List;` in my code and just have the documentation sort the collections into a common bucket for the purposes of keeping them logically organized and associated.  

> where it seems obvious?

The intent of my previous comment was to say that, to me, grouping the memory initialization features and the memory diagnostics features doesn't seem particularly "obviously right / good", and multiple times while reviewing or refactoring the documentation since we made the decision, it's been more the opposite to me—it just feels like it's not quite right / consistent / of a kind (with each other; with other things).  That's not to say it's obviously bad or wrong or that different people might not organize them differently, just that it's grated on me personally.  If I'm in the vast minority, I'm not going to fight it, but that's why I pushed for this discussion.

Contrast with an `OS` hierarchy in which the root module contains stuff that is OS-neutral and we have submodules for POSIX, Windows, VAX, whatever.  To me, that feels like a more natural and consistent and attractive use of modules and submodules than this one does.

**Comment by dlongnecke-cray** [comment]
> I don't think we did it as an excuse or means to introduce more hierarchy into our module system.

I didn't mean to imply that we should use `Memory` as an opportunity to shoehorn include modules into the standard modules. That it is a natural application follows (to me) from the thought that these are all entities that belong in the "Memory" namespace.

I'm not really bothered by there not being too many (or any symbols) in the top level `Memory` module right now. We could introduce symbols to it later, e.g, I've been thinking that maybe `explicitDeinit` could live there, or a `widePtr` / `lowLevelLocalBuffer` if we introduce that later.

And if seeing an empty module irks you, maybe we could adjust `chpldoc` so that it omits parent modules that don't have any symbols in them from being clickable (maybe it's just an organization thing).

To me the aesthetic issue is that as soon as we start having `2+` modules with a common prefix e.g., `MemInit` /`MemDiagnostics`, it feels like we're artificially namespacing things and really ought to just be using the submodule concept instead.

Maybe this issue could be sidestepped if we renamed `MemoryDiagnostics` to something like `AllocationStats` or something that disassociates it from `Memory`. In which case we could do with renaming `Memory.Initialization` to something else that isn't a submodule (I'm not quite certain what that name should be at this point, though).

**Comment by benharsh** [comment]
>  That it is a natural application follows (to me) from the thought that these are all entities that belong in the "Memory" namespace.

I'm also inclined to view ``Memory`` here as a sort of namespace.

**Comment by bradcray** [comment]
> (maybe it's just an organization thing).

I kind of alluded to that above.  Let's say we fixed the documentation such that the standard modules index looked like this:
<img width="270" alt="Screen Shot 2022-08-12 at 3 45 49 PM" src="https://user-images.githubusercontent.com/7536222/184453957-941087bc-76f8-400f-9c6b-0d141f3c27f0.png">

To me, this view emphasizes that these two submodules aren't really two peas in a pod, but instead two pretty unrelated things.  Whereas a view like this:

<img width="275" alt="Screen Shot 2022-08-12 at 3 49 25 PM" src="https://user-images.githubusercontent.com/7536222/184454148-45c07448-b9d9-4673-9acb-17c342961590.png">

feels less "forced" to me.  Yes there's a common prefix, but I don't view it as a second-rate namespace so much as a reflection of what the  module's contents are.  More on this below.

I strongly suspect there's a big dose of personal taste here that we're unlikely to agree on.  If you gave me a collection of things on the order of a few dozen to maybe 50 or 75, I think I'd typically prefer to be able to think of those things as a flat collection and be able to randomly access whichever I want, and then use documentation (e.g., categories, tags, or the like) to make the collection organized and comprehensible.  Whereas I suspect your preference would be to sort them into a hierarchy as much as possible and have as few top-level modules as possible?  And I'm not saying that's bad or wrong, just that it's different from my preference.

Two additional arguments I'll give beyond "it's my preference" are:
* many modules have multiple cross-cutting aspects to them, like `Memory.Diagnostics` being about both Memory and Diagnostics.  So who's to say that `Memory.Diagnostics` is the right hierarchical organization rather than `Diagnostics.Memory`?  (as Engin argued for at some earlier point)  If there is no obvious correct choice, using a less hierarchical organization dodges the need to have to make the choice.
* it also seems inconsistent to have only one empty standard module that acts as a namespace while all other standard modules are either top-level modules or logical specializations of their parent module.  That is, if we really believe this is the right thing to do, arguably we should do a bunch more of it so that this wouldn't seem like such an outlier to me (but I don't really want to do that due to both the previous bullet and the taste thing, not to mention that it will require more changes than just changing this one case).

**Comment by dlongnecke-cray** [comment]
This is a tough one. I did have a rebuttal but deleted it due to the feeling things were getting circuitous. It's true there's a big dose of personal taste here.

Can we find common ground by just avoiding the collision on the `Mem` prefix? My hope is that we can. Then we can keep things flat and tidy.

[Aside: You bring up `Diagnostics.Memory` and truth be told, I'd be quite happy with that organization instead. Of course that leaves us with another module that has no contents (or maybe it can have a "turn all the diagnostics in the universe on?" 😄).]

I think we're probably going to settle on the name `Mem(ory)Diagnostics` to match the others, so that just leaves the name of this module to sort out.

And as I come back to this module, I find that I only really tend to think about it in the context of "I am building a collection", so maybe we can call it...`CollectionSupport`?

Ahhh, I feel like I'm retreading well worn ground now 😄.

**Comment by benharsh** [comment]
If we go with a top-level module, I'd prefer something like ``MemMovement``. ``MemInit`` does not feel like a useful name to me.

Some other personal taste stuff:
- Generally I'm not too bothered by longer module names
- ``Diagnostics.Memory`` is also appealing to me...
- Conversely, if we have a ``Communication`` module I wouldn't mind CommDiagnostics moving *under* there as a submodule...

**Comment by bradcray** [comment]
> MemInit does not feel like a useful name to me.

@benharsh: Can you say more?  Is it simply the brevity?  (e.g., would `MemoryInitialization` fix that?)  Or were you similarly opposed to `Memory.Initialization`?

To both David's and Ben's comments, I'm much more in favor of not having a singleton "empty, namespace" module and moving these submodules to the top-level than I am with the names I've proposed (though I do think `MemDiagnostics` fits well with the other diagnostics names we have).

(and of course, another way to not have a singleton empty namespace module would be to have a bunch more of them, but I'm not going to be the one to propose or champion it for similar reasons—when I want to use a list, I'd much rather type `import List;` than `import Collections.List;`.  Similarly, I'm generally not a fan of deeply hierarchical online documentation—categories and sections of pages are great, but deeply nested docs I tend to find challenging to browse).

**Comment by benharsh** [comment]
> > MemInit does not feel like a useful name to me.
> 
> @benharsh: Can you say more? Is it simply the brevity? (e.g., would `MemoryInitialization` fix that?) Or were you similarly opposed to `Memory.Initialization`?

There are two reasons I dislike ``MemInit``:
a) I don't like "Initialization" being in the name we choose
b) The brevity

Concerning the word "Initialization": I recognize that this module will often be used to handle initialization of memory correctly, but I believe that if I were coming from another language I would find the word "Movement" to be much more natural and intuitive than "Initialization". I feel that in other languages memory movement semantics are often used in the context of initialization, and might be considered a special subset of initialization.

The brevity also bothers me somewhat, though I don't have a particularly consistent stance here. I think "Mem" with another shortened word is going a bit too far (e.g. even ``MemMove``). I'm generally not bothered by longer module names since I almost always just have to write them once, and can rename them if I need to use them in a qualified access style. At the same time, something like ``MemoryInitialization`` does feel too verbose to me.

I would be interested in a namespace-module that contained ``Movement``, ``Reflection``, and ``Types``. This is also verbose, but I believe we'll eventually have a language server that can provide tab-completion for this sort of thing. I think that we can improve chpldoc or our custom doc scripts to handle the "flattening" of these kinds of modules in order to avoid deep obfuscating hierarchies in the online documentation.

**Comment by bradcray** [comment]
I tend to agree that `MemMoves` is in some way more descriptive of what this module does than `MemInit` (and like it).  I think the main downside with both names is that neither really says anything about the deinitialization aspects of it.  That makes me think of `MemOps` or `MemUtils`, both of which feel unsatisfactorily vague.

> I believe we'll eventually have a language server that can provide tab-completion for this sort of thing.

Even with such support (even if it were provided in emacs), my preference is still to type things rather than rely on tools to save typing for me (in part because I find I type fast enough that the tools don't help that much, particularly when there are ambiguities or it needs to "think").  Beyond just the typing, I'm also thinking of the additional printer ink that'll be required when I make hardcopies of my source code.  Basically, I don't see what value I get as a programmer (or a reader of my code gets) by having a deep hierarchy of standard libraries beyond putting things further out of reach (but I've probably made that plenty clear by now).

That said, I think if you/someone wanted to champion that approach, that person should create a new issue that would be titled like "Should we organize most/all of our standard modules into namespace categories?" and propose an organization that takes that approach for the current modules.  As I said, I'd rather all or none of our modules be organized that way than just two (and I'm definitely not going to be the champion who writes up such a proposal).

**Comment by benharsh** [comment]
@mppf, @bmcdonald3 , @vasslitvinov , @daviditen : you all voted on the comment proposing a module naming discussion (whether or not that vote was in favor). I think we could use some more opinions about the things we've discussed so far, but you don't necessarily need to propose a new option. You're also welcome to say that you are content with the naming/hierarchy as-is.

Our decision concerning the sub-module nature of this module will have a notable impact on the naming. I think Brad has made his argument(s) against the sub-module at this point. Does anyone else feel that this structure is not the right approach? Does anyone support this module being part of some other sub-module-group (e.g. ``Language.<something>``)?

It's tempting to try and take a vote on _something_ but I don't think we're converging on any proposals just yet.

**Comment by daviditen** [comment]
https://github.com/chapel-lang/chapel/issues/20330#issuecomment-1200042213 If you mean this vote I think Vass and I voted against. Brad, Michael, Ben and Michelle were for keeping the discussion open.

**Comment by vasslitvinov** [comment]
I do not have a strong opinion one way or another. My disinclination to discuss is because the current structure and naming are a result of a discussion we had in the past. In order to revisit it, we need a strong argument, which I do not have.

**Comment by bradcray** [comment]
For me, the strong argument for revisiting is that—since the initial discussion—it's increasingly felt like a singleton outlier in our standard modules (the only case of using a top-level empty module as a namespace to link two other not-so-related moduels), which has given it a bad smell for me whenever I review the standard module documents.  If I'm the only person who feels this way, I'm willing to concede the concern and leave it as an outlier.  That said, it was also notable to me that BHarsh didn't think `Initialization` should be in the module name (where I'm not sure he was around when the previous discussion took place).

**Comment by mppf** [comment]
It might seem trivial/stupid, but the main reason I think we should seriously consider changing this, is that when I want to find docs for `Memory.Initialization`, I click on "Diagnostics" which makes no sense. I understand that there are other ways we could fix that, but we haven't. I think an implication is that we probably want the module/submodule hierarchy to match something reasonable, in terms of documentation structure/heirarchy. I haven't felt I had the time to read all the other comments here but at a glance this looks like a point that Brad has already brought up.

What are some other submodules in the standard library?
 * OS.POSIX
 * Random.PCGRandom / Random.NPBRandom
 * IO.FormattedIO

But, all of these are very different from Memory.Diagnostics and Memory.Initialization.

In the OS.POSIX case, the intention is that the submodules of OS will more or less cover the same topics, but support different platforms. (As Brad noted above). The Random.PCGRandom / Random.NPBRandom is similar - different implementations of the same general concepts.

IO.FormattedIO is different - where FormattedIO is a different feature from everything else in IO that "is its own thing" in terms of documentation. I would describe it as additional, optional IO functionality.

Compare with Memory.Diagnostics / Memory.Initialization. There is no functionality in the Memory module and in fact it only seems to exist to contain the others. So we cannot say that either is adding additional, optional functionality. And, at the same time, Diagnostics / Initialization aren't both alternative implementations of the same concept.

Now, of course, we could conclude that we like this module/submodule organization. The main point I am trying to make here is that it seems to be weird case, today.

**Comment by mppf** [comment]
(Also, in terms of revisiting an earlier decision, which I understand is annoying: In this case I think I voted for Memory.Diagnostics / Memory.Initialization with the expectation that we would end up with other standard modules using a similar structure, but that hasn't happened, an now it seems like a weird outlier.)

**Comment by bradcray** [comment]
> when I want to find docs for Memory.Initialization, I click on "Diagnostics" which makes no sense

I'm not following this Michael—can you clarify?  How are you finding and what are you clicking on?

**Comment by mppf** [comment]
> > when I want to find docs for Memory.Initialization, I click on "Diagnostics" which makes no sense
> 
> I'm not following this Michael—can you clarify?  How are you finding and what are you clicking on?

* I start from https://chapel-lang.org/docs/
* then I click "Standard Modules" on the left
* then I click "Diagnostics" on the left
* then I click "Memory" on the left
* now I can click "Memory.Initialization" in the main page

It's really just another way of saying "The Memory.Initialization and Memory.Diagnostics ought to be in different documentation categories" which is something already brought up here, AFAIK.

**Comment by bradcray** [comment]
Got it, thanks.  As you note, the docs org would be an easy fix which I prototyped to create the screen grabs in https://github.com/chapel-lang/chapel/issues/20425#issuecomment-1213578615.  But I understand that you're using this more as an indication that something smells a little funny (and backing up my claim that it's a singleton outlier) rather than this being the main problem.

**Comment by benharsh** [comment]
I'm hoping to revive this discussion as we get closer to the next release, and in time for an upcoming offline discussion next week. I believe there are three major areas of concern regarding the renaming of this module renaming:
1) Should we rename it at all?
2) Should it be a sub-module or a singleton module?
3) Should the module name involve "Initialization" or "Movement" as concepts? Or perhaps something else entirely?

Now that some time has passed, I'm leaning towards a standalone module instead of a sub-module. I find myself motivated by the argument of this being a weird case in our module hierarchy today.

As far as actual naming goes, I still find myself favoring something with the words "Move" or "Movement".

**Comment by dlongnecke-cray** [comment]
I'd be fine with just calling the module `Move`.

**Comment by benharsh** [comment]
Following up after some online discussion:
A) Vote taken on standalone vs sub-module options:
  - Move to standalone module: 10
  - Rename, but keep as sub-module: 1
  - Keep as-is: 1

B) Initialization vs. Movement (or variants)
  - Initialization: 0
  - Movement: 9
  - Other: 1

@dlongnecke-cray made the point that Movement doesn't really convey anything about the explicit deinitialization options, and suggested we might think of these as a collection of "low level" memory operations. Does this resonate with anyone else? Perhaps some kind of name like ``LowLevelMem``?

**Comment by dlongnecke-cray** [comment]
Michael suggested something like `CollectionSupport`, as well.

I think what would help me more is to figure out where we'd want the following entities to live, even if some of them don't exist yet:

- `widePtr` and `LowLevelBuffer` (neither exists yet, second may not need to exist)
- `explicitDeinit` (currently exists in this module)

I could imagine a world where we have:

- `Move` `use Move;` `Move.moveInitialize()`
- We introduce `widePtr` as a builtin type or something in `ChapelBase`
- Where would we put `explicitDeinit`?

If we could move the things out of this module that aren't related to `Move` then I'd be OK with calling it `Move` or `Movement`.

**Comment by bradcray** [comment]
I'm not offended with deinit-related capabilities being in a module named `MemMove` or `Move` if we believe that they'll typically be used hand-in-hand with those features.  Do we?

I'm not excited about `CollectionSupport` because my sense is that these capabilities have value even if you're not writing a collection.  I'd also prefer to have the module name characterize what the module provides / focuses on rather than the context in which it might be used.

**Comment by benharsh** [comment]
> I'm not offended with deinit-related capabilities being in a module named `MemMove` or `Move` if we believe that they'll typically be used hand-in-hand with those features. Do we?

We discussed this a bit over in https://github.com/chapel-lang/chapel/issues/20410 , but I don't think we came to any particular conclusion. I think if we understood that better, or could reach a consensus, then we'd have an easier time deciding on the names.

I believe a use-case unrelated to move-semantics was the ability to check if a buffer/array's elements required deinitialization, and manually deinit if necessary.

**Comment by mppf** [comment]
I don't think it's necessarily the case that an explicit deinit call would always be used in a module also using `move` functions, but I do think it's by far the common situation.

**Comment by benharsh** [comment]
I think there are three variants to vote on:
- 👍 Movement
- 🚀 Move
- 🎉 MemMove

Please vote!

**Comment by bradcray** [comment]
Rationalizing my vote:  My sense is that there are many forms of moving (e.g., `mv` in Unix) so I like giving the user some hint of what kind of move we're talking about.  And I think the name is still plenty short and sweet.

**Comment by dlongnecke-cray** [comment]
I voted for `Move` because I think if we were adding this feature to the language, we'd name its keyword `move`, so I don't think having the module being named `Move` is terribly ambiguous. I'm not a fan of partial/shortened names, so I'd prefer `MemoryMove` over `MemMove` aesthetically.
