### ISSUE TITLE
How to handle `QIO_CH_ALWAYS_UNBUFFERED` in the IO module?

### ISSUE THREAD

**Issue by jeremiah-corrado** [chapel-lang/chapel#20432]
The `QIO_CH_ALWAYS_UNBUFFERED` IO hint indicates that a channel should not use buffering. This is currently used in some of the `shootout` benchmarks.

In some discussion on [this](https://github.com/chapel-lang/chapel/issues/20346 ) thread, it was noted that the `ioHintSet` type should not be used to pass this directive to the runtime because it affects which methods are available on the channel interface (specifically: `mark`, `revert`, and `commit` do not work without buffering). 

## Option 1 : 
The channel type could toggle buffering behavior with a boolean param which mediates method availability via `where` clauses (similar to the way `locking` is currently used on the channel type). 

For example, the `mark` method might look like this:
```chapel
proc channel.mark() throws where this.locking == false && this.buffering == true { ... }
```

And presumably the `File` methods that return a channel would also take a boolean param as an argument. It would likely have a default value of true, as buffering is desirable in the vast majority of situations.

## Option 2: 

Non-buffering IO could also be supported by an entirely separate non-buffering-channel type (the unsupported methods would of course not be available on this interface)

The `File` methods that return a channel, would still have a boolean argument to toggle between buffering and non-buffering IO, except in this case, the return type would depend on the value of that argument. Or they could have separate methods, say `nonBufferingWriter`.

**Comment by mppf** [comment]
@jeremiah-corrado - are we pretty sure that we need this feature in some form? What happens to the performance of the tests/benchmarks using it if the hint is not used? Is there an alternative strategy to get some of the same goals? For example, using the mmap hint should really change how the buffering occurs & reduce the total amount.

**Comment by jeremiah-corrado** [comment]
I'm not totally sure whether it's necessary. I ran some quick tests on the revcomp benchmark last week using one of the larger test files -- with and without buffering. The hint didn't seem to impact performance at all, but this was just one benchmark on my laptop, so I'd like to do some more rigorous testing.  

Also @ronawho's comment on the related issue: https://github.com/chapel-lang/chapel/issues/20346#issuecomment-1218281800, indicated that the non-buffering flag was included in the shootout benchmarks because of a memory limitation in the old testing system. So if I'm understanding correctly, this flag might have just been added for internal testing purposes, but isn't really needed anymore?

**Comment by ronawho** [comment]
I don't think we changed any flags because of memory limitations on testing systems, just that memory limitations on an older system resulted in variable timings that weren't seen when running benchmarks on the official shootout site.

**Comment by jeremiah-corrado** [comment]
Ok I see. I was misinterpreting your message on the the other thread. 

I'll run some more rigorous performance tests next sprint and report back here.

**Comment by jeremiah-corrado** [comment]
@mppf - here are some execution-time data I collected on the revcomp2/3 benchmarks. I believe these are the only two shootout benchmarks that currently use the `QIO_CH_ALWAYS_UNBUFFERED` flag. 

There appears to be a small advantage to using `QIO_CH_ALWAYS_UNBUFFERED` in all cases. There is also a small advantage to using the`mmap` hint (which was only applied to the input file on the fileIO tests).

![Screen Shot 2022-09-26 at 12 02 31 PM](https://user-images.githubusercontent.com/62707311/192348166-08afac6f-d068-446f-8fcd-58405dc83cf1.png)

![Screen Shot 2022-09-26 at 12 02 42 PM](https://user-images.githubusercontent.com/62707311/192348172-02b9bafb-b7df-41fb-91e0-ce42367b976a.png)

This experiment was run on my laptop (m1 mac). Mean execution times were averaged over 200 runs. The input file was generated from the "fasta" benchmark with n=25000000 (same input as the perf testing for these benchmarks).

The `stdio` experiments used the benchmarks as designed (i.e. streaming the input through `stdin`, and the results out through `stdout`). The `fileio` experiments used files (i.e. openreader/openwriter) instead.

More detailed data here: [stats_summary.pdf](https://github.com/chapel-lang/chapel/files/9648596/stats_summary.pdf)

**Comment by bradcray** [comment]
> The stdio experiments used the benchmarks as designed (i.e. streaming the input through stdin, and the results out through stdout). 

Tagging @ronawho because I can never quite remember what we do or do not know here (no matter how many times he reminds me):
* I believe that the shootout site pipes stdout into `/dev/null` when it's doing timings for its performance runs and that we've found this to have an impact on execution time, so it could be worth seeing whether that affects your stdio timings positively or negatively
* I also think that even when we had a near-exact replica of the CLBG box available to us, we were not able to reproduce the site's timings for all I/O benchmarks where we were able to for computation-only benchmarks (and maybe other I/O benchmarks?)—I can never recall whether we came up with a satisfactory explanation of this or not.

The scripts used by the site are open-source, so presumably could be used to gather timings, but I can't recall whether we tried that and still saw differences (maybe suggesting a subtle difference in our I/O systems) or whether we didn't ever dig that deep (out of disinterest).  And we no longer have an exact replica of the site's system, so maybe this is a moot point anyway.

**Comment by ronawho** [comment]
> Tagging @ronawho because I can never quite remember what we do or do not know here (no matter how many times he reminds me):

I haven't really been keeping up with this, but probably talking about https://github.com/chapel-lang/chapel/issues/20346#issuecomment-1218281800

**Comment by bradcray** [comment]
Thanks for wrestling with this Jeremiah.  My quick reactions are:

* Since this isn't a POSIX routine, it seems like it should go in `OS` rather than `OS.POSIX`?
* I'm wondering whether, in doing so, we could also get rid of the `stdinBin = openfd(0), stdoutBin = openfd(1);` declarations, which to me are very non-Chapeltastic.  E.g., should `OS` define its own `stdin`/`stdout` which are these file descriptors?

**Comment by bradcray** [comment]
Good point that I hadn't updated to the new syntax.  You're right though that the preservation of the 0 and 1 still make these not feel Chapeltastic to me.

**Comment by lydia-duncan** [comment]
We will probably want that name to not conflict with the stdout and stdin in the IO module, since we have this definition in the IO module today:

```chapel
const stdin:fileReader(iokind.dynamic, true);
stdin = try! (new file(0)).reader();
```

(note that `IO.stdout` is created using an extern helper function instead)

**Comment by bradcray** [comment]
I was thinking that maybe using the same name would be the most logical since they're different libraries' notions of what stdin/stdout/etc. are.  I.e., "this is what stdin/stdout/stderr mean to the OS; this is what they mean for our standard IO library."  And if / when there are conflicts in a given piece of source code, the user would have to deal with them.

Part of that is, admittedly, not having any particular inspiration about what other names we might use.

**Comment by lydia-duncan** [comment]
Sorry, I meant more from the perspective of "if we try to use it in the IO module to create IO's stdin, as would be natural, we'll either run into naming conflicts or need to use qualified access"

**Comment by bradcray** [comment]
I see.  I think qualified access would be a natural/clear way to handle this.

**Comment by bradcray** [comment]
Reviewing deprecations in submitted shootouts today for the 1.30 release, I ran into this issue and opened up https://github.com/Cray/chapel-private/issues/4530 as an issue that focuses more broadly than on the unbuffered case that motivated this issue, and on the larger question of alternatives to writing `new file(0)`/`new file(1)` that we've been discussing in the past few comments above.  It's highly coupled with this issue, but arguably just approaches it from the top-down ("how should we be writing these idioms?") rather than bottom-up focusing on the unbuffered element.
