### ISSUE TITLE
`locale` module stabilization: the `numPUs` method 

### ISSUE THREAD

**Issue by jeremiah-corrado** [chapel-lang/chapel#20445]
The acronym: *processor unit*, used in `locale.numPUs()` is not properly camel cased. See this related issue: https://github.com/chapel-lang/chapel/issues/20240

Should the method be renamed to `locale.numPus()` (*hint: probably yes*)? However... if it needs to be renamed anyway, this would be a good opportunity to make a more significant change. I'd be curious to know if anyone is in favor of entirely renaming this method (ex: `cpuCount()` or `numCpus()` - to future proof against any possible confusion with G<ins>PU</ins>s)?

If not, the camel-casing does need to be fixed at the very least. 
___

During the locale module review, I also brought up the notion of replacing this method with something more general. The following proposal did not gain much traction, but I figured since this method needs to be changed anyway, it would be a good idea to reiterate here just in case other locale-related discussions have changed peoples thinking:

Instead of having a cpu-specific method that returns an integer, perhaps it would be beneficial to have a more general "hardwareSpecs" method that returns a record or Class type with the relevant/available data about the `locale`. 

This has three main benefits that I can think of:

- We can simplify the current interface by removing both of the boolean arguments described in the [docs](https://chapel-lang.org/docs/language/spec/locales.html#ChapelLocale.locale.numPUs). (i.e. the returned record type could contain all four cpu-counts stored in the `locale` type: logical-accessible, physical-accessible, logical-all, physical-all)
- As GPU features become more stabilized and mainstream, we may want this method to return something reasonable for the gpu sub-locale type. In this case, the returned value could be populated with different information relevant to the GPU's specs (ex: memory size, num-SMs ,etc.). 
- As oversubscription gains more support (specifically for one-locale per NUMA domain), the definition of the current interface might become somewhat muddied (i.e. do we consider neighboring CPU cores on the same node, but different locale to be accessible?) Therefore, we may want to expose additional or different fields about the NUMA architecture through this method when an oversubscribed configuration is in use. Returning a record/Object would allow us to do that, and to add such a feature later on without breaking the interface.  

In practice, the above would involve deprecating `locale.numPUs()` and replacing it with a new method (maybe `locale.hardwareSpecs`). The new method would return the same cpu-count information currently defined on the `flat` locale model, except in the form of a record or Class. 

In the future, other record-fields or subClasses (depending on the implementation) could be added to handle gpu-sub-locales, different oversubscription configurations, etc.

**Comment by bradcray** [comment]
> I'd be curious to know if anyone is in favor of entirely renaming this method (ex: cpuCount() or numCpus()

I think we intentionally avoided `cpu` because a "quad core CPU" would arguably be 1 CPU but have 4 processing units (or 8 if hyperthreading was enabled).

> to future proof against any possible confusion with GPUs)?

In a CPU+GPU locale model, I think I'd expect the top-level locale's `.numPUs` query to never include the sublocale's capabilities (and similarly for other queries like amount of memory and the like).

All that said, I agree that `numPus`, with the agreed upon capitalization, is not particularly clear (I read it as "number of pus" (amount of pus).  So it's a case where I find myself wishing for some creative license to be granted to authors in casing/naming (because I think `numPUs` is not a bad name once you learn the acronym, and visually scans reasonably clearly).

While I wouldn't be opposed to a richer query that returned an object with a bunch of stuff stored in it, I think there's merit in having simple ways to pick out commonly-needed features like this for simplicity/brevity.  For example, I've definitely written lots of code that's done things like `if ... < here.numPUs()` or `coforall tid in 0..<here.numPUs()` (and similarly for memory queries) which are attractively short and sweet.

**Comment by jeremiah-corrado** [comment]
> > to future proof against any possible confusion with GPUs)?

> In a CPU+GPU locale model, I think I'd expect the top-level locale's .numPUs query to never include the sublocale's capabilities (and similarly for other queries like amount of memory and the like).

I agree. By future proofing, I was thinking about what would happen when users call this method on a gpu sub-locale. Specifically, in the following case, I think it is more obvious that this call doesn't make sense:
```chapel
here.gpus[0].numCpus();
```
compared to the current name, where the user might expect it to return the number of SMs on the gpu or something. (which I suppose could be a reasonable way for the gpu sub-locale to be implemented, except, the two boolean arguments `logical` and `accessible` don't really make sense in that case).
___

> I think there's merit in having simple ways to pick out commonly-needed features like this for simplicity/brevity. For example, I've definitely written lots of code that's done things like `if ... < here.numPUs()` or `coforall tid in 0..<here.numPUs()` (and similarly for memory queries) which are attractively short and sweet.

If we were to give the current method's default return value (for `logical = false, accessible = true`) a short name in the record/Class, I don't think the above would be *too* much longer. Example:
```chapel
coforall tid in 0..<here.hardwareSpecs.numCores { }
```

**Comment by bradcray** [comment]
> I was thinking about what would happen when users call this method on a gpu sub-locale.
> Specifically, in the following case, I think it is more obvious that this call doesn't make sense: `here.gpus[0].numCpus();`

I don't think I'm understanding... Isn't the implication that the current name would be better then, because it's more general / less specific to the CPUs / non-GPU context?

> I don't think the above would be too much longer.

I agree it's not much longer, but it feels more involved.  I.e., slightly more typing and roundabout, and also a bit like "I want an int, but you're making me accept a full record only to drop all of it on the floor just to get the int out."  So it feels a bit expensive/overkill relative to just querying the int that I want.

I also feel as though—having programmed in Chapel for years now—we don't have a long list of fields about machine configuration that we want with any frequency, so much as a few key facts (# of CPUs, amount of memory) that we rely on pretty heavily.  Meaning I'm not sure what all else we'd put into the object representing the machine configuration and when we'd prefer to receive a big record of values back rather than a collection of routines that return singleton values (again, not to say we couldn't have both, but in practice I feel like I generally want one at a time when I want any at all).

**Comment by bradcray** [comment]
> iff the goal was for the method to return something useful when called on a gpu sub-locale (currently, it just returns zero).

I think we're in agreement that this would ideally return something other than zero for a GPU sub-locale.  It could be that it should return the number of SMs if we think that that's a good count of "processing units" on the GPU, or it may be that it should just return 1 if we don't want to think of the SMs as distinct/separate processing units for some reason (e.g., would want to discourage users from doing something like `coforall tid in 0..<here.numPUs()` on a GPU.  

>  but then the methods interface ... doesn't make a lot of sense, because logical and accessible don't really apply to the gpu (as far as I know).

Oh right, I meant to address this point, but forgot, sorry.  I think it would be reasonable to just say that there are locale types in which logical and physical are one and the same (i.e., there is no way to get a different logical view via hyperthreading or the like) and/or where nothing can change the amount of accessibility (e.g., the OS can't restrict you from getting some SMs) such that these arguments would still be valid, but would simply have no effect.  So they'd be extraneous, where the benefit would be a single routine with a single interface for both cases rather than distinct routines with different interfaces depending on the locale kind.

**Comment by jeremiah-corrado** [comment]
> I think it would be reasonable to just say that there are locale types in which logical and physical are one and the same ... such that these arguments would still be valid, but would simply have no effect.

Ok, that route makes sense. I'd be willing to drop the `hardwareSpec` idea, and just go with the `numPUs` -> `numPus` change. 

Pinging @stonea just in case he has anything to add (IIRC we had a brief offline discussion about this method returning a hardware-spec type rather than an int).

**Comment by stonea** [comment]
My concerns here are similiar to the `.id` field in that I'm not sure what this ought to mean for GPUs. Keeping `.id` and `numPUs` "as-is" might be the right thing to do just because of how much existing code (both in our standard modules and in client code) use it but if ignore any concerns I'd have about that I'd say:

Since I'm not sure what `numPUs` ought to mean for the GPU I'd rather we get rid of it, name it something else that makes it obvious it's referring to the specific locale the GPU is on, or move it to some other abstraction that is CPU specific.

In terms of having a `hardwareSpec` my suggestion would be to have some method like `loc.getHwInfo()` that returns some abstract base class that could be upcast into whatever the appropriate type for `loc` is.  So there'd be a `CpuHardwareSpec` with a `.numCores` field and a `GpuHardwareSpec` with a `.numSMs` field.

IOW you'd write code like this:

```chpl
          const spec : CpuHardwareSpec = here.hwSpec();
/* or: */ const spec = (CpuHardwareSpec)here.hwSpec();
/* or: */ const spec = new CpuHardwareSpec(here);
          writeln("num cores = ", spec.cores();
```

And it would be a runtime error if you tried to do this with a sublocale for a GPU.

Not that I think that's particularly pretty but having a `numPUs` method accessible on a locale where that might not make sense isn't particularly great either.  And this isn't just a problem for GPUs what if we had locales for things like FAM someday that really doesn't have a notion of "processing units".

Alternatively, maybe we could a CpuSpec accessible from all sublocales, so you could do something like this:

```
here.cpuSpec.numPus();
```

Or if you don't like the word spec:

```
here.cpu.numPus();
```

Though there since we already have a `.gpus` array I might expect that `.cpu` would return a locale.


- - -

Anyway I'm willing to defer to Brad's judgement on this if this isn't something that we could practically do without upsetting a lot of legacy code.

As far as a pattern like: `coforall tid in 0..<here.numPUs()` is concerned I can see this being a useful idiom but if in practice we're using `numPUs` to really mean something like "the number of tasks that should be spawned for a coforall" maybe we should come up with a name that better captures that.  Say something like: "numSuggestedCoforallTasks()".

**Comment by stonea** [comment]
> Isn't this essentially what locale.maxTaskPar does?

(taking a look at the documentation) I believe so.  Having it return 1 or the number of SMs for a GPU doesn't seem as bad to me.

Now I'm wondering in practice when `numPUs() != maxTaskPar`.

Grepping around our module and test code it does seem like `maxTaskPar` is more commonly used than `numPUs` and I'm wondering if some of the cases that do use `numPUs` really ought to be using `maxTaskPar` instead -- there are comments like `// TODO: here.numPUs() or here.maxTaskPar` that show up in a couple of places.

**Comment by jeremiah-corrado** [comment]
> Now I'm wondering in practice when numPUs() != maxTaskPar

Looking at the runtime code behind `maxTaskPar`:
 - for `qthreads` it appears to return the number of workers
 - for `fifo` it returns min(number of accessible physical cores, maximum number of threads)

So it seems like `maxTaskPar` would take OS and launch-configuration into account (i.e. if the number of available threads had been limited it would reflect that). 

Meaning that `maxTaskPar` is probably more useful for guiding task-creation, while `coforall tid on 0..<here.numPus()` is still a useful idiom for explicitly doing something on each physical cpu core.

**Comment by jeremiah-corrado** [comment]
Summary of yesterday's design re-review discussion:
---

Two distinct issues about this method were brought up yesterday:
1. The name, and how it relates to the naming convention for acronyms more broadly. Brad summarized some notes about that discussion here: https://github.com/chapel-lang/chapel/issues/20240#issuecomment-1224762182
2. The value/purpose of this method, and whether it should be stabilized, deprecated, or marked as unstable. I'll provide more details about that discussion here. (If we do decide to stabilize, then the naming discussion likely needs to be reconsidered, as disobeying the convention had quite a bit of support from the team).
___

Similar to the [concerns with `locale.id`](https://github.com/chapel-lang/chapel/issues/20217#issuecomment-1226349887), the `locale.numPUs` method works quite well as a convenience function on the flat locale model; however, as we consider the GPU sub-locales that are coming online (and other sub-locale types that might be added in the future), we considered whether this method makes sense to keep around in its current state. 

**Some points from the discussion, in favor of deprecation/destabilization:**
- We noted that this method was designed for a world where all locales have a clear notion of Processor Units (and one in which the methods arguments `logical` and `accessible` both apply). This is changing with GPUs.

    Stabilizing `numPUs` is not a major issue as we look forward to GPU support becoming stabilized, because the method could return the gpus SM count (and the two boolean arguments could be ignored) when called on a gpu sub-locale. It becomes more of a problem if something like a memory-based sub-locale is added, that does not have any notion of a Processor Unit. Again, this could be dealt with by implementing the `numPUs` method to return 0 for that sub-locale type. That being said, there was a general sentiment from some of the group, that these solutions feel like band-aids, and that it would be better to deprecate/destabilize this method and add a more general interface in the future (something like a locale.hardwareSpecs` method).

- We also noted that there are many cases where it makes more sense to use `locale.maxTaskPar` than `numPUs`. This indicates that deprecating `numPUs` might push programmers in the right direction wrt which method they should be using. 

I'll also note that those in favor of deprecating, did not seem keen on trying to design an alternative interface until we have a better handle on which types of sub-locales may need support in the future.

**Some points in favor of keeping/stabilizing `numPUs`:**

- We want to minimize churn for users. Removing this method may require a lot of code to be rewritten.
- Although `maxTaskPar` is an alternative, it provides less detailed information. I.e. you cannot query the number of physical vs logical cores, nor the accessible vs. inaccessible cores. Users may find some of this more specific information valuable, or they may dislike the general opacity of `maxTaskPar` where the current documentation states that "The value is an estimate by the runtime tasking layer".
- As stated above, `numPUs` is not strictly incompatible with gpu sub-locales or other sub-locale types. It's implementation simply needs to be adjusted for those types (i.e. returning the number of SMs for gpu sub-locales).

**Comment by jeremiah-corrado** [comment]
Deprecate `numPUs`

**Comment by jeremiah-corrado** [comment]
Mark `numPUs` as unstable

**Comment by jeremiah-corrado** [comment]
Keep `numPUs` (and discuss whether we should rename it, make an exception to the convention, etc)

**Comment by bradcray** [comment]
I prefer either marking it as unstable or stabilizing it because even if "`maxTaskPar` is the thing users typically should use", to say "if you want to reason about the hardware you're running on, the only way to do that in Chapel is by making C or system calls",  that doesn't feel productive to me.  Locales form a very nice and natural way of reasoning about hardware capabilities that fits reasonably naturally into the language given that we need to have ways to talk about locality anyway.  For this specific question, we've got a reasonably productive solution, and put effort into designing and implementing it.  To say to users "you just can't do that anymore" feels like a step in the wrong direction to me, and if it's motivated primarily by an inability to resolve the identifier we prefer with the (freshly minted, now being battle-tested) capitalization rules, that feels like a cop-out of a reason to me (which is to say, what are we going to do when we hit a capability with a similar naming pattern that is essential and can't be thrown out?).

To me, marking it unstable is a reasonable way of kicking this can down the road, and I'm OK with that, but I don't think we should pretend the question of naming is somehow resolved just because we take that action.  Put another way, let's say that the routine had been named `numPus` all along and fit the naming convention.  Would we really be talking about deprecating this?  I'm not convinced.

> this method was designed for a world where all locales have a clear notion of Processor Units

I'm not sure I agree with that.  If we'd intended for it to only work for multicore CPUs, I believe we would've just called it `numCores()` or something like that.  The term 'processing units' and abbreviation 'PUs' came about because we wanted a more general term that could apply to more diverse situations (where Jeremy gives plausible interpretations for some of those situations above).

**Comment by jeremiah-corrado** [comment]
> To me, marking it unstable is a reasonable way of kicking this can down the road, and I'm OK with that, but I don't think we should pretend the question of naming is somehow resolved just because we take that action

Good point. I updated the voting to include that.

**Comment by jeremiah-corrado** [comment]
It looks like most people are in favor of marking `locale.numPUs` as unstable. I'll send out one more reminder about the poll, and then wait until tomorrow morning before moving on to the naming question (i.e. should we keep the name the same or change it to `numPus`. If we keep it the same, should this just be an exception to the convention, or should we amend the convention s.t. numPUs is legal).

**Comment by ronawho** [comment]
>> this method was designed for a world where all locales have a clear notion of Processor Units

> I'm not sure I agree with that. If we'd intended for it to only work for multicore CPUs, I believe we would've just called it numCores() or something like that. The term 'processing units' and abbreviation 'PUs' came about because we wanted a more general term that could apply to more diverse situations (where Jeremiah gives plausible interpretations for some of those situations above).

Right, I think we intentionally tried to come up with a general term here and in fact it used to be called `numCores()`. This was changed back in 1.13. https://chapel-lang.org/releaseNotes/1.13/01-language.pdf slide 52 notes the change, but there aren't may details and unfortunately this predates our use of github issues and I wasn't able to find any old email threads in a quick search.

**Comment by mstrout** [comment]
I recommend we stabilize `numPUs` and then start a list of methods that are exceptions to the naming policy and put `numPUs` on there.

**Comment by ronawho** [comment]
I thought we're talking about not stabilizing because we're not sure what we want the interface to look like longer term, and that happens to get us out of finalizing any naming policies. I don't think we're talking about not stabilizing just because we don't want to figure out the names.

**Comment by jeremiah-corrado** [comment]
> Right, I think we intentionally tried to come up with a general term here and in fact it used to be called numCores(). This was changed back in 1.13. 

Yeah my bad. I didn't mean to mischaracterize the design or naming choice. My broader point was that an even more general design--included at some point in the future--would be nice for things like `FAM` locales (or even to query more detailed data about a `GPU`s architecture if it's available).

> I thought we're talking about not stabilizing because we're not sure what we want the interface to look like longer term, and that happens to get us out of finalizing any naming policies. I don't think we're talking about not stabilizing just because we don't want to figure out the names.

Yeah that's correct. The idea of marking `numPUs` as unstable is motivated by the interface design not the name of the method. 

> ...start a list of methods that are exceptions to the naming policy and put numPUs on there.

Regardless, I think this sounds like a reasonable way of dealing with the naming question if we do decide to stick with`numPUs`. This exceptions-list could live on the same docs page as the rules themselves. The alternative is to update the rules to make `numPUs` legal. (Brad gave a list of possible rule changes here: https://github.com/chapel-lang/chapel/issues/20240#issuecomment-1224762182)

**Comment by lydia-duncan** [comment]
I'm still in favor of marking numPUs as unstable, but if we do stabilize it with this name, I think it's reasonable to just list it as an exception to the naming policy.  If we get five or more such exceptions, then I think it is necessary to start thinking about if a different rule or a subrule is necessary to return us to less than five exceptions, but this individual case does not make me concerned that we've made the wrong decision there

**Comment by jeremiah-corrado** [comment]
No rush on this, but I'd like to take a poll to see how people are feeling about the `numPUs` naming exception. There are two avenues we could take to justify keeping `numPUs` as is in spite of the convention:

1. 🚀 Simply list it as an exception to the rule (probably [here](https://chapel-lang.org/docs/developer/bestPractices/StandardModuleStyle.html))
2. 🎉 Update the rules to allow names like `numPUs`. (For example, allowing fully capitalized acronyms if they are plural). If we do choose this option, there will need to be more discussion to land on a specific amendment to the rules.

**Comment by bradcray** [comment]
Clarifying my vote for updating the rules rather than simply listing it as an exception:  The reason I voted that way was that I suspect there will be other identifiers that will similarly cause us to say "that should be an exception as well" for similar reasons.   In 10 years I wouldn't want for us to have a long list of exceptions if we could come up with a rule that described what it was about these cases that seemed exceptional to us (e.g., short acronym, plural acronym, end-of-identifier acronym, reads-as-an-English-word-acronym).

That said, I'd also be OK with making it an exception for the time being until we have a collection of such exceptions and decide which rule(s) we'd want to add to the current proposal to cover them rather than picking one or more of the four proposals above (say) before we have enough data to feel confident in it.  So, put another way, if there were an option "list it as an exception for now, but strive to find rules that would cover it [and other exceptions we encounter along the way]" I would happily vote for that option as well (and might even prefer it because I'm lazy).

**Comment by mppf** [comment]
I don't have any strong opinion on the above poll, but I also don't think we would necessarily even need to include `numPUs` as an exception in `StandardModuleStyle.rst`. That document starts with this:

> This document describes general guidance for style when writing a standard module. Of course, there will be exceptions to this guidance when there is a good reason.

I think that we should be comfortable making exceptions to the style guide when they make sense. I do not think we should try to update the style guide every time we do that. (At the same time, it might be useful to track exceptions somewhere, for the purpose of deciding if we want to clarify the style guide or make some adjustment to it. Perhaps we could do that in the style guide itself, but GitHub issues seem like a better place to me).

**Comment by dlongnecke-cray** [comment]
I voted for deprecating `numPUs` and then introducing a replacement called `numProcessingUnits`. I don't see a need for updating the rules, as I think the existing name isn't very understandable in the first place. Similarly, I don't think marking it unstable is the right thing to do, because that just punts the decision further down the road and increases the likelihood that `numPUs` sticks around.

**Comment by jeremiah-corrado** [comment]
> I think that we should be comfortable making exceptions to the style guide when they make sense. I do not think we should try to update the style guide every time we do that.

Thats a good point. I've updated the poll to include that option.

> Similarly, I don't think marking it unstable is the right thing to do, because that just punts the decision further down the road and increases the likelihood that `numPUs` sticks around.

I'm not sure if I'm repeating something you already knew/read above, but the decision to mark `numPUs` as unstable was independent of the acronym-capitalization question. It was marked as unstable because we will likely want to come up with a different `locale.hardwareSpecs` interface in the future that is designed around a wider range of locale/sub-locale types. So I think the idea was to intentionally punt it down the road s.t. we could decide whether to design the newer interface, and then base it around a more mature gpu-sub-locale design (and potentially some other sub-locale types).

**Comment by bradcray** [comment]
> we will likely want to come up with a different locale.hardwareSpecs interface in the future that is designed around a wider range of locale/sub-locale types.

FWIW, I don't personally believe this.  I think users will always find utility in having a variety of standalone queries to get access to various specific pieces of information when they want them rather than—or in addition to—a monolithiic "tell me everything" query that then requires them to pick information out of it field-by-field or method-by-method (either of which essentially becomes the equivalent naming problem to supporting the standalone queries themselves).  That's not to say that we can't or won't support a "tell me everything about the HW" type of query, just that I don't think it'll make the desire for, or utility of, standalone routines go away given their greater simplicity and efficiency (e.g., the routine doesn't have to build up a big record just so I can pluck out the one integer from it that I actually care about).  I think such an approach feels seductive because it seems like it can answer all possible questions due to its nebulous nature ("What's in there?"  "Well, everything!"). 
 But I think that's a false sense of security.

**Comment by jeremiah-corrado** [comment]
I hesitate to get too deep into this conversation, because the mark-numPUs-as-unstable move was meant to delay it, but I figure it can't hurt to get some of my thoughts down (plus I already typed them):

> we will ~~likely~~ (should have said **potentially**) want to come up with a different locale.hardwareSpecs interface in the future that is designed around a wider range of locale/sub-locale types.
>> FWIW, I don't personally believe this. I think users will always find utility in having a variety of standalone queries to get access to various specific pieces of information when they want them...

I agree with this principle; however, I think we might disagree slightly about what role the locale type is playing in those hardware queries... 

In other words `symbol_representing_my_hardware.numPUs()` makes sense to me. But I don't think `here` represents the hardware as directly as it used to (mainly due to progress on gpu-sub-locales and on one-locale-per-socket configurations). Instead, something like: `here.hardware.numPUs()` matches more closely with the conceptual model I have in my head ( i.e. *symbol representing the enclosing on-block* -> *abstraction over the unit of hardware it's tied to* -> *query about that hardware* ). 

> ... greater simplicity and efficiency (e.g., the routine doesn't have to build up a big record just so I can pluck out the one integer from it that I actually care about)

I think the record/Class could just be a field on the `locale` type that gets populated upon initialization, and `here.hardware` (or whatever name we use) would provide a reference to it.

**Comment by dlongnecke-cray** [comment]
Yeah I mean if we don't know what we want to do with `numPUs` in the first place as far as how it fits into the overall API then we should obviously mark it as unstable. So I'd say I'm against stabilizing it with the name `numPUs`, but anything else is OK with me (though it seems like a bunch of unknowns at this point).

**Comment by jeremiah-corrado** [comment]
Resolved by: https://github.com/chapel-lang/chapel/pull/20699

**Comment by jeremiah-corrado** [comment]
Resolved by: https://github.com/chapel-lang/chapel/pull/20699
