### ISSUE TITLE
Should compiler-generated assignment use field accessors?

### ISSUE THREAD

**Issue by benharsh** [chapel-lang/chapel#20472]
Consider the following program:

```chpl

record R {
  var x : int;

  proc x ref {
    writeln("R.x accessor");
    return x;
  }
}

proc main() {
  var a = new R(5);
  var b = new R(10);
  writeln("-----");
  a = b;
  writeln("-----");
  writeln(a);
  writeln(b);
}
```

This program currently prints:
```
-----
-----
(x = 10)
(x = 10)
```

Should a user expect their field accessor to be invoked by the compiler-generated ``=`` operator overload?

The user-defined version might look like this:
```chpl
// Can add these at the end of the previous chpl snippet
operator R.=(ref lhs : R, rhs : R) {
  lhs.x = rhs.x;
}

// Must implement `init=` if `=` is also implemented
proc R.init=(other:R) {
  this.x = other.x;
}
```

With these additions the program outputs:
```chpl
-----
R.x accessor
R.x accessor
-----
(x = 10)
(x = 10)
```

Is there a situation in which we wouldn't want to invoke the user-defined field accessor?

Is it concerning that the compiler is generating code that users cannot write themselves?

**Comment by bradcray** [comment]
I'm actually surprised that we permit the user to create a field and a method with the same name.  I would've expected the same behavior as:

```chapel
var x: int;

proc x: real {
  return 1.2;
}

writeln(x);
```

which is:

```
testit.chpl:1: error: 'x' has multiple definitions, redefined at:
  testit.chpl:3
```

If the field in your program were named `_x` (say) and the accessor was updated to refer to that, would that make things work more consistently?  (I'd guess/hope so?)

This issue is _vaguely_ related (in the sense that I found myself trying to remember whether it was this identical case or not—but searching for it, I'd say "not").

**Comment by benharsh** [comment]
I think we specifically allow for this according to the spec: https://chapel-lang.org/docs/language/spec/classes.html#variable-getter-methods

> If the field in your program were named _x (say) and the accessor was updated to refer to that, would that make things work more consistently? (I'd guess/hope so?)

I'm not sure what you mean by this. The ``R.=`` function I wrote will call my user-defined getter method for ``x``. It's the compiler-generated ``R.=`` that will not call my user-defined getter.

> This issue is vaguely related (in the sense that I found myself trying to remember whether it was this identical case or not—but searching for it, I'd say "not").

I think you meant to include a link here.

FWIW, it appears that the comparison operator implementations will invoke a user-defined accessor if one is present.

**Comment by bradcray** [comment]
> I think we specifically allow for this according to the spec

Oh, interesting...  (and also: "bummer"... in that I don't know that I'd make this same decision today...  it seems like a pretty confusing pattern.  Did you come across this by finding uses of it in user code?  Were they compelling?).

> I'm not sure what you mean by this. 

Hmm... yeah me neither anymore.  Let's pretend I didn't say it.

> I think you meant to include a link here.

Fixed that, thanks.

**Comment by benharsh** [comment]
> Oh, interesting... (and also: "bummer"... in that I don't know that I'd make this same decision today... it seems like a pretty confusing pattern. Did you come across this by finding uses of it in user code? Were they compelling?).

I came across this in the context of looking into default functions. The compiler currently generates these field getter/setter methods by default, and I wondered if the other generated functions would resolve any user-defined overrides - leading to the question posed by this issue.

I don't recall the history of this feature, but it looks like it's been around for quite a while (at least 2012, if I'm navigating git correctly). Other languages deal with the notion of getter/setter methods for fields, but don't necessarily do it in the same way as us. I think C# might be closest. As far as I know, Rust and C++ use a differently-named field from the methods used to 'access' that field.

For some reason this functionality has stuck around in my brain as something I _could_ do if needed, but I don't know whether we actually rely on this anywhere. It occurs to me that this functionality could cause some complications with resolving initializers, in which we really need to be able to tell when a field is used.

I could try and come up with a modification to the compiler that at least warns for such cases, and see what that exposes in our testing system?

**Comment by lydia-duncan** [comment]
Brad, didn't we talk about making accessors start with things like `get` and `set` as part of language stabilization?  Iirc people were pretty against doing that and preferred using the name of the field

**Comment by bradcray** [comment]
>  it looks like it's been around for quite a while (at least 2012, if I'm navigating git correctly)

I suspect it's probably been since the dawn of the project, and I rarely forget that the compiler implements fields using this approach.  But I tend to think of that feature as being special to the compiler in some way rather than something exposed to the user.  And specifically, I would've expected a user wanting to make a field with a getter and setter either use paren-less functions referring to a field of a different name as Ben suggests here:

> As far as I know, Rust and C++ use a differently-named field from the methods used to 'access' that field.

...or to use some sort of named routine with parens that accepts the value to set to in order to check it before assigning (e.g., "is the age within a reasonable range before I store it into the 'age' field?"  Note that the feature as it exists wouldn't really permit that pattern since it returns a ref rather than taking an argument...  which also makes it reminiscent of Michael's pattern-matching ideas that he's been kicking around on https://github.com/chapel-lang/chapel/issues/17999#issuecomment-976579379).

> I think C# might be closest.

We were modeling pretty heavily off of C# in those early days, so it wouldn't be surprising if we took this cue from them.

The aspect of the status quo that is distasteful to me is the implication that there are multiple "conflicting" definitions of a given symbol in a single scope; where my typical instinct is that within a single scope a given identifier can either be (a) a variable/field, (b) a group of paren-ful overloads, (c) a group of paren-less overloads (where they'd have to differ by where-clause or return intent to not be ambiguous).

> I could try and come up with a modification to the compiler that at least warns for such cases, and see what that exposes in our testing system?

I'd be curious about that experiment if it's not much work (and particularly if you have similar misgivings that we may not be in a good place here, like with your comment about resolving initializers).

> Brad, didn't we talk about making accessors start with things like get and set as part of language stabilization? Iirc people were pretty against doing that and preferred using the name of the field

I'm not a big fan of get/set as a language-endorsed convention for sure, though if users want to use that convention (e.g., in my "checked age setter" example above), I wouldn't stop them either.  So could imagine that outcome, though I don't remember the specific conversation w.r.t. 2.0 offhand.  Just to make it concrete, what I'm imagining is that a user would create a virtual field via methods using:

```chapel
class C {
  var _x;  // would ultimately want this to be `private var _x;`
  proc x ref { return _x; }
  // and maybe also: proc x { return _x; }
}
```

where I'd imagine that the compiler-introduced setters/getters would either rename the field or simply be a special case that didn't trigger a "incompatible definitions of 'x' within a single scope"-style error.

(I also think that—because the setters don't take the RHS—this feature isn't actually all that useful or powerful.  Even the example in the language spec suggests its limitations by just bumping a counter rather than anything more sophisticated... because there's not much sophisticated that you can do?).

**Comment by bradcray** [comment]
One more note:  I believe the reason that we chose to have the compiler introduce getters/setters like this for users' fields was for the sake of "making every `x.y` pattern a method call" rather than having to handle method calls vs. field accesses differently (?).  Given our compilation times and AST bloat, I've definitely wondered at times how much time/memory we'd save if we'd just taught the compiler how to resolve fields rather than introducing these routines for each field.  I suppose dyno could be an opportunity to explore that?

**Comment by mppf** [comment]
@benharsh - you might want to look at the PR message for https://github.com/chapel-lang/chapel/pull/19505 and be aware of issue https://github.com/chapel-lang/chapel/issues/19474 which it resolves. The reason that I bring these up is that there was some discussion about the purpose of the feature. I would summarize my own understanding after that discussion as "Parenless procs should allow a user to replace a field with something else, to keep code using the type working as it was without modification". I do not think that this purpose for parenless procs justifies in any way having a field and parenless proc of the same name. I think it is reasonable to require users wishing for that pattern to rename their field.

**Comment by benharsh** [comment]
I've opened the following issue to track the discussion about user-defined field-accessors in general: https://github.com/chapel-lang/chapel/issues/20509

I think we can leave this current issue concerning compiler-generated usage of those field-accessors alone until we reach a decision about the feature.

**Comment by benharsh** [comment]
Issue #20509 concluded with the decision to consider such paren-less methods as re-declarations of the field, which would result in an error at compile time. PR #22917 implemented this error, which means that the question posed by this issue is moot.
