### ISSUE TITLE
Update openUrlReader and openUrlWriter to use region argument instead of start and end

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#20527]
`openUrlReader` and `openUrlWriter` follow a similar pattern to `file.reader` and friends in terms of their arguments.  #20475 updates `file.reader` and friends to use a `region` argument instead of `start` and `end` arguments and these functions in the `URL` module were adjusted to call the more stable versions.  However, it would make sense for them to also update their interface, both to stay in sync with their counterparts and because Chapel's `range` type is a more natural interface to use to indicate regions of a webpage.

#20475 did not take this on because the `URL` module is not intended to be stabilized for Chapel 2.0, but I anticipate this being an easy change to make

**Comment by Guillaume-Helbecque** [comment]
I created PR #22907 to fix this issue. I successfully test the depreciation messages as well as the use of `region` in `openUrlReader`, but I've no idea how to test `openUrlWriter`. I never use local servers etc before. 
Do you know how to proceed?

**Comment by lydia-duncan** [comment]
Unfortunately, I think making a nightly test for `openUrlWriter`'s actual functionality will be difficult.  The two that we have in our testing system are not set up to run nightly because our internal infrastructure is not set up for it yet.  It's part of why the module is a package module instead of a standard one - it's difficult to fully test its functionality and ensure that what is provided continues to work.

@mppf - as someone involved with the creation of the module, do you have any tips about testing that portion of the Curl module locally to ensure it works?

**Comment by mppf** [comment]
The easy thing to do would be to change upload-ftp and download-http-upload-ftp to compile but not run, instead of not being tested at all. That can be done by renaming upload-ftp.notest to upload-ftp.noexec and similarly for download-http-upload-ftp. @Guillaume-Helbecque - I recommend you fold that change into your PR & potentially add other testing of `openUrlWriter` that simply checks if the code compiles.

In the past, I've tested these with a local server configured with FTPD, but we wouldn't want to do that in nightly testing. We could instead set up a container for this testing; or, alternatively, use some other technique to create a local server that the tests can write to (for example, it might be relatively easy to use Python libraries to start a web server that accepts POST requests). I think we should view these as separate efforts for the issue here and the PR.

**Comment by Guillaume-Helbecque** [comment]
Thank you both for the support on this PR! I just updated it.
