### ISSUE TITLE
How to handle unstable warnings triggered in the provided modules?

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#20541]
Users should not be troubled by things that are outside their control, and an unstable warning for a use of an unstable symbol in our library code (e.g. if the IO module uses an unstable symbol from the Range module or something) is something they don't have control over.  However, since unstable symbols don't have an obvious replacement, it is not as easy for a developer to remove such uses.  It seems fraught to merely ignore such warnings, but perhaps it is okay since developers will be able to perform updates when the unstable symbol is converted to its final form.  Something needs to be done in the meanwhile, the question is: what should be done?

I currently favor:
- turning it off with `--warn-unstable`
- and adding a new flag to ensure we still see those messages, e.g. `--warn-unstable-devel` or something
- and adding a job to test the test suite with that flag nightly

Other ideas?

**Comment by bradcray** [comment]
I could definitely imagine having `--warn-unstable` squash warnings for uses in the `modules/` hierarchy unless `CHPL_DEVELOPER` was set.

**Comment by mppf** [comment]
I think I'd like `--warn-unstable` to squash warnings for uses in the `modules/` directories but I'm not so sure it makes sense to tie it to `CHPL_DEVELOPER`. (I am just worried about trying to reproduce a problem and having `CHPL_DEVELOPER` set and getting lots of unstable warnings that are neither here nor there).

**Comment by vasslitvinov** [comment]
I do not see that we need `--warn-unstable-devel`. Historically, whenever we have changed something in the modules, we have adjusted all our uses of it, as part of ensuring that paratest passes.

**Comment by stonea** [comment]
I think what this issue is proposing to do (turn off reporting unstable warnings originating from within our internal and standard module code) is the right thing to do.

Just a heads up ---

One possible wrinkle with this has to do with how we're informing users that GPU support is unstable. Currently we produce a warning when the `LocaleModel` module gets implicitly pulled in (when using `CHPL_LOCALE_MODEL=gpu`):

https://github.com/chapel-lang/chapel/blob/c37e544829801168a5ee99479528a672a5909170/modules/internal/localeModels/gpu/LocaleModel.chpl#L30

I'm not 100% sure but I'm guessing turning off internally produced unstable warnings might inadvertently turn this one off. I'd like that warning to stay (until we stabilize GPU support that is). I'd be fine placing the warning somewhere else or using something other than `@unstable` to trigger it if that would help.

It looks like we do have a test that's locking down the presence of this message with `--warn-unstable` for GPUs so if this does change we'll know: https://github.com/chapel-lang/chapel/blob/main/test/gpu/native/jacobi/flags-warn-unstable.good

**Comment by bradcray** [comment]
> I'm not 100% sure but I'm guessing turning off internally produced unstable warnings might inadvertently turn this one off.

We could just make it a normal compiler warning?  Or we could have the compiler generate this warning when `--warn-unstable` is on when its populating its understanding of the `CHPL_` environment variables.  Or we could continue to generate unstable warnings on modules themselves and only squash warnings on their contents.

**Comment by lydia-duncan** [comment]
The warning Andy is referring to is currently generated by the use of `LocaleModel` in `ChapelStandard` and `ChapelLocale`.  So would still be handled by squashing the warning for their contents

**Comment by lydia-duncan** [comment]
I'm not hearing anyone arguing against turning off these warnings (aside from the GPU LocaleModel warning).  If someone feels like that is a bad idea, they definitely should feel empowered to speak up, but for now I'm going to proceed as if that is the conclusion.

To me, the question remaining is: should we maintain these warnings via a developer flag?  Please react to this message with your preference:
👍🏻 - yes, add a developer flag
👎🏻 - no, we'll just update these uses later, we should just suppress them for now

**Comment by bradcray** [comment]
I don't feel as though the first draft of this needs to have a developer flag to re-enable these, though I could imagine it being helpful later on if we're trying to weed out a bunch of unstable warnings.  Or, maybe not even then, since if/when we change something that's unstable, we should catch any impacts on our own code in testing.  It's that uncertainty that makes me think "let's add it when we want it."  (or just make it trigger off the `--devel` flag, which still appeals to me... I hear what Michael's saying, but given how rarely I think anyone uses the `--warn-unstable` flag, it doesn't feel like a big concern for me, at least in a first draft.  And when I'm reproducing a user's error, I'll typically add `--no-devel` anyway).

All that said, it's not like it's particularly hard to add such developer flags...   Probably updating the bash autocomplete script is the worst part.

**Comment by dlongnecke-cray** [comment]
Do we really not care for a way to turn unstable warnings back on in internal/standard modules? It seems like a nice way to periodically do bookkeeping for ourselves. I imagine we could just have `--warn-unstable-standard` and `--warn-unstable-internal` that are off by default. They would not have to be user facing.

**Comment by bradcray** [comment]
I don't read anything in the conversation so far as saying "We don't [ever] want this."  Simply "It doesn't seem crucial and doesn't need to preclude making progress on turning them off by default."

**Comment by dlongnecke-cray** [comment]
Thanks Brad. Didn't mean to sound unnecessarily confrontational here, and I've admittedly lost the thread a little bit. I was just led to believe otherwise and I've halfway implemented the feature.

**Comment by dlongnecke-cray** [comment]
I've just merged #22033 which is the first part of this effort. The next step is to suppress unstable warnings for language features in internal/standard modules as well.

**Comment by lydia-duncan** [comment]
I believe this is fully resolved now, closing
