### ISSUE TITLE
When should shadowing occur for operator functions and methods?

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#20540]
### Summary of Problem

Before PR #20528, operators had the following shadowing behavior:
 * if an operator method shadows an operator method, ambiguity
 * if a non-method operator shadows an operator method, ambiguity
 * if an operator method shadows an non-method operator, ambiguity
 * if an non-method operator shadows an non-method operator, the inner one is chosen

After PR #20528, that behavior changes to choosing the closer one in all of the above cases.

Note that in #19306 we went with the design that methods aren't subject to shadowing at all (see also issue #19352). However, operators are strange because the same call can resolve to a method and to a non-method. As a result, we have to decide what happens when these are mixed.

Which behavior is the behavior we want?

### Steps to Reproduce

**Source Code:**

```chapel
// shadowing-nonmethod-method.chpl
module Library {

  record R { var x: int; }

  operator +(a: R, b: R) { 
    writeln("in Library plus");
    return new R(a.x + b.x);
  }
}

module Variant {
  import Library.R;

  operator R.+(a: R, b: R) {
    writeln("in Variant plus");
    return new R(a.x + b.x);
  }
}

module Main {
  use Library;

  proc main() {
    use Variant;

    var x = new R(1);
    var y = new R(2);
    var z = x + y;

    assert(z.x == 3);
  }
}

```

Before PR #20528: ambiguity. After: `in Variant plus`.

**Associated ~Future~ Test(s):**
[`test/functions/operatorOverloads/shadowing-*`](
           https://github.com/chapel-lang/chapel/blob/main/test/functions/operatorOverloads/shadowing-method-method.chpl ) #20528

**Comment by benharsh** [comment]
If we decided that we would only support operators on types that were defined in the same module as the type itself, would that decision render this topic moot?

**Comment by lydia-duncan** [comment]
I think we'd have to be very careful that that rule does not exclude things like:
```chapel
operator +(lhs: R, rhs: int) { ... }
```

**Comment by lydia-duncan** [comment]
I'd need to think more about if I'm okay with it after that addendum

**Comment by mppf** [comment]
I've updated the OP to say a bit about the related decision for non-operator methods.

**Comment by bradcray** [comment]
> If we decided that we would only support operators on types that were defined in the same module as the type itself, would that decision render this topic moot?

@benharsh : Would that prevent me from being able to define an operator combining two types that are defined by distinct library modules that I don't own?  (e.g., `operator +(b: BensType, l: LydiasType)`?  Or would it only preclude me from defining this as a method like BensType.+ or LydiasType.+?)

**Comment by benharsh** [comment]
@bradcray : I believe I've only heard of this in the context of operator signatures that the compiler would otherwise provide because they are especially relevant to the behavior of the type (e.g. the assignment operator). I'm not sure what should happen for operators involving types that the ``BensType`` module couldn't know about.

Also, it wasn't my intention to derail this issue concerning shadowing with a potentially-separate question. Should a new issue be created to act as a dependency for this issue?

**Comment by bradcray** [comment]
> I believe I've only heard of this in the context of operator signatures that the compiler would otherwise provide because they are especially relevant to the behavior of the type (e.g. the assignment operator).

We definitely have been discussing not permitting tertiary operator methods to be defined by users for operators that the compiler will provide default implementations for (and it's an idea I'm in favor of).  I haven't interpreted that discussion as prohibiting operators from being defined outside of a type's module in general, and feel wary about that due to the potential utility of cross-type operators.  And as a result, I didn't interpret this issue as being related to that discussion since it focused on `+` as an example and the compiler doesn't generate default `+` methods (I believe).

I also didn't interpret your question as derailing necessarily.  But I do worry that it'd be overly restrictive.

**Comment by lydia-duncan** [comment]
I think we're in better shape on this than we were, is it okay to close it?

**Comment by mppf** [comment]
Right, we concluded that the example in this issue should result in an ambiguity error and PR # #22917 implemented that and updated the test. I'll close it.
