### ISSUE TITLE
What should negating a uint(32) do?

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#20629]
This issue asks what negating a `uint` or a `uint(32)` should do. Note that these two are currently arguably inconsistent and the `uint(32)` behavior might be surprising in that it brings in a larger width type that the user has not been using.

``` chapel
var myUint: uint;
var negMyUint = -myUint; // error: illegal use of '-' on operand of type uint(64)
writeln("negMyUint = ", negMyUint, " : ", negMyUint.type:string);
```

``` chapel
var myUint32: uint(32);
var negMyUint32 = -myUint32;
writeln("negMyUint32 = ", negMyUint32, " : ", negMyUint32.type:string);
// outputs:
//  negMyUint32 = 0 : int(64)
```

The above behaviors are the same in 1.27 as well as after PR #20528 was merged. However, now that `int` to `uint` implicit conversions are allowed, these behaviors seem less defensible.

The compilation error comes from an error overload in ChapelBase:
``` chapel
inline operator -(a: uint(64)) { compilerError("illegal use of '-' on operand of type ", a.type:string); }
```

It seems likely that adjusting this overload (possibly with `uint(?w)`) will allow whatever behavior we desire here. Perhaps such adjustments were not possible before PR #20528. In any case once we have a direction here we will need to demonstrate that it can work smoothly with the current disambiguation rules from PR #20528.

**Comment by bradcray** [comment]
What do C/C++/C# do in these cases?

Do smaller uint widths have an effect similar to the uint32 case, bumping up to the next integer size?

Given the current theme of our changes that "working at smaller bit-widths should preserve those widths without requiring constant down-casting", it seems like our two main options would be to have `-uint32` result in int32 and `-uint64` result in `int64`, or to simply not support the operation?

**Comment by mppf** [comment]
> What do C/C++/C# do in these cases?

C++ produces the unsigned type of the same width (same as input, so `-myUint32` is a `uint(32)`).

<details>

``` c++
#include <cinttypes>
#include <cstdio>

const char* tname(int8_t x)  { return "int8_t"; }
const char* tname(int16_t x) { return "int16_t"; }
const char* tname(int32_t x) { return "int32_t"; }
const char* tname(int64_t x) { return "int64_t"; }

const char* tname(uint8_t x)  { return "uint8_t"; }
const char* tname(uint16_t x) { return "uint16_t"; }
const char* tname(uint32_t x) { return "uint32_t"; }
const char* tname(uint64_t x) { return "uint64_t"; }

const char* tname(float x)  { return "float"; }
const char* tname(double x) { return "double"; }

int main() {
  uint64_t myUint64 = 1;
  auto negMyUint64 = -myUint64;
  printf("-myUint64 = %lx : %s\n", negMyUint64, tname(negMyUint64));
  uint32_t myUint32 = 1;
  auto negMyUint32 = -myUint32;
  printf("-myUint32 = %x : %s\n", negMyUint32, tname(negMyUint32));
  return 0;
}
```

```
-myUint64 = ffffffffffffffff : uint64_t
-myUint32 = ffffffff : uint32_t
```

</details>

C# generates an error for `-myUint64` and has `-myUint32` produce an `int(64)`.

<details>

``` c#
// to run this on linux
// sudo apt-get install mono-complete

// mcs -out:testneg.exe testneg.cs
// mono testneg.exe

 // csharp numeric types
 // sbyte byte short ushort int uint long ulong nint nuint
 // float double decimal

 // ignoring decimal, nint, nuint since Chapel does not have these

using System;

class testneg {
  static void Main() {
    uint myUint32 = 0;

    Console.WriteLine("-myUint32");
    Console.WriteLine(-myUint32);
    Console.WriteLine((-myUint32).GetType().ToString());


    //ulong myUint64 = 0;
    //Console.WriteLine("-myUint64");
    //Console.WriteLine(-myUint32);
    //Console.WriteLine((-myUint64).GetType().ToString());
    //error CS0023: The `-' operator cannot be applied to operand of type `ulong'

  }
}
```

```
-myUint32
0
System.Int64
```

</details>

**Comment by mppf** [comment]
> Given the current theme of our changes that "working at smaller bit-widths should preserve those widths without requiring constant down-casting", it seems like our two main options would be to have `-uint32` result in int32 and `-uint64` result in `int64`, or to simply not support the operation?

Yes, I agree. I think we should pick one of those two, where I view the current situation as a mix of the two (which is the same situation as C#).

**Comment by bradcray** [comment]
Oh, I hadn't even thought of the C++ approach...  I suppose that's an option as well, though I don't find it particularly appealing (e.g., I think I'd make all negative uints last resort errors before doing that).  Arguably the C# approach is what we have traditionally done, but would no longer want to do with our new "preserve low bit-widths" hats on.

Also, in case this question wasn't clear:

> Do smaller uint widths have an effect similar to the uint32 case, bumping up to the next integer size?

This was asking about Chapel rather than C/C++/C# (though that may not have been clear).  And I was wondering whether this issue is specific to uint(32)/(64) in some way, or whether uint(32) is a stand-in for uint(8), uint(16) and that all three behave similarly (which is what I'm guessing).

**Comment by mppf** [comment]
> Also, in case this question wasn't clear:
> 
> > Do smaller uint widths have an effect similar to the uint32 case, bumping up to the next integer size?
> 
> This was asking about Chapel rather than C/C++/C# (though that may not have been clear). And I was wondering whether this issue is specific to uint(32)/(64) in some way, or whether uint(32) is a stand-in for uint(8), uint(16) and that all three behave similarly (which is what I'm guessing).

I think I just forgot to answer that question. Yes, it bumps up to the next width, so `-myUint16` produces an `int(32)`.

<details>

``` chapel
var myUint16: uint(16);
var negUint16 = -myUint16;
writeln("negUint16 = ", negUint16, " : ", negUint16.type:string);
```

</details>

**Comment by bradcray** [comment]
I've been keeping this tab open to see if I'd get any further clarity on it, and mostly haven't.  I still like the two options I initially proposed best (-uint(w) => int(w) or simply don't support the operations).  This might be a case where we want to poll the users to get more data.  Or we could decide to make it an error on the argument that we can relax the error later without breaking code if people want it.

**Comment by mppf** [comment]
> Or we could decide to make it an error on the argument that we can relax the error later without breaking code if people want it.

This might be the best move, for now. 

A related puzzle is that we currently have this:

https://github.com/chapel-lang/chapel/blob/4848643f775e52f0d4b7779bc8136d2f6ccaa8f1/modules/internal/ChapelBase.chpl#L250-L255

If I am reading it right, it means that you can do `param p = (-1):uint; writeln(-p);` without facing the error, but I'm having trouble understanding why that makes any sense.

**Comment by mppf** [comment]
I ran testing with these unary `-` on `uint(w)` being an error. I only saw these failures:

```
[Error matching compiler output for domains/sungeun/rect/expand]
[Error matching compiler output for domains/sungeun/rect/exterior]
[Error matching compiler output for domains/sungeun/rect/interior]
[Error matching compiler output for domains/sungeun/rect/translate]
[Error matching compiler output for functions/diten/unary_uint64_param_minus]
[Error matching compiler output for trivial/deitz/integers/negate_uint32]
[Error matching compiler output for visibility/except/operatorsExceptions/exceptNegation]
```

**Comment by bradcray** [comment]
> A related puzzle is that we currently have this:

Yeah, that definitely seems odd/random.  Reading the commit message, it looks like the intention was to return an `int(64)` with the negated value if the negation of the unsigned value fit into it.  So maybe the conditional should've been something like `if a < max(int) +/- 1`?

I'd remove it along with this effort, I think (ah, looks like you did on your branch).  I suppose it could be argued that since it's a param value, and it can be legally negated and stored in an `int(64)`, why not do that?  But I think the argument would be "consistency with non param-values" and "given the trouble it takes to get a uint param to begin with, what would compel someone to do this?"  The user could always cast the param to int(64) and apply the `-` themselves if desired.  And, for consistency, we should arguably do this for `param int(?w)` as well.

We could also see whether @daviditen remembers more about this:  https://github.com/chapel-lang/chapel/commit/9b6870c18881a825ce29d0f91ec5bd59239c44ab

>  I only saw these failures:

For the four sungeun/rect tests, I think we should update the unsigned cases to use something like `{un/2..un}` as the base domain to keep all the values positive.  Might need to change the arguments sent to the helper routine to `-n/2 + 1` or something to avoid a wraparound issue.  I can help look at these if you want.

For functions/diten/unary_uint64_param_minus, this was added in the commit above, so should be updated if we remove it.

> trivial/deitz/integers/negate_uint32

This should presumably be updated to reflect the error.

> visibility/except/operatorsExceptions/exceptNegation

I'm not guessing how this one's behavior has changed.  Maybe just prints out different candidates?

**Comment by daviditen** [comment]
> A related puzzle is that we currently have this:
>  ...
> If I am reading it right, it means that you can do `param p = (-1):uint; writeln(-p);` without facing the error, but I'm having trouble understanding why that makes any sense.

That example would trip the compiler error. The idea of this operator was to allow compile time negation of uint(64) values as long as it didn't cause any overflow. If casting a positive uint(64) into an int(64) made it turn negative an overflow occurred and an error should be issued. Otherwise the result of the negation operator is a negative number with the same magnitude as the original uint(64).

**Comment by daviditen** [comment]
> Was the idea that - on a uint(64) would result in an int(64) rather than a uint(64)?

Yes, this negation operator allows converting a positive `uint(64)` into a negative `int(64)` with the same absolute value at compile time. If you do `-(1:uint(64))` it will result in `-1` (a signed int(64)). If you do -(uint(64) with top bit set) it will error out because `-(positiveNumber)` should be negative but it will instead be a positive `int(64)`.

**Comment by mppf** [comment]
I've created PR #20805 to do this. When updating the expand/interior/etc tests, I noticed that these functions were not working correctly for negative values passed when working with an unsigned index type. The tests were only handling the uint case (because negating the small int value led to a small uint). I've fixed these and am running testing (in case my fixes introduce other errors).
