### ISSUE TITLE
Add priority level to github issue template

### ISSUE THREAD

**Issue by ronawho** [chapel-lang/chapel#21023]
Often our first question on a new user-issue is whether the problem is a blocker or if the user has a workaround. I think it'd be valuable to just put this in the issue template so we consistently have the information and can better judge priority/severity of an issue. 

If we had https://github.com/chapel-lang/chapel/issues/9469, this may be something I'd only ask for in the "bug report" template.

**Comment by damianmoz** [comment]
I thought at the multiple template stuff was deprecated. Or am I just silly.

Anyway, some things are bugs. Some things means a task cannot be completed but it might mean a workaround needs to be found.  I try to stick Urgent (but mainly Not Urgent) into the title.

Addressing some issues would make life easier (or avoid workarounds). My suggestions for those are often so that future design decisions do not preclude addressing such issues.
