### ISSUE TITLE
--help shows a lot of built-in config consts; do we want all these to be displayed?

### ISSUE THREAD

**Issue by stonea** [chapel-lang/chapel#21150]
With the following program:

```chpl
config const myUserConfig = true;

writeln("Hello world");
```

If I run `./foo --help` I get:

```
FLAGS:
======
  -h, --help            : print this message
  -a, --about           : print compilation information
  -nl <n>               : run program using n locales
                          (equivalent to setting the numLocales config const)
  -q, --quiet           : run program in quiet mode
  -v, --verbose         : run program in verbose mode
  --gdb                 : run program in gdb
  --lldb                : run program in lldb
  -E<envVar>=<val>      : set the value of an environment variable

CONFIG VAR FLAGS:
=================
  -s, --<cfgVar>=<val>  : set the value of a config var
  -f<filename>          : read in a file of config var assignments

CONFIG VARS:
============
Built-in config vars:
             printModuleInitOrder: bool
            dataParTasksPerLocale: int(64)
        dataParIgnoreRunningTasks: bool
            dataParMinGranularity: int(64)
                         memTrack: bool
                         memStats: bool
                   memLeaksByType: bool
                         memLeaks: bool
                           memMax: uint(64)
                     memThreshold: uint(64)
                           memLog: string
                      memLeaksLog: string
                   memLeaksByDesc: string
                         debugGpu: bool
  defaultHashTableResizeThreshold: real(64)
                       numLocales: int(64)

foo config vars:
                     myUserConfig: bool
```

It's nice that we separate the "Built-in" config vars from the users config vars but:

* It still seems like we're littering the help output with a lot of information that won't be relevant to most users.
  * And presumably over time this list will get longer.
* Do we consider these config constants stabilized for Chapel 2.0? If they're considered unstable what mechanism is informing the user of that?

Perhaps:
* We should make all these config constants "private config const"s, or
* We could have some sort of `@nohelp` or `@help` annotation for configs that could squash them in the help output
  * Perhaps we could automatically "nohelp" these builtin consts, or
* We could only display the builtin consts when `CHPL_DEVELOPER=true`

**Comment by stonea** [comment]
One concern for suppressing the output of (non private / qualified) config consts is if the user makes their own config const overriding an existing one (say they define their own `debugGpu` config const) they'll get an error message like this:

```
<command-line arg>:1: error: Configuration variable 'debugGpu' is defined in more than one module.  Use '--help' for a list of configuration variables and '-s<module>.debugGpu' to disambiguate.
```

Which might cause a reaction like: "Hey what other module is defining `debugGpu`? I don't see any other documentation or references to it? What is this error talking about?"

**Comment by lydia-duncan** [comment]
I think we've reviewed some of them in the module they were defined, but I don't know that we've reviewed all of them.

I believe the memory related ones will not be stabilized for 2.0.  There's an issue tracking an action item for unstable configs (#20680) but at the time I made it, I had forgotten the memory tracking module had configs in it.  So I'll update that issue to mention them and to suggest that their help output also be adjusted to include `(unstable)` or allow the short descriptor to be set in a specific way or something.

I don't remember the outcome about the `dataPar` configs, but I'm pretty sure we discussed them (maybe when we were stabilizing language stuff?).

I don't know that we've discussed `printModuleInitOrder`.  `defaultHashTableResizeThreshold` is not in a public facing module and is a long enough name that it's probably okay?  I'm not sure, we should get more eyes on this.

I think `numLocales` probably should be hidden since `-nl` is the preferred of setting it, but we also probably should get more eyes on it.

It's probably obvious, but I expect the gpu one to be treated like the memory ones.

**Comment by lydia-duncan** [comment]
I'll talk with Michelle about this in our normal 2.0 topic strategy session on Monday

**Comment by lydia-duncan** [comment]
I can't find discussion about the `dataPar` ones in any module review setting that I would expect, nor do they turn up in a public github issue with the 2.0 tag.

**Comment by lydia-duncan** [comment]
In our discussion on Tuesday, we weren't fully decided on whether the `dataPar*` configs should be stabilized for 2.0, but will have that discussion be lower priority than other 2.0 discussions.

**Comment by e-kayrakli** [comment]
Since OP, we have added another flag (`enableGpuP2P`) to the internal `ChapelGpuSupport` module. I am in the process of adding yet another one (probably `noCpuModeWarning`).

I am still very supportive of using `private config const`s as much as possible, but one complication that's not recorded here is that `private config const`s in internal modules are not usable. We cannot mark them private because the module is internal and its name is not visible ( https://github.com/Cray/chapel-private/issues/1605).

Moving these variables to the standard `GPU` module is not an option, because we rely on module initialization to set the runtime equivalent of these flags. If the standard module is not used, then we won't have a module to initialize.

**Comment by lydia-duncan** [comment]
This made me look for the meat of the unstable config discussion notes, which it looks like are on #20680.  I think it would be good to include your concern there as well

**Comment by bradcray** [comment]
Engin's #22849 improves the situation here.  A next step here would be to determine which configs (if any) we want to commit to stabilizing in 2.0 and to mark all others as unstable.

**Comment by lydia-duncan** [comment]
I've got a chart I made back in February, but haven't looked more recently than that.  Most of them are already unstable due to being in an unstable module (the Diagnostics module, one of the GPU modules).

**Comment by lydia-duncan** [comment]
I think the ones to mark are:
- printModuleInitOrder (modules/internal/PrintModuleInitOrder.chpl)
- dataPar* (modules/internal/DefaultRectangular.chpl)

If the Diagnostics and GPU ones are not showing as unstable, then we can also go and mark them explicitly

**Comment by lydia-duncan** [comment]
I believe this has been resolved, closing
