### ISSUE TITLE
design: is the buffer of a string or a bytes value required to terminate with a 0 ?

### ISSUE THREAD

**Issue by vasslitvinov** [chapel-lang/chapel#21160]
[Update:] This started as a bug issue assuming that the the answer was "yes". Turns out that we are not settled on the answer.

Therefore this issue now requests to determine the answer and to adjust our implementation to comply with it. If the answer is "yes", users can create non-compliant strings (see below). If the answer is "no", we likely have code that will malfunction when passed a non-0-terminating string.

[Previous contents:] Our convention today for the underlying buffer of a string, i.e., `_string.buff` [(source)](https://github.com/chapel-lang/chapel/blob/4d5379da31/modules/internal/String.chpl#L670-L674), is that it is zero-terminated. Therefore, s.buffSize should be at least s.buffLen+1.

Neither condition is checked in `createStringWithBorrowedBuffer(x: c_ptr(?t), length: int, size: int)` [(source)](https://github.com/chapel-lang/chapel/blob/4d5379da31/modules/internal/String.chpl#L470-L480). Therefore users can invoke this function in a way that creates a string with our convention violated.

The test `test/library/standard/IO/readAll/readBytesArray.chpl` [(source)](https://github.com/chapel-lang/chapel/blob/4d5379da31/test/library/standard/IO/readAll/readBytesArray.chpl)does exactly that. It invokes createStringWithBorrowedBuffer() passing it a buffer of size 1032 and length == size == 1032. The violation of both conditions goes unnoticed because nothing in that test relies on the invariant to hold. Whether or not the string is 0-terminated is immaterial because the buffer `a_signed` does not have room for that final zero.

If we switch the test to invoke createBytesWithBorrowedBuffer(), it will have the same violation.

Chapel version: 4d5379da31

**Comment by vasslitvinov** [comment]
We have the choice to introduce the checks in createStringWithBorrowedBuffer / createBytesWithBorrowedBuffer vs. `initWithBorrowedBuffer(ref x: ?t, other: bufferType, length:int, size:int)` [(source)](https://github.com/chapel-lang/chapel/blob/4d5379da31/modules/internal/BytesStringCommon.chpl#L291-L301) . I suggest the latter if it is user-facing. Note that the former (the string version) already validates for UTF8-ness.

We also have the choice to disable this validation upon --fast / --no-checks. I can go either way, given that it is constant-time. Although checking for the terminating zero may be a cache miss.

**Comment by vasslitvinov** [comment]
While there... we may want to optimize getHash() to return 0 if x.buffLen == 0 and countNumCodepoints() to return buffLen if it is <= 1, to avoid potentially going cross-locales in these cases.

**Comment by mppf** [comment]
It's my understanding that we are trying to null-terminate all of our strings in memory, but I don't think it's necessarily the case that we should guarantee that property in a user-facing way.

In the long term, the main issue with null-terminating all strings in memory is that it prevents us from having a string slice that refers to another string's memory. (See also #11222 and #12670 about how we might one day add "borrowed strings" which would make this relevant). But, even in that case, if we are willing to add a bit to the string record, we could arrange for the string to manage allocating a copy of itself that is null terminated (and deleting it when the string is deleted). Relatedly, today we use `someString.localize().c_str()`; here the temporary copy of the string (if needed) is created because `someString.localize()` returns a new string by value. Perhaps we could generalize this pattern to effectively do `someString.localizeAndZeroTerminate().c_str()`.

**Comment by vasslitvinov** [comment]
I updated the issue to determine whether we require null-termination and to adjust our implementation to comply with the answer.

**Comment by bradcray** [comment]
Still catching up on December, I'm tagging @e-kayrakli as string-/bytes-master to get his read on this.

**Comment by e-kayrakli** [comment]
I don't have strong opinions on the matter.

First, I certainly hope that none of our methods on string/bytes rely on null-termination. I know that the way we have nulls at the end is a bit haphazard.

Some cases where enforcing null-termination can be problematic:
- As Michael pointed out string views can be a little difficult to implement when/if we need them,
- Related but, cases where we want to borrow a part of a raw buffer as a Chapel string/bytes
  - e.g., here we don't get the null-terminator from qio interface, but it is fine. Should we allocate a new buffer and add null at the end? But that's not borrowing. So should we not be able to create "borrowed" strings: https://github.com/chapel-lang/chapel/blob/main/modules/standard/Regex.chpl#L634-L640
  - e.g., do we need to avoid null-termination for exporting string/bytes arguments? I can't explain what's going on here, but it is another case where a non-null-terminated "borrowed" string is created: https://github.com/chapel-lang/chapel/blob/main/modules/internal/ExportWrappers.chpl#L83-L99

I don't think these cases are without solutions should we enforce null-termination. But the design around creating "borrowed" strings from raw data would have to change.


However, having null-termination guarantee can make C interop easier. I am curious whether there's any internal case where we have to add/ensure null termination before calling an extern C function.

**Comment by mppf** [comment]
> First, I certainly hope that none of our methods on string/bytes rely on null-termination.

Arguably, `.c_str()` does rely on the string being null terminated.

**Comment by e-kayrakli** [comment]
True. I meant more from an algorithmic standpoint. We shouldn't be relying on a terminating null to determine the end of a string. It should all be based on the length.

**Comment by vasslitvinov** [comment]
> True. I meant more from an algorithmic standpoint. We shouldn't be relying on a terminating null to determine the end of a string. It should all be based on the length.

Are you suggesting that it is OK for a Chapel string to lack the terminating 0? I am game for that. In this case, how to implement .c_str() ?

**Comment by e-kayrakli** [comment]
> Are you suggesting that it is OK for a Chapel string to lack the terminating 0?

I was merely saying that the implementation of string algorithms do not rely on the null termination, but instead they work with the a priori knowledge of string's length.

Thinking about this more, one of the main points that I was thinking about is that `0x00` is legal UTF-8 byte (https://github.com/chapel-lang/chapel/issues/14177). Granted, it is only used for the null codepoint and no other codepoints. So, another way to ask the question this issue is asking is "can Chapel strings contain `0x00` byte?"

Currently, the answer to that question is "yes". This is consistent with python, which was the main example while we were converting our strings to unicode-only. However, this is not good for C interop, at least not today. `"AAA\x00AAA"` will not be usable with C interop:

```chapel
extern proc printf(s...);
var s = "AAA\x00AAA";

writeln(s);  // AAAAAA (my terminal doesn't show null bytes)
printf("%s\n", s.c_str()); // AAA
```

Options as far as I can see:

1. Make an exception for `0x00` and not support it within Chapel strings
  **Con:** This might hurt python interop
  **Pro:** Better C interop

2. We can make all our string null-terminate *and* keep a field as to whether the buffer contains `0x00`, in which case `c_str()` halts
  **Con:** Potentially costly, especially for `bytes` for which there is no validation today.
  **Pro:** Can interact with C and Python well

3. Make `c_str` return a copy of the buffer with `0x00` filtered out except the terminating one
  **Con:** `c_str` will be costly
  **Pro:** Not breaking
  3a. Same as 3, but do filtering only if a field like in (2) says the string contains null byte
  **Con:** Costly for `bytes`, like (2)
  **Pro:** Not breaking, not bad for `c_str` performance 

4. Keep the status quo
  **Con:** buggy C interop
  **Pro:** ?

**Comment by mppf** [comment]
Of those I'd go with the status quo. I think C programmers are used to the limitation that C strings cannot contain null bytes (other than the null terminator). They can use a pointer + length strategy when the code needs to handle nulls. We can support calling `extern procs` with a pointer + a length for our C strings (e.g. `c_ptrTo(myString)` can return a pointer to the buffer; and we have a function to get the length in bytes already, I think).

I *am* suggesting that Chapel strings should not be required to always be null-terminated. My best ideas for adding the null for `.c_str()` are:
 1. `someString.localizeAndZeroTerminate().c_str()` or
 2. the proposal in #21233
    > If we have custom reference types as proposed in this issue, the `string.c_str()` method could be adjusted to return a custom reference type that can store a copy that is deinitialized at the end of the relevant scope.

**Comment by bradcray** [comment]
> Arguably, .c_str() does rely on the string being null terminated.

Does it, or does it do a deep copy of the string? (at which point it could add the null).  I was wondering about this while trying to figure out how Scott's NetCDF code today, and couldn't easily come to a conclusion by just reading the code, though it seemed like it might be a deep copy (unless `const` intent means `const in`, which I doubt).

**Comment by e-kayrakli** [comment]
> Does it, or does it do a deep copy of the string? (at which point it could add the null). I was wondering about this while trying to figure out how Scott's NetCDF code today, and couldn't easily come to a conclusion by just reading the code, though it seemed like it might be a deep copy (unless const intent means const in, which I doubt).

It does not. It returns the pointer to the beginner of the data buffer. It only casts it to `c_string`. (Where do you see `const`?)

**Comment by bradcray** [comment]
The `const` was in Scott's blog article—I couldn't figure out how his code could work if something wasn't making a deep copy, either `.c_str()` or `const`.

**Comment by arezaii** [comment]
closing as we decided to **not require** null termination on string/bytes buffers
