### ISSUE TITLE
module-qualified names within loops causing an internal compiler error

### ISSUE THREAD

**Issue by mstrout** [chapel-lang/chapel#21190]
### Summary of Problem
When one tries to convert a `use` statement to an `import` statement, the resulting code gets an internal compiler error.  This happens with both 1.28 and on main today (today is code freeze for 1.29).

### Steps to Reproduce

**Source Code:**

```chapel
/***** bar.chpl *****/
module bar {

  record data {
    var a: int;
  }

}
```

```chapel
/***** foo.chpl *****/
use BlockDist;
import bar;
//use bar;

var D: domain(1) dmapped Block(boundingBox={0..10}) = {0..10};

var data_set: [D] bar.data = for i in {0..10} do new bar.data(5);
//var data_set: [D] data = for i in {0..10} do new data(5);
```

**Compile command:**
`chpl foo.chpl`

Error message
```
foo.chpl:7: internal error: AST-LOO-XPR-0528 chpl version 1.29.0
Note: This source location is a guess.

Internal errors indicate a bug in the Chapel compiler ("It's us, not you"),
and we're sorry for the hassle.  We would appreciate your reporting this bug --
please see https://chapel-lang.org/bugs.html for instructions.  In the meantime,
the filename + line number above may be useful in working around the issue.
```

*edited to break source into separate blocks to represent separate source files

**Comment by riftEmber** [comment]
What is the error encountered? On my own machine on main I get the following with *either* the `import` or the `use`.
```
foo.chpl:8: internal error: assertion error [AST/LoopExpr.cpp:528]
Note: This source location is a guess.
```

**Comment by DanilaFe** [comment]
Smaller reproducer:
```Chapel
/* foo.chpl */
import bar;

var data_set = for i in {0..10} do new bar.data(5);
```
and
```
/* bar.chpl */
record data {
  var a: int;
}
```

**Comment by DanilaFe** [comment]
Also observing this on 1.27.

**Comment by mstrout** [comment]
> What is the error encountered?

Oops, I just put the error message in the OP.

**Comment by riftEmber** [comment]
@DanilaFe discovered a more minimal reproducer that shows the issue isn't with `use`/`import`, but with referencing a module symbol in a loop expression:
```chpl
module bar {
  record data {
    var a: int;
  }
}

var data_set = for i in {0..10} do new bar.data(5);
```

**Comment by bradcray** [comment]
I've only spent seconds looking at this and am curious whether there's a workaround that could be used here?  E.g., brainstorming briefly, would the following work?

```chapel
type bardata = bar.data;
var data_set = for i in {0..10} do new bardata(5);
```

I'm also curious about the degree to which this is a blocking issue (that is, will make 1.29 hard for the user to use) vs. something they ran into and just happen to be reporting today as good citizens.  Michelle, do you know?

[In both cases I'm asking because, if the fix requires major work or feels nontrivial, it may be wiser to put off merging it, even if we had it already.  I think it's natural to have bugs that show up just before a release feel urgent because it's an unsettling time to receive them.  But if it's non-blocking and not an easy fix, then there's no inherent reason to prioritize them over any other user bug fixes, particularly when it's a pre-existing condition].

All that said, if the fix is easy / not scary, I'm all for getting it in today.
