### ISSUE TITLE
`bigint ** bigint` gives unexpected results

### ISSUE THREAD

**Issue by pierce314159** [chapel-lang/chapel#21194]
### Summary of Problem

It seems that `bigint ** bigint` results in `0` (with the exception of when the exponent is `0`). In the source code below, I raise a `bigint` array to an int array and it's equivalent bigint. I expect to get the same result for both, but I get
```
1 12052035331942427 145251555642388606563664842650329
1 0 0
```

### Steps to Reproduce

**Source Code:**

```chapel
use BigInteger;
var bi = "12052035331942427": bigint;
writeln(bi ** [0,1,2]);
writeln(bi ** [0,1,2]:bigint);
```

**Compile command:**

`chpl PlayingAround.chpl -o playing`

**Execution command:**

`./playing`

**Associated Future Test(s):**

### Configuration Information

- Output of `chpl --version`:
```
chpl version 1.28.0
  built with LLVM version 14.0.6
```
- Output of `$CHPL_HOME/util/printchplenv --anonymize`:
```
CHPL_TARGET_PLATFORM: darwin
CHPL_TARGET_COMPILER: llvm
CHPL_TARGET_ARCH: arm64
CHPL_TARGET_CPU: native *
CHPL_LOCALE_MODEL: flat
CHPL_COMM: none *
CHPL_TASKS: fifo
CHPL_LAUNCHER: none
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: cstdlib
CHPL_ATOMICS: cstdlib
CHPL_GMP: system *
CHPL_HWLOC: none
CHPL_RE2: bundled *
CHPL_LLVM: system *
CHPL_AUX_FILESYS: none
```
- Back-end compiler and version, e.g. `gcc --version` or `clang --version`:
```
Homebrew clang version 14.0.6
Target: arm64-apple-darwin22.1.0
Thread model: posix
InstalledDir: /opt/homebrew/opt/llvm@14/bin
```

**Comment by mppf** [comment]
@pierce314159 - thanks for creating this issue. It is definitely not the behavior I would expect.

I created a slightly simpler program that does not use promotion to demonstrate to myself that the problem is solely within `**` on bigint.

<details>

``` chapel
use BigInteger;

config const x = 2;
config const y = 3;

var x_bi: bigint = x;
var y_bi: bigint = y;

writeln(x_bi**y_bi);
```

</details>

I looked at this enough to characterize the problem but I'm not sure what we should do to fix it.

We have
``` chapel
  operator bigint.**(const ref base: bigint, const ref exp: bigint): bigint {
    var c = new bigint();

    if _local {
      mpz_powm(c.mpz, base.mpz,  exp.mpz,  base.mpz);
    } ...

    return c;
  }
```

But, `mpz_powm` is modular exponentiation. (see also https://gmplib.org/manual/Integer-Exponentiation ). In other words, it computes the result `% mod` where this is the 3rd argument. GMP only supports a bigint exponent for modular exponentiation and a regular int exponent for non-modular exponentiation. Additionally, `mpz_powm` can work with a negative `exp`.

For the case of `base` and `exp` both being large enough to justify storing as `bigint`, it seems pretty easy to create very very large numbers... perhaps this is why GMP only supports the modular case. See also https://stackoverflow.com/questions/18149940/gnu-gmp-mpz-powm-without-mod

Anyway, the code we have here computes `base ** exp % base` which is always going to be 0 (because any multiple of `base` mod `base` is 0).

So, what can we do about it?
 * For `exp` small enough to fit into an `unsigned long int`, we could just call `mpz_pow_ui`. We could throw in the other cases.
 * We could try passing something else as the `mod` argument (but what would that be?). If we went with this strategy, we could handle negative `exp` by throwing for now. Perhaps we could estimate the size of the result (e.g. rounding everything in sight up to a power of two) and create a modulus bigger than the result that way. Or, maybe there is some smarter math-y way to compute this that I'm not aware of yet.
 * We could implement our own exponentiation algorithm with some kind of repeated squaring algorithm.

**Comment by ronawho** [comment]
> For exp small enough to fit into an unsigned long int, we could just call mpz_pow_ui. We could throw in the other cases.

This seems appropriate to me. Anything that's too big to fit in a `ui` will result in a number that exceeds memory capacity.

**Comment by mppf** [comment]
> > For exp small enough to fit into an unsigned long int, we could just call mpz_pow_ui. We could throw in the other cases.
> 
> This seems appropriate to me. Anything that's too big to fit in a `ui` will result in a number that exceeds memory capacity.

Well, I suppose we could make an exception for base being `0` `1` or `-1` though, which wouldn't have that problem.

But `2**(2**64)` is certainly a very large number indeed and would use too many bits, as you say.

**Comment by ronawho** [comment]
> Well, I suppose we could make an exception for base being 0 1 or -1 though, which wouldn't have that problem.

Yeah, but seems like we could special case that. I'm imagining something like:

```chpl
if base == -1 || base == 0 || base == 1 {
 return base; // -1 probably needs more special casing to figure out sign?
}
if exp.fitsInto(c_ulong) {
  return this.**(base, exp:uint);
} else {
  // throw or halt or something
}

**Comment by cassella** [comment]
Note also that `0 ** -n` should be handled before that.  `ChapelBase` has a few `**` helpers that might be good models.

**Comment by bmcdonald3** [comment]
Taking a look at this and I think we want to halt if the `exp` is too large, mainly because there are no `bigint` operators that throw today. Are there any objections to halting if `exp` is too large to fit into `c_ulong`?

**Comment by mppf** [comment]
I'm surprised that the cast to go from a `bigint` to an `int` does not throw if the `bigint` is too large `inline operator :(const ref x: bigint, type t:numeric) where isIntType(t)`. (It does not even halt). I think perhaps we want some of these to throw?

**Comment by bmcdonald3** [comment]
> I think perhaps we want some of these to throw?

I think what I'll do here is implement a halting version for now and then open an issue to discuss throwing in the `gmp` module at large, where we may want to change several procedures and others who are currently out on vacation can have a say (and I don't feel confident in my opinion here just yet, as this is my first real exposure to bigint). Let me know if you disagree with this approach.

**Comment by bmcdonald3** [comment]
Alright, I've opened https://github.com/chapel-lang/chapel/pull/21244, which should resolve this issue using a halt and then opened up https://github.com/chapel-lang/chapel/issues/21242 to continue the conversation on whether we want halting or throwing for `bigint` casts/operators.

**Comment by ronawho** [comment]
@pierce314159 I think casting the right hand side of the `**` to an `int` is a decent workaround until you can rely on a Chapel version with Ben's fix.
