### ISSUE TITLE
Promote Memory.Diagnostics to top-level module

### ISSUE THREAD

**Issue by benharsh** [chapel-lang/chapel#21205]
With Memory.Initialization having been replaced by "MemMove" (#20425), the Memory.Diagnostics module now stands alone. We should promote this to a top-level module for consistency.

**Comment by benharsh** [comment]
I'll kick this off by proposing the name "MemDiagnostics" for consistency with "MemMove".

An alternative approach would be to collect some of the various diagnostics modules (CommDiagnostics, GPUDiagnostics) into a collection of modules under a "Diagnostics" module.

**Comment by bradcray** [comment]
I like `MemDiagnostics` due to symmetry with `MemMove` and `CommDiagnostics`.

Since Engin's not here, I'll say that in the past, he's been an advocate for the `Diagnostics.{...}` approach.  To me, this feels like more hierarchy than necessary and typing than ideal, so I'm not as wild about it, at least until we have 100's of standard modules.  That said, I will note that it doesn't trigger the same negative reaction in me that I had to `Memory.*` because even though the root module would likely still be empty (making it a singleton), at least the child modules would be more symmetric with one another (at least in purpose...  they aren't particularly in terms of interfaces or approach, so lumping them together in this way might beg the question whether they should be).

I'll also mention that I don't think this is technically 2.0 b/c I don't think this module is on our list for stabilization.  But at the same time, I'd like to resolve it before 2.0 b/c I think it should be easy and would be a shame to leave it as a singleton submodule of an empty module (in the sense that it makes us look funny).  So I'm good with the label being applied here for that reason.

**Comment by bradcray** [comment]
Going through old issues, I'm wondering what it would take to make this change.  If we're not stabilizing the module for 2.0, does it have to go through the design process?  Can we just get a straw poll about whether people are OK with `MemDiagnostics`?  @lydia-duncan / @mstrout what do you think?  This feels like an easy task to get done, and a bit unfortunate to go into 2.0 in its current state.
