### ISSUE TITLE
Compiler Times

### ISSUE THREAD

**Issue by Ethan-DeBandi99** [chapel-lang/chapel#21214]
### Steps to Reproduce

**Source Code:**
No applicable source code since this is a general thing occurring with compilation.

### Configuration Information
My configuration information is below, but again this is applicable to all systems.

```bash
chpl --version
chpl version 1.28.0
Copyright 2020-2022 Hewlett Packard Enterprise Development LP
Copyright 2004-2019 Cray Inc.
(See LICENSE file for more details)

$CHPL_HOME/util/printchplenv --anonymize
CHPL_TARGET_PLATFORM: darwin
CHPL_TARGET_COMPILER: clang
CHPL_TARGET_ARCH: arm64
CHPL_TARGET_CPU: unknown
CHPL_LOCALE_MODEL: flat
CHPL_COMM: gasnet *
  CHPL_COMM_SUBSTRATE: udp
  CHPL_GASNET_SEGMENT: everything
CHPL_TASKS: fifo *
CHPL_LAUNCHER: amudprun
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: cstdlib *
CHPL_ATOMICS: cstdlib
  CHPL_NETWORK_ATOMICS: none
CHPL_GMP: none *
CHPL_HWLOC: none
CHPL_RE2: bundled *
CHPL_LLVM: none *
CHPL_AUX_FILESYS: none

gcc --version
Apple clang version 14.0.0 (clang-1400.0.29.202)
Target: arm64-apple-darwin22.1.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Comment by mstrout** [comment]
Hi Ethan, we appreciate you reaching out to share your concern about compiler times with Chapel.  We share your concern are about a third of the way through a multiyear project to provide separate and incremental compilation for Chapel.  Check out the "Dyno update" in our most recent release notes if you want to read more about this effort, https://chapel-lang.org/releaseNotes.html.

**Comment by ronawho** [comment]
I asked Ethan to capture this on his way out the door today just to get the ball rolling. While we expect dyno to have the longer term improvements, I asked Ethan to open this to raise attention that waiting for dyno isn't a very satisfying answer for them.

And for more context: Chapel compilation times for Arkouda are quite slow, which reduces developer velocity/productivity. Building without optimizations (`ARKOUDA_QUICK_COMPILE`) helps and doing modular builds can also help, but compilation times are still quite slow, especially when debugging multi-locale codes that requires most arkouda modules. Here's a few data points for build times:
 - `ARKOUDA_QUICK_COMPILE=true CHPL_COMM=none`: 5 minutes
 - `ARKOUDA_QUICK_COMPILE=true CHPL_COMM=gasnet`: I think Ethan said ~20+ minutes but will report next week
 
I think we were hopeful that `QUICK_COMPILE` + reduced modules would be fast enough to get by until more of dyno is online, but there have been a few arkouda development efforts the last few weeks that require most modules in a multi-locale config, and that really hits the long compilation times, which can be frustrating when you're stuck in a debug cycle.

~2 years ago in https://github.com/Cray/chapel-private/issues/1260 we looked at low-hanging fruit to reduce compilation time and from https://chapel-lang.org/releaseNotes/1.23/04-perf-opt.pdf that resulted in almost a 2x compilation time improvement. The arkouda code base has changed and grown a lot since then so here I'm wondering if there's new low-hanging fruit we could address to improve compilation times (ideally work that wouldn't be thrown out when dyno is more fully online.)

I'll also note that Ethan opened https://github.com/Bears-R-Us/arkouda/issues/1957 to look into whether there's any unused code in Arkouda that could be removed.

**Comment by bradcray** [comment]
If I were an Arkouda developer trying to reduce compile-times to improve my turnaround cycle, I'd start using the C back-end and `-j` flag.  I know there are concerns about performance impact and using the non-default back-end, but I think the time saved would get me past those concerns pretty quickly (again when in developer mode—I would not recommend this for a production build).  At the time of development, it reduced the makeBinary step of Arkouda by 3x (which is not the whole shebang, but one of the bigger bottlenecks): See slide 11 of https://chapel-lang.org/releaseNotes/1.26/04-compiler.pdf

It would be great to extend the `-j` flag to the LLVM back-end, but I have no read on what would be required there.

**Comment by ronawho** [comment]
Good point for `make -j` with the c-backend. That and using`CHPL_HOST_MEM=jemalloc` seem like low-hanging configuration changes.

**Comment by bradcray** [comment]
Just in case it was unclear, I was proposing using the `chpl -j` flag (which uses `make -j` under the covers, so you may have been as well—just clarifying for @Ethan-DeBandi99 ).

**Comment by Ethan-DeBandi99** [comment]
@bradcray - I am already using the `-j` with the C backend (specifically in cases when building with gasnet). These do not have a big of an impact as I would expect. I am actually unable to build gasnet on my machine using `llvm` so it forces me to use the C backend. The issue here is that we are doing development and testing against a different set of parameters than what is being used by our users.

**Comment by ronawho** [comment]
@Ethan-DeBandi99 can you attach the per-pass timings for a comm=none and comm=gasnet build (at the end of an arkouda build there should be a sorted table)

**Comment by ronawho** [comment]
> The issue here is that we are doing development and testing against a different set of parameters than what is being used by our users.

I don't think that's big issue FWIW. I think it's ok for developers and CI to run with flags to speed up builds and just rely on nightly testing to run like users to catch any backend/optimization bugs.
