### ISSUE TITLE
[Internal error] Class variables usage within `coforall` doesn't check for default init

### ISSUE THREAD

**Issue by bmcdonald3** [chapel-lang/chapel#21272]
### Summary of Problem
Variables that have not been default initialized but are accessed in a `coforall` loop cause an internal error. This should result in a compiler error saying that the variable cannot be default initialized, like it would when accessing the variable outside of a `coforall` loop. This issue was ran into in Arkouda, where the use of the symbol table was causing this error.

### Steps to Reproduce

**Source Code:**

```chapel
class MyClass {
  proc func() {
    return 2 + 2;
  }
}
var m: MyClass;
// var m = new MyClass(); // works as expected
// m.func(); // compiler error, can't default init

coforall idx in 0..3 {
  m.func();
}
```

### Configuration Information
Chapel 1.29.

**Comment by cassella** [comment]
The internal error is

```
internal error: assertion error [resolution/functionResolution.cpp:7204]
```

```c
static void handleTaskIntentArgs(CallInfo& info, FnSymbol* taskFn) {
...
      // If 'call' is in a generic function, it will have been instantiated by
      // now. Otherwise our task function has to remain generic.
      INT_ASSERT(varActual->type->symbol->hasFlag(FLAG_GENERIC) == false);
```

Maybe `m` (or its type) is sneaking its way in there still generic?  If it's declared as `var m: unmanaged MyClass` the result is a normal error,

```
foo.chpl:1: In module 'foo':
foo.chpl:6: error: cannot default-initialize m: unmanaged MyClass
foo.chpl:10: error: use here prevents split-init
note: non-nilable class type 'unmanaged MyClass' does not support default initialization
note: Consider using the type unmanaged MyClass? instead
```

**Comment by dlongnecke-cray** [comment]
If the manager type is omitted e.g., `var m: MyClass`, and `m.func()` is called outside the `coforall`, then the error ends up looking like this:

```chapel
var m: MyClass;
m.func();
```
```
CoforallDefaultInitBug.chpl:1: In module 'CoforallDefaultInitBug':
CoforallDefaultInitBug.chpl:8: error: cannot default-initialize a variable with generic type
CoforallDefaultInitBug.chpl:8: note: 'm' has generic type 'anymanaged MyClass'
CoforallDefaultInitBug.chpl:8: note: cannot find initialization point to split-init this variable
CoforallDefaultInitBug.chpl:11: note: 'm' is used here before it is initialized
```

If I just delete the internal assertion Paul mentioned, the test code with the `coforall` ends up with a similar error, just missing the line about `m` being used before initialization.

```chapel
var m: MyClass;

coforall idx in 0..3 {
  m.func();
}
```
```
CoforallDefaultInitBug.chpl:1: In module 'CoforallDefaultInitBug':
CoforallDefaultInitBug.chpl:10: error: cannot default-initialize a variable with generic type
CoforallDefaultInitBug.chpl:10: note: 'm' has generic type 'anymanaged MyClass'
CoforallDefaultInitBug.chpl:10: note: cannot find initialization point to split-init this variable
```

---

The spec says:

```
If a class type’s memory management strategy is unspecified, it will be generic.
(This is not the case for instances of classes. When a new class instance is
created with an unspecified memory management strategy it will default to owned.)
```

So, perhaps:

- The error should mention `owned` instead of `anymanaged` / generic management...
-  We need to get the warning about being unable to default-initialize `m` to show up for the `m.func()` call in the `coforall`, still.
- It would be nice if we could silence the split-init warnings.

**Comment by bradcray** [comment]
It's interesting to me that the errors focus on the generic-ness of the type rather than the non-nilability.  Since `m: MyClass` means it's non-nilable, to  me that's the real reason it isn't default initializable—we can't store `nil` into it and we never call class initializers on the user's behalf.  If it were declared `m: MyClass?` then I think it's appropriate for it to complain about the class being generic (i.e., "Should I store an `owned nil`, `borrowed nil`, etc.)

> It would be nice if we could silence the split-init warnings.

The split-init warning seems appropriate to me, in the sense that if this example:

```chapel
var m: MyClass;
m.func();
```

had included `m = new MyClass();` before `m.func();` then it would be OK due to split initialization.

> The error should mention owned instead of anymanaged / generic management...

That doesn't seem right to me—only if it were `new MyClass()` or `new owned MyClass()` would I expect `owned` to come into the picture.  If the user doesn't use a `new` or otherwise assign the class, we don't default to `owned`.

**Comment by bradcray** [comment]
> wouldn't we take var m: MyClass; to be the initialization point of m?

Yes.

> At which point it would have to be determined to be owned, since nothing else is said about it.

No, I don't think that was the intention in that spec verbiage (@mppf, double-check me?).  I think the key is "when a new class instance is created" which is only done through the `new` keyword (i.e., declaring a class variable doesn't create an instance just a pointer to a potential instance).  This could almost certainly be made clearer since you thought otherwise, though.

> And then it is only at that point we would say "hey this doesn't work, we can't default-initialize m".

That part is correct, where there are two or three reasons we can't default initialize it — it's non-nilable (so we can't use `nil`), it's generic (so we don't know what type it is), and we don't create new class instances implicitly.

> I thought split-init only applies if there actually is another point between var m: MyClass; and m.func() that can be considered as initialization for m. But I see that message even if var m = new MyClass() is commented out.

I think that's right.  My interpretation of that message is "there's no initialization expression, and I didn't see you explicitly split-init it anywhere, so I couldn't find a split-init style initialization point."

> I thought that @bmcdonald3 only included it in the OP to indicate that if he did that, things worked.

I think you're correct about that (the reason being that then a split initialization point can be found and the compilation can proceed).

**Comment by mppf** [comment]
> > > If a class type’s memory management strategy is unspecified, it will be generic. This is not the case for instances of classes. When a new class instance is created with an unspecified memory management strategy it will default to owned.)



> > At which point it would have to be determined to be owned, since nothing else is said about it.

> No, I don't think that was the intention in that spec verbiage (@mppf, double-check me?). I think the key is "when a new class instance is created" which is only done through the new keyword (i.e., declaring a class variable doesn't create an instance just a pointer to a potential instance). This could almost certainly be made clearer since you thought otherwise, though.

Yes, please update that spec section to specifically mention `new`.

**Comment by dlongnecke-cray** [comment]
So to fix this bug, the only thing I should try to do is propagate the "cannot default-initialize `m`" error into the `coforall`?

**Comment by mppf** [comment]
Yes, just like the OP said:

> Variables that have not been default initialized but are accessed in a coforall loop cause an internal error. This should result in a compiler error saying that the variable cannot be default initialized, like it would when accessing the variable outside of a coforall loop.

**Comment by dlongnecke-cray** [comment]
Simply removing the `INT_ASSERT` will fix this issue. With a bit of extra effort I can get the "note: 'm' is used here before it is initialized" to display as well, but it isn't necessary (all of these are part of the same split-init error).
