### ISSUE TITLE
[internal error] COD-CG--XPR-2789 chpl version 1.29.0

### ISSUE THREAD

**Issue by kwaters4** [chapel-lang/chapel#21296]
### Summary of Problem

This problem can most likely be reduced to something more stripped down, below is a reproducer.

Incorrect --ccflag on the command line creates an internal compiler error.
Initial output suggests correct flag, however it is followed an error, see below:
```
error: unknown argument '-mavx512'; did you mean '-mavx512f'?
internal error: COD-CG--XPR-2789 chpl version 1.29.0
```

### Steps to Reproduce

**Source Code:**
Any valid chapel file should work, here is an example of ```foo.chpl```

```chapel
var x = 5;
```

**Compile command:**
```chpl foo.chpl --fast --cflags -mavx512``` (Any misspelled cflag may do?)

**Execution command:**
Will not compile. 

**Associated Future Test(s):**

### Configuration Information

- Output of `chpl --version`:
 ```
chpl version 1.29.0
built with LLVM version 14.0.0
```

- Output of `$CHPL_HOME/util/printchplenv --anonymize`:
```
CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: llvm
CHPL_TARGET_ARCH: x86_64
CHPL_TARGET_CPU: native
CHPL_LOCALE_MODEL: flat
CHPL_COMM: none *
CHPL_TASKS: fifo *
CHPL_LAUNCHER: none
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: cstdlib *
CHPL_ATOMICS: cstdlib
CHPL_GMP: none *
CHPL_HWLOC: none
CHPL_RE2: none *
CHPL_LLVM: bundled *
CHPL_AUX_FILESYS: none
```
- built with LLVM version 14.0.0

**Comment by bradcray** [comment]
In cleaning out my inbox for the end of the year, I'm realizing that this never got any attention, probably due to arriving during the holidays and the beginning of year rush.  Sorry about that.  Checking the behavior today, it looks improved, and I have a vague memory of someone maybe working on something similar to this recently, though I'm having trouble finding the PR I'm thinking of.  I'm adding in a test in https://github.com/chapel-lang/chapel/pull/24100 to lock in the current behavior and will have that close this issue once merged in 2024.
