### ISSUE TITLE
[Map Module] What should we do about the various `get` methods?

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#21395]
Today our map type supports `getReference()`, `getBorrowed()` and `getValue()`.  The various versions were provided due to concerns about accidentally transferring ownership of `owned` classes stored in the map when trying to just perform a read, enabling users to be very explicit about what they were looking for from the method call.

It was proposed that we could condense these methods into a single new `get` method, ensuring that in the case of owned classes only a `borrow` would be returned.

It was also proposed that maybe `[]` accesses on the map are sufficient and these `get` methods could be removed.

Precedence:

<details>

- C++ maps provide `[]` and `at()`, where the `[]` will also insert the element if it does not already exist and `at` will fail if the key does not already exist
- Swift provides a dictionary type rather than a type called map, though they are probably used in a similar way.  The dictionary type provides `[]` accesses that can be used to get the value at the key, to provide a default value if the key does not already exist in the dictionary, to update the value in the key if it did already exist, and to add the value if it did not.  The dictionary type closest equivalent to `get` or `at` so far as I can tell is the `index` method, which will return the index in the dictionary storing the key/value pair, or nil if that key is not in the dictionary.
- Python's dictionary type is the closest to an actual map, there is also the `map` function which returns an iterable grouping.  The dictionary type provides both `get` and `[]` accesses, though their behavior is the reverse of C++ - `get` will never fail if the item is not already present, while `[]` will.
- Java maps seem to only provide `get` so far as I could tell
- Go maps seem to only provide `[]` so far as I could tell
- Julia dictionaries have a `get` function that can be called with them.  I did not see `[]` associated with it in the API I checked, but I might have missed it. 
- Rust's map provides both `[]` and `get`, as well as a `get_mut` which allows the value returned to be mutated.

</details>

Differences between `get*` and `[]` on the map type today:
- `get*` will only retrieve the stored value, while `[]` can be used to store new values as well
- `get*` can be used for greater clarity on exactly what operation is being performed.
- `get*` will fail if the key does not already exist in the map, while `[]` will give no indication on whether the key already existed

Vote here:

❤️ - keep `getReference`, etc
👀 - condense `getReference` etc into `get`
🚀 - remove `getReference` etc entirely and only rely on `[]`

**Comment by bmcdonald3** [comment]
We added a `map.getValue()` that allowed the passing of a sentinel value that will be returned if the value is not found: `proc getValue(k: keyType, const sentinel: valType) const`.

I am planning on deprecating that one as well, since we will be throwing in the map accessors and be able to handle that with a try/catch in a similar way.

The other case that isn't mentioned in the OP is `proc getAndRemove(k: keyType)`. I am inclined to deprecate this one as well as I'm not entirely convinced it is more valuable than just doing a `this` access and then a `remove()`, but just wanted to make sure that no one disagreed before closing the door on that method.

**Comment by bradcray** [comment]
> I am planning on deprecating that one as well, since we will be throwing in the map accessors and be able to handle that with a try/catch in a similar way.

I'm not sure that's the right move here.  Specifically, I don't think of the sentinel-taking `getValue()` as being just a workaround for not having a throwing routine, but also a way to handle cases more elegantly and efficiently than using a try-catch.  As an example, if I had a map storing the count of the number of employees in a team with a given first name, `getValue("Bradley", 0)` as a means of finding out that there aren't any such employees is much more ergonomic than `try { count = getValue("Bradley") } catch ... { count = 0; }`.  In that sense, it's a bit like a sparse array where there's a logical value associated with elements that aren't otherwise explicitly members of the set.

**Comment by lydia-duncan** [comment]
Should it just be named `get`, then, since there won't be a corresponding `getReference` or `getBorrowed` it could be confused with?

**Comment by bmcdonald3** [comment]
I think that I still like `getValue`, since we often speak of map as key, value pairs, that to me still makes sense to call it `getValue`, but I don't feel strongly enough to argue if there is a majority just wanting to call it `get`.
