### ISSUE TITLE
Extend Docker container to support both LLVM and C back-ends

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#21448]
In an Arkouda developer meeting today, we were discussing the desire to be able to use the C back-end within a Docker container, which our Docker containers apparently don't support today (motivation: GitHub CI on Arkouda is running out of memory, and using the C back-end would permit us to do the makeBinary step as a separate process and/or using `chpl -j`.  Ultimately, the compiler driver is expected to help out here, but that's still a ways off.  Beyond that initial motivation, though, it was suggested that this also has the benefit of making the Docker container more capable, which is attractive).

The idea here would be to have the Docker formula do two builds, one with CHPL_TARGET_COMPILER=llvm (the default/current status) and a second with CHPL_TARGET_COMPILER=gnu|clang.

**Comment by bradcray** [comment]
Talking with @riftEmber, it sounds like this would be a fairly simple change to make, and one that they're willing to take up next sprint.

**Comment by ronawho** [comment]
Capturing from https://github.com/chapel-lang/chapel/issues/21449:

> Motivated by https://github.com/chapel-lang/chapel/issues/20845#issuecomment-1278120945, we'd like to be able use the c-backend in the docker image.

> I believe the docker image takes a long time to build today. Instead of building the runtime/third-party a second time with gnu, I was wondering if we can just use what used to be "clang-included" as the c compiler (basically use the clang we bundle and avoid having to rebuild the third-party/runtime.)

**Comment by bradcray** [comment]
Interesting idea.  I forgot the docker image was slow to build, though that sounds familiar now that you mention it.  Maybe a question for @riftEmber, but what about it makes it significantly slower than (say) doing a desktop build?

**Comment by riftEmber** [comment]
Misclicked the close button, sorry

**Comment by riftEmber** [comment]
As far as the suggestion at hand, if we don't need to rebuild to let users use either backend, that sounds like an attractive option. However, I don't think a second build of the runtime consumes too much additional build time, so I don't think it's a bad option either.

Right now the slow speed of Docker image builds are a source of annoyance at release time, which I don't mean to discount. The reason I speak of build time as not a huge concern *here* are:

1. Rebuilding the runtime isn't likely to be the straw that breaks the camel's back after we've already had to wait a long time to build the compiler itself.
2. Once we have automated Docker builds running in CI this won't matter as much as we won't need human involvement waiting around for these to finish. (i.e. "who cares if a nightly job takes an extra 15 minutes?")

**Comment by bradcray** [comment]
@riftEmber : Just pinging on this as you're thinking about the next sprint.

**Comment by riftEmber** [comment]
It finally occurred to me that if we try to use the bundled clang compiler to avoid a rebuild of the runtime, we will in fact have to build the bundled clang compiler, which our Docker image currently does not (we use `CHPL_LLVM=system`). Since that's a bigger build than the entirety of Chapel I think it's preferable to go ahead and just rebuild the runtime.

**Comment by ronawho** [comment]
That's a good point. I guess instead of specifically the clang we bundle, I would want to use "whatever C compiler an llvm config builds the runtime/third-party with" (the bundled clang for `CHPL_LLVM=bundled` and whatever we infer for `CHPL_LLVM=system`)

And I don't disagree with the notion that maybe the time for the second runtime/3p build isn't a huge deal for the docker builds (though it's still something I find myself wanting so I don't have to rebuild (and remember that I have to rebuild) when I want to use the C backend.)

**Comment by riftEmber** [comment]
Did not realize I closed this by merging the PR. The Dockerfile has been updated to support both backends, but this image is not published anywhere yet, and since this is a user issue it should probably remain until we confirm it works for Arkouda's CI.

**Comment by riftEmber** [comment]
I just realized making this modification to our Dockerfile does not affect our `chapel/chapel-gasnet` and `chapel/chapel-gasnet-smp` images, which can still only use a single backend. I have PR'd https://github.com/chapel-lang/chapel/pull/21603 to make this change in those Dockerfiles as well, because although they are not used by Arkouda CI this seems like desirable functionality for others.

**Comment by bradcray** [comment]
@riftEmber : Even though the work here hasn't been released out to the public yet (and we've decided to wait until 1.30 for that), it seems like the work described by this issue is done and that this could be closed now.  Do you agree?

**Comment by riftEmber** [comment]
@bradcray The work described by this issue is done. However, I see this as a user issue and my understanding was those should remain open until we are able to confirm it has resolved the user's concern. In this case that won't be possible until Arkouda CI is using 1.30 release of our Docker image; we don't yet have any real confirmation my Dockerfile changes fixed the problem. Since you were the one interfacing with the user in this case I think it's up to your judgment; closing this and then making a new issue if it somehow turns out things are still broken wouldn't hurt much.

**Comment by bradcray** [comment]
Though the motivation for the issue was to enable the Arkouda CI testing, the way I wrote it up the issue was more to focus on the changes to Docker, which seem done enough to call this done to me (similar to how, if we fix a bug that a user reports, we close the issue once it's fixed rather than once it's released).  I'll look into putting together a follow-up issue for actually enabling the improved CI testing once I verify with @ronawho and @bmcdonald3 that we don't already have one and whether they think that most naturally belongs in the Arkouda repo or one of ours.  Thanks!
