### ISSUE TITLE
do we need a new intent?

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#21499]
This issue asks if we need a new intent that mean something similar to the default argument passing intent but that can be used in return contexts.

### Background & Motivation

First, consider the array accessor declaration. It's declared as 3 methods that I below. In these 3 methods, `i` is an index expression, and they are going to return an array element, by value or by reference. Which method is chosen depends on how some expression like `A[i]` is used (and that feature is called [return intent overloading](https://chapel-lang.org/docs/language/spec/procedures.html#return-intent-overloads)).

This one returns a mutable `ref` to an element:

https://github.com/chapel-lang/chapel/blob/10ed2bec9308f560c2409e2152fc7b3a7b5c38bb/modules/internal/ChapelArray.chpl#L1018

This one returns a value but isn't always available:

https://github.com/chapel-lang/chapel/blob/10ed2bec9308f560c2409e2152fc7b3a7b5c38bb/modules/internal/ChapelArray.chpl#L1034-L1035

This one returns a `const ref` that refers to an element:

https://github.com/chapel-lang/chapel/blob/10ed2bec9308f560c2409e2152fc7b3a7b5c38bb/modules/internal/ChapelArray.chpl#L1052

Do all well-behaved data structures / collection types need to have similar behavior? Is it asking a lot of data structure authors to define these? Note that `shouldReturnRvalueByValue` is an undocumented function internal to the `ChapelArray` module. For the most part, it amounts to checking if the type is trivially copyable. So, the current definition is probably not reasonable if we consider adding something like `int(4096)` to the language, because we would probably prefer to return such a type by `const ref` rather than copying it unnecessarily. Arguably, we have that problem already today with a large tuple like `64*int`.

Currently, the language defines the default intent [with a table](https://chapel-lang.org/docs/language/spec/procedures.html#abstract-intents-table) that varies depending upon the type. Perhaps, if we had a different intent, it would be suitable as the default intent for all types.
 * That would help with constrained generics. When working with a constrained generics, the intent can't vary based on the type. The function signatures in interfaces / constrained generics need to use one intent for all types. See also #16988.
 * It might help with larger integer types, such as `int(128)` and `int(4096)`, it would seem to add a performance problem if we pass these by `const in` even when they are large. Of course, we could also update the intents table to say `int(128)` and smaller are passed by `const in` by default and `int(4096)` and bigger are passed by `const ref`. But would that be too confusing?

Lastly, another problem we have faced is that when writing a data structure that stores `owned` elements (e.g., a list or map), there are two different operations that one might want to do when retrieving an `owned` element:
 * return an `owned` by value & remove it from the data structure, or
 * return a borrow of the class, where currently we tend to write this as returning a `const ref` for consistency with other types. But, a `const ref` to an `owned` adds indirection that is not really necessary.

Similarly, in an argument passing context, a formal like `const ref arg: owned MyClass` is basically functionally equivalent to passing a borrow.

### Why is `const ref` different from passing by value anyway?

It's relatively easy to write programs that differ in behavior depending on whether or not the default intent means `const in` or `const ref`. Here is one such example:

``` chapel
var global: int = 1;

proc f(arg) {
  global = 2;
  writeln(arg); // Does this print 1 or 2?
}
```

It's possible to write such examples that involve many tasks and synchronization, as well. It is unclear to me if these programs are curiosities or if they express a pattern programmers need to rely on.

There is a similar point for returning, where whether returning by value or `const ref` can change behavior. Consider for example a distributed array `A`. `A[i].locale` probably needs to use the `const ref` return intent, to correctly compute the locale of the value; in contrast, returning by value would lead it to always evaluate to `here`.

### Proposal: a new intent

Here I am supposing that we add a new intent. I will call the new intent `cvref` here, but I am assuming that if we investigate this direction further we will come up with a better name for it. In later discussion, there is a proposal to have the `const` intent mean `cvref` instead of what it means today.

The core concept of cvref can be summarized as this user-view: *`cvref` means "I don't care if it's `const ref` or `const in` or something in-between"*. In other words, it is up to the implementation what `cvref` means.

The `cvref` intent means that it is either a `const ref` or a value, or a combination of the two (for owned/shared), but that determination is made late in compilation (after resolution) so as not to impact resolution itself, and it will depend on the type. The `cvref` intent can be used as a formal intent and returning intent (and, potentially, as a way to declare a variable, if we like).

A value returned by `cvref` intent is not mutable (in other words, it is inherently `const`).

For types that are trivially copyable and small (such as `int`), `cvref` would mean *by value*. For types that are not trivially copyable (such as `string`) or types that are large (such as `int(4096)`), `cvref` would mean the same as `const ref`. A starting point for the proposal for *too large* would be something that has a memory representation larger than 4 pointers (so `int(256)` would be the largest that gets *by value* treatment but anything larger would use `const ref`).

Additionally, `cvref` would have special behavior for `owned` and `shared`. These types are not trivially copyable, but nonetheless `cvref` would arrange to pass them / return them as shallow copies of their implementing record. Another way to view that is that after type and call resolution, an formal argument like `proc f(cvref arg: owned MyClass)` will be taken to mean the same as `arg: borrowed MyClass`. Here the `borrowed` forms the instance pointer that is the relevant value for an `owned` when ownership transfer is not occurring. Similarly, a function returning an `owned MyClass` by `cvref` intent would effectively return a borrow. For `shared`, because it's possible to add a new variable that also shares & that requires incrementing the reference count, the `cvref` would become the combination of the `borrowed` value and the pointer to the reference count. Since both of those are fields in the record implementing `shared`, a shallow copy will do it. Note that these shallow copies will be added after type and call resolution and they will not deinitialized.

(Note also: We had previously some special rules where passing an `owned MyClass` to an argument like `proc g(arg)` would pass a borrow; however this made a confusing exception to the normal behavior of generic functions, where they are instantiated with the type they are passed. This proposal avoids that issue by leaving the type the same as it is today with `const ref` intent; but then adjusting the program representation to optimize this pattern after the fact)

When used in a return-intent overloading context, a `cvref`-returning overload would count the same as one returning by value. It'd be an error to define both a `cvref`-returning overload and one returning by value.

It is an open question whether we would publish the `cvref` implementation rules or if we would just say it is implementation defined, within some potential possible behaviors, in the spec.

### How would the proposal help?

It would optimize some passing and returning cases while keeping the language consistent. It would offer similar benefits to the [Ada](http://archive.adaic.com/standards/83rat/html/ratl-08-02.html) strategy but potentially without the drawback of having program behavior be implementation-defined. It offers a way to extend the benefits of the current default intent in Chapel to:
 * returning data structure elements
 * `owned` and `shared`
 * and large numeric types.

Data structures wishing to define reasonable accessors would just write these two:

``` chapel
// returns a mutable reference to an element
proc ref myList.this(idx) ref { ... }
// returns a value / const ref as appropriate
inline proc ref this(idx) cvref { ... }
```

(If they are distributed data structures, they would also need to write a `const ref` returning accessor, to make `myDataStructure[i].locale` work as one might expect).

These will work reasonably as newer types are added such as `int(4096)`, will work reasonably with large tuples, and will work more optimally with `owned` elements in the collection (by returning `borrowed`).

It would allow an easy work-around for the issue with passing a child class to a formal expecting a parent class, if the `cvref` intent is used  -- or if we change the default intent for `owned` and `shared` to `cvref` (relevant issues about that problem below)
 * #20513
 * #17097
 * #8489

It helps with constrained-generics, because `cvref` can be type checked in a type-independent manner, even though the behavior can depend on the type, because the difference does not impact type and call resolution. So, `cvref` could be used in constrained-generics function signatures just as it can be used elsewhere (see #16988). 

It can help to unify some of the special handling that the compiler currently does for array/domain/distribution especially around `on` statements and task functions. (These types use record-wrapped classes, and the record itself is immutable. Using a shallow copy of this record allows for communication optimization).

### Going Further

If this approach seems tenable, we can consider taking the proposal further.

Could the default intent for all types be `cvref` or, potentially, have the same behavior as `cvref`?

Could `cvref` replace the `const ref` intent? Could `const ref` mean `cvref` as described above? (If we went that far, we'd have to figure out how to handle `A[i].locale`, since AFAIK that requires returning a real `const ref` not one that might be a value).

If we had `const ref` mean the `cvref` as described above only for owned/shared classes, would the behavior of the below program be too strange?

``` chapel
class MyClass { var x: int; }

var global: int = new owned MyClass(1);

proc f(const ref arg: owned MyClass) {
  global = new owned MyClass(2);
  writeln(arg.x); // Does this print 1 or 2?
}
```

Or, what about having `const` mean `cvref`? (Would that be too weird in a return intent context?) This idea is a bit similar to the idea of making the blank intent be `cvref`.

### Language Stability Impact

This change would be a breaking change if we choose to change the default intent for `owned` and `shared` to `cvref`. Such a change is unlikely to have negative consequences in practical applications, but it is certainly possible that it could introduce problems.

We can consider changing the default intent / `const` intent for `owned` and `shared` to match this behavior without creating a new intent. That approach leaves for the future two things: 1) how to write an explicit intent that matches and 2) how to get the `cvref` behavior described above when returning.

For most other types, `cvref` would (by design) match the current default intent, so it would be up to us if we choose to describe the default intent in terms of `cvref` or not. (The exception are arrays/record receivers discussed in #21398 and sync/single/atomic which are `ref` but that doesn't have its own issue).

**Comment by cassella** [comment]
> (If they are distributed data structures, they would also need to write a `const ref` returning accessor, to make `myDataStructure[i].locale` work as one might expect).

Wouldn't all data structures with accessors need that?  For e.g. `myBytes[i].locale` to be the same as `myBytes.locale`, `bytes.this()` couldn't return a copy, even though a byte is small enough?

**Comment by mppf** [comment]
The point is that it's not relevant for all data structures. If `myBytes[i]` always returns a copy (of something) rather than a reference, then IMO it's not surprising that `myBytes[i]` would evaluate to `here`. I'm arguing that the main reason why one would want to literally write `myCollection[i].locale` is if there is any possibility that `myCollection.locale != myCollection[i].locale`; in other words, it is a distributed collection. (Here I am ignoring the possibility that the elements are class instances, which can behave differently). And, of course, not all data structures are distributed.

**Comment by vasslitvinov** [comment]
Discussing this with Michael:

To summarize, `cvref` is `const` with tweaks, except it is distinct from any concrete intent during resolution.

If we like it, we can change the meaning of `const` to mean cvref. This meaning will apply when `const` is used as a formal, return, and yield intent and possibly as a variant of `var`.

My further thoughts:

If we do away with "ref maybe const" and friends in #21398, we can further simplify our intent table to remove the default intent. Perhaps rename `const` from "abstract intent" to "adaptive intent".

As to `myBytes[i].locale`, we may need a dedicated operation like `myBytes.localeOf[i]`. This may be a good idea in any case because today even `myBytes[i].locale` is unreliable when the collection stores classes. (Or is this a more general problem with `.locale` query.)

**Comment by mppf** [comment]
It is interesting that if we consider changing the meaning of the `const` intent (and the default intent in most cases), we might be able to do support the `cvref` behavior for formal intents as a documentation-only change. The practical impact of that would be that the behavior of `const` being `const in` vs. `const ref` vs. something in-between becomes implementation-defined and won’t be described by the spec anymore with per-type tables. If we made that spec change, we could update the implementation for `owned` and `shared` & do so without technically changing the language, since it will be only changing implementation-defined behavior.

**Comment by vasslitvinov** [comment]
I wasn't clear that the proposal includes making "value vs. ref" in `cvref` implementation-dependent. I am open to this idea. However I suggest that we make a few cases predetermined, for example:
* for ints it is "value"
* for arrays it is "ref"
* for classes it is a borrow
* the user can request value or ref for their record type

**Comment by mppf** [comment]
> for ints it is "value"

I do not think we want that behavior for all `int` widths in the potential future when we have `int(4096)`. However we could say for the current sized ints it is value.

Personally, I am thinking that the situation is simpler to understand if we simply do not specify it at all. Of course we can make the behavior in practice be more or less what it is today for ints etc.

**Comment by vasslitvinov** [comment]
Here is a snapshot of how I think about "cvref" and its key open issues.

#### What is cvref?

Cvref is like today's `const` argument intent in that it can mean `const in` or `const ref`. Cvref is different from today's `const` in that it does not guarantee whether the formal argument will or will not track concurrent changes to the actual argument. When tracking or not tracking needs to be assured, `const ref` or `const in` needs to be used explicitly.

The compiler does not treat cvref as `const in` or `const ref` during resolution. Code that cannot be compiled without distinguish between `const in` and `const ref` results in a compilation error. This can happen, for example, if the result of a return-intent-overloaded function is passed to a `cvref` formal.

#### What do I like about cvref?

It allows the compiler to pass by value instead of by reference in more cases. That benefit optimization.

It helps with early resolution of interface generics.

#### Open questions gating acceptance of cvref

How practical is the rule "he compiler does not treat cvref as `const in` or `const ref` during resolution" ? That is, what are the hard-to-handle corner cases? how doable is it to make this change in the compiler given our tight schedule?

Do we want to change the meaning of the `const` intent to mean "cvref"? We probably have to because we do not want to have two intents that are similar yet subtly different. If not `const`, then what to call "cvref" in user code?

How to write a variable that stores the result of a function that returns by cvref intent? For example, `const x = f();` may result in an unwanted copy when f() returns a reference. This is particularly relevant for interface generics where this may be a common case. Perhaps, although inelegant, it could be `const ref x = f();`. If f() returns by value, `x` is a reference to a compiler temp storing the returned value. The compiler can then optimize the dereferences of `x`.

Analogously, how to reason about the index variable of a loop whose iterator yields by cvref intent, especially in an interface-generic function? Should the index variable be a `const` or a `const ref` ?

How acceptable is the borrowing semantics when an owned or shared is passed by cvref? The proposal allows the formal argument to behave like a `const ref` owned during resolution, while snapshotting the class reference during execution.

How about allowing the program to snapshot the value during execution in other cases where cvref means `const ref` ? For example, when a large record is passed by cvref however just one field of it is referenced multiple times in a region of code, it may make the program execute faster if that field is loaded just once.

Should the choice of `const in` vs. `const ref` be determined strictly by the type, just like it is for today's `const` ? It may be compelling to allow context-depending semantics, for example use `const in` when passing an expiring value. However this is not a real "open question", as the design subteam favors "strictly by the type." Then again, what does it mean w.r.t. allowing to snapshot the value when cvref means `const ref`, as discussed above?

How can we implement the principle "there should be a concrete intent for each abstract intent" for cvref? This principle may not make sense here. As long as we define a Java.

How can we implement the princple "there should be a way to specify explicitly the default intent"? Originally cvref was proposed to be the default intent, to reduce the complexity of our intent table. However, we want the default intent to be non-const for atomics, syncs, singles, and potentially for arrays and record `this` (see #21398). Using `const` or a "cvref"-like name to mean "non-const" would be conterintitive for users. So we will need exceptions to the rule "the default intent is cvref" for these types.

**Comment by mppf** [comment]
> How to write a variable that stores the result of a function that returns by cvref intent? For example, `const x = f();` may result in an unwanted copy when f() returns a reference. This is particularly relevant for interface generics where this may be a common case. Perhaps, although inelegant, it could be `const ref x = f();`. If f() returns by value, `x` is a reference to a compiler temp storing the returned value. The compiler can then optimize the dereferences of `x`.

Of all the concerns listed, this is the most concerning to me, but I think it's an existing problem with the language / a side issue for this proposal. In particular, if you have `proc f(const arg)` then, supposing we pass a record, `arg` is a `const ref`. But if I write `const x: myRecord = ...` then `x` is a value, not a `const ref`. So we have two different meanings for the keyword `const` in different places. I have not heard anyone complain about this particular problem before, but it seems to be a potential issue in understanding. I think people probably don't usually fall into that trap because when teaching about variables, it's normal to introduce `var` first and then say "You can also use `const` if the variable does not change". So people are already thinking of values (vs references). If we wanted to avoid the issue, we would make people write `const var x;` instead of just `const x;` for variables. (Or do something else to differentiate).

Back to the main point here; if capturing the result of a function that returns by rvref intent, `const ref x = f()` seems acceptable to me. But, if we wanted to rely less on `const` meaning different things in variable declaration and formal contexts, and we asked people to write `const var`, then we could use `const` to mean a `cvref`. I.e. `const x = f()` would capture `x` as a `cvref`. But `const var x = f()` would capture the value.

All that said, I am uncertain if it's better to leave `const` variables alone or to solve the above issues by differentiating (perhaps by asking people to write `const var`).

**Comment by bradcray** [comment]
I'm not so wild about introducing `val` for some of the historical reasons Vass cites above combined with preferring to reserve `val`/`value` as a `param` replacement if we introduce it at all.  

If I were to do anything here, I _might_ permit `const var` as a long-hand way of saying what we've traditionally thought of `const` as meaning and as a sibling to `const ref` and then re-interpreting `const` as "I can't be bothered to tell you which `const` I mean and will rely on the compiler to choose the right thing based on the initializing expression."  That said, I'm not sure I like it—just that I like it better than `const` + `val` + `var`.

**Comment by vasslitvinov** [comment]
I am game for `const` + `const ref` + `const var`. I would expect that `const` will suffice for a beginning Chapel programmer without the need to write `const var`.

The compiler will need to do a little more work in this new world to establish that a given `const` thing is immutable, in order for some optimizations to get triggered. This sounds feasible.

The next step to move forward is to rename the argument intents `in` to `var` and `const in` to `const var`. This will bridge the gap we have between variable kinds and argument intents. (`inout` --> ?; `in` task intent vs. `var` task-private variable?)

**Comment by bradcray** [comment]
> I am game for const + const ref + const var.

I would suggest forking this off to an issue of its own if you / anyone wants to champion it.  I feel like it came up here as something of a sidebar.

> The next step to move forward is to rename the argument intents in to var and const in to const var. 

I am not in favor of this change, personally.

**Comment by vasslitvinov** [comment]
> > I am game for const + const ref + const var.
> 
> I would suggest forking this off to an issue of its own if you / anyone wants to champion it.  I feel like it came up here as something of a sidebar.

This surely needs to go into its own issue. However it is directly related to the meaning of `const` being discussed here.

**Comment by e-kayrakli** [comment]
The last comment is quite interesting, @mppf. Do you think the ideas are still applicable after having finalized the design? This is quite interesting because we've observed that Chapel compiler doing more aggressive LICM is really helping GPU performance. But at the same time anything involving passing arrays to functions can throw it off today:

```chpl
on here.gpus[0] {
  foreach i in 1..10 {
    foo(A);  // it is too challenging for LICM to peel off the metadata here 
  }
}
proc foo(ref A: []) { }  // this function has to do a lot of
                         // pointer chasing to get to the data
```

But the way you describe it, this "optimization" can be a more fundamental part of lowering Chapel arrays, which in turn can make LICM more powerful, potentially without changing it at all.


> proc computeElementContribution(const in A: cvrefDRArray, const in B: cvrefDRArray, i: int) {

Here, is there any specific reason we are packing the instance and data together? Instance is not used, so what's the point passing it?

**Comment by mppf** [comment]
@e-kayrakli - I'm going to close this issue because 1.32 includes the this idea as spec changes.

See also:
 * [the language specification section on `const` intent](https://chapel-lang.org/docs/language/spec/procedures.html#the-const-intent)
 * [the 1.32 release notes slides](https://chapel-lang.org/releaseNotes/1.31-1.32/01-language.pdf) starting on slide 39.

I've created https://github.com/chapel-lang/chapel/issues/23685 for the future work of adding checking.

To answer your questions specifically:
 * AFAIK at this point, we can start to implement such optimization. However, I think we need to start with adding the checking (#23685) to make sure that the request we are making of users is practical.
 * I demonstrated `cvrefDRArray` including the instance and data for generality. In particular, some array operations would need the instance. However, this is just a sketch, and in practice we could handle it with additional arguments (and then rely on the optimizer to remove unused arguments, say).
