### ISSUE TITLE
Should attributes have some way to indicate which tool they belong to?

### ISSUE THREAD

**Issue by arezaii** [chapel-lang/chapel#21493]
In https://github.com/Cray/chapel-private/issues/3974#issuecomment-1349703579 I proposed adding some identifier to attributes which would specify that this attribute is destined for a specific tool. The idea is similar to a namespace to distinguish between attributes the `chpl` compiler should act on and those it does not need to worry about. 

This idea is a clone of tool attributes from Rust: https://doc.rust-lang.org/reference/attributes.html#tool-attributes

Today we have attributes which are specific to the `chpl` compiler, such as `@unstable` and `deprecated`, and one ("no doc") that is specific to `chpldoc`, which is currently a pragma but https://github.com/chapel-lang/chapel/issues/21485 proposes to make it an attribute as well.

If we don't do something to differentiate attributes, the `chpl` compiler will not know when an attribute is a typo that it should complain about, or if it's just something it doesn't need to worry about. Adding a tool-space to the attribute allows the compiler to gleefully ignore any attributes that are prefixed with an identifier and a dot. For example, in https://github.com/chapel-lang/chapel/issues/21485, I propose we replace `pragma "no doc"` with `@chpldoc.nodoc()`, which would indicate this is an attribute for `chpldoc` and that the `chpl` compiler does not need to validate the syntax or number of arguments, etc. 

Having the tool-space also allows developers of tools that use the compiler library to add attributes for their tools without having to make `chpl` aware of how to handle it. 

This idea got some support in the comments after the draft proposal, https://github.com/Cray/chapel-private/issues/3974#issuecomment-1349703579, but I'd like to put it out in front of more eyes in case there's any concern.

Current:
```chapel
pragma "no doc"
proc undocumentedProc() {}
```

Proposal:
```chapel
@chpldoc.nodoc
proc undocumentedProc() {}
```

**Comment by arezaii** [comment]
Question from the design discussion:

> Are there some attributes we should allow future compilers to ignore? 

One way we could potentially accommodate that is by prefixing optionally supported attributes with our own `chpl` toolspace name, while leaving the required ones without a prefix.

Another way we could address this is by adding a symbol, such as a `!` to the attribute name, which would indicate the attribute is required to be supported (or ignorable, depending on the meaning we want to give to `!`)

**Comment by vasslitvinov** [comment]
I did not follow why we need to decide if future compilers should or not ignore a given attribute.

Perhaps I do not understand the meaning of "ignore" ? What is it? At the end of the day, a Chapel program defines certain observable behavior. It does not matter whether any part of the program is ignored or not as long as the behavior is preserved. For example...

If a future compiler's optimizer determines that it is better not to inline a function that is marked with `inline`, that's perfectly OK with me. I am fine if a future compiler ignores a vectorization attribute or lack thereof. It may actually HAVE to ignore it if the hardware does not provide vectorization. If an executable allocates a class instance on the stack instead of the heap and foregoes the class ID header, that's OK as long as the program works the same in observable ways.

The future compiler will have a lot of Chapel's corner cases to deal with. Adding to that some number of attributes that need to be parsed is a small potato in that pot.

**Comment by vasslitvinov** [comment]
I support the requirement for the compiler to verify that a non-toolspaced attribute is legal / one of acceptable attributes with an acceptable number of arguments. In order to help avoid typos and such.

Next, what if somebody mistypes a tool's name? How should that be detected? I am OK for us to ship Chapel 2.0 such that it accepts only a fixed set of tool names, plus an option to add other names to be accepted.

**Comment by arezaii** [comment]
> what if somebody mistypes a tool's name? How should that be detected?

This is a good question and does need some kind of solution. I'd really like to avoid making the tool names part of the compiler. With that goal in mind, would it be acceptable to provide a flag to list all the expected tool names when compiling?

We could discuss whether or not to include `chpldoc` by default.

Other possible options that I don't like as much:

1. centralize all the tool names in the compiler, which will then verify tool names (optionally?), and top-level attributes, but not attributes that belong to tools.
2. rely on some outside linter tool to check tool names
3. ignore misspelled tool names

**Comment by lydia-duncan** [comment]
> This is perhaps a long way of saying that I suggest we do not worry at this point about separating required from optional attributes.

If we intend to mark some attributes as optional in a specific way that is different than how they would be marked today, any code that uses them will need to be updated when that changes.  That makes distinguishing between them a breaking change if the attribute has already been added.

My expectation, however, is that the attributes we add before 2.0 will be limited to a specific subset that are necessary to support 2.0, e.g. `@unstable` and `@deprecated`, or some obvious ones that we know we will want to support, e.g. `@chpldoc.nodoc`.  That's part of why I was proposing we distinguish between ones we expect every Chapel compiler to support and ones that we think are optional - I would expect every Chapel compiler to support `@unstable` and `@deprecated`, so I wouldn't expect them to need the distinguishing feature, meaning we could consider them stable for 2.0.

**Comment by arezaii** [comment]
> it'd be interesting understand if Rust has a solution to a misspelt tool space.

See the proposal for long term support at https://rust-lang.github.io/rfcs/2103-tool-attributes.html

The takeaways I got:
 1. top-level space is reserved. But they also allow the tool name `rustc`
 2. `rustc` maintains an allow-list of tool names
 3. you can opt-in to additional tool names
 4. if you compile code with unrecognized tool names or top-level attributes, you will get an error

To do something similar we could have a sanctioned list of tool names the compiler knows about, `chpldoc` for example, and then if a developer comes along and makes their own tools, they could use a flag to add entries to the list of expected/known tools at compile time. The list of sanctioned tools could grow over time, if needed.

> That's part of why I was proposing we distinguish between ones we expect every Chapel compiler to support and ones that we think are optional.

I would expect the list of attributes all Chapel compilers _must_ support as something we'd document as being part of the language. Then we could use the `chpl` tool name to indicate attributes which are just parts of our compiler, maybe `@chpl.unroll(_N_)` is an example.
This carries the expectation that if a future compiler comes across a top-level attribute it doesn't support, it would (at least) warn the user.

**Comment by bradcray** [comment]
> Today we have attributes which are specific to the chpl compiler, such as @unstable and deprecated

Just to make sure there's no understanding: doesn't chpldoc consume and act on these as well?  (by putting the text into the doc strings).  In asking, I'm not suggesting that's necessarily a problem, just noting that they're not specific to the chpl compiler in the sense of "not intended for other tools to look at and consume as well."  I don't know whether that suggests that top-level (non-toolspace-qualified) attributes are intended to be consumed by all tools by design, or whether it just means that any tool is able to consume them if it wants to (and would be curious what others think).

Capturing an alternative to having the compiler and/or other tools enumerate all attributes for spell-checking purposes, we could have it complain about ones it doesn't recognize (maybe combined with some form of fuzzy matching to see if it looks like a misspelling of another one), and then have a way of disabling those warnings, either via a big hammer or by providing a list of ones not to warn about (which may start to get close to what Ahmad is describing as the Rust approach?).  Again, I'm not certain what the implications are for other tools:  They should also warn about unrecognized top-level attributes?  Or they should only warn about ones within their toolspace?

Part of my allergy to having a list of all known attributes for the purposes of spell-checking is that it (seems to) effectively make those attributes part of the language in the sense of "these must be able to be handled or recognized in order for you to be a legal Chapel compiler / tool."  And maybe that's OK, but it makes me uneasy for some reason.

**Comment by lydia-duncan** [comment]
> I don't know whether that suggests that top-level (non-toolspace-qualified) attributes are intended to be consumed by all tools by design, or whether it just means that any tool is able to consume them if it wants to (and would be curious what others think).

That's a good point.  I personally lean towards "any tool is able to consume them if it wants to".

> Capturing an alternative to having the compiler and/or other tools enumerate all attributes for spell-checking purposes, we could have it complain about ones it doesn't recognize (maybe combined with some form of fuzzy matching to see if it looks like a misspelling of another one), and then have a way of disabling those warnings, either via a big hammer or by providing a list of ones not to warn about (which may start to get close to what Ahmad is describing as the Rust approach?).

I was viewing "compiler complains about ones it doesn't recognize" as sufficient for spell-checking purposes, but others may feel differently.

> Again, I'm not certain what the implications are for other tools: They should also warn about unrecognized top-level attributes? Or they should only warn about ones within their toolspace?

If we go the route of other tools having to support all the top level attributes, then I would be in favor of them also warning when they get one they don't recognize.  If they only support specific top-level attributes, then I wouldn't feel the need for them to check if a top-level attribute they don't recognize matches one they don't support.

**Comment by arezaii** [comment]
> doesn't chpldoc consume and act on these as well?

Yes and that's a good point about top-level attributes, I would expect them to be optional for other tools to use, but for other _compilers_ I would expect them to be supported, or at least warn about those they don't support.

> I'm not certain what the implications are for other tools: They should also warn about unrecognized top-level attributes? Or they should only warn about ones within their toolspace?

I don't think other tools should be expected to handle top-level attributes, but they could choose to (assuming we documented the top-level ones in the language spec or somewhere). My thoughts are that tools are only responsible for things in their toolspace, and can optionally act on other attributes as appropriate in the realm of the tool. If a tool is built upon the dyno library, then we could provide the spell-checking of top-level attributes and specifying additional toolspace names from there.

Maybe it's a good exercise to imagine a universe where there were someone created an alternate Chapel compiler,  we'll call it `chplr`, and another person created a linter for Chapel we'll call `chpllint`. 

In this universe:
- `chpl` and `chpldoc` are maintained by our team, but `chplr` and `chpllint` are both developed by independent third-parties. 
- top-level attributes `@unstable` and `@deprecated` are documented as language features
- `chpl` defines one special attribute `@chpl.unroll(N)`

- `chpllint` defines one attribute, `@chpllint.ignore` which is used to ignore linter evaluation on a piece of code

- `chplr` has one specialized attribute for memory alignment `@chplr.align(N)`
- `chpldoc` has one specialized attribute to prevent generating documentation, `@chpldoc.nodoc`

In this example universe, `chpl` only needs to understand `@unstable`, `@deprecated`, and `@chpl.unroll`. It should spell check for these, and warn about misspellings of the two top-level attributes, the single `@chpl.unroll` attribute, and `@anytool.anyattribute`, where `@anytool` is not `@chpl` (we could argue about if it should warn about `@chpldoc.` attributes by default). 
A user could turn off these warnings by specifying an ignore-list of toolnames to accept, maybe something like `--using-attribute-toolspace=chpldoc --using-attribute-toolspace=chpllint`. The user could not specify a top-level name, like `@myCustomAttribute` to ignore, because those are reserved for our use.

With those flags, `chpl` would also ignore and stop warning about `@chpldoc.anyattribute` and `@chpllint.anyattribute`. `chpl` would still warn on `@chplr.align`. 

`chplr` would be responsible for implementing `@unstable` and `@deprecated` as they are language features (I suppose it could also just warn the user that it doesn't support those). It would be optional to handle `@chpl.unroll`. `chplr` could not add any top-level attributes, but would be free to implement anything under `@chplr.`. 

`chpllint` would be free to evaluate or ignore any attributes, but it should spellcheck `@chpllint.ignore`. The developer of `chpllint` could decide which, if any, attributes they wanted to support. 

`chpldoc` would implement support for `@unstable` and `@deprecated` and its own `@chpldoc.nodoc`, but ignores other attributes. 


Maybe we can use these hypothetical tools as common placeholders when we're discussing toolspace names and attributes.

**Comment by arezaii** [comment]
closing since https://github.com/chapel-lang/chapel/pull/21425 implements the concept of a _tool name_ as described here

**Comment by bradcray** [comment]
Catching up on mail belatedly...

> top-level attributes @unstable and @deprecated are documented as language features

I'm not particularly satisfied by this because if they're part of the language, I don't think they shouldn't be attributes.  Maybe saying a similar thing with a phrase that doesn't rub me as badly, "They are attributes that all conforming Chapel compilers are expected to be familiar with."?
