### ISSUE TITLE
Unexpected type aliasing between `range` and `domain`

### ISSUE THREAD

**Issue by milthorpe** [chapel-lang/chapel#21537]
Assigning a `range` literal to a variable of unconstrained `domain` type appears to change the type of the variable to `range`. For example:

```
var aDom: domain = 0..#N;
writeln(aDom.type:string);
```

The output of this code is `range(int(64),bounded,false)`.

I was actually a little surprised that this compiled, as I didn't think that there was a subtype relation between `range` and `domain`. I would have guessed that this was 'syntactic sugar' to allow easy initialization of domains, except that I didn't expect the type of `aDom` to change. For example, if the range expression is enclosed in curly braces it becomes a [rectangular domain literal](https://chapel-lang.org/docs/language/spec/domains.html#rectangular-domain-values), and the output of the code is `domain(1,int(64),false)` as expected.

If I change the type definition to `domain(1)`, I see the output I expect: `domain(1,int(64),false)`.

Interestingly, the following code doesn't compile at all:
```
var aDom: domain = 0..#N;
aDom = {0..#N};
```
The Chapel compiler gives `error: Cannot assign to range(int(64),bounded,false) from domain(1,int(64),false)`

### Configuration Information

- Output of `chpl --version`:
```
$ chpl --version
chpl version 1.29.0
  built with LLVM version 14.0.0
Copyright 2020-2022 Hewlett Packard Enterprise Development LP
Copyright 2004-2019 Cray Inc.
(See LICENSE file for more details)
```
- Output of `$CHPL_HOME/util/printchplenv --anonymize`:
```
$ $CHPL_HOME/util/printchplenv --anonymize
CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: llvm
CHPL_TARGET_ARCH: x86_64
CHPL_TARGET_CPU: native
CHPL_LOCALE_MODEL: flat
CHPL_COMM: none
CHPL_TASKS: qthreads
CHPL_LAUNCHER: none
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: cstdlib
CHPL_GMP: bundled
CHPL_HWLOC: bundled
CHPL_RE2: bundled
CHPL_LLVM: bundled
CHPL_AUX_FILESYS: none
```

**Comment by bradcray** [comment]
Thanks for filing this, Josh!  I've been poking at it since you mentioned it on gitter and have the following notes (not for you, but for other developers following this):

* changing the type specification from `domain` (currently "a completely generic domain") to `domain(1)` (a 1D domain) results in the error:
  ```
  testit1a.chpl:2: error: Illegal assignment to a rectangular domain
  ```
  which is more like the behavior we'd want to see for this test (or, rather, "cannot initialize a domain using a range")
* changing the declaration to `var aDom: domain = 5.67;` results in `aDom` being a `real`, so the error isn't specific to initializing with a range
* I believe that things go wrong in the resolution pass, where the IR changes from
  ```
      (558715 'init var' aDom[182411] 5.67 _domain[176935](?))
  ```
  to:
  ```
     (558715 'move' aDom[182411] 5.67)
   ```
  without also introducing some sort of type-compatibility checks.

**Comment by bradcray** [comment]
I've got a simple (maybe too simple?) fix here that I'm about to run through testing:  https://github.com/bradcray/chapel/tree/error-for-init-generic-domain-with-non-domain

**Comment by bradcray** [comment]
With a minor tweak, the branch is passing testing, and I've opened a PR for it in #21539.  Just need a reviewer now.  Thanks again for bringing this to our attention, Josh @milthorpe!
