### ISSUE TITLE
无法编译

### ISSUE THREAD

**Issue by RainbowTaro2022** [chapel-lang/chapel#21540]
CMake Error at G:/tools/mingw64/lib/cmake/llvm/LLVMConfig.cmake:330 (include):
  include could not find requested file:

    G:/Cone/LLVM/build/./lib/cmake/llvm/LLVMExports.cmake
Call Stack (most recent call first):
  G:/tools/mingw64/lib/cmake/clang/ClangConfig.cmake:6 (find_package)
  frontend/util/linters/CMakeLists.txt:42 (find_package)

CMake Error at G:/tools/mingw64/lib/cmake/llvm/LLVMConfig.cmake:331 (include):
  include could not find requested file:

    G:/Cone/LLVM/build/./lib/cmake/llvm/LLVMBuildTreeOnlyTargets.cmake
Call Stack (most recent call first):
  G:/tools/mingw64/lib/cmake/clang/ClangConfig.cmake:6 (find_package)
  frontend/util/linters/CMakeLists.txt:42 (find_package)

CMake Error at G:/tools/mingw64/lib/cmake/llvm/LLVMConfig.cmake:348 (include):
  include could not find requested file:

    G:/Cone/LLVM/llvm/cmake/modules/LLVM-Config.cmake
Call Stack (most recent call first):
  G:/tools/mingw64/lib/cmake/clang/ClangConfig.cmake:6 (find_package)
  frontend/util/linters/CMakeLists.txt:42 (find_package)

CMake Error at G:/tools/mingw64/lib/cmake/clang/ClangConfig.cmake:15 (include):
  include could not find requested file:

    G:/Cone/LLVM/build/lib/cmake/clang/ClangTargets.cmake
Call Stack (most recent call first):
  frontend/util/linters/CMakeLists.txt:42 (find_package)

-- Using libclang from G:/tools/mingw64/lib/cmake/clang
-- Configuring incomplete, errors occurred!

**Comment by RainbowTaro2022** [comment]
1.The version I'm trying to build is the development version
2.Windows 11 22h2/gcc 12.2
3.Just execute cmake, and I didn't execute anything else

**Comment by RainbowTaro2022** [comment]
G:\Cone\Cmake\chapel>cmake -B build
-- Configuring Chapel version: 1.30.0
-- Reading CONFIGURED_PREFIX
-- previously configured to install to "C:/Program Files (x86)/Chapel"
-- CMAKE_INSTALL_PREFIX is C:/Program Files (x86)/Chapel
-- Installation Mode:
CHPL_DEVELOPER is not set, using OFF
-- No CHPL_LLVM_GCC_PREFIX env var or value given from command line.
%1 涓嶆槸鏈夋晥鐨?Win32 搴旂敤绋嬪簭銆?
Updating build configuration with results from printchplenv:

-- Using Python:
-- wrote git-version.cpp
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) (Required is at least version "1.8.17")
CMake Error at G:/tools/mingw64/lib/cmake/llvm/LLVMConfig.cmake:330 (include):
  include could not find requested file:

    G:/Cone/LLVM/build/./lib/cmake/llvm/LLVMExports.cmake
Call Stack (most recent call first):
  G:/tools/mingw64/lib/cmake/clang/ClangConfig.cmake:6 (find_package)
  frontend/util/linters/CMakeLists.txt:42 (find_package)


CMake Error at G:/tools/mingw64/lib/cmake/llvm/LLVMConfig.cmake:331 (include):
  include could not find requested file:

    G:/Cone/LLVM/build/./lib/cmake/llvm/LLVMBuildTreeOnlyTargets.cmake
Call Stack (most recent call first):
  G:/tools/mingw64/lib/cmake/clang/ClangConfig.cmake:6 (find_package)
  frontend/util/linters/CMakeLists.txt:42 (find_package)


CMake Error at G:/tools/mingw64/lib/cmake/llvm/LLVMConfig.cmake:348 (include):
  include could not find requested file:

    G:/Cone/LLVM/llvm/cmake/modules/LLVM-Config.cmake
Call Stack (most recent call first):
  G:/tools/mingw64/lib/cmake/clang/ClangConfig.cmake:6 (find_package)
  frontend/util/linters/CMakeLists.txt:42 (find_package)


CMake Error at G:/tools/mingw64/lib/cmake/clang/ClangConfig.cmake:15 (include):
  include could not find requested file:

    G:/Cone/LLVM/build/lib/cmake/clang/ClangTargets.cmake
Call Stack (most recent call first):
  frontend/util/linters/CMakeLists.txt:42 (find_package)


-- Using libclang from G:/tools/mingw64/lib/cmake/clang
-- Configuring incomplete, errors occurred!
See also "G:/Cone/Cmake/chapel/build/CMakeFiles/CMakeOutput.log"
[CMakeOutput.log](https://github.com/chapel-lang/chapel/files/10680206/CMakeOutput.log)

**Comment by bradcray** [comment]
@RainbowTaro2022 : At present, Chapel should be built using `make` rather than `cmake`.  Although we use `cmake` under the hood to build the compiler, currently it is `make` that drives the process.  Please refer to the instructions at https://chapel-lang.org/docs/main/usingchapel/QUICKSTART.html for details, including the step prior to running `make` to `source util/quickstart/setchplenv.bash`.

Also, please note that our only experiences using Chapel with Windows systems involve using Cygwin or WSL/ Linux bash shell, so if you're not using either of those UNIX-emulation environments, you are charting new territory here.  Of the two, we believe WSL/Linux bash shell to be the better option since it is more native; that said, we do nightly testing with Cygwin which works—it just tends to be quite slow.

**Comment by RainbowTaro2022** [comment]
> 

How does Windows run the source command?

**Comment by bradcray** [comment]
If using Cygwin with bash or WSL/Linux bash shell, it would provide it.  As noted in my previous comment, we have no experience using Chapel with Windows other than in those two modes.

**Comment by bradcray** [comment]
@RainbowTaro2022 : I wanted to check in on this issue and see whether you were able to make progress (either by using Cygwin or WSL/Linux bash shell; or by somehow getting things running on Windows), whether we could help more here, or close this issue if not.  I should have mentioned earlier, but https://github.com/chapel-lang/chapel/issues/12453 is an issue about supporting Chapel natively on Windows (albeit one that hasn't received much attention because we haven't had sufficient interest from users to work more on it).

**Comment by bradcray** [comment]
I'm going to close this due to inactivity and lack of a clear action that would logically close this issue short of solving #12453.
