### ISSUE TITLE
Design: Domain vs. Range Slicing,  Part 2

### ISSUE THREAD

**Issue by vasslitvinov** [chapel-lang/chapel#21605]
In #12936 we decided that slicing an array with a domain vs. with range(s) should behave differently w.r.t. the domain map of the resulting slice.

This issue proposes that we do the same when slicing a domain, namely:

| operation | domain map of the result |
| --- | --- |
| `D1[r...]` where D1 is a domain and r... is a range or ranges | the domain map of D1 |
| `D1[D2]` where D1, D2 are domains | the domain map of D2 |

Pros: consistent with array slicing
Cons: ?

**Comment by bradcray** [comment]
I think this is an intriguing proposal from a consistency argument.  I'd be curious to put in a check that flags cases in the test system whose behavior would change.  Note that this may require more than making the change and seeing what fails, since the differences may be only performance-oriented; so I'd make the check specifically flag cases where D1 and D2 don't share the same (or equivalent) domain maps.

If we found that the proposed behavior was worse in some way, one rationale for making it inconsistent with array slicing is that array slicing creates an alias to an existing array whereas domain slicing creates a new domain value (so they're already asymmetrical, and it may be argued that there's a reason making them asymmetrical in this regard may be preferable as well—such as that domain storage is cheap, so its locality doesn't matter as much).

That said, I agree that consistency in this regard seems more attractive, barring cons / surprises that I haven't thought of.

**Comment by bradcray** [comment]
I ran into this issue when reviewing #22655—specifically, I read a `DistDomain[DRDomain]` slice and got nervous that it would localize the domain based on what happens with arrays, so was surprised when it didn't (though what the code wanted was for it not to).  So I think I'm still in favor of changing it for consistency, and maybe even more so now that I've been confused by the inconsistency (barring surprises in testing).

**Comment by lydia-duncan** [comment]
@vasslitvinov - I see you've added this posthumously to Cray/chapel-private#5206.  Does that mean it's still under discussion or being implemented?  I wasn't sure from the sprint task

**Comment by vasslitvinov** [comment]
Our conclusion is "accept this proposal, unless we hit show-stoppers when implementing it."

**Comment by bradcray** [comment]
I was thinking about this a bit more last night and wondering "Is it too weird, when both the slicer and slicee are of the same type `Dom1[Dom2]`, to have the slicing domain control the distribution of the result when the slicee seems like the dominant expression in this idiom.  That is, given: `MyBigBlockDistDom[MyLocalDom]`, it seems a bit odd to say that the distribution (or lack thereof) of the slicer `MyLocalDom` "wins" over that of the slicer.

Moreover, if one wanted the other effect, it would be simple enough to switch the order of the domains, to `MyLocalDom[MyBigBlockDistDom]` since they're both of the same type.

The reason that this difference in behavior with distributed arrays could be justifiable is that in the array slicing case, the two arguments are not of the same type (one's a domain, the other's an array), so it is not possible to reverse the arguments to get the different behavior—that is `MyLocalDom[MyBigBlockDistArr]` isn't supported.

For that reason, this issue could be viewed as "In a case where one domain is used to slice the other, whose distribution is most natural to preserve for the result:  `D1[D2]` where my intuition would be "D1's".

At the same time, the symmetry with array slicing is attractive as well.  That is, `A[D]` is related to `A.domain[D]`.

As a result, I feel very uncertain what the right thing to do here is (but am not second-guessing our array slicing choice over this).

An option to punt the decision down the field would be to make domain slicing unstable _in the event the two don't share the same distribution_.  I wonder how many instances of this we would find in practice.

**Comment by vasslitvinov** [comment]
As I was implementing the new behavior in #23250, I realized that there is a notable difference between array vs. domain slicing:

* `A[D]` does not relocate the array elements. Therefore it preserves at least partial locality information, i.e., the placement of the array elements. I conclude that because of this the change from `A[D]` to `A[(...D.dims())]` was not needed in #12931.

* `D1[D2]` discards the placement of the indices in `D1` entirely, under the new semantics. Therefore an additional effort is needed if this placement needs to be preserved. Perhaps simply switching the order of the domains?

Other than that, #23250 shows that we almost never use non-trival domain/domain slicing.

> if one wanted the other effect, it would be simple enough to switch the order of the domains

I was fearing that the array bounds check would kick in. However for domain slicing, like for range slicing, it does not. This means that I should be able to do without `[(...D.dims())]` in #23250, instead simply switching the argument order.

**Comment by bradcray** [comment]
Here's a case that I've been thinking about today, though I don't know that it's all that compelling:

Say you had a block-distributed array and wanted to slice it in a way that preserved the distribution of the resulting expression, but the subset of indices you were slicing with happened to be a local domain.  So you wouldn't want to write:

```chapel
MyBlockArr[MyLocDom]
```

because that would (conceptually) localize the result (for the sake of iteration, assigning the result into another variable, etc.).  So, then, which of the following rewrites would seem more obviously to result in a block-distributed result:

```chapel
MyBlockArr[MyBlockDom[MyLocDom]]
MyBlockArr[MyLocDom[MyBlockDom]]
```

For my intuition, it's the first.  (This is probably not surprising, given my statement above:

> That is, given: MyBigBlockDistDom[MyLocalDom], it seems a bit odd to say that the distribution (or lack thereof) of the slicer MyLocalDom "wins" over that of the slicer.

).

**Comment by vasslitvinov** [comment]
Given the above discussion, @bradcray and I conclude that we want to keep the existing domain slicing rules.

I am closing this issue as resolved. I am closing my implementation #23250 of an earlier proposal in this issue without merging.
