### ISSUE TITLE
Meaning/value of CHPL_HOME when using a `make install` build?

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#21622]
A user who has been using the `./configure` + `make install` build of Chapel expressed confusion about what `$CHPL_HOME` means in that setting.  For example, our compiler sometimes generates the message:

```
error: The runtime has not been built for this configuration. Run $CHPL_HOME/util/chplenv/printchplbuilds.py for information on available runtimes.
```

For a developer, or potentially a user building from source, this path may make sense, but a user using a pre-installed version of Chapel may not have any idea what $CHPL_HOME means—and in a `make install` setting, what it maps to is not entirely clear.

Should we:
* have such compiler-generated messages use a full path instead?  (e.g., 

  ```
  error: The runtime has not been built for this configuration. Run /Users/bradc/chapel-install/share/chapel/1.30/util/chplenv/printchplbuilds.py for information on available runtimes.
  ```

  I was thinking we could do this by just replacing `"$CHPL_HOME"` with `"%s", CHPL_HOME` in such messages in the compiler, but this seems to embed the path where the compiler was built, not the one where it was running.

  Other than that challenge, a downside to this approach is that I find it nicer to get errors on modules pointing to them using `$CHPL_HOME/module/standard/ModuleName.chpl` rather than a full/longer path.  But maybe the longer path is worth it for lack of ambiguity?  Note that it would make it harder to make some of our test output more difficult to maintain, where CHPL_HOME insulates us from that currently.

* Improve the documentation for `make install` users to define what CHPL_HOME is.  Upside: Probably pretty easy.  Downside: Has a bit of a "RTM" kind of feel to it.  Challenge: In a `make install` build, does CHPL_HOME sometimes want to refer to the `bin` and `lib` directories instead of just the `share` directory?  (e.g., I don't know whether we ever use it to point at binaries or libraries)

* Something else?

**Comment by bradcray** [comment]
@mppf: With BenA gone, I feel like you're the resident expert / proponent on `make install`.  Could you give me your take on this question?

**Comment by mppf** [comment]
`$CHPL_HOME` has a particular meaning when you do `make install`. As you figured out in your post above, it ends up meaning the `/usr/share` type directory.

The compiler can compute `$CHPL_HOME` whether it is prefix installed or not.

e.g.

```
$ /tmp/prefix/bin/chpl --print-chpl-home
/tmp/prefix/share/chapel/1.30	/tmp/prefix/bin/chpl
# configured prefix  /tmp/prefix
```

There is a table in the PR that added `make install` (https://github.com/chapel-lang/chapel/pull/6036) that explains what `$CHPL_HOME` and other variables mean both in the prefix install and the regular "home" install.

> 
> ```
>                    CHPL_HOME set         installed
> CHPL_RUNTIME_LIB   lib/                  /usr/lib/chapel/1.15/runtime/lib
> CHPL_RUNTIME_INCL  runtime/include       /usr/lib/chapel/1.15/runtime/include
> CHPL_THIRD_PARTY   CHPL_HOME/third-party /usr/lib/chapel/1.15/third-party
> CHPL_HOME          CHPL_HOME             /usr/share/chapel/1.15/
> ```
> 

Now, getting to the specific error:

```
error: The runtime has not been built for this configuration. Run $CHPL_HOME/util/chplenv/printchplbuilds.py for information on available runtimes.
```

I think there are a few things we could do, as you said:
 * we could emit a full path for this error. As you said, `$CHPL_HOME` is convenient. But, we could consider expanding it for `--prefix` installs. I think it's probably better not to do this, though (don't want to make different install modes more different than they have to be)
 * we could document what `$CHPL_HOME` means for a prefix installation. This makes sense to me to do in any case. We can describe that it can be gotten with `chpl --print-chpl-home`. (Note that `--print-chpl-home` so far is a developer flag, so isn't really properly documented).
 * we can try to eliminate common cases where this matters. For example, we have the ability to ask `chpl` to run `printchplenv` -- `chpl --print-chpl-settings`. We could make it a point to improve such methods & document them so that `chpl` can be the main entry point to the tool for users. (IIRC somewhere we have a note about changing the new issue template to use `--print-chpl-settings`. Oh yeah, it is #18206.) (Note that, like `--print-chpl-home`, `--print-chpl-settings` is a developer flag that isn't really very well documented).

**Comment by bradcray** [comment]
@mppf: I was thinking that something more aggressive was going to be required here, imagining that `$CHPL_HOME` would have a different meaning depending on whether we were talking about `$CHPL_HOME/modules` or `.../util` versus, say `$CHPL_HOME/bin`, `$CHPL_HOME/include`, `$CHPL_HOME/lib`, etc.  However, with a bit of `git grep`ping, I'm not seeing much indication that we ever print out those other paths to the user, in which case I'm on-board with just updating the docs, which seems like an easy/appropriate fix, and the very minimum that we should be doing.

One thing that I worry about here is the use of the `--chpl-home` flag in the `configure` script because it's using a similar name for what ends up being a different thing for `util/`, `modules/`, etc.  Do you recall whether there was a reason we didn't use a more standard flag name like `--prefix`?

**Comment by bradcray** [comment]
(Oh, I also like the idea of promoting `--print-chpl-home` to a user flag, potentially renaming it `--print-CHPL_HOME` to improve the chances of finding it and correlating it to CHPL_HOME).

**Comment by bradcray** [comment]
Put together the documentation part of this here:  https://github.com/chapel-lang/chapel/pull/21867

**Comment by mppf** [comment]
> One thing that I worry about here is the use of the `--chpl-home` flag in the `configure` script because it's using a similar name for what ends up being a different thing for `util/`, `modules/`, etc. Do you recall whether there was a reason we didn't use a more standard flag name like `--prefix`?

Our installer supports two installation modes, because at the time we were creating it, we were trying to create a Debian package, and Debian is strict about where things end up.

`./configure --prefix=/usr` e.g. selects an installation more like Debian. It will split up things int `/usr/bin/` `/usr/lib` and `/usr/share`.

`./configure --chpl-home=/opt/chapel-1.30` e.g. selects an installation more like what we have traditionally used and more like how things like Java JDK are distributed. It's "all the Chapel stuff in one directory".

So we can't simply rename `--chpl-home` to `--prefix`. However, if we wanted to, we could change to always expecting `--prefix` and using a different option to select the installation mode. One thing I like about the current situation is that most configure/make based projects have a `--prefix=` argument that selects an installation mode more like the Debian one. So I am happy that our `./configure --prefix=/usr` works in a way that I think people would expect if they haven't ready any docs.

**Comment by bradcray** [comment]
Shoot, I clearly completely missed (and forgot) the distinctions you were making between prefix and chpl-home installations in your previous comment, sorry about that.  And the fact that we already have `--prefix` removes my concern about `--chpl-home`.  I have an install local on my machine that must've used `--prefix` mode, but it was long enough ago that I forgot and forgot that I'd even chosen between those modes, and just assumed I'd used `--chpl-home` mode when looking at it more recently.
