### ISSUE TITLE
IO channel methods in support of Serializers

### ISSUE THREAD

**Issue by benharsh** [chapel-lang/chapel#21628]
Note: The exact naming will depend on the outcome of the discussion over on https://github.com/chapel-lang/chapel/issues/21627

### Method 1: A method to access the serializer or deserializer

I propose that we support a paren-less method to access the serializer or deserializer. In my prototype PR, I have something like:

```chpl
proc fileWriter.serializer : this.serializerType
proc fileReader.deserializer : this.deserializerType
```

### Method 2: A method to change the encoder or decoder

I propose that we support a method to return an alias of the current channel with a different serializer or deserializer. For example:

```chpl
proc fileWriter.withSerializer(type st) : fileWriter(this.kind, this.locking, st)
proc fileWriter.withSerializer(serializer: ?st) : fileWriter(this.kind, this.locking, st)

proc fileReader.withDeserializer(type dt) : fileReader(this.kind, this.locking, dt)
proc fileReader.withDeserializer(deserializer: ?dt) : fileReader(this.kind, this.locking, dt)
```

Some example usage:
```chpl
// translate a YAML object to JSON
var jw = stdout.withSerializer(JsonSerializer);
var yr = stdin.withDeserializer(YamlDeserializer);
var value = yr.read(MyType);
jw.write(value);
```

### Open Questions
1) Should we try to support an optional argument on methods like ``read`` and ``write`` that set serializer/deserializer for that call?

2) Should channel-creating methods support a new optional formal that allows for specifying a the serializer/deserializer at that time? Or is the functionality from a "method 2"-like thing sufficient?

**Comment by mppf** [comment]
It doesn't say it above, but there are two important elements of the `withFormatter` strategy as compared to a `setFormatter` strategy:
 * it neatly avoids the potential for race conditions with adjusting the channel's formatter if the channel is used by multiple tasks ; similarly, it avoids the need to lock/unlock the channel when setting this
 * it allows the formatter to be a record, which we expect to have significant performance advantages and we also expect it to significantly enable compile-time errors if a formatter/unformatter doesn't support some particular type (vs; if it's a class, the compiler will compile *all* of the formatter/unformatter methods for all of the types where I/O is done with them, because they could be invoked by virtual dispatch).
 
 

> 1. Should we try to support an optional argument on methods like `read` and `write` that set encoder/decoder for that call?

This is the direction we were headed in discussion on #18504. However, I think it would be OK to add that later as a non-breaking change.


> 2. Should channel-creating methods support a new optional formal that allows for specifying a the encoder/decoder at that time? Or is the functionality from a "method 2"-like thing sufficient?

I'd lean towards doing this, but like the previous, it could be added later as a non-breaking change, if we have a reason for hesitation.
