### ISSUE TITLE
"get" in method names

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#21691]
In discussions of some modules, we've talked briefly about whether an individual parenless method that fulfills the purpose of a "getter" should use "get" in its name.  This issue aims to take a look at the 2.0 modules as a whole so that we can determine a consistent position for the standard module style guide and perform any updates before 2.0 if needed.

Pull open this tab for the full list of types that have methods I would qualify and how they are defined today (as well as some other functions with "get" in their name):
<details>

Types and their methods that don’t use “get”:
- Tuples
    - size
    - indices
- String
    - size
    - indices
    - numBytes
    - numCodepoints
- Bytes
    - size
    - indices
    - numBytes
- Range
    - boundedType
    - idxType
    - stridable
    - stride
    - alignment
    - aligned
    - size
    - first
    - last
- Domain
    - dist
    - rank
    - idxType
    - intIdxType
    - stridable
    - shape
    - size (everything post unsafeAssignManager.newIndices should be moved if we intend to keep it)
    - lowBound
    - low
    - highBound
    - high
    - stride
    - alignment
    - first
    - last
- unsafeAssignManager (was this supposed to be included in the spec?)
    - checks
- Array
    - eltType
    - idxType
    - intIdxType
    - rank
    - indices
    - size
    - IRV
    - last
    - first
    - shape
- Locale
    - hostname
    - name
    - id
    - maxTaskPar
    - callStackSize
- Sync
    - isFull
- Single
    - isFull
- File
    - path
    - size
- List
    - size
    - indices
- Map
    - size
- Random.RandomSupport.SeedGenerator
    - currentTime
    - oddCurrentTime
- Set
    - size
- Subprocess
    - stdin
    - stdout
    - stderr
- Date
    - year
    - month
    - day
- Time
    - hour
    - minute
    - second
    - microsecond
    - timezone
- Datetime
    - year
    - month
    - day
    - hour
    - minute
    - second
    - microsecond
    - timezone
    - timetz
- Timedelta
    - days
    - seconds
    - microseconds

Types and their methods that do use “get”:
- List
    - getValue
    - getBorrowed
- Map
    - getValue (that takes a sentinel value)
- RandomStreamInterface, NPBRandomStream, PCGRandomStream
    - getNext
    - getNth
- Datetime
    - getdate
    - gettime

Where does the Reflection module fall on this?  It doesn’t have types, but it does define get functions and we did think using “get” was the right call

Time module also has getCurrentTime, getCurrentDate, getCurrentDayOfWeek

</details>

The history of each of these methods is a little too much to investigate in a reasonable amount of time, so I'm going to skip doing that for now.

What's the precedent in other languages, if they support it?
- Java doesn’t specify it in their conventions, but JavaBeans recommends using get
- Python doesn’t use getters and setters so doesn’t recommend using `get`
- Rust recommends using just the name of the field you’re accessing for getters, so no `get`
- Julia doesn’t seem to have a specific recommendation about them

I'm not aware of previous issues talking about this

Proposals:
- Given the sheer volume of methods that don't use "get" today, I would propose we take the position that accessor methods do not have to include "get" in their name.  And that "get" can be permitted where reasonable, such that the outlier cases do not require an update
  - Pros: only action item is to update the style guide to include this guidance
  - Cons: not completely unified
- Alternatively, we could choose to update these methods to use "get".
  - Pros: symbols would be unified
  - Cons: lot of work to support a style that was not widely used before

**Comment by lydia-duncan** [comment]
Brad's initial reaction to this discussion topic was:

> - I definitely don’t think we should require all getters use get*() names, as they feel clunky compared to .idxType, .rank, .size, .first, etc.
> - That said, I wouldn’t necessarily preclude types from supporting get*() method names if they seem best / that’s what the type author wants to use; but for our standard libraries, my instinct would be to try harder to come up with a clear name for the query first.
> - If you forced me to force types to use one style or the other, I suppose it’s obvious I’d force the non-get*() style

I suspect his position will not change after this issue, but will let him make that decision

**Comment by mppf** [comment]
> Rust recommends using just the name of the field you’re accessing for getters, so no get

Personally, this is the style that I like, even in C++ code. I am happy that there is some precedent that we can point to.

I have two other points to bring up, both in support of something like the status quo:

First, looking at these:

> Types and their methods that do use “get”:
> 
>     * List
>       
>       * getValue
>       * getBorrowed
> 
>     * Map
>       
>       * getValue (that takes a sentinel value)
> 
>     * RandomStreamInterface, NPBRandomStream, PCGRandomStream
>       
>       * getNext
>       * getNth
> 
>     * Datetime
>       
>       * getdate
>       * gettime

IMO, of these, only `datetime.getdate` and `datetime.gettime` would qualify as accessor methods. I think this weakens the argument for `getBla` type accessors.


Second, I've felt for a long time that needing to write `getBla()` and `setBla()` for all of your fields in Java or C++ is basically a sign of a lack in the language design. It can turn in to a lot of boilerplate code. My understanding for the rationale for this practice is that it hides the implementation details of how the fields are represented behind these methods. In other words, they support keeping the same API for a class even as the implementation details of what is stored in which field change.

It's my understanding, that in Chapel, we are trying to solve this by supporting methods without parentheses. In fact the language spec has an example that discusses how a parenless method can be used to preserve the same API for a record even when it no longer makes sense to keep a particular field. https://chapel-lang.org/docs/language/spec/methods.html#methods-without-parentheses . (Note that, a `setBla()` type setter does have one advantage that we haven't covered yet -- and that is that the code can take some action with the value. In contrast, the need to return a reference to something (to keep it looking field-like) creates challenges here. However, I think that the issues are very similar to those for arrays -- which we are discussing in #17999 -- and I think we should look for a solution to both, rather than requiring `setBla` functions, broadly speaking. A lot of types don't present a mutable interface anyway (and non-mutable types can be advantageous for parallel access). Anyway, this issue is specifically about `getBla` type accessors, and if we need a `setBla` accessor, IMO we can make `bla` to return a value/`const ref` and then add `setBla(x)` to set it; and as I said, in the future, I expect that there will be another way to handle it as well to allow using the type in a way that is more field-like, so that `myObject.thing = 4` can continue to work even if `thing` is not literally a field.

**Comment by lydia-duncan** [comment]
> It is a different question (which AFAIK we are not asking here?) if -- assuming we are not using `getBla` style for accessors -- if it is OK to use `getSomething` for other purposes -- or if that is too confusing for people coming from languages where `getBla` is normally a field accessor.

I don't think it would be too confusing.  Ultimately something is still "gotten" and at least in these cases we have here, it should be obvious where it is intended as a getter in the pure sense or not.

> Second, I've felt for a long time that needing to write `getBla()` and `setBla()` for all of your fields in Java or C++ is basically a sign of a lack in the language design. It can turn in to a lot of boilerplate code. My understanding for the rationale for this practice is that it hides the implementation details of how the fields are represented behind these methods. In other words, they support keeping the same API for a class even as the implementation details of what is stored in which field change.

That is one benefit.  Another benefit is that it makes it easier to find when there is a unified prefix for the method - the process of gathering all "getters" would have gone much faster if I could rely on being able to search for "get" and have them all turn up.  In the much more limited case of wanting to know what getters are on the type quickly, a find on the documentation page will be faster than having to read through the entire documentation for the type (though perhaps one could argue that we should not provide such shortcuts)

That said, I still support the current proposal of maintaining the status quo

**Comment by dlongnecke-cray** [comment]
Can the outcome of this discussion also apply to non-methods? There are several `Reflection` function which have `get` in the front such as `getField`.

**Comment by lydia-duncan** [comment]
I did include them in the list of symbols, but noted that they weren't "getters" and we'd determined that we wanted them to start with get.  Did I misremember that discussion?

**Comment by bradcray** [comment]
@lydia-duncan : In the OP, it seems like there's an obvious third proposal (arguably alluded to in Michael's response above), which would be:

* getters written according to the standard style guide shouldn't use `get*()` as their names (though methods that are not intended to be field-getter-like can still do so)
  * Pros: symbols would be unified, not much work to implement given the small number in that category today
  * Cons: the only one I can think of is getting into debates about what makes a given method sufficiently getter-like to have this rule be applied to it

@mppf wrote:
> if it is OK to use getSomething for other purposes -- or if that is too confusing for people coming from languages where getBla is normally a field accessor.

Like Lydia, this doesn't seem too confusing to me.

> Second, I've felt for a long time that needing to write getBla() and setBla() for all of your fields in Java or C++ is basically a sign of a lack in the language design. It can turn in to a lot of boilerplate code. My understanding for the rationale for this practice is that it hides the implementation details of how the fields are represented behind these methods. In other words, they support keeping the same API for a class even as the implementation details of what is stored in which field change.
> 
> It's my understanding, that in Chapel, we are trying to solve this by supporting methods without parentheses. 

This all resonates strongly with me...

The other main thought I have here, now that it's been pointed out how few get*() field accessors we support today: I don't recall any users ever complaining about the status quo.

**Comment by mppf** [comment]
> Cons: the only one I can think of is getting into debates about what makes a given method sufficiently getter-like to have this rule be applied to it

It does not change things much, but I think that we already have to think about / debate about something very similar to this, in order to decide if the method should have parentheses or not. In particular, if we think something should be a method without parentheses, then that seems to imply that it does not start with `get` (because we are making it look like a field).

Specifically, of the identified method names starting with `get`, I would expect `proc datetime.getdate() { ... }` and `proc datetime.gettime() { ... }` to fit into the "could be reasonably implemented as fields" category; so that they would be spelled `proc datetime.date { ... }` and `proc datetime.time { ... }`.

<details>

Our standard module style guide says this:

> Use parentheses-less methods only for returning properties that could be
reasonably implemented as fields. However, if such a method is named
isXYZ or hasXYZ it should use parentheses (so, use
``proc isReal() { ...  }`` rather than ``proc isReal { ... }``).
Parentheses-less functions that aren't methods should be avoided.

</details>

**Comment by lydia-duncan** [comment]
Considering those names are the same as types that live in the module, I suspect renaming them would cause problems

**Comment by lydia-duncan** [comment]
We (Brad, Jeremiah, Vass and I) discussed this today in an ad-hoc subteam meeting.

Opening questions from Vass:
- What qualifies as a getter? A: a parenless method intended to return a distinct piece of information about the type.  Whether that information is calculated based on the internal fields or whether it is actually a field is an implementation detail
- Does ref/val matter?  A: no, getters can return the information by ref or by val and doing one or the other does not impact its categorization
- Will adding this to the style guide impact users?  A: no, the style guide is and always has been only a requirement for internal and standard modules, they are only recommendations for users but users can write whatever they want

Positions:
- Proposal one (update style guide to permit either, no modifications to code)
  - Lydia preferred this, everyone else supported with concerns
- Proposal two (change everything to use get)
  - Everyone was against this
- Proposal three (change everything to not use "get", except methods that are not specifically getters)
  -  Vass, Jeremiah and Brad all preferred this option, Lydia supported it with concerns about updating the datetime methods.  As a result, this is the proposal we will follow.

There was some discussion about the difference between supporting proposal 3 with an exception for the datetime methods if it wasn't possible versus just supporting proposal 1.  The main objection was the use of "prefer", we agreed we should take a stronger position to avoid implying that both were fine always.

We decided to consider the Reflection and standalone Time functions not impacted by this rule so previous decisions on them stand.

**Comment by vasslitvinov** [comment]
A couple of other tidbits from today's meeting:

Should getter methods be parenless or parenful? A: this has already been settled elsewhere.

What to do about the methods on List, Map, RandomStream that are currently named get* ? A: we agreed with the above https://github.com/chapel-lang/chapel/issues/21691#issuecomment-1446469450 in that they are not "getters", so their naming is to be discussed separately as desired.
