### ISSUE TITLE
Finalize interface of array.count (so we no longer consider it unstable)

### ISSUE THREAD

**Issue by stonea** [chapel-lang/chapel#21730]
Currently (as discussed here: https://github.com/chapel-lang/chapel/issues/18089#issuecomment-1276500706) we have `count` marked as unstable in arrays due to the thought that we might want to change its interface to be more consistent with uses of counts in other datastructures.

Here's the interfaces as they exist in different modules:

`proc string.count(pattern: string, indices: range(?) = this.indices):int`
`proc bytes.count(pattern: bytes, indices: range(?) = this.indices):int`
`proc list.count(x: eltType):int`
`proc array.count(val: this.eltType):int`

Taking a look at this it seems like the only real question is: "should we allow count in list/array" to take a range?  Since this is an optional parameter we can always add it in later without breaking existing code so I don't really see a need for this to remain unstable in the interim.

Also taking a look at this it seems like if we do want to keep this unstable in Chapel 2.0 we should similarly mark it unstable in string, bytes, and list.

**Comment by bradcray** [comment]
> it seems like the only real question is: "should we allow count in list/array" to take a range?

Interesting question...  Arrays don't necessarily need a range argument, since we could call .count() on an array slice (whereas strings and bytes will create a new string/bytes when slicing, which won't have the desired effect; and lists don't support slicing AFAIK).  That said, slices can (currently) be expensive, and in some cases (notably `readLine()`), we've found that using slices can be annoyingly expensive compared to the old `readline()` that took an offset (so, similar to the range argument here).  And maybe uniformity is more important anyway.

> Since this is an optional parameter we can always add it in later without breaking existing code so I don't really see a need for this to remain unstable in the interim.

This sounds compelling to me.

> if we do want to keep this unstable in Chapel 2.0 we should similarly mark it unstable in string, bytes, and list.

That sounds less attractive to me.

**Comment by stonea** [comment]
I checked with the team and it looks like we have a consensus with making the existing interface stable. I'll wait until things open up for for the next release (1.31) before proceeding.

**Comment by bradcray** [comment]
You can always open the PR before the thaw occurs.  :)

**Comment by stonea** [comment]
This should now be complete with: https://github.com/chapel-lang/chapel/pull/21999
