### ISSUE TITLE
GPU: can runtime build artifacts be kept separate per GPU vendor?

### ISSUE THREAD

**Issue by DanilaFe** [chapel-lang/chapel#21978]
Right now, if you try to build for an AMD GPU, and then for an NVIDIA GPU on the same filesystem / repo, you need to rebuild the runtime (since it gets compiled for AMD the first time, and for NVIDIA the second time). Could we somehow avoid this, perhaps by keeping the build outputs for AMD separate from the build outputs for NVIDIA? It's possible that we're already doing this to some extent, but clearly not perfectly (rebuilds _are_ needed).

Convenience aside, one advantage to this is parallel GPU tests: computers that share a filesystem, but have different GPUs, would be able to compile Chapel GPU programs for each vendor at the same time, thereby making it possible to parallelize GPU testing.

**Comment by e-kayrakli** [comment]
Most likely, the first step is removing `NOPATH` here: https://github.com/chapel-lang/chapel/blob/main/util/chplenv/printchplenv.py#L95. Is it the only step?

**Comment by e-kayrakli** [comment]
> Otherwise, don't the cuda and rocm binaries go into the same directory?

What do you mean by cuda and rocm binaries?

Today both environment variables match. It may be where we will be for good, as well. But to me, `CHPL_GPU_CODEGEN` determines the target onto which GPU code should be compiled. Whereas `CHPL_GPU_RUNTIME` determines the runtime layer that's used to support GPUs. This dichotomy was rooted in the days where we were considering libomptarget as a potential runtime layer. In that scenario, `CHPL_GPU_CODEGEN` could be rocm, but `CHPL_GPU_RUNTIME` could be libomptarget, for example.

I think the purpose here is to have two different runtime builds live side by side, so we should differentiate based on `CHPL_GPU_RUNTIME`. Does that still sound wrong?

---

Tangent, and I think we discussed this in the past, but can help with my point: I find `NVPTX` and `AMDGPU` to be more proper options for `CHPL_GPU_CODEGEN` rather than `cuda` and `rocm` as we have today. I don't remember off-hand why we didn't go that way, there may well be a good reason for it.

**Comment by bradcray** [comment]
> What do you mean by cuda and rocm binaries?

The `.o`/`.a`/`.so` files created when building the runtime.

> Today both environment variables match.

I see, OK.  I misunderstood what CHPL_GPU_RUNTIME was and was thinking of it as being more binary (I've become more aware of `CHPL_GPU_CODEGEN` due to the recent changes in that area and the compiler build complaining at me when it's not set.  Does one take its default from the other?).

**Comment by e-kayrakli** [comment]
> Does one take its default from the other?

Sort of. `CHPL_GPU_CODEGEN` is the "main" flag that determines the vendor. i.e., we run `which nvcc` and `which hipcc` to see what is there to determine `CHPL_GPU_CODEGEN`. And all this is implemented in `chpl_gpu.get()` in our scripts. `CHPL_GPU_RUNTIME` also seems to be calling the same code path if nothing is set by the user. i.e., it'll do a `chpl_gpu.get()` if no user flag was set.

**Comment by e-kayrakli** [comment]
> Or does chpl_gpu.get() look at the CHPL_GPU_CODEGEN setting as part of its logic?

It will. `CHPL_GPU_RUNTIME` will default to whatever you set `CHPL_GPU_CODEGEN` to.
