### ISSUE TITLE
IO Serializers: What should we support as the standard binary format?

### ISSUE THREAD

**Issue by benharsh** [chapel-lang/chapel#21997]
Historically our binary format has been homegrown and Chapel-specific. In rewriting this interface we could have the opportunity to change our standard binary format to something else. A popular example would be [MessagePack](https://msgpack.org/index.html).

One approach could be to support a ``ChapelBinary`` format for older code that matches the current behavior of iostyle's binary encoding, which could help users migrate to a new format.

**Comment by bradcray** [comment]
Just as a gut reaction: It seems to me like writing out an int or array of ints in a binary format should default to writing that int or buffer of ints out as raw bytes (e.g., 8 bytes for an `int` and 8 * myArray.size for the array); that by choosing "binary" I'm wanting to opt out of as much formatting or decisions about representation as possible, just raw bytes of output (by some definition).  Whereas for a curated format that happens to be binary, like MessagePack, I would imagine opting into that using a MessagePack encoder/decoder for that.  My intuition would be that I'd be able to guess the structure of a binary file for most types and that that's what I want when requesting "binary" rather than "a structured file format that is binary in nature".

That said, I realize there are some tough questions in my "raw binary format" response like "how many bytes should be spent on a bool or enum?" which could cause portability issues (across platforms or versions of Chapel) depending on the stance taken (where one approach might be to not support serializers/deserializers for any types that don't have a simple/obvious answer; or another would be to just decide something and not change it).

**Comment by bradcray** [comment]
I was speaking with a user whose gut reaction was different than mine, so wanted to capture that here.  Whereas my C background suggested the approach above "writing an array in binary format by default should write out the binary data in that array", this user wanted a much more self-documenting binary file format in which, say, enough of the array's definition was written out that it could be read back in without knowing its size a priori (whereas my file format would've required manually writing the size as a binary int, declaring the array of that size, and then reading it in in binary).  In addition, they wanted enough meta-data in the file format to get a type mismatch error like "You tried to read an array, but the next thing in the file is a single real".  And to be able to write and read lists, maps, etc.  So, a much more productive and dummy-proof solution than I was advocating for.

Assuming the user is right, I think I would still want a simpler / more "raw" binary encoder/decoder option that could be opted into even if it was not the default.

**Comment by benharsh** [comment]
In 2.0 we have the ``binarySerializer`` and ``binaryDeserializer`` types, which use a completely unstructured/raw format. This provides users with the most control over their serialization.

We also have an unstable ``ObjectSerialization`` package module which we expect/intend to fulfill the role of "pickling" types in a bespoke binary format suitable for Chapel. This effort requires further design and discussion.
