### ISSUE TITLE
Before building chpl, check that we have a compatible CUDA or ROCm toolkit installed

### ISSUE THREAD

**Issue by stonea** [chapel-lang/chapel#22087]
When configuring Chapel to use the GPU locale model and build for NVIDIA GPUs it would be nice if we detected what version of the CUDA API is being used and error out if we don't detect what we need. My understanding is currently Chapel supports CUDA 11.x and we run into issues with 12.x. Do we support versions earlier than 11.x?

In addition to having chplenv do a check programmatically, we should also document our required version on the tech note.

Somewhat motivating this is:

This issue: https://github.com/chapel-lang/chapel/issues/22085
And this comment: https://github.com/chapel-lang/chapel/issues/22085#issuecomment-1505796807

**Comment by stonea** [comment]
Considering how to do this some things come to mind:

* We could call `nvcc` from `$CHPL_CUDA_PATH/bin/nvcc` and use regexp (or whatever) to process the output of the `--version` message. But string processing is always kind of brittle (and does the nvcc version always match the driver API version which is what we really care about right?)
* We could compile a small program that links to the driver API and calls `cuDriverGetVersion`, this is foolproof but kind of a heavyweight way to do things and `printchplenv` gets invoked before we make anything else.
* We could look at what the `libcudart.so` symlink points to and see the version is shown in the name of the target (e.g. `libcudart.so.11.0`)
* It looks like there’s a `version.json` file in `$CHPL_CUDA_PATH` and this looks like the ideal sort of thing to feed to a Python script.

**Comment by bradcray** [comment]
It would be nice if `chpl` could be built whether or not a compatible CUDA API was installed since, traditionally at least, the `chpl` compiler itself has not been particularly sensitive to what it's compiling for, for the most part (aside from whether or not LLVM is available).  Having the runtime build balk if it's being built for GPUs without the appropriate requirements makes more sense to me, but I would only balk at the runtime build stage, not proactively at the start of a `make compiler` or `make all`.

**Comment by e-kayrakli** [comment]
> Having the runtime build balk if it's being built for GPUs without the appropriate requirements makes more sense to me, but I would only balk at the runtime build stage, not proactively at the start of a make compiler or make all

Can you elaborate more? For example, if you set `CHPL_LLVM=system`, but the system LLVM version is not a version that's supported, you get an error early from the environment scripts before even build starts. I understand that the compiler build is more tied to the LLVM version than it is to CUDA version, but that difference is probably not that relevant or obvious to the user.

**Comment by stonea** [comment]
Somewhat tangentially, given [this comment](https://github.com/chapel-lang/chapel/issues/22085#issuecomment-1505999553) from @hpcpony on the issue this GH issue was forked from:

> I did try using the CUDA 12.1 build but pointed it at application compile time to a (user) installed CUDA 11.8 and it seemed to work but that was only the simple "hello world" above.

Whether we add a version check for the compiler or runtime build; I'm wondering if we should have some kind of (possibly hidden) `IGNORE_REQUIREMENTS` option you can pass to our Makefiles/chplenv to tell it to force the build through with the disclaimer that you might get unexpected results.  In addition to the "sometimes things can still work with not officially supported dependencies", one thing I worry about anytime we introduce a version check is that some point the third-party dependency will update and we'll either (again) needlessly prevent users from using the future version or, perhaps more embarrassingly, something will break with the version check code itself.  When such cases happen, it would be nice if we could tell folks to try passing in a flag like that rather than waiting around for us to fix things or asking them to hack something in `chplenv` or the Makefile itself.

**Comment by hpcpony** [comment]
Just my two cents as a user...

In software packages (not just chapel) i like to see:

1) warnings to alert me if my configuration might be unsupported or be
unstable or otherwise not a good choice.

2) suggestions/correction to point me in the direction of a configuration
that's expected to work properly, is supportd, etc...

3) the ability to (reasonably) configure as i see fit in case i want to
experiment/test something.

More broadly....

1) I prefer to build tools in as few configurations as possible and nfs
mount the software across potentially different machine configurations. As
a (relevant example) in my case ive got mixes of epyc and x86, different
cuda/driver releases, v100, a100 (sxm and pci) boxes

2) customize software for specific machines/configurations via environment
modules (that share the above common software install).

Don't think any of that is especislly radical, but just in case....  I do
realize there theres only so much that can be done.

**Comment by bradcray** [comment]
> I suppose these dependencies could be satisfied after building chpl itself though so I could move the check to when building the runtime (or even when chpl itself is run) if you think that would be useful.

This was my thinking:  That if I can build chpl without having those dependencies (which I hope is still the case—it sounds like the dependencies are more about running the compiler than building it?), then it would feel unfortunate to prevent me from building it over this.  I.e., maybe I want to do a `--no-codegen` GPU compile, in which case I probably shouldn't need the dependencies?  Or maybe I inadvertently had CHPL_LOCALE_MODEL set to gpu from a previous session and was making sure my compiler was up-to-date before doing some CPU-only compiles, so did `make compiler`.  It seems like that shouldn't prevent me from building the compiler, only from invoking it?

Or is there an Nvidia dependence built into the compiler itself now that I'm not aware of.

I'm much more comfortable with having the build print a warning in such cases than thwarting me from taking an action that doesn't require Nvidia (assuming it doesn't).

Engin anticipates correctly that the reason the CHPL_LLVM=system case doesn't seem contradictory is because we actually need LLVM to build the compiler (due to the headers and support libraries it depends on ).

**Comment by stonea** [comment]
> This was my thinking: That if I can build chpl without having those dependencies (which I hope is still the case—it sounds like the dependencies are more about running the compiler than building it?), then it would feel unfortunate to prevent me from building it over this. I.e., maybe I want to do a --no-codegen GPU compile, in which case I probably shouldn't need the dependencies? Or maybe I inadvertently had CHPL_LOCALE_MODEL set to gpu from a previous session and was making sure my compiler was up-to-date before doing some CPU-only compiles, so did make compiler. It seems like that shouldn't prevent me from building the compiler, only from invoking it?

Ah I see where you're coming from; not enforcing runtime library requirements for someone who just wants to use `--no-codegen` or just do `make compiler` sounds right.  

It does seem like if someone ran `make` alone (since that implies a runtimelib build) we still might want to have some kind of early-on conspicuous feedback given about missing runtime dependencies without making the user wait around for the compiler to finish building.  We could go with warnings here but those feel so easy to lose in the noise.  I'm going to set that aside for the moment and just error for unmet runtime requirements as part of the runtime build.  I've created a draft PR that does just that here: <https://github.com/chapel-lang/chapel/pull/22093>.

> Or is there an Nvidia dependence built into the compiler itself now that I'm not aware of.

There are no dependencies needed to get a working build of `chpl` that could run with `--no-codegen`; if things do get to the codegen pass then you'll need:

- Access to various CUDA tools: `ptxas`, `fatbin`, etc.
- Driver bitcode files: `libdevice*.bc`

And (maybe, I'm unsure) at `chpl` buildtime you'll need:

- LLVM to be built so that the NVPTX target available

All of these have ROCM analogues as well.

For the first two of these requirements I suppose you could build `chpl` in an environment that didn't meet them and then satisfy them later. I'm unsure about the third one (does `chpl` dynamically or statically link to LLVM? If even if does dynamically link would including/excluding the NVPTX target change the libs ABIs in a manner that could break things?); either way I think you'd be fine if you didn't get to the codegen pass.

Currently, `printchplenv` already does checks for all three of these every time its invoked.

In my draft PR I've changed all of these to be done as part of the runtime build, but that doesn't quite seem right either. For the first the first two (maybe three), maybe the right thing to do would be for `printchplenv` warn at compiler build time and then have `chpl` elegantly error out if we got to the codegen pass and didn't meet the requirement; though this would bother me somewhat if satisfying the third requirement (the need for LLVM to be build with NVPTX or AMDGPU) requires rebuilding `chpl`, does someone know if that would be the case?

**Comment by stonea** [comment]
> Do we support versions earlier than 11.x?

Given that we mention 10.x on [the technote](https://chapel-lang.org/docs/technotes/gpu.html#known-limitations) I guess we expect it to work.

Also, given this prerequisite [on the clang documentation](https://llvm.org/docs/CompileCudaWithLLVM.html#:~:text=Clang%20currently%20supports%20CUDA%207.0,CUDA%20installation%20guide%20for%20details.), I would assume we also wouldn't support anything prior to 7.0.

> CUDA is supported since llvm 3.9. Clang currently supports CUDA 7.0 through 11.5. If clang detects a newer CUDA version, it will issue a warning and will attempt to use detected CUDA SDK it as if it were CUDA 11.5.

So I'm tempted to say (on the technote) that we require a CUDA version after 7.0 but that we have only tested it with 10.x and 11.x

**Comment by bradcray** [comment]
> It does seem like if someone ran make alone (since that implies a runtimelib build) we still might want to have some kind of early-on conspicuous feedback about missing runtime dependencies without making the user wait around for the compiler to finish building.

I think that's a reasonable point, though it sounds awkward to engineer, based on what I know of our Makefiles.

If we were to just keep it simple, I don't think that it'd be the worst thing in the world if the "Hey, I can't actually build the runtime as you've requested given your system setup" error came only once the runtime started getting built since (a) the user would still get a working compiler out of it (assuming they had _some_ runtime they could use with it) and (b) the fix would be for the user to change something, and re-do `make` which wouldn't waste any time re-building the compiler since we're not specializing it based on GPU details.

> this would bother me somewhat if satisfying the third requirement (the need for LLVM to be build with NVPTX or AMDGPU) requires rebuilding chpl, does someone know if that would be the case?

I don't, but that does sound concerning.

**Comment by bradcray** [comment]
> do you still think that that we should avoid having these checks done when we run make compiler?

Let me answer that with some clarifying questions:

What will happen, by default, if I set `CHPL_LOCALE_MODEL=gpu` and do a `make` on a system that doesn't have Nvidia or ROCM installed?  Will `CHPL_GPU_CODEGEN` default to `none` and I'll get a working compiler, or will something else happen?

If I build the compiler with `CHPL_LOCALE_MODEL` unset, and then later set it to `CHPL_LOCALE_MODEL=gpu` are there cases where the compiler would need to be rebuilt?  (assuming I don't change any of my LLVM-related settings or installation?)

**Comment by stonea** [comment]
> What will happen, by default, if I set CHPL_LOCALE_MODEL=gpu and do a make on a system that doesn't have Nvidia or ROCM installed? Will CHPL_GPU_CODEGEN default to none and I'll get a working compiler, or will something else happen?

I think there's a discussion to be had there.  Given that Engin's 'none' mode adds simulated GPU sublocales I'm a bit hesitant for it to be any kind of default (I think it would confusing in cases where the system actually has a GPU but we were unable to detect what kind).  I'm imagining you'd get an error message telling you to explicitly set `CHPL_GPU_CODEGEN` to one of: `cuda, rocm, none`.

> If I build the compiler with CHPL_LOCALE_MODEL unset, and then later set it to CHPL_LOCALE_MODEL=gpu are there cases where the compiler would need to be rebuilt? (assuming I don't change any of my LLVM-related settings or installation?)

Assuming `CHPL_GPU_CODEGEN` default to `cuda` in that case, then if you used a system LLVM that was not built with NVPTX support then your compiler would be in an invalid state for doing codegen. If you wanted to use the compiler and generate something at the end, you would need to modify your LLVM-related settings and rebuild (or relink) the compiler.

**Comment by bradcray** [comment]
OK.  I definitely have lingering concerns about the complexity involved here, but I'm not sure what can be done to mitigate it.  Specifically:

* For most of the project's history, it's been sufficient to have a single build of `chpl` for use with all configurations.  I.e., you could change `CHPL_*` settings, not rebuild the compiler and be fine (or attempt to rebuild it and nothing would happen because nothing needed to change).  This was a really nice property.
* With LLVM being incorporated, things have gotten a little more complicated in that a given `chpl` binary may or may not have LLVM support built into it.  We specialize the `build/` directories to try account for this by keeping separate directories for different `llvm-` settings, but then blur the lines a bit in the `bin/` directory (in that building with CHPL_LLVM=none vs. system vs. bundled won't give you three different `chpl` binaries, but whichever you happened to build last will "win").  Two things that mitigate this potential for confusion are:
  * `chpl --version` prints information about the LLVM that it was built against as a sanity check
  * a `chpl` built with `CHPL_LLVM!=none` will still work for any combination of `CHPL_` settings
* Now it seems like we're entering a world where it's not simply whether or not LLVM was built in, but whether or not that LLVM had support for additional optional features.  So, are there similar things we can do to prevent that from becoming too confusing / hard to tell what you have?

But back to your question:

> given all that, do you still think that that we should avoid having these checks done when we run make compiler?

If setting `CHPL_GPU_CODEGEN=none` is sufficient to bypass them, then no.

**Comment by stonea** [comment]
> a chpl built with CHPL_LLVM!=none will still work for any combination of CHPL_ settings

I don't really see a way to mitigate this unless we want to enforce that LLVM always be built with the NVPTX and AMDGPU backends enabled. I think that would be an unfortunate thing to ask of users who really don't intend to use GPU support though. I have encountered installs of LLVM without AMDGPU in the wild before.

> Now it seems like we're entering a world where it's not simply whether or not LLVM was built in, but whether or not that LLVM had support for additional optional features. So, are there similar things we can do to prevent that from becoming too confusing / hard to tell what you have?

Would it be worth having `--version` tell you whether you built with the bundled LLVM or not?  I think it's a fair assumption to make that going forward if you're using the bundled LLVM that it will work with all possible configurations of 'CHPL_*' settings.  I suppose we could also have it print out other whether LLVM was built with the NVPTX and/or AMDGPU backends.

You can also get this information by running `llvm-config --targets-built` (which is how we go about checking what you have installed).

> If setting CHPL_GPU_CODEGEN=none is sufficient to bypass them, then no.

And just so there's no misunderstandings: do you mean that literally or would you be fine if 'none' was named something different too (like 'sim' or 'cpu') just so long as there was a way to bypass. Either way I could have any relevant error message suggest setting `CHPL_GPU_CODEGEN` to this mode one way of satisfying the requirements.

**Comment by bradcray** [comment]
> I think that would be an unfortunate thing to ask of users

I completely agree.

> I suppose we could also have it print out other whether LLVM was built with the NVPTX and/or AMDGPU backends.

That sounds more valuable (and presumably something the compiler would need to know anyway so that it could generate a useful error message if someone tried to target a GPU they couldn't?)

> do you mean that literally or would you be fine if 'none' was named something different too (like 'sim' or 'cpu') just so long as there was a way to bypass.

The latter.

**Comment by stonea** [comment]
I have a PR for this now merged so I'm going to close this issue: https://github.com/chapel-lang/chapel/pull/22170

Note that I have it producing an error message referring to the `GPU_CODEGEN=none`, which isn't yet merged and we may rename. So if this does change there's a TODO item on the PR for `GPU_CODEGEN=none` (https://github.com/chapel-lang/chapel/pull/22172) (pinging @e-kayrakli).
