### ISSUE TITLE
Confusing compile error for promotion of overloaded function over generic range

### ISSUE THREAD

**Issue by milthorpe** [chapel-lang/chapel#22098]
Not really sure if this is a 'bug', a 'gotcha', or a 'PEBCAK':

I defined two variants of a function, overloaded for the type of a parameter that could be either an array of `range` or a single `int`. Something like this:
```chapel
private proc foo(r: [0..1] range) {
  writeln(r);
}

private proc foo(r: int) {
  writeln(r);
}

foo([0..1, 2..3]);
```

The compile error I got was initially baffling:
`ranges.chpl:12: error: invalid use of parallel construct in serial iterator`

I guess this may be because the compiler is trying to promote the `int` version of the function twice, first over the array and then over the range type of the array elements, and one of these promotions doesn't define a parallel iterator...?

If I change the first function definition to include the generic `idxType` for the `range` type -- i.e. 
```chapel
private proc foo(r: [0..1] range(int))
```
-- then the first version of the function is called, as expected.

If instead I explicitly indicate that the `range` type should be unconstrained -- i.e.
```chapel
private proc foo(r: [0..1] range(?))
```
-- *and remove the second function definition*, I get a more helpful compile error:
```
ranges.chpl:11: error: unresolved call 'foo([domain(1,int(64),false)] range(int(64),bounded,false))'
ranges.chpl:3: note: this candidate did not match: private foo(r: [0..1] range(?))
ranges.chpl:3: note: because an argument was incompatible
```
This would have been a better compile error to receive for the original code. I guess this is a complex interaction between function promotion and resolution, and maybe not one commonly encountered.

**Comment by bradcray** [comment]
Thanks for reporting this, Josh—I have to admit to being at least as baffled as you were about the behavior you're getting.  Specifically, I would have expected an array element type of `range` or `range(int)` to behave identically for this program, and don't have a guess as to why that change would have fixed things.  Tagging @vasslitvinov who's been working in this area recently to see whether he understands something that I don't.

I think you're also correct that the compiler is considering the second `foo()` overload to be a match due to promotion when (I believe) it should not be.  Specifically, the only way it could match would be a double promotion (first we'll attempt to pass each range into the routine as a promotion, then we'll pass each range's integers into the routine as a second one), and I don't think we should be allowing that.

Tagging @mppf who's working on a rework of the compiler resolution pass to see whether that's far enough along that he could say how things are working there (though I don't know whether ranges are online yet or not).

**Comment by mppf** [comment]
> Tagging @mppf who's working on a rework of the compiler resolution pass to see whether that's far enough along that he could say how things are working there (though I don't know whether ranges are online yet or not).

I don't think we're quite ready to check this example in the dyno resolver (we are just getting arrays working & promotion isn't implemented yet). But, if production is doing the double-promotion and we want to stop doing that, it'd be good to change that and get tests locking in the right behavior etc. I'll also tag @benharsh because he might know if we are closer to understanding the behavior of this test in dyno than I am thinking.

**Comment by jabraham17** [comment]
Looks like this is working on main
```chapel
private proc foo(r: [0..1] range) {
  writeln("first");
  writeln(r);
}

private proc foo(r: int) {
  writeln("second");
  writeln(r);
}

foo([0..1, 2..3]);
```

outputs
```
first
0..1 2..3
```

I've opened https://github.com/chapel-lang/chapel/pull/25449 to lock in this behavior

**Comment by vasslitvinov** [comment]
@jabraham17 Perhaps this issue was opened when `range`, written on its own, was a concrete type `range(int, both, one)` ? Meaning that in today's terms the test should read `r: [0..1] range(?)` . Could you double-check please, and include both variations in your test in 25449?

**Comment by jabraham17** [comment]
> Perhaps this issue was opened when range, written on its own, was a concrete type range(int, both, one) ? Meaning that in today's terms the test should read r: [0..1] range(?) . Could you double-check please, and include both variations in your test in 25449?

Changing the test to `foo(r: [0..1] range(?))` still works. I will add that case to my PR
