### ISSUE TITLE
param loop iterating over element types of a tuple type

### ISSUE THREAD

**Issue by stonea** [chapel-lang/chapel#22239]
File this under a "wild ideas" category if you want, but it would be nice if I could write code like the following and have it unroll the loop substituting 't' as appropriate (where `runTest` takes in `t` as a type):

```chpl
for param t in (c_int, c_uint, c_ulonglong, c_float, c_double) do
  runTest(t);
```

As of today this errors with: "error: param for-loops currently only support range expressions with well-defined param integral bounds"

**Comment by bradcray** [comment]
Since `t` isn't a `param` but a `type`, I think we'd actually want to write this as:

```chapel
for type t in (c_int, c_uint, c_ulonglong, c_float, c_double) do
  runtTest(t);
```

(i.e., "I don't think of 'param loop' as meaning "a fully unrolled loop", but rather "a loop in which the index variable is a `param`", and our current implementation strategy is to fully unroll it)

Potentially obvious, but a current workaround for this is [TIO](https://ato.pxeger.com/run?1=m70sOSOxIDVnwYKlpSVpuhY3o0oqC1IVSkoLFGwVNDLzSnQUilITc3QUikuKMvPSNa250vKLFAoSixJzFTIVMvMUDPT0bICq9Yozq1IVqrkUFMqLMktSc_I0gIIamZpWCI21EBugFsEsBAA):

```
type tup = (int, real, string);
for param i in 0..<tup.size {
  writeln(tup(i): string);
}
```

Not that I'm suggesting we wouldn't want to support the more straightforward way of writing it...  I'd be a big fan of this feature and suspect this would be fairly low-hanging fruit to implement, and akin to how #15034 was done.  I also thought we had related issues for user-defined iterators that yield types and/or params, but am not finding them with a quick search (either too many hits or too few for the keywords I'm searching for.

**Comment by cassella** [comment]
This looks like #9634.

**Comment by bradcray** [comment]
Your search-fu is better than mine apparently...

**Comment by stonea** [comment]
Yeah, looks to be the same and I agree making it a `type` loop rather than `param` loop makes more sense.  I'm going to cross-reference and close this issue as a duplicate.
