### ISSUE TITLE
Compiler Error in Arkouda

### ISSUE THREAD

**Issue by Ethan-DeBandi99** [chapel-lang/chapel#22310]
I encountered the following compiler error during updates to the Arkouda Symbol Table code.

```
/Users/ethandebandi/Documents/git/arkouda//src/MultiTypeSymEntry.chpl:430: internal error: UTI-MIS-1040 chpl version 1.30.0
Note: This source location is a guess.

Internal errors indicate a bug in the Chapel compiler,
and we're sorry for the hassle.  We would appreciate your reporting this bug --
please see https://chapel-lang.org/bugs.html for instructions.  In the meantime,
the filename + line number above may be useful in working around the issue.
```

The line it is referring to is

```
var sz: int;
```

Please let me know if you need any other information.

**Comment by bradcray** [comment]
@Ethan-DeBandi99 : Is the code that led you to this internal error available on a branch somewhere, or otherwise reproducible?

**Comment by Ethan-DeBandi99** [comment]
@bradcray unfortunately it is not. I came across it working something that I needed to get working yesterday. I can try to reproduce it off our master branch, but it may take some time. I was just trying to do a better job at actually reporting these occurrences.

**Comment by bradcray** [comment]
OK, sorry that I was unclear when you asked about it yesterday then.  Without a reproducer (where a snapshot of a dev branch on the Arkouda repo would be fine—no need to try and create a minimal one), there's not much we can do to resolve this.  It's up to you whether it's worth your time to try and reproduce this case or not, but I'll close this for now so that you don't feel pressure to do so for our sake (not that we're not interested...).  If you hit internal errors again and are able to create a branch, commit your changes to it, push it to bears-r-us and point us to it in an issue like this, that would be valuable.
