### ISSUE TITLE
Error building docs with Doxygen 1.9.7

### ISSUE THREAD

**Issue by nikkirad** [chapel-lang/chapel#22425]
Error when running `make docs` on current version of doxygen (1.9.7):

`Invalid C++ declaration: Expected identifier in nested name. [error at 0]`

This is displayed at line 11 of `resolution.rst`, which corresponds to:

`.. doxygennamespace:: chpl::resolution`

Not sure exactly in which version this issue becomes present, but version 1.9.4 works.

**Comment by DanilaFe** [comment]
Checking out https://github.com/Homebrew/homebrew-core/commit/41828ee36b96e35b63b2a4c8cfc2df2c3728944a and installing as `brew install Formula/doxygen.rb` helped downgrade to 1.9.4., which is the version I started with and which works for me.

**Comment by mppf** [comment]
These issues in the other projects could be related
* https://github.com/sphinx-doc/sphinx/issues/9433
* https://github.com/sphinx-doc/sphinx/issues/10016
* https://github.com/breathe-doc/breathe/pull/711

But, it looks like these were fixed in Breathe 4.31 & we are already on 4.31.

Perhaps we should report a bug upstream to breathe? But to do so, we need to know if it is present with the current version. I tried experimenting with updating some dependencies, but that failed because https://github.com/chapel-lang/sphinxcontrib-chapeldomain requires docutils 0.16 while the other versions I picked (Pygments 2.15.1, Sphinxs 6.2.1, breathe 4.35.0) require docutils >= 0.18.1 and < 19. I don't remember off-hand how to make a local copy of sphinxcontrib-chapeldomain, so that is where my attempt stopped. In any case updating it is more than we can do for 1.31.

**Comment by lydia-duncan** [comment]
The last time I tried to upgrade our version of docutils, other packages we rely on (sphinx-rtd-theme, iirc) required an older version.  It's been almost a year since I last upgraded packages so the problem may have been resolved by now, though

**Comment by mppf** [comment]
Yes, I think my attempt showed that we could upgrade to docutils 0.18.1 (but not 19 yet).

**Comment by mppf** [comment]
If you are not working with dyno docs updates, another short-term alternative is to `brew remove doxygen` for now.

**Comment by jabraham17** [comment]
Looks like this is resolved on main. Homebrew has updated to doxygen 1.11, and I can build the dyno docs with it.
