### ISSUE TITLE
`Block` to become a record

### ISSUE THREAD

**Issue by vasslitvinov** [chapel-lang/chapel#22428]
This issue proposes `new Block(....)` as a way to create a distribution value, where `Block` is the name of the distribution.

Recall that distribution values are parallel to instances of domain and array types. Today `Block` is a class; a distribution value is created using `new dmap(new Block(....))` where `dmap` is a value type that exists to hide implementation details from the user and to manage deallocation of the underlying class instance, which also provides identity to domains. Under this propsal, the `Block` record will wrap a class instance the way `dmap` does today.

The benefit of this change is in switching from `dmap` that is meaningless to the user to letting the user interact the distribution in question directly via the `Block` record.

Our concerns about this approach include:

* Now that the distribution author needs to define the `Block` record in addition to the underlying distribution class, will that be too much boilerplate? Today the `dmap` type, internally called `_distribution`, provides at least the following methods that redirect to the underlying class: `newRectangularDom` `newAssociativeDom` `newSparseDom` `idxToLocale` `targetLocales` `displayRepresentation`. Under this proposal, the `Block` record will need to define also the initializer(s) that will need to invoke initializer(s) of the underlying implementation class.

* How will the underlying class be managed? One option is to make it `shared`.

* How will it interact with the future approach to privatization?

**Comment by bradcray** [comment]
> The benefit of this change is ...

To me, the biggest benefit is that it has the potential to make:

```chapel
var myDist = new Block(...);
```

and:

```chapel
var myDistDom1 = {1..n} dmapped Block(...);
var myDistDom2 = {1..n} dmapped MyDist;
```

much more symmetric syntactically with one another, where today, writing the distribution as:

```chapel
var myDist = new dmap(new Block(...));
```

for me seems very much more different than:

```chapel
var myDistDom1 = {1..n} dmapped Block(...);
```

That said, there's obviously still a difference in that a direct substitution would arguably need to be:

```chapel
var myDistDom1 = {1..n} dmapped new Block(...);
```

Or we just say that `dmapped` can either take an instance of a distribution or create that instance given a valid initializer call; but today to say that it also injects the `new dmap(...)` seems like a regrettable asymmetry (and to be clear, one that's been regrettable since we introduced it... it's just seemed more and more regrettable as other aspects of the language have improved).

> How will the underlying class be managed? One option is to make it shared.

In the short-term, I would imagine the answer to this to be "Exactly as it is by `dmap` today" (which I think is `unmanaged`?) since anything else will potentially cause issues for privatization.

> How will it interact with the future approach to privatization?

I don't think this really matters (to the user anyway) because whatever privatization is done can be done under the hood.  And for us, it doesn't need to be addressed until we have that future approach in-hand.

**Comment by vasslitvinov** [comment]
> How will the underlying class be managed?

The reason for raising this question is to avoid excessive boilerplate that the author of the `Block` record will need to write.

**Comment by vasslitvinov** [comment]
> the underlying class instance, which also provides identity to domains

Having written this, I can see that having an underlying class instance is not a must for a distribution. For example, if a distribution does not support redistributing of its domains and arrays, identity can be implemented simply with a unique integer. Then the `Block` record can carry the bounding box information and the targetLocales array directly.

**Comment by bradcray** [comment]
I've managed to put together a branch that converts `Block` to a record and passes some simple tests (hello4 written with block, redistBlock.chpl).  About to run a paratest now to see what I've broken...

**Comment by bradcray** [comment]
I've put my draft branch of this up on #22657
