### ISSUE TITLE
Unexpected error with array type alias with non-default initializeable type

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#22451]
### Summary of Problem

I would expect the following code to work because no array element is default initialized. But, instead it gives a compilation error. A workaround is to create an initializer to support default initialization (in this case, with a `type T` formal).

Looking within the compiler, it looks like the error is being emitted while resolving a call to `isDefaultInitializableType`.

### Steps to Reproduce

**Source Code:**

```chapel
record R {
  type T;
  var x: T;
  proc init(type T, arg: T) {
    this.T = T;
    this.x = arg;
  }
  proc init(arg: ?t) {
    this.T = t;
    this.x = arg;
  }
}

type D = [0..#2] R(real);

proc main() {
  var x: D = [new R(1.0), new R(2.0)];
  writeln(x);
}
```

**Compile command:**

```
$ chpl bb.chpl  --no-devel
bb.chpl:14: error: unresolved call 'R.init(T=type real(64))'
bb.chpl:4: note: this candidate did not match: R.init(type T, arg: T)
bb.chpl:14: note: because call does not supply enough arguments
bb.chpl:4: note: it is missing a value for formal 'arg'
bb.chpl:14: note: other candidates are:
bb.chpl:8: note:   R.init(arg: ?t)
```

**Context:**

I'm filing this issue on behalf of @lucaferranti.

This came about in the context of changing a type from being concrete to generic (along with #22450).

**Associated Future Test(s):**
TODO

### Configuration Information

Fails on `main`

**Comment by dlongnecke-cray** [comment]
Michael is right that the issue seems to be:

- We resolve `DefaultRectangular`'s `dsiReallocate()` override during `buildVirtualMaps()`
- The body of `dsiReallocate()` has a module-level `isDefaultInitializableType()` call
- This call uses the primitive `PRIM_HAS_DEFAULT_VALUE` to check `R(real(64))`
- Which calls, in course, `resolveUninsertedCall` -> `resolveInitializer` -> `resolveInitCall`
- Which fails because it cannot find any candidates

So my fix here is going to be trying to adjust, perhaps `findZeroArgInitFn`, to do an initial lookup and bail if no candidates are found instead of issuing normal errors.

Alternatively I can try and add a setting to `resolveNormalCall` / `tryResolveCall` so that we try to resolve a call and _actually skip_ emitting errors. Is this what `CHECK_CALLABLE_ONLY` is already supposed to mean? I'm not sure. I don't actually see any uses of `CHECK_CALLABLE_ONLY` in old compiler code.

The more comprehensive fix might end up affecting other features that speculatively resolve calls, so I might bail on it if it touches too many tests.

**Comment by dlongnecke-cray** [comment]
I think some of the plumbing for "try to resolve a call but do not error if it fails" already exists in the legacy compiler and `findZeroArgInitFn` on downwards is just not activating it correctly. So I'm trying to see what's going on there. It's a bit difficult for me to understand, though.
