### ISSUE TITLE
What should happen when passing a nil class to read/readf by reference?

### ISSUE THREAD

**Issue by benharsh** [chapel-lang/chapel#22588]
Consider the following program:

```chpl
use IO;

class C {
  var x : int;
}

proc main() {
  var f = openMemFile();
  {
    f.writer(serializer=new DefaultSerializer()).write(new C(5));
  }
  {
    var r = f.reader(deserializer=new DefaultDeserializer());
    var nilTemp : owned C?;
    r.read(nilTemp);

    writeln(nilTemp!.x);
  }
}
```

Should ``read`` allocate a new ``C`` to be placed in ``nilTemp``? Or should it throw an error because it could not read ``nil``?

**Comment by bradcray** [comment]
If a non-nil `owned C?` was passed in, would its fields be overwritten, or would it be freed and a new `owned C?` be allocated and returned in its place?  If the former, my inclination would be to throw on `nil`.  If the latter, returning a new object seems appropriate.

**Comment by benharsh** [comment]
Currently the behavior is to modify non-nil classes in-place through their ``deserialize`` method. Generally speaking the default compiler-generated behavior for ``deserialize`` methods ignores the current values, which I believe is consistent with our historical approach to ``readThis`` with some exceptions for things like ``ioLiteral``.

Do you have a preference for what should happen if passing in a non-nil``owned C?`` by reference, and encountering ``nil`` in the file?

**Comment by bradcray** [comment]
> Do you have a preference for what should happen if passing in a non-nil owned C? by reference, and encountering nil in the file?

I guess throwing an error continues to seem consistent with the other behaviors if we went that route.

If we went more the route of "read() on a class will (re)allocate/free the ref argument based on what it finds in the file" approach, then I'd be comfortable having it free the class.  The borrow checker would need to be aware that this is a potential outcome of passing the class to read() (and probably would end up assuming so by default without lifetime annotations?)

I don't have an obvious preference at the moment between what seem like the two most likely modes to me ("always reads in-place if there's a place to read into and something to read; throws otherwise" vs. "always (de-/re-)allocates the argument and creates a new object capturing what's read)."  While the former is closer to what we've historically done, the latter could be rationalized by the fact that the "class variable" is the reference to the object, and not the object (struct) itself—so maybe that's the value we should be considering ourselves to read (?).

**Comment by benharsh** [comment]
> While the former is closer to what we've historically done, the latter could be rationalized by the fact that the "class variable" is the reference to the object, and not the object (struct) itself—so maybe that's the value we should be considering ourselves to read (?).

I think if we went with the "not the object (struct) itself" approach then that would be somewhat inconsistent with records (where we read fields in-place rather than re-allocating). Hardly the end of the world since users already need to be rather mindful of class semantics, but it feels a bit unfortunate.

Also, if we went that route and I'm understanding correctly, then the ``deserialize`` method would be useless on classes because presumably the Deserializer would be responsible for invoking the initializer when allocating a new class instance. The ``deserialize`` method is useful because it allows for type authors to define how their already-allocated type can be read in-place. This is particularly useful for arrays, or types that contain arrays, where allocating and de-allocating a copy might be expensive. I think this is a feature that something like Arkouda could take advantage of, but I don't know if that's of interest to that project. It's also worth pointing out that users could always add their own method that they pass a ``fileReader`` into, rather than using standard IO methods directly: ``myValue.readInPlace(myReader)`` vs ``myReader.read(myValue)``.

**Comment by bradcray** [comment]
Don't take this as pushing back on the direction you're advocating for (which I'm fine with), but just for the sake of argument / exploration:

> I think if we went with the "not the object (struct) itself" approach then that would be somewhat inconsistent with records (where we read fields in-place rather than re-allocating).

I think the inconsistency would be pretty easy to rationalize if we wanted to:  Given class C and record R, since in `var r: R;`, `r` is the variable _is_ the object whereas in `var c: C;` it's logically a pointer to the object, I could see an argument that `read(r)` is reading the fields of the object, and that `read(c)` is reading the class instance (the fields and the identity, including potentially `nil`, so is free to create/destroy/change the pointer itself (or, probably, even "has to").

Something that didn't occur to me until now, though:  this would probably also imply some sort of pickling of classes such that if we had variables `c1`, `c2`, and `c3` that all pointed to the same class when written, reading them back in would cause them all the end up pointing to the same class instance again, rather than having three class objects that happened to have their fields set to the original class's.  On the plus side, this seems like a great productivity win for the user ("I wrote out my DAG and read it back in, and the DAG was preserved rather than turning into a tree!") but also a lot more accounting for the IO system.  Note that it's something we've been asked to provide, so I think it's a question of whether we provide it as part of the basic IO ser/deser support or whether it requires opting into something more advanced that can handle pickling.

Anyway, the point of the above paragraph is that if we're doing any form of pickling in the IO code, we probably need to treat reads of classes as setting class identity, not fields (and vice-versa).  And if we're just treating class reads as reads of the fields then throwing on your nil cases seems appropriate, and we'll just need to come up with some other way that users can do pickled IO.

**Comment by mppf** [comment]
The discussion so far is interesting. One thing that resonates with me is thinking about class instance identity vs record identity. Another thing is the part about pickling.

I think it's a really important goal of the Serializer/Deserializer effort that something like pickling and unpickling class instances is possible. It's true that it's more accounting in the I/O system, but the way I see it, the goal is to be able to write such accounting in the context of a Deserializer implementation, but we don't have to implement that yet. So today, it's a matter of making sure the relevant APIs are OK and I think the question this issue is asking is definitely relevant.

Anyway, all that said, I might be making an incorrect logical leap somewhere, but I have been imagining that it would not be possible to deserialize a DAG if we don't give the `read(myNilableClass)` the ability to set `myNilableClass` to a new instance allocated and read in.

In terms of something like an array, a type like that is a record wrapping a class. The record defines how the array behaves in terms of copying (and reading and writing). So for I/O, the fact that there is a class at all is an implementation detail that should not be relevant for the I/O system (presuming that there are defined `deserialize` etc methods on the array record & these do the right thing on an element-by-element basis).

**Comment by bradcray** [comment]
A few notes that stuck with me from an offline exchange with Ben:
* I was mixing up the terms "pickling" and "swizzling" (of pointers or class variables in our case), though if I've understood what users mean by pickling, I think it must involve pointer swizzling, so this may be a benign mix-up
* Ben clarified for me that whether the framework supported the ability to do pointer swizzling (serialize and deserialize DAGs or graphs) vs. whether a given serializer/deserializer made use of that capability were potentially two different things.  I think this is similar to Michael's "be able to write such accounting" point above.
* We also checked my notes and saw that one of the requests for this DAG deserialization capability was made in the context of the default binary ser/deser support (so not something that that particular user would want to have to access by opting into a more complex serializer)

**Comment by benharsh** [comment]
Circling back to this, I would be content in defining that the question here is to be answered by individual Deserializer implementations. If an implementation wants to allow pickling/caching of duplicate classes, then it may do so. If the implementation does not support that behavior, and prefers to read in-place, then that is also fine.

I think the only question I have remaining here is whether a Deserializer should have the ability to free the argument. Presumably if the user is passing it in by ref they expect it to be overwritten, so it should be fine then, right? Conversely, we could state that Deserializers should not do this and leave it up to users to deal with the memory management.

**Comment by mppf** [comment]
> I think the only question I have remaining here is whether a Deserializer should have the ability to free the argument. Presumably if the user is passing it in by ref they expect it to be overwritten, so it should be fine then, right?

Yes, this makes sense to me. It would also allow for a fall-back implementation of `ReadDeserialize` by running `InitDeserialize`, for classes. I don't think we can have the potential of such a fall-back implementation without the ability of the Deserializer to free the class and overwrite it with a newly read one. (Of course, with `owned`, that all happens just in an assignment).

**Comment by benharsh** [comment]
This is on my radar to close once I have implemented this capability and added tests.

**Comment by benharsh** [comment]
This behavior will be documented in the release, so I will close this issue. The capability is already implemented, though we do not have a full Deserializer that makes use of the feature. I expect future experiments with pickling will exercise this capability quite heavily.
