### ISSUE TITLE
IO: import vs. use: `string.format()`

### ISSUE THREAD

**Issue by kwaters4** [chapel-lang/chapel#22688]
### Summary of Problem
I am porting over some code from 1.30 to 1.31 and I ran into an issue that I have been able to create a quasi-reproducer that errors in both 1.30 and 1.31. I am not sure why I have only now ran into the issue in 1.31 in the code base. I have not isolated the exact issue, but I have been getting away with something in the past. My assumption is something was cleaned up between releases and it is scoping properly now? A wild conjecture. I get the same error as the reproducer in 1.31 on the code base.

My brain is stuck here. I think I am missing something obvious. It works fine with `use IO;`, however it does not work with the import statement and I am not sure what I need do to fix that? `IO.a.format` is not right and `a.IO.format` is also not right.  I did not have much luck experimenting use `import IO.Formatted;` either.

This is not blocking, but I would like to live in a world without `use` statements for maintainability. 

### Steps to Reproduce

**Source Code:**

```chapel
import IO;
//use IO;

proc foo() {
	var a: string = "%06xi";
	return a.format(1);
}

foo();
```
[ATO Link](https://ato.pxeger.com/run?1=m70sOSOxIDVnwYKlpSVpuhY34zNzC_KLShQ8_a259PVLi1PBLK6CovxkhbT8fA1NhWouzrLEIoVEK4XikqLMvHQFWwUlVQOzikwlay7OotSS0qI8hUQ9T3-9tPyi3MQSDUNNa65aLi6wZmsuiDVQ22C2AgA)

**Compile command:**
`chpl foo.chpl`

**Comment by lydia-duncan** [comment]
When trying to get access to tertiary methods, generally you need to import the type from the module where the tertiary method is defined (e.g. `import IO.string` or `import IO.FormattedIO.string`).  However, it seems like something about the string type itself (probably because it's one of the more special types) is thwarting that ability.

**Comment by mppf** [comment]
This version of the program works:

``` chapel
import IO.format;

proc foo() {
	var a: string = "%06xi";
	return a.format(1);
}

foo();
```

@lydia-duncan - do you think it's a bug that that works (should it have to be `import IO.string.format`?)

**Comment by kwaters4** [comment]
Thanks for pointing that out @lydia-duncan. I knew something silly was going on here, that makes complete sense! I am still thrown by why it is showing up now in 1.31. It may take some digging on my part. 

What do you think the correct behavior should be here?

```chapel
import IO.FormattedIO;

proc foo() {
	var a: string = "%06xi";
	return IO.FormattedIO.a.format(1);
}
```

In the hot-fix suggested by @mppf, what am I actually importing here (`IO.format`)?

**Comment by lydia-duncan** [comment]
For the code as written, I would expect a message about not being able to find `a` in `FormattedIO`, because the name a is local to your function.  Based on Michael's comment, I think that code should be:
```chapel
import IO.format;

proc foo() {
	var a: string = "%06xi";
	return a.format(1);
}
```
and that looks to compile for me

**Comment by kwaters4** [comment]
@lydia-duncan Thanks! The second one is what I was looking for. From a maintainability perspective, how am I, the user, supposed to know that I am referencing the IO library in the call `a.format(1)`? Or what is the difference between the following to functions:
```chapel
import IO.string;

proc foo() {
	var a: string = "%06xi";
	return a.format(1);
}
```
and 
```chapel
use IO.string;

proc foo() {
	var a: string = "%06xi";
	return a.format(1);
}
```

I think within the current discussion/modification these two calls into the IO library should both be valid?

**Comment by lydia-duncan** [comment]
Use requires a slightly different format when you're trying to limit the symbols you're bringing in from it:
```chapel
use IO only string;

proc foo() {
	var a: string = "%06xi";
	return a.format(1);
}
```

I would agree that otherwise both should be valid.  For the purposes of what you're trying to do, they are also equivalent, though the spec says that the use statement declaration would also enable qualified access to symbols that aren't methods (so `IO.someOtherFunc()` would be enabled by the `use`, but not the `import`).

From a maintainability perspective, that is a good point that there's significantly less breadcrumbs about the source of `format`.  It should be clear that it's a method, so I would expect the user to look for information about the type (which does lead me back to my current favorite unimplemented feature, #5953).

But it's also no different than primary and secondary methods.  If you have the following, the user is in the same boat about determining where `myMethod` is defined:
```chapel
import SomeMod.SomeType;

proc foo() {
  var a: SomeType = new SomeType(...);
  return a.myMethod(...);
}
```

If it was a type method, sure, you could put the full module path in before the type name.  But the method is specific to this particular instance of the class and its behavior potentially varies based on how you've initialized it locally, the values you've given when initializing its fields.  If `myMethod` has arguments, you can add a little bit more control, but it's still impacted by the declaration of the type and any operations that have happened to it since then.  Whereas a standalone function is much more tied to the module it is in.

**Comment by DanilaFe** [comment]
> When trying to get access to tertiary methods, generally you need to import the type from the module where the tertiary method is defined (e.g. import IO.string or import IO.FormattedIO.string). However, it seems like something about the string type itself (probably because it's one of the more special types) is thwarting that ability.

This should be fixed as of #22738. In particular, the following program:

```
import IO.string;

proc foo() {
	var a: string = "%06xi";
	return a.format(1);
}
writeln(foo());
```

Now compiles and prints `000001`.

**Comment by bradcray** [comment]
Thanks for the fix here @DanilaFe!

@kwaters4 : I consider Daniel's PR to close this issue, but let us know if you think otherwise.  Specifically, for tertiary methods in Chapel (like `string.format()` here, which is tertiary because it's defined in a module other than where the `string` type is), the current way to access such a method is to `import`/`use` the type that serves as its receiver, which brings all the tertiary methods from that module into scope—so `import IO.string;` in this case.

When Daniel demo'd this for the team this week, there was a little bit of consternation about whether the current syntax—while sound and something we've been living with for a few years now—might be too subtle or unintuitive to someone new to Chapel or reading the client code.  That led us to file https://github.com/chapel-lang/chapel/issues/22761 which could be considered a continuation of the questions you were wrestling with in the OP here.

**Comment by bradcray** [comment]
In the absence of more information, I'm going to close this based on my understanding of the original issue and sense that #22761 covers logical/potential future work here.  If I've missed something, we can re-open or fork the missing piece off into its own issue.
