### ISSUE TITLE
Should ContextManager methods be enter/leave or enter/exit?

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#22712]
Spin-off of #22618. Per decisions in that issue, there will be a `ContextManager` interface that contains renamed methods for `enterThis` and `leaveThis` (which we have currently). We will not have `-This` suffixes on these.

Some have proposed that the names should be `enter` and `exit` instead of `enter` and `leave`.

Note: I only know of the Python precedent here; other languages considered (Rust, Swift, Java, C#) don't have a direct equivalent.

### enter and leave

Pros
* It is more or less what we have now (once we remove the `-This`)
* The length matches between `enter` and `leave`

### enter and exit

Pros
* It matches Python's ContextManager interface

Cons
* Could be potentially confused with `exit` to quit the program

**Comment by bradcray** [comment]
I’d be inclined to put a `Context` suffix onto those names in order to link them more strongly to the context (ha ha) in which they’re behaving.  I.e., `enterContext()`, `leaveContext()`/`exitContext()`.  I feel as though `enter`/`leave`/`exit` are too general-purpose as names on their own without having more information.  Though it makes the names slightly longer, I think the improved precision is a net win.

**Comment by lydia-duncan** [comment]
@bmcdonald3 - I think you resolved this on Monday, right?  Can this be closed?

**Comment by bmcdonald3** [comment]
Yes, this was resolved with https://github.com/chapel-lang/chapel/pull/22909, thanks for pointing that out.
