### ISSUE TITLE
c2chapel Fails on Nested Array Types

### ISSUE THREAD

**Issue by Stinners** [chapel-lang/chapel#22797]
### Summary of Problem
Running c2chapel on a C header file with a nested array type throws an exception.

### Steps to Reproduce

Call c2chapel on any C header file containing a nested array type.

```bash 
echo "int n[][];" > example.h
c2chapel example.h
```

This seems to be have been introduced in commit 86eb803 which changed how chapel types are generated for arrays. Previously, nested arrays where converted to nested `c_ptr`s. 

### Configuration Information

- Output of `chpl --version`: chpl version 1.32.0 pre-release (0fc7def0ae)

**Comment by bradcray** [comment]
@Stinners : Thanks for reporting this.  Could you let us know if this is a blocking issue for you or whether you just happened to notice?  (it sounds more like the former?)

@riftEmber: Since the commit above is yours, would you have time to look into whether it's possible to restore the previous behavior in the new c_ptr world?  And/or @bmcdonald3 or @benharsh, since you're familiar with c2chpl, would you be able to help with this?

**Comment by Stinners** [comment]
@bradcray, not a blocker for me. I've made a small change to c2chapel to unpack nested arrays into a single unnested c_ptr which works for my purposes.

I happy to do a bit more investigation and make a pull request with my change in the next couple of days.

**Comment by bradcray** [comment]
We're always happy to receive pull requests!  But thanks for reporting it in any case!

**Comment by riftEmber** [comment]
@bradcray Acknowledging this. It was definitely not intentional to break the representation of nested arrays as nested `c_ptr[Const]`s. At a glance it looks like I overlooked that the inner array can't have a const qualifier. Since @Stinners is already working on a PR (thank you!) I'll do nothing for now.

**Comment by Stinners** [comment]
@riftEmber, I've made a pull request (#22813) with a small change to fix this. It does change the behaviour of c2chapel compared to what it was before 86eb803d but I suspect the old behaviour never produced working code.

Let me know if you have any changes or concerns.

**Comment by mppf** [comment]
I would think that C nested arrays need the inner (and outer?) dimension to be specified, and if that's the case, maybe they should make to our fixed-size-array-interop type `c_array` rather than anything involving `c_ptr`.

**Comment by riftEmber** [comment]
@mppf In my unscientific testing with my above example, I had to specify the dimension of the inner array, or get this error:
```
./mytest.h:3:22: error: array has incomplete element type 'int[]'
static void foo(int a[1][]) {
```
I did not have to specify the outer dimension. For a non-nested array as well, you can leave out dimension and just have it treated exactly like a pointer AFAIK. I think this means `c_array` would be too limiting here. (Although I'm not sure what we use `c_array` for at all at this point...)

**Comment by mppf** [comment]
OK, in that case, I think we could use `c_array` for the inner dimension for nested array types, but I agree it wouldn't make sense for the whole array / for the outer dimension.

**Comment by riftEmber** [comment]
@mppf I think even with that we have some problems for a 3 or more dimensional array. A 1D array would be be `c_array`, a 2D array would be `c_ptr(c_array)`, and a 3D array would be `c_ptr(c_ptr(c_array))`. In the 2D case I don't even know if it's possible to dereference into the `c_ptr(c_array)`, but in the 3D case we then have `c_ptr`s to `c_ptr`s which won't work for the same reasons representing a 2D array with nested `c_ptr`s doesn't work.

**Comment by mppf** [comment]
I'd expect the outermost dimension would be `c_ptr` and any inner dimensions would be `c_array`:

* 1D : `c_ptr(eltType)`
* 2D : `int a[][10]` : `c_ptr(c_array(c_int, 10))`
* 3D : `int b[][20][10]`c_ptr(c_array(c_array(c_int, 10), 20)`

**Comment by riftEmber** [comment]
Oh ok, that makes sense. Tested out this program on main for a 3D array and it works:
```
use CTypes;

require "mytest.h";

extern proc foo(in a : c_ptr(c_array(c_array(c_int, 3), 3)));

var inner : c_array(c_int, 3);
for i in 0..2 {
  inner[i] = i:c_int;
}
var middle : c_array(c_array(c_int, 3), 3);
middle[0] = inner;
middle[1] = inner;
middle[2] = inner;
var outer = c_ptrTo(middle);

foo(outer);
```

`mytest.h`:
```
#include "stdio.h"

static void foo(int a[][3][3]) {
  printf("hi, %i\n", a[0][2][1]);
}
```
I assumed nesting `c_array`s would cause similar problems to the `c_ptr` case, like indexing into the 0th position of the outer `c_array` would give you the variable descriptor of the first internal `c_array`, but it appears to be working properly.

I think this is an advantage over just a single `c_ptr` since it lets us represent the dimensions on the Chapel side. @Stinners would this kind of approach work for you?

**Comment by bradcray** [comment]
Catching up:  I proposed (offline) to @riftEmber that we merge @Stinners PR since it improves upon the current behavior and (as I understand it) restores something that used to work.  And that we then open an issue capturing the notion of generating more precise signatures that use `c_array` as a future effort.

**Comment by riftEmber** [comment]
This is completed with the merge of https://github.com/chapel-lang/chapel/pull/22813; I will create a follow up issue for the `c_array` representation proposal shortly.
