### ISSUE TITLE
Should we allow array assignment over an array of indices

### ISSUE THREAD

**Issue by jabraham17** [chapel-lang/chapel#22828]
Currently, Chapel allows assigning to an array over a full array of indices. Consider the following example:

```chapel
var B = [1, 3, 4, 3];
var A: [1..5] int = 10;
A[B] += 3;
writeln(B);
```

The assignment `A[B] += 3` will assign `3` to `A[1]`, `A[4]`, and `A[3]` twice. This is a race condition.

Do we want to continue to support this for 2.0. It can be a subtle error for a programmer to accidentally write.

A few options
1. Make this an error
  - Users would no longer be able to write this pattern, instead needing to write `forall bi in B with (ref A) do A[bi] += 3`.
2. Warn by default for this
  - Warn users that this is a race condition and the behavior/feature may stop working in the future 
3.  Warn for `--warn-unstable`
  - This would be marking this as unstable with a similar warning as above, just not on by default
4. Allow this for 2.0 and beyond

**Comment by lydia-duncan** [comment]
I would consider that a bug, personally, though I imagine it's tied to behavior in other areas (like how loops accept domains and arrays) and so would be difficult to fix

**Comment by mppf** [comment]
@lydia-duncan - I'd like to understand more about what you mean. When you say it's a bug, what is it that you are expecting to happen that isn't? Were you expecting it to not compile?

**Comment by lydia-duncan** [comment]
Yes, I would expect it to not compile

**Comment by bradcray** [comment]
I'm open to most of the proposals here, and would choose the one that's most consistent with other aspects of the language.  If I'm catching up properly, I'd guess that that would be making it illegal because the default task intent for `A` would be `const`?

**Comment by lydia-duncan** [comment]
@jabraham17 - what do you consider the next step for this?  Scheduling a discussion?

**Comment by jabraham17** [comment]
Perhaps a quick topic item with a few options
1. We should not change this
2. We should provide some kind of warning for this (whether that is by default or --warn-unstable)
3. We should consider this a bug
4. We need more discussion to decide for 2.0

**Comment by bradcray** [comment]
@jabraham17 : Did this question not fall within the charter of the ref-maybe-const team?  If it did, I don't think it necessarily requires a full-team discussion.  If we failed to resolve it, we should.  My guess was that we'd make it illegal due to a strict interpretation of ref-maybe-const and promotion as a forall equivalent (?).

I was going to ask what happens on main today, but I guess this is tied up with the forall + ref-maybe-const changes, which are still the long pole in the tent?  (i.e., main doesn't reflect any new ref-maybe-const work?).

**Comment by jabraham17** [comment]
In my brief tests prior to and during the ref-maybe-const discussion, this was not affected. I think we could argue it not being affected is a bug like Lydia said, but as of right now I don't think deprecating ref-maybe-const will change this.

**Comment by bradcray** [comment]
Huh...  I thought @vasslitvinov's earlier ref-maybe-const experiments caused this to become an error, which is partially why I was predicting that outcome in your work as well (but I do see the "brief tests" qualifier).

Do you see a rationale for preserving the current behavior in the new no-ref-maybe-const world?  My intuition would be:

```chapel
A[B] += 3;
```

gets rewritten (by promotion rules) to:

```chapel
forall b in B do
  A[b] += 3;
```

which then is illegal because `A` has a default `const ref` intent when crossing into the `forall` loop.  So consistency would suggest to me that the original should be illegal as well.

One unfortunate side effect of that choice is that if `A` was an array of `atomic int`, it would be quite reasonable to do histogramming using:

```chapel
forall b in B do
  A[b].add(1);
```

or:

```chapel
A[B].add(1);
```

but this rule would prevent that.  That might suggest making arrays-of-t share the const-ness or ref-ness of their eltType as a task intent by default to enable these safe cases.  But I'd probably still start with making it illegal since relaxing it later for such cases would be a non-breaking change (and seems complicated / not something to rush into).

This sidebar is loosely related to:  https://github.com/chapel-lang/chapel/issues/17221 (having collections of things have different default intents based on other properties of them) and https://github.com/chapel-lang/chapel/issues/13319 (giving users the ability to say what the default intent for their type should be).

**Comment by jabraham17** [comment]
> Do you see a rationale for preserving the current behavior in the new no-ref-maybe-const world?

I think we can make the argument that `A[B] += 3` gets rewritten to

```chapel
forall b in B with (ref A) do
  A[b] += 3;
```

So of course `A[B] += 3` is legal.

>  That might suggest making arrays-of-t share the const-ness or ref-ness of their eltType as a task intent by default to enable these safe cases. But I'd probably still start with making it illegal since relaxing it later for such cases would be a non-breaking change (and seems complicated / not something to rush into).

I think that would be useful. One thing that is already on main is this

```chapel
// user defined proc that takes atomics
proc addAtomic(at) {
...
}
```

This procedure will work, if you pass in a single atomic, but calling it as `addAtomic(arrOfAtomics)` breaks without an explict `ref`.

But as useful as it is, I think it actually makes the code less readable. Because now a generic procedure that takes an array of ints or an array of atomic ints behaves different.

**Comment by bradcray** [comment]
OK, thanks, I misinterpreted your previous comments as being in favor of preserving the historical behavior.

**Comment by mstrout** [comment]
@bradcray and I discussed this and think for the Fall release this should be an error.

**Comment by jabraham17** [comment]
There is another problem here which will need to be resolved.

```chapel
var B = [1, 3, 4, 3];
const A: [1..3] int = 10;
A[B] += 3; // should be an error
proc foo(ref a: int) do a += 3;
foo(A[B]); // should be an error
```

This code incorrectly compiles and runs today, we do not appear to be checking promotion wrappers for `const` violations.
