### ISSUE TITLE
Should we continue to permit `$` in identifier names?

### ISSUE THREAD

**Issue by Guillaume-Helbecque** [chapel-lang/chapel#22979]
### Summary of Problem

Until now, the `$` character is permitted in identifier names mainly for the `foo$` convention used with `sync`/`single` variables, as mentioned in the doc:
https://github.com/chapel-lang/chapel/blob/2bfefa51d6468a6b111ae7bcd84d4ef9b5fd2b79/doc/rst/language/spec/lexical-structure.rst#L112-L117

Following PR #17287, the `foo$` convention is no longer needed, and PR #22953 aims to remove it.

As a follow-up of https://github.com/chapel-lang/chapel/issues/19152#issuecomment-1677803463, the main question under consideration is whether to continue allowing `$` in identifier names or to mark it as unstable for version 2.0?

**Comment by bradcray** [comment]
I don't feel particularly strongly about this in either direction.  My thoughts are basically:

* While I can think of cases where we've wished for more symbols to have available to use for new things, I'm not coming up with cases where we wished `$` was available to us as that symbol.
* Most of the languages we look to for precedent do not support `$` in identifier names, so we would probably not lose much by retiring support for it
* Maybe it would be useful for a user's project's naming convention to have something special to set certain classes of variables apart?  But based on the previous bullet, it seems obvious that we'd be in good company without banking on that.
* I could see an argument that scripting languages support (really, probably "require"?) `$` in identifier names so maybe we're supporting a more palatable experience for such users by permitting them to retain that convention?  But I'm not sure I'm convinced by that argument, in part because I believe such cases often start identifiers with `$`, which we don't currently support anyway; in part because of the "require" belief above.
* It'd be easy to leave it in and probably not cause anyone any grief to do so

I think based on those thoughts, I'd at least mark it unstable, and potentially just deprecate it, but am curious what others think.

**Comment by lydia-duncan** [comment]
This feature has now been deprecated, closing
