### ISSUE TITLE
Figure out what to do with `single` variables

### ISSUE THREAD

**Issue by ronawho** [chapel-lang/chapel#23034]
`single` (assignment) variables are a restricted `sync` that can only be written to once. You could consider them a sort of optimization of a  `sync` in the same way a latch would be an optimization for a barrier in that single/latch can only be used once, but sync/barrier are reusable. So far as I know the original motiving use-case was a return value for futures, but futures haven't made it into the language yet.

Given the current lack of use-cases and that we don't actually optimize single's in any way, we've decided to make them unstable for 2.0 to allow us to change them in the future.

This issue is just meant to be a place to capture the current state and discuss future directions.

**Comment by bradcray** [comment]
I think it's accurate that `single` was intended to provide a future-like construct, where we'd originally imagined patterns like:

```chapel
var res1$, res2$: single int;
begin res1$ = doFuture1();
begin res2$ = doFuture2();
...then imagine lots of reads of res1$ and res2$ here...
```

I think these patterns are still reasonable, though over time it was pointed out that a good futures feature would want richer concepts than this, such as the notion of a begin expression.  But I don't think singles specifically would be needed for such a concept since the result of a `begin expr()` is a write-once/read-once variable, for which sync would be just fine.

I also think we thought of singles as being a general write once, read many concept.  I think of it as being sort of like a `const`, yet one that's useful in an asynchronous context where you can't know the `const` value at initialization time, and also don't know when you will know it; so you'd would want to block if you tried to read it before it's empty.  And, like most constants, you wouldn't want your read of its value to prevent others from reading it thereafter as well.

Of course, this made much more sense when implicit reads of syncs/singles were still supported.  That is, with singles, I can write:

```chapel
var x = res1$ + res2$;
var y = res1$ * res2$;
etc.
```

where it's nice and convenient to have a single value to be able to read the values again and again in their default form (where syncs would block on the second statement if I didn't override the default .readFE()).

But in a world like the current one where I have to apply methods explicitly to read singles:

```chapel
var x = res1.readFF() + res2.readFF();
var y = res1.readFF() * res2.readFF();
```

then it doesn't really matter whether the variables are sync and single since nothing is saved—the type no longer implies a useful default, and the restriction to a subset of the interface doesn't feel like a big win.... It's probably not going to save me from too many mistakes relative to just using the full sync interface.

I think this argues pretty strongly for deprecating single variables for simplicity/minimalism.

**Comment by ronawho** [comment]
Great, thanks for the additional context. I don't think I realized single's implicit read was a `readFF`, but of course it had to be. I agree that deprecation makes sense.

**Comment by ronawho** [comment]
Vote to deprecate
