### ISSUE TITLE
Passing external variable to a GPU kernels gets a garbage value in certain conditions

### ISSUE THREAD

**Issue by ShreyasKhandekar** [chapel-lang/chapel#23045]
### Summary of Problem
If we try to use scalar variables declared on the CPU inside a kernel, they can sometimes have garbage values inside the kernels instead of their correct values when using the `array-on-device` memory strategy.

This happens when we have the scalar declared before the `on here.gpus` block and is then used/modified again after the `on` block ends.

### Steps to Reproduce

In order to test the value of the variable inside the kernel, I use a workaround technique to print from inside a kernel.
This does not impact the behavior, the value inside is garbage regardless of if it is printed or using in another operation.

**Source Code:**

```chapel
use GPU;
use CTypes;
​
extern {
  static __device__ __host__ void printInt(int x) {
    printf("%d\n", x);
  }
}
​
pragma "codegen for GPU"
pragma "always resolve function"
extern proc printInt(x : c_int);
​
proc testValue(){
  var exp = 1234;
​
  on here.gpus[0]{
    @assertOnGpu
    foreach i in 0 .. 0 {
      printInt(exp:c_int); // prints garbage value
    }
  }
  exp = exp + 1; // Without this line there's no error and the printInt function prints the right value
}
​
testValue();
```

<details> 
<summary> Alternate Version that does not use printing, still gives garbage value </summary>

```chapel
use GPU;

proc testValue(){
  var exp = 1234;
  on here.gpus[0]{
    var result = [1,2,3,4];
    @assertOnGpu
    foreach i in result.domain {
      result[i]=exp;
    }
    writeln(result); // All elements are the same garbage value
  }
  exp = exp + 1; // Without this line there's no error and the printInt function prints the right value
}
testValue();
```
</details>

**Compile command:**
`chpl garbageKernel.chpl`

**Execution command:**
`./garbageKernel`

### Known workaround

If I explicitly copy `exp` to GPU memory before launching the kernel:

```chapel
var gpuExp = exp;
```
Then I get the correct result, but we should not be required to do this for scalar values.

### Configuration Information

<details>
<summary>Output of `chpl --version`:</summary>

```bash
❯ chpl --version
warning: The prototype GPU support implies --no-checks. This may impact debuggability. To suppress this warning, compile with --no-checks explicitly
chpl version 1.32.0 pre-release (12965f3967)
built with LLVM version 14.0.6
available LLVM targets: amdgcn, r600, nvptx64, nvptx, x86-64, x86
Copyright 2020-2023 Hewlett Packard Enterprise Development LP
Copyright 2004-2019 Cray Inc.
(See LICENSE file for more details)
```

</details>

<details>
<summary>Output of `$CHPL_HOME/util/printchplenv --anonymize`:</summary>

```bash
❯ $CHPL_HOME/util/printchplenv --anonymize
CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: llvm
CHPL_TARGET_ARCH: x86_64
CHPL_TARGET_CPU: native
CHPL_LOCALE_MODEL: gpu *
  CHPL_GPU: nvidia *
CHPL_COMM: none *
CHPL_TASKS: qthreads
CHPL_LAUNCHER: none
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: cstdlib
CHPL_GMP: bundled
CHPL_HWLOC: bundled
CHPL_RE2: bundled
CHPL_LLVM: system *
CHPL_AUX_FILESYS: none

```
</details>

**Comment by ShreyasKhandekar** [comment]
Capturing some of the offline discussion to bring this issue up to speed:

@DanilaFe said:

I think the behavior is incompatible with the way that we expect Chapel programmers to think of variables. In particular, I think the whole essence of Chapel is that if you can see a variable, you can access it, whether it involves communication or something like that. However, that mode of thinking breaks down with array_on_device, because sure, you can see the array / exp, but you need to perform a local copy of it, else things go really wrong if you use it on a GPU.


@stonea  said:

You should be able to write Chapel in a globally addressed way and be assured that it will always give the correct result even if doing so sacrifices performance by conducting costly communication or making a loop fail to gpuize (not something we do today but option I suppose).
Currently we're limited by the fact that we don't have a way to do PUTs/GETs from within a GPU kernel (there's been some thought of having the GPU "signal back" to the CPU to conduct the comm on its behalf but we haven't gotten too far with that).
Add to this, I think there's open questions / design issues that deal with what "default intents" (like `in`/`ref`/`const`) variables should have when passed to a `foreach`/`forall` loop.
 
Assuming these variables really do get passed in "by pointer", then I think things only really go wrong if: 
(1) you're using AOD, 
(2) you're executing inside a kernel, and 
(3) the (cpu-allocated) thing you're accessing is a scalar.  
If it's an array (or maybe anything heap allocated, I'm not sure?) than the data gets "page locked" and the GPU is able to access it using DMA.  IOW I think your original example would also work if you made exp an array.

**Comment by e-kayrakli** [comment]
I took a quick look at this as it looked pretty fundamental. https://github.com/chapel-lang/chapel/pull/23048 is the fix (test is still running). I'll also need to touch base with @stonea as to whether I should move forward with it without interfering with his intent work too much (probably not, the change is small).

When `exp = exp + 1` is in, the variable is passed to the `on` statement by ref. So, the loop `deref`s to get the value. However, our GPU transforms can't handle outer refs like that. Probably because of oversight. When you remove that statement, `exp` is RVF'ed so that it is not a reference to the actual thing but an actual integer that we create inside the `on` statement. That's safe to use within GPU kernels.

My PR will pass such arguments "by offload" as I like to call it. The runtime will allocate memory on GPU global memory and copy the data into it. It will pass the pointer to that address as an argument to the kernel. So, the kernel can actually safely deref it. I think that's the right choice for now, but down the road, we can consider creating a temp int value on host and passing that temp to the kernel as long as the int has `in` intent. I expect the default to be `const in` here.

---

> (1) you're using AOD,

@stonea -- can you elaborate? I don't see how AOD can throw things off here, but maybe I am missing some context.

**Comment by stonea** [comment]
> @stonea -- can you elaborate? I don't see how AOD can throw things off here, but maybe I am missing some context.

Not sure what I was thinking, I think I'm fixated on AOD for whatever reason.

What I'd like to now, is for 'unified memory' and 'AOD' modes, which are the following are safe:
* GET within a kernel to a host allocated scalar
* GET within a kernel to a host allocated array

I would expect, regardless of the memory strategy, scalars should "just work" because they get copied in by-value, right? But that's not what Shreyas is seeing (so maybe there's something wrong with my understanding).

I would expect GETs to a on-host array would also work with AOD since those get page locked.

For GETs of arrays in kernels when using um I don't recall of the top-of-my-head if those get allocated in unified memory (in which case it would just transparently work) or not.

**Comment by e-kayrakli** [comment]
> What I'd like to now, is for 'unified memory' and 'AOD' modes, which are the following are safe:


Ideally, both. But today, neither obviously, because GPU kernel bodies cannot have wide pointers today.

> I would expect, regardless of the memory strategy, scalars should "just work" because they get copied in by-value, right? But that's not what Shreyas is seeing (so maybe there's something wrong with my understanding).

Correct. The reason Shreyas is observing this behavior is because there are no shadow variables  in `foreach` loops today. If you replace `foreach` with `forall` where there are proper shadow variables implemented via default intents, I expect it will work (I don't have easy access to GPUs/cpu-as-device doesn't cover the case here). Because `exp` will have a `const in` intent, implying that it will be copied in when entering the loop. So, there will be a shadow of `exp` that's an actual value and that value will be passed to the kernel.

> I would expect GETs to a on-host array would also work with AOD since those get page locked.

Yes. Note that we can make that work without page locking, too. You just have to make one extra copy. Sometimes I wonder whether we should allow disabling page locking.

> For GETs of arrays in kernels when using um I don't recall of the top-of-my-head if those get allocated in unified memory (in which case it would just transparently work) or not.

I don't know what you mean here. You can't allocate arrays in GPU kernels today.

**Comment by bradcray** [comment]
> I took a quick look at this as it looked pretty fundamental. https://github.com/chapel-lang/chapel/pull/23048 is the fix (test is still running).

Impressively fast response, nice, Engin!

(now I'm just going to be jealous that my issues don't usually get fixes this fast... :) ).
