### ISSUE TITLE
Module import ambiguity bug when conflicting with package module

### ISSUE THREAD

**Issue by jeremiah-corrado** [chapel-lang/chapel#23100]
## Summary of problem

When compiling a chapel source file that has the following two properties:
- it is adjacent to a file called `search.chpl`[^1]
- it uses the `Time` module

An ambiguity error with the `Search`[^2] Package module is emitted, and the compiler hits an internal error in `frontent/lib/framework/Context.cpp:setFilePathForModuleId`

Note, this bug arose after [these seemingly unrelated changes]( https://github.com/chapel-lang/chapel/pull/22766/commits/0deffbd86882d6ddea45ed1dc0cb106022e2ae39#diff-97b289e5fce1179b949e8d692a8ba925a5cd03db09afe338764e26c886de1023) were made to the Time module (namely, `import JSON.JsonDeserializer` was added to `Time`)

## Steps to reproduce

I believe this bug only comes up on Mac OS or with case-insensitive filesystems . Here is my configuration:

<details>
<summary>printchplenv...</summary>

```
CHPL_TARGET_PLATFORM: darwin
CHPL_TARGET_COMPILER: llvm +
CHPL_TARGET_ARCH: arm64
CHPL_TARGET_CPU: native
CHPL_LOCALE_MODEL: flat
CHPL_COMM: none *
CHPL_TASKS: fifo *
CHPL_LAUNCHER: none
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: cstdlib *
CHPL_ATOMICS: cstdlib
CHPL_GMP: none *
CHPL_HWLOC: none
CHPL_RE2: none *
CHPL_LLVM: system *
CHPL_AUX_FILESYS: none
```
</details>

With the following programs in the same directory:

- `myFile.chpl`:
```chapel
use Time;
```

- `search.chpl`:
```chapel
// contents of this file don't matter
```

Compiling `myFile.chpl` will result in the following error:
```
warning: Ambiguous module source file -- using ./Search.chpl over $CHPL_HOME/modules/packages/Search.chpl
internal error: UTI-MIS-1041 chpl version 1.32.0 pre-release (03a08825ac)

Internal errors indicate a bug in the Chapel compiler,
and we're sorry for the hassle.  We would appreciate your reporting this bug --
please see https://chapel-lang.org/bugs.html for instructions.
```

[^1]: this only seems to be a problem with the search module, not other package modules (I tried a few others and did not encounter the same bug)
[^2]: note the difference in capitalization

**Comment by bradcray** [comment]
Here's a bit about what is going on:

* the changes in https://github.com/chapel-lang/chapel/pull/22766/ added new `import JSON...` statements to `Time`, which changed the order in which modules were searched for and resolved.  This can be recreated by comparing the output of compiling your test with `--print-module-files` with the `import` statements commented in vs. out
* something about that change causes the compiler to search for `Search.chpl` in the user's module path rather than just the standard + package module paths as it had before.  Specifically, the version with no `import JSON` finds it in `$CHPL_HOME/modules/packages/Search.chpl` while the version with finds it in `Search.chpl` and then generates the ambiguity error
* because of the case insensitivity, `search.chpl` is parsed as though it was providing the module `Search`
* then, `ensureRequiredModuleFilesAreParsed()` goes to check that we've parsed all the standard module files that we expected, finds that `modules/standard/Search` was not parsed, and takes another run at it, but the wheels fall off for some reason (that I didn't look into)

Tagging @benharsh because it looks as though he touched related code in https://github.com/chapel-lang/chapel/pull/20824 so may have thoughts or more information here.

I don't consider this particularly high-priority since we are generating the ambiguity error which demonstrates an issue, but I think the big question is what causes the difference in behavior w.r.t. whether `./` is considered part of the module path for `Search` or not (my guess is that it probably should always be in the search path since `Search` is a package rather than standard module, and I think we tend to consider package modules as though they were user modules?)

Beyond that, I'm wondering:  Despite Mac being case-insensitive, do we have any means of saying "OK, but what's the casing of this filename _really_?" and skipping over a file whose casing doesn't match the identifier we're looking for before opening it?  That would have the added benefit of making our behavior more consistent across OSes.

**Comment by benharsh** [comment]
I don't have any particularly deep insight here, and would need to dive into the frontend to see what's really going on.

I do think that using ``std::filesystem`` (from C++17) could generally improve the reliability of path-related code, and might have something to help us with the case sensitivity.
