### ISSUE TITLE
Detect tests with same names (modulo capitalization) as standard modules?

### ISSUE THREAD

**Issue by DanilaFe** [chapel-lang/chapel#23129]
We have had several issues in the past of tests (`sort.chpl`, `math.chpl`, `search.chpl`) having the same name as a standard module with the exception of capitalization (`Math.chpl`, etc.) This causes problems on some filesystems that are not quite case-sensitive (e.g. macOS). 

* https://github.com/chapel-lang/chapel/issues/23100
* https://github.com/chapel-lang/chapel/pull/22899

Whether or not the ambiguity is reasonable, we don't want to have to keep fixing our tests. It would be nice if there was some sort of "test" that runs in our suite that detects other similarly-named files, and fails if there are any. This way, we can be sure no test in the test suite conflicts with a standard module.

**Comment by lydia-duncan** [comment]
There's some value to being able to explicitly replace a standard or internal module with a locally defined one.  We use it to exercise failure modes that happen only in the standard or internal modules.  So I personally wouldn't want a hard failure, and any sort of list that tracks ones that are "okay" would have to be updated for new tests along those lines.

**Comment by bradcray** [comment]
@DanilaFe : On these issues, my head has recently been going to the question of "Even if Mac OS is case insensitive, isn't there some way in which our compiler could ask it what it thinks the name of the file is in a case-sensitive way?"  E.g., `ls` has a way it thinks the file should most naturally be printed, so can our compiler determine what that is and treat the files `Foo.chpl` and `foo.chpl` as defining `Foo` and `foo` rather than both of them defining whatever filename we happened to use when going to look for the file?  That led me to [this](https://stackoverflow.com/questions/69828470/get-case-correct-file-name-on-macos), which is tantalizing, but doesn't feel particularly conclusive.

@lydia-duncan: Don't we require the use of one of the `--prepend-[internal|standard]-module-dir` flags in order to treat a local file as a replacement for an internal/standard module?

**Comment by mppf** [comment]
> "Even if Mac OS is case insensitive, isn't there some way in which our compiler could ask it what it thinks the name of the file is in a case-sensitive way?"

One way is to use the equivalent of `file.path` to check that the file we opened has matching case to what we tried to open. That is implemented by `qio_file_path_for_fd` which has some ifdef logic for Mac OS X. I suspect there might be an LLVM Support library way to do this.

Another approach is to use directory listing instead of trying to open a file at various locations. (E.g., with dyno, we could have a query to provide the list of files present in a directory; we could invoke that for each of the module search path directories; and when handling a use/import, we could proceed by searching for the appropriate name in these cached directory listings).

Also, note that the `Ambiguous module source file` error is coming from `parser.cpp`. It would be good to move this warning (and perhaps more of the module search path processing) into dyno (which already has some such logic).
