### ISSUE TITLE
Should ref arrays and slices require explicit intent when used in `forall`s

### ISSUE THREAD

**Issue by e-kayrakli** [chapel-lang/chapel#23229]
Consider:

```chpl
use BlockDist;

var arr = Block.createArray(1..10, int);

ref localSlice = arr[{3..8}];

forall i in localSlice.domain {
  localSlice[i] = i;
}
```

should this code be legal? Or do we need `with (ref localSlice)` on forall?

With recent changes, compiler inference in this case is deprecated and will be removed. So, explicit intent will be required for `var` arrays. However, this case is more in the gray area as the symbol that I am using in the loop is already a ref.

This should be allowed because: I have already declared `localSlice` as a `ref`. Saying that the shadow variable must be a ref in the loop header feels redundant.

This should not be allowed because: The compiler isn't supposed to do any inference, technically `ref` slices/arrays like this could be assigned to a `var`, too. So, compiler using `ref` by default is still an inference and should not be done.

The current state on main is that this gets deprecation warnings.

**Comment by e-kayrakli** [comment]
Another related question is about `this` inside methods, which is `ref`. This comes up in https://github.com/chapel-lang/chapel/pull/23265/files#diff-0cd9e52cfbd4ff41c75d9cad95797584aea4d373353811f0c0966fda6211c614R366

**Comment by Iainmon** [comment]
Are all usages of variables in a `forall` loop that don't have references, treated as `const`? If so, requiring the `with (ref x)` for any x that is being assigned or mutated makes sense to me. I noticed when writing my Tensor record, it was confusing that I did not have to use `with (ref t)` when `t` was an array, but I did when `t` was a record. In this case, I think that `ref x` should be required even if it is already a reference.

**Comment by bradcray** [comment]
> Are all usages of variables in a forall loop that don't have references, treated as const? 

That is nearly the effect of @jabraham17's recent work in https://github.com/chapel-lang/chapel/pull/23175 (which might be better described as "make arrays have `const` default intent when entering forall loops").  I believe the only exceptions to your statement, at present, are `sync` and `atomic` variables, because it is in their nature to be used by `ref` in parallel contexts.

**Comment by bradcray** [comment]
> should this code be legal? Or do we need with (ref localSlice) on forall?

I think we should require the `ref` because if the point of this feature is to avoid races, whether you're talking about an OG array or a ref / view of one, you could have a race equally well.  That is, if we think:

```chapel
var A: [0..10] real;
forall i in 1..10 do
  A[i] = A[i-1];
```

should require a `ref` to opt into the race, it's not obvious to me why:

```chapel
var A: [0..10] real;
ref B = A;
forall i in 1..10 do
  B[i] = B[i-1];
```

would not be given equal protection.  That said, for your original case:

```chapel
forall i in localSlice.domain {
  localSlice[i] = i;
}
```

I could see potentially not needing the `with ref` due to the argument in: https://github.com/chapel-lang/chapel/issues/23488  (i.e., the iterator returns unique indices and is only used to access the array in a straightforward way, and the array is only written, so there can't be a race).

**Comment by jabraham17** [comment]
This was resolved by https://github.com/chapel-lang/chapel/issues/23819, any modifiable array or array slice does not need an explicit ref intent
