### ISSUE TITLE
Problem combining tuple unpacking formal and type queries

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#23302]
The compiler is giving strange errors when tuple unpacking and type queries are combined in a formal. This bug report came from https://chapel.discourse.group/t/repeated-query-of-size-of-type-in-argument-list/26585/3

``` chapel
use Math;

//inline proc cmplx1((x , y) : (real(?w), imag(?w)))
//{
//  writeln(w); // error: w undeclared [should be an error about w being redeclared]
//  return x * exp(y);
//}

// error: unable to resolve type
//inline proc cmplx((x , y)) where isRealType(x.type) && isImagType(y.type)
//{
//    return x * exp(y);
//}

// this version seems to work
// note: you could add `numBits(tup(0).type) == numBits(tup(1).type)`
//       if you want the real and imag to be the same width.
inline proc cmplx(tup)
  where isTuple(tup) && isRealType(tup(0).type) && isImagType(tup(1).type)
{
  const (x,y) = tup;
  return x * exp(y);
}

writeln(cmplx( (1.0, 40.0i) ));

// edit from BLC from the notes below:  Here's another case that doesn't work, but should:
//
// error: w and _w undefined in routine:
// proc foo((r, s) : (real(?w), imag(?_w))) {
//   if w != _w then compilerError("real and imag argument sizes must match!");
//   var c: complex(2*w) = (r, s): complex;
//  return c;
// }
```

**Comment by damianmoz** [comment]
Thanks for the workaround.

**Comment by damianmoz** [comment]
The original but problematic argument list was so elegant and clear.

It will be nice when it is fixed.

Actually, the following works.
```chapei
nline proc cmplx((r, s) : (real(?w), imag(?w)))
```
The only thing you have to remember is that _w_ cannot be used. I just added
```chapel
param w = numBits(r.type);
```
as the first line of the code (so you ignore the original _w_ in the argument list( and it works.

Scary stuff.

**Comment by bradcray** [comment]
I don't believe it actually should work, though, as Michael's `[should be an error about w being redeclared]` comment suggests.

Specifically, a `?w` in a formal type declaration is meant to be like the definition of a new identifier `w`, so having two of them in a single argument list is similar to saying:

```chapel
inline proc cmplx((r, s): (real(?), imag(?))) {
  param w = r.numBits();
  param w = s.numBits();
  ...
}
```

which ought to complain about the definition of the two identical identifiers at the same scope, [similar to what happens when similar constraints are put on standalone arguments `s` and `r`](https://ato.pxeger.com/run?1=m70sOSOxIDVnwYKlpSVpuhY3uzLzcjLzUhUKivKTFZJzC3IqNIqsFIpSE3M07Ms1dRSKERxNhWqF8qLMktScPA0lzzyIah2FksqC1GKFxKJUKyUdBY0ioBZNPZCYVXFJUWZeuqa1Qi0XF8RkDUM9IyuwccZGQLON9UysMnMT0zXMTDQ1Na0hLoI6DOZAAA).

```chapel
inline proc cmplx(r: real(?w), s: real(?w)) { writeln("In cmplx, types are:", (r, s).type:string); }

cmplx((1.2:real(32), 3.4:imag(64)));
```

The result being:

```
code.chpl:1: In function 'cmplx':
code.chpl:1: error: 'w' has multiple definitions
code.chpl:1: note: redefined here
```

> Actually, the following works.

I don't have a guess as to why that is, so agree with your final statement.  :)

> Scary stuff.

While I could imagine taking a more pattern-matchy / unification-oriented approach to interpreting multiple query arguments in a formal list, that'd be a pretty significant departure to the way the language has traditionally worked (and, at the very least, would need someone to champion it by opening up a new feature request issue).

**Comment by damianmoz** [comment]
We do not want any significant departure from current handling. Not special handling please. I agree that it ought to complain about the definition of the two identical identifiers at the same scope. It is just a bug in handling a generic tuple. If the elemenbts of the tuple are not generic, i.e have an explicit size such as 32 or 64 bits, the code works flawlessly. But I like programming generically because I often want to run algorithms in 32-bit mode and then check them against results in 64-bit mode.

Because the **real**(?w) and **imag**(?w) are in the same tuple definition, it would appear that they are being processed (effectively) concurrently (what do I know??) and do not know each other exists. For example
```chapel
inline proc cmplx((r, s) : (real(?w), imag(?_w))) // introduce a separate formal
{
    param w = numBits(r.type); // DELETE when bit in argument list fixed
    type Uint = uint(w);
```
This compiles but does not provide a `w` in the scope of the routine. I know that because
```chapel
inline proc cmplx((r, s) : (real(?w), imag(?_w)))
{
    // param w = numBits(r.type); // DELETE when bit in argument list fixed
    type Uint = uint(w); // this is Line 321 !!!!!!!!
```
fails with a message
```
test.chpl:318: In function 'cmplx':
test.chpl:321: error: 'w' undeclared (first use this function)
```
And for sure
```chapel
inline proc cmplx((r, s) : (real(?w), imag(?_w))) where w == _w // Line 318
{
    // param w = numBits(r.type); // DELETE when bit in argument list fixed
    type Uint = uint(w); // this is Line 321 !!!!!!!!
```
fails with a message
```
est.chpl:318: In function 'cmplx':
test.chpl:321: error: 'w' undeclared (first use this function)
test.chpl:318: error: '_w' undeclared (first use this function)
```
I can define a variant of my routine with an explicit **real**(32)/**imag(32) tuple as the argument and it works. I can then define another routine  with an explicit **real**(64)/**imag**(64) and it works. But I (and probably others) would prefer that the generic programming approach for a generic tuple (containing formal queries) in an argument list worked at some stage into the future.

I can upload the code if you want to play with it. But I (or you) can write a vastly simpler piece of code that has this same bug.

I hope I have described the situation adequately (and without typos).I am using 1.31.0. 

But for now, I have a program that works for my test cases so I have an overloaded routine `cmplx` that can create a complex number from any of
* a real by its lonesome
* an imag by its lonesome
* another complex which is trivial
* a real and an imag (or vica versa)
* the polar form of some other complex number

without the programmer having to mess with a **complex** coercion which you need to specify the type.

And I can continue with my documentation task knowing that what I am writing is not wrong (or rubbish) and maybe vaguely useful some day.

By the way, this little `cmplx` routine/function that converts (from) an argument in polar form routine uses the `transmute`method. It is so, so useful for programming the robust (optimal) processing of floating point arguments.

**Comment by bradcray** [comment]
We'd definitely agree that those size queries in the tuple type should be available in the where clause and procedure body.  I've updated the OP to include this example, thanks!

**Comment by damianmoz** [comment]
Thanks, I assume that OP = Operational Plan?

**Comment by bradcray** [comment]
"Original Post" in this case (the text that describes the issue at the top).

**Comment by damianmoz** [comment]
Is this related?  The following complains
```chapel
proc primefactorsfill(f : [?D] uint(?w), r : [D] uint(w))
```
It says that _w_ is used before being defined.

**Comment by bradcray** [comment]
Definitely related in that it's another case of queries not behaving as they ought to; but also potentially unrelated in that it wouldn't surprise me if fixing either issue didn't fix the other without additional work.  So it would probably be worthwhile spinning off a new issue for that case if you're up for that.

**Comment by mppf** [comment]
Just noting here that @damianmoz did make issue #23533 for the `primefactorsfill` case.

**Comment by dlongnecke-cray** [comment]
The frontend seems to handle scope resolving `tup: (int(?w), int(?w))` just fine and emits the duplicate symbol error. But it seems to turn a blind eye to `(x, y)...` the unpacking. I'll look to make my first patch there to avoid duplicate work.

**Comment by dlongnecke-cray** [comment]
This issue has been partially fixed by https://github.com/chapel-lang/chapel/pull/23830, but there are two futures I filed in that PR that I think we should fix before I'd consider this to be fully resolved.

They are:

- A segfault when resolving bitwidth queries in a tuple type
- Failure to resolve the type of a generic tuple value used in a where clause

**Comment by dlongnecke-cray** [comment]
The PR https://github.com/chapel-lang/chapel/pull/24392 will fix the `BitWidthQuery...` segfault.

**Comment by dlongnecke-cray** [comment]
The last bug is a bit more difficult to fix. When we normalize unpacked tuple formals like `(a, b)` we shove the definitions for `a` and `b` into the body. When we go to instantiate a generic signature we only do a "partial copy", just copying the signature and where clause.

I need to adjust this partial copy to include the definitions of `a` and `b` in the body.
