### ISSUE TITLE
Internal compiler error when using the `in` intent with exported procedures

### ISSUE THREAD

**Issue by twesterhout** [chapel-lang/chapel#23419]
### Summary of Problem

The following results in an internal error:

```chapel
export proc foo(in x : int) {
  if x < 10 then
    x = 11;
}
```

The error is:
```
internal error: COD-CG--XPR-3714 chpl version 1.32.0 pre-release (xxxxxxxxxx)
```

### Configuration Information

- Output of `chpl --version`:
```
chpl version 1.32.0 pre-release (xxxxxxxxxx)
  built with LLVM version 15.0.7
```
- Output of `$CHPL_HOME/util/printchplenv --anonymize`:
```
CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: llvm
CHPL_TARGET_ARCH: x86_64
CHPL_TARGET_CPU: none *
CHPL_LOCALE_MODEL: flat
CHPL_COMM: none *
CHPL_TASKS: qthreads
CHPL_LAUNCHER: none *
CHPL_TIMERS: generic
CHPL_UNWIND: system *
CHPL_MEM: jemalloc
CHPL_ATOMICS: cstdlib
CHPL_GMP: system *
CHPL_HWLOC: bundled
CHPL_RE2: bundled *
CHPL_LLVM: system *
CHPL_AUX_FILESYS: none
```
- Back-end compiler and version, e.g. `gcc --version` or `clang --version`:  LLVM 15.0.7

**Comment by bradcray** [comment]
Huh, looks like this is new since 1.31:  https://ato.pxeger.com/run?1=m70sOSOxIDVnwYKlpSVpuhY3bVIrCvKLShQKivKTFdLy8zUy8xQqFKwUMvNKNBWquRQUMtOAfBsFQwOFkozUPKCAApBvq2BoaM1VCzEDahTMSAA

The assertion it's tripping over has been there since 2016, so it seems that something upstream changed.

**Comment by bradcray** [comment]
Oh wait, no I'm wrong.  Though ATO doesn't give the error, my local build of 1.31 does...

**Comment by twesterhout** [comment]
@bradcray thanks for looking into this! And I'm really relieved that you can reproduce it, your first comment got me scared thinking it Nix's fault :D

**Comment by bradcray** [comment]
OK, the real difference is that it works with the C back-end (which is what ATO uses) but doesn't work with the LLVM back-end (on 'main' or in Chapel 1.31).

**Comment by bradcray** [comment]
Potentially obvious, but it appears that the following workaround works (basically, don't use an `in` intent and do the copy within the routine):

```chapel
export proc foo(xx : int) {
  var x = xx;
  if x < 10 then
    x = 11;
}
```

This is probably fine for `int` arguments, but may not be as nice for record/array arguments where the `in` argument gives the potential to "steal" the value without copying.

**Comment by twesterhout** [comment]
In my code, I did `if x < 10 then 11 else x` as an expression, bypassing the assignment, but your approach is more general. I'm wondering how big a deal it is that it doesn't work with record/array arguments -- are these often passed to `export`ed functions?

**Comment by bradcray** [comment]
Good point, probably not.  And `in` arguments in the context of exported functions are a bit weird in general anyway because, as of a few years ago, we moved the handling of the copies for `in` from the callee to the caller.  So `in`, probably technically, can't be supported for `export` routines, at least without telling the external caller to do the copy themselves and pass in a `ref` to it.  But in that case, why not just require `ref` to be the intent?

Or, maybe the callee should do the copy in the case of an exported routine, and the steal optimization should be disabled?  This may make sense because otherwise, I think we can only accept `ref`/`const ref` input arguments?  (which seems like a weird restriction... I can't pass a C int into an exported Chapel routine?

Though now I'm doubting everything I've written because when I look at the C prototype generated for the routine, it isn't passing a pointer but just a value (whether or not it's marked `export`).  Maybe we don't bother with the pointer for simple types like `int` since it'd be overkill?

Tagging @mppf on this to have him set me straight, as I consider him to be the expert on `in` intents.

(one other thing to keep in mind in this discussion is that even though an `export` function is designed to be called from outside of Chapel, they can be called from within Chapel as well...)

**Comment by mppf** [comment]
> Maybe we don't bother with the pointer for simple types like int since it'd be overkill?

That's right

More broadly speaking, I think it's good for us to not allow `in` intent on `extern`/`export` routine formal arguments right now, with the exception of possibly allowing it for the built-in numeric types. The reason for this is that C code doesn't know how to copy appropriately when passing in & we don't provide a way to call these copy initializers manually from C, either. In the future, I think it'd be reasonable to allow `in` intent on `extern`/`export` routine formal arguments provided that the type in question is trivially copyable (or POD, to use a C++ term).

> (one other thing to keep in mind in this discussion is that even though an export function is designed to be called from outside of Chapel, they can be called from within Chapel as well...)

Yes, I think it's a point of some debate as to whether it is reasonable to expect that `export` will work with all Chapel types / code forms when calling it from other Chapel code -- or if it should be more restricted to the cases that work with C interoperability. (And, if it can be used for Chapel code, what is the purpose of doing so? Is it merely for testing the interoperability code? Or is it some way to achieve separate compilation?). Anyway that's for another issue if you want to debate it.

Anyway, I think that it's good for us to go with the restricted view for now. Note that if we relax it in the future, we can use the trick of turning one `export proc` into two routines; where one is to be called from C and another is to be called from Chapel. (However, this does not appeal to me, because it means that you can't test the interoperability code from Chapel, because you will be calling it in a totally different manner)

**Comment by bradcray** [comment]
@twesterhout : You may have gotten a notification, but I wanted to mention that this should be resolved thanks to @vasslitvinov 's work.  Please let us know if you find otherwise, and thanks for reporting the issue!
