### ISSUE TITLE
GPU locale model crashes with localSubdomain queries on multidimensional arrays/domains

### ISSUE THREAD

**Issue by daviditen** [chapel-lang/chapel#23574]
### Summary of Problem
The GPU locale model crashes when compiling the distributions primer: `test/release/examples/primers/distributions.chpl`. The code in this issue is reduced from that file.

### Steps to Reproduce

**Source Code:**

```chapel
use BlockDist;

config const n = 8;
const Space = {1..n, 1..n};

const BlkDist = new blockDist(boundingBox=Space);
const BlockSpace = BlkDist.createDomain(Space);
var BA: [BlockSpace] int;

const myIndices = BA.localSubdomain();
```

**Compile command:**
```bash
$ chpl reduced.chpl  --no-checks
$CHPL_HOME/modules/dists/BlockDist.chpl:1882: internal error: Unexpected symbol expression [/gpuTransforms.cpp:1031]
```

### Configuration Information
```bash
$ printchplenv --anonymize
CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: llvm *
CHPL_TARGET_ARCH: x86_64
CHPL_TARGET_CPU: native
CHPL_LOCALE_MODEL: gpu *
  CHPL_GPU: cpu *
CHPL_COMM: none *
CHPL_TASKS: qthreads
CHPL_LAUNCHER: none
CHPL_TIMERS: generic
CHPL_UNWIND: bundled *
CHPL_MEM: jemalloc
CHPL_ATOMICS: cstdlib
CHPL_GMP: bundled *
CHPL_HWLOC: bundled
CHPL_RE2: bundled
CHPL_LLVM: bundled *
CHPL_AUX_FILESYS: none
```

```bash
$ chpl --version --no-checks
chpl version 1.33.0 pre-release (30ff6893f3)
  built with LLVM version 15.0.7
  available LLVM targets: amdgcn, r600, nvptx64, nvptx, aarch64_32, aarch64_be, aarch64, arm64_32, arm64, x86-64, x86
Copyright 2020-2023 Hewlett Packard Enterprise Development LP
Copyright 2004-2019 Cray Inc.
(See LICENSE file for more details)
```

**Comment by daviditen** [comment]
I added a .skipif case for the distributions.chpl test for this case. Once this issue is fixed remember to remove this .skipif condition.

**Comment by e-kayrakli** [comment]
We seem to get a goto that we don't handle during our GPU transformations. If the goto's target is somewhere within the same function, we should just be able to copy it directly. So, it may be an easy fix.

I got bogged down trying to come up with a simpler reproducer and failed. However the following diff makes this code compile:

```diff
diff --git a/modules/dists/BlockDist.chpl b/modules/dists/BlockDist.chpl
index 64b5e41ef2..6574ddc91c 100644
--- a/modules/dists/BlockDist.chpl
+++ b/modules/dists/BlockDist.chpl
@@ -1879,10 +1879,11 @@ proc BlockImpl.dsiTargetLocales() const ref {
 }

 proc BlockImpl.chpl__locToLocIdx(loc: locale) {
+  var ret = (false, targetLocDom.first);
   for locIdx in targetLocDom do
     if (targetLocales[locIdx] == loc) then
-      return (true, locIdx);
-  return (false, targetLocDom.first);
+      ret = (true, locIdx);
+  return ret;
 }

 // Block subdomains are continuous
```

So that goto has something to do with multiple returns coming from different branches of a conditional. But why we generate that goto in the first place is probably irrelevant.

---

But while trying to create a reproducer, I realized that the code in OP doesn't fail for 1-D `Space`. So I propose we rename this issue as something like "GPU locale model crashes with localSubdomain queries on multidimensional arrays/domains"
