### ISSUE TITLE
Overlapped array assignment exhibits different behavior on CPU than GPU

### ISSUE THREAD

**Issue by stonea** [chapel-lang/chapel#23690]
In the following program there's an assignment `rightA = A` where `rightA` is a ref of a slice of  elements of `A`.  If we do this assignment on the CPU it looks like we handle this somehow (maybe we generate a copy first?) so that the assignment doesn't end up copying values that were themselves overwritten during the assignment. Whatever magic we're doing for the CPU doesn't appear to be happening when on the GPU.

So IOW, if I compile and run the following and run with `./foo --doOnGpu=false` this runs fine without complaint, but if I do `./foo --doOnGpu=true` it'll trigger my error message:

```
config const N = 1024 * 1024;
config const doOnGpu = true;

var HostCopyOfA : [0..N] int;
const loc = if doOnGpu then here.gpus[0] else here;

on loc {
  var A : [0..N] int;

  foreach i in 0..N do A[i] = i;

  ref rightA = A[2..N];
  rightA = A;

  HostCopyOfA = A;
}

for i in 2..N {
  if HostCopyOfA[i] != i-2 then writeln("Invalid value found at: ", i);
}
```

At one point I had a draft PR for this test (https://github.com/chapel-lang/chapel/pull/20628) where I had some comments indicating that (at the time I made the draft PR) it was working. Apparently, this is no longer the case.

**Comment by bradcray** [comment]
We definitely don't generate a copy in Chapel (or, if we are, that's a bug and we shouldn't be).  Since this is race-y code by nature (the forall asserts these iterations are order-independent, when they aren't), my guess is that you're "getting lucky" on the CPU somehow.  Specifically, I'd guess that the arrays are large enough that the places where tasks overlap in read/write ownership happen to be read before the neighboring tasks try to write the updated values to the same locations.  [Changing to a left-shifted version of the array](https://ato.pxeger.com/run?1=XVG7TsMwFBWrv-K0E6AmChEDasQQMQBL-wFRBiuxG0vGjhy7CCG-hKULfBRfw7XDozBd6dzz8vXrezfwUejD4S14mV19nDx01ki1A43JY4NrXBTlJc7TqNifbW-35nYMxJFcT6JibM8d7uzkb-z4tJU11miKPN-0UMYnMam07Uih5I_cD8JgEE7kuzFMTdFCkFtCyNKapHhmQHT_70mwtI5rDUUA4oaMUTeqjSmJ4ISEFtLXhNRJnJVtRYtfsIyOiXxcnzYVe2GMEmb7SEtVqP4RMYYtKC0r58c8OuWFNqfLe7PnWvXUXAdBRYPpwf0ayxXUGVnPV_86_vcnfAI) seems to confirm this/

Also, note that the assignment itself is illegal since `rightA.size != A.size` and that the code complains about this when not compiled with `--fast` (fixed in the left-shifted version above and [here](https://ato.pxeger.com/run?1=XZE9TsQwEIVF61M8tgJEohBRoI0oIgqg2T1AlMJK7MSSZUeOvQghTkKzDRyK0zB2-NmlsvRmvvdmxm8f3cgnoff79-BldvN5YjtrpBpAz-yxwS2uivIaF-mp2FG1t1tzPwXqkVzPomJsxx0e7Ozv7PS8lTXWaIo837RQxieYKG07IpT8xf0oDEbhRD5MYW6KFoLckkKW1iTihQHR_b8nydI6rjUUCYgVMkbdqDampAYnJJwaRl-TVDdlpKuo_2mRy8o2tR8uQLWKvTJGGUtAhNMwtMBBY4w7pbysXNZ5csoLbc5Wj2bHteppdh0EjRpMD-7XWF1CnZP1cvfv8_98wxc) for the right-shifted version).

**Comment by stonea** [comment]
> We definitely don't generate a copy in Chapel (or, if we are, that's a bug and we shouldn't be).

I think we end up, ultimately, for an A=B assignment calling `chpl_memmove` which calls the C `memmove` function, which does some magic to handle the overlap: https://man7.org/linux/man-pages/man3/memmove.3.html ("The memory areas may overlap: copying takes place as though the bytes in src are first copied into a temporary array that does not overlap src or dest, and the bytes are then copied from the temporary array to dest.")

I would guess we're deliberately using `memmove` rather than `memcpy` specifically to handle these sorts of cases? If not, then I'd agree this is undefined behavior and we could ignore that I'm getting a different result for CPU and GPU.

For your left-shifted example you'd need to update the verification code to do `if HostCopyOfA[i] != i+2` instead of `!= i-2` and iterate 0..N-2. If I make those changes then it looks like it passes fine

**Comment by bradcray** [comment]
> For your left-shifted example you'd need to update the verification code to do if HostCopyOfA[i] != i+2 instead of != i-2 and iterate 0..N-2. If I make those changes then it looks like it passes fine

Derp, my bad.  Going too fast such that when it confirmed my expectations, I didn't look harder.

> I would guess we're deliberately using memmove rather than memcpy specifically to handle these sorts of cases? If not, then I'd agree this is undefined behavior and we could ignore that I'm getting a different result for CPU and GPU.

No, if we're using it, it's strictly for performance reasons, not to deal with race conditions.  An array assignment like this is semantically equivalent to:

```chapel
forall (r,a) in zip(rightA, A[0..n-2]) do
  r = a;
```

and we don't make any guarantees about what happens when the iterations of a forall aren't actually order-independent—the resulting behavior is on the user to deal with.

I definitely think there's nothing to be done here for the GPU to try and match the CPU's behavior.

**Comment by stonea** [comment]
> No, if we're using it, it's strictly for performance reasons, not to deal with race conditions. An array assignment like this is semantically equivalent to:

Ok great, it definitely simplifies things for gpus if we don't have to maintain `memmove` semantics. I'll close this issue.
