### ISSUE TITLE
Apparent bug in readBinary() (for sufficiently large files?  sufficiently large offsets within files?  array slice reads?)

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#23800]
### Summary of Problem

While working on updating codes to use new features, I ran into a problem with test/studies/shootout/submitted/revcomp5.chpl in which converting from an old-style binary fileReader + read() routine to a readBinary() call, I found that the input had become corrupted.  I then boiled the code down to a simpler one that just reads in and writes out enough of the data file to show that the input set is not preserved.  Reverting to the old-style reads makes the code work, as does compiling with `-sIOSkipBufferingForLargeOps=false`.

### Steps to Reproduce

**Associated Future Test(s):**
[`test/studies/shootout/reverse-complement/bradc/bugs/revcomp-mirror.chpl`](
           https://github.com/chapel-lang/chapel/blob/main/test/studies/shootout/reverse-complement/bradc/bugs/revcomp-mirror.chpl
          ) #23797

### Configuration Information

- Output of `chpl --version`: `chpl version 1.33.0 pre-release (fcd1910b3d)`

**Comment by bradcray** [comment]
@jeremiah-corrado : I'd be curious if you had any insight into what might be going wrong here.  As a pointer to the type of corruption that's occurring compare:

https://github.com/chapel-lang/chapel/pull/23797/files#diff-d387dbe9602166a65f42a9e8d6f82a10c94f6971ba5911dea57aaf9605fc112bR1075-R1077

to

https://github.com/chapel-lang/chapel/pull/23797/files#diff-956cf950a21dd73e8db9b6927ae92e927219448f5f3ce1e75ce74997b0f618d9R1075-R1077

It may be a red herring, but the byte offset where this is occurring seems to be right around 2**16, which may or may not be meaningful.

Somewhat surprisingly to me, if I read a much larger file, I only have seen a single corruption like this in it; not one for every 1075 lines or so...

**Comment by jeremiah-corrado** [comment]
Interesting, I'm not exactly sure what's going on off the top of my head, but I'll look into this more.

Some things that jump out at me right away:
* 2**16 does line up exactly with the size of a single "chunk" in the QIO buffer (see `qbytes_iobuf_size` in `qbuffer.c`). 
* It looks like the first buffer "chunk" worth of data is being read via the buffering mechanism because none of first few reads are large enough to bypass it (larger than `qio_read_unbuffered_threshold`)
* Then, it looks like there is some kind of bug (maybe with updating the file offset) when transitioning from using the buffering mechanism to executing reads directly from the file.
   * The delta only shows up once because the subsequent reads are all large enough to bypass buffering

I have a test that exercises a similar pattern to your revcomp-mirror program, but it doesn't seem to suffer from the same issue because it's working with operations much smaller than a buffer "chunk": https://github.com/chapel-lang/chapel/blob/main/test/io/corrado/buffering_optimization/growing_buff_read_write.chpl

I'll see if I can fix this tomorrow.

**Comment by bradcray** [comment]
OK great, that explanation makes a lot of sense—a discontinuity as we transition between mechanisms.  Thanks for taking a look and I hope the cause and fix turn out to be obvious.
