### ISSUE TITLE
Improve IO's bulk read/write performance when endianness is non-native

### ISSUE THREAD

**Issue by benharsh** [chapel-lang/chapel#23857]
At the time of this issue's creation using an endianness like ``ioendian.little`` or ``ioendian.big`` does not take advantage of bulk reads or writes in methods like ``fileReader.readBinary``, even when the desired endianness matches the system's endianness. This can cause surprisingly poor performance when the non-native cases devolve into element-by-element reads.

I think we should add a utility (perhaps developer-only) to the IO module that returns the system's endianness, and use it in places where we optimize for ``ioendian.native`` to check if the non-native endianness matches the system's endianness.

**Comment by bradcray** [comment]
"Write a C routine that can detect the endianness of a system" was a common systems-y interview question when I was looking for jobs.  Happily. I think I could still manage that without a Google search.  :D

I think we recently discussed whether these routines should just throw up their hands when used in the non-native endianness mode since they're designed to be more of a low-level way to blast out a bunch of bytes rather than anything terribly smart, which I'm still open to.  That said, I'd still implement this issue, in the sense that I'd make it fast for native or the explicit equivalent of what native is and just throw up my hands in the final case.

**Comment by bradcray** [comment]
I've got a start on this in https://github.com/chapel-lang/chapel/pull/23866

**Comment by bradcray** [comment]
This was resolved by #23866, which I merged this evening, but forgot to link to this issue.
