### ISSUE TITLE
Can we constrain where nested functions with outer variables can be called?

### ISSUE THREAD

**Issue by dlongnecke-cray** [chapel-lang/chapel#24053]
Chapel allows functions to be called _before_ their point of definition. This is useful because it sidesteps the need for "declaration before use" in languages like C (which can lead to a bunch of redundant boilerplate).

Naturally, this rule also applies to _nested_ functions:

```chapel
proc main() {
  var x = nested();
  proc nested() do return 1;
}
```

A simple case such as the above is trivial to support, but nested functions can also refer to _outer variables_, which are variables defined in a parent function(s):

```chapel
proc main() {
  const g = 8;
  var x = nested();
  proc nested() do return 2*g;
}
```

This will compile today, however it's a bit frustrating to type.

I think that it would be nice if the language would uniformly constrain only nested functions such that: "**a nested function cannot be invoked before its definition**".

This means you wouldn't be able to write the above program. Instead you'd have to write:

```chapel
proc main() {
  const g = 8;
  proc nested() do return 2*g;
  var x = nested();
}
```

I find this to be a bit more intuitive to read and understand. It would also be an easier rule for the compiler to implement and explain while achieving roughly the same ordering constraint as would be required for the first code.

**Comment by bradcray** [comment]
Hi David —

I agree that your second through fourth programs should not be legal.  That said, to me, nothing about these is specific to the nested context, since the same issues could be encountered [at module-scope.](https://ato.pxeger.com/run?1=m70sOSOxIDVnwYKlpSVpuhY3vcsSixQqFGwV8vLz8lKLS1JTNEw0rbmS8_OKSxTSgeJG1lwFRfnJSPLlVgqZeSWaCtUKRaklpUV5CuUKWgrp1gq1ECOhJsNsAAA).  For example,

```chapel
var x = nonnested(4);
const g = 2;
proc nonnested(w: int) { return w * g; }
```

yields:

```bash
testit.chpl:3: In function 'nonnested':
testit.chpl:3: error: use of 'g' before encountering its definition, type unknown
```

I think this error message could be improved and clarified, but consider it to be an indicator of the problem you're highlighting: an attempt to read a variable before it has been initialized.

For that reason, I think your proposal:

> I think that it would be nice if the language would uniformly constrain nested functions such that: "a nested function cannot be invoked before its definition".

is too strict, since I don't think we'd want to apply that constraint to non-nested routines, and don't need to.  Instead, I think the restriction should relate to the position of the calls to the procedure relative to where that procedure's non-local references are declared and initialized.

**Comment by dlongnecke-cray** [comment]
> is too strict, since I don't think we'd want to apply that constraint to non-nested routines, and don't need to

I'm only advocating we constrain _nested_ functions, though. Even more specific, it would only have to be nested functions that capture.

I was probably overly selective in my examples in the OP despite my best attempts not to be 😄.

My proposal would mean that you wouldn't be able to write:

```chapel
proc main() {
  var x = nested();
  const g = 8;
  proc nested() do return 2*g;
}
```

This is a much better example (I think I'll update the OP with it).

There could be an arbitrary amount of code between the call to `nested` and its definition, and all of that code would need to be resolved before we could try to type `nested`. We can't simply pluck it out at its point of call and try to type it, because it refers to `g` (and N other potential dependencies we could conjure up). And the situation becomes even more difficult if that code in-between is dependent on `x`.

Under my proposed rules, you'd have to write:

```chapel
proc main() {
  const g = 8;
  proc nested() do return 2*g;
  var x = nested();
}
```

It sounds like you're advocating (feel free to correct) for something like:

```chapel
proc main() {
  const g = 8;
  var x = nested();
  proc nested() do return 2*g;
}
```

If that's the case, is there that big of a difference between this and the above? There is still a very heavy ordering constraint. It seems like the first is more simple to explain (must call after definition, instead of saying, must call after `g`) while also having the same effect.

Additionally, we could also relax the first constraint into the second over time.

**Comment by dlongnecke-cray** [comment]
I've updated the OP to be more reflective of the actual problem. Thanks for your helpful examples, Brad.

**Comment by bradcray** [comment]
> My proposal would mean that you wouldn't be able to write ...

I'm still confused because that example also [doesn't work at module-scope](https://ato.pxeger.com/run?1=m70sOSOxIDVnwYKlpSVpuhY3HRUUyhKLFCoUbBXyUotLUlM0NK25FBSS8_OKSxTSgaIWIG5BUX4yXF4hJV-hKLWktChPwUgr3RpiENQ8mLkA) (so it still doesn't seem specific to nested functions to me).

> it would only have to be nested functions that capture.

I don't view your nested function as "capturing", merely referring to a symbol declared at the same scope as the procedure itself.  If they were returned from the outer procedure, then capturing would seem to come into play (but since that's more closure-like, and we don't support closures yet, I don't feel like that's a case we should focus on for now.

> It sounds like you're advocating (feel free to correct) for something like:

My working proposal would be that no procedure (whatever the scope) should be able to be called if it refers to a variable/const whose declaration point would be executed after the call itself (since that would be a use-before-def, temporally speaking).

**Comment by dlongnecke-cray** [comment]
Yeah, I've updated the OP and my first comment now that my understanding of the problem has finally snapped into place. I'm advocating for a more strict rule than currently exists. I've also removed the word "capturing" since I agree that it means something different than what i intended.

**Comment by damianmoz** [comment]
In terms of recommended practice, one should try and define routines (and obviously variables) before use. It certainly makes things more readable,

**Comment by bradcray** [comment]
The previous comment I was replying to has changed since my last comment, so I went back and read the revised OP.

> however it's a bit frustrating to type

Assuming you mean "for the compiler to type-resolve", it's not clear to me what makes it more complicated or frustrating than putting the body of the procedure at module-scope.  Can you clarify that?

An obvious downside of your proposal is that it wouldn't be possible to create mutually-recursive nested routines, which seems limiting.  It also places stricter constraints on nested procedures than on module-scope procedures, which seems unfortunate to me, at least without a rationale that I'm not seeing.

Generally, my belief is "if something can be written at module scope, it should be able to be refactored into a local scope if at all possible" where there are some obvious exceptions, like sub-module declarations not making sense at scopes other than module scope.  (Implementation-wise, there have been other exceptions, but the ones I'm thinking of have been more due to lack of implementation effort rather than the concept not making sense).

On Damian's comment:

> one should try and define routines (and obviously variables) before use

I don't necessarily agree with that (not that I would object to anyone preferring that style in their code).  Specifically, when reading code top-down (which Chapel was designed to support) rather than bottom-up, it can often be useful to read the high-level algorithm without getting into the details of how procedures supporting that algorithm are defined.  I think the Chapel [computer language benchmarks game entries](https://benchmarksgame-team.pages.debian.net/benchmarksgame/fastest/chapel.html) and some of the [Advent of Code 2023 blog series entries](https://chapel-lang.org/blog/posts/aoc2022-day03-rucksacks/) are good examples of this principle, where you can start at the top of the file, get a sense of the overall flow of the program, and then dive into its supporting procedures when interested, or just assume you can correctly guess what they do based on their name if not.

(I say "bottom-up" for C-like languages, but it's not even that.  It's like 'bottom-up" for the top-level declarations, but then "top-down" within each class, function, whatever to consider the execution order.  Contrast that with Chapel where you can make the execution order and reading order generally match, modulo recursion).

**Comment by dlongnecke-cray** [comment]
I had never even considered mutually recursive nested routines. That seems like a feature worth supporting.

RE: Implementation difficulties:

Due to the architecture of the new compiler, a lot of functionality is factored into separate queries that don't have access to some state such as outer variable types. The outer variable types need to be known when the initial signature is first prepared as a candidate. So when `nested()` is called, we need to have the type of `g` present so that it can be stored in the signature. And it's a bit of a PITA to get it there, but it's nothing we can't work around.

Having the property that you can construct the signature at the point of definition spares a lot of that pain, because it means that a lot of our API can remain intact as it is today.

I'm closing this since it seems like a feature we'd like to continue to support.
