### ISSUE TITLE
Record variable considered const inside forall?

### ISSUE THREAD

**Issue by sdbachman** [chapel-lang/chapel#24074]
I'm getting some strange behavior when trying to update a record variable inside a FORALL loop (see arrow below).   When trying to compile I get 

arrays.chpl:100: In function 'update_dynamic_arrays':
arrays.chpl:111: error: cannot assign to const variable

but when I change the enclosing loop to a basic FOR loop it compiles fine.   Is this expected?   Am I doing something wrong?

-------------------------------------------  

```chapel
class Domains {
  var rho_3D : domain(4);
}

record Arrays {
  const r0, r1, r2, r3 = 1..0;

  var h : [r2, r3] real;
  var thickness0 : [r1, r2, r3] real;
  var dHdt : [r0, r1, r2, r3] real;

  var zeta_old : [r0, r2, r3] real;
  var zeta_new : [r0, r2, r3] real;

  proc init(arg: Domains) {
    this.r0 = arg.rho_3D.dim[0];
    this.r1 = arg.rho_3D.dim[1];
    this.r2 = arg.rho_3D.dim[2];
    this.r3 = arg.rho_3D.dim[3];
  }
}

proc update_dynamic_arrays(ref A: Arrays, D: Domains, infiles, step : int) {

  // Read in SSH, update thicknesses
    A.zeta_new = get_var(infiles[step], "zeta", D.rho_2D);

    if (step == Nt_start) {
      A.zeta_old = A.zeta_new;
    }

  // From SM09, Eq. 2.13
    forall (t,k,j,i) in D.rho_3D {
      A.dHdt[t,k,j,i] = A.thickness0[k,j,i] * (A.zeta_new[t,j,i] - A.zeta_old[t,j,i]) / (A.h[j,i] / dt);     <-----------------------
    }
```

**Comment by bradcray** [comment]
Hi Scott —

This is expected.  To explain why, as background, Chapel strives to prevent programmers from accidentally writing race conditions like the following:

```chapel
var total = 0;
forall i in 1..1_000_000 {
  total += i;
}
```

(where the potential for a race here is that multiple threads running iterations of the loop concurrently might each read the same value of `total`, increment it with their personal value of `i`, and then store the result back, where one thread could overwrite the updates made by others).

What Chapel does to prevent inadvertent races like this is to introduce a _shadow variable_ for any outer variables (like `total` here) that is referenced within a parallel construct (like this `forall`).  These shadow variables are made `const` to avoid such mistakes.  Typically, the error message refers to the shadow variable concept, but it looks like that's not the case for your code?  That definitely bears more looking into.

One reason you may not have seen this in the past is that arrays get a free pass and have not traditionally generated shadow variables—the reason being that we found such cases to be more onerous than not, particularly since many forall loops access arrays in ways that are parallel-safe.

Records, however, do generate `const` shadow variables, resulting in the problem you're hitting even though (ironically) you're using them to wrap arrays which would normally get that pass.

The way you can override the default `const` shadow variable for a variable is using a _with-clause_, which says how you want each task to see the outer variable.  For example, if I wanted the race in my original program, I could write:

```chapel
var total = 0;
forall i in 1..1_000_000 with (ref total) {
  total += i;
}
```

to say that each task should simply refer to the original variable.  Running this on a multicore processor, you will likely see different results for `total` on different runs due to the race.

Though I didn't digest your whole program, glancing at the indexing expressions in your loop, I expect you could use this technique since it appears that each iteration writes to unique elements of the array field and there are no loop-carried dependencies:

```chapel
  // From SM09, Eq. 2.13
    forall (t,k,j,i) in D.rho_3D with (ref A) {
      A.dHdt[t,k,j,i] = A.thickness0[k,j,i] * (A.zeta_new[t,j,i] - A.zeta_old[t,j,i]) / (A.h[j,i] / dt);     <-----------------------
    }
```

There are also other options that can be used within `with-clauses`.  For example, for my simple example, I could use a `reduce` intent to specify that each task should get its own copy of `total` and that they should be added up as the tasks end:

```chapel
var total = 0;
forall i in 1..1_000_000 {
  total += i;
}
```

This doesn't look like what you'd want in your loop, though.

It has occasionally been proposed that perhaps we should introduce shadow variables on `for`-loops as well for consistency, but I've pushed back against this proposal because I think it would simply be too weird and onerous given that they're not necessary (for-loops don't introduce races) and would be completely different than what people would expect coming from other sequential languages.  Anyway, that's why you don't see the same behavior with a for-loop today.

There's more information on these task intents and with clauses [here](https://chapel-lang.org/docs/primers/forallLoops.html#task-intents-and-shadow-variables}, [here](https://chapel-lang.org/docs/language/spec/task-parallelism-and-synchronization.html#task-intents), and [here](https://chapel-lang.org/docs/language/spec/data-parallelism.html#forall-intents).

Give a shout if you have additional questions here.

**Comment by bradcray** [comment]
> Typically, the error message refers to the shadow variable concept, but it looks like that's not the case for your code? That definitely bears more looking into.

Validating this, a simple program like mine [does mention shadow variables in the error message](https://ato.pxeger.com/run?1=m70sOSOxIDVnwYKlpSVpuhY3LcsSixRK8ksScxRsFQysudLyixJzchQyFTLzFAz19AzjDQwMQFihmksBqk7bViHTmqsWYgDUHJh5AA), while a case with [an array field in a record like yours does not](https://ato.pxeger.com/run?1=m70sOSOxIDVnwYKlpSVpuhY3k4pSk_OLUhSCFKq5FBTKEosUHK0Uog319AzjDQwMQDhWoSg1Mceaq5aLCyRdZKUQZM3FlZZflJiTo5CpkJmngKwabEyRnmN0ZqyCtq2CIVAfxCaohTCLAQ).

I'm not sure why that would be.  Taking a shot in the dark, @vasslitvinov or @jabraham17, would either of you know why?

**Comment by jabraham17** [comment]
I expect the difference in error messages is because of the field access. The compiler marks the record variable as const, and then attempting to modify its const fields is just a const check. [This program trying to modify the record directly](https://ato.pxeger.com/run?1=m70sOSOxIDVnwYKlpSVpuhY3K4tSk_OLUhSCFKq5FBTKEosUMhVsFQysgZz8gtSixJL8IgVtW42i1DSFIiuFIB2FCiuFzLwSTYWUfIUivUygnEKFNVctFxdIK0iFNRdXWn5RYk4O0KDMPAVDPT3DeAMDAxAGWwEyTiETqAXiAKg7YO4BAA) fails with a mention of shadow variables, while [this program doing the same action through a field](https://ato.pxeger.com/run?1=m70sOSOxIDVnwYKlpSVpuhY3q4tSk_OLUhSCFKq5FBTKEosUMhVsFQysgZz8gtSixJL8IgVtW42i1DSFIiuFIB2FCiuFzLwSTYWUfIUivUygnEKFNVctFxdIK0iFNRdXWn5RYk4O0KDMPAVDPT3DeAMDAxAGWwHVlAnUBHEC1CUwFwEA) fails as just a plain const invalid access.

**Comment by bradcray** [comment]
Thanks for the quick analysis Jade.  I'll file an issue suggesting we try to clarify the error to trace that the record is const due to a shadow variable and similarly specialize the error message.

**Comment by bradcray** [comment]
I believe that we can now close this issue, as the original behavior is as-intended and Jade's https://github.com/chapel-lang/chapel/pull/24089 improved the error message issue.  @sdbachman and @jabraham17, please let me know if I missed a reason to keep it open.
