### ISSUE TITLE
chplSerializer does not output domains as expected

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#24123]
Since `ChplFormat` / `chplSerializer` exist to emit objects in a similar manner to Chapel source code, I would expect it to emit a domain in the same format as a domain literal.

For example:

``` chapel
use IO;
use ChplFormat;

var D = {1..10};

stdout.withSerializer(new chplSerializer()).writeln(D);
```

This emits

```
["1..10"]
```

But I would expect it to emit

```
{1..10}
```

Perhaps we could apply whatever exception we are using for the default serializer for ranges also to the `chplSerializer` here?

**Comment by benharsh** [comment]
This is an unintended side effect of https://github.com/chapel-lang/chapel/pull/23392 , which changed some IO behavior to print out domains as lists and ranges as strings when the serializer is not the default serializer.

I'll take a look at updating the chplSerializer implementation to add an exception for ranges and domains.

**Comment by bradcray** [comment]
I'm throwing the 'user issue' label on this since it sounds like @redhatturtle hit this on this [Discourse thread](https://chapel.discourse.group/t/replacement-for-8ht/29244/4) (which may have led @mppf to post this?) and the 'bug' label since @benharsh indicated that it was an unintentional change in behavior.

**Comment by benharsh** [comment]
Resolved by https://github.com/chapel-lang/chapel/pull/24145

**Comment by mppf** [comment]
thanks @benharsh !
