### ISSUE TITLE
Ignoring loop indices is not possible in bracket loops

### ISSUE THREAD

**Issue by DanilaFe** [chapel-lang/chapel#24149]
I found the following code in `AllLocalesBarrier`:

```Chapel
  private var globalBarrier = [b in BarrierSpace] new unmanaged aBarrier(1, reusable=true, procAtomics=true, hackIntoCommBarrier=true);
```

The linter complained that the loop index `b` is unused. However, it's a syntax error to replace it with `_`. It seems to me that using `_` in this context should be allowed.

**Comment by bradcray** [comment]
I'm definitely open to that argument, but before we jump into it:  Note that, currently, the standalone underscore isn't allowed in for loops either.  That is,

```chapel
for _ in 1..10 do writeln("Hi!");
```

also generates a syntax error.  I believe that the original intention was that `_` was for dropping tuple elements on the ground since one could write the for loop as:

```chapel
for 1..10 do writeln("Hi!");
```

and the square bracket form as:

```chapel
  private var globalBarrier = [BarrierSpace] new unmanaged aBarrier(1, reusable=true, procAtomics=true, hackIntoCommBarrier=true);
```

(which shows how square bracket syntax and array declarations are really just type vs. value variations of the same thing).

So, I think what we currently have is consistent and reasonable, but that there's a question as to whether we'd want to extend both cases to support a standalone `_` as well.  Upside: Maybe `_ in` is clearer than just omitting it?  Downside: two ways to write the same thing.

An intermediate approach would be to replace the syntax error with a suggestion to just drop the `_ in` expression.

**Comment by DanilaFe** [comment]
I hadn't considered that. For some reason, I was perfectly happy removing the index from `for` loops (and did it without trying `_`), but went for `_` in bracket loops. There might be something to be said there about "intuitiveness" but probably it's just that I've seen no-`in` `for` loops, but not no-`in` bracket loops. I'm content with your answer and would be good with closing the issue, unless others want to continue the discussion.

**Comment by DanilaFe** [comment]
No complaints then. Closing 😄
