### ISSUE TITLE
Should fileReader / fileWriter be unlocking by default?  (or un-defaulted?)

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#24263]
Reviewing IO codes for performance, it's not unusual for us to suggest to users that they use an unlocked fileReader/Writer in order to get a performance boost when they're only accessing the object from a single task at a time (or ever).  This issue asks whether we made the wrong choice by having them be locking by default, particularly given the recent move toward making random streams and potentially associative arrays/domains unlocked by default.

I think the way that we got into the current state is that my design philosophy was "safe first, then fast" to avoid having users new to parallel computing shoot themselves in the foot—hence `parSafe=true` by default in random streams and associative domains/arrays.  However, over time, it seems like the balance has tipped the other way, and people have been more annoyed my heavyweight locking being on by default, particularly since these objects are often only used by a single task anyway.

This question asks whether we think we have the wrong default on fileReader / fileWriter as well, and would want to switch it to non-locking, or just remove the default to require the user to think about it.

In proposing this, I'm not personally proposing we change the locking=true behavior of `stdin`, `stdout`, or `stderr`—to me, those are sufficiently global, common, and OK-to-be-heavyweight to remain as they are (and since we create them, we can set them as we want regardless of the default).

To retain the safety that we've traditionally had, Michael suggested supporting a mode in non-`--fast` compiles that would complain if a single fileReader/Writer is used by multiple tasks simultaneously; effectively, store a lock in such cases, and complain if the lock is held when a task goes to take it (optimizing the lock away in `--fast` compiles).

**Comment by jeremiah-corrado** [comment]
> This question asks whether we think we have the wrong default on fileReader / fileWriter as well, and would want to switch it to non-locking, or just remove the default to require the user to think about it.

I agree that in many cases, users actually want a non-parallel safe fileReader/fileWriter, and are unaware that this isn't what they're getting; however, I'm somewhat wary of changing the default value in all cases. I'd propose that we make the following changes to make it more likely that users get the locking behavior they want:

1. Remove `locking`'s default value in the [`file.reader`](https://chapel-lang.org/docs/modules/standard/IO.html#IO.file.reader) and [`file.writer`](https://chapel-lang.org/docs/modules/standard/IO.html#IO.file.writer) methods. Since these methods are more amenable to scenarios where multiple readers/writers are being created around the same file, this forces users to think about whether they need parallel safety in those cases. For example:

```chapel
var f = open("path/to/file.txt", ioMode.r);

coforall tid in 1..nTasks {
  var taskReader = f.reader(locking=true, ...);
  ... 
}
```
note: we could also consider simply keeping the default value of `true` for these methods

2. Switch the default value to `false` for the [`openReader`](https://chapel-lang.org/docs/modules/standard/IO.html#IO.openReader) and [`openWriter`](https://chapel-lang.org/docs/modules/standard/IO.html#IO.openWriter) standalone procs. In my experience, these are used more commonly in cases where a user only wants one reader/writer to a particular file. For example:

```chapel
proc getIntFrom(file: string): int throws {
  return openReader(filePath).read(int);
}
```
Additionally, I consider these to be convenience functions, and thus would prefer to have default values for as many arguments as possible.

3. Remove the default value for `locking` from the fileReader/fileWriter types themselves, implying that parallel safety should be decided on a situation by situation basis.
    * As you mentioned above, I agree that `stdin`, `stdout`, or `stderr` should be parallel safe due to their global nature.

**Comment by bradcray** [comment]
Only tangentially related, but:  Would any of you following this issue so far have any appetite for introducing an unlocked version of stdin/stdout/stderr as part of this effort?  (the goal being to have low-overhead shootouts that don't have to rely on the open file 0 trick that we currently have).  I think the only hard part is the naming (e.g., `stdinUnlocked`?  `stdinNoLock`?  `lockFreeStdin`?  they all seem clunky...?)

**Comment by mppf** [comment]
@bradcray - I'd expect we'd also want stdin/stdout/stderr that works directly with the OS rather than using line-buffering and working through a `FILE*`. In the past I've considered maybe having a compilation flag (maybe a config param or something?) to opt out of the current mode which could be described as "stdout etc interoperate with C but are slower". Not sure if such a flag would be reasonable to toggle stdin/stdout/stderr having locking or not.

On approach would be to have something like `fastStdin` that isn't locking and also disables the C interoperability.

**Comment by bradcray** [comment]
> Not sure if such a flag would be reasonable to toggle stdin/stdout/stderr having locking or not.

I'm always hesitant to have program behavior depend on a flag that isn't visible in the source code, so of the options, I like the notion of having a `fastStdin` or the like instead.  That would also permit both fast and safe uses of stdout within a single program, I think.  Alternatively, we could have a `FastConsole` module or the like whose use/import would define `stdin`/`stdout`/`stderr` to be the fast versions within that scope.  But I worry a bit about how that would mix with standard uses of the IO module (and it seems like it could lead to confusion and definitely the inability to mix the two notions of the console in a current scope).

I'll fork this off into its own issue if nobody objects (and I don't find we've already got one).

**Comment by lydia-duncan** [comment]
This was resolved, closing
