### ISSUE TITLE
undetected stackoverflow iwth output type annotation

### ISSUE THREAD

**Issue by lucaferranti** [chapel-lang/chapel#24581]
### Summary of Problem

If I have something like (bug coming from me forgetting to cast `x` to `real` first)

```chapel
proc f(x: real) do return 1;

proc f(x: ?T) where isImag(T) {
  return f(x): T;
}
```

then I get the nice error message at compile time

```
tmp2.chpl:3: error: unable to resolve return type of function 'f'
tmp2.chpl:3: In function 'f':
tmp2.chpl:4: error: called recursively at this point
  tmp2.chpl:7: called as f(x: imag(64))
note: generic instantiations are underlined in the above callstack
```

and everything is good.

however, if I specify the output type in the `proc` definition, that is I have

```chapel
proc f(x: real) do return 1;

proc f(x: ?T):T where isImag(T) { // NOTE THE DIFFERENCE IN THIS LINE
  return f(x): T;
}

writeln(f(0.0i));
```

then the code compiles without problems, but at runtime I get the less informative error

```
fish: Job 1, './tmp2' terminated by signal SIGSEGV (Address boundary error)
```

To be clear, I am well aware of the [halting problem](https://en.wikipedia.org/wiki/Halting_problem) being undecidable :P

I am not sure if this is a bug itself, my questions are mainly

1. Why does specifying the output type trick detecting the stack-overlow?
2. Could it be detected in this simple case
3. Could the error at runtime be made more informative? I am not sure how chapel handles stack-overflows, does it limit the call stacktrace? To be fair, I am actually not sure if it even technically errors for a stack-overflow at runtime, or if something else happens before it.

### Steps to Reproduce

**Compile command:**

`chpl tmp2.chpl`

**Execution command:**

```
./tmp2
```

### Configuration Information

- Output of `chpl --version`: 1.33, built with llvm
- Output of `$CHPL_HOME/util/printchplenv --anonymize`:
```
CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: llvm
CHPL_TARGET_ARCH: x86_64
CHPL_TARGET_CPU: native
CHPL_LOCALE_MODEL: flat
CHPL_COMM: none
CHPL_TASKS: qthreads
CHPL_LAUNCHER: none
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: cstdlib
CHPL_GMP: bundled
CHPL_HWLOC: bundled
CHPL_RE2: bundled
CHPL_LLVM: system
CHPL_AUX_FILESYS: none
```
- Back-end compiler and version, e.g. `gcc --version` or `clang --version`: 11.4.0
- (For Cray systems only) Output of `module list`:

**Comment by bradcray** [comment]
@lucaferranti: Here's my take on your questions:

> 1. Why does specifying the output type trick detecting the stack-overlow?

I wouldn't characterize the initial error message you report as the compiler intelligently detecting a stack overflow due to the infinite recursion.  Rather, I'd describe it as "Chapel isn't very good at inferring the return type of recursive procedures in general, and currently needs the user to help it know what the return type is."  So then in your second program, having supplied that return type, Chapel doesn't need to infer the return type anymore and can proceed without help.  Of course, that permits you to run the infinite recursion and get the stack overflow you detected.

> 2. Could it be detected in this simple case

Yes, there's no reason to believe the compiler couldn't detect obvious infinite recursions (e.g., cases like this in which routines call themselves outside of control flow).  I think that, to date, this has not been something users have hit and been surprised by very often; and in practice, when users have hit it, it has tended to be in recursive routines that are not actually infinite, but simply make enough recursive calls to overflow the stack anyway.  I think it would be reasonable to open an issue for detecting the obvious cases at compile-time if you would like to advocate for that.

> 3. Could the error at runtime be made more informative? I am not sure how chapel handles stack-overflows, does it limit the call stacktrace? To be fair, I am actually not sure if it even technically errors for a stack-overflow at runtime, or if something else happens before it.

We've discussed this before because the behavior for task stack overflows is so unfriendly at present, but have never implemented it.  If I recall correctly, there were concerns about the performance impact of doing so, and maybe also some challenges integrating it with Qthreads?  (our default/preferred tasking option in most configurations).  I think the former could arguably be mitigated a bit by disabling the checks with `--fast` or making it an opt-in feature.  But the last time it came up, it felt sufficiently difficult to do that we didn't dive into it.  I'm not finding a GitHub issue for this (it may have predated our use of GitHub), and think it would be definitely be reasonable to file a request for such checks.

**Comment by lucaferranti** [comment]
Thank you a lot for the reply, brad.

- The first one (the compiler accidentally sounding smart when failing inference in a stack-overflow) was pretty fun, would make a nice meme.

- Second one, I can open an issue for the compiler detecting stack-overflow in simple cases like this one if it's feasible. I would tend to say its middle-low priority, but not sure. Also, this is not my expertise, but I fear even simple cases might easily become a rabbit hole of problems.

- Third one, I'll open an issue. It definitely makes sense to disable the checks with `--fast` (slightly prefer over being opt-in, but no opinion really).

**Comment by bradcray** [comment]
@lucaferranti : I'm going to close this issue since the questions it posed were answered.  You're still welcome to file the potential follow-up issues if you want to advocate for them, of course.
