### ISSUE TITLE
Missing support for `try` error-propagation in array expressions

### ISSUE THREAD

**Issue by jeremiah-corrado** [chapel-lang/chapel#24631]
Consider the following code, which attempts to create an array by calling a throwing function:

```chapel
module test {
    proc makeThing(i) throws {
        return i;
    }

    proc makeArr() throws {
        var arr = [i in 1..10] (try makeThing(i));
    }

    proc main() throws {
        makeArr();
    }
}
```

I'd expect the `try` to propagate any errors from `makeThing` up to main where `makeArr` is called; however a compiler error is produced:
```
test.chpl:7: In function '_isArrayTypeFn':
test.chpl:7: error: call to throwing function makeThing is in a try but not handled
test.chpl:2: note: throwing function makeThing defined here
```

Without the `try`, the following error is produced:
```
asdf.chpl:7: In function '_isArrayTypeFn':
asdf.chpl:7: error: call to throwing function makeThing without throws, try, or try! (relaxed mode)
asdf.chpl:2: note: throwing function makeThing defined here
```

However, if the array expression is replaced with: 
```chapel
var arr = forall i in 1..10 do (try makeThing(i));
```
The program compiles.

Note that the language spec and the second error message above both indicate that using a `try` to propagate errors in this type of expression should be supported.

**Comment by ShreyasKhandekar** [comment]
Note that the case where the array expression is replaced with a `forall` also compiles without the `try`.
This combined with the error message from above `asdf.chpl:7: error: call to throwing function makeThing without throws, try, or try! (relaxed mode)` suggests to me that the iterator called by the `[...]` syntax isn't as smart as the one called by `forall` because it doesn't handle `throws` properly.

**Comment by bradcray** [comment]
> suggests to me that the iterator called by the [...] syntax isn't as smart as the one called by forall because it doesn't handle throws properly.

That's a good guess—that the compiler creates a little lightweight wrapper iterator for the `[...]` case and fails to propagate the `throws` bit to that wrapper?

**Comment by DanilaFe** [comment]
So, the difference between the two loops is that one needs to be checked for being an array expression. The `isArrayType` handling introduces an intermediate function, which is not marked `throws`, and that's what causes the error. Also, this issue is likely a duplicate. https://github.com/chapel-lang/chapel/issues/14233
