### ISSUE TITLE
Question about `Random.choice` deprecation

### ISSUE THREAD

**Issue by stress-tess** [chapel-lang/chapel#24673]
I'm working on aligning the arkouda random functionality with numpy. In https://github.com/Bears-R-Us/arkouda/issues/3066, I started looking into the numpy methods that have counterparts in chapel. 

The numpy version of `choice` has an optional probabilities argument indicating the probability each element will be selected. The only method in the `Random` module I can find that has this option is `randomStream.choice`, which is exactly what I want, but it's deprecated. This issue is mostly to get a sense of why it's been deprecated and if there's an easy way to get similar functionality that I'm just missing. Thanks!

**Comment by bradcray** [comment]
@stress-tess (great username! :D ): Thanks for bringing this use-case to our attention.  This issue feels thematically related to https://github.com/chapel-lang/chapel/issues/24652, so I want to link to it here.  Tagging @jeremiah-corrado here who's done most of the work with the Random module interface and stabilization lately.

**Comment by jeremiah-corrado** [comment]
Hi @stress-tess, our motivation for not including that functionality in `choice`'s replacement procedure ([`sample`](https://chapel-lang.org/docs/modules/standard/Random.html#Random.randomStream.sample)) was to simplify the interface as much as possible, with the intention of adding more functionality in the future as needed. Given your interest, I think we should work on adding an overload of `sample` that accepts a probabilities argument in the next release. Unfortunately there isn't a non-deprecated way to get the same behavior as of now.

In the meantime, please let me know if you'd like any help (re)implementing the probabilities functionality in Arkouda.

**Comment by lydia-duncan** [comment]
Not just thematically related, I'd argue they're the same issue :)

**Comment by jeremiah-corrado** [comment]
To add weighted random sampling to the stable random module, I propose we add a few new overloads of `sample` that accept a `weights` argument. This would be similar to what we had with the `choice` method.

Some design considerations:

#### `choose` and `sample`?

Additionally, we could add overloads of `choose` that accept a `weights` argument; however sampling with `n=1` is essentially the same as calling `choose`, so I'd be inclined to only add this functionality to `sample` for now to keep the interface simpler. I.e., the following would be equivalent if both procs could do weighted sampling:
```chapel
var x = choose(arr, weights);
var x = sample(arr, 1, weights)[0];
```

#### `weights` argument type:

For the top-level procedures I'd propose we only allow a real-valued weights argument because it makes the computation more straightforward. For the methods on `randomStream`, `weights` could be a real-valued array for `real` eltType, or an array of integers for a stream with an integer `eltType`. This would allow users to go from unweighted to weighted sampling with the same `randomStream`, for example:

```chapel
var rs = new randomStream(int);

const samplesU = rs.sample([1, 2, 3, 4, 5], 2);
const samplesW = rs.sample([1, 2, 3, 4, 5], 2, [8, 8, 3, 5, 1]);
```
as opposed to:
```chapel
var rsi = new randomStream(int),
    rsr = new ranomStream(real);

const samplesU = rsi.sample([1, 2, 3, 4, 5], 2);
const samplesW = rsr.sample([1, 2, 3, 4, 5], 2, [8.0, 8.0, 3.0, 5.0, 1.0]);
```

Note: I have weighed sampling with integer weights working in an [experimental branch](https://github.com/chapel-lang/chapel/pull/24847).

#### Errors:

`sample` currently throws an `IllegalArgumentError` in the following cases:
* `n<1`
* `n` is larger than the population size, if `withReplacement=false`
* the population has a size of zero

I'd propose that the new overloads of sample also throw an `IllegalArgumentError` if `weights` has a different length than the population size.

Also, the weights array should be constrained to be a 1D rectangular domain using where-clauses. If we start supporting multidimensional arrays in these procedures, then that constraint should be dropped.

#### Other languages/libraries:

The only other language I found that has functionality like this in their random module is Python with the [`Random.choices` ](https://docs.python.org/3/library/random.html#random.choice)function. NumPy also has analogous functionality with [`numpy.random.choice`](https://numpy.org/doc/stable/reference/random/generated/numpy.random.choice.html).

I'm inclined to go with Python's argument name of `weights`, as it is descriptive and draws from their likely well-known precedent. 

### Straw Proposal for Signatures:

Module-level procedures:
```chapel
proc sample(arr: [?d] ?t, n: int, weights: [?dw] real, withReplacement=false): [] t throws;
proc sample(d: domain, n: int, weights: [?dw] real, withReplacement=false): [] t throws;
proc sample(r: range, n: int, weights: [?dw] real, withReplacement=false): [] t throws;
```

Methods on `randomStream`:
```chapel
proc ref sample(arr: [?d] ?t, n: int, weights: [?dw] ?wt, withReplacement=false): [] t throws where isCoercible(this.eltType, wt);
proc ref sample(d: domain, n: int, weights: [?dw] ?wt, withReplacement=false): [] t throws where isCoercible(this.eltType, wt);
proc ref sample(r: range, n: int, weights: [?dw] ?wt, withReplacement=false): [] t throws where isCoercible(this.eltType, wt);
```

**Comment by lydia-duncan** [comment]
Just noting that we think Jeremiah's #24847 should have restored the desired functionality to the replacement function for Random.choice.  Thanks @jeremiah-corrado , and thanks for reporting, @stress-tess !  Please let us know if the new implementation works for you or if there's anything else we can do to improve it :)

**Comment by stress-tess** [comment]
This is perfect! thanks!!
