### ISSUE TITLE
[Bug]: Cannot initialize an array of user-initialized records

### ISSUE THREAD

**Issue by Guillaume-Helbecque** [chapel-lang/chapel#24677]
### Summary of Problem

**Description:**
I don't know if this issue is a bug or a curiosity, but I faced it today. 
My wish was to create (and initialize) an array of generic records, themselves initialized using a provided `init` method. What I observed is that it produces the following error at compile-time:

```
sandbox.chpl:16: In function 'main':
sandbox.chpl:23: error: unresolved call 'R2.init(eltType=type real(64))'
sandbox.chpl:10: note: this candidate did not match: R2.init(type elemType)
$CHPL_HOME/modules/internal/ChapelBase.chpl:1508: note: because call uses named argument eltType
sandbox.chpl:10: note: but function contains no formal named eltType
```

**Is this a blocking issue with no known work-arounds?**
No. The work-around consists in removing the provided `init` method and to initialize the variables in their declaration. I guess that the compiler is then using its own initializer, which seems to work.

### Steps to Reproduce

**Source Code:**

```chapel
record R1 { // workaround
  type eltType;
  var a = 3:eltType;
}

record R2 {
  type eltType;
  var a: eltType;

  proc init(type elemType) {
    this.eltType = elemType;
    this.a       = 3:elemType;
  }
}

proc main() {
  var r1 = new R1(real);
  writeln(r1);    // (a = 3.0)
  var r2 = new R2(real);
  writeln(r2);    // (a = 3.0)
  var r1Arr: [0..1] R1(real);
  writeln(r1Arr); // (a = 3.0) (a = 3.0)
  var r2Arr: [0..1] R2(real); // error
}
```

**Compile command:**
`chpl sandbox.chpl`

**Execution command:**
`./sandbox`

**Associated Future Test(s):**

### Configuration Information

- Output of `chpl --version`: 1.33.0
- Output of `$CHPL_HOME/util/printchplenv --anonymize`:
- Back-end compiler and version, e.g. `gcc --version` or `clang --version`:
- (For Cray systems only) Output of `module list`:

**Comment by e-kayrakli** [comment]
I was curious about this, and just wanted to clarify: your formal to `R2.init` is named `elemType`. However, R2's field is `eltType`. This is probably what confuses the compiler. I am not an expert in initializers, but this may be something we need to clarify in the spec somehow (can't see anything about this on a quick look), if we are doing name-based matching.

**Comment by lydia-duncan** [comment]
It seems like it should be okay, though.  The point of defining an initializer is to explicitly define what should be needed to create an instance of the type.  I remember us specifically discussing whether to use named arguments for this case and it had some benefit, but I'm blanking on what it is right now and it could be that we can remove that usage for the type initializer call (which is I think what's getting triggered here)

**Comment by bradcray** [comment]
My memory is that because Chapel does not yet have user-defined type constructors/initializers (https://github.com/chapel-lang/chapel/issues/21992), we may currently require the names of generic fields in user-defined initializers to match the names of the fields in the classes in order to make a link between user-defined value initializers (the user-defined `proc init`), type signatures (like `R2(real)` here), and the compiler-generated type constructors.  Notably, changing `elemType` to `eltType` does make the `R2` case work.

Searching for documentation backing up this memory, though, I'm coming up short.  [This section](https://chapel-lang.org/docs/technotes/initTypeAlias.html#an-experimental-solution-using-named-expressions) looks related, but specific to type aliases?

Tagging @benharsh and @mppf who probably remember this better than I do.

**Comment by benharsh** [comment]
This issue can be triggered much more directly using default-initialization:

```chpl
record R2 {
  type eltType;
  var a: eltType;

  proc init(type elemType) {
    this.eltType = elemType;
    this.a       = 3:elemType;
  }
}

var r : R2(real);
```

```
foo.chpl:11: error: unresolved call 'R2.init(eltType=type real(64))'
foo.chpl:5: note: this candidate did not match: R2.init(type elemType)
foo.chpl:11: note: because call uses named argument eltType
foo.chpl:5: note: but function contains no formal named eltType
```

I believe the linked section of the spec is indeed relevant because of the way in which we rely on type aliases to implement arrays. At some point we are using a type alias to default-initialize an element before moving it into the array's memory. Something like:

```chpl
for i in 0..#numElements {
  var elt : arrayEltType; // alias to R2(real)
  moveInitialize(data[i], elt);
}
```

This is the likely source of the error above, which is trying to be more helpful by pointing to user code rather than the internal array implementation.

I think [this part of the spec](https://chapel-lang.org/docs/technotes/initTypeAlias.html#default-initialization-for-instantiated-generic-types) is also relevant in how it describes default initialization. In particular:


> When the compiler knew it was invoking a compiler-generated initializer it would use named-expressions to pass generic instantiation information. When invoking a user-defined initializer it would simply pass the instantiation arguments in-order. This allowed user-defined initializers to use arbitrary names for their arguments, but enforced a specific ordering of those arguments.
> [...]
> In the Chapel 1.19 release default-initializing a variable with a generic type will always invoke the initializer with named-expressions. This has the benefit of allowing the same initializer to be used for default-initialization and for new-expressions with a type alias. This is also a simpler rule for users to remember.

Perhaps our stance has changed since the 1.19 release? At the very least, this error message isn't very helpful.

**Comment by Guillaume-Helbecque** [comment]
Thanks to all of you for your answer. This sounds clear to me now.

I've got into the (bad) habit of using a different name for the generic record type in initializers because I remember getting into trouble using identical names in the past; but that was probably an old thing.

**Comment by bradcray** [comment]
> I remember getting into trouble using identical names in the past; but that was probably an old thing.

If it's encouraging at all, I always use the same names and haven't gotten into trouble.  But if you do, please let us know about that.

I'm wondering what to do about this issue.  I think arguably things are working as advertised (though not yet as we'd like them, where, for that, I think we'd also want user-defined type initializers), such that we could close it unless you disagree, @Guillaume-Helbecque.  I think @benharsh  is right that we could arguably make the error message better, so we could fork that off into a new issue if anyone wanted to champion putting effort into that.

**Comment by Guillaume-Helbecque** [comment]
@bradcray: Yes I agree that we can close this issue. All is clear to me now, and there is finally no issue.
