### ISSUE TITLE
[Bug]: Memory leak for invalid UTF-8 in string.createAdoptingBuffer

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#24781]
### Summary of Problem

**Description:**

`string.createAdoptingBuffer` is documented as "taking ownership of the memory allocated" for the passed pointer. However, it validates that it's legal UTF-8 and if not, it throws an error and does not free the pointer, which I find surprising.

### Steps to Reproduce

**Source Code:**

```chapel
use CTypes;

config const n = 500;

proc main() {
  try {
    var tx: c_ptr(c_char);
    tx = allocate(c_char, n);
    for i in 0..<n {
      tx[i] = 0xff:c_char;
    }
    var s = string.createAdoptingBuffer(tx, n);
    writeln(s);
  } catch e {
    writeln("caught an error ", e);
  }
}
```

This program leaks memory (since `tx` is never freed). I would expect that `string.createAdoptingBuffer` would free it along with throwing an error (so it takes ownership of the pointer in all cases).

**Compile command:**
`chpl bb.chpl`

**Execution command:**
`./bb --memLeaks`

**Associated Future Test(s):**

TODO

**Comment by e-kayrakli** [comment]
I am not sure I agree this is a bug. If `createAdoptingBuffer` failed, I consider the "Adopting" part to have failed also. My reflex is that this is a user bug, because cleaning up memory after failed operations is user's responsibility where try/catch is the perfect tool for that.

What if `tx`'s memory was allocated outside of the `try` block? Wouldn't it be surprising that a failed string creation freed its memory? Also, if string creation failed, maybe the user wants to take further action based on that to sanitize the buffer manually or something? Or maybe they'll choose to create a `bytes` with it instead.

That being said, the ergonomics may be improved. Can we put a warning in the error message explaining this behavior? Needless to say, the documentation should be clear about the behavior no matter which way we go.
