### ISSUE TITLE
[Bug]: gpuSort() error checking and deadlock

### ISSUE THREAD

**Issue by bretteiffert** [chapel-lang/chapel#24806]
### Summary of Problem

When calling gpuSort() at runtime on Nvidia GPUs with a non-GPU array, error is returned (as expected) and exits:

`c_ptrToConst() can only be applied to an array from the locale on which it lives (array is on locale 0, call was made on locale 0)`

When calling gpuSort() at runtime on AMD GPUs with a non-GPU array, the code hangs indefinitely within no error return or exit. 

Also, it would be helpful to return a more specific error message than the one that specifies that the array is on locale 0 (cpu) vs locale 0 (gpu). I realize what's happening here, but I assume this could be a headache of a bug in certain situations because the specific location of the array is not specified.

This is not blocking because the solution is to simply not call gpuSort() on a non-GPU array.

### Steps to Reproduce

**Source Code:**

`var A: [1..n] uint;
fillRandom(A);
on here.gpus[0] {
    gpuSort(A);
}`

**Compile command:**
chpl --report-gpu gpu-test.chpl

**Execution command:**
./gpu-test

### Configuration Information

- Output of `chpl --version`
2.0.0

- Output of `$CHPL_HOME/util/printchplenv --anonymize`: 
`CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: llvm
CHPL_TARGET_ARCH: x86_64
CHPL_TARGET_CPU: native
CHPL_LOCALE_MODEL: gpu *
  CHPL_GPU: nvidia *
CHPL_COMM: none
CHPL_TASKS: qthreads
CHPL_LAUNCHER: none
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: cstdlib
CHPL_GMP: bundled
CHPL_HWLOC: bundled
CHPL_RE2: bundled
CHPL_LLVM: bundled *
CHPL_AUX_FILESYS: none`

- Back-end compiler and version, e.g. `gcc --version` or `clang --version`: 
gcc 12.1.0

cc: @milthorpe

**Comment by e-kayrakli** [comment]
@bretteiffert -- Thanks for filing this.

`gpuSort` is a temporary solution that may be rough around the edges. This is definitely an example of that. Our near-term plan is to integrate GPU-based sorting into our existing `Sort` module's `sort` function. The core of that integration will be adding the ability to detect where the array is and call the proper sort function under the hood. I view that improvement as a matter of time, rather than trying to wrestle with major challenges. (I know myself to be optimistic in my guesses, though :) )

Tagging @ShreyasKhandekar, as he made some great progress in `gpuSort`'s performance recently. We've discussed this direction with him as the next step, as well.

**Comment by lydia-duncan** [comment]
@bretteiffert - just making sure you saw, @ShreyasKhandekar resolved this with his #25192.  Thanks for reporting, and thanks Shreyas for fixing it!
