### ISSUE TITLE
[Bug]: `mason new` does not start an interactive session

### ISSUE THREAD

**Issue by lucaferranti** [chapel-lang/chapel#25071]
I'm using

```
❯ chpl --version
chpl version 2.1.0 pre-release (44b3e6b437)
  built with LLVM version 14.0.0
```

Just calling `mason new` should start an interactive session

```
❯ mason new --help
Usage:
    mason new [options] <project name>
    mason new                    Starts an interactive session
 ```
 
 
 however this does not seem to be the case
 
 ```
 ❯ mason new
A package name must be specified
```

A similar issue for `mason init`, the [documentation](https://chapel-lang.org/docs/tools/mason/guide/basicusage.html) says it should start an interactive session, but running it only creates a `Mason.toml`.

Looking at `masonNew.chpl`, I see a `proc beginInteractiveSession` defined, but that is not called anywhere as far as I can tell.

**Comment by lucaferranti** [comment]
As far as I can tell, the interactive functionality was introduced in [this PR](https://github.com/chapel-lang/chapel/pull/15748/files#diff-fc352d49a9bc13625f3da1ea9118f0d6072a80979ede5e9c0bbe840ff9498c2cR45) 4 years ago. The linked line is where the proc was called.

That function call was removed [here](https://github.com/chapel-lang/chapel/pull/20482/files#diff-fc352d49a9bc13625f3da1ea9118f0d6072a80979ede5e9c0bbe840ff9498c2cL76). Looking at the description there, it seems it was intentional to remove interactivity support, in which case this would not be a bug, but doc being outdated

**Comment by bmcdonald3** [comment]
Hi Luca, yes, the interactive package initialization was removed as we decided that it was overly complex and not very helpful. For the most part, when you would use it, it would require setting up quite a few things that we don't anticipate early users to be concerned about that were only valuable when publishing a package as a brick (such as licensing) and not things that users of mason packages would be interested in. My recollection was that we were trying to get mason to be more new-user friendly and cater towards users of existing packages, rather than package developers, since users would much more likely be a much greater number than developers.

I think you are correct in pointing out that the docs are outdated. Is the interactive initialization something that you are interested in or was it more just that seeing it in the help command was confusing as it didn't reflect the actual behavior?

**Comment by lucaferranti** [comment]
Thanks for the reply!

I was mainly confused by the cli documentation saying it's interactive when it isn't. I agree we don't need to have an interactive cli in the core mason. It could be nice to have a more sophisticated template for mason projects that allows to setup things interactively, but I think that would indeed be better as a third-party cli tool and not as part of core mason itself.

with a quick check, the following updates would be needed in the docs

- [mason basic usage](https://chapel-lang.org/docs/tools/mason/guide/basicusage.html): remove mention of `mason init` being interactive
- `mason new --help`: remove mention of interactive session
- `proc beginInteractiveSession` is dead code and should be removed

I'll draft an MR myself tomorrow morning if nobody gets there first

**Comment by lydia-duncan** [comment]
Noting here that Luca opened #25099 to resolve this issue.  @bmcdonald3 , would you be a good person to review it?
