### ISSUE TITLE
Make the Sort module a proper standard module

### ISSUE THREAD

**Issue by jabraham17** [chapel-lang/chapel#25083]
Currently, the Sort module exists in the `modules/packages` directory in the Chapel tree. This effectively works as a standard, always available to be imported module, with the caveat that the documentation shows up in a different location.

In an offline discussion today, we discussed moving the Sort module into `module/standard`. This would have no effect on user code today, but would change how our documentation shows the module. Ideally, when making this change, https://chapel-lang.org/docs/modules/packages/Sort.html should redirect to https://chapel-lang.org/docs/modules/standard/Sort.html in some way.

**Comment by bradcray** [comment]
I completely agree with this.  I think the Sort module's sorting (ha ha) into the packages/ directory was more because of its history and instability than a sense that it shouldn't be part of the standard modules.  The only question in my mind recently has been how much to stabilize it first and them promote it vs. promote it and then stabilize it.
