### ISSUE TITLE
Rename default and reverse comparators in the sort module

### ISSUE THREAD

**Issue by jabraham17** [chapel-lang/chapel#25552]
This issue captures implementation information for decision made in https://github.com/chapel-lang/chapel/issues/24857

We are renaming the default comparators and removing the associated globals.

Tasks

- [x] Remove `const defaultComarator ...`, replacement is `new defaultComparator()`
- [x] Remove `const reverseComarator ...`, replacement is `new reverseDefaultComparator()`
- [ ] Rename `DefaultComparator` to `defaultComparator`
- [ ] Rename `ReverseComparator` to `reverseComparator`
- [x] ~Add `type reverseDefaultComparator = reverseComparator(defaultComparator);`~
- Add `enum keyPartStatus` with the following enum members
  - [x] returned
  - [x] pre
  - [x] post
- [x] Rename `defaultComparator.compare(a, b)` to `defaultComparator.compare(x, y: x.type)`
- [x] Rename `reverseComparator.compare(a, b)` to `reverseComparator.compare(x, y: x.type)` 
- [x] Rename `TwoArrayDistSortPerBucketTaskStartComparator.key(arg ...` to 
`TwoArrayDistSortPerBucketTaskStartComparator.key(elt ...`
  - this is an internal implementation detail and will not require a deprecation 
- [x] Convert all `keyPart` methods to the new style
  - `proc keyPart(elt, i: int): (keyPartStatus, integral)`

**Comment by lydia-duncan** [comment]
I took a start at deprecating `defaultComparator`, but then ended up with a question, which I have recorded in #25633.  The current branch is https://github.com/chapel-lang/chapel/compare/main...lydia-duncan:deprecateGlobals?expand=1 and it has 68 failures on it at the moment - I think some of them are simple test updates but the library/packages/SortedMap/update/testUpdate failure is related to the question in the issue.

Gonna task switch for now since I'm unblocked on one of my other tasks, but didn't want to leave this progress in just my space in case I don't come back to it quickly enough
