### ISSUE TITLE
[Bug]: Could not find C function for cabsf

### ISSUE THREAD

**Issue by hpcpony** [chapel-lang/chapel#26019]
### Summary of Problem

**Description:**
Compiler can't find function for cabsf

**Is this issue currently blocking your progress?**
no

### Steps to Reproduce

**Source Code:**

```chapel
use Math;

var x : complex(64);
x = 1.0 + 1.0i;
writeln(x, abs(x));
```

**Compile command:**
chpl bug_cmplx.chpl

warning: The prototype GPU support implies --no-checks. This may impact debuggability. To suppress this warning, compile with --no-checks explicitly
$CHPL_HOME/modules/internal/ChapelStandard.chpl:24: error: Could not find C function for cabsf;  perhaps it is missing or is a macro?

**Execution command:**
N/A

**Associated Future Test(s):**
N/A

### Configuration Information

- Output of `chpl --version`:

warning: The prototype GPU support implies --no-checks. This may impact debuggability. To suppress this warning, compile with --no-checks explicitly
chpl version 2.1.0
  built with LLVM version 18.1.6
  available LLVM targets: amdgcn, r600, nvptx64, nvptx, aarch64_32, aarch64_be, aarch64, arm64_32, arm64, x86-64, x86
Copyright 2020-2024 Hewlett Packard Enterprise Development LP
Copyright 2004-2019 Cray Inc.
(See LICENSE file for more details)

- Output of `$CHPL_HOME/util/printchplenv --anonymize`:
 
CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: llvm
CHPL_TARGET_ARCH: x86_64
CHPL_TARGET_CPU: skylake-avx512 +
CHPL_LOCALE_MODEL: gpu +
  CHPL_GPU: nvidia *
CHPL_COMM: gasnet +
  CHPL_COMM_SUBSTRATE: smp +
  CHPL_GASNET_SEGMENT: fast +
CHPL_TASKS: qthreads
CHPL_LAUNCHER: smp
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: cstdlib
  CHPL_NETWORK_ATOMICS: none
CHPL_GMP: bundled +
CHPL_HWLOC: bundled +
CHPL_RE2: bundled +
CHPL_LLVM: bundled +
CHPL_AUX_FILESYS: none

- Back-end compiler and version, e.g. `gcc --version` or `clang --version`:

gcc (GCC) 11.4.1 20231218 (Red Hat 11.4.1-3)
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by e-kayrakli** [comment]
Thanks for reporting this @hpcpony! This is the same issue as https://github.com/chapel-lang/chapel/issues/25610.

In both user reports, these were not blocking issues. However, how simple it is to bump into this makes me feel uneasy about it. @jabraham17 -- I know your internal notes and earlier investigations on this matter. Do you have a solution in mind, even if it is a bit patchy on the runtime side? I believe we should consider fixing this sooner rather than later.

**Comment by jabraham17** [comment]
In my opinion, the proper thing to do is to just implement complex number support with a C++ compiler using C++ `std::complex` instead of C99 complex numbers. At one time, we had this in the runtime and it was removed in https://github.com/chapel-lang/chapel/pull/20239, I think due to portability issues.

That is probably a bigger effort though, a simpler solution is to expand the ideas from https://github.com/chapel-lang/chapel/pull/25021 (which edited `ChapelBase`) to cover all the complex functions in `Math`/`AutoMath`. For an idea of scope, I counted extern procs with `complex(128)` in those modules. `AutoMath` has 5 and `Math` has 14

**Comment by e-kayrakli** [comment]
> For an idea of scope, I counted extern procs with complex(128) in those modules. AutoMath has 5 and Math has 14

These number are much lower than I expected. While these workarounds create code bloat, I still find it more favorable over pursuing C++ complex path. we could consider sticking all of these wrappers in an internal module to avoid adding everything to ChapelBase. It could make the workaround look a bit nicer.

**Comment by damianmoz** [comment]
Chapel's current handling of complex numbers is superior to both that of C++ and C99.  I would keep the status quo even with that little bit of code bloat. Thanks

**Comment by damianmoz** [comment]
Just as a matter of interest, did it only show up on a GPU?

I had no problems at all with the code. It worked for me.

**Comment by bradcray** [comment]
@hpcpony — This should be fixed on the `main` branch now, and if you're game to give it a try, we'd be happy to hear if it works for you.  in any case, thanks for raising this issue.

And thanks to @jabraham17 for the quick fix!
