### ISSUE TITLE
[Bug]: First class functions can't be assigned into after declaration

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#26213]
### Summary of Problem

**Description:**
According to https://github.com/chapel-lang/chapel/issues/18413#issuecomment-919164625, in the old lambda syntax it used to be possible to assign to a first class function that had previously been declared.  However, today it results in a syntax error.

Looking at some other fcf tests, it looks like the only difference between the updated syntax working today and failing is whether it is used when declaring the variable or whether it is used as an assignment (or probably split initialization, but the compiler doesn't get that far).

**Is this issue currently blocking your progress?**
No, I stumbled across this while looking at bugs to fix and figured I should record it

### Steps to Reproduce

**Source Code:**

```chapel
config var isHammingWeightFixed: bool = true;

var projFn: func(int, int);

if isHammingWeightFixed {
  projFn = proc (x:int) { return x; };
} else {
  projFn = proc (x:int) { return x+1; };
}

writeln(projFn(1));
```

**Compile command:**
`chpl foo.chpl`

**Execution command:**
N/A

**Associated Future Test(s):**
[`test/functions/fcf/assignLater.chpl`](https://github.com/chapel-lang/chapel/blob/main/test/functions/fcf/assignLater.chpl)
[`test/functions/fcf/assignInIfExpr.chpl`](https://github.com/chapel-lang/chapel/blob/main/test/functions/fcf/assignInIfExpr.chpl) #26214

### Configuration Information

- Output of `chpl --version`: 2.3.0 pre-release
- Output of `$CHPL_HOME/util/printchplenv --anonymize`: N/A
- Back-end compiler and version, e.g. `gcc --version` or `clang --version`: N/A
- (For Cray systems only) Output of `module list`: N/A

**Comment by jabraham17** [comment]
I believe the correct syntax is `proc(...`, rather than `proc (...`. I wouldn't consider this a bug, its a noted limitation in the docs https://chapel-lang.org/docs/main/technotes/firstClassProcedures.html due to parsing issues

**Comment by lydia-duncan** [comment]
We talked about this a bit in the User Support and Stabilization subteam meeting, but I find having something in the language that is whitespace-sensitive antithetical to our design principles. If this isn't something we can solve, I would strongly advocate for returning to the `lambda` syntax.

Still, I have adjusted my tests for the guidance (with an additional fix for the declaration of the variable's type in the case of `assignLater.chpl`) and found that Jade is correct, so I will close this issue and update the other one with that information

**Comment by bradcray** [comment]
Catching up on this issue late:

* My read of the docs doesn't suggest that we will always require `proc(` to have no spaces, just that that's all the current implementation supports due to parsing challenges—is that right?  Does anyone (@dlongnecke-cray ) remember whether there were known barriers to supporting the space, or whether it was just more flex/bison wrassling than we were willing to put the time into at the time (where it wouldn't take much for me to back off from wrestling with it, personally, if I got something working).
* Though I'm opposed to defining Chapel as a whitespace-sensitive language, I don't consider this case to (necessarily) imply that we've become whitespace-sensitive.  The key is to think of `proc(` as being a single lexical token in the language, much like we do `init=`, `reduce=`, `0x0000abcd`, or `+=` is, none of which permit spaces between the alphanumeric and a-z elements.  With that perspective, we're no more whitespace-sensitive than before.  That said, if this is the argument we're using, then `proc(` should be in the list of keywords at https://chapel-lang.org/docs/language/spec/lexical-structure.html#keywords (hmm… and it looks like we failed to get `init=` in that list either.  I wonder what else we're missing…?
* I definitely prefer the `proc`-based syntax that we've adopted for FCFs and the like over the `lambda`-based syntax and tokens we supported before and would not want to go back.  I think they're both more consistent with other elements of the language while also being less PL-centric (though I'm open to the argument that lambdas have been popularized so much by Python that this isn't a major concern)

**Comment by lydia-duncan** [comment]
>     * Though I'm opposed to defining Chapel as a whitespace-sensitive language, I don't consider this case to (necessarily) imply that we've become whitespace-sensitive.  The key is to think of `proc(` as being a single lexical token in the language, much like we do `init=`, `reduce=`, `0x0000abcd`, or `+=` is, none of which permit spaces between the alphanumeric and a-z elements.  With that perspective, we're no more whitespace-sensitive than before.  That said, if this is the argument we're using, then `proc(` should be in the list of keywords at https://chapel-lang.org/docs/language/spec/lexical-structure.html#keywords (hmm… and it looks like we failed to get `init=` in that list either.  I wonder what else we're missing…?

The comparison to `reduce=` is fair.  But that still doesn't change the fact that my eyes completely glossed over the fact that the examples I was using when updating the code had dropped the space in addition to replacing `lambda` with `proc`.  I can't imagine I'll be the only person to do that.  It's a confusing limitation to have present when transforming old code to avoid the deprecation warning.  Even if we don't call Chapel itself whitespace-sensitive, this change in particular is.  While the symmetry of using `proc` in both cases is very appealing, I personally don't think it's worth it if we can't get around this limitation.  As someone that was tripped up by it, the benefit of using the same word is lost by having this incredibly subtle stumbling block present.
