### ISSUE TITLE
rename domain.member?

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#5041]
The current method name for querying if a value is in a domain is `domain.member()`.

E.g.

    var D:domain(int);

    D += 4;

    assert(D.member(4));
    assert(!D.member(3));

This method name bothers me for English/Programming Style reasons. `member` is a noun and I really want the method name to be a verb in this case.

What should we do?

1) add domain.contains()
   a) and deprecate domain.member()
   b) and keep domain.member() as a synonym
2) enable parser/build to translate `x in someDomain` into this query (#5034)
   a) and deprecate domain.member()
   b) and keep domain.member() as a synonym
3) do nothing

**Comment by mppf** [comment]
I created PR #5026 to do this. I think we should add a deprecation warning to domain.member(), but leave it around (no-doc'd) for some time, since this is just a trivial renaming.

**Comment by bradcray** [comment]
If we add a deprecation warning, I think we should add a test case that triggers it in test/deprecated and then remove it after the next release.  I.e., I don't think there's great value in carrying deprecated features across multiple releases and would prefer to avoid carrying too much deprecated code around.  I could possibly imagine an argument to carry it across two releases in case professors only teach a class using Chapel once a year, particularly in this case due to the triviality of carrying the code forward.

**Comment by mppf** [comment]
@lydia-duncan, @bradcray, @ben-albrecht: OK, my current plan is to:
 * add domain.contains
 * deprecate domain.member() with a warning (for 1.15 and 1.16)
 * remove domain.member() in 1.17

Sound OK? If I understand correctly this is OK with each of you...

Thanks.

**Comment by lydia-duncan** [comment]
Sounds good to me!

**Comment by ben-albrecht** [comment]
:+1:

**Comment by bradcray** [comment]
It remains unclear to me whether we have a quorum on this decision or whether most people blew it off as being silly and didn't bother responding.  I think it'd be worth taking a better straw poll on rather than relying on only those who had time to weigh in on the topic.  Or maybe you've got better results than I do...

**Comment by daviditen** [comment]
I am fine with @mppf 's proposal.

**Comment by noakesmichael** [comment]
I was disappointed by it.

Mike

On Dec 16, 2016, at 9:25 AM, David Iten <notifications@github.com<mailto:notifications@github.com>> wrote:


I am fine with @mppf<https://github.com/mppf> 's proposal.

**Comment by mppf** [comment]
The proposal has 3 advocates and the only objections are that we have bigger fish to fry.
