### ISSUE TITLE
Complete initial design for de-initializers

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#5201]
Here are some proposed questions and answers regarding de-initializers in the Chapel language design, put together for the sake of discussion and forming consensus:

Q: What should a class / record de-initializer be called?
A: deinit() has been proposed.  Any objections or counter proposals?

Q: Should a user be able to call deinit() routines?
A: Yes.  This permits code that might free resources to be called (or called multiple times) before the object itself is destroyed.  While the same effect can be achieved in a destructor world with software engineering, such approaches require more programmer effort.

Q: Should a deinit() routine be permitted to take arguments?
A: Yes, since the user can call them.  The compiler-generated call based on 'delete's (on classes) or leaving scope (for records) will always be a 0-argument call.  Thus, in order for a user-defined deinit() call to be invoked, it should either have 0 arguments or have default values for all arguments.

Q: Should deinit() be permitted to take multiple overloads?
A: Sure.  Ambiguities should be treated like any other function call.

Q: If a user defines a deinit() routine, should this prevent the compiler from creating a default deinit() routine?  Or should the presence of any deinit() routine prevent the creation of a deinit() routine by the compiler?  Here's a particularly motivating case:

    class C {
      proc deinit(x: int) { ... }
    }

Since C has no 0-argument deinit() routine, this is either an error or the compiler should create one.  The latter is arguably more convenient/productive; but also potentially confusing if the user (for some naive reason) expected their deinit() routine to be called.

Q: What other questions should we be asking about deinit()?

**Comment by bradcray** [comment]
I provide an initial implementation of deinit in PR #5200

**Comment by mppf** [comment]
For my part:
 * I'm pretty confident that `deinit` is the right name to go along with `init` and definitely don't want `~MyRecord()`.
 * I don't think we should support `deinit` with >0 arguments. The reason is that the compiler will need to do something special with this method (see below).
 * I do think we should eventually support users explicitly calling deinit, but that's for equivalent situations to "placement new" in C++.
 * I think that the compiler-generated deinit should be the same as if the user provided one with an empty body.
 * As part of destroying a record, the compiler needs to destroy any fields of record type. I would expect that to happen in the deinit method. I expect the compiler to add calls to deinit for any member fields of record type. These additional calls happen after the user code in the destructor. I think it's important for the language to guarantee
   1) all fields are initialized after Phase 1 of an initializer runs
   2) all fields are destroyed after deinit completes

In terms of other questions - I think it's important to point out that `deinit` is a method that is subject to virtual dispatch when applied to classes. That is probably obvious, but worth saying.

**Comment by lydia-duncan** [comment]
I would additionally like to require that:

- deinit only be permitted on a type that has not defined a constructor.  To put this another way, deinit should be acceptable when the user has either defined at least one initializer for the class, or has not defined either an initializer or a constructor.  I am willing to be talked down from this position, but I think it is useful to clearly denote the connection between the two methods to the user in this way.

- there should be an error if a user defines both a destructor and a deinitializer, even if resolving the call would not be ambiguous.  Since we expect destructors to go away and deinitializers are their replacement, it seems confusing to permit both to be present for a given type.  If we decide to not permit deinitializers to take additional arguments, then the normal resolution error is probably sufficient, but it seems friendlier to explicitly call out to the user that we don't permit both styles to be defined. (I mentioned this in the PR as well)


Would you mind providing motivation for when the writer of a type would want an argument for their destructor?  At the moment it seems purely hypothetical and I'm not sure I see the point of supporting it until a user requests it (even though the support sounded pretty easy?).  It also seems like a source of confusion if the user of the type accidentally attempts to use the zero argument version, whether we fail to produce a default deinitializer or whether there is a compiler generated one.  Should the writer of the type be given full control over how their type is destroyed, or should such full control only occur if the writer of the type has overridden the default deinitializer?  It would be consistent with our initializers implementation to avoid the default version when any user defined deinitializer is present.

**Comment by lydia-duncan** [comment]
Probably pointing out the obvious, but if we agree about the first bullet I mentioned then a test should be added to the PR to lock in this behavior (as one is not already present)

**Comment by lydia-duncan** [comment]
And in (explicit) answer to your earlier questions:
- I support deinit as the name
- I tentatively support allowing the user to call deinit methods, but I would like some checks or support in place to elide the deinit call as part of delete if no operations have occurred on the instance since the deinit method was last called, as I can see this causing memory issues otherwise.
- I am on the fence about whether the deinit method should be allowed to take arguments, for the reasons given above
- I view the ability for deinitializers to take overloads as entirely dependent on whether we allow it to take arguments and so will be influenced by that discussion
- I lean towards having the presence of a deinitializer determine whether a default deinitializer is generated for the type (though there are some challenges here w.r.t. secondary deinitializers.  What if the only explicitly defined deinitializer is in a separate module, so not all uses of the type are guaranteed to be able to see it?)

**Comment by bradcray** [comment]
It sounds to me like the initializers team should reconvene to hash out what deinit means and identify an owner for implementing it.  It sounds like the sense I'd been given that there wasn't really much to discuss is incorrect.

**Comment by lydia-duncan** [comment]
Unless I'm missing something, the only point of disagreement seems to be on the presence of arguments, I'm interpreting Michael and my comments as "addendums" otherwise (and not in conflict).  But I am curious what @vasslitvinov and @noakesmichael think

**Comment by noakesmichael** [comment]
I fully supported Brad’s PR “as is” but subject to passing at least linux64 paratest
and I admired that he jumped on it and had such quick success.

I thought  it was likely that there would be additional minor PRs in the
nearer term as the feature matured.  I am very comfortable with this as
a development process for such a relatively simple feature.

Mike



On Jan 20, 2017, at 11:15 AM, Lydia Duncan <notifications@github.com<mailto:notifications@github.com>> wrote:


Unless I'm missing something, the only point of disagreement seems to be on the presence of arguments, I'm interpreting Michael and my comments as "addendums" otherwise (and not in conflict). But I am curious what @vasslitvinov<https://github.com/vasslitvinov> and @noakesmichael<https://github.com/noakesmichael> think

**Comment by lydia-duncan** [comment]
My only hesitancy with Mike's approach is that supporting arguments:

1. Is a departure from constructors' behavior today (i.e. required implementation effort, albeit a trivial amount, see https://github.com/chapel-lang/chapel/pull/5200/files#diff-36b9f64c9ddf188ee28d572a1c8437f7R131)

2. Would cause user code to break going forward if we changed our mind on whether they were allowed.

**Comment by lydia-duncan** [comment]
So I would propose reverting that line, merging the PR, and continuing discussion?

**Comment by noakesmichael** [comment]
On Jan 20, 2017, at 12:53 PM, Lydia Duncan <notifications@github.com<mailto:notifications@github.com>> wrote:


My only hesitancy with Mike's approach is that supporting arguments:

  1.  Is a departure from constructors' behavior today (i.e. required implementation effort, albeit a trivial amount, see https://github.com/chapel-lang/chapel/pull/5200/files#diff-36b9f64c9ddf188ee28d572a1c8437f7R131)

  2.  Would cause user code to break going forward if we changed our mind on whether they were allowed.



This is a valid concern but it seems to me that deinit is not a documented feature
in the immediate term and so this issue need not be an impediment to Brad’s
“first draft” PR.

Simultaneously Brad created a github issue to drive resolution on issues like
this so that minor updates could be introduced, as needed, before the formal
release / promotion of this feature.

Mike

**Comment by lydia-duncan** [comment]
That's fine with me

**Comment by bradcray** [comment]
I proposed the initializers team take this up because nothing in the initializers CHIP or in other recent conversations about deinit (in person; in the discussion on PR #5019) suggested that there were design decisions of this size lurking (which may simply mean that we've become aware of them since then).  I think the feedback is interesting and reasonable, just larger in magnitude than I was expecting, and seemingly unlikely to resolve quickly in an online issue.  I also think we need to fill in the gap from the 1.15 planning exercise as to who's going to implement deinit()  (I thought this yesterday as well, but then rather than sending out a call for help, decided to see if I could do it quickly.  I now know that I can't, so am reverting to that call).
