### ISSUE TITLE
approach for #5217: just const ref

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#5218]
This issue describes a possible approach to solve the problems in #5217.

The particular approach under consideration here is that blank intent be `const ref` for arrays, for argument passing and task/forall intents.

Pros:
* simple in concept
* simple to implement
* arrays are more consistent with other types
* added const checks may be beneficial, like for other types, to avoid race conditions or other unintended uses in some cases

Cons:
* A lot of test code would need to change
* What should we do for promotion, considering that promotion is an implicit forall loop? For example:

```
	A[I] = 3;  // where I is an array of index(A.domain)
```

## Handling Promotion

I'm pretty sure we want something like
```
A = B;
```
to continue to work, when `A` and `B` are arrays over the same domain. Right now, in a strict sense, this is using promotion on arrays.

If that is to continue to work, we could:
1. adjust blank intent for arrays to be possibly ref (this is the ref-is-modified proposal e.g.)
2. adjust default task+forall intent for arrays to be 'ref' even though args blank is const
3. adjust promotion -> forall process

See below discussion for further issues brought up with these options.

2. users would have to add `with (const ref A)` in certain common situations such as:
```
proc f(A:[?D] int) {
  var B:[D] real;
  forall i in 1..100 {
    B[i] = A[i] : real;
  }
}
```

3.  a few issues were brought up:

  * users would have to add an explicit `ref` task intent in common situations e.g.
  ```
  var A:[1..10] int;
  var B:[1..10] int;
  forall i in 1..10 with (ref A) do
    A[i] = B[i];
  ```

  * also the design arguably has problems fitting in with ref-pair rules (but... arguably that is an implementation issue). Here is an example of the last issue (discussed in more detail it the `Let's consider option 3` comment below.
  ```
  var D = {"a", "b"};
  var AA:[D] [1..2] int;
  var Inds = [1,2];
  AA["b"][Inds] = 3; // promoted

  writeln(AA["a"]);
  writeln(AA["b"]);
  ```

**Comment by vasslitvinov** [comment]
For promotion, my proposal is to pass all relevant variables into the implicit forall loop by `ref` intent instead of the default intent.

Cf. when we flatten functions, we (should) add the outer variables as `ref` formals, rather than pass them by the default intent. (Switching to by-value is an optimization.) Promotion IMO is analogous.

**Comment by vasslitvinov** [comment]
If the default forall/task intent for arrays becomes `const ref`, this may not add undue burden on the programmer compared to existing const intents for other types.

**Comment by benharsh** [comment]
Would this present a problem with dynamic distributed arrays? As a trivial example, consider a distribution like Block that counts how many times an index is **read**. As far as the user knows they are only reading elements, but one could imagine that a strict view of const might result in a compile-time error.

Put another way: would it then be illegal to modify the array metadata/header under this model?

**Comment by vasslitvinov** [comment]
It is a very good point. However, it seems like it is the same issue as simply with argument intents. E.g.:

    var A: ... our dynamic array ...;
    proc useit(const ref ARG) { writeln(ARG[7]); } <--- legal?
    useit(A);

My proposal here is that argument/task/forall intents talk about user-level semantics, such as subscripting.

As long as subscripting is allowed by the const checker, the underlying array implementation, such as dsiAccess(), is allowed to do anything.

**Comment by mppf** [comment]
I'm pretty sure we want something like
```
A = B;
```
to continue to work. Right now, in a strict sense, this is using promotion on arrays.

If that is to continue to work, we could:
1. adjust blank intent for arrays to be possibly ref (this is the ref-is-modified proposal e.g.)
2. adjust default task+forall intent for arrays to be 'ref' even though args blank is const
3. adjust promotion -> forall process

Of these 3 is probably the most special-case and maybe least appealing for that reason.

But if we choose 2, the following program would not compile without a `with (const ref A)` task intent:

```
proc f(A:[?D] int) {
  var B:[D] real;
  forall i in 1..100 {
    B[i] = A[i] : real;
  }
}
```

and I think it seems a shame to force the user to write that they are *not* modifying something.

**Comment by vasslitvinov** [comment]
I still think (3) "adjust promotion -> forall process" is a very reasonable option.

To make `A=B` work using promotion, my proposed promotion rule "pass all relevant variables into the implicit forall loop by ref intent" needs modification: "by ref intent for non-const variables and by const ref intent for const variables". I think this revised rule is intuitive and easy to explain (and implement).

**Comment by bradcray** [comment]
[I failed to subscribe to this issue, so didn't realize how much chatter was going on on it, and wrote up the following this morning in response to where the email thread on this proposal left off.  Quickly scanning the conversation, I think it's still a relevant opinion, though it looks like maybe some of it has been anticipated as well.]

As soon as it was proposed that "the default intent for task/forall intents should differ from the default intent for function arguments," my sense of symmetry began worrying that such a choice would just set us up for an equivalent set of challenges in the parallel context as the ones we're currently wrestling with in the function call context.  This is my attempt to create an analogous situation:

    var A: [1..n] [1..3] real;

    foo(A[1]);

    proc foo(X: [] real) {
      forall i in 1..3 do
        ...X[i]...
    }


If X is passed into foo() by 'const ref' by default yet is  passed into the forall loop by 'ref' by default then we seem to have a similar situation to function call cases, where we'd complain "you can't pass a 'const' thing in where a 'ref' is expected."

We could arguably push this onto the user by saying that they should be forced to write:

    proc foo(ref X: [] real) {
      ...
    }

but then if the body of the loop is:

    var sum: atomic int;
    forall i in 1..3 do
      sum.add(X[i]);

and A is declared as:

    const A: [1..n] [1..3] real;

then we can' t pass A into foo() ("can't pass 'const' to a 'ref' argument") even though nothing about the body of foo() actually wants to modify A.  So then we would essentially be forced to write:

    proc foo([const ref] X: [] real) {
      forall i in 1..3 with (const ref X) do
        sum.add(X[i]);

which works, but is laborious.  And it also goes against the main point of this "treat function intents and parallel intents differently" which I think of as being motivated by simplifying common forall loop idioms while also continuing to support current key promotion idioms.  Note that we've failed to support promotion for this case.  I.e., we can't write foo() as:

    proc foo([const ref] X: [] real) {
      sum.add(X);
    }

(because the blank intent going into the implicit forall loop implementing the promotion would be 'ref' but the actual is 'const').  Nor can we write:

    proc foo(ref X: [] real) {
      sum.add(X);

(because the actual is 'const', so mismatches the formal, and the promotion doesn't actually want/need the ref semantics anyway).

My suspicion is that we could create similar analogies for the other cases that have given us semantic challenges (like the sparse IRV case), but I haven't taken that on yet (and may not if this argument is convincing to others).

All of the fixes to this that I can think of have the flavor of "maybe we change the default task/forall intent for arrays based on whether the arrays are const or not" and/or "... based on how it's used within the body of the loop."  And I think this makes good sense, but at which point I think we're essentially back to the most recent "specialize-blank-for-arrays" proposal.

I view this as a good thing, though, as I continue to believe that that solution would preserve a symmetry between how argument intents and task/forall intents are handled.  And there's also arguably a reasonable symmetry between "selection of setters and getters based on context" and "selection of whether blank intent means 'ref' vs. 'const ref' based on context."  So that's still the solution that I'm advocating for.

My other main hesitation to the 'blank means const' proposal is the huge number of changes I expect we'd need to make to the code base to keep things running.  That's a large enough effort that I don't want to jump into it unless we're very, very convinced it's the best way forward.  I'm still a long ways off from that.

**Comment by mppf** [comment]
Let's consider option 3, adjusting how promotion works, for a moment.

Under that version of this proposal, argument and task/forall intent for arrays would match. All would be 'const ref' and imply that the elements cannot be modified.

That means that users would have to use the `ref` forall intent in an example like below:
```
var A:[1..10] int;
var B:[1..10] int;
forall i in 1..10 with (ref A) do
  A[i] = B[i];
```

But furthermore, adjusting promotion in this manner can run into problems with the ref-pair feature.
```
var D = {"a", "b"};
var AA:[D] [1..2] int;
var Inds = [1,2];
AA["b"][Inds] = 3; // promoted

writeln(AA["a"]);
writeln(AA["b"]);
```

As far as I can tell, promotion (currently) executes the sub-expressions only once. So the line marked promoted
```
AA["b"][Inds] = 3; // promoted
```

translates into
```
tmp = AA["b"]
tmp[Inds] = 3;
```

which translates into
```
tmp = AA["b"]
forall i in Inds {
  tmp[i] = 3;
}
```

Now, the question is, how does the compiler know whether to use the ref-return-intent version of AA["b"] or the const-ref one? It seems to me it would depend on whether or not `tmp` is modified in the forall loop's body. I don't think it's sufficient to use a rule like "forall generated from promotion captures const by const and ref by ref" for this reason. (compare with the "ref-if-modified" strategy which easily handles this case).

**Comment by vasslitvinov** [comment]
@mppf - this is clearly an issue if we consider the implementation.

However, if we simply apply Brad's rule, we get that:

    AA["b"][Inds] = 3; // promoted

translates into

    forall ind in Inds with(ref AA) do
      AA["b"][ind] = 3;

which makes sense to me.

AA["b"] could be hoisted out as an optimization, matching what the compiler does now.

**Comment by vasslitvinov** [comment]
@bradcray This proposal is that the default intent for arguments, tasks, and foralls is the same (for a given type).

**Comment by bradcray** [comment]
> This proposal is that the default intent for arguments, tasks, and foralls is the same (for a given type).

Which proposal are you referring to?  The proposal at the top of the issue (which is the one I was commenting on) suggests otherwise:

> Probably want array elements to be mutable by default in forall/tasks/promoted calls. It's not so clear how to make that work with this proposal and it would almost certainly make the current strategy of task intent == blank intent no longer reasonable.

And I'm not seeing anything else in a quick scan of the comments suggesting that we'd use "just const ref" in the forall or promotion cases.  What am I missing?

**Comment by vasslitvinov** [comment]
@bradcray I updated the proposal to clarify same-ness.
