### ISSUE TITLE
approach for #5217: ref-if-modified

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#5219]
This issue describes a possible approach to solve the problems in #5217.

The particular approach under consideration here is that blank intent be `ref` or `const ref` for arrays, depending on whether or not the array formal was set or used in a setting context in the body of a function.

I.e. the compiler would choose what blank intent means based on how the formal is used rather than based upon the type.

In some ways the analysis to compute blank intent would be similar to choosing one or the other branch of a ref-pair.  I think it could proceed in a bottom-up manner. E.g. the following things would cause the formal intent to become ref:
- 'ref' variable declared pointing to formal
- formal passed to another function by 'ref', 'inout, or 'out' intent (including functions we recursively decide have blank intent meaning 'ref').
- formal assigned to (but that's arguably passing to proc = with ref intent).

For arrays, modifying an element of an array formal would cause the concrete intent to be 'ref'. (I *think* this will "fall out" with minor adjustments to the ref-pair 'this' methods. We might need to add support for the idea of ref-pair on iterators though).

For task/forall intents, the same rule would apply to the body of the task/loop as would to the body of a function with an array formal. If the array is modified, it should be "passed" to the task with `ref` intent.

Pros:
* fits with current language - programs that work now still work
* can apply to task/forall intents as well as argument intents
* arguably meets blank-intent design goals:
    * most programs should be able to be written using only blank intents
    * blank intents should minimize the surprises you get if you don't quite understand what they do.
* integrates with analysis to handle ref-pairs - both are backward
* conceptually matches with the idea that blank intent is a shorthand

Cons:
* more complicated in concept than some alternatives
* definitely more complicated to implement than resolveIntents is now
* it might require explicit programmer help for recursive functions (but maybe not)
* it might be surprising how changing one function can change the behaviors of callers to that function
* Almost certainly will need to explicitly choose `const` or `ref` for array formals in extern procs.

**Comment by benharsh** [comment]
I think I'm currently leaning towards this approach the most. It seems to keep the current world mostly the same, and should fix the current refpair issue. In the event of edge-cases, I think it's fine to require users to clarify the intent (as I suspect these cases will involve uncommon patterns).

I was formerly in the "just const ref" camp, but I think I've come to the conclusion that it would be too intrusive of a change for users. If we were to try and work around some of those changes (e.g., promotion), I feel like we'd end up in a similar state where arrays have weird special-case rules.

I've been trying to think of ways that this behavior might be surprising to users, but for the most part I think it should "just work" the way they expect. One possible surprise could be an array modification wrapped in a config param. It seems like an unlikely case though.

Recursion could be tricky, but I think we'd be justified in asking users to break ambiguity if needed.

**Comment by bradcray** [comment]
I think this approach has become my strong preference as well.  I'm going to capture a bit of "why" here, though nobody may care other than me.

My proposal (issue #5220) ended up blending into this because it needed to know what the function was going to do with an array in order to make the correct choice between setter and getter (the ref-pair functions).  At that point, I thought of it as subsuming this proposal but containing the extra element of looking at the actual.  But that begs the question, "Why look at the actual too?"  And on reflection, I don't think there's any strong reason to.  If the function sets (and optionally reads) the array, it's going to decide 'ref':

    proc foo(X: [] real) {
      X = 1.0;
    }

so given:

    var V: [1..n] real;
    const C: [1..n] real;

    foo(V);
    foo(C);

the first call works as you'd expect (and you'd get the same interpretation as if you looked at the actual) while the second would generate an error as it would need to even if you used C's const-ness to determine that X should be passed by const ref:  The difference is whether the error would be in foo()s body ("can't assign to 'const' argument X") or at the callsite and arguably the callsite makes a bit more sense.

Meanwhile if the function only reads X:

    proc foo(X: [] real) {
      var sum: atomic real;
      sum.add(X);
    }

then this proposal would infer 'const' which would make both foo(V) and foo(C) legal while also having the benefit of optimizing foo(V) as suggested in an early draft of my proposal.

So I don't think involving the actual's constness adds anything other than complexity to the implementation and model.  The note about whether the error message is at the callsite or at the assignment suggests to me that, in the ideal implementation, when we determine whether an array argument's default intent is 'const ref' vs. 'ref', we could generate clearer error messages if we keep a trail of breadcrumbs indicating why we decided that.  I.e., "can't pass V to foo() because the default intent of 'X' is assumed to be 'ref' due to the assignment to 'X' in line xyz" is likely to help the programmer understand where they went wrong better than simply "can't pass V to foo() because 'X' has 'ref' intent."

**Comment by bradcray** [comment]
> Almost certainly will need to explicitly choose const or ref for array formals in extern procs.

Thinking out loud:

It seems to me that we could define a default for extern functions, optionally warning the user that we assume that for all extern functions, and that they should add an explicit intent if they want something else.

Related, recall that array formals in extern procs today mean "pass a native/C array," so we're essentially passing Chapel's ddata off to C.

My intuition was initially that 'ref' should be the default because it's the more flexible of the two.  OTOH, one could argue 'const' should be the default because in other Chapel routines wrapping the extern with blank intent, it would permit them to use the more optimized getter() if they weren't doing any writes themselves.  So maybe supporting a default isn't the right approach.

**Comment by mppf** [comment]
Vass pointed out that the default argument intent for the `this` argument for record methods is `ref` but we don't do const checking on it. Perhaps it would make sense to apply the ref-if-modified rule to these `this` arguments as well.

**Comment by bradcray** [comment]
To make sure I'm understanding, the point is that the intent is 'ref' but that we don't stio you from calling a method on a const record as we arguably should?  I.e.,

    record R {
       proc foo() { ... }
    }
    const myR = new R(...);
    myR.foo();   // strictly speaking ought to be illegal; consts can't be passed to a 'ref' intent

If so, that sounds like a plausible proposal to me, for records.  Would that also enable better (or perhaps simplify existing) const checking for record fields?

**Comment by mppf** [comment]
Yes here is an example
```
record R {
  var i:int;
  proc foo() {
    i = 3;
  }
}


const r = new R();
r.foo();
writeln(r);
```

This example compiles and runs now but should be a compilation error. I think that modifying record fields in methods is arguably a convenience of a similar type to being able to modify array elements from a blank intent formal.

Also, I personally think it would be appealing to apply the ref-if-modified strategy to all blank-intent record arguments (not just the `this` ones) - but doing so for the `this` arguments would help to address the current issue above - clean up `const` checking while not rejecting programs that used to be valid. But, one might argue that the default intent for `this` arguments for records should just be `const ref` anyway. I think there's some appeal to making it the same as the default argument intent.

**Comment by vasslitvinov** [comment]
While I prefer "just const ref" because I believe that const checking is good for you, I am OK if this approach is chosen.

**Comment by mppf** [comment]
One more note Re. making ref-if-modified apply to records in addition to arrays.

First, in certain cases, we might have a record containing an array (for example, that is one way we might make a Matrix type). In those cases, I think they will be more intuitive if they can match the array argument behavior.

Second, one reason for 'const' intent being the default for scalar types is so that C and Fortran programmers are less likely to be confused (since these languages have basically opposite behaviors for modifying formals). But, for records, it seems to me that C/C++ programmers normally pass structs by pointer/reference. For that reason I don't think it would be as surprising if a record formal can modify the passed actual. Note that in C/C++ when passing by pointer/reference the default is that the record is mutable.

**Comment by bradcray** [comment]
I wonder if this conversation about records should be broken into its own issue.  It seems like we're discussing four options:

1) Change default intent for 'this' records into 'const ref' always and require the user to create 'ref' methods for things that should actually modify the record.

2) Keep the current default intent for 'this' records as 'ref' but do a better job of const-checking such methods when called on const records.

3) Make the default intent for 'this' records be 'const ref' or 'ref' based on whether the method is read-only or read-write for the record.

4) Make the default intent for all record arguments be 'ref' or 'const ref' based on whether the method is read-only or read-write for the argument.

Each of which has its pluses and minuses.

**Comment by mppf** [comment]
Good point about record intent/this being a separate issue. I've spawned off #5266 to talk about it and plan to delete the comments about it from this thread (including yours - I'm hoping you'll move your thoughts there).

**Comment by mppf** [comment]
(For the record). I'm also in favor of the `ref-if-modified` strategy as I think it fits better with the language we have than the other options.
