### ISSUE TITLE
default intent for ranges?

### ISSUE THREAD

**Issue by vasslitvinov** [chapel-lang/chapel#5256]
What should be the default intent for ranges?
At the very least this should be documented in the spec.

It should probably be `const`.
Concretely, should it be `const in` or `const ref` ?

An important consideration is in handling of range literals and begin statements. E.g.:

    proc processEm(myRange) {
      // do something with the range...
      writeln(myRange);
    }
    proc startIt(myRange) {
      begin { processEm(myRange); }
    }
    startIt(1..10);

Cf. the same for records:

    startIt(new MyRecord());

See also the thread "default argument intent for ranges?" on the internal list in October 2016.

**Comment by mppf** [comment]
I think it should be `const in`.

**Comment by mppf** [comment]
Interestingly, my work towards improving iterator record memory management has run into this, in a way. It happens to be that the default argument that has been giving me trouble is a tuple with a range component. That range component is captured in the iterator as 'ref' since the compiler currently considers ranges to have 'const in' default intent (in most places - for tasks it currently considers them to have 'in' intent). That causes problems when the default argument is created in a proc that returns an iterator record, since the reference refers to stack trash by the time the iterator runs.

Of course there are many ways that I can solve that problem, but changing ranges to be `const in` by default would also do it.

I also wanted to point out that programs can detect the difference between `const in` and `const ref`. Even though the function argument won't be modified, the argument could be a global variable that is modified within the function body.

E.g.

``` chapel
var global = 1..10;
proc test( arg ) {
  global = 1..20;
  writeln(arg);
}
test(arg);
```

It would print out `1..20` if the default intent for ranges is `const ref` and `1..10` if it is `const in`.

Either way, I think we should attempt make task and argument default intent for ranges be the same. Otherwise it would be the first time that these differ & we'd have to say more in the documentation.

**Comment by ronawho** [comment]
I would also lean towards, `const in` but I don't feel incredibly strongly about this. 

I strongly agree with "we should attempt make task and argument default intent for ranges be the same" though

**Comment by bradcray** [comment]
I don't have a strong preference between `const in` and `const ref` but believe it should be one of these.  I agree it should be the same for argument intents as task intents.

**Comment by benharsh** [comment]
I'm leaning towards ``const in`` as well.

Do we know of any existing programs that would change their behavior if we went with ``const in``?

**Comment by noakesmichael** [comment]
I have a clear bias for const in.


On Dec 12, 2017, at 3:01 PM, Ben Harshbarger <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm leaning towards const in as well.

Do we know of any existing programs that would change their behavior if we went with const in?

**Comment by vasslitvinov** [comment]
+1 for const in.

I think the iterator trouble is not a good argument, though, because #7858 should take care of that, right?

**Comment by mppf** [comment]
@vasslitvinov - regarding iterator problems - certainly we can find other ways to adjust the compiler - but it's evidence that there is a meaningful issue here.  #7858 addresses some of it but I'm finding other similar issues that may or may not be fixed by using `const in`.

Certainly we should choose `const in` or `const ref` based on language-level conversations, not so much based on the implementation.

**Comment by mppf** [comment]
The consensus seems fairly clear. We have (so far) 5 in favor of `const in` and nobody championing `const ref` or the current combination of `const in` and `const ref`.

Therefore I'll give the implementation a try. We might learn something important to the decision in the process of testing, and if not, I'll proceed with the change.

**Comment by aditmehta9** [comment]
I think const in might be more preferable.
