### ISSUE TITLE
Try to avoid patching GASNet

### ISSUE THREAD

**Issue by ronawho** [chapel-lang/chapel#5269]
We have a couple of patches that we apply on top of GASNet releases in order to support launching an xterm window to run a debugger and for initial 64-bit arm support. 

I imagine the 64-bit arm support will come in later GASNet releases (it's just a cross-configure file), but it'd be nice to generalize the xterm support and contribute it upstream so we don't have to patch every time we upgrade gasnet versions.

**Comment by ronawho** [comment]
@gbtitus I assigned this to you since you've been the one who upgrades GASNet versions, but I think either of us (or even somebody else) could do this just as easily

**Comment by gbtitus** [comment]
That sounds fine.  I'll start a conversation about this with the GASNet folks.  I think it might be possible to do what our patch does using the existing GASNet environment variables that change the launcher behavior.  I tried doing this for a few hours last year and felt like I was close, but couldn't quite get all the way there.

**Comment by gbtitus** [comment]
I've just been playing around with the CHPL_COMM_USE_{G,LL}DB feature a bit.

With CHPL_COMM_USE_GDB=1 on linux, our current patch effectively prefixes 'xterm -e gdb --args' to the front of the command line executed by the amudp spawner.  I can reproduce this behavior by throwing '-v' to show the amudprun command and then running amudprun manually, with its target command prefixed by that same stuff.  This works fine with GASNET_SPAWNFN=L (local spawning via fork/exec).  With GASNET_SPAWNFN=S (ssh spawning) I also have to set GASNET_SSH_OPTIONS=-X so that ssh enables X forwarding, and then it works there as well.

With CHPL_COMM_USE_LLDB=1 on n MacOS, the corresponding lldb feature works fine with local spawning also.  I can't get it to work with ssh spawning but from the errors I'm seeing I believe this is due to not enabling X forwarding properly.  (Supporting this, the "official" CHPL_COMM_USE_LLDB technique also doesn't work for me on MacOS with ssh spawning, and with the same error messages.)  Since it doesn't work either way, and I'm not sure ssh spawning is critical for "multilocale" debugging) I'm inclined to treat this as a separate problem,

Based on this, I think for CHPL_COMM_USE_{G,LL}DB support we can just modify our launcher to change the target command line, and remove our corresponding GASNet patch.

**Comment by ronawho** [comment]
We've decided not to try to contribute the aarch64 cross-configure upstream. 

I think all we have to do then is move `CHPL_COMM_USE_{G,LL}DB` support into runtime/src/launch/amudprun/launch-amudprun.c

Taking a quick look -- it doesn't seem like it'd be that hard. @gbtitus are you interested in doing that, or would like to try to hand that off?

**Comment by gbtitus** [comment]
I think it'd be a fun thing to work on but it's more worthwhile to the group for me to do comm=ugni performance, so if somebody else can take `CHPL_COMM_USE_{G,LL}DB` that would be great.

**Comment by ronawho** [comment]
Ok, I think that somebody else is me. If I get a free hour or two this week I'll see what I can do
