### ISSUE TITLE
promoted array assignment with downcasting of complex(128)

### ISSUE THREAD

**Issue by ben-albrecht** [chapel-lang/chapel#5343]
### Summary of Problem

The following program results in a compile-time error during function resolution as a result of the promoted assignment of A to a `complex(128)` literal. The error message (with `CHPL_DEVELOPER=true`) is:

```
$CHPL_HOME/modules/internal/ChapelIteratorSupport.chpl:95: error: cannot iterate over values of type complex(128)
$CHPL_HOME/modules/internal/ChapelIteratorSupport.chpl:95: note: unresolved call had id 1089401
```

with `--no-devel`, the error is:

```
complex_downcast.chpl:3: error: cannot iterate over values of type complex(128)
```

Ideally, I'd expect this program to succeed, with the literal assignment `A = i +0i` being downcasted from `complex(128)` to `complex(64)`. A potential short-term solution might be to give a more meaningful error message, such as a type error.

### Steps to Reproduce

**Source Code:**

```chapel
var A: [0..3] complex(64);
// Note: If rewritten (more correctly) as `A = (1 + 0i): t;`, error does not occur
A = 1 + 0i;
```

**Associated Future Test(s):**
`test/arrays/promotion/complex_downcast.chpl`  #5344

### Configuration Information

- Output of `chpl --version`: chpl Version 1.14.0.f3cacb7 (master branch at the time of posting)
- Output of `$CHPL_HOME/util/printchplenv --anonymize`:
```
CHPL_TARGET_PLATFORM: darwin
CHPL_TARGET_COMPILER: clang
CHPL_TARGET_ARCH: native
CHPL_LOCALE_MODEL: flat
CHPL_COMM: none
CHPL_TASKS: qthreads
CHPL_LAUNCHER: none
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_MAKE: make
CHPL_ATOMICS: intrinsics
CHPL_GMP: none *
CHPL_HWLOC: hwloc
CHPL_REGEXP: re2 *
CHPL_WIDE_POINTERS: struct
CHPL_AUX_FILESYS: none
```
- Back-end compiler and version, e.g. `gcc --version` or `clang --version`: Apple LLVM version 8.0.0 (clang-800.0.42.1)

**Comment by bradcray** [comment]
At present, there are a few challenges to making this work as you'd like:

* there are currently no complex literals in Chapel, so 1 + 0i is actually an expression that is adding an integer and an imaginary.  1.0 + 0i would be one that adds a real and an imaginary.  Either of these evaluates to a complex(128) as you note.

* we don't currently do param computations on floating point expressions, which I believe includes not folding "real + imag" expressions to create a param complex.  Based on my memory and looking through the compiler sources, I don't believe we have any notion of param complex values at present (the Immediate type is set up to store them, but I don't see any code that ever creates complex Immediates).

* downcasts from larger types to smaller ones only happen for param values where the value can be seen at compile time to fit into the smaller type without loss of precision.  So we'd need to have a notion of param complexes in order for this to happen.

* I think currently, as a corollary to the "no floating point param ops", we don't downcast 64-bit floating point values to 32-bit values due to not having a good notion of when that's reasonable or not based on the "without loss of precision" rule (perhaps just due to our ignorance w.r.t. floating point semantics).

So these are the things that would need to change / be improved for this to work as hoped for.
