### ISSUE TITLE
Casting enums with explicit types

### ISSUE THREAD

**Issue by ben-albrecht** [chapel-lang/chapel#5412]
### Summary of Problem

Casting an enum element with explicit element types to the element type results in a compilation error in *some* cases.

### Steps to Reproduce

**Source Code:**

The following enum snippet fails to compile:

```chapel
enum Numbers {one=1:int(64), two};
writeln(Numbers.one: int(64)); // error here
```

The error is from `type.cpp` line 260:

```cpp
// We think that all params should have init values by now.
INT_ASSERT(sym && !sym->symbol()->hasFlag(FLAG_PARAM));
```

Interestingly, this snippet, which has a slightly altered code path, succeeds in compiling and executing as expected:

```chapel
type t = int(64);
enum Numbers {one=1:t, two};
writeln(Numbers.one: t); // prints '1'
```

**Associated Future Test(s):**

[`test/types/enum/typed.chpl`](https://github.com/chapel-lang/chapel/tree/master/test/types/enum/typed.chpl) #6207

### Configuration Information

- Output of `chpl --version`: `chpl Version 1.14.0.8dc84bd`

**Comment by cassella** [comment]
`writeln(Numbers:one: int(64)); // error here`

That does fail to compile, but I think you meant `Numbers.one: int(64)`, which fails to compile as described.

**Comment by ben-albrecht** [comment]
@cassella  - corrected, good catch!

**Comment by lydia-duncan** [comment]
I'm going to grab this one next, assuming no one has claimed it

**Comment by lydia-duncan** [comment]
The internal error is due to failing to recognize that the initial value for the first enum constant is a CallExpr (specifically, a call to a _cast function).  Interestingly, removing the explicit size for the int causes the program to work - we only seem to have issues with ints, uints, etc. that involve an explicit size rather than relying on Chapel's default.  Still investigating
