### ISSUE TITLE
param-guarded divide-by-zero test?

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#5476]
Twice in the past year, I've had users get reasonably confused/frustrated by hitting divide-by-zero errors in their Chapel programs (in both cases, in code that they did not write) where they showed up as exceptions.  Given that in our default 'checks' mode we check for seg faults and OOB errors to head off similar exceptional conditions, should we put a check for zero divisor in our / definitions in ChapelBase that are disabled with a --no-div-zero-checks flag (controlled by --no-checks and therefore --fast)?

**Comment by mppf** [comment]
Is this all about *integer* divide by zero (vs floating point)?

**Comment by bradcray** [comment]
I believe so but left that intentionally open to see how people reacted to it.

**Comment by bradcray** [comment]
My opinion is: I believe we should do this only for divides that would otherwise cause exceptions at execution time...  If a divide results in a NaN/Inf style of result and continues on, I think we should retain that behavior rather than trying to intercept it.

**Comment by dmk42** [comment]
Not that this matters yet, but it seems like that would nuke a lot of vectorization.

**Comment by bradcray** [comment]
@dmk42 : I may not have put enough detail to be clear for readers who haven't written these checks in the past:  My working assumption is that these checks would be implemented using a param conditional that would be folded out at compile-time when checks are disabled, resulting in the same code we have today.  I believe it's already the case that if we don't throw --no-checks / --fast, we'll generate code that's extremely unlikely to vectorize.  So I don't think this proposal would significantly change the code's vectorizability in either mode.

**Comment by dmk42** [comment]
@bradcray : OK, that makes sense.  At a later date, we might want to think again about what the default is.  It sounds like currently the checks are on by default.  Once Chapel gets used more heavily, it might be better to have the checks be like \-g (off by default but easy to get).

**Comment by bradcray** [comment]
At the risk of moving away from the issue being proposed here and arguably a different one...

Philosophically, I strongly disagree with this approach.  From past experience, when working in distributed, parallel languages, every segfault, user OOB error, etc. tends to result in a claim that there's a bug in the implementation that we need to fix.  Then, taking the time to dig into it, it turns out that the user was at fault.  I think having safety by default and performance on request is much more likely to result in happy developers and users than performance by default and correctness when asked.  I think it also reflects the trend taken by most modern languages (where the safety may be done through compile-time semantics, execution time exceptions, or some other mechanism).

Coming at it from another angle, most programmers have to work through correctness issues before they start worrying about performance, so focusing on correctness by default seems like the right approach to reflect the typical workflow to me.  Moreover, when programmers aren't getting the performance they want, I think they're much more likely to go looking for flags to improve it; whereas I believe, from past experience, that when users get segfaults they don't expect, they're not likely to go looking for a flag that will point out their mistakes -- they're much more likely to blame the implementation or abandon it altogether.  Anecdotally, the amount of time I've spent chasing down stupid user errors in Chapel on the user's behalf has been almost none compared to my experience with ZPL in grad school, and I think it is in large part due to this philosophy.

Having said all that, I'm curious what you think the value is of having the checks off by default?

**Comment by dmk42** [comment]
From the early days, the Cray philosophy has been to have optimizations on by default.  This accomplishes two things.  First, the optimizations are more heavily tested and are therefore made more robust.  Second, by default, users get the value they were expecting from HPC, including users who don't know how to program, but compile code written by others.

**Comment by noakesmichael** [comment]
I support the preference that Brad expresses here.  It’s possible that I feel it even
more keenly though I take note when Brad uses the phrase “I strongly …”.

Mike




On Mar 3, 2017, at 9:26 AM, Brad Chamberlain <notifications@github.com<mailto:notifications@github.com>> wrote:


At the risk of moving away from the issue being proposed here and arguably a different one...

Philosophically, I strongly disagree with this approach. From past experience, when working in distributed, parallel languages, every segfault, user OOB error, etc. tends to result in a claim that there's a bug in the implementation that we need to fix. Then, taking the time to dig into it, it turns out that the user was at fault. I think having safety by default and performance on request is much more likely to result in happy developers and users than performance by default and correctness when asked. I think it also reflects the trend taken by most modern languages (where the safety may be done through compile-time semantics, execution time exceptions, or some other mechanism).

Coming at it from another angle, most programmers have to work through correctness issues before they start worrying about performance, so focusing on correctness by default seems like the right approach to reflect the typical workflow to me. Moreover, when programmers aren't getting the performance they want, I think they're much more likely to go looking for flags to improve it; whereas I believe, from past experience, that when users get segfaults they don't expect, they're not likely to go looking for a flag that will point out their mistakes -- they're much more likely to blame the implementation or abandon it altogether. Anecdotally, the amount of time I've spent chasing down stupid user errors in Chapel on the user's behalf has been almost none compared to my experience with ZPL in grad school, and I think it is in large part due to this philosophy.

Having said all that, I'm curious what you think the value is of having the checks off by default?

**Comment by bradcray** [comment]
> From the early days, HPC philosophy has been to have optimizations on by default. This accomplishes two things. First, the optimizations are more heavily tested and are therefore made more robust. Second, by default, users get the value they were expecting from HPC, even users who don't know how to program, but compile code written by others.

I don't really want to get into a debate over how well or poorly HPC's traditional philosophies have done at nurturing and growing a productive programmer community on this issue, since I think it is an obvious extension of Chapel's current and historical philosophy.  Let's move any further debate about whether Chapel's philosophy is wrong onto a new issue rather than belaboring it here.

**Comment by bradcray** [comment]
I've opened up PR #5583 to address this request.  To @mppf's comment, I only applied the checks to / on ints and uints.  To @dmk42's concern, I verified that the generated code is identical before and after this change when --no-checks is thrown.
