### ISSUE TITLE
Determine a good default for CHPL_RT_MAX_HEAP_SIZE

### ISSUE THREAD

**Issue by ronawho** [chapel-lang/chapel#5678]
We're inconsistent with our default heap size: 
 - For gasnet, we default to 90% of available ram. 
 - For ugni under aprun we default to 2/3 of availble ram.
 - For ugni under slurm we default to 16GB 

We should figure out a good default and stick with it. Note that a smaller heap size has the benefit of faster startup times: 

Here's some rough startup timings for a no-op test on an XC-30 with 128GB of ram:

```sh
// using qthreads and 16 MB hugepage
export CHPL_RT_CALL_STACK_SIZE=256K
export CHPL_RT_MAX_HEAP_SIZE<size>
start_test --performance test/performance/elliot/no-op.chpl --numlocales=4
```

| size | ugni     | gn-aries |
| ---- | -------- | -------- |
|   1G |   ~5 sec |  ~2 sec  |
|   2G |   ~6 sec |  ~3 sec  |
|   4G |   ~8 sec |  ~4 sec  |
|   8G |  ~12 sec |  ~5 sec  |
|  16G |  ~18 sec |  ~6 sec  |
|  32G |  ~31 sec |  ~9 sec  |
|  64G |  ~61 sec | ~18 sec  |
| 128G | ~103 sec | ~30 sec  |

**Comment by gbtitus** [comment]
The time for ugni is so much greater because it registers the entire heap with the NIC.  Doing so pins the virtual pages to physical ones, which in turn requires the kernel to actually zero the physical memory (so the user process sees clean memory).  I don't believe gasnet+aries registers the heap, which explains why it's much faster.  However, it's still taking time proportional to the amount of memory, which probably reflects page table setup and other memory management overheads.

**Comment by ronawho** [comment]
https://github.com/chapel-lang/chapel/pull/7026 unified ugni-aprun and ugni-slurm defaults. 

ugni is now using dynamic registration so I think it's ok for ugni and gasnet to have different defaults.

With that in mind, I'm going to close this.
