### ISSUE TITLE
Improve ugni startup times

### ISSUE THREAD

**Issue by ronawho** [chapel-lang/chapel#5680]
Ugni startup times can be really long depending on the heap size (CHPL_RT_MAX_HEAP_SIZE)

https://github.com/chapel-lang/chapel/issues/5678 has some detailed timings in it, but using all available memory for 128 GB nodes takes ~100 seconds to startup. Note that this number is fixed (it's mostly a per-node cost, there's not too much overhead as the number of locales increases.)

We recommend lowering the heap size during debugging, but this is annoying and not always practical. It'd be great if there was something we could do to mitigate the high startup times so that we could just default to a larger heap, and not have to worry about long startup times.

**Comment by ronawho** [comment]
@gbtitus would you mind adding some notes on what causes the startup time to be so high? I vaguely remember that it's mostly the kernel zeroing the pages, but I don't understand it well enough to give a good summary

**Comment by ronawho** [comment]
There's some potentially helpful notes in an internal "speed of first touch" thread.

**Comment by gbtitus** [comment]
Duplicating info from #5678, just for ease of reading: comm=ugni startup is slow because it registers the entire heap with the NIC. Doing so pins the virtual pages to physical ones, which in turn requires the kernel to actually zero the physical memory so the user process sees clean memory. (Memory has to be zeroed between when one process uses it and when another does so, so that information doesn't leak across processes and/or users. As I understand it the kernel zeroes a page when a process acquires it rather than when it releases it. Basically, zeroing is delayed until it's known to be needed.)  I rather doubt we can speed up the registration, so probably our only recourse here is to register a smaller heap.

Note that some of the solutions proposed for getting performance with locModel=numa might actually help here as well.  One idea we had was to only register a relatively small (by XC standards) heap, and then register memory and broadcast registrations for larger arrays only as they were allocated.  Of course the total registration and kernel page zeroing time would work out the same, at least for any program that is currently using a right-sized heap, but at least the program startup time would be quicker.

**Comment by cassella** [comment]
FWIW, on my laptop I can allocate a 4GB buffer and memset it 32 times (128 GB of zeroing) in a single-threaded C program in about 10 seconds.  It seems like there's something else going on besides the actual zeroing.

Also FWIW, I doubt you're getting 128 GB allocated as 16 MB hugepages on a node with 128 GB of physical memory.  More likely in the neighborhood of 120 GB.

**Comment by ronawho** [comment]
Yeah, you're right about not getting the full 128GB, internally ugni rounds down from the specified max size to an amount it can actually grab: https://github.com/chapel-lang/chapel/blob/master/runtime/src/comm/ugni/comm-ugni.c#L2453-L2469

**Comment by ronawho** [comment]
Put together a simple program that mimics how we grab huge pages in ugni and then just calls memset. Total execution time is ~41 seconds for 128GB (well actually 115GB with the auto-round down.) 99% of the time is from the memset. Obviously, memset will include page faults/kernel zeroing _and_ user space zeroing, so we should probably update this to just get the fault/kernel zeroing. 

Still even with the user space zeroing, this is only represents 40% of ugni startup time so I agree that something else is going on. Next step is probably to update this toy program with gni registration calls 

```sh
module load craype-hugepages16M
cc f.c -O3
srun --quiet --nodes=1 --ntasks=1 --ntasks-per-node=1 --cpus-per-task=56 --exclusive --constraint=BW28  time -p ./a.out
```

```c
#include <stdio.h>
#include <hugetlbfs.h>
#include <string.h>


size_t bytesToMb(size_t bytes) { return (size_t)((float)bytes/(1024.0*1024.0)); }
size_t bytesToGB(size_t bytes) { return (size_t)((float)bytes/(1024.0*1024.0*1024.0)); }
size_t gbToBytes(size_t gb) { return gb *(1024*1024*1024); }

int main() {
  size_t page_size = gethugepagesize();
  size_t size = gbToBytes(128);
  size_t decrement = 0;
  void*  start;

  printf("page size is %zu MB\n", bytesToMb(page_size));

  size = (size / page_size) * page_size;
  decrement = (((size_t) (0.05 * size)) / page_size) * page_size;

  size += decrement;
  do {
    size -= decrement;
    start = get_huge_pages(size, GHP_DEFAULT);
    printf("HUGEPAGES get_huge_pages(%zu GB) returned %p\n", bytesToGB(size), start);
  } while (start == NULL && size > decrement);

  memset(start, 0, size);
}
```

**Comment by gbtitus** [comment]
I stuffed some timing code into comm=ugni in order to investigate this.  I then ran hello.chpl on 2 nodes with various heap sizes.  Here are the timings for the `GNI_MemRegister()` and `GNI_MemDeregister()` calls, in seconds quoting 2 significant digits:

| size | register | deregister |
| ----: | ----: | ----: |
|   1G |   0.34 |  0.50  |
|   2G |   0.68 |  0.99  |
|   4G |   1.40 |  2.00  |
|   8G |  2.70 |  4.00  |
|  16G |  5.50 |  8.00  |
|  32G |  11.00 |  16.00  |
|  64G |  23.00 | 32.00  |
| 128G | 43.00 | 54.00  |

A few notes:

- The ugni comm layer doesn't actually call `GNI_MemDeregister()` to de-register the heap or anything else for that matter.  I added the de-registration calls just so I could time them.  I expect that in the absence of explicit calls the de-registration is still effectively done, however, as a side effect of process teardown.

- We register the shared heap once for every communication domain we create.  The above timings are the sum of the registration and de-registration time for all these comm domains.  I observed that the first registration takes by far the longest.  I don't know which, if any, of the de-registrations stands out in the same way.

- These are just registration and de-registration for the shared heap.  There are other registered memory regions, but they wouldn't typically be nearly as large as the heap.

It would be interesting to know what the de-registration cost reflects.  @cassella, do you know?  If you don't I can find out for us.

**Comment by cassella** [comment]
I don't know off-hand, sorry.

**Comment by ronawho** [comment]
Todo for me -- distill registration code into a relatively simple/standalone C program

**Comment by ronawho** [comment]
Looks like gasnet-aries uses dynamic registration and they have done some work recently to improve startup times, so that's probably why their startup times are faster than ours currently:

```
05-12-2016 :  Release 1.26.2

* Cray uGNI (gemini- and aries-conduits)
  - Use Cray's UDREG library to ammortize cost of dynamic registration
  - Multiple changes to reduce startup overheads
```

**Comment by gbtitus** [comment]
I've just rerun my little 2-node test case, holding the heap size constant at 16G and varying the hugepage module page size by factors of 4 from 2M (8192 pages) to 512M (32 pages).  The timings were basically all the same for both registration and deregistration, indicating that whatever is taking the time, it's not an operation that is proportional to the number of pages.

**Comment by gbtitus** [comment]
I've extended my comm=ugni timing code and done a few more runs.  I added the ability, under control of an environment variable, to touch the shared heap into existence before registering it and to time the touch and the registration separately.  I again ran on 2 XC nodes and I varied the heap size by powers of 2 from 16G to 64G.  Here are the results, to 2 significant digits as before:

| size | touch | register | deregister |
| ----: | ----: | ----: | ----: |
|  16G |  3.50 | 2.10 | 8.00  |
|  32G |  6.90 | 4.20 | 16.00  |
|  64G |  14.00 | 8.40 | 32.00  |

Note that the sum of the "touch" and "register" values match the "register" values from the previous runs quite well.  It appears from this that, roughly speaking, the kernel overhead of the page management and memory zeroing is about 2/3 of the heap creation time and the actual registration is about 1/3.

I also added code to `munmap()` the shared heap before deregistering it at the end.  Doing that caused a `SIGSEGV` later in program shutdown, not in the `munmap()` itself but later on.  I didn't track that down, but I did discover that unmapping the heap takes almost no time, less than 1 millisecond.  So it's still a mystery what's so expensive about deregistration.

**Comment by gbtitus** [comment]
Another update about unmapping the heap.  Zach Tiffany pointed out that the `munmap()` wouldn't actually do anything if the memory was registered, because the user count for the pages wouldn't be zero.  I did some more hacking in comm=ugni, such that only the first 1G of the heap was actually registered and available for use by the program, and at the end deregistered that and unmapped the rest.  The `munmap()` only took a few hundredths of a second.  The deregister is still the biggest part of the shutdown time.
