### ISSUE TITLE
Improve code that limits the size of qthreads memory pools

### ISSUE THREAD

**Issue by ronawho** [chapel-lang/chapel#5749]
I setup code to limit the size of qthreads memory pools in #257 and #1649. At the time I thought there was a single global pool for task stacks, but now I believe there's a task-stack pool per worker. 

With that in mind, I'm limiting the max size in #5748 to avoid using outrageous amounts of memory on high cpu count systems (like KNL)

The comments around the limiting code could use some cleanup, and I'd like some verification from the qthreads team that pooling is indeed done on a per-worker basis.

This is just a reminder to cleanup that code and talk to the qthreads team.

**Comment by gbtitus** [comment]
If there really is a pool per Qthreads worker then it seems like we could reduce the pool size quite a bit without hurting performance in the usual case in which we don't oversubscribe the workers with tasks/qthreads.  It seems like enough room for 2 stacks (including guard pages, if appropriate) per pool would be enough, maybe even 1 stack per pool.

Relatedly: we should consider reducing our stack size by the amount needed for guards, if any, plus whatever other overhead is needed for the pooling. We could reduce some of our current waste if the pools fit evenly into the large jemalloc chunk size used when we have a registered heap on hugepages for Cray systems. (Current max-sized 65m pools waste hugepageSize-1m bytes per pool, since the memory is acquired in full hugepages.)

**Comment by ronawho** [comment]
Yeah, I was thinking about that recently too. I was wondering if we could have every worker grab enough room for 2 stacks initially, and maybe have future extensions grab larger sizes. i.e. grab room for 2 stacks on init, and if more are needed later, grab larger chunks. 

Today, I think we'd want room for 2 task stacks -- because we do usually end up with 2 tasks running on "worker 0". A `coforall in 1..here.maxTaskPar` will create maxTaskPar tasks, in addition to the 1 running main, so we'll end up with 2 tasks there.

I'm also not super familiar with how qthreads pooling works. I don't know how they "extend" pools when a pool is out of memory. I'm assuming if the pool is out of memory, they just allocate a new pool, and somehow link them together, but I'm not sure if there is a cost for a "pool miss"
