### ISSUE TITLE
Try making network atomics comm layer agnostic

### ISSUE THREAD

**Issue by ronawho** [chapel-lang/chapel#5796]
Our current network atomic support requires CHPL_COMM=ugni. So far as I know, the network AMO support isn't actually tied in with the rest of the comm layer, so I'm wondering if we could make it work on a Cray regardless of what communication layer is being used.

**Comment by ronawho** [comment]
@gbtitus and/or @sungeunchoi I'm curious if you have any thoughts

**Comment by sungeunchoi** [comment]
I don't necessarily think they should be comm layer agnostic.  It would be difficult to manage the low level resources if you did that. and I think it would lead to problems.

What I do think is that they should be able to reuse the module code that does the remote atomics if network atomics are not supported.  Right now, that code is duplicated in the ugni comm layer, and that doesn't seem like a good thing.

**Comment by gbtitus** [comment]
I'm not sure exactly what you're thinking about, so I'll comment based on what I think you're thinking about, and then if my assumptions are wrong you can ignore my comments.  :-)

Certainly at some level you want agnosticism for network atomics, so that user code doesn't have to write architecturally-based if-stmts.  There are arguments in favor of placing that agnosticism in either the module code or the runtime, but they're different arguments and I think actually it's appropriate to decide in both places.  I think it's fine to make a global decision in the module code, based on the comm layer, whether to do all network atomics by means of runtime comm layer `chpl_comm_atomic_*()` calls or to do all of them using on-stmts and processor atomics.  (I always like to do this sort of thing at the highest level we can in the S/W stack, all other things being equal.)  But to emphasize: I think the appropriate decision at this level is a single one covering all the atomic ops: to do all of them either the one way or the other.

I also think that within the individual comm layer is a good place to do this, but here the decision has to do with specific atomic ops and/or operand types and/or situations.  An example is the comm=ugni code to do 32-bit network AMOs using executeOn and processor atomics for Gemini (which doesn't support those), versus using real network ops for Aries (which does).  Another is our use of executeOn and processor atomics when the target isn't in registered memory, versus network ops when it is.  For these cases it's appropriate to decide at the lowest level in the S/W stack, because (1) the information needed to make the decision isn't available at higher levels and (2) you have a chance of being able to use lower-overhead techniques for the executeOn+cpuAtomic solution that you'd have no way of writing the code for at a higher level.  An example of (2) is the effort we go to in comm=ugni to short-circuit both the AM and the operation (done in the AM handler) for the executeOn+cpuAtomic case.  You could achieve the same functional effect by using `chpl_comm_execute_on_fast()` from outside the comm layer but it wouldn't run as fast.

Another place you could introduce agnosticism is at the very top surface of the runtime comm interface; you could put a default comm-layer-agnostic executeOn+cpuAtomics implementation at the interface level (runtime/src/chpl-comm.c, basically) and then allow individual comm layer implementations to override this if they were capable.  I'm not so fond of this solution -- it's essentially the same as deciding in the module code, but one level lower in the S/W stack, and I don't think we have any additional info at the top surface of the runtime interface that we don't (or can't) have at the module level to make just as good a decision there.

An interesting case related to all this is: what do you want to do with a network atomic op to a target that turns out to be node-local?  It's tempting to decide in the module code to do this with a CPU atomic operation on the local variable, but that's only safe if network and CPU AMOs are coherent (they're not, in the Cray Gemini and Aries networks).  The specific comm layer obviously knows or can find out whether they are and then make this decision safely, but the module code cannot.  We could extend the comm layer interface so the module code could get the info it needed to decide this, but I'm not sure this could be done with both full correctness and maximum performance unless the decision also took into account the operation and the operand type and perhaps other characteristics (like registration) and by the time you get this complicated you might as well decide way down deep in the runtime (as we do, in comm=ugni).

Hope this helps!

**Comment by ronawho** [comment]
Cool, thanks for the info. Really what I was wondering is whether the network atomic code was really intertwined with the chpl_comm=ugni implementation, or if it would be easy/possible to use the existing network atomic code with gasnet. i.e. since gasnet doesn't have a network AMO interface I was wondering if our `chpl_comm_atomic_*` interface could be coded in a way that didn't depend on the comm layer.

**Comment by sungeunchoi** [comment]
Just to reiterate, unless both the comm layer (gasnet+ugni) and the network atomics code (ugni) were written to not assume they can have all the HW resources on a node, using them together may be difficult to control (in the best case) or lead to complete failure (in the worst case).

Since this can't be guaranteed for arbitrary comm layers, I don't think this is a good idea.

**Comment by gbtitus** [comment]
I think I understand the proposal better now.  No, the network atomics support in comm=ugni could not easily be transplanted into comm=gasnet or used at the same time as the latter.  You'd have to in essence run two comm layers simultaneously (ugni for network atomics and the AMs to support those, gasnet for everything else), two pollers, etc.  It'd be hard to write, impossible to debug, and a giant pain to maintain.

**Comment by PHHargrove** [comment]
I just wanted to mention that GASNet should have an AMO interface, including Aries-specific support, in a developer's snapshot by the end of Dec 2017 and in a full public release by Mar 2018.

**Comment by ronawho** [comment]
So (obviously) I had no idea how network AMOs were implemented when I originally opened this. Based on the feedback in this issue and some chats with Greg, I'm going to close this issue.

@PHHargrove good to know about GASNet's upcoming AMO interface. I'd certainly be interested in testing out that interface whenever it starts to come online.
