### ISSUE TITLE
Internal docs missing links for repeated symbols

### ISSUE THREAD

**Issue by ben-albrecht** [chapel-lang/chapel#5884]
### Summary of Problem

On the [Domains and Arrays](http://chapel.cray.com/docs/master/builtins/internal/ChapelArray.html) documentation page, any method or field that is repeated does not have a URL shortcut for the second link, e.g. `domain.shape()` has this [link](http://chapel.cray.com/docs/master/builtins/internal/ChapelArray.html#ChapelArray.shape) and `array.shape()` has no link.

I suspect that the issue is related to the post-processing done on internal modules when building the docs. I did not find any examples of this in the standard/package modules, and I was unable to reproduce this bug in a smaller code snippet, e.g. the following 2 snippets work as expected:

```chapel
class A { }
class B { }
proc A.foo() {} // gets linked as #A.foo
proc B.foo() {} // gets linked as #B.foo
```

```chapel
class A { proc foo() {} } // gets linked as #A.foo
class B { proc foo () {} } // gets linked as #B.foo
```

#### Motivation

While this bug is fairly trivial, it can be annoying when trying to point a user to a particular part of the documentation. I believe @bradcray initially encountered this when trying to link new array & domain methods in the release notes.

**Compile command:**
`chpldoc foo.chpl`

### Configuration Information

- Output of `chpl --version`: `1.15.0` (master at the time of writing)

**Comment by ben-albrecht** [comment]
Originally reported by @bradcray

**Comment by lydia-duncan** [comment]
I'm going to take a look at this next if no one else has claimed it

**Comment by lydia-duncan** [comment]
This is due to [this line](https://github.com/chapel-lang/chapel/blob/95ef07424e476500567e4413d9577e20ea4f21d8/modules/internal/fixInternalDocs.sh#L121), [this line](https://github.com/chapel-lang/chapel/blob/95ef07424e476500567e4413d9577e20ea4f21d8/modules/internal/fixInternalDocs.sh#L173), and [this line](https://github.com/chapel-lang/chapel/blob/95ef07424e476500567e4413d9577e20ea4f21d8/modules/internal/fixInternalDocs.sh#L193).  All three modify the starting line for a record declaration.

They were added so that we didn't reveal the under-the-cover information that domains, arrays, etc. are records.  However, they break the tagging for the type so Sphinx doesn't know that the indented information underneath it should be linked with the type declared above.

How to resolve this seems like a discussion item - I can remove those operations, but do we want to reveal that information for the sake of the links?  I'm not sure what a good alternate solution would be - there's no situation where a type alias would be able to define methods within its declaration, so forcing Sphinx to recognize that possibility is another case of "a chpldoc change that would only ever benefit the internal modules, never chpldoc users", so I'm loathe to do something along those lines.

**Comment by ben-albrecht** [comment]
> However, they break the tagging for the type so Sphinx doesn't know that the indented information underneath it should be linked with the type declared above.

Do you know why the renames break the tagging, and if it's possible to rename while maintaining tagging?

**Comment by lydia-duncan** [comment]
What I meant by tagging is the prefix that gets generated so that Sphinx understands what we've given it.  "record" is intrinsically part of that prefix, so replacing it changes the meaning and confuses Sphinx.

**Comment by ben-albrecht** [comment]
Gotcha, and a prefix of "type" does not allow for fields or methods. So like you said above, the open question is something like: "are we okay with exposing things like domains, arrays, and tuples as records instead of types in the documentation?"

**Comment by lydia-duncan** [comment]
Essentially, yeah.  A prefix of type allows secondary methods, but the problem we're seeing only impacts primary methods and type's can't have those (or fields, as you said).

**Comment by ben-albrecht** [comment]
Would it be that bad for Chapel's sphinx domain to allow types to have fields and methods? If not, that might be one solution that doesn't involve modifying `chpldoc` to treat internal docs special.

**Comment by lydia-duncan** [comment]
Personally, I find it hard to justify that work since it would only impact our internal documentation generation - we're never going to support that on type aliases in normal Chapel code.  I'd be willing to do it anyways, I just am leery of using developer time that way.

**Comment by ben-albrecht** [comment]
> Personally, I find it hard to justify that work since it would only impact our internal documentation generation 

I think it's easier to justify when you consider it's the internal documentation generation of the user-facing documentation. The modification just happens to be on a tool that is available to users as well, [Chapel's Sphinx Domain](https://github.com/chapel-lang/sphinxcontrib-chapeldomain).

Thinking more about this, I don't think it'd be that bad to allow types to have fields in methods in documentation land. Anyone using Chapel's sphinx domain would be unaware of this, unless they tried it, in which case they probably would like this feature for similar reasons we do (abstracting away implementation details to users).

**Comment by mppf** [comment]
I just noticed this again with targetLocales.

**Comment by lydia-duncan** [comment]
This looks to have been resolved (by migrating the documentation for the automatically included types into their spec chapters).  Closing
