### ISSUE TITLE
Restore understanding of blk field in arrays, in support of pyChapel array translation

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#5904]
### Summary of Problem
After #5338, we experienced an error in the pyChapel build due to translating a numpy array that was sparsely packed into a Chapel array.  Previously, this implementation relied on the blk field, but the blk field is no longer interesting for default rectangular arrays.

Note that some pyChapel tests, test_pych_reduce_add.py and test_chapel_slicing_inline.py, work
in spite of this change.

When this issue is resolved, please also close [the corresponding pyChapel issue](https://github.com/chapel-lang/pychapel/issues/67)

### Steps to Reproduce

**Source Code:**

See https://github.com/chapel-lang/pychapel/blob/master/module/templates/chapel/prefix.chpl#L57

**Compile command:**
`python test_finance_chapel_numpy.py --filename aux/GBPUSD1m.txt --no-viz`

**Associated Future Test(s):**
$pyChapel_home/docs/source/examples/test_finance_chapel_numpy.py

### Configuration Information

- Output of `chpl --version`:
chpl Version 1.15.0
pyChapel 0.1.17
- Output of `$CHPL_HOME/util/printchplenv --anonymize`:
CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: gnu
CHPL_TARGET_ARCH: native
CHPL_LOCALE_MODEL: flat
CHPL_COMM: none *
CHPL_TASKS: fifo *
CHPL_LAUNCHER: none
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: cstdlib *
CHPL_MAKE: gmake
CHPL_ATOMICS: intrinsics
CHPL_GMP: none *
CHPL_HWLOC: none
CHPL_REGEXP: none *
CHPL_WIDE_POINTERS: struct
CHPL_AUX_FILESYS: none

CHPL_LIBMODE: shared
- Back-end compiler and version, e.g. `gcc --version` or `clang --version`:
gcc 4.8.5 (probably any)
python 2.7.9 (probably any)

**Comment by lydia-duncan** [comment]
How does this look, @bradcray?

**Comment by bradcray** [comment]
This looks good -- I changed it over to a feature request, because I don't think we've ever made any claim that Chapel can support external arrays with non-packed striding (even though pyChapel was relying on this by poking around in Chapel's internals).

My proposed solution here is to introduce a param in DefaultRectangular which pyChapel can set to say whether the blk() of the inner dimension should be used.  This also relates somewhat to my effort to optimize away the storage of that blk() value (which could be done when this param is false), started in https://github.com/bradcray/chapel/tree/arrayViewAllThree-noStoreBlkRank (which is going to take some work to bring back onto master...  but will also now benefit from 'void' support).

**Comment by lydia-duncan** [comment]
Closing since we don't intend to support pyChapel going forward
