### ISSUE TITLE
Unfriendly behavior of assigning generally real values to real(32) variables

### ISSUE THREAD

**Issue by ian-bertolacci** [chapel-lang/chapel#5922]
### Summary of Problem
Assignments from a real-like expression to a real(32) typed variable produce the error:
`error: type mismatch in assignment from real(64) to real(32)`

For example, both of these statements produce this error:
```
var a : real(32) = 0.0;
var b : real(32) = 1 / (2.0 : real(32));
```

While this can be fixed with casting, it seems odd that 
1. The size of real literals is always assumed to be 64-bit
2. Operations with a real(32) and an int (of seemingly any size) result in a real(64)

A user might also be confused since assigning an int literal to a int(8) variable does not require casting:
```
var a : int(8) = 10; // No error
```

While not a 'bug' it is not especially user friendly, and results in lots of seemingly unnecessary casts.

### Configuration Information

- Output of `chpl --version`:
```
chpl Version 1.14.0
Copyright (c) 2004-2016, Cray Inc.  (See LICENSE file for more details)
```

**Comment by bradcray** [comment]
Hi Ian --

> 1) The size of real literals is always assumed to be 64-bit

Here's my take on this.  I think it's reasonable for real literals to be assumed to be 64-bit because they need to be assumed to be _something_ so that for cases like:

````chapel
var a = 1.0;
````

we have a well-defined type for 'a'.  For your first case:

> ````chapel
> var a : real(32) = 0.0;
> ````

I'd argue what you really want is for the compiler to be willing to coerce param real(64) values into real(32) values, at least in some situations.  This is the feature that permits your int case to work today:

> ````chapel
> var a : int(8) = 10; // No error
> ````

Here, '10' is an int(64), but because it's a param value (one known to the compiler), it enjoys coercions to smaller int types that can hold its value (which happens to be all of them; but if your initializer above was 512, the initialization would not be legal).  

For floating point values, when we were drafting the language, we felt uncertain how to define cases when it would vs. would not be reasonable to coerce a 64-bit float into a 32-bit float (due to a combination of lack of floating-point expertise on our team and fear of doing the wrong thing).

I'd guess that, broadly, the team would support real(64)->real(32) param coercions given a solid proposal for when it does / does not make sense to do so.  For example, it seems obvious to me that a real(64) whose exponent was out of the bounds allowable by a real(32) should not be coercible.  Should we also be sensitive to the amount of precision used/required to represent the mantissa, or should we be willing to drop that on the floor?  Is there a precedent we could look to here for making this decision?

Until such a change makes it into the code base, I'll note that I usually approach your first statement by writing it as follows:

````chapel
var a = 0.0: real(32);
````

(that is, using type inference and a cast).  I'm not suggesting this is a complete solution in lieu of coming up with a better param-float coercion story; simply that it may save some typing relative to the more ludicrously repetitious:

````chapel
var a: real(32) = 0.0: real(32);
````

Your second case:

> ````chapel
> var b : real(32) = 1 / (2.0 : real(32));
> ````

is more surprising to me, unrelated to the rationale I gave above, and appears to be a bug/oversight to me.   If you compile this with ``--explain-call='/':1``  ("explain the '/' function call that appears on line 1"), the compiler reports that the four candidates are:

````
$CHPL_HOME/modules/internal/ChapelBase.chpl:277: note: candidates are: /(a: real(64), b: real(64))
$CHPL_HOME/modules/internal/ChapelBase.chpl:279: note:                 /(a: complex(128), b: complex(128))
$CHPL_HOME/modules/internal/ChapelBase.chpl:283: note:                 /(a: real(64), b: complex(128))
$CHPL_HOME/modules/internal/ChapelBase.chpl:286: note:                 /(a: complex(128), b: real(64))
$CHPL_HOME/modules/internal/ChapelBase.chpl:277: note: best candidate is: /(a: real(64), b: real(64))
````

and then selects the ``real(64)``, ``real(64)`` version.  I'd agree that this is the best of these four candidates, but note that the real(32) versions are not listed here.  Doing a different quick check:

````chapel
proc foo(x: real(32)) { }
foo(1);
````

it appears that integers do not coerce to 32-bit floats.  This seems like an oversight/mistake to me and is probably reasonably simple to fix.  I'll take a quick look into it.

**Comment by bradcray** [comment]
(I also wanted to note that this issue is at least somewhat related to #5343)

**Comment by bradcray** [comment]
Looking at the code, I don't think "oversight" covers our failure to support int->real(32) coercions, because we very explicitly exclude it.  But that's not to say that we made the right decision.  I'm currently exploring what implications might be if we were to relax this.

Here's my best guess as to why we disallowed it when this was implemented:

1) We generally wanted to create a language that would only support coercions when the original value would not be compromised by the conversion (e.g., we don't support int(64)->int(32) coercions, except when the int(64) value is known to the compiler and can be represented by int(32)).
2) We understood that there are integer values which can't be represented as floating point values without loss of accuracy which would suggest not permitting ints to coerce to floats by principle 1 unless the int's legal range of values completely fit within the float's mantissa.
3) At the same time, we knew that we wanted ints to coerce to some sort of floating point type because requiring casts for -every_ int(64)->real(64) coercion would be too counterproductive.
4) As a result, I think we only opened the door to coercions to real(64) and not real(32) figuring that the number of int value cases that could lose accuracy would be less.

That said, I'm not prepared to argue that this was the right decision -- I think we made it conservatively, figuring it would be easier to relax it later than to try and put the cows back in the barn.  See also my disclaimer above about not having floating point expertise on the team at that time.  Perhaps int->float conversions should always be permitted without worrying about losing accuracy.

Interestingly, we often went to C# as a reference point in questions of coercions, and I'm noting that they permit both ints and longs to coerce to floats and doubles which also suggests we were being unduly cautious:  https://msdn.microsoft.com/en-us/library/y5b434w4.aspx

I've opened a five-minute fix (TM) PR in #5923 and am running it through testing to see what breaks if we relax this restriction (assuming I've done it appropriately).

**Comment by npadmana** [comment]
Let me add a :+1: to this issue....   I just tripped over this doing `var tmp:real(32); tmp = 2*tmp-1;` (see discussion in #5595, where this was compounded by the fact that the compiler obscured this error).

While type-casting once in a while is fine, it really does start to get clumsy, because you end up needing to do it everywhere if you use real(32). (I think the phrase I used on IRC was "drives me nuts"). So it would be nice if the compiler could coerce these param ints into real(32)'s in these cases.

**Comment by bradcray** [comment]
@npadmana : I believe the case you give should work, similarly to Ian's original case 2.  Unfortunately, my attempt to fix the issue quickly in #5923 ran into sufficient issues that I wasn't able to fix it as hoped in the time available, but would still like to get back to it sometime.  If this is high priority for you, would you let me know?

**Comment by npadmana** [comment]
@bradcray -- It's not blocking anything, simply because I can always cast. However, since the code I've been working on uses real(32)'s, it does get a tad old..... It's a hit on the P=Productivity in HPCS.

**Comment by bradcray** [comment]
As a workaround until the root problem can be addressed, are you able to provide your own int op real(32) overloads to avoid relying on the casts?

**Comment by npadmana** [comment]
Oh, I hadn't thought about that. I guess I could do that..... 

Do I need to worry about performance hits with user defined versions of these?

**Comment by bradcray** [comment]
No, they shouldn't have any impact on performance relative to the casting you're doing now (I'm imagining they'll just do the same casting as you are).  You could declare them as 'inline proc' to ensure that they'll end up being essentially identical to the cast-based code you're writing today.

**Comment by mppf** [comment]
@bradcray - I've been thinking about this issue again. I'm able to describe what was going wrong with earlier attempts at least.

What I want to discuss is - what should the resolution rules be that enable this to work?

First, let's consider an example from your earlier PR:
```
proc foo(x: real(32)) {
  writeln("In 32-bit foo()");
}
proc foo(x: real(64)) {
  writeln("In 64-bit foo()");
}
foo(1);
```

Without any special treatment, resolution would choose the 32-bit version, because there is an implicit conversion from real(32) to real(64) and so the real(32) argument is "more specific". I believe that we can adjust "param prefers" to choose the real(64) version in this case, but the way your earlier PR did it broke the following example:

```
var i32:int(32);
var i64:int(64);
i32 == i64;
```

I think this example shows some language-design questions about the resolution rules. It seems obvious to me that we would like this to resolve to the int(64) version of `==` but the following pairs of types for the arguments are all candidates:
 * int(64), int(64)
 * real(64), real(64)
 * complex(128), complex(128)

(These cases come from studying the table in the Implicit conversions section of the spec & knowing that we'll have == for each numeric type).

Resolution should choose the int(64) version because there is an implicit conversion from int(64) to the others and so int(64) is "more specific".

Now, to the language-design component here. The spec section "Determining More Specific Functions" lists param preference as being a late type-breaker - after all other arguments are equally specific. But that is not what the implementation does - instead, the implementation checks for param preferences before considering if the argument is more specific. This is related to the bug above. But if we were to move it later, how could  it handle the `foo(1)` case above? Perhaps we need to consider param rules twice in determining more specific arguments - once before the general more specific argument test and once after?

**Comment by mppf** [comment]
@bradcray - I'm very close to getting this working. However I've encountered a language-design open question. I'm interested in your thoughts on the matter.

Right now, on master, we have:
``` chapel
proc foo(x: real(32)) {
    writeln("In 32-bit real foo()");
}

proc foo(x: real(64)) {
    writeln("In 64-bit real foo()");
}

var x:int(8);
foo(x);
```

resolving to the 64-bit real version. On my prototype branch, this changes this to the 32-bit version. (Vs foo(1) with a param/literal, which resolves to the 64-bit version, since `1` is a 64-bit integer).

The thing is, right now on master, if we have

``` chapel
proc bar(x: int(32)) {
    writeln("In 32-bit int bar()");
}

proc bar(x: int(64)) {
    writeln("In 64-bit int bar()");
}


var y:int(8);
bar(y);
```

it resolves to the 32-bit version. I believe that one of the two needs to change as we add support for implicit conversions to real(32). Do we want both programs to resolve to the 32-bit version (which the spec's "there is an implicit conversion" resolution rule gives) or do we want both programs to resolve to the 64-bit version (according to some new rule)?

**Comment by mppf** [comment]
I'd like to register a preference for "some new rule" to prefer the default-sized int/real but I'd still like to hear your feedback. My reasoning is that this matches better with an alternative (but inexact) interpretation of param literals like `1` - that its type is the smallest type that can store the number. This alternative interpretation is closer to true with enums.

In other words, it might seem surprising that `128` and `y:uint(8)` behave differently, in terms of what integer types they prefer to dispatch to.

**Comment by bradcray** [comment]
I prefer the status quo, but am still working on how I would argue for it.  I'm curious how your proposed new rule would behave for an int(8) and `64` in the event that there was neither an int(8) overload nor an int(64) overload.

My argument for the status quo is that when you stay within a type, it seems natural to slowly work your way up the size hierarchy for that type.  However, when you jump types, it seems reasonable to jump to the default size for that type, if available.

You may not be, but I wouldn't spend too much time thinking about preserving / studying the current behavior for either uints or enums, both of which are pretty broken I think.

**Comment by dmk42** [comment]
I've been discussing this with @ben-albrecht .  I'd like to express an opinion in favor of allowing the coercion to 32-bits because then it's easier to make INFINITY and NAN work for real(32) as suggested by Damian McGuckin.

**Comment by bradcray** [comment]
@dmk42: You're talking about coercion of real literals to real(32) values?  I'm not sure anyone's disagreed with that part of the proposal, but I may be wrong...

**Comment by dmk42** [comment]
@bradcray : OK, I misunderstood your arguing for the status quo.

**Comment by mppf** [comment]
First, I went ahead and adjusted my branch to be more like master in this regard. At least the implementation seems to be understandable (to me) at this point...

> My argument ... is that when you stay within a type, it seems natural to slowly work your way up the size hierarchy for that type. However, when you jump types, it seems reasonable to jump to the default size for that type, if available.

It depends on what you mean by "stay within a type". I think you mean that int(8) to int(16) conversions "stay within a type" but that uint(8) to int(16) does not, and uint(8) to real(32) certainly does not.
 
>  I'm curious how your proposed new rule would behave for an int(8) and 64 in the event that there was neither an int(8) overload nor an int(64) overload.

I don't have a good formulation for a new rule yet, but it's clear to me that the spec needs to change either way (since it doesn't describe the current behavior either). But, to answer your question:

``` chapel
proc baz(x: int(16)) {
    writeln("In 16-bit int baz()");
}
proc baz(x: int(32)) {
    writeln("In 32-bit int baz()");
}

var z:int(8);
baz(z);
baz(64);
```

prints out "in 16-bit baz()" both on my earlier branch / with my rule as well as on master.

Lastly, I thought a little bit about "Why do we have 'param prefers' at all?". I think that the answer has to do with preferring to stay within a type when possible. The 'param prefers' idea is really just a weak preference that is lower priority that the "more specific" rule for other arguments. To enable something like myUint8 + 1 to resolve to the uint(8) version of + rather than being ambiguous. In my branch, I've renamed this to 'weak prefers' since I've been confused about what this has to do with 'params' for several weeks (the answer is, it's particularly applicable to params but important in other cases too).

> uints or enums ... are pretty broken I think

If it's easy for you to point me to some examples / commit messages / whatever, I'd like to understand if I can also fix these issues. I've had to make what I consider significant changes to the "param prefers" logic in order to get param int -> real(32) coercions working...

**Comment by mppf** [comment]
Here is another tricky issue (which I have simply worked around for now).

``` chapel
proc foo(param x:int(16), param y:int(16)) param
{
  return x + y;
}

proc foo(param x:int(32), param y:int(32)) param
{
  return x + y;
}

param ap:int(16) = 1;
param bp:int(32) = 1;
param c = foo(ap, bp);

writeln(c.type:string);
```

Which `foo` should the call resolve to? My understanding of *param prefers* rules is that they'd prefer to keep their argument type the same (if we're not switching types like int -> real say). For that reason, each candidate foo has one *param preferred* argument, which leads to ambiguity.

The reason this program compiles on master is simply that param integers with not default size don't participate in such *param prefers* logic and instead operate with non-param logic. For that reason, the `int(32)` version is chosen (since the int(32) argument is an exact type match). However that looks like a lucky accident more than something intentional.

If we adjusted the compiler to consider a matching type more important than *param prefers* in such cases, then programs like `myInt32 + 1` don't compile, since it now becomes ambiguous which `+` to resolve to. But there might be another reasonable way to solve this issue.

Thanks for any thoughts.

**Comment by mppf** [comment]
>If we adjusted the compiler to consider a matching type more important than *param prefers* in such cases, then programs like `myInt32 + 1` don't compile, since it now becomes ambiguous which `+` to resolve to. But there might be another reasonable way to solve this issue.

Ah but this issue has a solution that @bradcray mentioned in his earlier PR - count the number of coercions required and use that in determining more specific functions. Perhaps combining these changes will lead to something workable.

**Comment by mppf** [comment]
Here's another related example:

``` chapel
proc foo(low: int(?w), high: int(w), stride: int(w)) {
  writeln("nonparam w ", w);
}

proc foo(low: int(?w), high: int(w), param stride: int(w)) {
  writeln("paramv w ", w);
}

proc foo(low: int(?w), high: int(w), stride) {
  writeln("generic stride");
}

proc foo(low, high, stride) {
  writeln("generic");
}

foo( 0, 9:int(8), 1 );
```

For this one, considering param types earlier + counting coercions doesn't help. I think we just want the default-sized param to be less insistent on matching type than other sizes of param ints.

**Comment by mppf** [comment]
> >    uints or enums ... are pretty broken I think

> If it's easy for you to point me to some examples / commit messages / whatever, I'd like to understand if I can also fix these issues. I've had to make what I consider significant changes to the "param prefers" logic in order to get param int -> real(32) coercions working...

Ah, there are a bunch in STATUS.devel. I see a lot of enum issues but not so many uint issues. (in fact the only uint issue I see is that enums don't implicitly convert to uints).

**Comment by mppf** [comment]
Here's another difficult example:
``` chapel
proc foo(x: int(8)) {
  writeln("int8 version of foo called");
}


proc foo(x: int) {
  writeln("int version of foo called");
}


foo(8:int(16));
```

On master this resolves to the int version, but it's easy for improved rules to cause it to resolve to the int(8) version. On master, a param that is cast to another size (such as int(16)) doesn't just "param prefer" to resolve to an `int` argument, it actually can't resolve to the smaller size at all, because of the way fits_in_int is written. So I can see these strategies:
  a. don't allow a param int(16) to pass to an int(8) even if it fits
  b. allow a param int(16) to pass to an int(8) but param prefer to pass to int(t) with t>=16 if available
  c. allow a param int(16) to pass to an int(8) and prefer it over an int or int(32) argument

@bradcray - any immediate reaction?

Maybe we choose `b` on the theory that param dispatch shouldn't depend over-much on the particular value of the param?
