### ISSUE TITLE
Why does chpldoc have trouble combining with verify?

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#5944]
### Summary of Problem
Back in 2015, Vass discovered that chpldoc does not work with `fVerify = true`.  Though `--verify` is not a flag that we allow on the chpldoc binary, it seems odd that verify would fail with chpldoc, considering chpldoc is not expected to modify the AST (though it does skip some code in pursuing its operations).  This happens even with the `--process-used-modules` flag thrown (relevant because that was the most recent change prior to the discovery of this bug, not because it was necessarily the cause of the error creeping in).

I have not investigated this problem, nor do I know which of the chpldoc tests were impacted (but this should be easy to determine).  We consider this to be a very low priority bug.

### Steps to Reproduce

Set `fVerify = true` in the compiler.  Run `start_test test/chpldoc`.  Look at what breaks.

### Configuration Information

- Output of `chpl --version`:
As early as Chapel 1.13.0, likely earlier.

**Comment by daviditen** [comment]
I took a short look at this issue, and it is happening because chpldoc doesn't parse the `String` module that sets up `dtString`, so `dtString` is just an empty type.  Then `--verify` tries to call `isAlive(type->symbol->defPoint)` on it, but `type->symbol` is `NULL` since it never got set up.

`--process-used-modules` actually does appear to fix the problem.

**Comment by lydia-duncan** [comment]
Cool, thanks for taking a look David!

**Comment by lydia-duncan** [comment]
The chpldoc binary has become even more thoroughly separated from the chpl binary at this point, so this is probably not worth keeping around.  Closing
