### ISSUE TITLE
Cannot build Chapel on Fedora Rawhide

### ISSUE THREAD

**Issue by russel** [chapel-lang/chapel#5965]
Fedora Rawhide uses GCC 7.0 which enforces many more of the C++11 and C++14 rules by default compared to GCC 6.3 (as used on Debian Sid). This means I am unable to build Chapel from a Git clone master on Fedora Rawhide. Since the build terminates on first error by default, the first problem is:
```
scopeResolve.cpp: In function ‘int computeNestedDepth(const char*, Type*)’:
scopeResolve.cpp:1773:55: error: ISO C++ forbids comparison between pointer and integer [-fpermissive]
     while (ct != NULL && ct->getField(name, false) == false) {
                                                       ^~~~~
```

On the matter of code style, doesn't `X == false` strike one as a "nasty code smell" anyway?

**Comment by noakesmichael** [comment]
Hi Russell,

I am sorry to see that the set of compilers that we test with
are missing an obvious error that 7.0 is correctly identifying.

It would be easy to push a fix for this error but I wonder how
many other issues are waiting to be exposed?

I’ll confer with others tomorrow on how we can best respond to this.

Mike Noakes



On Apr 5, 2017, at 11:09 PM, Russel Winder <notifications@github.com<mailto:notifications@github.com>> wrote:


Fedora Rawhide uses GCC 7.0 which enforces many more of the C++11 and C++14 rules by default compared to GCC 6.3 (as used on Debian Sid). This means I am unable to build Chapel from a Git clone master on Fedora Rawhide. Since the build terminates on first error by default, the first problem is:

scopeResolve.cpp: In function ‘int computeNestedDepth(const char*, Type*)’:
scopeResolve.cpp:1773:55: error: ISO C++ forbids comparison between pointer and integer [-fpermissive]
     while (ct != NULL && ct->getField(name, false) == false) {
                                                       ^~~~~


On the matter of code style, doesn't X == false strike one as a "nasty code smell" anyway?

**Comment by noakesmichael** [comment]
Russel,

I updated my local clang configuration to enable C++14 checks.
This generated the error mode you report but did not surface any
other issues.  I performed some local testing and then pushed an
update to master.

Thanks for reporting this and sorry for the hassle.

We will develop an additional testing configuration to ensure we
enforce default C++11/C++14 checks going forward.


With best regards,

Mike







On Apr 5, 2017, at 11:26 PM, Mike Noakes <mnoakes@cray.com<mailto:mnoakes@cray.com>> wrote:

Hi Russell,

I am sorry to see that the set of compilers that we test with
are missing an obvious error that 7.0 is correctly identifying.

It would be easy to push a fix for this error but I wonder how
many other issues are waiting to be exposed?

I’ll confer with others tomorrow on how we can best respond to this.

Mike Noakes



On Apr 5, 2017, at 11:09 PM, Russel Winder <notifications@github.com<mailto:notifications@github.com>> wrote:


Fedora Rawhide uses GCC 7.0 which enforces many more of the C++11 and C++14 rules by default compared to GCC 6.3 (as used on Debian Sid). This means I am unable to build Chapel from a Git clone master on Fedora Rawhide. Since the build terminates on first error by default, the first problem is:

scopeResolve.cpp: In function ‘int computeNestedDepth(const char*, Type*)’:
scopeResolve.cpp:1773:55: error: ISO C++ forbids comparison between pointer and integer [-fpermissive]
     while (ct != NULL && ct->getField(name, false) == false) {
                                                       ^~~~~


On the matter of code style, doesn't X == false strike one as a "nasty code smell" anyway?

**Comment by mppf** [comment]
I've verified that Chapel builds in quickstart and default mode in Fedora 26 with GCC 7. Mike's fix seems to resolve the comparison mismatch error, so I'm going to close the issue. @russel, please let us know if the issue persists on your system.

There are some warnings from the qthreads build but they don't stop the build. I'll include them here for reference, but these are definitely less critical. In particular, I think we can wait for Fedora 26 to actually be released to resolve them.

```
In file included from chapel/third-party/qthread/install/linux64-gnu-native-flat/include/qthread.h:1661:0,
                 from ../../../../include/tasks/qthreads/tasks-qthreads.h:34,
                 from ../../../../include/chpl-tasks.h:31,
                 from ../../../../include/chpl-comm.h:29,
                 from ../../../../include/chpl-mem.h:30,
                 from ../../../../include/qio/deque.h:43,
                 from ../../../../include/qio/qio-all.h:23,
                 from ../../../../include/chplio.h:30,
                 from ../../../../include/stdchplrt.h:36,
                 from re2-interface.cc:14:
chapel/third-party/qthread/install/linux64-gnu-native-flat/include/qthread/qthread.hpp: In function ‘int qthread_empty(const T*)’:
chapel/third-party/qthread/install/linux64-gnu-native-flat/include/qthread/qthread.hpp:17:65: warning: ignoring attributes in template argument ‘(bool)((sizeof (T) == sizeof (aligned_t)))’ [-Wignored-attributes]
 #define QTHREAD_STATIC_ASSERT(X) (void)sizeof(OnlyTrue<(bool)(X)>)
                                                                 ^
chapel/third-party/qthread/install/linux64-gnu-native-flat/include/qthread/qthread.hpp:18:34: note: in expansion of macro ‘QTHREAD_STATIC_ASSERT’
 #define QTHREAD_CHECKSIZE(X)     QTHREAD_STATIC_ASSERT(sizeof(X) == sizeof(aligned_t))
                                  ^~~~~~~~~~~~~~~~~~~~~
chapel/third-party/qthread/install/linux64-gnu-native-flat/include/qthread/qthread.hpp:35:5: note: in expansion of macro ‘QTHREAD_CHECKSIZE’
     QTHREAD_CHECKSIZE(T);
     ^~~~~~~~~~~~~~~~~
```

**Comment by russel** [comment]
I got a complete build on Rawhide (currently Fedora 27) this morning. :-)

Are there people building Chapel from source who do not have a C++14 compliant compiler so that it could be made the default compliance level?

**Comment by mppf** [comment]
@russel - we're not even requiring C++11 for our code base yet. Some HPC systems can have a long life with old compilers. And there are a variety of HPC compilers that won't implement C++14 as quickly as clang and gcc.

At the same time, as I understand, we do test with some compilers that enable C++14 by default (in particular, with GCC 6). For some reason, GCC 6 with C++14 by default didn't raise this error.

It may be that requiring C++14 would be a step forward, but I think we need to get to requiring C++11 first. That is less of a stretch for us since some of our (optional) third-party dependencies require C++ (such as LLVM and I think RE2).
