### ISSUE TITLE
Path library - add support for normCase

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#6013]
Back in late 2014, we started undertaking the implementation of the FileSystem and Path libraries, with input from the user community ([start of thread](https://sourceforge.net/p/chapel/mailman/message/32800541/), [mail with updated proposal after feedback](https://sourceforge.net/p/chapel/mailman/message/32902710/)) Much progress has been made in getting the support onto master, but 10 functions still remain unimplemented due to the youth of our string implementation at the time.  With our string implementation in a good state, these functions should be returned to and implemented

This issue is for the function `normCase`.

Here is the expected documentation and declaration:
```chapel
/* For case-insensitive file systems, alters path to lowercase.  On Windows,
   additionally converts forward slashes to back-slashes.  For case-sensitive
   file systems, this will return the path unaltered and generate a warning
   to the user that the action could not be taken.

   :arg name: a potential path to convert to lowercase if that would not alter
             the meaning of the path.
   :type name: `string`

   :return: the path in a normalized form, if necessary
   :rtype: `string`
*/
proc normCase(name: string): string;
```

**Comment by lydia-duncan** [comment]
Tests will need to be written for this feature

**Comment by victor-ludorum** [comment]
Hello @lydia-duncan  I have worked on this issue and made a **normCase function**  . 
``
    proc normCase(name: string): string {
   
      // Variable "result" stores the final
	 // result .
      var result: string = "";
       
	   for i in 1..name.length {
	      
		  // variable "str" stores 
		  // character of string name.
		  
		  var str: string = name[i];
		  
		  /*
		  Replacing all '/' forward slashes 
		  with the back-slashes '\' .
		  */
		  
		  if (str == "/") {
		     result += '\\';
		  }
		  
		  /*
		  Checking if character is Capital .
		  In the variable "asc" we store the ascii value
                  of str . As it is capital so to change it into 
                  small letter we will add 32 to the asc value .
                  In the variable "stri" we store the string
                  resulting from the modified ascii value which
                  is basically the small letter of the capital
                  letter .		  
		  */
		  
		  else if (str.isUpper()) {
		         var asc: uint(8) = ascii(str);
			 var asciimodified: uint(8) = asc + 32; 
			 var stri: string = asciiToString(asciimodified);
			 result += stri;
		  }  
		  
		  // If str is small letter then 
		  // nothing to change .
		  else {
		       result += str;
		  }
	    }
	      return result ;
    }
``
Kindly check it and suggest the necessary changes that should be done .

**Comment by victor-ludorum** [comment]
@lydia-duncan  Thanks for your suggestion 😊 I will use **toLower()** to ease this task . But I have problem in checking **case-insensitive or case-sensitive file system** . Can you suggest some method or any procedure to check the **case-insensitive or case-sensitive** file system

**Comment by lydia-duncan** [comment]
This something you'll have to research yourself, as it doesn't look like we have a solution at the Chapel code level.  My suggestion is to look into how to determine this in C and add some extern functions similar to the ones added for [the chdir implementation, for instance](https://github.com/chapel-lang/chapel/blob/master/modules/standard/FileSystem.chpl#L155) (look up the code added to support chdir, especially that which was added to the runtime directory.  You will likely not want to put it in the same source file, but the strategy for adding it should be similar).

**Comment by victor-ludorum** [comment]
Okay @lydia-duncan I will do as you have suggested !!

**Comment by dlongnecke-cray** [comment]
As has been mentioned before by @lydia-duncan and @mppf, in order to implement the behavior of normCase correctly two things are needed.

- Determine whether or not a file system is case sensitive.
- Get the current platform.

For the first, a silly solution would be to create a temporary file with (lower/upper)case letters, invert the case, and check to see if the file still exists. This could be done relatively easily, but I'm not entirely sure if all the edge cases are covered. (I could use the C function mktemp if a wrapper is already written for it, or write one myself).

A more convoluted solution might be to introduce C code which wraps around statfs (if it doesn't exist already), and to switch based off the file system type. I'm not sure how comprehensive this would be. It would also involve a nontrivial amount of platform specific code.

As for the issue of platform, @bradcray brought up the ability to fetch CHPL_TARGET_PLATFORM as a param string in #8146.

I've also got no clue about how a multi-locale environment (possibly with multiple file systems?) might further constrain the semantics.

Any thoughts about best approach?

**Comment by mppf** [comment]
@dlongnecke-cray - neither checking CHPL_TARGET_PLATFORM nor creating a temporary file in /tmp (or with mktemp generally) will work reliably, because a system can have many filesystems mounted and some (but not all) of these can be case insensitive.

> A more convoluted solution might be to introduce C code which wraps around statfs (if it doesn't exist already), and to switch based off the file system type. I'm not sure how comprehensive this would be. It would also involve a nontrivial amount of platform specific code.

In fact we already have such C code here:
https://github.com/chapel-lang/chapel/blob/0ef6753d88c9f46e196a723db6b74d238e7f5276/runtime/src/qio/sys.c#L667

This C code is currently called from the C code in the runtime implementing I/O operations but it isn't currently available from Chapel module code. I think it'd be reasonable to make it available in the Sys module though.

In my view, there are two challenges with statfs:
 1. Identify case sensitive vs case insensitive filesystems from the call. For example, HFS can be case sensitive or insensitive, but it's not obvious to me how to see this from the statfs result.
 2. In Python, this is a Path routine, which implies that it operates on the path without opening any files. It seems even calling statfs would be more than a path routine would normally do.

What does Python do? On windows, it just returns lower case:

https://github.com/python/cpython/blob/18618e652c56e61a134e596b315a13c7cb997a89/Lib/ntpath.py#L44-L58

and everywhere else, it doesn't change the case at all.

This strategy seems odd/wrong to me since a Windows system can in principle mount a case-sensitive FS. Or at least a Linux system can mount a case-insensitive filesystem like FAT32.

Here's another thing:

https://stackoverflow.com/questions/45878188/checking-case-sensitive-file-name-hfs

This recommends using `fcntl(fd, F_GETPATH, buffer)` to get the canonical file name. That can only be done for a file that exists, though. This operation is already available to Chapel users (but may not work on all platforms). For example, on my Mac OS X system, I created a file called test.txt and then ran this program:
``` chapel
var f = open("TeSt.txt", iomode.r);
writeln(f.path);
```

and it output test.txt.

So, my advice here? Simply do not implement `normCase` and instead recommend an alternative way to handle case insensitivity, such as the `f.path` example above.

**Comment by dlongnecke-cray** [comment]
Thanks for such a detailed and eye opening response! 

I'll put ``normCase`` on the backburner for now and focus on implementing the rest of the procedures in the Path library.

Should I go ahead and close this issue?

**Comment by mppf** [comment]
Closing the issue sounds good to me.
