### ISSUE TITLE
Function to turn an integer into an ascii string

### ISSUE THREAD

**Issue by daviditen** [chapel-lang/chapel#6047]
I would like a procedure that does the reverse of the [ascii(a:string)](http://chapel.cray.com/docs/latest/builtins/internal/String.html?highlight=ascii#String.ascii) procedure.  I'd like it to accept an integral value (only uint(8)?), and return a string containing the character that value represents in ascii.

In my desire for this, I recently added a procedure to modules/internal/String.chpl:

```
/*
   :returns: A string with the single character with the ASCII value `i`.
*/
inline proc asciiToString(i: uint(8)) {
  var buffer = chpl_here_alloc(2, CHPL_RT_MD_STR_COPY_DATA): bufferType;
  buffer[0] = i;
  buffer[1] = 0;
  var s = new string(buffer, 1, 2, owned=true, needToCopy=false);
  return s;
}
```

Some questions:

1. Is a procedure that does the opposite of `ascii` desirable?
2. Is the functionality of the procedure above acceptable?  If not, what needs to change?
3. Is the name "asciiToString" good, acceptable, bad?  Would anybody like to suggest a better name?

I think that the answer to question 1. is "yes", and I'm open to making changes to address questions 2. and 3.

**Comment by ronawho** [comment]
Just a pointer to pythons equivalent: https://docs.python.org/3/library/functions.html#chr

Note that it's a builtin, not part of the string library.  They have `chr()`, `ord()`, as well as `unichr()`

There's also a bunch of related internal threads (some of them saying "The 'ascii' method should get tossed into some deep dark hole. Or just deprecated."). Here's the list I found:

 - "ascii() -- int(8) or uint(8)" 
 - "Re: byte-oriented string methods" 
 - "the ascii function"
 - "Strings API proposal"

I don't know enough about strings to have an opinion one way or the other hear. Just wanted to give a pointer to what python does (since our string library was heavily base on python) and provide pointers to threads that that discussed something like asciiToString as well as possibly removing ascii. Also note that there is a source comment above ascii saying `TODO: replace with ordinal()` so presuambly aciiToString should really be `fromOrdinal()`?

**Comment by ben-albrecht** [comment]
> 1. Is a procedure that does the opposite of ascii desirable?

Yes.

> 2. Is the functionality of the procedure above acceptable? If not, what needs to change?

No strong opinions here. Looks fine as far as I can tell.

> 3. Is the name "asciiToString" good, acceptable, bad? Would anybody like to suggest a better name?

It's not clear to me how this naming scheme will work with other encodings that we may support for this functionality down the road.. e.g. would we use `unicodeToString()` and `unicode()` for unicode encoding? This makes me wonder whether or not the encoding should be an argument, if the function should be a method on the string, or something else.. For reference, python distinguishes the string encoding with the string-prefix notation. It would be valuable to survey some other established languages to see what has been done and try to determine what has worked well and what hasn't.

@ronawho - note that `unichr()` is deprecated in Python 3, and `chr()` supports unicode and ascii. [See the docs](https://docs.python.org/3.6/library/functions.html#chr) for more info.

**Comment by bradcray** [comment]
Although we eventually intend to support utf8 strings and make them the default, I suspect that ascii-based computation will continue to be important in certain circles where performance is key due to its support for quick random access and historical context.  For that reason, I'm not part of the "ascii should be thrown into a hole and forgotten" crowd, though I'm more interested in the capability than the specifics/naming of our current routine.

I'd be inclined to push the larger "ascii vs. utf8 vs encoding x" questions into their own issue and suggest that we just treat this one as "in a world where we have ascii(), should we also have David's routine?"  Put another way, while I'd like to come to conclusions on the broader encoding design questions, I don't think we should let our recent immobility on those issues prevent improvements to what we have today.  Unless we think we're going to solve the encoding questions so quickly that it represents wasted effort (though since this is already implemented, its too late to avoid that cost).

(Don't interpret this as lack of interest in solving the encoding questions, or lack of belief that we could do so quickly if we set our minds to it...  more a vote not to have that issue cripple other ones).

**Comment by mppf** [comment]
I've often had (I think?) a different opinion from others about the encoding questions. Even with a future string library that fully supports Unicode, I think it's reasonable to have some methods that work only with the ASCII-subset of Unicode. So I don't see any problem with asciiToString or ascii methods.

As we make strings support Unicode more generally, I think we will have other, more general purpose names for such things, more like `ordinal` or `unichr` or whatever names we pick. But even in that world, it can still be useful to have versions that only work with ASCII characters. I would expect that the ASCII versions would be used less and less over time.

**Comment by ben-albrecht** [comment]
@mppf - that's a fair point. I just wanted to make sure this naming convention was mindful of future unicode support. In that context, I'm not opposed to functions specialized to ascii encoding. In terms of the available names, I don't have a strong opinion at the moment.

**Comment by mppf** [comment]
@dmk42 - I just noticed this issue and wanted to point it out to you. I'm not certain, but I think resolving it overlaps with your other efforts on strings (maybe it is already done?).

**Comment by dmk42** [comment]
@mppf - Thanks.  @daviditen - I think this issue should be closed because `asciiToString()` was accepted and became part of String.chpl quite a while back.

During one of the March deep dives, we decided to deprecate `ascii()` and `asciiToString()` in favor of `string.byte()` and `codepointToString()`.

**Comment by daviditen** [comment]
@dmk42 closing this works for me.
