### ISSUE TITLE
Support `make install`

### ISSUE THREAD

**Issue by ben-albrecht** [chapel-lang/chapel#6050]
It would be nice to support `make install`. It has been requested by Chapel users and may be necessary for releasing Chapel in some packaging ecosystems, such as Debian.

A proposed solution (or at least, a first step) has been introduced in #6036 

## Design questions

Here are few open questions as to what `make install` would actually do -- more questions and hopefully  answers to follow.

- What actually needs to be installed separably?
    - `lib/`
    - `runtime/include`
    - `bin/`
    - `modules/`
    - `util/`
    - ...
- Should we support a standardized `configure` setup script, with the `--prefix` flag to change install destinations?
    - Would the prefix option effectively install all the necessary files into a new `CHPL_HOME`?
- How to handle stuff under `third-party/`? Should it be able to be installed globally?
- How should standard and internal modules be installed?
- Is installing main.o a problem (vs having something in a .a file)?
- Should a `make install` install all built configurations, or just the currently selected one?

**Comment by mppf** [comment]
My take on the answers:
* What actually needs to be installed separably?

  * we need to install lib, runtime/include to `/usr/lib/chapel` (or something along those lines)
  * we need to install bin stuff (`chpl`, `chpldoc`) to `/usr/bin`
  * we need to install everything else to `/usr/share/chapel` (or something along those lines)

* Should we support a standardized configure setup script, with the --prefix flag to change install destinations? 
  * I think it's acceptable to set PREFIX during with a Make variable for Make install.
   * I think we could create a standardized configure script to make the building process of Chapel less "special"
   * I think a configure script would amount to creating a chplconfig file

* How to handle stuff under third-party/? Should it be able to be installed globally?
  * I don't think we need to support global installs of things in third-party
  * We should attempt to work with system installs of these when possible

* How should standard and internal modules be installed?
  * I think these go in to `/usr/share/chapel/modules`
  * A wrinkle is the generated SysCTypes.chpl. I think it's acceptable to install that in `/usr/share/chapel` but it technically depends on which C compiler is selected. We already encode the C compiler in the path to it, e.g. `modules/stardard/gen/darwin-clang/SysCTypes.chpl`. Since it's not architecture-specific, I think it's OK for it to be in `/usr/share`.

* Is installing main.o a problem (vs having something in a .a file)?
  * I don't see a problem with installing a main.o
  * Chapel will be configured to work with a particular C compiler (clang, for LLVM)
  * So I'm not too concerned about installing an object file for that C compiler...
  * But I might be missing some issue

* Should a make install install all built configurations, or just the currently selected one?
  * I think all built configs

**Comment by mppf** [comment]
I'm closing this issue because PR #6036 fixed it, at least initially.
I'll make a new issue with make-install TODOs.
