### ISSUE TITLE
extra files in release tarball

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#6124]
Here are some files that don't seem to me to belong in the release tarball but that are in 1.15:

 * examples/ *.notest *.good and other testing files. I don't think these make sense to end users, and with the Debian package at least, we get package warnings if we install 0-length "documentation" files.
 * util/chplenv/template
 
I intend to update this issue if I find others.

**Comment by bradcray** [comment]
The examples files designed for the testing system have intentionally been included in the release in the past in order to (a) permit users to run the Chapel testing system on the examples/ directory (for example, I think 'make check' does this?) and (b) give some indication of what expected output for the tests is (under the constraints of the .compopts, .execopts, etc. if present).  Would a workaround for the Debian package be to make these not be 0-length files?  (e.g., in a .notest, I usually put an explanation for why the corresponding .chpl file is not intended to be tested).

I'm completely unfamiliar with the role of util/chplenv/template and can't quite guess at its purpose reading its name either...  Looks like @ben-albrecht has touched it recently.  Oh, is the idea that you'll make a copy of this file when you want to add the next chpl_foo.py file?  I guess while this file may not be necessary to the release, I don't see a problem with including it in the release either (i.e., it's in a directory that users won't be looking through much anyway, doesn't add much size, might be useful if someone has to customize the release they downloaded in some way, ...?).  Part of my motivation for keeping it around is that as much as possible I like to include entire directories in the release tarball -- the less we have to pick out or remove singleton files, the better.

**Comment by mppf** [comment]
re. the testing files, at least at present the Debian package doesn't include the testing infrastructure. But maybe we should fix that. (Add it to the long list). Anyway, I think putting a comment in all of the 0-length ones would be a good plan going forward.

re. util/chplenv/template I'd personally just remove it because the existing chplenv scripts seem to cover the same territory (for me at least). I also don't have a real problem leaving it in the release if it's not worth nit-picking about.

**Comment by ben-albrecht** [comment]
re. the testing files, 

> (a)  permit users to run the Chapel testing system on the examples/ directory (for example, I think 'make check' does this?)

I'm not sure if you were implying this, but to be clear: `make check` does not utilize the `start_test` infrastructure as of #2487

On one hand, removing the testing meta-files would clean up the `examples/` directory and make it easier for users to find what they're there for, i.e. they will only find example programs of Chapel. On the other hand, it serves as a good example of the test infrastructure. Of those two, I favor former as being the larger benefit for users working out of the release directory, whereas the latter might be accomplished via developer documentation or working out of the git repository.


re. util/chplenv/template, I'm also in favor of removing it, but if someone felt strongly about keeping it, I'd argue that it should be maintained as a code-block in some developer documentation rather a sibling file to other `chplenv` scripts in the release.

**Comment by bradcray** [comment]
I feel like this issue got a tepid response and feels low priority to me, so  I'm going to close it for now, but if @mppf, @ben-albrecht, or others feel differently, please feel free to reopen.
