### ISSUE TITLE
Cannot access module-scope function from shadowed record-scope method

### ISSUE THREAD

**Issue by ben-albrecht** [chapel-lang/chapel#6275]
### Summary of Problem

Due to scoping rules in Chapel, the only way to access a function or variable
that shares the same name as a method or field in a record/class is to specify the intended scope with the module prefix. The future linked below demonstrates that this does not work for
methods shadowing functions.

Confusingly, the compiler emits the error:

    use of 'A' before encountering its definition, type unknown

despite the A module being accessible elsewhere within the method.

For what it's worth, the shadowed variable/field case works as expected.

### Steps to Reproduce

**Associated Future Test(s):**
[`test/visibility/shadow.chpl`](
           https://github.com/chapel-lang/chapel/blob/master/test/visibility/shadow.chpl
          ) #6274

**Comment by lydia-duncan** [comment]
I believe this is because we are recognizing that the function is a method on a class in the closest scope with that function defined, and so think that A could be the name of a local instance of that type.  However, A is a module, not an instance, so it isn't valid to look for it as if it is an instance.

**Comment by noakesmichael** [comment]
This issue was resolved by PR 6279.  The future created in PR #6274 was retired.
