### ISSUE TITLE
Error handling design changes

### ISSUE THREAD

**Issue by psahabu** [chapel-lang/chapel#6286]
## Context

The community has asked that error handling be made more ergonomic and legible. At the same time, we want to maintain control flow clarity like Swift.

### unhandled throwing calls in throwing fns
Users want the ability to call a throwing function from another throwing function without a `try`, even in strict mode. While this is appealing, it is also against the Swift philosophy of marking every throwing call. There are a few possible ways to handle this contradiction:

- _no action_: continue raising an error for such calls in strict mode
- _proposed only_: permit such calls in strict mode, assert `throws` as a similar contract to `try`
- _proposed + strict warnings_: permit such calls in strict mode, but have strict mode emit warnings
- _proposed + separate warnings_: permit such calls in strict mode, but have another flag emit warnings for such calls
- _proposed + third mode_: permit such calls in strict mode, but add a pedantic mode similar to our current strict mode

### `try!`/`catch`
In the current design, we support the following pattern:

```
try! {
  mayThrowAnError();
} catch err: SpecificError {
  logSpecificError(err);
} // halt if uncaught
```

My concern is that the `halt()` is too subtle and unintuitive here, but @mppf thinks this is a non-issue. Possible actions:

- _no action_: allow this pattern
- _disallow catch with_ `try!`: may be used with single statements or blocks, but cannot use `catch`

### throwing beyond the top level
Here is a pattern that is not captured in the current design:

```
proc main() throws {
  try {
    mayThrowAnError();
  }
  writeln("now what?");
}
```

If an error is thrown from the top level, what should happen?

- halt: `halt: ...`
- continue: `now what?`

**Comment by bradcray** [comment]
[Meta: Each of these sub-topics seems as though it may deserve to be its own issue, as each might generate a decent amount of discussion that'll be tangled together due to GitHub's linear comment system]

> throwing beyond the top level

I think if main() throws, it should result in a halt, similar to a ``try!``

Alternatively, I could imagine saying that main() may not throw and that its try's must be completely locked down -- e.g., you must use ``try!`` or must have a catch-all case (and the compiler will complain if it's not airtight).  That said, I'm not certain that forcing the user to do this (in which case they would likely put in halts themselves) is that much better than having the compiler put an implicit ``try!`` around a throwing main().

**Comment by mppf** [comment]
My two cents:
 * separate error control flag for insisting that every throwing call is marked
 * allow try! { } catch
 * require main to not throw in strict mode, but in other modes it works as though called by `try! main`

**Comment by vasslitvinov** [comment]
* I do not see that marking every throwing call with `try` is all that valuable. In the past and recently we have striven to simplify the programmer's job. For example, we detect whether an array formal is ref or const-ref automatically, rather than forcing the user to declare that. Therefore I prefer allowing unmarked calls within a throwing function.

* allow try! { } catch

* I do not see the harm of allowing main() to throw. I expect this to be a common case during rapid prototyping. Why should we burden the user just because their indexing into an array can be out of bounds?

**Comment by psahabu** [comment]
Alright, it's been quite awhile so I'm comfortable coming to a conclusion here:

- separate `pedantic-errors` compiler flag
- allow `try! / catch`
- do not allow `main` to throw in strict mode, allow it in `default` mode which will cause a `halt()`
