### ISSUE TITLE
Standard Error hierarchy

### ISSUE THREAD

**Issue by psahabu** [chapel-lang/chapel#6297]
Including a standard `Error` hierarchy will help users take advantage of error handling out of the box without needing to create their own. Here's an incomplete starting point, taken from Java, Python, and the discussions that we've had so far. Please feel free to suggest new errors, errors to remove, renames, and reorganizations.

(Note: All of these will be appended with 'Error' when they are implemented.)

IO
  - File
    - EOF
    - FileNotFound
    - FileExists
    - Permission
  - HTTP
    - MalformedURL
    - UnknownHost

System
  - Buffer
  - Memory
    - OOM
  - Network
    - NodeNotFound
    - NetworkTimeout
  - Task
    - TaskSpawn
    - TaskTimeout

Runtime
  - Arithmetic
    - DivideByZero
    - FloatingPoint
    - Overflow
  - IllegalCast
  - IllegalArgument
  - IllegalState
  - NoSuchElement
  - NilPointer
  - NilThrownError
  - OutOfBounds

UserError
  - a distinct general use error

**Comment by bradcray** [comment]
While I appreciate this effort to start defining an error hierarchy, it seems premature/unnecessary to me to try and define it to this level of detail at present.  Instead, I'd suggest starting by focusing on just the top level of the hierarchy for now and then filling things in beneath it as we start actually introducing the errors rather than trying to anticipate all errors that we might need a priori.  Specifically, some of the above seem as though we might not want to support them as errors (too heavyweight for a throw?) while I can easily imagine not anticipating others that we might need until we start trying to remove halt()s from the standard/internal modules.

Another top-level decision that could be made here without trying to anticipate every error would be to agree on a capitalization convention.  I.e., is everyone good with InitialCapsCamelCaseError?

**Comment by mppf** [comment]
I agree with Brad. I'm immediately distracted by questions like "What is a BufferError?" and "Can we support DivideByZero through errors without ruining performance?" and "There are quite a few other IO errors not on your list...".

Instead, let's change the description of the issue to introduce each top-level category with a sentence or two describing what would go in it and possibly a few for-instance cases.

On that point, it's not immediately obvious to me where the boundary lies between IO errors, Runtime errors, and System errors. For example, I could imagine thinking of File Not Found as a System error, since it has a corresponding POSIX error code and can be returned from system calls. But since the IO system is implemented partially in the Runtime, maybe File Not Found is a Runtime error?

Thus I think each top-level category needs some justification.

What do I think the top-level categories should be?

 * IO because I/O errors are common and make sense to work with error handling
 * UserError for a general user-defined error (But couldn't users also extend from an IO error?) And, I don't like the name, because it implies the "user" made an error, rather than that it's just not a Chapel-system-defined error. It could be GeneralError, or OtherError, or PackageError, or StringError, or ?
 * Things like nil pointer / out of bounds I don't expect we'll want to have errors for at all. Nonetheless if we did I'd put them in to a bucket of *language*-level errors.
 * Failure in task spawn or out-of-memory errors could conceivably be handled by the error mechanism (but I expect we'll choose to fail catastrophically instead, at least at first). I'd be tempted to call those "Runtime" errors but perhaps it would be better to simply describe them as Resource errors. "System" errors is OK but doesn't really mean anything specific to me.

**Comment by vasslitvinov** [comment]
I would like to have a good justification for introducing UserError, or whatever its name may be.

Similarly, it is unclear to me that, say, nil pointer and out of bounds Error classes will benefit from a common superclass that's not Error itself.

Following Michael's lead, maybe it's worth distinguishing:
* errors that are user fault, and
* errors beyond user control (out of memory, stack overflow, ...)

I feel good about introducing the IOError class as a parent for various IO errors. Although, ironically, they probably do not fit cleanly in either of my above two categories. So maybe the categories are not right.

My understanding about Michael's `StringError` suggestion as a class that simply carries an error message, as a convenience for users doing rapid prototyping. Probably a better name is due. Or - we may allow `Error` itself to be constructed by users as in `throw new Error("stuff happened");`

**Comment by vasslitvinov** [comment]
InitialCapsCamelCaseError sounds good.

**Comment by cassella** [comment]
This made me think of the python PEP where they reorganized their OS
and IO Exception hierarchy (circa python 3.3):

https://www.python.org/dev/peps/pep-3151

My take on the Rationale section is that what motivated this big,
intrusive change was that writing correct, careful code took more
typing and cognitive load than it should have.


This proposal already avoids some of those drawbacks by providing
explicitly-named errors (e.g. `FileNotFoundError` vs. the old-style
Python's `OSError(errno=ENOENT)` and also `IOError(errno=ENOENT)`).


Beyond that, I think the lesson of the pep is that the layout of the
hierarchy directly impacts how easy it is to write careful, correct
code.  In python's case, it made conceptual sense for the `io` module
to throw `IOError`s and for the `os` module to throw `OSError`s.  But
it made it annoying for the user who wanted to write one short
`except` block to handle "all the exceptions I should be handling
here".

And I think it'll be much harder to surface those sorts of issues just
by looking at the proposed hierarchies, vs actually working through
common use cases to see the impact.

**Comment by mppf** [comment]
@cassella - thanks for pointing that out. I think it would be reasonable to try to duplicate Python's error hierarchy and names. Of course, that doesn't answer many of the questions about Chapel-specific errors.

**Comment by mppf** [comment]
Here is what I interpret as the useful-to-us part of Python's PE 3151.
```
+-- BlockingIOError        EAGAIN, EALREADY, EWOULDBLOCK, EINPROGRESS
+-- ChildProcessError                                          ECHILD
+-- ConnectionError
    +-- BrokenPipeError                              EPIPE, ESHUTDOWN
    +-- ConnectionAbortedError                           ECONNABORTED
    +-- ConnectionRefusedError                           ECONNREFUSED
    +-- ConnectionResetError                               ECONNRESET
+-- FileExistsError                                            EEXIST
+-- FileNotFoundError                                          ENOENT
+-- InterruptedError                                            EINTR
+-- IsADirectoryError                                          EISDIR
+-- NotADirectoryError                                        ENOTDIR
+-- PermissionError                                     EACCES, EPERM
+-- ProcessLookupError                                          ESRCH
+-- TimeoutError                                            ETIMEDOUT
```

Note that in Python, they chose to make all of these subclasses of OSError. We could do the same, but we're also going to have some other things I'd call I/O errors rather than OS errors, such as a the required format not being found (e.g. trying to read an integer but see only "a").

**Comment by gbtitus** [comment]
A couple of notes, one major, one minor.

The major one: I don't think we should have a category called "runtime".  Whether a capability is provided by (or an error originates in) the runtime or some other part of the SW stack is an implementation decision, not a functional one.  Nor do I think "I/O" should be a top-level category.  I'm a leery of "System" also.  If it does stay it seems like it should contain the OS error codes but I'm disinclined to show those to the user; at some point as an error traverses up the SW stack to user code those OS error codes should be translated into something more abstract.  I'd do something like this as a hierarchy:

- ChapelBase
  - Language
    - NilPointer
    - OutOfBounds
    - ...
  - IO
    - File
    - HTTP
    - ...
  - Memory
  - Task
  - Comm
  - Internal
  - System
- User

The minor one: Let's not call out-of-memory "OOM".  OOM has a specific Linux meaning and when that thing happens one can't do anything about it.  Let's use NoMoreMemory for the catchable Chapel error.

**Comment by mppf** [comment]
See https://docs.python.org/3/library/exceptions.html#os-exceptions for a complete list of what Python ended up with. At the moment, Preston and I are planning to directly implement these as subclasses of SystemError in Chapel, based solely upon the error number. That basically amounts to - besides creating the classes - creating one or more factory methods for SystemError. (In other words, these are extensions of SystemError and could generally come up because system calls return a variety of error numbers).

**Comment by mppf** [comment]
As of today, the consensus plan is to follow through with subclasses of SystemError that are inspired by the Python subclasses of OSError.

**Comment by mppf** [comment]
PR #7218 did this - so I'm closing the issue.
