### ISSUE TITLE
min(string) and catch-all min/max(type) ?

### ISSUE THREAD

**Issue by vasslitvinov** [chapel-lang/chapel#6312]
How about we implement `min(string)` to return an empty string?

How about we implement `max(string)` to report compilerError("there isn't one")?

Further, given that min/max on a type are language-defined operations (I think), the compiler should generally report an intelligent error whenever there is an incorrect use of them. We could implement it as a catch-all `proc min(type t)` and same for `max`.

**Comment by lydia-duncan** [comment]
My only disagreement is that I don't think min(string) is meaningful, so would have it also report an error or something

**Comment by ben-albrecht** [comment]
> How about we implement min(string) to return an empty string?

Could you provide some cases where this might be useful? I know that this emerged from the bug reported in #6311, but I believe the `min(string)` shouldn't even be getting called, as pointed out in that issue.


> Further, given that min/max on a type are language-defined operations (I think), the compiler should generally report an intelligent error whenever there is an incorrect use of them. We could implement it as a catch-all proc min(type t) and same for max.

This seems nice. In the long term, it'd be ideal for our compiler to emit a more useful message for these types of errors, so that this pattern is no longer necessary in most cases.

**Comment by bradcray** [comment]
@aconsroe-hpe connected the dots between this issue and #19108.  I'd be inclined to close this issue because nobody seems particularly in favor of it, and if the main goal is to support minloc/maxloc on arrays whose idxType is string, it feels like a point solution that's not generalizable to other types that don't support min/max.  @vasslitvinov / @ben-albrecht / @lydia-duncan , any of you want to argue that we keep it open?

**Comment by ben-albrecht** [comment]
since you don't get notifications for comment reactions: I support closing this in favor of #19108

**Comment by vasslitvinov** [comment]
This issue includes a suggestion to have min/max(type t) report an explicit error for those types that do not define them.

If this is of value, let us keep this issue open.

**Comment by bradcray** [comment]
I generally agree with BenA above, that the more worthwhile investment would be to make the compiler's errors better when it can't resolve something (which I think we've already done some of since 2017?) so that every time someone adds a new function `foo(x: t)` they didn't feel compelled to also add `foo(x)` to generate an error because the compiler will do a good enough job on its own.  Not to say that it isn't reasonable to add such error overloads in some particularly common or confusing cases, but I don't think we should get into the business of opening a GitHub issue for every function that doesn't have one.

Today the error for max() on a bad type is:

```chapel
testit.chpl:1: error: unresolved call 'max(type string)'
$CHPL_HOME/modules/internal/ChapelTuple.chpl:393: note: this candidate did not match: max(type t)
$CHPL_HOME/modules/internal/ChapelTuple.chpl:393: note: because where clause evaluated to false
testit.chpl:1: note: other candidates are:
$CHPL_HOME/modules/standard/Types.chpl:734: note:   max(type t)
$CHPL_HOME/modules/standard/Types.chpl:737: note:   max(type t)
note: and 22 other candidates, use --print-all-candidates to see them
```

which is not bad, though it could arguably be made better by not pointing to internal modules, having the notes in the standard modules include the where clauses that make them ineligible, etc.

I won't go so far as to say that the warning proposed here is definitely not of value, but given how easy it is to implement, how long this issue's been open without implementing it, how little the feature has been clamored for or upvoted since this issue has been opened, it doesn't feel like the kind of thing that warrants keeping an issue open for to me.  If it were truly a pain in someone's side, they'd fix it.  If not, it doesn't matter.  And in either case, it's not as though someday we'll refer back to this issue and think "thank goodness we had an issue reminding us of this important task."

If you disagree and really want to keep it open, though, perhaps you could at least update it to remove the part about min(string) since—as you say—it describes two suggestions, and I think that one's failed to garner any support.
