### ISSUE TITLE
Runtime error after make on Linux Mint 

### ISSUE THREAD

**Issue by danindiana** [chapel-lang/chapel#6348]
Getting an error after make on Linux mint. Also occurs if I use sudo make. Was able to successfully install Chpl on Ubuntu 14.04 but Mint seems to be throwing an error. See below. 

```
[Info] Running minimal test script: $CHPL_HOME/util/test/checkChplInstall
[Info] Found executable chpl in /home/strelkov/Downloads/chapel-1.15.0/bin/linux64/chpl.
[Info] Found $CHPL_HOME directory: /home/strelkov/Downloads/chapel-1.15.0
[Info] /home/strelkov/.chpl does not exist. Creating it.
[Info] Temporary test job directory: /home/strelkov/.chpl/chapel-test-tsYHo
[Info] Compiling $CHPL_HOME/examples/hello6-taskpar-dist.chpl
[Fail] Test job failed to compile - Chapel is not installed correctly
[Fail] Compilation output:
/home/strelkov/Downloads/chapel-1.15.0/runtime/etc/Makefile.include:135: *** The runtime has not been built for this configuration. Check $CHPL_HOME/util/printchplenv and try rebuilding with 'make' from $CHPL_HOME.  Stop.
error: compiling generated source
Makefile:176: recipe for target 'check' failed
make: *** [check] Error 1
```

System info: 

```
 strelkov@strelkov-ThinkPad-X260
 MMMMMMMMMMMMMMMMMMMMMMMMMmds+.        OS: Mint 18.1 serena
 MMm----::-://////////////oymNMd+`     Kernel: x86_64 Linux 4.4.0-72-generic
 MMd      /++                -sNMd:    Uptime: 1h 54m
 MMNso/`  dMM    `.::-. .-::.` .hMN:   Packages: 3028
 ddddMMh  dMM   :hNMNMNhNMNMNh: `NMm   Shell: bash 4.3.48
     NMm  dMM  .NMN/-+MMM+-/NMN` dMM   Resolution: 1920x1080
     NMm  dMM  -MMm  `MMM   dMM. dMM   DE: Cinnamon 3.2.7
     NMm  dMM  -MMm  `MMM   dMM. dMM   WM: Muffin
     NMm  dMM  .mmd  `mmm   yMM. dMM   WM Theme: Mint-Y-Dark (Mint-X)
     NMm  dMM`  ..`   ...   ydm. dMM   GTK Theme: Mint-X [GTK2/3]
     hMM- +MMd/-------...-:sdds  dMM   Icon Theme: Adwaita
     -NMm- :hNMNNNmdddddddddy/`  dMM   Font: Noto Sans 10
      -dMNs-``-::::-------.``    dMM   CPU: Intel Core i5-6300U CPU @ 3GHz
       `/dMNmy+/:-------------:/yMMM   GPU: Mesa DRI Intel(R) HD Graphics 520 (Skylake GT2) 
          ./ydNMMMMMMMMMMMMMMMMMMMMM   RAM: 2882MiB / 7850MiB
             \.MMMMMMMMMMMMMMMMMMM    
```

**Comment by bradcray** [comment]
Hi @danindiana :

* Were there any errors prior to the one you quote above?  The following message typically suggests that there was a failure in building the runtime itself:

```
/home/strelkov/Downloads/chapel-1.15.0/runtime/etc/Makefile.include:135: *** The runtime has not
been built for this configuration. Check $CHPL_HOME/util/printchplenv and try rebuilding with 'make'
from $CHPL_HOME. Stop.
```

* Could you attach the output of ``$CHPL_HOME/util/printchplenv`` and of ``ls -R $CHPL_HOME/lib`` (or something similar that would show the recursive directory structure under ``$CHPL_HOME/lib/``?

**Comment by danindiana** [comment]
Thanks for the quick reply @bradcray 

strelkov@strelkov-ThinkPad-X260 ~/Downloads/chapel-1.15.0/util $ printchplenv
machine info: Linux strelkov-ThinkPad-X260 4.4.0-72-generic #93-Ubuntu SMP Fri Mar 31 14:07:41 UTC 2017 x86_64
CHPL_HOME: /home/strelkov/Downloads/chapel-1.15.0 *
script location: /home/strelkov/Downloads/chapel-1.15.0/util
CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: gnu
CHPL_TARGET_ARCH: native
CHPL_LOCALE_MODEL: flat
CHPL_COMM: none *
CHPL_TASKS: fifo *
CHPL_LAUNCHER: none
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: cstdlib *
CHPL_MAKE: make
CHPL_ATOMICS: intrinsics
CHPL_GMP: none *
CHPL_HWLOC: none
CHPL_REGEXP: none *
CHPL_WIDE_POINTERS: struct
CHPL_AUX_FILESYS: none

strelkov@strelkov-ThinkPad-X260 ~/Downloads $ ls -R chapel-1.15.0/lib
chapel-1.15.0/lib:
linux64

chapel-1.15.0/lib/linux64:
gnu

chapel-1.15.0/lib/linux64/gnu:
arch-native

chapel-1.15.0/lib/linux64/gnu/arch-native:
loc-flat

chapel-1.15.0/lib/linux64/gnu/arch-native/loc-flat:
comm-none

chapel-1.15.0/lib/linux64/gnu/arch-native/loc-flat/comm-none:
tasks-qthreads

chapel-1.15.0/lib/linux64/gnu/arch-native/loc-flat/comm-none/tasks-qthreads:
tmr-generic

chapel-1.15.0/lib/linux64/gnu/arch-native/loc-flat/comm-none/tasks-qthreads/tmr-generic:
unwind-none

chapel-1.15.0/lib/linux64/gnu/arch-native/loc-flat/comm-none/tasks-qthreads/tmr-generic/unwind-none:
mem-jemalloc

chapel-1.15.0/lib/linux64/gnu/arch-native/loc-flat/comm-none/tasks-qthreads/tmr-generic/unwind-none/mem-jemalloc:
atomics-intrinsics

chapel-1.15.0/lib/linux64/gnu/arch-native/loc-flat/comm-none/tasks-qthreads/tmr-generic/unwind-none/mem-jemalloc/atomics-intrinsics:
gmp

chapel-1.15.0/lib/linux64/gnu/arch-native/loc-flat/comm-none/tasks-qthreads/tmr-generic/unwind-none/mem-jemalloc/atomics-intrinsics/gmp:
hwloc

chapel-1.15.0/lib/linux64/gnu/arch-native/loc-flat/comm-none/tasks-qthreads/tmr-generic/unwind-none/mem-jemalloc/atomics-intrinsics/gmp/hwloc:
re2

chapel-1.15.0/lib/linux64/gnu/arch-native/loc-flat/comm-none/tasks-qthreads/tmr-generic/unwind-none/mem-jemalloc/atomics-intrinsics/gmp/hwloc/re2:
wide-struct

chapel-1.15.0/lib/linux64/gnu/arch-native/loc-flat/comm-none/tasks-qthreads/tmr-generic/unwind-none/mem-jemalloc/atomics-intrinsics/gmp/hwloc/re2/wide-struct:
fs-none

chapel-1.15.0/lib/linux64/gnu/arch-native/loc-flat/comm-none/tasks-qthreads/tmr-generic/unwind-none/mem-jemalloc/atomics-intrinsics/gmp/hwloc/re2/wide-struct/fs-none:
chplconfig  libchpl.a  libchplmalloc.a  main.o

**Comment by bradcray** [comment]
We really need a tool to help debug these types of issues and print better error messages...

It appears to me that you built for ``CHPL_TASKS=qthreads`` (note the tasks-qthreads directory in your lib/ hierarchy) but are compiling for ``CHPL_TASKS=fifo``).  In our typical/preferred configuration, ``qthreads`` is the default, but when using the quickstart instructions / scripts, it sets it to ``fifo`` to get people up and running faster and more portably.

So a guess as to how this could have happened is that you built (``make``) then sourced the quickstart scipt, then compiled.  Re-make-ing as suggested by the error message should fix the issue.  Please let me know whether or not it does.

**Comment by bradcray** [comment]
> We really need a tool to help debug these types of issues and print better error messages...

Oh look, issue #5743 already asks for this... :)

**Comment by danindiana** [comment]
Thanks @bradcray I will give your recommendations a try and report back the results.

**Comment by danindiana** [comment]
When I run $: source util/quickstart/setchplenv.bash

strelkov@strelkov-ThinkPad-X260 ~/Downloads/chapel-1.15.0 $ source util/quickstart/setchplenv.bash
Setting CHPL_HOME to /home/strelkov/Downloads/chapel-1.15.0
Setting CHPL_HOST_PLATFORM to linux64
Updating PATH to include /home/strelkov/Downloads/chapel-1.15.0/bin/linux64
                     and /home/strelkov/Downloads/chapel-1.15.0/util
Updating MANPATH to include /home/strelkov/Downloads/chapel-1.15.0/man
Setting CHPL_COMM to none
Setting CHPL_TASKS to fifo
Setting CHPL_MEM to cstdlib
Setting CHPL_GMP to none
Setting CHPL_REGEXP to none
Setting CHPL_LLVM to none

Then I run $: sudo make 

and then with make check I get the same runtime error. Might be a dumb question, but how do I change the make to compile for CHPL_TASKS=qthreads?

**Comment by bradcray** [comment]
Huh, weird... So maybe we do have some sort of portability issue in our scripts or Makefiles.  I'll see if I can figure out a way to access a Mint VM to see if we can reproduce on our side...

Just to validate one other thing...  When your make is running (or re-run for that matter), you should see it go through a number of runtime directories that end up looking something like this (my output is for a re-make such that nothing needs to be rebuilt):

```
***** src/comm/ *****
***** src/comm/none/ *****
***** src/mem/ *****
***** src/mem/jemalloc/ *****
***** src/tasks/ *****
***** src/tasks/fifo/ *****
```

Do you see ``src/tasks/fifo`` in that output or ``src/tasks/qthreads``?

> how do I change the make to compile for CHPL_TASKS=qthreads?

Try setting the environment variable CHPL_TASKS to qthreads (e.g., ``export CHPL_TASKS=qthreads``) and then re-run ``make test``.

Generally speaking, whatever CHPL_* environment variables are set in your environment should control what is built when ``make`` is run as well as the default settings when ``chpl`` is run.  ``$CHPL_HOME/util/printchplenv`` should run the same logic that our Makefiles and ``chpl`` use, which is why it's odd that it's seemingly reporting different things along different code paths.

One caveat to the above is that we've recently added support for Chapel configuration .dotfiles (http://chapel.cray.com/docs/latest/usingchapel/chplenv.html#chapel-configuration-file) but the environment settings ought to win.  This makes me wonder whether you might have a configuration file somewhere that is getting picked up along one path but not the other (?).

Sorry for this confusion.  Hopefully we can get to the bottom of this quickly...

**Comment by bradcray** [comment]
@awallace-cray / @mppf : Do either of you have easy access to a Mint VM matching the above, and if so, could you try and reproduce the above?

**Comment by danindiana** [comment]
If it helps I could always do a make > chplmintinstall.txt file and upload it and you could get the full details. 

I will also try setting the environmental variables and report back. Stepping out for dinner but will be able to pick this thread back up either later tonight (central time) or tomorrow.

**Comment by danindiana** [comment]
@bradcray OK. 

The txt file chplbuildconfigmake.txt attached is the make output for Chapel after having run the python build_configs.py
[chplpybuildconfigmake.txt](https://github.com/chapel-lang/chapel/files/1040177/chplpybuildconfigmake.txt)


The Second file is the make output after having run the source util/quickstart/setchplenv.bash
It seems obvious at this point that running the setchplenv.bash file sets something up wrong at least for Mint linux. 
[chplmakesetchplenv.txt](https://github.com/chapel-lang/chapel/files/1040167/chplmakesetchplenv.txt)

**Comment by mppf** [comment]
I'm really surprised to see you running `sudo` at all unless you are using `make install`.

**Comment by danindiana** [comment]
@mppf Ah yes, well in this case it doesn't make a difference and it's force of habit but you are correct just running make is best practices.

**Comment by bradcray** [comment]
Thanks for including the logs.  I'm still stymied, though.  chplmakesetchplenv.txt shows that tasks/fifo is being built as we'd expect when doing a quickstart build:

```
***** src/tasks/ *****
***** src/tasks/fifo/ *****
```

and then your ranlib and ar commands to create the libraries seem to be putting them in the appropriate ``tasks-fifo`` directory under ``$CHPL_HOME/lib/`` rather than the ``tasks-qthreads`` directory that was shows in your original ``ls -R`` output:

```
ar -rc ../lib/linux64/gnu/arch-native/loc-flat/comm-none/tasks-fifo/tmr-generic/unwind-none/mem-cstdlib/atomics-intrinsics/gmp-none/hwloc-none/re-none/wide-struct/fs-none/libchplmalloc.a ./../build/runtime/linux64/gnu/arch-native/loc-flat/comm-none/tasks-fifo/tmr-generic/unwind-none/mem-cstdlib/atomics-intrinsics/gmp-none/hwloc-none/re-none/wide-struct/fs-none/src/chpl-mem-replace-malloc.o
ranlib ../lib/linux64/gnu/arch-native/loc-flat/comm-none/tasks-fifo/tmr-generic/unwind-none/mem-cstdlib/atomics-intrinsics/gmp-none/hwloc-none/re-none/wide-struct/fs-none/libchplmalloc.a
```

This suggests to me that it's most likely that something went wrong in the original build -- e.g., the original 'make' and the 'make test' were not both run in the quickstart environment.  Specifically, it looks like the order of operations might have been (1) ``make``, (2) ``source $CHPL_HOME/util/quickstart/setchplenv.bash``, (3) ``make test`` which would lead to the observed behavior (because the default make would assume qthreads as the tasking layer while step 2 would cause step 3 to assert fifo would be used).

One other wild guess as I sign off for the night:  Is there any chance that doing a ``sudo make`` could cause previous environment settings to be lost?  E.g., if the order was:  (1) ``source $CHPL_HOME/util/quickstart/setchplenv.bash``, (2) ``sudo make``, ... is there any chance that the sudo make would cause CHPL_TASKS no longer to be set to fifo for Mint?  Seems unlikely, but I'm struggling to try and find an explanation other than user error...

**Comment by mppf** [comment]
I've created a Mint 18.1 VM and here is what I observe:

### The normal procedure works

If I use the normal procedure to build Chapel (and yes, I know this might not be obvious to new users), it builds without error:

``` bash
wget https://github.com/chapel-lang/chapel/releases/download/1.15.0/chapel-1.15.0.tar.gz
tar xvzf chapel-1.15.0.tar.gz
cd chapel-1.15.0/
source util/quickstart/setchplenv.bash 
make
make check
```

This works for me with master as well as with the Chapel 1.15 release.

### Using `sudo make` causes a problem

If I use this unusual procedure, I can reproduce the issue:

``` bash
tar xvzf chapel-1.15.0.tar.gz
cd chapel-1.15.0/
source util/quickstart/setchplenv.bash 
sudo make
make check
```

I particular, I am observing that the `sudo make` seems to lose its environment variable settings. (Which is what Brad was suggesting - e.g. CHPL_TASKS is no longer set for the `make` command).

### Why is this happening?
 * sudo doesn't generally forward environment variables, although this can be controlled by /etc/sudoers to some extent, and `sudo -E` will request environment variable forwarding
 * see also [this stack overflow post](https://stackoverflow.com/questions/8633461/how-to-keep-environment-variables-when-using-sudo)
 * `source util/quickstart/setchplenv.bash` just sets a bunch of environment variables
 * `make` and `make check` need to be run with the same environment variables to have the correct result.

I verified that this explanation is correct by running `sudo -E make`. 

### HOWEVER

Do not build Chapel or anything else as root. It is a really terrible idea. The first problem is that project developers will generally work with a user account (and so building as root will not be tested). The second problem is that if you build it as root, you have to do every other step that later modifies the same files as root (e.g. `./configure`, `make clean`, `git reset`, ...). The third problem is that it's a horrible security practice. Malicious code is one thing, but what if a Makefile contains an error and accidentally runs `rm -rf /` as root? It could just fail silently with a "permission denied" error for everybody else but blow away your system.

So, don't do that.

### make install

Now, we are aware that Chapel has a slightly strange build process. Nonetheless we have tried to document it well in the [Quickstart Instructions](http://chapel.cray.com/docs/latest/usingchapel/QUICKSTART.html) which you probably have seen. Nonetheless we have recently also created a script that will allow a user to run `./configure` `make` `sudo make install` like they usually do.

However, `./configure` and `make install` are newer than 1.15, so they wouldn't have been available to you. Nonetheless I've verified that the following sequence works on Linux Mint 18.1 with the master branch available on GitHub:
``` bash
./configure
make
sudo make install
```

(and then in another window I ran `chpl hello.chpl` to use the newly installed `/usr/bin/chpl`).

(Note, in case somebody tries this now: `make check` is not currently using the settings created by `./configure`, which is why I omitted it from the listing above. I'll create an issue about that.)

**Comment by bradcray** [comment]
Thanks for reproducing this Michael (and I'm glad that my wild guess was correct!  ...though admittedly, it would not have occurred to me if you hadn't raised the "why ``sudo make``?" question).

If @danindiana is OK with it, I would suggest we close this issue and rename it to something like "Sudo make (don't do it) may cause make test to fail" such that others might be able to find it more easily if running into the same issue.

**Comment by mppf** [comment]
I'm closing & renaming to tidy up our open issues.
