### ISSUE TITLE
Have to rebuild chapel after logging out

### ISSUE THREAD

**Issue by DanielFeshbach** [chapel-lang/chapel#6360]
### Summary of Problem
Basically, I'm trying to install chapel 1.15.0, and I'm finding that I have to rebuild it after every time I log out.

I installed chapel 1.15.0 on my Ubuntu 16.04 desktop, and it seems to be working fine until I log out and log back in again, either as the administrator or in my own user account. After logging out, trying to compile a chapel program that was compiling fine before, or just typing `chpl -h`, resulted in a `chpl: command not found` error:
```
No command 'chpl' found, did you mean:
 Command 'ctpl' from package 'ctpl' (universe)
chpl: command not found
```
However, when I rebuild it by running `source util/setchplenv.bash` and then `make`  from the chapel home, it works again. It also works on my other account as I ssh in, so it seems that the issue is the logging out rather than the logging in.

I have tried reinstalling it in a different location, and the problem persists.

### Configuration Information

- Output of `chpl --version`:
```
chpl Version 1.15.0
Copyright (c) 2004-2017, Cray Inc.  (See LICENSE file for more details)
```
- Output of `$CHPL_HOME/util/printchplenv --anonymize`:
```
CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: gnu
CHPL_TARGET_ARCH: native
CHPL_LOCALE_MODEL: flat
CHPL_COMM: none
CHPL_TASKS: qthreads
CHPL_LAUNCHER: none
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_MAKE: make
CHPL_ATOMICS: intrinsics
CHPL_GMP: gmp
CHPL_HWLOC: hwloc
CHPL_REGEXP: re2
CHPL_WIDE_POINTERS: struct
CHPL_AUX_FILESYS: none
```

- Back-end compiler and version, e.g. `gcc --version` or `clang --version`:
```
gcc (Ubuntu 4.8.5-4ubuntu2) 4.8.5
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by bradcray** [comment]
Hi Daniel --

Here's my guess as to what's going on:  Sourcing ``setchplenv.*`` files do a few things for you like setting your path to include $CHPL_HOME, setting CHPL_* environment variables, etc.  As they are processed, they should print out the actions they are taking.

To use an existing Chapel installation, these settings need to be made consistently on each usage, either by re-sourcing the same ``setchplenv.*``, or adding the settings to your ~/.bashrc file, or otherwise modifying your environment to get the same settings.  The specific issue you're running into -- ``chpl`` not being found -- seems indicative of the appropriate `$CHPL_HOME/bin/...` directory not being added to your path.  We have no way of making that setting persist across shells -- it's something  you need to take care of yourself.

Other $CHPL_* settings can be put into a Chapel configuration file, as documented [here](http://chapel.cray.com/docs/latest/usingchapel/chplenv.html#chapel-configuration-file) and may make it so that only your path needs to be updated.

Though it's not included in Chapel 1.15, on our master branch today, we have a new feature (planned for 1.16) that supports a `./configure` script and a `make install` step that can be used to install Chapel into a standard location that's already in your path (like ``/usr/local/bin`` or ``~\bin``) which would avoid needing to set your path specially.

Hope this helps answer your question -- let us know either way.

**Comment by DanielFeshbach** [comment]
Thank you for your quick and helpful reply with what I did not at first realize was a basic sysadmin issue rather than a chapel issue. It was actually slightly more complicated because it turns out a previous sysadmin had made users default to the previous version of chapel, but I think I've fixed it now.

**Comment by bradcray** [comment]
Great, glad to hear it!
