### ISSUE TITLE
Move mailing lists from SourceForge to a different platform

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#6440]
For some time, we've wanted to move our mailing lists from SourceForge to something more modern (e.g., with better archive/search mechanisms) and less advertisement-oriented.  This issue is meant to capture alternatives that we might consider and their pluses and minuses.  

I think of some of our goals as including:

* the ability to use it in a "push" mode, like mailing lists
* good archives / search
* ideally, an easy way to preserve the SourceForge mailing list archives

**Comment by ty1027** [comment]
I have tried searching the net for various languages, and it seems that the pattern of forums is rather limited (only a few patterns):

* Pattern 1 : The language website provides a "built-in" forum (e.g., D, Nim).

* Pattern 2 : Google Groups (e.g., C++, Fortran, Go)
https://groups.google.com/forum/#!overview

* Pattern 3 : Discourse (e.g., Rust, Julia)
https://www.discourse.org/

----------------------------------------------
An expanded list of some forums (found with a search engine):

* C++
https://isocpp.org/forums
https://groups.google.com/a/isocpp.org/forum/?fromgroups#!forum/std-discussion
https://groups.google.com/a/isocpp.org/forum/?fromgroups#!forum/std-proposals

* D
https://forum.dlang.org/
http://digitalmars.com/NewsGroup.html   (old page?)
https://news.ycombinator.com/item?id=3592769
(old news about the new forum)

* Go
https://groups.google.com/forum/#!forum/golang-nuts
https://forum.golangbridge.org/
https://forum.golangbridge.org/t/welcome-to-the-go-forum/8
https://golang.org/help/

* Rust
https://users.rust-lang.org/

* Nim
https://forum.nim-lang.org/
https://github.com/nim-lang/nimforum (run by this program?)

* Julia
https://julialang.org/community/
https://discourse.julialang.org/
https://groups.google.com/forum/#!forum/julia-users (not used now)
https://gitter.im/JuliaLang/julia

* Fortran
https://groups.google.com/forum/#!forum/comp.lang.fortran

* Swift
https://forums.developer.apple.com/community/xcode/swift
https://www.reddit.com/r/swift/

* Kotlin
https://discuss.kotlinlang.org/
https://kotlinlang.org/community/

* Scala
https://www.scala-lang.org/community/
https://users.scala-lang.org/?_ga=2.236677193.918504109.1498691960-1666919074.1495278134
https://contributors.scala-lang.org/?_ga=2.200825261.283844884.1498692014-1666919074.1495278134
https://gitter.im/scala/scala

------------------------------------------------------------------------

Though I have only very limited experience of using such a forum, Google Group is
pretty easy for us to post any questions. For some reason, it has a very low (mental)
threshold to post a question as compared to, e.g., StackOverflow or Github issues.
(It may be natural because StackOverflow has strict rules, and Github issues are mainly for
developers.) For "open-ended" discussions, or just for posting new info, I expect 
such forum will be very useful.

For example, I expect it would be great if we can see the following kind of threads
in a forum: 

 - Notification of recent related articles, web pages, and events
 - Personal experiences about Chapel and PGAS computing (with TIPS)
 - Comparison of features with other PGAS or non-PGAS languages
 - "Is the learning curve of Chapel rather steep?" (<-- I think so for various parts...)
 - "Is the official web page sufficiently easy to understand?"
 - "where can I find XXX?" (this type of questions are immediately closed in StackOverflow)
 - Heterogeneous computing (cluster + GPU etc)
 - Handling of large non-regular data in parallel

Also, I think it would be fun if users can communicate with other users to ask any trivial
questions, or just to show their new applications in Chapel (and ask opinions or improvements).

It might also be an option to open a forum experimentally, or unofficially to see whether
it is convenient enough for various purposes (e.g., "push" mode).

**Comment by bradcray** [comment]
Here are some notes related to this issue from @ben-albrecht that I was reminded of while cleaning up my inbox:  https://gist.github.com/ben-albrecht/043a9a29bdcc8c43e1199dd699d3ec95

**Comment by ben-albrecht** [comment]
Searchability came up as a potential issue for mailman.

For reference:

Here is the [mailman guide for improving searchability](https://wiki.list.org/DOC/How%20do%20I%20make%20the%20archives%20searchable)

Here is an [example using nabble (numpy)](http://numpy-discussion.10968.n7.nabble.com/)

**Comment by bradcray** [comment]
In meeting about this at the end of 2017, we focused primarily on:

* mailman, but moved from SourceForge to chapel-lang.org:
  + simple, familiar
  + comes for free with chapel-lang.org
  - poor UI / searchability (though it's been proposed that third-party software could help with this, as Ben refers to above)

* Discourse:
  + much more modern, feature-rich
  - higher learning curve to use (for those unfamiliar with it) and set up
  - would probably require "paying up" to get server cycles on chapel-lang.org

(@psahabu : Would you check that you think this is a reasonably complete & accurate summary of the December discussion?)

**Comment by psahabu** [comment]
@bradcray I would add that mailman provides easy archive access, whereas Discourse would require us to host our mailman archives separate of the main forum. Otherwise, this is an accurate summary of the discussion.

After researching Nabble from @ben-albrecht's post, I feel that we should start beta testing it with our beta mailing list. While the UI is basic, it provides all the functionality we need in a clean online interface.

**Comment by bradcray** [comment]
Assuming we haven't said anything on the test list that we wouldn't want to be public, I'd be open to pointing Nabble at our test list.  I looked at it enough to conclude that I wasn't going to have the time to investigate that anytime soon (but can take care of the DreamHost side of things as necessary, given clear instructions).  Did I understand correctly that nabble lives remotely and mirrors your mailing lists (effectively?)

**Comment by bradcray** [comment]
> mailman provides easy archive access

Good point, I forgot about this and edited to include that point.

**Comment by psahabu** [comment]
@bradcray That's correct, Nabble is remote and mirrors our public mailing list archive. It shouldn't require much DreamHost fiddling other than making the beta mailing list public. I'll start investigating it a little bit.

**Comment by ben-albrecht** [comment]
We may qualify for a free hosted Discourse: https://blog.discourse.org/2018/11/free-hosting-for-open-source-v2/

**Comment by bradcray** [comment]
I've filled out the Discourse application.  We'll see what happens.

**Comment by bradcray** [comment]
We got accepted overnight, now just need to set it up.

**Comment by ronawho** [comment]
Good to close this now that we have https://chapel.discourse.group/?

**Comment by bradcray** [comment]
Definitely, thanks!
