### ISSUE TITLE
chpl-env-gen.h contains non-runtime defines

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#6547]
chpl-env-gen.h is stored in the runtime build directory, but it contains some information that is not encoded in the runtime build directory.

E.g. in one configuration, I have this runtime build directory:

`../build/runtime/linux64/gnu/arch-native/loc-flat/comm-none/tasks-qthreads/tmr-generic/unwind-none/mem-jemalloc/atomics-intrinsics/gmp/hwloc/re2/wide-struct/fs-none/`

and this in chpl-env-gen.h:

```
#define CHPL_HOST_PLATFORM_LINUX64
#define CHPL_HOST_COMPILER_GNU
#define CHPL_TARGET_PLATFORM_LINUX64
#define CHPL_TARGET_COMPILER_GNU
#define CHPL_TARGET_ARCH_NATIVE
#define CHPL_LOCALE_MODEL_FLAT
#define CHPL_COMM_NONE
#define CHPL_COMM_SUBSTRATE_NONE
#define CHPL_GASNET_SEGMENT_NONE
#define CHPL_TASKS_QTHREADS
#define CHPL_LAUNCHER_NONE
#define CHPL_TIMERS_GENERIC
#define CHPL_UNWIND_NONE
#define CHPL_MEM_JEMALLOC
#define CHPL_JEMALLOC_JEMALLOC
#define CHPL_MAKE_GMAKE
#define CHPL_ATOMICS_INTRINSICS
#define CHPL_NETWORK_ATOMICS_NONE
#define CHPL_GMP_GMP
#define CHPL_HWLOC_HWLOC
#define CHPL_REGEXP_RE2
#define CHPL_WIDE_POINTERS_STRUCT
#define CHPL_LLVM_LLVM
#define CHPL_AUX_FILESYS_NONE
```

Where in particular the following are NOT represented in the runtime build path:

`../build/runtime/linux64/gnu/arch-native/loc-flat/comm-none/tasks-qthreads/tmr-generic/unwind-none/mem-jemalloc/atomics-intrinsics/gmp/hwloc/re2/wide-struct/fs-none/`

and this in chpl-env-gen.h:

```
CHPL_HOST_PLATFORM_LINUX64
CHPL_HOST_COMPILER_GNU
CHPL_LAUNCHER_NONE
CHPL_MAKE_GMAKE
CHPL_LLVM_LLVM
```

This causes test failures for `runtime/sungeun/chpl-env-gen` when toggling between `CHPL_LLVM=llvm` and `CHPL_LLVM=none`.

(Also, I've verified that with CHPL_COMM=gasnet, the env-gen.h file includes the launcher setting but the build runtime path does not).

**Comment by mppf** [comment]
Note, generation of chpl-env-gen.h was added in PR #2273.

**Comment by mppf** [comment]
I can see the following reasonably simple ways to resolve this issue:
a) only include runtime-relevant defines in chpl-env-gen.h (i.e. printchplenv --simple --runtime, but note that such a combination does not work correctly now).
b) store chpl-env-gen.h in a build/install directory that includes all configuration components
c) generate chpl-env-gen.h during `chpl` invocation time

**Comment by mppf** [comment]
@ronawho - do you have any thoughts on this matter? thanks.

**Comment by ronawho** [comment]
I don't think option c works because we use some of the macros defined in chpl-env-gen.h directly in runtime files. e.g. in runtime/src/chpl-topo.c we check ` #if defined(CHPL_HWLOC_HWLOC) || defined(CHPL_HWLOC_SYSTEM)` so we need to know the values at runtime build time.

I don't particularly like option a. 

Option b sounds reasonable to me. 

In the short term, couldn't we just add llvm to the runtime install dir?

**Comment by mppf** [comment]
@ronawho - thanks for your thoughts. In the short term, we can just tolerate this issue, which is even easier. I don't think adding llvm to the runtime install dir would be an improvement (now we'd have other issues).

I think whenever somebody tries to fix this problem, starting with Option b sounds like a good idea.

**Comment by ronawho** [comment]
@mppp / @ben-albrecht have mostly fixed this with https://github.com/chapel-lang/chapel/pull/7976

`chpl-env-gen.h` is now generated by `printchplenv --runtime` so it can only include values that will be in the runtime path. The one exception to this is that we explicitly exclude `CHPL_MAKE` from the path, but it's still included in the runtime output. 

I actually don't think that's a big deal, because I can't imagine `CHPL_MAKE` changing on a single machine, and I can't imagine anything in the runtime wanting to check the value of `CHPL_MAKE`. I'd be ok with pruning it `--runtime` too

**Comment by mppf** [comment]
Should we just filter out CHPL_MAKE when we generate chpl-env-gen.h ?

**Comment by ben-albrecht** [comment]
> Should we just filter out CHPL_MAKE when we generate chpl-env-gen.h ?

That would be a quick solution. I agree that `CHPL_MAKE` probably shouldn't be in `--runtime` output in the first place, since it primarily exists for debugging purposes. Maybe it's worth separating out into a separate category that is included by default (or not).

**Comment by ronawho** [comment]
Note that https://github.com/chapel-lang/chapel/pull/8025 removed `CHPL_NETWORK_ATOMICS` from the runtime path, but we still print it out with `printchplenv --runtime`. Technically it could have a stale value, but in reality with never set `CHPL_NETWORK_ATOMICS`. If we want to disable network atomics for ugni, we tend to just compile with `--network-atomics=none` so I'm not really worried about this one having a stale value.
