### ISSUE TITLE
Local-block violation with global ref-var to array

### ISSUE THREAD

**Issue by benharsh** [chapel-lang/chapel#6562]
### Summary of Problem
If a user creates a global alias to a block-distributed array, they might expect to be able to use that alias within a local block on remote locales (provided they are accessing local elements). This currently results in a local-block violation. This pattern used to work with the ``=>`` operator.

The problem likely lies in the ``parallel`` or ``remoteValueForwarding`` passes. ``parallel`` is currently responsible for broadcasting global record-wrapped types, but fails to do so for global references to record-wrapped types.

**Associated Future Test(s):**
[`optimizations/remoteValueForwarding/bharshbarg/arrayRefLocalBlock.chpl`](https://github.com/chapel-lang/chapel/blob/master/test/optimizations/remoteValueForwarding/bharshbarg/arrayRefLocalBlock.chpl)

**Comment by bradcray** [comment]
Though my observation of this `ref` vs. `=>` difference led to this issue, I don't think I agree with this statement:

> they should expect to be able to use that alias within a local block on remote locales

Specifically, I don't think there's anything about the definition of `ref` (currently anyway) that would guarantee that such accesses should be guaranteed to be local -- though we could amend the language's description of global refs to create such guarantees if that were of interest.  Instead, I'd say that it's a reasonable feature request to expect the compiler to optimize such refs so that no communication is required without bringing the `local` block into it.  This is part of why we've been trying to move from `local` blocks to data-centric expressions of locality (and why the `local` block has never made it into the language spec) -- it's difficult to precisely define them in the presence of optimizations like this that one might expect or hope for, but that the language definition doesn't guarantee and a different compiler (or a compile with optimizations off) might not provide.
