### ISSUE TITLE
Parallel iterators not yielding records by ref

### ISSUE THREAD

**Issue by benharsh** [chapel-lang/chapel#6696]
### Summary of Problem
I was writing a leader/follower iterator that wrapped some simple,
yet frequent, iteration over an array-of-arrays-of-records. To my
surprise, I found that the leader/follow iterator yielded the records
by value but that the serial iterator yielded the records by ref. All
this despite all the iterators involved having the ref yield-intent.

**Associated Future Test(s):**
[`test/functions/iterators/bharshbarg/yieldRecordByRef.chpl`](
           https://github.com/chapel-lang/chapel/blob/master/test/functions/iterators/bharshbarg/yieldRecordByRef.chpl
          ) #6694

**Comment by benharsh** [comment]
@vasslitvinov : here's the bug mentioned over email.

**Comment by cassella** [comment]
When I change the leader to yield an idx and the follower to index
into A with it, it works,

```chapel
iter allFoo2() ref {
  for a in A do
    for f in a do
      yield f;
}
iter allFoo2(param tag:iterKind) ref where tag == iterKind.leader {
  forall a in 1..4 do
    for f in 1..4 do
      yield (a,f);
}

iter allFoo2(param tag:iterKind, followThis) ref where tag == iterKind.follower {
  yield A[followThis[1]][followThis[2]];
}

forall f in allFoo2() do f.x = 1;
writeln(A[1]); // Should print 1s
```

```
fortytwo@magrathea:~/src/chpl$ chp parrarrarr.chpl 
(x = 1) (x = 1) (x = 1) (x = 1)
```

Is this because in the failing code, though the leader returns `f` by
ref, what's passed to the follower as `followThis` isn't the same ref?


In fact, if I change your `allFoo` to take `followThis` as a ref, it
works too:

```chapel
iter allFoo(param tag:iterKind, const ref followThis) ref where tag == iterKind.follower {
```

So maybe it was just `followThis` being passed into the follower by
default intent instead of by ref?


(I had to change it to `const ref` because if it's just `ref` it
didn't compile.  However, the `const ref` version still allows me to
yield it as a plain `ref`, which allows the caller to modify the
array.)

**Comment by vasslitvinov** [comment]
Clarifying that this is not an issue with standalone iterators.

**Comment by benharsh** [comment]
This future has been passing since ~2018. Closing.

**Comment by bradcray** [comment]
🤦

**Comment by cassella** [comment]
Should this also work for `A : [1..4] [1..4] int`?  I get the same behavior as the original `.bad` file:

```
fortytwo@enodia:~/src/chapel (main)$ ./yieldRecordByRef -nl 1
0 0 0 0
2 2 2 2
3 3 3 3
```

(Of course changing all the `f.x` to `f`.)

The original writeup of

>  the leader/follow iterator yielded the records
by value but that the serial iterator yielded the records by ref. All
this despite all the iterators involved having the ref yield-intent.

seems as applicable and as surprising.  (And the "fix" was something like the default intent for the `followThis` record arg changing from value to ref?)

**Comment by vasslitvinov** [comment]
Good catch @cassella ! I created an issue about this: #22624.

To clarify:
* The int version should not compile because we cannot yield `followThis` by ref intent when it is a formal of integer type with the default intent, because in this case the default intent is `const`.
* The reason it works for records is because the default intent for `followThis` of a record type is "ref maybe const". Since it is yielded by ref, "ref maybe const" means "non-const ref", so the mutable reference to A[i][j] is passed through correctly.
