### ISSUE TITLE
Ordering of deinitializers: modules vs. records

### ISSUE THREAD

**Issue by ben-albrecht** [chapel-lang/chapel#6726]
What should be called first: *module deinitializers* or *record deinitializers*? Today (as of 1.15), module deinitializers are called first. However, this can be problematic in some use-cases.

Consider the following code:

```chpl
var c = new C(1);
var r = new R(c);

class C { var x: int; }

record R {
  var c: C;
  proc init(c) { this.c = c; }
  proc deinit() {
    writeln('Record deinitializer called');
    writeln('I need to read field c, in order to deinitialize');
    writeln(c.x);
  };
}


proc deinit() {
  writeln('Module deinitializer called');
  writeln('Deleting c, even though r still holds a reference to it');
  delete c;
}
```

Today on master, the sequence of events for the above program goes as follows:

- `c` instantiated
- `r` instantiated, with reference to `c`
- module deinitialized, deleting `c`
- `r` deinitialized, accessing field of `c`, which has already been deleted.

The program reports an error with valgrind, since the reference to `c` is being accessed after it's been freed. So this leads to the open question(s): 

- **Should the record deinitializer get called before the module deinitializer?**
  - **If not, how should programs like this ensure `c` is being freed in the correct order?**

**Comment by bradcray** [comment]
Can you give a practical example in which `R` would need to know the value of `C` in order to invoke its deinitializer?

**Comment by vasslitvinov** [comment]
The sequence you are describing is new as of 1.15. The rationale is that global variables should be deinitialized after module deinit(), because the latter may refer to the former.

**Comment by ben-albrecht** [comment]
> Can you give a practical example in which R would need to know the value of C in order to invoke its deinitializer?

[Here](https://github.com/chapel-lang/chapel/pull/6695/files#diff-5a736cac1292deb92c19b3fff952c242R205) is the example that surfaced this issue.

`privateDist` is accessed by `PrivateSpace ` during the record (domain) deinitialization. I haven't dug further into the domain code to see *why* it's accessing the distribution for deinitialization, since it seems like a reasonable thing to do.

**Comment by vasslitvinov** [comment]
@ben-albrecht In this example, seems like privateDist will be deleted automatically at the end of the scope, probably because you used it in dmap(privateDist). So not deleting it in module deinit() would be a solution.

PrivateSpace keeps a pointer to privateDist, so the latter should not be deleted while the former is still around.

**Comment by ben-albrecht** [comment]
>So not deleting it in module deinit() would be a solution.

This would re-introduce the memory leak that the PR is trying to squash.

**Comment by mppf** [comment]
Normally we deinitializers we have a strategy that prevents users from accessing un-initialized memory (or freed objects). That would seem to me to suggest that the module deinit needs to run first.
I think this analagous to this decision in CHIP 10:
> The fields of a given class or record will be deinitialized after the deinit method for that class or record has completed.

As for the PR, if you can't make it work right with that assumption, I'd revert it. I'm not so sure I could explain whether or not `domain(1) dmapped new dmap(new Private());` creates a domain that "owns" the `new Private()` or not.

**Comment by vasslitvinov** [comment]
Another thing to try is to have privateDist be dmap(new private()), to make it deinitialized at the end of the module scope and hopefully delete the class. I am not sure though how this would be different from the code prior to the PR.

**Comment by ben-albrecht** [comment]
>Another thing to try is to have privateDist be dmap(new private()), to make it deinitialized at the end of the module scope and hopefully delete the class.

This is how the code was before the PR (see changes linked in previous comment). The `new Private()` class instance does not get deleted.

**Comment by bradcray** [comment]
I think there is a large class of leaks like this -- an explicitly 'new'd domain map class is used to distribute something -- who should clean up?  To me the issue to discuss here is more about what our memory management story is for such cases and/or whether we want users to still explicitly call `new` on domain map classes and/or dmaps.  I think regardless of whether category a is feed before or after category b, one could come up with an example that would want it the other way...

**Comment by ben-albrecht** [comment]
@bradcray -- Thanks for the broader perspective. This makes me think that we should be using the Owned/Shared memory management here.

Could the `OwnedObject` module provide a solution to this problem?

For example,

```chpl
use OwnedObject;

var c = new Owned(new C(1));
var r = new R(c.borrow());

class C { var x: int; }

record R {
  var c: C;
  proc init(c) { this.c = c; }
  proc deinit() {
    writeln('Record deinitializer called');
    writeln('I need to read field c, in order to deinitialize');
    writeln(c.x);
  };
}

```

The above program has no leaks nor any use-after-free memory errors (as reported through valgrind). I have confirmed this works in the `PrivateDist` case as well (providing a fix for the latest regression)

**Comment by mppf** [comment]
@ben-albrecht - I don't think it's a good solution for distribution objects in particular. The reason is that distribution objects are reference counted. That means that a distribution used in some arrays in another module (say) could conceivably exist longer.

Let's think about this in terms of functions instead of global variables. I find thinking about functions usually gets the problems to be more apparent more quickly. And besides, global variables have a bunch of special behavior that I don't think is actually relevant here.

What if you had this:

``` chapel
proc makeMySpecialDomain() {
  var p = new Private();
  var d: domain(1) dmapped new dmap(p);
  return d;
}
```

This function probably leaks memory now. But what is it supposed to do? We could choose to make `d` own `p` or not (through the distribution for that domain):
 * if `d` does not own `p`, `p` would need to be deleted upon exiting this function, and then it wouldn't be possibly to return `d` (because it uses `p`). Or returning such a domain would cause a deep copy of the distribution.
 * if `d` does own `p`, then it can free it once the distribution is no longer used by any domains. `d` can be returned without a problem. The function `makeMySpecialDomain` shouldn't delete `p`, though.

So, that makes me think that the solution to the memory leaks you were facing is this:
 * make `dmapped` take in an Owned(SomeDistributionClass) instead of a raw class instance and have it "take ownership" - meaning that the pointer is set to `nil` for the caller.
 * adjust users of `dmapped` to match
 * find and fix memory management errors from this strategy

Such an API change would be for clarity. Even without it, we could write the code to assume that `domain(1) dmapped new dmap(p)` assumes ownership of `p`. For example, if actually using `Owned` in that context was a problem, we could adjust the compiler to leave `p` as `nil` after that operation.

Alternatively we could just entirely prohibit people from saying `dmapped new Private()` and instead only support `dmapped Private()`. The second syntax variant here neatly avoids this point of potential confusion.

Unfortunately both your PRs #6695 and #6733 seem to me to be going in the wrong direction in this regard. (They assume that `domain(1) dmapped new dmap(p)` "borrows" `p` when as far as I can tell, it needs to "own" `p`).

**Comment by mppf** [comment]
One more thing - I think this issue is asking a completely separate question from your PRs and the problem you ran in to. I answered the question I think you should be asking in my last comment.

To answer the question you are actually asking:

> If this is a satisfactory solution, then the answers to my original question would go as follows:
> 
> - **Should the record deinitializer get called before the module deinitializer?**
>   - No
> - **If not, how should programs like this ensure c is being freed in the correct order?**
>   - By using the `OwnedObject` / `SharedObject` memory-management modules

**Should the record deinitializer get called before the module deinitializer?**
   * No, record deinitializers for global variables of record type need to run after module deinitializer

**If not, how should programs like this ensure c is being freed in the correct order?**
  * Global records will be destroyed in reverse declaration order. Therefore, it suffices to to wrap `c` in an `Owned`.
   * Alternatively, a module `deinit` function could explicitly destroy  `r` (say by calling a function that asks it to clear its pointer, first doing any deinitialization steps that need to know `c`) and then `delete c`. The key to this strategy is that `R.deinit` needs to gracefully handle an already-destroyed object and/or one that no longer has a `c`.
  * Alternatively, `record R` could contain an `Owned(C)` instead of a bare c. The act of constructing an `R` gives it the responsibility to free the instance. In that event, no module deinitialization action is required for `c` and in fact it should be `nil` once the record initializer "takes ownership" of it.

**Comment by ben-albrecht** [comment]
My original comment on #6695:

>I am open to reverting this PR if #6726 cannot be answered & implemented quickly.

I think it's clear this is not an issue that can be answered and implemented quickly, so I am going to  remove the module-deinit from `PrivateDist` and allow the leak to continue until we reach a consensus on what the appropriate strategy is.

**Comment by bradcray** [comment]
With respect to this point of Michael's:

> The reason is that distribution objects are reference counted. That means that a distribution used in some arrays in another module (say) could conceivably exist longer.

While I agree that this is the challenge in general for domain map values and classes, is it necessarily for PrivateDist?  My understanding is that that's a singleton domain map whose lifetime is that of the program, and so it could potentially be cleaned up in this way.  I suppose a downside of cleaning up PrivateDist in a special way is that hopefully it wouldn't be necessary once we had a more general solution (and might even cause problems?  though maybe those problems would be obvious due to the proposed use of `Owned`?)

At the same time, I'm not overly concerned about the private-related leaks at this point, so am happy to wait until we have a more general solution if there was trepidation about going down a "take care of private specially" path.

**Comment by mppf** [comment]
*oh*
If `PrivateDist` is a singleton, we have no business calling `new PrivateDist()` in test code under any circumstances. Instead, we should be following the pattern of DefaultDist, where a global (single) variable is created and that is the value used when constructing a PrivateDist. (Or a function is available to return the single instance).

Along those lines, for the `dmapped Private()` syntax to work, we'll need the compiler to somehow know that since PrivateDist is a singleton, it shouldn't turn that in to a `new`. I think we havn't seen this problem with `DefaultRectangular` because the compiler just has special support for it (and we don't write tests that `dmapped DefaultDist()`). Not certain.

**Comment by vasslitvinov** [comment]
Ah good point. PrivateDist and DefaultRectangular distribution descriptors claim themselves singleton using `proc singleton() param return true`. Record `_distribution` checks that and refuses to delete it in proc _do_destroy(). So these guys are pretty much guaranteed to leak. (Does our DefaultRectangular distribution leak?)

BTW what is it about PrivateDist that we need to make it a singleton? Why not `new PrivateDist()` freely and rely on reference counting to clean up?

Michael mentions this test in his commit, although it's still unclear to me:
```
test/parallel/taskPar/sungeun/private.chpl
```

**Comment by bradcray** [comment]
> BTW what is it about PrivateDist that we need to make it a singleton? Why not new PrivateDist() freely and rely on reference counting to clean up?

My guess is that it's because there's no benefit in distinguishing one instance of PrivateDist() from another -- it has no distinguishing state.

**Comment by mppf** [comment]
I'm closing this issue because the original question is resolved. The private distribution still leaks memory but we have #12731 for tracking that issue specifically.
