### ISSUE TITLE
Unresolved call within parallel iterator

### ISSUE THREAD

**Issue by ben-albrecht** [chapel-lang/chapel#6745]
### Summary of Problem

When compiling a program with an unresolved call within a parallel iterator (standalone), the error message is misleading. It would be nice if this error message was clean like the serial iterator error message (shown below).

### Steps to Reproduce

**Source Code:**

```chapel
proc main() {
  forall j in iterator() {
    writeln(j);
  }
}

// Parallel iterator
iter iterator(param tag:iterKind) where tag == iterKind.standalone {
  foo(); // unresolved call
  yield 1;
}

// Serial iterator (unused)
iter iterator() { yield 1; }
```

**Compiler error:**

```
bug.chpl:1: In function 'main':
bug.chpl:2: error: unresolved call 'iterator(tag=iterKind)'
bug.chpl:8: note: candidates are: iterator(param tag: iterKind)
bug.chpl:14: note:                 iterator()
```

For comparison, here's the program with the unresolved call inside the serial iterator, which provides a helpful error message:

**Source code:**

```chapel
proc main() {
  for j in iterator() {
    writeln(j);
  }
}

// Parallel iterator (unused)
iter iterator(param tag:iterKind) where tag == iterKind.standalone {
  yield 1;
}

// Serial iterator
iter iterator() {
  foo(); // unresolved call
  yield 1;
}
```

**Compiler error:**

```
bug.chpl:13: In iterator 'iterator':
bug.chpl:14: error: unresolved call 'foo()'
```
**Associated Future Test(s):**
*TODO*

### Configuration Information

- Output of `chpl --version`: `chpl Version 1.16.0 pre-release (1e0c50a)`

**Comment by ronawho** [comment]
Isn't this just because if the standalone fails to compile we use the tryToken to fall back to the leader/follower? In this case there is no leader/follower so the compiler is complaining about the lack of a leader/follower iterator. 

pinging @vasslitvinov to be sure, but I'm pretty sure https://github.com/chapel-lang/chapel/pull/5295 (or some related commit) will resolve this since it removes our (ab)use of the tryToken for falling back to leader/follower iterators if there's a bug in the standalone version.

**Comment by vasslitvinov** [comment]
Thanks Elliot, you may be right on. I assigned this to myself.

**Comment by vasslitvinov** [comment]
The error message is good now.
Closing this issue.
