### ISSUE TITLE
yield stmt in else part affects time.

### ISSUE THREAD

**Issue by TomsyPaul** [chapel-lang/chapel#6757]
### Summary of Problem
The yield statement in else part of an if-else is also adding to the execution time.

### Steps to Reproduce

**Source Code:**

```chapel
use Time;
const n=10000;
var A:[1..n,1..n] int, t = new Timer();
//A.thankGod;
iter myiter()
{
  var x:bool=true;
  if x then
    for (i,j) in A.domain do yield (i,j);
  else
    for (i,j) in A.domain do yield (i,j);
}

iter youriter()
{
  if true then
    for (i,j) in A.domain do yield (i,j);
  else
    for (i,j) in A.domain do yield (i,j);
}

t.start();
for (x,y) in myiter() do A[x,y]=1;
t.stop();
writeln("myiter: ", t.elapsed(), " seconds");

t.clear();
t.start();
for (x,y) in youriter() do A[x,y]=1;
t.stop();
writeln("youriter: ", t.elapsed(), " seconds");

```

**Compile command:**
chpl iftrueiter.chpl

**Execution command:**
./a.out

**Output**
myiter: 1.00722 seconds
youriter: 0.193151 seconds

### Configuration Information

- Output of `chpl --version`: 
chpl Version 1.14.0.953f818
- Output of `$CHPL_HOME/util/printchplenv --anonymize`: 
CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: gnu
CHPL_TARGET_ARCH: native
CHPL_LOCALE_MODEL: flat
CHPL_COMM: none
CHPL_TASKS: qthreads
CHPL_LAUNCHER: none
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_MAKE: make
CHPL_ATOMICS: intrinsics
CHPL_GMP: gmp
CHPL_HWLOC: hwloc
CHPL_REGEXP: re2
CHPL_WIDE_POINTERS: struct
CHPL_AUX_FILESYS: none
- Back-end compiler and version, e.g. `gcc --version` or `clang --version`:
gcc (GCC) 4.8.0 20130311 (GNU UPC 4.8.0-3)

**Comment by ronawho** [comment]
Multiple yield statements prevent iterators from being inlined, at least in our current iterator inlining implementation. The `if true`case is a param conditional, so the else brach is folded away before iterator inlining, so that can be inlined. Similarly if you change `var x:bool=true;`  to `param x:bool=true;` the iterator could be inlined.

Longer term we have plans to improve the cases that iterator inlining can handle, but for now your best bet is to write iterators that only have a single yield. And we actually have 2 forms of iterator inlining. One for direct (non-zippered) loops and another for zippered loops. For zippered loops there's a few more restrictions: You can only have a single yield, and it must be in a top-level loop.

Feel free to paste in your actual code, and we can make suggestions on how it could be modified so it can be inlined.

Pinging @bradcray and @daviditen in case they have more to add. 

Also, we should probably document iterator performance/inlining tricks somewhere and provide a user-facing mechanism to help determine which loops can/cannot be inlined

**Comment by bradcray** [comment]
@ronawho said most of what I was planning on saying here.  It's probably worth adding that the 'param' that controls the conditional could be a param argument to the iterator or a config param (i.e., it doesn't have to be a local true/false value).  But yeah, if you can collapse down to a single yield (e.g., by refactoring the code or by making multiple overloads of the iterator which can be chosen between at compile-time), that's going to be much better for performance.

**Comment by TomsyPaul** [comment]
What I want is to process a list and generate values from every node.
```chapel
for node in mylist.these() do
switch(node.indexfield)
 {  when 1 { do something and yield a set of values}
    when 2 { do someother and yield another set of value}
   when 3  ....
}

**Comment by bradcray** [comment]
How many cases in the 'switch' statement?  (i.e., how many distinct yields?)  Also, what's the likely size of the body of the loop that is invoking this iterator?

To shed some more light on the implementation of the single-yield optimization, we essentially inline the iterator where it is invoked within a loop and then inline the loop body back into where the yield statement occurs.  The current implementation limits this to a single yield in order to avoid blowing up the code too much.  So my questions above are designed in part to get to the question "Would this blow up the code too much for your use case?"

I think we've also discussed making the `inline` keyword on (serial) iterators dictate "I don't care about the code blow-up, please do the inline regardless," but I don't believe this idea has ever been agreed-upon or implemented.

**Comment by TomsyPaul** [comment]
There are 5 cases in the switch. One of them has three sub cases and another has two.
By the way, I am presently working on serial iteration.

**Comment by TomsyPaul** [comment]
I think the above comment was missed. So resubmitting.

There are 5 cases in the switch. One of them has three sub cases and another has two.
By the way, I am presently working on serial iteration.

**Comment by ronawho** [comment]
@TomsyPaul is it possible for you to share the entire iterator and call-site with us? That'd make this more concrete and easier to think about, at least for me.

**Comment by ronawho** [comment]
And FWIW the force inlining that brad mentioned will only work for direct (non-zippered) iterators. 

e.g. we could force inline something like:

```chpl
iter myiter() {
  for i in 1..10 do yield i;
  for i in 11..20 do yield i;
}

for i in myiter() do writeln(i);
```

but our current iterator inlining implementation can't handle inlining things like:

```chpl 
for (i, j) in zip(myiter(), 1..20) do writeln(i);
for (i, j) in zip(myiter(), myiter()) do writeln(i);
```

for the `zip(myiter(), 1..20)` case I can't think of any way to inline those loops together. We could inline the `zip(myiter() myiter())` case, but that's not something we currently support.

And note that we have future plans to expand our iterator inlining infrastructure, but so far as I know that's not a near term-priority.

**Comment by ronawho** [comment]
https://github.com/chapel-lang/chapel/pull/7270 increases the number of yields permitted in inlined iterators from 1 to 10. Once that gets merged, you shouldn't see any performance loss. 

For your reproducer I see equivalent timings:

master:
```
chapcs11: chapel (master) $ ./multi-yield
myiter:   0.781426 seconds
youriter: 0.096971 seconds
```

With #7270:
```
chapcs11: chapel (inline-more-direct-iters) $ ./multi-yield-improved
myiter:   0.098762 seconds
youriter: 0.098497 seconds
```

If you end up having more than 10 yields, you can increase the number of yield with the compiler flag ` --inline-iterators-yield-limit <limit>` but note that this can significantly increase the amount of code generated.

**Comment by TomsyPaul** [comment]
Thank you so much.. My work was stuck at this point..
