### ISSUE TITLE
Chapel-IPE fails on writeln()

### ISSUE THREAD

**Issue by buddha314** [chapel-lang/chapel#6760]
### Steps to Reproduce

Within the chpl-ipe command line, I think this is pretty self-explanatory.
**Source Code:**

```chapel
chpl-ipe



IPE 0.1

 1 > var x = 20;
 2 > writeln('X is');
   IpeProcedure::resolve(SymExpr*, actuals[])
   matchCount = 0


      #<SymExpr       1646 var:  #<VarSymbol     1553 name: NULL.writeln                qual: unknown          type: #<PrimitiveType     255 procedure> depth:  0 offset:  200>>
   0: #<SymExpr       1647 var:  #<VarSymbol     1636 imm:  "X is"                       type: #<AggregateType      18internal error: MIS0491 chpl Version 1.15.0

Internal errors indicate a bug in the Chapel compiler ("It's us, not you"),
and we're sorry for the hassle.  We would appreciate your reporting this bug -- 
please see http://chapel.cray.com/bugs.html for instructions.  In the meantime,
the filename + line number above may be useful in working around the issue.
```

**Compile command:**

**Execution command:**

**Associated Future Test(s):**

### Configuration Information

- Output of `chpl --version`:
```
chpl Version 1.15.0
Copyright (c) 2004-2017, Cray Inc.  (See LICENSE file for more details)
```

- Output of `$CHPL_HOME/util/printchplenv --anonymize`:
- Back-end compiler and version, e.g. `gcc --version` or `clang --version`:
```
gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin14.5.0
Thread model: posix
```

- (For Cray systems only) Output of `module list`:

**Comment by bradcray** [comment]
This is embarrassing.  It looks to me as though this behavior broke since the IPE's documentation was written.  Specifically, between then and now `'foo'` started being interpreted as a Chapel string literal whereas prior to that it had been interpreted as a C string literal.  Today, C string literals can be expressed using `c'foo'` and it appears to me that changing to that form makes this test work as expected.  Still, it'd be nice if this worked with "normal" Chapel strings, and at the very least we should update the documentation.  I've asked @noakesmichael if he could take a look at this issue.

In the spirit of full disclosure, I should mention that the ipe has received very little attention over the past several releases, not due to lack of interest, but lack of resources and a need to more fully re-architect our compiler to better support an interpreted/interactive mode.  We wish we could spend more time on it, but have been unable to do so recently.

**Comment by buddha314** [comment]
Lack of resources is completely understood.   But here I am breaking things anyway!

Another breakage:
```
 1 > var x = 2;
 2 > writeln(x);
   IpeProcedure::resolve(SymExpr*, actuals[])
   matchCount = 0
```

Not sure if that's you or me.

**Comment by bradcray** [comment]
Hi @buddha314 : That looks like it's to be expected.  As I recall, to avoid the full generality of varargs writeln()s in the initial prototype of the IPE, it was restricted to just a few frequently occurring signatures, either a c_string or a c_string followed by a bool, int, or real argument.  See:

http://chapel.cray.com/docs/latest/technotes/chpl-ipe.html#output-functions.

So a workaround would be ``writeln(c"", x);``

**Comment by buddha314** [comment]
Thanks!  This works

```
> var x = 2;
> writeln(c"",x);
         2
> var y = 19;
> writeln(c"", x+y);
```

**Comment by buddha314** [comment]
Ah, I see that definition [in the source](https://github.com/chapel-lang/chapel/blob/master/modules/ipe/internal/ChapelBase.chpl).  If I had the REPL, I could try to figure out how to fix the REPL, but...

**Comment by bradcray** [comment]
Support for chpl-ipe has been removed.  We hope to return to an interactive mode for Chapel in the coming years, but have decided to take a different approach than chpl-ipe.
