### ISSUE TITLE
Create graphBLAS module for Chapel

### ISSUE THREAD

**Issue by buddha314** [chapel-lang/chapel#6840]
Inspired by several presentations, including [Azad & Buluc](http://chapel.cray.com/CHIUW/2017/azad-slides.pdf), [graphBlas](http://graphblas.org/index.php?title=Graph_BLAS_Forum) and the field of [Algebraic Graph Theory](https://en.wikipedia.org/wiki/Algebraic_graph_theory), we could really use a systemic treatment of graphs within Chapel, along with the associated matrices.

**Comment by buddha314** [comment]
Bruce said this was a good idea...

**Comment by buddha314** [comment]
It is an open question whether to build it native or do something like MPI + iGraph.  There has been MPI discussion on igraph forums [here](https://lists.nongnu.org/archive/html/igraph-help/2008-01/msg00020.html) and [there](https://lists.nongnu.org/archive/html/igraph-help/2009-09/msg00045.html)

**Comment by buddha314** [comment]
Now that @bradcray is back from vacation, I want to annoy him by bumping this ticket.

**Comment by buddha314** [comment]
There is also [stinger](https://github.com/stingergraph/stinger) written C, maybe Chapel bindings to that?

**Comment by ct-clmsn** [comment]
@buddha314 stinger is a pretty unique solution. it's been a couple years since i've looked at the source but, from what i remember, stinger implemented under a client/server model. the server maintains [a highly specialized graph data structure](http://cass-mt.pnnl.gov/docs/pubs/pnnlgeorgiatechsandiastinger-u.pdf) in shared memory. graph algorithms accessing the stinger data structure are implemented as client applications which lock that server managed shared memory structure to perform a graph algorithm. when the computation is completed, the application unlocks the shared memory data structure and the server continues business as usual. [the publication history](http://www.stingergraph.com/index.php?id=publications) is worth reviewing.

**Comment by buddha314** [comment]
I don't know much about it, thanks for the link.  I'm just looking for the fastest way to interact with distributed graphs from chapel.  I'd like something that allows me to pull an adjacency matrix, not really a database.  I'd love to hear more of your opinions on that!

**Comment by buddha314** [comment]
John Leidel from Tactical Computing Labs pointed me to the [GraphBLAS C API](http://gauss.cs.ucsb.edu/~aydin/GraphBLAS_API_C.pdf) that would be instructive in building the Chapel version.

**Comment by buddha314** [comment]
Apparently some people are using [Giraph](http://giraph.apache.org/) at Facebook, and they published a [comparison of Giraph and GraphX](https://code.facebook.com/posts/319004238457019/a-comparison-of-state-of-the-art-graph-processing-systems/) .  I have used GraphX and I am not a fan.

**Comment by buddha314** [comment]
Just came across an early presentation on [Pregel and GraphX](https://stanford.edu/~rezab/classes/cme323/S16/notes/Lecture16/Pregel_GraphX.pdf) briefly describing some algorithms.

**Comment by buddha314** [comment]
I have begun work on [Chingon](https://github.com/buddha314/chingon) but very much would appreciate help.

**Comment by buddha314** [comment]
I'm far enough along in [Chingon](https://github.com/buddha314/chingon) to close this issue.  But help is still very much appreciated!
