### ISSUE TITLE
Define record "inheritance"

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#6851]
We used to define record inheritance as "field only".  We've since decided that we hadn't sufficiently defined what that would mean, what should happen with methods, etc, and so removed it from the language specification and will (shortly) make it an error for a record to inherit.

This is a placeholder issue for the discussion on what record inheritance should mean, so that the error message can point users to it and we can get feedback on what would be wanted.  We don't anticipate working on this issue immediately, but would likely be disappointed if Chapel had not figured this out 5-10 years down the road

**Comment by psahabu** [comment]
Record inheritance would be useful for error memory management if we don't get an Owned/Shared story first. I don't know if that should be a driving motivation though.

**Comment by vasslitvinov** [comment]
@lydia-duncan @bradcray I suggest to close this issue. We did away with record inheritance officially in #5892 because we had - and have - no current plans to consider it. We can reopen this issue - or create a new one - when+if appropriate.

**Comment by vasslitvinov** [comment]
Bonus: how about remove the tests that, since #6860, say "This test will probably be useful when we rethink the feature" and reference this issue:
```
test/classes/deitz/inherit-class-record/record_inherit1.chpl
test/classes/deitz/inherit-class-record/record_with1.chpl
test/classes/deitz/inherit/test_value2.chpl
test/classes/ferguson/generic-inherit-record-no-parent-methods.chpl
test/classes/figueroa/RecordDestructor3.chpl
test/classes/marybeth/test_dispatch_record.chpl
test/functions/jplevyak/scoping/visibility-4.chpl
test/users/vass/type-tests.isSubtype-records.chpl
```

**Comment by lydia-duncan** [comment]
I'm ambivalent to closing the issue but against removing the tests.

**Comment by mppf** [comment]
I'm closing this issue to reflect that our current plan is not to support record inheritance. Of course, in the future, that can be revisited with a new issue proposing a particular meaning and showing a compelling use case.

**Comment by bradcray** [comment]
At one point, we discussed having a "mix-in" concept instead of supporting record inheritance.  However, since we  implemented `forwarding` fields, that has felt to me to be sufficiently mix-in-like and to provide inheritance-like behavior to not make me wish for more than that, personally.

> I'm ... against removing the tests.

@lydia-duncan: Can you say more about this?  I haven't reviewed all of them, but checking the first as an example, I'm not seeing that preserving it adds much value to our nightly testing...  And I agree with Vass's sentiment that it doesn't represent a feature or syntax that we have any intention of supporting.

**Comment by lydia-duncan** [comment]
That comment was from 2019.  I don't feel strongly today
