### ISSUE TITLE
Improve support for enums declared within classes

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#6871]
While the spec says that it is legal to declare an enum within a class, in practice this is not well supported.  The type itself and its constants are not found when resolving field declarations or the contents of a method (I have only verified initializers so far).

### Steps to Reproduce

**Source Code:**

```chapel
class Foo {
  enum classTag { field1, field2};

  var tag: classTag = classTag.field1;
}
```

**Compile command:**
`chpl foo.chpl`

**Associated Future Test(s):**
[`test/types/enum/lydia/declaredInClass1.chpl`](https://github.com/chapel-lang/chapel/blob/master/test/types/enum/lydia/declaredInClass1.chpl)
[`test/types/enum/lydia/declaredInClass-initializer.chpl`](https://github.com/chapel-lang/chapel/blob/master/test/types/enum/lydia/declaredInClass-initializer.chpl)
#6870

### Configuration Information

- Output of `chpl --version`: 1.16.0 (prerelease)

**Comment by bradcray** [comment]
Removed [`test/types/enum/lydia/declaredInClass-constructor.chpl`](https://github.com/chapel-lang/chapel/blob/master/test/types/enum/lydia/declaredInClass-constructor.chpl) from the list of tests above because we don't really care about constructors anymore and I'm planning to remove the future in PR #10320.

**Comment by lydia-duncan** [comment]
Sweet, feel free to update the description and remove the constructor version when you merge it!
