### ISSUE TITLE
Internal error with CHPL_HOST_COMPILER=pathscale

### ISSUE THREAD

**Issue by PHHargrove** [chapel-lang/chapel#7039]
I am trying Chapel with pathscale compilers and not exactly getting winning results.  
If I should just pretend I never saw `make/compiler/Makefile.pathscale`, then let me know and I'll exclude it from our testing.

```
source /home/upcnightly/EX-dirac-ibv-pathscale/runtime/bld/dbg/chapel/util/setchplenv.bash && \
  env CHPL_COMM=gasnet CHPL_COMM_SUBSTRATE=ibv CHPL_HOST_COMPILER=pathscale  \
    chpl  -o example-hello6-taskpar-dist $CHPL_HOME/examples/hello6-taskpar-dist.chpl 2>&1
Setting CHPL_HOME to /home/upcnightly/EX-dirac-ibv-pathscale/runtime/bld/dbg/chapel
Setting CHPL_HOST_PLATFORM to linux64
Updating PATH to include /home/upcnightly/EX-dirac-ibv-pathscale/runtime/bld/dbg/chapel/bin/linux64
                     and /home/upcnightly/EX-dirac-ibv-pathscale/runtime/bld/dbg/chapel/util
Updating MANPATH to include /home/upcnightly/EX-dirac-ibv-pathscale/runtime/bld/dbg/chapel/man
$CHPL_HOME/modules/standard/IO.chpl:1387: internal error: ALI0118 chpl Version 1.16.0
Internal errors indicate a bug in the Chapel compiler ("It's us, not you"),
and we're sorry for the hassle.  We would appreciate your reporting this bug -- 
please see http://chapel.cray.com/bugs.html for instructions.  In the meantime,
the filename + line number above may be useful in working around the issue.
```

**Comment by bradcray** [comment]
Hi Paul / @PHHargrove  --

Probably you should pretend you never saw Makefile.pathscale.  We lost our free access to pathscale compilers years ago and haven't done any testing or maintenance against them since.  It's intriguing to me that it results in an internal error (as opposed to, say, a C/C++ compatibility issue at build time), but not enough to be motivated to look into it without a user who cares.  I vote we note this, close it, and wait for a user to resurrect it at some point in the future if you're cool with that.

**Comment by PHHargrove** [comment]
@bradcray 
I am fine with closing this.  

In case you were not aware: PathScale went bust back in May.  
You will find their wikipedia entry is now in the past tense.  😢

**Comment by mppf** [comment]
As per this discussion, closing until somebody wants to actually use Chapel with the PathScale compilers. This issue should be re-opened if that happens.
