### ISSUE TITLE
Document direct construction of arrays.

### ISSUE THREAD

**Issue by buddha314** [chapel-lang/chapel#7183]
It was extremely surprising to me that this does not work

```
var x: [1..3,1..3] real = [[1,0,0], [0,2,0], [0,0,3]];
-- addcol.chpl:1: error: rank mismatch in array assignment
```

but instead you need to do use parens.

```
var x: [1..3,1..3] real = ((1,0,0), (0,2,0), (0,0,3));
```

The [arrays primer](http://chapel.cray.com/docs/master/primers/arrays.html) never directly constructs a 2D array and the 1D array uses brackets.

```
chpl --version
chpl Version 1.16.0 pre-release (f2f4ce90e3)
Copyright (c) 2004-2017, Cray Inc.  (See LICENSE file for more details)
```

**Comment by ben-albrecht** [comment]
Today, there is no built-in syntax for 2D array literals (what you refer to as direct construction of a 2D array). Historically, this is due to challenges in distinguishing a 2D array literal and array-of-arrays literal.

The solution you've found is actually an interesting work-around that utilizes coercion from a tuple of tuples to a 2D array.

e.g.

```chpl
// main.chpl
var t = ((1,0,0), (0,1,0),  (1,1,1));
writeln(t);
writeln(t.type:string);
```

```bash
> chpl main.chpl
> ./main
((1, 0, 0), (0, 1, 0), (1, 1, 1))
3*3*int(64)
```

It's unclear to me whether or not we want to recommend this work-around in the official array documentation...

**Comment by bradcray** [comment]
It'd be great to fork this off into its own "define and implement multidimensional array literal format" issue.  I'd thought we had an issue for this already, but searching, it looks as though I may have been thinking of this email discussion (before we enabled GitHub issues):

https://sourceforge.net/p/chapel/mailman/message/31974940/

Brian, building on Ben's response note that your initializer would work for an "array of arrays" rather than a 2D array:

```chapel
var x: [1..3][1..3] real = [[1,0,0], [0,2,0], [0,0,3]];
```

(not that I"m suggesting that's a reasonable thing for you to do -- if you truly want a multidimensional array, you really want a multidimensional array literal which is why I'm suggesting we create and solve that issue).

> It's unclear to me whether or not we want to recommend this work-around in the official array documentation...

I'd say "not in the official array documentation".

**Comment by ben-albrecht** [comment]
I'm going to close this one as duplicate with the specific feature request for multi-dimensional array literals: https://github.com/chapel-lang/chapel/issues/8864

**Comment by lucaferranti** [comment]
Can this be reopened? #8864 is more about finding a better general solution, this issue is about documenting a currently existing workaround. Until #8864 is solved, I think it would be valuable to document this trick, maybe with a note it's unstable and might change if needed. (Unless the tuple trick is bad and should never be used, but I understand that's not the case?)

If one does not want to include it in the language specifications (the official array documentation), maybe it can be added to the primers?

**Comment by bradcray** [comment]
Speaking just for myself, I'm not a big fan of this workaround, primarily because I suspect it doesn't scale very well to larger arrays due to the implementation approach we use for tuples.  I don't mind people using it if it works for them, but don't consider it a sufficiently satisfying/official solution to document in any official capacity (which is what I'd consider putting it into either the spec or the primers would suggest).

If adding the workaround to the conversation in #8864 would be useful since people would be more likely to find it in an open issue than a closed one, that wouldn't give me any pause.
