### ISSUE TITLE
Strange issue on use of random

### ISSUE THREAD

**Issue by buddha314** [chapel-lang/chapel#7227]
I tried --checkForStupid, too.

random.chpl
```
use Random;
var rands: [1..10] real;
fillRandom(rands);
```

Produces 
```
 chpl random.chpl 
warning: Ambiguous module source file -- using ./Random.chpl over $CHPL_HOME/modules/standard/Random.chpl
./Random.chpl:4: error: unresolved call 'fillRandom([domain(1,int(64),false)] real(64))'
```

```
chpl --version
chpl Version 1.16.0 pre-release (9137cfca8f)
Copyright (c) 2004-2017, Cray Inc.  (See LICENSE file for more details)
```

```
$CHPL_HOME/util/printchplenv --anonymize
CHPL_TARGET_PLATFORM: darwin
CHPL_TARGET_COMPILER: clang
CHPL_TARGET_ARCH: native
CHPL_LOCALE_MODEL: flat
CHPL_COMM: none
CHPL_TASKS: qthreads
CHPL_LAUNCHER: none
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_MAKE: make
CHPL_ATOMICS: intrinsics
CHPL_GMP: gmp
CHPL_HWLOC: hwloc
CHPL_REGEXP: re2
CHPL_WIDE_POINTERS: struct
CHPL_AUX_FILESYS: none
```

**Comment by mppf** [comment]
I suspect this has to do with the way that random.chpl and Random.chpl are the same file in a case-insensitive compare (which is the default on mac os x).

**Comment by bradcray** [comment]
If it's not obvious, this also relates to the fact that a file which doesn't explicitly declare a module within its code takes its filename as the module name.  Thus, your random.chpl test is automatically creating a module named 'random'.  When the compiler processes the `use Random` statement, since it doesn't already know of any modules named 'Random', it searches for files named `Random.chpl` in the module search path and finds two due to the case-insensitivity of the file system on Mac/Windows that Michael mentions: the standard Random.chpl module file and your random.chpl file.

**Comment by buddha314** [comment]
'Twas not obvious.  Changed the name to `rnd.chpl` and it worked.  Hmm...

**Comment by bradcray** [comment]
A better approach in the compiler (long-planned, never-implemented) would be to have a little utility that scans through the module search path, parses any .chpl files therein, and creates little directory files for each saying "this file defines these modules."  Such a tool would (presumably) determine that `random.chpl` defines a module named `random` and `Random.chpl` defines one named `Random` and therefore would have avoided any ambiguity due to filenames being identical in a case-insensitive world.  This would also avoid current assumptions within the compiler that "if I don't already know about a module named `foo` I can only imagine it would be defined in a file named `foo.chpl`."
