### ISSUE TITLE
error handling: modes, compiler flag for release

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#7292]
This issue is proposing adding a compiler flag to relax the default that module error handling is checked. Additionally it is discussing the short-term `pragma` approach for selecting error handling modes.

PR #7244 and PR #7245 enabled 3 error handling modes, selectable by a pragma on a module:
 * `pragma "error mode fatal"` : don't give compile-time errors if errors are not handed, instead `halt` at runtime if an error comes up in that situation. This is the default for implicit modules (i.e. files with no module declaration).
 * `pragma "error mode relaxed"` : check at compile-time that errors are handled in some way, but don't insist that every throwing call be inside a `try` or `try!`. This is the default for explicit modules (i.e. a `module` statement).
 * `pragma "error mode strict"` : check at compile-time that errors are handled in some way and also that each throwing call is inside a `try` or `try!` to make sure the control flow is clear. (We were calling this "pedantic" at one point).

Since strict programs compile at the lower levels of checking, the main thing we've needed when updating tests is to add `pragma "error mode fatal"` to a test declaring a module but where that module doesn't yet handle the errors. In most of these cases, simply removing the module statement (so that the file uses the implicit module) is a reasonable way to remove the pragma, but users might desire a more straightforward way to get the easiest behavior. So, we are thinking about adding a flag to change the default.
 
Possible names for the flag:
 * --enable-lazy-errors, --permit-lazy-errors, or --lazy-errors
 * --fatal-errors, --halt-on-unhandled-errors, --unhandled-errors-halt

Note that we used to have a flag, `--enable-strict-errors`, that turned on strict error handling for everything. That flag was removed by PR #7244 since it doesn't really make sense anymore.

A flag like `--enable-lazy-errors` will not change the behavior of code that already handles errors correctly without the flag; it only serves to enable more code to compile. It's only particularly relevant for code inside an explicit `module` declaration.

I'm proposing that this flag merely change the default for explicit modules (rather than overriding any uses of the pragmas above). Additionally, I'm proposing to extend the error messages from the error handling pass to hint about removing the module declaration or using this flag if the code is still in "prototype mode".

**Comment by gbtitus** [comment]
I'd be more explicit with the flag name.  There are two problems with the term "lazy":
- It's ambiguous because of the potential for confusion with delaying an activity, as in "lazy evaluation".  Someone with only a surface understanding of Chapel error handling might think this was the intended meaning.
- It only implies why one would throw it ("because I want to do the minimum to get this to work") and doesn't say anything about what it does (changes the default for explicit modules to fatal).

How about `--default-module-errors-fatal`?

**Comment by bradcray** [comment]
I really like the idea of this flag (though I may have proposed it :) ).

I don't have as big a problem with the "lazy" term as Greg does, but do like his suggestion to focus on what it does.  The problem is that I have a hard time coming up with a short phrase for it.  ``--default-module-errors-fatal`` sounds to me like it's saying something about "default modules" (whatever they are... my head would go to one without a `module` keyword, when this flag does nothing to that case).  The full phrase for me is currently something like ``--permit-unhandled-errors-in-explicit-modules-and-halt-when-they-occur`` but that's obviously not a good flag name.  I think this is how we got to the "lazy" options -- though vague, they were at least succinct.

Part of my problem might also be that I increasingly think we have a sparse set of 2 x 2 error-handling modes rather than 3.  I think of us as having:

* the ability to let code be lazy about error-handling (in which case we halt) or not
* having two levels of strictness for calling throwing routines

where the strictness only kicks in when we have code that is non-lazy (hence 3 modes rather than 4).

Along these lines, I was going to propose that we also have a second flag that permits users to choose between the two strictness levels in bullet 2 above.  My working hypothesis is that we should eventually have just 2 modes of error-handling rather than 3 and that for this release, we mostly need ways for people to be able to (1) revert to lazy error-handling everywhere for simplicity and backwards compatibility with 1.15 and earlier and (2) experiment with the two levels of strictness to see which they prefer so that we can ultimately drop the other one of them.

[aside: am I correct that nobody's a big fan of having both strictness modes, and that we're mostly split about which of the two strictness modes is preferable?]

So maybe the second flag is called something like ``-require-try-for-throwing-calls`` (I think this is a short-lived experimental flag, so don't care if it's wordy).

I was hoping that writing this would give me clarity on the name for the first flag, but I end up at ``--permit-unhandled-module-errors`` which is still wordier than I'd like while also a bit vague given that implicit modules are modules too (and unaffected by the flag)...

**Comment by psahabu** [comment]
First flag: `--module-errors-fatal-default` or `--module-errors-default-fatal`

To the aside, it seems we're uncomfortable with the three modes just because it's three, not for any technical reason. As you pointed out, in practice it's more like a two-deep decision tree: 'is implicit halting okay?' and 'do I want to know where the errors are coming from?'

I will defend the use case of each, but it's reasonable to see if anybody actually wants to make that second decision. For this second flag, we could make it change the default behavior of explicit modules only, so we could base it off the first flag: `--module-errors-strict-default` or `--module-errors-default-strict`

**Comment by bradcray** [comment]
Part of my reason for suggesting that the controls seem more like a 2x2 choice than 3 siblings is that I'm not entirely comfortable with the current names of the three pragmas/modes:  the unity in the naming suggest that they're all siblings, but I don't see them that way (colloquially, the first seems more like "should I let you be lazy or not?" while the second two seem like "given that you've agreed not to be lazy, how much should I hold your feet to the fire?")

Similarly, making the second flag based on the first flag seems like a bad idea to me.  E.g., in your proposal, the word "module" seems out of place to me in that, as I see it, the flag's behavior is completely independent of modules.  It's really about how throwing functions can/must be called (right?), not about how modules are declared or treated.

I also think that a downside of making the flag names similar is that it makes the reasonably different choices that they control seem more similar than they are (e.g., I'd imagine needing to refer to a man page to understand how they differ from one another rather than having them be self-descriptive).

**Comment by mppf** [comment]
I'm only really interested in implementing the flag to relax modules globally to "error mode fatal" for this release. The other flag I think we should leave for future work (and error handling design enthusiasts can use the pragma to experiment).

**Comment by bradcray** [comment]
> To the aside, it seems we're uncomfortable with the three modes just because it's three, not for any technical reason.

I think your characterization is reasonable, but that "three" is a reasonable thing to balk at.  It feels a bit like a "0/1/many" (or "1/2/many") design issue to me.  Specifically, I think that having two modes of strictness _in the language_ suggests "Chapel's designers just couldn't make up their mind."  And I think that most users won't ever switch to whichever mode is not the default (or even know that there is a switch that can be made).

I think Michael's view of the choice in strictness as being like a warning mode on gcc is attractive.  E.g., if we adopt relaxed as the default, we should let people opt into a stricter mode using something like a "-Wtryless-calls-to-throwing-routines".  If we adopt strict as the default... then I'm not as sure what the gcc analogy would be for permitting a more relaxed behavior, but I'm still hesitant to make it part of the language proper.

> I will defend the use case of each

I'm interested in seeing this defense (and think it belongs in the release notes as well).  Not so much "What's the rationale for each case" but more "Why a single language ought to provide both" (again, as part of the language, not a compiler implementation that helps enforce a certain coding style).

**Comment by bradcray** [comment]
> The other flag I think we should leave for future work

If the flag is easy to implement, I think we should implement the flag.  I think it'd be more interesting to see globally (including in internal/standard modules) what the affect of the stricter mode is rather than having to edit each module independently.  Doing so seems like it could also permit us not to have to advertise the pragma to any end-users as originally desired (is that right?).

**Comment by psahabu** [comment]
> I think Michael's view of the choice in strictness as being like a warning mode on gcc is attractive. E.g., if we adopt relaxed as the default, we should let people opt into a stricter mode using something like a "-Wtryless-calls-to-throwing-routines".

I was not aware that we were considering this route, and at first glance I agree with it totally. I think it's important that users have an option to suss out their throwing calls in an easy way, like Swift does, but I also agree that it's easier to add warnings to `relaxed` than `strict`.

**Comment by psahabu** [comment]
Regarding the second flag, since we all seem to agree that `strict` should eventually be opt-in warnings rather than a full-blown mode, it seems alright to have users use the pragma for `strict` and not advertise it using a compiler flag.

**Comment by bradcray** [comment]
> should eventually be opt-in warnings rather than a full-blown mode, it seems alright to have users use the pragma for strict.

Could "eventually" be "now" in order to avoid the need to use pragmas in 1.16 for this purpose?  Is this a difficult flag to implement?  (seems like not to me -- wouldn't it just be a conditional on which strictness mode explicit modules get by default and maybe a change from an error to a warning?)

**Comment by mppf** [comment]
>  Is this a difficult flag to implement? 

A flag that universally enables increased strictness would cause lots of module code not to compile, since it doesn't follow the strictest rules. While adding the flag is easy, getting all the module code cleaned up so you could compile Hello World or even a nontrivial program is not, because it involves basically all our module code.

This is the reason I prefer to think of the "warning for unclear try control flow" as being the provenance of each module author rather than as a global compile flag. There is not a problem using other people's code that don't want to play that game.

It's a bit related to the way in GCC, you compile to libraries, and then use the library. Right now, in Chapel, we compile everything at once. So this flag would be sortof like saying with C projects that *all code you will use* meets `-Wall` if you choose to throw it (libc, BLAS, regexp library, ...). We can get out of this particular situation with separate compilation, but this is the reason I don't think we should have this flag right now.

**Comment by mppf** [comment]
Can we focus on the name of the "first flag"?

AFAIK we have these options/suggestions:
 * --enable-lazy-errors (Greg didn't like this)
 * --default-module-errors-fatal (Brad didn't like this)
 * --permit-unhandled-module-errors
 * --module-errors-default-fatal

I'd like to name it `--permit-unhandled-module-errors` and be done with that part. Is that Good enough?

**Comment by psahabu** [comment]
That flag name works for me.

**Comment by bradcray** [comment]
> A flag that universally enables increased strictness would cause lots of module code not to compile, since it doesn't follow the strictest rules. While adding the flag is easy, getting all the module code cleaned up so you could compile Hello World or even a nontrivial program is not, because it involves basically all our module code.

If the flag were only to apply to user modules by default, though, this problem would go away...  Then, as developers (and assuming it applied to all modules for developers), we could use the flag to determine how we feel about living with stricter or more relaxed styles in our internal and standard modules.

**Comment by mppf** [comment]
> If the flag were only to apply to user modules by default, though, this problem would go away.

I do not believe it. It would make the problem less immediately obvious.

Consider a user who is starting to use Mason. They download 6 mason libraries to make their awesome project. These mason libraries will count as "user modules" as far as the compiler is concerned. They probably won't support the stricter error mode.

**Comment by bradcray** [comment]
> These mason libraries will count as "user modules" as far as the compiler is concerned.

I was imagining these to be considered package modules rather than user modules, maybe incorrectly (my understanding of mason's categorization of modules is weak).

**Comment by mppf** [comment]
Closed by PR #7309.
