### ISSUE TITLE
Global stream scaling poorly under ugni

### ISSUE THREAD

**Issue by benharsh** [chapel-lang/chapel#7611]
With the [dynamic registration gains](http://chapel.sourceforge.net/perf/16-node-xc/?startdate=2017/06/11&enddate=2017/10/18&graphs=hpccstreamepperfgbsn5723827200,hpccglobalstreamperfgbsn5723827200,hpccpromotedstreamperfgbsn5723827200) during 1.16, we were expecting to see improvements in global stream performance at higher scales. Unfortunately, we observe global stream performance falling off at 32 locales:

| config   | GB/s   |
|---|---|
| ugni+qthreads  | 1550  |
| u+q w/o hugepages  | 1550  |
| gn+mpi  | 3000  |

Gasnet+mpi exhibits the expected results (32 * 95 = ~3000). Since unloading hugepages with ugni did not help, this doesn't seem to be an affinity issue (at least not one we've seen before).

**Comment by benharsh** [comment]
@gbtitus : Any initial reactions to this information?

**Comment by gbtitus** [comment]
Weird.  No, I don't know what's going on.  On an internal XC just now I got the following (to 3 significant digits):

| nodes  | GB/s  |
|---|---|
| 4 | 376 |
| 8 | 748 |
| 16 | 1480 |
| 32 | 1560 |

So clearly it falls off a cliff somewhere above 16 nodes.  Filling in some gaps to see where things go astray:

| nodes | GB/s |
|---|---|
| 16 | 1480 |
| 20 | 1860 |
| 24 | 2160 |
| 27 | 2450 |
| 28 | 2480 |
| **29** | **1410** |
| 32 | 1583 |

It's curious that the problem arises just above 28 nodes.  That's also the number of cores on the nodes I ran on, and thus also the number of uGNI comm domains available to the compute threads (tasks).  I'll need to do some investigating to understand why this is happening.

**Comment by gbtitus** [comment]
Running on 24-core nodes produces a similar effect.  The slowdown occurs when the number of nodes equals the number of cores rather than rises above it, and is more dramatic, but qualitatively it seems like the same thing:

| nodes | GB/s |
|---|---|
| 6 | 423 |
| 12 | 838 |
| 23 | 1580 |
| **24** | **853** |
| 25 | 892 |

**Comment by gbtitus** [comment]
The problem is not driven by the number of uGNI comm domains.  If I use `CHPL_RT_COMM_CONCURRENCY` to set the comm domain count, it doesn't have any appreciable effect.  Even with just a single comm domain, running on 23 24-core nodes produces around 1580 GB/s and running on 24 24-core nodes produces around 850 GB/s.  This makes sense; `stream` hardly communicates anyway.

**Comment by gbtitus** [comment]
This doesn't appear to have to do with memory affinity.  I instrumented the emitted C code to check memory affinity before the kernel loop.  Specifically, I had each task count the number of pages in its `A[]`, `B[]`, and `C[]` subsections that had locality mismatches with each other (i.e., A/B/C pages for the same index value didn't have the same locality), and that had affinity mismatches with the task (i.e., A/B/C page localities didn't match the task/thread locality), and the number of tasks whose stack had the wrong locality.  I ran with 8, 16, and 32 28-core nodes.  The results were as we've been seeing: about 750 GB/s on 8 nodes, about 1500 GB/s on 16, and also about 1500 GB/s on 32.  I did see some locality problems, both A/B/C mismatches and thread/array wrong affinity, on 16 nodes but none on 8 or 32 nodes.  So, affinity doesn't seem to be the issue.  Thinking about it, this makes sense: locality problems affect memory reference latency, but stream measures memory reference bandwidth.  Those can interact, but caching (especially if it's smart enough to prefetch) ought to be able to hide the latency of referencing the "wrong" NUMA node and thus deliver the desired bandwidth.

A final note: exactly half the tasks/threads in my runs, independent of the node count, had an affinity mismatch between the thread's execution locality and its stack locality.  I expect this is due to Qthreads stack pooling; it'll be nice when we can do something about it but it's not the problem here.

**Comment by ronawho** [comment]
I think this has the same root cause as https://github.com/chapel-lang/chapel/issues/7830

Once we start forking enough remote tasks for the underlying`coforall locDom in locDoms do on locDom` we end up yielding the processor and doing the entire local computation before spawning the remaining tasks. 

i.e. The main task on locale 0 that is forking remote tasks will yield while waiting for an ack back from newly forked remote tasks, and when it does so it allows the qthreads doing the stream kernel to run to completion, preventing the remainder of the remote forks until the local computation is done.

I don't quite understand why the magic number of remote forks needed to see this is the number of cores, but the branch that resolves #7830 by not yielding when doing remote forks, seems to resolve this at least for 32 nodes (will try at higher scales shortly)
