### ISSUE TITLE
Remote variable declaration specified but not implemented

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#7704]
This issue is a follow-up to [this Stack Overflow issue](https://stackoverflow.com/questions/47047442/remote-variable-declarations) which pointed out that the specification (section 27.2.1) says that you can write
``` chapel
on Locales[1] var x: [0..10] real;
```

But if you do, it fails to compile with a syntax error. The spec doesn't flag this as an unimplemented feature.

** Associated Futures: **
[`multilocale/sungeun/on_statement_var_decl.chpl`](https://github.com/chapel-lang/chapel/blob/master/test/multilocale/sungeun/on_statement_var_decl.chpl)

**Comment by BryantLam** [comment]
Just ran into this issue.

**Comment by bradcray** [comment]
We traditionally have tried to keep the spec describing the language as it should be rather than the language as implemented, so it doesn't surprise me that the spec doesn't describe this.  That said, in an attempt to keep the spec and the implementation closer in sync, we could also consider removing this description from the spec and then add a feature request issue related to extending the language and compiler to add the support.

**Comment by mppf** [comment]
An `on` expression is a related feature in some cases.

`on Locales[1] var x = new MyClass();`

is related to

`var x = on Locales[1] do new MyClass()`.

**Comment by DanilaFe** [comment]
This was addressed in https://github.com/chapel-lang/chapel/pull/25240 and the associated future test was un-futurized.

**Comment by riftEmber** [comment]
@DanilaFe , should [this docs note](https://github.com/chapel-lang/chapel/blob/1c8fe2b16f2b63d1f0faf2451879daa0ebcf2177/doc/rst/language/spec/locales.rst?plain=1#L286-L288) about RVD being unimplemented be removed now? (or modified to say it's unstable -- I didn't look at the state of implementation much)

**Comment by DanilaFe** [comment]
Yes, I will do that.
