### ISSUE TITLE
Environment variables set in launchers are not reflected in verbose output

### ISSUE THREAD

**Issue by ronawho** [chapel-lang/chapel#7841]
Environment variables that are set as part of the launcher code aren't included in the output of `-v`, so it's easy to miss some important env vars if you need to launch manually.

For example, [runtime/src/comm/ugni/comm-ugni-launch.c](https://github.com/chapel-lang/chapel/blob/master/runtime/src/comm/ugni/comm-ugni-launch.c) sets `HUGETLB_NO_RESERVE=yes`, which is currently crucial for getting good first touch. Unfortunately, it has to be set before program startup, so we can't just set it in the runtime, it needs to be set before the executable is even run. 

https://github.com/chapel-lang/chapel/pull/7700 is adding a new case to set some jemalloc env var, which also needs to be set before execution. 

We recommend using `-v` as a way to figure out what the launcher is doing in case the launchers aren't doing everything you need, so omitting the env vars that are being set seems like a bug.

For a specific example, while gathering performance numbers of Edison, we needed to manually submit jobs through batch instead of using our launcher. We grabbed the -v output and used that, forgetting that we needed to set some env vars too, which ultimately led to very poor (and initially confusing) performance from stream: 

```
./stream-ep -nl2
>70 GB/s

srun -q --nodes=2 --ntasks=2 --ntasks-per-node=1 --cpus-per-task=64 --exclusive ./stream-ep_real -nl2
>52 GB/s

HUGETLB_NO_RESERVE=yes srun -q --nodes=2 --ntasks=2 --ntasks-per-node=1 --cpus-per-task=64 --exclusive ./stream-ep_real -nl2
70 GB/s
```

We should figure out some way to include the env in the `-v` output. Maybe instead of doing a setenv on the launch node, we could just prefix the whole command with the env var list and have some sort of launcher_setenv() helper?

**Comment by gbtitus** [comment]
Ideally we'd find some way to tell the system launchers to set the env vars for us, on the target nodes before running the programs.  With `aprun` we could throw `--environment-override X=Y` for this.  `srun` doesn't have an exact analog, but you can throw `--task-prolog=program` and it'll run `program` right before running each task (target program in our usage) and if `program` produces any lines in its stdout of the form `export X=Y` then `srun` will set those environment values for the task/target program.  That would be harder for us to use because `program` has to be a standalone binary which won't be given any command line options, so it must be able to produce the desired environment settings unilaterally.

Alternatively, I could imagine us having our own env-setter to be run on the target nodes.  Maybe something like `chapelEnvSet --env X=Y [--env A=B ...] targetProgram_real [targetProgramArgs]` and it would set X=Y and any others in the environment and then `exec` the target program with the given args directly (no `fork()`).  Then instead of building a `targetProgram_real` command line in our launcher we'd build a `chapelEnvSet` command line and run that.

**Comment by ronawho** [comment]
slurm has an `--export` option, though I'd love if we could come up with a solution that didn't require adding explicit options for each launcher

Our current solution (setenv on the login node) just relies on the launcher propagating all env vars. I think that's an ok assumption, especially since ugni is the only case that currently requires this and we know slurm/aprun will propagate env vars. I'm hoping we can come up with a solution that still effectively modifies the login env and then relies on the launcher to propagate it, but in a way that's visible in the `-v` output.

A `chapelEnvSet` solutions seems ok to me, but I'm wondering if we could just prefix the command we run with `env=val` (though maybe that doesn't work for all shells?)

**Comment by gbtitus** [comment]
My guess is that just prefixing our command with `env=val` strings won't work because that's shell command line syntax and the system launcher doesn't run the launched program in a shell; instead it does `fork()` and some flavor of `exec()`.
