### ISSUE TITLE
Reduction-related leaks

### ISSUE THREAD

**Issue by benharsh** [chapel-lang/chapel#7896]
This issue exists to track and discuss leaks related to reductions:

- [ ] [reduction.chpl](https://github.com/chapel-lang/chapel/blob/master/test/trivial/sidelnik/reduction.chpl)
- [x] [sum_reduce.chpl](https://github.com/chapel-lang/chapel/blob/master/test/arrays/sungeun/array_of_arrays/sum_reduce.chpl)
- [x] [bxor_reduce.chpl](https://github.com/chapel-lang/chapel/blob/master/test/arrays/sungeun/array_of_arrays/bxor_reduce.chpl)
- [ ] [threeclasstypes-construct.chpl](https://github.com/chapel-lang/chapel/blob/master/test/reductions/bradc/manual/threeclasstypes-construct.chpl)
- [ ] [ri-6-user-instance.chpl](https://github.com/chapel-lang/chapel/blob/master/test/parallel/forall/reduce-intents/ri-6-user-instance.chpl)
- [x] [reductionex_record_class.chpl](https://github.com/chapel-lang/chapel/blob/master/test/users/ferguson/histogram/reductionex_record_class.chpl)

**Comment by bradcray** [comment]
I'm curious whether rewriting one of the simple `op reduce` expression cases as the equivalent forall loop with reduce intents also results in a leak (since that's what the compiler does).  It's also curious to me that a large number of tests use a reduce expression, but only a small number of tests leak due to them.

**Comment by vasslitvinov** [comment]
Rewriting the reduce expression in reduction.chpl into a forall loop reduces the leaks dramatically.
6 things are still leaking after the rewrite due to the forall.

**Comment by vasslitvinov** [comment]
In this test:

- [ ] [reductionex_record_class.chpl](https://github.com/chapel-lang/chapel/blob/master/test/users/ferguson/histogram/reductionex_record_class.chpl)

the leaks are user error. Each instance of `myhisto` allocates an instance of `histo` and does not delete it.

BTW simply deleting that `histo` when deleting the `myhisto` is not a solution, because `myhisto.generate()` leaks it out, so the `histo` outlives its `myhisto`. So these two should not be deleted at the same time.

**Comment by e-kayrakli** [comment]
https://github.com/chapel-lang/chapel/issues/15612 seems to be the cause of the remaining leaks today.

#15623 has the summary of all memory leaks we have as of today.
