### ISSUE TITLE
Should promoted calls execute nested call expressions one or many times?

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#7904]
When a promoted call includes a non-promoted sub-expression, as with `foo(A, makeit());` below, should the sub-expression be run once or many times?

Consider the following program:

``` chapel
proc makeit() {
  writeln("IN makeit");
  return 1;
}

proc foo(x:int, y:int) {
  return x+y;
}

var A = [1,2,3,4,5,6,7,8,9];
foo(A, makeit());
```

The promoted call `foo(A, makeit())` could have one of two behaviors:
1. Run `makeit()` only once:
   ``` chapel
   var tmp = makeit();
   forall a in A do
     foo(a, tmp);
   ```
2. Run `makeit()` many times:
   ``` chapel
   forall a in A do
     foo(a, makeit());
   ```

Currently on master, it does 1 - it only runs `makeit()` once. Is that an implementation artifact or the design we want?

**Comment by mppf** [comment]
One advantage to running it only once is that `makeit()` need not be parallel safe - whereas running it many times would require it to be so.

**Comment by bradcray** [comment]
This week, I've been thinking that approach 2 is the right answer and that the compiler doing approach 1 might be a case of premature (or poor) optimization where we hoisted such expressions out, incorrectly assuming they were pure.  I feel like it is intuitive, results in clean rewrite rules, and can provide nice power if we thought of replacing `makeIt()` with something like `getNextRandomNumber()` or `readIntFromFile()` in that each iteration would get its own value.  As Elliot pointed out on the issue that spawned this one, if the user wants the other behavior, they can get it by inserting the temp manually.  If they want approach 2 and we implement approach 1, they have to abandon promotion, which seems too bad.

The one thing that gives me slight pause is the point by Michael just above that the function would need to be parallel safe, so you could imagine a naive user crashing things accidentally.  OTOH, we are a parallel language...

**Comment by bradcray** [comment]
I'm also generally curious what existing codes would break/change if we switched approaches today and whether they're cases we care about or not....

**Comment by mppf** [comment]
>  If they want approach 2 and we implement approach 1, they have to abandon promotion, which seems too bad.

It wouldn't worry me if users needing this had to write a forall statement or expression. I think it'd be clearer what was going on that way.

**Comment by mppf** [comment]
@bradcray - wouldn't this be a breaking language change if we changed the behavior?

**Comment by bradcray** [comment]
I woke up thinking about this issue for whatever reason, and had some new thoughts about it.

* Above, I said that if we took approach 1 and you wanted to call the routine once per iteration, you'd have to abandon promotion, but that's not actually true.  You could write the argument using a forall loop expression, for example `[1..A.size] makeit()`.  So the whole call could be `foo(A, [1..A.size] makeit());`  That's a little more verbose, but it also has the advantage of making the fact that you're calling the routine multiple times in parallel clear in the code, avoiding the potential pitfall of silently calling `makeit()` multiple times in parallel if it's not a parallel-safe routine.  So I don't think approach 1 is inherently bad or broken.

* A similar case is `var A = makeit();` which I think we've discussed and decided we'd prefer this to take the current approach of calling `makeit()` once because it appears in the source that it's only being called once and you can always insert the forall loop expression if you want to call it more than once.  I think it could make sense to treat these two cases symmetrically.

* I was going to argue that I think it's a common case that `makeit()` will be a pure function in which case it'd be unfortunate to have to require the user to store it into a temp to avoid calling it unnecessarily many times; but of course the compiler could potentially do this for them (with analysis) if it could prove functions were pure; or we could introduce a notion of pure function declarations into the language.  And the flip side of that argument is that if the compiler could do the analysis, both cases would behave in the way you'd want "out of the box."  The obvious downside of that is that it seems unfortunate to define the language relying on compiler smarts like this, which could break down in the context of separate compilation, or where different compilers may be more or less aggressive at proving a function is pure.

* Another way I was thinking about it was "If you thought you knew what this did and you were wrong, what would the consequences be?"  If you thought it would be called once and it was really called multiple times, that could be problematic if your routine was not written to be parallel-safe, and in pretty arbitrary ways.  If you thought it would be called multiple times and it was only called once, your program would probably still be "safe" and the repeated result would probably become apparent to you pretty quickly, permitting you to course-correct.

All of this internal debate keeps me feeling undecided on the topic, though if I had to choice, I think my first choice would be:

1) Do option 1
  - because it's what we have today
  - because it seems less dangerous if the user assumes we do the other thing
  - because the forall-expression rewrite gives a pretty concise way to work around it
  - because of the similarity to array initialization
  - for simplicity

And otherwise, I might say:

2) Do option 2b: the compiler will call the routine multiple times unless it can prove it's pure (by some definition... e.g., will return the same value / not affect global state / not have side effects) in which case it will call it once.  And ideally the compiler will/should warn if it's calling the routine multiple times and can determine that it's unlikely to be thread-safe.
  - this approach has the advantage that it should always do what someone wants without surprises
  - but the major downside that it relies a lot more on the compiler

I don't think I'd do the original option 2 at this point.  Moreover, I believe that we could potentially evolve from option 1 to option 2b in the future without breaking existing code if need be.

**Comment by mppf** [comment]
@bradcray - one more thing - whenever we feel we are getting close to resolving this design question - we should make sure that we are happy with where #7889 ended up including the choice here. (And then presumably the next step would be to document these subtleties in the spec).

**Comment by bradcray** [comment]
Whichever approach we take here, I'm still happy with where #7889 ended up.  I think we can justify doing different things here vs. #7889 due to the difference between the implicit/invisible nature of default arguments and explicit, user-provided ones.  But it is interesting to consider whether #7889 suggests that option 2 is preferable / more consistent.

OTOH, w.r.t. array declarations like `var A: [1..10] int = makeIt();` or assignments like `A = makeIt();` I think it would be _very_ weird to have makeIt() be called multiple times when there's nothing indicating it should be.  So the case explored by this issue is interesting because it falls between these two "obvious" points for me.

Since @ronawho was outspoken on issue #7889, I'd be curious what he thinks about this one.

**Comment by mppf** [comment]
I think there is enough support for the current behavior, which is 1 - `foo(A, makeit())` runs `makeit()` only once - to close this issue.

**Comment by bradcray** [comment]
I agree, thanks everybody!

**Comment by mppf** [comment]
It appears that this decision isn't recorded in the language specification https://chapel-lang.org/docs/language/spec/data-parallelism.html#promotion . I think that section should be updated to say something about nested call expressions.
