### ISSUE TITLE
Unexpected initializer error

### ISSUE THREAD

**Issue by nspark** [chapel-lang/chapel#7938]
### Summary of Problem
The included code produces an unexpected error with initializers.

### Steps to Reproduce

**Source Code:**

```chapel
// error-0.chpl
record Foo {
  type eltType;
  type idxType = int;
  var size: idxType;
  proc init(type eltType, size: idxType) {
    this.eltType = eltType;
    this.size    = size;
    super.init();
  }
}
var foo = new Foo(real, 42);
```

**Compile command and output:**
```
$ chpl error-0.chpl
error-0.chpl:5: In initializer:
error-0.chpl:5: error: invalid access of class member in initializer argument list
```

### Configuration Information

- Output of `chpl --version`: 1.17.0 pre-release (febd6ff96f)

**Comment by lydia-duncan** [comment]
That's a bug in your code.  You're not using the type argument you defined, you're trying to use the field but the field doesn't know what it is yet

**Comment by lydia-duncan** [comment]
`proc init(type eltType, size: idxType) {`
eltType != idxType

**Comment by lydia-duncan** [comment]
idxType is not a valid symbol in the argument list unless you also provide an argument of the same name.  The compiler has rightly determined that you meant the field but also knows that the field doesn't know it's type yet.

**Comment by nspark** [comment]
> you're trying to use the field but the field doesn't know what it is yet

@lydia-duncan The compiler isn't aware of `idxType` even though `type idxType = int;` is defined in `Foo`?

**Comment by nspark** [comment]
I guess I'm just surprised that the type alias of `idxType` to `int` doesn't apply within the scope of functions.

For comparison, I think this would be comparable C++ (though I haven't tested it):

```c++
template <typename T>
class Foo {
  using eltType = T;
  using idxType = int;
  idxType size;
  Foo(size: idxType) : size(size) { }
};
auto foo = Foo<float>(42);
```

**Comment by noakesmichael** [comment]
Hi Nick,


This is an interesting program and I think it raises some
interesting questions but, after a minor mis-step on my
part, I conclude that the current behavior is the one we
want.


The current position is that a “field initializer expression”
does not provide an “initial value” for a field.  Instead it
is a “last resort” if you will.

At the entry to an initializer, none of the fields have any
value whatsoever.  In your example idxType is undefined
at the entry to the initializer.

As you know, during phase 1 the compiler considers
each field in order and determines whether the body
defines the initial value or if it should use an appropriate
default.

I think this seems very natural in the following variation
of your program

record Foo {
  var x : int = 10;
  var y : int = 20;
  vaz z : int =  0;

  proc init(a : int = x + y) {
    x = 1;
    y = 2;
   z = a;

   super.init();
}


The current language definition says that the
value of ‘a’ cannot be determined, rather than
inferring that it is 30.

This seems like the right choice to us but I
could envisage language designers who
took the alternative position.


For good and for bad, but mostly for good I think,
the compiler currently applies the same logic to
the “initialization” of param/type fields as value fields.


This is despite a recognition that param/type “fields”
are not “initialized” in quite the same way as
value fields.

Binding a param/type field is something that occurs
at compile time in order to generate a concrete
instantiation of a generic type.  This is clearly
distinct from initializing a type-field at execution
time.





Mike



On Dec 5, 2017, at 10:52 AM, Nick Park <notifications@github.com<mailto:notifications@github.com>> wrote:


you're trying to use the field but the field doesn't know what it is yet

@lydia-duncan<https://github.com/lydia-duncan> The compiler isn't aware of idxType even though type idxType = int; is defined in Foo?

**Comment by noakesmichael** [comment]
On Dec 5, 2017, at 2:18 PM, Mike Noakes <mnoakes@cray.com<mailto:mnoakes@cray.com>> wrote:

Hi Nick,


This is an interesting program and I think it raises some
interesting questions but, after a minor mis-step on my
part, I conclude that the current behavior is the one we
want.


The current position is that a “field initializer expression”
does not provide an “initial value” for a field.  Instead it
is a “last resort” if you will.

At the entry to an initializer, none of the fields have any
value whatsoever.  In your example idxType is undefined
at the entry to the initializer.

As you know, during phase 1 the compiler considers
each field in order and determines whether the body
defines the initial value or if it should use an appropriate
default.

I think this seems very natural in the following variation
of your program

record Foo {
  var x : int = 10;
  var y : int = 20;
  vaz z : int =  0;

  proc init(a : int = x + y) {
    x = 1;
    y = 2;
   z = a;

   super.init();
}


The current language definition says that the
value of ‘a’ cannot be determined, rather than
inferring that it is 30.

This seems like the right choice to us but I
could envisage language designers who
took the alternative position.


For good and for bad, but mostly for good I think,
the compiler currently applies the same logic to
the “initialization” of param/type fields as value fields.


This is despite a recognition that param/type “fields”
are not “initialized” in quite the same way as
value fields.

Binding a param/type field is something that occurs
at compile time in order to generate a concrete
instantiation of a generic type.  This is clearly
distinct from initializing a type-field at execution
time.


<Sorry.  "Initializing a variable field at execution time”>

Mike







Mike



On Dec 5, 2017, at 10:52 AM, Nick Park <notifications@github.com<mailto:notifications@github.com>> wrote:


you're trying to use the field but the field doesn't know what it is yet

@lydia-duncan<https://github.com/lydia-duncan> The compiler isn't aware of idxType even though type idxType = int; is defined in Foo?

**Comment by nspark** [comment]
Thanks @noakesmichael and @lydia-duncan!
