### ISSUE TITLE
internal error: IPE0098

### ISSUE THREAD

**Issue by hariharanj4v4** [chapel-lang/chapel#8057]
### Summary of Problem
The error occurs in 'chpl-ipe' when intended to use any module with the 'use' keyword.

### Steps to Reproduce

**Execution command:**
 chpl-ipe

### Configuration Information

- Output of `chpl --version`: 
chpl Version 1.16.0
- Output of `$CHPL_HOME/util/printchplenv --anonymize`:
CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: gnu
CHPL_TARGET_ARCH: native
CHPL_LOCALE_MODEL: flat
CHPL_COMM: none
CHPL_TASKS: qthreads
CHPL_LAUNCHER: none
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_MAKE: make
CHPL_ATOMICS: intrinsics
CHPL_GMP: gmp
CHPL_HWLOC: hwloc
CHPL_REGEXP: re2
CHPL_WIDE_POINTERS: struct
CHPL_AUX_FILESYS: none

- Back-end compiler and version, e.g. `gcc --version` or `clang --version`: 
gcc (Ubuntu 6.3.0-12ubuntu2) 6.3.0 20170406

**Comment by ben-albrecht** [comment]
Thanks for reporting this @hariharanj4v4. 

@bradcray's comment on #6760 is also related here:

>In the spirit of full disclosure, I should mention that the ipe has received very little attention over the past several releases, not due to lack of interest, but lack of resources and a need to more fully re-architect our compiler to better support an interpreted/interactive mode. We wish we could spend more time on it, but have been unable to do so recently.

**Comment by bradcray** [comment]
The `use` of modules is outside of the set of features that are documented as being supported by `chpl-ipe` in its initial release:

https://chapel-lang.org/docs/1.16/technotes/chpl-ipe.html#the-ipe-subset-of-chapel

That doesn't mean that an internal error is reasonable, but I'm not surprised that the feature doesn't work...

Since I wrote the comment on issue #6760, interest in putting more effort into `chpl-ipe` has grown considerably, and I'm hoping 2018 will afford us more time work on it.

**Comment by bradcray** [comment]
Support for chpl-ipe has been removed.  We hope to return to an interactive mode for Chapel in the coming years, but have decided to take a different approach than chpl-ipe.
