### ISSUE TITLE
Provide version selection menu on Chapel Documentation page

### ISSUE THREAD

**Issue by buddha314** [chapel-lang/chapel#8114]
When doing a Google search for [Chapel Docs](https://chapel-lang.org/docs/1.12/index.html), you typically get older versions.  V. 12 seems popular.  Postgres has provided a version selection menu at the top of their [documentation](https://www.postgresql.org/docs/9.5/static/index.html) that allows you to get to the current version independent of what your search engine thinks you should be reading.

**Comment by bradcray** [comment]
We've long discussed making the version number in the upper-left of the Chapel docs pages be a pull-down menu allowing one to select the version, but nobody's ever taken that on (I'm not sure what the level of effort would be.

I wondered whether v1.12's popularity with Google might be because we stopped embedding Google-specific metadata into the html files with that release (out of laziness / forgetfulness), but it looks like we included them for 1.13 as well.  So maybe it's just when Google and users first started discovering them heavily?  This makes me wonder whether there's metadata that can be provided to Google to say "prefer this version" of these files that are very similar from release to release...

**Comment by buddha314** [comment]
Here is a [Stack Overflow](https://stackoverflow.com/questions/28849284/how-do-i-have-multiple-versions-of-my-doc-with-sphinx) about multiple versions on Sphinx.

FWIW, DuckDuckGo returns a hodgepodge of 1.12, 1.13, 1.15 and 1.16.

**Comment by bradcray** [comment]
@ben-albrecht : I feel like you know our use of the sphinx stuff best.  Any chance you'd be able to look into the Sphinx extension mentioned on the SO page @buddha314 references to see what level of effort would be required for us to make use of it?

**Comment by ben-albrecht** [comment]
I believe the challenge with the `sphinxcontrib-versioning` extension is that it requires rebuilding all of the existing documentation with the extension, which would be difficult, since there were many post-release documentation edits throughout the releases. 

That said, I think it'd be a good idea to start using this extension going forward. We can probably hack together a solution for previous versions if we think it'd be useful enough.

**Comment by bradcray** [comment]
> which would be difficult, since there were many post-release documentation edits throughout the releases

It seems in any reasonable solution, the "menu" providing the list of versions would be stored in a file independent from the source html files themselves so that old versions of docs wouldn't need to be updated to be able to refer to the newer versions (?), is that right?  If so, it may be a simple matter of finding the delta in html between our current docs and the ones that "`#include`" the menu code and running a script over the static html to update it in that respect (?).

In other news, I've been googling for information about "latest versions of docs" and the main advice seems to be about moving the latest version up one level in the directory hierarchy, similar to what we've discussed in other contexts for simpler URLs to get to the "current" docs.  Combining this with removing links within the website to the older versions of docs (other than the aforementioned menu, if we can implement it) may be enough to make Google prefer the latest docs.

**Comment by buddha314** [comment]
My opinion is that going forward would be good unless it's really cheap to do the last few releases. Maybe for those just put a banner saying "latest" and point to master.

**Comment by ben-albrecht** [comment]
> It seems in any reasonable solution, the "menu" providing the list of versions would be stored in a file independent from the source html files themselves so that old versions of docs wouldn't need to be updated to be able to refer to the newer versions (?), is that right?

I am not positive, but that's what I would assume too.

> If so, it may be a simple matter of finding the delta in html between our current docs and the ones that "#include" the menu code and running a script over the static html to update it in that respect (?).

This is what I had in mind when I wrote:

>> We can probably hack together a solution for previous versions if we think it'd be useful enough.

**Comment by bradcray** [comment]
OK.  So it seems like a good first step would be to try generating a 'master' copy of the docs with and without the extension and then doing a diff on the generated files to see how they differ.

**Comment by bradcray** [comment]
Update on this issue:  @ben-albrecht implemented a prototype ability to switch to other versions that follows the lead of read-the-docs.  Currently, it appears at the bottom of the sidebar and leads to the root doc for that version.  @benharsh has agreed to briefly look into how hard it might be to make a little widget that would cause the existing version number at the top of the page turn into a pulldown menu permitting versions to be selected.  Ideally, I think doing so should take one to the same URL, simply with a new version number inserted (and maybe something nice if that version of the docs didn't have such a doc).

One other thing related to this issue that seemed attractive to me was something that would visibly warn users that they were referring to an old version of the docs if they landed on something other than 'latest'.  Perhaps this could even be worked into this same widget and make the version number red or something like that (?).

**Comment by bradcray** [comment]
Update on this issue: @benharsh has a prototype that supports a pull-down menu to select between versions of a given documentation page (currently requires that prior versions shared the same URL pattern).  Some work will still be required to apply this to old drafts of the documentation (and I've offered to help with that effort).

**Comment by bradcray** [comment]
This afternoon, with ongoing help from @benharsh, I propagated the menu back to earlier versions of the documentation and also set up a redirection so that if a given document doesn't exist in a given version of the documentation, you're kicked to the front page for that version instead of getting a 404.  Take a look and see if you think this is sufficient to close this issue @buddha314 .  As a follow-up, I'm going to explore a reorganization of our docs hierarchy in hopes that it will help Google point to the latest released version of the docs rather than stale versions.

**Comment by buddha314** [comment]
Cool!  This will be very useful, I think. At least it will help me. DuckDuckGo has gotten better about pointing to 1.16.  From my perspective, this seems close-worthy!

**Comment by bradcray** [comment]
Thanks Brian!
