### ISSUE TITLE
When should we set GASNET_MAX_SEGSIZE?

### ISSUE THREAD

**Issue by ronawho** [chapel-lang/chapel#8199]
Currently, we (mistakenly) set `GASNET_MAX_SEGSIZE` only when we're _not_ on a cray: 
https://github.com/chapel-lang/chapel/blob/f3613c87d22c75f91e77d72773523868bdf9ef1c/third-party/gasnet/Makefile.setup#L33-L35
https://github.com/chapel-lang/chapel/blob/f3613c87d22c75f91e77d72773523868bdf9ef1c/runtime/src/comm/gasnet/comm-gasnet.c#L764-L777

We used to only set it when we were on a cray, but that condition was accidentally reversed with 1d5e2442d6

It seems weird to base whether we're setting `GASNET_MAX_SEGSIZE` on the system. It seems like we should only set `GASNET_MAX_SEGSIZE` when we're using segment fast/large.

From the gasnet docs:

```
--with-segment-mmap-max=<n>GB - configure maximum segment size.
  Many of the GASNet network conduits obtain memory for the shared segment
  (in FAST and LARGE segment configurations) using mmap().
...
* GASNET_MAX_SEGSIZE - control the upper limit for FAST/LARGE segment size 
```

I think we should adjust our code to set segsize only for segment fast/large. I'd also like to confirm that setting this only impacts performance, and not correctness.

**Comment by ronawho** [comment]
>I think we should adjust our code to set segsize only for segment fast/large. I'd also like to confirm that setting this only impacts performance, and not correctness.

@bonachea and/or @PHHargrove if you get a second, could you weigh in this?

**Comment by PHHargrove** [comment]
The environment variable `GASNET_MAX_SEGSIZE` has no impact at all for segment everything.

For segment fast / large it may limit the maximum size of the GASNet segment.  
I say "may" because other factors may impose a tighter limit.  
However, the available segment size will not exceed the value of this environment variable.  

As to the "only impacts performance, and not correctness" issue:   
So long as you are not choosing an absurdly small value, there is no correctness impact on GASNet.

**Comment by mppf** [comment]
I believe that part of our setting GASNET_MAX_SEGSIZE is so that we can propagate CHPL_RT_MAX_HEAP_SIZE to that variable (so Chapel users don't have to use the GASNet-specific setting). That started in commit 769efae6cd16dfbe5529b2caed4c10b49237ad0e.

There's another part, though; we used to set it on Cray X* systems for some reason. From that commit message:

> If neither is set and we really need a max segment size, as when
> using the gemini or aries conduits on Cray X* systems, default to 90%
> of the available memory on the locale.

Did GASNet require setting GASNET_MAX_SEGSIZE on gemini/aries at some point in the past & then stop doing so? Or are we just currently using a sub-optimal default?

From the GASNet docs:

>     --with-segment-mmap-max=<n>GB - configure maximum segment size.
>       Many of the GASNet network conduits obtain memory for the shared segment
>       (in FAST and LARGE segment configurations) using mmap().  By default
>       GASNet will use a very conservative (2GB minus pagesize) maximum value
>       for calls to mmap().  This configure option allows one to raise that
>       to a value more appropriate to your platform.  See also the description
>       below for the GASNET_MAX_SEGSIZE environment variable, for information
>       on the two setings which take precedence over this configure setting.

So, it sounds like if we don't set GASNET_MAX_SEGSIZE, we'll get ~2GB.

So, assuming that this setting matters at all for performance, I'd expect better performance (for  benchmarks using lots of memory remotely, RA?) once we start setting it to any value > 2GB.

@ronawho - would you be up for doing some experiments to determine if any of our benchmarks go faster with a segment > 2GB & complete whatever implementation needs to happen? (You might start with my branch https://github.com/mppf/chapel/tree/fix-GASNET_NEEDS_MAX_SEGSIZE ).

**Comment by ronawho** [comment]
Yeah, I ran performance testing for gasnet-aries yesterday hoping/expecting that there'd be some improvements, but unfortunately I didn't see any changes for any of the multi-locale performance tests.

Maybe segsize matters for other networks/conduits like IBV?

**Comment by mppf** [comment]
I'd like to create an issue about *how* we're setting GASNET_MAX_SEGSIZE (using the amount of free memory reported - but that doesn't account for reclaimable memory like the page cache).
But that seems like we first need to know if it's still important to set it.

**Comment by ronawho** [comment]
I'll make a PR for https://github.com/mppf/chapel/tree/fix-GASNET_NEEDS_MAX_SEGSIZE today, but I really have no sense of whether it's "worth" setting `GASNET_MAX_SEGSIZE`. It didn't impact performance for gasnet-aries, and we don't have any other performance testing for large/fast segments.

If we ever get around to https://github.com/chapel-lang/chapel/issues/6324, we would have some IBV performance testing, but that's not anywhere on the current priority list.

**Comment by ronawho** [comment]
As of 1.32.0 it looks like GASNet defaults to 85% now, so we may want to just stop setting MAX_SEGSIZE and only override if `CHPL_RT_MAX_HEAP_SIZE` is set: 

https://bitbucket.org/berkeleylab/gasnet/src/7f48fc9651187c5b9f3b15aa77274e669f8ec91c/ChangeLog?at=gasnet-1.32.0&fileviewer=file-view-default#ChangeLog-54:55

**Comment by bonachea** [comment]
@ronawho : Agreed - this change was motivated by the request from the Chapel team (and it also helped us clean up lots of internal goop in BUPC and UPC++).

We're hoping most clients will be able to use the default and never need to think about this option again.
