### ISSUE TITLE
Implementing gcd function in Math.chpl

### ISSUE THREAD

**Issue by victor-ludorum** [chapel-lang/chapel#8324]
As many languages have **gcd function** to calculate greatest common divisor , so I think this function should be implemented in Chapel too.
Please suggest !!

**Comment by mppf** [comment]
I think it'd be reasonable to add `proc gcd(arg1: int, arg2: int) : int ` to Math.chpl.

**Comment by nimitbhardwaj** [comment]
Hey, isn't it already in BigInteger, if its still required, then why not add the other number theory functions in Math.chpl.
But they are already there in BigInteger, just wrappers over GMP, as I saw code there, I also thought there would be need of em, but then I got that they are implemented.

One thing not there is nCr, nPr etc which are necessary functions for Combinatorics. Catalan's number etc, I thought they would be there, but I feel they are sometimes necessary.

**Comment by mppf** [comment]
It'd be reasonable to create a new package if we want to add a lot of combinatiorics functions.

**Comment by nimitbhardwaj** [comment]
Yeah, a new package is better, because Math is something different, number theory is different, even number theory is part of math, may be not explaining correctly, in computer science we study the algorithms regarding the number theory, like implementing these functions, sieve, prime numbers etc other things

**Comment by victor-ludorum** [comment]
@nimitbhardwaj I have also checked those modules . But those are related with BigInteger and gcd is common function which should be present in standard math module . Therefore, I have thought to implement in Chapel module. 

> One thing not there is nCr, nPr etc which are necessary functions for Combinatorics. Catalan's number etc, I thought they would be there, but I feel they are sometimes necessary.

Actually problem with nCr and nPr function is that they may give very large values to some small input due to factorial which is difficult to be stored in any datatype . I think this may be reason that C++ or python has no inbuilt function for nCr or nPr .

**Comment by nimitbhardwaj** [comment]
Cool bro

**Comment by mppf** [comment]
https://chapel-lang.org/docs/master/modules/standard/BigInteger.html#BigInteger.bigint.bin

> One thing not there is nCr, nPr etc which are necessary functions for Combinatorics. Catalan's number etc, I thought they would be there, but I feel they are sometimes necessary.

The BigInteger module does include the way to compute the binomial coefficient (n choose k) https://chapel-lang.org/docs/master/modules/standard/BigInteger.html#BigInteger.bigint.bin

I'm not familiar with all of the functions you're talking about but it seems to me that most of these do not operate simply on integers (and would require bigint, say).

> Yeah, a new package is better, because Math is something different, number theory is different,

I think it's reasonable to put `gcd` in Math because:
 a. it's used more commonly than these others
 b. it has a reasonably simple implementation that does not require new data types

In Python, they put `gcd` in the `fractions` module. But it seems that the primary purpose of the Fractions module is to support rational numbers (`a/b`). So it seems odd to me that `gcd` is in there, when it operates strictly on integers.

**Comment by ben-albrecht** [comment]
Having `gcd` in the Math module sounds reasonable to me.

**Comment by mppf** [comment]
I think there's enough support to put gcd in Math at this point (but of course others are welcome to comment still).

**Comment by nimitbhardwaj** [comment]
I think there should be the other overload of the gcd function, its gcd of an array, it sometimes handy, just do gcd(a, b, c) = gcd(a, gcd(b, c)), applying similarly on the array, also there should be lcm if possible

**Comment by victor-ludorum** [comment]
Yeah!! @nimitbhardwaj After gcd I will go to implement lcm of two numbers . As, that function too is important and useful . Actually I have also thought of gcd of array function . But as it has not been implemented in any language I have checked so far i.e. in C++ or python . So, if it is acceptable , I will always go for it

**Comment by mppf** [comment]
Re the gcd(a,b,c) you can implement this with a var-args function. See https://chapel-lang.org/docs/master/primers/varargs.html - but that could come in a different PR as it's a separate function.

LCM it seems to me is more likely to need a larger data type, and so by my reasoning doesn't belong as obviously in Math. I'm certainly open to seeing one, but there's already one in GMP/biginteger (https://chapel-lang.org/docs/master/modules/standard/BigInteger.html#BigInteger.bigint.lcm). @victor-ludorum - it would help matters greatly if you or somebody would write some documentation for the BigInteger methods.

**Comment by victor-ludorum** [comment]
Okay @mppf  !! After gcd function , I will make another PR regarding gcd() for an array .
And for documentation part of BigInteger, I will work on that too for those methods .

**Comment by nimitbhardwaj** [comment]
Hey, what about making gcd of multi parameters, I want to do it, how about it, if it don't bother anyone, I wanted to deal with multiple parametes of the language, can I ??

**Comment by mppf** [comment]
@nimitbhardwaj - I think that's between you and @victor-ludorum but I'd expect you to give @victor-ludorum the first chance to try it or to decline to do so, to be polite.

**Comment by victor-ludorum** [comment]
Yeah!! Sir it would be great to work collaboratively 😊 !!

**Comment by nimitbhardwaj** [comment]
Yeah, sounds cool, and also nice to work collaboratively, cool for me, I can help, I have a good hand on data structures and algorithms and also number theory.:smile:

**Comment by mppf** [comment]
Implemented in just-merged PR  #8325.
