### ISSUE TITLE
Anonymous Function with scope variable Bug

### ISSUE THREAD

**Issue by marcoscleison** [chapel-lang/chapel#8350]
I would like to create an anonymous function inside a function such way it uses variables declared outside its scope.
Here the example:
```chapel
module Main{
    proc main(){
        var x = 10;

        var foo = lambda(z: int) { return z * x; };

        writeln(foo(3)); /it would output 30

    }
}

```

But the compiler says:
```bash
$ chpl -o ./bin/test ./examples/test.chpl -M ./src -levent -I ./src/
.test.chpl:2: In function 'main':
test.chpl:7: internal error: CAL1326 chpl version 1.17.0 pre-release (4b9d25676f)

Internal errors indicate a bug in the Chapel compiler ("It's us, not you"),
and we're sorry for the hassle.  We would appreciate your reporting this bug --
please see https://chapel-lang.org/bugs.html for instructions.  In the meantime,
the filename + line number above may be useful in working around the issue.

```
What does it means?
Thank you very much.

**Comment by mppf** [comment]
Hi @marcoscleison - first class functions (lambdas) aren't really completely designed or completely implemented.

In fact I disabled this functionality in PR #4794 since it was impeding progress in other areas of the compiler. From strictly a language design point of view, I don't think we've yet decided if such capturing is legal.

But note, the `lambda` support in the current compiler actually operates by creating a class with a `this` method. So you can probably do the same - create a "function object" - that has the same effect. E.g.

``` chapel
proc main(){
  var x = 10;

  record Lambda {
    proc this(z:int) {
      return z*x;
    }
  }
  var foo = new Lambda();

  writeln(foo(3)); //it would output 30

}
```

**Comment by marcoscleison** [comment]
Hi @mppf , thank you very much.
I will try to use you tip.

**Comment by lydia-duncan** [comment]
I think it would be fine to leave this open, since we should give you a better error than an internal compiler error
