### ISSUE TITLE
is in task intent racey?

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#8416]
I'm working on a PR (#8417) that adjusts the `in` argument to perform the copy at the call site rather than in the called function. This effort led me to the realization that the current task intent implementation, for `in` intent, piggybacks on the compiler's existing argument intent implementation, which adds the copy to the body of the called function. That has the result of creating potentially surprising behavior, since a user might imagine that if the `in` task intent is used, it's not possible to race on that variable. But it is possible to have a race there, since the copy happens within the task.

Below is a complete program that reproduces this problem. On master, this consistenly prints out something like:
```
serial has 0 mismatches
begins has 6007 mismatches
```

but on my in-progress in-intent branch (PR #8417), which moves the copy to the call site (i.e. out of the task function and instead performs the copy in the process of creating the task argument bundle), it prints out:
```
serial has 0 mismatches
begins has 0 mismatches
```

The question is, do we consider the below program a wrong program? (If so, what should the user have written instead to synchronize correctly?).

``` chapel
class Impl {
  var x:int;
}

record R {
  var ptr:Impl;
}

proc R.init() {
  this.ptr = new Impl(0);
}

proc R.deinit() {
  delete this.ptr;
}

proc R.init(from:R) {
  this.ptr = new Impl(from.ptr.x);
}

proc =(ref lhs:R, rhs:R) {
  lhs.ptr = new Impl(rhs.ptr.x);
}

proc R.increment() {
  this.ptr.x += 1;
}


config const n = 10000;
config const debug = false;

proc report(phase, hits) {

  var mismatches = 0;
  for i in 0..#n {
    var count = hits[i].read();
    if count != 1 {
      mismatches += 1;
      if debug then
        writeln(phase, " hits count ", i, " is ", count, " not 1!");
    }
  }

  writeln(phase, " has ", mismatches, " mismatches");
}

proc test() {

  {
    var hits:[0..n] atomic int;

    var r:R;

    // First, run the pattern in a serial loop
    for i in 0..#n {
      hits[min(n,r.ptr.x)].add(1);
      r.increment();
    }

    // Report any hits != 1
    report("serial", hits);
  }

  {
    var hits:[0..n] atomic int;

    var r:R;

    // Now, run it with a begin per iteration
    sync {
      for i in 0..#n {
        begin with (in r) {
          hits[min(n,r.ptr.x)].add(1);
        }
        r.increment();
      }
    }

    // Report any hits != 1
    report("begins", hits);
  }
}

test();
```

**Comment by mppf** [comment]
I suspect making this change to `in` intent would also have the effect of changing to which task "first touch" might apply - and for that reason it could possibly have (negative) performance impact. However I think I'd rather have something I view as correctness (which others might view as simpler `in` intent semantics).

**Comment by vasslitvinov** [comment]
If `R` defined serialization, when would the initializer run - an actual call to init() or conceptually?
We probably want the cases "R with serialization" and "R without serialization" to have (at least conceptually) similar behavior.

I suggest that we want "snapshots" of an outer variable passed by an `in` intent - including running the copy initializer - to occur when the task is created, not when it starts executing. That way, for example, all iterations of a `coforall` start out with a copy of the outer variable taken at the same time, rather than at potentially different times.

Simplifying the situation to an integer:
```chpl
var i: int;
....
coforall ... with (in i) do writeln(i);
```
we want the guarantee that all iterations print the same `i` -- even when there are concurrent updates to `i`.

Tagging @benharsh as this relates to serialization.

**Comment by dmk42** [comment]
I'm strongly in favor of this not being a user bug.  It's downright scary.

**Comment by benharsh** [comment]
@vasslitvinov : serialization (currently) only applies to on-statements. It calls serialize() on the source locale and calls deserialize on the destination locale. Serialization is still poorly-defined, so I think we should focus on non-serialized cases to start.

I agree with @dmk42 : this should not be on the user to fix.

**Comment by vasslitvinov** [comment]
To support in-intent making copy at task creation, rather than within the task function, we can make a simpler argument: a record wrapping an integer should behave like an integer by itself:

```chpl
// print each digit once
var i = 0;
while i < 10 {
  begin with (in i) do writeln(i);
  i += 1;
}

// ditto
record R { var i: int; }
var r = new R(0);
while r.i < 10 {
  begin with (in r) do writeln(r.i);
  r.i += 1;
}
```

The desired behavior is guaranteed only when the outer integer and the outer record are captured at task creation.
