### ISSUE TITLE
Support assumed-domain array return types

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#8468]
### Summary of Problem

Today, if you want to return an array of completely unknown size, the main way you have
of doing so is to have the return type be inferred.  But for those who want to say more
about what their procedure is returning (for readability; for checking themselves), it'd
be nice to support an assumed-domain array return type as we do for formal arguments.
I.e., `proc foo(): [] real { ... }` would say "foo() returns an array of reals, but we aren't saying
(maybe can't say) how big / what type of array it is."

[edit: Just as formals support an element-type-less `proc foo(X: [])` format, I think we'd want
to do the same with this feature, though I didn't think of that fast enough to get it into my
future].

### Steps to Reproduce

**Associated Future Test(s):**
[`test/arrays/return/returnArbitraryArray.chpl`](
           https://github.com/chapel-lang/chapel/blob/master/test/arrays/return/returnArbitraryArray.chpl
          ) #8466

### Configuration Information

- Output of `chpl --version`: `chpl version 1.17.0 pre-release (6b89687)`

**Comment by bradcray** [comment]
Note that this issue is related to #8469.

**Comment by lydia-duncan** [comment]
Does this also mean that recursive functions can't return arrays?

**Comment by bradcray** [comment]
Today I believe it is accurate that recursive functions can't return arrays.  We've had a long-term academic user who's bristled over this for years.

**Comment by lydia-duncan** [comment]
I would like to up the priority on this issue.  It forces me to support inferred returns from exported functions that return an array, especially in the case of an exported function like the following code.  Only supporting explicit return type declarations would have been a nice simplifying case while I got this feature off the ground.

```chapel
export proc foo(size: int) /*: [] int*/ {
  var x: [0..#size] int;
  return x;
}
```

Additionally, it would improve documentation for functions that otherwise have to use inferred returns.
