### ISSUE TITLE
RangeChunk's chunks should use 1-based indices

### ISSUE THREAD

**Issue by psahabu** [chapel-lang/chapel#8484]
@ben-albrecht noticed that `RangeChunk.chpl` uses 0-based indices when referring to chunks. Given the recent move of `LinearAlgebra` to 1-based indices, and the overall orientation of Chapel to 1-based indices, `RangeChunk` should be brought in line.

**Comment by ben-albrecht** [comment]
It just occurred to me that `RangeChunk` tends to interact with `numTasks` or `numLocales`, which are system resources and tend to use 0-based indices. That may have been the original idea behind this decision. I still like 1-based indices, but that makes it a little more understandable.

**Comment by bradcray** [comment]
This seems surprising to me.  I'd expect `RangeChunk()` to take a range and either (a) return the range's native indices (whether they were 0-based, 1-based, or -3-based) or (b) return indices that will work in a leader-follower context for our typical interface (which I believe is dense and 0-based regardless of the original indices).

In wht way does RangeChunk() have to choose an indexing scheme?

**Comment by psahabu** [comment]
@bradcray: Within `RangeChunk` there is a notion of an "nth chunk", where n is zero-based, and some procedures allow the user to query the nth chunk. The indices themselves can be whatever-based, as you pointed out.

**Comment by bradcray** [comment]
OK, thanks for clarifying.  So we're talking about the numbering used by the input arguments rather than the output indices that it's yielding.  I didn't understand that from the issue title/description.

This seems like one of those "no answer will make all users happy" types of issues.

One way to make it neutral at the cost of complicating the interface slightly would be to have the callee pass in a range representing the chunks (e.g., `1..numChunks` or `0..#numChunks` or whatever and then have `idx` be a member of that range such that they could pick the indexing scheme.  I'm not sure this is great, but if most callsites that we care about already had a range like this that they were iterating over, it might not be that weird...

**Comment by psahabu** [comment]
Most callsites probably won't have their own indexing range for iteration because `RangeChunks` already provides iterators that ignore the chunk indexing entirely. In this example, despite the comment, the user does not need to worry about `idx`:

``` chapel
/*
   Iterates through chunks ``0`` to ``numChunks - 1`` of range ``r``, emitting each
   as a range. The remainders will be distributed according to ``remPol``.
*/ iter chunks(r: range(?RT, bounded, ?S), numChunks: integral,
            remPol: RemElems = Thru): range(RT, bounded, S)
```

Hence indexing chunks is something of a special case, so it's reasonable to choose one scheme over the other.

**Comment by bradcray** [comment]
@ben-albrecht: I wonder whether we can close this now that most of Chapel's implicit indices have gone to 0-based indexing?
