### ISSUE TITLE
Generate type constructors based on initializers

### ISSUE THREAD

**Issue by benharsh** [chapel-lang/chapel#8499]
### Summary of Problem
Consider the following program:
```chpl
record R {
  type t;
  param b : bool;

  proc init(type t = int, param b : bool = false) {
    this.t = t;
    this.b = b;
    super.init();
  }
}

var r : R; // wants the default of R(int, false)
```

This program fails to compile on master with the error message:
```
foo.chpl:12: error: Variables can't be declared using not-fully-instantiated generic types like 'R'
```

Should this be a valid program? With a simple program like this, the compiler could build a type constructor based on the initializer, but what if there were multiple initializers?

If not, the only other existing way to achieve this behavior is to add defaults for the type/param fields:
```chpl
type t = int;
param b : bool = false;
```

Is that an acceptable 'solution'?

Note that ranges rely on this ability (``var r : range``), and currently require defaults for the fields.

## Associated Future Test(s)
[`test/classes/initializers/generics/declarations/argument_type.chpl`](https://github.com/chapel-lang/chapel/blob/master/test/classes/initializers/generics/declarations/argument_type.chpl)
[`test/classes/initializers/generics/declarations/concrete-inits.chpl`](https://github.com/chapel-lang/chapel/blob/master/test/classes/initializers/generics/declarations/concrete-inits.chpl)
[`test/classes/initializers/generics/declarations/concrete-inits-bad.chpl`](https://github.com/chapel-lang/chapel/blob/master/test/classes/initializers/generics/declarations/concrete-inits-bad.chpl)
[`test/classes/initializers/generics/declarations/concrete-inits-multiple-bad.chpl`](https://github.com/chapel-lang/chapel/blob/master/test/classes/initializers/generics/declarations/concrete-inits-multiple-bad.chpl)
[`test/classes/initializers/generics/declarations/concrete-inits-multiple.chpl`](https://github.com/chapel-lang/chapel/blob/master/test/classes/initializers/generics/declarations/concrete-inits-multiple.chpl)
[`test/classes/initializers/generics/declarations/default_value.chpl`](https://github.com/chapel-lang/chapel/blob/master/test/classes/initializers/generics/declarations/default_value.chpl)
[`test/classes/initializers/generics/declarations/default_value_bad.chpl`](https://github.com/chapel-lang/chapel/blob/master/test/classes/initializers/generics/declarations/default_value_bad.chpl)
[`test/classes/initializers/generics/declarations/no-arg-param.chpl`](https://github.com/chapel-lang/chapel/blob/master/test/classes/initializers/generics/declarations/no-arg-param.chpl)
[`test/classes/initializers/generics/declarations/no-arg-type.chpl`](https://github.com/chapel-lang/chapel/blob/master/test/classes/initializers/generics/declarations/no-arg-type.chpl)
[`test/classes/initializers/generics/declarations/same_type_function_equally_good.chpl`](https://github.com/chapel-lang/chapel/blob/master/test/classes/initializers/generics/declarations/same_type_function_equally_good.chpl)
[`test/classes/initializers/generics/declarations/unusual-param-arg.chpl`](https://github.com/chapel-lang/chapel/blob/master/test/classes/initializers/generics/declarations/unusual-param-arg.chpl)
[`test/classes/initializers/generics/declarations/unusual-type-arg.chpl`](https://github.com/chapel-lang/chapel/blob/master/test/classes/initializers/generics/declarations/unusual-type-arg.chpl)
[`test/classes/initializers/generics/declarations/unusual-var-arg.chpl`](https://github.com/chapel-lang/chapel/blob/master/test/classes/initializers/generics/declarations/unusual-var-arg.chpl)

**Comment by benharsh** [comment]
I think something like this has been brought up in other past discussions, but what if we allowed record/class authors to implement their own type constructors?

```chpl
proc R.type(type t = int, param b : bool = false) {
  this.t = t;
  this.b = b;
}
```

Then a statement like:
```chpl
var r : R;
```
becomes
```chpl
var r : R.type();
```

**Comment by bradcray** [comment]
> With a simple program like this, the compiler could build a type constructor based on the initializer, but what if there were multiple initializers?

Presumably there would only be one initializer that accepted zero arguments, though, right?

For me a major recurring question here is whether `R` should be legal, or whether one should have to type `R()`.  It's certainly convenient to just be able to type `R`, but I could also see an argument that it's inconsistent with function calls.  OTOH, types are semantically easy for the compiler to distinguish from expressions.

I'm also open to the notion of having a separate type constructor declaration style, though I wonder how often they will differ from the ones the initializers would create (i.e., would they result in annoying code duplication / more typing for the common cases).

**Comment by benharsh** [comment]
> Presumably there would only be one initializer that accepted zero arguments, though, right?

I think that's correct.

> I'm also open to the notion of having a separate type constructor declaration style, though I wonder how often they will differ from the ones the initializers would create (i.e., would they result in annoying code duplication / more typing for the common cases).

I also share that concern.

**Comment by cassella** [comment]
The type constructor approach implies that there'd be a ``super.type(...)`` call?  Would you entertain ``this.type()``?

OOC, when using an initializer as a type constructor, if the initializer does non-trivial work (e.g., reading a file to initialize values), would the compiler be able to skip that work when constructing the type?

**Comment by lydia-duncan** [comment]
Part of the challenge with an explicit type constructor is determining which initializer it would correspond to in the record declaration use case (i.e. `var x: R(args);`, which always tries to initialize what it has declared).  Generating the type constructor from the initializers removes that concern, though it does lead to the possibility of conflicts between the generated type constructors.

@cassella - at the moment we always call the initializer after the type constructor for records, and only call it for classes if an explicit `new` call is present.  I don't anticipate changing that behavior, but that doesn't mean we won't.  It just doesn't quite seem sufficiently motivated at this time to me.

**Comment by mppf** [comment]
When I correct the program in the issue description (to match current initializer design) it compiles and runs (and seems to work, to my mind):

``` chapel
record R {
  type t;
  param b : bool;

  proc init(type t = int, param b : bool = false) {
    this.t = t;
    this.b = b;
    this.complete();
  }
}

var r : R; // wants the default of R(int, false)
writeln(r.type:string, " ", r);
```

Can this issue be closed?

**Comment by mppf** [comment]
In PR #14917 I am changing the way default variable initialization are handled in the compiler and it's causing the above program to no longer compile.

It seems to me that `var r: R` should not be legal because `R` is a generic type (and it does not have defaults, even). If we were to make it legal, would it introduce an inconsistency with `var r: R = something` ? In this 2nd option, the type `R` is taken as the generic type, not the result of `R.init()`.

**Comment by mppf** [comment]
I see 4 different questions here:

### 1. can record default initialization init override type

In default-initialization of a concrete instantiation of a generic record, e.g. `var x: R(int)`, can an initializer override the field type provided, to e.g. to set the field type to `real` ?

``` chapel
record R {
  type t;
  var field: t;
}

proc R.init(type t) {
  this.t = real;
  field = 1.0;
}

var x: R(int);
writeln(x.type:string, " ", x); // currently prints R(real(64)) (field = 1.0)
```

This seems to me to be a type error. The compiler should insist that both types match in such cases. Otherwise I think that the resulting programs can be unnecessarily confusing. Making sure the type field matches also aligns with the strategy for `init=`.

### 2. can a variable of generic record type be default-initialized if the init accepts 0 arguments?

Is default-initialization of a generic record allowed, e.g. `var xx: R;`, `R.init()` resolves and sets the type field? 

``` chapel
record R {
  type t;
  var field: t;
}

proc R.init(type t=real) {
  this.t = t;
  field = 1.0;
}

var xx: R;
writeln(xx.type:string, " ", xx); // currently prints R(real(64)) (field = 1.0)
```

I would have expected that a generic type could not be default-initialized no matter how many arguments the init() function can accept. But, there might be a good reason to let the initializer construct the type that I'm not thinking of. This case is interfering with my out-intent PR #14917.

### 3. can record or class init called by `new` override the type

In a `new` call with a type alias for a class or record, such as `type t = C(int); var z = new t()`, can the initializer invoked override the field type from the type alias, e.g. to set the field type to `real` ?

``` chapel
class C {
  type t;
  var field: t;
}

proc C.init(type t) {
  this.t = real;
  field = 1.0;
}

type t = C(int);
var y = new t();
writeln(y.type:string, " ", y); // currently outputs owned C(real(64)) {field = 1.0}

record R {
  type t;
  var field: t;
}

proc R.init(type t) {
  this.t = real;
  field = 1.0;
}

type tt = R(int);
var yy = new tt();
writeln(yy.type:string, " ", yy);  // currently outputs R(real(64)) (field = 1.0)
```

Code doing this seems really confusing to me but it is arguably allowable under a strict interpretation of the default arguments rule for type aliases. I would favor making it an error though. (One implementation approach - the compiler could check that the result of a resolved new on a type is compatible with the new'd type).

4. When running `new` on a class or record with generic type, can the `init` call set a type field?

``` chapel
class C {
  type t;
  var field: t;
}

proc C.init() {
  this.t = real;
  field = 1.0;
}

var z = new C();
writeln(z.type:string, " ", z); // currently outputs owned C(real(64)) {field = 1.0}

record R {
  type t;
  var field: t;
}

proc R.init() {
  this.t = real;
  field = 1.0;
}

var zz = new R();
writeln(zz.type:string, " ", zz); // currently outputs R(real(64)) (field = 1.0)
```

This case seems to be desirable, not so confusing, and part of the goals of initializer design. If it were not supported, there would not be any point in setting type or param fields in initializers (apart from runtime types). Instead it would lead to a design where the type/param fields must be known prior to initialization. That leads to expressions like `new R<real>(1.0)` which have two argument lists. I think that is something to avoid.

**Comment by e-kayrakli** [comment]
@mppf -- I completely agree with your opinions for the 4 questions above, maybe except for 2. The case that brought me here is #14895. The relevant part of the issue is to give a deprecation warning for newly-generic `regexp` type when the user does `var r:regexp`. The intent there is to make `string` the default type via a `proc init()` and issue a compiler warning.

There might be similar cases where we can use a 0-arg init to generate a default type without actually giving default values to generic fields in class and records. I cannot come up with a more concrete example than this at the moment though. And I can sympathize with your argument against supporting this, as well.

**Comment by bradcray** [comment]
@e-kayrakli: I haven't spent much time thinking about this, so apologies if it's naive.  If the field type were default initialized to string and the default init didn't set it explicitly, but relied on that, would that get you to a working solution?  (then, in the next release, we could remove the 0-arg init and the field initializer?)

**Comment by e-kayrakli** [comment]
@bradcray I think that is prevented by something else (bug?, unimplemented feature?)

```chapel
record R {
  type t = string;

  proc init() {
    compilerWarning("No arg init");
  }
}

var r: R;
writeln(r.type:string);
```
compiler wants to call a `init(type t=string)` here. Resulting in `unresolved call 'R.init(t=type string)'` it may be slightly off-topic where we go from here, though.

**Comment by bradcray** [comment]
But you'll also need to define the overload that does take a `type t`, right?  That is: https://tio.run/##Vc4xDsMgDIXhnVM8ZYIlBwjqFTpk6YwoSixRQI7VqqpydkqCOnS1vt@2X10JsVYOPvMdMz4KkHcJEFywCVNarGqzwtmDEok2pwF8fhSKgW@OU1N6uGY4Xk40GNvM/h/2tb9cVtrG44h02vDTMXjCbNWLSUJMmscjmvofxtb6BQ

**Comment by e-kayrakli** [comment]
Right, then the compiler picks that overload never issuing the warning. For this to help in my case, I'd need the compiler to call the 0-arg init, not the overload that takes a type argument. The overload with the type argument is the new thing we are adding and suggesting that the user should call normally.

**Comment by bradcray** [comment]
Ah right, I see.

**Comment by mppf** [comment]
This works just fine (on my branch that disables (2))

``` chapel
proc errorIfNoTypeActual() type {
  compilerError("Error - missing field type"); 
  return string;
}

record R {
  type t = errorIfNoTypeActual();
}

//var r: R; // error

var r: R(string);
writeln(r.type:string);
```

I don't think that supporting errors for bad type construction in `init` is good enough reason to keep 2 working the way it does on master now. I still feel this way:

> I would have expected that a generic type could not be default-initialized no matter how many arguments.

**Comment by e-kayrakli** [comment]
@mppf -- This works on master, too. Thanks!

I am still ambivalent towards 2. That approach doesn't feel more hacky then this snippet. But I am fine with it being prohibited.
