### ISSUE TITLE
`Owned` in initializer causes lvalue assignment

### ISSUE THREAD

**Issue by BryantLam** [chapel-lang/chapel#8604]
### Summary of Problem
Trying to move an `Owned` into an initializer causes lvalue assignment. Intent was rvalue move.
```
error: illegal lvalue in assignment
```

### Steps to Reproduce

**Source Code:**

```chapel
use OwnedObject;

class Foo {
  var x: int;
};

class Bar {
  var y: Owned(Foo);

  proc init(y0: Owned(Foo)) {
    y = y0;
  }
};

var fooval = new Owned(new Foo(1));
var barval = new Owned(new Bar(fooval)); // <-- Error here.
```

**Compile command:**
`chpl --force-initializers <source>`

### Configuration Information
`chpl version 1.17.0 pre-release (2f0af5c5db)`

**Comment by mppf** [comment]
You can write this, you just have to use `in` or `ref` intent on the initializer.
Otherwise, since Owned has default intent const-in, it the actual argument can't be modified to "move" out of it. We might consider allowing "move" out of a const actual if we add compile-time checking that an Owned doesn't store a nil, but right now the Owned handles ownership transfer by setting the transfered-from-value to store nil (Otherwise there would be a double-delete). Alternatively, we could try to have a better error message in this case.

This works for me:

``` chapel
use OwnedObject;

class Foo {
  var x: int;
};

class Bar {
  var y: Owned(Foo);

  proc init(in y0: Owned(Foo)) {
    y = y0;
  }
};

var fooval = new Owned(new Foo(1));
var barval = new Owned(new Bar(fooval));
```

**Comment by BryantLam** [comment]
Thanks. This solves the immediate example. I didn't realize `in` intent allowed `Owned` to take ownership of another `Owned`'s value via its copy-initializer.
