### ISSUE TITLE
Investigate overheads of dynamic array registration

### ISSUE THREAD

**Issue by ronawho** [chapel-lang/chapel#8625]
https://github.com/chapel-lang/chapel/pull/6947 added dynamic array registration support for ugni in order to improve numa affinity for arrays. We've had some outstanding questions about the overheads and non-numa-affinity performance implications of this work, particularly with regard to ISx.

We thought the broadcast critical section might be slow and that it could have a significant serializing impact on applications. We took a look reducing the critical section in https://github.com/chapel-lang/chapel/pull/8177, but we didn't see any large performance wins with that. Prior to https://github.com/chapel-lang/chapel/issues/8497 we also didn't have a good platform to investigate because ISx was so noisy. 

This issue is meant to serve as a placeholder to investigate as well as a place to store the results for future reference.

**Comment by gbtitus** [comment]
I added some low-level timing to the built-in performance stats in comm=ugni and collected data for isx-hand-optimized on 16 BW28 nodes using the XC-16 perf testing setup:

    scaling mode = weakISO
    total keys = 60129542144
    keys per bucket = 134217728 (2**27)
    maxKeyVal = 3670016
    bucketWidth = 8192 (2**13)
    numTrials = 1
    numBuckets = 448

I set `CHPL_RT_COMM_UGNI_BLOCKING_CQ=y` during the run, to use a blocking Aries CQ for the inbound AM requests, to reduce the interference created by AM handler threads polling for work.  The reported timings were:

    averages across locales of min across trials (min..max):
    decl = 0.359871 (0.280543..0.458649)
    input = 0.550123 (0.548769..0.556878)
    bucket count = 1.13144 (1.12306..1.1765)
    bucket offset = 6.10268e-06 (3e-06..1.8e-05)
    bucketize = 1.77637 (1.68202..1.92019)
    exchange = 4.05609 (3.88031..4.18592)
    exchange only = 3.75266 (2.15518..4.09517)
    exchange barrier = 0.303423 (4.3e-05..2.0209)
    count keys = 0.326789 (0.28446..0.394036)
    total = 8.2007 (8.05573..8.28786)

Note that the `decl` timing is the separated-out timing for the `myKeys` array produced by editing the program; in the unmodified program this would be included in the `input` timing.  The other array created during each trial (`myBucketedKeys`) is included in the `bucketize` time.

I collected low-level statistics for the dynamic array allocation and registration.  With the above setup the program allocates, registers, deregisters, and frees 1792 512-MiB arrays: 2 during each of 2 trials (a warm-up and a "real" one) in 28 tasks on 16 nodes.  We enter the memory registration critical section 3 times for each array, once each during allocation, registration+broadcast, and deregister+free, and we broadcast the registration information 2 times, once when the array is registered and again when it is deregistered.  The low-level timings from the comm layer were as follows:

    Time (ms)  Operation
    ---------  ---------
       0.016   acquire the critical section lock
       0.0081  in the critical section
       5.8     alloc
     170       kernel page creation/zeroing
     130       default initialize
      21       register
       7.9     deregister (ISz n/a)
      32       free (ISx n/a)

The deregistration and free times are marked with `(ISx n/a)` because the ISx internal timing doesn't include these operations, which occur implicitly when we exit the scopes in which the arrays in question are declared.  The array creation costs are included in the ISx reported timings, however, under `decl` and `bucketize` respectively.

We had been concerned that the critical sections had a significant performance cost, but it looks as though that isn't the case at least at this scale.  (Note that these are within-node critical sections, not across-node ones.)  It will take `28 cores * (0.016 + 0.0081)` ms or about 0.67 ms to cycle all the tasks on a node through the first critical section if they all try to create arrays at the exact same time.  This is quite small compared to the ~330 ms (which could be reduced to ~200 ms) it will take to allocate and zero and register each array.  In addition, it's likely that the allocation step will have previously serialized the tasks, since it requires the kernel to update the single copy of the memory region information shared by all the threads.  Based on all of this it seems reasonable to conclude that the critical section isn't hurting us much, if at all.

**Comment by gbtitus** [comment]
I ran the same program on 256 2.1 gHz BW36 nodes, with the same configuration and setup.  The reported timings were:

    averages across locales of min across trials (min..max):
    decl = 0.422114 (0.305505..0.528591)
    input = 0.687376 (0.644008..0.700589)
    bucket count = 1.38095 (1.28793..1.4199)
    bucket offset = 5.38142e-05 (4.1e-05..9.5e-05)
    bucketize = 3.47894 (3.15525..3.72849)
    exchange = 12.7429 (12.3764..13.372)
    exchange only = 8.28083 (0.685102..12.7263)
    exchange barrier = 4.46205 (0.000171..12.6347)
    count keys = 0.445666 (0.405013..0.516626)
    total = 19.158 (18.8653..19.3665)

Here we make 36864 512-MiB arrays, 2 during each of 2 trials in 36 tasks on 16 nodes.  The low-level timings from the comm layer were as follows:

    Time (ms)  Operation
    ---------  ---------
        0.37   acquire the critical section lock
        0.069  in the critical section
        5.6    alloc
      220      kernel page creation/zeroing
      160      default initialize
       26      register
        7.2    deregister (ISz n/a)
       64      free (ISx n/a)

Allocation through free (the last 6) are all slower, which is mostly (maybe entirely) explained by the slower clock (2.1 vs. 2.6 gHz) clock on these BW36 nodes compared to the BW28 ones used for the 16-node run.  The critical section is about 8 times slower, which is probably due to the broadcast.  We use uGNI chained transactions of length up to 64 for the broadcasts.  In the 16-node case we only need 1 16-item transaction per broadcast, but in the 256-node case we need 4 64-item transactions.  So we're probably 4x slower due to 4 transactions instead of 1, and each one is 2x slower due to having more items.  (Much transaction cost is due to network latency rather than initiation time, so we don't see a full 4x slower for 4x as many items per transaction.)

Finally, the critical section lock acquisition time is 5x the critical section time versus having been just 2x in the BW28 case, possibly reflecting both more cores and the slower clock.  The total time to cycle all cores through a critical section is now quite a bit higher: 16 ms compared to 0.67 ms in the 16-node case.  It's still not large compared to the sum of everything else, but it certainly won't improve at higher scale and this might be an area we'll need to revisit in the future.

**Comment by gbtitus** [comment]
Our investigation shows that there are overheads from fully dynamic array registration, but they are dominated by the hugepage allocation (kernel memory management including page zeroing) and the time to register and broadcast is much less. We're closing this since we believe there is little for us to improve on, at least until program scale increases significantly.  This also addresses #7493.
