### ISSUE TITLE
HDF5 Support

### ISSUE THREAD

**Issue by benjamin-robbins** [chapel-lang/chapel#8640]
As a Chapel Programmer, I want to be able to read and write HDF5 file because of their wide support in the greater development community.

Acceptance Criteria:
User reads and writes HDF5 file from Chapel program.

**Comment by ct-clmsn** [comment]
@benjamin-robbins there are currently two mechanisms to use HDFS in Chapel. The first mechanism is documented [here](https://chapel-lang.org/docs/1.13/modules/packages/HDFS.html). That mechanism uses the existing Java JNI capabilities to interface the compiled Chapel software with the Java, JVM, bytecode compiled version of HDFS.

The second mechanism to accessing HDFS requires the use of a native C++ library called libhdfs3. The C++ libhdfs3 was integrated into the Chapel runtime's IO system and can be `activated` with some compile-flag options. You can read about how that works with Chapel [here](https://github.com/chapel-lang/chapel/tree/master/third-party/libhdfs3).

The current 3rd-party directory that pulls in libhdfs3 could use some updating because Hawq was originally a commercial product by PivotalHD. libhdfs3 was provided to the public under a permissive license and made available in it's own GitHub repository. Since, Hawq is now an Apache project, the git repository urls are probably out-of-date. That said, you can get copies of the current Apache-Hawq libhdf3 [here](https://github.com/apache/incubator-hawq/tree/master/depends/libhdfs3).

libhdf3 was selected because of it's use in Hawq and because there was some conversation in the Hadoop community about integrating it in some capacity. You can read that discussion [here](https://issues.apache.org/jira/browse/HDFS-6994).

More ancient versions of libhdfs3 can be found [here](https://github.com/Pivotal-Data-Attic/attic-c-hdfs-client) and [here](https://github.com/ContinuumIO/libhdfs3-downstream/tree/master/libhdfs3).

**Comment by ct-clmsn** [comment]
@benjamin-robbins I've added a ticket to fix the GitHub pull issue. #8753 should fix the issue and provide you the ability to build in libhdfs3 support into the chapel runtime using the provided instructions found [here](https://github.com/chapel-lang/chapel/tree/master/third-party/libhdfs3).

**Comment by ct-clmsn** [comment]
@benjamin-robbins apologies! I saw HDF5 and my brain transliterated it into HDFS. comments removed.

**Comment by daviditen** [comment]
We support reading/writing HDF5 files and I don't think there's any further work planned here in the near term. Closing.
