### ISSUE TITLE
Allow class reflections on proc names

### ISSUE THREAD

**Issue by buddha314** [chapel-lang/chapel#8724]
To support functionality like Python's [Unittest](https://docs.python.org/3/library/unittest.html) and [testing in general](https://github.com/chapel-lang/chapel/issues/7495) it would be useful to have something like a `TestCase` class with methods that are tests.  E.g.

```chapel
class TestMyThang : TestCase {
   var barney;

    proc setUp() { do stuff before like
       barney = new Dinosaur();
   }
    proc searDown() {do stuff after }

   proc testHappy() {
      assert(barney.isHappy() == true, "RUN FOR YOUR LIVES!!");
   }
}
```

Then the extended class `TestCase` could have a method that does something like

```chapel
proc TestCase.getMyTestes() {
  return all of my tests that start with "test";
}
```

**Comment by buddha314** [comment]
Is this the kind of thing that might be solved by decorators?  In that case, let me ask the status of decorators.

```chapel
class TestMyThang : TestCase {
   var barney;

   @setup
    proc setUp() { do stuff before like
       barney = new Dinosaur();
    }

   @teardown
    proc searDown() {do stuff after }

    @unittest
    proc testHappy() {
      assert(barney.isHappy() == true, "RUN FOR YOUR LIVES!!");
    }
}
```

**Comment by buddha314** [comment]
As I think about it, I suppose you also need a method to actually execute the `proc` given only it's name. So the super class has to do something like 

```chapel
proc doAllMyTestes() {
  for t in self.getMyTests() {
    t.run();
  }
```

**Comment by bradcray** [comment]
The reflection-oriented theme of this issue is a bit like the "fielderator" concept that's supported by the Reflection module ([numFields](https://chapel-lang.org/docs/modules/standard/Reflection.html?highlight=reflection#Reflection.numFields), [getFieldName](https://chapel-lang.org/docs/modules/standard/Reflection.html?highlight=reflection#Reflection.getFieldName, [getField](https://chapel-lang.org/docs/modules/standard/Reflection.html?highlight=reflection#Reflection.getField)), yet extended to methods rather than just fields.  What makes such support for methods harder is that in a full reflection solution, you'd also want the ability to iterate over the method's arguments; query the arguments' names, types, and default values; query the method's return type and intent; etc.  Yet for a simple test jig like the one you sketch above, a lot of that would be overkill and you'd probably be happy with something simpler.  This leads me to wonder "Is the priority to support full method reflection?" vs. "Should there be some other cue built into the language or implementation which says 'run all things marked as being tests?'"

**Comment by buddha314** [comment]
+1 on the name "Fielderator".

I am just aiming at the test suite, so I don't know how has to be done to make that happen.

**Comment by bradcray** [comment]
@ben-albrecht is working on writing an issue to collect and discuss some of the (many, varied) ideas that have been kicked around for supporting user-based test suites, unit testing, etc.  If that's your main topic of interest, his issue may subsume the need for this one.  I was responding to the specific request you made for the reflection module to support reasoning about and calling methods.

With respect to the side question about decorators, there isn't any current plan to add them to Chapel, though they do come up from time to time when discussing various aspects of the language.  I often view things like decorators and pragmas as being an indication that a language's design was frozen too soon, so keep putting off introducing them for things that are arguably better handled within the language itself.  That's not to say that we'll never have them, simply that we haven't had the case that's suggested "now's the time" become a priority as of yet.  Will unit testing be that case?  I'm not sure yet.

**Comment by buddha314** [comment]
That's an interesting point about the decorators.  I hadn't thought of it that way.  I know them mostly from Spring, which seems extremely baroque.

Yes, testing, that's the big one.

**Comment by buddha314** [comment]
Another thing to add would be the ability to detect `ignore` somehow.  In Spring, this is a decorator `@ignore` I think, and something like `@skip` for Python, but now I have been so influenced by the Svengali-like charisma of @bradcray that I HATE HATE HATE decorators!  Python decorators! Spring Decorators! Interior Decorators!  THEY ALL MUST GO!

```chapel
class TestMyThang : TestCase {
   var barney;

    proc setUp() { do stuff before like
       barney = new Dinosaur();
   }
    proc searDown() {do stuff after }

    proc testHappy() {
      assert(barney.isHappy() == true, "RUN FOR YOUR LIVES!!");
    }

    proc testMiserable_Ignore() {
      assert(barney.isHappy() == false, "RUN FOR YOUR LIVES!!");
    }

    // or simpler for ignoring, unless this violates a convention
    proc _testMiserable() {
      assert(barney.isHappy() == false, "RUN FOR YOUR LIVES!!");
    }
}
```

**Comment by buddha314** [comment]
Here is another use case, I just want to know the name of the calling procedure.  Something like

```
proc useless() {
  var n = whatProcDothDareCallMe();
  writeln("thou hast been summonsed by ", n)
}

useless();  //  thou hast been summonsed by useless
```

**Comment by bradcray** [comment]
It looks like there's an error in your example above?  `useless` isn't the calling procedure, it's the callee.  I.e., I'm guessing you'd want

```chapel
proc foo() {
  writeln(whatProcDothDareCallMe());
}

proc bar() {
  foo();
}
```

to print `bar` rather than `foo`?  (or else you might rename the call to `whatsMyNameAgain()`...?)

**Comment by bradcray** [comment]
How about editing the pseudocode to show what you want then?  Put the call to useless() into another routine and update the comment to name that routine instead of useless()...

**Comment by bradcray** [comment]
Oh, or is the pseudocode actually showing what you want and I'm the one who's misinterpreting?  That it's not "who called the procedure that contains the call to `whatProcDothDareCallMe()`" but rather "who called `whatProcDothDareCallMe()`?  It seems maybe I was confused, which is why I posted another interpretation / example.

**Comment by buddha314** [comment]
```
proc myNameIsSam() {
  // somehow get a string variable with the content  "myNameIsSam", call it n
  // no cheating!
  writeln(n);  // myNameIsSam
}
```

**Comment by krishnadey30** [comment]
I think we can close this issue as we have [UnitTest module](https://chapel-lang.org/docs/master/modules/packages/UnitTest.html).
@buddha314 @bradcray

**Comment by bradcray** [comment]
That seems plausible to me, @krishnadey30, but I'll defer to @buddha314 since he filed the issue.

**Comment by ben-albrecht** [comment]
I feel pretty confident that we can close this issue. @buddha314  can speak up if he disagrees.
