### ISSUE TITLE
improve the error upon a labeled forall loop - or allow it

### ISSUE THREAD

**Issue by vasslitvinov** [chapel-lang/chapel#8914]
Currently a forall loop cannot be labeled. However, the error is misleading:

```chpl
label MyLabel forall loc in Locales do writeln(loc);
```
```
error: cannot label non-loop statement
```

It would be good either to improve the error or to allow a label on a forall statement - for use in `continue` statements. (Recall that `break` out of a forall loop is not allowed.)

References:
* #8125; #8340 (especially the PR message)
* spec 11.10 *"The Break, Continue and Label Statements"*

**Comment by krishnadey30** [comment]
I checked the code.
Changing the error statement will can help.
https://github.com/chapel-lang/chapel/blob/3ae999d39f3dd345bb95031e8776b8d1e952b4c4/compiler/AST/build.cpp#L642

**Comment by vasslitvinov** [comment]
@krishnadey30 - sounds good. Please verify that this test:
```
test/statements/sungeun/bad_label.chpl
```
continues to work correctly with your changes.

**Comment by krishnadey30** [comment]
@vasslitvinov -
![image](https://user-images.githubusercontent.com/22263782/53852228-4dfe0880-3fe7-11e9-8f95-0bc7008b6dd0.png)
This is the current output. I was trying to make it work. I think forall is not able to pass https://github.com/chapel-lang/chapel/blob/3ae999d39f3dd345bb95031e8776b8d1e952b4c4/compiler/AST/build.cpp#L635

**Comment by gbtitus** [comment]
As a user, I think in this case I'd prefer the message tell me what I can do rather than what I cannot.  So perhaps "can only label for- or while-do- or do-while-statement", which is what the spec says.

It looks like the documentation could be improved also.  The spec says you can't use `break` to exit a parallel loop.  But it doesn't mention using `continue` in a parallel loop, which could be taken as implying that's legal.  But in fact I expect it's not legal at least in some cases.  For example, you probably can't do a labeled `continue` from an inner parallel loop where the label is on an outer loop, because that effectively requires doing a `break` on that inner parallel loop, which isn't allowed.  In other words, you can only `continue` a parallel loop if it's the innermost parallel loop of the nest you're in.  But there could be more-inner non-parallel loops, so you still might need to be able to label the parallel loop so you can specify it's the one you're `continue`ing.  So maybe even the compiler code needs work, if it really does disallow all labeled parallel loops?

**Comment by vasslitvinov** [comment]
@gbtitus - in my recollection, our compiler's detection of problematic cases with break and continue is surprisingly good. It would take some stress-testing to find bugs there.

`continue` is indeed legal in a parallel loop, as long as it does not cause exit from an inner parallel loop. Which the user can't do anyway - because of "cannot label a forall loop".

**Comment by gbtitus** [comment]
> `continue` is indeed legal in a parallel loop, as long as it does not cause exit from an inner parallel loop. Which the user can't do anyway - because of "cannot label a forall loop".

What I was saying is that if you indeed can `continue` the innermost parallel loop, then it would make sense to allow labels on parallel loops so that you could `continue` that innermost parallel loop even if you were inside a more-inner serial loop.  Or to say it the other way around: unless you can label parallel loops, you can't `continue` the current parallel iteration if you're in a serial loop nested within a parallel loop.  If the compiler currently disallows labels on parallel loops outright, as the spec says it does and the current error message implies, then you can't write this code even though there doesn't seem to be any inherent reason we can't make it work.

**Comment by krishnadey30** [comment]
@gbtitus  Its a good idea to give a positive message "can only label for- or while-do- or do-while-statement"

 @vasslitvinov @gbtitus I think its better if we don't allow the user to continue from a inner parallel loop to outer parallel loop and at the same time a user can continue to a parallel loop from a inner serial loop.

**Comment by vasslitvinov** [comment]
@krishnadey30 - sounds good. Let us go ahead with this phrasing: "can label only for-, while-do- and do-while-statements" .

Bonus point: eliminate "error: cannot label non-loop statement" (or the revised phrasing) when compiling this:
```chpl
label l: for i in 1..3 do writeln();
```

**Comment by krishnadey30** [comment]
@vasslitvinov Sure I will look at this. Once I am done I will let you all know.

**Comment by krishnadey30** [comment]
@vasslitvinov Is this syntax correct? I tried to run the code. It showed 
`test.chpl:1: syntax error: near ':'`
`test.chpl:1: error: can label only for-, while-do- and do-while-statements`

**Comment by vasslitvinov** [comment]
The syntax is not correct, so the compiler should be issuing "syntax error: near ':'".

OTOH the line `error: can label only for-, while-do- and do-while-statements` is misleading because the user IS trying to label a for-loop. How to get rid of this line?

**Comment by krishnadey30** [comment]
Yes, we should just show the error. I will try to correct the error statement.

**Comment by krishnadey30** [comment]
> @krishnadey30 - sounds good. Let us go ahead with this phrasing: "can label only for-, while-do- and do-while-statements" .
> 
> Bonus point: eliminate "error: cannot label non-loop statement" (or the revised phrasing) when compiling this:
> 
> ```chapel
> label l: for i in 1..3 do writeln();
> ```

I tried to correct it but was not able to. In https://github.com/chapel-lang/chapel/blob/1cf7393291205764fd6f0df7ba48d72afa40665a/compiler/AST/build.cpp#L635 `toLoopStmt(breakLabelStmt->prev)` returns none.
Will be glad if someone can help as I am new to compilers.

**Comment by krishnadey30** [comment]
Also, what output is expected ?

**Comment by vasslitvinov** [comment]
@krishnadey30 let me think how to respond to your questions. Meanwhile if you'd like to put together a PR to change the text of the error message as we discussed above, it needs to be done by noon PST Monday 3/11 or soon after if you'd like to get it into the upcoming Chapel release.

**Comment by krishnadey30** [comment]
@vasslitvinov I have created a PR https://github.com/chapel-lang/chapel/pull/12564
