### ISSUE TITLE
Edison scalability data

### ISSUE THREAD

**Issue by psahabu** [chapel-lang/chapel#8935]
### Configuration:
- up to 1024 nodes on NERSC's Edison
 
### Collect and graph scalability data for the following tests:
- [x] PRK Stencil
- [ ] ISx
- [x] RA-on
- [x] RA-rmo
- [x] RA-atomics
- [x] reduction
- [x] stream

**Comment by ronawho** [comment]
![stream-perf-u q](https://user-images.githubusercontent.com/1588337/39480182-48102566-4d1c-11e8-87e1-aad00d286a89.png)

![stencil-opt-perf](https://user-images.githubusercontent.com/1588337/39480186-4c020c34-4d1c-11e8-8f38-93b16d5d47a3.png)

![reduction](https://user-images.githubusercontent.com/1588337/39480197-56bea128-4d1c-11e8-91c6-77fcccb5bced.png)

![ra-atomics-perf](https://user-images.githubusercontent.com/1588337/39480164-3a1ddad4-4d1c-11e8-8915-cad306f8a194.png)

![ra-rmo-perf](https://user-images.githubusercontent.com/1588337/39480172-3ddef978-4d1c-11e8-9797-b78c73cd0171.png)

![ra-on-perf](https://user-images.githubusercontent.com/1588337/39480177-415cf168-4d1c-11e8-8a00-c6f3e4146dd2.png)

**Comment by bradcray** [comment]
Really minor, but I think flipping the legends on these graphs so that 1.17 is on top would generally help their readability (particularly for those in which 1.17 outperforms 1.16 which outperforms 1.15.

**Comment by ronawho** [comment]
I was thinking about that too after I posted the graphs.

That's what I did for https://github.com/chapel-lang/chapel/issues/9063 (well actually I ordered them so that they're in sorted order -- e.g. for time graphs I swapped the order)

I wasn't quite sure what I wanted to do for these graphs, since there's not always a clear winner (I picked the order based on the RA atomic graphs where 1.17 isn't on top)

**Comment by ronawho** [comment]
Updated the graphs above (so now both of our comments make us look like crazy people)

**Comment by bradcray** [comment]
I'm deleting mine so that you'll look even more crazy!
