### ISSUE TITLE
Design a domain map-based framework for partial reductions

### ISSUE THREAD

**Issue by vasslitvinov** [chapel-lang/chapel#9012]
Define an interface to be implemented by a domain map for partial reductions. Understand the mechanics of implementing a partial reduction for a given domain map and minimizing communication of partial results between locales.

Includes the following deliverables, for now in the test/ subtree:

- [ ] the function for the compiler to invoke upon a partial-reduce expression
 - it will serve as a "driver" and call into the domain map via the interface
- [ ] implementation of the interface for DefaultRectangular
- [ ] the counterpart for SumReduceScanOp for partial reductions
- [ ] tests

**Comment by bradcray** [comment]
My suggestion would be to start on this end of the pipeline rather than the compiler end—determine what the domain map interface needs to be, get buy-in for it, implement a test of it on default rectangular and/or block, and then create code that manually invokes it to demonstrate that it works as expected before trying to plumb partial reductions through the compiler.  That way we know what we're trying to target (which might affect how we deal with them in the compiler).
