### ISSUE TITLE
Surprising behavior when returning _void from param conditional

### ISSUE THREAD

**Issue by benharsh** [chapel-lang/chapel#9152]
### Summary of Problem

If any path of a conditional returns ``_void``, the compiler currently sets all paths to return ``_void``. It does this even if the condition is ``param`` and other paths return non-void values.

### Steps to Reproduce

**Source Code:**

```chapel

proc helper(param cond : bool) {
  if cond {
    return (1, 2.0, "3");
  } else {
    return _void;
  }
}

var T = helper(true);
writeln("T = ", T);
writeln("T.type = ", T.type:string);

var F = helper(false);
writeln("F = ", F);
writeln("F.type = ", F.type:string);
```

Output:
```
T = 
T.type = void
F = 
F.type = void
```

### Associaited Future Test(s) 
[types/void/param-return-void.chpl](https://github.com/chapel-lang/chapel/blob/master/test/types/void/param-return-void.chpl)

### Workaround

Replace `return _void;` with `var myvoid = _void; return myvoid;`

**Comment by benharsh** [comment]
I encountered this while working on conversion of arrays to use initializers. I was able to work around it in an ugly way, and would prefer to use the ``return _void`` pattern instead.

**Comment by bradcray** [comment]
@daviditen : Have you taken a peek at this issue at all?
@benharsh: Would you file a future against this?

**Comment by daviditen** [comment]
I took a peek at it today.  `normalizeReturns()` in the normalize pass replaces all returns in any function that has a `void` return with a single `void` return.  Prior to first class void values, this was OK because an earlier pass would issue an error if a function both returned a value and returned no value (e.g. `return;`).  When returning a `_void` value, that error message doesn't trigger and the assumption that returning something of type `void` in one place means all returns are `void` is no longer true.

**Comment by benharsh** [comment]
@bradcray : A future has been added.

**Comment by vasslitvinov** [comment]
I tried to fix this and was tantalizingly close. See 575720b866 .
Alas, the generated code was incorrect.

My reflections are:

* Since normalize() is sensitive to `return;` vs. `return _void;`
we shouldn't replace the former with the latter before normalize.

... and/or ...

* We should remove that piece of normalize where it replaces all
`return [something];` with `return _void;` once a `return _void;`
has been detected. Apparently something in the compiler downstream
depends on this transformation; it will be good to remove that
dependence. Because normalize does not do this transformation
for some void-returning `return` statements.

A couple of interesting findings:

* A void-returning function can be `param`. Ex.
`inline proc _defaultOf(type t:void) param return _void;`

* Whereas `isLegalParamType()` does not include `void`.

* `proc chpl__initCopy(x: _tuple)` as empty body in its Chapel code.
Therefore normalize thinks it is not supposed to return anything.
