### ISSUE TITLE
Uncoordinated exits with gasnet smp are slow

### ISSUE THREAD

**Issue by ronawho** [chapel-lang/chapel#9163]
With the smp substrate doing an uncoordinated exit (exit from just 1 locale) takes a long time to shutdown. 

A no-op chpl program (where a coordinated barrier followed by gasnet_exit on all locales will occur) finishes extremely quickly:

```sh
$ time ./no-op -nl2
real	0m0.020s
```

And an uncoordinated shutdown takes over 10 seconds: 

```chpl
extern proc chpl_comm_exit(s: int, a: int);
chpl_comm_exit(0, 0); // thin wrapper over gasnet_exit()
```

```sh
$ time ./exit -nl2
real	0m10.537s
```

Doing a exit on all locales also finishes quickly:

```chpl
extern proc chpl_comm_exit(s: int, a: int);
coforall loc in Locales do on loc do
  chpl_comm_exit(0, 0); // thin wrapper over gasnet_exit()
```

```sh
$ time ./exit-all -nl2
real	0m0.020s
```

Note that an uncoordinated shutdown with gasnet-udp finishes very quickly (0m0.035s)

I'm guessing that just doing an exit on 1 locale just kills the current smp instance and not the other processes, and the program is just waiting until a gasnet watchdog triggers a sigalarm or something that finally kills the program.

**Comment by bonachea** [comment]
This smp-conduit issue has now been fixed in the upstream GASNet repo, [by this commit](https://bitbucket.org/berkeleylab/gasnet/commits/a636c641d1e3e10f9ed38133dca3f6df4940ab75?at=develop), which tweaks the exit timeouts to be more responsive and appropriate for modern SMPs, providing speedier non-collective exits.

The patch in the commit should apply cleanly to any recent version of GASNet, and is the recommended solution for anyone who cares.

**Comment by ronawho** [comment]
@bonachea this certainly improves things (~1.2 seconds vs ~10.5), but I am curious why smp has to wait for the watchdog to kill things. Using the udp substrate an uncoordinated shutdown takes ~.04s (and most of that is probably chpl startup time)

Is there a technical reason why this is harder/different under smp (naively I would have guessed the udp case would be harder.) I'm mostly just curious -- I'd be fine with a "we're not interested in spending the time on smp" answer. 

And note that this doesn't hurt us that much (and certainly not any users that I know of), I only ran into when trying to reproduce https://github.com/chapel-lang/chapel/issues/7737 with non-udp segments

**Comment by bonachea** [comment]
@ronawho The only reason smp-conduit waits at all is because the only exit function in GASNet-1 is non-collective, and when possible we like to dynamically detect that a collective exit is happening - so that we can coordinate appropriately (most notably by returning the highest exit code from any process, rather than the one from the first process to reach the gasnet_exit call during a collective exit). The exit timeout is a heuristic that determines how long we wait to detect if the exit seems to be collective, before we start asynchronously killing peer processes. 

udp conduit handles shutdown using a completely different mechanism (written by different author) over sockets, and there the synchronous shutdown mechanism gives each process in a collective exit the opportunity to contribute to the exit code before it dies. That's why the behavior differs.

**Comment by ronawho** [comment]
Gotcha, thanks for the info
