### ISSUE TITLE
User-defined hashing for DefaultAssociative

### ISSUE THREAD

**Issue by benharsh** [chapel-lang/chapel#9182]
It is currently not possible for users to define a hashing method on their custom types to be used with DefaultAssociative. Instead, they must rely on the general-purpose Chapel implementation. This may be particularly problematic for classes, which currently hash on pointer value. It is likely that users would prefer to use some custom "ID" field instead, but they have no documented way to do so.

**Comment by bradcray** [comment]
I like this feature request, but I'm not sure I agree for the specific case of supporting it for classes (for similar, but different reasons to believing we shouldn't support assignment overloads on classes):

For records where their logical value is the value of their fields, I think it makes sense to provide a custom hash that hashes on an ID field within the record object.  For classes, I think their logical value is effectively their identity, and it feels like it'd be problematic if a class object's field changed and therefore the hash that was used to store it into an associative domain became invalid.  This doesn't seem like it'd be a concern for records since changing one of the fields effectively changes the logical value of the record (e.g., it'd be like changing an integer '3' to '4' and expecting it to still be in a `domain(int)`).

As a slightly related note, the prototype distributed memory default associative domain permits the user to provide their own hash function to map values to domains.  However, because we were wary about leaning on first-class functions, I believe the way this is expressed is by providing an object with a specific interface... :(

**Comment by benharsh** [comment]
Two counterpoints regarding classes:

1) We ran into issues in the compiler (C++) when std::map hashed on pointer values, which lead to nondeterministic AST ordering. We fixed this by implementing ``less`` structs that compared BaseAST 'id' values. It's conceivable that users may want similar functionality.

2) We, or users, may replicate classes across locales. I think it could make sense for those replicated classes to hash to the same value.

**Comment by benharsh** [comment]
Perhaps this should be a separate issue, but: I think we should also investigate more hash functions than our current one, or at least be able to justify our current default hash function.

**Comment by bradcray** [comment]
@bmcdonald3, @vasslitvinov : I think we can close this now that it's supported, right?

**Comment by bmcdonald3** [comment]
Yes, that is correct, this is now supported.
