### ISSUE TITLE
where clauses with unmanaged and borrow types

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#9273]
Suppose a method uses a where clause to filter based upon type.
Should that where clause filtering allow for coercions from `unmanaged` to `borrows`?
For example:

``` chapel
class MyClass { }
proc f(x) where x.type : MyClass { }

var c = new unmanaged MyClass();
f(c);
```

Should this program compile? At present it results in an error like:
```
ex.chpl:5: error: unresolved call 'f(unmanaged MyClass)'
ex.chpl:2: note: candidates are: f(x)
```

Currently these where clause subtype checks A:B do allow for:
 * A is an instantiation of B
 * A is a class subtype of B (i.e. A inherits from B, directly or indirectly)

However they do not allow for numeric coercions.

**Comment by mppf** [comment]
@benharsh - I'm wondering about your opinion on this issue.
Historically, the subtype check in a where clause doesn't allow for coercions, but @bradcray and I were speculating than maybe it should. E.g.:

``` chapel
proc g(x) where x:int {
}
var num:int(16) = 1;
g(num); // instantiates g with int(16)
        // where clause `true` because int(16) coercible to int
```

**Comment by bradcray** [comment]
Talking with Michael about this issue, I had a few reactions:

* I don't feel like I have a strong intuition about the status of `:` in where clauses on master anymore (and this concerns me a bit).  I think this is in part because it's evolved over time and in part because we never defined it very well to begin with.

* That, intuitively, I think of `==` in where clauses as being a strict type assertion and of `:` in where clauses as being similar to a `:` in a formal argument list, though not exactly the same.  Here are some examples I just wrote up with BHarsh on the whiteboard:

```chapel
proc foo(x) where (x.type == int(64)) { ... }
proc bar(x) where (x.type: int(64)) { ... }
proc baz(x: int(64) { ... }
```

If I say `foo(42:int(16)` then I would not expect that to resolve since `foo()` is essentially asserting that `x`'s type is `int(64)`, yet it's not

If I say `baz(42:int(16))` then I'd expect the call to resolve and for the actual to coerce to an `int(64)` as it's being copied in.

If I say `bar(42:int(16))` then it would seem reasonable to me to say that like the call to `baz()` this "works" since the actual can coerce to the type in the where clause.  Yet I'd expect the instantiation of the function to be an `int(16)` instantiation since it's generic and that's the actual type of `x`.

* That said, return to point 1.   :)

**Comment by lydia-duncan** [comment]
I should note that I found a distinct difference in
```chapel
proc foo(x) where (x.type == someType) { ... }
proc bar(x) where (x.type: someType) { ... }
```
when `someType` is generic.  I don't remember which was which off the top of my head, but it meant that one idiom could not be written when the type was generic (and this impacted its utility in the case of eliminating copy initializer candidates for a generic type when the argument was generic, as an example) - with that in mind, we will want to be careful.  A user may want to only allow instantiations of a generic type but the types it inherits from, or vice versa, and it would be frustrating to force them to only accept both or to only accept one or the other.

**Comment by benharsh** [comment]
I'm open to allowing both ``where unmanaged : borrow`` and the general colon-coercion.

A case I brought up with Brad, assuming we allow general coercions for ``x:t``  :
```chpl
proc foo(x) where x : int { }
proc foo(x) where x : real { }

foo(5);
```

Is this a valid program? If so, which ``foo`` is chosen? I suspect (and I think Brad agrees) that this would not be valid and would result in an ambiguity error.

Taking a step back, are we overloading ``:`` too much for where clauses? Should we split off some of this functionality somehow? I don't think we have a way to ask 'can this coerce' today, which seems potentially useful. Also, I don't think we have a way to perform the two queries mentioned in the issue (instantiates, inherits) outside of a where clause.

**Comment by bradcray** [comment]
> are we overloading `:` too much for where clauses?

I think this is an interesting question.  If I were going to defend it, I might say that where clauses are like an extension of the formal argument list and so treating it like "canCoerce()" or a formal type constraint is reasonable.  But frankly, where clauses are a lot more like executable code contexts than they are declaration contexts, so this is arguably an abuse.  So probably the cleaner thing to do would be to have `:` be interpreted strictly as "cast" in the where-clause context (and as such, not a valid where-clause in itself since it doesn't return a boolean) and to introduce (or use existing) predicates for other cases we want to express.

**Comment by vasslitvinov** [comment]
I support Michael's summary that `A:B` in a where-clause checks:

* A is an instantiation of B
* A is a class that inherits from B, directly or indirectly
* I think the latter is, more generally, "from B or an instantiation of B" (??)

BHarsh brings up a good question - should `A:B` also allow:

* A can implicitly coerce to B

I do not have a good intuition about it. It is very different from what we have currently, so there may be unexpected consequences. Perhaps more definitely, there **will** be. :)

Instead of that we could add a "can coerce" test that the user can invoke explicity. Maybe write it as `A<=B` where A and B are types.

Note that we can already say "some kind of int" as `where x.type : integral` . Dunno about reals.

**Comment by vasslitvinov** [comment]
Back to Michael's original question: should `A:B` also allow unmanaged->borrowed?

Support for "yes": it is very likely that if a function is legitimate for a borrowed pointer, it is also legitimate for an unmanaged pointer.

Another support for "yes": right now it would be very inconvenient to express that a function can be instantiated for an unmanaged as well as for a borrowed type.

My reservations are (a) working with unmanaged pointers should happen rarely, so we shouldn't make it too convenient, and (b) allowing unmanaged->borrowed is aking to allowing int(16)->int(64), which we are not allowing at present.

An interesting case is the changes to ReplicatedVar.chpl in #9282. There, I think the solution is to put "unmanaged" to the right of `:`, ex. `replicatedVar._value: unmanaged ReplicatedArr` .

Speaking of which, @benharsh  allowed users to drop `._value` in this context, right?

**Comment by mppf** [comment]
I tend to agree with @bradcray about the special treatment for `:` in where clauses and in fact I was flabbergasted the first time I encountered it.

However I think the terminology is challenging. Certainly `canCoerce` has a relatively easy interpretation, but what does `isSubType` mean? Why do we distinguish between the two, when for argument passing they are interchangeable? Especially since the compiler actually implements "subtypes" (e.g. class inheritance) with coercions, I find the terms difficult to nail down.

**Comment by benharsh** [comment]
@vasslitvinov : I only updated the compiler to allow ``distribution : class``. I didn't do anything for arrays/domains.

**Comment by bradcray** [comment]
To clarify, I wasn't trying to say that we must support these predicates specifically (canCoerce, isSubType).  More that anything that we're trying to squeak out of `:` should be implemented as a predicate.

**Comment by psahabu** [comment]
To the original question posed by this issue, @vasslitvinov lays out good arguments on both sides. While I am generally in favor of making `unmanaged` pointers harder to work with, doing so in this case would be of minimal benefit to users and the lifetime checker. Fundamentally, anything that can be done with a `borrowed` can be done with an `unmanaged`, so I am okay with the coercion.

As to `:` in `where` clauses, I agree that it is currently overloaded and that we need to differentiate coercions and casts. I am partial to @vasslitvinov's proposal for coercion syntax, `B <= A`, because it resembles the mathematical formalism `B <: A` (B is a subtype of A). This syntax and semantics would allow `:` to be strictly a cast.

**Comment by mppf** [comment]
#10060 is a specific proposal about changing `:` in where clauses

**Comment by mppf** [comment]
Closing as this is implemented. PR #10852 was the final step.
