### ISSUE TITLE
Slow Assignment of Sparse Arrays

### ISSUE THREAD

**Issue by Tshimanga** [chapel-lang/chapel#9344]
I need to build matrix polynomials out of sparse square matrices that have 10^6 rows/cols and 10^6 or 10^7 nonzeros. I need to be able to take loaded `NamedMatrix` objects and build the polynomials out of sums of the powers of it's underlying sparse array and its transpose. I can load the matrix, but the step of assigning it's underlying matrix to a new variable

```
var t: Timer;
t.start();
var P = namedMatrix.X;
t.stop();
writeln("Time to Handle Underlying Sparse Matrix: ",t.elapsed());
```

takes a prohibitively long time. I don't have enough time to let it run to completion.

**Comment by bradcray** [comment]
@Tshimanga : Would you be willing to put together a standalone test case that illustrates the issue for study / improvement?

**Comment by Tshimanga** [comment]
Okay, I'll try to get to that soon. Actually I've been wondering if it would be useful to have a `chapel-lang/reproducers` repo to store all of these open problems @bradcray

**Comment by Tshimanga** [comment]
If I write the standalone test and submit a PR do I get granted admittance to the list of Chapel Contributors? :P

**Comment by bradcray** [comment]
If you put the test on this issue, I'm happy to do the test harness and PR work for you (though obviously, I'd be happy if you were to do that yourself as well).  We typically only add people to the contributors list when they do PRs that show up in the release tarball and for the most part the test/ directory does not go into the release (where test/release/ is the exception).

**Comment by ben-albrecht** [comment]
If the issue is with sparse array assignment, I'd expect something like this to be a work-around:

```chpl
var PDom: namedMatrix.X.domain.type;
PDom += namedMatrix.X.domain;
var P: namedMatrix.X.type;
P = A;
```

**Comment by ben-albrecht** [comment]
> We typically only add people to the contributors list when they do PRs that show up in the release tarball and for the most part the test/ directory does not go into the release

However, he *would* get added to the [Chapel Contributors Team](https://github.com/orgs/chapel-lang/teams/chapel-contributors) when he turned in his CLA, which would be required to submit the test.

**Comment by bradcray** [comment]
For Chapel developers looking at this issue:  When this question came up on Gitter a few weeks back, a quick look at the implementation of sparse (domain) assignment made it appear that it was very general and presumed that the LHS was live.  It seemed like a case where distinguishing between assignment and initialization could result in big payoffs (no need to preserve anything; could assume the LHS was new).  At that time, the domain map framework had not yet been converted into initializers, so it didn't seem to make sense to start on it.  Since then, we've converted it over to initializers, so may now be better positioned to optimize this case (e.g., just do simple deep copies on the underlying data structures).

**Comment by Tshimanga** [comment]
> var PDom: namedMatrix.X.domain.type;
> PDom += namedMatrix.X.domain;
> var P: namedMatrix.X.type;
> P = A;

@ben-albrecht what is `A` in the last line? did you mean `namedMatrix.X`?

**Comment by ben-albrecht** [comment]
>  did you mean namedMatrix.X?

Whoops - yes. Corrected

> Would the following work just as well?

Yes

**Comment by Tshimanga** [comment]
Sadly, the proposed work-around does not seem to finish within reasonable time either @ben-albrecht @bradcray 

I made the edit and then went out to lunch. Still hadn't moved when I returned.

**Comment by ben-albrecht** [comment]
@Tshimanga  - Alright, I have 1 more to try:

```chpl
var PDom: namedMatrix.X.domain.type;
PDom += namedMatrix.X.domain;
var P: namedMatrix.X.type;
P.data = namedMatrix.X.data;
```

**Comment by Tshimanga** [comment]
@ben-albrecht I just re-ran it with timers in between each bit as follows:

```    //TROUBLESHOOTING

    var t1: Timer;
    t1.start();
    var PDom: parentMatrix.SD.type;
    t1.stop();
    writeln("Define PDom: ",t1.elapsed());

    var t2: Timer;
    t2.start();
    PDom += parentMatrix.SD;
    t2.stop();
    writeln("Populate PDom: ",t2.elapsed());

    var t3: Timer;
    t3.start();
    var P: parentMatrix.X.type;
    t3.stop();
    writeln("Define P: ",t3.elapsed());

    var t4: Timer;
    t4.start();
    P = parentMatrix.X;
    t4.stop();
    writeln("Populate P: ",t4.elapsed());
```

and saw no progress up data in over 15min or so

**Comment by ben-albrecht** [comment]
> and saw no progress up data in over 15min or so

So to clarify, does this mean your execution is not getting past this line?

```chpl
 var PDom: parentMatrix.SD.type;
```

**Comment by Tshimanga** [comment]
Yes, it would appear to be the case. Not sure why that step would cause a hang up though @ben-albrecht

**Comment by Tshimanga** [comment]
@ben-albrecht @bradcray I wrote the following `proc` as a work-around
````
proc extractMatrix(N: NamedMatrix) {
  var dom = N.D;
  var sps = CSRDomain(dom);
  sps += N.SD;
  var R: [sps] real;
  for (i,j) in sps {
    R(i,j) = N.X(i,j);
  }
  return R;
}
````
this handle the extraction a 2.5m by 2.5m matrix with 3.3m nonzeros in ~10s

The original problem, of course, is still at large.

**Comment by ben-albrecht** [comment]
> Not sure why that step would cause a hang up though 

I'm not sure either. That's surprising to me.

It'd still be nice to have a minimal standalone program that reproduces the issue, in the form of a contribution as a PR or code block in this issue. You could populate the sparse matrix with random data that is representative of your data if that's necessary to reproduce (I understand your dataset is confidential).

I'm going to remove the gating issue tag since you have a work-around, but this is still an important issue.

**Comment by e-kayrakli** [comment]
Hi @Tshimanga -- This issue was marked close when I merge #14112, which was more about sparse domain assignment. I played around with sparse array assignment and it seemed to me that it was already fast (0.02 seconds on my MBP with 10^7 indices on a CSR domain), so it may have been resolved before my PR. Feel free to comment/reopen this issue if you still observe similar performance issues.
