### ISSUE TITLE
List comprehension as input to string.join yields wrong output

### ISSUE THREAD

**Issue by BryantLam** [chapel-lang/chapel#9372]
### Summary of Problem
Wrong output for similar code, possibly due to function promotion of `join` method with list comprehension (Is this what it's called?) as an argument input.
```
_ir__iterator_for_loopexpr2 output: // Wrong?
one two three // Wrong
[domain(1,int(64),false)] string output:
one,two,three
```
Expectation is that both outputs should be `one,two,three`. First expression has confusing/implementation-specific type `_ir__iterator_for_loopexpr2` instead of an array of strings.

### Steps to Reproduce

**Source Code:**

```chapel
var list = ["one", "two", "three"];

writeln(([l in list] l).type:string, " output:");
writeln(",".join([l in list] l));

var x = [l in list] l;
writeln(x.type:string, " output:");
writeln(",".join(x));
```

### Configuration Information

`chpl version 1.18.0 pre-release (296301484f)`

**Comment by bradcray** [comment]
Here's what seems to be going on here (with some help from `--explain-call=join:4` and source code browsing): 

* The forall-expression argument (what you're, reasonably, calling a list comprehension) is effectively its own thing in Chapel, not actually an array, though it can be turned into one if captured in a variable as in your `x`.

* Like other parallel expressions, if it's yielding `t`'s and passed to a routine that accepts a single `t`, then it will call that routine in a promoted manner.

* Chapel does not insert array temporaries unless the user explicitly requests them, as you effectively do with `x`, in order to avoid blowing up memory in surprising ways.

* As a result, the call to `join()` with the forall-expression prefers to promote the version of `join()` that takes a variable number of `string` arguments (effectively calling it three times, passing in one string each time) rather than to insert an array temporary.

* Thus, you can view your `join()` call as being equivalent to the following rewrites:

```chapel
writeln(",".join([l in list] l));
writeln(",".join(forall l in list do l);
writeln(forall l in list do ",".join(l));
```

* Since each `join()` call is getting a single string, this is similar to a series of single-argument `join()` calls which are effectively the degenerate case that drops the separator on the floor (the "," in this case).  This is why no "," characters are showing up.

* The printed type of the forall-expression is "correct" in that it's how the compiler refers to such types, but really should be sugared into something intended for the end-user to make sense of.  For that matter, I think Chapel really needs a way of declaring formal arguments (if not variables) of such types.

* A potential "fix" for this case that would give the behavior you want would be for the string library to supply an overload of join() that took an iterable expression, in which case it would be a better match than promoting the string version.

* Another option _might_ be to provide a way of turning (via a cast?) the forall-expression into an argument list (similar to what `(...myTuple)` does) or a tuple.  The downsides of these approaches are that they would manifest the expression in memory (like when you inserted the array), which may not be desirable for a long list.  So I don't think this is as attractive.

* Lastly, I'm wondering if you really want `for l in list do ... l` since the `[l in list]` form is equivalent to a forall loop and seemingly could result in a race in terms of the order in which the strings are presented to the `join()` (unless I'm missing something subtle, which I may be...?).  I.e., would you be troubled if the output were "two three one" (with or without commas).

**Comment by BryantLam** [comment]
Closing. Satisfactory answer, albeit confusing if you're coming from Python.

**Comment by ian-bertolacci** [comment]
I'm poking this issue because I just hit it and was very confused.
I suggest we add a promoted join function.

**Comment by bradcray** [comment]
Can you put an example of the case you wrote here?

**Comment by ian-bertolacci** [comment]
I had this test program:
```chpl
var v = [i in 1..3] (i : string);
writeln( "=", "".join( v ), "=" ); 
writeln( "=", "".join( ([i in 1..3] (i : string)) ), "=" );
writeln( "=", "-".join( ([i in 1..3] (i : string)) ), "=" );
```
which outputs
```
=123=
=1 2 3=
=1 2 3=
```
but was expecting
```
=123=
=123=
=1-2-3=
```

The actual code I was trying to write was something like:
```chpl
const padding = 3;
const blank_string = "".join( [i in 1..#padding+1] " " );
```

**Comment by BryantLam** [comment]
It's worth asking whether people would expect this Python-list-comprehension-style syntax to behave like a `for` in Chapel, because I certainly didn't expect it to behave like a `forall`. It only solves half of this issue (the race-condition portion).

**Comment by bradcray** [comment]
Hi @BryantLam and @ian-bertolacci — I thought I'd pinged you guys on this issue after getting back from vacation this week, but it seems that I failed to (at least here...?).

The two main things I'm curious to hear from you are:
* PR #10448 adds an overload of `join()` that causes Bryant's test above to work as expected; should we merge it?
* Do you have insights into whether this idiom is one of a small number of cases that will lead to confusion like this, or is indicative of (say) hundreds of cases where Chapel's promotion semantics will be confusing to Python programmers?
  - note that, if the latter, one improvement on the horizon would be to define such routines in terms of constrained generic "iterable" types that would accept arrays or forall expressions like this one.  This is an approach that @benharsh champions with some frequency.

Some other noteworthy details from the exploration I did just before vacation are:
* I no longer believe that the nondeterministic output / race condition I was anticipating in my earlier comment exists when we use a forall expression in this context because Chapel's zippered promotion semantics mean that parallelism doesn't imply nondeterminism (e.g, `[(a,b) in zip(A,B)] a = b;` doesn't cause a permuted version of `b` to be assigned to `a` but a properly zippered one).
* This issue's surprising output (sans commas) occurs whether using a forall expression (as in the issue's code) or replacing it with a `for`-expression, so seems more related to promotion semantics and the function signatures we created for `join()` than whether Python programmers will be surprised that `[i in J]` is parallel in Chapel (?).

**Comment by BryantLam** [comment]
- We should merge #10448 or something like it because it prevents this issue with `join`.
- I can't say I'm experienced with Chapel's promotion semantics to know whether there are other locations that trip up with Pythonic usage. That said, I do agree that a constrained generic "iterable" could be a solution if all of these usage sites were identified (this is now the problem).

> ..., so seems more related to promotion semantics and the function signatures we created for `join()` than whether Python programmers will be surprised that `[i in J]` is parallel in Chapel (?).

Given your corrected explanation that this is more like a deterministic zippered iteration than nondeterministic race, this behavior does seem more attributed to promotion semantics and the (missing) function signature for `join`.

My personal opinion is that I'd avoid using the `[i in J]` syntax because `forall` conveys more identifiable and equivalent meaning, but with regards to this issue, I'm now more interested in preventing similar issues like this one because it affects the user's intent regardless of `[i in J]`/`forall`/etc.

**Comment by bradcray** [comment]
Thanks for the feedback.  So I'll plan to get #10448 merged to close this issue, and then open up a feature request for an `iterable` interface (linking it to constrained generics) as a means of writing routines like this rather than taking an array.
