### ISSUE TITLE
Design Spike: Export functions with array argument types/return types

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#9402]
Today exporting a function with an array argument generates the error message `exported function can't be generic`, even when the domain and type are known.  We would like to be able to export functions that take and return arrays, eventually supporting all flavors of Chapel arrays.

**Comment by bradcray** [comment]
> eventually supporting all flavors of Chapel arrays.

I'm not sure whether it makes sense to export a Chapel function that takes (say) a distributed sparse array because most other languages don't have distributed sparse arrays, so wouldn't have them to pass into Chapel.  I expect that such cases will need to be supported by having Chapel make utility routines available to external languages so that they can create Chapel sparse arrays from data that they might have.

A stepping stone that seems like it'd move the ball forward and support an important common case would be to do the converse of what we do for external procedures that take arrays.  Namely, if we write:

```chapel
extern proc foo(X: [1..10] real);
```

Chapel will essentially expect a C function with the signature `void foo(double* X)`.  So we could similarly say that for an exported function with an array argument:

```chapel
export proc foo(X: [1..10] real);
```

Chapel could generate the exported version of the function to take a `double*`, and would wrap that raw C pointer in a Chapel array as `foo()` starts running.  Note that we'd still (potentially) need a version of `foo()` that could be called from within Chapel.  So this suggests having the compiler create two such copies of foo()—one that serves as a bridge to the external language and the other which implements foo() as usual:

```c
void foo(double* X) {  // this version corresponds to the exported function
  _array X_chpl = ...create a Chapel array referring to `X`'s elements
  foo_chpl(X_chpl);
}

void foo_chpl(_array X) {  // this version can be called from within Chapel including from foo() above
  ...normal foo() definition...
}
```

As a starting point, we could only permit functions accepting 1D arrays of various types to be exported in this way.  Then expand to support multidimensional arrays.  Then think harder about whether we want/need/can handle associative, sparse, and/or distributed cases.

**Comment by lydia-duncan** [comment]
I talked with Michael and Ben H.  Today, our normal array set up assumes that it owns the underlying array and so deletes it when it is done with it.  What we'll need to do is set up our own domain map/array that understands it doesn't own the contents and so can't reallocate or delete, likely following a similar pattern to array view slices to get set up.  We may need to have one version that handles just C arrays and one that handles numpy arrays, or at least one version of the function Brad mentioned per structure style.
