### ISSUE TITLE
Allow reading additional types beyond c_int in HDF5 files

### ISSUE THREAD

**Issue by daviditen** [chapel-lang/chapel#9415]
As a Chapel user with lots of HDF5 files, I want to be able to read HDF5 files containing arrays of different datatypes beyond just C integers.

The types handled should include 32 and 64 bit floating point, 8, 16, 32, 64 bit signed and unsigned integer, and string.

**Comment by bradcray** [comment]
I think it'd be good to make the first step here be to sketch out a proposal for what the user-facing interface would look like for reading into a Chapel array of type t_chpl from a file storing C type t_c since I think that would address the main questions that seem to be lurking here:  (1) How to deal with not knowing a priori (at compile-time) what types are stored in the HDF5 file and (2) Determining how to translate those types to Chapel's types safely/reasonably.  As I mentioned today, I'd guess that the right approach would be for the user's interface to say "I want to read an array of size t_c" and for the routine to create that array, interrogate the file to see what type it stores, and convert between them if appropriate / possible."

**Comment by daviditen** [comment]
PR https://github.com/chapel-lang/chapel/pull/9707 adds a function to read HDF5 files into arrays in parallel for any basic type.
