### ISSUE TITLE
spike: Urika-XC launcher

### ISSUE THREAD

**Issue by ben-albrecht** [chapel-lang/chapel#9668]
The Urika-XC platform currently requires a custom tool called `run_training` (documented [here](https://pubs.cray.com/content/S-2589/1.1.UP00/xctm-series-urika-xc-analytic-applications-guide/run-tensorflow-with-the-cray-pe-machine-learning-plugin))  to launch Chapel programs onto nodes within OSA containers. What would it take to implement a Chapel launcher specific to the Urika-XC platform such that users can simply compile their Chapel programs and run them like they would anywhere else?

Some questions to consider:

- Is a launcher necessary?
  - Users of Urika platform would already be familiar with using the `run_training` script. This may be acceptable in the short-term.
- How would Chapel launcher flags map down to `run_training`?
- [x] Will the job launch tool always be available on a Urika-XC, such that we can simply wrap it?
  - If not, what are our options?
- [x] What components are required to write a new launcher in general?
  - Documented in `doc/rst/developer/adding-a-launcher.rst`
- [x] How should we support both slurm and PBS?
  - `CHPL_LAUNCHER={slurm-urika-xc, pbs-urika-xc}` ?
  - We will only support slurm at first
- [x] Should the launcher do the `salloc / qsub` as well?
  - Yes
- [x] How should we handle passing general flags, such as `--gres=gpu ` ?
  - Option 1: Any unrecognized flag is assumed to be a valid flag and passed down to launcher
  - Option 2: Add a specific flag for passing additional arguments
      - similar to Chapel's `--ccflags="--flag1=1 --flag2=2 ..."`
- [x] Can we detect that we are running on a Urika-XC and default to the `urika` launcher if so?
  - We might want to rely on the `analytics` module being loaded
    - This module is a dependency anyway, i.e. it provides access to `run_training`

**Comment by ben-albrecht** [comment]
> What components are required to write a new launcher in general?

I am writing a brief document for `doc/rst/developer/bestPractices` to answer this.

> Will the job launch tool always be available on a Urika-XC, such that we can simply wrap it?

Yes, but it will require users to `module load analytics`

**Comment by ben-albrecht** [comment]
Some other questions that came up when looking into this:

- How should we support both slurm and PBS?
  - `CHPL_LAUNCHER={slurm-urika-xc, pbs-urika-xc}` ?
- Should the launcher do the `salloc / qsub` as well?
- How should we handle passing general flags, such as `--gres=gpu ` ?

**Comment by gbtitus** [comment]
What is the out-of-band framework the `run_training` launcher sets up?  By "out-of-band" I mean the technique by which the multiple instances of a distributed program discover how many of them there are, which one each one is, and whatever info is needed to connect to the others.  This is used by the Chapel runtime comm layer to connect all the program instances together.  As examples, with comm=gasnet GASNet itself provides the out-of-band support and the comm layer just calls various GASNet functions to get everything connected together.  With comm=ugni on Cray X* systems we use PMI to discover the number of nodes and which node each program instance represents, and also to do the all-to-all sharing of that info in order to connect together via uGNI and the Cray network.  With the now-defunct comm=mpi layer I believe we used MPI itself for this (and programs were launched using mpirun, which set up the information).

It would definitely be best for us if `run_launcher` used PMI as its out-of-band framework, since we presumably will be using the ugni comm layer on Urika-XC.  But it also wouldn't be totally surprising if `run_launcher` used MPI as an out-of-band framework, though it would be awkward for us.  If `run_launcher` is really just a wrapper for the system launcher, however, then we're home free since the system launcher will set up the PMI information for us.
