### ISSUE TITLE
Module visibility compilation error with overloaded private function

### ISSUE THREAD

**Issue by BryantLam** [chapel-lang/chapel#9793]
### Summary of Problem
The module `A` has a public method that calls into an overloaded private method. Using an explicit module prefix to call the public method causes an unexpected compilation error because it is trying to incorrectly access the private method instead of the public one. Workarounds: Omit the module prefix; Rename the private function.
```
error: Cannot access 'aproc', 'aproc' is private to 'A'
```

### Steps to Reproduce

**Source Code:**

```chapel
module A {
  proc aproc() {
    writeln("public aproc");
    aproc(1);
  }

  private proc aproc(x: int) {
    writeln("private aproc ", x);
  }
}

module B {
  use A;
  proc main() {
    A.aproc(); // error
    //aproc(); // This works.
  }
}
```

### Configuration Information
`chpl version 1.18.0 pre-release (e770634374)`

**Comment by bradcray** [comment]
@lydia-duncan : This one looks like it's logically yours?  Have you had a chance to glance at it at all?

**Comment by lydia-duncan** [comment]
I noticed it came in, but put off looking into it since it seemed like it might be a product of the design behind handling private symbols instead of something that could get hammered out quickly.  I meant to ask about prioritization for it but forgot :/

**Comment by bradcray** [comment]
The fact that the commented out case worked made me hope that it would not be a major effort...?

**Comment by lydia-duncan** [comment]
I can certainly take a closer look at it, sure.  I'll report back when I know more

**Comment by lydia-duncan** [comment]
We're seeing this only with the module prefix because the module prefix causes it to have its visibility evaluated during scopeResolve instead of punted until function resolution.  Scope resolution doesn't track all the function overloads, it just looks at one arbitrarily (in this case, the last one defined - you can avoid this in all cases by defining the private version first, but that's a brittle hack).

First thought on how to fix this is to do some comparisons when we store a symbol in scopeResolves "ResolveScope" type - if one already exists, prioritize on keeping public versions over private ones.  There might be a more principled solution, so I'd like to think about it a little longer before implementing that.

**Comment by bradcray** [comment]
It definitely seems as though, while we're in this world, the rule "if any public symbols exist, use one of them over an arbitrary private one" is better than the current choice.  But the concept of using an arbitrary one makes me nervous in any case (as compared to, say, Mike's notion of having some sort of "collection of visible overloads to choose between" that scopeResolve would use.

**Comment by lydia-duncan** [comment]
I think we get away with it because even if we do find "one" function or choose one arbitrarily, function resolution will get to doing the right thing (assuming we didn't generate a failure because of it, like we did in this case).  I would definitely prefer it for us to either ignore functions entirely in scope resolve or have resolution happen in only one place, though

**Comment by lydia-duncan** [comment]
I've been looking through ResolveScope to make sure such a change will not prevent the symbol from getting scope resolve run over it.  Seems to be okay, but I'm going to write an additional test to be certain
