### ISSUE TITLE
Mason build on last modified

### ISSUE THREAD

**Issue by Spartee** [chapel-lang/chapel#9843]
Similar to a Makefile, Mason should be able to build on the last modified file instead of compiling every time. Checking the last modified time of the binary against the last modified time of chapel files within the source code subdirectory, `/src/*.chpl`, of a mason project should give us this ability.

**Comment by ben-albrecht** [comment]
It looks like `mtime` is not available in the standard library. Bonus points if we can add it to the `FileSystem` module along the way.

We can probably expose [`stat.st_mtime`](http://man7.org/linux/man-pages/man2/stat.2.html) similar to Python's [`os.getmtime`](https://docs.python.org/3/library/os.path.html#os.path.getmtime).

Here's an [example in C from SO](https://stackoverflow.com/questions/13542345/how-to-convert-st-mtime-which-get-from-stat-function-to-string-or-char).

**Comment by bradcray** [comment]
Bonus bonus points if we can call it something better than `mtime()`  :)

**Comment by ben-albrecht** [comment]
@bradcray - Have any suggestions? I'll throw some out:

```chpl
proc lastModified(filePath: string) { .. }
proc timeStamp(filePath: string) { .. }
proc modifiedTime(filePath: string) { .. }
```

Would it make sense for this to return a [`datetime`](https://chapel-lang.org/docs/master/modules/standard/DateTime.html#DateTime.datetime) object?

**Comment by bradcray** [comment]
Is there prior art we can learn from, or does everyone use mtime?  Of your suggestions, I like `lastModified` I think...

I was wondering about whether this was a chance to put more weight on datetime as well...

**Comment by russel** [comment]
@bradcray convinced me to add this comment:

Regarding doing separate compilation rather than all source at once, modified time alone has some issues. SCons uses both modified time and (MD5 I think) hash. This saves compiling files that are updated but have no substantive changes, at the cost of calculating the hash. Some people feel the extra cost of calculating hashes is an overhead to far, but those that have files that take a long time to compile (C++ is full of these) are very happy that they can make non-substantive changes to files and not have them recompiled.The balance of calculating the minimum build time remains an issue people are working on.

I believe Gradle is now looking to do better compilation product caching. Many see Gradle as a JVM language systems, but it also has C++build capability. I believe they are using dates and hashes to determine the minimal work required.

**Comment by ben-albrecht** [comment]
Thanks for your input @russel.

Do you know if SCons uses some local temp directories within the project to store the cache of hashes, or does it rely on something like `$TMPDIR`?

I don't feel strongly about this optimization making it into the first pass of this feature, but I do think it'd be worth looking into afterwards.

**Comment by Spartee** [comment]
Feature has been added in PR #10058. PR lists a TODO to put getLastModified() into the standard library.
