### ISSUE TITLE
Cannot use outer-scope variable, then shadow-redefine it

### ISSUE THREAD

**Issue by BryantLam** [chapel-lang/chapel#9985]
### Summary of Problem
The following code has several test cases in it. The case that breaks is the one that reads the outer-scoped variable first, and then shadows that variable with a scope-local definition.
`11: error: 'a' used before defined (first used here)`

I question whether this behavior should be allowed, but since it is already in the language, it should work consistently. (And even if I didn't want *this specific test case* to work, the error message would not accurately explain what was wrong.)

### Steps to Reproduce

**Source Code:**

```chapel
proc main() {
  var a = 12;
  {
    var b = a;
  }
  {
    var a = 1;
    var b = a;
  }
  {
    var b = a; // <-- error reported here.
    var a = 1;
  }
  {
    var b = a;
    {
      var a = 1;
    }
  }
}
```

### Configuration Information
`chpl version 1.18.0 pre-release (b0251ba45e)`

**Comment by lydia-duncan** [comment]
I believe this is not behaving inconsistently, but agree that the error message could be improved, probably to include the location of the "a" is that being used before defined.

Basically, the scope of a variable is defined to be the block where it is defined and any subscopes.  A symbol defined in the scope of another is always closer to that other symbol than a symbol defined in the outer scope.  We always look in the current scope first, and if we don't find a match there *then* we start looking into higher scopes (and scopes included via use statements).  This allows us to reference functions defined at any part within the scope instead of requiring that the function symbol is defined prior to the call to it.

I'm looking to find a bit of the spec that describes this, but am not finding it quickly.  I'll make another comment when I find it

**Comment by bradcray** [comment]
Hi Bryant -- Lydia's right about this, though in saying that, I acknowledge that we depart from other languages in this respect.  By design, Chapel set out to be a language in which declaration order doesn't matter (e.g., you can call a procedure before it's defined and there's no need for prototypes; module declaration order shouldn't affect semantics or require any kind of "forward"/prototype declaration of the module).  Early on in the project, we decided to be uniform about this principle:  that naming a symbol declared within a given scope would refer to that symbol regardless of whether its declaration came before or after the reference.  An even simpler version of a program that demonstrates this issue is:

```chapel
var a = 1;   // call this a1
{
  var a = a;  // call this new a 'a2'; the initializer here also refers to a2, making this illegal
}
```

If this is something you'd want to advocate for changing (as compared to producing a better error message as Lydia suggests), please file a feature request for it with a rationale for why you think it's an important feature.

**Comment by BryantLam** [comment]
Nope, I don't want to advocate for this feature. I simply didn't know whether it was intended behavior or not. Closing.

It would be nice to get that reference to where this is described in the Language Specification though.

**Comment by lydia-duncan** [comment]
> It would be nice to get that reference to where this is described in the Language Specification though.

Unfortunately I'm not finding anything that explicitly mentions it, more vague places where you can read between the lines for the interpretation.  I could have sworn there was an actual document, though - Brad, do you have any ideas?

**Comment by bradcray** [comment]
Not offhand.  Lydia, would you open up two issues relating to this?  One about improving the error message (ideally with a future) and the second about improving the spec?

**Comment by lydia-duncan** [comment]
Can do!

**Comment by BryantLam** [comment]
Related #9750

**Comment by bradcray** [comment]
I knew I'd seen that a = a case somewhere recently...

**Comment by lydia-duncan** [comment]
Test added in #10035, error message requested in #10034, spec description in #10021
